### ISSUE TITLE
Issue when compiling under Arch linux: identifier undefined

### ISSUE THREAD

**Issue by GPistre** [davisking/dlib#100]
Compiling either the examples or the python API results in an error, apparently when trying to build the cuda project:

```
[  0%] Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/dnn/dlib_generated_cuda_dlib.cu.o
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00000885_00000000-7_cuda_dlib.cpp1.ii"
```
I have the latest versions of both gcc (5.3) and cuda (7.5). Are there any other requirements?

**Comment by davisking** [comment]
CMake tries to build a cuda test project and if it doesn't work it disables
it.  Or that's what should happen.  What is the entire output from cmake
and make?

**Comment by GPistre** [comment]
The compilation stops right after this step.

```
...
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Found cuDNN: /opt/cuda/lib64/libcudnn.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gpistre/dlib/tools/python/build
Build using cmake ...
[  1%] Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/dnn/dlib_generated_cuda_dlib.cu.o
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
2 errors detected in the compilation of "/tmp/tmpxft_00001b71_00000000-7_cuda_dlib.cpp1.ii".
CMake Error at dlib_generated_cuda_dlib.cu.o.cmake:266 (message):
  Error generating file
  /home/gpistre/dlib/tools/python/build/dlib_build/CMakeFiles/dlib.dir/dnn/./dlib_generated_cuda_dlib.cu.o
dlib_build/CMakeFiles/dlib.dir/build.make:63: recipe for target 'dlib_build/CMakeFiles/dlib.dir/dnn/dlib_generated_cuda_dlib.cu.o' failed
make[2]: *** [dlib_build/CMakeFiles/dlib.dir/dnn/dlib_generated_cuda_dlib.cu.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'dlib_build/CMakeFiles/dlib.dir/all' failed
make[1]: *** [dlib_build/CMakeFiles/dlib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
error: cmake build failed!

```

**Comment by davisking** [comment]
Huh.  Can you compile the C++ example programs?

**Comment by GPistre** [comment]
I get the same error when building the cuda test project

```
[  0%] Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/dnn/dlib_generated_cuda_dlib.cu.o
/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00001dc4_00000000-7_cuda_dlib.cpp1.ii".
CMake Error at dlib_generated_cuda_dlib.cu.o.cmake:266 (message):
  Error generating file
  /home/gpistre/dlib/examples/build/dlib_build/CMakeFiles/dlib.dir/dnn/./dlib_generated_cuda_dlib.cu.o

```

**Comment by davisking** [comment]
That doesn't look like output from the cuda test build.  What did you type exactly?

**Comment by GPistre** [comment]
Sorry, running 
```
cd dlib/test
mkdir build
cd build
cmake .. 
```
works up until this point.
But this: 
`cmake --build . --config Release`
results in the previous error.

**Comment by davisking** [comment]
Ok, what about the project in dlib/dnn/test_for_cuda?  That's the project CMake tries to build to see if cuda is working on your system.  I assume building that works?

Also, you have cuda and cudnn installed.  Do they work on your system?

**Comment by GPistre** [comment]
I use theano and lasagne regularly, with GPU, so I assume  there is no problem with cuda or cudnn. 
I just tried building cuda_test_generated_cuda_test, and it seems to work fine...

**Comment by davisking** [comment]
Hmm.  But what about dlib/dnn/test_for_cuda?  You can build it with the same cmake commands as the test project.

**Comment by GPistre** [comment]
```
cd dlib/dnn/test_for_cuda
mkdir build
cd build 
cmake ..
cmake --build . --config Release
```
seems to work without a problem

**Comment by davisking** [comment]
Well, according to the [cuda documentation](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#axzz45LsWblQK) GCC 5.3 isn't supported with cuda.  I don't see Arch linux on the list either.  How did you build Theano?

**Comment by davisking** [comment]
Also, I just updated the test_for_cuda project to #include some headers to make it more realistic.  Especially since it seems like one of the headers that comes with gcc 5.3 is causing the problem.  So if you pull the latest from github does that fix your problem?

**Comment by GPistre** [comment]
Ok. Cuda still fails to build the test, but the compilation continues.
However, it fails later with this :
```
In file included from /home/gpistre/dlib/dlib/../dlib/data_io/../image_io.h:14:0,
                 from /home/gpistre/dlib/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/gpistre/dlib/dlib/../dlib/data_io.h:11,
                 from /home/gpistre/dlib/tools/python/src/other.cpp:7:
/home/gpistre/dlib/dlib/../dlib/data_io/../image_loader/load_image.h: In function ‘void dlib::load_image(image_type&, const string&)’:
/home/gpistre/dlib/dlib/../dlib/data_io/../image_loader/load_image.h:82:70: error: too few arguments to function ‘GifFileType* DGifOpenFileName(const char*, int*)’
                 GifFileType* gif = DGifOpenFileName(file_name.c_str());
                                                                      ^
In file included from /home/gpistre/dlib/dlib/../dlib/data_io/../image_loader/load_image.h:14:0,
                 from /home/gpistre/dlib/dlib/../dlib/data_io/../image_io.h:14,
                 from /home/gpistre/dlib/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/gpistre/dlib/dlib/../dlib/data_io.h:11,
                 from /home/gpistre/dlib/tools/python/src/other.cpp:7:
/usr/include/gif_lib.h:179:14: note: declared here
 GifFileType *DGifOpenFileName(const char *GifFileName, int *Error);
              ^
In file included from /home/gpistre/dlib/dlib/../dlib/data_io/../image_io.h:14:0,
                 from /home/gpistre/dlib/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/gpistre/dlib/dlib/../dlib/data_io.h:11,
                 from /home/gpistre/dlib/tools/python/src/other.cpp:7:
/home/gpistre/dlib/dlib/../dlib/data_io/../image_loader/load_image.h:144:38: error: too few arguments to function ‘int DGifCloseFile(GifFileType*, int*)’
                     DGifCloseFile(gif);
                                      ^
In file included from /home/gpistre/dlib/dlib/../dlib/data_io/../image_loader/load_image.h:14:0,
                 from /home/gpistre/dlib/dlib/../dlib/data_io/../image_io.h:14,
                 from /home/gpistre/dlib/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/gpistre/dlib/dlib/../dlib/data_io.h:11,
                 from /home/gpistre/dlib/tools/python/src/other.cpp:7:
/usr/include/gif_lib.h:183:9: note: declared here
     int DGifCloseFile(GifFileType * GifFile, int *ErrorCode);
         ^

```
Although this might be related to something else, I'll have to check later.

**Comment by davisking** [comment]
Huh, apparently there are multiple versions of libgif.  Joy :)

**Comment by davisking** [comment]
I just updated dlib to work with the new libgif API so this should all work now.  Let me know if it doesn't.

**Comment by e-fominov** [comment]
Got the same problem with CUDA 7.5 CUDNN 5 and gcc 5.3 on Ubuntu
After searching internet found solution: add -D_MWAITXINTRIN_H_INCLUDED 
Like this:
cmake .. -DCUDA_NVCC_FLAGS="-D_MWAITXINTRIN_H_INCLUDED"

If test_fo_cuda failed to build - its CMakeFiles.txt:
list(APPEND CUDA_NVCC_FLAGS "-arch=sm_30;-std=c++11;-D__STRICT_ANSI__;-D_MWAITXINTRIN_H_INCLUDED")

**Comment by davisking** [comment]
I just upgraded to ubuntu 16.04 and got this error.  However, when I added -D_MWAITXINTRIN_H_INCLUDED it then lead to this error:

/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope

Were you able to compile the rest of dlib?

As an aside, I don't think nvidia supports cuda on this version of ubuntu yet (http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#axzz48DDS8nWd), but if there is some way to make dlib's cmake files work with it I'll update them :)

**Comment by pixelou** [comment]
Some pointers on possible workarounds (comes down to disabling some features of the standard library to avoid issues, this is not optimal):
- https://m.reddit.com/r/archlinux/comments/4iczja/a_work_around_if_you_are_using_cuda_and_have/  -> gcc 6 not supported at all
- https://github.com/tensorflow/tensorflow/issues/1066 -> similar issue in tensorflow
- http://deeplearning.net/software/theano/install_ubuntu.html -> see workaround

**Comment by davisking** [comment]
Yeah.  I would recommend sticking to a version of Linux with official CUDA support.
