### ISSUE TITLE
mmod error for predicting opencv Mat

### ISSUE THREAD

**Issue by yanchao12122** [davisking/dlib#1001]
my code is follows:

net_type net;
deserialize("mmod_human_face_detector.dat") >> net;
cv::Mat frame = cv::imread("face.jpg");
dlib::cv_image<<dlib::bgr_pixel>> cimg(frame);
auto dets = net(cimg);       //【【【 !!! error, can't work

**Comment by davisking** [comment]
Right, that doesn't work because it's not how you are supposed to use it.  The documentation discusses how this all works in great detail and has examples.
