### ISSUE TITLE
Installing in Ubuntu system with support of GPU

### ISSUE THREAD

**Issue by ghimiredhikura** [davisking/dlib#1007]
Hello Dr. Davis King, 

Thank you for building this wonderful library 'dlib'. 
I am having trouble on how to install this library in ubuntu system with support of GUP. 
As I installed according to the instruction in web and tried example such as "dnn_mmod_face_detection_ex.cpp", the detection time is extremely slow. Will you please provide detail setup command so that we don't need to link library path on example compilation time as they can be anywhere (outside of example folder). And of course with support of GUP or instructions like AVX. 

Thanks in advance.

**Comment by davisking** [comment]
Fill out the issue template.
