### ISSUE TITLE
DLIB_ISO_CPP_ONLY is broken, as dnn includes some multithreading stuff.

### ISSUE THREAD

**Issue by mcourteaux** [davisking/dlib#1008]
It's me again... (sorry to bother you this much).

It seems like the `DLIB_ISO_CPP_ONLY` toggle is essentially broken, as the `dnn` (I assume deep neural network) module tries to compile some multithreading stuff:

    dlib/threads/threads_kernel_2.h

So, enabling the ISO c++ only option, causes the build to break. I'm still trying to use the face detector only, and was looking at it again to reduce some compile time.

* **Version**: git latest today
* **Where did you get dlib**: git
* **Platform**: linux amd64
* **Compiler**: gcc5.4

**Comment by davisking** [comment]
I'm pretty tempted to delete the DLIB_ISO_CPP_ONLY option from dlib all
together.  Why do you think you need to use it?

**Comment by mcourteaux** [comment]
Ah, because I'm a bit OCD when it comes to compiling stuff that I don't need. 😛 
I disabled all other flags, but left the build iso c++ only flag off for now.

**Comment by davisking** [comment]
Ok, well, I just fixed it. :)  But I think it's probably a misfeature.  I would have taken it out a while ago but I don't like breaking backwards compatibility.
