### ISSUE TITLE
Undefined symbols for architecture x86_64 building with SCons in OSX

### ISSUE THREAD

**Issue by jshin49** [davisking/dlib#101]
Hi there,

I've been trying to link dlib_18_14 to a shared library in OSX El Captain with SCons, but it's keep failing to build with the following error log:

`Timothys-MBP:sdk tllewellynn$ sudo scons TARGET_OS=darwin TARGET_ARCH=x86_64 PARALLELIZATION=true GOLDENEYE=false RELEASE=true SDK_VERSION=1.0.0
Password:
scons: Reading SConscript files ...
Release mode? : true
Goldeneye?: False
Use paralellization?: True
Checking for C++11 flag for g++... (cached) -std=c++11
Checking for broken GCC C headers when C++11 is enabled... (cached) no
CONFIG: pthread already installed
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: out/darwin/x86_64/release/1.0.0
g++ -o out/darwin/x86_64/release/1.0.0/bin/libAPI3dfi_api_v1.dylib -ldl -lpthread -mmacosx-version-min=10.11 -m64 -dynamiclib out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Api.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_App_Manager.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_App_Params.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_App_Retry.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Device_Heartbeat.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Device_Init.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Frame_Stats.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Manager.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Session_Assign.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Session_End.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/NV3DFI_Event_Session_Start.os out/darwin/x86_64/release/1.0.0/src/api/3dfi_api_v1/src/SHA1Hash.os -L/usr/local/lib -L/opt/local/lib -Ldeps/darwin/lib/x86_64 -Lout/darwin/x86_64/release/1.0.0 -L. -Lout/darwin/x86_64/release/1.0.0/bin -Lbin -Lout/darwin/x86_64/release/1.0.0/lib -Llib -L/Users/tllewellynn/Desktop/dev/build_scons/runtime/darwin/xcode/x86_64/pthread/lib -L/Users/tllewellynn/Desktop/dev/build_scons/runtime/darwin/xcode/x86_64/intraface/lib -lSDK3dfi_detect -lSDK3dfi_algo -lSDK3dfi_au -lSDK3dfi_align -lSDK3dfi_proc -lSDK3dfi_cluster -lSDK3dfi_attr -lSDK3dfi_type -lOpencvCore -lOpencvHighgui -lOpencvImgproc -lOpencvObjdetect -lOpencvFlann -lOpencvFeature2d -lOpencvVideo -lOpencvCalib3d -lOpencvMl -lFreeimage -lFreeimageOpenEXR -lFreeimageLibTIFF -lFreeimageLibPNG -lFreeimageLibOpenJPEG -lFreeimageLibJPEG -lFreeimageLibMNG -lFreeimageZLib -lFrameworkNvaam_base -lFrameworkNvaam_filter -lFrameworkNvaam -lFrameworkProtobuf -lFrameworkLibbff -lFrameworkNvclassifier -lFrameworkNvexpression -lFrameworkTrimesh2 -lFrameworkPolyfit -lFrameworkGClasses -lFrameworkFlandmark -lFrameworkAlglib -lNetMsgpack -lNetJsoncpp -lNetTinyxml2 -lNetTinyxmlparam -lCnnEblearnTools -lCnnEblearnIdx -lCnnEblearn -lThirdPartyDlib_18_14 -lSystemTinycthread -lSystemTinythread -lSystemGlobal -lSystemDebug -lpthread -lTbb -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/ -framework Cocoa -framework QuartzCore -framework AVFoundation -framework CoreVideo -framework CoreMedia
ld: warning: directory not found for option '-Ldeps/darwin/lib/x86_64'
ld: warning: directory not found for option '-Lbin'
ld: warning: directory not found for option '-Llib'
ld: warning: directory not found for option '-L/Users/tllewellynn/Desktop/dev/build_scons/runtime/darwin/xcode/x86_64/pthread/lib'
ld: warning: directory not found for option '-L/Users/tllewellynn/Desktop/dev/build_scons/runtime/darwin/xcode/x86_64/intraface/lib'
Undefined symbols for architecture x86_64:
  "_XAllocColor", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XAllocSizeHints", referenced from:
      dlib::base_window::set_size(int, int) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XChangeProperty", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XCheckIfEvent", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XClearArea", referenced from:
      dlib::base_window::invalidate_rectangle(dlib::rectangle const&) in libThirdPartyDlib_18_14.a(source.o)
  "_XCloseDisplay", referenced from:
      nativefont::font_renderer::font_renderer::vals_internal::~vals_internal() in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::~event_handler_thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XCloseIM", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::~event_handler_thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XConvertSelection", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
  "_XCreateFontSet", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XCreateGC", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XCreateIC", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
  "_XCreatePixmap", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XCreateWindow", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XDefaultDepth", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XDestroyIC", referenced from:
      dlib::base_window::~base_window() in libThirdPartyDlib_18_14.a(source.o)
  "_XDestroyWindow", referenced from:
      dlib::base_window::close_window() in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XExtentsOfFontSet", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XFillRectangle", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XFilterEvent", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XFlush", referenced from:
      dlib::base_window::invalidate_rectangle(dlib::rectangle const&) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::set_size(int, int) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::set_title(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::set_pos(long, long) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::show() in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::hide() in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
      ...
  "_XFree", referenced from:
      dlib::base_window::set_im_pos(long, long) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::set_size(int, int) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::set_title(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
  "_XFreeFontSet", referenced from:
      dlib::base_window::~base_window() in libThirdPartyDlib_18_14.a(source.o)
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
      nativefont::font_renderer::font_renderer::vals_internal::~vals_internal() in libThirdPartyDlib_18_14.a(source.o)
  "_XFreeGC", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
      nativefont::font_renderer::font_renderer::vals_internal::~vals_internal() in libThirdPartyDlib_18_14.a(source.o)
  "_XFreeModifiermap", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::init_keyboard_mod_masks() in libThirdPartyDlib_18_14.a(source.o)
  "_XFreePixmap", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
      nativefont::font_renderer::font_renderer::vals_internal::~vals_internal() in libThirdPartyDlib_18_14.a(source.o)
  "_XFreeStringList", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XGetICValues", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
  "_XGetImage", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XGetModifierMapping", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::init_keyboard_mod_masks() in libThirdPartyDlib_18_14.a(source.o)
  "_XGetSelectionOwner", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
  "_XGetWindowProperty", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
  "_XInitImage", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XInitThreads", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XInternAtom", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XLookupString", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XMapRaised", referenced from:
      dlib::base_window::show() in libThirdPartyDlib_18_14.a(source.o)
  "_XMoveWindow", referenced from:
      dlib::base_window::set_pos(long, long) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XNextEvent", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XOpenDisplay", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XPeekIfEvent", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
  "_XPending", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XPutBackEvent", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::~event_handler_thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XPutImage", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XQueryColor", referenced from:
      nativefont::font_renderer::font_renderer::vals_internal::color2rgb(unsigned long, _XDisplay*, unsigned long&) in libThirdPartyDlib_18_14.a(source.o)
  "_XResizeWindow", referenced from:
      dlib::base_window::set_size(int, int) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XScreenNumberOfScreen", referenced from:
      dlib::base_window::get_display_size(unsigned long&, unsigned long&) const in libThirdPartyDlib_18_14.a(source.o)
  "_XSelectInput", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
  "_XSendEvent", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::~event_handler_thread() in libThirdPartyDlib_18_14.a(source.o)
  "_XSetBackground", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XSetForeground", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XSetICValues", referenced from:
      dlib::base_window::set_im_pos(long, long) in libThirdPartyDlib_18_14.a(source.o)
  "_XSetNormalHints", referenced from:
      dlib::base_window::set_size(int, int) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XSetSelectionOwner", referenced from:
      dlib::put_on_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&) in libThirdPartyDlib_18_14.a(source.o)
  "_XSetWMName", referenced from:
      dlib::base_window::set_title(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&) in libThirdPartyDlib_18_14.a(source.o)
  "_XSetWMProtocols", referenced from:
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
  "_XTranslateCoordinates", referenced from:
      dlib::base_window::get_pos(long&, long&) in libThirdPartyDlib_18_14.a(source.o)
  "_XUnmapWindow", referenced from:
      dlib::base_window::hide() in libThirdPartyDlib_18_14.a(source.o)
  "_XVaCreateNestedList", referenced from:
      dlib::base_window::set_im_pos(long, long) in libThirdPartyDlib_18_14.a(source.o)
      dlib::base_window::base_window(bool, bool) in libThirdPartyDlib_18_14.a(source.o)
  "_XkbKeycodeToKeysym", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::init_keyboard_mod_masks() in libThirdPartyDlib_18_14.a(source.o)
  "_XwcDrawString", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XwcFreeStringList", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
  "_XwcLookupString", referenced from:
      dlib::gui_core_kernel_2_globals::event_handler_thread::event_handler() in libThirdPartyDlib_18_14.a(source.o)
  "_XwcTextExtents", referenced from:
      void nativefont::font_renderer::font_renderer::vals_internal::create<unsigned int>(unsigned int*, int, bool, bool, bool, nativefont::font_renderer::font_renderer::rgb_type, nativefont::font_renderer::font_renderer::rgb_type) in libThirdPartyDlib_18_14.a(source.o)
  "_XwcTextListToTextProperty", referenced from:
      dlib::base_window::set_title(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&) in libThirdPartyDlib_18_14.a(source.o)
  "_XwcTextPropertyToTextList", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in libThirdPartyDlib_18_14.a(source.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [out/darwin/x86_64/release/1.0.0/bin/libAPI3dfi_api_v1.dylib] Error 1
scons: building terminated because of errors.`

The follwoing is the SCons script that handles the building of a dlib static library (which builds fine), and this static library also binds nicely with a final static library output of my application; is there any identifiable problems in my SCons script (posted below):

`Import('env')

# Add third party libraries
lib_env = env.Clone()
SConscript( [env.get('SRC_DIR') + '/src/system_libs.scons', env.get('SRC_DIR') + '/src/thirdparty_libs.scons'], exports = 'lib_env')

module_lib_env = lib_env.Clone()
target_os = env.get('TARGET_OS')

######################################################################
# Build flags
######################################################################
module_lib_env.AppendUnique(CPPPATH = ['inc', 'src'])

if target_os not in ['windows', 'winrt']:
	module_lib_env.AppendUnique(CXXFLAGS = ['-Wall'])
	if target_os != 'android':
		module_lib_env.AppendUnique(CXXFLAGS = ['-pthread'])

if target_os == 'android':
	module_lib_env.AppendUnique(CXXFLAGS = ['-frtti', '-fexceptions'])

######################################################################
# Source files and Targets
######################################################################
module_lib_src = env.Glob('src/*.cpp')

######################################################################
# Targets
######################################################################
module_lib_env.InstallTarget( 'libThirdPartyDlib_18_14',module_lib_src)
`

Thank you.

**Comment by jshin49** [comment]
Sorry for the bizarre styling.
Since SCons is basically Python, the comments produce weird headlines for Github markdown.

**Comment by davisking** [comment]
You need to link to X11

**Comment by jshin49** [comment]
Works like magic!

Thanks so much!
