### ISSUE TITLE
cudaGetErrorString	error when compiling dnn_introduction_ex.cpp

### ISSUE THREAD

**Issue by arnaghizadeh** [davisking/dlib#1012]
Hi, I could successfully install dlib version 19.7  for VS 2015 Update 3 on windows 10 64bit.  I created a separate project (64 bit on release mode) and configured the project with "Include Directories" and "Additional dependency" on Linker/input. I can successfully compile and run 3d_point_cloud_ex.cpp example. But my real need for dlib is neural net, so I tried to compile  "dnn_introduction_ex.cpp" which is also used as introduction to  deepnet with dlib. But I cannot compile this particular example and get a LNK2001 error for cudaGetErrorString . It seems that my project is not linked with CUDA properly. Any suggestion what I should do?

**Comment by arnaghizadeh** [comment]
Thought that maybe creating a project as cuda (e.g. NVIDIA/CUDA 8.0/CUDA 8.0 Runtime) would solve the problem. But it does not, again I can compile 3d_point_cloud_ex.cpp but dnn_introduction_ex.cpp gives me a lot of linking error such as unresolved external symbol cudnnCreate

**Comment by davisking** [comment]
Use cmake, it will configure visual studio correctly for you.  http://dlib.net/compile.html tells you what to type.
