### ISSUE TITLE
dlib python3 build fails on fedora27

### ISSUE THREAD

**Issue by Stef4fun** [davisking/dlib#1015]
The dlib python3 build fails on fedora27, using also the cuda 9.0 packages provided from here https://negativo17.org/nvidia-driver/ also with **cuda-gcc cuda-g++ and cuda-gfortran**

## Expected Behavior
Linking should succeed

## Current Behavior
When calling 
python3 setup.py build --yes USE_AVX_INSTRUCTIONS
the following error shows up:
[100%] Linking CXX shared library dlib.so
/usr/bin/ld: /usr/lib64/gcc/x86_64-redhat-linux/6.4.0/libstdc++.a(eh_globals.o): relocation R_X86_64_TPOFF32 against `_ZZN12_GLOBAL__N_110get_globalEvE6global' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib64/gcc/x86_64-redhat-linux/6.4.0/libgomp.a(team.o): relocation R_X86_64_TPOFF32 against hidden symbol `gomp_tls_data' can not be used when making a shared object
/usr/bin/ld: /usr/lib64/gcc/x86_64-redhat-linux/6.4.0/libgomp.a(oacc-init.o): relocation R_X86_64_TPOFF32 against hidden symbol `goacc_tls_data' can not be used when making a shared object
/usr/bin/ld: /usr/lib64/gcc/x86_64-redhat-linux/6.4.0/libstdc++.a(cow-shim_facets.o): relocation R_X86_64_PC32 against symbol `_ZTVSt7collateIcE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/dlib_.dir/build.make:632: dlib.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/dlib_.dir/all] Error 2
gmake: *** [Makefile:130: all] Error 2
error: cmake build failed!

Interesting is that:
cmake3 ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_BUILD_TYPE=Release -DUSE_AVX_INSTRUCTIONS=1 -DCMAKE_POSITION_INDEPENDENT_CODE=ON
succeeds properly

**python3 was build was build with --enabled-shared**
python3
import sysconfig
sysconfig.get_config_vars('Py_ENABLE_SHARED')
[1] 
**And -fPIC shows up in flags.cmake and link.txt** in /dlib/tools/python/build/CMakeFiles/dlib_.dir
[flags.make.txt](https://github.com/davisking/dlib/files/1563375/flags.make.txt)
[link.txt](https://github.com/davisking/dlib/files/1563377/link.txt)

## Steps to Reproduce
Install Fedora 27 workstation dvd, (I'm using a ZBOX 1060K)
do the following steps
#SET IN .bashrc
export CCFLAGS="-march=native"
export CXXFLAGS="-march=native"
export CC=/usr/bin/cuda-gcc
export CXX=/usr/bin/cuda-g++
. ~/.bashrc

yum -y remove \*nvidia\*
dnf config-manager --add-repo=https://negativo17.org/repos/fedora-nvidia.repo
dnf install nvidia-driver nvidia-settings kernel-devel
yum install cuda nvidia-driver-cuda
yum install cuda-devel
yum install cuda-cudnn*
yum install cuda-extra-libs
yum install cuda-gcc
yum install cuda-gcc-c++

reboot

yum install cmake3 libX11-devel libpng-devel libjpeg-turbo-devel openblas-devel sqlite-devel fftw-devel boost-devel python2-devel python3-devel boost-python-devel boost-python3-devel

git clone https://github.com/davisking/dlib.git
cd dlib/
rem git checkout 9f6ad63b06f4a375f91b592e53446e729da23d99

mkdir cmake; mkdir build; cd cmake;
cmake3 ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_BUILD_TYPE=Release -DUSE_AVX_INSTRUCTIONS=1 -DCMAKE_POSITION_INDEPENDENT_CODE=ON
 
python3 setup.py build --cmake cmake3 --yes USE_AVX_INSTRUCTIONS

* **Version**: Latest from github and/or commit 9f6ad63b06f4a375f91b592e53446e729da23d99
* **Where did you get dlib**: this github repo
* **Platform**: 
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 27 (Twenty Seven)
Release:        27
Codename:       TwentySeven

* **Compiler**: cuda-gcc 6.4.0 cuda-g++ 6.4.0 from the above link

**Comment by davisking** [comment]
Try building without cuda.   Also, I don't think this has anything to do with dlib.  The problem is that cmake is selecting the static libstdc++ to link against (which isn't compiled with fPIC).  It normally would select the shared version of libstdc++ which would have worked fine.  The question is, why is it linking to the static version of libstdc++?  If you can find a way to get cmake to link against the shared version then please submit it as a PR so this issue can be avoided in the future :)

Also, building the dlib folder doesn't do a lot.  Nearly all of dlib is in templates in header files and so there is nothing to do when "building" most of dlib.  That's probably why trying to build it doesn't give the error.

**Comment by Stef4fun** [comment]
Solved:
the cuda-gcc 6.4.0.1 package was not complete, it only contained the libstdc++.a.
Now I could update to cuda-gcc 6.4.0.4 and the libstdc++.so is now in
/usr/lib64/gcc/x86_64-redhat-linux/6.4.0
Thanks a lot.
