### ISSUE TITLE
dnn_trainer fails to overwrite synchronization file/Windows

### ISSUE THREAD

**Issue by e-fominov** [davisking/dlib#102]
Windows 7/MingW x64 GCC 5.3
With dnn_mnist_ex.cpp sample, I found that restarting training process does not work correctly - only first saving of state file can be loaded. After first sate file is saved, training process fails to overwrite it with renaming temporary file

While debugging, I found at file https://github.com/davisking/dlib/blob/master/dlib/dnn/trainer.h, line s 705-707:
```c++
    // Now that we know the state is safely saved to disk, delete the old sync
    // file and move the .tmp file to it.
    std::rename(tempfile.c_str(), sync_filename.c_str());
```

The result code of std::rename is not checked. And on Windows it returns -1:
```c++
     int res = std::rename(tempfile.c_str(), sync_filename.c_str());
     if (res)
           perror("Error renaming file");
```

The output is: *Error renaming file: File exists*

This is Windows-specific issue, according to http://www.cplusplus.com/reference/cstdio/rename
>If newname names an existing file, the function may either fail or override the existing file, depending on the specific system and library implementation.

If I remove state file manually wile training process is running - it is saved, but only once until I remove it again

**Comment by davisking** [comment]
Got to love windows :)

Putting a std::remove() call right in front of the rename fixes it I hope?

**Comment by e-fominov** [comment]
Yes, I tested it:
```c++
                // Now that we know the state is safely saved to disk, delete the old sync
                // file and move the .tmp file to it.
                std::remove(sync_filename.c_str());
                std::rename(tempfile.c_str(), sync_filename.c_str());
```

works good on Windows

**Comment by davisking** [comment]
Cool, thanks for finding this bug.  I just pushed the fix.
