### ISSUE TITLE
DNN MMOD detector training with non-square bbox

### ISSUE THREAD

**Issue by mahehu** [davisking/dlib#1021]
I'm training a DNN detector for pedestrian detection. My detection window and cropper chip size are not square (instead, something like 80x32).

With v19.6 everything went fine, and I reached precision & recall in the order of 95%. However, in v19.7 the file `dlib/image_transforms/random_cropper.h` has the following line 277:

`DLIB_CASSERT(crop_rect.width() == crop_rect.height());`

Thus, only **square** chip_sizes are allowed in random_cropper, which seems to require square detection windows, as well. 

I can delete this line, but leaves me wondering if I should not do this.

**Steps to test now-square windows:**

Edit `examples/random_cropper_ex.cpp` at line 41:
`cropper.set_chip_dims(400,400);`
into for example:
`cropper.set_chip_dims(400,100);`

This will cause random_cropper to crash.

Thanks in advance for any insight on this!

**Comment by davisking** [comment]
Oops, that shouldn't have been committed at all.  I just pushed the fix.  Thanks for reporting this.
