### ISSUE TITLE
Time lag on facial recognition : Not using GPU as expected

### ISSUE THREAD

**Issue by xhuvom** [davisking/dlib#1022]
I have installed dlib with AVX_INSTRUCTIONS and CUDA+cuDNN. But running a real-time facial detection and recognition (5 points) from a video file lags about 1~2 sec per frame with OPENCV VideoCapture function. The code should run butter smooth (theoretically) on my GTX 1080 GPU but I am confused whether Dlib using the GPU at all. Checking GPU memory while runtime shows only 9MB consumption per instance while its occupying 99% of 1 CPU core. Running more instances of the same program on different program shows linear increment on GPU (9MB per instance) memory and smartly adjusting all CPU cores (Core i7) to the maximum. I want to reduce CPU burden and move the compute intensive part to my powerful GPU so that the program runs smoothly with multiple instances. Can anyone suggests if its normal or anything I am missing to use GPU?

**Comment by davisking** [comment]
Who knows.  You didn't even say what you are running.  Fill out the issue template.
