### ISSUE TITLE
CMAKE_CXX_COMPILER Fails Windows 32 bit

### ISSUE THREAD

**Issue by k4m35h** [davisking/dlib#1025]
Sir, i am in need of dlib for using **face recognistion** python library ...
It requires dlib version 19.7 and above ... I am tried searching for **.whl** for python 2.7 win32 ... Also windows build fails .. Could you please provide the prebuilt wheel ??

**Comment by davisking** [comment]
There is a prebuilt wheel for the 64bit version of python 3.6 on windows.  If you want to use an older version of python it's up to you to build it.  Which you can do by installing visual studio and following cmake's instructions that print when you build it.

**Comment by k4m35h** [comment]
I tried it sir , but i am unable to build and solve errors ... It will be very helpful if you provide it
