### ISSUE TITLE
Python example face_landmark_detection.py does not run

### ISSUE THREAD

**Issue by noammor** [davisking/dlib#103]
Tested on Ubuntu 15.10 with dlib 18.18, and also 18.17 (via pip install) and 18.16, on Python 2.7 and Python 3.4. In all cases I'm getting a Boost::Python error.

```
~/code/dlib-18.18/python_examples$ python face_landmark_detection.py shape_predictor_68_face_landmarks.dat ../examples/faces
Traceback (most recent call last):
  File "face_landmark_detection.py", line 66, in <module>
    predictor = dlib.shape_predictor(predictor_path)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)
```

**Comment by davisking** [comment]
I just tried it on Ubuntu 14.04 and it worked fine.  Are you sure you have
boost-python installed correctly and that it is installed for your version
of python (e.g. you don't have multiple python versions installed and it's
linked the the wrong one)?

**Comment by noammor** [comment]
I have boost-python installed from the Ubuntu repositories. Could it be related to the boost-python version? I have version 1.58.0, while I see that Ubuntu 14.04 has version 1.54.0.

**Comment by noammor** [comment]
I deliberately don't have dlib installed on my system site-packages. Other tests run correctly:

(root)noam@noam-ubuntu:~/code/dlib-18.18/python_examples$ python face_detector.py ../examples/faces/2008_002079.jpg
Processing file: ../examples/faces/2008_002079.jpg
Number of faces detected: 6
Detection 0: Left: 59 Top: 127 Right: 103 Bottom: 170
Detection 1: Left: 37 Top: 187 Right: 89 Bottom: 239
Detection 2: Left: 434 Top: 170 Right: 486 Bottom: 222
Detection 3: Left: 405 Top: 166 Right: 441 Bottom: 202
Detection 4: Left: 121 Top: 130 Right: 157 Bottom: 166
Detection 5: Left: 345 Top: 138 Right: 381 Bottom: 174
Hit enter to continue
Detection [(59, 127) (103, 170)], score: 2.3232625518938925, face_type:2.0
Detection [(37, 187) (89, 239)], score: 2.173191884627047, face_type:2.0
Detection [(434, 170) (486, 222)], score: 1.4440646325416986, face_type:1.0
Detection [(405, 166) (441, 202)], score: 1.0526294862099115, face_type:1.0
Detection [(121, 130) (157, 166)], score: 0.891693452467623, face_type:2.0
Detection [(345, 138) (381, 174)], score: 0.7759302296174879, face_type:0.0
(root)noam@noam-ubuntu:~/code/dlib-18.18/python_examples$ python face_landmark_detection.py shape_predictor_68_face_landmarks.dat ../examples/faces
Traceback (most recent call last):
  File "face_landmark_detection.py", line 66, in <module>
    predictor = dlib.shape_predictor(predictor_path)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)
(root)noam@noam-ubuntu:~/code/dlib-18.18/python_examples$

**Comment by davisking** [comment]
I just tried this example on Ubuntu 15.10, using python 2.7.10 and boost
python 1.58.0 and it works without issue.  boost pyhton was installed with
apt-get.

**Comment by noammor** [comment]
Maybe my process is wrong? From what I understand from the instructions, all you need is `python setup.py install`. Is that correct?

**Comment by davisking** [comment]
Yes, that's what I did.   You need to have the dependencies installed
correctly though.  It's common to have problems if you have multiple
versions of python installed since you have to be consistent about linking
things together.  Boost python is usually the culprit, where someone will
have boost-python installed for the wrong version of python, or at least
not for the version they are trying to use in that moment.

**Comment by noammor** [comment]
I think I've found the problem - it's a compiler issue. I compiled dlib with GCC 5.2 instead of 4.9 and now the example works.

**Comment by davisking** [comment]
Cool
