### ISSUE TITLE
Training object detector on 1000 images with upsample 3 is killed.

### ISSUE THREAD

**Issue by buliginleo** [davisking/dlib#1030]
## Expected Behavior
Hello. I want to train hog object detector on own dataset. 
http://dlib.net/train_object_detector.cpp.html 

Objects have one class. I have dataset with 12 000 images. First, I train object detector on 100 images. Then I try to train object detector on 1000 images with upsample 3 and I get error:

## Current Behavior
> Loading image dataset from metadata file final_dataset/dlib_dataset/training1000.xml
> Number of images loaded: 1001
> Killed

## Steps to Reproduce
-Compile dlib
-Compile script
`g++ train_object_detector.cpp -std=c++11 -O3 -I.. ../dlib/all/source.cpp -lpthread -lX11 -ljpeg -lpng -DDLIB_JPEG_SUPPORT -DDLIB_PNG_SUPPORT`
-Run script
`./a.out -tv final_dataset/dlib_dataset/training1000.xml -u3`

* **Version**: 19.8.99
* **Where did you get dlib**: git clone https://github.com/davisking/dlib
* **Platform**: Ubuntu 16.04 xenial 64 minimal
* **Compiler**: g++ 4.8.5 from anaconda

Ubuntu logs:

> Dec 25 15:52:24 Ubuntu-1604-xenial-64-minimal kernel: [1818692.409025] Out of memory: Kill process 2059 (a.out) score 961 or sacrifice child
> Dec 25 15:52:24 Ubuntu-1604-xenial-64-minimal kernel: [1818692.409162] Killed process 2059 (a.out) total-vm:99272240kB, anon-rss:64928316kB, file-rss:0kB, shmem-rss:0kB
> Dec 25 15:52:25 Ubuntu-1604-xenial-64-minimal kernel: [1818693.695334] oom_reaper: reaped process 2059 (a.out), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

What I can do to fix it? Dataset does not fit in memory?

**Comment by davisking** [comment]
You are running out of RAM.  Use less data or buy more RAM.  Also, upsampling 3 times is excessive.  **That makes the images 64 times larger**.  Don't do that.

**Comment by buliginleo** [comment]
@davisking I use upsample 3 because some images have small area of bounding box. Can I ignore non correct images automatically?

**Comment by davisking** [comment]
Then only upsample the small ones.
