### ISSUE TITLE
Visual Studio 2017 tagged as incomplete c++11

### ISSUE THREAD

**Issue by giordi91** [davisking/dlib#1031]
## Expected Behavior
I expect to be able to compile dlib with the latest visual studio 2017

## Current Behavior
Get a warning saying that is not c++11 complete:
`-- Your version of Visual Studio has incomplete C++11 support and is unable to compile the
-- DNN examples. So we are disabling the deep learning tools.  If you want to use the DNN
-- tools in dlib then update your copy of Visual Studio.
`
I do not have multiple installations of visual studio 2017 
## Steps to Reproduce
just running cmake

* **Version**: latest, from master
* **Where did you get dlib**: github
* **Platform**: win10 64 bit
* **Compiler**: 
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0

**Comment by davisking** [comment]
That's not the latest version of visual studio.  There is a new one and it has better C++11 support.

**Comment by giordi91** [comment]
hasn't visual studio being c++11 complete since vs 2015? I did a fresh install of the latest 4 weeks ago.  I have visual studio 15.45, I checked the lastest 15.5 version and did not see anything related to c++11 in the release notes. Can you please tell me what is required such that a month old visual studio won't cut it?
Please advise

M.

**Comment by davisking** [comment]
No, visual studio has never had complete C++11 support.  It's far and away the worst compiler in terms of standards conformance.  However, the visual studio dev team is actively working on it and it gets better all the time.  What is required is a compiler with good enough C++11 support.  Get the newest visual studio.  It finally has good enough C++11 support to compile this stuff as of like 2 weeks ago.

**Comment by giordi91** [comment]
Thank you so much for your reply, and thank you for correcting my understanding, I always referred to this:
https://msdn.microsoft.com/en-us/library/hh567368.aspx?f=255&MSPPError=-2147217396
And most the boxes for 2015 were ticked so I expected 2017 to be by far done. I will update and try.

Cheers and happy holidays

**Comment by davisking** [comment]
No problem :)
