### ISSUE TITLE
 Chineese Whisper Strange Behavior with Intel MKL multiply core

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1037]
I modified the dnn_face_recognition_ex to take camera feed and feed the captured faces to the faces vector until window closed. than It is perfectly clustering the faces.

I Installed Intel MKL to my VM Ubuntu 17.04 . Same code same version of the dlib behaiving very strangely. I gave the 8 cores to the vm . its using all cores.

Clustering looks not working. It makes cluster for each faces. ! Same faces  same code. 

When I dropped the cpu 1 core for VM its working again as it should be ?

Any idea ? I am confused..

Best

**Comment by davisking** [comment]
That shouldn't happen.  You should run the dlib unit test suite on that VM
with and without the MKL.  It will run tests to see if the MLK is working
correctly.
