### ISSUE TITLE
Unable to open file: C:\dlib-18.18\work\train_1\100032540_1.jpg

### ISSUE THREAD

**Issue by ehsaneshaghi** [davisking/dlib#1039]
I run the train_shape_predictor.py from python_example for HELEN dataset. I give the path to the 'training_with_face_landmarks.xml'  which is in the same directory as the images are.
 
I expect to the procedure of training starts.
I get the following error:
RuntimeError: Unable to open file: C:\dlib-18.18\work\train_1\100032540_1.jpg 

the error is raised on this line:
training_xml_path = os.path.join(faces_folder, 'training_with_face_landmarks.xml')

dlib version: '19.8.1'
OS: Ubuntu 16.04 64 bit
Python 3.5.2 |Anaconda 4.2.0 (64-bit)|

**Comment by ehsaneshaghi** [comment]
Mr.King 
why did you close my issue leaving no answer for it? 
it seems that some parameters are hard coded in the library!!! Please help me figure out what the problem is.

**Comment by davisking** [comment]
Read the issue template and follow its instructions.
