### ISSUE TITLE
include error

### ISSUE THREAD

**Issue by ShuangLiu1992** [davisking/dlib#104]
when including both bridge.h and image_processing.h visual studio reports error:

e:\libs\dlib\dlib\bridge/bridge.h(404): error C3861: 'deserialize': identifier not found (E:\Dropbox\perspective\data_host\main.cpp)
2>          e:\libs\dlib\dlib\bridge/bridge.h(371) : while compiling class template member function 'void dlib::impl::impl_bridge<T,R>::receive_thread(void)'
2>          with
2>          [
2>              T=dlib::pipe<int>
2>  ,            R=dlib::pipe<int>
2>          ]
2>          e:\libs\dlib\dlib\bridge/bridge.h(203) : see reference to function template instantiation 'void dlib::impl::impl_bridge<T,R>::receive_thread(void)' being compiled
2>          with
2>          [
2>              T=dlib::pipe<int>
2>  ,            R=dlib::pipe<int>
2>          ]
2>          e:\libs\dlib\dlib\bridge/bridge.h(604) : see reference to class template instantiation 'dlib::impl::impl_bridge<T,R>' being compiled
2>          with
2>          [
2>              T=dlib::pipe<int>
2>  ,            R=dlib::pipe<int>
2>          ]
2>          e:\libs\dlib\dlib\bridge/bridge.h(577) : see reference to function template instantiation 'void dlib::bridge::reconfigure<dlib::pipe<int>,dlib::pipe<int>>(dlib::listen_on_port,dlib::bridge_receive_decoration<dlib::pipe<int>>,dlib::bridge_transmit_decoration<dlib::pipe<int>>)' being compiled
2>          E:\Dropbox\perspective\data_host\main.cpp(8) : see reference to function template instantiation 'dlib::bridge::bridge<dlib::listen_on_port,dlib::bridge_receive_decoration<dlib::pipe<int>>,dlib::bridge_transmit_decoration<dlib::pipe<int>>>(T,U,V)' being compiled
2>          with
2>          [
2>              T=dlib::listen_on_port
2>  ,            U=dlib::bridge_receive_decoration<dlib::pipe<int>>
2>  ,            V=dlib::bridge_transmit_decoration<dlib::pipe<int>>
2>          ]

sample code:

```
#include <dlib/image_processing.h>
#include <dlib/bridge.h>
#include <dlib/type_safe_union.h>

int main(int argc, char **argv)
{
	dlib::pipe<int> echo(1);
	dlib::bridge echo_bridge(dlib::listen_on_port(ECHO_PORT), dlib::receive(echo), dlib::transmit(echo));


	//typedef dlib::type_safe_union<int, dlib::shape_predictor> shape_type;
	//
	//dlib::pipe<bool> signal(1);
	//dlib::pipe<bool> output(1);
	//dlib::bridge shape_bridge(dlib::listen_on_port(ECHO_PORT), dlib::receive(signal), dlib::transmit(output));

	getchar();

	return 0;
}
```

**Comment by davisking** [comment]
That code is full of errors, probably because of HTML processing.  Post something that isn't mangled :)

**Comment by ShuangLiu1992** [comment]
I have updated the code

**Comment by davisking** [comment]
Cool, thanks for finding this bug.  I just pushed the fix to github.

**Comment by ShuangLiu1992** [comment]
Great!
Also, this seems to work but
```
#include <dlib/bsp.h>
#include <dlib/image_processing/shape_predictor.h>
```

this doesn't
```
#include <dlib/bsp.h>
#include <dlib/image_processing/shape_predictor.h>
```

**Comment by davisking** [comment]
Cool.  That should be fixed now too.
