### ISSUE TITLE
QT Creator & Dlib

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1042]
Hi,

I spend 4 hours to figure out to integrate  dlib to my Qt Create project which I already successfully added Opencv.

I compiled as usual and give the below parameters tofaceRec.pro in qt project:

`#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = faceRec
TEMPLATE = app

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += \
        main.cpp \
        mainwindow.cpp \
    ../Downloads/dlib-19.8/dlib/all/source.cpp

HEADERS += \
        mainwindow.h

FORMS += \
        mainwindow.ui

#INCLUDEPATH += -L/Users/alpullu/Downloads/dlib-19.8/dlib
#LIBS += -L/Users/alpullu/Downloads/dlib-19.8/build/dlib
INCLUDEPATH += -L/Users/alpullu/Downloads/DLIB-lib/include
LIBS += -L/Users/alpullu/Downloads/DLIB-lib/lib
LIBS += -ldlib

QMAKE_CXXFLAGS += -std=c++11  -I/opt/X11/include -v

INCLUDEPATH += -L/opt/X11/include/X11

LIBS += -pthread
CONFIG += link_pkgconfig
CONFIG +=c11
#PKGCONFIG += x11
` 

I also added the all/source.cpp  to the my project source .

Also put dlib/dlib folder to my project .

I got : 

"_XwcTextPropertyToTextList", referenced from:
      dlib::get_from_clipboard(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&) in source.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How we can use dlib from qt Creator? 

I chosed this qt standard way. there is also cmake project alternative in Qt Creator but needs too much effort.

Best 

thx.

**Comment by andriy-gerasika** [comment]
Greetings!
I am also using dlib in my Qt/QtCreator project and it works just fine:
1. do not include dlib/all/source.cpp
2. do not include /opt/X11, LIBS += -pthread, etc, etc,
3. use just this one line in .pro file to get dlib in QtCreator:
PKGCONFIG += dlib

dlib supports Qt/QtCreator/pkgconfig ok

**Comment by MyraBaba** [comment]
Andriy . my dear :) You saved my day... :))))

I made it run through the hard way.. including source , phtread , and lib..  whatever shouldnt do I did . It worked..  But compalins about the Blass, Lapack and after added that it super slow..  

With your PKGCONFIG . (I run make install in build dir before to see the paths)  all is good. Intel MKL looks working.

I required to add : 

LIBS += -L/opt/intel/compilers_and_libraries_2018.1.126/mac/mkl/lib/
INCLUDEPATH+=/opt/intel/compilers_and_libraries_2018.1.126/mac/mkl/include/

It is faster now. Looks I have same performance with bare c++ compile with Clion.

Do you have experince with Intel MKL by the way ?  Shouldnt it use the all cpu cores (dlib compiled with MKL) ?  Any experince on that ? 

Best and thanks again.

**Comment by andriy-gerasika** [comment]
dlib + Intel MKL + OpenCV was not working for me: see https://github.com/davisking/dlib/issues/931
maybe the problem was in specific Intel MKL version; dlib + OpenCV works just fine for me

**Comment by MyraBaba** [comment]
Hi Andriy,

I couldn wirte video with openCV in the QT have you ant experience on this ? QtCreator I added videowriter:
```

`void Widget::show_frame(Mat &image)
{
    Mat resized_image = image.clone();
    video.write(image);

    int width_of_label = ui->label_camera->width();
    int height_of_label = ui->label_camera->height();

    Size size(width_of_label, height_of_label);

//    cv::resize(image, resized_image, size);
    cvtColor(image,image,CV_BGR2RGB);
    cvtColor(resized_image, resized_image, CV_BGR2RGB);`
```

But its opening the output file and freezind at the 6kb and not writing. Try both mjpg mpeg etc.

But is is working in plain C++11 . without Qt . framework. 

Any idea?

**Comment by andriy-gerasika** [comment]
Sadly, no experience w/ Qt && cv::VideoWriter

**Comment by MyraBaba** [comment]
very sadly :)  it makes me crazy, Qt . Yes great tool but if you stuck you stuck . and have to wait next prophet :)

thanks

**Comment by xsacha** [comment]
I don't understand the problem. Dlib is C++, so is Qt. Qt doesn't make the process any easier.
Heck I can open a dlib example app and start writing Qt in it.

Qt works perfectly with CMake. Dlib works perfectly with qmake.

**Comment by mshobeyri** [comment]
you can use https://github.com/mshobeyri/QFaceRecognition repo that is a qt/qml wrapper on dlib.
