### ISSUE TITLE
cmake error: "Boost python library not found."

### ISSUE THREAD

**Issue by rigid** [davisking/dlib#1043]
## Expected Behavior
Successful cmake build

## Current Behavior
`python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA`
fails with:

> running install
> running bdist_egg
> running build
> Detected Python architecture: 64bit
> Detected platform: linux
> Configuring cmake ...
> -- The C compiler identification is GNU 6.4.0
> -- The CXX compiler identification is GNU 6.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1597 (message):
>   No header defined for python-py34; skipping header check
> Call Stack (most recent call first):
>   /tmp/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
>   CMakeLists.txt:9 (include)
> -- Could NOT find Boost
> CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1597 (message):
>   No header defined for python-py35; skipping header check
> Call Stack (most recent call first):
>   /tmp/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
>   CMakeLists.txt:9 (include)
> -- Could NOT find Boost
> CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1597 (message):
>   No header defined for python3; skipping header check
> Call Stack (most recent call first):
>   /tmp/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
>   CMakeLists.txt:9 (include)
> -- Could NOT find Boost
> -c: unable to find executable in PATH.
> -- Could NOT find Boost
> -- Found PythonLibs: /usr/lib/libpython3.5m.so (found suitable version "3.5.4", minimum required is "3.4")
> -- Enabling AVX instructions
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
> -- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
> -- Looking for gethostbyname
> -- Looking for gethostbyname - found
> -- Looking for connect
> -- Looking for connect - found
> -- Looking for remove
> -- Looking for remove - found
> -- Looking for shmat
> -- Looking for shmat - found
> -- Looking for IceConnectionNumber in ICE
> -- Looking for IceConnectionNumber in ICE - found
> -- Found X11: /usr/lib/libX11.so
> -- Looking for png_create_read_struct
> -- Looking for png_create_read_struct - found
> -- Looking for jpeg_read_header
> -- Looking for jpeg_read_header - found
> -- Searching for BLAS and LAPACK
> -- Searching for BLAS and LAPACK
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
> -- Checking for module 'cblas'
> --   Found cblas, version 1.16
> -- Checking for module 'lapack'
> --   Found lapack, version 3.2.1
> -- Found BLAS and LAPACK via pkg-config
> -- C++11 activated.
> --  *****************************************************************************************************
> --  To compile Boost.Python yourself download boost from boost.org and then go into the boost root folder
> --  and run these commands:
> --     ./bootstrap.sh --with-libraries=python
> --     ./b2
> --     sudo ./b2 install
> --  *****************************************************************************************************
> CMake Error at /tmp/dlib/dlib/cmake_utils/add_python_module:149 (message):
>    Boost python library not found.
> Call Stack (most recent call first):
>   CMakeLists.txt:9 (include)
> -- Configuring incomplete, errors occurred!
> See also "/tmp/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
> See also "/tmp/dlib/tools/python/build/CMakeFiles/CMakeError.log".
> error: cmake configuration failed!

## Steps to Reproduce
Manually compile or install with pip according to instructions.

* **Version**: 19.8.1 (pip) and master (manual compile)
* **Where did you get dlib**: PyPI and this repo
* **Platform**: gentoo amd64
* **Compiler**: gcc 6.4.0

This patch seems to fix/workaround the issue:
```
diff --git a/dlib/cmake_utils/add_python_module b/dlib/cmake_utils/add_python_module
index 543cb43d..d2c8fde6 100644
--- a/dlib/cmake_utils/add_python_module
+++ b/dlib/cmake_utils/add_python_module
@@ -68,6 +68,12 @@ if (PYTHON3)
         FIND_PACKAGE(Boost 1.41.0 COMPONENTS python-py35)
     endif()
     if (NOT Boost_FOUND)
+        FIND_PACKAGE(Boost 1.41.0 COMPONENTS python-3.4 )
+    endif()
+    if (NOT Boost_FOUND)
+        FIND_PACKAGE(Boost 1.41.0 COMPONENTS python-3.5 )
+    endif()
+    if (NOT Boost_FOUND)
         FIND_PACKAGE(Boost 1.41.0 COMPONENTS python3)
     endif()
     if (NOT Boost_FOUND)
```

i'm not sure about the bug or if this would be an acceptable fix, so I just put it here and don't open a PR.

**Comment by davisking** [comment]
Thanks for reporting this.  Once this PR (https://github.com/davisking/dlib/pull/1040) is merged we don't be using boost.python anymore so this whole sort of problem should go away.  This should happen soon, so I'll leave this patch unmerged to avoid creating conflicts with the pybind11 PR.
