### ISSUE TITLE
How to merge multiple .svm files to create face detector using Dlib python? 

### ISSUE THREAD

**Issue by mschaudhari** [davisking/dlib#1044]
I am trying to train an face detector using **Dlib**.  I have created three .svm file for using different types of images. I want to merge that svm file to create master detector. So, What should I do? 

I have created svm files using Dlib python. Anybody help me. Thanks in advance.

for example :

```
detector1.svm
detector2.svm
detector3.svm
```

I want to merge above files and create master detector. like:
`detector.dat`

**Comment by davisking** [comment]
You have to use the C++ API to do this.  The constructor for the
object_detector class takes an array of detectors.  So there isn't much to
it, but you need to use C++.
