### ISSUE TITLE
dnn_trainer train / train_one_step compilation error with msvc vs2017

### ISSUE THREAD

**Issue by justadudewhohacks** [davisking/dlib#1045]
I managed to run some of the dnn examples with msvc (visual studio 2017). However, I can not get the example `dnn_metric_learning_on_images_ex.cpp` to compile as it says '**no instance of overloaded function**' at `trainer.train_one_step(images, labels)`.

The expected input should be a `std::vector<matrix<rgb_pixel>>` as the input_type of the net is defined as `input_rgb_image`, right?

I ran into this issue with the v19.8 release.

**Comment by davisking** [comment]
That example is compiling successfully for me on my desktop and also in the
Appveyor automated test, both using visual studio 2017.  So it should
work.  Have you modified anything?

**Comment by justadudewhohacks** [comment]
Ok, so apparently the compilation error is gone after rebuilding the solution from scratch. However, for some reason visual studio still highlights this as a syntax error, probably a bug.

Atleast the example is compiling. Thanks for the quick response and sorry for the noise!
