### ISSUE TITLE
Why Dlib detector doesn't detect some images?

### ISSUE THREAD

**Issue by mschaudhari** [davisking/dlib#1046]
I have 100 images. all the images have frontal faces.  Detected all the images using dlib detector. But, 17 images not detected.

```
Total images : 100
Detected images : 83
Not Detected images : 17 (That images have frontal faces, but not detected)
```

Why doesn't Dlib detector detect some images? In my case 17 images not detected.

Sorry for my poor english.

**Comment by sturkmen72** [comment]
could you upload sample images that not detected.

**Comment by davisking** [comment]
http://dlib.net/faq.html#WhydoesnttheobjectdetectorItrainedwork

**Comment by davisking** [comment]
Or maybe you are using the detector that comes with dlib.  Who knows.  You should fill out the issue template.
