### ISSUE TITLE
error: cmake configuration failed

### ISSUE THREAD

**Issue by nouxu1** [davisking/dlib#1049]
Hello, am new with python and dlib compiled with cuda.
first, I have installed VS 2015. Then I installed cmake 3.10.
I have Cuda 9 intalled with cuDNN 7.
I tried to compile dlib with python by using the command:

> python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

I got the following error:
[error.txt](https://github.com/davisking/dlib/files/1604095/error.txt)

what should I do to use dlib with python and cuda.
Thanks in advance

**Comment by davisking** [comment]
You need to install the newest visual studio 2015.  You must have an old version if you are getting the error about lack of C++11 support.

**Comment by nouxu1** [comment]
@davisking how to check the version of cuDNN?

**Comment by davisking** [comment]
Uninstall visual studio. Then go to the microsoft webpage and download visual studio.  Then install it.  Then you will have the newest version.

**Comment by nouxu1** [comment]
I fixed the problem of VS and cuDNN..I had the suitable versions..
but I got another error referring to boost.python !!
