### ISSUE TITLE
static shared_ptr bridge throw exception while freeing

### ISSUE THREAD

**Issue by ShuangLiu1992** [davisking/dlib#105]
Sample code:

```
typedef dlib::type_safe_union<int, optical_flow_params> input_type;
	typedef dlib::type_safe_union<int, optical_flow_solution> output_type;

	static std::shared_ptr<dlib::bridge> bridge;
	static std::shared_ptr<dlib::pipe<input_type>> input;
	static std::shared_ptr<dlib::pipe<output_type>> output;
	if (bridge == nullptr)
	{
		input = std::make_shared<dlib::pipe<input_type>>(1);
		output = std::make_shared<dlib::pipe<output_type>>(1);
		bridge = std::make_shared<dlib::bridge>(dlib::connect_to("localhost:" + std::to_string(FLOW_PORT)), dlib::transmit(*input), dlib::receive(*output));
	}
```

The bridge works fine but when the program finishes and the shared_ptr is freed it reports the following

>  	ntdll.dll!00007ff9d8764aa0()	Unknown
>  	ntdll.dll!00007ff9d86f0216()	Unknown
>  	ntdll.dll!00007ff9d86eee69()	Unknown
> >	perspective.exe!dlib::mutex::unlock() Line 56	C++
>  	perspective.exe!dlib::auto_mutex::unlock() Line 71	C++
>  	perspective.exe!dlib::auto_mutex::~auto_mutex() Line 89	C++
>  	perspective.exe!dlib::pipe<dlib::type_safe_union<int,optical_flow_params,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void> >::is_enabled() Line 299	C++
>  	perspective.exe!dlib::impl_brns::impl_bridge<dlib::pipe<dlib::type_safe_union<int,optical_flow_params,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void> >,dlib::pipe<dlib::type_safe_union<int,optical_flow_solution,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void> > >::transmit_thread() Line 492	C++
>  	perspective.exe!dlib::member_function_pointer<void,void,void,void>::mp_impl<dlib::impl_brns::impl_bridge<dlib::pipe<dlib::type_safe_union<int,optical_flow_params,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void> >,dlib::pipe<dlib::type_safe_union<int,optical_flow_solution,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void,dlib::_void> > > >::call() Line 216	C++
>  	perspective.exe!dlib::member_function_pointer<void,void,void,void>::operator()() Line 244	C++
>  	perspective.exe!dlib::multithreaded_object::thread_helper() Line 231	C++
>  	perspective.exe!dlib::dlib_create_new_thread_helper<dlib::multithreaded_object,&dlib::multithreaded_object::thread_helper>(void * obj) Line 25	C++
>  	perspective.exe!dlib::threads_kernel_shared::thread_starter(void * object) Line 273	C++
>  	perspective.exe!dlib::threads_kernel_shared_helpers::thread_starter(void * param) Line 39	C++
>  	[External Code]	
>

**Comment by davisking** [comment]
This isn't a dlib bug.  You have multiple global objects and their order of destruction is important, but C++ doesn't define global object destruction order.   Even more, are the pipes always destructed before the bridge?  That's definitely illegal in C++.  

You would be much better off not using global (or static) variables.
