### ISSUE TITLE
error: cmake configuration failed!

### ISSUE THREAD

**Issue by aquibjaved** [davisking/dlib#1050]
I am trying to upgrade dlib, My current version of dlib installed is '19.1.0'.
When I am trying to upgrade via pip or making from source `python setup install`
I am getting the below error:
`running install
 running bdist_egg
 running build
 Detected Python architecture: 64bit
 Detected platform: linux2
 Removing build directory /home/aquib/dlib-master/./tools/python/build
 Configuring cmake ...
 -- The C compiler identification is unknown
 -- The CXX compiler identification is unknown
 error: cmake configuration failed!
`
can someone please help me, how to fix it.
Thanks

**Comment by davisking** [comment]
You need to install a c++ compiler.  Also, if you google that error message
you can find additional instructions.

**Comment by aquibjaved** [comment]
Hi @davisking, thanks for the swift reply,
I already have gcc installed, 
I looked in Google, I tried few things but didn't help me much.
Thanks

**Comment by dev-ramesh** [comment]
@aquibjaved : I'm struggling with same issue. Were you able to resolve it ?

**Comment by aquibjaved** [comment]
@dev-ramesh  I tried the following steps and it worked, it was the issue of gcc as @davisking  told in the earlier comment:
` sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  sudo apt-get update
  sudo apt-get install gcc-5 g++-5
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5`
