### ISSUE TITLE
Strange memory allocation for DNN with MMOD

### ISSUE THREAD

**Issue by vrodionovpro** [davisking/dlib#1053]
Hi. I'm trying to detect problem about two weeks, but cannot and now reporting here.

My network with mmod loss layer get one square image on input with size 230 pixels and using about 100 mb of video memory. But then image size grow to 250 pixels network want about 4 gb of video memory and application fails.

There is my network:
```
template <long num_filters, typename SUBNET> using con5__2 = con<num_filters,5,5,2,2,SUBNET>;
template <long num_filters, typename SUBNET> using con5__1  = con<num_filters,5,5,1,1,SUBNET>;
template <typename SUBNET> using downsampler__A = relu<affine<con5__1<512,
        relu<affine<con5__1<256,
        relu<affine<con5__1<128,
        relu<affine<con5__1<256,
        relu<affine<con5__2<128,
        relu<affine<con5__2<64,
        relu<affine<con5__2<32,
        SUBNET
        >>>
        >>>>>>>>>>>>>>>>>>;

using netMouthA = loss_mmod<con<4,9,9,1,1,downsampler__A<input_rgb_image_pyramid<pyramid_down<6>>>>>;

```

and there is code with simple calling network:

```
netMouthA       m_netMouth;
matrix<rgb_pixel> imgTmp;
...

auto dets_tmp = m_netMouth(imgTmp);
m_netMouth.clean();

```
This code calling in parallel with main thread. May be this is the problem?

About memory. I added in cuda_data_ptr.cpp line in constructor:
`std::cout << "get " << n / (1024) << " kb" << std::endl;`

and after calling network saw this on screen:
```
IMG SIZE:240x238
get 6 kb
get 4279680 kb
```
and also:
`forward_workspace_size_in_bytes=4321885 kb`

My configuration:
Windows 10 x64, Visual Studio 2015 (19.0.24215.1), using cuda (8.0, cudnn 5.1)  and Intel Compiler 18 with VS (trying compile with VS compiler and Intel - same result).

Last updated dlib. Additional: openSSL, avx, sse2,4, blas, lapack, Intel MKL. 

Trying on HW: Intel Xeon 2690 (14 cores), 24 Gb memory, Video: gtx 970 4 Gb, Gtx 660 2 Gb (same effect on both cards).

**Comment by davisking** [comment]
What happens if you call set_dnn_prefer_smallest_algorithms() at program
startup?

**Comment by vrodionovpro** [comment]
Thanks, Davis. I'm training with with function, but when calling network all was good with fastest algorithms. 

Now it works, but if you think it's not a bug, let it be with smallest algorithms.

Love u and your library. Thanks!

**Comment by davisking** [comment]
So calling set_dnn_prefer_smallest_algorithms() fixed the issue?

**Comment by vrodionovpro** [comment]
Yes, now it works perfectly.
