### ISSUE TITLE
CMake configuration failed

### ISSUE THREAD

**Issue by najwaghamdi** [davisking/dlib#1054]
I'm trying to install dlib and this is the message I got -- can you please point out how to resolve this issue 

thanks 

-----

Collecting dlib
  Using cached dlib-19.8.1.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command /Users/najwaghamdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/tmp9zfqx4e6pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  Detected Python architecture: 64bit
  Detected platform: darwin
  Configuring cmake ...
  -- The C compiler identification is AppleClang 7.3.0.7030031
  -- The CXX compiler identification is AppleClang 7.3.0.7030031
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
    New Boost version may have incorrect or missing dependencies and imported
    targets
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
    /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1610 (message):
    No header defined for python-py34; skipping header check
  Call Stack (most recent call first):
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  -- Could NOT find Boost
  CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
    New Boost version may have incorrect or missing dependencies and imported
    targets
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
    /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1610 (message):
    No header defined for python-py35; skipping header check
  Call Stack (most recent call first):
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  -- Could NOT find Boost
  CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
    New Boost version may have incorrect or missing dependencies and imported
    targets
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
    /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1610 (message):
    No header defined for python3; skipping header check
  Call Stack (most recent call first):
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  -- Boost version: 1.66.0
  -- Found the following Boost libraries:
  --   python3
  -- Found PythonLibs: /Users/najwaghamdi/anaconda/lib/libpython3.6m.dylib (found suitable version "3.6.0", minimum required is "3.4")
  -- Enabling SSE4 instructions
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - found
  -- Found Threads: TRUE
  -- Looking for png_create_read_struct
  -- Looking for png_create_read_struct - found
  -- Looking for jpeg_read_header
  -- Looking for jpeg_read_header - found
  -- Searching for BLAS and LAPACK
  -- Searching for BLAS and LAPACK
  -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
  -- Checking for module 'cblas'
  --   No package 'cblas' found
  -- Checking for module 'lapack'
  --   No package 'lapack' found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of void*
  -- Check size of void* - done
  -- Found Intel MKL BLAS/LAPACK library
  -- Looking for sgesv
  -- Looking for sgesv - found
  -- Looking for sgesv_
  -- Looking for sgesv_ - found
  CUDA_TOOLKIT_ROOT_DIR not found or specified
  -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
  -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
  CMake Error at /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/use_cpp_11.cmake:74 (target_compile_features):
    target_compile_features The compiler feature "cxx_thread_local" is not
    known to CXX compiler
    "Clang"
    version 7.3.0.7030031.
  Call Stack (most recent call first):
    /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/CMakeLists.txt:742 (enable_cpp11_for_target)
  -- Building a C++11 test project to see if your compiler supports C++11
  -- ********** Your compiler failed to build a C++11 project.  C++11 is required to use all parts of dlib! **********
  -- Performing Test COMPILER_SUPPORTS_CXX11
  -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
  -- Performing Test COMPILER_SUPPORTS_CXX0X
  -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
  -- C++11 activated (compiler doesn't have full C++11 support).
  -- USING BOOST_LIBS: /usr/local/lib/libboost_python3-mt.dylib
  -- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 (found version "3.6.3")
  CMake Warning at CMakeLists.txt:16 (message):
    Numpy not found.  Functions that return numpy arrays will throw exceptions!
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
  error: cmake configuration failed!
  
  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command /Users/najwaghamdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-plzr3ene-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Detected Python architecture: 64bit
    Detected platform: darwin
    Removing build directory /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/./tools/python/build
    Configuring cmake ...
    -- The C compiler identification is AppleClang 7.3.0.7030031
    -- The CXX compiler identification is AppleClang 7.3.0.7030031
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
      New Boost version may have incorrect or missing dependencies and imported
      targets
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1610 (message):
      No header defined for python-py34; skipping header check
    Call Stack (most recent call first):
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    -- Could NOT find Boost
    CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
      New Boost version may have incorrect or missing dependencies and imported
      targets
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1610 (message):
      No header defined for python-py35; skipping header check
    Call Stack (most recent call first):
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    -- Could NOT find Boost
    CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
      New Boost version may have incorrect or missing dependencies and imported
      targets
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1610 (message):
      No header defined for python3; skipping header check
    Call Stack (most recent call first):
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    -- Boost version: 1.66.0
    -- Found the following Boost libraries:
    --   python3
    -- Found PythonLibs: /Users/najwaghamdi/anaconda/lib/libpython3.6m.dylib (found suitable version "3.6.0", minimum required is "3.4")
    -- Enabling SSE4 instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    -- Looking for png_create_read_struct
    -- Looking for png_create_read_struct - found
    -- Looking for jpeg_read_header
    -- Looking for jpeg_read_header - found
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for module 'lapack'
    --   No package 'lapack' found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Found Intel MKL BLAS/LAPACK library
    -- Looking for sgesv
    -- Looking for sgesv - found
    -- Looking for sgesv_
    -- Looking for sgesv_ - found
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    CMake Error at /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/cmake_utils/use_cpp_11.cmake:74 (target_compile_features):
      target_compile_features The compiler feature "cxx_thread_local" is not
      known to CXX compiler
      "Clang"
      version 7.3.0.7030031.
    Call Stack (most recent call first):
      /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/dlib/CMakeLists.txt:742 (enable_cpp11_for_target)
    -- Building a C++11 test project to see if your compiler supports C++11
    -- ********** Your compiler failed to build a C++11 project.  C++11 is required to use all parts of dlib! **********
    -- Performing Test COMPILER_SUPPORTS_CXX11
    -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
    -- Performing Test COMPILER_SUPPORTS_CXX0X
    -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
    -- C++11 activated (compiler doesn't have full C++11 support).
    -- USING BOOST_LIBS: /usr/local/lib/libboost_python3-mt.dylib
    -- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 (found version "3.6.3")
    CMake Warning at CMakeLists.txt:16 (message):
      Numpy not found.  Functions that return numpy arrays will throw exceptions!
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
    error: cmake configuration failed!
    
    ----------------------------------------
Command "/Users/najwaghamdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-plzr3ene-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/5c/_l5yg4411v1gdlr0p0bt_s_m0000gn/T/pip-build-v8e_j6r3/dlib/

**Comment by davisking** [comment]
Fill out the issue template.
