### ISSUE TITLE
Get the detail of all the variables tested by find_min_global

### ISSUE THREAD

**Issue by RomainSabathe** [davisking/dlib#1055]
Hi, thanks for the great work on this project and for the awesome 19.8 update. :-)

I'm having a lot of fun playing with `find_min_global` and `find_max_global`. I wonder if instead of getting the (estimated) function optimum only, we could also get all the other parameters that have been tested.  In other words, I'd like to be able to reproduce [this sort of plot](https://2.bp.blogspot.com/-Yo31249Ta0s/WkEPvou7SWI/AAAAAAAAA0o/O0rkQR5ar8cOpKmzTEq_KSq4af_xZTUCQCLcBGAs/s1600/bayesopt_vs_lipo.svg.png). 

I'd be happy to work on that. The only thing is my experience with C++ is not as diversified as I want it to be. Would you mind giving some indications as to where I can start?

I have looked into [find_max_global.h](https://github.com/davisking/dlib/blob/d3a824d942bd6889b277580dda970f9135e9777b/dlib/global_optimization/find_max_global.h) where we use the `get_next_x` function defined [here](https://github.com/davisking/dlib/blob/d3a824d942bd6889b277580dda970f9135e9777b/dlib/global_optimization/global_function_search.cpp#L691).
Correct me if I'm wrong, but the `global_function_search` object is a sort of a class (or struct) that holds the best objective value found so far and the parameters that have been tested? Sort of. I guess it does more than that, but that's the idea, isn't it?
I think I'm also getting confused with the role and behavior of `function_evaluation_request`. It seems this is a struct that holds information as well?

In any case, if it happens that either `global_function_search` or `function_evaluation_request` keep in memory all the past configurations tested, then it should be relatively easy to output them in some ways?

Any help/indication would be very much appreciated. Thank you!

**Comment by davisking** [comment]
Thanks, I'm glad you like it :)

You can just make your lambda function record those things.  So capture a `std::vector` and append all the function evaluations into it with whatever statistics you would like.  Then when the whole thing is done you can look at that vector and plot the information.

Yes, `global_function_search` knows everything.  It's fully documented (http://dlib.net/optimization.html#global_function_search) so you can see it's entire API there.  You could also do what you want by interacting directly with the `global_function_search`, but I would just use a lambda that captured a `std::vector`.  Although if you want to do multiple random trials you will need to set the random seed for the `global_function_search` to something different each time.
