### ISSUE TITLE
Adjusting font size and rectangle thickness of detection results

### ISSUE THREAD

**Issue by justadudewhohacks** [davisking/dlib#1056]
Hey again,

first of all thanks for providing this awesome library. Maybe I'm just acting dumb but I couldn't figure out how to adjust font size and position of text or the thickness of rectangles drawn for detection results.

For example I am using:
`win.add_overlay(dlib::image_window::overlay_rect(rect, dlib::rgb_pixel(0, 0, 255), label))`

Is there actually a way to specify font size and thickness of things to draw? I couldn't find something in the examples. I found the default font size to appear pretty small for larger images.

**Comment by davisking** [comment]
There isn't any option to change those things.  The GUI is somewhat limited in that way unfortunately.

**Comment by justadudewhohacks** [comment]
Ok no worries, thanks for the quick response.
