### ISSUE TITLE
Question : face_chip from frontal_face_detector

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1057]
Hi,

Is there any decent way to extract face_chip at frontal_face_detector ?  I tried and get below error: 
```
‘dlib::rectangle dlib::full_object_detection::rect’ is private within this context
                     extract_image_chip(img, get_face_chip_details(shapes[i].rect, 150, 0.25), face_chip);
```

I know probably this is not an issue but its lock me down.

**Comment by davisking** [comment]
Yes, you can.  Read the documentation for extract_image_chip().

**Comment by MyraBaba** [comment]
I read and couldn't find the correct way :( .
I tried:
`                    extract_image_chip(img, get_face_chip_details(shapes[i], 150, 0.25), face_chip);
` 
and it returns empty chip. So I have error in the face_id extraction. Is it different than the DNN version of the  extraction ?  It is working in DNN but not in the frontal version. Clearly  I am missing something.

**Comment by davisking** [comment]
What documentation did you read?

**Comment by MyraBaba** [comment]
http://dlib.net/dlib/image_transforms/interpolation_abstract.h.html#extract_image_chips

I am also following the example at dnn_face_recogniton_ex.cpp (there is a working face chip extraction).  Sorry for taking your time Davis.

**Comment by davisking** [comment]
I'm just trying to teach you how to read documentation :)

So you see that the function takes a chip_details?  Did you read the
documentation for chip_details to see how to make one?  I think if you read
it you would see how to do this.

**Comment by MyraBaba** [comment]
:) working on it :) 

Finally i figure it out.   

nothing  !!!  

I re-write from the beginning  and the same code.  I looks like it was the curse of the IDE cLiON .....  I should call it cCat (seaCat) . it is drowning sometimes :((

Davis are you using any IDE ? what would you suggest ?

**Comment by davisking** [comment]
I use Vim for all my C++ work.
