### ISSUE TITLE
[iOS] Memory leak when deserializing face landmarks model file

### ISSUE THREAD

**Issue by noblakit01** [davisking/dlib#1058]
I use this code to init dlib::shape_predictor 

> NSString *modelFileName = [[NSBundle mainBundle] pathForResource:@"shape_predictor_5_face_landmarks" ofType:@"dat"];
    std::string modelFileNameCString = [modelFileName UTF8String];
    dlib::shape_predictor shape;
    dlib::proxy_deserialize a = dlib::deserialize(modelFileNameCString) >> shape;

But everytimes I run this code, I realize that it leak memory. I don't know how to release memory here.

**Comment by davisking** [comment]
Why do you think there is a memory leak in dlib?

**Comment by noblakit01** [comment]
Hi @davisking, I do some several test.

1. When I comment this line
`dlib::proxy_deserialize a = dlib::deserialize(modelFileNameCString) >> shape;`
The memory leak had gone.

2. I also checked the destructor of `shape_predictor ` and `proxy_deserialize ` class. It already called the destructor.

Thank you for the prompt reply and sorry for my bad English.

**Comment by davisking** [comment]
I’m very confident there isn’t a memory leak in that dlib code. I expect that you are either doing something wrong in the surrounding code or are measuring this wrong and there isn’t any leak at all.

**Comment by noblakit01** [comment]
Hi @davisking,

I recorded some videos to hope find out it.

1. [Release](https://vimeo.com/250268198).
You can see that I commented the lines 
`dlib::proxy_deserialize a = dlib::deserialize(modelFileNameCString) >> shape;`.
And in the memory go from 12.3MB -> 21.7MB (it gone to camera screen) -> 13.6MB(escape the camera).

2. [Memory leak](https://vimeo.com/250268337). 
I open the line:
`dlib::proxy_deserialize a = dlib::deserialize(modelFileNameCString) >> shape;` and do the same action.  The memory go from 12.2 MB -> 27.2 MB -> 19.1 MB.

I promised that I only changed commented the line above and did the same actions.

**Comment by davisking** [comment]
Do it a bunch of times and see if it keeps building up and up to
progressively higher memory usage.  You will either find that it doesn't
continue growing and this is just part of the normal working of the memory
manager used by your runtime (not part of dlib) and is normal.  Or you will
find that objective C or whatever language you are using isn't calling the
destructors on the C++ objects like it should.  If that's the case then you
need to figure out how to fix that.

**Comment by noblakit01** [comment]
I found that it doesn't continue growing up. So, It is a part of the normal working of memory manager in iOS. Do you know any solution to release it?

**Comment by davisking** [comment]
It doesn't matter, just let the memory manager do what it does and you will be fine.
