### ISSUE TITLE
dlib network thread safety

### ISSUE THREAD

**Issue by daisyron** [davisking/dlib#1059]
Hi,

Is it legal to do invoke network forward operation from different threads?

Thanks,
Ron.

**Comment by davisking** [comment]
No

**Comment by daisyron** [comment]
Hi Davis,

Can you elaborate please:

My configuration is the following:
- I have a collection of networks.
- I have a collection of working threads.
- Each thread invokes the network forward method for a different network.

I'm not invoking the forward of a specific network from two different threads.

Is this legal?

Regards,
Ron.

**Comment by davisking** [comment]
I mean that all the normal thread safety and synchronization rules apply to
a network object just like they would to a std::string, int, or any other
normal object.   The network object isn't special with regards to threads.

**Comment by daisyron** [comment]
Hi Davis,

Thanks for your answer.

Ron.
