### ISSUE TITLE
"png_loader: parse error in file " when I'm trying to load png image

### ISSUE THREAD

**Issue by BillHu** [davisking/dlib#106]
Hi, I'm trying to load png file using load_image() in iOS device, but always get an error:
libc++abi.dylib: terminating with uncaught exception of type dlib::image_load_error: png_loader: parse error in file /var/containers/Bundle/Application/13BCABF9-6F86-4C1E-850F-DB167E9820C7/DLibBuild1.app/2.png

**Comment by davisking** [comment]
Sounds like that png file is corrupt.  Can you open it in another application?

**Comment by BillHu** [comment]
yes, and I have tried some different png pics, still the same error

**Comment by davisking** [comment]
There must be something wrong with how you have built or linked to libpng,
as that error originates from libpng.

**Comment by BillHu** [comment]
Thanks for replying. Now I'm converting iOS UIImage to cv::Mat, and then convert to array2d.

```objective-c
array2d<bgr_pixel> img;
UIImage *uiimage = [UIImage imageNamed:@"3.png"];
cv::Mat cvimg;
UIImageToMat(uiimage, cvimg);
dlib::assign_image(img, dlib::cv_image<dlib::rgb_alpha_pixel>(cvimg));
```
