### ISSUE TITLE
dlib takes about 200ms to detect a face

### ISSUE THREAD

**Issue by cfoch** [davisking/dlib#1061]
**The Gstreamer plugin**
I have created a GStreamer plugin including "dlib" as a library. In my plugin, the[ detection part ](https://github.com/cfoch/gst-plugins-cheese/blob/tmp2/gst/face/gstcheesefacedetect.cpp#L239)takes about 210ms in that plug-in.
**Isolate case**
However if I isolate the problem using a simple "dlib" + "opencv" program, [that part](https://github.com/cfoch/gst-plugins-cheese/blob/tmp2/examples/detector/main.cpp#L65) is done in about 65ms.

You can see how I compiled it in [https://github.com/cfoch/gst-plugins-cheese/blob/tmp2/configure.ac](https://github.com/cfoch/gst-plugins-cheese/blob/tmp2/configure.ac
)
## Expected Behavior
The detection part in *GStreamer plugin* should average around 65ms, too.
## Current Behavior
The detection part in *GStreamer plugin* takes an average around 210ms.

## Steps to Reproduce
precondition: dlib, opencv and gstopencvvideofilter (libgstreamer-plugins-base1.0-dev in Ubuntu)

```
$ ./autogen.sh
$ make
$ export GST_PLUGIN_PATH_1_0=$PWD/gst/face/.libs:$GST_PLUGIN_PATH_1_0
$ export GST_PLUGIN_PATH=$PWD/gst/face/.libs:$GST_PLUGIN_PATH
$ gst-launch-1.0 v4l2src ! videoconvert ! cheesefacedetect ! videoconvert ! xvimagesink
```

* **Version**: 19.8.99
* **Where did you get dlib**: git
* **Platform**: x86_64 x86_64 GNU/Linux Fedora 27
* **Compiler**: autotools + g++ (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)

**Comment by davisking** [comment]
I don't see how this could be a dlib issue.  It's either that you are compiling these two cases with different compiler switches (like probably without -O3 or -mavx) or you are giving the detector bigger images when using gstreamer.

**Comment by cfoch** [comment]
Yes, there were different resolutions. In the  GStreamer pipeline (dlib + opencv + gstopencvvideofilter) it was using 1280 x 720. While in the simple dlib program (dlib + opencv) it was using a 480x600 resolution. So I have set opencv's VideoCapture resolution to 1280x720. In that resolution, it's slower, but is extremely smooth (visually) with an average of (180ms) yet compared to the GStreamer plugin (210ms). 

About compiling with two different compilers, I am using the same rules for both programs, since they are compiled with the same [configure.ac.](https://github.com/cfoch/gst-plugins-cheese/blob/tmp2/configure.ac#L128).

**Comment by davisking** [comment]
Ok, well, this isn't a dlib issue.  As an aside, you should use -mavx since that will run even faster.
