### ISSUE TITLE
failed to compile a simple CUDA program

### ISSUE THREAD

**Issue by georgesterpu** [davisking/dlib#1063]
## Expected Behavior
I would like to compile dlib 19.8 Python API with CUDA support.

## Current Behavior
An error message is shown:
`*** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. ***`
[Full log on Pastebin](https://pastebin.com/Tr4m5zMX)

## Steps to Reproduce
`$ python setup.py build --yes USE_AVX_INSTRUCTIONS`

* **Version**: 19.8
* **Where did you get dlib**: github repo
* **Platform**: Manjaro (~Arch) Linux testing repository, Kernel 4.14.12, Python 3.6.4, Skylake i7-6700k, Nvidia GTX1080, cuda 9.1.85, nvidia drivers 390.12
* **Compiler**: gcc 7.2.1

I found a related thread about the Visual Studio compiler on Windows, but the fix indicated there did not work. My aim is to use the face alignment modules.

**Comment by davisking** [comment]
The test program is in dlib/cmake_utils_test_for_cuda.  You should try to
compile that with cmake and see what the errors are.  You probably just
don't have cuda installed correctly.  Also, does NVIDIA even support cuda
on arch linux?

**Comment by georgesterpu** [comment]
Thanks for the prompt reply.
I guess that Cuda is installed correctly, works fine with tensorflow. Don't know if Nvidia officially supports the platform or not, but the package maintainers are doing a really great job.

This is the log: [Pastebin link](https://pastebin.com/kkmt3pgH)
It requires gcc <= 6, which is already installed (6.4.1).
Any idea how I could link /usr/bin/gcc-6 instead of /usr/bin/gcc ?

**Comment by davisking** [comment]
You can set the CXX compiler environment variable.

**Comment by georgesterpu** [comment]
Nice, it works now
I used: `export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-6`

**Comment by neumartin** [comment]
@georgesterpu how can you do it?
I set export CXX=/usr/bin/gcc-6 and export CC=/usr/bin/gcc-6 and dos not work.
