### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by MarcoPorracin** [davisking/dlib#1064]
- Mac OS
- Python 3.6.1
- dlib 19.8.1

When import dlib:
`Traceback (most recent call last):
  File "multiface_tracking.py", line 3, in <module>
    import dlib
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib/dlib.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /opt/local/lib/libboost_python-mt.dylib
  Expected in: flat namespace
 in /opt/local/lib/libboost_python-mt.dylib`

I already tried the solutions on this issues:

- https://github.com/davisking/dlib/issues/889
- https://github.com/ageitgey/face_recognition/issues/168

None worked.

**Comment by davisking** [comment]
Try using the version of dlib from this PR. https://github.com/davisking/dlib/pull/1040

**Comment by MarcoPorracin** [comment]
I just downloaded https://github.com/supervacuus/dlib and run:

`python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA`

But the problem persists.

**Comment by davisking** [comment]
You have to use the code from the PR.  So get the code from the pybind11
branch.

**Comment by MarcoPorracin** [comment]
It worked! 

PS: for future people remember to uninstall any current version of dlib u may have.
