### ISSUE TITLE
Weights saving format

### ISSUE THREAD

**Issue by giovannirescia** [davisking/dlib#1066]
Hi all! I used the Dlib's function `net_to_xml` to save a model. I would like to know the format in which  the weights are saved, because each weight is saved as a vector.
For example, the first convolutional layer in the `dnn_face_recognition`'s ResNet34 has 32 7x7 kernels, the vector (weights from the xml file) has 4736 elements (3x32x7x7 + 32 from the bias). So, how are the weights for each kernel distributed? Is it something like:

`[bias_0, kernel_0_w_0, ..., kernel_0_w_48, bias_1, kernel_1_w_0, ..., kernel_1_w_48]` ?

Or maybe...

`[kernel_0_w_0, ..., kernel_0_w_48, ..., kernel_31_w_0, ..., kernel_31_w_48, bias_0, bias_1, ..., bias_31]` ?

I tried to use the `get_output` method from the `dnn_introduction2_ex` script:

```
// Now that we know the index numbers for each layer, we can access them
// individually using layer<index>(pnet).  For example, to access the output
// tensor for the first prelu layer we can say:
layer<3>(pnet).get_output();
```
To get the output from the first layer and that way make it more easy to realize how the weights are formated, but there was no output at all using that method.

Thanks!

**Comment by PXT846765038** [comment]
@giovannirescia I've met the same problem. After read the tools/convert_dlib_net_to_cafffe/main.cpp line 481&line482, I think "[kernel_0_w_0, ..., kernel_0_w_48, ..., kernel_31_w_0, ..., kernel_31_w_48, bias_0, bias_1, ..., bias_31]" maybe the right format (all the bias are at the end of these parameters). But... maybe "[kernel_0_w_0,kernel_1_w_0,kernel_2_w_0 ..., kernel_0_w_1,kernel_1_w_1,kernel_2_w_1, ..., , bias_0, bias_1, ..., bias_31]" ? Have you solve this problem? Can you provide any information about this? Thanks a lot!

**Comment by PXT846765038** [comment]
@davisking 
Hi , I saw 
 'filters = alias_tensor(num_filters_, sub.get_output().k(), filt_nr,filt_nc);' 
in layers.h line 182. Does that mean the weights for each kernel distributed as follows ?
"[kernel_0_0.w_0~kernel_0_0.w_48 ,kernel_0_1.w_0~kernel_0_1.w_48 ,kernel_0_2.w_0~kernel_0_2.w_48,
  kernel_1_0.w_0~kernel_1_0.w_48 ,kernel_1_1.w_0~kernel_1_1.w_48 ,kernel_1_2.w_0~kernel_1_2.w_48,
  ...
  ...
kernel_31_0.w_0~kernel_31_0.w_48,kernel_31_1.w_0~kernel_31_1.w_48,kernel_31_2.w_0~kernel_31_2.w_48,
bias0~bias31]"
I tried to get some infomation in your code but I can't get the essence. (╥﹏╥) Could you please give me some help ? Thank you.
A student sit at your feet !

**Comment by PXT846765038** [comment]
@davisking 
Hi , I saw
'filters = alias_tensor(num_filters_, sub.get_output().k(), filt_nr,filt_nc);'
in layers.h line 182. 
Does that mean that the weights for each kernel distributed as follows ? (ex. 4736 elements (3x32x7x7 + 32 from the bias))
"[kernel_0_0.w_0 to kernel_0_0.w_48 ,kernel_0_1.w_0 to kernel_0_1.w_48 ,kernel_0_2.w_0 to kernel_0_2.w_48,
kernel_1_0.w_0 to kernel_1_0.w_48 ,kernel_1_1.w_0 to kernel_1_1.w_48 ,kernel_1_2.w_0 to kernel_1_2.w_48,
...
...
kernel_31_0.w_0 to kernel_31_0.w_48, kernel_31_1.w_0 to kernel_31_1.w_48, kernel_31_2.w_0 to kernel_31_2.w_48,
bias0 to bias31]"
I tried to get some infomation in your code but I can't get the essence. (╥﹏╥) Could you please give me some help ? Thank you.
A student sit at your feet !

**Comment by davisking** [comment]
Tensors are always laid out in memory in sample, channel, row, column order.

**Comment by giovannirescia** [comment]
@PXT846765038 Sorry, not luck yet!

**Comment by PXT846765038** [comment]
来填个坑...
https://s1.ax1x.com/2018/04/26/C12yMq.png
