### ISSUE TITLE
Strange multi-core cpu behaviour for FaceID extraction (Intel MKL )

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1067]
Hi,

I faced this problem and solved (I dont know how) then. Now its here again.

I have installed Intell MKL and dlib recognized it. 
Environment : Ubuntu 17.10 Vmware / dlib 19.18

Same code working as expected in 1 CPU config at vmware. face Clustering working normally.

When I increase the CPU to 4 same code produce different FaceIDs and cluster each same face almost a new cluster. Also I noticed when the CPU is 4 the FaceID matrix looks like : 

` -4.81966    3.90495     3.7205   -4.50122   -1.58244  -0.523119  -0.992003    2.40911    4.38612   -4.20561    2.58002   -7.28974   -9.97469     3.6213   -2.98523    4.30516    3.83785    1.19064    -1.6977   0.439132    9.26733    6.57626   -3.56553    6.01283    1.25151   -10.1555     0.8558    4.42363    -4.3713   -5.35394    -3.7994    4.83549   -2.82209     4.9129   -3.12849    8.29048     1.8618   -2.08589   -1.73739    1.82456    -5.2071    1.07544   0.807497    3.94249  -0.438325   -1.01708  -0.935712   -3.23921    5.47425   -5.45159   -6.16232    6.36454    1.03887    1.52471    8.69113    2.71433    4.39939    2.44534   -6.40033     -2.007     1.9639   -1.31346    4.79818   -5.76698    4.28917    1.80952   -4.21522   -2.02713   -3.66099   -4.86666   -3.24266    3.69046 -0.0807444   -1.09379   -5.60643    3.97923     5.8499    3.59275   -3.79129    3.45195    1.16131   -4.15846     5.0772   0.647237   -2.01039   -1.24512   -5.96567    2.75296    5.86146    1.03891     5.4573    4.65191   0.403612    2.68568   -4.46816    3.66393   -9.68044    1.83355    3.08468    4.52143   -1.13614   -3.16549   -2.55605    0.96315   -3.21963    1.30811   -4.82536   -2.41554   -2.23716    1.20127   -4.05715    2.31485   -4.04909   -7.55441    1.39822   -2.84986   -2.96798   -1.21996   -1.09481    3.91338   -1.03413   -1.25198   0.479234   -5.08398    6.38813    -0.6226   -1.27153   -4.23582 `

But when I dropped the core number to 1 Cpu the matrix looks normal again:

`jittered face descriptor for one face:  -0.0342712    0.084815  -0.0129788  -0.0451168  -0.0387702   0.0468915  0.00486689   -0.158835    0.107166  -0.0588578    0.182379 -0.00549194   -0.280178   -0.130366    0.098114   0.0890493   -0.192882   -0.194091   -0.157906  -0.0813735   -0.106098  -0.0107024  -0.0688471  -0.0554715   -0.119377   -0.296071  -0.0644314  -0.0713873    0.144129   -0.106762   0.0104759  -0.0230365   -0.183921  -0.0609619   0.0706838   0.0630575  -0.0663186  -0.0788693    0.157492 0.000944382   -0.150513  -0.0387619   0.0793632    0.231997    0.169082   0.0692956   0.0174228  -0.0866586   0.0921634   -0.248945    0.107778    0.111375    0.154624    0.105993   0.0857368   -0.211503 -0.00265506   0.0960695   -0.229208   0.0828195   0.0908889  -0.0950158  -0.0960813  -0.0450996    0.136131   0.0600525   -0.080665   -0.146225    0.189676   -0.179161  -0.0711786  0.00395713  0.00539976   -0.178421   -0.291237   0.0324236    0.316072    0.192308   -0.177114   0.0142077 -0.00122157  -0.0655447   0.0763595   0.0582405  -0.0580904  -0.0355142  -0.0371499   0.0255795    0.182523  -0.0147614   0.0322971    0.145843  -0.0263463  -0.0283364  0.00971028   0.0388974  -0.0691186   0.0275721  -0.0800178  -0.0244961    0.088181  -0.0774656   0.0762962   0.0953166   -0.169695    0.221634   0.0576681  -0.0463131   0.0538869  -0.0576424 0.000498078   -0.022824    0.174242   -0.336898    0.231434    0.249284 0.000115582    0.137946  0.00932593   0.0591217   0.0536361  -0.0366447   -0.215465   -0.143773  -0.0519901  -0.0437162  -0.0201693    0.065073 
`

Decriptors:      `std::vector<matrix<float, 0, 1>> online_face_descriptors;`

Do you have any idea on this ? 

thx

**Comment by MyraBaba** [comment]
Further investigation:

I cloen vanilla dlib and ran test:

```
Running test_matrix \                                                          

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEST FAILED: test_matrix !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Failure message from test: 

Error occurred at line 1474.
Error occurred in file /home/osboxes/dlib/dlib/test/matrix.cpp.
Failing expression was colm(a,0) == m*b.

                                                                               

Testing Finished
Total number of individual testing statements executed: 470775651
Number of failed tests: 1
Num
```ber of passed tests: 134



FYI

**Comment by davisking** [comment]
Something is wrong with your BLAS install.  I don't know what it is.  But
the Intel MKL is giving the wrong outputs.
