### ISSUE TITLE
Getting C2678 error in trainer.h dnn metric learning in visual studio please help

### ISSUE THREAD

**Issue by ShubhamParab** [davisking/dlib#1068]
`
                size_t start = i*block_size;
                size_t stop  = std::min(num, start+block_size);

                if (start < stop)
                {
                    devices[i]->net.to_tensor(dbegin+start, dbegin+stop, job.t[i]);
                    **job.labels[i].assign(lbegin+start, lbegin+stop);**
                    job.have_data[i] = true;
                }
                else
                {
                    job.have_data[i] = false;
                }
            }
`
Error	C2678 - binary '+': no operator found which takes a left-hand operand of type 'std::vector<unsigned long,std::allocator<_Ty>>' (or there is no acceptable conversion)	
Also, C2088 - '+': illegal for class

line 1162 - job.labels[i].assign(lbegin+start, lbegin+stop);

**Comment by davisking** [comment]
Fill out the issue template.
