### ISSUE TITLE
Compiling Error C2678 & C2088 in trainer.h    function: void send_job (bool test_only,data_iterator dbegin,data_iterator dend,label_iterator lbegin)

### ISSUE THREAD

**Issue by ShubhamParab** [davisking/dlib#1069]
## Expected Behavior

Using http://dlib.net/dnn_metric_learning_on_images_ex.cpp.html to train identify human faces 

## Current Behavior

Error	C2678	binary '+': no operator found which takes a left-hand operand of type 'std::vector<unsigned long,std::allocator<_Ty>>' (or there is no acceptable conversion)
c:\dlib-19.8\dlib-19.8\dlib\dnn\trainer.h	1162	
Error	C2088	'+': illegal for class	VerifEye	c:\dlib-19.8\dlib-19.8\dlib\dnn\trainer.h	1162	

## Steps to Reproduce

changed: trainer.train_one_step(images, labels); 
to: trainer.train_one_step(images.begin(), images.end(), labels);
because it was giving error not matching argument list 

* **Version**: 19.8
* **Where did you get dlib**: dlib.net
* **Platform**: 64-bit
* **Compiler**: Visual Studio C++

**Comment by davisking** [comment]
The third argument is an iterator.  You gave a std::vector, which isn't an iterator. Give `labels.begin()`.
