### ISSUE TITLE
Problem building imglab

### ISSUE THREAD

**Issue by rodolfovalentim** [davisking/dlib#107]
Can someone help me with this issue? 

`In file included from /home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser/../algs.h:83:0,
                 from /home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser/cmd_line_parser_kernel_1.h:7,
                 from /home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser.h:6,
                 from /home/rodolfo/Workspace/dlib/tools/imglab/src/cluster.h:6,
                 from /home/rodolfo/Workspace/dlib/tools/imglab/src/cluster.cpp:4:
/home/rodolfo/Workspace/dlib/dlib/../dlib/image_loader/../image_transforms/../statistics/../matrix/matrix.h: In instantiation of ‘dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::matrix(const dlib::matrix_exp<U>&) [with EXP = dlib::matrix<float, 0l, 1l>; T = double; long int num_rows = 0l; long int num_cols = 1l; mem_manager = dlib::memory_manager_stateless_kernel_1<char>; layout = dlib::row_major_layout]’:
/home/rodolfo/Workspace/dlib/tools/imglab/src/cluster.cpp:155:56:   required from here
/home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser/../assert.h:90:53: error: incomplete type ‘dlib::compile_time_assert<false>’ used in nested name specifier
         DLIB_NO_WARN_UNUSED typedef char BOOST_JOIN(DLIB_CTA, __LINE__)[::dlib:
                                                     ^
/home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser/../assert.h:26:32: note: in definition of macro ‘BOOST_DO_JOIN2’
 #define BOOST_DO_JOIN2( X, Y ) X##Y
                                ^
/home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser/../assert.h:24:28: note: in expansion of macro ‘BOOST_DO_JOIN’
 #define BOOST_JOIN( X, Y ) BOOST_DO_JOIN( X, Y )
                            ^
/home/rodolfo/Workspace/dlib/dlib/../dlib/cmd_line_parser/../assert.h:90:42: note: in expansion of macro ‘BOOST_JOIN’
         DLIB_NO_WARN_UNUSED typedef char BOOST_JOIN(DLIB_CTA, __LINE__)[::dlib:
                                          ^
/home/rodolfo/Workspace/dlib/dlib/../dlib/image_loader/../image_transforms/../statistics/../matrix/matrix.h:1087:13: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
             COMPILE_TIME_ASSERT((is_same_type<typename EXP::type,type>::value =
             ^
CMakeFiles/imglab.dir/build.make:192: recipe for target 'CMakeFiles/imglab.dir/src/cluster.cpp.o' failed
make[2]: *** [CMakeFiles/imglab.dir/src/cluster.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/imglab.dir/all' failed
make[1]: *** [CMakeFiles/imglab.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by davisking** [comment]
Oops.  This should be fixed now.  Thanks for finding the bug.

**Comment by rodolfovalentim** [comment]
Tks man!

**Comment by davisking** [comment]
No problem
