### ISSUE TITLE
Convert lib models into CoreML format

### ISSUE THREAD

**Issue by atrbx5** [davisking/dlib#1071]
I am looking the way to speed up network with GPU on iOS, OSX
as I understand there is no metal/CoreML support for dlib?

I am expecting that it's possible to convert dlib .dat models to CoreML format similar to caffee models

`
import coremltools
coreml_model = coremltools.converters.caffe.convert(('***.caffemodel', '***.prototxt'))
coreml_model.save('hand/***.mlmodel')
`

Can you advise on the .dat format or is there is converters available for it?

* **Platform**: iOS, OSX

**Comment by davisking** [comment]
Save the models to xml using net_to_xml() and convert that instead.  That will be easier.  You can also look at the caffe converter in the tools folder which converts those xml files to caffe format if you want an example.

**Comment by atrbx5** [comment]
heave error while converting

'./dtoc dlib_face_recognition_resnet_model_v1.xml 1 3 150 150
Writing python part of model to dlib_face_recognition_resnet_model_v1_dlib_to_caffe_model.py
Writing weights part of model to dlib_face_recognition_resnet_model_v1_dlib_to_caffe_model.weights


*************** ERROR CONVERTING TO CAFFE ***************
No conversion between dlib pooling layer parameters and caffe pooling layer parameters found for layer 127
dlib_output_nc: 35
bottom_nc:      72
padding_x:      0
stride_x:       2
kernel_w:       3
pad_x:          1'

**Comment by davisking** [comment]
Yes, that's going to happen.  The whole idea of "one common format" is fundamentally ill-conceived when there is a lot of diversity of possible models.  There are things in dlib that have no correlate in caffe, this is one of many of them.

**Comment by atrbx5** [comment]
Well, got you (I am not an nn expert) 
but hoverer I like the idea of what apple doing here... providing engine that will use out of the box most efficient equation engine available on the device

I assume that caffee may not have same models as dlib, but CoreML have ability to create custom layers, so that direct dlib->CoreML conversion should be possible

but that's over hard for me at this moment)

thanks

**Comment by davisking** [comment]
Yes, it's always possible to reimplement anything. My point however is that there is a lot of innovation happening in ML and expecting some specific piece of software (e.g. CoreML) to somehow implement everything that currently exists as well as everything that will be created at any point in the future is not a reasonable expectation.  That kind of expectation is implicit in anything that claims to be able to be the universal software capable of running any model and that's why it's unreasonable.
