### ISSUE TITLE
Output tensors dimension of different network layers

### ISSUE THREAD

**Issue by daisyron** [davisking/dlib#1072]
Hi,

Is it possible to get the dimensions of each layer output tensor in the DNN right after its creation?

When I try `dlib::layer<*>(net).get_output().nc()` etc., right after creation I get zeros - meaning the layers output tensors are not initialized.

After running an image through the network I get the right numbers.

For the purpose of my project I need to know these dimensions in construction time...

Regards,

Ron.

**Comment by davisking** [comment]
You can't know, because it depends on the size of the input to the network,
which you haven't given the network yet.

**Comment by daisyron** [comment]
Thanks.
