### ISSUE TITLE
dlib link failure

### ISSUE THREAD

**Issue by takotakot** [davisking/dlib#1073]
I encountered a problem linking to dlib when compiling gazr (https://github.com/severin-lemaignan/gazr). I reported the issue to https://github.com/severin-lemaignan/gazr/issues/21 but maybe it's dlib problem.

## Expected Behavior
`lib/libdlib.so` or `lib/libdlib.so.x.y.z` is used for link.

## Current Behavior
`lib/libdlib.a` is given.

## Steps to Reproduce

```
# dlib
cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/takotakot/dlib_install/ -DBUILD_SHARED_LIBS=ON ..
make
make install

# gazr
dlib_DIR=/home/takotakot/dlib_install/ cmake .. -DWITH_ROS=false
make
```

Got error: ``/usr/bin/ld: /home/takotakot/dlib_install/lib/libdlib.a(base64_kernel_1.cpp.o): relocation R_X86_64_32S against `_ZTVN4dlib6base64E' can not be used when making a shared object; recompile with -fPIC``

When I changed the file path from `/home/takotakot/dlib_install/lib/libdlib.a` to `/home/takotakot/dlib_install/lib/libdlib.so` manually, I could comiple libgazr.so .

* **Version**: 23499b7d130c74ee6dbd1822a79f7a4c2a15880b
* **Where did you get dlib**: github
* **Platform**: x86_64
* **Compiler**: Ubuntu 5.4.0-6ubuntu1~16.04.5

**Comment by davisking** [comment]
If you changed libgazr's target_link_libraries call to link against dlib::dlib_shared it works.

**Comment by davisking** [comment]
For reference, there is some discussion of this here https://github.com/davisking/dlib/issues/923.  I still don't think that changing the dlib cmake files to build either a shared or static library based on BUILD_SHARED_LIBS is a good idea.  I'm open to arguments against this view, but they need to address all the use cases.

**Comment by takotakot** [comment]
Thank you very much. I'll try other options for dlib and change libgazr's target and report again.

**Comment by davisking** [comment]
You could also compile dlib with position independent code by setting CMAKE_POSITION_INDEPENDENT_CODE to true.
