### ISSUE TITLE
How to add images to a window?

### ISSUE THREAD

**Issue by jackweiwang** [davisking/dlib#1075]
In gui_api_ex.cpp file and image_ex.cpp file.
The implementation  is blue rectangle, Now, I want add image_window class to rectangle position.
 What should I do? 
Is there an API or A member function?

ex:
![image](https://user-images.githubusercontent.com/19305790/35137931-e4321a62-fd26-11e7-94a5-8f2693484f7c.png)

**Comment by davisking** [comment]
Read the documentation.  It's all discussed there. http://dlib.net/faq.html#Whereisthedocumentationforobjectfunction
