### ISSUE TITLE
convert face-chip to png make people like Shrek :) . color problem

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1076]
Hi,

I am converting the face_chip to cv::Mat and than jpeg or png  like below:

`save_png(face_chip, path + buffer + SAYI + ".png");  //saving is ok. no color problem

                //MONGO MONGO

                std::vector<uchar> buf;
                //std::vector<unsigned char> v;

                cv::Mat tmp_chip = dlib::toMat(face_chip);

                imencode(".jpeg", tmp_chip, buf);
`

Than I am inserting the mongodb as base64 encoded.

Prpblem is the converted face_chips  color palette 

Original:

<img width="300" alt="screen shot 2018-01-20 at 03 00 08" src="https://user-images.githubusercontent.com/17505439/35177197-aff6878e-fd8e-11e7-95c3-0cbbfe5a9cee.png">

after converted ::  

<img width="153" alt="screen shot 2018-01-20 at 03 00 36" src="https://user-images.githubusercontent.com/17505439/35177201-bbb72736-fd8e-11e7-9f87-4aba965df5b0.png">

any idea ? 

Best

**Comment by wangg** [comment]
It seems that you saved it and opened it as an RGB while OpenCV uses BGR by default? so switching the B and R channels should make it right. one way to do that is cv::cvtColor

**Comment by MyraBaba** [comment]
Thanks for your helpfull note.

`                cv::cvtColor(tmp_chip, tmp_chip,CV_BGR2RGB);
`



perfectly solved the problem.
