### ISSUE TITLE
Is there any way to speed up the dnn-mmod-face-detector?

### ISSUE THREAD

**Issue by yanchao12122** [davisking/dlib#1079]
the dnn face detector is so accurate and great, but it's too slow.
do you have any plan to improve the speed?

**Comment by davisking** [comment]
No, but if you run it with CUDA it's reasonably fast.  These kinds of DNN
models are always much slower than non-DNN models.  That's not to say I
couldn't design a specialized cascaded face detection model that's faster.
But doing that isn't high on my priority list.
