### ISSUE TITLE
Error vector of struct serialization

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1080]
Hi,

I have a struct:

`struct person {

    matrix<float, 0, 1 > face_descriptors;
    matrix<rgb_pixel> face_chips;
    string name;
};`

it gave below compilation errors:
`error: no matching function for call to 'serialize'
                serialize(item[i],out);
`

any idea ? maybe default serialization not supporting the struct type of vectors ?

**Comment by davisking** [comment]
Don't feel like I'm giving you a hard time, but you need to learn C++.  The best way to do this is to read a book on it. I highly recommend one of these here: http://dlib.net/books.html

But to help you out this time, you need to define a serialize function for your person struct.  C++ doesn't do it for you.  That's what the error is telling you.

**Comment by MyraBaba** [comment]
no such feelings Davis. 

Thanks a lot
