### ISSUE TITLE
kkmeans_ex error

### ISSUE THREAD

**Issue by cmlyldz** [davisking/dlib#1085]
DLib/dlib-18.14/examples/kkmeans_ex.cpp:149:46: note: 
      in instantiation of function template specialization
      'dlib::spectral_cluster<dlib::radial_basis_kernel<dlib::matrix<double, 2,
      1, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>
      >, std::__1::vector<dlib::matrix<double, 2, 1,
      dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>,
      std::__1::allocator<dlib::matrix<double, 2, 1,
      dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > >
      >' requested here
    std::vector<unsigned long> assignments = spectral_cluster(kernel_typ...
                                             ^
In file included from /Users/infodif/Desktop/changed codes/DLib/dlib-18.14/examples/kkmeans_ex.cpp:24:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:450:28: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 2 were provided
class _LIBCPP_TEMPLATE_VIS vector
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:450:28: note: 
      candidate constructor (the implicit default constructor) not viable:
      requires 0 arguments, but 2 were provided
2 errors generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/examples.build/Release/kkmeans_ex.build/Objects-normal/x86_64/kkmeans_ex.o kkmeans_ex.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

dlib version is 18.14 and cmake version is 3.10.2 and XQuartz-2.7.11
I am trying to build for iOS with following commands (in dlib-18.14/examples);
mkdir build
cd build
cmake -G Xcode ..
cmake --build . --config Release

**Comment by davisking** [comment]
That is an ancient version of dlib.  Get the new dlib v19.9.
