### ISSUE TITLE
Is there a good way to add a GUI progress report for HOG training

### ISSUE THREAD

**Issue by guenterneust** [davisking/dlib#1087]
Hi
I want to integrate HOG training into a GUI app.
It would be nice to have some sort of progress report, as the training takes a pretty long time for an interactive app.
But as far as I can see, the training function only writes to stdout.
One way I could imagine to do it is to make the training a separate process, pipe the output to the GUI app and parse it, but it's not very nice.

**Comment by davisking** [comment]
There is no hook for this.  You will have to edit the code to add whatever callback you want.
