### ISSUE TITLE
Dlib For ios arm64

### ISSUE THREAD

**Issue by cmlyldz** [davisking/dlib#1089]
I am using xcode 9 with dlib version 18.18.
When I try to detect faces it takes nearly 4 to 5 seconds.
Is there any way for faster detection on iOS devices (like cmake eneable AVX instructions).
When I building dlib I try to use -mfpu=neon but Xcode says its unused for arm64, and I also tried -mcpu=cortex-a9+fp  but there is no difference before and after mcpu instruction.

**Comment by cmlyldz** [comment]
By the way I tried with dlib 19.9 and its takin 8-9 seconds to detect face what can I do to improve this detection time.

**Comment by davisking** [comment]
Fill out the issue template.
