### ISSUE TITLE
Face Detector Is Too Slow On iOS device

### ISSUE THREAD

**Issue by cmlyldz** [davisking/dlib#1090]
Hello,

I build dlib 19.9 with cmake 3.10.1 for using in Xcode 9 using with Obj-C and with following C++ commands;
-lpthread 
-mcpu=cortex-a9+fp 
-mcpu=cortex-a9+simd 
-mcpu=cortex-a53+fp 
-mcpu=cortex-a53+simd 
-mcpu=cortex-a57+fp 
-mcpu=cortex-a57+simd
and DLIB_ENABLE_ASSERTS,
DLIB_ENABLE_STACK_TRACE,
DLIB_JPEG_SUPPORT
DLIB_NO_GUI_SUPPORT
DLIB_USE_BLAS
DLIB_USE_LAPACK

After Xcode project occurs I select iOS and arm64. Then build it for iOS.  At the last I use libdlib.a with my application.

and in the application I use following part of code
        NSDate *methodStart = [NSDate date];   ///timer
        std::vector<dlib::rect_detection> dets;
       detector(dlib::cv_image<unsigned char>(inputImageforFace), dets);
        NSDate *methodFinish00 = [NSDate date];
        NSTimeInterval executionTime00 = [methodFinish00 timeIntervalSinceDate:methodStart];
        NSLog(@"\nexecutionTime00 = %f", executionTime00);  ///timer

and the output is 6+ seconds.
after resizing my input images row: 352 and col: 288.

Is there any way to make it fast for this code part.

**Comment by davisking** [comment]
Don't put DLIB_ENABLE_ASSERTS or DLIB_ENABLE_STACK_TRACE.  Those make things slower, especially enabling asserts.  Additionally, you need to enable compiler optimizations for your code as well as dlib.  *dlib is mostly a template library* so the code you are interested in isn't even compiled into libdlib.a.  Turn on compiler optimizations in the rest of your application and it will be much faster.  Google how to use XCode if you don't know how to do that.
