### ISSUE TITLE
DLL failed:

### ISSUE THREAD

**Issue by kimgenegaby** [davisking/dlib#1094]
Compiler: msvc 14
OS: Windows 10     64bit

     After stating "using cuda" and compiled by using "python setup.py --yes DLIB_USE_CUDA" successfully and then executing "import dlib" in the python environment, the error message stated,"Import Error: DLL failed. The specified module could not be found."  This is 19.9 version. 
     When I typed in "python setup.up install --no DLIB_USE_CUDA", the problem had gone away.

Thanks.

**Comment by davisking** [comment]
When you install cudnn you have to put the cudnn dll files in your PATH.
That's why you are getting this error.  DLLs need to be in your path or
windows can't find them.

**Comment by kimgenegaby** [comment]
Hello DavisKing,

     I had been struggling to find this problem for a long time. After trial and error from window's environmental variables or modifying batch file finally did the trick, and now the GPU is processing the programs! Furthermore, the executions are much faster than CPU.

Thanks very much!

Steve
