### ISSUE TITLE
xml output data of the "Imglab" tool

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#1095]
Hello,

This is an example of the Imglab xml data:

`<box top='131' left='69' width='345' height='335'/>`

When I check it which the image, it seems the top-left is `(y, x)` not `(x, y)` and the rest is `height` and `width`, not `width` and then `height`. is that true?

I don't think it can affect the results, but I want to know if I am right.

**Comment by davisking** [comment]
I don't know what you mean.  When it says height=123 it really means the
height of the box is 123.  The same goes for the other fields.

**Comment by VanitarNordic** [comment]
The `top` value should be equal to `x` coordinate and `left` equal to `y` coordinate of the top-left point, isn't it? (top=x, left=y, ....)
if that is the case, the generated values of top-left are in reverse order, top=y and left=x.

**Comment by davisking** [comment]
No, the top is the top of the object.  The left number is the left of the object.  As is always the case, the Y axis goes up and down, the x axis goes left to right.  It's not backwards.
