### ISSUE TITLE
Face Recog-nition practices 

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1096]
Hi,

I would like to know the best way to 1-to-many face recognition ways, and it could be help to the others.
 Accuracy increasing & clustering / searching methods

- As we know **jittering** image increasing the accuracy . From your experience is it useful to add more pictures of the same persons and use them to calculate one ID like jitter calculation (mean)? 
 Or keep them separate and process jitter each of them and use them seperately. ?
What could be the other methods to increase accuracy and decrease false alarms?

- We have two different face database : 1 - 10.000 people  and 2 - 100.000 . All ID extracted with jittering image. To search 1-to-many what is the best way : 

  * check all **lenght(face_ID_1 - faceID_2)**  walk through all faces and take top few which least distance.
  * Or make a chineese clustering and ask him to make cluster for searched face.

  *any other suggestion..

Best 

_thanks again davis such a great library._
 _you have lifetime ticket from us for beer/wine/lunch :) if  you pass by .. as a friend._

**Comment by davisking** [comment]
Don't average a bunch of vectors from different images.  A better thing to
do is to use either k-nearest-neighbors or something like a linear SVM if
you want to take advantage of multiple images.  I wouldn't use chinese
whispers.

**Comment by MyraBaba** [comment]
If we have only one image per person that the is the  best option  to check  **lenght(face_ID_1 - faceID_2)** and find the (with sort) smallest distance ?

**Comment by davisking** [comment]
Generally speaking, yes.

**Comment by ksachdeva** [comment]
Hi Davis,

> Don't average a bunch of vectors from different images.  A better thing to
> do is to use either k-nearest-neighbors or something like a linear SVM if
> you want to take advantage of multiple images.
>  I wouldn't use chinese whispers.

Would appreciate if you could provide guidance/education on why Chinese Whisper should not be used.

I have a similar challenge i.e. doing 1-to-many match.

Regards & thanks
Kapil

**Comment by wyd1520** [comment]
@MyraBaba 将所有人人脸特征截入到内存里，然后再用
face_ID_1=xxx;
foreach item in cacheFeatures
    lenght(face_ID_1 - item)
花不了几毫秒
