### ISSUE TITLE
dnn mmod with varying aspect ratios of a similar object

### ISSUE THREAD

**Issue by Galisela** [davisking/dlib#1097]
Hi!
I am trying to implement the front and back car detector for traffic signs. The problem is that sometimes signs are facing the camera (with a square aspect ratio) and sometimes are seen from the side (as a rectangle).

Since I saw the detector is having a hard time training (and gave a recall of 0), and since it was hard to tell the limit of when a sign from the side is different enough to constitute a different class, I decided to just train a separate "side view" detector by just going through the xml file and adding ignore = '1' to each label that is closely a square.

I keep getting this message (with varying values for height and width, that as a side note do not actually exist in my xml label file):

"Warning, ignoring object.  We encountered a truth rectangle with a width and height of 171 and 166.  The image pyramid and sliding windows can't output a rectangle of this shape.  This is either because (1) the final layer's features have too large of a stride across the image, limiting the possible locations the sliding window can search or (2) because the rectangle's aspect ratio is too different from the best matching detection window, which has a width and height of 30 and 65."

Does this refer to the ignored boxes or is it another mistake I missed?

Thanks!

**Comment by davisking** [comment]
No, it's not talking about the boxes you marked as ignore.  The boxes you
mark as ignore just make parts of the image get ignored entirely by the
algorithm.  I don't know how to explain the problem any more simply than
what that error message says.  Read this:
http://blog.dlib.net/2017/08/vehicle-detection-with-dlib-195_27.html, and
think about how a scanning window detector has to work.

**Comment by Galisela** [comment]
Ooooh, apparently the algorithm was complaining about boxes with wrong aspect ratios in the test set which I forgot to adjust, (and also didn't think would have much effect on the training)

Thanks for taking the time to reply!

**Comment by davisking** [comment]
No problem.
