### ISSUE TITLE
Compile error at "Building CXX object CMakeFiles/dnn_mnist_ex.dir/dnn_mnist_ex.cpp.o"

### ISSUE THREAD

**Issue by ChanMinPark** [davisking/dlib#110]
Hello,

I hava a problem in compile process.
first, I use a Raspberry Pi 3. and I download source files of dlib from github(git clone).
and when I run 'cmake --build . --config Release', I meet a error below

=================================================================
Scanning dependencies of target dnn_mnist_ex
[ 60%] Building CXX object CMakeFiles/dnn_mnist_ex.dir/dnn_mnist_ex.cpp.o
In file included from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:12:0,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h: In instantiation of ‘void dlib::dnn_trainer<net_type, solver_type>::train(const std::vector<typename net_type::input_type>&, const std::vector<typename net_type::label_type>&) [with net_type = dlib::add_loss_layer<dlib::loss_multiclass_log_, dlib::add_layer<dlib::fc_<10ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::fc_<84ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::fc_<120ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::max_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::con_<16l, 5l, 5l, 1, 1, 2, 2>, dlib::add_layer<dlib::max_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::con_<6l, 5l, 5l, 1, 1, 2, 2>, dlib::input<dlib::matrix<unsigned char> >, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void> >; solver_type = dlib::sgd; typename net_type::input_type = dlib::matrix<unsigned char>; typename net_type::label_type = long unsigned int]’:
/home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:105:51:   required from here
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h:271:90: error: no matching function for call to ‘min(long unsigned int, std::vector<dlib::matrix<unsigned char> >::size_type)’
                               data.begin()+std::min(epoch_pos+mini_batch_size,data.size()),
                                                                                          ^
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h:271:90: note: candidates are:
In file included from /usr/include/c++/4.9/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.9/string:40,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/../algs.h:66,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix_exp.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/tensor.h:8,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:6,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/usr/include/c++/4.9/bits/stl_algobase.h:194:5: note: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:194:5: note:   template argument deduction/substitution failed:
In file included from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:12:0,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h:271:90: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::vector<dlib::matrix<unsigned char> >::size_type {aka unsigned int}’)
                               data.begin()+std::min(epoch_pos+mini_batch_size,data.size()),
                                                                                          ^
In file included from /usr/include/c++/4.9/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.9/string:40,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/../algs.h:66,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix_exp.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/tensor.h:8,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:6,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/usr/include/c++/4.9/bits/stl_algobase.h:240:5: note: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:240:5: note:   template argument deduction/substitution failed:
In file included from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:12:0,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h:271:90: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘std::vector<dlib::matrix<unsigned char> >::size_type {aka unsigned int}’)
                               data.begin()+std::min(epoch_pos+mini_batch_size,data.size()),
                                                                                          ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/../algs.h:79,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix_exp.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/tensor.h:8,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:6,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/usr/include/c++/4.9/bits/stl_algo.h:3439:5: note: template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3439:5: note:   template argument deduction/substitution failed:
In file included from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:12:0,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h:271:90: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long unsigned int’
                               data.begin()+std::min(epoch_pos+mini_batch_size,data.size()),
                                                                                          ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/../algs.h:79,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix_exp.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix/matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/../matrix.h:6,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn/tensor.h:8,
                 from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:6,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/usr/include/c++/4.9/bits/stl_algo.h:3444:5: note: template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3444:5: note:   template argument deduction/substitution failed:
In file included from /home/pi/Desktop/dlib/dlib/../dlib/dnn.h:12:0,
                 from /home/pi/Desktop/dlib/examples/dnn_mnist_ex.cpp:21:
/home/pi/Desktop/dlib/dlib/../dlib/dnn/trainer.h:271:90: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long unsigned int’
                               data.begin()+std::min(epoch_pos+mini_batch_size,data.size()),
                                                                                          ^
CMakeFiles/dnn_mnist_ex.dir/build.make:54: recipe for target 'CMakeFiles/dnn_mnist_ex.dir/dnn_mnist_ex.cpp.o' failed
make[2]: *** [CMakeFiles/dnn_mnist_ex.dir/dnn_mnist_ex.cpp.o] Error 1
CMakeFiles/Makefile2:480: recipe for target 'CMakeFiles/dnn_mnist_ex.dir/all' failed
make[1]: *** [CMakeFiles/dnn_mnist_ex.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: * * * [all] Error 2

=================================================================

**Comment by e-fominov** [comment]
This is the reason:

> ‘std::vector >::size_type {aka unsigned int}’

And it means that sizeof(unsigned long) > sizeof(size_t)

Fast and ugly solution can help to build this sample without changing library itself:
add this function before including dlib/dnn.h

```
namespace std{
    inline const unsigned long
    min(const unsigned long& __a, const size_t& __b)
    {
        if (__b < __a)
            return (const unsigned long)__b;
        return __a;
    }
}
```

Looks like trainer code should be changed to exclude this in a future

Other parts of library should work well. If you do not need DNN samples on rasberry Pi, you can build them expicitly:

`cmake --build . --target face_detection_ex`

**Comment by ChanMinPark** [comment]
Thank you so much~!!
I'll try :)

**Comment by e-fominov** [comment]
@davisking , do we need to change trainer to exclude this?

`data.begin()+std::min(epoch_pos+mini_batch_size,data.size())`

change to

`data.begin()+std::min(static_cast<size_t>(epoch_pos+mini_batch_size),data.size())`

**Comment by davisking** [comment]
We definitely should.  I just changed epoch_pos to be a size_t which should fix it.

**Comment by e-fominov** [comment]
is it safe to serialize/deserialize size_t type if platform change?

**Comment by davisking** [comment]
Yes.  The way integers are serialized is all the same regardless of the
underlying type.
