### ISSUE TITLE
"dlib.cnn_face_detection_model_v1(...)" problem with a custom trained weights

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#1102]
Hello,

I have trained a model using `dnn_mmod_ex` in C++ examples and the weights file was saved. I tested the `cnn_face_detector.py` with this weights but I get the following error on this:

`detect = dlib.cnn_face_detection_model_v1('weight.dat')`

```
RuntimeError: An error occurred while trying to read the first object from the file weights.dat.
ERROR: Wrong padding_y found while deserializing dlib::con_
```

I have compiled the `Dlib 19.9` python using `setup install`  in an Anaconda environment, with CUDA and CuDNN enabled on a Windows 10 machine. it compiled without any error.

Then tested it by this python script. What's the problem? it shows no problem when I use your trained weights, I mean `mmod_human_face_detector.dat`

**Comment by davisking** [comment]
You have to use the same network architecture as the face detection model.  You can't just load any arbitrary network.

**Comment by VanitarNordic** [comment]
one more thing, 
To get the maximum detection Fps on a video-stream (live or a video file), it is better that we test the Dlib model using C++ code, like examples?

**Comment by davisking** [comment]
It shouldn't matter.  I would use C++ though.

**Comment by lorenzob** [comment]
Is there currently any way to load a custom trained model from python (the one from dnn_mmod_ex for example)?

**Comment by davisking** [comment]
You can do so, but you have to use pybind11 to make a custom binding to python.  Which isn't hard to do.  Pybind11 is pretty great.
