### ISSUE TITLE
module 'dlib' has no attribute 'DLIB_USE_CUDA'

### ISSUE THREAD

**Issue by room3dev** [davisking/dlib#1103]
## Expected Behavior
using dlib.DLIB_USE_CUDA() to check if dlib is now using CUDA.

## Current Behavior
`AttributeError: module 'dlib' has no attribute 'DLIB_USE_CUDA'`

Dlib: 19.9.0 (git repository)
OS: Windows 7 / Visual Studio 14 2015 Win64
Python: 3.6.4 (Conda 4.3.33)
Install by: python setup.py install --yes USE_AVX_INSTRUCTIONS ('DLIB will use CUDA' is show up)

**Comment by davisking** [comment]
You don't have the new code from github.

**Comment by room3dev** [comment]
that's ok I'll wait.
