### ISSUE TITLE
anyone who encounter the erro when "python setup.py install" (dlib19.9)

### ISSUE THREAD

**Issue by caocao1989** [davisking/dlib#1105]
when "python setup.py install" (dlib19.9), what is the erro? anyone who can help me please
-- Building for: NMake Makefiles
CMake Error in CMakeLists.txt:
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by davisking** [comment]
Fill out the issue template.
