### ISSUE TITLE
test_dnn fails on mac os x with MKL

### ISSUE THREAD

**Issue by ramkakarala** [davisking/dlib#1109]
I built the unit tests on Mac OS X (10.13.2) High Sierra, with the Intel MKL. All the tests passed,  except one: 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEST FAILED: test_dnn !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Failure message from test: 

Error occurred at line 1797.
Error occurred in file /User/..../projects/dlib/dlib/dlib/test/dnn.cpp.
Failing expression was res.
Gradient error in parameter #160.  Relative error: -0.119709
expected derivative: -1.29617
output derivative:   -1.45133
iteration:           2

The same test passes on Ubuntu 14.04, without MKL.

The code block causing the error is 

      {
            print_spinner();
            fc_<4,FC_NO_BIAS> l;
            auto res = test_layer(l);
            DLIB_TEST_MSG(res, res);
        }

DLIB 19.9

-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   Found lapack, version 3.8.0
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found Intel MKL BLAS/LAPACK library
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Configuring done
-- Generating done

**Comment by davisking** [comment]
What happens if you try it on OS X without the MKL?

**Comment by ramkakarala** [comment]
Without MKL, I get a different test failure: 

Running test_global_optimization /                                             

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEST FAILED: test_global_optimization !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Failure message from test: 

Error occurred at line 213.
Error occurred in file /Users/../projects/dlib/test/dlib/dlib/test/global_optimization.cpp.
Failing expression was std::abs(result.y - 21.9210397) < 0.0001.
0.988774

---- cmake .. output


-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   Found lapack, version 3.8.0
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found LAPACK library
-- Found CBLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ramkakarala/projects/dlib/test/dlib/dlib/test/temp

**Comment by davisking** [comment]
That's a different issue, probably just that the test is not configured in
a reasonable enough way.  What happens if you change the
max_function_calls(300) to a bigger number like 400?

**Comment by davisking** [comment]
I just tried this on high sierra and got the same error.  It appears to be a problem with whatever BLAS library that's already in high sierra.  If you tell cmake to not use BLAS and LAPACK the error goes away.  It's unfortunately common for systems to have broken BLAS or LAPACK libraries :(.  I'm not really sure what I can do about this other than changing cmake to avoid linking to this version of BLAS and LAPACK.

**Comment by ramkakarala** [comment]
I tried LAPACK on High Sierra, with max_function_calls(400), and this test passed, as did all others. 

Out of curiosity, if dlib doesn't link to BLAS or LAPACK, and doesn't use MKL, what does it use?

**Comment by davisking** [comment]
It uses an internal implementation. The reason to link against another one is for speed.

Oddly, when I tried changing the number of calls to 400 on High Sierra I still got the same failure...

**Comment by davisking** [comment]
Also, I had to change from linking to libmkl_rt.dylib to
libmkl_intel_lp64.dylib, libmkl_sequential.dylib, and libmkl_core.dylib. If
I linked to libmkl_rt.dylib I was getting "Intel MKL FATAL ERROR: Cannot
load libmkl_intel_thread.dylib" at runtime. This is despite setting
LIBRARY_PATH and DYLD_LIBRARY_PATH to /opt/intel/mkl/lib, which I would
think would make the loader find it.

Did you have this issue when linking to the Intel MKL? I'm using the very
latest Intel MKL version, 2018.1.126.

**Comment by davisking** [comment]
Ah, never mind. This version of the MKL needs additional paths in DYLD_LIBRARY_PATH in addition to the one that contains the file it's complaining about `libmkl_intel_thread.dylib`.  Fun times.

I'm still irritated that the MLK causes that one test to fail.  I also note that if I just move that test to later in the file it passes.  That should definitely not matter.  There is no randomness or anything in that test function.  Might be a bug in the MLK, or how this version of the MLK requires client code to link to it.  Not sure.
