### ISSUE TITLE
I can't compile Python Interface...

### ISSUE THREAD

**Issue by ChanMinPark** [davisking/dlib#111]
When I run "sudo python setup.py install"
I got a error

I can't find solution..

===========================================================
Build using cmake ...
Scanning dependencies of target dlib
[  0%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.o
c++: error: unrecognized command line option â��-msse4â��
dlib_build/CMakeFiles/dlib.dir/build.make:54: recipe for target 'dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.o' failed
make[2]: *** [dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'dlib_build/CMakeFiles/dlib.dir/all' failed
make[1]: *** [dlib_build/CMakeFiles/dlib.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
error: cmake build failed!

===========================================================

**Comment by e-fominov** [comment]
Yes, dlib/tools/python/CMakeLists.txt has SSE4 support enabled by default

try 

`python setup.py install --no USE_SSE4_INSTRUCTIONS`

**Comment by ChanMinPark** [comment]
Oh My God!!
It works!!! Thank you~!!
You're my hero~ :D

**Comment by davisking** [comment]
What compiler and OS are you using?  I thought the SSE4 selection would always just work :(

**Comment by ChanMinPark** [comment]
I use gcc for compiler and RASPBIAN JESSIE for OS.

**Comment by davisking** [comment]
Oh, right, obviously that wouldn't work :)   I'll update the cmake files to
automatically do the right thing.

**Comment by davisking** [comment]
If you get the newest code and try it now it should automatically do the
right thing.

**Comment by ChanMinPark** [comment]
Wow~ That's nice !
Thank you so much :)
I'm happy to know the dlib!

**Comment by davisking** [comment]
No problem :)

**Comment by chdebezenac** [comment]
I am having trouble installing dlib. When running python setup.py install on macbook 10.10.5 I get the errors below. Any advice would be greatly appreciated.
Chris

MacBook-Pro-2:dlib chdebezenac$ python setup.py install
running install
running bdist_egg
running build
Detected Python architecture: 64bit
Detected platform: darwin
Removing build directory /Users/chdebezenac/pythonScript/dlib/./tools/python/build
Configuring cmake ...
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /Users/chdebezenac/anaconda/lib/libpython2.7.dylib (found suitable version "2.7.11", minimum required is "2.6")
-- USING BOOST_LIBS: /Users/chdebezenac/anaconda/lib/libboost_python.dylib
-- USING PYTHON_LIBS: /Users/chdebezenac/anaconda/lib/libpython2.7.dylib
-- Enabling SSE4 instructions
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.28")
-- Checking for module 'cblas'
--   Package 'cblas' not found
-- Checking for module 'lapack'
--   Package 'lapack' not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found Intel MKL BLAS/LAPACK library
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
-- *** Dlib CUDA support requires C++11 but your compiler doesn't support it. ***
-- Configuring done
-- Generating done
Build using cmake ...
Scanning dependencies of target dlib
[  0%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
[  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
[  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
[  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
[  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
[  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
[  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
[  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
[ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
[ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
[ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
[ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
[ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
[ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
[ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
[ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
[ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
[ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
[ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
[ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
[ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
[ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
[ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
[ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
[ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
[ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
[ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
[ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
[ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
[ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
[ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
[ 32%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
[ 33%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
[ 34%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
[ 35%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
In file included from /Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/fonts.cpp:14:
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:313:21: error: use of undeclared identifier 'XAllocColor'
                    XAllocColor(d, cmap, &xcol);
                    ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:319:36: error: use of undeclared identifier 'XmbTextExtents'; did you mean 'XTextExtents'?
                            return XmbTextExtents(fs, str, len, ink, logical);
                                   ^~~~~~~~~~~~~~
                                   XTextExtents
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:318:43: note: 'XTextExtents' declared here
                        inline static int XTextExtents (XFontSet fs, char *str, int len, XRectangle *ink, XRectangle *logical){
                                          ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:322:36: error: use of undeclared identifier 'XwcTextExtents'; did you mean 'XTextExtents'?
                            return XwcTextExtents(fs, str, len, ink, logical);
                                   ^~~~~~~~~~~~~~
                                   XTextExtents
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:321:43: note: 'XTextExtents' declared here
                        inline static int XTextExtents (XFontSet fs, wchar_t *str, int len, XRectangle *ink, XRectangle *logical){
                                          ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:325:29: error: use of undeclared identifier 'XmbDrawString'; did you mean 'XDrawString'?
                            XmbDrawString(d, w, fs, gc, x, y, str, num_bytes);
                            ^~~~~~~~~~~~~
                            XDrawString
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:324:44: note: 'XDrawString' declared here
                        inline static void XDrawString(Display *d, Window w, XFontSet fs, GC gc, int x, int y, char *str, int num_bytes){
                                           ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:328:29: error: use of undeclared identifier 'XwcDrawString'; did you mean 'XDrawString'?
                            XwcDrawString(d, w, fs, gc, x, y, str, num_bytes);
                            ^~~~~~~~~~~~~
                            XDrawString
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:327:44: note: 'XDrawString' declared here
                        inline static void XDrawString(Display *d, Window w, XFontSet fs, GC gc, int x, int y, wchar_t *str, int num_bytes){
                                           ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:334:29: error: use of undeclared identifier 'XOpenDisplay'
                        d = XOpenDisplay(NULL);
                            ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:337:33: error: use of undeclared identifier 'XOpenDisplay'
                            d = XOpenDisplay(":0.0");
                                ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:369:29: error: use of undeclared identifier 'XFreeFontSet'
                            XFreeFontSet(d, fs);
                            ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:371:30: error: use of undeclared identifier 'XCreateFontSet'
                        fs = XCreateFontSet(d, fontset, &mlist, &mcount, &def_str);
                             ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:376:34: error: use of undeclared identifier 'XExtentsOfFontSet'
                        extent = XExtentsOfFontSet(fs);
                                 ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:379:25: error: use of undeclared identifier 'XFreeStringList'; did you mean 'XwcFreeStringList'?
                        XFreeStringList(mlist);
                        ^~~~~~~~~~~~~~~
                        XwcFreeStringList
/Users/chdebezenac/anaconda/include/X11/Xutil.h:777:13: note: 'XwcFreeStringList' declared here
extern void XwcFreeStringList(
            ^
In file included from /Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/fonts.cpp:14:
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:379:41: error: cannot initialize a parameter of type 'wchar_t **' with an lvalue of type 'char **'
                        XFreeStringList(mlist);
                                        ^~~~~
/Users/chdebezenac/anaconda/include/X11/Xutil.h:781:1: note: passing argument to parameter here
);
^
In file included from /Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/fonts.cpp:14:
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:388:29: error: use of undeclared identifier 'XFreeGC'
                            XFreeGC(d, gc);
                            ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:389:29: error: use of undeclared identifier 'XFreePixmap'
                            XFreePixmap(d, pix);
                            ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:393:103: error: use of undeclared identifier 'XDefaultDepth'
                        pix = XCreatePixmap(d, DefaultRootWindow(d), pix_width_prev, pix_height_prev, XDefaultDepth(d, DefaultScreen(d)));
                                                                                                      ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:394:30: error: use of undeclared identifier 'XCreateGC'
                        gc = XCreateGC(d, pix, 0, NULL);
                             ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:398:21: error: use of undeclared identifier 'XSetForeground'
                    XSetForeground(d, gc, backcolor);
                    ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:399:21: error: use of undeclared identifier 'XSetBackground'
                    XSetBackground(d, gc, backcolor);
                    ^
/Users/chdebezenac/pythonScript/dlib/dlib/gui_widgets/nativefont.h:400:21: error: use of undeclared identifier 'XFillRectangle'
                    XFillRectangle(d, pix, gc, 0, 0, width, height);
                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
dlib_build/CMakeFiles/dlib.dir/build.make:998: recipe for target 'dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o' failed
error: cmake build failed!

**Comment by davisking** [comment]
You have a broken version of X11 somewhere on your machine.  Sometimes
anaconda contains bad versions of X11 headers.  You should use something
like XQuartz.

**Comment by chdebezenac** [comment]
Thanks… I have XQuartz on my machine but how do I get dlib to use it?

Chris

**Comment by davisking** [comment]
I don't know.  I've never had this kind of problem, but I know it happens
sometimes.  I would delete the offending copy of X11, wherever it is.

**Comment by XiaXuehai** [comment]
@chdebezenac I got the same problem which resulted from anaconda.you can install the cmake client,and configure the python path to your system python path,then generate.
typed `make ` in command line in your build file.Then it work.

**Comment by KentChun33333** [comment]
I found the exactly same problem as @chdebezenac  encountered. 
As the Error message, the main problem is caused by *gui* things. 
I solve the problem by add *--yes DLIB_NO_GUI_SUPPORT*

Thanks @davisking : )

**Comment by davisking** [comment]
lol. Definitely not those.   Delete the anaconda ones.  Not the system copy.

**Comment by dfsdsdwe** [comment]
I recently installed dlib on my raspberry pi3 and when i try and run example programmes i am getting the message:
'File "face-recognition.py", line 50, in <module
    import dlib
ImportError: dynamic module does not define init function (initdlib)'
any idea what is causing this? Thanks

**Comment by davisking** [comment]
face-recogition.py isn't part of dlib.  You should try running the dlib examples and follow the dlib instructions for building.
