### ISSUE TITLE
Question about shape predictor

### ISSUE THREAD

**Issue by buliginleo** [davisking/dlib#1111]
Hello! 

This is example from dataset for train face shape predictor (http://dlib.net/files/data/ibug_300W_large_face_landmark_dataset.tar.gz) :

How shape predictor can predict landmarks, if bounding box of face smaller than area of landmarks?

![screen shot 2018-02-06 at 12 19 08](https://user-images.githubusercontent.com/9847551/35851158-2b2a5d84-0b38-11e8-8bff-911d5150a106.png)

**Comment by davisking** [comment]
If you want to know how it works read the paper cited by the documentation. It explains how it works in great detail.
