### ISSUE TITLE
Training shape predictor on objects other than faces

### ISSUE THREAD

**Issue by Galisela** [davisking/dlib#1112]
Hello,

I have been trying to use the shape_predictor_trainer to refine my detection. However it requires that the object would have parts, which is not very applicable in my case. 

I was wondering how you trained the shape predictor for the vehicle detection (as I have noticed the xml's there have only boxes and no parts).

Thanks in advance for the answer and in general for all your work.

**Comment by davisking** [comment]
I used this https://github.com/davisking/dlib/blob/07a7995a274f45fb84f45223bd40887f0eae59be/dlib/image_processing/shape_predictor_trainer_abstract.h#L374 for that.  In general though, you have to define parts.  Define whatever parts make sense for your problem.

**Comment by Galisela** [comment]
Great! Thanks!
