### ISSUE TITLE
Compile-time sized matrices cause calls to dlib::fft_inplace to fail at compile time.

### ISSUE THREAD

**Issue by MDBrothers** [davisking/dlib#1113]
## Expected Behavior
This is an extract of code that should compile:
```
	dlib::matrix<std::complex<double>, 64, 64> myMatrix;
	dlib::fft_inplace(myMatrix);
```

## Current Behavior
It does not compile, the static assert failed is in matrix.h, ~l1275. That is the extent of the error message the compiler provides.
```
        T& operator() (
            long i
        ) 
        {
            // You can only use this operator on column vectors.
            COMPILE_TIME_ASSERT(NC == 1 || NC == 0 || NR == 1 || NR == 0);
```
I think the problem is in fft_inplace, here's the part I'm talking about:
```
        if (data.nr() == 1 || data.nc() == 1)
        {
            impl::twiddles<T> cs;
            impl::fft1d_inplace(data, false, cs);
        }
        else
        {
            impl::fft2d_inplace(data, false);
        }
```
Where the true branch is being compiled with the type of 'data' including compile time dimension information. That is because the .nr() and .nc() methods are not determined at compile time. I think this is the problem because if I just keep the code in the else clause and comment out the rest, the mwe compiles:
```
        //if (data.nr() == 1 || data.nc() == 1)
        //{
        //    impl::twiddles<T> cs;
        //    impl::fft1d_inplace(data, false, cs);
        //}
        //else
        {
            impl::fft2d_inplace(data, false);
        }
```
That is if I make the above change in fft_inplace, the code compiles. Obviously this isn't the fix. The fix is not obvious to me if the intention is to make fft_inplace compatible with compile-tile sized matrices. 

## Steps to Reproduce
throw this in a main method with the appropriate headers included:
```
	dlib::matrix<std::complex<double>, 64, 64> myMatrix;
	dlib::fft_inplace(myMatrix);

```
then try to compile it.

* **Version**:
DLIB_REVISION_H
DLIB_MAJOR_VERSION  19
DLIB_MINOR_VERSION  6
DLIB_PATCH_VERSION  99

* **Where did you get dlib**: this GitHub repo

* **Platform**: Windows 10 64bit

* **Compiler**:  MSVS 15 2017

**Comment by faboules** [comment]
dlib::matrix<std::complex<double>, 64, 64> myMatrix;
	dlib::fft_inplace(myMatrix);

**Comment by davisking** [comment]
Yeah, that's a bug. There just need to be overloads of fft_inplace() for
the different cases.  You should submit a PR for it :)

**Comment by davisking** [comment]
I just pushed a fix for this.  Thanks for reporting it :)
