### ISSUE TITLE
LIVE image detection with fullHD Quality

### ISSUE THREAD

**Issue by AvinashOB** [davisking/dlib#1115]
Currently we are able to install tracking.js and run it from laptop webcam.
moving ahead, we want to detect faces from longer distance (maybe 20 feet) assuming we have atleast 8 MP camera. The face detection image should have fullHD quality (1920 * 1080p)

In the existing scenario we are not able to exceed face detection beyond 3-4 feet and image detected (with 8 MP camera) is at very low quality. please suggest

Thank you.

**Comment by davisking** [comment]
I don't know what to tell you. Use a better camera?  I don't think this is a dlib related question.
