### ISSUE TITLE
more extra cmake options to configure different compiler

### ISSUE THREAD

**Issue by JensTimmerman** [davisking/dlib#1117]
At the moment it's not really easy to tell the python install script to use a compiler different then gcc,
I had to manually edit setup.py to set 

## Expected Behavior
```
python setup.py install --user-DCMAKE_C_COMPILER=/apps/gent/CO7/sandybridge/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icc -DCMAKE_CXX_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source' -DCMAKE_CXX_COMPILER=/apps/gent/CO7/sandybridge/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icpc -DCMAKE_C_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source' -DCMAKE_VERBOSE_MAKEFILE=ON
```
compiles dlib with icc and correct optimization flags

## Current Behavior
Arguments are ignored and CMake builds with gcc

## Steps to Reproduce
see above

## steps to fix:
manuelly edit setup.py and set 
`_cmake_extra_options=["-DCMAKE_C_COMPILER=/apps/gent/CO7/sandybridge/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icc", "-DCMAKE_CXX_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source'", "-DCMAKE_CXX_COMPILER=/apps/gent/CO7/sandybridge/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icpc", "-DCMAKE_C_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source'", "-DCMAKE_VERBOSE_MAKEFILE=ON"]`
 

* **Version**: latest master, ef811cbd8119738cc17ce15d043c3b137ffedbe0
* **Where did you get dlib** this github repo
* **Platform**
:LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core)
Release:	7.4.1708
Codename:	Core
* **Compiler**: icc 2017.1.132

**Comment by JensTimmerman** [comment]
actually it doesn't compile with correct optimization flags, since `-DUSE_AVX_INSTRUCTIONS=yes` is not set it overrides `-xHost` with `-msse4`, so I also had to set `-DUSE_AVX_INSTRUCTIONS=yes` in the end.

**Comment by faboules** [comment]
Yes

**Comment by davisking** [comment]
Please submit a PR with what you think fixes it.  Mabe add a new command line option to setup.py.

**Comment by faboules** [comment]
DUSE_AVX_INSTRUCTIONS=yes

**Comment by JensTimmerman** [comment]
@davisking I think I'm fine, Further digging into the documentation got me to http://dlib.net/compile.html
```
Alternatively, if you want to add more python bindings to dlib's python interface then you probably want to avoid the setup.py file and work directly using CMake. In particular, dlib's python API is built by the CMake project in the tools/python folder. You build this project using the usual CMake commands and when compiled it outputs the dlib shared library that defines the python API for dlib.
```

Which is the route I'm going to take. 
you could change the wording to
```
Alternatively, if you want more control over the build process, or to add more python bindings to dlib's python interface then you probably want to avoid the setup.py file and work directly using CMake. In particular, dlib's python API is built by the CMake project in the tools/python folder. You build this project using the usual CMake commands and when compiled it outputs the dlib shared library that defines the python API for dlib.
```

**Comment by JensTimmerman** [comment]
oh, but the issue with the cmake file still adding -msse4 eveywhere should be fixed, I'll look into that

**Comment by JensTimmerman** [comment]
I found the culprit
https://github.com/davisking/dlib/commit/fbd117804758bd9174a27ce471acfe21b8bfc208

Is there any reason to have this there? I image most people who build this from source have avx by now? And the documentation everywhere states what to do.

Having this definition there overwrites anything I set (e.g. `-xHost` which I recommend when using intel) or even setting `-DUSE_AVX_INSTRUCTIONS=yes`

You should probably replicate the code from
https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L47
into https://github.com/davisking/dlib/blob/master/tools/python/CMakeLists.txt

**Comment by davisking** [comment]
People don't read documentation.  set_compiler_specific_options.cmake is already in effect for the python scripts.  Anyway, I set that because people don't read directions and complain that dlib is slow.  Like all the time.  I even get people, regularly, who will post the output of an error message that literally tells them what to type and they are like "I can't figure it out, what do I type?", I then paste the error back to them, the one they sent me, and they go "oh, I couldn't find that information!".

Anyway. A better solution would be to improve set_compiler_specific_options.cmake so that it automatically enabled SSE4 or AVX when it was appropriate to do so.  Like via some check that the target architecture supported those instructions sets. Then the default could be ON for those options, if they really are available.  Then that hard coded statement in https://github.com/davisking/dlib/blob/master/tools/python/CMakeLists.txt could be removed.

But whatever you do, it can't assume people will read instructions because most of them won't. :(

**Comment by JensTimmerman** [comment]
But that turns of avx and turns on sse4... avx is faster then sse4, so you're making dlib slower.

AVX started shipping in 2011, I don't imagine a lot of people don't have it? So why turn it off by default?

Maybe you could inverse the logic so sse4 is only used when `-DUSE_AVX_INSTRUCTIONS=yes` is not set? Now it always overrides AVX instructions...

Maybe you could reverse the logic so that only get's used when`  -DUSE_AVX_INSTRUCTIONS=yes`

**Comment by davisking** [comment]
It doesn't overwrite AVX.

**Comment by JensTimmerman** [comment]
Yes it does, that's the whole issue.

https://github.com/davisking/dlib/blob/fbd117804758bd9174a27ce471acfe21b8bfc208/tools/python/CMakeLists.txt#L5 sets `USE_SSE4_INSTRUCTIONS` to `ON`

but it has no options to parse e.g. what needs to happen on `-DUSE_AVX_INSTRUCTIONS`
This happens in https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L47
but this file is not relevant when building in `tools/python/`


and even when using the functions defined in 
This happens in https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L47

These do an `append` of -msse4 or `-mavx` so when I set `-xHost` (which compiles to all features known on the current host) this is ignored, because -mavx is appended, and intel listens to the last option given, so mavx wins, even thought xHost is set.

This makes it impossible to build a fast dlib for me on intel systems...

**Comment by JensTimmerman** [comment]
@davisking if you want to target architecture buidling on, with intel compiler family: use `-xHost`, with gcc use `-march`

no need to detect if avx or sse2 is on these cpu's, the processor will do the detecting for you...

**Comment by JensTimmerman** [comment]
@davisking if you want to target architecture of the current machine you are building on, with intel compiler family: use -xHost, with gcc use -march=native

no need to detect if avx or sse2 is on these cpu's, the compiler will do the detecting for you...
see https://www.osc.edu/book/export/html/3729

**Comment by davisking** [comment]
I don't understand what you are on about.  For example, run these commands:

```
dlib/tools/python/build$ cmake .. -DUSE_AVX_INSTRUCTIONS=1
make VERBOSE=1
```

The output shows it using -mavx.

**Comment by JensTimmerman** [comment]
@davisking I'm talking about when compiling with intel compiler

```
cmake -DUSE_AVX_INSTRUCTIONS=yes -DCMAKE_CXX_COMPILER='/apps/gent/CO7/sandybridge/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icpc' -DCMAKE_CXX_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source'
make VERBOSE=1
<snip>
cd /user/scratch/gent/gvo000/gvo00002/vsc40485/dlib/tools/python/dlib_build && /apps/gent/CO7/sandybridge/software/icc/2017.1.132-GCC-6.3.0-2.27/compilers_and_libraries_2017.1.132/linux/bin/intel64/icpc   -DDLIB_JPEG_STATIC -DDLIB_NO_ABORT_ON_2ND_FATAL_ERROR -O3 -DNDEBUG -fPIC   -DDLIB_JPEG_SUPPORT -DDLIB_USE_BLAS -DDLIB_USE_LAPACK -DDLIB_PNG_SUPPORT -DLAPACK_FORCE_UNDERSCORE -msse4 -o CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o -c /user/scratch/gent/gvo000/gvo00002/vsc40485/dlib/dlib/bigint/bigint_kernel_1.cpp
<snip>
```

This doesn't seem to fail when I don't set `-DCMAKE_CXX_FLAGS`
or set `-DUSE_AVX_INSTRUCTIONS=1` at the end. In that case it does set `-mavx` but I really want to compile with `-xHOST` on intel and `-march=native` on gcc, because these cpus have avx2, and it would be a shame not to use that.

**Comment by davisking** [comment]
Ok, submit a PR.
