### ISSUE TITLE
Dlib OpenCV - Showing Empty Frame

### ISSUE THREAD

**Issue by guruvishnuvardan** [davisking/dlib#1118]
![dlib code](https://user-images.githubusercontent.com/31349523/36060254-dbf33bdc-0e6b-11e8-91c6-d32f937d5aee.png)

Hi Davis, I have already trained the images and detector.svm is ready, when I am trying execute detect.py, I get only empty frame and it takes more than a minute to show the empty frame, Can you please suggest, If something had gone wrong. 

I have also attached my code
![empty frame](https://user-images.githubusercontent.com/31349523/36060244-9dfb6318-0e6b-11e8-8550-b6c28c9348e7.png)

**Comment by davisking** [comment]
This is an opencv problem, not a dlib issue.
