### ISSUE TITLE
Any dlib related js file for client side face recognition?

### ISSUE THREAD

**Issue by vijaysagi** [davisking/dlib#1119]
Hi,

currently we are using **dlib_face_recognition_resnet_model_v1.dat** to extract face descriptor values which is used for face recognition.

Could  you pls suggest relavant javascript  framework by which i can extract face descriptor values from the  **dlib_face_recognition_resnet_model_v1.dat**  file.

Thanks

**Comment by davisking** [comment]
I don't use js so I can't say.
