### ISSUE TITLE
Error "ImportError: libboost_python.so.1.60.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by ChanMinPark** [davisking/dlib#112]
Hello,

When I run a command [python -c "import dlib"], I got a error message below.

========================
pi@raspberrypi:~/Desktop/dlib $ python -c "import dlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dlib-18.18.0-py2.7-linux-armv7l.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: libboost_python.so.1.60.0: cannot open shared object file: No such file or directory

========================

But, If I run a command [LD_LIBRARY_PATH="/usr/local/lib" python -c "import dlib"], there is no error.

So, I think that there is a problem about library path.
Is this dlib setting problem or my system problem?

If you know the solution, how can i fix this?
I use raspberry pi 3  and OS is Raspbian Jessie.

please help me... Thank you.

**Comment by davisking** [comment]
This is not a dlib problem.  You just need to add /usr/local/lib to your LD_LIBRARY_PATH.

**Comment by ChanMinPark** [comment]
@davisking 
Okay, Thank you~  :)
