### ISSUE TITLE
train multi-class object detector.

### ISSUE THREAD

**Issue by ahmdrz** [davisking/dlib#1120]
Hi , How can I train multi-class object detector in python using `simple_object_detector_training_options` ?
I've just labeled classes with `imglab` but I don't know how to train and get label from detected object.

**Comment by davisking** [comment]
Train one detector for each class.

**Comment by ahmdrz** [comment]
I think it will increase processing time. Is it true ?

On Feb 10, 2018 22:14, "Davis E. King" <notifications@github.com> wrote:
Train one detector for each class.

**Comment by davisking** [comment]
No, not if you run them like this: https://github.com/davisking/dlib/blob/master/python_examples/train_object_detector.py#L134

**Comment by ahmdrz** [comment]
Thank you

**Comment by davisking** [comment]
No problem.
