### ISSUE TITLE
Acceleration using Intel Movidius?

### ISSUE THREAD

**Issue by petri** [davisking/dlib#1121]
First, thank you for your efforts on dlib. This is just awesome software. With almost no background, I was able to learn the ropes, collect training data and develop a sufficient-quality feature counter (Python) app on my Macbook, such that it is actually usable in a real-life project, all in one long evening! If only all sw was as smooth to install and use... 

The question: Intel is shipping a < 100$ USB stick to accelerate machine learning apps via custom hw on the stick. It supports TensorFlow and Caffe at least on Ubuntu & Raspberry PI.

See https://movidius.github.io/ncsdk/

Is there any sensible way to benefit from that device with dtlib?

**Comment by davisking** [comment]
Thanks, glad you like dlib.

I haven't heard of that sdk and haven't setup anything in dlib to use it.
I'm sure it could be done though but I doubt it will just work out of the
box.

Are you even using deep learning? None of dlib's deep learning training
interfaces are in python.

**Comment by petri** [comment]
Ok thanks. I'm using the HOG detector.

**Comment by davisking** [comment]
Ok, then that intel thing is unrelated. Just make sure you turn on compiler
optimizations and AVX instructions and you will be fine.

**Comment by vrushang25** [comment]
I want to increase processing power of Raspberry pi what should I do?
Because if I start video stream from CCTV camera my Raspberry pi is not able to handle to it and program terminates
