### ISSUE TITLE
plate detection

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1124]
Hi,

Is it a good idea to use dlib for vehicle plate detection and recognition like openalpr ? Is there anybody has experience ? What could be the best starting point if advised?

Best

**Comment by davisking** [comment]
Is there a paper that describes that kind of technique?

**Comment by MyraBaba** [comment]
This is what I found : 
Adversarial Generation of Training Examples: Applications to Moving Vehicle License Plate Recognition


https://arxiv.org/pdf/1707.03124.pdf

**Comment by davisking** [comment]
I think this isn't a great idea. You would be better off training a normal
detector to find license plates, or using a non-ML based text detector like
maximally stable extremal regions or the stroke width transform.

**Comment by edubois** [comment]
I would generate fake examples by means of the GAN, and insert true / false examples from another labelized set when training the discriminator. This semi supervised method would give you more examples. But making a GAN is a bit tricky.

**Comment by edubois** [comment]
We'd love to have a Conditionnal GAN in a future release of dlib :)

**Comment by MyraBaba** [comment]
I will test with normal detector and let you know the results.

**Comment by AKSHAYUBHAT** [comment]
The visual genome dataset contains few hundred images with bounding box for license plates.
