### ISSUE TITLE
Dlib installation error in Linux server

### ISSUE THREAD

**Issue by zmuhsin** [davisking/dlib#1125]
Hi
 I followed the link: (https://www.learnopencv.com/install-dlib-on-ubuntu/ )
 to install dlib on a Linux server using Dlib ver 19.9. 
I've got some errors that can be imaged in the following installation log. 
Your help in resolving this problem would be greatly appreciated - many thanks, 

(mylashve) 17:15 ~/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build (master)$ cmake ..                                                  
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found LAPACK library
-- Found ATLAS BLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - not found
-- Looking for sgesv_
-- Looking for sgesv_ - not found
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mylash/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build
Scanning dependencies of target dlib
[  0%] Building CXX object dlib/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
[  1%] Building CXX object dlib/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
[  2%] Building CXX object dlib/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
[  3%] Building CXX object dlib/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
[  4%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
[  5%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
[  6%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
[  7%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
[  8%] Building CXX object dlib/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
[  8%] Building CXX object dlib/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
[  9%] Building CXX object dlib/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
[ 10%] Building CXX object dlib/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
[ 11%] Building CXX object dlib/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
12%] Building CXX object dlib/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
[ 13%] Building CXX object dlib/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
[ 14%] Building CXX object dlib/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
[ 15%] Building CXX object dlib/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
[ 16%] Building CXX object dlib/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
[ 16%] Building CXX object dlib/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
[ 17%] Building CXX object dlib/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
[ 18%] Building CXX object dlib/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
[ 19%] Building CXX object dlib/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
[ 20%] Building CXX object dlib/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
[ 21%] Building CXX object dlib/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
[ 22%] Building CXX object dlib/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
[ 23%] Building CXX object dlib/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
[ 24%] Building CXX object dlib/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
13%] Building CXX object dlib/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
[ 14%] Building CXX object dlib/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
[ 15%] Building CXX object dlib/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
[ 16%] Building CXX object dlib/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
[ 16%] Building CXX object dlib/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
[ 17%] Building CXX object dlib/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
[ 18%] Building CXX object dlib/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
[ 19%] Building CXX object dlib/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
[ 20%] Building CXX object dlib/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
[ 21%] Building CXX object dlib/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
[ 22%] Building CXX object dlib/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
[ 23%] Building CXX object dlib/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
[ 24%] Building CXX object dlib/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
[ 25%] Building CXX object dlib/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
[ 25%] Building CXX object dlib/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
[ 26%] Building CXX object dlib/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
[ 27%] Building CXX object dlib/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
[ 28%] Building CXX object dlib/CMakeFiles/dlib.dir/server/server_http.cpp.o
[ 29%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
[ 30%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
[ 31%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
[ 32%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
[ 33%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
[ 33%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
[ 34%] Building CXX object dlib/CMakeFiles/dlib.dir/threads/async.cpp.o
[ 35%] Building CXX object dlib/CMakeFiles/dlib.dir/timer/timer.cpp.o
[ 36%] Building CXX object dlib/CMakeFiles/dlib.dir/stack_trace.cpp.o
[ 37%] Building CXX object dlib/CMakeFiles/dlib.dir/dnn/cpu_dlib.cpp.o
[ 38%] Building CXX object dlib/CMakeFiles/dlib.dir/dnn/tensor_tools.cpp.o
[ 39%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
[ 40%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_widgets/widgets.cpp.o
[ 41%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_widgets/drawable.cpp.o
[ 41%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.cpp.o
[ 42%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_widgets/style.cpp.o
[ 43%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_widgets/base_widgets.cpp.o
[44%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.cpp.o
[ 45%] Building CXX object dlib/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.cpp.o
[ 46%] Building CXX object dlib/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
[ 47%] Building CXX object dlib/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
[ 48%] Building CXX object dlib/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
[ 49%] Building CXX object dlib/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
[ 50%] Linking CXX static library libdlib.a
[ 50%] Built target dlib
Scanning dependencies of target dlib_shared
[ 50%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/base64/base64_kernel_1.cpp.o
[ 51%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/bigint/bigint_kernel_1.cpp.o
[ 52%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/bigint/bigint_kernel_2.cpp.o
[ 53%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/bit_stream/bit_stream_kernel_1.cpp.o
[ 54%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
[ 55%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
[ 56%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
[ 57%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
[ 58%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/md5/md5_kernel_1.cpp.o
[ 58%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/tokenizer/tokenizer_kernel_1.cpp.o
[ 59%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/unicode/unicode.cpp.o
[ 60%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/data_io/image_dataset_metadata.cpp.o
[ 61%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/data_io/mnist.cpp.o
[62%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/global_optimization/global_function_search.cpp.o
[ 63%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/sockets/sockets_kernel_1.cpp.o
[ 64%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/bsp/bsp.cpp.o
[ 65%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dir_nav/dir_nav_kernel_1.cpp.o
[ 66%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dir_nav/dir_nav_kernel_2.cpp.o
[ 66%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dir_nav/dir_nav_extensions.cpp.o
[ 67%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/linker/linker_kernel_1.cpp.o
[ 68%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/logger/extra_logger_headers.cpp.o
[ 69%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/logger/logger_kernel_1.cpp.o
70%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/logger/logger_config_file.cpp.o
[ 71%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/misc_api/misc_api_kernel_1.cpp.o
[ 72%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/misc_api/misc_api_kernel_2.cpp.o
[ 73%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/sockets/sockets_extensions.cpp.o
[ 74%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/sockets/sockets_kernel_2.cpp.o
[ 75%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/sockstreambuf/sockstreambuf.cpp.o
[ 75%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
[ 76%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/server/server_kernel.cpp.o
[ 77%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/server/server_iostream.cpp.o
[ 78%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/server/server_http.cpp.o
[ 79%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/multithreaded_object_extension.cpp.o
80%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/threaded_object_extension.cpp.o
[ 81%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/threads_kernel_1.cpp.o
[ 82%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/threads_kernel_2.cpp.o
[ 83%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/threads_kernel_shared.cpp.o
[ 83%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/thread_pool_extension.cpp.o
[ 84%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/threads/async.cpp.o
[ 85%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/timer/timer.cpp.o
[ 86%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/stack_trace.cpp.o
[ 87%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dnn/cpu_dlib.cpp.o
[ 88%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dnn/tensor_tools.cpp.o
[ 89%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_widgets/fonts.cpp.o
[ 90%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_widgets/widgets.cpp.o
 91%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_widgets/drawable.cpp.o
[ 91%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_widgets/canvas_drawing.cpp.o
[ 92%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_widgets/style.cpp.o
[ 93%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_widgets/base_widgets.cpp.o
[ 94%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_core/gui_core_kernel_1.cpp.o
[ 95%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/gui_core/gui_core_kernel_2.cpp.o
[ 96%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/image_loader/png_loader.cpp.o
[ 97%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/image_saver/save_png.cpp.o
[ 98%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/image_loader/jpeg_loader.cpp.o
[ 99%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/image_saver/save_jpeg.cpp.o
[100%] Linking CXX shared library libdlib.so
[100%] Built target dlib_shared
(mylashve) 17:25 ~/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build (master)$ 
(mylashve) 17:25 ~/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build (master)$ make install                                              
[ 50%] Built target dlib
[100%] Built target dlib_shared
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libdlib.a
CMake Error at dlib/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/mylash/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build/dlib/libdlib.a"
  to "/usr/local/lib/libdlib.a".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
make: *** [install] Error 1
(mylashve) 17:26 ~/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build (master)$ cd /home/mylash/.virtualenvs/mylashve/lib/python3.6/site-packages
(mylashve) 17:30 ~/.virtualenvs/mylashve/lib/python3.6/site-packages $ cd /home/mylash/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/
(mylashve) 17:30 ~/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib (master)$ python setup.py install
running install
running bdist_egg
running egg_info
creating dlib.egg-info
writing dlib.egg-info/PKG-INFO
writing dependency_links to dlib.egg-info/dependency_links.txt
writing top-level names to dlib.egg-info/top_level.txt
writing manifest file 'dlib.egg-info/SOURCES.txt'
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
error: [Errno 38] Function not implemented

**Comment by davisking** [comment]
Read the error message in your post. It tells you the problem.  Look for the word error.

**Comment by zmuhsin** [comment]
I read the errors but I don't know how to fix them. For example the following error: 
python setup.py install
package init file 'dlib/init.py' not found (or not a regular file)
I spent hours trying to fix it but no luck. could you please help me to get around this problem.
Thank you

**Comment by davisking** [comment]
> -- Installing: /usr/local/lib/libdlib.a
> CMake Error at dlib/cmake_install.cmake:41 (file):
> file INSTALL **cannot copy file
> "/home/mylash/.virtualenvs/mylashve/lib/python3.6/site-packages/dlib/build/dlib/libdlib.a"
> to "/usr/local/lib/libdlib.a".**
> Call Stack (most recent call first):

You don't have write access to /usr/local/lib.  Run the command with sudo or as root.

**Comment by zmuhsin** [comment]
That's great! Many thanks.

**Comment by zmuhsin** [comment]
Hi again
I've checked with the current web hosting provider as well as others - unfortunately, they do not allow for root access to run the command with sudo or as root! Any idea how to get around this problem? Do you know any web-host provider that supports dlib installation? 
Many thanks.

**Comment by davisking** [comment]
Google setup.py --user.  Yes, you can do this. It's got nothing to do with dlib.  You just have to tell setup.py where you want to install.  This is a general python install thing.
