### ISSUE TITLE
set_dnn_prefer_smallest_algorithms() in Python

### ISSUE THREAD

**Issue by HarveyBrezinaConniffe** [davisking/dlib#1126]
Long story short, My program crashes when I try to use the CNN face detector, Saying its out of memory( Even though my images are way smaller then the amount of memory in my GPUs, 4GB ). After reading other issues it seems that CUDA is selecting larger architectures, And I should run set_dnn_prefer_smallest_algorithms(). I cant seem to find that method in Python, Is there any way to call it from Python or will I have to use C++?

**Comment by davisking** [comment]
A binding for python needs to be added.  You should add one and submit a PR
:)

**Comment by HarveyBrezinaConniffe** [comment]
Thanks for the quick reply! I'm not too familiar with bindings but will give it a try!

**Comment by HarveyBrezinaConniffe** [comment]
For future reference, I have added a python binding for set_dnn_prefer_smallest_algorithms() and it fixed the problems I was having!
