### ISSUE TITLE
VS 2017 recursive type or function dependency context too complex

### ISSUE THREAD

**Issue by azmathmoosa** [davisking/dlib#1129]
Hi, I am trying to implement the FaceAlignmentNetwork given [here](https://github.com/1adrianb/face-alignment/blob/master/face_alignment/models.py) as FAN module.

However, VS 2017 fails to compile saying 

> C1202 recursive type or function dependency context too complex 

and it points to line 599 in core.h        
>  typedef typename subnet_type::input_type input_type;`

My DNN template is as follows:
```
template <
	long num_filters,
	long nr,
	long nc,
	int stride_y,
	int stride_x,
	int pad_y,
	int pad_x,
	typename SUBNET
>
using conp = add_layer<con_<num_filters, nr, nc, stride_y, stride_x, pad_y, pad_x>, SUBNET>;
template <
	int nFilters,
	typename SUBNET
>
using conv3x3 = conp<nFilters, 3, 3, 1, 1, 1, 1, SUBNET>;
template <
	int nFilters,
	typename SUBNET
>
using conv1x1 = conp<nFilters, 1, 1, 1, 1, 0, 0, SUBNET>; //bias=False in pytorch
template <
	int nFilters,
	typename SUBNET
>
using convBlock = concat3<tag1, tag2, tag3, 
	tag3<conv3x3<nFilters/4, relu<bn_con<
	tag2<conv3x3<nFilters/4, relu<bn_con<
	tag1<conv3x3<nFilters/2, relu<bn_con<SUBNET>>>>>>>>>>>>>;
template <
	typename SUBNET
>
using hglow = convBlock<256, avg_pool<2, 2, 2, 2, SUBNET>>;
template <
	typename SUBNET
>
using hglowup = upsample<2,convBlock<256, SUBNET>>;
template <
	typename SUBNET
>
using hgup = convBlock<256, SUBNET>;
template <
	typename SUBNET
>
using hourglass = add_prev8<hgup<skip1<			\
	tag8<convBlock<256,add_prev7<hgup<skip2<	\
	tag7<convBlock<256,add_prev6<hgup<skip3<	\
	tag6<convBlock<256,add_prev5<hgup<skip4<	\
	tag5<hglowup<convBlock<256, hglow<			\
	tag4<hglow<									\
	tag3<hglow<									\
	tag2<hglow<									\
	tag1<SUBNET									\
	>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
template <
	typename SUBNET
>
using preprocess = convBlock<256, 
	convBlock<128, avg_pool<2,2,2,2,
	convBlock<128, relu<bn_con<
	conp<64, 7, 7, 2, 2, 3, 3, SUBNET>>>>>>>;
template <
	typename SUBNET
>
using hgstack = relu<bn_con<conv1x1<256, convBlock<256, hourglass<SUBNET>>>>>;
template <
	typename SUBNET
>
using lin = conv1x1<68, SUBNET>;
using faNet = loss_mean_squared_multioutput<fc<136, \
	lin<concat3<tag4, tag8, tag9, tag9<lin<hgstack<	\
	add_prev5<add_prev7<conv1x1<256,				\
	tag8<lin<skip6<									\
	tag7<convBlock<256,								\
	tag6<hgstack<									\
	tag5<add_prev1<add_prev3<conv1x1<256,			\
	tag4<lin<skip2<									\
	tag3<convBlock<256,								\
	tag2<hgstack<preprocess<						\
	tag1<input_rgb_image>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
```
Is there anything I can do to make this compile?  I've seen examples with ResNets.  This should be possible.  What can I do to make this work?  I'll be grateful for your time.

Dlib Version: 19.8
Dlib source: GitHub tagged v19.8
OS/Env: Win 10, VS 2017 64-bit MSBuild Compiler, v141 Toolset, x64 Host.

**Comment by davisking** [comment]
No idea.  Maybe you found a new bug in visual studio.  Make sure you have the very latest version of visual studio. They release updates to it all the time.  If you haven't downloaded an update for visual studio in the last month you should probably update.  Also get the newest dlib.

**Comment by azmathmoosa** [comment]
I think the error is indeed what it says it is.  I got rid of half of the network and it compiles.
```
using faNet = loss_mean_squared_multioutput<fc<136, \
	conv1x1<1,add_prev4<add_prev1<add_prev3<conv1x1<256,			\
	tag4<lin<skip2<									\
	tag3<convBlock<256,								\
	tag2<hgstack<preprocess<						\
	tag1<input_rgb_image>>>>>>>>>>>>>>>>;
```
I will try with updated dlib.  But VS 2017 version is latest.  15.5.  I looked up and it seems there is a template recursion limit of 2048 in VS compilers.   Is there a way for me to define my network within that limit? or was templating for DNNs a bad idea... 


Thanks for the excellent library!

**Comment by davisking** [comment]
You can use the repeat layer to sidestep some of this since repeat doesn't instantiate the template it repeats in the context of the overall network.  So using repeat will probably make it work fine.  Or if you switch to gcc or clang it should work fine as well.  Visual Studio isn't that great of a compiler.  Just a few months ago it couldn't compile the dlib DNN code at all or would take hours to compile other parts of it when gcc only took seconds.
