### ISSUE TITLE
fatal error LNK1104: cannot open file 'MSVCRTD.lib' when building CompilerIdC and CompilerIdCXX

### ISSUE THREAD

**Issue by leftler** [davisking/dlib#1130]
I am attempting to run `python setup.py install --yes USE_AVX_INSTRUCTIONS`, When I do I get the following output

> subprocess.CalledProcessError: Command '['cmake', 'D:\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\dlib\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\Scott\\AppData\\Local\\Programs\\Python\\Python36\\python.exe', '-DUSE_AVX_INSTRUCTIONS=yes', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=D:\\dlib\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

Checking CMakeError.log gives the error 

> Link:
  D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'MSVCRTD.lib' [D:\dlib\build\temp.win-amd64-3.6\Release\CMakeFiles\3.6.2\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "D:\dlib\build\temp.win-amd64-3.6\Release\CMakeFiles\3.6.2\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

## Expected Behavior
I expected the compile to complete sucessfully

## Current Behavior
[console output.txt](https://github.com/davisking/dlib/files/1722888/console.output.txt)
[CMakeError.log](https://github.com/davisking/dlib/files/1722890/CMakeError.log)
[CMakeOutput.log](https://github.com/davisking/dlib/files/1722891/CMakeOutput.log)

## Steps to Reproduce
* Open the "x64 Native Tools Command Prompt for VS 2017" command prompt.
* Run the following commands
```
C:\Users\Scott\Source>D:
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cd\
D:\>git clone https://github.com/davisking/dlib.git
D:\>cd dlib
D:\dlib>python setup.py install --yes USE_AVX_INSTRUCTIONS
```

* **Version**: ca1c7af
* **Where did you get dlib**: Github
* **Platform**: Windows 10 Enterprise - 64 bit - Version 1709
* **Compiler**: Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64
* **Linker**: Microsoft (R) Incremental Linker Version 14.12.25835.0

I likely have something simply set up stupid in my environment that is causing this to not work, I am primarally a .NET developer so compiling native apps is a little new to me. [Here is a copy of the environment variables that are set in the command window](https://github.com/davisking/dlib/files/1722909/EnvVars.txt)

**Comment by davisking** [comment]
There must be something wrong with your visual studio install. It should
come with that file. Maybe you need to reinstall it, I have no idea.

**Comment by leftler** [comment]
`D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\lib\x64\msvcrtd.lib` exists, and that folder it is in is included in both LIB and LIBPATH. I will go for a uninstall and reinstall of VS.

**Comment by leftler** [comment]
When I reinstall Visual Studio, do you know besides the basic "Desktop C++" development roll what other features should I be enabling in the installer? I just want to make sure all the components I need are installed.

**Comment by davisking** [comment]
The visual c++ option should be all you need.

**Comment by leftler** [comment]
Uninstalling Visual Studio Community and re-installing as Visual Studio Enterprise on the C: drive did not fix it, same link error.

**Comment by davisking** [comment]
No idea. This isn't a dlib issue, but rather some problem with visual studio in general. You probably can't compile any programs at all with the compiler in this state since that file it's complaining about is part of visual studio's core runtime.

**Comment by leftler** [comment]
Installing 2015 and using it's x64 console, ill' see if that works.

**Comment by leftler** [comment]
Closing the issue as this is a enviorment issue not a dlib issue.

**Comment by leftler** [comment]
Switching to the 2015 x64 console fixed it btw.

**Comment by davisking** [comment]
I generally run these compile commands at the normal console, not any of visual studio's magic consoles.  Did you try it that way as well?

**Comment by WHerroo** [comment]
I have solved this problem, you need install all spectre lib.
**Vistual Studio Installer->Modify->Component->Any spectre lib**

**Comment by nutrino** [comment]
> I have solved this problem, you need install all spectre lib. **Vistual Studio Installer->Modify->Component->Any spectre lib**

Or you can bypass it. Set "Visual C++ Project Properties > C/C++ > Code Generation > Spectre Mitigation" to Disabled.
