### ISSUE TITLE
Prevent false positive results of HOG object detector

### ISSUE THREAD

**Issue by don-prog** [davisking/dlib#1133]
I want to train my own HOG face detector using [this example](https://github.com/davisking/dlib/blob/master/examples/fhog_object_detector_ex.cpp). My goal is to train the detector to detect only open face - face without sunglasses, hands, a lot of hair etc. and only frontal face view. Now HOG detects faces but I have many false positive results, i.e. HOG detects closed faces too. I tried to add negative sample without box, but it seems like nothing has given. 
So, how can I add negative samples or how can I train detector to detect only open faces?

**Comment by davisking** [comment]
You add negative examples by including those images in your training set
without drawing boxes on them.  Anything without a box is a negative
example. Also,
http://dlib.net/faq.html#WhydoesnttheobjectdetectorItrainedwork

**Comment by don-prog** [comment]
@davisking I'm still trying to create frontal face detector, but now I have another issue: I created a large dataset with 466 positive and 335 negative samples, but still have many false positive and false negative results. It's really strange because the data is really simple and I have large dataset as for HOG. Of course I tried to set `epsilon`, `c` and `nuclear norm regularization` using many different values: `epsilon` from 0.0001 to 0.01, `c` from 1 to 150, `nuclear norm` from 1 to 15, but it gives little(so I changed only these parameters in fhog_object_detector_ex.cpp), and I still have many false positive and false negative results. [This is a folder with my xml for training and for testing and the photos themselves.](https://drive.google.com/open?id=1VGo0zgnukt-UnqibJSDD5GjXfXnft5t8)
Where I was mistaken and how can I improve this detector?
Regards.

**Comment by don-prog** [comment]
@davisking I'm still trying to create frontal face detector, but now I have another issue: I created a large dataset with 466 positive and 335 negative samples, but still have many false positive and false negative results. It's really strange because the data is really simple and I have large dataset as for HOG. Of course I tried to set `epsilon`, `c` and `nuclear norm regularization` using many different values: `epsilon` from 0.0001 to 0.01, `c` from 1 to 150, `nuclear norm` from 1 to 15, but it gives little(so I changed only these parameters in fhog_object_detector_ex.cpp), and I still have many false positive and false negative results. [This is a folder with my xml for training and for testing and the photos themselves.](https://drive.google.com/open?id=1CzBDh8FFsF8_zQx2G-DRICN7ExrzIUGw)
Where I was mistaken and how can I improve this detector?
Regards.

**Comment by davisking** [comment]
Read http://dlib.net/faq.html#WhydoesnttheobjectdetectorItrainedwork and
get more data.  The datasets used to train the public dlib face detectors
are also here: http://dlib.net/files/data/.  Those are examples of good
datasets.

**Comment by don-prog** [comment]
@davisking, thank you for the information, but I already tried to use your dlib_face_detection_dataset and dlib_face_detector_training_data. 
Please, check results:
1. Dataset: dlib_face_detector_training_data. I marked 10-15 boxes as ignored, used `./imglab --flip` command for the dataset and added approximately half of flipped images to the original dataset(11358 in total), because I can't use `add_image_left_right_flips` with this dataset - it generates too much images for the my RAM, and due to this program freezes. Also, I reduced `detection_window_size` to `50, 50` because this dataset has many small boxes, so the program throws exceptions. I tried to use this dataset with `c` = 1, `epsilon` = 0.01 and `c` = 10, `epsilon` = 0.01 and got the same testing results - 0 detections from 20 images with faces(it's absolutely trivial set of faces). Training results: 1; 0; 0. Testing results: 1; 0; 0;.

2. Dataset: dlib_face_detector_training_data/frontal_faces.xml. Here I marked only ~5 boxes as ignored due to small size, and used `add_image_left_right_flips` with this dataset, set `detection_window_size` to `80, 80`.  Num of training images: 4748. `c` = 1, `epsilon` = 0.01 gives 8/20 detections, `c` = 10, `epsilon` = 0.01 and `c` = 20, `epsilon` = 0.01 gives 16/20 detections. Best results: Training results: 0.998; 0.892; 0.892. Testing results: 0.571; 0.8; 0.669.

Code: 

```
try
       {

           if (argc != 2)
           {
               cout << "Give the path to the examples/faces directory as the argument to this" << endl;
               cout << "program.  For example, if you are in the examples folder then execute " << endl;
               cout << "this program by running: " << endl;
               cout << "   ./fhog_object_detector_ex faces" << endl;
               cout << endl;
               return 0;
           }
           const std::string faces_directory = argv[1];


           dlib::array<array2d<unsigned char> > images_train, images_test;
           std::vector<std::vector<rectangle> > face_boxes_train, face_boxes_test;

           load_image_dataset(images_train, face_boxes_train, faces_directory+"flipped_faces_and_faces_2016_09_30.xml");
           load_image_dataset(images_test, face_boxes_test, faces_directory+"/detector dataset/testing.xml");

           upsample_image_dataset<pyramid_down<2> >(images_train, face_boxes_train);
           upsample_image_dataset<pyramid_down<2> >(images_test,  face_boxes_test);

           cout << "num training images: " << images_train.size() << endl;
           cout << "num testing images:  " << images_test.size() << endl;

           typedef scan_fhog_pyramid<pyramid_down<6> > image_scanner_type;
           image_scanner_type scanner;

           scanner.set_detection_window_size(50, 50);
//           scanner.set_nuclear_norm_regularization_strength(15.0);
           structural_object_detection_trainer<image_scanner_type> trainer(scanner);

           trainer.set_num_threads(4);

           trainer.set_c(10);
           trainer.be_verbose();
           trainer.set_epsilon(0.01);

           object_detector<image_scanner_type> detector = trainer.train(images_train, face_boxes_train);

           cout << "training results: " << test_object_detection_function(detector, images_train, face_boxes_train) << endl;
           cout << "testing results:  " << test_object_detection_function(detector, images_test, face_boxes_test) << endl;

           image_window hogwin(draw_fhog(detector), "Learned fHOG detector");

           image_window win;
           for (unsigned long i = 0; i < images_test.size(); ++i)
           {
               // Run the detector and get the face detections.
               std::vector<rectangle> dets = detector(images_test[i]);
               win.clear_overlay();
               win.set_image(images_test[i]);
               win.add_overlay(dets, rgb_pixel(255,0,0));
               cout << "Hit enter to process the next image..." << endl;
               cin.get();
           }

           serialize("face_detector.svm") << detector;

           cout<<"svm saved"<<endl;

           object_detector<image_scanner_type> detector2;
           deserialize("face_detector.svm") >> detector2;

           std::vector<object_detector<image_scanner_type> > my_detectors;
           my_detectors.push_back(detector);
           std::vector<rectangle> dets = evaluate_detectors(my_detectors, images_train[0]);

           cout << "num filters: "<< num_separable_filters(detector) << endl;

           detector = threshold_filter_singular_values(detector,0.1);

       }
       catch (exception& e)
       {
           cout << "\nexception thrown!" << endl;
           cout << e.what() << endl;
       }
```
But It's not even close to your dlib detector, even my own made detector gives 18/20, so I incorrectly set some other parameters or I'm doing something wrong, but what?
Regards.

**Comment by davisking** [comment]
Read this comment:
http://dlib.net/dlib/image_processing/frontal_face_detector.h.html#get_frontal_face_detector

**Comment by don-prog** [comment]
@davisking , ok, I did as it is written. Results:
1. The front detector. I used `frontal_faces.xml` and set `upsample_image_dataset<pyramid_down<2> >`, `scan_fhog_pyramid<pyramid_down<6> >`, `add_image_left_right_flips(images_train, face_boxes_train)`, `trainer.set_loss_per_missed_target(1)`, `trainer.set_epsilon(0.05)`, `scanner.set_padding(0)`, `scanner.set_detection_window_size(80, 80)`, `trainer.set_c(700)`, `scanner.set_nuclear_norm_regularization_strength(9)`, `scanner.set_cell_size(8)`, and got training results: 0.998; 0.895; 0.894. Also I got many detections of only frontal face, so I think here all fine, right?

   2-3.  The left and right detectors. I used `left_faces.xml`/`right_faces.xml` and set `upsample_image_dataset<pyramid_down<2> >`, `scan_fhog_pyramid<pyramid_down<6> >`, `trainer.set_loss_per_missed_target(2)`, `trainer.set_epsilon(0.05)`, `scanner.set_padding(0)`, `scanner.set_detection_window_size(80, 80)`, `trainer.set_c(250)`, `scanner.set_nuclear_norm_regularization_strength(8)`, `scanner.set_cell_size(8)` and got training results: 1; 0; 0. Also I got no one detection.
But if I remove `scanner.set_padding(0)` from code for this detector, then I got: 0.911; 0.732; 0.710 and 4 detections for `left_faces.xml` and 0.920; 0.741; 0.719 and 2 detections for `right_faces.xml`. So, why `scanner.set_padding(0)` gives such results, how can I use it and what else have I done wrong here?

   4-5.  The front-rotate-left and front-rotate-right detectors. I used `frontal_faces.xml` and set `upsample_image_dataset<pyramid_down<2> >`, `scan_fhog_pyramid<pyramid_down<6> >`, `rotate_image_dataset(-27, images_train, face_boxes_train)`/`rotate_image_dataset(27, images_train, face_boxes_train)`, `add_image_left_right_flips(images_train, face_boxes_train)`, `trainer.set_loss_per_missed_target(1)`, `trainer.set_epsilon(0.05)`, `scanner.set_padding(0)`, `scanner.set_detection_window_size(80, 80)`, `trainer.set_c(700)`, `scanner.set_nuclear_norm_regularization_strength(9)`, `scanner.set_cell_size(8)`, and got training results: 1; 0; 0. Also I got no one detection. Here I also tried to remove `scanner.set_padding(0)` from code and got these training results: 0.997; 0.903; 0.903, but still without any detection(despite the fact that the testing dataset has rotated heads). Please note that I first did `add_image_left_right_flips` and then `rotate_image_dataset`, if I do this in reverse order, then I got: 0.998; 0.847; 0.847. So, here I face same problem here.

Code for the last detector(but I used it for others, changing the parameters):
```


           if (argc != 2)
           {
               cout << "Give the path to the examples/faces directory as the argument to this" << endl;
               cout << "program.  For example, if you are in the examples folder then execute " << endl;
               cout << "this program by running: " << endl;
               cout << "   ./fhog_object_detector_ex faces" << endl;
               cout << endl;
               return 0;
           }
           const std::string faces_directory = argv[1];

           dlib::array<array2d<unsigned char> > images_train, images_test;
           std::vector<std::vector<rectangle> > face_boxes_train, face_boxes_test;

           load_image_dataset(images_train, face_boxes_train, "frontal_faces.xml");
           load_image_dataset(images_test, face_boxes_test, faces_directory+"/detector dataset/testing.xml");

           upsample_image_dataset<pyramid_down<2> >(images_train, face_boxes_train);
           upsample_image_dataset<pyramid_down<2> >(images_test,  face_boxes_test);

           add_image_left_right_flips(images_train, face_boxes_train);
           cout << "num training images: " << images_train.size() << endl;
           cout << "num testing images:  " << images_test.size() << endl;

           rotate_image_dataset(-27, images_train, face_boxes_train);

           typedef scan_fhog_pyramid<pyramid_down<6> > image_scanner_type;
           image_scanner_type scanner;

         //scanner.set_padding(0);
           scanner.set_cell_size(8);

           scanner.set_detection_window_size(80, 80);
           scanner.set_nuclear_norm_regularization_strength(9);
           structural_object_detection_trainer<image_scanner_type> trainer(scanner);

           trainer.set_loss_per_missed_target(1);
           trainer.set_num_threads(4);

           trainer.set_c(700);
           trainer.be_verbose();
           trainer.set_epsilon(0.05);

           object_detector<image_scanner_type> detector = trainer.train(images_train, face_boxes_train);

           cout << "training results: " << test_object_detection_function(detector, images_train, face_boxes_train) << endl;
           cout << "testing results:  " << test_object_detection_function(detector, images_test, face_boxes_test) << endl;

           image_window hogwin(draw_fhog(detector), "Learned fHOG detector");

           image_window win;
           for (unsigned long i = 0; i < images_test.size(); ++i)
           {
               // Run the detector and get the face detections.
               std::vector<rectangle> dets = detector(images_test[i]);
               win.clear_overlay();
               win.set_image(images_test[i]);
               win.add_overlay(dets, rgb_pixel(255,0,0));
               cout << "Hit enter to process the next image..." << endl;
               cin.get();
           }

           serialize("new_front detector.svm") << detector;
```
Where do I still have mistakes? Maybe somewhere there is a code(not only parameters) of training of dlib face detector?
Regards.

**Comment by davisking** [comment]
Are you calling add_image_left_right_flips() when training all the
detectors?

**Comment by don-prog** [comment]
No, as I wrote, I didn't use it with 2-3 detectors(left and right detectors).

**Comment by davisking** [comment]
You seem to be ignoring the ignored boxes in the training dataset.  They are returned by load_image_dataset and you need to give them to the trainer.  You seem to be aware of their existence, but your code doesn't show you doing anything with them. They need to be an input to the trainer for it to know about them as well.

**Comment by don-prog** [comment]
@davisking, I modified code in [the previous comment with the code](https://github.com/davisking/dlib/issues/1133#issuecomment-366510644) how it looks now. Now I can use `scanner.set_padding(0)`, and now I got more detections using left and right detectors. But front-rotate-left and front-rotate-right detectors still give 0 detections.
So, I trained 5 new detectors and test them using `evaluate_detectors`, [this dataset contains only false negative results of this 5 new detectors](https://drive.google.com/open?id=1cdryWPmSPC3waUO3TMxkYlKlNEHPewk_). I also tried to use dlib's default face detector with this dataset and got almost all true positive results(but it's strange why not all true positive, because I used dlib's face detector to get these images).
I think that now front-rotate-left and front-rotate-right detectors are the main problem, but I still can't get the same training results of others detectors as dlib's detectors have, so, I think they still have issues too.
So, what is the next step? 
Also, If you posted the needed parameters for the training dlib's face detector, then there is nothing secret about this, so can you, please, share the original code of the training of dlib's face detector? I think this will be the best solution and can save our time. Testing of many detectors in different configurations takes a lot of time, please, understand me.
Regards.

**Comment by davisking** [comment]
I don't have the original code.

**Comment by don-prog** [comment]
Ok, but what about next step? Please, check my previous comment.

**Comment by don-prog** [comment]
@davisking, I still try to create face detector, I provided the latest information in [this comment](https://github.com/davisking/dlib/issues/1133#issuecomment-366596180). So, what is the problem?
Regards.

**Comment by davisking** [comment]
I don't know. Maybe you aren't rotating the ignore boxes. Github issues isn't a code writing service, you need to debug your own code and be sure to read the documentation.  If you are calling a function in dlib, read it's documentation. All the things I've told you are things you would know if you had just read the documnetation.

**Comment by don-prog** [comment]
@davisking, of course, I understand, but I don't ask to write the code for me, I just ask where I made a mistake? I tried to fix it for hours, but it does not do any good, you see. If I had an example of working code, I would not have had such problems, it would be much easier to understand the needed workflow. All the problem code in [the comment above](https://github.com/davisking/dlib/issues/1133#issuecomment-366510644). As I wrote, I did `upsample`, `flips` and `rotate` in this order:
```
           upsample_image_dataset<pyramid_down<2> >(images_train, face_boxes_train, ignore);
           upsample_image_dataset<pyramid_down<2> >(images_test,  face_boxes_test);

           add_image_left_right_flips(images_train, face_boxes_train, ignore);
           cout << "num training images: " << images_train.size() << endl;
           cout << "num testing images:  " << images_test.size() << endl;

           rotate_image_dataset(-27, images_train, face_boxes_train, ignore);
```

Maybe the problem is related to this? 

Or a problem with the wrong parameters of training:
```
           typedef scan_fhog_pyramid<pyramid_down<6> > image_scanner_type;
           image_scanner_type scanner;

           scanner.set_padding(0);
           scanner.set_cell_size(8);

           scanner.set_detection_window_size(80, 80);
           scanner.set_nuclear_norm_regularization_strength(9);
           structural_object_detection_trainer<image_scanner_type> trainer(scanner);

           trainer.set_loss_per_missed_target(1);
           trainer.set_num_threads(4);

           trainer.set_c(700);
           trainer.be_verbose();
           trainer.set_epsilon(0.05);

           object_detector<image_scanner_type> detector = trainer.train(images_train, face_boxes_train, ignore);
```
I really checked them many times, but maybe you can see the problem?
Regards.

**Comment by davisking** [comment]
I can't even tell what you are really doing since you keep posting little snippets without context.  However, I'll tell you one more thing.  Look at add_image_left_right_flips(), what does the documentation say it does?  It doesn't make any sense to put that in training data that also rotates the images. Think about it. I linked you this http://dlib.net/faq.html#WhydoesnttheobjectdetectorItrainedwork already.  It clearly explains why this is bad.

**Comment by don-prog** [comment]
1. @davisking, thanks for this information, but I don't understand why I don't have to use `add_image_left_right_flips()` with frontal faces and then `rotate_image_dataset()`(for training front-rotate-left and front-rotate-right detectors) because of these three things: you wrote "trained on mirrored set of labeled_faces_in_the_wild/frontal_faces.xml" about front-rotate-left and front-rotate-right detectors, so you did this too; you wrote "num images: 4748" about front-rotate-left and front-rotate-right detectors, so this equates to a doubled frontal_faces.xml dataset; we can flip frontal_faces dataset because frontal face has symmetry, and after that we can rotate this doubled dataset on the needed angle.
Anyway, I already tried to train front-rotate-left and front-rotate-right detectors without `add_image_left_right_flips()` and it gave 0 detections for [this dataset](https://drive.google.com/open?id=1cdryWPmSPC3waUO3TMxkYlKlNEHPewk_).

2. I don't know why you write that I "posting little snippets without context". My last two code snippets - quotation of [my previous comment with full problem code](https://github.com/davisking/dlib/issues/1133#issuecomment-366510644), so I already posted full code. I also posted my [testing dataset](https://drive.google.com/open?id=1cdryWPmSPC3waUO3TMxkYlKlNEHPewk_). 
So, what else is needed for the full context?

Regards.

**Comment by davisking** [comment]
It makes sense for the front looking faces, but it doesn't make any sense for the side looking faces.

You posted what you were doing a while ago.  I'm not going to guess or assume that you are doing the right thing now, because obviously you aren't.

**Comment by don-prog** [comment]
@davisking, I agree about it. As I wrote I don't use `add_image_left_right_flips()` for the left and right detectors.
Ok, then I will post what I'm using now for training of front-rotate-left and front-rotate-right detectors:

```
           if (argc != 2)
           {
               cout << "Give the path to the examples/faces directory as the argument to this" << endl;
               cout << "program.  For example, if you are in the examples folder then execute " << endl;
               cout << "this program by running: " << endl;
               cout << "   ./fhog_object_detector_ex faces" << endl;
               cout << endl;
               return 0;
           }
           const std::string faces_directory = argv[1];

           dlib::array<array2d<unsigned char> > images_train, images_test;
           std::vector<std::vector<rectangle> > face_boxes_train, face_boxes_test, ignore;

           ignore = load_image_dataset(images_train, face_boxes_train, "frontal_faces.xml");
           load_image_dataset(images_test, face_boxes_test, faces_directory+"/detector dataset/testing.xml");

           upsample_image_dataset<pyramid_down<2> >(images_train, face_boxes_train, ignore);
           upsample_image_dataset<pyramid_down<2> >(images_test,  face_boxes_test);

           add_image_left_right_flips(images_train, face_boxes_train, ignore);
           cout << "num training images: " << images_train.size() << endl;
           cout << "num testing images:  " << images_test.size() << endl;

           rotate_image_dataset(-27, images_train, face_boxes_train, ignore);

           typedef scan_fhog_pyramid<pyramid_down<6> > image_scanner_type;
           image_scanner_type scanner;

           scanner.set_padding(0);
           scanner.set_cell_size(8);

           scanner.set_detection_window_size(80, 80);
           scanner.set_nuclear_norm_regularization_strength(9);
           structural_object_detection_trainer<image_scanner_type> trainer(scanner);

           trainer.set_loss_per_missed_target(1);
           trainer.set_num_threads(4);

           trainer.set_c(700);
           trainer.be_verbose();
           trainer.set_epsilon(0.05);

           object_detector<image_scanner_type> detector = trainer.train(images_train, face_boxes_train, ignore);

           cout << "training results: " << test_object_detection_function(detector, images_train, face_boxes_train) << endl;
           cout << "testing results:  " << test_object_detection_function(detector, images_test, face_boxes_test) << endl;

           image_window hogwin(draw_fhog(detector), "Learned fHOG detector");

           image_window win;
           for (unsigned long i = 0; i < images_test.size(); ++i)
           {
               // Run the detector and get the face detections.
               std::vector<rectangle> dets = detector(images_test[i]);
               win.clear_overlay();
               win.set_image(images_test[i]);
               win.add_overlay(dets, rgb_pixel(255,0,0));
               cout << "Hit enter to process the next image..." << endl;
               cin.get();
           }

           serialize("new_front detector.svm") << detector;
```
I used [this testing dataset](https://drive.google.com/open?id=1cdryWPmSPC3waUO3TMxkYlKlNEHPewk_), trained detector gives 0 detection on it.
Regards.

**Comment by davisking** [comment]
I know I seem like a broken record, but you need to read the documentation
for the functions you are calling. I say this because I don't like
answering these types of questions because all I'm doing is reading the
documentation myself and telling it to you.  For instance, I just read the
documentation for rotate_image_dataset and it says the angle is in radians,
not degrees. If you read the documentation you would know this. Also, how
do you expect the testing to work if you only rotate the training data and
not the testing data?  Of course it's going to look like it doesn't detect
any faces in that case.

**Comment by don-prog** [comment]
@davisking, indeed, now it gives much more detections, I already checked description about this function on the http://dlib.net/imaging.html page which doesn't say anything about radians, and parameter is named "angle", so I didn't suggest that the angle is given in radians. Thanks.

**Comment by davisking** [comment]
I'm looking at the documentation for that function on dlib.net and it most
definitely says it's in radians.

**Comment by don-prog** [comment]
@davisking, yes, you meant documentation in the sources, but I meant the description about this function on the http://dlib.net/imaging.html page.

**Comment by xueliang** [comment]
Dear don-prog,
     Do you use the standard _dlib_face_detector_training_data_ . I run your code with this dataset but I met a very puzzled problem. It is an except saying that：
`exception thrown!
An impossible set of object labels was detected. This is happening because none
of the object locations checked by the supplied image scanner is a close enough
match to one of the truth boxes in your training dataset. To resolve this you
need to either lower the match_eps, adjust the settings of the image scanner so
that it is capable of hitting this truth box, or adjust the offending truth
rectangle so it can be matched by the current image scanner. Also, if you are
using the scan_fhog_pyramid object then you could try using a finer image
pyramid. Additionally, the scan_fhog_pyramid scans a fixed aspect ratio box
across the image when it searches for objects. So if you are getting this error
and you are using the scan_fhog_pyramid, it's very likely the problem is that
your training dataset contains truth rectangles of widely varying aspect
ratios. The solution is to make sure your training boxes all have about the
same aspect ratio.

image index              151
match_eps:               0.5
best possible match:     0.414524
truth rect:              [(396, 560) (442, 606)]
truth rect width/height: 1
truth rect area:         2209
nearest detection template rect:              [(381, 541) (453, 613)]
nearest detection template rect width/height: 1
nearest detection template rect area:         5329
`.
Any comments or suggestions are appreciated. Thanks.

**Comment by hafiz031** [comment]
Hi @davisking I have added negative examples and in the xml file I have added the images' directories like this:
```
...
<image file="negative_samples/063_0071.jpg" width="165" height="300"/>
<image file="negative_samples/230_0033.jpg" width="300" height="206"/>
<image file="negative_samples/158_0033.jpg" width="560" height="400"/>
<image file="negative_samples/147_0152.jpg" width="480" height="640"/>
<image file="negative_samples/224_0003.jpg" width="614" height="819"/>
...
```
along with the other positive examples. But I am getting:
```
...
ERROR:root:Couldn't read the image: negative_samples/218_0029.jpg
ERROR:root:list index out of range
ERROR:root:Couldn't read the image: negative_samples/200_0094.jpg
ERROR:root:list index out of range
ERROR:root:Couldn't read the image: negative_samples/110_0007.jpg
ERROR:root:list index out of range
ERROR:root:Couldn't read the image: negative_samples/132_0167.jpg
...
```

Why?
