### ISSUE TITLE
Too slow FPS

### ISSUE THREAD

**Issue by springkim** [davisking/dlib#1139]
## Problem
The object detection is too slow. I build dlib with cuda8.0 on GeForce 1080ti. But FPS is only 7~8.
How can i make fast as you said(98FPS)?

Here is my cmake build option on Windows batch.
```
cmake ../dlib^
 -G "Visual Studio 14 2015 Win64"^
 -DCMAKE_BUILD_TYPE=RELEASE^
 -DCMAKE_INSTALL_PREFIX=build^
 -DCUDA_USE_STATIC_CUDA_RUNTIME=ON^
 -DDLIB_USE_CUDA=ON^
 -Dcudnn=..\cuda\lib\x64\cudnn.lib^
 -Dcudnn_include=..\cuda\include\^
;
cmake --build . --config Release --target ALL_BUILD
cmake --build . --config Release --target INSTALL
```

* **Version**: latest (19.9)
* **Where did you get dlib**: github
* **Platform**: Windows10 x64
* **Compiler**: MSVC14

**Comment by davisking** [comment]
Fill out the issue template
