### ISSUE TITLE
Problem with shape predictor  5 face land marks 

### ISSUE THREAD

**Issue by paisilv** [davisking/dlib#1142]
sp = dlib.shape_predictor(predictor_path)
RuntimeError: Unable to open shape_predictor_5_face_landmarks.dat

I get that error , what am i doing wrong, I have Dlib install, cmake,python, and other libraries currently running in ubuntu 

`import sys
import os
import dlib
import glob
from skimage import io

predictor_path = 'shape_predictor_5_face_landmarks.dat'
face_rec_model_path = 'dlib_face_recognition_resnet_model_v1.dat'
faces_folder_path = '../examples/faces'

detector = dlib.get_frontal_face_detector()
sp = dlib.shape_predictor(predictor_path)
facerec = dlib.face_recognition_model_v1(face_rec_model_path)

win = dlib.image_window()

for f in glob.glob(os.path.join(faces_folder_path, "*.jpg")):
    print("Processing file: {}".format(f))
    img = io.imread(f)

    win.clear_overlay()
    win.set_image(img)

    
    dets = detector(img, 1)
    print("Number of faces detected: {}".format(len(dets)))

 
    for k, d in enumerate(dets):
        print("Detection {}: Left: {} Top: {} Right: {} Bottom: {}".format(
            k, d.left(), d.top(), d.right(), d.bottom()))
       
        shape = sp(img, d)
     
        win.clear_overlay()
        win.add_overlay(d)
        win.add_overlay(shape)

    .
        face_descriptor = facerec.compute_face_descriptor(img, shape)
        print(face_descriptor)
        

        dlib.hit_enter_to_continue()
`

**Comment by davisking** [comment]
You don't have a `shape_predictor_5_face_landmarks.dat` file.  That's what the error is telling you.

**Comment by paisilv** [comment]
I do have the file that’s why I was asking why is not hable to open it or how can i get it to work , my folder looks something lIke this

Face detector/
-“shape predictor......dat
-“dlib face recognition....dat
-examples(folder)
     -faces(folder)
           -images.jpg

**Comment by paisilv** [comment]
Also the python file

**Comment by liobrando** [comment]
Similar issue. I train a shape predictor, create the .dat file but when trying to load it instead of the 68 landmarks shape predictor, i get a runtime error , could not open newpredictor.dat

**Comment by TheBlue24** [comment]
RuntimeError: Unexpected version found while deserializing dlib::shape_predictor.

How to solve this error??
