### ISSUE TITLE
Run cnn_face_detector on multiple GPUs

### ISSUE THREAD

**Issue by HarveyBrezinaConniffe** [davisking/dlib#1144]
Sorry in advance if I have missed something, I am attempting to identify faces( And then recognise them ) using cnn_face_detector on multiple GPUs at a time using python bindings. I have not been able to find much about using multiple GPUs for classification. I am thinking that I should add some way to run cuda's set_device() function from python, separate my images up into batches for each GPU and use threading to run a cnn_face_detector for each GPU. Would this be the best way to do this?

**Comment by davisking** [comment]
Yes, you need to call set_device(), or cudaSetDevice() which is the same thing.  I just added a python interface for this in dlib.cuda.  So get the latest code and you can do it from python now.

**Comment by HarveyBrezinaConniffe** [comment]
Thanks!

**Comment by davisking** [comment]
No problem :)
