### ISSUE TITLE
dnn_mmod cpu behaviour

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1146]
Hi Davis,

Thanks again. I start learning c++ because of your dlib :) 

As we utilized both java, python and scala world there is always a way to using all possible cores specially in training. Keras, Tensorflow, D4j etc.

what is the best approach to using all possible cpus in training ? Is it all ready if we install some packages ie MKL , BLASS etc . or it needs be coded ?

Best

**Comment by davisking** [comment]
I don't know what part of dlib you are asking about, but in general dlib is setup to efficiently use multi-core CPUs.  So the answer is probably yes.

**Comment by MyraBaba** [comment]
I maean the dnn_mmod_ex.cpp    (training CNN with Max-Margin Object Detection) . It is not using all available cores.

**Comment by davisking** [comment]
Link to a multi-core BLAS like the Intel MKL.

But really, use a GPU.  Training will take forever on a CPU.

**Comment by MyraBaba** [comment]
Than the second job to come to an agreement with eternity :)

Do I need to link manually from cmakeList.txt  or cmake it self can found the lib and could be automatically linked ?


PS: we have plenty of i7 cores (1000+)

**Comment by davisking** [comment]
CMake should do it automatically unless you install the MKL to an unusual location.
