### ISSUE TITLE
When using the CNN face detector with CUDA, CPU limit the speed.

### ISSUE THREAD

**Issue by czfhhh** [davisking/dlib#1150]
One CNN face detector only use one CPU core. With nvidia tesla K80, if run 3 processes together, it is about 1.5x faster than only 1 process. But this method not work on nvidia tesla P100 because of the GPU memory. One CNN face detector cost more then 8G ram on P100, but it has only 16G total.(One detector only cost less than 2G ram on K80)
Is there any way to use more CPU cores in this situation?

**Comment by davisking** [comment]
Make sure you compiled with compiler optimizations enabled.  But beyond
that, there isn't much the CNN does with the CPU, so there isn't much to
do. Be careful how you load data I guess and maybe you need to use multiple
data loading threads to keep your network saturated with data.

**Comment by czfhhh** [comment]
I has compiled dlib with OpenBLAS(mkl seems to use more CPU but has the same speed), AVX, CUDA and cuDNN. Is there any other things I can do?
I use CNN to detect faces in 1920x1080 RGB24 pictures, loading data from python api in numpy array. The speed is about 1.7 pictures/s with K80 and 1 process, speed up to 2.6 pictures/s when using 3 processes. Is it a normal speed?

**Comment by davisking** [comment]
On my NVIDIA 1080ti I observe about 50 million pixels per second of
processing speed with that detector.  So you are doing something wrong if
it's running that slow. The bottleneck is probably some other part of the
code.

**Comment by czfhhh** [comment]
I use upsample_num=1. So the pixels number per second processed is 1920*1080*4*2.6=21.6 million. Is that right? 1080ti is about 2x~3x faster than K80(refer to http://browser.geekbench.com/cuda-benchmarks). So the speed is all right.
When your machine process 50 million pixels per second, what about the CPU usage?

**Comment by davisking** [comment]
It's just using one CPU core. Basically all the work is happening on the
GPU.

**Comment by czfhhh** [comment]
I have 2 ideas to test when I need detect faces in the future.
1. Move pyramid_up() function to other process
2. Detect banch of images one time
I will report the result when that have done.

**Comment by xsacha** [comment]
Can you profile your application to find what is using the CPU?
dlib does not seem to use much CPU in CUDNN mode.
It's more likely to be the rest of your application code, like processing the video or frames.

**Comment by czfhhh** [comment]
@xsacha there are only 4 things in the python process.
1. unserialize the image from the queue
2. use CNN face detector to detect faces
3. convert dlib 'rect' object to a plain tuple in (top, right, bottom, left) order
4. serialize the locations and image to the queue

**Comment by xsacha** [comment]
I believe 1 and 4 will use a lot of CPU. Do you need to serialise image back to queue?

**Comment by xsacha** [comment]
The 5% is the total usage? That seems low enough. Are you still having problems?

I had similar bottlenecks with copying the data from CPU to GPU and back where the cuda sync appeared to lock up the CPU due to it being blocking. There was no actual usage but it just needed to be threaded.
For my usage I couldn't make it threaded so I have just been leaving the data on the GPU.

**Comment by czfhhh** [comment]
If the process only do 1 and 4, the speed is about 50 pictures(1920x1080) per second. So I said 5% usage.
Using batch detecting may help but still slower than multi-process in my case.
I think that the data just copied to GPU but not back in 2, GPU only return the result.
