### ISSUE TITLE
[question] Which CUDA compute capabilities does dlib support?

### ISSUE THREAD

**Issue by logidelic** [davisking/dlib#1156]
Which CUDA architectures are supported by dlib and do these ever need to be specified manually when building?

I saw [this open issue](https://github.com/davisking/dlib/issues/605) which leads me to wonder how dlib handles this currently.

I'm trying to do some training using a Titan V and it is working, but I'm not sure if the performance is what I should be expecting. Does dlib support the Volta architecture?

**Comment by davisking** [comment]
Dlib just uses cuDNN. So if you are using a version of cuDNN appropriate
for your machine then you are good.

**Comment by xsacha** [comment]
CuDNN requires CUDA Compute Capability 3.0 as a minimum by the way.

Same with CUDA 9.x.
