### ISSUE TITLE
Error at the image_window() overlay

### ISSUE THREAD

**Issue by AVINASH18794** [davisking/dlib#1157]
Traceback (most recent call last):
  File "face-rec.py", line 58, in <module>
    win.add_overlay(shape)
RuntimeError:

Error detected at line 25.
Error detected in file C:\bld\dlib_1504193025992\work\dlib-19.4\dlib\..\dlib/image_processing/render_face_detections.h.
Error detected in function class std::vector<struct dlib::image_display::overlay_line,class std::allocator<struct dlib::image_display::overlay_line> > __cdecl dlib::render_face_detections(const class std::vector<class dlib::full_object_detection,class std::allocator<class dlib::full_object_detection> > &,const struct dlib::rgb_pixel).

Failing expression was dets[i].num_parts() == 68.
         std::vector<image_window::overlay_line> render_face_detections()
         Invalid inputs were given to this function.
         dets[0].num_parts():  5

**Comment by davisking** [comment]
Read the error message.  You can't call that function with a 5 part annotation.
