### ISSUE TITLE
Dlib c++ inference time (batch\no-batch)

### ISSUE THREAD

**Issue by ariel415el** [davisking/dlib#1159]
Hi , 
I'm Trying to measure dlib's inference time and searched for some reference about the expected run-time for the c++ face recognition using GPU?
All i found was #98, concerning CPU inference and the python warping package (in which there is no batched inference)
and #1150 which does not specify inference time for  the 3 different nets (detection shape-prediction and recognition) and does not concern batching as-well.
From the experiments i did i get:

> **Face detection net::**
> 0.00777 s       (Batch size: 1)
> 0.0030075 s   (Batch size: 4)
> 0.00171812 s (Batch size: 16)
> 
> **shape prediction net:**
> 0.00171812 (Batch size: 1)
> 
> **face recognition net:**
> 0.04081 s     (Batch size: 1)
> 0.0377875 s (Batch size: 4)
> 0.0373 s       (Batch size: 16)

> Are these normal results? how much time reduction is supposed to be seen using batches for these nets?

By the way, is there a way to batch shape-predictor's inference as well? i did not find an equivalent api for the shape prediction net.

I'm using:
Dlib: 19.9
Cuda: 8.0
cudnn: 5.1
cmake: 3.9
compiler: Visual C++ 14.0
GPU: GeForce GTX 1070
System:
![capture](https://user-images.githubusercontent.com/32613612/36717978-d0c3c1e2-1ba8-11e8-90c6-7b0b2bb214f7.PNG)

Thanks, 
Ariel

**Comment by davisking** [comment]
Those seem fine.

No, there is no shape predictor batching. It doesn't make sense to do that.

**Comment by ariel415el** [comment]
Really ? It seems that bathing doesn't help much reducing the recognition inference time opposed to the significant improvement in the detection net. 
0.0373 seconds per image (not per batch) is quite time consuming.
Can you elaborate on why batching shape prediction does not make sense?

Thanks a lot.

**Comment by davisking** [comment]
Look at the code.  I don't know why you would think batching would make any
sense there.

Processing time is a function of image size, you didn't say your image
size, so 0.0373 is a meaningless number out of context.

**Comment by ariel415el** [comment]
I'm working on a single image (with a detectable face) of dimension 212x210. The batches comprise copies of the same image. i perform no down-sampling before detection.

**Comment by davisking** [comment]
This all sounds fine. Some networks are bigger than others.

**Comment by ariel415el** [comment]
Actually it is more relevant talking about the face-chip size cropped from the bigger image by the detection and shape prediction nets results and on which the recognition net runs.
the results I got were taken from running on a face-chip of size 150x150 .
These results are quite time consuming but on the other hand when I resize the image to smaller dimensions the face in it just doesn't get detected.
I wonder whether I can solve this by the following:  detecting and cropping a face chip on a large image (I can afford it for such fast nets) and then inferring the recognition nets on a smaller , resized, face chip hoping to get similar feature vector.

Do this method makes sense to you? 
Are there any other ways for optimizing the inference time of this big recognition net?

**Comment by davisking** [comment]
The face recognition model that comes with dlib requires 150x150 sized inputs.  Most models like this operate on fixed sized images.  If you want to use a faster model you need to make a new model that has fewer computations.  That new model would need to be trained though.
