### ISSUE TITLE
Error compiling at "'CMakeFiles/dlib_.dir/src/matrix.cpp.o'

### ISSUE THREAD

**Issue by trungdn** [davisking/dlib#116]
I try to compile Dlib on Raspberry Pi 3 with Ubuntu 16.04 OS but it always stop in the middle.
I run 'cmake --build . --config Release' 

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/dlib_.dir/build.make:86: recipe for target 'CMakeFiles/dlib_.dir/src/matrix.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_.dir/src/matrix.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_.dir/all' failed
make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
trungdn@trungdn-desktop:~/src/dlib/python_examples/build$ ^C
trungdn@trungdn-desktop:~/src/dlib/python_examples/build$

**Comment by e-fominov** [comment]
> c++: internal compiler error: Killed (program cc1plus)
This is possible means not enough memory. [How to change spaw space](http://askubuntu.com/questions/178712/how-to-increase-swap-space ) 

> trungdn@trungdn-desktop:~/src/dlib/python_examples/build$ ^C

Why building from python_examples? 
Did you tried to follow instructions from readme.txt?

> COMPILING DLIB Python API
   Before you can run the Python example programs you must compile dlib. Type:
       python setup.py install
   or type
       python setup.py install --yes USE_AVX_INSTRUCTIONS
   if you have a CPU that supports AVX instructions, since this makes some
   things run faster.  


Are you able to build and run normal examples?

**Comment by trungdn** [comment]
No. I tried the normal way and it still stop in the middle. I will try to swap mem.

**Comment by trungdn** [comment]
Yes. It worked when I swap mem by 2Gb.
Thank you very much.

**Comment by parthlathiya42** [comment]
> > c++: internal compiler error: Killed (program cc1plus)
> 
> This is possible means not enough memory. [How to change spaw space](http://askubuntu.com/questions/178712/how-to-increase-swap-space)
> 
> > trungdn@trungdn-desktop:~/src/dlib/python_examples/build$ ^C
> 
> Why building from python_examples?
> Did you tried to follow instructions from readme.txt?
> 
> > COMPILING DLIB Python API
> > Before you can run the Python example programs you must compile dlib. Type:
> > python setup.py install
> > or type
> > python setup.py install --yes USE_AVX_INSTRUCTIONS
> > if you have a CPU that supports AVX instructions, since this makes some
> > things run faster.
> 
> Are you able to build and run normal examples?

Worked like charm. Memory was the issue. My AWS instance had only 1 gb space. Reading the problem intuition, I created a swap space of 6 more gb and it worked. 

Now, I'm able to complete installation. 
Thanks
Regards 🤗

**Comment by aliaksandr960** [comment]
At least I confirm, there is problem with cones. In your data gimbal roll somtimes is 0 and sometims is 180, which cause cones looking to the sky.

<img width="724" height="402" alt="Image" src="https://github.com/user-attachments/assets/b73c39f2-4130-41a7-b788-fc929e90eaef" />
