### ISSUE TITLE
Object landmark

### ISSUE THREAD

**Issue by AndrGolubkov** [davisking/dlib#1160]
Hi,
For some tasks it would be interesting to create a landmark not only for the face, but for any objects, for example, for the hand. I read an article about hippesterization of dogs, but I didn't understand everything from it. Prompt please, whether it is possible basically with usage Dlib to make a landmark. And if so, what should be the sequence of actions.

Thanks

**Comment by davisking** [comment]
You can train it to do anything, not just faces. The documentation is quite detailed as to its training and use: http://dlib.net/imaging.html#shape_predictor
