### ISSUE TITLE
How do I convert dnn result to a dlib::rectangle?

### ISSUE THREAD

**Issue by cfoch** [davisking/dlib#1161]
Hello, I have seen that dlib has a DNN face detector. I am writing a program that just passing to it which detector to use, it chooses among the available detectors.
In the [example](http://dlib.net/dnn_mmod_face_detection_ex.cpp.html), it puts
```
        for (auto&& d : dets)
            win.add_overlay(d);
```
How can I convert these "dets" to a std::vector<dlib::rectangle>"?
* **Version**: 19.8.99
* **Where did you get dlib**: github repo
* **Platform**: Linux 4.14.11-200.fc26.x86_64 
* **Compiler**: gcc version 7.2.1 20170915

**Comment by davisking** [comment]
The documentation for the loss_mmod layer tells you the output.  So dets is a `std::vector<dlib::mmod_rect>`.

**Comment by deepakcrk** [comment]
vector<dlib::rectangle> v1
        for (auto&& d : dets) 
        {
            v1.push_back(d.rect)
         }
