### ISSUE TITLE
problem in matrix

### ISSUE THREAD

**Issue by plumtus** [davisking/dlib#1164]
I found a problem in matrix, I'm not sure is this a bug. I post my test program as below:

```
#include < thread>
#include <dlib/matrix.h>
using namespace std;
using namespace dlib;

//const matrix<double, 3, 3> getm() {    // declaration 1
const matrix<double, 3, 0> getm() {      // declaration 2
    return matrix<double, 3, 3>();
}

int main(int argc, char* argv[])
{
    int threads = 4;
    matrix<double, 3, 3> w = getm() * getm();
    std::thread ths[threads];
    for (int i = 0; i < threads; i++) {
        ths[i] = std::thread([]() {
            int a = 1;
            for (;;) {
                a = (a * std::rand() + 1234) % 1000;
            }
        });
    }
    for (int i = 0; i < threads; i++) {
        ths[i].join();
    }
    exit (0);
}
```

As declaration 2, the return type is matrix<double, 3, 0>, When this program is running, all threads run on only one core of CPU, in other words, One core is 100% usage, others is free.
As declaration 1, I change the return type to matrix<double, 3, 3>, all cores of CPU is 100% usage, this is my expected result.
I do this test, because this problem exists in shape_predictor.
In function 'find_affine_transform' (geometry/point_transforms.h),
the line: const matrix<double,2,3> m = Q*pinv(P);
The matrix P is defined as matrix<double,3,0>, so return type of template function pinv is matrix<double,3,0>.

* **Version**: 19.9
* **Where did you get dlib**: github
* **Platform**: ubuntu 16.04 64
* **Compiler**: gcc 5.4.0

**Comment by davisking** [comment]
Those threads don't even use the matrix.
