### ISSUE TITLE
Problem of matrix

### ISSUE THREAD

**Issue by plumtus** [davisking/dlib#1165]
Sorry, please test this program first before close this issue.
No matter the thread use the function 'getm' or not,  If this function was invoked, all threads would be binded on the same core of CPU.  You can move the line: matrix<double, 3, 3> w = getm() * getm(); into body of thread, the result is same. But when using declaration 1, the usage of CUP is normal.
The key problem is not about the body of thread, the body in thread could be anything. I think it may be because of memory management of matrix.

--------------------------------------------------------------------
#include < thread>
#include <dlib/matrix.h>

using namespace std;
using namespace dlib;

//const matrix<double, 3, 3> getm() {    // declaration 1
const matrix<double, 3, 0> getm() {      // declaration 2
    return matrix<double, 3, 3>();
}

int main(int argc, char* argv[])
{
    int threads = 4;
    matrix<double, 3, 3> w = getm() * getm();
    std::thread ths[threads];
    for (int i = 0; i < threads; i++) {
        ths[i] = std::thread([]() {
            int a = 1;
            for (;;) {
                a = (a * std::rand() + 1234) % 1000;
            }
        });
    }
    for (int i = 0; i < threads; i++) {
        ths[i].join();
    }
    exit (0);
}
-------------------------------------------------

As declaration 2, the return type is matrix<double, 3, 0>, When this program is running, all threads run on only one core of CPU, in other words, One core is 100% usage, others is free.
As declaration 1, I change the return type to matrix<double, 3, 3>, all cores of CPU is 100% usage, this is my expected result.
I do this test, because this problem exists in shape_predictor.
In function 'find_affine_transform' (geometry/point_transforms.h),
the line: const matrix<double,2,3> m = Q*pinv(P);
The matrix P is defined as matrix<double,3,0>, so return type of template function pinv is matrix<double,3,0>.

* **Version**: 19.9
* **Where did you get dlib**: github
* **Platform**: ubuntu 16.04 64
* **Compiler**: gcc 5.4.0

**Comment by davisking** [comment]
I ran it and nothing funny happens.  All the threads run as expected.

**Comment by davisking** [comment]
It should also be pointed out that there is no magic inside dlib matrix.  It's just allocating a little bit of RAM with new just like any other C++ object would.  So you must be confused and not running what you think you are running.

As an aside, you should fix the formatting of your posts so it's not all garbled.

**Comment by plumtus** [comment]
The funny things really happen to me :)，But I have found the reason，It have nothing to do with dlib，but with the openblas. I build the openblas from source, the CPU affinity is set as default.
When using matrix<double, 3, 3>, it simply allocate memory in stack, I guess the program just include the matrix header file, this have no need to link dlib and openblas library, but matrix<double, 3, 0>  need to link the libraries. So, the code in openbals  cause unexpected CPU usage.
