### ISSUE TITLE
Change labels in trained model

### ISSUE THREAD

**Issue by cchadowitz-pf** [davisking/dlib#1166]
I was digging through google results and dlib documentation but I couldn't find anything definitive - how does dlib store class labels for a trained model and more specifically, is there a way that I can change or redefine the class labels after training is complete?

Thanks!

**Comment by davisking** [comment]
What part of dlib are you talking about?

**Comment by cchadowitz-pf** [comment]
Sorry, I should have been more clear - the deep learning part of dlib. I trained a custom multi-class object detector based on this example http://dlib.net/dnn_mmod_train_find_cars_ex.cpp.html and was wondering if it was possible to change the label associated with one of the classes at a later point.

**Comment by davisking** [comment]
It's stored in `mmod_options`. You can go edit the label string and it will be whatever you make it.

**Comment by cchadowitz-pf** [comment]
Maybe this is getting to detailed, but from your tip I managed to expose `mmod_options` successfully, but because of the way it's designed, I can only get a `const` reference to it. I should add that this is after I'm done training and serializing the model to disk, and then deserializing it into memory at a later stage.

I'm using `layer<loss_mmod>(net).loss_details().get_options()` to get a `const dlib::mmod_options` (https://github.com/davisking/dlib/blob/ffaa322fbf64bcf5fa70e6fb3972678c92b10eb6/dlib/dnn/loss_abstract.h#L775) but obviously can't then edit the label or anything like that.

Am I missing something? Or is there no easy way to edit the label after training+serializing the model to disk, then reading it at a later point (without access to the original `mmod_options` used during training). 

I managed to get around the `const` issue using `const_cast`, which seems pretty questionable, and modified the label in that way, but this doesn't change the label for the `mmod_options` still associated with the original trained net. So either I need to be able to get at a non-`const` reference of the associated `mmod_options`, or I need to somehow copy the trained model to a second net object with a new `mmod_options` and use that instead.

Hopefully I'm just missing something and it's not as complicated as I'm making it, but any insight you can provide is greatly appreciated. Thanks again!

**Comment by davisking** [comment]
Well, in general, I don't want to encourage people to go meddling with
things they don't understand.  It would be very easy for someone who was
careless or didn't understand the algorithm to mess up the layer if they
could easily edit anything. My general attitude is that if you are
sufficiently unfamiliar with C++ that you can't figure out how to modify
this then you probably shouldn't. So I'm not going to make it super easy to
do this.

But yes, you could use a const_cast.  Or you could just overwrite the
entire loss_mmod layer by assigning to it with operator =. That wouldn't
involve a const_cast.
