### ISSUE TITLE
Best way to visualize in-place intermediate layer output from pre-trained dlib DNN?

### ISSUE THREAD

**Issue by bakercp** [davisking/dlib#1168]
First, thanks @davisking  for all of your work on and support of dlib.  I've learned an immense amount from creating a wrapper / bridge [addon for openFrameworks](https://github.com/bakercp/ofxDlib/) over the last year.  I love your [generic image interface](https://github.com/bakercp/ofxDlib/blob/develop/libs/ofxDlib/include/dlib/of_image.h)!

So, I don't think this is a dlib "issue", but a question about a best approach given the existing DNN architecture.

For pedagogical reasons (I'm teaching art students to use dlib), I would like to show my students the intermediate data layer outputs in a dlib DNN.  I'm going for something interactive and similar to this lovely [LeNet Vis](http://scs.ryerson.ca/~aharley/vis/conv/).

Currently it is easy to extract / view the layer parameters(convolution kernels, layer weights, etc), but trickier to view the outputs for each layer because outputs for many traditional layer types are processed in place.

Given a pretty thorough reading of the great docs and in-line comments [like these](https://github.com/davisking/dlib/blob/master/dlib/dnn/core.h#L1544-L1558) I attempted to force non-in-place output by creating two versions of the LeNet like this:

```c++
using LeNet = dlib::loss_multiclass_log<
                                        dlib::fc<10,
                                        dlib::relu<dlib::fc<84,
                                        dlib::relu<dlib::fc<120,
                                        dlib::max_pool<2,2,2,2,dlib::relu<dlib::con<16,5,5,1,1,
                                        dlib::max_pool<2,2,2,2,dlib::relu<dlib::con<6,5,5,1,1,
                                        dlib::input<dlib::matrix<unsigned char>>
                                        >>>>>>>>>>>>;
 
template <typename SUBNET> using tlnet0  = dlib::add_tag_layer< 1100 + 0, SUBNET>;
// ... etc.

using TaggedLeNet = dlib::loss_multiclass_log<
                    tlnet0<dlib::fc<10,
                    tlnet1<dlib::relu<
                    tlnet2<dlib::fc<84,
                    tlnet3<dlib::relu<
                    tlnet4<dlib::fc<120,
                    tlnet5<dlib::max_pool<2,2,2,2,
                    tlnet6<dlib::relu<
                    tlnet7<dlib::con<16,5,5,1,1,
                    tlnet8<dlib::max_pool<2,2,2,2,
                    tlnet9<dlib::relu<
                    tlnet10<dlib::con<6,5,5,1,1,
                    dlib::input<dlib::matrix<unsigned char>
                    >>>>>>>>>>>>>>>>>>>>>>>>;

```

I then trained the `LeNet` as described in the examples, serialize/deserialize and set the LeNet equal to my instance of `TaggedLeNet` like this:

```c++
LeNet _net;
dlib::deserialize("mnist_network.dat") >> _net;
TaggedLeNet net = _net;
```

Upon running my program, I get a runtime error:

```c++
auto& layer = dlib::layer<tlnet10,1>(net);
auto& layer_output = layer.get_output(); 
    // -> Runtime error: Accessing this layer's get_output() is disabled because an in-place layer has been stacked on top of it.
```

From my code read, this is happening because the state of `get_output_and_gradient_input_disabled` is getting serialized with the untagged net [here](https://github.com/davisking/dlib/blob/master/dlib/dnn/core.h#L1279).  Then when I assign the deserialized `LetNet` to the `TaggedLeNet` (even though it's assignment compatible) it doesn't (for good reason I'm sure) recalculate the serialized values of `get_output_and_gradient_input_disabled` for each layer, even though the layers are surrounded by tag layers in the `TaggedLeNet`.  This all makes sense and is confirmed when I train `TaggedLeNet` directly, serialize/deserialize and receive no runtime errors

So, the question -- for small networks like `LeNet` it's easy to just retrain a tagged visualization version of the network.  But for some of the larger / more complex networks, I'd prefer not to retrain them.  I've considered some other ideas like creating partial networks that terminate at the outputs I'd like to visualize, but that starts to get pretty complicated and slow.

Does anyone have a suggestion about how best to visualize these intermediate layer outputs?

Thanks for reading this very long post.  CB

**Comment by davisking** [comment]
Hmm, well, what you are trying to do should probably work.  It's not obvious to me that the assignment shouldn't flip the state of `get_output_and_gradient_input_disabled`.  Or more simply, `add_tag_layer` should probably call the private versions of `get_output()` and `get_gradient_input()` so that it sidesteps this. Changing the code to allow this seems like the right thing to do here. Or is there some issue it raises that I'm missing?

**Comment by bakercp** [comment]
This change doesn't raise any particular red-flags for me.  As you say in your notes, if a tag layer is added, then it is assumed that the user does not want in-place outputs.  If a user is intentionally adding tag layers via assignment, it makes sense that their assignment would override any non-applicable internal layer state variables.

I think my uncertainty comes because explicitly serializing `get_output_and_gradient_input_disabled` seems to elevate it past its function as a private internal state variable.  As far as I can tell, it is only ever set via assignment, construction, and the private `disable_output_and_gradient_getters()` method.  Thus the user won't typically take action that would cause its value to deviate from a it's architecturally determined defaults.  So it makes me wonder why it is being serialized at all when perhaps it should always be calculated in response to the architecture (defaulting to in-place in most circumstances for efficiency)?  Perhaps there is a scenario with a user-defined layer that would cause it to make sense?  I'm not proposing that the serialization scheme be modified -- it seems the right solution is to modify `add_tag_layer` to do the right thing.  One small note -- if a user serializes a tagged architecture, then deserializes and assigns it to a non-tagged architecture, would the values of `get_output_and_gradient_input_disabled` for each layer be preserved?

Anyway, I'd be happy to develop a PR for, but it would likely need a few iterations. 

Thanks again for your feedback.

**Comment by davisking** [comment]
It could be calculated when deserialized, but that just makes the
deserialization code more error prone.  I'm sure there are other redundant
variables that are serialized other places as well.  The deserialization
routines would have to be a lot smarter and know a lot more about the
objects to be able to correctly reconstruct them if they didn't simply save
everything.

That's a good point about preserving the variable if tags are removed. I'm
not even sure an assignment from a tagged network to an untagged network
will compile. Does it?

Sure, submit a PR :)

**Comment by bakercp** [comment]
No, it doesn't compile, so we don't have to worry about that for now. :)

Will be back with a PR as soon as life allows.
