### ISSUE TITLE
Is loss_mean_square gradient corrent?

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#1169]
In line:
https://github.com/davisking/dlib/blob/881ce1744d662fef165ea24b7da6e2cbbfcf9a34/dlib/dnn/loss.h#L2026

It seems it should be, instead:
```
    g[i] = -2.0 * temp2;
```

**Comment by davisking** [comment]
Multiplying by 2 doesn't matter.

**Comment by davisking** [comment]
And in any case, it's customary for the MSE loss to be 0.5*(x-y)^2, which
would mean there isn't a 2.

**Comment by lvella** [comment]
> it's customary for the MSE loss to be 0.5*(x-y)^2

In that case, the scaling by 0.5 seems missing from the loss.

**Comment by davisking** [comment]
Which doesn't matter. And it's nice if the loss output that get's logged
isn't scaled by 0.5 because people find that confusing.
