### ISSUE TITLE
build dlib in iOS

### ISSUE THREAD

**Issue by hungbv** [davisking/dlib#117]
Hi Davisking!
I built dlib for iOS, both for real device and simulator (2 files libdlibd.a in Debug-iphoneos folder and Debug-iphonesimulator folder)
In my viewcontroller.mm, I called to face_landmark_detection.cpp with a simple detect function (code is quite similar with example from dlib).
When I ran on simulator, my project run quite well, but I can not run on real device. I found that error occurs in this code:
> load_image(img, image);
Error like this:
 > Undefined symbols for architecture armv7: "_png_init_filter_functions_neon", referenced from: _png_init_filter_functions in libdlibd.a(pngrutil.o)

please help me solve this problem. thank you :)

**Comment by davisking** [comment]
I haven't done any iOS development so I don't know what you have to do to compile things correctly.  This isn't a dlib problem though.  It's just a matter of linking to libpng or cross compiling correctly, which is a general "C++ on iOS" issue.
