### ISSUE TITLE
not able tinstall setup.py in windows

### ISSUE THREAD

**Issue by djangid** [davisking/dlib#1171]
## Current Behavior
python C:\Code-Repo\dlib-19.9\setup.py install
running install
running bdist_egg
running egg_info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
error: package directory 'dlib' does not exist

## Steps to Reproduce

* **Version**:  19.9
* **Where did you get dlib**:  from dlib page 
* **Platform**: Windows 10 64-bit -->
* **Compiler**:  python 2.7

**Comment by davisking** [comment]
cd into the dlib-19.9 folder before running setup.py.

**Comment by djangid** [comment]
c:\Code-Repo\dlib-19.9>python setup.py install
running install
running bdist_egg
running egg_info
creating dlib.egg-info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
writing manifest file 'dlib.egg-info\SOURCES.txt'
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
Invoking CMake setup: 'cmake c:\Code-Repo\dlib-19.9\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=c:\Code-Repo\dlib-19.9\build\l
ib.win32-3.6 -DPYTHON_EXECUTABLE=C:\Python36\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=c:\Code-Repo\dlib-19.9\build\li
b.win32-3.6'
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hos
tx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hos
tx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/H
ostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/H
ostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Python36/python.exe (found version "3.6.3")
-- Found PythonLibs: C:/Python36/libs/Python36.lib
-- pybind11 v2.3.dev0
-- ******************************************************************************************
-- Your version of Visual Studio has incomplete C++11 support and is unable to compile the
-- DNN examples. So we are disabling the deep learning tools.  If you want to use the DNN
-- tools in dlib then update your copy of Visual Studio.
-- ******************************************************************************************
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling SSE4 instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- LAPACK requires BLAS
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is
at least version "7.5")
-- *** Dlib CUDA support requires C++11 but your compiler doesn't support it. ***
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
CMake Error at CMakeLists.txt:38 (message):
  You have to use a version of Visual Studio that supports C++11.  As of
  December 2017, the only versions that have good enough C++11 support to
  compile the dlib Pyhton API is a fully updated Visual Studio 2015 or a
  fully updated Visual Studio 2017.  Older versions of either of these
  compilers have bad C++11 support and will fail to compile the Python
  extension.  ***SO UPDATE YOUR VISUAL STUDIO TO MAKE THIS ERROR GO AWAY***


-- Configuring incomplete, errors occurred!
See also "C:/Code-Repo/dlib-19.9/build/temp.win32-3.6/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Code-Repo/dlib-19.9/build/temp.win32-3.6/Release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 238, in <module>
    'Topic :: Software Development',
  File "C:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python36\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python36\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python36\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Python36\lib\site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "C:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python36\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Python36\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 119, in run
    self.build_extension(ext)
  File "setup.py", line 153, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'c:\\Code-Repo\\dlib-19.9\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=c
:\\Code-Repo\\dlib-19.9\\build\\lib.win32-3.6', '-DPYTHON_EXECUTABLE=C:\\Python36\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTOR
Y_RELEASE=c:\\Code-Repo\\dlib-19.9\\build\\lib.win32-3.6']' returned non-zero exit status 1.
