### ISSUE TITLE
DLib Extremely long to compile with clang on windows

### ISSUE THREAD

**Issue by edubois** [davisking/dlib#1172]
## Expected Behavior
Reasonable compilation time

## Current Behavior
Compilation with clang on windows on a 20 core machine is taking approx. 20 minutes to compile this net architecture:
https://arxiv.org/pdf/1611.09326.pdf

My question is more, is there any trick that I could use? With Visual Studio standard toolset, it's not even compiling, but VC is not a good C++ compiler.

## Steps to Reproduce
Unfortunately I cannot provide any code.

* **Version**: master asof March 2018.
* **Where did you get dlib**: this github
* **Platform**: 64 bits Windows 7
* **Compiler**: LLVM Clang + MSVC linker

**Comment by xsacha** [comment]
Make sure you use 64-bit compiler on Windows. By default it picks 32-bit which usually runs out of memory compiling heavily templates code like dlib.

**Comment by reunanen** [comment]
@edubois, is the dlib implementation of this specific network architecture available somewhere?

**Comment by edubois** [comment]
@reunanen : Yes: https://arxiv.org/pdf/1611.09326.pdf

**Comment by reunanen** [comment]
@edubois Hmm, to me it looks like Theano / Lasagne, and not dlib?

**Comment by edubois** [comment]
I'm not sure I understand, but unfortunately, there are no dlib implementation public / that I can make public.
Because of this problem, and for this kind of network, I'm thinking of switching to caffe2.

**Comment by isgursoy** [comment]
Following
