### ISSUE TITLE
problem of train fhog

### ISSUE THREAD

**Issue by Jialeen** [davisking/dlib#1175]
When I used "fhog_object_detector_ex.cpp" to train my own model, I met the question:
exception thrown!
An impossible set of object labels was detected. This is happening because none
of the object locations checked by the supplied image scanner is a close enough
match to one of the truth boxes in your training dataset. To resolve this you 
need to either lower the match_eps, adjust the settings of the image scanner so
that it is capable of hitting this truth box, or adjust the offending truth 
rectangle so it can be matched by the current image scanner. Also, if you are 
using the scan_fhog_pyramid object then you could try using a finer image 
pyramid. Additionally, the scan_fhog_pyramid scans a fixed aspect ratio box 
across the image when it searches for objects. So if you are getting this error
and you are using the scan_fhog_pyramid, it's very likely the problem is that 
your training dataset contains truth rectangles of widely varying aspect 
ratios. The solution is to make sure your training boxes all have about the 
same aspect ratio. 

image index              248
match_eps:               0.5
best possible match:     0.389663
truth rect:              [(461, 158) (477, 208)]
truth rect width/height: 0.333333
truth rect area:         867
nearest detection template rect:              [(453, 133) (477, 221)]
nearest detection template rect width/height: 0.280899
nearest detection template rect area:         2225
=========================================
The code modified by me contained removing test and the detection window size (scanner.set_detection_window_size(32, 96) ). The box information in xml file is as follows:
 <image file="set00v004137.jpg">
        <box top="141" left="529" width="24" height="72"/>
    </image>
    <image file="set00v004139.jpg">
        <box top="140" left="532" width="25" height="75"/>
    </image>
    <image file="set00v004140.jpg">
        <box top="140" left="534" width="25" height="75"/>
    </image>
    <image file="set00v004141.jpg">
        <box top="140" left="536" width="25" height="75"/>
    </image>
    <image file="set00v004142.jpg">
        <box top="140" left="537" width="25" height="75"/>
    </image>
    <image file="set00v004146.jpg">
        <box top="144" left="544" width="21" height="63"/>
    </image>
    <image file="set00v004147.jpg">
        <box top="144" left="545" width="22" height="66"/>
    </image>
    <image file="set00v004149.jpg">
        <box top="144" left="550" width="23" height="69"/>
    </image>
    <image file="set00v004150.jpg">
        <box top="143" left="552" width="24" height="72"/>
    </image>
    <image file="set00v004151.jpg">
        <box top="143" left="555" width="25" height="75"/>
    </image>
    <image file="set00v004152.jpg">
        <box top="142" left="556" width="26" height="78"/>
    </image>
I tried many methods, but no one worked. 
Could you please tell me how to solve the problem.
Thank you very much

**Comment by xueliang** [comment]
DO you sovled this issue? I met the similar problem.
