### ISSUE TITLE
Ubuntu, pip3 install dlib (compile error: can not find "Python.h")

### ISSUE THREAD

**Issue by kilho** [davisking/dlib#1176]
Hello

Ubuntu, pip3 install dlib (compile error: can not find "Python.h")

I think I have installed all the requirements including python3-dev. And, I see the "Python.h" file in /usr/include/python3.5 but the compiler can not see that. Since pip install is automatic, it is not easy to include paths for compiling.

tried
pip3 install --global-option=build_ext --global-option="-I/usr/include/python3.5/" --global-option="-L/usr/lib/python3.5" dlib
but didn't work

**Comment by kilho** [comment]
Hello

I think I have installed all the requirements including python3-dev. And, I see the "Python.h" file in /usr/include/python3.5 but the compiler can not see that. Since pip install is automatic, it is not easy to include the path for compiling.

tried 
pip3 install --global-option=build_ext --global-option="-I/usr/include/python3.5/" --global-option="-L/usr/lib/python3.5" dlib
but didn't work

**Comment by davisking** [comment]
Read the issue submission instructions.
