### ISSUE TITLE
Visual Studio 2017 15.6.1 produces [[nodiscard]] compiler warning in old_deserialize_floating_point in serialize.h

### ISSUE THREAD

**Issue by jjaloszy2** [davisking/dlib#1179]
## Expected Behavior
old_deserialize_floating_point generates an unexpected warning.   It looks like the second call may have intended to set the flags, since the flags are saved and later restored.  Please consider removing the second call to in.flags() in old_deserialize_floating_point.

## Current Behavior
Visual Studio 15.6.1 adds the [[nodiscard]] attribute to istream::flags().  There are 2 calls in.flags() at the top of old_deserialize_floating_point.   The return value of the second call is not used.  It looks like this second call has no effect; the warning may be legitimate.

## Steps to Reproduce
I was able to produce this by including <dlib/matrix/matrix.h> in a source file and compiling it with VS 2017 15.6.1 as a 64 bit executable, in debug mode.  I suspect any file including serialize.h may generate the warning.

* **Version**: 18.16.    This code is still present in serialize.h in current code on github.
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 10 1709, 64 bit.
* **Compiler**: Visual Studio 2017 15.6.1 64 bit

**Comment by davisking** [comment]
Yep, that looks legit.  You want to submit the change as a PR?

**Comment by jjaloszy2** [comment]
I can though I’m not sure if this detected a real problem.   Do you think the correct thing to do is just to remove the second .flags() call?  Was it intended to set the flags instead?    If it’s not setting the flags, the code that saves & restores the flags might also be unnecessary.  Thoughts?

Regards,

Jon

**Comment by davisking** [comment]
The second call should clear the flags, and so should be something like
in.flags(0);

**Comment by faboules** [comment]
I can though I’m not sure if this detected a real problem.   Do you think the correct thing to do is just to remove the second .flags() call?  Was it intended to set the flags instead?    If it’s not setting the flags, the code that saves & restores the flags might also be unnecessary.  Thoughts?

**Comment by davisking** [comment]
Fixed by https://github.com/davisking/dlib/pull/1190
