### ISSUE TITLE
ubuntu cuDNN doesn't get picked up by cmake

### ISSUE THREAD

**Issue by tobyclh** [davisking/dlib#1181]
## Expected Behavior
build with CUDA support 

## Current Behavior
cudnn doesn't get detect and build without CUDA support

## Steps to Reproduce
Install ubuntu 16.04 
install cuda and cudnn through ubuntu deb package
build with python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA
when install cudnn manually dlib build flawlessly.
* **Version**: 
* **Where did you get dlib**:  master
* **Platform**:  ubuntu 16.04
* **Compiler**: 
ubuntu default gcc 5.4

**Comment by davisking** [comment]
I use it all the time in Ubuntu with the regular package.  Moreover, READ THE ISSUE TEMPLATE INSTRUCTIONS.  What you posted is not useful and does not follow the instructions.
