### ISSUE TITLE
Unchecked Return Values

### ISSUE THREAD

**Issue by Marisamy01** [davisking/dlib#1186]
There seems to be lot of unchecked return values in the dlib project

It wil be very helpful if u cud solve tis

I have mentioned one such instance below

File: /tools/imglab/src/cluster.cpp
Method:
double mean_aspect_ratio (
 sum += rect.width()/(double)rect.height();

**Comment by davisking** [comment]
This isn't a bug. And please stop posting these auto generated messages.
