### ISSUE TITLE
Compilation error find_min_bobyqa.h 

### ISSUE THREAD

**Issue by tagaf** [davisking/dlib#1194]
================================================================== -->

## Expected Behavior
Successful Compilation of find_min_bobyqa.h .
## Current Behavior
Compiling fails when using find_min_bobyqa, while does not when using find_min_global for example.
Error: find_min_bobyqa.h Line 878: term does not evaluate to a function taking 1 argument.
How can I solve this problem? 
Thanks, have a good day.

* **Version**: 19.9
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 32bit
* **Compiler**: Visual Studio 2017

**Comment by davisking** [comment]
This does not constitute filling out the issue template.  Read the instructions.
