### ISSUE TITLE
https://github.com/davisking/dlib/issues/653

### ISSUE THREAD

**Issue by User198101** [davisking/dlib#1197]
Hi.

I'm using dlib 19.8. Writing my codes on windows platform for Android devices.

I've the codes below as part of the face detection function.

// .. some codes before this
dlib::cv_image<dlib::bgr_pixel> cimg(img);
std::vector<dlib::rectangle> faces = detector(cimg);
// .. some codes after this

img is my image loaded from a local jpg file to opencv Mat.

The above codes are part of a function that gets called continuously as new img gets streamed in from the camera.

Line (2) of the codes caused the program on Android to crash.
The crash does not happen immediately, it will happen only after x number of iteration.

If my image is large, the crash happens faster. That means the x number is smaller.
If my image is small, the crash happens later. That means it takes longer iteration before crash occurs. x is larger.
If there is no face detected in the img, it still crash but it takes much longer before crash occurs. x is largest.

If I remove the line (2), no crash happens.
After some investigation, it seems to me that there is memory leak for the function call detector(cimg).

Is this a bug?

Thank you.
Marc

**Comment by davisking** [comment]
You probably deleted the underlying image memory at some point.  But in any case, this isn't a bug in dlib.  You have to debug your own code.
