### ISSUE TITLE
Interesting paper  for you

### ISSUE THREAD

**Issue by DarioBernardo** [davisking/dlib#1202]
Hey, first of all thank you for your work. The quality of your code and documentation is impressive. 
I just wanted to point you out this [paper](https://arxiv.org/abs/1506.02640). It is also implemented [here](https://pjreddie.com/darknet/yolo/) I'd like to hear your thoughts about it. Do you think could be an improvement on your CNN Max-Margin object detection? The reported performances are quite impressive.

Furthermore, could you point me out some python examples for training a classifier for detecting front/rear cars (as an example, or any other object) instead of faces. I saw your C++ examples but unfortunately I am not familiar with C++ and would prefer stick with python. Thank you.

**Comment by davisking** [comment]
Thanks, glad you like dlib.

Yes, I'm familiar with that paper. 

Unfortunately, there isn't a python interface for training.  You should use the C++ code for that.
