### ISSUE TITLE
[Question] cnn face recognition 

### ISSUE THREAD

**Issue by MartyEz** [davisking/dlib#1203]
Hi,
I have a question about this topic :
http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html

i have a question about the way the cnn works with a person or two which are not present in  the database used for training

The neural network is trained with 7485 persons. But it can recognize a person which is not is the database.
The tested person will be close to the trained person with she shares the most physical similarities ? 

Thanks

**Comment by davisking** [comment]
No. That's not at all how it works.  The trained people are irrelevant.
The network embeds people into a vector space such that images of the same
person will be close to each other.

**Comment by MartyEz** [comment]
Ok thank you, i should read dnn_metric examples. Thanks
