### ISSUE TITLE
unable to build dnn_mmod_train_find_cars_ex.cpp

### ISSUE THREAD

**Issue by jangstar** [davisking/dlib#1206]
## Current Behavior

I creaed my own .xml files for both training and testing sets in order to use the example of mmod_train_find cars_ex.cpp. However,it gave me some of lnk2005 errors. 

these are

LNK2005 "bool __cdecl dlib::cuda::can_access_peer(class dlib::tensor const &, class dlib::tensor const &)" (?can_access_peer@cuda@dlib@@YA_NAEBVtensor@2@0@Z) already defined in dlib_19.1.lib(dlib_generated_cuda_dlib.cu.obj)
LNK2005 "void __cdel dlib::cuda::device_synchronize(int)" (?device_synchronize@cuda@dlib@@YAXH@Z)already defined in dlib_19.1.lib(dlib_generated_cuda_dlib.cu.obj)
LNK2005 "int __cdel dlib::cuda::get_device(void)" (?get_device@cuda@dlib@@YAHXZ) already defined in dlib_19.1.lib(dlib_generated_cuda_dlib.cu.obj)
NLK2005 "void __cdel dlib::cuda::set_device(int)" (?set_device@cuda@dlib@@YAXH@Z) already defined in dlib_19.1.lib(dlib_generated_cuda_dlib.cu.obj)
LNK1169 one or more multiply defined symbols found

I used cmake and type the exact commands in the "dlib.net/compile.html" instruction. only mmod_traind_findcars_example is not working. other cpp examples such as find cars, face detection are working. 
## Steps to Reproduce

* **Version**:  19.1
* **Where did you get dlib**:  dlib.net
* **Platform**:  64 bit, visual studio 15, cuda 9.1 and cudnn is 7.1.2
* **Compiler**:

**Comment by davisking** [comment]
Use the new version of dlib and fill out the issue template (and read it's instructions in their entirety).

**Comment by fizmatbfu** [comment]
I have same problem. I use newest version of Dlib (19.16), CUDA 10, cudnn 7.4.1.5. 
Platform: win64, visual studio 15, dlib was building with cmake (with cuda support).

**Comment by davisking** [comment]
Fill out the issue template
