### ISSUE TITLE
 trying to install dlib 18.16 in python2.7 in ubuntu 

### ISSUE THREAD

**Issue by aaganaie** [davisking/dlib#1207]
I am trying to install dlib 18.16 in python2.7 in my ubuntu  when i use command  cmake --build . --config Release it shows me an error 'reference to list is ambigous'

[ 75%] Building CXX object CMakeFiles/dlib_.dir/src/other.cpp.o
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:56:1: error: reference to ‘list’ is ambiguous
 list _max_cost_assignment (
 ^
In file included from /usr/local/include/boost/python/dict.hpp:11:0,
                 from /usr/local/include/boost/python.hpp:24,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/local/include/boost/python/list.hpp:57:7: note: candidates are: class boost::python::list
 class list : public detail::list_base
       ^
In file included from /usr/include/c++/5/list:63:0,
                 from /usr/local/include/boost/detail/container_fwd.hpp:92,
                 from /usr/local/include/boost/functional/hash/extensions.hpp:22,
                 from /usr/local/include/boost/functional/hash/hash.hpp:594,
                 from /usr/local/include/boost/functional/hash.hpp:6,
                 from /usr/local/include/boost/type_index/stl_type_index.hpp:46,
                 from /usr/local/include/boost/type_index.hpp:29,
                 from /usr/local/include/boost/function/function_base.hpp:21,
                 from /usr/local/include/boost/function/detail/prologue.hpp:17,
                 from /usr/local/include/boost/function/function_template.hpp:13,
                 from /usr/local/include/boost/function/detail/maybe_include.hpp:15,
                 from /usr/local/include/boost/function/function0.hpp:11,
                 from /usr/local/include/boost/python/errors.hpp:13,
                 from /usr/local/include/boost/python/handle.hpp:11,
                 from /usr/local/include/boost/python/args_fwd.hpp:10,
                 from /usr/local/include/boost/python/args.hpp:10,
                 from /usr/local/include/boost/python.hpp:11,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/include/c++/5/bits/stl_list.h:507:11: note:                 template<class _Tp, class _Alloc> class std::__cxx11::list
     class list : protected _List_base<_Tp, _Alloc>
           ^
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:69:11: error: reference to ‘list’ is ambiguous
     const list& assignment
           ^
In file included from /usr/local/include/boost/python/dict.hpp:11:0,
                 from /usr/local/include/boost/python.hpp:24,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/local/include/boost/python/list.hpp:57:7: note: candidates are: class boost::python::list
 class list : public detail::list_base
       ^
In file included from /usr/include/c++/5/list:63:0,
                 from /usr/local/include/boost/detail/container_fwd.hpp:92,
                 from /usr/local/include/boost/functional/hash/extensions.hpp:22,
                 from /usr/local/include/boost/functional/hash/hash.hpp:594,
                 from /usr/local/include/boost/functional/hash.hpp:6,
                 from /usr/local/include/boost/type_index/stl_type_index.hpp:46,
                 from /usr/local/include/boost/type_index.hpp:29,
                 from /usr/local/include/boost/function/function_base.hpp:21,
                 from /usr/local/include/boost/function/detail/prologue.hpp:17,
                 from /usr/local/include/boost/function/function_template.hpp:13,
                 from /usr/local/include/boost/function/detail/maybe_include.hpp:15,
                 from /usr/local/include/boost/function/function0.hpp:11,
                 from /usr/local/include/boost/python/errors.hpp:13,
                 from /usr/local/include/boost/python/handle.hpp:11,
                 from /usr/local/include/boost/python/args_fwd.hpp:10,
                 from /usr/local/include/boost/python/args.hpp:10,
                 from /usr/local/include/boost/python.hpp:11,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/include/c++/5/bits/stl_list.h:507:11: note:                 template<class _Tp, class _Alloc> class std::__cxx11::list
     class list : protected _List_base<_Tp, _Alloc>
           ^
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp: In function ‘double _assignment_cost(const dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, const int&)’:
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:72:72: error: no matching function for call to ‘python_list_to_vector(const int&)’
     return assignment_cost(cost, python_list_to_vector<long>(assignment));
                                                                        ^
In file included from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6:0,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:29:16: note: candidate: template<class T> std::vector<T> python_list_to_vector(const boost::python::api::object&)
 std::vector<T> python_list_to_vector (
                ^
/home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:29:16: note:   template argument deduction/substitution failed:
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:72:72: note:   cannot convert ‘assignment’ (type ‘const int’) to type ‘const boost::python::api::object&’
     return assignment_cost(cost, python_list_to_vector<long>(assignment));
                                                                        ^
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp: In function ‘void bind_other()’:
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:89:32: error: ‘_max_cost_assignment’ was not declared in this scope
     def("max_cost_assignment", _max_cost_assignment, (arg("cost")),
                                ^
CMakeFiles/dlib_.dir/build.make:206: recipe for target 'CMakeFiles/dlib_.dir/src/other.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_.dir/src/other.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_.dir/all' failed
make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
arshad@arshad-SVE1513ACNB:~/src/dlib-18.16/python_examples/build$ cmake --build
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
arshad@arshad-SVE1513ACNB:~/src/dlib-18.16/python_examples/build$ cmake --build . --config Release
[ 73%] Built target dlib
[ 75%] Building CXX object CMakeFiles/dlib_.dir/src/other.cpp.o
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:56:1: error: reference to ‘list’ is ambiguous
 list _max_cost_assignment (
 ^
In file included from /usr/local/include/boost/python/dict.hpp:11:0,
                 from /usr/local/include/boost/python.hpp:24,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/local/include/boost/python/list.hpp:57:7: note: candidates are: class boost::python::list
 class list : public detail::list_base
       ^
In file included from /usr/include/c++/5/list:63:0,
                 from /usr/local/include/boost/detail/container_fwd.hpp:92,
                 from /usr/local/include/boost/functional/hash/extensions.hpp:22,
                 from /usr/local/include/boost/functional/hash/hash.hpp:594,
                 from /usr/local/include/boost/functional/hash.hpp:6,
                 from /usr/local/include/boost/type_index/stl_type_index.hpp:46,
                 from /usr/local/include/boost/type_index.hpp:29,
                 from /usr/local/include/boost/function/function_base.hpp:21,
                 from /usr/local/include/boost/function/detail/prologue.hpp:17,
                 from /usr/local/include/boost/function/function_template.hpp:13,
                 from /usr/local/include/boost/function/detail/maybe_include.hpp:15,
                 from /usr/local/include/boost/function/function0.hpp:11,
                 from /usr/local/include/boost/python/errors.hpp:13,
                 from /usr/local/include/boost/python/handle.hpp:11,
                 from /usr/local/include/boost/python/args_fwd.hpp:10,
                 from /usr/local/include/boost/python/args.hpp:10,
                 from /usr/local/include/boost/python.hpp:11,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/include/c++/5/bits/stl_list.h:507:11: note:                 template<class _Tp, class _Alloc> class std::__cxx11::list
     class list : protected _List_base<_Tp, _Alloc>
           ^
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:69:11: error: reference to ‘list’ is ambiguous
     const list& assignment
           ^
In file included from /usr/local/include/boost/python/dict.hpp:11:0,
                 from /usr/local/include/boost/python.hpp:24,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/local/include/boost/python/list.hpp:57:7: note: candidates are: class boost::python::list
 class list : public detail::list_base
       ^
In file included from /usr/include/c++/5/list:63:0,
                 from /usr/local/include/boost/detail/container_fwd.hpp:92,
                 from /usr/local/include/boost/functional/hash/extensions.hpp:22,
                 from /usr/local/include/boost/functional/hash/hash.hpp:594,
                 from /usr/local/include/boost/functional/hash.hpp:6,
                 from /usr/local/include/boost/type_index/stl_type_index.hpp:46,
                 from /usr/local/include/boost/type_index.hpp:29,
                 from /usr/local/include/boost/function/function_base.hpp:21,
                 from /usr/local/include/boost/function/detail/prologue.hpp:17,
                 from /usr/local/include/boost/function/function_template.hpp:13,
                 from /usr/local/include/boost/function/detail/maybe_include.hpp:15,
                 from /usr/local/include/boost/function/function0.hpp:11,
                 from /usr/local/include/boost/python/errors.hpp:13,
                 from /usr/local/include/boost/python/handle.hpp:11,
                 from /usr/local/include/boost/python/args_fwd.hpp:10,
                 from /usr/local/include/boost/python/args.hpp:10,
                 from /usr/local/include/boost/python.hpp:11,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:6,
                 from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/usr/include/c++/5/bits/stl_list.h:507:11: note:                 template<class _Tp, class _Alloc> class std::__cxx11::list
     class list : protected _List_base<_Tp, _Alloc>
           ^
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp: In function ‘double _assignment_cost(const dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, const int&)’:
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:72:72: error: no matching function for call to ‘python_list_to_vector(const int&)’
     return assignment_cost(cost, python_list_to_vector<long>(assignment));
                                                                        ^
In file included from /home/arshad/src/dlib-18.16/dlib/../dlib/python.h:6:0,
                 from /home/arshad/src/dlib-18.16/tools/python/src/other.cpp:4:
/home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:29:16: note: candidate: template<class T> std::vector<T> python_list_to_vector(const boost::python::api::object&)
 std::vector<T> python_list_to_vector (
                ^
/home/arshad/src/dlib-18.16/dlib/../dlib/python/boost_python_utils.h:29:16: note:   template argument deduction/substitution failed:
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:72:72: note:   cannot convert ‘assignment’ (type ‘const int’) to type ‘const boost::python::api::object&’
     return assignment_cost(cost, python_list_to_vector<long>(assignment));
                                                                        ^
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp: In function ‘void bind_other()’:
/home/arshad/src/dlib-18.16/tools/python/src/other.cpp:89:32: error: ‘_max_cost_assignment’ was not declared in this scope
     def("max_cost_assignment", _max_cost_assignment, (arg("cost")),
                                ^
CMakeFiles/dlib_.dir/build.make:206: recipe for target 'CMakeFiles/dlib_.dir/src/other.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_.dir/src/other.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_.dir/all' failed
make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davisking** [comment]
This is an ancient version of dlib.  Use a new dlib.

**Comment by aaganaie** [comment]
I first installed dlib 19.10 . I actually want to use dlib with openface but when i called facePredictor function , it showed an error - Unexpected version found while deserializing dlib::shape_predictor

That is why i tred to use dlib 18.16 but while building that I always get an error of - reference kist ambigous

**Comment by davisking** [comment]
The shape predictor version hasn’t changed. Using the old version shouldn’t fix that. You are just loading the wrong file or making some other simple error.
