### ISSUE TITLE
Python dlib => no extract_image_chips() and get_face_chip_details()

### ISSUE THREAD

**Issue by joeking11829** [davisking/dlib#121]
Hi All,

I want to use dlib face alignment in my python program.
but, i cannot find method extract_image_chips() and get_face_chip_details() .

if i want to get alignment face using python dlib.
Should I implement it by myself or i missed something !?

Any comment !?

**Comment by davisking** [comment]
Right, that's not in the pyhton API

**Comment by AbdealiJK** [comment]
@davisking Any particular reason for that ?
Could you point in the direction to how someone can add it to the API ?

**Comment by davisking** [comment]
There is no reason, just haven't gotten around to it.

All the code for the pyhton API is in the tools/python folder.

**Comment by e-fominov** [comment]
Anybody working add this functions into python interface?

**Comment by vinnitu** [comment]
I need it too.
Anybody have python wrapper yet?
