### ISSUE TITLE
GTX1080Ti+cuda9.0+cuda7.0.3 build error

### ISSUE THREAD

**Issue by reach-xx** [davisking/dlib#1211]
I use dlib19.10 to install GPU version compile error? 
Operation is as follows：
$cd dlib-19.10
$mkdir build
$cd build
$cmake ..
The error is as follows：
*****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/yang/reach/dlib-19.10/build/dlib/cuda_test_build
   ***   
   ***   Run Build Command:"/usr/bin/make"
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   /usr/include/c++/5/functional(78): error: class "std::thread" has no member "result_type"
   ***             detected during:
   ***               instantiation of class "std::_Maybe_get_result_type<_Functor, void> [with _Functor=std::thread]" 
   ***   (86): here
   ***               instantiation of class "std::_Weak_result_type_impl<_Functor> [with _Functor=std::thread]" 
   ***   (184): here
   ***               instantiation of class "std::_Weak_result_type<_Functor> [with _Functor=std::thread]" 
   ***   (264): here
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   /usr/include/c++/5/functional(266): error: class "std::thread" has no member "argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   /usr/include/c++/5/functional(267): error: class "std::thread" has no member "first_argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   /usr/include/c++/5/functional(268): error: class "std::thread" has no member "second_argument_type"
   ***             detected during:
   ***               instantiation of class "std::_Reference_wrapper_base_impl<true, true, _Tp> [with _Tp=std::thread]" 
   ***   (283): here
   ***               instantiation of class "std::_Reference_wrapper_base<_Tp> [with _Tp=std::thread]" 
   ***   (399): here
   ***               instantiation of class "std::reference_wrapper<_Tp> [with _Tp=std::thread]" 
   ***   /usr/include/c++/5/future(1638): here
   ***   
   ***   4 errors detected in the compilation of "/tmp/tmpxft_00006476_00000000-7_cuda_test.cpp1.ii".
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:262 (message):
   ***     Error generating file
   ***     /home/yang/reach/dlib-19.10/build/dlib/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***   
   ***   
   ***   CMakeFiles/cuda_test.dir/build.make:63: recipe for target 'CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o' failed
   ***   make[2]: *** [CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cuda_test.dir/all' failed
   ***   make[1]: *** [CMakeFiles/cuda_test.dir/all] Error 2
   ***   Makefile:83: recipe for target 'all' failed
   ***   make: *** [all] Error 2
   ***   
-- *****************************************************************************************************************
**CUDA version**： cuda9.0+cudnn7.0.3
**Platform**:    ubuntu 16.0.4
**GCC version**:    gcc-5.4.0
**dlib**:    19.10   （Download from official website）

In this environment, I use tensorflow to enable normal GPU training. What is the reason for dlib compiling?

**Comment by davisking** [comment]
Use a compiler supported by cuda. http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by reach-xx** [comment]
Dear Davis E. King:
       Will I need to install the following environment to compile Dlib normally?
        CUDA version： CUDA9.1 + cudnn7.1
        GCC version: 5.3.1
         dlib-19.10
