### ISSUE TITLE
How to decode the binary .dat face recognition models into tensor flow or in python?

### ISSUE THREAD

**Issue by s0r2637** [davisking/dlib#1215]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

**I searched for this question in google and dlib forum (here), and I didn't find a solution.  Basically, I am interested in a transfer learning of the face recognition model (http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2).  I want to know the deserialization schema.  I don't understand the comments given in serialize.h.  In simple, I was wondering if there is a way to read the .dat file in a json format in Python.**  

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by davisking** [comment]
Convert the network to xml using net_to_xml().

**Comment by s0r2637** [comment]
**Hi Davis,
I quickly saw the net_to_xml() in utilities folder.  I was wondering what network type can be converted to xml.  Is it both net_type and anet_type? Or just the net_type network.  Maybe they are the same, but I wanted to make sure.  So the steps would be to:

1) deserialize the .dat file into a anet_type object

2) run the net_to_xml() method on the anet_type object with the filename.

Please correct me if I am wrong here.**
