### ISSUE TITLE
DNN convert 128D vector slow

### ISSUE THREAD

**Issue by backylee** [davisking/dlib#1217]
Hi davisking

i use dlib to face recognition in real time stream, without 128D vector compare, the program can reach 10fps. when add DNN convert 128D vector, its slower.
`               using anet_type = loss_metric<fc_no_bias<128, avg_pool_everything<`
`	                  alevel0<`
`                         alevel1<`
`                         alevel2<`
`                         alevel3<`
`                         alevel4<`
`                         max_pool<3, 3, 2, 2, relu<affine<con<32, 7, 7, 2, 2,`
`                         input_rgb_image_sized<150>`
`                         >>>>>>>>>>>>;`
` `
`               clock_t vstart; `
`                vstart = clock();`
`                face_descriptors = net(faces);`
`                cout << "clock: " << clock() - vstart  << endl;`

DNN net get 128D vector cost almost 500ms,  slower than python versoin.

any idea to make DNN convertion faster?
thx

**

- Version: dlib 19.10
- Platform: win7 64bit 
- Where did you get dlib:  dlib.net
- Compiler: Visual Studio2015 x64 release mode

**

**Comment by davisking** [comment]
Link to the Intel MLK or use CUDA.
