### ISSUE TITLE
face vectors for dissimilar faces are matching

### ISSUE THREAD

**Issue by vijaysagi1** [davisking/dlib#1218]
## Expected Behavior
Technically we are using **face_recognition.py** for face recognition, the cosine similarity between the two faces  is 95%

In our case we have set the thresold vlaue of 93% of above and over is the same face. If we increase the thresold value to 95% lot of correct match faces are missing. Pls suggest what best can be done.

I cannot share the faces publicly,pls suggest the best way of sharing the images offline

* **Version**: dlib 19.9
* **Where did you get dlib**:https://pypi.python.org/pypi/dlib
* **Platform**: ubuntu 16.04,  64 bit
* **Compiler**: python 2.7

**Comment by davisking** [comment]
Nothing is perfect.  The public model is also trained on a dataset heavily
biased towards US faces. If you want to make it work better you need to
train a new model with more diverse training data.

**Comment by xxllp** [comment]
@davisking ，I think I have to train an new model ,because I find woman in my pics have smilar distance （0.5-0.7）。but man offen have good performance 。why?

**Comment by vijaysagi1** [comment]
i think we need to train custom dataset, pls suggest using python how can i train to create custom **dlib_face_recognition_resnet_model_v1.dat** file.

**Comment by davisking** [comment]
You can't do it in python.  This C++ example shows how to do it though: http://dlib.net/dnn_metric_learning_on_images_ex.cpp.html
