### ISSUE TITLE
how to get my own own mean_face_shape_x/y in get_face_chip_details if i train my own models?

### ISSUE THREAD

**Issue by wqvbjhc** [davisking/dlib#122]
1.the mean_face_shape_x/y in get_face_chip_details is hard codeing. how can i custom my own mean_face_shape_x/y if i use 5 point landmark?
2.by the way, i found that the initial_shape in shape_predictor_68_face_landmarks.dat is not equal to the mean_face_shape_x/y in get_face_chip_details. if i train your own models, how can i to get my own mean_face_shape_x/y?

**Comment by wqvbjhc** [comment]
the initial_shape in shape_predictor_68_face_landmarks.dat is as follow: 
>initial_shape=(136,1)
0.029446        0.321950        0.032626        0.446431        0.045943
0.570428        0.071791        0.692023        0.120274        0.804951
0.194731        0.902886        0.285819        0.984597        0.386310
1.050212        0.500003        1.069708        0.613697        1.050210
0.714190        0.984596        0.805277        0.902887        0.879741
0.804952        0.928229        0.692024        0.954078        0.570430
0.967397        0.446431        0.970579        0.321947        0.119182
0.230909        0.177509        0.178388        0.259835        0.162735
0.345086        0.174880        0.424904        0.208063        0.575140
0.208059        0.654959        0.174876        0.740211        0.162732
0.822538        0.178384        0.880866        0.230908        0.500021
0.305547        0.500017        0.385739        0.500015        0.465222
0.500011        0.547027        0.404506        0.602343        0.450375
0.619234        0.500013        0.633663        0.549654        0.619236
0.595526        0.602348        0.213870        0.315571        0.264750
0.286316        0.325858        0.287176        0.379375        0.327564
0.322083        0.337778        0.261248        0.336975        0.620667
0.327560        0.674184        0.287173        0.735291        0.286312
0.786169        0.315570        0.738790        0.336972        0.677958
0.337776        0.317107        0.751117        0.384429        0.724204
0.452547        0.710256        0.500013        0.721995        0.547484
0.710262        0.615600        0.724211        0.682923        0.751117
0.617772        0.816892        0.551586        0.846004        0.500013
0.851504        0.448439        0.846000        0.382257        0.816887
0.345192        0.754674        0.451943        0.749935        0.500013
0.755041        0.548087        0.749940        0.654835        0.754675
0.549021        0.785685        0.500015        0.791599        0.451010
0.785681

**Comment by davisking** [comment]
I'm not sure what to say.  If you want to know the mean of your own model then add up a bunch of outputs of your model and divide by the number of instances.  Then you can write a function similar to get_face_chip_details using your mean face and clip out chips however you want.
