### ISSUE TITLE
[iOS] Dog hipsterizer linker error

### ISSUE THREAD

**Issue by AndrGolubkov** [davisking/dlib#1229]
Hi, 
I'm use open source C++ toolkit for iOS app. In the application, I try to implement an example "dnn_mmod_dog_hipsterizer", but during linking Xcode show such errors:
Undefined symbols for architecture arm64:
"dlib::tt::relu(dlib::tensor&, dlib::tensor const&)", referenced from: dlib::relu_::forward_inplace(dlib::tensor const&, dlib::tensor&)
"dlib::tt::affine_transform(dlib::tensor&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&)", referenced from: dlib::affine_::forward_inplace(dlib::tensor const&, dlib::tensor&)
"dlib::tt::affine_transform_conv(dlib::tensor&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&)", referenced from: dlib::affine_::forward_inplace(dlib::tensor const&, dlib::tensor&)
"dlib::cpu::tensor_conv::operator()(bool, dlib::resizable_tensor&, dlib::tensor const&, dlib::tensor const&)", referenced from: dlib::tt::tensor_conv::operator()(bool, dlib::resizable_tensor&, dlib::tensor const&, dlib::tensor const&)
"dlib::tt::add(float, dlib::tensor&, float, dlib::tensor const&)"

I'm using the version of the library 19.10. 

Any idea what these errors can be caused?

**Comment by davisking** [comment]
Fill out the issue template.
