### ISSUE TITLE
Easy downloading of helper files

### ISSUE THREAD

**Issue by AbdealiJK** [davisking/dlib#123]
It would be nice to provide an easy function or method to download the helper files by code.

For example, in http://dlib.net/face_landmark_detection.py.html it says the facial shape detector can be downloaded in the help message. But if I want to use this shape detector, it would be nice to have a simple function like `dlib.download_helpers('shape_predictor_68_face_landmarks', '/path/to/save/it/to')`.

Otherwise I'd have to implement downloading it myself when the function is run the first time in any library/app I want to make. This got further complicated for me because it seems the `.dat` files are different for different versions. i.e. 18.10's dat throws a Runtime error with `Unexpected version found while deserializing dlib::shape_predictor.` if I run it with dlib 18.17.100.

To avoid all this, it would be nice to have the helper.

**Comment by AbdealiJK** [comment]
Oops, sorry. My conclusion about different versions needing different .dat files is invalid ... The error threw me on the wrong track. It seems like the md5sum of my file I was using is invalid. So, something wrong with the download.

But yeah - still easier if a helper is provided

**Comment by davisking** [comment]
You should download the file once and distribute it with your application.  I'm not going to make each invocation of the example wget a file, especially not a somewhat large file that needs to be decompressed.

**Comment by AbdealiJK** [comment]
I'm not suggesting the file be downloaded for each invocation either.
The file would be saved in a data directory of the system (Example:
`~/.local/dlib-data` for Linux)
Hence, this would automatically install the file in the first invocation,
and use the saved file after that for other invocations.

**Comment by davisking** [comment]
That's a good idea for an application that uses the face landmarking
system.  But the point of the example programs that come with dlib is to be
easy to understand tutorials, not end user applications.  This kind of
thing, while a good idea in a real program, would complicate the exposition
in the example program, making it harder to understand and therefore less
effective as an educational document, which is its primary purpose.

**Comment by AbdealiJK** [comment]
:+1:
