### ISSUE TITLE
dlib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by GitEasonXu** [davisking/dlib#1230]
## Expected Behavior

import dlib
ERROR:
ImportError: /home/xx/anaconda3/lib/python3.5/site-packages/dlib-19.10.0-py3.5-linux-x86_64.egg/dlib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE

## Steps to Reproduce

* **Version**: 
dlib-19.10
* **Installation method**: 
1. pip install dlib
   or
   2.reference install tutorial: http://dlib.net/compile.html
* **Platform**: 
Ubuntu 16.04
Anaconda3
* **Compiler**: 
python3.5

**Comment by davisking** [comment]
That error isn't about dlib. It means something is terribly wrong with your compiler. I also use dlib on ubuntu all the time without issue.  If you can post complete instructions to replicate this error on ubuntu I'll look into it. But you need to post what exactly someone types, starting from a standard ubuntu install.

**Comment by GitEasonXu** [comment]
Today，I reinstalled dlib on the system of Ubuntu 14.04 with python3.6 and it succeeded.
I think the Error may be related to python3.5。

**Comment by QuantumLiu** [comment]
I also got this problem on 
ubuntu16,
ananconda3,
python3.5
cuda9.0
cudnn7

**Comment by davisking** [comment]
Fill out the issue template

**Comment by GitEasonXu** [comment]
@QuantumLiu 
I encountered this problem again.
run: `conda install libgcc`
can solve this problem.
