### ISSUE TITLE
Will other face detector be compatible with dlib's shape predictor 68?

### ISSUE THREAD

**Issue by cfoch** [davisking/dlib#1232]
Hello. I want to explore using other face detectors like DNN/CNN or PICO and using a tracking system at the same time to give sense of "smoothness". After that, I want to find the landmark of the face based on the detectors' result. If I just use the shape_predictor_68_face_landmarks.dat.bz2 provided [here](https://github.com/davisking/dlib-models) is there a reason to think that it may be less accurate than using it with HOG dlib's face detector?

**Comment by davisking** [comment]
The only thing that matters is getting an initial bounding box aligned the
way dlib's HOG detector aligns it.

**Comment by cfoch** [comment]
And how does the HOG detector aligns the bounding box?
