### ISSUE TITLE
Tried to train profile shape predictor, but the model obtained doesn't fit well

### ISSUE THREAD

**Issue by chicn** [davisking/dlib#1233]
## What

Hi. I'm trying to train shape_predictor's model for profile faces since the provided model is not accurate enough for those faces.

## Issue

The model trained doesn't fit well to the test profile faces I prepared.

## Some other information

- The parameter I used for training were all default values.
- I used the pictures from [here](https://ibug.doc.ic.ac.uk/resources/300-W/) but only profile faces. So the number of train data was around 200.

If any of you also tried to train a model like this, please tell me the tips!! Thank you all :D

**Comment by davisking** [comment]
That's the dataset dlib's model is trained on. Making the dataset smaller isn't going to make the results better. Think about it.
