### ISSUE TITLE
build example train_shape_predictor_ex.cpp error

### ISSUE THREAD

**Issue by cheng33c** [davisking/dlib#1235]
ubuntu 18.04 g++ (Ubuntu 7.3.0-14ubuntu1) 7.3.0

dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<dlib::thread_pool_implementation::thread_pool_implementation(unsigned long)::{lambda()#1}> > >::~_State_impl()':
thread_pool_extension.cpp:(.text+0x1f): undefined reference to `std::thread::_State::~_State()'
dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `dlib::thread_pool_implementation::thread_pool_implementation(unsigned long)':
thread_pool_extension.cpp:(.text+0x130d): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<dlib::thread_pool_implementation::thread_pool_implementation(unsigned long)::{lambda()#1}> > >::~_State_impl()':
thread_pool_extension.cpp:(.text+0xb): undefined reference to `std::thread::_State::~_State()'
dlib_build/libdlib.a(thread_pool_extension.cpp.o):(.data.rel.ro+0x10): undefined reference to `typeinfo for std::thread::_State'
collect2: error: ld returned 1 exit status
CMakeFiles/train_shape_predictor_ex.dir/build.make:103: recipe for target 'train_shape_predictor_ex' failed
make[2]: *** [train_shape_predictor_ex] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/train_shape_predictor_ex.dir/all' failed
make[1]: *** [CMakeFiles/train_shape_predictor_ex.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davisking** [comment]
Fill out the issue template.
