### ISSUE TITLE
fatal error: dlib-master/dlib/dnn.h: No such file or directory

### ISSUE THREAD

**Issue by vijaysagi1** [davisking/dlib#1239]
My requirment is i need to train **renset.dat** with custom images

## Expected Behavior
The file **dnn_metric_learning_on_images_ex.cpp** should be compiled sucessfully

## Current Behavior
dnn_metric_learning_on_images_ex.cpp:29:34: fatal error: dlib/dnn.h: No such file or directory
compilation terminated.

## Steps to Reproduce
With the below command i tried to compile the code 
g++ dnn_metric_learning_on_images_ex.cpp -o dlibtest

* **Version**:  19.9.99
* **Where did you get dlib**: this github repo
* **Platform**: 64 bit
* **Compiler**:  5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by davisking** [comment]
Follow the instructions here: http://dlib.net/compile.html
