### ISSUE TITLE
Face tracking and landmark detection not accurate.

### ISSUE THREAD

**Issue by cfoch** [davisking/dlib#1240]
Hello, I need to speed up the face detector. So one of the options was to use a face tracker.

Procedure:
I am detecting a face in the first frame, then I create a tracker for the detected face. Then the tracker runs for the next frames until it loses its target. If the target is lost, the old tracker is deleted and a new tracker is created with the output of the face detector.

Problem:
If I apply the landmark detector over the tracker's ROI, then the landmark detection gets pretty innacurate sometimes.

Preview: https://www.youtube.com/watch?v=WozvmF1kaZU&feature=youtu.be
Legend:
- Cyan: OpenCV KCF Tracker (and landmark over the tracker's box)
- Blue: Dlib's HOG face detector (and landmark over the detected face bounding box)

Models used:
- Dlib frontal face detector default model
- Dlib 68 shape predictor 

Question: 
Is the problem of a not well-trained 68-landmark shape predictor? Or the problem is in the tracker?
If neither of both, what would be the problem and what else can I do?

**Comment by davisking** [comment]
The problem is the initial bounding box becoming too off for the shape
predictor to work correctly.  If you want to do this you should use the
shape predictor to correct the box position on each frame.  You will need
to match the box position that would have been given by dlib's detector.
