### ISSUE TITLE
In .cu file, when the number of Resnet layers increased, occured error "excessive recursion at instantiation of class dlib::add_layer<...>", how can use deep resnet in a .cu file?

### ISSUE THREAD

**Issue by YPeking** [davisking/dlib#1241]
## Code:
template <template <int, template<typename>class, int, typename> class block, int N, template<typename>class BN, typename SUBNET>
using residual = add_prev1<block<N, BN, 1, tag1<SUBNET>>>;

template <template <int, template<typename>class, int, typename> class block, int N, template<typename>class BN, typename SUBNET>
using residual_down = add_prev2<avg_pool<2, 2, 2, 2, skip1<tag2<block<N, BN, 2, tag1<SUBNET>>>>>>;

template <int N, template <typename> class BN, int stride, typename SUBNET>
using block = BN<con<N, 3, 3, 1, 1, relu<BN<con<N, 3, 3, stride, stride, SUBNET>>>>>;

template <int N, typename SUBNET> using ares = relu<residual<block, N, affine, SUBNET>>;
template <int N, typename SUBNET> using ares_down = relu<residual_down<block, N, affine, SUBNET>>;

template <typename SUBNET> using alevel0 = ares_down<512, SUBNET>;
template <typename SUBNET> using alevel1 = ares<512, ares<512, ares_down<512, SUBNET>>>;
template <typename SUBNET> using alevel2 = ares<256, ares<256, ares<256, ares<256,
	ares<256, ares<256, ares<256, ares<256,
	ares<256, ares<256, ares<256, ares<256,
	ares<256, ares<256, ares<256, ares<256,
	ares<256, ares_down<256, SUBNET>>>>>>>>>>>>>>>>>>;
template <typename SUBNET> using alevel3 = ares<128, ares<128, ares<128, ares_down<128, SUBNET>>>>;
template <typename SUBNET> using alevel4 = ares<64, ares<64, ares<64, SUBNET>>>;

using anet_type = loss_metric<fc_no_bias<128, avg_pool_everything<
	alevel0<
	alevel1<
	alevel2<
	alevel3<
	alevel4<
	max_pool<3, 3, 2, 2, relu<affine<con<64, 7, 7, 2, 2,
	input_rgb_image
	>>>>>>>>>>>>;

**Comment by davisking** [comment]
Use the repeat layer.

**Comment by faboules** [comment]
Thank you for show, Have Been using It on repeat

**Comment by YPeking** [comment]
Yeah, Thanks, this problem has been solved 😀。
but here is another question, I don't use repeat layers in training, and use repeat layers in .cu file, Is the Error  "dlib::serialization_error"  occurred by this reason?

**Comment by YPeking** [comment]
Yeah, Thanks, this problem has been solved😀。
But here is another question, I didn't use repeat layers in training model files, and I use repeat layers in .cu files. Is the error "dlib::serialization_error" caused by this reason?

**Comment by davisking** [comment]
Yes. That’s a problem. You must be consistent in your network definitions.
