### ISSUE TITLE
Compute_face_descriptor will not work with greyscale pictures

### ISSUE THREAD

**Issue by jjcasalo** [davisking/dlib#1242]
## Expected Behavior
I am running the Face Recognition sample (http://dlib.net/face_recognition.py.html), using dlib 19.8.1 and Python 3.6.
In a folder, I have some pictures (in JPG). Some of them are in color, and some in B&W.
I expect the script to handle all the pictures the same, whether they are color or B&W.

## Current Behavior
When I run the script, the color pictures are displayed correctly.
But when the script opens the B&W picture, I have this error message message : 
  face_descriptor = facerec.compute_face_descriptor(img, shape)
RuntimeError: Unsupported image type, must be RGB image

## Steps to Reproduce
 1) Take the script in http://dlib.net/face_recognition.py.html
 2) In a folder, add color and B&W pictures
 3) Run script, with the folder as parameter
 4) Errror message !

Thanks for your help

* **Version**: 19.8.1
* **Where did you get dlib**: https://pypi.python.org/simple/dlib/
* **Platform**: Windows 10 64-bit
* **Compiler**: I'm using the WHL provided by https://pypi.python.org/simple/dlib/

**Comment by davisking** [comment]
Convert the images to RGB.

**Comment by jjcasalo** [comment]
Hi,
 Thanks a lot.
Yes, I converted all the pictures to 24 BPP, and it worked.
