### ISSUE TITLE
cxx_thread_local requirement for Apple Clang

### ISSUE THREAD

**Issue by aldanor** [davisking/dlib#1243]
Apple's Clang (at least the older ones) apparently refuses to support cxx_thread_local (see [here](http://stackoverflow.com/questions/28094794/why-does-apple-clang-disallow-c11-thread-local-when-official-clang-supports) for details), wondering if it could be possibly removed from compile feature requirements in `use_cpp_11.cmake`?

**Comment by davisking** [comment]
No, it is needed.  Also, if you update clang it's been fixed for a while now.

**Comment by aldanor** [comment]
It fails on Clang 6.1.0 which is what Travis has apparently: https://travis-ci.org/conda-forge/dlib-feedstock/jobs/363818043 -- can't really control that.

... though it seems to compiles fine if `cxx_thread_local` requirement is removed via a patch: https://travis-ci.org/conda-forge/dlib-feedstock/jobs/363823745 

(however the latter still fails because of `LLVM ERROR: Cannot select: intrinsic %llvm.x86.sse41.blendvps` which didn't seem to happen for v19.9, but that seems to be a separate thing...)

**Comment by davisking** [comment]
Yes, some things will work without thread_local.  But some things won't.  I
don't know what to tell you.  It's 2018, you should have a C++11 compiler.

In any case, I'm not removing the check because it will just lead to more
confusing errors later on for other people.

**Comment by ShuangLiu1992** [comment]
I am using a very new version of clang and it does have c++ support.
the cmake file works fine for x86_64 target but when I try to compile it for ios with a popular cmake toolchain file [https://github.com/leetal/ios-cmake](https://github.com/leetal/ios-cmake) I get the following

`CMake Error at dlib/cmake_utils/use_cpp_11.cmake:74 (target_compile_features):
  target_compile_features The compiler feature "cxx_thread_local" is not
  known to CXX compiler

  "Clang"

  version 10.0.0.10001145.
`

**Comment by davisking** [comment]
Either that copy of cmake is broken or your compiler doesn't support C++11.  

In any case, you need to use a C++11 compiler and a non-broken copy of cmake if you want to use dlib.
