### ISSUE TITLE
Training landmark with custom object configuration

### ISSUE THREAD

**Issue by gungui98** [davisking/dlib#1245]
Hi, first of all, dlib is an amazing library that helps me a lot with my computer vision problems! Moreover, I currently want to build a model with functioning like face landmarks detection, that means,I want build a landmark in a car, Is it possible to configure the number of landmark and also the dataset to fit this problem!

Thanks for listening! Hope to see your reply soon!

**Comment by davisking** [comment]
Yes, this is easy to do with dlib.  Read the documentation: http://dlib.net/ml.html#shape_predictor_trainer
