### ISSUE TITLE
Pickle error on v19.10

### ISSUE THREAD

**Issue by ahmdrz** [davisking/dlib#1248]
Hi,

In dlib v19.10 I have a problem with `pickle` in python.
In this line on `v19.10` I have a core dump problem.
https://github.com/mrl-athomelab/gender_classifier/blob/master/train.py#L81

But when I use `v19.7` everything is great !

**Comment by davisking** [comment]
See http://pybind11.readthedocs.io/en/stable/advanced/classes.html

In particular, you have to use pickle protocol version 2.
