### ISSUE TITLE
How to submit LFW test result to lfw webpage?

### ISSUE THREAD

**Issue by yewuyue111** [davisking/dlib#1251]
I want to submit LFW test result to LFW results webpage(http://vis-www.cs.umass.edu/lfw/results.html). However, I failed to find any submit port or webpage or description. Could anybody give me some advice?

**Comment by davisking** [comment]
This is not the right place to ask.  But you email the LFW people to submit. You also need to follow their instructions carefully, which incidentally explain how to submit.  Also, FYI, if you email a submission to them without reading the instructions, which you obviously haven't read, they are going to be irritated when your submission doesn't follow the rules.

**Comment by yewuyue111** [comment]
I am sorry to bother you and thanks for your reply.
