### ISSUE TITLE
dlib Python module references save_jpeg() even if built with DLIB_JPEG_SUPPORT=0

### ISSUE THREAD

**Issue by aldanor** [davisking/dlib#1252]
When building dlib with `-DDLIB_JPEG_SUPPORT=0`, Python bindings shouldn't unconditionally refer to `save_jpeg()` (in face_recognition module), otherwise dlib becomes unimportable like so:

```
ImportError: dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: 
_ZN4dlib9save_jpegERKNS_7array2dINS_9rgb_pixelENS_33memory_manager_stateless_kernel_1IcEEEERKSsi
```

**Comment by davisking** [comment]
Why would you compile the python bindings without jpeg support in the first
place?

**Comment by aldanor** [comment]
In my particular case? Since I only use dlib for its global opt module, nothing to do with image-related stuff - and because of this build issue all Python environments that use dlib have to carry a ljbjpeg around.

**Comment by davisking** [comment]
Are there any problems this causes? What bad things happen because of this?

I'm not excited about adding more switches because users find them
confusing.  I don't want to get questions from people like, "I compiled
with DLIB_JPEG_SUPPORT=0 and then got an error that I couldn't load a jpeg
file. I am confused."  I get lots of such questions already. :(

**Comment by aldanor** [comment]
My point of view, as a user, may be different from yours, of course :) Ditto re: not being excited about adding more switches, but here goes:

- Most 'normal' users of the Python side of dlib would just do a `pip install` or `conda install` a pre-built tarball, not having to mess with cmake compile flags and the like. This gives them the 'whole thing' if possible so, thus no questions.
- Those who disable things on purpose (e.g. jpeg support) probably do so because they know what they're doing and why they're doing it - in which case it should be no surprise to them that this or that feature ends up being disabled; I would be very surprised if someone purposefully disabled jpeg support and then opened a ticket to complain about, as you've noted above.
- There's parts of dlib (e.g. global optimization) that don't deal with any image related stuff; making libjpeg.so a hard dependency of the Python package is pretty brutal, since now you either have to ensure the boxes you deploy your Python package to have libjpeg installed, or haul it around in every conda environment your package gets installed to, depending on how you're structuring/packaging your Python code. If it wasn't for libjpeg, the only dependency is `numpy` - which makes total sense.
- When building Python package, you could probably wrap module bindings that depend on libjpeg in an ifdef and possibly output a big red cmake warning when building pybind11 bindings (e.g. "face_detection module is disabled due to jpeg_support=0").

**Comment by davisking** [comment]
>
>
>    - I would be very surprised if someone purposefully disabled jpeg
>    support and then opened a ticket to complain about, as you've noted above.
>
> Yes, it's very surprising.  But I nevertheless get a huge number of
questions along these lines.

>
>    - There's parts of dlib (e.g. global optimization) that don't deal
>    with any image related stuff; making libjpeg.so a hard dependency of the
>    Python package is pretty brutal, since now you either have to ensure the
>    boxes you deploy your Python package to have libjpeg installed, or haul it
>    around in every conda environment your package gets installed to, depending
>    on how you're structuring/packaging your Python code. If it wasn't for
>    libjpeg, the only dependency is numpy - which makes total sense.
>    - When building Python package, you could probably wrap module
>    bindings that depend on libjpeg in an ifdef and possibly output a big red
>    cmake warning when building pybind11 bindings (e.g. "face_detection module
>    is disabled due to jpeg_support=0").
>
> I'm convinced.  Can you submit a PR with the necessary #ifdefs or whatever
in the code so the build doesn't fail?

**Comment by aldanor** [comment]
Thanks! I'll try and do so in the next few days.
