### ISSUE TITLE
In a .cu file, when load images, load_image() function caused a dlib::image_load_error, Is it caused by missing DLIB_JPEG_SUPPORT in project->properties->preprocesser?

### ISSUE THREAD

**Issue by YPeking** [davisking/dlib#1255]
## CMakeLists.txt:
project(face_compare_top10)
find_package(CUDA)
INCLUDE(D:/cmake_3.9.1/share/cmake-3.9/Modules/FindCUDA.cmake)
add_subdirectory(../dlib dlib_build)
CUDA_add_executable(face_compare_top10 face_compare_top10.cu)
target_link_libraries(face_compare_top10 dlib::dlib)
## Code throwing exception in load_image.h:
inline type read_type(const std::string& file_name) 
        {
            std::ifstream file(file_name.c_str(), std::ios::in|std::ios::binary);
            if (!file)
                throw image_load_error("Unable to open file: " + file_name);
            ......
        }
## Code in .cu file:
matrix<rgb_pixel> img;
string temp_img_path = img_path[i];
load_image(img, temp_img_path);
matrix<float, 0, 1> face_descriptor = net(img);

**Comment by davisking** [comment]
No. It’s telling you the file doesn’t exist or you don’t have read access to it.
