### ISSUE TITLE
cannot get accurate face landmark shape model

### ISSUE THREAD

**Issue by Roger8** [davisking/dlib#1256]
I use shape_predictor_trainer and ibug-300W datasets to train my own shape predictor model(i choose 12 points  from the 68 landmarks ) , then i get 11 points positions with my trained model . But their positions are not that accurate like 68_landmarks detected, especially landmarks on closed eyes which i want to detect eye blinking;  i tried to adjust training parameters to improve the mean error from 0.10 to 0.076 , however it seems not so good. These are my  current training parameters and results:
**cascade_depth:               15
_tree_depth:                 4
_num_trees_per_cascade_level:50
_nu:                         0.05
_oversampling_amount:       40
_feature_pool_size:         800
_lambda:                     0.1
_num_test_splits:           150**
_mean training error: 0.076646
mean testing error:  0.0767946_
I've searched some Issues of this repo and cannot get my answer, now i don't know how to optimize my model ,should i increase samples with closed eyes ? Do u  have any good ideas, i need help . 
Thanks in advance.

**Comment by davisking** [comment]
Yes, get more data.  Also, use a tool like dlib's find_min_global() to do parameter search.  That's much better than doing it by hand.
