### ISSUE TITLE
Dlib performance on low resolution faces and retraining dlib.

### ISSUE THREAD

**Issue by ariel415el** [davisking/dlib#1260]
Hi,

I'm working with Dlib face-recognition for quite a long time on surveillance-camaeras videos. The faces in the videos i'm working with are much smaller than those in the public datasets like LFW, on which Dlib is benchmarked. This difference causes a significant degradation in performance on my data comparing to the 99% accuracy on LFW and i suspect it is, up to some point, due to Dlib being trained on high resoltuion images like those inLFW.

A possible solution could be to lower the resolution of  dlib's train data or to pass it through a domain adapter so that it will be more similar to surveillance footage data and then retrain dlib on it.

Have you thought about such face-recognition net version that will work with low resolution faces. I think this might be practical for any integration of dlib on programs that works on video, where faces are usually much smaller than 255x255

Since the data dlib was trained on is not public i can't do this adaptation my self and i ask you:
- What is the average face\image size in dlib's face train dataset. Does it contain low reolution image or 
  is it more similar to LFW
- I there a way to buy this dataset ?
- Do you think such a retrained model will perform better on unseen low resolution faces? 

I'm using:
- Dlib: 19.9
- Cuda: 8.0
- cudnn: 5.1
- cmake: 3.9
- compiler: Visual C++ 14.0
- GPU: GeForce GTX 1070
- System:Windows

Thanks in advance,
Ariel.

**Comment by davisking** [comment]
This example shows the code and example images used to train dlib's public model: http://dlib.net/dnn_metric_learning_on_images_ex.cpp.html.  You can see the image size in there and all  the other settings.  In general, the images are not blurry and are like those in LFW.

Retraining on blurry or smaller images might help. I'm not really sure. It's certainly possible and is what I would try. But you shouldn't expect it to recognize instances that even humans can't recognize.  You can email me at davis@dlib.net about getting the dataset or retraining a model.

**Comment by odrasile** [comment]
> 
> 
> Hi,
> 
> I'm working with Dlib face-recognition for quite a long time on surveillance-camaeras videos. The faces in the videos i'm working with are much smaller than those in the public datasets like LFW, on which Dlib is benchmarked. This difference causes a significant degradation in performance on my data comparing to the 99% accuracy on LFW and i suspect it is, up to some point, due to Dlib being trained on high resoltuion images like those inLFW.
> 
> A possible solution could be to lower the resolution of dlib's train data or to pass it through a domain adapter so that it will be more similar to surveillance footage data and then retrain dlib on it.
> 
> Have you thought about such face-recognition net version that will work with low resolution faces. I think this might be practical for any integration of dlib on programs that works on video, where faces are usually much smaller than 255x255
> 
> Since the data dlib was trained on is not public i can't do this adaptation my self and i ask you:
> 
>     * What is the average face\image size in dlib's face train dataset. Does it contain low reolution image or
>       is it more similar to LFW
> 
>     * I there a way to buy this dataset ?
> 
>     * Do you think such a retrained model will perform better on unseen low resolution faces?
> 
> 
> I'm using:
> 
>     * Dlib: 19.9
> 
>     * Cuda: 8.0
> 
>     * cudnn: 5.1
> 
>     * cmake: 3.9
> 
>     * compiler: Visual C++ 14.0
> 
>     * GPU: GeForce GTX 1070
> 
>     * System:Windows
> 
> 
> Thanks in advance,
> Ariel.

**Comment by davisking** [comment]
The training data is freely available: http://dlib.net/files/data/

**Comment by odrasile** [comment]
Thank you very much @davisking for your fast answer, but I was talking about fine tuning the face recognition model with small face images, and it seems that none of the available datasets is valid for that purpose :)
