### ISSUE TITLE
Recommendations for dlib

### ISSUE THREAD

**Issue by edubois** [davisking/dlib#1261]
Hi,

I really liked dlib (especially the way it's written), and that's why I'm going to write this. Unfortunately, recently, I moved to a different deep learning lib because of dlib's compilation time on a net that I had to build. This is not criticizes, just ideas to help dlib staying competitive. I am sorry but unfortunately I cannot share code.

- Handling of dilation and 3d convolutions / pool would be a good gain for a small dev cost,
- Spatial deformable convolutions, Roi pool, Roi align, etc.. are new things that looks very interesting, it would be so nice to have more of those state of the art tools, especially the ones solving the scale problem when learning features (right now you get easily limited when using the conv that dlib proposes),
- An example of implementation of a spatial deformer would be good, to me, this is a very important technic.
- Even if very easy to write, as much activation functions as possible would be nice, like ELU, SELU, LeakyRelu, .....
- If integrating SELU, adding AlphaDropout + Gaussian initialization would be required (https://arxiv.org/pdf/1706.02515.pdf),
- Adding an example of LSTM, or GRU units,
- RMSProp, YellowFin are two optimizers that I think should be in dlib,
- Putting a Generative Adversial Net example would be great, even if I was able to write my own with dlib, it's not trivial at all. The possibilities behind those nets are incredible.
- More ways to cut the inputs would be good (cropping, splitting, channel shuffling, ...)
- Handling of deep image stacks,
- Distributed training (That would be more like an external project, but every framework is starting to propose this. If I had to do my own, I would use RabbitMQ). At least I think dlib should propose the merging of the weights, I think there is a special way to merge the gradients. I'm not well documented on this.

This is not a wish-list or feature request, it's just that I really think this would help the dlib project to have those. It would be a huge boost for every of your users.

**Comment by davisking** [comment]
Yes, there are lots of things that could be added.  You should submit some in a pull request :)

A lot of these things are easy to do now though, like all kinds of input transformations can be coded by making a custom input layer, which is very easy to do.  You should also be able to have large networks.  The only time this is an issue is with visual studio, but new versions of visual studio have reasonable compile times now, so long as you put the compiler in 64bit mode. You can do this with a statement like `cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ..`.  The important part is the `-T host=x64` which instructs it to use the 64bit toolchain.  This isn't the same as making a 64bit app, it's using the 64bit version of the compiler.  If you don't say this then by default visual studio is only allowed to use 2GB of your RAM, which is obviously not good.

**Comment by bakercp** [comment]
Hi @edubois can you share your GAN example?  I'm building out a VAE example now and GAN is on my TODO list over here https://github.com/bakercp/ofxDlib/.
