### ISSUE TITLE
Ubuntu, pip install dlib (common.h:111:20: fatal error: Python.h: No such file or directory) 

### ISSUE THREAD

**Issue by theoldgun** [davisking/dlib#1268]
[ 82%] Built target dlib
Scanning dependencies of target dlib_python
[ 82%] Building CXX object CMakeFiles/dlib_python.dir/src/vector.cpp.o
[ 83%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
[ 84%] Building CXX object CMakeFiles/dlib_python.dir/src/matrix.cpp.o
[ 85%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o
[ 86%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o
[ 87%] Building CXX object CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/dlib.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:62: recipe for target 'CMakeFiles/dlib_python.dir/src/dlib.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/dlib.cpp.o] Error 1
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/vector.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
make[2]: *** Waiting for unfinished jobs....
compilation terminated.
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/matrix.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:110: recipe for target 'CMakeFiles/dlib_python.dir/src/vector.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/vector.cpp.o] Error 1
[ 87%] Building CXX object CMakeFiles/dlib_python.dir/src/other.cpp.o
CMakeFiles/dlib_python.dir/build.make:86: recipe for target 'CMakeFiles/dlib_python.dir/src/matrix.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/matrix.cpp.o] Error 1
[ 88%] Building CXX object CMakeFiles/dlib_python.dir/src/basic.cpp.o
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/svm_c_trainer.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/svm_rank_trainer.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:134: recipe for target 'CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o] Error 1
CMakeFiles/dlib_python.dir/build.make:158: recipe for target 'CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o] Error 1
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/decision_functions.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:182: recipe for target 'CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o] Error 1
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/opaque_types.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/other.cpp:4:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:206: recipe for target 'CMakeFiles/dlib_python.dir/src/other.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/other.cpp.o] Error 1
In file included from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/../dlib/python.h:6,
                 from /home/dms/cuifengyi-work/deepfakes-faceswap/dlib/tools/python/src/basic.cpp:3:
/home/dms/cuifengyi-work/deepfakes-faceswap/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:230: recipe for target 'CMakeFiles/dlib_python.dir/src/basic.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/basic.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    'Topic :: Software Development',
  File "/home/dms/.virtualenvs/faceswap_env_python36/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dms/.virtualenvs/faceswap_env_python36/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/dms/.virtualenvs/faceswap_env_python36/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dms/.virtualenvs/faceswap_env_python36/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dms/.virtualenvs/faceswap_env_python36/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dms/.virtualenvs/faceswap_env_python36/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 129, in run
    self.build_extension(ext)
  File "setup.py", line 165, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.

I have install python3.6-dev and python3-dev，but didn't work，can anyone help me？

**Comment by theoldgun** [comment]
I use Ubuntu16.04 and python3.6

**Comment by davisking** [comment]
You are either not running python 3.6 or you didn't really install the dev package.  Run python --version.  Does it say 3.6?  Fill out the issue template.  I'm not going to guess what your problem might be any more than that.

**Comment by theoldgun** [comment]
I am really thank you@davisking，I am a newbee,When I python --version，it says “Python 3.6.3”


`(faceswap_env) dms@dms-System-Product-Name:~/cuifengyi-work/deepfakes-faceswap/dlib$ python 
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> exit()
(faceswap_env) dms@dms-System-Product-Name:~/cuifengyi-work/deepfakes-faceswap/dlib$ python --version
Python 3.6.3
(faceswap_env) dms@dms-System-Product-Name:~/cuifengyi-work/deepfakes-faceswap/dlib$ 
`


![image](https://user-images.githubusercontent.com/28718923/39106149-5e05e22e-46ec-11e8-8da7-34baf52aabc6.png)
but in this picture it has says“Reason: module 'dlib' has no attribute 'get_frontal_face_detector'
”
can you help me.

**Comment by davisking** [comment]
That shows you are able to import dlib since the import worked.  That doesn't match what you have already posted.
