### ISSUE TITLE
How can I view C++ source  code in dilb

### ISSUE THREAD

**Issue by FightForCS** [davisking/dlib#1272]
what is the C++ source code path?How can I qucikly find the cpp file I want? All I can find is .h header file. Where is cpp file?
for example, I want to view the C++ souce code of the following "detctor" method
`std::vector<rectangle> dets = detector(img);`
How can I do this? I am a newbie to C++, hope someone can help me. Thx

**Comment by davisking** [comment]
You should use an editor that allows you to jump to the definitions of functions and classes.  I like vim and ctags for this, but there are many others.  Pick an editor and learn to use it.

**Comment by FightForCS** [comment]
@davisking Thanks for your quick reply, I import source files to Visual Studio, all methods jump to .h header file which only define those methods, but I want to view cpp files which implement those methods.
Any ideas? Thanks.

**Comment by stereomatchingkiss** [comment]
Recommend QtCreator, it works very well and much faster than Visual Studio

2018-04-24 20:05 GMT+08:00 FightForCS <notifications@github.com>:
