### ISSUE TITLE
dnn_mmod_face_detection_ex  throw exception

### ISSUE THREAD

**Issue by roy81f** [davisking/dlib#1274]
i'm trying to run dnn_mmod_face_detection_ex example program,  everything built just fine, in addition Cuda toolkit installed.
from some reason i'm getting exception in Layers.h   (it takes a few mins) .

"Exception thrown at 0x000000013F0734DD in dnn_mmod_face_detection_ex: 0xC0000005: Access violation reading location 0xFFFFFFFF3F130E6C. occurred"

Arguments:  mmod_human_face_detector.dat  faces/2008_007676.jpg
V. Card: Nvidia 1050
Os: Win7
VS15 (2017)

Can someone help me? Thanks a lot.

**Comment by davisking** [comment]
Fill out the issue template.  In particular, if no one can reproduce the
problem you aren't going to get help.
