### ISSUE TITLE
cudaMalloc error on testing dnn_semantic_segmentation_train.ex.cpp network

### ISSUE THREAD

**Issue by langheran** [davisking/dlib#1278]
Hello,

My net finished training but now it won't run, it says I don't have enough memory.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/7329323/39341383-98873854-4998-11e8-8238-f4583574fc05.png)

The server has 32GB RAM but it seems it is not enough:

![image](https://user-images.githubusercontent.com/7329323/39341418-bcbfd320-4998-11e8-8d9a-e35cb90b0be0.png)

Should I try with a cloud server with more memory? or am I doing something wrong? maybe the file had corrupted..

Thank you David, best regards

**Comment by davisking** [comment]
If it says you are out of memory then that's the problem.  Load less data or get a computer with more memory.

**Comment by langheran** [comment]
I'll try it, thank you Davis
