### ISSUE TITLE
Facial landmark detection failing when RGBA is converted to RGB

### ISSUE THREAD

**Issue by AbdealiJK** [davisking/dlib#128]
Hi,
I understand that the facial landmark detection fails if I give a RGBA image, as it expects either  a greyscale or a RGB image. But, when I try removing the alpha channel, it still fails.

```python
import os
from shutil import copyfileobj

try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen

import dlib
from skimage.io import imread

def download(url, filename, overwrite=False):
    if not os.path.exists(filename) or overwrite:
        response = urlopen(url)
        with open(filename, 'wb') as out_file:
            copyfileobj(response, out_file)

download('https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Beatrix_Podolska_pedagog_muzykolog_Krakow_2008.xcf/720px-Beatrix_Podolska_pedagog_muzykolog_Krakow_2008.xcf.png',
         'Beatrix.png')

im = imread('Beatrix.png')
detector = dlib.get_frontal_face_detector()

print('Shape of image data', im.shape)
im = im[:, :, :3]
print('Shape of image data after processing', im.shape)
print(detector.run(im))
```

Here is an example of a PNG which is downloaded, it initially has the shape `(1024, 720, 4)` and after removing the alpha channel has `(1024, 720, 3)`.
But it still gives:
```python
Shape of image data (1024, 720, 4)
Shape of image data after processing (1024, 720, 3)
Traceback (most recent call last):
  File "beatrix.py", line 32, in <module>
    print(detector.run(im))
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.
```

EDIT:
Note that this works perfectly fine if i give a PNG with RGB only or even a jpg.

**Comment by davisking** [comment]
Shouldn't that be :2 instead of :3?

**Comment by AbdealiJK** [comment]
The `:3` is to choose only the first 3 (RGB) of the 4 channels (RGBA) actually there
```
In [84]: a = [1,2,3,4,5]
In [85]: a[:3]
Out[85]: [1, 2, 3]
In [86]: a[:2]
Out[86]: [1, 2]
```
So, :3 will select the first 3 items in that dimension -> R, G, B

if I use :2, I'd be removing the B channel wouldn't I ?

**Comment by davisking** [comment]
Oh, it's a length.  I thought it would be an index.  I don't use python
much.

Anyway, apparently that's not the way scikit image wants you to do this
kind of operation.  I'm not sure what the appropriate function is for it.

**Comment by AbdealiJK** [comment]
I don't quite understand your comment. skimage simply loads the image into a numpy ndarray of 3Dimensions. Then I simply splice the ndarray appropriately to get a 3 Channel image.
There's no additional metadata involved that could be getting confused afaik.

skimage doesnt seem to have any function for this - http://scikit-image.org/docs/dev/api/skimage.color.html

Then I went around checking out the error more. The error seems to be coming from `tools/python/src/object_detection.cpp` and it happens because `is_rgb_python_image()` returns false. `is_rgb_python_image()` is defined in `/dlib/python/numpy_image.h` which throws an error only if `shape[2] != 3`. So, it would seem that `get_numpy_ndarray_parts` is not giving the shape correctly. And 

I get stuck here, because that function seems to do some manipulation with the buffer directly - which I have no experience with.

So, ultimately skimage has no role to play, because it's just considered to be a numpy ndarray. I think the shape detection in the C code is getting confused because this array is spliced ... and I don't know how numpy handles that at the buffer level so i can't debug that more.

**Comment by AbdealiJK** [comment]
Yep, so I confirmed that the way being used to find the shape is the problematic part.
Using `im = im[:, :, :3].copy()` instead of `im = im[:, :, :3]` fixes it.
The `copy()` changes the buffer which doesn't confuse that function any more.

**Comment by davisking** [comment]
Sweet.

**Comment by AbdealiJK** [comment]
I don't think the issue should be closed.
This is just a workaround, but it is not the best way to do this as it costs memory.
This is still a issue with the way dlib finds the shape of numpy arrays and should be fixed.

**Comment by davisking** [comment]
How do you find the shape of numpy arrays in python?  Not via shape?

The documentation for how numpy works and what it does with this kind of thing is terrible by the way. :(

**Comment by AbdealiJK** [comment]
So, in python I do `im.shape` which does show 3 channels for me (Refer output of shape in first description - `(1024, 720, 3)`). So, it works as expected in python.

But dlib thinks the `shape` of `im` has 4 channels, Hence the way dlib is finding the shape is causing the issue ...

The related code is at https://github.com/davisking/dlib/blob/master/dlib/python/numpy.h#L34
I've never used boost-python before, and not sure why though. The use of `PyBUF_ND` with `PyObject_GetBuffer` seems correct to me ... Maybe the `obj` being given itself is wrong ?

**Comment by davisking** [comment]
Welcome to the Python C API.  It's generally not documented, inconsistent, and somewhat sloppy.  :)

Boost.python helps make it a little bit nicer but boost.python isn't super well documented itself.

**Comment by mljli** [comment]
@AbdealiJK  @davisking  Hey. The problem is dlib requires the array to be contiguous as specified by the `PyBUF_ND` flag. Slicing off the fourth channel makes a non-contiguous view since the last dimension varies first. Sure we can instead use strides to determine shapes but I have no idea if dlib really needs contiguous buffers.

**Comment by davisking** [comment]
It doesn't.  It's just copying the data into another buffer.  It's just a
matter of getting the appropriate dimensions and strides from the python C
API, which as I recall is not documented at all when it comes to this
detail.  But if you can figure it out that would be super :)

**Comment by mljli** [comment]
Cool. I'd like to help though I'm not familiar with Python's C API. So I will refer to some other projects to see how they do it. After the exam next week off course :).

**Comment by davisking** [comment]
Sweet.  Good luck with your exam :)

**Comment by mljli** [comment]
Got bored of preparing for the exam. LOL

> It's just copying the data into another buffer.

I doubt that. It seems that Dlib simply passes a `numpy_rgb_image` which holds a pointer to the underlying buffer of a `Py_Buffer` object to an `object_detector` and I did't see any copyings until computing the FHOG features. From what I understand, if an array is non-contiguous and shares the buffer with its 'base' array, Dlib can't handle it. The `image_view` type requires C-contiguous buffers to correctly find the offset of a pixel.

The solution is obvious, copying the array to a contiguous buffer if necessary. We can use either `PyBuffer_ToContiguous` or `PyBuffer_GetPointer`.

Things should have become more complex if [advanced indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing) is used. But thanks to Numpy's optimization, if a view has discontiguous columns (like array `B` below), it becomes Fortran-style contiguous. And if a view has both discontiguous rows and columns (like array `C` below), a new contiguous buffer will be allocated for it. However, whether the conclusion is true is unknown.

```python
> A = numpy.arange(16, dtype=numpy.uint8).reshape(4, 4)
> A
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=uint8)
> B = A[:, [0,1,3]]
> B
array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15]], dtype=uint8)
> B.flags  # B doesn't share buffer with A (already verified)
 C_CONTIGUOUS: False
 F_CONTIGUOUS: True
 OWNDATA: False
> C = B[[0,2,3], :]
> C
array([[ 0,  1,  3],
       [ 8,  9, 11],
       [12, 13, 15]], dtype=uint8)
> C.flags
 C_CONTIGUOUS: True
 F_CONTIGUOUS: False
 OWNDATA: True
```

To conclude, the array passed in is either contiguous (C or Fortran) or has the same strides with its 'base' array. So theoretically we can handle any arrays with the help of strides. The remaining problem is the way Dlib views an image buffer. For example, `rgb_pixel` assumes RGB channel to be contiguous which obviously may not be true. So for multi-channel images with discontiguous third dimension, we have no choice but to copy the buffer?

Correct me if I was wrong.

**References**
* Python Buffer Protocol
* Python source code
* [C-API for non-contiguous arrays](https://mail.scipy.org/pipermail/numpy-discussion/2007-October/029652.html)

**Comment by davisking** [comment]
Yes. I expect you will need to copy into a contiguous buffer to make this work.

**Comment by mljli** [comment]
What's the preferred way to allocate memory on heap? I'm currently using `dlib::shared_ptr` and cast it to `pixel_type*`.

**Comment by davisking** [comment]
Create an dlib::array2d.  Definitely don't call new or malloc.
