### ISSUE TITLE
dnn_semantic_segmentation_train terminate called without an active exception

### ISSUE THREAD

**Issue by maatici** [davisking/dlib#1282]
Hi;
When I run dnn_semantic_segmentation_train_ex.cpp on VOC2012 dataset, I get the following error immediately:
..
step#: 0     learning rate: 0.1   average loss: 0            steps without apparent progress: 0
terminate called without an active exception
Aborted (core dumped)

How can I fix this?

My OS is Ubuntu 16.04
Dlib version : 19.10
Cuda version : 9.1

and 
nvidia-smi result is below:

Wed May  2 16:02:26 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 840M        Off  | 00000000:03:00.0 Off |                  N/A |
| N/A   52C    P0    N/A /  N/A |    176MiB /  2004MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1035      G   /usr/lib/xorg/Xorg                            82MiB |
|    0      2038      G   compiz                                        32MiB |
|    0      6067      G   /proc/self/exe                                58MiB |
+-----------------------------------------------------------------------------+

**Comment by davisking** [comment]
Did you edit any of the code?

**Comment by maatici** [comment]
I just changed the following line to save the model with different name:

 serialize("semantic_segmentation_voc2012net_my.dnn") << net;

**Comment by davisking** [comment]
Does it work if you don't change anything at all? Get a fresh copy and try
again.  If it works then you probably changed other lines too.  I get lots
of people saying just this kind of thing "oh I didn't change anything
except for this simple and obviously correct change".  But then later they
post something like "oh yeah, and I also added a bunch of array accesses
that go out of bound later on" or some other kind of basic programming
errors that don't have anything to do with dlib.

**Comment by maatici** [comment]
I also tried with fresh copy and again it didn't work but I watched the results of nvidia-smi command and it seems that 2G ram of the GPU exhausts immediately.

**Comment by davisking** [comment]
Then you are just running out of RAM.

**Comment by davisking** [comment]
Load smaller minibatches.

**Comment by Mut1nyJD** [comment]
With 2GB VRam you probably have to use a minibatch size of 2-4.

**Comment by maatici** [comment]
I change the following line as
dlib::pipe<training_sample> data(4);

but result is same. In addition, I play with this line

chip_details(rect, chip_dims(227, 227));

and I get an error if I change 227. How is this value specified?

**Comment by maatici** [comment]
I also do the followings but result doesn't change anyway.
trainer.set_mini_batch_size(4);
 trainer.set_dnn_prefer_smallest_algorithms();

**Comment by Mut1nyJD** [comment]
You need to change the inner while loop in the training while loop which feeds the data to 4 as well. just changing the container initial size alone will not make a difference. Also I think 4 is probably still too big I would try 2 first.

**Comment by maatici** [comment]
Finally started to work, thanks.

**Comment by maatici** [comment]
@davisking How is 227 specified in chip_details(rect, chip_dims(227, 227))? It gives error if I change to any other value. Is it calculated according to input image size?
