### ISSUE TITLE
Chineese whisper image search using Graph DB

### ISSUE THREAD

**Issue by vijaysagi1** [davisking/dlib#1284]
## Expected Behavior
We are using chineese whispers for image similarity and construct image graph so that we can traverse the image in least possible time. we have images more than 1 million 

## Current Behavior
Currently we are storing the image descriptors in .pkl file and traversing it is taking minutes.

Pls suggest how can we store the graph structure of chineese whisper in Graph DB and use it face recognition ? Pls suggest

* **Version**: dlib 19.10
* **Where did you get dlib**: github repo
* **Platform**:  64-bit 
* **Compiler**: python 2.7

**Comment by davisking** [comment]
Github issues are not a code writing service.
