### ISSUE TITLE
shape_predictor_trainer takes an eternity to run

### ISSUE THREAD

**Issue by Vermeille** [davisking/dlib#1285]
Hello,

I am trying to train a new shape predictor with your 5 face landmarks dataset with more rotations. However, that took more than 18h to train on an expense AWS instance with 64 CPUs (and 64 worker threads), and the result was absolute garbage, probably because I had an hyper parameter wrong.

So, I'm trying to optimize a bit the trainer so that I can quickly try various hyper parameters choices on a subset of the dataset, but even 3% of the initial dataset (~1.7k images when augmented with flips and rotations) takes more than 1h to train. Sadly, I know I did not miss any important gcc flag: I have blas, -march=native -O3 and -flto.

After profiling it appears that the guilty function is `generate_split` in which most (>90%) of the CPU time is spent. And more precisely in the first loop, computing the sums of vectors that go left for each feature. Though, after many hours looking at the code, I fail to see any optimization opportunity there.

I thought you may have an idea on how to speed things up or how to deal with the big amounts of time at play here.

Thanks!

**Comment by Vermeille** [comment]
I actually use the default parameters. It's not running on my laptop because the data augmentation needs way too much memory.

On a 4 core servers but enough RAM, it still takes 18 to 20h

**Comment by Vermeille** [comment]
Thanks for your input.

By actually commenting the parameters that the training code changed, I got it to run in 15 mins on 1.4k images after augmentation. Though I guess you changed those values for a reason and it takes more time to run with those values for a reason. I'll run some evaluations with the defaults parameters anyway.

Many thanks for your help. I'm using your code at work, it saves me a great deal of time, and as such, I hope I'll be useful to you with some PR (just as I did yesterday) to give back to you and the community.

**Comment by Vermeille** [comment]
Hello Davis,

First things first, thank you. I managed to train the model under a reasonable amount of time.

I have a smoke follow up question: when the shape predictor fails to converge, it returns what I guess it's the mean shape, but it's not flagged as an error. Is there a way to know that it failed? My face detector detects faces that the shape predictor can't handle (mostly because they are a bit more rotated), and I'd like to get rid of them.

Initially I thought I'd just had to train a shape predictor with more rotations but actually that just makes a bad mean shape that won't converge to anything meaningful

**Comment by davisking** [comment]
The shape predictor isn't doing anything that could be characterized as "converging" or "not converging". If it doesn't work then either you need better training data or the parameter settings are bad.  The algorithm is relatively insensitive to the settings of the parameters so you probably have bad data.  Data needs to be labeled accurately and consistently.

**Comment by Vermeille** [comment]
I totally get the "convergence" thing you've talked about, but I lack better vocabulary.

If you want to see for yourself, take your own 5 points face alignement dataset, use [that code](https://github.com/davisking/dlib/blob/master/tools/archive/train_face_5point_model.cpp) (actually your own lol), but change

`add_image_rotations(linspace(-20,20,3)*pi/180.0,images_train, faces_train);`

to

`add_image_rotations(linspace(-160, 160, 9) * pi / 180.0, images_train,  faces_train);`.

Whether you use the default parameters or the one in the code don't change anything. The output is super bad 😢  And I guess your data is good considering the results you got.

I'm thinking this algorithm badly handles arbitrary rotation because of the initial mean shape used in the cascade. The mean shape of something arbitrarily rotated is just all the points in the center (mean of random points on a circle => center). Given that all the pixels are indexed relatively to the landmark points and they're all grouped in the center, the algorithm cannot properly run. Just my hypothesis :)

I really don't want to use a convnet just to guess the rotation of the face, that's really overkill.

Many thanks for your help. Is there somewhere I can donate a bit to thank you for your time?

**Comment by davisking** [comment]
Yeah, that's likely to be an issue. You should try running it with a manually specified initial mean shape.  Like take the initial shape from the unrotated dataset and use that. Maybe that will fix it.  There is no API for doing this now, but it would be easy enough to just add a parameter or make the fields public and jam it in there. 

Sure, donations can go to davis@dlib.net via paypal or zelle :)

**Comment by Vermeille** [comment]
Donation sent. Better late than never :smile: 
And closing this since I'm done investigating it, and you've answered everything relevant to the issue for further searches.
