### ISSUE TITLE
python code for data augumentation with landmarks

### ISSUE THREAD

**Issue by NikolayTV** [davisking/dlib#1288]
Hello. 
Are there any examples of how to augument image data and landmarks with it?

**Comment by NikolayTV** [comment]
It seems that I found a solution:
http://imgaug.readthedocs.io/en/latest/source/examples_keypoints.html

If you have somethign useful to add, you are very welcomed.
BTW great library, thanks so much!

**Comment by davisking** [comment]
I would use the imglab tool in the dlib/tools/imglab folder.  It can correctly mirror and rotate datasets with landmarks.  See also: http://blog.dlib.net/2018/01/correctly-mirroring-datasets.html for a discussion.

**Comment by NikolayTV** [comment]
This is fantasy!

Any augumenting methods you would advise to use for landmark dataset? 

Any other advise for how to get best results on training?

**Comment by davisking** [comment]
Do experiments and see what works for your problem.  Or read computer
vision papers and try to replicate their results.

**Comment by NikolayTV** [comment]
What about other augumenting technics that you used for 68landmark dataset?

**Comment by davisking** [comment]
I just mirrored it.
