### ISSUE TITLE
dlib.shape_predictor on the whole image

### ISSUE THREAD

**Issue by FightForCS** [davisking/dlib#1290]
Hi, shape_predictor() takes 2 input parameters: the input image and the face detection results.
How can I just run shape_predictor() on the whole image without face detection. Can someone provide me a Python example, Thanks.

Maybe construct a bounding box wrapper for the whole image? How can I construct such a mmod_rectangle object in Python?

**Comment by davisking** [comment]
Yes, make a rectangle for the whole image.  Read the documentation: http://dlib.net/python/index.html. It tells you what to do.

**Comment by davisking** [comment]
Hmm, some of the functions are missing from http://dlib.net/python/index.html.  Like the dlib.rectangle constructor, which has a docstring. I'm not sure why sphinx didn't include it in the HTML docs.  

Anyway, make a dlib.rectangle(left,top,right,bottom).  Use that.

**Comment by FightForCS** [comment]
@davisking Thanks for your reply. Yep, I have read the api and have also tried to construct an mmod_rectangle object in the following ways, but all fail, rasing an error: dlib.mmod_rectangle: No constructor defined!
```
det=mmod_rectangle()
det=mmod_rectangle(rect=None, confidence=1)
```

Can you show me an example on how to construct such an object to pass to shape_predictor()? Thanks.

**Comment by davisking** [comment]
Look at what I just said.  `dlib.rectangle`

**Comment by FightForCS** [comment]
OK, I will try that later, Thanks
