### ISSUE TITLE
Could NOT find CUDA - Anaconda - Windows 10

### ISSUE THREAD

**Issue by adrian1906** [davisking/dlib#1300]
## Expected Behavior
Compile dlib with CUDA support

## Current Behavior
I get the following error when compiling using: 
`>cmake  -T host=x64 -D CUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\\v9.1" ..` 

"Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA"

## Steps to Reproduce
- Installed CMAKE
- Downloaded and installed Visual Studio 2017
- Created and compiled a toy cpp program to force Visual Studio to download the cpp compiler
- Downloaded and installed CUDA Toolkit 9.1 for Windows 10
(https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10)
- Downloaded and installed cuDNN for my specific graphic card from NVidia.com
- loaded Visual Studio Command Window
- Navigated to ../dlib/build
- typed `cmake  -T host=x64 -D CUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\CUDA\\v9.1`
- also tried `python setup.py install`
- also tried `conda install -c anaconda cudatoolkit`

* **Version**: 19.10
* **Where did you get dlib**: GitHub
* **Platform**: Windows 10 64bit
* **Compiler**: Visual Studio 2017

**Comment by davisking** [comment]
`cmake -T host=x64 -D CUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\CUDA\\v9.1` can't have been what you typed since it wouldn't do anything.  Look over what you did carefully and make sure your steps to reproduce are correct.

**Comment by adrian1906** [comment]
It looks like I left out the " .. when I typed the message.  
I did some more searching around this morning. Based on the screen shots from this site:
(https://stackoverflow.com/questions/44724849/cmake-3-4-3-cant-find-cuda-on-windows/44727414#44727414)
I should set the variables to these values.  This reference uses a GUI but I suppose I would just use the -D as before.  
CUDA_NVCC_EXECUTABLE = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\CUDA\\v9.1\\bin"
CUDA_INCLUDE_DIRS = ""C:\\Program Files\\NVIDIA GPU Computing Toolkit\CUDA\\v9.1\\include"
CUDA_CUDART_LIBRARY = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\CUDA\\v9.1\\lib\\.."

I'll report back after I try this.

**Comment by davisking** [comment]
If you install cuda using the nvidia installer and let it do it's default install cmake will find it.  That's how I do it.  You shouldn't have to set any special paths when invoking make.  If you do then you did something bad when installing cuda.

**Comment by adrian1906** [comment]
Thank you for the reply and letting me know what I should expect.
I did install from the nvidia installer but it is possible that I may have inadvertently changed some default settings.  I will give it another go and report back.
