### ISSUE TITLE
Training and running dnns on CPU with MKL Multithreaded is slower than with MKL Sequential

### ISSUE THREAD

**Issue by Zyrin** [davisking/dlib#1303]
## Expected Behavior
Training and running a dnn on CPU with dlib linked against the multithreaded version of MKL should give a speedup of (CPU_Cores - 1) compared to MKL sequential.

## Current Behavior
Training and running a dnn on CPU with dlib linked against the multithreaded version of MKL results in a performance loss of about 10% compared to MKL sequential. Additionally cpu time is wasted in the multithreaded case since all cores run on 100% instaed of one core beeing used in sequential mode.

## Steps to Reproduce
1.: Build the examples of dlib without cuda
2.: Train a dnn example (I used the mnist example dnn_introduction_ex).
3.: Time the execution of the dnn like in  https://github.com/Zyrin/dlib/commit/13caad723e8922e660e54dc2d871d22dada98535
4.: Rebuild the example with PullRequest https://github.com/davisking/dlib/pull/1302 and cmake option DLIB_USE_MKL_SEQUENTIAL enabled
5.: Rerun the same timing programm

* **Version**: 19.8 + 19.10
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 7 + 10 64 bit and Ubuntu 16.04.4 LTS 64 bit
* **Compiler**: Visual Studio 2015 + gcc  5.4

**Comment by Zyrin** [comment]
I have tested it with the dnn_imagenet_ex example and I can only see a speedup of about 20% with four (real) cores running at full load.

**Comment by davisking** [comment]
What about setting the `OMP_NUM_THREADS` environment variable to 1 and linking to the normal multi-threaded version of the MLK.  Does that end up being notably slower than linking to sequential? I normally just set `OMP_NUM_THREADS` as appropriate rather than relinking.

**Comment by Zyrin** [comment]
No, setting OMP_NUM_THREADS to 1 seems to perform the same as linking against the sequential lib.
Unfortunately, this is not an option when openmp is useded elsewhere.

**Comment by davisking** [comment]
Sure, but there is also MLK_NUM_THREADS if you want to just effect the
MLK.  I assume it has the desired effect?

**Comment by davisking** [comment]
Ok, seems like we can close this then. I think the sensible thing for most people is to use the MKL's environment variables to control this rather than mess with linker settings.  I already get lots of questions from confused people who are just beginning to program and have no idea what "this linking thing is". So adding more options and complications to the build and link process isn't something I'm super excited about.
