### ISSUE TITLE
You can't give objects that don't have any parts to the trainer.

### ISSUE THREAD

**Issue by daVincere** [davisking/dlib#1305]
I'm trying to train a model using the shape_predictor module of DLib.

```
Here's the trackback:
Training with cascade depth: 10
Training with tree depth: 2
Training with 500 trees per cascade level.
Training with nu: 0.05
Training with random seed: 
Training with oversampling amount: 300
Training with feature pool size: 400
Training with feature pool region padding: 0
Training with 0 threads.
Training with lambda_param: 0.1
Training with 20 split tests.
Traceback (most recent call last):
  File "train_model.py", line 30, in <module>
    dlib.train_shape_predictor(training_xml_path, "predictor.dat", options)
RuntimeError: 

Error detected at line 250.
Error detected in file /home/hasime/Downloads/dlib-19.10/dlib/../dlib/image_processing/shape_predictor_trainer.h.
Error detected in function dlib::shape_predictor dlib::shape_predictor_trainer::train(const image_array&, const std::vector<std::vector<dlib::full_object_detection> >&) const [with image_array = dlib::array<dlib::array2d<unsigned char> >].

Failing expression was objects[i][j].num_parts() != 0.
	 shape_predictor shape_predictor_trainer::train()
	 You can't give objects that don't have any parts to the trainer.
```

## Expected Behavior
I'm using the train_shape_predictor.py script. I've gone through the train_shape_predictor.h script [line 250] and as far as I can understand, the object here refers to the object of interest in any image. In my case that'd be a hand and hence I've used a box in every image to mark the hand hence denoting the object of interest. 
In addition to that, I've marked every finger-tip with some corresponding value, with similar values in every picture.  
Each picture has 7 boxes, 1 box for encapsulating the hand the other 6 for the finger-tips and the wrist respectively.

## Current Behavior
I can't understand what this error means. Or how I can go about resolving it. I apologise for concerning you with this Davis.

* **Version**: 19.10
* **Where did you get dlib**: GitHub. Built from source.
* **Platform**: Ubuntu 16.04 LTS 64 bit.
* **Compiler**: GCC 5.4.0 20160609

**Comment by davisking** [comment]
Look at the examples that come with dlib.  There are examples that train the shape predictor.  Look at the example training data.  I don't know how to explain the error you are making any more simply.  If you use the shape predictor you need to annotate each object with parts.  Look at the example data and you will see what that means.

**Comment by daVincere** [comment]
Sincerest apologies. I skipped doing that. Sorry.

**Comment by davisking** [comment]
This is wrong. You can annotate parts with imglab.  Read the about/help
menu. It tells you how to do it.  Also, if you get the newest imglab in
github it has a more convenient way of adding parts.  But nevertheless,
imglab lets you add parts via the GUI and this has always been the case.

**Comment by daVincere** [comment]
I was indeed wrong. I was able to move past that and train my own model. I'm, however, stuck with the error that the model takes my face to be the object, rather than my hands, and hence overlays the feature points (parts) onto my face. I'm working on it and most probably be done with it. I'd love it if you could tell me what I am missing.
I'd also let to know that I'm contributing to the Imglab README (it's the least I can do). I'll send you the Pull Request in a few hours. I hope you look at pull requests of that sort.
