### ISSUE TITLE
facial landmark detection on multiple cores

### ISSUE THREAD

**Issue by dancv000** [davisking/dlib#1309]
Hello,

I'm dealing with an facial landmark detection application using dlib. The application runs on an embedded board with a quad core ARM CPU and also it's GPU supports OpenCL.

My problem is that the application still has a little delay in image processing, and I want to make it real-time.

The application currently runs on a single CPU core (at 100%).  Is there an option in dlib library so it could run on multiple cores, in parallel? Or did anyone edit the library to run on multiple cores?

 
The images from camera are 200x200 and the application still does not run in real-time.

I use the latest version of the dlib library, and I have OpenBLAS installed. The Dlib is compiled with the following cmake command:
```
cmake .. -DCMAKE_C_FLAGS="-O3 -fprofile-use -DENABLE_NEON" -DNEON=ON
cmake  --build . --config Release
```

Thanks!

**Comment by davisking** [comment]
There isn't any multi-core stuff. However, dlib has NEON specific execution
paths so if you enable NEON instructions it will run faster.  Also, using
profile guided optimization is a big help.  It's not clear to me from what
you posted that you have really even enabled NEON.  You should look at the
specific build commands cmake is executing and make sure it's doing what
you want.
