### ISSUE TITLE
Eclipste Ubuntu. dlib.gui_core: Unable to connect to the X display. Failed to initialize X11 resources

### ISSUE THREAD

**Issue by cygi1989** [davisking/dlib#1314]
I am running on Ubuntu 16.04. 
Projects were build fine using CMAKE, however I encounter problems when running on Eclipse programs with GUI.
This is an error when I run gui_api_ex in Eclipse.
0 FATAL [1] dlib.gui_core: Unable to connect to the X display.
No protocol specified
terminate called after throwing an instance of 'dlib::gui_error'
  what():  Failed to initialize X11 resources

Note : other programs not using GUI works fine in Eclipse.
Also I can run all binaries created by CMAKE - including GUI ones (works fine).
So this seems like I need to include sth in Eclipse, since X11 seems to be installed fine.
(Also I just run  sudo apt-get install libx11-dev)

**Comment by davisking** [comment]
Fill out the issue template.  Also, this doesn't even sound dlib related.
