### ISSUE TITLE
dlib c++ compute_face_descriptor not equal with python compute_face_descriptor ? 

### ISSUE THREAD

**Issue by Jayhello** [davisking/dlib#1315]
I use the dlib c++ code as demo code https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp and https://github.com/davisking/dlib/blob/master/tools/python/src/face_recognition.cpp which realize python interface.

python code https://github.com/davisking/dlib/blob/master/python_examples/face_recognition.py

For same image, same parameter (  predictor_path, face_rec_model_path)

But the python compute_face_descriptor result is not equal with c++ code, even has much difference.

You can see the result here:

https://github.com/ageitgey/face_recognition/issues/494 

I just want to know why?

**Comment by davisking** [comment]
The code is different.  One upsamples the images and the other doesn't.

**Comment by Jayhello** [comment]
Below it python core code:

```
    img = face_recognition.load_image_file(img_path)

    dets = detector(img, 1)  # number_of_times_to_upsample = 1
    for k, d in enumerate(dets):
        shape = sp(img, d)
        face_descriptor = facerec.compute_face_descriptor(img, shape)
        print(face_descriptor)


```

c++ code:

```
        std::vector<dlib::rectangle> dets = detector(img, 1); // number_of_times_to_upsample=1 ?
        dlib::full_object_detection shape = sp(img, dets[0]);
```

The above code is not the same?

**Comment by davisking** [comment]
What are you talking about? That's not what the C++ code looks like.

**Comment by Jayhello** [comment]
I use C++ code from https://github.com/davisking/dlib/blob/master/tools/python/src/face_recognition.cpp
which you create dlib python interface.


### My purpose:
I have use the python face_recognition lib and use it's KNN train a face classify model.

I want change it code to C++.  but I found the dlib c++ code get compute_face_descriptor is not equal with python.

you saws upsamples not the same, but indeed I pass the value 1 .

**Comment by davisking** [comment]
That's not what it does.  Putting a 1 there in the C++ code sets the batch
size.  Don't just call code randomly and guess at what it might do or what
arguments exist.  Read the documentation.

**Comment by Jayhello** [comment]
@davisking my full code is as below, can you check it ?

https://github.com/ageitgey/face_recognition/issues/494#issuecomment-390375696
