### ISSUE TITLE
dlib brew link error

### ISSUE THREAD

**Issue by Padalingam** [davisking/dlib#1316]
When i installed dlib on mac os, it was installed successfully but link is not able made. I used the command ```brew link dlib``` it gives me the following error.

````
Padalingam-MacBook-Pro:~ padalingam$ brew link dlib
Linking /usr/local/Cellar/dlib/19.10... 
Error: Could not symlink include/dlib
/usr/local/include is not writable.
Padalingam-MacBook-Pro:~ padalingam$ 
````
Can any one help me on this?

**Comment by davisking** [comment]
I don't think this has anything to do with dlib.  Although I will point out that you probably need to use sudo to be able to write to /usr/local/include.
