### ISSUE TITLE
'module' object has no attribute 'image_window'

### ISSUE THREAD

**Issue by yyf1986** [davisking/dlib#1317]
When I run py example 'face_alignment.py',tell me the wrong:
Traceback (most recent call last):
  File "123.py", line 39, in <module>
    window = dlib.image_window()
AttributeError: 'module' object has no attribute 'image_window'

one: I try `pip install dlib` to install dlib,and with no problem.

two: git clone https://github.com/davisking/dlib.git
cd dlib
python setup.py install

the two ways has the same wrong

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whyisdlib.imagewindowmissing
