### ISSUE TITLE
How to compute recall on LFW while training process of the frontal face detector

### ISSUE THREAD

**Issue by td042** [davisking/dlib#1318]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by td042** [comment]
Acoording to this documentation: https://github.com/davisking/dlib/blob/master/dlib/image_processing/frontal_face_detector.h you compute the precision while training the Sub Detectors. LFW only contains images with labeled faces. Non-face regions are not labeled. How do you get the value for true negativ (regions which are detected correctly as non-face regions) for the equation to compute the precision? Did you use an additional dataset for testing that contains images with no faces?

**Comment by davisking** [comment]
Use a different dataset, one that's meant for face detection.

**Comment by td042** [comment]
Sorry, I meant Precison and not Recall in the headline. As a rule, the typical face detection databases only supply the labels of the faces. Non-face regions are not marked, so I do not understand how to calculate True Negatives which is necessary for the equation of precision
