### ISSUE TITLE
After successfull installation  dlib with message 'dlib will use cuda'..gpu is not enabled for CNN face detection

### ISSUE THREAD

**Issue by ashokbugude** [davisking/dlib#1322]
After successfull installation  dlib with message 'dlib will use cuda'..gpu is not enabled for CNN face detection

Fri May 18 13:04:49 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 0000A260:00:00.0 Off |                    0 |
| N/A   27C    P0    49W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+--

**Comment by davisking** [comment]
Read the issue submission template and follow the instructions.
