### ISSUE TITLE
After successfull installation dlib with message 'dlib will use cuda'..gpu is not enabled for CNN face detection

### ISSUE THREAD

**Issue by ashokbugude** [davisking/dlib#1323]
## Expected Behavior

1. What are you doing ?
I am running python cnn based face detector on cpu and gpu.

2. What part of dlib are you using ?
CNN face detection

3. What is happening ?
The time taken by cpu and gpu is same
The gpu doesn't list dlib as one of the processes of gpu as shown below
Fri May 18 13:04:49 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46 Driver Version: 390.46 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla P40 Off | 0000A260:00:00.0 Off | 0 |
| N/A 27C P0 49W / 250W | 0MiB / 22919MiB | 0% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| No running processes found |

4. What do you think should happen ?
The time taken by gpu should be less than the time taken by cpu 
The gpu should list dlib as one of the processes of gpu

## Current Behavior
1. What happens instead of the expected behavior
The time taken by cpu and gpu is same

## Steps to Reproduce
Run CNN python based face detection on NVIDIA GPU.
download dlib library
cd dlib
mkdir build
cd build
cmake ..
cmake --build . --config Release
python setup.py install

* **Version**: Latest vesion at this point of time
* **Where did you get dlib**: git clone https://github.com/davisking/dlib.git
Ran setup.py with CUDA enabled. Found message 'dlib built with CUDA' 

* **Platform**: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

* **Compiler**: gcc-4.9 , g++-4.9, python 3.6.3

**Comment by davisking** [comment]
You probably have multiple copies of dlib installed and are using one not
built to use cuda.  What does dlib.DLIB_USE_CUDA say?

**Comment by ashokbugude** [comment]
I am running dlib 
1. One inside flask server which gives false
2. One outside flask server which gives true

I wanted it to be working inside flask server.

Can I please know how to uninstall dlib everywhere

**Comment by ashokbugude** [comment]
Sometimes , I get 
`"AttributeError: module 'dlib' has no attribute 'DLIB_USE_CUDA'" `
inside flask virtual enviroment

**Comment by ashokbugude** [comment]
Resolved all the issues by installing face_recognition in virtual environment

**Comment by davisking** [comment]
The face_recognition package doesn't have anything to do with this issue.  For reference for future readers: http://dlib.net/faq.html#IcompileddlibsPythoninterfacewithCUDAenabled,whyisntitusingCUDA
