### ISSUE TITLE
Request: A way to load a cuda memory directly in to dlib

### ISSUE THREAD

**Issue by xsacha** [davisking/dlib#1324]
## Expected Behavior
When DLIB_USE_CUDA is enabled, there should be a method to send a pointer and size (OR a gpucv_image) directly rather than having to download the cuda mat to CPU before uploading it back again to the GPU.

## Current Behavior
There does not appear to be any API to send cuda memory as an image to dlib.
For instance, most (all that take an image?) classes are templated to take a type that has templated types (eg. pixel_traits) allowing for CPU manipulation (eg. assign_pixel).

## Steps to Reproduce
Attempt to use a cuda mat in dlib

**Comment by davisking** [comment]
I assume you are asking about sending these things to a DNN?  If so, why
don't you just call the network member functions that take tensors?

**Comment by xsacha** [comment]
Is there any example of this? Using gpu-backed memory to construct a tensor to gen a Dnn?

**Comment by davisking** [comment]
Tensor objects *are* GPU backed.

**Comment by xsacha** [comment]
I mean without any copy to host

**Comment by xsacha** [comment]
I've read the documentation (they are the source files right?) and maybe I am just missing it.

So I create a tensor. Every constructor I see takes a CPU object for some reason, or an existing tensor object.
Now I could create a resizable_tensor and copy memory to its device pointer. This would still require copying memory though.

I just want to wrap my existing, non-resizable CUDA memory.

Am I missing the CUDA memory constructor?

**Comment by davisking** [comment]
The documentation is in the files ending in _abstract.h.  They aren't
really source files.

Yes, you make a resizable_tensor.  Why don't you start with a
resizable_tensor in the first place? It seems that your issue is that
someone else owns the CUDA memory buffer and you want to imbue it into a
tensor.  There isn't an API for that because I don't like non RAII APIs.  A
tensor alias type of thing could be made though to wrap arbitrary CUDA
memory though.

**Comment by xsacha** [comment]
OK, is it possible using the current API or do you mean it would need to be added?
It is just very expensive to copy large images every time. My GPU Copy gets very high and memory usage gets maxed out.

**Comment by davisking** [comment]
You don't have to edit any part of dlib.  You can inherit from tensor and
define a new container, just like resizable_tensor or the aliasing tensor
do. Then you can make that container do whatever you want with CUDA memory.

**Comment by xsacha** [comment]
I'll probably end up doing that but I think it's something needed in the core library as well.
There needs to be some way to get images in without all the copying. 
In this instance I do actually own the memory, created directly from the nppicc which is a significant memory allocation itself (for eg. 4k RGB images) and if I want to do DNN on this, I get a very high peak memory usage.

**Comment by davisking** [comment]
Is there a reason why you don't let the resizable_tensor allocate the CUDA
memory for you?

And what are you doing? Are you using raw calls to cudaMalloc() or are you
doing some RAII thing?

**Comment by xsacha** [comment]
I suppose I could use dlib tensor throughout my code but right now it writes to a cv cuda GpuMat that I manage simply because OpenCV has all the image manipulation code for the GPU.

**Comment by davisking** [comment]
Ok.  Well, making something like the alias tensor tool that can wrap a
pointer is probably sensible.  You should set it up and submit a PR :)

**Comment by xsacha** [comment]
I'm currently implementing this but one issue I am coming across is that tensors are designed to sync the host and device memory. However, I only ever want the memory on device.

Also, tensors are laid out in memory as separate channels. Would it break much to change it to packed format for my code?

**Comment by davisking** [comment]
The tensors don't really have a layout. However, many layers assume they are laid out in planar format. Those layers won't work.

Look in the .cpp file.  `the_device_id` is set to whatever device you are using.  It doesn't do anything other than record it.

**Comment by xsacha** [comment]
I suppose the tensor needs the same layout that was used when I trained the model still. 

OK, but the id is private so I can't set it if I created the GPU memory externally.

**Comment by davisking** [comment]
It sets itself. Look at the cpp file or read the documentation in the abstract file.

**Comment by xsacha** [comment]
I see. I will have to set the cuda device prior to creating the tensor. 

Is there a way to have to_tensor not attempt to upload the host memory to device after running?
See: https://github.com/davisking/dlib/blob/592361e/dlib/dnn/core.h#L1139-L1147

**Comment by davisking** [comment]
I don't recall, but probably not.  You don't have to call the network via
to_tensor though.  You can feed in tensor objects yourself instead.

**Comment by davisking** [comment]
The entire API is documented in detail here:
http://dlib.net/dlib/dnn/core_abstract.h.html

**Comment by xsacha** [comment]
It is but I still can't work it out :(
There seems to be no examples doing what I need either.

**Comment by davisking** [comment]
There can't be examples of every possible thing.  Do you see the docs for the object you are calling?  It has methods that take a tensor as input.  You just give it a tensor. Look at the add_layer object.  That's the object that represents the network.  It's the object you have if you have a network.  It's methods are listed in the docs.
