### ISSUE TITLE
Compile dlib 19.11 and cannot find INSTALL.vcxproj project

### ISSUE THREAD

**Issue by lezan** [davisking/dlib#1325]
## Expected Behavior
I am try to compile dlib 19.11 to update my code from 19.7 to the last version of library. I expected to get INSTALL.vcxproj project like in 19.7, but with the last version I just get ALL_BUILD and ZERO_CHECK.

## Current Behavior
As I said, I expected three project: ZERO_CHECK, ALL_BUILD and INSTALL, but I just have ZERO_CHECK and ALL_BUILD. I do not know if it is a problem, but I am searching for an answer.
Moreover, I use `-DCMAKE_INSTALL_PREFIX` to specify where I want to put the result of building, but seems cmake is ignoring me (I know, it is not cmake, it is me, just kidding). With dlib 19.7 I am able to specify in the right way, but I cannot figure out where is the issue in CMakeLists.

## Steps to Reproduce
I downloaded dlib from dlib.net, extracted in D:\dlib.
Run Power Shell.
```
cd d:\dlib
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64" -T host=x64 -DDLIB_USE_CUDA=ON  -DUSE_AVX_INSTRUCTIONS=ON -DCMAKE_INSTALL_PREFIX=D:\dlib\build\Release
```

With dlib 19.7 I get an INSTALL project, so
`cmake --build . --target install --config Release`

I do the same with Debug version.
```
cmake .. -G "Visual Studio 15 2017 Win64" -T host=x64 -DDLIB_USE_CUDA=ON -DUSE_AVX_INSTRUCTIONS=ON -DCMAKE_INSTALL_PREFIX=D:\dlib\build\Debug
cmake --build . --target install --config Debug
```

With dlib 19.11 I did not get INSTALL project, so I run (after cmake .. -G etc.) from build\ only
```
cmake --build . --config Release
cmake --build . --config Debug
```

In this way I get two directory inside build\dlib: Release and Debug. 
Inside Release I have dlib19.11.0_release_64bit_msvc1913.lib.
Inside Debug I have dlib19.11.0_debug_64bit_msvc1913.lib.

Is it correct? Am I missing something? I did not get any error, but I am a bit confused.

* **Version**: 19.11.
* **Where did you get dlib**: dlib.net.
* **Platform**: Windows 7 64 bit SP1.
* **Compiler**: cmake 3.11.3 and Visual Studio 15.6 with the last update (not the last version of Visual Studio 17.1).

**Comment by davisking** [comment]
What happens when you run `cmake --build . --config Release --target
install` with the new dlib?

**Comment by lezan** [comment]
Hello Davis, thanks for your quickly answer.
cmake just say that install not exist.

MSBUILD : error MSB1009: the project file does not exist. Option: install.vcxproj

**Comment by davisking** [comment]
That shouldn't happen.  Also, the commands you posted don't appear to make sense. There is no `cd build` in them.  If you didn't do that then that's part of your problem.  Please try again and follow the exact commands you posted here or fix the post to reflect what you did and update the instructions.

**Comment by lezan** [comment]
Correct. I did it, but I missed to report here. Sorry.

**Comment by davisking** [comment]
So I just went into windows and tried this and it works fine. There is definitely an install target. I don't know what you could possibly be doing to make it not appear.

**Comment by lezan** [comment]
Today I decided to throw all dlib folder into the thrashbin and re-extracted.
All work. I do not know, maybe I failed something with CMakeLists, but I did not rembember to have modify it. Anyway, I lost all day for nothing, but now work.
Thanks.
