### ISSUE TITLE
cnn face detection cuda multi-processing throwing error 

### ISSUE THREAD

**Issue by ashokbugude** [davisking/dlib#1328]
What are you doing ?
I am running python cnn based face detector cuda based gpu in nginx server created through WSGI (web service gateway interface) using below command
`uwsgi -- processes=2 --socket=0.0.0.0:5000 --protocol=http -w wsgi:app
`

What part of dlib are you using ?
CNN face detection.

What is happening ?
`RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-build-Bm_q1t/dlib/dlib/dnn/gpu_data.cpp:178. code: 3, reason: initialization error`

What do you think should happen ?
It should be running with multi-processing on flask nginx webserver with cuda enabled.

Current Behavior
What happens instead of the expected behavior
The code works fine in flask server but throws error when process in created in nginx through WSGI

Steps to Reproduce
Run CNN python based face detection on NVIDIA GPU through WSGI

Version: Latest version at this point of time

Where did you get dlib: git clone https://github.com/davisking/dlib.git
Ran setup.py with CUDA enabled. 

Platform:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

Compiler: gcc-4.9 , g++-4.9, python 3.6.3

**Comment by handsomefun** [comment]
also have this problem
