### ISSUE TITLE
dlib.test_shape_predictor broken on pypi version 19.12.0

### ISSUE THREAD

**Issue by joarleymoraes** [davisking/dlib#1331]
## Expected Behavior
the python function dlib.test_shape_predictor should return the error value when testing the predictor. We are using the following signature:

`test_shape_predictor(images: list, detections: list, scales: list, shape_predictor: dlib.shape_predictor) -> float`

## Current Behavior
When using the version 19.10.0, the function works as expected, but it's no longer working for version 19.12.0 and it throws the following exception:

```
Traceback (most recent call last):
  File "tests/issue_test_predictor.py", line 32, in <module>
    error = dlib.test_shape_predictor(np_images, img_detections, img_scales, shape_predictor)
RuntimeError: Expected a 2D numpy array, but instead got one with 3 dimensions.
```

## Steps to Reproduce
I have created the following reproduction snippet:

https://gist.github.com/joarleymoraes/141ab359521f073636e53075988110af#file-dlib_test_shape_predictor_issue-py

Let me know if you need anything else.

* **Version**: 19.12.0
* **Where did you get dlib**: pypi
* **Platform**: 
```
sb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
* **Compiler**: 
```
-- The C compiler identification is GNU 4.8.4
    -- The CXX compiler identification is GNU 4.8.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found PythonInterp: /usr/bin/python (found version "2.7.6")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Failed
    -- Performing Test HAS_CPP11_FLAG
    -- Performing Test HAS_CPP11_FLAG - Success
    -- pybind11 v2.2.2
    -- Enabling SSE4 instructions
    -- Using CMake version: 2.8.12.2
    -- Compiling dlib version: 19.12.0
```
* **Additional Info**:

The error seems to be thrown from here:

https://github.com/davisking/dlib/commit/43e5f42ef5a49e4410777402003de82ade299e21#diff-83e177fcdcff825bdc5fea0d236620ecR53

And it looks like it's interpreting our RGB image as grayscale.

This is the shape of a sample numpy image:

`(332, 500, 3)`

**Comment by davisking** [comment]
Thanks for reporting this.  I've been cleaning up the image binding code, and it's a little too clean now :)

I just pushed the fix. So if you get the latest code from github it should all work again.

**Comment by joarleymoraes** [comment]
@davisking, Thanks for the quick reply.

I will try that and will let you know if it fixes.

**Comment by joarleymoraes** [comment]
Great, I confirm it's working again :)
