### ISSUE TITLE
Error: does not support platform specification ...   when using setup.py. (Compiles with CUDA otherwise)

### ISSUE THREAD

**Issue by adrian1906** [davisking/dlib#1333]
## Expected Behavior
Expecting to run setup.py and have it compile dlib with CUDA support and make it accessible in Python. 

## Current Behavior
I was able to successfully compile dlib with CUDA support when I used the command:
`cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ..`
Below is the relevant output letting me know that it was successful.

> -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 (found suitable version "9.1", minimum required is "7.5")
> -- Looking for cuDNN install...
> -- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudnn.lib
> -- Building a CUDA test project to see if your compiler is compatible with CUDA...
> -- Checking if you have the right version of cuDNN installed.
> -- Enabling CUDA support for dlib.  DLIB WILL USE CUDA

According to the readme file, in order to use Python, I need to run the setup.py file.  I issued
`python setup.py install`
and I get this:

> Building extension for Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
> Invoking CMake setup: 'cmake C:\Users\Photo\Documents\GitHub\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Photo\Documents\GitHub\dlib\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -G Visual Studio 14 2015 Win64 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Photo\Documents\GitHub\dlib\build\lib.win-amd64-3.6 -A x64'
> -- Selecting Windows SDK version  to target Windows 10.0.17134.
> CMake Error in CMakeLists.txt:
>   Generator
> 
>    Visual Studio 14 2015 Win64
> 
>   does not support platform specification, but platform
> 
>    x64
> 
>   was specified.

## Steps to Reproduce
(Was previously using Visual Studio 2017 which did not work)
Uninstalled Visual Studio 2017
Installed Visual Studio 2015
Uninstalled CMAKE
Reinstalled CMAKE
Did not touch CUDA installation.
Added `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin` to my path (contains compiler cl.exe.)
Opened 

> VS2015 x64 Native Tools Command Prompt

in Administrative Mode
and issued:
`python setup.py install`
I also did
`python setup.py -G "Visual Studio 14 2015 Win64" install `
without any success

* **Version**: 19.10.99
* **Where did you get dlib**: github
* **Platform**: Windows 10 64bit
* **Compiler**: 
Visual Studio 14 2015 Win64

**Comment by davisking** [comment]
What happens when you run: `python setup.py -G "Visual Studio 14 2015" install --clean`?

**Comment by adrian1906** [comment]
Here is my output.  I was surprised by the line tha said The C compiler identification is unknow.
As a sanity check, I deleted the contents of the ..\dlib\build folder and rebuilt dlib directly again using `cmake -G "Visual Studio 14 2015 Win64" -T host=x64` The  C and CXX copiler were both identified.

> C:\Users\Photo\Documents\GitHub\dlib>python setup.py -G "Visual Studio 14 2015" install --clean
> running install
> running bdist_egg
> running egg_info
> writing dlib.egg-info\PKG-INFO
> writing dependency_links to dlib.egg-info\dependency_links.txt
> writing top-level names to dlib.egg-info\top_level.txt
> package init file 'dlib\__init__.py' not found (or not a regular file)
> reading manifest file 'dlib.egg-info\SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'dlib.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_py
> running build_ext
> Removing old directory C:\Users\Photo\Documents\GitHub\dlib\build\temp.win-amd64-3.6\Release
> Building extension for Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
> Invoking CMake setup: 'cmake C:\Users\Photo\Documents\GitHub\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Photo\Documents\GitHub\dlib\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -G Visual Studio 14 2015 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Photo\Documents\GitHub\dlib\build\lib.win-amd64-3.6 -A x64'
> -- Selecting Windows SDK version  to target Windows 10.0.17134.
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error in CMakeLists.txt:
>   No CMAKE_C_COMPILER could be found.
> 
> CMake Error in CMakeLists.txt:
>   No CMAKE_CXX_COMPILER could be found.
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/Photo/Documents/GitHub/dlib/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/Photo/Documents/GitHub/dlib/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "setup.py", line 252, in <module>
>     'Topic :: Software Development',
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
>     self.do_egg_install()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 170, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 156, in call_command
>     self.run_command(cmdname)
>   File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
>     self.build()
>   File "C:\ProgramData\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
>     self.run_command('build_ext')
>   File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 129, in run
>     self.build_extension(ext)
>   File "setup.py", line 165, in build_extension
>     subprocess.check_call(cmake_setup, cwd=build_folder)
>   File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Photo\\Documents\\GitHub\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Photo\\Documents\\GitHub\\dlib\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\ProgramData\\Anaconda3\\python.exe', '-G', 'Visual Studio 14 2015', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Photo\\Documents\\GitHub\\dlib\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

**Comment by davisking** [comment]
I think you just haven’t installed all of visual studio.

**Comment by adrian1906** [comment]
Thank you!
I re-installed Visual Studio 2015 in the python setup.py install --clean ran to completion. Is there another step to have the previous version of dlib replaced?  That version was installed via conda.

Also,
How can I tell that Python is indeed using the version that uses CUDA?

I'm running a training session and according to my NVIDIA GPU Activity monitor, only 3 items are listed:
logonui.exe
microsoft.photos.exe
MicrosoftEdge.exe

Thank you.
Adrian

**Comment by davisking** [comment]
There are no other steps other than having cmake and a working compiler installed. 

http://dlib.net/faq.html#IcompileddlibsPythoninterfacewithCUDAenabled,whyisntitusingCUDA

**Comment by adrian1906** [comment]
Thanks again.

I have dlib.DLIB_USE_CUDA = True.

**Comment by stippingerm** [comment]
This issue seems different, but I would like to add for reference that **I got an almost identical error message when the Visual Studio compiler was _not_ installed**. As the error message told about platform specification it was quite difficult to find out the real cause.

> CMake Error in CMakeLists.txt:
> Generator
> 
> NMake
> does not support platform specification, but platform
> 
> x64
...
