### ISSUE TITLE
cnn_face_detection_model_v1 doesn't seem to batch properly

### ISSUE THREAD

**Issue by Vermeille** [davisking/dlib#1336]
Hi Davis,

I'm investing this, but would like to write it, in case you have any idea or suggestion that could save me some time. I have a great need for a face detection & recognition pipeline that's fast, so I'm batching images together (hence the PR I just made).

Batched face detection seems to be already implemented, but here are my scores:

On 1042 images, "batched" one by one:

```
total detect time: 62.365166902542114
mean detect time: 0.0597940238758793
```

On the same 1042 images, batched by group of 75:

```
total detect time: 53.905285120010376
mean detect time: 3.8503775085721696
```
Quick maths, `75 * 60ms ~= 4.5s`. The gain is clearly not substantial enough, an looks like the batching is not happening.

I'm investigating. If you have any idea in the meantime... please let me know :)

**Comment by davisking** [comment]
Yeah or maybe you aren't actually batching.  No idea.

**Comment by Vermeille** [comment]
I'm investigating then :) Thanks for letting me know. The other PR should be ready very soon.

**Comment by Vermeille** [comment]
Okay, most of the time is spent in the net. Is there a way for me to check the time spent in each layer individually?

**Comment by davisking** [comment]
I would add logging/timing statements to the code.

**Comment by Vermeille** [comment]
Closing since I couldn't find any obvious way to speed things up and I moved on with a custom face detector with Pytorch.

**Comment by redionxhepa** [comment]
@Vermeille  Hi ! Please which face detector did you use in Pytorch  ? If you could share a link or the code would be great ! Thanks in advance !
