### ISSUE TITLE
Dlib Correlation Tracker not working with Video file works with Webcam only

### ISSUE THREAD

**Issue by zubairahmed-ai** [davisking/dlib#1339]
## Expected Behavior

It should process the incoming video frame and show me a tracker rectangle just like it works for live Webcam
## Current Behavior

When using `vid = cv2.VideoCapture(args["video"])` I am getting the following error on `tracker.start_track(frame, dlib_rect)` note that if I am using a webcam `vid = cv2.VideoCapture(0)` this works flawlessly

`Error detected in function void __cdecl dlib::correlation_tracker::start_track<class numpy_rgb_image>(const class numpy_rgb_image &,const class dlib::drectangle &).`

## Steps to Reproduce

Following will give you the error

`tracker = dlib.correlation_tracker()
    while True:        
        frame = vid.read()
        
        if args.get("video") and frame is None:
            break           
        dlib_rect = dlib.rectangle(left, top, bottom, right)
        tracker.start_track(frame, dlib_rect)
`
* **Version**: 
`dlib==19.10.99`

* **Where did you get dlib**: 
Install it with `pip`
* **Platform**: 
`Windows 10 64 bit`
* **Compiler**: 
Didn't compile

**Comment by davisking** [comment]
There should have been more text in that error message.  You need to post
complete error messages.

Also, try the newest dlib.

**Comment by zubairahmed-ai** [comment]
Indeed there was more text in the error message
Here it is

`  tracker.start_track(frame, dlib_rect)
RuntimeError:

Error detected at line 61.
Error detected in file e:\documents\projects\dlib\dlib\image_processing\correlation_tracker.h.
Error detected in function void __cdecl dlib::correlation_tracker::start_track<class numpy_rgb_image>(const class numpy_rgb_image &,const class dlib::drectangle &).

Failing expression was p.is_empty() == false.
         void correlation_tracker::start_track()
         You can't give an empty rectangle.
`

**Comment by zubairahmed-ai** [comment]
Also error in newest Dlib 

`    tracker.start_track(frame, dlib_rect)
RuntimeError:

Error detected at line 61.
Error detected in file e:\documents\projects\dlib\dlib\image_processing\correlation_tracker.h.
Error detected in function void __cdecl dlib::correlation_tracker::start_track<class dlib::numpy_image<struct dlib::rgb_pixel>>(const class dlib::numpy_image<struct dlib::rgb_pixel> &,const class dlib::drectangle &).

Failing expression was p.is_empty() == false.
         void correlation_tracker::start_track()
         You can't give an empty rectangle.`

**Comment by davisking** [comment]
It's telling you the error.  You are giving it an empty rectangle to track.  That doesn't make sense and doesn't have anything to do with the video source.  You just have an error in your code.

**Comment by zubairahmed-ai** [comment]
What does it even mean?

Does it mean values provided to rectangle are all zeros or does it mean frame where the rectangle needs to start tracking is empty?

**Comment by zubairahmed-ai** [comment]
Hi Davis, please let me know if you can help with this issue https://stackoverflow.com/questions/50664940/dlib-rectangle-failing-expression-was-p-is-empty-false

**Comment by davisking** [comment]
You aren't creating the rectangle correctly.  Read the documentation.  You
have the order of arguments wrong.  If you looked at the rectangle you
made, by printing it for instance, you would also see that it's wrong.

**Comment by zubairahmed-ai** [comment]
You're right, this was indeed the problem. thanks for helping me out
