### ISSUE TITLE
License on CNN-models

### ISSUE THREAD

**Issue by manmitya** [davisking/dlib#1340]
Hi, Davis! Thank you for great work!
I have a question about license on your CNN-models in http://dlib.net/files/ and datasets in http://dlib.net/files/data/.
What type of license is used for these binary files and algorithms?
Interest in particular licenses for the following:
- mmod_human_face_detector.dat.bz2
- mmod_rear_end_vehicle_detector.dat.bz2
- mmod_dog_hipsterizer.dat.bz2
- shape_predictor_5_face_landmarks.dat.bz2
- shape_predictor_68_face_landmarks.dat.bz2
- dlib_face_recognition_resnet_model_v1.dat.bz2
- resnet34_1000_imagenet_classifier.dnn.bz2

**Comment by davisking** [comment]
See: https://github.com/davisking/dlib-models

**Comment by manmitya** [comment]
Thanks!
