### ISSUE TITLE
Proposal: ignore bmp 'Reserved Area' value

### ISSUE THREAD

**Issue by Palmitoxico** [davisking/dlib#1342]
The header of .bmp images has 4 bytes starting from the 0x06 address marked as  ['Reserved'](https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header), most bmp images I've come across have these 4 bytes zeroed, however that isn't the case for all images, as some softwares uses this reserved areas for their purposes.

In my opinion these bytes must be ignored (every software I've used to open bmp images ignores it).

Relevant lines:
https://github.com/davisking/dlib/blob/996a4bbba51381d21a8893e51a7da31587a9c618/dlib/image_loader/image_loader.h#L82-L84
https://github.com/davisking/dlib/blob/996a4bbba51381d21a8893e51a7da31587a9c618/dlib/image_loader/image_loader.h#L92-L93

* **Version**: 996a4bbba51381d21a8893e51a7da31587a9c618
* **Where did you get dlib**: Official github repository
* **Platform**: any
* **Compiler**: any

**Comment by davisking** [comment]
That's fine.  If you have really encountered BMP images that don't load because of this then we can change it.  So a PR is certainly welcome :)

**Comment by Palmitoxico** [comment]
Yes, I've tried to load some otherwise perfectly bmp files that had this reserved area filled with non zero numbers. I'll do a PR soon.
