### ISSUE TITLE
Variable Execution Time for face_recognition_model

### ISSUE THREAD

**Issue by shang-vikas** [davisking/dlib#1344]
##Specifications
hardware - Odroid XU4
OS - Armbian
testing_image - Any image with a face in it.(i am using picture with my face)

## Expected Behavior
face_recognition_model.compute_face_descriptor should get executed in fixed time.

## Current Behavior
    while True:
        if c>50:
            break
        
        t_dets1 = time.time()
        dets = detector(myface_gray_short,0)
        t_dets2 = time.time()
        print('_______________c = _________________ {}'.format(c))
        print('____dets__time___taken__{}'.format(t_dets2 - t_dets1))
        spp = sp(myface_gray_short,dets[0])
        t_spp2 = time.time()
        print('____68shape predict__time___taken__{}'.format(t_spp2 - t_dets2))
        feat = facerec.compute_face_descriptor(myface_short,spp)
        t_feat2 = time.time()
        print('____faceerec__time___taken__{}'.format(t_feat2 - t_spp2))
        c+=1
        gc.collect()

The result is that the facerec.compute_face_descriptors() sometimes gets executed with .30 -+ .05 and after some iterations the execution time is 3.35 +- 0.05 seconds. Sometimes the execution time goes high just after 2-3 iterations.This is a very strange behaviour. I even cleared the values of variables(dets, spp, feat) from memory and garbage too.

## Steps to Reproduce
Required - Odroid xu4
simply install armbian in Odroid xu4 and then install dlib. Take any picture with a  face and compute face descriptors n(say 20) times in a loop.

* **Version**:  Tried 19.9.0, 19.10.0
* **Where did you get dlib**: 19.9.0 installed via pip, 19.10.0 installed via cmake
* **Platform**: armbian (Ubuntu 16.04 LTS)

**Comment by shang-vikas** [comment]
**Update**: I tried running the sample code on my Raspberry Pi B+.
```
import os,sys,dlib,cv2
import time
detector = cv2.get_frontal_face_detector()
sp = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")
facerec = dlib.face_recognition_model_v1("dlib_face_recognition_resnet_model_v1.dat")

myface = cv2.imread('./myface.png')
GrayImg = cv2.cvtColor(myface,cv2.COLOR_BGR2GRAY)
while True:
    t1 = time.time()
    dets = detector(GrayImg,0)
    t2 = time.time()
    print('time taken for detection - {}'.format(t2 - t1))
    shape = sp(myface,dets[0])
    t3 = time.time()
    print('time taken for shape prediction - {}'.format(t3 - t2))
    face_features = facerec.compute_face_descriptors(myface,shape)
    t4 = time.time()
    print('time taken for computing features - {}'.format(t4 - t3))
```
After 5-8 iterations , the program gets stuck at face_features statement.
I think there is something terribly wrong with the dlib's SIMD implementation or maybe something else.
@davisking can you have a look or point me in some direction please??

**Comment by davisking** [comment]
You are probably just running out of ram and expecting a lot of disk swapping.

**Comment by shang-vikas** [comment]
That might be the case with Raspberry Pi, but Odroid has got 2 GB RAM so i am pretty sure its not getting out of RAM.
