### ISSUE TITLE
Advice regarding weights dump order in dlib resnet model

### ISSUE THREAD

**Issue by raffra** [davisking/dlib#1345]
Hello all,
we are trying to convert dlib resnet to pytorch (for example). We have extracted the xml file of the model using net_to_xml() function. We have a script ready which can be used to convert the xml to weights files. However we are unable to understand the order of the weight and bias dump for each layer. For example are the bias  followed by the weights for each layer, or vice versa? Also, how do we read the weights, for example as number of out channels x filter size x filter size x number of input channels or some other way?
Your help will be highly appreciated.
Thank you

**Comment by davisking** [comment]
You should look at the code for the layer.  It's only a few lines and you
can see how it uses the filter values.

**Comment by raffra** [comment]
Hi,
Thanks for the reply. When i look at the code  I found in lines 481 and 182 of layer.h file
 filters = alias_tensor(sub.get_output().k(), num_filters_, _nr, _nc); 
and 
filters = alias_tensor(num_filters_, sub.get_output().k(), filt_nr, filt_nc);
reshaping the 1d xml dump into 4d will give different results in each case.
so I should reshape the xml dump in which order?
Thanks.

**Comment by davisking** [comment]
When I type alias_tensor in google the first hit is dlib’s documentation that goes into this in detail.

**Comment by shang-vikas** [comment]
Hey @raffra ! I am working on a model that uses dlib and needs to be deployed on embedded hardware. Can you share you script to convert the xml to weight files? i wanted to try to use the weights to make a tflite model or Maybe NNAPI and use it.
