### ISSUE TITLE
Dlib was compiled to use SSE41 instructions which are not available on your machine.

### ISSUE THREAD

**Issue by satbirsinghsama** [davisking/dlib#1346]
I am using Ubuntu 16.04- x64, with Intel Xenon CPU, Nvidia Titan X graphics card.  

I installed Dlib version 19.13.99 from GitHub repo. Used Cmake version 3-9.0-rc5 to compile for python 3.5 64 bit, But every time I use "import dlib" the following message appears "dlib was compiled to useSSE41 instructions but are not available on your machine." 

I tried compiling with:
-DUSE_SSE2_INSTRUCTIONS which doesn't work. There is not any method in Cmakelists.txt file too which I can use. Can you Please suggest some other method.

Regards

**Comment by davisking** [comment]
-DUSE_SSE2_INSTRUCTIONS needs to be set to something.  Like
-DUSE_SSE2_INSTRUCTIONS=0.

**Comment by satbirsinghsama** [comment]
I used (=True;1 ;0). But still, the same message pops up.

**Comment by satbirsinghsama** [comment]
and while Cmake is running it shows the message "Manually-specified variables were not used by this project: 
USE_SSE2_INSTRUCTIONS"

**Comment by davisking** [comment]
look at the cmake options.  There is no such option.  Try SSE4, not SSE2.
