### ISSUE TITLE
dlib directly includes avx2intrin.h

### ISSUE THREAD

**Issue by lschilli** [davisking/dlib#135]
Note: The following report is based on observations on ubuntu trusty using gcc 4.8.4.

dlib includes `avx2intrin.h` in [`simd/simd_check.h`](https://github.com/davisking/dlib/blob/bb0ac566db00bc24e3948829431891542977d582/dlib/simd/simd_check.h#L76) if it is compiled with avx2 enabled.
Our project includes multiple libraries, specifically dlib and opencv 2.4 (the latter also makes use of `immintrin.h`). The compiler flags contain `-march=native -O3` which leads to `__AVX2__` being set (compiling on a newer i7 CPU) and dlib's check enables `DLIB_HAVE_AVX2` as expected.

In this case I get error messages like this:
```
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/avx2intrin.h: In function ‘__m256i _mm256_mpsadbw_epu8(__m256i, __m256i, int)’:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/avx2intrin.h:34:1: error: redefinition of ‘__m256i _mm256_mpsadbw_epu8(__m256i, __m256i, int)’
 _mm256_mpsadbw_epu8 (__m256i __X, __m256i __Y, const int __M)
```

In `/usr/lib/gcc/x86_64-linux-gnu/4.8/include/avx2intrin.h` the following check can be found:
```
#ifndef _IMMINTRIN_H_INCLUDED
# error "Never use <avx2intrin.h> directly; include <immintrin.h> instead."
#endif
```
This check is not triggered if `immintrin.h` was already included by another library.

To me it seems including `avx2intrin.h` directly is discouraged (at least in gcc 4.8.4). Maybe there is a special reason why dlib is including this file directly. If not, this would be an issue that could be fixed by changing [`simd/simd_check.h`](https://github.com/davisking/dlib/blob/bb0ac566db00bc24e3948829431891542977d582/dlib/simd/simd_check.h#L76) to not use `#include <avx2intrin.h>` but to use `#include <immintrin.h>`

**Comment by davisking** [comment]
Thanks for the report.  I removed the offending #include.  I recall adding it because some system needed to have it included, but I don't recall what.  I just ran a bunch of tests on different systems and compilers and all worked without that header, and as you point out, it's not supposed to be included.  So removing it seems to be a good idea.
