### ISSUE TITLE
Is there any more accurate face detection algorithm than dlib hog-SVM?

### ISSUE THREAD

**Issue by Jayhello** [davisking/dlib#1350]
##### Can any one give some advise or good reference ?

**Comment by davisking** [comment]
Yes, there is a CNN based face detector in dlib.  It's much more accurate.
The example programs show how to use it.

**Comment by Jayhello** [comment]
I mean not to use deep learning method ? Just traditional opencv method .

Can you give some advise ?

@davisking

**Comment by davisking** [comment]
No
