### ISSUE TITLE
Alignment issue with get_face_chips

### ISSUE THREAD

**Issue by DigitalHubRocks** [davisking/dlib#1351]
Hi, we realize that aligning the face with get_face_chips only performs a rotation to make the face upright, but does not perform an affine transformation to fix facial landmarks at standardized locations (meaning if a face is side facing, align it such that it becomes front facing). 

Was this intended and is such an affine alignment feature available natively in dlib?

Thank you!

**Comment by davisking** [comment]
You can't convert a side looking face to front facing with an affine transformation.  That's simply impossible.
