### ISSUE TITLE
Visual Studio linker error when compiling dlib 19.13 with CUDA 9.2 in release mode 

### ISSUE THREAD

**Issue by yjtan118** [davisking/dlib#1354]
## Current Behavior
Managed to compile dlib 19.13 with DLIB_USE_CUDA directives turned on in Visual Studio 2017 debug mode. Expecting that Release mode should compile without issues too, but am getting the following linker error:

Error	LNK2005	USER_ERROR__inconsistent_build_configuration__see_dlib_faq_1_ already defined in source.obj	Project	<project path>\dlib19.13.0_release_64bit_msvc1912.lib(test_for_odr_violations.obj)		

Error	LNK1169	one or more multiply defined symbols found	Project	<project path>\x64\Release\Project.exe		

## Steps to Reproduce
The linker dependencies in my VS 2017 look something like these:
D:\Lib\dlib\build\dlib\Release\dlib19.13.0_release_64bit_msvc1912.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudnn.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudart_static.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\curand.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cusolver.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cublas.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudadevrt.lib

* **Version**: dlib 19.13, CUDA 9.2
* **Where did you get dlib**: downloaded from dlib.net
* **Platform**: Windows 10, 64 bit
* **Compiler**: Visual Studio 2017 Prof ver 15.5.7

Is there something that I've overlooked? Rather strange as I'm not getting the error when compiling in Debug mode.
Thanks.

**Comment by yjtan118** [comment]
Somehow, I have to declare ENABLE_ASSERTS to get this compiled in Release mode.

**Comment by yjtan118** [comment]
I would still have to rely on the ENABLE_ASSERTS preprocessor directive specified and am wondering is this the right way of getting past the VS linker error with CUDA 9.2. Would the latest version of dlib fix this? Appreciate any comments to get CUDA compiled without ENABLE_ASSERTS in release mode. Thanks.

**Comment by yjtan118** [comment]
I'm still using ENABLE_ASSERTS to bypass the linker error and am wondering if this is the right way to fix this. Appreciate some comments here. Thanks.

**Comment by davisking** [comment]
No this is not the right thing to do. Did you read the faq suggested by the error? http://dlib.net/faq.html#WhydoIgetUSERERRORinconsistentbuildconfigurationseedlibfaq1

**Comment by davisking** [comment]
There is something deeply wrong with github right now, when I refresh this issue it's showing me 3 different versions of the posts here, seemingly selected at random.

**Comment by yjtan118** [comment]
Github was a bit cranky earlier, so I have created a new issue (1523) since the old thread can't be reopened. I'll close this one as it's a duplicate.
