### ISSUE TITLE
How to compare multiple vector<matrix<float, 0, 1>> face_descriptors ?

### ISSUE THREAD

**Issue by ashuezy** [davisking/dlib#1356]
Hi,

I am a beginner student and just starting with Machine Learning and running few examples. So please bear with me and i am sorry if i am asking wrong questions.

-Have 2 face images in std::vector<matrix<float, 0, 1>> unknown_face_descriptors and 2 images in another 2 face images vector<matrix<float, 0, 1>> known_face_descriptors;
 
**How do i compare these multiple face descriptors with each other for face recognition ?** 

I have executed the example containing the chinese_whisper algorithm but i am not looking to do clustering.

**Comment by davisking** [comment]
One of your classmates already asked about this (https://github.com/davisking/dlib/issues/1355).  You all need to do your own homework problems.  Don't go asking on github for other people to spoon feed you the answers, you will never learn if that's your attitude to programming.

**Comment by ashuezy** [comment]
@davisking 
Can you tell me if the name of class containing the method ?
