### ISSUE TITLE
Distance [Student Question] : Performance, Accuracy ?

### ISSUE THREAD

**Issue by ashuezy** [davisking/dlib#1357]
@davisking 

Sorry for bothering you yesterday but the problem was that intellisense in Visual Studio was not working so i was unable to look into details. Anyways, I did manage to check the distance but i would like your advice regarding the performance and accuracy. 

```
	for (auto&& a : known_face_descriptors)
	{
		for (auto&& b : unknown_face_descriptors)
		{
			cv::Mat cvFace1 = toMat(a);
			cv::Mat cvFace2 = toMat(b);

			std::cout << endl << cv::norm(cvFace1, cvFace2) << std::endl;
		}
	}
```
- Is this accurate enough to be used in real life ?
- Is it faster/slower to np.linalg.norm in numpy ?
- Is there is a faster way available to calculate euclidean_distance ?
- There is a struct squared_euclidean_distance in dlib also but i am getting different results. Why is that ?

**Comment by davisking** [comment]
These sound like more homework questions.  And even if they aren't you shouldn't be asking "google this for me" questions on github.
