### ISSUE TITLE
Global optimization with automatic differentiation ? 

### ISSUE THREAD

**Issue by blackball** [davisking/dlib#1358]
Hi, 

I am playing around with dlib's find_max_global method in Python. Nowadays in Python, we could easily differentiate the cost function with packages  like autograd, AlgoPy, etc. I wonder whether providing gradient function could improve find_max_global or not. Or better to use other method(s) in this case ?  

Thanks,

**Comment by davisking** [comment]
It's not that simple.  Consider for example an objective function that does cross validation of a binary classifier and measures the number of times the classifier makes a classification error.  That objective function is piece-wise constant and therefore its derivative is 0 essentially everywhere. That derivative tells you nothing useful for optimization.  Many things are like this.  

But yes, if you had a function that is smooth then you could use the derivatives profitably.  But that's not really the situation in many hyper parameter optimization settings, which is the intended use for find_max_global().
