### ISSUE TITLE
Crosshair not appearing after installing imglab.exe

### ISSUE THREAD

**Issue by AmandaBoatswain** [davisking/dlib#1360]
Hi Davisking, 

I compiled the imglab software on my computer using Visual Studio and created an imglab.exe file. The software opens up properly when I run  the imglab -c command with a .xml file and  dataset path from the command window, but the cross-hairs for drawing bounding boxes are not working or appearing on the GUI while I press the shift key. I have tried using the arrow keys to surf through the image directory and that works. No error messages appear. 

The version of Dlib that I am using is dlib-19.13, I downloaded it directly from http://dlib.net/. I am working on Windows 10, 64 bit. The C and CXX compiler I used are both the MSVC  version 19.0.24210.0.

**Comment by davisking** [comment]
I have no idea.  It works fine for me with the same setup as you describe.
You probably just have an old copy by accident.

**Comment by AmandaBoatswain** [comment]
I just downloaded the most recent version of dlib from your github page. I recompiled dlib using the same method and the issue was fixed! Thank you!
