### ISSUE TITLE
Not able to train DNN model

### ISSUE THREAD

**Issue by PawanWagh** [davisking/dlib#1368]
I am trying to train DNN model using this program dnn_imagenet_train_ex.cpp for my sample dataset.
This is the output on my console
```
SCANNING IMAGENET DATASET

images in dataset: 19527
step#: 0     learning rate: 0.1   average loss: 0            steps without apparent progress: 0

**************************** FATAL ERROR DETECTED ****************************

Error detected at line 322.
Error detected in file /home/ubuntu/dlib/dlib/../dlib/dnn/loss.h.
Error detected in function double dlib::loss_multiclass_log_::compute_loss_value_and_gradient(const dlib::tensor&, const_label_iterator, SUBNET&) const [with const_label_iterator = __gnu_cxx::__normal_iterator<long unsigned int*, std::vector<long unsigned int> >; SUBNET = dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::fc_<1000ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::avg_pool_<0l, 0l, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<512l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<512l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<512l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<512l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag2>, dlib::add_layer<dlib::avg_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_skip_layer<dlib::tag1, dlib::add_tag_layer<2ul, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<512l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<512l, 3l, 3l, 2, 2, 0, 0>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<256l, 3l, 3l, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0u>, dlib::add_layer<dlib::con_<256l, 3l, 3l, 1, 1, 1, 1>, dlib::add_tag_layer<1ul, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib
******************************************************************************

Aborted (core dumped)
```

dlib Version: 19.13.99 form your github repo
Platform: ubuntu 16.04 64-bit
Compiler: gcc 5.4.0

I am running on 1 NVIDIA K80 GPU, 4 vCPUs and 61 GiB of host memory, with a combined 48 GB of GPU memory. I am having Intel MKL BLAS/LAPACK library installed along with CUDA version 9.

Is this a mess up of misconfiguration ?

**Comment by davisking** [comment]
There should have been more text in that error message.  Is that really all that came out?

In any case, this is happening because the network must produce a number of outputs equal to the number of labels in your dataset, but you have these numbers missmatched.  Look at that line in the code generating the error, there is text to that effect there.

**Comment by PawanWagh** [comment]
Yes. This all i have on the console.

**Comment by PawanWagh** [comment]
Yes you were right. This is were i am getting the error. 
```
// The network must produce a number of outputs that is equal to the number
// of labels when using this type of loss.
DLIB_CASSERT(y < output_tensor.k(), "y: " << y << ", output_tensor.k(): " << output_tensor.k());
```
How can i resolve this ?

**Comment by PawanWagh** [comment]
Is this because the dataset i am using have uneven number of images per classes like some classes are having 10 and some classes have only 1 image.

**Comment by davisking** [comment]
No.  That’s got nothing to do with it.

**Comment by PawanWagh** [comment]
@davisking: Can you please suggest how i can resolve this ? any clue ?

**Comment by PawanWagh** [comment]
Hi,
Can you please suggest how i can resolve this ?

**Comment by davisking** [comment]
I told you, this is happening because the network must produce a number of outputs equal to the number of labels in your dataset, but you have these numbers missmatched.  Make the number of outputs from the network match the number of classes in your dataset.

**Comment by PawanWagh** [comment]
Hey, thanks. My silly mistake.

**Comment by PawanWagh** [comment]
I had read your blog and related articles but didn't find anything related.
Just wanted to ask if there any image dimension restrictions for training model with my dataset.
like i have 200k images with 8513 unique labels of varying dimension eg., some are 150x150 while some are 80x80 or uneven. Can this affect my accuracy.
also many of the images have guys wearing sunglasses, can this images be used for training ?

**Comment by PawanWagh** [comment]
Hi,
After training i have 2 dat files of 187 MB each even though i had only 200k faces whereas you trained for 3 million faces and still your dat file is around 22 MB.
Do you know what could have went wrong ?
Thank you.

**Comment by PawanWagh** [comment]
now when i try to use my own trained model i have this error - 
An error occurred while trying to read the first object from the file 
`/home/ubuntu/face-recog/node_modules/face-recog-models/models/dlib_face_recognition_resnet_model_v1.dat.
Unexpected version found while deserializing dlib::add_loss_layer.
terminate called after throwing an instance of '
dlib::serialization_error`

**Comment by wangx404** [comment]
Hi, did you finally solve this problem? Recently, I found dlib's face recognition accuracy was quite low on Asian people. 3Q.
