### ISSUE TITLE
Help regarding DLib

### ISSUE THREAD

**Issue by praveenlovely** [davisking/dlib#137]
Hi Dr.Davis,

Thanks for your awesome Face Recognition Package DLib.
I am doing some research on biometrics and on my due progress, I heard about your package and started using it today. It is really awesome. I am using your frontal face detector and also the shape predictor classes right now. The results and the output was extraordinary.
But, now I am looking for this,
I would like to crop the ocular region in a face image. Would that be possible?
Also let me know if you have more interesting things in your package that I would be making use of!
Thanks again on your help.

**Comment by davisking** [comment]
You can certainly crop out the eyes.  The shape predictor example program includes examples of cropping out the entire head.  If you look at the code that implements that it should be obvious what to do.  The rest of dlib is documented on the dlib.net web page.

**Comment by praveenlovely** [comment]
Thanks sir!
Will try it out and will let u know.

Thanks and regards,
Praveen Kumar P.S
Masters in Information Assurance and Cyber Security.

**Comment by praveenlovely** [comment]
Does Dlib have a function to crop the faces?
I did not find out an option for cropping the head. 
A link of it would help

**Comment by davisking** [comment]
Yes, it's part of the example: http://dlib.net/face_landmark_detection_ex.cpp.html

**Comment by praveenlovely** [comment]
Oh thank you sir,
But like I said, I am using the python version of DLib.
Can you get this to me in Python?

On Wednesday, June 15, 2016, Davis E. King <notifications@github.com> wrote:

> Yes, it's part of the example:
> http://dlib.net/face_landmark_detection_ex.cpp.html
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davisking/dlib/issues/137#issuecomment-226360674>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQTnBd1fNOjCbb35FcGv2XWz1PMZkqGQks5qMJ2IgaJpZM4I17ng>
> .
>


-- 
Regards,
Praveen Kumar P S
Masters in Cybersecurity

**Comment by davisking** [comment]
You didn't mention python.  There is no crop function in dlib's python api.  There are lots of ways to crop images with existing python tools though.

**Comment by praveenlovely** [comment]
Ya. I tried cropping through openCV and it works.
So to detect eyes, what method do you suggest?
Train some eyes and use the classifier to the test dataset?

On Thursday, June 16, 2016, Davis E. King <notifications@github.com> wrote:

> You didn't mention python. There is no crop function in dlib's python api.
> There are lots of ways to crop images with existing python tools though.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davisking/dlib/issues/137#issuecomment-226456970>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQTnBcLLexf9boXk9AUSQ8-_5vMwc8gTks5qMTCzgaJpZM4I17ng>
> .
>


-- 
Regards,
Praveen Kumar P S
Masters in Cybersecurity

**Comment by davisking** [comment]
Have you looked at the facial landmark output?  It tells you where all the
parts of the face are, including the eyes.

**Comment by praveenlovely** [comment]
Oh. So do you think I could just drop from it?

On Thursday, June 16, 2016, Davis E. King <notifications@github.com> wrote:

> Have you looked at the facial landmark output? It tells you where all the
> parts of the face are, including the eyes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davisking/dlib/issues/137#issuecomment-226471301>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQTnBYLTbZHBuIpEgRT5RnHkjzsaT5Eqks5qMUIbgaJpZM4I17ng>
> .
>


-- 
Regards,
Praveen Kumar P S
Masters in Cybersecurity

**Comment by davisking** [comment]
Yes

**Comment by praveenlovely** [comment]
In the facial landmarking, you are using a classifier predictor and it
gives out shape as an output.
But the part 0 and part 1 of the shape array doesn't seem to be relevant to
the eye coordinates.
Could you explain?

Thanks and regards,
Praveen Kumar P.S
Masters in Information Assurance and Cyber Security.

**Comment by praveenlovely** [comment]
Any ideas sir?

**Comment by praveenlovely** [comment]
So as a progress, I have found that the shape list consists of several landmark points which are finally joined using the add_overlay function.
However, do you have any possibility to reveal on which corresponding points consist the nose and eye centres?  So, how many landmarking points are captured by DLib?

**Comment by e-fominov** [comment]
@praveenlovely , 68 landmarks, take a look here https://matthewearl.github.io/2015/07/28/switching-eds-with-python/
And I recommend you using http://stackoverflow.com/questions/tagged/dlib or https://sourceforge.net/p/dclib/discussion/442518/ for asking support - you will get answers with less time. 
Github is for issues/suggestions and other development tasks

**Comment by praveenlovely** [comment]
Thanks a lot for your guidance. This is exactly what I have been looking
for. Will do it like that from now!

Thanks and regards,
Praveen Kumar P.S
Masters in Information Assurance and Cyber Security.
