### ISSUE TITLE
affine layer empty_params

### ISSUE THREAD

**Issue by ShuangLiu1992** [davisking/dlib#1376]
hi davis

when runnning dlib::visit_layer_parameters it calls get_layer_params(), affine layer doesn't return the actual gamma and beta but instead return empty_params, why is this? To be able to read the params does one have to call to_xml then parse the string for the affine layer?
```
        const tensor& get_layer_params() const { return empty_params; }
        tensor& get_layer_params() { return empty_params; }
```

**Comment by ShuangLiu1992** [comment]
you can get them with bn_con with bn_fc, but once the model is convert to affine layers and saved to the disk, I don't think it's easy to convert it back, is it?

**Comment by davisking** [comment]
Yeah, I guess affine_ is over encapsulated.  There need to be member functions that return the layer parameters you are asking about.  You should submit a PR :)
