### ISSUE TITLE
Error instatiating simple_object_detector from multiple simple_object_detectors

### ISSUE THREAD

**Issue by visionworkz** [davisking/dlib#1378]
## Description
When loading multiple separately trained fhog detectors, creating a simple_object_detector from a list of other simple_object_detectors fails.

## Expected Behavior
The simple_object_detector should be instantiated or give a better error message describing why it cannot be instantiated.

## Current Behavior
The construction fails on the following line:
```
detectors = dlib.simple_object_detector([detector_left, detector_frontal, detector_right])
```
The following error message is shown:
```
Error detected in function dlib::object_detector<image_scanner_type_>::object_detector(const image_scanner_type&, const dlib::test_box_overlap&, const std::vector<typename image_scanner_type_::feature_vector_type>&) [with image_scanner_type_ = dlib::scan_fhog_pyramid<dlib::pyramid_down<6u> >; dlib::object_detector<image_scanner_type_>::image_scanner_type = dlib::scan_fhog_pyramid<dlib::pyramid_down<6u> >; typename image_scanner_type_::feature_vector_type = dlib::matrix<double, 0l, 1l>].

Failing expression was w_[i].size() == scanner_.get_num_dimensions() + 1.
	 object_detector::object_detector(scanner_,overlap_tester,w_)
	 Invalid inputs were given to this function 
	 scanner_.get_num_detection_templates(): 1
	 w_[1].size():                     4465
	 scanner_.get_num_dimensions(): 4433
	 this: 0x7ffd8cde87f0
```

## Steps to Reproduce
Train two or more models with different pose for the same object

* **Version**: HEAD
* **Where did you get dlib**: Github Repo
* **Platform**: Ubuntu
* **Compiler**: gcc

**Comment by davisking** [comment]
You can only use that interface if all the models use the same sliding
window setup.  You should use the run_multiple() interface instead.

**Comment by visionworkz** [comment]
Is there a way I can force the model to use a particular sliding window while training? `run_multiple` does not have non-max suppression and `evaluate_detectors` does not seem to be exposed in Python.

**Comment by davisking** [comment]
If you make all the training rectangles have the same aspect ratio then the detectors will be compatible.

**Comment by davisking** [comment]
I just added fields that let you see the window size being used so this is
less inscrutable.

**Comment by visionworkz** [comment]
We should close this if you think this is a good enough resolution?

**Comment by davisking** [comment]
Yeah, it's fine with me.

**Comment by mrgloom** [comment]
Looks like `dlib.fhog_object_detector.run_multiple` doesn't have NMS.

Using `dlib.simple_object_detector` I get error: `RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)` what does it mean?

Example of usage:
```
frontal_detector = dlib.fhog_object_detector('dlib_resources/frontal_detector.svm')
left_detector = dlib.fhog_object_detector('dlib_resources/left_detector.svm')
right_detector = dlib.fhog_object_detector('dlib_resources/right_detector.svm')
detector_list = [frontal_detector, left_detector, right_detector]

for d in detector_list:
    print('d.detection_window_height', d.detection_window_height)
    print('d.detection_window_width', d.detection_window_width)
    print('d.num_detectors', d.num_detectors)

detector = dlib.simple_object_detector(detector_list)
```

**Comment by davisking** [comment]
It for sure runs NMS.  The separate detectors don't NMS each other though.  Running `run_multiple` is identical to running each detector separately.  It's just that `run_multiple` is faster sometimes.

I guess that other part of the python api doesn't support that?  It doesn't have all possible overloads for all C++ types.
