### ISSUE TITLE
Correlation_tracker class needs an id field.

### ISSUE THREAD

**Issue by dexception** [davisking/dlib#1379]
An auto generated unique numerical id field would help in tracking the uniqueness of the object among multiple trackers. I am right now storing the same in other variable and it would help if this inside the class.
Thanks.

**Comment by davisking** [comment]
It's not so easy to do this since the correlation tracker algorithm doesn't naturally provide any id information.  But if you want to implement an extension that uses some reasonable algorithm to do this and submit a PR that would be cool :)
