### ISSUE TITLE
How does dlib face aligment works?

### ISSUE THREAD

**Issue by Jayhello** [davisking/dlib#1382]
After get 5 face landmarks then use it to do face alignment.I have see a example from:
http://dlib.net/face_alignment.py.html  and `face_landmark_detection_ex.cpp` in the dlib examples directory.

My question is: 
1. How does this work (align face by 5 points)?

2. Is there any reference ?

And I use MTCNN to do face detection and landmark(also five points),  I have do face alignment by `opencv warpAffine`, but it does't work well. And want to ues dlib's method(it works well), But I don't know how to realize it ?

Can you give any suggest?

**Comment by davisking** [comment]
It just warps the image so the 5 points are in some canonical upright and
centered pose.  There isn't a reference, it's just doing the simple thing
that everyone does for this kind of thing.  Why do you have to call some
function in opencv?  Just call the dlib function.

**Comment by Jayhello** [comment]
Thank you for reply, I have solved it by https://stackoverflow.com/questions/26279853/how-to-store-all-the-pixels-within-a-rotatedrect-to-another-matrix/26284491#26284491 this method.

The reason for why I use opencv, because I use MTCNN caffe to do face detection and landmark, so I can't introduce dlib.

The method `MTCNN` detect face much more accurate the `dlib's` method.

Does you have any plan to realize `MTCNN` by dlib for face detection?

**Comment by davisking** [comment]
Have you tried the CNN face detector in dlib?  It's much more accurate than dlib.get_frontal_face_detector().

**Comment by Jayhello** [comment]
Yes, I have tried it, but it is less accurate than MTCNN [a good caffe implement can be found here](https://github.com/wowo200/MTCNN)

**Comment by Jendker** [comment]
I am sorry for writing in the closed issue, but was just curious.
When we are doing alignment we are not actually running any face detector? We are just doing the extraction of 5 feature points on the face which will be aligned?

Because you mentioned the CNN face detector, so I am wondering.

**Comment by davisking** [comment]
You are finding a face, determining its orientation, and then cropping out an appropriately rotated image.
