### ISSUE TITLE
segmentation fault when import dlib and torch

### ISSUE THREAD

**Issue by xubaoquan33** [davisking/dlib#1383]
I run .py in ubuntu, but i get error:segmentation fault. I check the code and find that when i import dlib and import torch,the error appear.like the follow:

`Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> import torch

Segmentation fault`

I change the order of import ,i still get the error.

so, i change the version of dlib.I use the dlib==19.5.0 instead. it success.
So why it happens for the latest version.I check the dlib==19.10.it alse appear error.

* **Version**:  19.13.99
* **Where did you get dlib**:  github 
* **Platform**:  ubuntu 14
* **Compiler**:  python

**Comment by davisking** [comment]
This doesn't happen when I try it, however, I'm not using anaconda.  My experience with anaconda is that it generally breaks things and is gratuitously incompatible with many other libraries and tools.  Does this happen if you use the system python?  If not then what are the exact commands that I can type at an ubuntu shell, starting with setting up anaconda however you have it setup, that causes this to happen?

**Comment by xubaoquan33** [comment]
@davisking 
in fact, I use a docker . the linux version is :
Linux version 4.2.0-42-generic (buildd@lgw01-55) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016

**above is my test in another environment,it use anaconda,but still get the error.following is the error in my linux in docker**

Python 2.7.6 (default, Nov 23 2017, 15:49:48)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import dlib
Segmentation fault

following is the record by gdb. I hope it can help you solve the problem.

Starting program: /usr/bin/python detect_landmarks_in_image.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fffbea5427e in ?? () from /usr/local/lib/python2.7/dist-packages/dlib.so
(gdb)

if i change the order of import in the py file,the error will change.like following.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fffcd2d6a53 in pybind11::detail::make_new_python_type (rec=...) at /pytorch/third_party/pybind11/include/pybind11/detail/class.h:564
564     /pytorch/third_party/pybind11/include/pybind11/detail/class.h: No such file or directory.
(gdb)

**Comment by developer-mayuan** [comment]
Have the same issue:

dlib:
    Version: 19.10
    Where did you get dlib: conda install -c conda-forge dlib
    Platform: ubuntu 18.04
    Compiler: python 3.6

**Comment by davisking** [comment]
I was not able to reproduce. I doubt this is a bug in dlib. 

I’m not doing anything here until someone posts exact instructions for reproducing the error. This means commands I can copy and paste into an Ubuntu terminal from a clean Ubuntu install.

**Comment by KeyKy** [comment]
I can get the same problem!! Need help!!
```
import torch
import dlib
Segmentation fault
```

**Comment by Davidrjx** [comment]
me too

**Comment by Davidrjx** [comment]
@all, most likely that cudnn runtime and development libs version is root cause.

**Comment by DongHwanJang** [comment]
@Davidrjx Did you solve this problem..?

**Comment by Davidrjx** [comment]
@DongHwanJang yes

**Comment by furkanese** [comment]
@Davidrjx  Could you walk us through to solve it, I'm getting the same error.

**Comment by Davidrjx** [comment]
@furkanese at that time, i used dockerfile for tf and pytorch dlib-gpu build test, some core snippets as follows
```
...
ENV CUDA_VERSION=9.0.176 
ENV CUDA_PKG_VERSION 9-0=$CUDA_VERSION-1
RUN ln -s /usr/local/cuda-9.0 /usr/local/cuda &&\
	# above link for dlib CUDA_TOOLKIT_ROOT_DIR variable search
    apt-get update &&\
    # install some extra packages, especially, cmake as dlib build tools
    apt-get install -y --no-install-recommends pkg-config\
    cmake\
    # install an optimized BLAS compared to dlib's built-in one
    libopenblas-dev liblapack-dev \
    # three libraries used for dlib variables dependencies
    cuda-cublas-dev-$CUDA_PKG_VERSION\
    cuda-curand-dev-$CUDA_PKG_VERSION\
    cuda-cusolver-dev-$CUDA_PKG_VERSION\
    #cudnn development files for dlib cudnn dependencies
    libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 &&\
    apt-get clean && rm -rf /var/lib/apt/lists/*
ADD . /usr/local/src/
WORKDIR /usr/local/src/
RUN cd dlib/dlib &&\
    mkdir build && cd build &&\
    /usr/bin/cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda &&\
    /usr/bin/cmake --build . && cd ../../ && ls -l && python3 setup.py install
...
```
hope that can help!

**Comment by zhuhaozh** [comment]
Same problem. anyone knows how to solve it? 

ENV:
dlib 19.17
pytorch 0.4.1

**Comment by zhuhaozh** [comment]
> Same problem. anyone knows how to solve it?
> 
> ENV:
> dlib 19.17
> pytorch 0.4.1

Solved by reinstalling the dlib: 

pip uninstall dlib  # 19.17.0
pip install dlib      # 19.21.1
