### ISSUE TITLE
Does the landmark order matter?

### ISSUE THREAD

**Issue by off99555** [davisking/dlib#1384]
In dlib face, there are 68 points. Is it necessary that you have to order them right?
For example, you might label your eyebrow first before your cheek if order doesn't matter.
And what if the landmark labeler mislabeled the number of points to, say 67 or 69?
I have an image of a mouth, not the entire face, and I want to put landmarks around that. 

Also I don't want to detect boxes, I only want to detect landmarks, as I know the image will be of a mouth from VR camera. So there is no need to find the mouth there, because it always exists.
Is it possible to train landmark detector model without box around it?

**Comment by davisking** [comment]
Order is irrelevant but you obviously have to label your data consistently.

**Comment by off99555** [comment]
When I say order matters, I mean if I choose to put landmark 1 at the eyebrow, I can't later change it to be on the mouth later. Do I understand this right? Or is it really doesn't matter at all.

**Comment by davisking** [comment]
You can have any number of landmarks.  You don't have to even be annotating
faces.  You could be annotating the parts of a stop sign.  But whatever you
are doing you need to consistently put the same points on the same parts of
whatever objects you are annotating.

**Comment by off99555** [comment]
OK. So it means that order matters in the case that it needs to be the same for all images. Thank you.
