### ISSUE TITLE
image2.cpp does not compile in MSVC debug mode

### ISSUE THREAD

**Issue by MaxBareiss** [davisking/dlib#1385]
## Expected Behavior

I expect dlib to compile in debug mode in Visual Studio 2015.

## Current Behavior

I get the following errors when I compile in Debug Mode in Visual Studio 2015:

```
C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(91): error C2039: 'nr': is not a member of 'dlib::numpy_image<float>'
  C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(80): note: see declaration of 'dlib::numpy_image<float>'
C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(91): error C2672: 'std::size': no matching overloaded function found
C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(91): error C2780: 'size_t std::size(const _Ty (&)[_Size]) noexcept': expects 1 arguments - 0 provided
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(1486): note: see declaration of 'std::size'
C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(91): error C2780: 'unknown-type std::size(const _Container &)': expects 1 arguments - 0 provided
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(1478): note: see declaration of 'std::size'
C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(91): error C2039: 'nc': is not a member of 'dlib::numpy_image<float>'
  C:\Users\maxb2\git\dlib\tools\python\src\image2.cpp(80): note: see declaration of 'dlib::numpy_image<float>'
```

When I comment out the offending lines ([image2.cpp:83-91](https://github.com/davisking/dlib/blob/master/tools/python/src/image2.cpp#L83-L91)) it compiles correctly, but obviously this is not desirable. The code compiles correctly in release mode.

## Steps to Reproduce

1. Get the latest version of dlib
2. Configure CMake for Visual Studio 2015
3. Open Visual Studio solution and set to the Debug configuration
4. Compile solution

* **Version**: 

dlib 8fdb3af9b

* **Where did you get dlib**: 

Git

* **Platform**: 

Windows 10 Version 1803 64 Bit

* **Compiler**: 

MSVC 2015

**Comment by davisking** [comment]
Thanks for reporting this.  I just pushed the fix to github, so it should
be working properly now.
