### ISSUE TITLE
How does add_overlay() know which points are connected?

### ISSUE THREAD

**Issue by off99555** [davisking/dlib#1388]
![2018-06-28_19-02-55](https://user-images.githubusercontent.com/15215732/42050474-393c6f64-7b33-11e8-8cba-85d321180210.png)
As far as I know, those 68 points in blue do not have information about how they connect to each other. So how can you plot connected points by just running `dlib.image_window().add_overlay(landmarks_predicted_by_shape_predictor)`?

Where does the information about how to draw lines come from?

**Comment by off99555** [comment]
I get it now. The `add_overlay()` method is not designed for general purpose. It's specifically for 68 or 5 landmarks only. So, it's designed for facial landmarks. That's why it contain hardcoded info on how to connect these landmarks by lines.
When my model doesn't predict 5 or 68 points, it reports an error.

I think this method name should be changed to something more specific like `add_overlay_face()`. If it's legacy code then the documentation of this method should be updated to reflect that it's not general and specific only to facial landmarks.

**Comment by davisking** [comment]
It’s more general. There are many overloads of add_overlay() different objects. So it’s already got an appropriate name for what it does. 

Also, in the newest dlib code it will draw other sets of points with dots in addition to its current behavior.

**Comment by davisking** [comment]
I think the current behavior is fine, but if you want to make some improvement please submit a PR.

**Comment by off99555** [comment]
I'm fine with it for now. `add_overlay_circle()` works for me.
