### ISSUE TITLE
[Question] Finding a vector valued regression model

### ISSUE THREAD

**Issue by MDBrothers** [davisking/dlib#1389]
I have data samples in R^4 (an rgb color and a distance) and I want to use them to build a regression model to match observations in R^3 (an rgb color).

Is there a way in dlib, directly or indirectly, to build a model that takes values from R^4 and produces values in R^3 based upon my data? All of the regression examples for the various methods in dlib show scalar dependent variables and I'm not sure where and if this is a strict requirement.

I have seen some earlier responses on the sourceforge page from some years ago mention something about using empirical_kernel_map in response to a question similar to mine but I don't really understand the advice, that is it isn't obvious how it helps me obtain three scalars per input from the trained model.

Thanks

**Comment by MDBrothers** [comment]
Ok that's what I suspected. 

You said most, are there some methods being researched that I could look into if separate regressions doesn't work?

**Comment by davisking** [comment]
It really depends on your problem.  There are lots of cases where people
learn models that output more than just one number.  There is a whole field
of structured prediction that specifically focuses on this. It's super
broad and the general idea is to incorporate some kind of prior knowledge
or place some kind of regularizer or assumption about the overall structure
of the outputs into the model. A specific example is something that does
image segmentation. Many segmentation models explicitly try to model the
fact that neighboring regions are likely to have either the same labels or
labels that are correlated in some way.

Anyway, don't worry about it.  Your problem doesn't sound like one of these
more complex situations, just do the simple thing, at least to start with.

**Comment by MDBrothers** [comment]
Actually a structured prediction sounds great.

I'm actually trying to emulate the stain and growth of mold. It is
observable that its development is affected by the structure of the growth
medium. Speaking of color film this can include what colors were where and
how sharp the gradients are. Some of this structural information I'm trying
to include directly in the samples.
