### ISSUE TITLE
use multi dnn detectors 

### ISSUE THREAD

**Issue by slmanali** [davisking/dlib#1390]
how to use multi dnn object detectors  like in function "std::vector<rectangle> evaluate_detectors"

**Comment by davisking** [comment]
No, there is no equivalent function.  For the dnns you just call them like normal.

**Comment by slmanali** [comment]
like this
for(int i=0;i<detectors.size()-1;i++)
    {
        for (auto&& d : detectors[i](img))
        {
            dlib::rect_detection rect;
            rect.detection_confidence=d.detection_confidence;
            rect.rect=d.rect;
             std::string::size_type sz;   // alias of size_t
            rect.weight_index=std::stoi (d.label,&sz);
            rects.push_back(rect);
        }
    }
