### ISSUE TITLE
use multi dnn detectors 1

### ISSUE THREAD

**Issue by slmanali** [davisking/dlib#1391]
like this
for(int i=0;i<detectors.size()-1;i++)
{
for (auto&& d : detectorsi)
{
dlib::rect_detection rect;
rect.detection_confidence=d.detection_confidence;
rect.rect=d.rect;
std::string::size_type sz; // alias of size_t
rect.weight_index=std::stoi (d.label,&sz);
rects.push_back(rect);
}
}

**Comment by davisking** [comment]
Yes, a good old for loop is all you need.

**Comment by slmanali** [comment]
i get error when this line execute  "rects.push_back(rect);"
can i speedup this loop?
