### ISSUE TITLE
The 《Segmentation fault (core dumped) 》bug of import lasted dlib and pytorch 

### ISSUE THREAD

**Issue by jianwu585218** [davisking/dlib#1394]
Hi，I got a trouble that when i import torch and the lasted dlib in linux , it will get《Segmentation fault (core dumped) 》error. I found that install dlib-19.8.1 in win10 will be fine.
So I try to install 19.8.1 in linux ,after I download the dlib-19.8.1.tra.gz
and use command:pip install dlib-19.8.1.tra.gz, it shows successfully install 
![image](https://user-images.githubusercontent.com/34296200/42135842-880f229c-7d83-11e8-84a8-ad74646f3177.png)
But when i import dlib ,there is a new bug 
![image](https://user-images.githubusercontent.com/34296200/42135851-a7992662-7d83-11e8-8460-2c6e7cb24f61.png)
Please help me,Thank you very much

**Comment by davisking** [comment]
Try the latest dlib version.

**Comment by jianwu585218** [comment]
Thanks for your reply.
I install the latest dlib version in the first . When i import the latest and torch in linux ,will get the 《Segmentation fault (core dumped) 》error.
![image](https://user-images.githubusercontent.com/34296200/42141253-9d368ac8-7dda-11e8-860c-d8eb8b7483fe.png)
I Install mang version , the dlib 19.8.1 with pytorch0.4 in other's machine is fine. So i want install dlib 19.8.1, but import dlib19.8.1,I get the <undefined symbol> error

**Comment by jianwu585218** [comment]
the face_recognition use the dlib

**Comment by davisking** [comment]
Ok, well, you need to fill out the issue template and follow its instructions if you expect to get any help.  **In particular, include exactly what I can type starting from a clean ubuntu install to reproduce this problem.**

**Comment by wxy656** [comment]
l get the same problem when I  use cuda 8.0 and cudnn7  ，while use cuda8.0 and cudnn6 ,the error is: 
  Error while calling cudnnActivationForward(context(), relu_activation_descriptor(), &alpha, descriptor(src), src.device(), &beta, descriptor(dest), dest.device()) in file /opt/dlib-master/dlib/cuda/cudnn_dlibapi.cpp:1465. code: 9, reason: CUDNN_STATUS_NOT_SUPPOR

**Comment by ailias** [comment]
The command like this. @davisking 
demo.py:
import dlib
import torch
# other code

$ python3 demo.py
Segmentation fault (core dumped)

**Comment by davisking** [comment]
Please read the issue submission instructions and follow them to submit a bug report.

**Comment by sunguwei** [comment]
I happened the same problem when I used the face detection function of dlib. Also follow the instruction above. I move the import dlib front of import torch. Amazing, it worked. Hope someone can tell the reason.

**Comment by jianwu585218** [comment]
@sunguwei I don't konw the reason.Please tell me if you find the reason ,thank u

**Comment by yushizhiyao** [comment]
> I slove it but i don't why.
> you should import face_recognition before torch,such as:
> ![image](https://user-images.githubusercontent.com/34296200/43120709-cb840110-8f4d-11e8-9351-3991abaeee19.png)

same error , it works to me. Have you found the reason
