### ISSUE TITLE
is_integer_variable no typecasting in Python

### ISSUE THREAD

**Issue by suuuehgi** [davisking/dlib#1395]
## Expected Behavior
For `dlib.find_min_global` and `dlib.find_max_global`, argument `is_integer_variable` is always producing floats. If `is_integer_variable` is set to `True` for a parameter, I expect it to be of type integer.

## Current Behavior
`is_integer_variable` produces integer floats.

## Steps to Reproduce
```python
import dlib

def test(p1,p2,p3):
    print(p1,p2,p3)
    print(type(p1), type(p2), type(p3))
    return 0

dlib.find_max_global(test,
   [1, 1, .0000001],
   [200, 100, .9],
   is_integer_variable=[True, True, False],
   num_function_calls=5)
```
```
101.0 51.0 0.4505
<class 'float'> <class 'float'> <class 'float'>
47.0 77.0 0.1326073181638293
<class 'float'> <class 'float'> <class 'float'>
57.0 45.0 0.12239850840155948
<class 'float'> <class 'float'> <class 'float'>
158.0 81.0 0.06164348877954179
<class 'float'> <class 'float'> <class 'float'>
114.0 90.0 0.5698208834696908
<class 'float'> <class 'float'> <class 'float'>
```

* **Version**: 19.13.1
* **Where did you get dlib**: pip3 install --user dlib
* **Platform**: 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux
* **Compiler**: gcc: 8.1.1, cmake: 3.11.4

**Comment by davisking** [comment]
This is on purpose.  It is very common for optimization problems that have
integer constraints to nevertheless evaluate generic linear algebraic
expressions on those variables and casting some variables to int makes that
irritating to deal with.

**Comment by suuuehgi** [comment]
Thank you for your reply!

Then I strongly suggest adding a note to [dlib.find_max_global](http://dlib.net/python/index.html#dlib.find_max_global) and dlib.find_min_global respectively.

Currently it states

> subject to the constraints:
> min(bound1[i],bound2[i]) <= x[i] <= max(bound1[i],bound2[i]) if (is_integer_variable[i]) then x[i] is an integer.

what is wrong. It's an integer represented as float but nevertheless a float.
It took me a while to find out what caused my cryptic error message and actually I don't want to clutter my code with `assert`'s where the API clearly promises something.

**Comment by davisking** [comment]
Yeah, that's ambiguous.  Thanks for pointing it out.  I just pushed a clarified version to github.

**Comment by suuuehgi** [comment]
All right! Thank you! :-)

**Comment by davisking** [comment]
No problem :)
