### ISSUE TITLE
divided by zero using auto_threshold_image with all pixels same

### ISSUE THREAD

**Issue by troublecoder** [davisking/dlib#1396]
## Expected Behavior
it shouldn't be occur divided by zero exception

## Current Behavior
when all pixel are same color, devided by zero exception is occured

## Steps to Reproduce

```
    dlib::matrix<unsigned char> matrix = dlib::uniform_matrix(100, 100, static_cast<unsigned char>(0));
    dlib::matrix<unsigned char> binarized;
    dlib::auto_threshold_image(matrix, binarized);
```

from thresholding.h
```
            long new_a = (a_mass + a_hits/2)/a_hits; // occured exception
            long new_b = (b_mass + b_hits/2)/b_hits;
```
I don't know best solution to fix it. so  I just modified it to below

 ```
           long new_a = (a_mass + a_hits/2)/std::max(int64(1), a_hits);
           long new_b = (b_mass + b_hits/2)/b_hits;
```

* **Version**: master
* **Platform**:  windows (32, 64 bit)
* **Compiler**: visual studio 2015
---
would you advise me a best solution to fix it, please?

I'm sorry that i'm bad at english.

**Comment by davisking** [comment]
auto_threshold_image was never very great.  It's depreciated and you should use parition_pixels, which is now the default method used by any routine in dlib that requires a threshold.  So for instance, if you just called threshold_image and didn't supply a threshold it would invoke partition_pixels to find one.  

So to summarize, no one should use auto_threshold_image anymore.  partition_pixels is way better and gives a much better thresholding value while being more general and robust.

**Comment by troublecoder** [comment]
@davisking thank you for your advice! I did not realize that threshold_image could be written without arguments.

**Comment by davisking** [comment]
No problem :)
