### ISSUE TITLE
How do I compile dlib into .dll file?

### ISSUE THREAD

**Issue by off99555** [davisking/dlib#1397]
From building `dlib` using `cmake`, I found a `.lib` file here:
`dlib-19.13\build\dlib\Release\dlib19.13.0_release_32bit_msvc1900.lib"`

But I want `.dll` file. So I thought that maybe I could use `dlib-19.13\build\dlib\dlib.sln` that was generated using `cmake` to generate `.dll` file. But I couldn't find an option to change the Applications Settings to be DLL inside Visual Studio 2017. As far as I know, it's only possible to create a DLL app from the start but not possible to change later.

So how do I compile all functionalities of `dlib` commands into `.dll` file? I want to use it inside `Unity3D` game engine.

If all the previous explanations are confusing for you, please ignore it and tell me how to compile `dlib` as a `.dll` library. If it's too difficult or impossible to compile all functionalities then please show me how to export just one functionality like `shape_predictor` class to predict facial landmark. It will be used with other languages like `C#` or `Python`.

Any better approach is appreciated. Thank you.

**Comment by xsacha** [comment]
`dlib-19.13/build $ cmake -DBUILD_SHARED_LIBS=ON -G"Visual Studio 15 2017 Win64" ..`

**Comment by off99555** [comment]
Thanks! This is native C library, right?
If so how do I know which functions are included in this DLL? As we need to create a function prototype file for it.

I saw that the DLL file is quite small compared to LIB file. It is 390 KB while LIB file is 13.7 MB.
Is this expected?

**Comment by xsacha** [comment]
Yes, this is the expected results. DLL will be smaller. However, static lib will likely be smaller again at link time as it strips out anything you don't use.

Just use the header files included in this project to call the functions if you are linking to the DLL. You will have different functions depending on what defines you set (i.e. Using cuda, sqlite, etc).

**Comment by Neltherion** [comment]
Sorry for reopening  this but Dlib 19.19 doesn't have any `BUILD_SHARED_LIBS` flags in Cmake. How can we build dlib as a Dynamic library and not a Static library?

Thanks

**Comment by xsacha** [comment]
That's a CMake flag. You just set it and everything should respect it.

**Comment by Neltherion** [comment]
![image](https://user-images.githubusercontent.com/22426131/99639442-d8f19180-2a5c-11eb-85a2-b237d84400bd.png)
Unfortunately, It's not present (or shown) in Cmake-GUI.

**Comment by xsacha** [comment]
Just put it in anyway. ALL CMake projects can use that flag. It's an inbuilt CMake feature.

**Comment by Neltherion** [comment]
Thanks, BUT is it possible to add this flag using the GUI? or one should just use the Command Line?
