### ISSUE TITLE
shape_predictor Segmentation fault.

### ISSUE THREAD

**Issue by MiXaiLL76** [davisking/dlib#1398]
I worked on an ordinary computer running debian 9 and everything was fine. Face recognition worked perfectly.

There was a need to compile this application under arm on Raspbian.
After a long, but successful compilation (without errors) I got the application.
At startup and debugging it was found out that the application comes up in execution before

```first_shape = _sp (r.first, r.second);```

and crashes with an error.

```
Thread 1 "face_recognizer" received signal SIGSEGV, Segmentation fault.
dlib::impl::extract_feature_pixel_values<dlib::cv_image<dlib::bgr_pixel>, float> (img_=..., rect=..., current_shape=..., reference_shape=...,
    reference_pixel_anchor_idx=std::vector of length 500, capacity 500 = {...},
    reference_pixel_deltas=std::vector of length 500, capacity 500 = {...}, feature_pixel_values=std::vector of length 500, capacity 500 = {...})
    at /usr/local/include/dlib/image_processing/shape_predictor.h:277
277                         feature_pixel_values[i] = get_pixel_intensity(img[p.y()][p.x()]);
(gdb) q
```

* **Version**: 19.13
* **Where did you get dlib**: git clone github.com/davisking/dlib
* **Platform**: 
```
lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

* **Compiler**: cmake + gcc

**Comment by xsacha** [comment]
Are you using OpenBLAS with this. If so, which version of OpenBLAS?
I have had issues with recent versions of OpenBLAS compiled using CMake + shape_predictor.

**Comment by MiXaiLL76** [comment]
The error still remains.

**Comment by davisking** [comment]
You need to follow the issue submission instructions if you want more help.

**Comment by MiXaiLL76** [comment]
move to https://github.com/davisking/dlib/issues/1436
