### ISSUE TITLE
best way to  finding eye state 

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1399]
Hi Davis,

what is the best and fastest way to find eye state (open or close only 2 state) with the help of dlib power ? I have eyes images in both states and try to train , before that according to your experince what could be the direction in dlib environment?

**Comment by davisking** [comment]
Just look at the face landmarks and check if the ones around the eye are close together or far apart.  You shouldn't need to train anything.  Just a simple if statement is enough.  Something like this: https://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/
