### ISSUE TITLE
clang compile warning dlib 19.13

### ISSUE THREAD

**Issue by YuriiOlenych** [davisking/dlib#1402]
Compile warning using Xcode Version 9.4.1 (9F2000); clang Apple LLVM version 9.1.0 (clang-902.0.39.2) and -std=gnu++1y:

- dlib/cuda/tensor_tools.cpp:121: warning: comparison of integers of different signs: 'long long' and 'size_t' (aka 'unsigned long') [-Wsign-compare]:
`DLIB_CASSERT(m.num_samples() == v.size());`
- dlib/cuda/tensor_tools.cpp:143: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'long long' [-Wsign-compare]:
`DLIB_CASSERT(v1.size() == m1.num_samples());`
- dlib/image_transforms/interpolation.h:2165: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`const std::array<dpoint,4> corners = {bounding_box.tl_corner(), bounding_box.tr_corner(), bounding_box.bl_corner(), bounding_box.br_corner()};`
- dlib/geometry/line.h:225: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`return {v03, v31, v12, v20};`
- dlib/geometry/line.h:224: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`if (is_convex_quadrilateral({v03, v31, v12, v20}))`
- dlib/geometry/line.h:223: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`return {v03, v32, v21, v10};`
- dlib/geometry/line.h:222: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`if (is_convex_quadrilateral({v03, v32, v21, v10}))`
- dlib/geometry/line.h:220: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`return {v02, v21, v13, v30};`
- dlib/geometry/line.h:219: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`if (is_convex_quadrilateral({v02, v21, v13, v30}))`
- dlib/geometry/line.h:218: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`return {v02, v23, v31, v10};`
- dlib/geometry/line.h:217: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`if (is_convex_quadrilateral({v02, v23, v31, v10}))`
- dlib/geometry/line.h:215: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`return {v01, v13, v32, v20};`
- dlib/geometry/line.h:214: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`if (is_convex_quadrilateral({v01, v13, v32, v20}))`
- dlib/geometry/line.h:213: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`return {v01, v12, v23, v30};`
- dlib/geometry/line.h:212: warning: suggest braces around initialization of subobject [-Wmissing-braces]:
`if (is_convex_quadrilateral({v01, v12, v23, v30}))`
* **Version**: 19.13
* **Where did you get dlib**: https://github.com/davisking/dlib/archive/v19.13.tar.gz
* **Platform**: macOS High Sierra 10.13.4 (17E199)
* **Compiler**: Apple LLVM version 9.1.0 (clang-902.0.39.2)

**Comment by davisking** [comment]
Can you submit a PR that adds the appropriate casts?

**Comment by YuriiOlenych** [comment]
Yep, I'll do it later.
