### ISSUE TITLE
dnn_introduction_ex stoped with error CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by leimingdev** [davisking/dlib#1411]
I compile dlib-19.14 succeed on ubuntu16.04 with cuda9.0, but when i run the demo dnn_introduction_ex, it stoped, get the following error:
Epoch: 1     learning rate: 0.01  average loss: 0.298612     steps without apparent progress: 8
Error while calling cudnnConvolutionBackwardData(context(), &alpha, (const cudnnFilterDescriptor_t)filter_handle, filters.device(), descriptor(gradient_input), gradient_input.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionBwdDataAlgo_t)backward_data_algo, backward_data_workspace, backward_data_workspace_size_in_bytes, &beta, descriptor(data_gradient), data_gradient.device()) in file /src/dlib-19.14/dlib/cuda/cudnn_dlibapi.cpp:1040. code: 3, reason: CUDNN_STATUS_BAD_PARAM

**Comment by davisking** [comment]
Yeah, I broke it in the last release :( 

Grab the latest from github, it's fixed there.  I'm going to push out dlib 19.15 in a moment because of this.
