### ISSUE TITLE
Ignore Boxes Multiclass object detection

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#1412]
Hi,
regarding Multiclass object detection. (convolutional Network)
musst boxes marked as ignore also beeing labeled?.

In other words is this correct:
  ` <box top='226' left='215' width='118' height='53' ignore='1'/>`
or this 
```
   <box top='226' left='215' width='118' height='53' ignore='1'>
   <label>front</label>
   </box>
```

or both?

Thanks

**Comment by davisking** [comment]
The label is not considered on ignore boxes.  See http://dlib.net/dlib/dnn/loss_abstract.h.html#mmod_options where this behavior is documented.
