### ISSUE TITLE
Conflicting types using libgsl and dlib with blas

### ISSUE THREAD

**Issue by ChrizzyM87** [davisking/dlib#1416]
## Expected Behavior
Including dlib/matrix.h (v19.15) and gsl/gsl_cblas.h (v2.1 libgsl-dev from Ubuntu Xenial Repo) in same projekt should work.

## Current Behavior
I get compilation errors with clang in matrix_trsm.h:
```
/usr/include/dlib/matrix/matrix_trsm.h:20: Fehler: conflicting types for 'cblas_strsm'
            void cblas_strsm(const CBLAS_ORDER Order, const CBLAS_SIDE Side,
                 ^
/usr/include/dlib/matrix/matrix_trsm.h:26: Fehler: conflicting types for 'cblas_dtrsm'
            void cblas_dtrsm(const CBLAS_ORDER Order, const CBLAS_SIDE Side,
                 ^
```
and a lot in matrix_blas_bindings.h e.G.:
```
/usr/include/dlib/matrix/matrix_blas_bindings.h:74: Fehler: conflicting types for 'cblas_sgemm'
            void cblas_sgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA,
                 ^
```

## Steps to Reproduce
Include in same project:
```
#include <gsl/gsl_cblas.h>
#include <dlib/matrix.h>
```

## Message:
I got a project where I use the libeemd library, which needs the libgsl, and the OpenFace library, which needs dlib. I cannot change their includes, but I can edit the dlib library. I tried the following:
- I added an ```#ifndef __GSL_CBLAS_H__ ```check in matrix_blas_bindings.h and matrix_trsm.h to prevent redeclarations. This does not work, because the function arguments are different, and dlib calls do not match with the declarations in gsl. e.G.:
Declaration in matrix_blas_bindings.h (dlib):
```
void cblas_sgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA,
                             const CBLAS_TRANSPOSE TransB, const CBLAS_INT_TYPE M, const CBLAS_INT_TYPE N,
                             const CBLAS_INT_TYPE K, const float alpha, const float *A,
                             const CBLAS_INT_TYPE lda, const float *B, const CBLAS_INT_TYPE ldb,
                             const float beta, float *C, const CBLAS_INT_TYPE ldc);
```
Declaration in gsl_cblas.h:
```
void cblas_sgemm(const enum CBLAS_ORDER Order, const enum CBLAS_TRANSPOSE TransA,
                 const enum CBLAS_TRANSPOSE TransB, const int M, const int N,
                 const int K, const float alpha, const float *A,
                 const int lda, const float *B, const int ldb,
                 const float beta, float *C, const int ldc);
```

- I tried to compile dlib without BLAS using cmake param ```DLIB_USE_BLAS_STR=OFF```, but this did not change anything. Why?
- I set function declarations in matrix_blas_bindings.h and matrix_trsm.h to static. That worked for me, when I did it after compiling dlib, but if I change this in my dlib fork, what I have to do for a final solution, I cannot compile dlib anymore. So that's not a practical solution as well.

Now I don't know what to do and I'm really hoping, that anybody got a good hint for my how to resolve that problem. Thanks a lot in advance!

* **Version**: 19.15
* **Where did you get dlib**: clone of official repo
* **Platform**: Ubuntu 16.04
* **Compiler**: clang 3.8.0

**Comment by davisking** [comment]
I just tried this in ubuntu 16.04 and everything compiled without any
errors.  There must be some other things going on here.

**Comment by ChrizzyM87** [comment]
Okay, thanks, that's really confusing! I will try to reproduce it in a naked ubuntu 16.04 docker container and write tomorrow again!

**Comment by ChrizzyM87** [comment]
Okay, it's working in that configuration I described above.
I wasn't aware that I'm using clang in my QT project, somehow this changed.
So the problem is with clang, it's no problem at all with gcc.
I will edit my post!

**Comment by davisking** [comment]
I pushed a change to github that should fix it.  So give the latest a try.

**Comment by ChrizzyM87** [comment]
It's working! Really nice! Thank you!!

**Comment by davisking** [comment]
No problem. Thanks for reporting the issue :)

**Comment by coralkashri** [comment]
For the next time that someone will ask chatGPT this question, here is another way to solve it:
Include gsl.h before any including of dlib. Flib will recognize the cblas implementation of gsl, and won't implement it again.

Another way if that's not possible, is to look for the ifdef in dlib cblas file, which comes before the 'extern C' section there, and undef it before the dlib file include, or as part of the cmake/build commands.
