### ISSUE TITLE
loss_mmod detector with single input_rgb_image prediction

### ISSUE THREAD

**Issue by headupinclouds** [davisking/dlib#1417]
I'd like to run inference with a pre-trained `loss_mmod` detector on single images -- basically omitting the tiled pyramid creation, sliding window evaluation, and non-max suppression.  Any advice on how to do this for a pre-trained pyramid/multi-scale network would be much appreciated.

Using the network from your [dnn_mmod_find_cars_ex](https://github.com/davisking/dlib/blob/4c816be0cdcb747b2d325d8f198d1b8cd1e78234/examples/dnn_mmod_find_cars_ex.cpp#L42) tutorial as an example:

```
template <int N=6>
using net_type6 = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<N>>>>>>>>;
...
net_type<6> net6;
deserialize(network_filename) >> net6;
```

Is there a way to achieve something like the following conversion:

```
net_type<1> net1;
net1.subnet() = net6.subnet(); // not quite right?
```

or even something like `net6.evaluate_chip(chip)`?

Thanks

**Comment by davisking** [comment]
I'm not really sure what you are asking to do.  That example you linked to
shows how to get all the intermediate outputs from the model.  As for not
doing the pyramid, there is no option for that. But you could just edit the
input layer code to tell it to not do it.

**Comment by davisking** [comment]
Yes, that's what I would do.  You have to take care to give a big enough
crop though.  80x80 may well be too small and border effects will screw up
the result.  In any case, experiment to see what works.

**Comment by headupinclouds** [comment]
Thanks for your help.
