### ISSUE TITLE
the speed of detecting car is very slow. why?

### ISSUE THREAD

**Issue by zhaowwenzhong** [davisking/dlib#1418]
We ran your car detection program（dnn_mmod_find_cars_ex.cpp and dnn_mmod_train_find_cars_ex2.cpp）on GPU(GTX 1080) platform, and used 
macro DLIB_USE_CUDA as well. CUDA version is 9.0, the operating system is win7 and the size of the image selected is 720×912. We would like
to know why the following problems occurred:
1, The detection speed was very slow, and the average time used was 850 milliseconds.
2, Only a part of the vehicles were identified.
3, How could we modify the net parameter settings to get a fast detection speed?

The code is shown as below:
#include <iostream>
#include "../dlib/dnn.h"
#include "../dlib/image_io.h"
#include "../dlib/gui_widgets.h"
#include "../dlib/image_processing.h"

using namespace std;
using namespace dlib;

#pragma comment(lib, "cudnn.lib")
#pragma comment(lib, "dlib-md-mkl-gpu-x64.lib")
#pragma comment(lib, "cudart.lib")
#pragma comment(lib, "cusolver.lib")
#pragma comment(lib, "cublas.lib")
#pragma comment(lib, "curand.lib")

// The front and rear view vehicle detector network
template <long num_filters, typename SUBNET> using con5d = con<num_filters, 5, 5, 2, 2, SUBNET>;
template <long num_filters, typename SUBNET> using con5 = con<num_filters, 5, 5, 1, 1, SUBNET>;
template <typename SUBNET> using downsampler = relu<affine<con5d<32, relu<affine<con5d<32, relu<affine<con5d<16, SUBNET>>>>>>>>>;
template <typename SUBNET> using rcon5 = relu<affine<con5<55, SUBNET>>>;
using net_type = loss_mmod<con<1, 9, 9, 1, 1, rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>;

// ----------------------------------------------------------------------------------------

int main() try
{
	net_type net;
	shape_predictor sp;
	deserialize("mmod_front_and_rear_end_vehicle_detector.dat") >> net >> sp;
	matrix<rgb_pixel> img;
	load_image(img, "./img1.jpg");

	image_window win;
	win.set_image(img);
	DWORD dstart = GetTickCount();
	// Run the detector on the image and show us the output.
	for (auto&& d : net(img))
	{
		// We use a shape_predictor to refine the exact shape and location of the detection
		// box.  This shape_predictor is trained to simply output the 4 corner points of
		// the box.  So all we do is make a rectangle that tightly contains those 4 points
		// and that rectangle is our refined detection position.
		auto fd = sp(img, d);
		rectangle rect;
		for (unsigned long j = 0; j < fd.num_parts(); ++j)
			rect += fd.part(j);

		if (d.label == "rear")
			win.add_overlay(rect, rgb_pixel(255, 0, 0), d.label);
		else
			win.add_overlay(rect, rgb_pixel(255, 255, 0), d.label);
	}
	save_jpeg(img, "E:\\Res.jpg");
	cout << "Tick Times " << GetTickCount() - dstart << endl;
	cout << "Hit enter to end program" << endl;
	cin.get();
}
catch (image_load_error& e)
{
	cout << e.what() << endl;
	cout << "The test image is located in the examples folder.  So you should run this program from a sub folder so that the relative path is correct." << endl;
}
catch (serialization_error& e)
{
	cout << e.what() << endl;
	cout << "The correct model file can be obtained from: http://dlib.net/files/mmod_front_and_rear_end_vehicle_detector.dat.bz2" << endl;
}
catch (std::exception& e)
{
	cout << e.what() << endl;
}

**Comment by davisking** [comment]
You should build the examples with CMake, following the instructions.

**Comment by w136111526** [comment]
I was running this examples with Visual Studio 2015 On windows platform，I'm sure using DLIB_USE_CUDA but it's is still slow，which instructions can I learn from？ Can you give me any more suggestion?

**Comment by davisking** [comment]
This page tells you exactly what to type: http://dlib.net/compile.html
