### ISSUE TITLE
Training to create a new predictor

### ISSUE THREAD

**Issue by ProudCule** [davisking/dlib#1419]
I don't know if it is the right place to post, apologies if it isn't

I am trying to train to create a new predictor just to output landmarks of eyes. I have followed everything you have written as how to train . I get an error as 

bhargav$ python3 train.py all_train
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    dlib.train_shape_predictor(training_xml_path, "predictor.dat", options)
RuntimeError: There is a fatal error on line 22 so parsing will now halt 

<img width="446" alt="screen shot 2018-07-20 at 10 54 58 am" src="https://user-images.githubusercontent.com/19468935/42984666-64066040-8c0b-11e8-85f8-1f6b67b45e09.png">
this is the xml file i am using to train

please let me know where it went wrong or what i should do to solve this?

**Comment by davisking** [comment]
Start out by looking at line 22, like the error says.  Also, no one can tell what that line is because you posted an image that's cropped.  Moreover, don't post images of text.

**Comment by ProudCule** [comment]
Sorry  for the mistake sir.
I am attaching the correct picture now .
<img width="815" alt="screen shot 2018-07-21 at 4 46 53 pm" src="https://user-images.githubusercontent.com/19468935/43035046-bdce457a-8d05-11e8-98d5-c7c4f6c67ac9.png">
The error is because I am only giving the landmarks of 12 points corresponding to just the eyes in the training xml file .
so my question is do I need to give all the 68 landmarks in the training xml file?
If yes, how do I do create a model that will just output the 12 landmarks of both the eyes and not the whole face?
Thanks in advance sir!

**Comment by davisking** [comment]
Don't post images of text.  

Anyway, the error has nothing to do with how many landmarks there are.  It's telling you your XML is malformed.  You have part tags that aren't closed.

**Comment by ProudCule** [comment]
sincere apologies for posting image.
 It was a silly mistake , Thank you so much!

**Comment by essalahsouad** [comment]
@ProudCule 
if you don't mind , I want to ask you about the training you did?is it worked fine??
because now I'm dealing with the same issue,after training i got bad prediction
XML fine looks like
![Capture du 2019-09-22 02-39-19](https://user-images.githubusercontent.com/34586193/65394517-11c5a600-dd87-11e9-922e-e62c6c646428.png)
left:prediction
right:groud truth
![Capture du 2019-09-22 02-44-02](https://user-images.githubusercontent.com/34586193/65394526-25710c80-dd87-11e9-9c69-8a5824a54ff9.png)
