### ISSUE TITLE
Trivial: regarding CMAKE_CURRENT_LIST_DIR

### ISSUE THREAD

**Issue by daisukelab** [davisking/dlib#142]
Hi, just wondering why cmake has this:

    < string(REGEX REPLACE "cmake$" "" dlib_path ${CMAKE_CURRENT_LIST_FILE})

Just could simply be replaced by:

    > set(dlib_path ${CMAKE_CURRENT_LIST_DIR})

I'm sorry but it's too trivial to make a pull request, just sharing what I noticed.
Anyway thanks for lib, it's super great!

**Comment by davisking** [comment]
I'm glad you like dlib :)

It's because CMAKE_CURRENT_LIST_FILE didn't exist in older versions of
cmake.  It's been so long no one uses those versions of cmake anymore so it
would be safe to update the cmake scripts though.  I'm going to organize
the cmake files a little today and I"ll update this as well.

**Comment by daisukelab** [comment]
Thanks for sharing history.
Though it's your decision but let me express that I don't want wasting your time, please feel free to leave as it is, as long as you'd feel so.
This is last comment to bother you before closing this.
I will close after some time waiting for something to happen; you might want to leave change info.
Thanks again!

**Comment by davisking** [comment]
No worries.  I really was going to clean up the cmake files.  I'm
prepairing the next dlib release right now.  Once that's finished I'll
clean up some things about the current cmake files, including this.

**Comment by daisukelab** [comment]
OK I'm very much looking forward to the new release. Thank you for your effort!

**Comment by davisking** [comment]
New release is out.  I also just updated all the cmake files.

Cheers,
Davis

**Comment by daisukelab** [comment]
Thanks for sharing new version! :)
