### ISSUE TITLE
DLIB Face Detector missing Chin | Question

### ISSUE THREAD

**Issue by dexception** [davisking/dlib#1420]
Hi,

I have been comparing face detectors from different models and i have a question related to your observations. Dlib face detector does not include "Chin" and the rectangle is drawn between lower lip and chin. Can you please tell me the reason why you decided to not include the chin in face detection ?

**Comment by davisking** [comment]
If you want to include the chin just resize the box.

**Comment by dexception** [comment]
@davisking 
Question is why dlib face detector ends between lib and chin ? 

Before closing the issue at least read the question.

**Comment by davisking** [comment]
The output box can be any shape. It is arbitrary.
