### ISSUE TITLE
dlib and tbb composability.

### ISSUE THREAD

**Issue by alexey-katranov** [davisking/dlib#1422]
Could you help us to investigate an issue with thread affinity when [tbb](https://github.com/01org/tbb) is used with `dlib` in one application? 

We know about at least two independent reports that `tbb` observes only 1 thread on the system when used with `dlib`:

- [tbb determines incorrect concurrency](https://stackoverflow.com/questions/51444294/tbb-determines-incorrect-concurrency)

- [task_scheduler_init::default_num_threads() returns 1](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/777514)

From our perspective, it is possible if someone binds the current thread to a one core only. However, it looks strange why it might be required by `dlib`. Does `dlib` perform any manipulations with affinity masks? Can a third-party used by `dlib` change the mask?

Thank you in advance.

**Comment by davisking** [comment]
I don't see what dlib could possibly have to do with this. There is nothing in dlib that binds threads to any core or meddles with your thread affinity.
