### ISSUE TITLE
Creating predcitor just for eyes

### ISSUE THREAD

**Issue by ProudCule** [davisking/dlib#1423]
The current landmark generator outputs 68 landmarks and is 100mb in size. I don't have use for many of these right now and am interested in only in a subset of those.
I used this [ibug dataset](http://dlib.net/files/data/ibug_300W_large_face_landmark_dataset.tar.gz).
i just edited the xml files present in it and trained the model. And my accuracy is too low.what should I do here?

Training with cascade depth: 10
Training with tree depth: 2
Training with 500 trees per cascade level.
Training with nu: 0.05
Training with random seed: 
Training with oversampling amount: 3
Training with feature pool size: 400
Training with feature pool region padding: 0
Training with 0 threads.
Training with lambda_param: 0.1
Training with 20 split tests.
Fitting trees...
Training complete                             
Training complete, saved predictor to file predictor.dat

Training accuracy: 11.001496554096557
Testing accuracy: 11.834624782075196

**Comment by davisking** [comment]
Use different training parameters.  Also, read the documentation. They are all explained in detail there and in the original reference paper discussing the algorithm.
