### ISSUE TITLE
Use png images to train CNN

### ISSUE THREAD

**Issue by don-prog** [davisking/dlib#1425]
Due to the some reason I need to train dlib CNN using png photos with transparency - in the center of the photo will be the face(I cropped it using dlib's shape predictor) and all background will be transparent. Is it ok? What additional changes should I make to the  dnn_metric_learning_on_images_ex.cpp(including disturb_colors() and jitter_image()) or to the loss layer? What else do I need to know in order to work correctly in this case?
Regards.

**Comment by davisking** [comment]
This doesn't strike me as a very good idea.  But if you wanted to do it I
would convert the images to 3 channel RGB by setting the transparent part
to black.
