### ISSUE TITLE
landmark jitter problem

### ISSUE THREAD

**Issue by ailias** [davisking/dlib#1426]
Can you solve the landmarks jittering problem ? Or what else I can do for dealing with it. Thanks.

**Comment by davisking** [comment]
I would use a kalman filter to smooth it over time.  Something like this is
good: http://dlib.net/algorithms.html#momentum_filter

**Comment by RubenBenBen** [comment]
@davisking when should momentum_filer be used? I detect landmarks on live camera by sending every frame img dlib::full_object_detection shape = sp(img, oneFaceRect), and it is jittering if I smile too sharply, or when my eyes are **almost** closed, but I don't move at all.

**Comment by RubenBenBen** [comment]
@davisking I mean when should I call the function momentum_filter() ? I've tried after and before dlib::full_object_detection shape = sp(img, oneFaceRect), but it seems to give no effect.

**Comment by davisking** [comment]
momentum_filter is a class, not a function, so you don't just call it. You need to read the documentation.  I'm not going to paste the documentation into the github issue.  If you follow the link I posted earlier you can read all about it.

**Comment by santo4ul** [comment]
@davisking Do we have any example to use the mememtum_filter class?

**Comment by davisking** [comment]
You can find out the answer to this by looking at the documentation or going into the example folder and typing `grep momentum_filter *.cpp`.

**Comment by santo4ul** [comment]
I tried this before writing here. I couldn't find anything related to "momentum_filter" inside dlib/examples folder. I'm using v19.9 release. Am I missing something? 

I'm currently going through the documentation http://dlib.net/algorithms.html#momentum_filter but had no luck with any examples so far. 

Thank you.

**Comment by santo4ul** [comment]
I also tried in v19.17 release, nothing related to "momentum_filter" inside dlib/examples folder.

**Comment by davisking** [comment]
Right, there aren’t any :)

**Comment by santo4ul** [comment]
@davisking I referred to class [rect_filter](http://dlib.net/dlib/filtering/kalman_filter.h.html) which uses momentum filter. Looks straight forward. Thanks for your inputs. I'll also submit an example of momentum_filter if possible. 

Thank you.
