### ISSUE TITLE
compilation problem with hog face detector

### ISSUE THREAD

**Issue by williamCorrea85** [davisking/dlib#1429]
## Expected Behavior
Faces to be detected

## Current Behavior
The line that generates an error is the number 601 of the file "scan_fhog_pyramid.h" : 
typedef typename image_traits<image_type>:: pixel_type pixel_type;

The errors gegerated are :
1. use of undefined type 'dlib::image_traits<image_type>'
2. syntax error: missing ';' before identifier 'pixel_type'
3. missing type specifier - int assumed. Note: C++ does not support default-int

## Steps to Reproduce

I'm following the following example : http://dlib.net/face_detection_ex.cpp.html

* **Version**:  19.13
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 32-bit (debug)
* **Compiler**: c++ visual studio 2015

**Comment by davisking** [comment]
That's not enough information to reproduce the error.  Include exact steps someone can take to reproduce the error if you want help.
