### ISSUE TITLE
the example of detecting car is very slow under cuda. how can I do?

### ISSUE THREAD

**Issue by w136111526** [davisking/dlib#1431]
I was runnin the dnn_mmod_train_find_cars_ex2.cpp examples with Visual Studio 2015 On windows platform。I'm sure using DLIB_USE_CUDA but it's is still slow - the average time used was 960 milliseconds one frame, which instructions can I learn from？ Can you give me any more suggestion?

**Comment by davisking** [comment]
Don't post the same question to multiple issues.
