### ISSUE TITLE
Python Q: how to explicitly delete cnn_face_detection_model_v1 object

### ISSUE THREAD

**Issue by mingwugmail** [davisking/dlib#1433]
In Python:

cnn_face_detector = dlib.cnn_face_detection_model_v1(model_fn)

how to explicitly delete this object and release its resource on GPU?

And another question is:
https://github.com/davisking/dlib/blob/a18e72e51685e0306f889642da15ff7994362dc3/python_examples/cnn_face_detector.py#L56

 dets = cnn_face_detector(img, 1)

is called in a loop, again any resource issue? e.g. no memory leaks?

Thanks.

**Comment by davisking** [comment]
Resources are freed just like in any other objects in python, when they are
destroyed.  There are no memory leaks.

**Comment by mingwugmail** [comment]
I tried the following small program, the GPU seems not released:

the function rel_gpu() is called twice, to check even after function returned, the GPU resource is still taken (search the two different "'before new") below.

So still my original question: how I can explicitly delete cnn_face_detection_model_v1 object?

======================== release_gpu.py
#!/usr/bin/env python

import dlib
import os

def rel_gpu():
  try:
    print('before new')
    os.system('nvidia-smi')
    dlib.hit_enter_to_continue()

    cnn_face_detector = dlib.cnn_face_detection_model_v1('mmod_human_face_detector.dat')
    print('after new')
    os.system('nvidia-smi')
    dlib.hit_enter_to_continue()

    del cnn_face_detector
    print('after del')
    os.system('nvidia-smi')
    dlib.hit_enter_to_continue()

    # just want to see: local variable 'cnn_face_detector' referenced before assignment
    # means del is indeed called
    print(cnn_face_detector)
  except NameError as ex:
    print(ex)


rel_gpu()
rel_gpu()
===================

$ ./release_gpu.py 
before new
Sat Jul 28 05:28:45 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0  On |                  N/A |
| 22%   54C    P8    17W / 250W |     64MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   38C    P8    13W / 250W |      1MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2484      G   /usr/lib/xorg/Xorg                            62MiB |
+-----------------------------------------------------------------------------+
Hit enter to continue
after new
Sat Jul 28 05:28:48 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0  On |                  N/A |
| 22%   54C    P2    43W / 250W |    187MiB / 12212MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   38C    P8    14W / 250W |     12MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2484      G   /usr/lib/xorg/Xorg                            62MiB |
|    0     22352      C   python                                       112MiB |
+-----------------------------------------------------------------------------+
Hit enter to continue
after del
Sat Jul 28 05:29:00 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0  On |                  N/A |
| 22%   58C    P2    76W / 250W |    183MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   38C    P8    14W / 250W |     12MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2484      G   /usr/lib/xorg/Xorg                            62MiB |
|    0     22352      C   python                                       108MiB |
+-----------------------------------------------------------------------------+
Hit enter to continue
local variable 'cnn_face_detector' referenced before assignment
before new
Sat Jul 28 05:29:01 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0  On |                  N/A |
| 22%   58C    P2    76W / 250W |    183MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   38C    P8    14W / 250W |     12MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2484      G   /usr/lib/xorg/Xorg                            62MiB |
|    0     22352      C   python                                       108MiB |
+-----------------------------------------------------------------------------+
Hit enter to continue
after new
Sat Jul 28 05:29:10 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0  On |                  N/A |
| 22%   57C    P2    39W / 250W |    187MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   38C    P8    13W / 250W |     12MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2484      G   /usr/lib/xorg/Xorg                            62MiB |
|    0     22352      C   python                                       112MiB |
+-----------------------------------------------------------------------------+
Hit enter to continue
after del
Sat Jul 28 05:29:11 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0  On |                  N/A |
| 22%   58C    P2    75W / 250W |    183MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 22%   38C    P8    13W / 250W |     12MiB / 12212MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2484      G   /usr/lib/xorg/Xorg                            62MiB |
|    0     22352      C   python                                       108MiB |
+-----------------------------------------------------------------------------+
Hit enter to continue
local variable 'cnn_face_detector' referenced before assignment

**Comment by davisking** [comment]
There isn't any memory leak. This is how CUDA works and you just don't understand what you are looking at.  For further reading: https://devtalk.nvidia.com/default/topic/892873/how-to-effectively-free-large-memory-allocation-/ https://stackoverflow.com/questions/10394755/why-doesnt-cudafree-seem-to-free-memory
