### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [davisking/dlib#1434]
Would you like to [replace any double quotes](https://github.com/davisking/dlib/blob/36d49e6781e25361e97589ab412af8edf0926241/dlib/statistics.h#L6 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by davisking** [comment]
No.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by davisking** [comment]
Yes, I know how it works and it currently does exactly what I want it to.  So I'm not changing it unless you find some use case where something bad happens.
