### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [davisking/dlib#1435]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [letter](https://github.com/davisking/dlib/blob/32a96ddb7567d59f5ae646f5d5de5da19b82cbea/dlib/gui_widgets/fonts.h#L69 "Destructor for letter")
- [sliding_buffer_kernel_1](https://github.com/davisking/dlib/blob/cf5e25a95f27833dff121e41bba1783190dc7f64/dlib/sliding_buffer/sliding_buffer_kernel_1.h#L55 "Destructor for sliding_buffer_kernel_1")
- [static_map_kernel_1::deserialize](https://github.com/davisking/dlib/blob/cf5e25a95f27833dff121e41bba1783190dc7f64/dlib/static_map/static_map_kernel_1.h#L92 "static_map_kernel_1::deserialize function")

**Comment by davisking** [comment]
Sure. Feel free to submit a PR :)
