### ISSUE TITLE
dlib arm issue

### ISSUE THREAD

**Issue by MiXaiLL76** [davisking/dlib#1436]
## Expected Behavior
The program will work as on the x86 system.
There will be no segmentation error.

## Current Behavior
The program after compilation ends with the error "SIGSEGV, Segmentation fault."
When debugging, the place where the program was dropped is calculated.

## Steps to Reproduce

```
dlib::shape_predictor _sp;
auto path = "./models/shape_predictor_68_face_landmarks.dat";
dlib::deserialize(path) >> _sp;
```

```
engine::face_info engine::get_face(const record_type &r) const
{
    cv::VideoCapture cap;
    cv::Mat src;

    std::string lastfile = "";
    bool exists = false;
    for (auto v : r.second)
    {
        cap.open(std::get<1>(v));
        exists = exists | cap.isOpened();
        lastfile = std::get<1>(v);
    }
    if (!exists)
    {
        throw std::string("get_face -> Files not ready -> " + lastfile);
    }

    face_info first_face;
    dlib::full_object_detection first_shape;
    int ignore_count = 0;
    for (auto v : r.second)
    {
        cap.open(std::get<1>(v));
        for (;;)
        {
            cap >> src;
            if (src.empty())
            {
                break;
            }
            if (ignore_count != 0)
            {
                --ignore_count;
                continue;
            }
            auto r = get_face(src);
            if (first_face.second.width() == 0)
            {

                first_face = r;
                io::mout << "r1" << r.first.size() << io::endl;
                io::mout << "r2" << r.second.width() << io::endl;

                io::mout << "first_face = r;" << io::endl;
                //first_shape = predictor_(r.first, r.second);
                first_shape = _sp(r.first, r.second);
                ignore_count = 2;
                continue;
            }
            else if (r.second.width() != 0)
            {
                //auto shape = predictor_(r.first, r.second);
                auto shape = _sp(r.first, r.second);
                float d = distance(shape, first_shape);
                io::mout << "OVERALL DISTANCE: " << d << io::endl;
                if (d < 5.0)
                {
                    first_shape = shape;
                    continue;
                }
                throw std::string("oK " + lastfile);
                return r;
            }
        }
    }
    return {{}, {}};
}
```
### Error
```
Detecting face: 1003 ms
r1307200
r2150
first_face = r;
Segmentation fault

Thread 1 "face_recognizer" received signal SIGSEGV, Segmentation fault.
dlib::impl::extract_feature_pixel_values<dlib::cv_image<dlib::bgr_pixel>, float> (img_=..., rect=..., current_shape=..., reference_shape=...,
    reference_pixel_anchor_idx=std::vector of length 500, capacity 500 = {...}, reference_pixel_deltas=std::vector of length 500, capacity 500 = {...},
    feature_pixel_values=std::vector of length 500, capacity 500 = {...}) at /home/stepanoff/raspberrypi/rootfs/usr/local/include/dlib/image_processing/shape_predictor.h:277
277     /home/stepanoff/raspberrypi/rootfs/usr/local/include/dlib/image_processing/shape_predictor.h: No such file or directory.
```

* **Version**: 19.15
* **Where did you get dlib**: http://dlib.net
* **Platform**: ARMv7 rpi3b
>>No LSB modules are available.
>Distributor ID: Raspbian
>Description:    Raspbian GNU/Linux 9.4 (stretch)
>Release:        9.4
>Codename:       stretch

* **Compiler**: CMake + Ninja 

```
g++ --version
g++ (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by davisking** [comment]
Please post a minimal program that someone can run and reproduce the
error.  What you just posted is just a fragment that no one else can run.

**Comment by MiXaiLL76** [comment]
Please write your email and I will give the program archive

**Comment by davisking** [comment]
No. I'm not going to debug your whole program.  It's very likely that the bug has nothing to do with dlib. Part of the point of you creating a minimal example that illustrates the bug is to work through showing that the bug is related to dlib.  If you are able to make something small that you can post here that uses dlib and illustrates there is a dlib bug then you can get help.  

To say that another way, the dlib forums are not a code debugging service.

**Comment by MiXaiLL76** [comment]
I wrote a simple example of what I'm trying to compile.
The error has remained and I think it is called from "dlib/opencv/cv_image.h"

At compilation on x86 / 64 the program works perfectly.
When compiled on ARM falls.

[https://yadi.sk/d/2HwsBtUY3ZpYJ2](simple example)

**Comment by davisking** [comment]
That's not a minimal example.  You should be able to get this down to like
10 lines of code.  That's a minimal example.  The thing you posted is doing
all kinds of stuff unrelated to this issue and, more importantly, some
other part of this program is probably where the bug really is.

**Comment by MiXaiLL76** [comment]
Through multiple tests, I found out that this error occurs on arm32 (armhf) bit architecture.
And on arm64 (aarch64) does not arise.
This is due to the fact that for armhf and for aarch64 the type long has different length values.


For aarch64:
sizeof (long) = 8
sizeof (long long) = 8

For armhf
sizeof (long) = 4
sizeof (long long) = 8

**Comment by davisking** [comment]
So you figured out the error then?  Sounds like we can close this issue.

**Comment by MiXaiLL76** [comment]
This is a very strange "mistake"

In fact, I would like this to work on armhf (32) archettektura.
