### ISSUE TITLE
AVX Instruction set

### ISSUE THREAD

**Issue by Drakesinger** [davisking/dlib#144]
Greetings,
During usage of your library for object detection I have wrongly compiled the example `fhog_object_detector_ex.cpp` with `DLIB_USE_SSE2`.

With 4 input images of 1920x1200 and detection windows of 210 x 190 (updated to more or less fit the objects in the images) the training took about **4 days**.

After reading and re-making the compilation using CMAKE I checked the box to use AVX and checked the options it sets up (also the hidden ones like static linking with `libpng` for example).

Now, I have a project for which I cannot use CMAKE to build my Visual Studio solution (simply because I am not competent enough with CMAKE) so I set up the `DLIB_USE_AVX` preprocessor definition in preprocessor options in Visual Studio and set the correct `/arch:AVX` option for compilation.

During execution, the debugger shows that it is running SSE2 SIMD4F instructions.

For example:
```cpp
    inline simd4f_bool operator< (const simd4f& lhs, const simd4f& rhs) 
    { 
    #ifdef DLIB_HAVE_SSE2
        return _mm_cmplt_ps(lhs, rhs); 
    #else
        return simd4f_bool(lhs[0]<rhs[0],
                           lhs[1]<rhs[1],
                           lhs[2]<rhs[2],
                           lhs[3]<rhs[3]);
    #endif
    }
```

It will run `_mm_cmplt_ps(lhs, rhs)`.

This surprised me and I checked your `simd_check.h` to see which headers and macros you define.
I was surprised to see that if __AVX__ is defined (which it is when setting up /arch:AVX), you define them all and add all headers.

Is this normal?
[After reading about it a bit I saw that the transition between the two sets of instructions is quite costly (70 cycles).](http://stackoverflow.com/a/7841251)

Am asking this because I have re-started a training, but this time with ~150 images for training, and am currently concerned that it will take "ages".

Any input about this?
If you need more info, just tell me.

---

PS. <br>The faces example also too much longer than 10 seconds on my machine (2 cores, 2.6 GHZ i7-6600U), even with AVX turned on and only the CMAKE generated solution used.

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whyisdlibslow

**Comment by Drakesinger** [comment]
Thank you.
Done that.

Was using dlib as a static library which was compiled in release though.

Added the following lines in the faces example:
```cpp
#ifdef __AVX__
		cout << "AVX on" << endl;
#ifdef DLIB_HAVE_SSE2
		cout << "DLIB_HAVE_SSE2 on" << endl;
#endif
#ifdef DLIB_HAVE_SSE3
		cout << "DLIB_HAVE_SSE3 on" << endl;
#endif
#ifdef DLIB_HAVE_SSE41
		cout << "DLIB_HAVE_SSE41 on" << endl;
#endif
#ifdef DLIB_HAVE_AVX
		cout << "DLIB_HAVE_AVX on" << endl;
#endif
#endif
```

Result:
```bash
AVX on
DLIB_HAVE_SSE2 on
DLIB_HAVE_SSE3 on
DLIB_HAVE_SSE41 on
DLIB_HAVE_AVX on
[rest of the program...]
```

Is this normal?

I restarted the training with the program in release.

**Comment by davisking** [comment]
That's all normal.  The problem is not compiling your program in release mode.
