### ISSUE TITLE
configure ip-address for web_server class ?

### ISSUE THREAD

**Issue by uday60** [davisking/dlib#1441]
Version: Newest
Source: github
Platform: 64bit Centos 7
Compiler: GCC

I am trying to find objects via a rest service. 

While running the code for accepting post requests i am getting the following error. The machine is on network but dlib is not detecting the ip_address properly from sysconfig/network-scripts folder.
How is dlib fetching the ip_address that is resulting in this error ? Is this a bug because the system is working fine and i am able to do ssh and copy files.

[root@localhost src]# ./dlib_server
Couldn't open file: HOSTNAME=localhost.localdomain

**Comment by davisking** [comment]
There is no such thing as dlib_server in dlib.  You must be using some other software.  You should report this to whoever made that software.

**Comment by uday60** [comment]
@davisking 
Well I made this application using gcc compiler in codeblocks. This is using dlib networking library.

**Comment by davisking** [comment]
Fine.  But I have no idea what this dlib_server program is or does.  If you want help you have to fill out the issue template.  Read the instructions in it for submitting an issue and follow them.
