### ISSUE TITLE
dlib19.15.0_release_64bit_msvc1900.lib(dlib_generated_cuda_dlib.cu.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease'

### ISSUE THREAD

**Issue by virtualenv** [davisking/dlib#1448]
Hi,

I have an library that I need to include in my project that needs to be runtime libray  (/MT).
Trying to build dlib with the same spec, I got the error :

dlib19.15.0_release_64bit_msvc1900.lib(dlib_generated_cuda_dlib.cu.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease'

Could someone point me to the right direction please ?

Thank you.

Mauricio.

**Comment by virtualenv** [comment]
After several hours, I realized it was a CMake setting.
Just add : 			
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")

in /dlib19.5/dlib/CMakeLists.txt

**Comment by seamanj** [comment]
you save my day.
