### ISSUE TITLE
would you please open source the code training face_recognition model which was used in dnn_face_recognition_ex.cpp file?

### ISSUE THREAD

**Issue by Jubird915** [davisking/dlib#1450]
Hi Davis,

thanks for your great jobs.

sorry i got the accuracy issue when using your model in a specific environment, so I want train my own face recognition model now.
but I found it much difficult to training a new model.

would you please open source the code training your model?
and I want to change your network such as enlarging the resnet34 or using loss_multiclass to improve the accuracy issue, any suggestions?

**Comment by davisking** [comment]
The code is already open sourced.  Read the commends in the example program you referenced.
