### ISSUE TITLE
need Confidence Vs Threshold

### ISSUE THREAD

**Issue by roy81f** [davisking/dlib#1451]
hi Davis,
just wondering if its possible to determine percentage of confidence when compare between 2 faces. (recognition) as a function of the threshold (table or formula).

Best regards and many thanks for a great project,
Roy

**Comment by davisking** [comment]
If you want to get a "probability that these faces are the same person" then you need to compute a calibration curve using something like Platt scaling or isotonic regression.  Tools for doing both of these things are in dlib and if you google them you can find much written on how to do it.

**Comment by noah196** [comment]
Can you describe this process a bit more?
Which one do you recommend (isotonic or platt) and how to use them by dlib?

**Comment by davisking** [comment]
These are things you do to calibrate the results at the end of training.  There is much written on how to do this.  Google isotonic regression calibration for instance.
