### ISSUE TITLE
Variational Autoencoders?

### ISSUE THREAD

**Issue by Mut1nyJD** [davisking/dlib#1452]
Not really a real issue more sort of a question about feasibility.
Sure the encoder/decoder part of variational auto encoder shouldn't be too hard to implement although I guess you would have to create probably a layer that you could sandwich to do the random sampling from a normalized gausian and use the mean and variation output by the encoder bit. However how would you go about the regularizer or KL in the loss function how could that information that is necessary would be able to be passed in.

**Comment by davisking** [comment]
You would need to write your own loss layer class. Then you can stick whatever you want in it.

**Comment by davisking** [comment]
The "how do I write a loss layer" documentation is here: http://dlib.net/dlib/dnn/loss_abstract.h.html#EXAMPLE_LOSS_LAYER_

**Comment by Mut1nyJD** [comment]
I'll get that but how would you be able in the loss function to access an intermediate layer in this case the output of the encoder part of the network?

**Comment by davisking** [comment]
You can use the layer() method to access sublayers.  In particular, this is
convenient if you use tags to mark the layers you are interested in.
