### ISSUE TITLE
Train model for face recognition

### ISSUE THREAD

**Issue by Strekalov** [davisking/dlib#1459]
Hello, I trained the model as shown in the example dnn_metric_learning_on_images_ex.cpp, but the resulting file has a size of 21997kb as opposed to your model size of 21940kb. So I want to ask how else you changed the example, except for the parameters specified in the comments.

**Comment by davisking** [comment]
That's fine.  It's not going to be exactly the same size each time since
part of the serialization format uses a variable bit width encoding.
