### ISSUE TITLE
Couldn't find the reference documentation on dnn_trainer

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#146]
I am trying to learn how to work with deep learning on dlib, and I couldn't find a reference to the class `dnn_trainer` at the Machine Learning page of the website. I assume this is a bug, given the policy of having everything well documented.

**Comment by davisking** [comment]
Oops, you are right.  It's missing from that page.  I'll add it later
today.

But in general you can find anything by looking at the index (
http://dlib.net/term_index.html) or by using the search box on the top
right of the page.  That will get you do the dnn_trainer's documentation.

**Comment by davisking** [comment]
It's updated.  Thanks for finding this omission :)
