### ISSUE TITLE
[question] How to split input then recombine later in a FCC layer?

### ISSUE THREAD

**Issue by MattWeir** [davisking/dlib#1460]
Hi, I really love dlib but I'm having trouble working out how to declare the following network.  The input data is a combination of image data and some extracted features.  I want to separate and process the image data part with a conv net and then merge the result of that with the feature data into some FCC layers.

Input = image data[128, 128] (flattened) + feature 1 [32] + feature 2 [1]
Conv net of ONLY image data part
FCC of Conv net + feature 1 + feature 2
Output

I'm guessing I'm meant to use extract_ and then concat3 but I'm stuck at how to do this.

**Comment by davisking** [comment]
Yes, you use extract and concat layers to do it.  Did you read the documentation for these layers and the two introductory example programs?  They talk about how you use tag layers to reference parts of the network and generally explain all this stuff.
