### ISSUE TITLE
package init file 'dlib/__init__.py' not found

### ISSUE THREAD

**Issue by N-Tirumala-Rao** [davisking/dlib#1461]
(C:\ProgramData\Anaconda3) C:\Users\Darling>pip install dlib
Collecting dlib
  Using cached https://files.pythonhosted.org/packages/df/aa/6a9bb2a763107bb2606
d6ee1aa65fcd3b51375a9ef6436e9c9280b0dd63c/dlib-19.15.0.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command c:\programdata\anaconda3\python.exe -u -c "import
 setuptools, tokenize;__file__='C:\\Users\\Darling\\AppData\\Local\\Temp\\pip-in
stall-8vkmviyq\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code
=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
 bdist_wheel -d C:\Users\Darling\AppData\Local\Temp\pip-wheel-2npiupz7 --python-
tag cp36:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.6.1 |Anaconda 4.4.0 (32-bit)| (default, May 11
 2017, 14:16:49) [MSC v.1900 32 bit (Intel)]
  Invoking CMake setup: 'cmake C:\Users\Darling\AppData\Local\Temp\pip-install-8
vkmviyq\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Darling\AppD
ata\Local\Temp\pip-install-8vkmviyq\dlib\build\lib.win32-3.6 -DPYTHON_EXECUTABLE
=c:\programdata\anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:
\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\build\lib.win32-3.6'

  -- Building for: Visual Studio 15 2017
  -- Selecting Windows SDK version  to target Windows 6.3.9600.
  CMake Error in CMakeLists.txt:
    Failed to run MSBuild command:

      C:/Program Files/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/M
SBuild.exe

    to get the value of VCTargetsPath:

      Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.

      Build started 28-08-2018 10:41:07.
      Project "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\bui
ld\temp.win32-3.6\Release\CMakeFiles\3.12.0\VCTargetsPath.vcxproj" on node 1 (de
fault targets).
      C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCT
argets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MSB803
6: The Windows SDK version 8.1 was not found. Install the required version of Wi
ndows SDK or change the SDK version in the project property pages or by right-cl
icking the solution and selecting "Retarget solution". [C:\Users\Darling\AppData
\Local\Temp\pip-install-8vkmviyq\dlib\build\temp.win32-3.6\Release\CMakeFiles\3.
12.0\VCTargetsPath.vcxproj]
      Done Building Project "C:\Users\Darling\AppData\Local\Temp\pip-install-8vk
mviyq\dlib\build\temp.win32-3.6\Release\CMakeFiles\3.12.0\VCTargetsPath.vcxproj"
 (default targets) -- FAILED.

      Build FAILED.

      "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\build\temp.
win32-3.6\Release\CMakeFiles\3.12.0\VCTargetsPath.vcxproj" (default target) (1)
->
      (Desktop_PlatformPrepareForBuild target) ->
        C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\V
CTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MSB8
036: The Windows SDK version 8.1 was not found. Install the required version of
Windows SDK or change the SDK version in the project property pages or by right-
clicking the solution and selecting "Retarget solution". [C:\Users\Darling\AppDa
ta\Local\Temp\pip-install-8vkmviyq\dlib\build\temp.win32-3.6\Release\CMakeFiles\
3.12.0\VCTargetsPath.vcxproj]

          0 Warning(s)
          1 Error(s)

      Time Elapsed 00:00:00.27

    Exit code: 1

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Darling/AppData/Local/Temp/pip-install-8vkmviyq/dlib/build/
temp.win32-3.6/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\setup.py
", line 257, in <module>
      'Topic :: Software Development',
    File "c:\programdata\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\programdata\anaconda3\lib\distutils\dist.py", line 955, in run_comm
ands
      self.run_command(cmd)
    File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_comm
and
      cmd_obj.run()
    File "c:\programdata\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line
 179, in run
      self.run_command('build')
    File "c:\programdata\anaconda3\lib\distutils\cmd.py", line 313, in run_comma
nd
      self.distribution.run_command(command)
    File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_comm
and
      cmd_obj.run()
    File "c:\programdata\anaconda3\lib\distutils\command\build.py", line 135, in
 run
      self.run_command(cmd_name)
    File "c:\programdata\anaconda3\lib\distutils\cmd.py", line 313, in run_comma
nd
      self.distribution.run_command(command)
    File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_comm
and
      cmd_obj.run()
    File "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\setup.py
", line 133, in run
      self.build_extension(ext)
    File "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\setup.py
", line 170, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "c:\programdata\anaconda3\lib\subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Darling\\AppData
\\Local\\Temp\\pip-install-8vkmviyq\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTP
UT_DIRECTORY=C:\\Users\\Darling\\AppData\\Local\\Temp\\pip-install-8vkmviyq\\dli
b\\build\\lib.win32-3.6', '-DPYTHON_EXECUTABLE=c:\\programdata\\anaconda3\\pytho
n.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Darling\\AppData\\L
ocal\\Temp\\pip-install-8vkmviyq\\dlib\\build\\lib.win32-3.6']' returned non-zer
o exit status 1.

  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command c:\programdata\anaconda3\python.exe -u -c "impo
rt setuptools, tokenize;__file__='C:\\Users\\Darling\\AppData\\Local\\Temp\\pip-
install-8vkmviyq\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);co
de=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')
)" install --record C:\Users\Darling\AppData\Local\Temp\pip-record-wl5lnx20\inst
all-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.6.1 |Anaconda 4.4.0 (32-bit)| (default, May
11 2017, 14:16:49) [MSC v.1900 32 bit (Intel)]
    Invoking CMake setup: 'cmake C:\Users\Darling\AppData\Local\Temp\pip-install
-8vkmviyq\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Darling\Ap
pData\Local\Temp\pip-install-8vkmviyq\dlib\build\lib.win32-3.6 -DPYTHON_EXECUTAB
LE=c:\programdata\anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=
C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\build\lib.win32-3.
6'
    -- Building for: Visual Studio 15 2017
    -- Selecting Windows SDK version  to target Windows 6.3.9600.
    CMake Error in CMakeLists.txt:
      Failed to run MSBuild command:

        C:/Program Files/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin
/MSBuild.exe

      to get the value of VCTargetsPath:

        Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.

        Build started 28-08-2018 10:41:12.
        Project "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\b
uild\temp.win32-3.6\Release\CMakeFiles\3.12.0\VCTargetsPath.vcxproj" on node 1 (
default targets).
        C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\V
CTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MSB8
036: The Windows SDK version 8.1 was not found. Install the required version of
Windows SDK or change the SDK version in the project property pages or by right-
clicking the solution and selecting "Retarget solution". [C:\Users\Darling\AppDa
ta\Local\Temp\pip-install-8vkmviyq\dlib\build\temp.win32-3.6\Release\CMakeFiles\
3.12.0\VCTargetsPath.vcxproj]
        Done Building Project "C:\Users\Darling\AppData\Local\Temp\pip-install-8
vkmviyq\dlib\build\temp.win32-3.6\Release\CMakeFiles\3.12.0\VCTargetsPath.vcxpro
j" (default targets) -- FAILED.

        Build FAILED.

        "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\build\tem
p.win32-3.6\Release\CMakeFiles\3.12.0\VCTargetsPath.vcxproj" (default target) (1
) ->
        (Desktop_PlatformPrepareForBuild target) ->
          C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\VC
\VCTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MS
B8036: The Windows SDK version 8.1 was not found. Install the required version o
f Windows SDK or change the SDK version in the project property pages or by righ
t-clicking the solution and selecting "Retarget solution". [C:\Users\Darling\App
Data\Local\Temp\pip-install-8vkmviyq\dlib\build\temp.win32-3.6\Release\CMakeFile
s\3.12.0\VCTargetsPath.vcxproj]

            0 Warning(s)
            1 Error(s)

        Time Elapsed 00:00:00.26

      Exit code: 1

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Darling/AppData/Local/Temp/pip-install-8vkmviyq/dlib/buil
d/temp.win32-3.6/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\setup.
py", line 257, in <module>
        'Topic :: Software Development',
      File "c:\programdata\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 955, in run_co
mmands
        self.run_command(cmd)
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\programdata\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.e
gg\setuptools\command\install.py", line 61, in run
      File "c:\programdata\anaconda3\lib\distutils\command\install.py", line 545
, in run
        self.run_command('build')
      File "c:\programdata\anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\programdata\anaconda3\lib\distutils\command\build.py", line 135,
in run
        self.run_command(cmd_name)
      File "c:\programdata\anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\setup.
py", line 133, in run
        self.build_extension(ext)
      File "C:\Users\Darling\AppData\Local\Temp\pip-install-8vkmviyq\dlib\setup.
py", line 170, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\programdata\anaconda3\lib\subprocess.py", line 291, in check_call

        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Darling\\AppDa
ta\\Local\\Temp\\pip-install-8vkmviyq\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OU
TPUT_DIRECTORY=C:\\Users\\Darling\\AppData\\Local\\Temp\\pip-install-8vkmviyq\\d
lib\\build\\lib.win32-3.6', '-DPYTHON_EXECUTABLE=c:\\programdata\\anaconda3\\pyt
hon.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Darling\\AppData\
\Local\\Temp\\pip-install-8vkmviyq\\dlib\\build\\lib.win32-3.6']' returned non-z
ero exit status 1.

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\Darling\\AppData\\Local\\Temp\\pip-install-8vkmviyq\\dlib\\
setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\
n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\U
sers\Darling\AppData\Local\Temp\pip-record-wl5lnx20\install-record.txt --single-
version-externally-managed --compile" failed with error code 1 in C:\Users\Darli
ng\AppData\Local\Temp\pip-install-8vkmviyq\dlib\

**I am Using windows . I have tried installing dlib .I have already installed cmake .  But I am getting troub le in installing dlib can anyone help me please and Thanks in advance**

**Comment by davisking** [comment]
You need to read the error message.  In particular, inside the error you posted is this text, which is basically telling you that you didn't install the right part of visual studio:

> error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of
> Windows SDK or change the SDK version in the project property pages or by right-
> clicking the solution and selecting "Retarget solution"

Do that and it will work.  You can also google that error and you will get many hits telling you what it means and how to fix it.
