### ISSUE TITLE
Trying to install dlib in Windows to use along with python

### ISSUE THREAD

**Issue by KarthikSubramanian17** [davisking/dlib#1463]
## Expected Behavior
Trying to install dlib in windows to use along with face detection modules. 

## Current Behavior
Throws error and cannot use along with python. I tried to build it to using this video which was the only one that worked to build. https://www.youtube.com/watch?v=BKGkA_K1KPA. I was able to successfully build dlib and the dlib is located in my site-packages folder. 

When i try pip install, it says already installed and i cannot import in python(in Anaconda prompt) and jupyter notebook. 

It is not a path issue as I have added all relevant paths. I dont want to install older versions of dlib using .whl file (https://pypi.org/simple/dlib/) or through conda-forge (19.9) as I have a requirement to use 19.13.1 or higher for my project

After building dlib using cmake and Visual Studio are there additional steps to make it work with python.

## Steps to Reproduce
I am unsure of how to reproduce the problem. I downloaded 19.5.0 zip file from this repo and i extracted in my site-packages. I built using cmake and successfully created a project in VS as shown in the video above. But when i go into my Anaconda Prompt inside python, it is saying dlib module cannot be found.

* **Version**: 19.5.0
* **Where did you get dlib**:  Cmake 3.6.3 x64

Update:
I was able to successfully install version 19.8 using .whl file. Where can i find a .whl file for the latest versions 19.13.1 - 19.15? It would be really useful as this method is the only one that works for me as using conda to install v19.10 downgrades other required packages.

**Comment by davisking** [comment]
The instructions in that video are just wrong.  Please read the official dlib instructions: http://dlib.net/compile.html
