### ISSUE TITLE
deep metric learning

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#1466]
Hi @davisking ,
For the deep metric learning, dnn_metric_learning_on_images_ex ,it seems that the training data should be square(rows = cols), 
DLIB_CASSERT(num_rows(img)==num_columns(img)); in jitter image processing.
I just wonder why it should be square to be processed, could I change this restriction? thank you

**Comment by davisking** [comment]
Just don’t call jitter_image if it doesn’t do what you want.
