### ISSUE TITLE
const adjust_threshold

### ISSUE THREAD

**Issue by takotakot** [davisking/dlib#1468]
https://github.com/davisking/dlib/blob/6ec3aea942766e5bdccd0ff241b521d7deb23445/dlib/image_processing/object_detector_abstract.h#L286

I think
`const double adjust_threshold = 0` may be better than
`const adjust_threshold = 0`
. (If I'm wrong, sorry.)

**Comment by davisking** [comment]
Yep, that's definitely a typo.  Thanks for pointing it out.  It's fixed now.
