### ISSUE TITLE
Replace std::vector with a template interface for dnn_trainer data and label

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#147]
This is a feature request that I feel is missing fro dlib's DNN interface. Instead of having the `train` family function taking `std::vector`s like this:

```c++
void train (
    const std::vector<input_type>& data,
    const std::vector<label_type>& labels 
); 
```

it would be nice if an vector like interface was defined, so that the user could get creative on how to get the data to feed the solver, like this:

```c++
template <
    typename vec_type_1,
    typename vec_type_2
>
void train (
    const vec_type_1& data,
    const vec_type_2& labels 
);
```

and the likes for other training family functions (and net evaluation functions). If the `vec_type` interface is specified to fit the std::vector functionalities used by the training functions, it wouldn't break code compatibility, and would allow fancy tricks on how to get the training data, like from a `mmap`ed pointer, or allow the user to attach on-the-fly filters or preprocessors on the data.

Is it desirable? How could it be done? Such a change would be merged? I've posted this to spark some discussion on the issue before I try to implement it.

**Comment by davisking** [comment]
We can do that.  However, I'm pretty sure you can already more easily
accomplish those things you mentioned using the existing API.  For example,
have you looked at this example program yet
http://dlib.net/dnn_introduction2_ex.cpp.html?

**Comment by lvella** [comment]
Indeed, doing step by step seems much simpler. I guess these modifications are not worth the effort...

**Comment by davisking** [comment]
No worries :)
