### ISSUE TITLE
weight file

### ISSUE THREAD

**Issue by 3073** [davisking/dlib#1472]
Hi guys 

Could not load image 'mmod_human_face_detector.dat'.
TGA image type not supported

the weight file for cnn face detector of dlib does not work for me....it just pop up syntax error in the line of code which is situated below the weight file

**Comment by davisking** [comment]
Fill out the issue template.

**Comment by 3073** [comment]
I just use this sample age detection script inside which a cnn based face detection run first.... then when I try to execute it gives syntax error. 
error occur at this line:
detector = cnn_face_detection_model_v1(args["weight_cnn"]
img_size = 64  ( syntax error cames here when I execute......) 
This is the script :

import cv2
import dlib
import numpy as np
from wide_resnet import WideResNet
args = {
        "weight": "/home/ame/Downloads/weights.28-3.73.hdf5",
        "depth": 16,
        "width" : 8,
        "margin" : 0.4,
        "weight_cnn" : "/home/ame/Downloads/mmod_human_face_detector.dat"
}
def draw_label(image, point, label, font=cv2.FONT_HERSHEY_SIMPLEX,
               font_scale=1, thickness=2):
    size = cv2.getTextSize(label, font, font_scale, thickness)[0]
    x, y = point
    cv2.rectangle(image, (x, y - size[1]), (x + size[0], y), (255, 0, 0), cv2.FILLED)
    cv2.putText(image, label, point, font, font_scale, (255, 255, 255), thickness)

def main():
    cap = cv2.VideoCapture(0)
    depth = args["depth"]
    k = args["width"]
    weight_file = args["weight"]
    margin = args["margin"]
    detector = cnn_face_detection_model_v1(args["weight_cnn"]
    img_size = 64
    model = WideResNet(img_size, depth=depth, k=k)()
    model.load_weights(weight_file)
    while True:
        ret, img = cap.read()
        if not ret:
                raise RuntimeError("Failed to capture image")
        input_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_h, img_w, _ = np.shape(input_img)
        detected = detector(input_img, 1)
        faces = np.empty((len(detected), img_size, img_size, 3))
        if len(detected) > 0:
            for i, d in enumerate(detected):
                x1, y1, x2, y2, w, h = d.left(), d.top(), d.right() + 1, d.bottom() + 1, d.width(), d.height()
                xw1 = max(int(x1 - margin * w), 0)
                yw1 = max(int(y1 - margin * h), 0)
                xw2 = min(int(x2 + margin * w), img_w - 1)
                yw2 = min(int(y2 + margin * h), img_h - 1)
                cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 0), 2)
                cv2.rectangle(img, (xw1, yw1), (xw2, yw2), (255, 0, 0), 2)
                faces[i, :, :, :] = cv2.resize(img[yw1:yw2 + 1, xw1:xw2 + 1, :], (img_size, img_size))
            results = model.predict(faces)
            predicted_genders = results[0]
            ages = np.arange(0, 101).reshape(101, 1)
            predicted_ages = results[1].dot(ages).flatten()
            for i, d in enumerate(detected):
                label = "{}, {}".format(int(predicted_ages[i]),
                                        "F" if predicted_genders[i][0] > 0.5 else "M")
                draw_label(img, (d.left(), d.top()), label)
        cv2.imshow("result", img)
        key = cv2.waitKey(30)
        if key == 27:
            break
if __name__ == '__main__':
    main()

**Comment by 3073** [comment]
img_size = 64
           ^
SyntaxError: invalid syntax

**Comment by 3073** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "/home/ame/Downloads/Zip/Test folder/age-gender-estimation-master/demo.py", line 26
    img_size = 64
           ^
SyntaxError: invalid syntax

**Comment by 3073** [comment]
Hi davis !!
I think you are not confortable with my question. i am sorry if it was confusing...

**Comment by matt-francomb** [comment]
Have you tried putting a closing parenthesis at the end of the line that
precedes the detection of the syntax error? This looks like a python
question, nothing to do with dlib.

**Comment by 3073** [comment]
Thank you !!! I am on to it ...
