### ISSUE TITLE
resize_image() for rgb image with same type arguments?

### ISSUE THREAD

**Issue by Elvisass** [davisking/dlib#1473]
* **Version**: 19.15
* **Where did you get dlib**: dlib.net
* **Platform**:  ARM-Linux with VFP & NEON

`interpolation.h` provides 1 common and 3 optimized version of `resize_image()`:
```C++
// Common template
template <typename image_type1, typename image_type2, typename interpolation_type>
void resize_image(...);

// Template for some other pixel or mixed pixel type?
template <typename image_type1, typename image_type2>
typename disable_if_c<
    (is_rgb_image<image_type1>::value&&is_rgb_image<image_type2>::value) || 
    (is_grayscale_image<image_type1>::value&&is_grayscale_image<image_type2>::value)>::type 
resize_image(...);

// Template for grayscale image
template <typename image_type, typename image_type2>
typename enable_if_c<
    is_grayscale_image<image_type>::value && is_grayscale_image<image_type2>::value
    && images_have_same_pixel_types<image_type,image_type2>::value>::type 
resize_image(...);

// Template for rgb image
template <typename image_type>
typename enable_if<is_rgb_image<image_type> >::type
resize_image (const image_type& in_img_, image_type& out_img_,interpolate_bilinear);
```
I'm trying to speed up the face detection, and use `matrix<rgb_pixel>` to store a rgb image.
In `create_fhog_pyramid()`, images are resized by `pyr.operator()`:
```C++
pyr(img, temp1);   // matrix and array2d
pyr(temp2, temp1); // array2d and array2d
```
and the first resizing call the common template version because `img` and `temp1` are two different types...

my question is,
Is there any special reason to limit rgb `resize_image` with same argument type but other template with 2 types? Can I modify it to
```C++
template <typename image_type, typename image_type2>
typename enable_if_c<
    is_rgb_image<image_type>::value && is_rgb_image<image_type2>::value
//  && images_have_same_pixel_types<image_type,image_type2>::value
    >::type 
resize_image(...);
```
or,
Did I use wrong type variable to store image? I choose `matrix` because `face_recognition_model_v1::compute_face_descriptor` use it...

**Comment by davisking** [comment]
No, there isn't any reason for it.  It would probably be better if it was changed in the way you suggest in fact.  You should submit a PR for it :)

**Comment by Elvisass** [comment]
Got it, thx.
But I may not submit a PR, as I have modified many other places for speeding up and I'm still not very clear about their side effect or, are them correct. For example, i'm not sure whether the commented line in my "suggestion" should be commented out.
Sorry for that.
