### ISSUE TITLE
what makes face detector slower than before

### ISSUE THREAD

**Issue by helloearth012** [davisking/dlib#1474]
dlib/image_processing/object_detector.h

I did face detection with below code from version 01/10/2018(don't quite accurate) and version 09/01/2018, it seems like the new version took 600ms to finish 1 image, and old version took 200ms to finish the same image, any change could cause this?

```
    template <
        typename image_scanner_type
        >
    template <
        typename image_type
        >
    void object_detector<image_scanner_type>::
    operator() (
        const image_type& img,
        std::vector<full_detection>& final_dets,
        double adjust_threshold 
    )
    {
        std::vector<rect_detection> dets;
        (*this)(img,dets,adjust_threshold);

        final_dets.resize(dets.size());

        // convert all the rectangle detections into full_object_detections.
        for (unsigned long i = 0; i < dets.size(); ++i)
        {
            final_dets[i].detection_confidence = dets[i].detection_confidence;
            final_dets[i].weight_index = dets[i].weight_index;
            final_dets[i].rect = scanner.get_full_object_detection(dets[i].rect, w[dets[i].weight_index].w);
        }
    }
```

**Comment by davisking** [comment]
I just tested this and I don't see any speed difference.  I also don't
recall making any changes to this stuff.

You are going to need to be way more specific.  How do I replicate this?
What did you do *exactly*?

**Comment by helloearth012** [comment]
Sorry, my mistake. 
I used modified old version dlib sped up with tbb, 
https://github.com/antimodular/ofxOpenFace/blob/master/libs_others/dlib/include/dlib/image_processing/object_detector.h
