### ISSUE TITLE
Can't save large jpeg file.

### ISSUE THREAD

**Issue by posutsai** [davisking/dlib#1475]
## Expected Behavior

I try to write a large jpeg file, in this case 100000 * 100000 with following code snippet.
```c++
int main() {
        dlib::matrix<dlib::rgb_pixel> test(100000, 100000);
        dlib::set_all_elements(test, dlib::rgb_pixel(125, 125, 125));
        dlib::save_jpeg(test, "bug.jpeg");
}
```
## Current Behavior

OS print following error message.
```
terminate called after throwing an instance of 'dlib::image_save_error'
  what():  save_jpeg: error while writing bug.jpeg
Aborted (core dumped)
```
## Steps to Reproduce

Compile my code and run it.

* **Version**: 
dlib-19.15
* **Where did you get dlib**: 
I download it from dlib.net.
* **Platform**: 
Ubuntu 16.04
* **Compiler**: 
g++

**Comment by davisking** [comment]
That is a limitation of the jpeg format, it's not up to dlib.
