### ISSUE TITLE
[Feature Request] Build just the DNN submodule

### ISSUE THREAD

**Issue by jpdoyle** [davisking/dlib#148]
First off, congratulations on making the only DNN library for C++ that (a) compiles easily without requiring a zoo of dependencies and (b) performs well on a variety of machines -- Caffe fails (a), and many alternatives like tiny-cnn fail (b).

One of the reasons I care about those things is that I do a lot of distributed systems work, where each machine might have slightly different hardware configuration (and thus, slightly different libraries available). Being able to recompile a project quickly and automatically for each machine is pretty important to my use case.

However, I'm currently only planning to use the DNN features of your library, and that appears to only use 10% or less of the total library. Compiling the other 90% adds a significant amount of overhead to the deployment process, so I was wondering if some compile-time switches could be added to decide which modules are enabled. Perhaps something like SFML, which is composed of 5 semi-independent modules.

**Comment by e-fominov** [comment]
Take a look at this file https://github.com/davisking/dlib/blob/master/dlib/all/source.cpp - there are switches you are looking for
Also you can copy-paste parts from this file (or include it) into your project and you will not need libdlib at all

**Comment by davisking** [comment]
There are also switches in cmake to disable the GUI, which is maybe what
you want.

But compiling things doesn't take that long.  Are you using parallel builds
e.g. make -j12?

**Comment by jpdoyle** [comment]
Interesting. I didn't realize everything was brought together in one file. @davisking I have been doing parallel builds, I just don't have the beefiest machine available for running the builds at this moment.

**Comment by davisking** [comment]
It shouldbe noted that dlib/all/source.cpp doesn't include the CUDA code
needed to run the GPU version of the deep learning tools though.  You can
only run the CPU version with that file.

You can also use cmake to install a shared library version of dlib.  Then
you won't have to build it at all from then on.

**Comment by jpdoyle** [comment]
Unfortunately I am not the sysadmin of the machines I'm trying to use DLib on, so installation is not really an option.

**Comment by e-fominov** [comment]
@jpdoyle, put libdlib.so into your app folder and run with changed LD_LIBRARY_PATH
`LD_LIBRARY_PATH=. ./your_application`

or use static version of dlib. so you have a lot of ways to optimize your process
library itself is 99% header-based, so dont worry about its size and modularity and I think, dlib has enough switches for excluding modules
