### ISSUE TITLE
memory error when loading more images on dnn_metric_learning_on_images_ex

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#1480]
* **Version**: 
19.15
* **Where did you get dlib**: 
downloaded from dlib.net 
* **Platform**: 
windows 64-bit and ubuntu 16.04 64bit
* **Compiler**: 
Visual studio 2015 on windows
Codeblock gcc on Ubuntu.

Building successfully but when I run the dnn_metric_learning_on_images_ex, it generated error as follow:
Saved state to face_metric_sync
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

I have about 51 identities, with about 200 images for each identity in different sub folders, I followed the training guide in the source code, but it seems that we could only use <5 identities, <5 images. 
for example:
load_mini_batch(5, 5, rnd, objs, images, labels); --------------------this is OK
..........................
load_mini_batch(51, 200, rnd, objs, images, labels);-----------------memory error
-------------------
load_mini_batch(51, 10, rnd, objs, images, labels);-----------------memory error
----------------------

**Comment by anguoyang** [comment]
I have tried on both windows and ubuntu, all with same result.

**Comment by davisking** [comment]
bad_alloc just means you are running out of RAM.  You need to use a
computer with more RAM or load less data.

**Comment by anguoyang** [comment]
my computer has 64g RAM

**Comment by anguoyang** [comment]
my computer has 64g RAM, the images are only 250*250 pixel

**Comment by davisking** [comment]
Maybe you are building your program in 32bit mode, and so can't access all your ram then.

**Comment by anguoyang** [comment]
no, I always build dlib in 64bit, could please use some time to test on it? I could send the data to you, it's not so big, thank you
