### ISSUE TITLE
Python face detection vs C++ example face detection

### ISSUE THREAD

**Issue by ndtreviv** [davisking/dlib#1484]
I'm trying to write a JNI wrapper to extract face descriptors and locations. I've so far used code from the examples to do this. It looks something like this:
```
   frontal_face_detector detector;
 ...
   detector = get_frontal_face_detector();
...
    for (auto face : detector(img, 0))
    {
        auto shape = sp(img, face); //sp = shape_predictor_5_face_landmarks
        matrix<rgb_pixel> face_chip;
        extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);
        faces.push_back(move(face_chip));
        coords.push_back(face);
    }
...
    std::vector<dlib::matrix<float,0,1>> face_descriptors = net(faces); //net = dlib_face_recognition_resnet_model_v1
```
It works, but `detector(img, 0)` takes over 2 minutes to run over my image (IKR!).
**HOWEVER** when I run the following in python:
```
import dlib

face_detector = dlib.get_frontal_face_detector()
import PIL.Image
im = PIL.Image.open("FullSizeRender.jpg")
im = im.convert('RGB')
import numpy as np
img = np.array(im)
face_detector(img, 0)
```
it runs exponentially faster - less than 2 seconds (Whaaaa?!).

What is the python API doing differently? I'm trying to track it back via the python bindings, but unfortunately my C++-fu isn't as strong as it should be.

What's the fastest way to obtain face encodings and locations using the C++ API (the examples are too slow)?

Thank you for any help you can offer!

**Comment by davisking** [comment]
The python interface isn't doing anything different.  See: http://dlib.net/faq.html#Whyisdlibslow

**Comment by ndtreviv** [comment]
I’ve read that. Several times.

I’m running it on a Mac. I’ve built dlib from source with Release config and the AVX instructions flag set.

What else have I missed?

**Comment by AlexeiScherbakov** [comment]
I made C# wrapper. Оn Windows/Visual Studio for fast run AVX/AVX2 support need be enabled by 3 switches: 2 DLIB defines DLIB_HAVE_AVX, DLIB_HAVE_AVX2, and 1 compiler flag /arch:AVX2, also various O flags must be setted.

**Comment by ndtreviv** [comment]
OK, so I did enable AVX Instructions when I compiled dlib, and I built it using the Release config.

Adding this into my project's CMakeLists.txt worked:
```
set(USE_AVX_INSTRUCTIONS ON CACHE BOOL "Use AVX instructions")
```

I found the solution here: https://stackoverflow.com/questions/51250296/dlib-face-detection-terrible-performance-on-c-good-in-python-why

**Comment by ndtreviv** [comment]
OK, I've figured out what it was.

I was building dlib with AVX instruction set compiler optimisation turned on (as above), and then building my project separately with this in my CMakeLists.txt file:
```
find_package(dlib REQUIRED)
message(STATUS "Using dlib-${dlib_VERSION}")
```
As it was outputting the message with the correct version of dlib, I was assuming that it was working.

This does not work. I mean, it works, but for some reason it doesn't work _fast_.

To get the most out of dlib, you need to include it as a subdirectory:
```
add_subdirectory(../dlib dlib_build)
```

And then build _**your**_ project as your would have built dlib, ie:
```
cmake -DUSE_AVX_INSTRUCTIONS=ON  ../
cmake --build . --config Release
```

**Comment by ndtreviv** [comment]
I did try it with find_package() and with building my project with exactly the same commands (Release build mode and AVX instructions enabled), but that didn't work. 🤷‍♂️
Anyway, it works now, and in reality there's not a lot of difference for me building dlib separately and include with find_package or using add_subdirectory when it comes to deploying it. Either way, I need to clone the dlib repo, so I'm happy.

**Comment by davisking** [comment]
To be very specific, compiler optimization is enabled with -O3. Then avx usage is enabled with -mavx. That’s how gcc and clang work. If you don’t do that it’s slow. And setting these sorts of options is up to you when you use find_package. That’s how cmake works.
