### ISSUE TITLE
Dlib on a raspberry Pi 3

### ISSUE THREAD

**Issue by paularios** [davisking/dlib#1487]
I am having problems when installing dlib on a Raspberry Pi 3. This is the exception log: 

sudo pip install dlib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting dlib
  Using cached https://files.pythonhosted.org/packages/df/aa/6a9bb2a763107bb2606d6ee1aa65fcd3b51375a9ef6436e9c9280b0dd63c/dlib-19.15.0.tar.gz
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command /usr/bin/python -u -c "import
setuptools, tokenize;__file__='/tmp/pip-install-6SPvyp/dlib/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-record-1CRWbk/install-record.txt
--single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 2.7.13 (default, Nov 24 2017, 17:33:09)
    Invoking CMake setup: 'cmake
/tmp/pip-install-6SPvyp/dlib/tools/python
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-6SPvyp/dlib/build/lib.linux-armv7l-2.7
-DPYTHON_EXECUTABLE=/usr/bin/python -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 6.3.0
    -- The CXX compiler identification is GNU 6.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python (found version "2.7.13")
    -- Found PythonLibs: python2.7
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.2.2
    -- Using CMake version: 3.7.2
    -- Compiling dlib version: 19.15.0
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Looking for XOpenDisplay in
/usr/lib/arm-linux-gnueabihf/libX11.so;/usr/lib/arm-linux-gnueabihf/libXext.so
    -- Looking for XOpenDisplay in
/usr/lib/arm-linux-gnueabihf/libX11.so;/usr/lib/arm-linux-gnueabihf/libXext.so
- found
    -- Looking for gethostbyname
    -- Looking for gethostbyname - found
    -- Looking for connect
    -- Looking for connect - found
    -- Looking for remove
    -- Looking for remove - found
    -- Looking for shmat
    -- Looking for shmat - found
    -- Looking for IceConnectionNumber in ICE
    -- Looking for IceConnectionNumber in ICE - found
    -- Found X11: /usr/lib/arm-linux-gnueabihf/libX11.so
    -- Looking for png_create_read_struct
    -- Looking for png_create_read_struct - found
    -- Looking for jpeg_read_header
    -- Looking for jpeg_read_header - found
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for module 'lapack'
    --   Found lapack, version 0.2.19
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Found OpenBLAS library
    -- Looking for sgetrf_single
    -- Looking for sgetrf_single - found
    -- Using OpenBLAS's built in LAPACK
    -- Looking for cblas_ddot
    -- Looking for cblas_ddot - found
    -- Looking for sgesv
    -- Looking for sgesv - not found
    -- Looking for sgesv_
    -- Looking for sgesv_ - not found
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR
CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required
is at least version "7.5")
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    -- Configuring done
    -- Generating done
    -- Build files have been written to:
/tmp/pip-install-6SPvyp/dlib/build/temp.linux-armv7l-2.7
    Invoking CMake build: 'cmake --build . --config Release -- -j1'
    Scanning dependencies of target dlib
    [  1%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
    [  2%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    [  3%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
    [  4%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
    [  5%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
    [  6%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
    [  8%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
    [  9%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
    [ 10%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
    [ 11%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
    [ 12%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
    [ 13%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
    [ 15%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
    [ 16%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
    In file included from /usr/include/c++/6/vector:69:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/global_optimization/global_function_search.h:7,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/global_optimization/global_function_search.cpp:2:
    /usr/include/c++/6/bits/vector.tcc: In member function ‘void
std::vector<_Tp, _Alloc>::_M_fill_insert(std::vector<_Tp,
_Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const
value_type&) [with _Tp = double; _Alloc = std::allocator<double>]’:
    /usr/include/c++/6/bits/vector.tcc:449:5: note: parameter passing
for argument of type ‘std::vector<double>::iterator {aka
__gnu_cxx::__normal_iterator<double*, std::vector<double> >}’ will
change in GCC 7.1
         vector<_Tp, _Alloc>::
         ^~~~~~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/vector.tcc: In member function ‘void
std::vector<_Tp, _Alloc>::_M_insert_aux(std::vector<_Tp,
_Alloc>::iterator, _Args&& ...) [with _Args = {std::pair<unsigned int,
double>}; _Tp = std::pair<unsigned int, double>; _Alloc =
std::allocator<std::pair<unsigned int, double> >]’:
    /usr/include/c++/6/bits/vector.tcc:321:7: note: parameter passing
for argument of type ‘std::vector<std::pair<unsigned int, double>
>::iterator {aka __gnu_cxx::__normal_iterator<std::pair<unsigned int,
double>*, std::vector<std::pair<unsigned int, double> > >}’ will
change in GCC 7.1
           vector<_Tp, _Alloc>::
           ^~~~~~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/vector.tcc:321:7: note: parameter passing
for argument of type ‘std::vector<std::pair<unsigned int, double>
>::iterator {aka __gnu_cxx::__normal_iterator<std::pair<unsigned int,
double>*, std::vector<std::pair<unsigned int, double> > >}’ will
change in GCC 7.1
    /usr/include/c++/6/bits/vector.tcc: In function ‘typename
dlib::disable_if<dlib::is_matrix<image_type> >::type dlib::assign(T&,
const dlib::matrix_exp<src_exp>&) [with T =
std::vector<std::pair<unsigned int, double> >; EXP =
dlib::matrix_op<dlib::op_colm2<dlib::matrix<double, 0l, 1l> > >]’:
    /usr/include/c++/6/bits/vector.tcc:313:4: note: parameter passing
for argument of type ‘__gnu_cxx::__normal_iterator<std::pair<unsigned
int, double>*, std::vector<std::pair<unsigned int, double> > >’ will
change in GCC 7.1
        _M_insert_aux(begin() + (__position - cbegin()),
        ^~~~~~~~~~~~~
    In file included from /usr/include/c++/6/vector:64:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/global_optimization/global_function_search.h:7,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/global_optimization/global_function_search.cpp:2:
    /usr/include/c++/6/bits/stl_vector.h: In member function ‘void
dlib::svm_c_linear_dcd_trainer<K>::optimizer_state::init(const
in_sample_vector_type&, const in_scalar_vector_type&, bool, bool,
bool, dlib::svm_c_linear_dcd_trainer<K>::scalar_type,
dlib::svm_c_linear_dcd_trainer<K>::scalar_type) [with
in_sample_vector_type =
dlib::matrix_op<dlib::op_std_vect_to_mat<std::vector<std::vector<std::pair<unsigned
int, double> > > > >; in_scalar_vector_type =
dlib::matrix_op<dlib::op_std_vect_to_mat<std::vector<double> > >; K =
dlib::sparse_linear_kernel<std::vector<std::pair<unsigned int, double>
> >]’:
    /usr/include/c++/6/bits/stl_vector.h:1055:2: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<double*,
std::vector<double> >’ will change in GCC 7.1
      _M_fill_insert(begin() + __offset, __n, __x);
      ^~~~~~~~~~~~~~
    [ 17%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/filtering/kalman_filter.cpp.o
    [ 18%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/test_for_odr_violations.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/svm/auto.cpp.o
    [ 20%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
    [ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
    In file included from /usr/include/c++/6/queue:62:0,
                     from /tmp/pip-install-6SPvyp/dlib/dlib/bsp/bsp.h:9,
                     from /tmp/pip-install-6SPvyp/dlib/dlib/bsp/bsp.cpp:6:
    /usr/include/c++/6/bits/stl_heap.h: In function ‘void
std::__push_heap(_RandomAccessIterator, _Distance, _Distance, _Tp,
_Compare) [with _RandomAccessIterator =
__gnu_cxx::__normal_iterator<dlib::impl1::thread_safe_message_queue::msg_wrap*,
std::vector<dlib::impl1::thread_safe_message_queue::msg_wrap,
std::allocator<dlib::impl1::thread_safe_message_queue::msg_wrap> > >;
_Distance = int; _Tp =
dlib::impl1::thread_safe_message_queue::msg_wrap; _Compare =
__gnu_cxx::__ops::_Iter_comp_val<std::less<dlib::impl1::thread_safe_message_queue::msg_wrap>
>]’:
    /usr/include/c++/6/bits/stl_heap.h:124:5: note: parameter passing
for argument of type
‘__gnu_cxx::__normal_iterator<dlib::impl1::thread_safe_message_queue::msg_wrap*,
std::vector<dlib::impl1::thread_safe_message_queue::msg_wrap,
std::allocator<dlib::impl1::thread_safe_message_queue::msg_wrap> > >’
will change in GCC 7.1
         __push_heap(_RandomAccessIterator __first,
         ^~~~~~~~~~~
    /usr/include/c++/6/bits/stl_heap.h: In function ‘void
std::__adjust_heap(_RandomAccessIterator, _Distance, _Distance, _Tp,
_Compare) [with _RandomAccessIterator =
__gnu_cxx::__normal_iterator<dlib::impl1::thread_safe_message_queue::msg_wrap*,
std::vector<dlib::impl1::thread_safe_message_queue::msg_wrap,
std::allocator<dlib::impl1::thread_safe_message_queue::msg_wrap> > >;
_Distance = int; _Tp =
dlib::impl1::thread_safe_message_queue::msg_wrap; _Compare =
__gnu_cxx::__ops::_Iter_comp_iter<std::less<dlib::impl1::thread_safe_message_queue::msg_wrap>
>]’:
    /usr/include/c++/6/bits/stl_heap.h:209:5: note: parameter passing
for argument of type
‘__gnu_cxx::__normal_iterator<dlib::impl1::thread_safe_message_queue::msg_wrap*,
std::vector<dlib::impl1::thread_safe_message_queue::msg_wrap,
std::allocator<dlib::impl1::thread_safe_message_queue::msg_wrap> > >’
will change in GCC 7.1
         __adjust_heap(_RandomAccessIterator __first, _Distance __holeIndex,
         ^~~~~~~~~~~~~
    [ 23%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
    [ 24%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
    [ 25%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
    [ 26%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
    [ 27%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
    [ 29%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
    [ 30%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
    [ 31%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
    [ 32%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
    [ 33%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
    [ 34%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
    [ 36%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
    [ 37%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
    [ 38%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
    [ 39%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
    [ 40%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
    [ 41%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
    [ 43%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
    [ 44%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
    [ 45%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
    [ 46%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
    [ 47%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
    [ 48%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
    [ 50%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
    [ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
    [ 52%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/cuda/cpu_dlib.cpp.o
    [ 53%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/cuda/tensor_tools.cpp.o
    [ 54%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
    [ 55%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/widgets.cpp.o
    In file included from /usr/include/c++/6/vector:69:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.h:12,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.cpp:9:
    /usr/include/c++/6/bits/vector.tcc: In member function ‘void
std::vector<_Tp, _Alloc>::_M_range_insert(std::vector<_Tp,
_Alloc>::iterator, _ForwardIterator, _ForwardIterator,
std::forward_iterator_tag) [with _ForwardIterator =
__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >; _Tp =
dlib::image_display::overlay_circle; _Alloc =
std::allocator<dlib::image_display::overlay_circle>]’:
    /usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing
for argument of type
‘std::vector<dlib::image_display::overlay_circle>::iterator {aka
__gnu_cxx::__normal_iterator<dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >}’ will change in
GCC 7.1
           vector<_Tp, _Alloc>::
           ^~~~~~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing
for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    /usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing
for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    In file included from /usr/include/c++/6/vector:64:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.h:12,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.cpp:9:
    /usr/include/c++/6/bits/stl_vector.h: In member function ‘void
dlib::image_display::add_overlay(const
std::vector<dlib::image_display::overlay_circle>&)’:
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type
‘std::vector<dlib::image_display::overlay_circle>::iterator {aka
__gnu_cxx::__normal_iterator<dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >}’ will change in
GCC 7.1
        _M_range_insert(__pos, __first, __last, _IterCategory());
        ^~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    /usr/include/c++/6/bits/stl_vector.h: In member function ‘void
dlib::image_window::add_overlay(const
std::vector<dlib::image_display::overlay_circle>&)’:
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type
‘std::vector<dlib::image_display::overlay_circle>::iterator {aka
__gnu_cxx::__normal_iterator<dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >}’ will change in
GCC 7.1
        _M_range_insert(__pos, __first, __last, _IterCategory());
        ^~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::image_display::overlay_circle*,
std::vector<dlib::image_display::overlay_circle> >’ will change in GCC
7.1
    In file included from /usr/include/c++/6/vector:69:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.h:12,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.cpp:9:
    /usr/include/c++/6/bits/vector.tcc: In member function ‘void
std::vector<_Tp, _Alloc>::_M_range_insert(std::vector<_Tp,
_Alloc>::iterator, _ForwardIterator, _ForwardIterator,
std::forward_iterator_tag) [with _ForwardIterator =
__gnu_cxx::__normal_iterator<const
dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >; _Tp =
dlib::perspective_display::overlay_line; _Alloc =
std::allocator<dlib::perspective_display::overlay_line>]’:
    /usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing
for argument of type
‘std::vector<dlib::perspective_display::overlay_line>::iterator {aka
__gnu_cxx::__normal_iterator<dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >}’ will change
in GCC 7.1
           vector<_Tp, _Alloc>::
           ^~~~~~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing
for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >’ will change in
GCC 7.1
    /usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing
for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >’ will change in
GCC 7.1
    In file included from /usr/include/c++/6/vector:64:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.h:12,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/gui_widgets/widgets.cpp:9:
    /usr/include/c++/6/bits/stl_vector.h: In member function ‘void
dlib::perspective_display::add_overlay(const
std::vector<dlib::perspective_display::overlay_line>&)’:
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type
‘std::vector<dlib::perspective_display::overlay_line>::iterator {aka
__gnu_cxx::__normal_iterator<dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >}’ will change
in GCC 7.1
        _M_range_insert(__pos, __first, __last, _IterCategory());
        ^~~~~~~~~~~~~~~
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >’ will change in
GCC 7.1
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >’ will change in
GCC 7.1
    /usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter
passing for argument of type ‘__gnu_cxx::__normal_iterator<const
dlib::perspective_display::overlay_line*,
std::vector<dlib::perspective_display::overlay_line> >’ will change in
GCC 7.1
    [ 56%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/drawable.cpp.o
    [ 58%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.cpp.o
    [ 59%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/style.cpp.o
    [ 60%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/base_widgets.cpp.o
    [ 61%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.cpp.o
    [ 62%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.cpp.o
    [ 63%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
    [ 65%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
    [ 66%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
    [ 67%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
    [ 68%] Linking CXX static library libdlib.a
    [ 68%] Built target dlib
    Scanning dependencies of target dlib_python
    [ 69%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
    In file included from
/tmp/pip-install-6SPvyp/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                     from
/tmp/pip-install-6SPvyp/dlib/dlib/../dlib/python/pybind_utils.h:6,
                     from /tmp/pip-install-6SPvyp/dlib/dlib/../dlib/python.h:6,
                     from
/tmp/pip-install-6SPvyp/dlib/tools/python/src/opaque_types.h:6,
                     from
/tmp/pip-install-6SPvyp/dlib/tools/python/src/dlib.cpp:4:
    /tmp/pip-install-6SPvyp/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20:
fatal error: Python.h: No existe el fichero o el directorio
     #include <Python.h>
                        ^
    compilation terminated.
    CMakeFiles/dlib_python.dir/build.make:62: fallo en las
instrucciones para el objetivo
'CMakeFiles/dlib_python.dir/src/dlib.cpp.o'
    make[2]: *** [CMakeFiles/dlib_python.dir/src/dlib.cpp.o] Error 1
    CMakeFiles/Makefile2:67: fallo en las instrucciones para el
objetivo 'CMakeFiles/dlib_python.dir/all'
    make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
    Makefile:83: fallo en las instrucciones para el objetivo 'all'
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6SPvyp/dlib/setup.py", line 257, in <module>
        'Topic :: Software Development',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py",
line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6SPvyp/dlib/setup.py", line 133, in run
        self.build_extension(ext)
      File "/tmp/pip-install-6SPvyp/dlib/setup.py", line 173, in build_extension
        subprocess.check_call(cmake_build, cwd=build_folder)
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.',
'--config', 'Release', '--', '-j1']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools,
tokenize;__file__='/tmp/pip-install-6SPvyp/dlib/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record /tmp/pip-record-1CRWbk/install-record.txt
--single-version-externally-managed --compile" failed with error code
1 in /tmp/pip-install-6SPvyp/dlib/

If anybody knows a possible solution, please let me know.

Thanks. 

Paula.

**Comment by badluckwiththinking** [comment]
Looks like you are missing the python development files. I'm guessing your running something like raspbian so run `sudo apt-get install python-dev` and then retry
