### ISSUE TITLE
Does Not Build w/Cuda 10.0

### ISSUE THREAD

**Issue by alexmarkley** [davisking/dlib#1490]
## Expected Behavior
`cmake --config Release ..` should successfully initialize cmake.

## Current Behavior
Cmake fails with the following errors:

```
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cuda/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /home/alex/Build/dlib/dlib_git/dlib

-- Configuring incomplete, errors occurred!
See also "/home/alex/Build/dlib/dlib_git/build/CMakeFiles/CMakeOutput.log".
See also "/home/alex/Build/dlib/dlib_git/build/CMakeFiles/CMakeError.log".
```

## Steps to Reproduce
- Install Cuda 10.0
- Install cudnn-10.0-linux-x64-v7.3.0.29
- Attempt to build Dlib

**Version**:
Dlib 19.15 and git master HEAD.

**Where did you get dlib**:
Problem exists in both the current release tarball (as downloaded from the dlib.net website) and in current git master.

**Platform**:
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
```

**Compiler**:
`gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)` (Installed via SCL devtoolset-7)

**Comment by alexmarkley** [comment]
Apparently the issue is with cmake `3.11.2`. The latest version of cmake `3.12.2` fixes this problem.

**Comment by davisking** [comment]
Thanks for pointing this out.  I pushed some changes to dlib's cmake scripts that should work around this bug in cmake.

**Comment by ferrouswheel** [comment]
Same issue with building the `examples/` directory. However it was probably time to upgrade my cmake so I went for that option.
