### ISSUE TITLE
Warning when compiling dlib with nuwen MinGW GCC 8.1.0

### ISSUE THREAD

**Issue by Raincode** [davisking/dlib#1491]
## Expected Behavior
Dlib compiles without warnings / silences warnings which can safely be ignored.

## Current Behavior
I get the following warning and don't know whether it might be a problem or is normal:
```
dlib\dlib\matrix/matrix_la.h:225:32: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
             y = abs(q(i)) + abs(e(i));
                             ~~~^~~~~~
dlib\dlib\matrix/matrix_la.h:163:20: note: within this loop
         for (i=0; i<n; i++)
                   ~^~
```

## Steps to Reproduce
I used the following Batch script to compile:
```
@echo off
cd dlib
if not exist "build-mingw" mkdir build-mingw
cd build-mingw
cmake .. -G"MinGW Makefiles" ^
	  -DUSE_AVX_INSTRUCTIONS=1 ^
	  -DCMAKE_INSTALL_PREFIX:PATH="..."

cmake --build . --config Release -j
cmake --build . --target install
```

* **Version**: Dlib-master,  I believe it is Version 19.15.99
* **Where did you get dlib**: github (2018-09-24)
* **Platform**: Windows 10 64bit
* **Compiler**: nuwen MinGW distro 16.0 (GCC 8.1.0)

**Comment by davisking** [comment]
I think this is a bug in mingw.
