### ISSUE TITLE
Compatibiliy with OpenCV 4.0-alpha

### ISSUE THREAD

**Issue by ayounes-nviso** [davisking/dlib#1492]
## Expected Behavior
Compile with OpenCV 4 headers.

## Current Behavior
Compilation error in cv_image.hpp

## Steps to Reproduce
just compile with latest OpenCV develop branch.

## FIX

Define CV__DISABLE_C_API_CTORS and apply this patch:

``` diff
--- a/dlib/opencv/cv_image.h
+++ b/dlib/opencv/cv_image.h
@@ -34,7 +34,8 @@ namespace dlib
                          << "\n\t img.channels(): " << img.channels() 
                          << "\n\t img.pixel_traits<pixel_type>::num: " << pixel_traits<pixel_type>::num 
                          );
-            IplImage temp = img;
+            IplImage temp;
+            temp = cvIplImage(img);
             init(&temp);
         }
 ```

* **Version**: latest master: 8234080bbbe01e764091d9b6eae2615311cd6462
* **Where did you get dlib**: github repo
* **Platform**: linux ubuntu
* **Compiler**: gcc 7.2

**Comment by davisking** [comment]
Thanks for reporting this. Can you submit it as a pull request?

**Comment by ayounes-nviso** [comment]
#1494
