### ISSUE TITLE
extracting face_descriptor slower than detection (ARM)

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1493]
Hi,

a quick question;
i am using raspi3B+ 
```

face deteciton (frontal_face..)                          = 210 msec 
matrix<float,0,1> temp_ID = anet(face_chip);             = 3245 ms (3 seconds)

```

is this normal ?

I assumed that detection always the slowest part ?

or I am missing something?

**Comment by MyraBaba** [comment]
with neon and march-native optimization new numbers:

> face deteciton (frontal_face..)                                  = 280 msec 
matrix<float,0,1> temp_ID = anet(face_chip);             = 248 ms 

shouldnt anet(chip) more faster ?  any idea?

**Comment by MiXaiLL76** [comment]
dlib has the worst support and issues.

How many I see the given problems and questions, and the solution is one "ignore from the developers."

Help us with arm and multithreading at last.

**Comment by Bhanuchander210** [comment]
Landed here...! Any one found solution ? Please share.
