### ISSUE TITLE
Gap Statistic Implementation for K-means algorithm

### ISSUE THREAD

**Issue by MFaisalZaki** [davisking/dlib#1495]
Is it possible to integrate gap statistic method for locating the optimal number of clusters for a given data set in dlib.

Also is it possible to include k-means extension like k-means++ and x-means.

Best regards

**Comment by davisking** [comment]
Yeah, you could definitely implement that and add it to dlib :)

Also, dlib.net/ml.html#pick_initial_centers is basically kmeans++.
