### ISSUE TITLE
How to remove/uninstall dlib completely from Ubuntu

### ISSUE THREAD

**Issue by ammar-khan** [davisking/dlib#1500]
Hi,
I successfully installed dlib on Raspberry Pi 3 Model B+ (Raspbian Stretch Lite).

I could not found any help how to remove dlib and extra modules completely? 

Any help and guide will be appreciated.

Thanks

Ammar

**Comment by sandsmark** [comment]
If you've installed it manually with cmake and make install, there's a file in the build folder called install_manifest.txt. just delete all the files listed in that file, and it's uninstalled.

**Comment by ammar-khan** [comment]
Thanks
