### ISSUE TITLE
global_function_search video doesn't play correctly

### ISSUE THREAD

**Issue by MaxBareiss** [davisking/dlib#1508]
The video for the `global_function_search` object doesn't work correctly:

http://dlib.net/optimization.html#global_function_search

The video is corrupted and unviewable in Chrome and Firefox on Windows 10 x64.

**Comment by davisking** [comment]
What video?

**Comment by davisking** [comment]
Huh.  All the browsers I have access too, including chrome, play the videos
correctly.

**Comment by MaxBareiss** [comment]
Hmm... This works correctly on my home computer, but not on my work computer. I guess this issue isn't related to the video itself.
