### ISSUE TITLE
alternative ways of marking face bounding box when detectors don't detect it.

### ISSUE THREAD

**Issue by RubenBenBen** [davisking/dlib#1509]
Hi, I'm making a custom dataset to train a new model of face landmarks with custom images, and on some images both ```shape_predictor_68_face_landmarks``` and ```shape_predictor_5_face_landmarks.dat``` fail to detect the face at all, and from the docs I know that in order for the model to work better, the bounding box should be detected with the same logic as within the dlib's HOG face detectors. I didn't try it with CNN model, as I guess it will work worse if the box is detected like that, so I'm considering other ways to get the bounding box. I've seen your comment on ```shape_predictor_68_face_landmarks``` i-bug dataset, where you state:
```"For the faces the detector failed to detect, we guessed at what the bounding box would have been had the detector found it and used that."```
So should I really use that method and manually "guess" the box? And what else should I consider when guessing besides that the box should be square and be centered to the face?

I'm attaching a couple of example images where it fails to detect the face, which is strange as the images aren't that different from the ones the models are trained with.
![hf1rgbgv](https://user-images.githubusercontent.com/11850666/46354139-95fab700-c666-11e8-997d-126ef2a02aa0.jpg)
![bwksbkdd](https://user-images.githubusercontent.com/11850666/46354145-9abf6b00-c666-11e8-81d2-117025903b1a.jpg)

**Comment by davisking** [comment]
On Tue, Oct 2, 2018 at 10:14 AM RubenBenBen <notifications@github.com>
wrote:

> Hi, I'm making a custom dataset to train a new model of face landmarks
> with custom images, and on some the images both
> shape_predictor_68_face_landmarks and shape_predictor_5_face_landmarks.dat
> fail to detect the face at all,
>
These things don't detect faces.  They find landmarks.  They are unrelated
to detecting faces.

> and from the docs I know that in order for the model to work better, the
> bounding box should be detected with the same logic as within the dlib's
> HOG face detectors.
>
This isn't right.  Read the notes about each model:
https://github.com/davisking/dlib-models.  You can use the CNN model just
fine with the 5 point model.

> I didn't try it with CNN model, as I guess it will work worse if the box
> is detected like that, so I'm considering other ways to get the bounding
> box. I've seen your comment on shape_predictor_68_face_landmarks i-bug
> dataset, where you state:
> "For the faces the detector failed to detect, we guessed at what the
> bounding box would have been had the detector found it and used that."
> So should I really use that method and manually "guess" the box? And what
> else should I consider when guessing besides that the box should be square
> and be centered to the face?
>
For dataset annotation you can manually draw boxes the detector failed to
find.  That's just fine, so long as you make an effort to draw the box in
the same way the detector would.  So if the detector centers boxes on the
nose then so should you.  Or if it centers them on the eyes then so should
you.  If it's tall and thin vs square then do it like that.  Just be
consistent. That's what is important.


>

**Comment by RubenBenBen** [comment]
@davisking thanks. I know that CNN works for 5 points, I just want the 68 one.
