### ISSUE TITLE
Compile example error

### ISSUE THREAD

**Issue by AndreWicked** [davisking/dlib#1512]
* **Version**: 19.16
* **Where did you get dlib**:  dlib.net
* **Platform**:  Windows 10 x64
* **Compiler**:  Microsoft Visual Studio 2015

Hi, Davis! First I want to thank for this wonderful library! I'm worked with her for a long time in python, but decided to start with C++, compiled, everything is fine, I run any example and get the following error:

Error LNK2001 Unresolved external character "USER_ERROR__inconsistent_build_configuration__see_dlib_faq_2"

Error LNK1120 Unresolved External Elements: 1

What is the problem?

**Comment by AndreWicked** [comment]
I downloaded version 19.7, it all worked, why did the new versions display such an error?

**Comment by davisking** [comment]
http://dlib.net/faq.html#WhydoIgetUSERERRORinconsistentbuildconfigurationseedlibfaq2
