### ISSUE TITLE
fhog and horizontal lines seems to have problems

### ISSUE THREAD

**Issue by edubois** [davisking/dlib#1515]
I'm trying to compute local hogs on very small images, where cell size = 5 and image size is {15,15}.

# Expected Behavior
I'm expecting the draw_fhog to show horizontal lines as my image only contains horizontal lines, right now I get a small shift.

## Current Behavior
Right now I get a small shift on the output (see screenshot).
On the vertical lines, it's working. When kVert = 1.0f, I get horizontal lines as an output of draw_fhog.

## Steps to Reproduce
generate an image using:
```
constexpr float kVert = 0.0f;
            for (long r = 0; r < h; ++r) {
                for (long c = 0; c < w; ++c) {
                    img[c][r] =
                        255.0f*std::abs(std::cos(kVert * 8 * r / float(h) +
                                          (1.0-kVert) * 8 * c / float(w)));
                }
            }
```
Then, given w = 15 + 2x5, and h =15 + 2x5
```
    dlib::array2d<dlib::matrix<float, 31, 1>> hogs;

    dlib::extract_fhog_features(tile_imgs, hogs, 1);

    dlib::image_window win(tile_imgs);
    dlib::image_window winhog(dlib::draw_fhog(hogs));
    unsigned long key;
    bool is_printable;
    unsigned long state;
    win.get_next_keypress(key, is_printable, state);
```

* **Version**: current
* **Where did you get dlib**: github repo
* **Platform**: all
* **Compiler**: all
<img width="346" alt="example_bug" src="https://user-images.githubusercontent.com/214761/46563245-fc314500-c8c5-11e8-91b5-34bba1a351c6.png">

**Comment by davisking** [comment]
This is just how it works. Nothing is wrong.
