### ISSUE TITLE
how to train a model like 'dlib_face_recognition_resnet_model_v1.dat.bz2'

### ISSUE THREAD

**Issue by SSTTTAY** [davisking/dlib#1522]
I wanna train a new model to face recognition on a Asian dataset named glint, because now the model is not suitable for Asian. Besides, I am not familiar with c++ , how can I do that?

**Comment by davisking** [comment]
There are complete and detailed instructions in the example program, which is linked to from many parts of the documentation.  http://dlib.net/dnn_face_recognition_ex.cpp.html
