### ISSUE TITLE
Returning Negative values for bounding boxes in Dlib Face Detector

### ISSUE THREAD

**Issue by avinsit123** [davisking/dlib#1526]
I was using Dlib to perform facial recognition on a photo.Specifically the one given below 
![index_face](https://user-images.githubusercontent.com/33565881/47422423-380e4a80-d7a0-11e8-8f64-db510854380c.jpg)

## Expected Behavior
As the face is cropped out a little bit,the bounding box coordinates for the upper-left y position should be 0 for the above image.

## Current Behavior
However,dlib's face detector returned negative values for the bounding box of the above image.As Dlib's face detector returns a drectangle object it becomes very difficult for using this object in further analysis if it contains negative values. 

## Steps to Reproduce
Run the face detector on the above Image or any other image with a cropped face.
```python
detect=dlib.get_frontal_face_detector()
#Convert colour image to black and white
rects=detect(image,1)
```
Certain Value of rects comes out to be negative.

* **Version**: 19.15.0
* **Where did you get dlib**: Pypi

**Comment by davisking** [comment]
Thanks for the bug report. However, this is how it’s supposed to work, not a bug.
