### ISSUE TITLE
Installed MKL - no improvement in face detection

### ISSUE THREAD

**Issue by sergei-sh** [davisking/dlib#1528]
I've installed MKL, recompiled DLIB and see almost no time difference in face detection.
Ensured importing the correct module.
MKL was found during compilation, no errors there.
I use get_frontal_face_detector from Python and run 64 consecutive detections on the same images.

Using the latest dlib under CentOs 7.5. I also compile with CUDA at the same time.

**Comment by sergei-sh** [comment]
I've installed MKL, recompiled DLIB and see no improvement in face detection.
Ensured importing the correct module.
MKL was found during compilation, no errors there.
I use get_frontal_face_detector from Python under CentOs and run 64 consecutive detections on the same images.
Is that expected? HOG face detection doesn't use linear algebra libraries?
(Also using CUDA, but this shouldn't affect)

**Comment by davisking** [comment]
Hog doesn’t use these so this is expected. Turn on avx or neon instructions instead.

**Comment by sergei-sh** [comment]
Hi, thanks for the answer. But I'm still confused. You use BLAS in matrix.h and matrix is used in scan_fhog_pyramid. To me this means the HOG detector should benefit from MKL. Am I wrong?

**Comment by davisking** [comment]
Yes, you are wrong.

**Comment by sergei-sh** [comment]
But I clearly see my Dlib is linked against MKL libraries which contain BLAS functions which are being used by matrix class. 

Could you help with any hint to understand which parts of Dlib do utilize this functionality?

**Comment by davisking** [comment]
Just look at the fhog extraction code. You can see what it does. That goes for anything else, look and see what it does.

**Comment by xsacha** [comment]
Is there much benefit for MKL if you are using CUDNN?

**Comment by davisking** [comment]
The hog based detectors don’t use mkl or cudnn. So it doesn’t matter either way.

**Comment by xsacha** [comment]
What about if we use DNN face detector? With CUDNN, would MKL have any benefit?

**Comment by davisking** [comment]
If you are using the DNN tooling the network is running either all on the GPU or all on the CPU.  So installing a CPU acceleration library like the MKL will do nothing if you are already using cudnn.

**Comment by davisking** [comment]
I don't think we are talking about the same thing.  The `shape_predictor` runs in about a millisecond on a normal computer.

**Comment by xsacha** [comment]
It does add up on my machine. Consider the scenario where you have 10 HD cameras and up to a dozen faces per camera.
The CUDNN keeps up fine but the CPU begins to be used up.

**Comment by davisking** [comment]
Yeah that’s a lot. Can’t you run multiple shape models on multiple cpu cores?

**Comment by xsacha** [comment]
It's over multiple cores already but with database and everything else, it adds up.
Was just wondering if it uses MKL. If not, I guess I can remove it.
