### ISSUE TITLE
Unable to build dlib on google colaboratory

### ISSUE THREAD

**Issue by ramkrish0403** [davisking/dlib#1529]
## Expected Behavior
I am trying to install dlib on google colaboratory(Ubuntu-18.04), but it's throwing an error.

## Current Behavior
I got the following report after the command : !cmake .. -DCMAKE_PREFIX_PATH=/content/cuda
Note: /content/cuda contains extracted cudnn files.

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMake version: 3.12.3
-- Compiling dlib version: 19.16.99
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   Found lapack, version 0.2.20+ds
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - found
-- Using OpenBLAS's built in LAPACK
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - not found
-- Looking for sgesv_
-- Looking for sgesv_ - not found
-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /content/cuda/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /content/dlib/dlib
CUDA_curand_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /content/dlib/dlib
cusolver (ADVANCED)
    linked by target "dlib" in directory /content/dlib/dlib

-- Configuring incomplete, errors occurred!
See also "/content/dlib/build/CMakeFiles/CMakeOutput.log".
See also "/content/dlib/build/CMakeFiles/CMakeError.log".

Comment: I don't understand why these libraries are set to 'NOTFOUND' or where to find them or how to set them. I have tried googling but to no avail.

## Steps to Reproduce

Step 1: Open google colaboratory with python 3 and gpu enabled.
Step 2: Download and extract 'cudnn-9.2-linux-x64-v7.3.1.20.tgz' to /content folder. Google colab is already setup with nvidia driver 396.44 and cuda 9.2. You will need to download the file from developer.nvidia.com.

%cd /content
!tar -xzvf cudnn-9.2-linux-x64-v7.3.1.20.tgz

Step 3: Install sudo.

!apt install sudo
!sudo apt-get update
!sudo apt-get upgrade
!sudo apt update
!sudo apt upgrade

Step 4:Remove the existing version and then Install latest version of cmake

%cd /content
!sudo apt remove cmake
!sudo apt purge --auto-remove cmake
!mkdir ~/temp
%cd ~/temp
!wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
!sudo mkdir /opt/cmake
!sudo sh cmake-3.12.3-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
!sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
!cmake --version

Step 5: Install a bunch of other libraries

%cd /content
!sudo apt-get install libopenblas-dev liblapack-dev 
!sudo apt-get install libx11-dev libgtk-3-dev
!sudo apt-get install libboost-all-dev

Step 6: Install dlib

%cd /content
!git clone https://github.com/davisking/dlib.git
%cd dlib
!mkdir build
%cd build
!cmake .. -DCMAKE_PREFIX_PATH=/content/cuda

Note that the above prefix path contains cudnn.

Steps to be continued, if it didn't throw the error: (please correct me, if these are wrong instructions to follow).
!cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
!cmake --build .
%cd ..
!python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

* **dlib version**:  
19.16.99

* **Where did you get dlib**:    
https://github.com/davisking/dlib.git

* **Platform**: 
!lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

* **Compiler**: 

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0

Log reports: Please ask if "CMakeOutput.log" or "CMakeError.log" are needed.

**Comment by davisking** [comment]
The error says cublas and curand aren't installed.  They are part of the
CUDA tools install package from nvidia.  This suggests that cuda isn't
properly or completely installed.  Check if they are really installed and
if not follow the instructions from NVIDIA to fully install CUDA.

**Comment by mujahid7292** [comment]
Did you solve the problem?

**Comment by ramkrish0403** [comment]
Google Colab now comes with dlib properly pre-installed with GPU support. We just need to import dlib.
