### ISSUE TITLE
shape landmark jittering on a camera with same image

### ISSUE THREAD

**Issue by RubenBenBen** [davisking/dlib#1530]
When testing 68 face landmarks model on a live camera, it has a slight jittering on all landmarks, even when the face image doesn't move at all. I'm looking for a way to reduce them as much as possible, but not sure where to look for the problem. I have some guesses, but not sure. I checked the bounding boxes for different frames and the face box detector outputs the same box coordinates, so it has to do with shape predictor itself. Maybe different seeds are being set to select random pixels at each frame, so the landmarks appear little different on the same image? I assume it should be something related to using randomness to get different results on the same image with same box.

**Comment by davisking** [comment]
There is no randomness in the shape predictor in dlib.  This is caused by
pixel noise in your images.  They are all a little bit different.  You
could use something like this to filter the points over time to make them
less jittery: http://dlib.net/algorithms.html#momentum_filter

**Comment by RubenBenBen** [comment]
I've tried it but no success so far. Is there a way for dlib to know when the particular parts of the shape are not "visible"? meaning for example if there is too much/low light on an eye, or when a person wears sunglasses, so his eyes and brows are not visible, dlib puts a mean shape on those parts.
