### ISSUE TITLE
Linking TBB to DLIB

### ISSUE THREAD

**Issue by r4ghu** [davisking/dlib#1532]
Hi! I am not an expert in CMake and Build systems. I am currently trying to test the performance of DLIB's face detection with/without TBB. My initial code has taken inspiration from the following file [`scan_fhog_pyramid.h`](https://github.com/TadasBaltrusaitis/CLM-framework/blob/master/lib/3rdParty/dlib/include/dlib/image_processing/scan_fhog_pyramid.h). Now, the tricky part is linking TBB with the program. I added TBB to the external directory and added the following lines of code into `dlib/dlib/CMakeLists.txt` file. 
```cmake
# TBB support
# Try to find TBB
include_directories(external/tbb/include)
set(dlib_needed_libraries ${dlib_needed_libraries} external/tbb/lib/tbb.dll)
set(REQUIRES_LIBS " tbb")
```

I was roughly testing and I might not be doing it right. Please comment if this is wrong.

Now, I build the examples of dlib and the first phase of building dlib is going fine. The second phase of building project `face_detection_ex` is getting the following error initially. 

Project: face_detection_ex
File: scan_fhog_pyramid.h
Line: 13
```shell
C1083: Cannot open include file: 'tbb/tbb.h': No such file or directory
```
With simple tweaking of Project properties of `face_detection_ex` inside Visual Studio, I included the directory to TBB include files into my current project. I am able to suppress the error I mentioned but now I am getting the strange error related to TBB support with Windows version

```shell
1>------ Build started: Project: face_detection_ex, Configuration: Release x64 ------
1>face_detection_ex.cpp
1>c:\users\srira\dlib\dlib\external\tbb\include\tbb\internal\_tbb_windef.h(28): fatal error C1189: #error:  TBB is unable to run on old Windows versions; _WIN32_WINNT must be 0x0501 or greater.
1>Done building project "face_detection_ex.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```
This doesn't make sense to me because I am using Windows 10 OS and the 0x0501 represents Windows XP. I am pretty sure I might be doing something wrong with respect to building the program. I tried testing integrating TBB (not with dlib) into a different file and everything works fine without errors. I am getting error only here.

**Comment by xbukovcikova** [comment]
Hello,
I have ran into similar problem when trying to build dlib with cpprestsdk. The problem for me was in 

> dlib\windows_magic.h

on lines:
```#if _WIN32_WINNT < 0x0500  \
#undef _WIN32_WINNT  
#define _WIN32_WINNT 0x0500  
#endif
```
After I commented out those lines, I was able to build and I haven't ran into an issue yet ... However, similarly to you I am using Windows 10 so I have no idea why those  lines were even executed.

**Comment by r4ghu** [comment]
Thank you @xbukovcikova ! It works now 👍  After a bit of research online, I figured that version 0x0500 refers to Windows Vista and TBB only supports from Windows XP (0x05001) and above. Also by changing the above code to this will also work. 

```
#if _WIN32_WINNT < 0x0500 
#undef _WIN32_WINNT  
#define _WIN32_WINNT 0x0501
#endif
```
