### ISSUE TITLE
Detector region proposal

### ISSUE THREAD

**Issue by BraginIvan** [davisking/dlib#1542]
What type of region proposal is used for simple_object_detector?
As I see in comments *This object represents a sliding window histogram-of-oriented-gradients based object detector.*  Also I see function http://dlib.net/dlib/image_transforms/segment_image_abstract.h.html#find_candidate_object_locations
Basing on the fact that we need upsample image to detect small objects I think it uses sliding window, but isn't it better to use selective search and filter regions whose aspect ratio is very different from train bounding boxes?

**Comment by davisking** [comment]
It's just a sliding window.  No, selective search would not be better. It
would definitely be worse.
