### ISSUE TITLE
dnn_mmod_ex out of memory

### ISSUE THREAD

**Issue by artemSSSS** [davisking/dlib#1546]
Hello.
I run dnn_mmod_ex with examples\faces. 
And I got this error.

num training images: 4
num testing images:  5
num detector windows: 1
detector window width by height: 40 x 40
overlap NMS IOU thresh:             0.170353
overlap NMS percent covered thresh: 0.33141
step#: 0     learning rate: 0.1   average loss: 0            steps without apparent progress: 0
Error while calling cudaMallocHost(&data, new_size*sizeof(float)) in file D:\dlib-19.16\dlib-19.16\dlib\cuda\gpu_data.cpp:185. code: 2, reason: out of memory

I have GeForce GTX 1080 8Gb.

**Comment by davisking** [comment]
Use smaller images.

**Comment by artemSSSS** [comment]
I did this. But same result.
And examples\faces is test thing.
Why 8Gb card memory is not enough?

**Comment by davisking** [comment]
Look at the code, it upsamples the image.  Comment that out.

**Comment by davisking** [comment]
Oops, wrong example.  That one doesn't upsample the images.  But still, load fewer images.  Make the batch size smaller, make the image crops smaller.  Think about it.  If you run out of RAM use less RAM by making things smaller.

8GB is not a lot.
