### ISSUE TITLE
Feature: MKL ML support

### ISSUE THREAD

**Issue by xsacha** [davisking/dlib#1550]
Currently dlib works with Intel MKL. I am under the impression Intel MKLML should work, other than it being named differently (mklml.dll).
Is this a correct assumption and if so, would it be worthwhile adding it?

I am mainly interested in it as it is a trimmed down version of Intel MKL (Designed for machine learning purposes), so it should come with a significant file size benefit.

**Comment by davisking** [comment]
I haven’t used it so I’m not sure. But if it works then sure.

**Comment by xsacha** [comment]
Just to note that I did attempt this but, for my purposes, it had a negative impact on performance. This is because MKL ML does not include the LAPACK features that are used by dlib.
