### ISSUE TITLE
RBF for object detection 

### ISSUE THREAD

**Issue by TARUSHREE** [davisking/dlib#1551]
How can I use RBF kernel for object detection using train_object_detector (that uses MMOD), instead of the linear kernel being used?

**Comment by davisking** [comment]
You can’t. And it’s not something that would work well anyway.

**Comment by TARUSHREE** [comment]
Thanks! Could you plz explain why RBF won't work well? I am looking to use RBF for object detection.

**Comment by davisking** [comment]
It doesn't make sense for HOG features.  They are designed to work well with a linear detector.  RBF is just never going to work well with them. Think about what the RBF kernel is doing, it's tiling the space with balls, and it takes a whole lot of balls to tile a space that's like 3000 dimension. 

If you want to learn some more complex model then use a CNN.

**Comment by TARUSHREE** [comment]
Okay, thanks for help.
