### ISSUE TITLE
aggressive-loop-optimizations error

### ISSUE THREAD

**Issue by joelgallant** [davisking/dlib#1554]
Fair warning, this looks the same as #1491, but I can repro on g++ 8.2.

## Expected Behavior
It would be great if dlib compiled without any compiler warnings (`-Werror`).

## Current Behavior
With g++ 8.2, I get

```
dlib/dlib/filtering/../matrix/matrix_la.h:225:32: error: iteration 1 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
             y = abs(q(i)) + abs(e(i));
                             ~~~^~~~~~
dlib/dlib/filtering/../matrix/matrix_la.h:163:20: note: within this loop
         for (i=0; i<n; i++)
                   ~^~
```

## Steps to Reproduce
Temporarily adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=aggressive-loop-optimizations")` to cmake will trigger this on a x86 build.

---

I would quite like to fix this myself, but on the first glance that part of the code is pretty tough to follow. It seems to be the `e()` that causes the error. A tiny bit of guidance and I can probably do this myself.

**Comment by davisking** [comment]
I have no idea.  This really seems like a compiler error since e is just an
array of n numbers, and that loop obviously doesn't go outside the bounds
of e.
