### ISSUE TITLE
[Question] Defining serialize() overloads for custom types

### ISSUE THREAD

**Issue by anaru** [davisking/dlib#1558]
Hi there, I am looking to use DLib's serialization to write a vector<cv::Point2d> to a file. I was able to achieve this by writing a function that looks like this:

```C++
namespace dlib {

void serialize(const cv::Point2d& p, std::ostream& stream);

}
```

And then calling dlib::serialize on the vector-of-points. I found that the new function had to be declared inside the dlib namespace in order to compile, but it feels a bit funny to be adding my own functions to the dlib namespace. So my question is, is the serialization intended to support this kind of extension to non-dlib types, and if so, is this the "right" way to do it?

(Note: I know this is a fairly simple case, but I'm interested in using this approach for other non-dlib nested types in future as well)

Many thanks.

**Comment by davisking** [comment]
You should put serialize functions inside the namespace of the object on which they operate, this will allow C++'s argument dependent lookup to find them.  So in this case, put it in the `cv` namespace.

**Comment by anaru** [comment]
I've tried your suggestion and it works. Thanks for the help; I wasn't really familiar with the mechanism of argument-dependent lookup.

**Comment by davisking** [comment]
No problem :)
