### ISSUE TITLE
Fatal error :visual studio is not supported 

### ISSUE THREAD

**Issue by nayanmiglani** [davisking/dlib#1560]
c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error: -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!

**Comment by xsacha** [comment]
CUDA 10.0 works on all visual studio versions.

Prior to this, it is selective on the minor version of Visual Studio 2017 you are using.
Your options with CUDA 9.0 are:
1) Use CUDA_HOST_COMPILER= (path to visual studio 2015 cl.exe)
2) Use an older Visual Studio 2017
