### ISSUE TITLE
Trained sp.dat wrong landmark detection

### ISSUE THREAD

**Issue by PhilippeSteinbach** [davisking/dlib#1563]
Hi,
I tried to train my own sp.dat using train_shape_predictor_ex with a sample set of 25 images.

Here you can see one of the images and how I tagged it:

<img width="718" alt="bildschirmfoto 2018-11-23 um 11 19 03" src="https://user-images.githubusercontent.com/16945319/48938591-f6dd9780-ef11-11e8-86cf-ee0ebc38db78.png">

And this is the output of face_landmark_detection_ex using my sp.dat:

<img width="707" alt="bildschirmfoto 2018-11-23 um 11 08 29" src="https://user-images.githubusercontent.com/16945319/48938333-35bf1d80-ef11-11e8-936b-8aa0a7d9cffa.png">

Seems like the face is not being detected properly and edges are not properly connected.
When I use the /examples/faces set, everything looks ok.
Am I missing something?

The example set of images is way smaller but seems to work pretty good im comparison to my own set.

**Comment by davisking** [comment]
You didn't use the same labels.

**Comment by PhilippeSteinbach** [comment]
Indeed my labels were name='0' instead of name='00'. Changed it and now everything looks ok.

If I want to detect a face using less landmarks (i.e. 30 instead of 68), what do I need to do?
Will it be enough to just use 30 labels per image?

I was just thinking of render_face_detections.h when I had a look at it.

`// Around Chin. Ear to Ear
                for (unsigned long i = 1; i <= 16; ++i)
                    lines.push_back(image_window::overlay_line(d.part(i), d.part(i-1), color));`

**Comment by davisking** [comment]
You can use whatever landmarks you want.

**Comment by oladayosolomon** [comment]
> Thank you! Indeed my labels were name='0' instead of name='00'. Changed it and now everything looks ok.
> 
> If I want to detect a face using less landmarks (i.e. 30 instead of 68), what do I need to do?
> Will it be enough to just use 30 labels per image?
> 
> I was just thinking of render_face_detections.h when I had a look at it.
> 
> `// Around Chin. Ear to Ear for (unsigned long i = 1; i <= 16; ++i) lines.push_back(image_window::overlay_line(d.part(i), d.part(i-1), color));`

PhilippeSteinbach::: pls am about to do same thing you just did. pls could you explain to me how you labeled your images and whats the size of the bounding box for each faces you used. thanks

**Comment by PhilippeSteinbach** [comment]
@oladayosolomon 
I labelled the images with http://imglab.ml but you can also use the version which is included in dlib/tools/imglab.
I did not pay attention to the size of the boxes, but in the example the boxes have the same height and width. Not sure if this is necessary.

**Comment by oladayosolomon** [comment]
> @oladayosolomon
> I labelled the images with http://imglab.ml but you can also use the version which is included in dlib/tools/imglab.
> I did not pay attention to the size of the boxes, but in the example the boxes have the same height and width. Not sure if this is necessary.

Thanks for your reply: am also using the imglab on http://imglab.ml. pls i also like to know for the facial landmarks after drawing the box and you have slected the pionts did you label the pionts or just used the numbering that were alocated to each pionts.

thanks

**Comment by PhilippeSteinbach** [comment]
I drawed boxes and all points. [Then these changes](https://github.com/davisking/dlib/issues/1563#issuecomment-441292618)
