### ISSUE TITLE
Dlib optimization for CPU and GPU

### ISSUE THREAD

**Issue by mark17prog** [davisking/dlib#1564]
Hi! Dlib is cool library. And I would like ask tip for optimize.
I used example http://dlib.net/dnn_face_recognition_ex.cpp.html and I read that you wrote https://github.com/davisking/dlib/issues/1421 that some functions don't support CUDA.

	
	int extract(...) {

		...
                for (auto & pr : fs::directory_iterator(path)) {

			...
			
			load_image(img, p);
		
			for (auto face : detector(img)) {
				auto shape = sp(img, face);
				matrix<rgb_pixel> face_chip;
				extract_image_chip(img, get_face_chip_details(shape, 150, 0.25), face_chip);
				faces.push_back(move(face_chip));

			}
			
			...
		
			face_descriptors = net(faces);
		
		}
		
		...
		
	}
	
	int main () {
		
		int threads_count = 100;
		
		frontal_face_detector detector = get_frontal_face_detector();	
		shape_predictor sp;
		anet_type net;
		
		deserialize(disk + ":\\FindP\\lib\\shape_predictor_68_face_landmarks.dat") >> sp;
		deserialize(disk + ":\\FindP\\lib\\dlib_face_recognition_resnet_model_v1.dat") >> net;
		
		for (int i = 0; i < threads_count; i++) {
			
			thread_array[i] = thread(extract, ... detector, sp, net);			
			
		}
		
		for (int i = 0; i < threads_count; i++) {
			thread_array[i].join();
		}
		
	}
	

How I undestand here only "net(faces)" uses CUDA. Other - CPU. What can you recommend me for optimize my program? For united power CPU and GPU.
May be I need change my thread function? Or change algorithm load image?

I use dlib-19.15

**Comment by xsacha** [comment]
The shape predictor uses CPU, the net uses GPU.
You can have a separate thread to process the images and insert faces in to a queue and then another thread to process the queue through facial recognition.

**Comment by gty3310** [comment]
> Detector uses GPU, the shape predictor uses CPU, the net uses GPU. You can have a separate thread to process the images and insert faces in to a queue and then another thread to process the queue through facial recognition.

May I ask how/where could you tell shape_predictor is using CPU?

**Comment by xsacha** [comment]
The shape predictor doesn't use the same deep learning methods for the regression tree, so there's no GPU acceleration. It's likely inefficient to put it on the GPU anyway. It's essentially a post-process on the detector.
