### ISSUE TITLE
how to use arithmetic coding

### ISSUE THREAD

**Issue by navid-mahmoudian** [davisking/dlib#1565]
I am interested to use arithmetic coding using entropy_encoder_kernel_1 and entropy_decoder_kernel_1, but I couldn't find any example of how to use these classes. Although Dlib is documented pretty well, it seems that there is a distinct lack of documentation for this part. The 2 examples which are given (compress_stream_ex.cpp and file_to_code_ex.cpp) is not related to arithmetic coding classes. Is there any possibility to have some examples for arithmetic coding?

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whereisthedocumentationforobjectfunction

**Comment by navid-mahmoudian** [comment]
Thank you very much for your response. I read this part and still it is not clear for me how to encode a sequence of short integer values using this function. Imaging I have a vector of short integers and I want to encode them with this function. How can I do that?

**Comment by davisking** [comment]
You just call the `.encode()` method for each element.

**Comment by navid-mahmoudian** [comment]
Thanks again for your answer. I have 2 questions:
1- The encode function arguments are "uint32 low_count,  uint32 high_count, uint32 total" which I think these values are related to low and high values of the interval in arithmetic coding. How should I feed each element to this function?
2- From the documentation, I noticed that there is a constraint that 0 < total <  65536 (2^16). Does it mean that the algorithm accepts 65535 alphabets (1 less than the size of the alphabet for short integers)? In other words, does it mean that I can not use it for short integer values because I will lose one of my symbols?
