### ISSUE TITLE
Cannot run example of face_landmark_detection.py on Windows 10

### ISSUE THREAD

**Issue by sekti92** [davisking/dlib#1566]
Hello how to run example of **_face_landmark_detection.py_** on windows?
I was trying to run on vscode using this command: **python .\face_landmark_detection.py .\shape_predictor_68_face_landmarks.dat .\test_21.jpg**

But the windows just force closed after I run the command and does not showing the landmark on my screen. Any idea what's wrong with the script?
I took the script from **https://github.com/davisking/dlib/blob/master/python_examples/face_landmark_detection.py**

**Comment by AlexXandreE** [comment]
Hi, is this still an issue? If yes, the error might be because you are passing a photo, not a directory.
Call like this: python .\face_landmark_detection.py .\shape_predictor_68_face_landmarks.dat .\

Hope this helps in any way

**Comment by sekti92** [comment]
I already fix the issue thanks for the help sir
