### ISSUE TITLE
dlib isn't multi-core

### ISSUE THREAD

**Issue by MiXaiLL76** [davisking/dlib#1567]
Hello, I opened the issue on OpenBlas, but I myself realized that without dlib, it uses multithreading.
https://github.com/xianyi/OpenBLAS/issues/1883
Here is the link, tell me how to enable multithreading in dlib?
I already did it, but I can’t repeat it.

**Comment by MiXaiLL76** [comment]
https://github.com/davisking/dlib/issues/557#issuecomment-298230416
I conducted tests and got this result. ~450.77 ms

In principle, the tests are good. but use only 1 core. is always. in any tests with dlib. in any of your examples

**Comment by MiXaiLL76** [comment]
### Code example
[test.zip](https://github.com/davisking/dlib/files/2614346/test.zip)

### test
![program](https://user-images.githubusercontent.com/31501945/48997010-67c5bf00-f15f-11e8-81e8-a6c3cb312e80.png)

### only 1 core, always
![htop](https://user-images.githubusercontent.com/31501945/48997023-7ca25280-f15f-11e8-9631-62596cde9958.png)

**Comment by MiXaiLL76** [comment]
Of course, I understand that all this is very difficult, and you do not have enough time for everyone, but please help me, where to dig?

**Comment by xsacha** [comment]
By default, dlib seems to use a single-core implementation cblas unless it finds your BLAS library.

Are you sure dlib finds and successfully uses your BLAS library?
Your BLAS library is OpenBLAS right?
If it does find your BLAS, then the problem you have is with this library (or its compilation settings).

**Comment by MiXaiLL76** [comment]
> Can you exclude the model deserialisation time from your profile? It's normal this takes a long time but this only needs to run once.

I load it 1 time, the rest of the time I process pictures at 200kb. and all 5-10 images are processed for 5 seconds and use 1 core.
