### ISSUE TITLE
Dlib linking problem on Android

### ISSUE THREAD

**Issue by alianse777** [davisking/dlib#1569]
I am trying to build latest dlib inside Android Studio.
When I compile my project, it actually includes BLAS from host system and throws lot of linking errors such as "undefined reference to 'cblas_saxpy'".
How can I tell dlib not to use host libraries and build without BLAS/LAPACK?
# Here is my CMakeLists.txt file:
cmake_minimum_required(VERSION 3.6.0)
set(DLIB_USE_BLAS 0)
set(DLIB_USE_LAPACK 0)
set(DLIB_NO_GUI_SUPPORT 1)
add_subdirectory(./dlib dlib_build)
add_library(native-lib SHARED src/main/cpp/native-lib.cpp)

target_link_libraries(
        native-lib
        dlib::dlib)
\# end
# Possible problem source in dlib/cmake_utils/find_blas.cmake:
\# try to find some other LAPACK libraries if we didn't find the MKL
   set(extra_paths
      /usr/lib64
      /usr/lib64/atlas-sse3
      /usr/lib64/atlas-sse2
      /usr/lib64/atlas
      /usr/lib
      /usr/lib/atlas-sse3
      /usr/lib/atlas-sse2
      /usr/lib/atlas
      /usr/lib/openblas-base
      /opt/OpenBLAS/lib
      $ENV{OPENBLAS_HOME}/lib
      )

**Comment by davisking** [comment]
Use cmake -D
