### ISSUE TITLE
failing to use CNN on RTX GPU + cuda10.0 + cudnn 7.4.1.5

### ISSUE THREAD

**Issue by rgrenonlkr** [davisking/dlib#1572]
## Expected Behavior
http://dlib.net/cnn_face_detector.py.html should works with either GTX GPU or RTX GPU

## Current Behavior
When launching example on RTX 2070 the face detector failed with this message
> Processing file: ../examples/faces/2007_007763.jpg
> Traceback (most recent call last):
>   File "cnn_face_detector_headless.py", line 58, in <module>
>     dets = cnn_face_detector(img, 1)
> RuntimeError: Error while calling cudnnConvolutionForward( context(), &alpha, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &beta, descriptor(output), output.device()) in file /tmp/pip-install-fkyl3w2d/dlib/dlib/cuda/cudnn_dlibapi.cpp:1007. code: 8, reason: CUDNN_STATUS_EXECUTION_FAILED

However when using another GTX 1050 on the same system the example is working as intended : 

> Processing file: ../examples/faces/2007_007763.jpg
> Number of faces detected: 7
> Detection 0: Left: 385 Top: 83 Right: 432 Bottom: 130 Confidence: 1.0736169815063477
> Detection 1: Left: 313 Top: 237 Right: 352 Bottom: 277 Confidence: 1.059773325920105
> Detection 2: Left: 293 Top: 85 Right: 332 Bottom: 125 Confidence: 1.0527307987213135
> Detection 3: Left: 193 Top: 89 Right: 232 Bottom: 129 Confidence: 1.038894534111023
> Detection 4: Left: 93 Top: 189 Right: 132 Bottom: 229 Confidence: 1.0129311084747314
> Detection 5: Left: 173 Top: 209 Right: 212 Bottom: 249 Confidence: 0.5883067846298218
> Detection 6: Left: 157 Top: 113 Right: 196 Bottom: 153 Confidence: 0.2902120351791382
> Hit enter to continue

## Steps to Reproduce
install cuda 10.0
install cuda 7.4.1.5
compile dlib (v19.16)
I modified the example to run headless (without dlib.image_window) and using dlib.cuda.set_device() to select GPU

Also, I had the same problem with cuda 9.1/cudnn7.1 and RTX also failed with https://github.com/AlexeyAB/darknet with the same error. I updated cuda/cudnn and now darknet is working fine with both cards)

* **Version**: 

```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> dlib.__version__
'19.16.0'
>>> dlib.DLIB_USE_CUDA
True
```

* **Where did you get dlib**: 
this repo

* **Platform**: 
Ubuntu 16.04.4 LTS

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0 Off |                  N/A |
| 39%   35C    P0     1W / 175W |      0MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 105...  Off  | 00000000:02:00.0 Off |                  N/A |
| 25%   29C    P0    N/A /  75W |      0MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

* **Compiler**: 
not sure about the information to provide in this field
I build dlib.so using "python3 setup.py install"
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130

**Comment by davisking** [comment]
Did you reinstall dlib after updating cuda and cudnn?

**Comment by rgrenonlkr** [comment]
Yes, building output : 

> -- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "7.5") 
> -- Looking for cuDNN install...
> -- Found cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
> -- Building a CUDA test project to see if your compiler is compatible with CUDA...
> -- Checking if you have the right version of cuDNN installed.
> -- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
> -- C++11 activated.
> -- Configuring done
> -- Generating done

**Comment by rgrenonlkr** [comment]
There may be a mismatch with my cudnn version.

Here is my output for cudnn samples. **Do you think that the first line have same version ?**

$/mnistCUDNN
> cudnnGetVersion() : 7102 , CUDNN_VERSION from cudnn.h : 7401 (7.4.1)
> Host compiler version : GCC 5.4.0
> There are 2 CUDA capable devices on your machine :
> device 0 : sms 36  Capabilities 7.5, SmClock 1620.0 Mhz, MemSize (Mb) 7951, MemClock 7001.0 Mhz, Ecc=0, boardGroupID=0
> device 1 : sms  6  Capabilities 6.1, SmClock 1392.0 Mhz, MemSize (Mb) 4040, MemClock 3504.0 Mhz, Ecc=0, boardGroupID=1
> Using device 0
> 
> Testing single precision
> Loading image data/one_28x28.pgm
> Performing forward propagation ...
> Testing cudnnGetConvolutionForwardAlgorithm ...
> Fastest algorithm is Algo 5
> Testing cudnnFindConvolutionForwardAlgorithm ...
> ^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.009600 time requiring 0 memory
> ^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.026720 time requiring 57600 memory
> ^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.038560 time requiring 3464 memory
> ^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.068288 time requiring 2057744 memory
> ^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.097408 time requiring 203008 memory
> Resulting weights from Softmax:
> 0.0000000 0.9999399 0.0000000 0.0000000 0.0000561 0.0000000 0.0000012 0.0000017 0.0000010 0.0000000 
> Loading image data/three_28x28.pgm
> Performing forward propagation ...
> Resulting weights from Softmax:
> 0.0000000 0.0000000 0.0000000 0.9999288 0.0000000 0.0000711 0.0000000 0.0000000 0.0000000 0.0000000 
> Loading image data/five_28x28.pgm
> Performing forward propagation ...
> Resulting weights from Softmax:
> 0.0000000 0.0000008 0.0000000 0.0000002 0.0000000 0.9999820 0.0000154 0.0000000 0.0000012 0.0000006 
> 
> Result of classification: 1 3 5
> 
> Test passed!
> 
> Testing half precision (math in single precision)
> CUDNN failure
> Error: CUDNN_STATUS_SUCCESS
> mnistCUDNN.cpp:331
> Aborting...

**Comment by rgrenonlkr** [comment]
I managed to solve my issue.

** root cause
there may have been a mess of library
there may have been a mess of cudnn version 

** fix
have a correct setup of cuda + cudnn
checks : 
nvccc -V => V10.0.130
cudnn test mnistCUDNN => passed both single and half precision, cudnn version should match .h : cudnnGetVersion() : 7401 , CUDNN_VERSION from cudnn.h : 7401 (7.4.1)
=> LD_LIBRARY_PATH contains cuda-10.0

** preventing hamster in the (python) wheel
After fixing my setup dlib compiling again did not solve my issue.
Until a I realized that repeating "sudo python3 setup.py clean; sudo python3 setup.py install" did not remove corrupted build in /usr/local/lib/python3.5/dist-packages

first make : 

> creating /usr/local/lib/python3.5/dist-packages/dlib-19.16.99-py3.5-linux-x86_64.egg
> Extracting dlib-19.16.99-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
> Adding dlib 19.16.99 to easy-install.pth file
> 
> Installed /usr/local/lib/python3.5/dist-packages/dlib-19.16.99-py3.5-linux-x86_64.egg
> Processing dependencies for dlib==19.16.99
> Finished processing dependencies for dlib==19.16.99

next make

> removing '/usr/local/lib/python3.5/dist-packages/dlib-19.16.99-py3.5-linux-x86_64.egg' (and everything under it)
> creating /usr/local/lib/python3.5/dist-packages/dlib-19.16.99-py3.5-linux-x86_64.egg
> Extracting dlib-19.16.99-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
> dlib 19.16.99 is already the active version in easy-install.pth
> 
> Installed /usr/local/lib/python3.5/dist-packages/dlib-19.16.99-py3.5-linux-x86_64.egg
> Processing dependencies for dlib==19.16.99
> Finished processing dependencies for dlib==19.16.99

removing the .egg is nice but it does not remove previous version because _dlib 19.16.99 is already the active version in easy-install.pth_

I'm not familiar with python and system setup in general but perhaps you should add an extra clean (?) with
sudo rm /usr/local/lib/python3.5/dist-packages/dlib* -rf

**Comment by davisking** [comment]
You can uninstall a package by saying `pip uninstall some_package`.  So say `pip uninstall dlib`.  Definitely don't go running `sudo rm`.
