### ISSUE TITLE
Support for specifying minimum face size for face detection to speed up performance

### ISSUE THREAD

**Issue by richmondu** [davisking/dlib#1573]
There are some use-cases where there is an expected size of face/s to detect. It would be nice if dlib's HOG and CNN face detector APIs can support such feature.

Face detector models such as Haar Cascade and MTCNN allow users to set the minimum face size. Based on test results, it speeds up performance a lot on PC and embedded systems (Rasberry Pi 3B+). Is this possible with the DLIB HOG and CNN models? 

Thanks!

**Comment by davisking** [comment]
Just shrink the the image before you run the detector.

**Comment by richmondu** [comment]
Shrinking image will make it too small. On Raspberry PI 3B+, im already using QVGA resolution (320x240). Dlib detector Performance is 3.5 fps for HOG and <1 fps for CNN.

**Comment by davisking** [comment]
Don't you want to find only larger faces?

**Comment by richmondu** [comment]
Yes, for 320x240 camera resolution, the expected size of the face will be about 180x180. If I further shrink the image frame, is shrinking down to 160x120 (25%) still good for dlib embeddings? If not, what would be the acceptable and optimal that I can shrink it further based on dlib's CNN? If I am correct, other detectors are using 300x300, 96x96 or 80x80.

**Comment by davisking** [comment]
That means you can shrink the image then.

Whatever any detector does to "only look for larger objects" is basically identical to shrinking the image and then running the normal detector.

**Comment by richmondu** [comment]
After shrinking image down to 25% 160x120, dlib HOG performance becomes 6 fps, now up to par with MTCNN and SSSDw/ResNet detectors. 

In terms of accuracy,
