### ISSUE TITLE
[Question] How to convert face recognition model from affine to batch norm?

### ISSUE THREAD

**Issue by xiaolin-cheng** [davisking/dlib#1574]
Hello,

Thanks for your help.

I would like to do some transfer learning based on the `dlib_face_recognition_resnet_model_v1.dat`, but this model seems to be for inference only (affine transformation replaces batch norm). Is there any way to convert this model to the batch norm version for training? I tried `net_to_xml( )`, but no clue how to use it to fill up a batch norm model type. 

I really appreciate any of your pointers and suggestions.

**Comment by davisking** [comment]
Unfortunately I didn't save the batch norm version of the model and there
is no automatic conversion from affine to batch norm.  You could write
custom code to populate the additional parameters of batch norm layers with
some reasonable initial values and copy over the affine transform though.

**Comment by xiaolin-cheng** [comment]
Thanks @davisking 

I created three helper functions to convert FC, BN and CON layers from the affine model to the bn model. 

For example:
```
    anet_type anet;
    deserialize("models/dlib_face_recognition_resnet_model_v1.dat") >> anet;

    net_type net;
    serialize_fc(layer<1>(anet).layer_details(), layer<1>(net).layer_details());
    serialize_bn(layer<8>(anet).layer_details(), layer<8>(net).layer_details());
    serialize_con(layer<9>(anet).layer_details(), layer<9>(net).layer_details());
    .... (the rest bn and conv layers)

    anet_type testing_net = net;   //segfault here
```

But I got segfault when I put the updated bn model back to the affine model.  Am I missing anything? I really appreciate you could take a look at my layer conversion APIs below. Thank you very much!

Three helper APIs: 
```
        void serialize_fc(fc_<128,FC_NO_BIAS>& fc_in, fc_<128,FC_NO_BIAS>& fc_out)
        {
            std::ofstream out;
            std::ifstream in;
            out.open("temp.dat");

            serialize(fc_in.params, out);
            serialize(fc_in.weights, out);
            out.close();

            in.open("temp.dat");
            deserialize(fc_in.params, in);
            deserialize(fc_in.weights, in);
            in.close();
        }

        template <long num_filters, long nr, long nc, int stride_y, int stride_x>
        void serialize_con(con_<num_filters, nr, nc, stride_y, stride_x>& con_in, 
                                     con_<num_filters, nr, nc, stride_y, stride_x>& con_out)
        {
            std::ofstream out;
            std::ifstream in;
            out.open("temp.dat");

            serialize(con_in.params, out);
            serialize(con_in.filters, out);
            serialize(con_in.biases, out);
            out.close();

            in.open("temp.dat");
            deserialize(con_out.params, in);
            deserialize(con_out.filters, in);
            deserialize(con_out.biases, in);
            in.close();
        }

        void serialize_bn(affine_& affine_in, bn_<CONV_MODE>& bn_out)
        {
            std::ofstream out;
            std::ifstream in;

            out.open("temp.dat");
            serialize(affine_in.params, out);
            serialize(affine_in.gamma, out);
            serialize(affine_in.beta, out);
            out.close();

            in.open("temp.dat");
            deserialize(bn_out.params, in);
            deserialize(bn_out.gamma, in);
            deserialize(bn_out.beta, in);
            in.close();
        }
```

**Comment by davisking** [comment]
You are probably not copying everything.  You also shouldn't be bouncing things off a disk, just use the = operator and copy variables like normal.  And look at the `bn_` class. There are other member variables in there that need to be set. That's the whole issue, it's not just those 3.

Also, a much simpler way to do this would be to add a constructor to `bn_` that builds a `bn_` from an `affine_` instance. Then you can just assign one net to another and it will do the appropriate conversion.

**Comment by xiaolin-cheng** [comment]
@davisking Thanks!

I thought batch norm only has two trainable variables (gamma and beta). What other member variables am I supposed to copy from affine_ to bn_? Affine model doesn't keep running means/means and running variances/variances, and number of updates. 

Thank you for your help!

**Comment by davisking** [comment]
Look at the code.  There are other variables in bn_.  Set them to some
sensible values.

**Comment by xiaolin-cheng** [comment]
Other than gamma and beta, other variables get runtime values. Here is what I did, but still segfault when assigning net to anet after restoring all layers from the affine model to the bn model. Anything I missed? Thanks a lot!

        ```
void serialize_bn(affine_& affine_in, bn_<CONV_MODE>& bn_out)
        {
            bn_out.params = affine_in.params;
            bn_out.gamma = affine_in.gamma;
            bn_out.beta = affine_in.beta;
            bn_out.running_means = 0;
            bn_out.running_variances = 1;
       }
```
