### ISSUE TITLE
Setup.py: How to use LDFLAGS?

### ISSUE THREAD

**Issue by nitanmarcel** [davisking/dlib#1575]
My PC is broken and I'm trying to install this on android using termux. Now android linker is different than the normal one so I need to compile it and link against libpython3.so. I've tried running:

LDFLAGS=" -llog -lpython3" python3 setup.py install --set 'DCMAKE_INSTALL_PREFIX=$PREFIX'

But with no results.

Any other way to install this? If I don't link it I will get this error: 

ImportError: dlopen failed: cannot locate symbol "PyInstanceMethod_Type"

 Thanks.

**Comment by nitanmarcel** [comment]
NVm... I fixed it by manually run the cmake commands with the LDFLAGS and other required options

**Comment by Nannigalaxy** [comment]
Any luck? I too got this error

**Comment by nitanmarcel** [comment]
@Nannigalaxy If I remember right I installed it with cmake. I don't remember from what folder but you can check the setup.py script to check from where is installing it.. it was tools/something

**Comment by youerning** [comment]
@nitanmarcel 
so how to install dlib finally?

**Comment by chaoranxie** [comment]
@nitanmarcel curious if you found a fix for this. I am also trying to install dlib on my android using termux. but got the same error.

**Comment by chaoranxie** [comment]
alright i think i got it working, looks like you i needed some additional package

```
apt update
apt upgrade
apt install python clang fftw libzmq libzmq freetype libpng libpng pkg-config zlib libiconv  curl

wget https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
tar -xf dlib-19.17.0.tar.gz
cd dlib-19.17.0
LDFLAGS=" -llog -lpython3" python3 setup.py install --set 'DCMAKE_INSTALL_PREFIX=$PREFIX'


```

**Comment by AndreiRadchenko** [comment]
Thank you, friend. I am almoust gave up, but your solution work for me perfect. I am finally got face_recognition on termux!

**Comment by MohamadOday** [comment]
@chaoranxie 
Thank you it start working i've realy lost hope but you saved me .

**Comment by nickelnine** [comment]
Hello,
I am getting the same error on Termux but the above additional package steps doesn't work for me. Running the above I get a bunch of:
`/data/data/com.termux/files/usr/include/python3.9/pyport.h:508:54: note: expanded from macro 'Py_DEPRECATED'    #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))                                                                                                ^  20 warnings generated.                                  13 warnings generated.                                  9 warnings generated.                                   In file included from /data/data/com.termux/files/home/dlib-19.17.0/tools/python/src/line.cpp:4:                In file included from /data/data/com.termux/files/home/dlib-19.17.0/tools/python/src/opaque_types.h:6:          In file included from /data/data/com.termux/files/home/dlib-19.17.0/dlib/../dlib/python.h:6:                    In file included from /data/data/com.termux/files/home/dlib-19.17.0/dlib/../dlib/python/pybind_utils.h:6:       /data/data/com.termux/files/home/dlib-19.17.0/dlib/external/pybind11/include/pybind11/pybind11.h:1060:9: warning: expression result unused [-Wunused-value]                     PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));`
