### ISSUE TITLE
how to set the appropriate size of  load_mini_batch（）

### ISSUE THREAD

**Issue by anan91** [davisking/dlib#1576]
Hello davisking !
I want to retrain the face recognition model . 
Question 1:
 I have 1.1 million ids with 80 million images,I would like to ask how to set the parameters of 
 load_mini_batch(), It is helpful for model training.
Question 2:
 Does the official framework need to be changed for such data? For example, deepen the layer number or feature layer 128 to 256 even more.

**Comment by davisking** [comment]
You must run experiments to see what works.  But I would start by trying
the same settings used by the public dlib model.

**Comment by anan91** [comment]
hello davisking,thanks for your reply.
resnet52:
        block2_x       block3_x       block4_x     block5_x
        1*1，64         1*1,128         1*1,256     1*1,512
        3*3，64         3*3,128         3*3,256      3*3,512
        1*1，256       1*1,512         1*1,1024     1*1,2048
I tried to build resnet52 network, but I was a little confused about the jumping layer between blocks. Avg_pool () samples W and H, but how to solve the difference in channel number between the two blocks?
