### ISSUE TITLE
max_pointwise between matrix and scalar

### ISSUE THREAD

**Issue by facug91** [davisking/dlib#1579]
I was trying to do that, max_pointwise between a matrix and a scalar, and couldn't find the proper function. I wanted to know if there's a reason for that, or if a PR with the functionality would be ok.

**Comment by davisking** [comment]
There is no function, I would do like `max(max(mymatrix),5.0)`.

**Comment by davisking** [comment]
`lowerbound(mymatrix, 0.5)`

**Comment by facug91** [comment]
That's what I was looking for, thanks!

**Comment by facug91** [comment]
Davis, one more thing. What about making pointwise matrix division? Is there a function to do that, which I'm not seeing?  
By the time, I was able to do it with pointwise_multiple(M1, 1.0 / M2), but I've tried implementing a quick pointwise_divide function, and it seems to perform ~10% faster.

**Comment by davisking** [comment]
Yeah, that sounds cool to me :)
