### ISSUE TITLE
how to label image for a beard region detector

### ISSUE THREAD

**Issue by oladayosolomon** [davisking/dlib#1583]
Hi, pls am working on a project that needs me to detect beard regions on profile faces. First I like to know if there is a detector for profile faces in dlib of i have to train my own model.

secodnly, for the beard region can i use the train landmark features in dlib to achieve this and is this labeling correct. 
![capture](https://user-images.githubusercontent.com/15249490/49621033-2d181e00-f9cc-11e8-9957-f13bd73dc09f.JPG)

**Comment by isgursoy** [comment]
following

**Comment by davisking** [comment]
You can use the `imglab` tool in dlib's tools folder to label images with point annotations, then train on those files.  There are example programs in dlib that talk about this.  Also, imglab's help menu tells you how to use it.
