### ISSUE TITLE
Call Dlib in C++ library from Java app using JNA

### ISSUE THREAD

**Issue by don-prog** [davisking/dlib#1589]
I try to use my C++ library with dlib code in Java project via JNA. So...
## Expected Behavior
I want to execute some Dlib C++ code(e.g. get_frontal_face_detector()) in C++ library from Java app. 

## Current Behavior
I get Java exception:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library '/home/user/QtProjects/build-dlibTest-Desktop_Qt_5_10_1_GCC_64bit-Release/libdlibTest.so': Native library (home/user/QtProjects/build-dlibTest-Desktop_Qt_5_10_1_GCC_64bit-Release/libdlibTest.so) not found in resource path ([file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar, file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar, ...
> 	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
> 	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
> 	at com.sun.jna.Library$Handler.<init>(Library.java:179)
> 	at com.sun.jna.Native.load(Native.java:591)
> 	at com.sun.jna.Native.load(Native.java:565)
> 	at Main$CppLibrary.<clinit>(Main.java:12)
> 	at Main.main(Main.java:20)

## Steps to Reproduce
Java app code:
```
public class Main {


    public interface CppLibrary extends Library {

        CppLibrary INSTANCE = (CppLibrary)
                Native.load("/home/user/QtProjects/build-dlibTest-Desktop_Qt_5_10_1_GCC_64bit-Release/libdlibTest.so",
                        CppLibrary.class);

        void dlibTest();
    }

    public static void main(String[] args){
        CppLibrary.INSTANCE.dlibTest();
    }
}
```

C++ library code: 

```
#include <dlib/image_processing/frontal_face_detector.h>

using namespace dlib;
using namespace std;

extern "C"
{
    void dlibTest(){
        frontal_face_detector detector = get_frontal_face_detector();
        cout<<"dlib test"<<endl;
    }
}

```
**Please note that if I delete `frontal_face_detector detector = get_frontal_face_detector();` line then all works fine.**

**Comment by davisking** [comment]
You apparently aren't linking your shard library to dlib. This isn't a dlib issue.

I will however point out that you can use CMake to build a jar file (see http://dlib.net/other.html#Java) and cmake will do the right thing and it will work.

**Comment by don-prog** [comment]
Thanks, I successfully built library with dlib using swig. But now I can't build some code expressions. I changed example files for testing:

swig_api.h:

```
#ifndef EXAMPLE_SWIG_ApI_H_ 
#define EXAMPLE_SWIG_ApI_H_

#include <dlib/java/java_array.h>
#ifdef SWIG
%include <dlib/java/java_array.h>
#endif
// ----------------------------------------------------------------------------------------

#endif // EXAMPLE_SWIG_ApI_H_
```
java_array.h:

```
#ifndef DLIB_SWIG_JAVA_ARRAY_H_
#define DLIB_SWIG_JAVA_ARRAY_H_

#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/dnn.h>
#include <dlib/data_io.h>
#include <dlib/timer.h>
#include <dlib/misc_api.h>

namespace java
{

template <template <int,template<typename>class,int,typename> class block, int N, template<typename>class BN, typename SUBNET>
using residual = dlib::add_prev1<block<N,BN,1,dlib::tag1<SUBNET>>>;

}

#endif // DLIB_SWIG_JAVA_ARRAY_H_

```

Output:

> 
> **./run_test.sh** 
> mkdir: cannot create directory ‘build’: File exists
> -- Using CMake version: 3.5.1
> -- Compiling dlib version: 19.16.99
> -- C++11 activated.
> -- JAVA_HOME environment variable not set, trying to guess it...
> -- Using JAVA_HOME OF /usr/lib/jvm/java-8-openjdk-amd64
> -- C++11 activated.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/user/Documents/dlib-master/dlib/java/build
> [ 97%] Built target dlib
> [ 98%] Swig source
> /home/user/Documents/dlib-master/dlib/java/../../dlib/java/java_array.h:18: Error: Syntax error in input(1).
> CMakeFiles/myproject.dir/build.make:61: recipe for target 'lib/java_src/net/dlib/swigJAVA_wrap.cxx' failed
> make[2]: *** [lib/java_src/net/dlib/swigJAVA_wrap.cxx] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myproject.dir/all' failed
> make[1]: *** [CMakeFiles/myproject.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> 
But I can get dlib and build this function in java_array.h:
```
std::vector<dlib::matrix<dlib::rgb_pixel>> jitter_image(
    const dlib::matrix<dlib::rgb_pixel>& img
);
```
I know that `The 'using' keyword in template aliasing is not fully supported yet` in swig, so maybe I should somehow change `template` expression, but what exactly should I do?

Also, `using namespace dlib;` occurs to `Error: Nothing known about namespace 'dlib'`.

**Comment by davisking** [comment]
Java doesn't understand C++ templates.  Write a class without templates,
something simple java can understand. Also, this is a swig/java question,
not a dlib question.  Consult the swig documentation.

**Comment by davisking** [comment]
Put things that upset swig into `#ifndef SWIG` blocks.  Or put them in a different file.  There are just limitations on what swig can parse in its main interface file.
