### ISSUE TITLE
what are the sub-detectors of Dlib's face detector?

### ISSUE THREAD

**Issue by PaniniGelato** [davisking/dlib#159]
Hi, I'm checking the score for each detection following this example http://dlib.net/face_detector.py.html

```
img = io.imread(sys.argv[1])
dets, scores, idx = detector.run(img, 1, -1)
for i, d in enumerate(dets):
    print("Detection {}, score: {}, face_type:{}".format(d, scores[i], idx[i]))
```

the comment says that 
```
the idx tells you which of the face sub-detectors matched
```

And I got some result like:
```
{
    "rects": [
      {
        "right": 841,
        "bottom": 557,
        "top": 236,        
        "left": 520,
        "score": 0.3562501464983847,
        "idx": 2.0
      }
    ],
    "file": "images/all/1/1/16245743.jpg"
  },
  {
    "rects": [
      {
        "right": 486,
        "bottom": 363,
        "top": 177,
        "left": 301
        "score": 1.2453413163490716,
        "idx": 1.0,
      }
    ],
    "file": "images/all/1/1/192993.jpg"
  }
```

My question is what are these sub-detectors? And where can I find some information about them?

**Comment by e-fominov** [comment]
Sub-detectors of frontal face detector are defined here: https://github.com/davisking/dlib/blob/master/dlib/image_processing/frontal_face_detector.h

**Comment by PaniniGelato** [comment]
@e-fominov thank you very much!

**Comment by td042** [comment]
I have a similar question about this. I get the final bounding box with the dimensions Left: 180 Top: 98 Right: 366 Bottom: 284. However, when I output the confidence score, I only get the value to other bounding boxes, e.g. Detection [(201, 116) (356, 270)], score: 0.7252923836551153, face_type: 3.0. Is it also possible to output the confidence score of the final bounding box?

**Comment by davisking** [comment]
What you are saying doesn't make sense.  The confidence score that's output is for the detection. It's not for some other hypothetical detection that might have happened but wasn't output.

**Comment by tkh5044** [comment]
Hi, I see in this file that the thresholds for each sub-detector range from 0.12 to 0.19, but when I run detector.run() I see scores as low as 0.0018. How is this possible?

**Comment by davisking** [comment]
Are you referring to the singular value thresholds noted in those comments?  Those are not referring to detection thresholds.
