### ISSUE TITLE
[question] row major or column major of fully connected parameter tensor?

### ISSUE THREAD

**Issue by xiaolin-cheng** [davisking/dlib#1592]
Hi Davis,

For the fully connected layer parameter tensor:

1. Can I update or freeze the individual parameters by changing `fc.host()[i]` ? 
where `fc ` is `tensor& fc = layer<1>(net).layer_details().get_layer_params();` 
2. Are the elements in tensor `fc` arranged row after row or column after column? I found nc and nr for this tensor are both 1.

Thanks!

**Comment by davisking** [comment]
You can modify tensors by getting their data via `host()` any way you like.  

The documentation explains the layout: http://dlib.net/dlib/cuda/tensor_abstract.h.html#tensor.  It also explains what these functions do.
