### ISSUE TITLE
dnn_models directory

### ISSUE THREAD

**Issue by headupinclouds** [davisking/dlib#1595]
Should there be a standardized location in dlib, or perhaps an associated dlib_models repository, for users to share common published SOTA DNN network definitions?  This would essentially be a collection of header files containing matched training and inference template definitions for a particular model that could be used in custom apps or as alternative models within the existing tutorial examples. 
 Users will likely want to copy and tune models for their needs, but having a collection of common model definitions would be useful as a starting point for prototyping and code reuse.  I was implementing a couple mobile friendly models recently, and thought they might be of interest to other users, but didn't really see a good place to put them in dlib.  These don't illustrate any new core functionality, and don't seem to warrant adding a new example, but they could be used as alternatives within the existing examples, such as [dnn-imagenet_train_ex](https://github.com/davisking/dlib/blob/master/examples/dnn_imagenet_train_ex.cpp).

**Comment by davisking** [comment]
You could submit to https://github.com/davisking/dlib-models

**Comment by headupinclouds** [comment]
[dlib-models](https://github.com/davisking/dlib-models) is currently lacking a directory for the associated network definitions, so perhaps we could add something like **dlib-models/dlib/dnn_models/some_model_name.h** (or similar).  

The main issue I see with using dlib-models for this, is that the serialized model weights tend to be large, of course, and there are already serialized models stored in git at that location.  If we store both the network definition header files (<= 4K) and the serialized model weights (1 MB - 500 MB) in the same git repo, I can see the size overhead making that location somewhat less user friendly from the perspective of having a package of pre-defined network definitions that can be used easily in our projects.

I was thinking of supporting a use case from CMake like this (similar to dlib):

```
find_package(dlib_dnn_models CONFIG REQUIRED)
target_link_libraries(my_app dlib::dnn_models) # or whatever name is preferred
```

which would be our closest C++ option to the `import` that is typically used to grab common network definitions in the python oriented deep learning frameworks.

In main.cpp, we would do something like this:

```
#include <dlib/dnn/trainer.h>
#include <dlib_contrib/squeezenext_1_23v5.h> // or whatever name is preferred 
#include <dlib_contrib/resnet_50.h> // etc

// <SNIP>

int main(int args, char **argv)
{
    // train with squeezenext_1_23v5_train
 
    // predict w/ squeezenext_1_23v5_test, or whatever template alias naming convention makes sense
}
```

For that use case, it seems a different repo, or possibly a top level directory in the main dlib repository might be preferable.  If you prefer to keep model definitions out of the main repo, it might make sense to start something like **dlib_contrib** where the lightweight network definitions could be stored, and the associated large binary serialized models could be placed in GitHub asset storage (outside of git).  If you still prefer adding the headers to dlib-models, I think it would still be a good start.

**Comment by headupinclouds** [comment]
@fourier79 : Have you seen @reunanen 's #1600 ?

**Comment by davisking** [comment]
I don't really want to get into the business of hosting models for people.  My general take on this is that people who want the models can download them and then stick them into whatever source/data control system they want to use, and that is up to them. 

It's also possible to download individual files from a github repo.  You don't have to grab them all.

**Comment by davisking** [comment]
Although I should clarify, people can submit models to this repository.  But I don't want to be on the hook for people's build/data management systems.
