### ISSUE TITLE
dlib::cuda::getdevice already defined in dlib.lib

### ISSUE THREAD

**Issue by fizmatbfu** [davisking/dlib#1599]
## Expected Behavior
I built dlib with CMake (with CUDA support). Then i created project in Visual Studio 2015 and added file dnn_mmod_train_find_cars_ex.cpp, and also added needed libs from dlib and cuda. I did this earlier, but without CUDA, and all worked fine. 

## Current Behavior
But now i get next errors:
LNK2005	"bool __cdecl dlib::cuda::can_access_peer(class dlib::tensor const &,class dlib::tensor const &)" (?can_access_peer@cuda@dlib@@YA_NAEBVtensor@2@0@Z) already defined in dlib19.16.0_release_64bit_msvc1900.lib(dlib_generated_cuda_dlib.cu.obj)	
LNK2005	"void __cdecl dlib::cuda::device_synchronize(int)" (?device_synchronize@cuda@dlib@@YAXH@Z) already defined in dlib19.16.0_release_64bit_msvc1900.lib(dlib_generated_cuda_dlib.cu.obj)
LNK2005	"int __cdecl dlib::cuda::get_device(void)" (?get_device@cuda@dlib@@YAHXZ) already defined in dlib19.16.0_release_64bit_msvc1900.lib(dlib_generated_cuda_dlib.cu.obj)
LNK2005	"void __cdecl dlib::cuda::set_device(int)" (?set_device@cuda@dlib@@YAXH@Z) already defined in dlib19.16.0_release_64bit_msvc1900.lib(dlib_generated_cuda_dlib.cu.obj)	

## Steps to Reproduce
1) Install CUDA 10, download cudnn
2) Build dlib with Cmake (with CUDA support) x64 Release
3) Create project in VS2015 (x64 Release). Add dnn_mmod_train_find_cars_ex.cpp, add needed libs from dlib, cuda.

* **Version**: 19.16
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 64
* **Compiler**: MSVC 2015

**Comment by davisking** [comment]
Step 3 is vague.  You must be doing something unreasonable there.

You should use cmake to setup the project, it will setup visual studio correctly.

**Comment by davisking** [comment]
Maybe this applies to you: http://dlib.net/faq.html#WhydoIgetUSERERRORinconsistentbuildconfigurationseedlibfaq2.  Although I'm unsure why you wouldn't have received this error message. But note that you can't just go copy files around since the build creates a config.h that sets appropriate #defines.  If you don't use the config.h then you need to set those #defines in your project settings.  I assume you did neither of these things.  

Importantly, *cmake will do all this automatically*.  Use cmake as shown in the examples and everything will always just work.

**Comment by fizmatbfu** [comment]
Thanks, Davis. I have built program with CMake and it works fine.

**Comment by hayTambourineMan** [comment]
> Step 3 is vague. You must be doing something unreasonable there.
> 
> You should use cmake to setup the project, it will setup visual studio correctly.

I agree there is something wrong with step 3. I encountered the exact same error messages when I tried to build my Visual Studio solution, and it's sloppy work on my part.

For anyone searching for a solution for the same error: I solved it by adding "dlib/all/source.cpp" to my console project, which is mentioned in dlib's documentation here: [http://dlib.net/compile.html#Using%20dlib%20from%20C++](url) under the "Compiling on Windows Using Visual Studio 2015 or Newer" headline. If you stick to dlib's tutorial, you should be fine.
