### ISSUE TITLE
how to convert cv_image to array2d?

### ISSUE THREAD

**Issue by dylansun** [davisking/dlib#16]
I want to read images using opencv's imread, and then wrap it using cv_image from dlib
However, when I try to feed this image to a front face detector, I got an error "invalid argument". How can transform  cv_image to array2d.
Here is my pieces of code define the data type:
```
frontal_face_detector detector = get_frontal_face_detector();
Mat img_opencv = imread(argv[i]);
cv_image<rgb_pixel> img(img_opencv);
std::vector<rectangle> dets = detector(img);
```

**Comment by davisking** [comment]
You can use dlib::load_image() to read an image without open cv.  However,
if you really want to use imread then you have to tell cv_image the type of
pixel in opencv's Mat object, which is usually bgr_pixel.

**Comment by dylansun** [comment]
Thanks davis, however my situation is that I want to feed the ```frontal_face_detector``` namely ```detector``` with an image, which seems to require an ```array2d``` type data, how can I transform ```cv_image``` to ```array2d```. can you show me some code?

**Comment by davisking** [comment]
Replace rgb_pixel with bgr_pixel in your code.

**Comment by dylansun** [comment]
Not work:( still the same error
''' error: invalid type in declaration before ‘=’ token 
std::vector<rectangle> dets = detector(img);'''

**Comment by dylansun** [comment]
```load_image()``` works

**Comment by Sundrops** [comment]
@dylansun  you can do like this:
array2d<bgr_pixel> img;
Mat img_opencv = cv::imread(argv[1]);
dlib::assign_image(img, dlib::cv_image<bgr_pixel>(img_opencv));
And, when I use load_image(), i gets errors:
exception thrown!
Unable to load image in file temp.jpg.
You must #define DLIB_JPEG_SUPPORT and link to libjpeg to read JPEG files.
How should i modify the CMakelists.txt ? thank you!

**Comment by davisking** [comment]
CMake should automatically enable DLIB_JPEG_SUPPORT.  Do the example programs, when compiled with cmake, work on jpeg files?

**Comment by Sundrops** [comment]
@davisking the example programs can work on jpeg files. but when i link the libdlib.so in my own programs,it cannot work on jpeg files.

**Comment by usu008** [comment]
dlib::cv_image<dlib::rgb_pixel> img(img_scene);    i am using like this but it shows the error as follows


Error	C2065	'cv_image': undeclared identifier

anyone plz?

**Comment by itsjasonc** [comment]
I had that error for undeclared identifier, I resolved it by including the header file that references the function.

`#include <dlib/opencv/cv_image.h>`
