### ISSUE TITLE
build errors when DLIB_NO_GUI_SUPPORT is defined

### ISSUE THREAD

**Issue by nidegen** [davisking/dlib#160]
For an iOS app i want to build dlib libraries without X11. Defining DLIB_NO_GUI_SUPPORT brings me to following error:

```
#ifdef DLIB_NO_GUI_SUPPORT
      #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
      #error "Also make sure you have libx11-dev installed on your system"
#endif
```

As it was set intentionally, there should be a way to get around it. Or, I am missing something:)

**Comment by davisking** [comment]
You are building code that tries to #include some part of the GUI.  So you get that error.   I'm not sure what else you would expect.   Are you building one of the examples that doesn't have anything GUI related in it?

**Comment by nidegen** [comment]
Yes I agree, but the problem is that i only include dlib/image_processing.h and instantiated an object  `dlib::bgr_pixel sdf;` in a cpp swift wrapper function. if image_processing.h needs GUI, my issue is irrelevant.

BTW: thanks for your code, you comments and your help. you are awesome!

**Comment by davisking** [comment]
Thanks :)

Anyway, are you sure?  I just compiled a test program that includes only dlib/image_processing.h and it compiled just fine.

**Comment by nidegen** [comment]
pretty much. I now use:
```
#include <dlib/image_processing.h>
#include <dlib/opencv.h>
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
```
and it still happens if i uncomment `#define DLIB_NO_GUI...`

 I think neither of those should use the GUI. also, if i dont add the flag it builds and runs on iOS. i assume any use of GUI would make that impossible.

the code is in a obj-c wrapper that is included in a swift app. i have to check how much i can share of the code though...:/ i am only using opencv additionally and havent touched dlib..

**Comment by davisking** [comment]
That face rendering code uses the GUI.

**Comment by nidegen** [comment]
ok. i assumed as it works on ios it couldnt include a GUI.
