### ISSUE TITLE
Help with error in assert.h

### ISSUE THREAD

**Issue by KimSerge1** [davisking/dlib#1601]
warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         argv[1] = "/home/oracle/CProject/dlib-net_models/shape_predictor_68_face_landmarks.dat";//
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sergey/dwadwa/19v/dlib/main.cpp:102:19: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         argv[2] = "/home/oracle/CProject/01/";
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sergey/dwadwa/19v/dlib/main.cpp:103:19: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         argv[3] = "/home/oracle/CProject/FaceDetect/res/";
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sergey/dwadwa/19v/dlib/main.cpp:104:19: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         argv[4] = "/home/oracle/CProject/dlib-net_models/dlib_face_recognition_resnet_model_v1.dat";
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/sergey/dwadwa/19v/dlib/dlib/image_processing/../image_processing/../geometry/../algs.h:111:0,
                 from /home/sergey/dwadwa/19v/dlib/dlib/image_processing/../image_processing/../geometry/rectangle.h:7,
                 from /home/sergey/dwadwa/19v/dlib/dlib/image_processing/../image_processing/../geometry.h:6,
                 from /home/sergey/dwadwa/19v/dlib/dlib/image_processing/../image_processing/object_detector.h:7,
                 from /home/sergey/dwadwa/19v/dlib/dlib/image_processing/frontal_face_detector.h:7,
                 from /home/sergey/dwadwa/19v/dlib/main.cpp:2:
/home/sergey/dwadwa/19v/dlib/dlib/image_saver/save_png.h: In instantiation of ‘typename dlib::disable_if<dlib::is_matrix<image_type> >::type dlib::save_png(const image_type&, const string&) [with image_type = dlib::array2d<dlib::rgb_pixel>; typename dlib::disable_if<dlib::is_matrix<image_type> >::type = void; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/sergey/dwadwa/19v/dlib/dlib/image_saver/save_png.h:150:17:   required from ‘void dlib::save_png(const dlib::matrix_exp<EXP>&, const string&) [with EXP = dlib::matrix<dlib::rgb_pixel>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/sergey/dwadwa/19v/dlib/main.cpp:181:87:   required from here
/home/sergey/dwadwa/19v/dlib/dlib/image_processing/../image_processing/../geometry/../assert.h:98:45: error: static assertion failed: Failed assertion
     #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                             ^
/home/sergey/dwadwa/19v/dlib/dlib/image_saver/save_png.h:64:13: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
             COMPILE_TIME_ASSERT(sizeof(image_type) == 0);
             ^
CMakeFiles/main.dir/build.make:62: recipe for target 'CMakeFiles/main.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/main.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

I have problem with assert.h(Using Ubuntu 18.04), don't know why it happend, please help me!
Cloning dlib from master.

**Comment by AlexXandreE** [comment]
Hi, 
Is that your own program? or an example?
