### ISSUE TITLE
Error when using pyqt

### ISSUE THREAD

**Issue by nouxu1** [davisking/dlib#1606]
Hello..
I have installed every thing and it works correctly without any errors.
But when I tried to use dlib with qt library and python an error occurred telling that failed to call cuDNN, notice that the same code implemented without using qt worked fine!

The error was:
> **RuntimeError: Error while calling cudnnConvolutionForward( context(), &alpha, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &beta, descriptor(output), output.device()) in file /tmp/pip-build-imozotm2/dlib/dlib/cuda/cudnn_dlibapi.cpp:1007. code: 7, reason: A call to cuDNN failed**

**Comment by congphase** [comment]
Did you solve the issue? I face the exact error message. Anyone ever experienced this, please help me.
