### ISSUE TITLE
Linking dependencies for dlib on iOS

### ISSUE THREAD

**Issue by don-prog** [davisking/dlib#161]
Hello!

I'm trying to use dlib on iOS. So, I found a [tutorial which describes how I can do this](https://github.com/RedHandTech/Object_Detector/blob/master/README.md#dlib-compile-instructions). I did everything exactly with this recommendation, including adding in the Xcode Other Linker Flags these items:
```
/usr/lib/liblapack.dylib
/usr/local/lib/libjpeg.dylib
/usr/local/lib/libpng.dylib
/usr/lib/libcblas.dylib
```

But after my try of building I get Xcode linker error which says:

    ld: building for iOS simulator, but linking against dylib built for OSX, file X for architecture x86_64

Where X - every library which listed above.

So, is this a correct building and using of dlib for iOS? And how can I use(or build) these libraries on iOS?

**Comment by davisking** [comment]
I don't know as I never do iOS development.  But more generally, these are not dlib specific questions or issues but about how the linker on iOS and Xcode works, so off topic for this forum.
