### ISSUE TITLE
CUDNN error:cnn_face_detector

### ISSUE THREAD

**Issue by taxuezcy** [davisking/dlib#1615]
when I use cnn_face_detector method to location the face , i meet the error ,RuntimeError:Error while calling cudnnGetConvolution2dForwardOutDim((const cudnnConvolutionDescripter_t)conv_handle,descriptor(data),(const cudnnFilterDescriptor_t)filter_handle,&out_num_samples,&out_k,&out_nr,&out_nc)in /root/dlib/dlib/cuda/cudnn_dlibapi.cpp:837,code:3,reason:CUDNN_STATUS_BAD_PARAM

**Comment by taxuezcy** [comment]
@davisking

**Comment by VisionEp1** [comment]
same error here
