### ISSUE TITLE
[question] dnn result not same slightly each trials

### ISSUE THREAD

**Issue by greenfish77** [davisking/dlib#1616]
i found that dnn result not same slightly each trials in one training dataset.
so, i started to find random code of random batch sampling, but i can't.

anyone, who knows that where is random sampling code to select batch in dnn trainer?
if i found that, i'll modify code to send fixed seed value for random.

**Comment by davisking** [comment]
There is no random code, but this sort of variability is to be expected since a lot of parallel processing is involved in training.
