### ISSUE TITLE
dlib module has no classes to work with RVM

### ISSUE THREAD

**Issue by kamua** [davisking/dlib#1618]
## Expected Behavior

I want to use RVM to solve a machine learning task in Python. I installed dlib by the command `conda install -c menpo dlib` successfully. The Python command `Import dlib` was done successfully too. I expect that the command `rvm = dlib.rvm_trainer_linear()` must create the `rvm` object to further work.

## Current Behavior

But `dlib` module has no classes to work with RVM (`rvm_trainer_linear`, `rvm_trainer_radial_basis`, etc.). The command `rvm = dlib.rvm_trainer_linear()` returns the error: 
> AttributeError: module 'dlib' has no attribute 'rvm_trainer_linear'

Note that the command `svm = dlib.svm_c_trainer_linear()` works correctly.
## Steps to Reproduce

`import dlib`
`rvm = dlib.rvm_trainer_linear()`
> AttributeError: module 'dlib' has no attribute 'rvm_trainer_linear'

* **Version**: 19.9.0
* **Where did you get dlib**: `conda install -c menpo dlib`
* **Platform**: Anaconda, Windows 10, 64-bit
* **Compiler**: I didn't use a compiler.

**Comment by davisking** [comment]
Correct, the RVM is not bound into python.  I honestly think that RVMs are not a great algorithm and that either KRR or SVM+hyper parameter optimization (e.g. http://dlib.net/model_selection_ex.cpp.html or http://dlib.net/ml.html#auto_train_rbf_classifier) is superior.  This is why RVMs are not in the python API.  However, if someone wants to submit a PR that adds them I will not reject it.

**Comment by kamua** [comment]
But rvm classes work in google colab correctly! The python module dlib (ver 19.16.0) is already installed by default. I tested it now.

**Comment by davisking** [comment]
Oh, right, I forgot someone already contributed a PR to add this to the python API :)

Well, you still should use something else.  But yes, you can use them from python. Get a newer version of dlib.

**Comment by kamua** [comment]
Could you tell me how install newest version of dlib for the Anaconda platform via some simple command `conda install ...` without comlpiling?

**Comment by davisking** [comment]
Just install a compiler.  They are free.  http://dlib.net/compile.html
