### ISSUE TITLE
shape_predictor_trainer runs out of memory loading images in large training set

### ISSUE THREAD

**Issue by darktable** [davisking/dlib#1620]
## Expected Behavior

running `shape_predictor_trainer` with a large set of training data should load/unload images as needed to perform the training.

## Current Behavior

running `shape_predictor_trainer` with a properly formatted training.xml with a large number of images (~2x labels_ibug_300W_train.xml) loads all images into memory before starting, consuming more than 32gb of RAM.

## Steps to Reproduce

run `train_shape_predictor_ex`, or use python function `dlib.train_shape_predictor` to load a properly formatted xml training file containing ~15,000 image elements. Memory usage should climb over 16gb as `load_image_dataset` loads all the images into an array. 

* **Version**: 
using dlib 19.16.0
* **Where did you get dlib**: 
dlib installed from pip
* **Platform**: 
platform macOS and Windows 10.
* **Compiler**: 
n/a

**Comment by davisking** [comment]
It's not reasonable to change the code to cycle back and forth between disk and ram like that.  It will make training very slow.  You should instead buy more RAM, or use smaller images.

**Comment by darktable** [comment]
At the moment I have more time than money, so slower would be better than buying more RAM. I'll try cropping and scaling the images. Thanks for the quick response.

**Comment by akfheaven** [comment]
I am facing the same problem. Can the training be designed in a way that  we can train the large dataset seprately in several times?

**Comment by davisking** [comment]
No, you need more RAM.

**Comment by darktable** [comment]
I ended up pruning my dataset and also scaling the images to get under 16gb. You could also use Google Compute Cloud to create a virtual machine with a lot of RAM and run it for a few hours for less than the cost of the RAM. I used Compute Cloud for free because they offered a one week trial.

**Comment by davisking** [comment]
You can also use dlib's find_max_global to automate the parameter search.  That's what I do.  I just launch this thing and forget about it for a day and when it's done it's done.

**Comment by akfheaven** [comment]
I‘am now solving the crash by increasing the virutal memory. For 20000 images it takes about 40GB, but it's really slow.Thank you both for the advices, I will try them sometime.

**Comment by harshkn** [comment]
@davisking Hi Davis, Is it not possible to just keep track of filenames and load images for each mini-batch like its done in segmentation training example ? I am planning to follow that segmentation_train example to train object detection using mmod because I have 16 GB CPU RAM and it exceeds in case I have loads of images to train on. You think this is feasible or buying the RAM the only option ? 

Another Question regarding find_max_global, I have only skimmed through this. If I follow your blog post on this, will I be able to use it to improve the  training on  MMOD Object detection model ?

**Comment by davisking** [comment]
@harshkn are you talking about training the shape predictor?  Then the answer is no.

You can use find_max_global to optimize anything so long as the number of variables you are optimizing is small, like under 10.

**Comment by harshkn** [comment]
@davisking Thanks David. No, I am talking about object detection with mmod loss function.

**Comment by davisking** [comment]
Then yes, you can setup whatever kind of threaded data loading you want.  This is what most of the examples do.
