### ISSUE TITLE
xlib11-dev, libopenblas-dev, and liblapack-dev installed but not found

### ISSUE THREAD

**Issue by ManuelTS** [davisking/dlib#1621]
## Expected Behavior
Build via Android Studio cmake of a shared library .so file in a Android Studio project directory of my own `jni_face_detection.cpp` file which is a rewrite of [webcam_face_pose_ex.cpp](https://github.com/davisking/dlib/blob/master/examples/webcam_face_pose_ex.cpp). Right now I use zero dlib features. I just initialize fields of dlib components but I don't use them. What should happen is a clear build without errors.

## Current Behavior
I hit the build button of Android Studio, it executes the following `build.gradle` file of my module:
```
apply plugin: 'com.android.feature'

task deleteSOs(dependsOn: build) { // Remove LIB_DIR content to avoid gradle build errors having "More than one file was found with OS independent path 'lib/...'"
    delete "src/main/jniLibs/"
}

android {
    compileSdkVersion minimalSDK.toInteger()
    defaultConfig {
        minSdkVersion minimalSDK.toInteger()
        targetSdkVersion maximalSDK.toInteger()
        versionCode 1
        versionName appVersion.toString()
        externalNativeBuild { // https://developer.android.com/studio/projects/gradle-external-native-builds
            cmake { // https://developer.android.com/ndk/guides/cmake
                arguments "-DANDROID_STL=c++_shared",
                          "-DANDROID_CPP_FEATURES=rtti exceptions",
                          "-DANDROID_TOOLCHAIN=clang"
                abiFilters abi2Build.toString() // Denotes what ABI is build
            }
        }
        ndk { // https://developer.android.com/studio/projects/gradle-external-native-builds
            abiFilters abi2Build.toString() // Denotes what ABI is packed
        }
    }
    splits.abi { // Make sure this is in every module!
        enable true
        reset() // Use reset() and include for specific ABIs
        include abi2Build.toString()  //select ABIs to build APKs for
    }
    buildTypes {
        release {
            minifyEnabled shrinkAndMinify.toBoolean()
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildToolsVersion buildToolVersion.toString()
    sourceSets {
        main {
            jniLibs.srcDirs "src/main/jniLibs" // https://stackoverflow.com/questions/44954122/more-than-one-file-was-found-with-os-independent-path-lib-x86-libusb-so/44962630#44962630
            jni.srcDirs = [] //disable automatic ndk-build call
        }
    }
    externalNativeBuild {
        cmake {
            path '../../dlib-19.16/examples/CMakeLists.txt'
        }
    }
}

dependencies {
    implementation 'com.android.support:appcompat-v7:' + androidSupportVersion.toString()
    implementation 'com.android.support:design:' + androidSupportVersion.toString()
    implementation 'com.android.support:recyclerview-v7:' + androidSupportVersion.toString()
    /*implementation'com.android.support:preference-v7:' + androidSupportVersion.toString()*/
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.google.ar:core:' + arCoreVersion.toString() // = 1.6.0
    implementation 'com.google.ar.sceneform:core:' + arCoreVersion.toString()
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:' + arCoreVersion.toString()
    implementation project(':base')
    implementation files('libs/xz.jar')
}
```
which calls with the installed Android Studio cmake 3.6.0 my `CMakeLists.txt` file:
```
cmake_minimum_required(VERSION 3.6.0)                              # RTFM of cmake.org, https://cmake.org/cmake/help/v3.6/ , Andriod Studio had no higher version
project(face_detection)


set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Werror") # https://github.com/tzutalin/dlib-android/blob/master/CMakeLists.txt
set(USE_AVX_INSTRUCTIONS ON CACHE BOOL "Use AVX instructions")     # -https://stackoverflow.com/a/51628855
set(DLIB_WRAPPER_NAME   "jni_face_detection")                      # Wrapper class used by Java and JNI
set(DLIB_NATIVE_NAME    "dlib_native")                             # Final library name
set(OpenCV_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/../../opencv-4.0.1-android-sdk/OpenCV-android-sdk/sdk/native/jni)
set(LIB_DIR             ${CMAKE_CURRENT_SOURCE_DIR}/../../arnatomy/controller/src/main/jniLibs/)

if(IS_DIRECTORY ${LIB_DIR})                                        # Only build if the directory is missing, much faster Android Studio build but if you change any .cpp file you also have to delete the dir
    message("Omitted native build since ${LIB_DIR} exists.")
else()
   option(DLIB_NO_GUI_SUPPORT     "" OFF)
   option(DLIB_ENABLE_STACK_TRACE "" OFF)
   option(DLIB_USE_BLAS           "" ON)
   option(DLIB_USE_LAPACK         "" ON)
   option(DLIB_USE_CUDA           "" OFF)
   option(DLIB_USE_MKL_SEQUENTIAL "" OFF)
   option(DLIB_PNG_SUPPORT        "" OFF)
   option(DLIB_GIF_SUPPORT        "" OFF)
   option(DLIB_JPEG_SUPPORT       "" OFF)
   option(DLIB_LINK_WITH_SQLITE3  "" OFF)
   option(DLIB_USE_FFTW           "" ON)
   option(DLIB_USE_MKL_FFT        "" ON)
   option(DLIB_ENABLE_ASSERTS_STR "" OFF) # Decleared before add_subdirectory the options overwrite others https://stackoverflow.com/a/14067342
   add_subdirectory(../dlib dlib_build) # check this!!!

    add_library(${DLIB_NATIVE_NAME} SHARED "${DLIB_WRAPPER_NAME}.cpp") # Decleare what library is build
    set_target_properties(${DLIB_NATIVE_NAME}
                          PROPERTIES
                          LIBRARY_OUTPUT_DIRECTORY
                          "${LIB_DIR}/${ANDROID_ABI}")             # Output directory of final, generated library

    find_library(ANDROID_LOG_LIB log)                              # Include Android libs: https://stackoverflow.com/a/47803975/10030695
    if(NOT ANDROID_LOG_LIB)
      message(FATAL_ERROR "android log library not found")
    endif()

    include(${OpenCV_INCLUDE_DIRS}/OpenCVConfig.cmake)
    target_include_directories(${DLIB_NATIVE_NAME} ${OpenCV_INCLUDE_DIRS} include) # https://cmake.org/cmake/help/v3.6/command/target_include_directories.html
    target_link_libraries(${DLIB_NATIVE_NAME} dlib::dlib ${ANDROID_LOG_LIB})

    #add_executable(${DLIB_WRAPPER_NAME} ${DLIB_WRAPPER_NAME}.cpp)
    #add_executable(webcam_face_pose_ex webcam_face_pose_ex.cpp)
    #add_executable(face_landmark_detection_ex face_landmark_detection_ex.cpp)
    #add_executable(train_shape_predictor_ex train_shape_predictor_ex.cpp)
endif()
```
which produces the following output in Android Studio:
```
Error configuring CMake server (./Android/Sdk/cmake/3.10.2.4988404/bin).
Check for working C compiler: ./Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
Check for working C compiler: ./Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: ./Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
Check for working CXX compiler: ./Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Using CMake version: 3.10.2
Compiling dlib version: 19.16.0
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - found
Found Threads: TRUE  
 *****************************************************************************
 *** DLIB GUI SUPPORT DISABLED BECAUSE X11 DEVELOPMENT LIBRARIES NOT FOUND ***
 *** Make sure libx11-dev is installed if you want GUI support.            ***
 *** On Ubuntu run: sudo apt-get install libx11-dev                        ***
 *****************************************************************************
Searching for BLAS and LAPACK
Searching for BLAS and LAPACK
Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
Checking for module 'cblas'
  No package 'cblas' found
Checking for module 'lapack'
  Found lapack, version 0.3.3+ds
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of void*
Check size of void* - done
 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************
Building a C++11 test project to see if your compiler supports C++11
C++11 activated.
Found OpenCV: ./Application/opencv-4.0.1-android-sdk/OpenCV-android-sdk (found version "4.0.1") 
CMake Error at CMakeLists.txt:42 (target_include_directories):
  target_include_directories called with invalid arguments


Configuring incomplete, errors occurred!
See also "./Application/arnatomy/controller/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".

```
I know it says xlib11-dev is missing, but I installed it with
```
sudo apt-get install libx11-dev
```
and a rerun delivers:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libx11-dev is already the newest version (2:1.6.7-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
However, cmake from Android Studio does not find it. Similar to blas:
```
sudo apt-get install libopenblas-dev liblapack-dev
```
and rerun gives:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
liblapack-dev is already the newest version (3.8.0-1build1).
libopenblas-dev is already the newest version (0.3.3+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
However, cmake from Android Studio does not find only one and strangely the Android Studio output says:
```
Checking for module 'cblas'
  No package 'cblas' found
Checking for module 'lapack'
  Found lapack, version 0.3.3+ds
```
and you can see that Android Studio says`0.3.3+ds` should be the version of `lapack` but the console output says this is the version of `libopenblas-dev`.

## Steps to Reproduce
I guess this problem is very project specific, but it is Android Studio 3.2.1, dlib 19.6, and OpenCV for android 4.0.1, cmake 3.6.0, on Ubuntu 18.10 x64. I got dlib from this very github repository.

So how can I let cmake find xlib11-dev, libopenblas-dev, and liblapack-dev?

**Comment by ManuelTS** [comment]
No response after one month, is it really that hard? I still have no solution.

**Comment by davisking** [comment]
Maybe no one knows the answer to this question, I certainly don't.  I'm not familiar with android or its build tooling.

**Comment by ManuelTS** [comment]
However, thanks for your reply.

**Comment by ManuelTS** [comment]
I downloaded [X11 lib manually](https://sourceforge.net/projects/libx11/files/libX11-1.4.99/) and replaced your `include(FindX11)` in the file [CMakeLists.txt on line 388](https://github.com/davisking/dlib/blob/master/dlib/CMakeLists.txt#L388) with:
```
set(X11_FOUND 1)
set(X11_INCLUDE_DIR MY_ABSOLUTE_PATH/libX11-1.4.99.1-mingw32/include)
set(X11_LIBRARIES MY_ABSOLUTE_PATH/libX11-1.4.99.1-mingw32/lib)
```
Only then the build of dlib with the usage of some methods from [webcam_face_pose_ex.cpp](https://github.com/davisking/dlib/blob/master/examples/webcam_face_pose_ex.cpp) worked. Even when I added those two `include` and `lib` paths in my local `/usr/share/cmake-3.12/Modules/FindX11.cmake` file dlib using cmake, both, were  unable to locate the above files even when the paths were given. The usage of [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/v3.10/variable/CMAKE_PREFIX_PATH.html?highlight=prefix_#variable:CMAKE_PREFIX_PATH) had also no effect. I had to hardcode the linking of X11 which is definitive an error. I only write this here to give future programmers a quick and dirty local workaround.

**Comment by GavinAndre** [comment]
If you don't need to write ui in the native layer, is it not necessary to compile x11?
Openblas is used to speed up the code, I think this is necessary, I used openblas when compiling mxnet, I need to first compile openblas into a static library through ndk, then link it when compiling mxnet.
Now I am also looking for ways to add openblas to dlib on android. If I get the result, I will post it here.

**Comment by GavinAndre** [comment]
first build openblas-0.3.6

ARMV7
```shell
cd $OPENBLAS_SOURCE
export NDK=${HOME}/Android/sdk/ndk-bundle
export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
make \
    TARGET=ARMV7 \
    ONLY_CBLAS=1 \
    CC=$TOOLCHAIN/bin/armv7a-linux-androideabi21-clang \
    AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar \
    HOSTCC=gcc \
    ARM_SOFTFP_ABI=1 \
    -j4
make PREFIX=./android-openblas/armv7a install
```

ARMV8
```shell
cd $OPENBLAS_SOURCE
#将ndk目录加入环境变量
export NDK=${HOME}/Android/sdk/ndk-bundle
#将toolchain目录加入环境变量
export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
#编译ARMV8环境静态库
make \
    TARGET=CORTEXA57 \
    ONLY_CBLAS=1 \
    CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
    AR=$TOOLCHAIN/bin/aarch64-linux-android-ar \
    HOSTCC=gcc \
    -j4
#安装静态库
make PREFIX=./android-openblas/arm64 install
```

then build dlib-19.17

```shell
#!/bin/sh

export BASE_PATH=${HOME}/Android
export SDK_PATH=${BASE_PATH}/sdk
export NDK_PATH=${SDK_PATH}/ndk-bundle
export cmake=${SDK_PATH}/cmake/3.6.4111459/bin/cmake
#export OPENBLAS_HOME=${BASE_PATH}/OpenBLAS-0.3.6/android-openblas/armv7a
export OPENBLAS_HOME=${BASE_PATH}/OpenBLAS-0.3.6/android-openblas/arm64

rm -rf android_build
mkdir android_build
cd android_build

${cmake} -DANDROID_SDK=${SDK_PATH} \
    -DANDROID_NDK=${NDK_PATH} \
    -DCMAKE_TOOLCHAIN_FILE=${NDK_PATH}/build/cmake/android.toolchain.cmake \
    -DANDROID_PLATFORM=android-21 \
    -DANDROID_ABI="arm64-v8a" \
    -DANDROID_STL=c++_static \
    -DBLAS_LIBRARIES=${OPENBLAS_HOME}/lib/libopenblas.a \
    -DDLIB_NO_GUI_SUPPORT=ON \
    -DCMAKE_INSTALL_PREFIX=./android_install/arm64 \
    -DCMAKE_BUILD_TYPE=Release $@ ..

    #-DANDROID_ABI="armeabi-v7a with NEON" \
${cmake} --build . --config Release --target install -- -j16
```

**Comment by sumitacharyalives** [comment]
I am trying to build openblas for android for dlib  but getting below error.
can you please help?

CMake Error at /media/newhd_g/ADTLATEST/sdk_linux/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeTestFortranCompiler.cmake:54 (message):
  The Fortran compiler "/usr/bin/f95" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /media/newhd_f/Samples/dlib-face-recognition-android-master/OpenBLAS-0.3.7/android_build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_0ceac/fast"

  /usr/bin/make -f CMakeFiles/cmTC_0ceac.dir/build.make
  CMakeFiles/cmTC_0ceac.dir/build

  make[1]: Entering directory
  '/media/newhd_f/Samples/dlib-face-recognition-android-master/OpenBLAS-0.3.7/android_build/CMakeFiles/CMakeTmp'


  Building Fortran object CMakeFiles/cmTC_0ceac.dir/testFortranCompiler.f.o

  /usr/bin/f95
  --sysroot=/media/newhd_g/ADTLATEST/sdk_linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot
  -fPIE -c
  /media/newhd_f/Samples/dlib-face-recognition-android-master/OpenBLAS-0.3.7/android_build/CMakeFiles/CMakeTmp/testFortranCompiler.f
  -o CMakeFiles/cmTC_0ceac.dir/testFortranCompiler.f.o

  Linking Fortran executable cmTC_0ceac

  /media/newhd_g/ADTLATEST/sdk_linux/cmake/3.6.4111459/bin/cmake -E
  cmake_link_script CMakeFiles/cmTC_0ceac.dir/link.txt --verbose=1

  /usr/bin/f95
  --sysroot=/media/newhd_g/ADTLATEST/sdk_linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot
  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a
  -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel
  -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined
  -Qunused-arguments -Wl,-z,noexecstack -Wl,--gc-sections
  CMakeFiles/cmTC_0ceac.dir/testFortranCompiler.f.o -o cmTC_0ceac

  f95: error: unrecognized command line option ‘-Qunused-arguments’; did
  you mean ‘-Wunused-parameter’?

  CMakeFiles/cmTC_0ceac.dir/build.make:97: recipe for target 'cmTC_0ceac'
  failed

  make[1]: *** [cmTC_0ceac] Error 1

  make[1]: Leaving directory
  '/media/newhd_f/Samples/dlib-face-recognition-android-master/OpenBLAS-0.3.7/android_build/CMakeFiles/CMakeTmp'


  Makefile:126: recipe for target 'cmTC_0ceac/fast' failed

  make: *** [cmTC_0ceac/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  cmake/f_check.cmake:24 (enable_language)
  cmake/prebuild.cmake:87 (include)
  cmake/system.cmake:157 (include)
  CMakeLists.txt:67 (include)


-- Configuring incomplete, errors occurred!
See also "/media/newhd_f/Samples/dlib-face-recognition-android-master/OpenBLAS-0.3.7/android_build/CMakeFiles/CMakeOutput.log".
See also "/media/newhd_f/Samples/dlib-face-recognition-android-master/OpenBLAS-0.3.7/android_build/CMakeFiles/CMakeError.log".

**Comment by sumitacharyalives** [comment]
> **ndk version r20**
> 
> **build openblas-0.3.6**
> 
> ARMV7
> 
> ```shell
> cd $OPENBLAS_SOURCE
> export NDK=${HOME}/Android/sdk/ndk-bundle
> export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
> make \
>     TARGET=ARMV7 \
>     ONLY_CBLAS=1 \
>     CC=$TOOLCHAIN/bin/armv7a-linux-androideabi21-clang \
>     AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar \
>     HOSTCC=gcc \
>     ARM_SOFTFP_ABI=1 \
>     -j4
> make PREFIX=./android-openblas/armv7a install
> ```
> 
> ARMV8
> 
> ```shell
> cd $OPENBLAS_SOURCE
> #将ndk目录加入环境变量
> export NDK=${HOME}/Android/sdk/ndk-bundle
> #将toolchain目录加入环境变量
> export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
> #编译ARMV8环境静态库
> make \
>     TARGET=CORTEXA57 \
>     ONLY_CBLAS=1 \
>     CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang \
>     AR=$TOOLCHAIN/bin/aarch64-linux-android-ar \
>     HOSTCC=gcc \
>     -j4
> #安装静态库
> make PREFIX=./android-openblas/arm64 install
> ```
> 
> **build dlib-19.17**
> 
> ```shell
> #!/bin/sh
> 
> export BASE_PATH=${HOME}/Android
> export SDK_PATH=${BASE_PATH}/sdk
> export NDK_PATH=${SDK_PATH}/ndk-bundle
> export cmake=${SDK_PATH}/cmake/3.6.4111459/bin/cmake
> #export OPENBLAS_HOME=${BASE_PATH}/OpenBLAS-0.3.6/android-openblas/armv7a
> export OPENBLAS_HOME=${BASE_PATH}/OpenBLAS-0.3.6/android-openblas/arm64
> 
> rm -rf android_build
> mkdir android_build
> cd android_build
> 
> ${cmake} -DANDROID_SDK=${SDK_PATH} \
>     -DANDROID_NDK=${NDK_PATH} \
>     -DCMAKE_TOOLCHAIN_FILE=${NDK_PATH}/build/cmake/android.toolchain.cmake \
>     -DANDROID_PLATFORM=android-21 \
>     -DANDROID_ABI="arm64-v8a" \
>     -DANDROID_STL=c++_static \
>     -DBLAS_LIBRARIES=${OPENBLAS_HOME}/lib/libopenblas.a \
>     -DDLIB_NO_GUI_SUPPORT=ON \
>     -DCMAKE_INSTALL_PREFIX=./android_install/arm64 \
>     -DCMAKE_BUILD_TYPE=Release $@ ..
> 
>     #-DANDROID_ABI="armeabi-v7a with NEON" \
> ${cmake} --build . --config Release --target install -- -j16
> ```
> 
> disable x11 by `-DDLIB_NO_GUI_SUPPORT=ON`
> link openblas by `-DBLAS_LIBRARIES=${OPENBLAS_HOME}/lib/libopenblas.a`

can you please check my error?
