### ISSUE TITLE
Adding different sized layers

### ISSUE THREAD

**Issue by xsacha** [davisking/dlib#1624]
## Expected Behavior
Layers have same size I think

## Current Behavior
Layers being added have different sizes

## Steps to Reproduce
dtoc

I am converting a model to caffe and noticed the following error:
*************** ERROR CONVERTING TO CAFFE ***************
The dlib network contained an add_prev layer (layer idx 66) that adds two
previous layers with different output tensor dimensions. Caffe's equivalent
layer, Eltwise, doesn't support adding layers together with different
dimensions. In the special case where the only difference is in the number of
channels, this converter program will add a dummy layer that outputs a tensor
full of zeros and concat it appropriately so this will work. However, this
network you are converting has tensor dimensions different in values other than
the number of channels. In particular, here are the two tensor shapes (batch
size, channels, rows, cols):
 1 32 11 11
 1 64 10 10

Then I am wondering, is there an issue with my model if it is trying to add different sized layers?

**Comment by davisking** [comment]
It's fine to do this, the layer in dlib adds appropriate 0 padding.  Whether or not that makes sense for your problem domain I can't say, but it's generally fine.

**Comment by xsacha** [comment]
OK, so there's no possible way to convert to caffe with this difference? Is there any modification I could do to my model to account for this difference?

**Comment by davisking** [comment]
As far as I know caffe can't represent that network.  You need to change
the conv definitions so that the output tensors have matching shapes.
