### ISSUE TITLE
Dlib to ONNX

### ISSUE THREAD

**Issue by kevref** [davisking/dlib#1626]
Does anyone know of any tools (or efforts to create a tool) to convert a trained deep learning Dlib network to ONNX?

**Comment by headupinclouds** [comment]
I don't know of any such feature.  If you haven't seen it already, dlib does have a tool to convert models to caffe.

see: https://github.com/davisking/dlib/blob/master/tools/convert_dlib_nets_to_caffe/running_a_dlib_model_with_caffe_example.py

You could potentially just use this (many inference engines support caffe models), or use the "network visitor" infrastructure as a reference to implement the ONNX conversion.

In the case of caffe, there is some tricky arithmetic related to`ceil()` vs `floor()` discrepancies between dlib and caffe for max pooling layers, which is described in some detail in issue https://github.com/davisking/dlib/issues/803.

ONNX would be a nice addition.
