### ISSUE TITLE
Match High Resolution with Low Resolution photo [Question]

### ISSUE THREAD

**Issue by deimsdeutsch** [davisking/dlib#1629]
I have not been able to find answer for this question and it is beyond my knowledge right now.

I am matching high resolutions photos of people against the cropped photo of people in CCTV cameras which are not of good quality. So the distance of matrix of high resolution and low resolution photos is varying a lot. How do i solve this problem ?

Can this problem be managed with Jitter ?
If so how much Jitter should i set.
Thanks !

Since the data dlib was trained on is not public i can't do this adaptation my self and i ask you:

What is the average face\image size in dlib's face train dataset. Does it contain low reolution image or
is it more similar to LFW.
Do you think such a retrained model will perform better on unseen low resolution faces?
I'm using:

Dlib: 19.9
Cuda: 9.0
cudnn: 7
cmake: 3.9
compiler: Visual C++ 14.0
GPU: GeForce GTX 1070
System: Windows 10

**Comment by deimsdeutsch** [comment]
Resolved.

**Comment by satya415** [comment]
@deimsdeutsch May I know the answer for this issue **Match High Resolution with Low Resolution photo**
