### ISSUE TITLE
Affine transform in dlib library 

### ISSUE THREAD

**Issue by nakohli** [davisking/dlib#163]
Hi,

First of all, thanks for the amazing library. I have a couple of questions that I was wondering if someone can answer. I have been using the face landmark detection code for the 68 landmarks and it works beautifully. My next goal is to align the face using an affine transform. 

For this first, I developed the code via OpenCV using `warpAffine` which works but unfortunately leaks memory. It seems to work for initial images but then stops with a segmentation fault. My next thought was to only utilize dlib and do the affine projection because there are some methods in `geometry.h` for it.

For this, I am using `find_affine_transform` method to get a `point_transform_affine` object where I find the affine transformation between 3 points obtained using the shape and template. In the documentation, it is written that we can use this object to apply the transformation on vector of points. However, I have been unable to find some example for it. 

1. Could you tell me how I can apply the transformation learnt ?
2. Secondly, I have an image loaded in `array2d` object. Is there a way to go from array2d to vector of points ?

**Comment by davisking** [comment]
Thanks, I'm glad you like lib.  But github issues are for posting bugs or problems in dlib, not for asking general programming questions about C++.  For that, it is better to ask on stackoverflow.
