### ISSUE TITLE
Unable to open face_metric_sync for writing

### ISSUE THREAD

**Issue by ASShusharin** [davisking/dlib#1630]
Hi, I tried to run dnn_metric_learning_on_images_ex.cpp for training model with CUDA/cuDNN. I changed mini-batchesto 35x15 (instead of 5x5), and iterations without progress to 10000. After some time I had this error:

step#: 0     learning rate: 0.1   average loss: 0            steps without apparent progress: 0
step#: 2     learning rate: 0.1   average loss: 6.51207      steps without apparent progress: 0
step#: 84    learning rate: 0.1   average loss: 0.542683     steps without apparent progress: 0
step#: 171   learning rate: 0.1   average loss: 0.120766     steps without apparent progress: 28
step#: 257   learning rate: 0.1   average loss: 0.109494     steps without apparent progress: 24
step#: 343   learning rate: 0.1   average loss: 0.10224      steps without apparent progress: 31
step#: 429   learning rate: 0.1   average loss: 0.096992     steps without apparent progress: 118
step#: 515   learning rate: 0.1   average loss: 0.0954706    steps without apparent progress: 102
terminate called after throwing an instance of 'dlib::serialization_error'
  what():  Unable to open face_metric_sync for writing.
Aborted (core dumped)

**Comment by davisking** [comment]
You are out of disk space or don't have write access to your hard drive.
