### ISSUE TITLE
dlib in macOS

### ISSUE THREAD

**Issue by POWX** [davisking/dlib#1632]
I use this commands to run examples in macOS
**cd examples**
**mkdir build**
**cd build**
**cmake ..**
**cmake --build . --config Release**

After that 
**cmake --build . --config Release**

I have error at 48%

[ 47%] Building CXX object CMakeFiles/using_custom_kernels_ex.dir/using_custom_kernels_ex.cpp.o
[ 48%] Linking CXX executable using_custom_kernels_ex
ld: warning: could not create compact unwind for _dpbtrf_: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _dhseqr_: stack subq instruction is too different from dwarf stack size
Undefined symbols for architecture x86_64:
  "__gfortran_concat_string", referenced from:
      _dgesvd_ in liblapack.a(dgesvd.o)
      _dhseqr_ in liblapack.a(dhseqr.o)
      _dormbr_ in liblapack.a(dormbr.o)
      _dormtr_ in liblapack.a(dormtr.o)
      _dtrevc3_ in liblapack.a(dtrevc3.o)
      _dormlq_ in liblapack.a(dormlq.o)
      _dormql_ in liblapack.a(dormql.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/using_custom_kernels_ex.dir/build.make:88: using_custom_kernels_ex] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/using_custom_kernels_ex.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2

**Comment by davisking** [comment]
You have a broken BLAS library installed. You should delete it.

**Comment by POWX** [comment]
I delete libblas.a from /usr/local/lib/ (If i understand you correctly), but have the same error
