### ISSUE TITLE
Image always recognized in dlib face recognition

### ISSUE THREAD

**Issue by jenabbhatia** [davisking/dlib#1634]
Hello,
As a project i am implementing Face recognition using dlib frontal face detector in c++. But i am facing difficulties in comparing training and testing image for recognition. The code of dlib given is this:

                 `if (length(face_descriptors[i]-face_descriptors_test[0]) < 0.6)
                               win.add_overlay(faces[i],rgb_pixel(255,0,0),"recognized");`

Here i don't understand what is the formula of length or what actually it compute ? Because i have simply computed squared distance between my trained and test image stored in a vector. The code is given below:

                `for(size_t i=0;i < face_vector.size();i++)
                {
                       this_diff = (face_vector[i] - test_vector[i]) * (face_vector[i] - test_vector[i]);
                       total_diff += this_diff;             
                }

                if(total_diff < 0.6)
                {
                    val="recognized";
                    cout << val << endl;
                }`

Here face vector contains trained images stored in a directory and test vector contains real time face capture through camera. The problem is for every test image when compared with stored trained image it gives me recognized, which is wrong.
I guess the computation i am doing is somewhat wrong, that is why i want to understand what the dlib length function is doing. I will be very glad, if someone clears this doubt.

Thank you.

**Comment by AlexXandreE** [comment]
Hi,

It seems you are trying to sum the distance using more than one image, the difference between the points is suposed to be used in a 1v1 comparison as the example shows.
So you just need to mode the if (distance < 0.6) to inside the for loop.

According to: http://dlib.net/dlib/svm/sparse_vector_abstract.h.html#length 

>  returns std::sqrt(length_squared(a,a))



Hope this helps in any way.

**Comment by jenabbhatia** [comment]
Actually i wanted to calculate distance between trained image feature points and test image feature points for recognition. That's why i calculated squared distance and then i compared the total distance with 0.6(threshold). If the value is less than 0.6 then test image is similar with trained image else not similar.  Sorry I did not understand your point of moving comparison part inside for loop.

Thanks for the link it really helped.

**Comment by AlexXandreE** [comment]
Hi,
I meant that you should only compare one face descriptor at a time, by summing it up for each image you are summing up all the distances.
If you print to the screen the value of `this_diff `  it will show you the distance you should compare.
Or you are using a different aproach than the example program and your face descriptor is not a 128D vector?

**Comment by jenabbhatia** [comment]
My face descriptor is of 128-D vector. ok i got your point, i should not do the summing part? and compare the difference inside the for loop?

**Comment by AlexXandreE** [comment]
Yeah, the `this_diff` variable should be the one used for comparison, it should work ok in theory.

**Comment by jenabbhatia** [comment]
Thank you soo much

**Comment by AlexXandreE** [comment]
No problem, just let me know if it worked. I'm also not very experienced in Dlib and I know how hard it gets to solve small problems, it's a lot of documentation to go through  :)

**Comment by jenabbhatia** [comment]
Y sure i will let you know it it works.
