### ISSUE TITLE
Train a lighter model also for profile views

### ISSUE THREAD

**Issue by beraldofilippo** [davisking/dlib#164]
Hi Davis, my congratulations for this amazing library.
I'm currently developing a project which should run on a constrained environment (Android) based on dlib-android, and I'm looking for ways to obtain a model with **fewer landmarks** (hoping it would speed up the detections) but most importantly which can recognize poses at the **full profile angle** of a single person in nearly ideal illumination setup.

I guess that iBUG database does not contain profile images (please tell me if I'm wrong), therefore I've been searching for a suitable dataset which I found could be [BioID](https://www.bioid.com/About/BioID-Face-Database) which gives me all the needed poses and 20 labeled landmarks. (But feel free to suggest some more prolific alternatives!)

My question is, is it possible to train on that dataset with dlib's trainer? How much in time and cost would it take (considering BioID has 1521 images, which probably I should mirror to have enough of them)? Would it be overkill to try to translate the data into the xmls required by your trainer?
_Consider I can use a fairly powerful cluster here at my University with 14 'blades' DELL PowerEdge M600 each with:
2 quad core Intel Xeon E5450 (12MB Cache, 3.00 GHz)
16 GB RAM
2 Hard disk 72GB in RAID-1 (mirroring)_

Also, I'm following with great interest @e-fominov pull request which is way cool.

Thanks, and sorry for asking such 'challenging' questions but that's for the sake of my MSc thesis :))

**Comment by davisking** [comment]
That dataset is not too large, so it will run fine.  A much better dataset is the [ALFW](https://lrs.icg.tugraz.at/research/aflw/), dataset which I've used for this task.  

You will however need a face detector that finds profile faces as well.  You can train such a detector with ALFW data as well.

You can use @e-fominov's version, it's ready to be used.  The only reason it's not merged is because of all the cases where dlib is used by old compilers without C++11 support.  

As for those computers, 16GB of RAM is tiny.  Cheap laptops have that much RAM.  I would find other computers to use.

**Comment by beraldofilippo** [comment]
Thanks! If I manage to get a nice detector I could make it available into dlib-models, would you be ok with that?
Thanks again!

**Comment by davisking** [comment]
Sure! :)

There is also an option in imglab, --cluster, that will automatically cluster a dataset into poses.  So when you run it you should see that left looking faces fall into a different cluster than right looking faces for instance.  --cluster makes creating a dataset for training multiple poses, which you need to do, much easier.

**Comment by e-fominov** [comment]
@beraldofilippo, changing the count of facial landmark points will not affect the performance much, as the shape prediction process is extremely fast and takes less than 5 msec for one face. The most of performance problems in dlib-android have different reason (like deserializing new face detector for each frame). Here are my soggestions how to make it run faster https://github.com/tzutalin/dlib-android/issues/15

**Comment by WuerfelDev** [comment]
Hi @beraldofilippo
Did you train a model for the profile face detection? I'd be interested to try it
Thanks
