### ISSUE TITLE
Face recognition dataset

### ISSUE THREAD

**Issue by lftb** [davisking/dlib#1643]
Hello to the DLIB team, and to all the participants.

@davisking You can give us a ready base for facial recognition training?

I wanted to add my base of faces to your ready base and train anew so that it would recognize our people very well.
During the test I found out that he does not recognize our faces well.
Or you can advise something more optimal solution?

Thank you all

**Comment by davisking** [comment]
I'm not going to start hosting a new face recognition dataset.  But you don't need the data I used anyway, you can get a much larger dataset by downloading the trillion pairs dataset and the ms celeb dataset.

**Comment by axmadjon** [comment]
@davisking 
can you give approximate files to find out how they look?

I do not understand what these files should look like during training?
Do they need to be aligned already or will he be align during the training?

**Comment by axmadjon** [comment]
I apologize for not being attentive,[this johns file](https://github.com/davisking/dlib/tree/master/examples/johns)
