### ISSUE TITLE
Hidden Layer Number

### ISSUE THREAD

**Issue by langheran** [davisking/dlib#1645]
Hi Davis, please could you guide me towards the paper that inspired your intuition for building the 220-layer architecture implemented in dnn_semantic_segmentation_ex.h?

Thank you in advance 👏

**Comment by davisking** [comment]
I'm not sure if there is a paper for it.  You can see some details here: https://github.com/davisking/dlib/pull/1600.  @reunanen wrote this example, so he would know better.

**Comment by reunanen** [comment]
The U-net paper is [here](https://arxiv.org/pdf/1505.04597). But the implementation (#1600) is certainly not identical with the one in the paper.

**Comment by langheran** [comment]
Thank you so much Juha =D, I'll check the U-Net paper out.
