### ISSUE TITLE
Instance segmentation: new layer (if needed), and an example program

### ISSUE THREAD

**Issue by reunanen** [davisking/dlib#1646]
I think I need to implement _instance segmentation_. For example, this looks like a useful approach to me: https://arxiv.org/pdf/1807.10007.pdf

If someone else implements any kind of approach before I get my head around this matter, great. If not, then I might give it a try.

Any feedback or comments are very welcome.

**Comment by davisking** [comment]
Sounds cool to me.  No one else is working on it as far as I know.
