### ISSUE TITLE
array2d or matrix?

### ISSUE THREAD

**Issue by python152** [davisking/dlib#1648]
As I read through examples, the two types seems being used interchangeable way: e.g., `array2d<rgb_pixel>` or `matrix<rgb_pixel>`. What is the difference? when to use which type?

**Comment by davisking** [comment]
You can use whichever you find more convenient. There is no preference built into dlib.

For more information, read the top paragraph of http://dlib.net/imaging.html and read about the generic image interface.  It talks about how you can use any kind of image like object with dlib.
