### ISSUE TITLE
Confusing cmake message when compiler does not support `thread_local`

### ISSUE THREAD

**Issue by bch29** [davisking/dlib#165]
When the compiler doesn't support `thread_local`, as on OSX with XCode < 8.0, running cmake reports that CUDA isn't being used with the following messages:

```
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
-- *** Dlib CUDA support requires C++11 but your compiler doesn't support it. ***
```

I do in fact have cuDNN installed, and the actual issue is that the test build failed due to my compiler not supporting `thread_local`, while it does support all the other necessary C++11 features (making the C++11 support error very confusing too). It took me a long time to get to the bottom of this, so I would suggest making the warning friendlier, e.g. by indicating that `thread_local` support is the likely problem.

**Comment by davisking** [comment]
thread_local is part of C++11, so your compiler doesn't support C++11.
I'll change the cuDNN message bit though.

**Comment by davisking** [comment]
The warning messages should be better now.
