### ISSUE TITLE
dlib compiled with GPU, but does not appear to be using GPUs

### ISSUE THREAD

**Issue by stevenc317** [davisking/dlib#1650]
## Expected Behavior
I am attempting to use dlib in python scripts as part of a facial recognition system.   I have been working with Dr. Adrian Rosebrock @ pyimagesearch.com and he pointed me to you.  The goal is to use both of my GPUs instead of the CPU/RAM.

## Current Behavior
Any python script that I use ends up giving memory errors such as the following after a few minutes of execution.  I have also tried reducing the file size and reducing the batch size.

```
Traceback (most recent call last):
File "encode_faces.py", line 46, in <module>
model=args["detection_method"])
File "/home/photoid/.virtualenvs/cv/lib/python3.6/site-packages/face_recognition/api.py", line 116, in face_locations
return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
File "/home/photoid/.virtualenvs/cv/lib/python3.6/site-packages/face_recognition/api.py", line 100, in _raw_face_locations
return cnn_face_detector(img, number_of_times_to_upsample)
MemoryError: std::bad_alloc
```
If I review `top` it shows my CPU and RAM being pegged at 90%+.  I think dlib is not seeing/using my GPUs.  To test this I tried:

```
import dlib.cuda as cuda
print(cuda.get_num_devices())

```
**returns**:
```
(cv) photoid@photoid:~/system/face-recognition-opencv$ python test.py
1
```
I do not think 1 is the correct response, as I have two GPUs as shown in `nivida-smi`

```
(cv) photoid@photoid:~/system/face-recognition-opencv$ nvidia-smi
Wed Feb  6 16:09:05 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| 33%   36C    P0    27W / 120W |      0MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   34C    P0    26W / 120W |      0MiB /  6078MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+——————————————————————————————————————+
```
## Steps to Reproduce
I am not trying to 'short-change' my answer here, however I will link to the codes I have been using.  I have tried with both:
- "Face recognition with OpenCV, Python, and deep learning" (https://www.pyimagesearch.com/2018/06/18/face-recognition-with-opencv-python-and-deep-learning/)
- "Face clustering with Python" (https://www.pyimagesearch.com/2018/07/09/face-clustering-with-python/)

Either batch of codes will give the memory error (above) unless I resize the images to a ridiculous size of 250x wide and only pass 4 or 5 pictures.  

In either case, I NEVER see the usage of my GPUs when I run nvidia-smi and quickly see CPU/RAM spike.

* **Version**: master-branch
* **Where did you get dlib**: github
* **Platform**: Ubuntu Server 18.04.1 LTS 64-bit
* **Compiler**: gcc 6

Thank you :)

**Comment by stevenc317** [comment]
Slight update:

I upgraded the server from 8GB of RAM to 32GB, this fixes the `MemoryError: std::bad_alloc` error.  However, the main issue still is we are using CPU/RAM instead of GPU.

Thank you

**Comment by stevenc317** [comment]
I think the issue is dlib was installed via pip not compiled.  However, I get this error when I try to compile from source:

`(cv) root@photoid:/home/photoid/driver_downloads/dlib/build# cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
Traceback (most recent call last):
  File "/usr/local/bin/cmake", line 11, in <module>
    load_entry_point('cmake==3.13.3', 'console_scripts', 'cmake')()
  File "/usr/local/lib/python2.7/dist-packages/cmake-3.13.3-py2.7-linux-x86_64.egg/cmake/__init__.py", line 34, in cmake
    raise SystemExit(_program('cmake', sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/cmake-3.13.3-py2.7-linux-x86_64.egg/cmake/__init__.py", line 30, in _program
    return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied`

**Comment by stevenc317** [comment]
@davisking:

While cmake was installed, I guess a different version was needed?  After a fresh install of cmake via source I was able to get cmake to run on dlib. 

`sudo cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
`

>[....]
> -- Enabling CUDA support for dlib.  DLIB WILL USE CUDA 

Cmake says that CUDA will be enabled.  However when I go to install:
`python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA --set CUDA_HOST_COMPILER=/usr/bin/gcc-6`

> root@photoid:/home/photoid/driver_downloads/dlib#  python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA --set CUDA_HOST_COMPILER=/usr/bin/gcc-6
running install
running bdist_egg
running egg_info
writing requirements to dlib.egg-info/requires.txt
writing dlib.egg-info/PKG-INFO
writing top-level names to dlib.egg-info/top_level.txt
writing dependency_links to dlib.egg-info/dependency_links.txt
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
Invoking CMake setup: 'cmake /home/photoid/driver_downloads/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/photoid/driver_downloads/dlib/build/lib.linux-x86_64-2.7 -DPYTHON_EXECUTABLE=/usr/bin/python -DUSE_AVX_INSTRUCTIONS=yes -DDLIB_USE_CUDA=yes -DCUDA_HOST_COMPILER=/usr/bin/gcc-6 -DCMAKE_BUILD_TYPE=Release'
-- pybind11 v2.2.2
-- Using CMake version: 3.14.0-rc1
-- Compiling dlib version: 19.16.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found OpenBLAS library
-- Using OpenBLAS's built in LAPACK
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cuda/lib64/libcudnn.so
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA

**Comment by stevenc317** [comment]
Removing the `build` dir and recreating it fixes the issue.  I think the first time I created `build` I did not set the gcc compiler properly.

**Comment by Light--** [comment]
> Removing the `build` dir and recreating it fixes the issue. I think the first time I created `build` I did not set the gcc compiler properly.

buddy , can you see the process name appears in ```nvidia-smi``` after you compile it?
