### ISSUE TITLE
Dlib DNN model trains and converges on VS 2015/17 Communtity edition 32bit but not 64bit

### ISSUE THREAD

**Issue by dynamite-ready** [davisking/dlib#1651]
## Expected Behavior
A DNN model should output the same loss when trained in 64bit mode, as it does in 32bits.

Right now, when I train my model with Visual Studio 2015/17 Community edition in 32 bit mode (on my WIndows machine) or on OSX, the model converges after 20 epochs (It's a fairly simple model). To train the model I use the `Adam` solver with the following config:

```
dnn_trainer<netType, adam> trainer(network, adam(0.0005, 0.9, 0.999));
```

I'm also training in minibatches with `trainer.test_one_step`.
I expect to see the program perform the same on on Visual Studio 2015/17 in 64bit mode.

## Current Behavior
On Windows I setup my Dlib program with the following command `cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ..` I also build with `cmake --build . --config release`.

When training the model with the setup above the first time, the result is very similar to the result I get when running the application after compiling with `cmake -G "Visual Studio 14 2015" ..` but if I run the trainier a second time the loss, at every stage, is `nan`... Or `inf` or some inordinately large float that would never appear when running in 32 bit mode.

## Steps to Reproduce
- Create a basic, unsophisticated DNN model (mine is based on 8 basic `fc` layers. The loss layer is a `loss_mean_squared_multioutput` with 3 elements, and the input is `matrix<float, 11, 3>`).

- Train the model on both Windows 8 with the following cmake setup for the 64bit version:
`cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ..`

And this setup for the 32bit version:
`cmake -G "Visual Studio 14 2015" ..`

- Then, for both executables, let the trainer run for a few epochs, stop the program, then restart them both. Check the loss on both the 32bit executable and 64bit executable. The 32 bit version appears to output similar loss values, while the 64bit version outputs a significantly higher loss at all stages, with or without the availability of CUDA

* **Version**: I'm running from GIT commit `61a021c`
* **Where did you get dlib**: Github
* **Platform**: Appears to break on Windows 8 64bit
* **Compiler**: "Visual Studio 14 2015 Win64 (Community edition)"

**Comment by davisking** [comment]
I suspect there is something in your code that causes this, as many people train in windows without issue. Please post a complete and minimal program that exhibits this behavior so other people can reproduce it.

**Comment by dynamite-ready** [comment]
Taking the above for advice, I tried using:

`cmake -G "Visual Studio 15 2017" ..`

Instead of...

`cmake -G "Visual Studio 15 2017 Win64" ..`

And that appears to work (the loss looks a lot like the OSX version). It's extremely slow though, but I can address that by trying out 32bit CUDA.

Can't quite understand why the 64 bit compiler won't work though.
I'll try to put together an example program when there's time, but the 64bit thing is a little odd.

Thank you for the reply, it was a helpful prompt. 👍

**Comment by dynamite-ready** [comment]
Ok. Recently made a few drastic changes to my environment, and this appears to work as I want it too.
In case it helps anyone, I performed the following:

- I dumped Visual Studio Community Edition 2017 and installed 2015 (only community build officially supported by CUDA - https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html)
- Upgraded to CUDA/Cudnn v10.0
- Pulled the latest version of Dlib (`f7f6f6`)

**Comment by dynamite-ready** [comment]
Ok. I'm still experiencing the same issue, but have narrowed this down to 64bit float handling on Windows. I wouldn't know about the pro versions of Visual Studio, but there's definitely an issue with VS 2015/17 Community edition.

My investigation so far lead me to wonder if this SO ticket has anything to do with the issue I see:
https://stackoverflow.com/questions/22710272/difference-in-floating-point-arithmetics-between-x86-and-x64

**Comment by dynamite-ready** [comment]
So I think I've fixed this. For anyone who might be running into similar issues, the last few changes that appeared to fix what I was experiencing, were: 

- Setting the compiler to use `AVX` for floating point operations, instead of `SSE` (http://dlib.net/faq.html#Whyisdlibslow). Not sure how helpful it would be to change the docs to make this point more conspicuous.

- Use `double` as DNN input. Not `floats`. Very subtle. Works in some environments, but not others. Tbf, most of the examples have `double` for input, and `float` for output. So while it's not unreasonable to suspect these types are interchangeable, assume they're not. Or at least be prepared to example the effect of switching to `double` in your program.

- Double check what you're feeding in. For some reason, after these changes, on Windows, I had a 3 row matrix that I thought was blank... On OSX however, it was initialised with random cruft. Stuff like that will confound efforts to deal with the other points above.

Hope that helps someone.

**Comment by davisking** [comment]
Thanks for reporting back.

I'm skeptical about some of this though.  For instance, the DNN takes floats as input.  It doesn't matter if you started with double, because the first thing the input layer does is convert everything to float anyway. It sounds like you have some uninitialized variables in your code and that is very likely the source of the problem.

**Comment by dynamite-ready** [comment]
Indeed. It still works after switching all the doubles back to floats. So essentially, this step:

> Double check what you're feeding in. For some reason, after these changes, on Windows, I had a 3 row matrix that I thought was blank... On OSX however, it was initialised with random cruft. Stuff like that will confound efforts to deal with the other points above

Was the key.

Humbling. But I've learnt a lot.

Thanks again.
