### ISSUE TITLE
Any plans to add Gender and Age to DLIB facial identification/feature analysis??? (feature request)

### ISSUE THREAD

**Issue by kaisark** [davisking/dlib#1652]
Any plans to add Gender and Age to DLIB facial identification/feature analysis???

I heard IBM just released a new dataset that could be used for training:
https://venturebeat.com/2019/01/29/ibm-releases-diversity-in-faces-a-dataset-of-over-1-million-annotations-to-help-reduce-facial-recognition-bias/

A few of the commercial facial identification services are including Age, Gender and Emotion, etc.
https://www.faceplusplus.com/face-detection/#demo

Thanks.

**Comment by xsacha** [comment]
You can use the existing facial recognition and compare to gender cohorts (male / female) and age group cohorts (Youth, Adult, Mature, Senior) etc.
This is how face++ and others will be doing it.

You can already do this in dlib.

**Comment by davisking** [comment]
Indeed, you can do this with the existing tools and to some extent with the
published models.  You can also easily train your own models for this using
the tools in dlib.  Making this sort of thing easy to do is the point of
dlib, rather than providing many prebuilt models.
