### ISSUE TITLE
compilation link error in visual studio

### ISSUE THREAD

**Issue by santoshk17** [davisking/dlib#1656]
I was trying to compile dlib using the steps provided at http://devdoc.net/c/dlib-19.7/compile.html
for visual studio.

using VS 2015 win64.
dlib version:  dlib-19.7

On building dlib from source,  \build\dlib\Release\dlib19.16.0_release_64bit_msvc1900.lib was generated.
( online resources suggest that it should be just dlib.lib)

while trying to compile 3d_point_cloud_ex.cpp  from"...\source\examples\3d_point_cloud_ex.cpp"
getting following errors

1>LINK : warning LNK4031: no subsystem specified; CONSOLE assumed
1>source.obj : error LNK2001: unresolved external symbol jpeg_CreateDecompress
1>source.obj : error LNK2001: unresolved external symbol jpeg_destroy_decompress
1>source.obj : error LNK2001: unresolved external symbol jpeg_read_header
1>source.obj : error LNK2001: unresolved external symbol jpeg_start_decompress
1>source.obj : error LNK2001: unresolved external symbol jpeg_set_quality
1>source.obj : error LNK2001: unresolved external symbol jpeg_CreateCompress
1>source.obj : error LNK2001: unresolved external symbol jpeg_stdio_src
1>source.obj : error LNK2001: unresolved external symbol jpeg_finish_decompress
1>source.obj : error LNK2001: unresolved external symbol jpeg_std_error
1>source.obj : error LNK2001: unresolved external symbol jpeg_stdio_dest
1>source.obj : error LNK2001: unresolved external symbol jpeg_destroy_compress
1>source.obj : error LNK2001: unresolved external symbol jpeg_set_defaults
1>source.obj : error LNK2001: unresolved external symbol jpeg_read_scanlines
1>source.obj : error LNK2001: unresolved external symbol jpeg_finish_compress
1>source.obj : error LNK2001: unresolved external symbol jpeg_write_scanlines
1>source.obj : error LNK2001: unresolved external symbol jpeg_start_compress
1>E:\dliblearn\x64\Release\dliblearn.exe : fatal error LNK1120: 16 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by davisking** [comment]
Please always use the dlib.net documentation rather then some other non official instructions.

**Comment by santoshk17** [comment]
I referred to the steps provided at [http://dlib.net/compile.html](http://dlib.net/compile.html)

**Comment by crimsonBlazee** [comment]
I'm facing a similar problem with dlib right now. Were you able to find a solution to this @santoshk17 ?
