### ISSUE TITLE
Add callback function pointer for optimization

### ISSUE THREAD

**Issue by 125626748** [davisking/dlib#166]
I'm using this lib to do optimization.
but I need to change some parameters after each iteration.
I hack the code by adding a function pointer input parameter for the dlib\optimization\optimization.h
now the head look like this:
double find_min_box_constrained (
        search_strategy_type search_strategy,
        stop_strategy_type stop_strategy,
        const funct& f, 
        const funct_der& der, 
        T& x,
        double x_lower,
        double x_upper,
        		**void(*callback)()**
)

I think callback is common for many use case.

**Comment by davisking** [comment]
The f and der arguments to that function are literally already callbacks.  So this is unneeded.  Do whatever work you want to do inside f.

**Comment by 125626748** [comment]
f will be invoked several times, and I'm not so sure about derivative behavior.
but yeah it works, so doesn't matter.
