### ISSUE TITLE
[Question] .h5 model to dlib: Layer parameters match, but output is different

### ISSUE THREAD

**Issue by Raincode** [davisking/dlib#1661]
Hi,

I am trying to write a .h5 to Dlib conversion script. This works by serializing in the dlib format. So far everything seems to be working nicely for Keras.layers.Dense, and when I output the parameters in Keras and in Dlib, they match (I can deserialize my generated .dat model without issues).

However, when I run a prediction on the same input in Keras and Dlib, the outputs don't match. Would you by any chance have an idea what the issue could be here? I know this is sort of a long shot, but I figured I could still ask. I already checked that I am serializing bias_mode correctly.. Could there be something else I am overlooking? 

The Keras model looks like this (note it is very simple for testing purposes):
```
    model = Sequential()
    model.add(Dense(5, activation='relu', input_dim=2))
    model.add(Dense(2))
    model.compile(loss='mse', optimizer='adam')
```
the resulting dlib network:
```
using Net_t = 
dlib::loss_mean_squared_multioutput<
dlib::fc<2,
dlib::relu<dlib::fc<5,
dlib::input<dlib::matrix<float>>
>>>>;
```

**Comment by davisking** [comment]
No idea.  Nothing you said sounds wrong.  You probably just have a bug in your code somewhere.

**Comment by Raincode** [comment]
> You probably just have a bug in your code somewhere

I've figured it out. I was serializing this_layer_setup_called as False (because I was just looking at the default ctor parameters). Of course, hindsight is 20/20 and I should obviously set it to True, since I am importing the weights/biases. Then both predictions match as expected :)
