### ISSUE TITLE
Jetseon TX2 CUDA compile

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1664]
Hi,

I succesfully compile dlib as a shared library and installed in Jetson tx2.  dlib examples working fine.

But when I try to use in Qt with pkg-config ie . PKGCONFIG += dlib-1  it gave below error 👍 

undefined reference to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'

any idea ?

**Comment by ccl-private** [comment]
I find  a solution other where. Comment out some code in "threads/threads_kernel_shared.h" should work.

//#ifdef ENABLE_ASSERTS  
//    extern int USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives;  
//    inline int dlib_check_consistent_assert_usage() { USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives = 0; return 0; }  
//#else  
//    extern int USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_;  
//    inline int dlib_check_consistent_assert_usage() { USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_ = 0; return 0; }  
//#endif  
//    const int dlib_check_assert_helper_variable = dlib_check_consistent_assert_usage(); 

Waiting for better solutions.

**Comment by davisking** [comment]
That's not a sensible thing to do.  I put that bit of code there to detect ODR violations.  If you are getting an error from it you are messing up your build and what is likely to happen is you will get worse and harder to debug errors elsewhere.  You need to fix your inconsistent build settings.
