### ISSUE TITLE
Chinese Whisper clustering: Can we get descriptors for clustered labels

### ISSUE THREAD

**Issue by buddhashrestha** [davisking/dlib#1665]
## Expected Behavior

I'm using dlib's python chinese whisper algorithm implementation to cluster faces.
But I would like to know if we could get the approximate face descriptor for each unique label after clustering?
## Current Behavior

Currently, we only get the list of unique labels, but I want the face descriptor of those labels as well.
## Steps to Reproduce

To reproduce this, you can just run the example : [http://dlib.net/face_clustering.py.html](url) 

* **Version**:19.9.0 
* **Where did you get dlib**: pip
* **Platform**: ubuntu 17.04 
* **Compiler**:

**Comment by davisking** [comment]
There is no such thing as the "descriptor of the cluster".  It's not something that exists inside the algorithm, and mathematically there can be no such thing.  The cluster is a cloud of points, and can't be losslessly summarized with one descriptor.  You could try to use the average descriptor as a representation of the cluster, and for some problems that can work ok.  

But high dimensional geometry is less straightforward than many expect.  For example, in high dimensions, you can have two point clouds, A and B, where the distance between any element of A and another in B is always > 1.  However, the distance between mean(A) and mean(B) can be much less than 1.  For this and other reasons, simple averaging is often not super great. You have to do something that makes sense for the task you are trying to tackle.
