### ISSUE TITLE
How do I use random forest regression to train data with input vectors of 10 dimensions and output vectors of 5 dimensions?

### ISSUE THREAD

**Issue by cydcydcyd** [davisking/dlib#1668]
How do I use random forest regression to train data with input vectors of 10 dimensions and output vectors of 5 dimensions?

**Comment by davisking** [comment]
I would train 5 separate models.

**Comment by cydcydcyd** [comment]
[http://dlib.net/dlib/random_forest/random_forest_regression_abstract.h.html#random_forest_regression_trainer](url)

this page says  'Any of these kinds of more complex feature extraction patterns can be realized with the random forest tools by implementing your own feature extractor object and using it with the random forest objects.'
But I do not know how to create my own feature extractor.
I can only train the dataset with multidimensional input data and one-dimensional output data.
