### ISSUE TITLE
@

### ISSUE THREAD

**Issue by sushil-bharati** [davisking/dlib#1673]

**Comment by davisking** [comment]
Use the Intel MKL, it works with visual studio just fine.

**Comment by sushil-bharati** [comment]
Okay, I successfully integrated Intel MKL Windows 2019, Update 2 with my VS2015. What next? Is there any flag that I should turn on to let dlib start using MKL?

**Comment by davisking** [comment]
Use CMake, like http://dlib.net/compile.html says.  It will set it up. If you don't want to use cmake then you have to read the MKL manual to find out how to use it.
