### ISSUE TITLE
begin and end is not member of dlib::proxy_deserialize

### ISSUE THREAD

**Issue by Christianwidjaya** [davisking/dlib#1682]
## Expected Behavior
Expected: the  FaceReq.cpp runs
[FaceReq.zip](https://github.com/davisking/dlib/files/2934090/FaceReq.zip)

## Current Behavior
every compile does failed, and this errors pops up

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'begin': is not a member of 'dlib::proxy_deserialize'	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2320	
Error	C2039	'end': is not a member of 'dlib::proxy_deserialize'	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2320	
Error	C2672	'std::distance': no matching overloaded function found	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2320	
Error	C2780	'iterator_traits<_Iter>::difference_type std::distance(_InIt,_InIt)': expects 2 arguments - 1 provided	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2320	
Error	C2039	'begin': is not a member of 'dlib::proxy_deserialize'	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2322	
Error	C3536	'i': cannot be used before it is initialized	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2327	
Error	C2064	term does not evaluate to a function taking 3 arguments	FaceRecognition	D:\FaceRecognition\include\dlib\dnn\core.h	2327	

## Steps to Reproduce
latest dlib in this github with 8gcc warning removal, compiled cuda 10.1 and avx instruction in visual studio 2019 rc2, make a project including all dlib and opencv, and then compiling FaceReq.cpp

* **Version**: commit 663a1b7
* **Where did you get dlib**: this github repo
* **Platform**: Windows 10 64 bit
* **Compiler**: Vc16 Visual Studio 2019

**Comment by davisking** [comment]
I just built the dlib examples in visual studio 2019 and it all works fine.  You just need to debug your code.
