### ISSUE TITLE
Q: Build DLIB as dynamic link library in Windows

### ISSUE THREAD

**Issue by Mut1nyJD** [davisking/dlib#1683]
Does anybody know what is the default procedure here?

I looked at the FAQ, Sourceforge forum, DLIB website, Stackoverflow but could not find anything about this. 

Using CMAKE -DBUILD_SHARED_LIBS=1 does nothing for me. It still generates VS projects that are static linked. 

Just changing the project type to dynamic library in the dlib solution does not work either because I guess it is going to miss all the necessary __DLLSPEC statements that are required. Although it does compile if you add the 3rd party dependencies, the corresponding lib file is useless for linking it later with any example or own code.

**Comment by xsacha** [comment]
BUILD_SHARED_LIBS works for me. Just make sure it's not add_subdirectory. You need to build it by itself.

**Comment by davisking** [comment]
It should also be noted that you almost certainly don't want to use shared libraries in windows.

**Comment by davisking** [comment]
Also read this: http://dlib.net/compile.html#Installing%20dlib%20as%20a%20precompiled%20library

**Comment by Mut1nyJD** [comment]
Unlike your comment there are good reasons why you want to do this. If this is part of a larger environment and the module using DLIB it is not always used so therefore you want to use delay on demand loading of .dlls than that is the only option I am afraid.

**Comment by xsacha** [comment]
@Mut1nyJD I do build it as a shared library for a different reason:
DLIB doesn't support falling back to CPU right now so I build a CUDA version and a CPU version and dynamically load them.
