### ISSUE TITLE
Face alignment issue with cnn detector

### ISSUE THREAD

**Issue by test4fest** [davisking/dlib#1690]
I am using "face_alignment.py" example for alignment.
I only replaced the following frontal face detection with cnn detection:
 dlib.get_frontal_face_detector() 
with 
detector = dlib.cnn_face_detection_model_v1("mmod_human_face_detector.dat")
and also convert mmnod.rectangles to dlib.rectangles
rects = dlib.rectangles()
rects.extend([d.rect for d in dets])
dets = rects
Although the shape predictor works fine, the output of get_face_chip() looks like the original one (without any alignment).

**Comment by test4fest** [comment]
This issue was resolved by reading images by Opencv. 
But other issue arose: the number of undetected faces has been increased.
Is input to face detection network  RBG or BGR format?

**Comment by davisking** [comment]
RGB
