### ISSUE TITLE
Deserialization error while initializing cnn_face_detection_model_v1 with dlib_face_recognition_resnet_model_v1

### ISSUE THREAD

**Issue by kirillbobyrev** [davisking/dlib#1691]
## Expected Behavior

I'm trying to initialize `dlib.cnn_face_detection_model_v1` using `dlib_face_recognition_resnet_model_v1.dat` (or `mmod_human_face_detector.dat` to double-check).

## Current Behavior

When using `dlib_face_recognition_resnet_model_v1.dat`, dlib reports deserialization error. Trying the same with `mmod_human_face_detector.dat` yields no such error.

## Steps to Reproduce

1) Download pre-trained models:

* http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2
* http://dlib.net/files/mmod_human_face_detector.dat.bz2

2) Try to initialize `dlib.cnn_face_detection_model_v1`:

```
$ python
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 19:16:44)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> dlib.cnn_face_detection_model_v1('dlib_face_recognition_resnet_model_v1.dat')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: An error occurred while trying to read the first object from the file dlib_face_recognition_resnet_model_v1.dat.
ERROR: Unexpected version found while deserializing dlib::loss_mmod_.
>>> dlib.cnn_face_detection_model_v1('mmod_human_face_detector.dat')
<dlib.cnn_face_detection_model_v1 object at 0x7f963a0348f0>
```

## Information
* **Version**: 19.17.0 (19.16.0 compiled with Clang 7.0.1 on Arch Linux fails, too)
* **Where did you get dlib**: tried three options: installing from `pip`, from Arch Linux's AUR (https://aur.archlinux.org/packages/python-dlib/), installing from `pip` inside Anaconda environment.
* **Platform**:
1) Arch Linux + dlib from AUR/pip (with Python 3.7.2)
```
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```
2) Ubuntu 18.04 + dlib from pip within Anaconda environment (with Python 3.6.7)
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
* **Compiler**: When building from source (Arch AUR), GCC 8.2.1. When installing from pip, no compiler is used.

**Comment by davisking** [comment]
`dlib_face_recognition_resnet_model_v1.dat` is not a face detector.  So this error is appropriate.
