### ISSUE TITLE
failed to import dlib

### ISSUE THREAD

**Issue by wnpllrzodiac** [davisking/dlib#1692]
failed to import dlib in python3

I have try pip3 install dlib and install it from the source
download source and run "python3 setup.py install"

Installation is always success, but cannt import dlib in RUNTIME.
It confused me for a long time.

=========================================
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /xxxxxxxx/python3/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _gfortran_pow_i4_i4
>>

ls /usr/lib64/libgfortran* -l
lrwxrwxrwx 1 root root     20 Mar  8 13:57 /usr/lib64/libgfortran.so.3 -> libgfortran.so.3.0.0
-rwxr-xr-x 1 root root 988064 Jun 19  2018 /usr/lib64/libgfortran.so.3.0.0

nm -D /xxxxxxxx/python3/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so|grep gfor
                 U _gfortran_compare_string
                 U _gfortran_concat_string
                 U _gfortran_pow_i4_i4

nm -D /usr/lib64/libgfortran.so.3|grep pow
00000000000a2270 T _gfortran_pow_c10_i16
00000000000a14d0 T _gfortran_pow_c10_i4
00000000000a1b20 T _gfortran_pow_c10_i8
00000000000a1f80 T _gfortran_pow_c4_i16
00000000000a1210 T _gfortran_pow_c4_i4
00000000000a1870 T _gfortran_pow_c4_i8
00000000000a2110 T _gfortran_pow_c8_i16
00000000000a1390 T _gfortran_pow_c8_i4
00000000000a19e0 T _gfortran_pow_c8_i8
00000000000a1d20 T _gfortran_pow_i16_i16
00000000000a1130 T _gfortran_pow_i16_i4
00000000000a1670 T _gfortran_pow_i16_i8
00000000000a1c10 T _gfortran_pow_i4_i16
00000000000a1070 T _gfortran_pow_i4_i4
00000000000a15b0 T _gfortran_pow_i4_i8
00000000000a1c90 T _gfortran_pow_i8_i16
00000000000a10d0 T _gfortran_pow_i8_i4
00000000000a1610 T _gfortran_pow_i8_i8
00000000000a1f20 T _gfortran_pow_r10_i16
00000000000a1820 T _gfortran_pow_r10_i8
00000000000a1e20 T _gfortran_pow_r4_i16
00000000000a1760 T _gfortran_pow_r4_i8
00000000000a1ea0 T _gfortran_pow_r8_i16
00000000000a17c0 T _gfortran_pow_r8_i8

**Comment by wnpllrzodiac** [comment]
linux version as follows:

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.4 Beta (Santiago)

**Comment by davisking** [comment]
Something is wrong with your gfortran install.  You are probably missing `libgfortran.so`. You either have to fix it or install dlib telling it not to use LAPACK, and maybe BLAS.  Use `--no DLIB_USE_BLAS` and `--no DLIB_USE_LAPACK`.

**Comment by wnpllrzodiac** [comment]
nm -D /usr/lib64/libgfortran.so.3|grep pow

gfortran.so exist and the function is implemented. Anyway, I will try your suggestion, thx.

**Comment by davisking** [comment]
libgfortran.so.3 ends in `.3`.  It’s not the same file name. Run `ldd` on dlib’s .so file and see what it’s setup to link to. Probably not something ending in .3

**Comment by wnpllrzodiac** [comment]
ldd /xxxxxxxxxxxxxxxxx/python3/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007fff2d988000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5e28941000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f5e28728000)
        libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f5e28520000)
        libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f5e28304000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f5e27fc6000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f5e27db4000)
        libpng12.so.0 => /usr/lib/libpng12.so.0 (0x00007f5e27b8e000)
        libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f5e27977000)
        libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007f5e27727000)
        libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007f5e27498000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f5e27100000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5e26dfe000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5e26be8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5e26849000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003a19600000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f5e26645000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f5e26427000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5e26222000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f5e2601f000)

**Comment by davisking** [comment]
Why isn’t here any blas or gfortran listed there?  Did you run that after recompiling *without blas*?

**Comment by wnpllrzodiac** [comment]
Finally I fix it by uncomment L207 in file dlib/cmake_utils/find_blas.cmake
`# set(lapack_libraries gfortran) `
then "python3 setup.py install"

Everything become peace.
It was a really tough problem which make me overwhelmed.
Any way it was fixed!

Python 3.6.7 (default, Oct 26 2018, 16:49:56)
[GCC 7.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>>

**Comment by wnpllrzodiac** [comment]
why the line was comment out?

**Comment by davisking** [comment]
https://github.com/davisking/dlib/commit/2889e520ae297904bf480bad657de42d28c5680b

Maybe a better thing would be to use a `try_compile` to check if linking to that copy of openblas it's found is going to work without gfortran.  Really though, gfortran shouldn't be required.
