### ISSUE TITLE
Qt qmake and CUDA error

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1695]
Hi,

I compiled dlib with cmake and it found the cuda cudnn . Than  make install.

when I try to use from Qt with : 

PKGCONFIG += dlib-1

it says a bınch of error regarding to Cuda .  It is working another machine without Nvidia card.

its at the linking stage
Error:

> 
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_descriptor::set_size(int, int, int, int)':
cudnn_dlibapi.cpp:(.text+0x4b): undefined reference to `cudnnDestroyTensorDescriptor'
cudnn_dlibapi.cpp:(.text+0x6f): undefined reference to `cudnnCreateTensorDescriptor'
cudnn_dlibapi.cpp:(.text+0x99): undefined reference to `cudnnSetTensor4dDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_descriptor::get_size(int&, int&, int&, int&) const':
cudnn_dlibapi.cpp:(.text+0x3ee): undefined reference to `cudnnGetTensor4dDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::clear()':
cudnn_dlibapi.cpp:(.text+0x5e3): undefined reference to `cudnnDestroyFilterDescriptor'
cudnn_dlibapi.cpp:(.text+0x5f1): undefined reference to `cudnnDestroyConvolutionDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::~tensor_conv()':
cudnn_dlibapi.cpp:(.text+0x933): undefined reference to `cudnnDestroyFilterDescriptor'
cudnn_dlibapi.cpp:(.text+0x941): undefined reference to `cudnnDestroyConvolutionDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::pooling::clear()':
cudnn_dlibapi.cpp:(.text+0xefd): undefined reference to `cudnnDestroyPoolingDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::pooling::setup(int, int, int, int, int, int, int)':
cudnn_dlibapi.cpp:(.text+0xfe5): undefined reference to `cudnnDestroyPoolingDescriptor'
cudnn_dlibapi.cpp:(.text+0x1017): undefined reference to `cudnnCreatePoolingDescriptor'
cudnn_dlibapi.cpp:(.text+0x1054): undefined reference to `cudnnSetPooling2dDescriptor'
cudnn_dlibapi.cpp:(.text+0x162e): undefined reference to `cudnnDestroyPoolingDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::add(float, dlib::tensor&, float, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0x1f0b): undefined reference to `cudnnAddTensor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::batch_normalize(double, dlib::resizable_tensor&, dlib::resizable_tensor&, dlib::resizable_tensor&, double, dlib::resizable_tensor&, dlib::resizable_tensor&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0x2bf0): undefined reference to `cudnnBatchNormalizationForwardTraining'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::batch_normalize_gradient(double, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor&, dlib::tensor&, dlib::tensor&)':
cudnn_dlibapi.cpp:(.text+0x3b38): undefined reference to `cudnnBatchNormalizationBackward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::batch_normalize_conv_gradient(double, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor&, dlib::tensor&, dlib::tensor&)':
cudnn_dlibapi.cpp:(.text+0x4c3b): undefined reference to `cudnnBatchNormalizationBackward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::setup(dlib::tensor const&, dlib::tensor const&, int, int, int, int)':
cudnn_dlibapi.cpp:(.text+0x5729): undefined reference to `cudnnCreateFilterDescriptor'
cudnn_dlibapi.cpp:(.text+0x575a): undefined reference to `cudnnSetFilter4dDescriptor'
cudnn_dlibapi.cpp:(.text+0x5770): undefined reference to `cudnnCreateConvolutionDescriptor'
cudnn_dlibapi.cpp:(.text+0x57a0): undefined reference to `cudnnSetConvolution2dDescriptor'
cudnn_dlibapi.cpp:(.text+0x57f9): undefined reference to `cudnnGetConvolution2dForwardOutputDim'
cudnn_dlibapi.cpp:(.text+0x5884): undefined reference to `cudnnGetConvolutionForwardAlgorithm'
cudnn_dlibapi.cpp:(.text+0x58fc): undefined reference to `cudnnGetConvolutionForwardWorkspaceSize'
cudnn_dlibapi.cpp:(.text+0x5964): undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
cudnn_dlibapi.cpp:(.text+0x59dc): undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
cudnn_dlibapi.cpp:(.text+0x5a43): undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
cudnn_dlibapi.cpp:(.text+0x5ac8): undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::operator()(bool, dlib::tensor&, dlib::tensor const&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0x7272): undefined reference to `cudnnConvolutionForward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::pooling::operator()(dlib::resizable_tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0x8814): undefined reference to `cudnnGetPooling2dForwardOutputDim'
cudnn_dlibapi.cpp:(.text+0x8993): undefined reference to `cudnnPoolingForward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::softmax(dlib::tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0x99dd): undefined reference to `cudnnSoftmaxForward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::softmax_all(dlib::tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0x9dfa): undefined reference to `cudnnSoftmaxForward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::sigmoid(dlib::tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0xa253): undefined reference to `cudnnActivationForward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::relu(dlib::tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0xa6b6): undefined reference to `cudnnActivationForward'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tanh(dlib::tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0xab16): undefined reference to `cudnnActivationForward'

**Comment by MyraBaba** [comment]
cuda 10.1 by the way

**Comment by MyraBaba** [comment]
What is the working version of the Cuda and cuDNN so I can use it for avaoid problems.

**Comment by davisking** [comment]
You need to build a dlib shared library if you want to link to it without being required to link to cuda yourself.

**Comment by MyraBaba** [comment]
I managed to find that I need .so shared library. Now blas library conflicting as below:

`In file included from ../main.cpp:1:
In file included from ../../FaciTest/widget.h:9:
In file included from ../../FaciTest/camera_01.h:51:
In file included from ../../FaciTest/network.h:12:
/opt/OPENBLAS/include/cblas.h:254:6: error: conflicting types for 'cblas_dgemm'
void cblas_dgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOS...
     ^
/usr/local/include/dlib/matrix/matrix_blas_bindings.h:73:18: note: previous declaration is here
            void cblas_dgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA,
                 ^
In file included from ../main.cpp:1:
In file included from ../../FaciTest/widget.h:9:
In file included from ../../FaciTest/camera_01.h:51:
In file included from ../../FaciTest/network.h:12:
/opt/OPENBLAS/include/cblas.h:256:6: error: conflicting types for 'cblas_cgemm'
void cblas_cgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOS...
     ^
/usr/local/include/dlib/matrix/matrix_blas_bindings.h:78:18: note: previous declaration is here
            void cblas_cgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA,
                 ^
In file included from ../main.cpp:1:
In file included from ../../FaciTest/widget.h:9:
In file included from ../../FaciTest/camera_01.h:51:
In file included from ../../FaciTest/network.h:12:
/opt/OPENBLAS/include/cblas.h:260:6: error: conflicting types for 'cblas_zgemm'
void cblas_zgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOS...
     ^
/usr/local/include/dlib/matrix/matrix_blas_bindings.h:83:18: note: previous declaration is here
            void cblas_zgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA,
                 ^
In file included from ../main.cpp:1:
In file included from ../../FaciTest/widget.h:9:
In file included from ../../FaciTest/camera_01.h:51:
In file included from ../../FaciTest/network.h:12:
/opt/OPENBLAS/include/cblas.h:302:6: error: conflicting types for 'cblas_strsm'
void cblas_strsm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_SIDE Side, OPENBLAS_CONST enum CBLAS_UPLO Uplo, OPEN...
     ^`

**Comment by davisking** [comment]
`#include` dlib's headers after the others so it can see you already defined cblas types somewhere else.  It will automatically avoid defining them.

**Comment by MyraBaba** [comment]
Hi again @davisking  I have strange situation with dlib 19.17 with Cuda shared lib compile.

ubuntu 16.04
clang
cuda 10.1 and cudnn 7.5 (latest one)
When I compile dlib19.9 without cuda support and sudo make install all codes compiling without problem.

when I switch to the dlib 19.17(latest one) with cuda 👍 

cmake -DBUILD_SHARED_LIBS=1 -DUSE_AVX_INSTRUCTIONS=1 ..
sudo make install

when I try to compile I have : 

> main.o: In function `_GLOBAL__sub_I_main.cpp':                                                                    
/data/Facial-/main.cpp:(.text.startup+0x39): undefined reference to `USER_ERRO
R__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'    
worker.o: In function `_GLOBAL__sub_I_worker.cpp':                                                                
/data/Facial-/worker.cpp:(.text.startup+0x39): undefined reference to `USER_ER
ROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'  
widget.o: In function `_GLOBAL__sub_I_widget.cpp':                                                                
/data/Facial-Z01-Saftas-MileSight-Commercial-v2__/widget.cpp:(.text.startup+0x39): undefined reference to `USER_ER
ROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'  
camera_02.o: In function `_GLOBAL__sub_I_camera_02.cpp':                                                          
/data/Facial-/camera_02.cpp:(.text.startup+0x39): undefined reference to `USER
_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_
'                                                                                                                 
camera_01.o: In function `_GLOBAL__sub_I_camera_01.cpp':                                                          
/data/Facial-/camera_01.cpp:(.text.startup+0x39): undefined reference to `USER
_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_
'                                                                                                                 
camera_03.o:/data/Facial-/camera_03.cpp:(.text.startup+0x39): more undefined r
eferences to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_prepro
cessor_directives_' follow                                                                                        
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by davisking** [comment]
You really need to fill out the issue template.  I have no idea what you
might have done.
