### ISSUE TITLE
Implementation detail of dlib shape predictor trainer

### ISSUE THREAD

**Issue by liangkangzheng** [davisking/dlib#1697]
Hi,

Recently I tried to understand the implementation detail of dlib shape predictor trainer. And I found that actually the feature_pixel_values are updated at each cascade. However, the current_shapes of each samples are updated in the process of make_regression_tree, s.t. each tree at each cascade, which made the feature_pixel_values and the target no longer match. What's the logic behind?

**Comment by davisking** [comment]
You should read the paper cited in the documentation.  It explains the algorithm in detail.
