### ISSUE TITLE
Correlation Tracker Unable to Start

### ISSUE THREAD

**Issue by balajiselvaraj1601** [davisking/dlib#1698]
## Expected Behavior
I am trying to pass the opencv colour image as input to the tracker. This is a test code as of now. This will be changed to video processing. 

Commenting the Issue line, causes proper conversion between the opencv image to and from dlib image.

## Current Behavior
Error occurs when i try to carry out tracking. Unable to start the tracker.

## Steps to Reproduce

**Code Section**

#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>
#include <dlib/image_io.h>
#include <dlib/opencv.h>
#include "dlib/matrix.h"

#include "opencv2/core/core.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/imgcodecs/imgcodecs.hpp"
#include "opencv2/videoio/videoio.hpp"
#include "opencv2/objdetect/objdetect.hpp"
#include "opencv2/core/utility.hpp"
#include <opencv2/opencv.hpp>

#include <vector>
#include <stdio.h>
#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <time.h>

using namespace dlib;
using namespace cv;
using namespace std;

int main()
{
	Mat frame= imread("sample.png");
	dlib::cv_image<bgr_pixel> correct(frame);
	correlation_tracker tracker;
       /************************************  Issue Line *******************************************/
	tracker.start_track(correct, dlib::centered_rect(dlib::point(93,110), 38, 86));
       /**********************************************************************************************/
	Mat temp=	dlib::toMat(correct);	
	namedWindow("Display");
	imshow("Display" , temp);
	waitKey(0);
}

**Building Command:**
g++ -std=c++11  sample.cpp   -o sample_proj `pkg-config --cflags --libs opencv dlib-1`

**Error:**
/tmp/ccfroENo.o: In function `dlib::lapack::binding::gesvd(char, char, int, int, double*, int, double*, double*, int, double*, int, double*, int)':
sample.cpp:(.text._ZN4dlib6lapack7binding5gesvdEcciiPdiS2_S2_iS2_iS2_i[_ZN4dlib6lapack7binding5gesvdEcciiPdiS2_S2_iS2_iS2_i]+0x91): undefined reference to `dgesvd_'
/tmp/ccfroENo.o: In function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
sample.cpp:(.text._ZN4dlib13blas_bindings10cblas_gemmENS0_11CBLAS_ORDERENS0_15CBLAS_TRANSPOSEES2_iiidPKdiS4_idPdi[_ZN4dlib13blas_bindings10cblas_gemmENS0_11CBLAS_ORDERENS0_15CBLAS_TRANSPOSEES2_iiidPKdiS4_idPdi]+0x71): undefined reference to `cblas_dgemm'
collect2: error: ld returned 1 exit status

**Platform:**
Ubuntu 16.04.6 LTS

**Version**
dlib-19.10 from github

**Compiler:** 
g++
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

**Comment by davisking** [comment]
Use cmake, it will link to things for you.  But if you don't want to use cmake then read the instructions: http://dlib.net/compile.html.  You in particular are getting linker errors for missing LAPACK symbols.  Link to whatever LAPACK you compiled dlib against.

**Comment by nizqsut** [comment]
> ## Expected Behavior
> I am trying to pass the opencv colour image as input to the tracker. This is a test code as of now. This will be changed to video processing.
> 
> Commenting the Issue line, causes proper conversion between the opencv image to and from dlib image.
> 
> ## Current Behavior
> Error occurs when i try to carry out tracking. Unable to start the tracker.
> 
> ## Steps to Reproduce
> **Code Section**
> 
> #include <dlib/image_processing.h>
> #include <dlib/gui_widgets.h>
> #include <dlib/image_io.h>
> #include <dlib/opencv.h>
> #include "dlib/matrix.h"
> 
> #include "opencv2/core/core.hpp"
> #include "opencv2/highgui/highgui.hpp"
> #include "opencv2/imgproc/imgproc.hpp"
> #include "opencv2/imgcodecs/imgcodecs.hpp"
> #include "opencv2/videoio/videoio.hpp"
> #include "opencv2/objdetect/objdetect.hpp"
> #include "opencv2/core/utility.hpp"
> #include <opencv2/opencv.hpp>
> 
> #include 
> #include <stdio.h>
> #include 
> #include <stdlib.h>
> #include <string.h>
> #include <assert.h>
> #include <time.h>
> 
> using namespace dlib;
> using namespace cv;
> using namespace std;
> 
> int main()
> {
> Mat frame= imread("sample.png");
> dlib::cv_image<bgr_pixel> correct(frame);
> correlation_tracker tracker;
> /************************************ Issue Line _******************************************/ tracker.start_track(correct, dlib::centered_rect(dlib::point(93,110), 38, 86)); /******************************************_***************************************************/
> Mat temp=	dlib::toMat(correct);
> namedWindow("Display");
> imshow("Display" , temp);
> waitKey(0);
> }
> 
> **Building Command:**
> g++ -std=c++11 sample.cpp -o sample_proj `pkg-config --cflags --libs opencv dlib-1`
> 
> **Error:**
> /tmp/ccfroENo.o: In function `dlib::lapack::binding::gesvd(char, char, int, int, double*, int, double*, double*, int, double*, int, double*, int)': sample.cpp:(.text._ZN4dlib6lapack7binding5gesvdEcciiPdiS2_S2_iS2_iS2_i[_ZN4dlib6lapack7binding5gesvdEcciiPdiS2_S2_iS2_iS2_i]+0x91): undefined reference to `dgesvd_'
> /tmp/ccfroENo.o: In function `dlib::blas_bindings::cblas_gemm(dlib::blas_bindings::CBLAS_ORDER, dlib::blas_bindings::CBLAS_TRANSPOSE, dlib::blas_bindings::CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)': sample.cpp:(.text._ZN4dlib13blas_bindings10cblas_gemmENS0_11CBLAS_ORDERENS0_15CBLAS_TRANSPOSEES2_iiidPKdiS4_idPdi[_ZN4dlib13blas_bindings10cblas_gemmENS0_11CBLAS_ORDERENS0_15CBLAS_TRANSPOSEES2_iiidPKdiS4_idPdi]+0x71): undefined reference to `cblas_dgemm'
> collect2: error: ld returned 1 exit status
> 
> **Platform:**
> Ubuntu 16.04.6 LTS
> 
> **Version**
> dlib-19.10 from github
> 
> **Compiler:**
> g++
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu Thread model: posix gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

Meets the same problem and try to fix now.

**Comment by nizqsut** [comment]
> Use cmake, it will link to things for you. But if you don't want to use cmake then read the instructions: http://dlib.net/compile.html. You in particular are getting linker errors for missing LAPACK symbols. Link to whatever LAPACK you compiled dlib against.

In my case there's LAPACK.  cmake prints information like these:
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   Found lapack, version 0.2.20+ds
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library

**Comment by nizqsut** [comment]
> Use cmake, it will link to things for you. But if you don't want to use cmake then read the instructions: http://dlib.net/compile.html. You in particular are getting linker errors for missing LAPACK symbols. Link to whatever LAPACK you compiled dlib against.

I used dlib in Qt. And I had link to LAPACK  by "LIBS += -L/usr/lib/x86_64-linux-gnu/openblas -llapack"
