### ISSUE TITLE
DNN on 3D image 

### ISSUE THREAD

**Issue by neuralthink** [davisking/dlib#1699]
I am trying to build a DNN for 3D image segmentation as the model mentioned here [https://github.com/ellisdg/3DUnetCNN](url). Actually i am trainning to reproduce the model with dlib. 
My question : is-it possible to do the same architecture with Dlib to deal with 3d images ? 
Additionaly to the layer for 4D convolusion as mentioned here [https://github.com/davisking/dlib/issues/989](url). Have i other tings to implement before i can make the model ? 
Thanks you a lot.

**Comment by davisking** [comment]
The DNN tooling in dlib is mainly for regular 2d images.  If you can get by
by putting all the information into the depth channels of an image then you
are good to go. But otherwise it might not be a good fit.
