### ISSUE TITLE
Porting to armv7 on iOS

### ISSUE THREAD

**Issue by itkingdom** [davisking/dlib#17]
Hello,
Is there anyone try to port dlib to iOS? Or knowning any repository which already there?

Thank you!

**Comment by davisking** [comment]
I haven't used it on iOS but my impression from users who have is that they
didn't need to modify anything to get it working.  Have you tried compiling
any of the examples on iOS?

**Comment by itkingdom** [comment]
Thank you, I will try and let you know the result later :)

**Comment by 0312birdzhang** [comment]
Hello,is it works well?
I build it on armv7hl(Jolla),but not work.
```
[nemo@Jolla ~]$ python3
Python 3.4.3 (default, Sep 17 2015, 18:09:44) 
[GCC 4.8.3 20140106 (Mer 4.8.3-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/dlib-18.17.100-py3.4-linux-armv7l.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /usr/lib/libboost_python-mt.so.1.51.0: undefined symbol: PyClass_Type
>>> 

```

**Comment by davisking** [comment]
Dlib works fine in that environment.  The problem is your copy of boost python is installed improperly.
