### ISSUE TITLE
calling Jitter_image() causes attribute error

### ISSUE THREAD

**Issue by adellelin** [davisking/dlib#1701]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

Jitter_image() causing attribute error

## Expected Behavior

I'm calling the dlib.jitter_image() function, passing in a cv2 image array, int and boolean value. I'm not clear what to expect, the documentation says it returns a list of jittered images. I'm trying to use this function for image augmentation.

## Current Behavior

  File "is-face.py", line 53, in detectFace
    dlib.jitter_image(bgrImg, 5, True)
AttributeError: module 'dlib' has no attribute 'jitter_image'

## Steps to Reproduce

import dlib
img = /path/to/image.png
bgrImg = cv2.imread(img)
dlib.jitter_image(bgrImg, 5, True)

* **Version**:  19.4
* **Where did you get dlib**:  conda install dlib
* **Platform**:  np112py36_blas_openblas_201  [blas_openblas]  conda-forge
* **Compiler**:  using python3.6

**Comment by davisking** [comment]
You need a newer version of dlib.
