### ISSUE TITLE
Dlib compilation issue  with cuda

### ISSUE THREAD

**Issue by hassanahmed95** [davisking/dlib#1703]
Dear Davis,
I have installed Dlib on my system by Sudo pip3 install dlib
But still dlib.DLIB_USE_CUDA returns False.
My system’s GPU supports cuda. I want to compile Dlib with cuda support? Actually, I am using CNN based face detector of dlib, and it is too slow on live video stream. Therefore I want to use Dlib with cuda support to make it fast.

Btw, I am using Geforce GTX 1080  gpu.

## Expected Behavior
I think dlib.DLIB_USE_CUDA should return True.

## Current Behavior
Current issue is that my Dlib's CNN based face detector is too slow. It also returns dlib.DLIB_USE_CUDA as False. I tried  to compile it  following your instruction, but still fail.

## Steps to Reproduce

* **Version**: I am using latest version of Dlib.
* **Where did you get dlib**:  I installed from Sudo pip install dlib 
* **Platform**: I am using Ubuntu 16.04
* **Compiler**:

**Comment by davisking** [comment]
Install with —verbose and you will see messages about what it’s doing and why. For instance, maybe you don’t have cudnn installed.

**Comment by hassanahmed95** [comment]
Actually I am quite newbie. Can you give me a favor to share any helping link, where I can go through in details about installation process. .  Thanks in anticipation .

**Comment by davisking** [comment]
Google install cudnn. You can get it from nvidia’s web site. You just downloaded it and run the installer.

**Comment by hassanahmed95** [comment]
You mean, I just need to install cudnn then run Python setup.py file (which is for dlib)  .. .   Did I get it right??

**Comment by davisking** [comment]
Yes, assuming you also have cuda installed.

**Comment by hassanahmed95** [comment]
Hmm ok got it. Can you please tell me that how I can know that Dlib  has successfully complied with cuda.? Does dlib.DLIB_USE_CUDA will return true, or is there any other way to check it.. Thanks for your cooperation . .

**Comment by davisking** [comment]
dlib.DLIB_USE_CUDA tells you this.

**Comment by hassanahmed95** [comment]
-- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found suitable version "9.0", minimum required is "7.5")
-- DID NOT FIND CUDA
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA



Now I am finding that issue. Can you please give me hint that how to solve it.  Thanks

**Comment by davisking** [comment]
You don't have cuda installed correctly.  Uninstall cuda, then go to the NVIDIA website and follow their instructions for installing cuda.  Do not follow any other instructions on the net or blog posts or anything else.  There are lots of bad instructions out there and they will mess it up.  The NVIDIA website has simple instructions and if you follow them it will work.

**Comment by hassanahmed95** [comment]
Thanks for letting me know. But I think Cuda is installed on my system . Check this.
Mu cuda version is 9.0. Isn't it?? Waiting for reply.


hassanahmed@PC193:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by Davidrjx** [comment]
@hassanahmed95, here pip installation should be for CPU, so i think GPU counterpart should be compiled from glib source code with  DLIB_USE_CUDA=1.
