### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#1709]
Hi,

Is there any way to use the dlib http_server
to accept and handle multipart/form-data

I know you can send multipart/x-mixed,
as discussed in an other issue.

But how can the server handle classic multipart on the receiving end

**Comment by davisking** [comment]
I'm not sure to be honest.  I haven't looked at this stuff in quite a while.  The server in dlib doesn't do a whole lot though and generally it's up to you do parse this stuff, which should be possible.
