### ISSUE TITLE
[Error]ImportError cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tcz717** [davisking/dlib#171]
First, I compiled Boost.Python in my centos server.
`sudo ./bjam toolset=gcc  --build-type=complete --layout=versioned  --with-python install`
or
```
./bootstrap.sh
sudo ./b2 install
```
then no matter I using `pip install` or `python setup.py install` , after installing dlib, I always get following error:

> Traceback (most recent call last):
>   File "avrface.py", line 7, in <module>
>     import dlib
>   File "/usr/lib64/python2.7/site-packages/dlib-19.0.99-py2.7-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
>     from .dlib import *
> ImportError: libboost_python-gcc48-mt-1_61.so.1.61.0: cannot open shared object file: No such file or directory

But `libboost_python-gcc48-mt-1_61.so.1.61.0` has been successfully installed in `/usr/local/lib`.
And I also tried `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`, however it dosen`t help.

**Comment by davisking** [comment]
I don't know why it's not working but you haven't installed it correctly somehow.  From the error, it looks like your LD_LIBRARY_PATH is not set correctly.

**Comment by tcz717** [comment]
when I run my scripts without `sudo`, it works successfully.
thanks.

**Comment by DongHwanJang** [comment]
@tcz717 did you successfully uninstalled 'sudo installed dlib'? I'm having the same problem, but reinstalling without sudo doesn't solve my problem..
