### ISSUE TITLE
Compiling dnn_mmod_face_detection_ex.cpp with CUDA enabled gives rise to linker errors

### ISSUE THREAD

**Issue by DorianAppeldoorn** [davisking/dlib#1710]
Hello.  I have the following problem:

I configured dlib with CMake with CUDA enabled. Cuda directory was found. The CUDA test program was built succesfully and the CMake output made clear that CUDA would be used in dlib:

`Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib`
`Enabling CUDA support for dlib.  `
`DLIB WILL USE CUDA`
`C++11 activated.`

Now I did everything exactly like the instructions on your website. To build my example, I included the dlib/all/source.cpp file in my program. When I compile without defining DLIB_USE_CUDA, everything compiles perfectly and it works, but when I add that flag, I get unresolved external symbol errors from the linker (function definitions not found), all from the CUDA namespace: `dlib::cuda`.

## Expected Behavior
DLIB_USE_CUDA should enable CUDA and then the functions that would make use of the GPU, like the convolutional network in the dnn_mmod_face_detection_ex.cpp example.

## Current Behavior
It compiles, but won't link when DLIB_USE_CUDA  is enabled (works perfectly when disabled). The functions which are not found are all from the `dlib::cuda` namespace, more specifically, all functions with tensors in them (cuDNN problem maybe?).

## Steps to Reproduce
I followed the exact instructions:
1) clone dlib from github
2) create directory dlib/build
3) configured everything with CMake gui
4) CMake output was fine, no complaints when building the cuda project.
5) Build example project dnn_mmod_face_detection_ex.cpp with dlib/all/source.cpp and DLIB_USE_CUDA enabled

I also want to add some notes, as I've read around the fora first for possible reasons of failure:

- the cudnn_test project builds perfectly.
- I did not get any of the 'see FAQ 1/2' errors
- I tried linking to the dlib .lib file instead of using the dlib/all/source.cpp file, which also failed
- I only have one CUDA version and one cuDNN version installed. The paths are correctly set up in the environment variables.
- CUDA and cuDNN have worked well in other places before (I used tensorflow with it, as well as some of my own CUDA software)

I followed all the instructions perfectly, multiple times even, just to be sure, but to no avail.

Do you have an idea of where the problem might be coming from? What am I missing?

Thanks in advance!

* **Version**: 19.17.99 (latest version on GitHub)
* **CUDA version**: v9.0 (the one that's compatible with VS2015 build tools)
* **cuDNN version**: v7.0
* **Where did you get dlib**: This repo.
* **Platform**: Windows 10 64-bit
* **Compiler**: Visual Studio 2015 compiler (MSBuild 14.0)

**Comment by davisking** [comment]
What you are describing isn't what's listed in the instructions on http://dlib.net/compile.html.  Please follow the instructions http://dlib.net/compile.html.  It tells you what to type to get it working.

**Comment by Davidrjx** [comment]
@DorianAppeldoorn i am not clear about problem you issued about link error?

**Comment by DorianAppeldoorn** [comment]
Sorry, Davis! I indeed did not follow your instructions clearly. I was confused by the building process. The thing that solved it for me was using: 

`cmake --build . --target install --config Release`

instead of 

`cmake --build . --config Release`

That installed it for me into the program files directory, which made it easily linkable like any other library. 

This might be something useful to add to the dlib/compile page, as it is not mentioned for installing dlib on Windows.

Thanks for the responses, Davis! (also on my other question) 
Much appreciated that you take the time to answer to any question, even if it's a silly one!

**Comment by Davidrjx** [comment]
thanks for reply

At 2019-04-12 22:39:19, "DorianAppeldoorn" <notifications@github.com> wrote:


Sorry, Davis! I indeed did not follow your instructions clearly. I was confused by the building process. The thing that solved it for me was using:

cmake --build . --target install --config Release

instead of

cmake --build . --config Release

That installed it for me into the program files directory, which made it easily linkable like any other library.

This might be something useful to add to the dlib/compile page, as it is not mentioned for installing dlib on Windows.

Thanks for the responses, Davis! (also on my other question)
Much appreciated that you take the time to answer to any question, even if it's a silly one!
