### ISSUE TITLE
CUDA exception in "wait_for_transfer_to_finish()"

### ISSUE THREAD

**Issue by mgilge** [davisking/dlib#1711]
Hi Davis,
I am having an issue with "wait_for_transfer_to_finish()" in gpu_data.cpp, which is timing out.
Does dlib need to be the exclusive user of CUDA? 
Is there a way to restrict dlib to 1 of my 2 multiprocessors?

There is a restriction for CUDA in Jetson: 
> Concurrent access is not supported on Jetson.
> That means you need to follow below rule or a bus error/segmentation fault will occur.
> process_1 > Sync > process_2 > sync > process_1 > ...

BR 
Michael

Version: dlib 19.17
Platform: NVIDIA Jetson TX2
Toolchain: gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

**Comment by davisking** [comment]
Dlib does not need any special access to the GPU.  You control which GPUs dlib uses just as you would any CUDA code, by calling `cudaSetDevice` or using the `CUDA_VISIBLE_DEVICES` environment variable.

**Comment by mgilge** [comment]
If dlib is configured to use CUDA, in your example `dnn_face_recognition_ex.cpp` does the pose detector 
`full_object_detection shape = sp(cimg, r);`
actually use CUDA or is the call to the neural net the only user of CUDA?

**Comment by davisking** [comment]
Only the neural network stuff uses cuda.

**Comment by mgilge** [comment]
Hi Davis, is there a possibility to accelerate the neural network using NEON on ARM platforms lacking CUDA?

**Comment by davisking** [comment]
That’s not a current dlib feature.
