### ISSUE TITLE
problem for deserialize a matrix<float,0,1>

### ISSUE THREAD

**Issue by goodgoodstudy92** [davisking/dlib#1712]
version of dlib: 19.17
platform : ubuntu18.04
complier:cmake 3.10

hi Davis:
    I am working on dnn_face_recognition_ex.cpp, I want to serialize face feature in redis,the face feature should be a matrix<float,0,1> form, so I use std::ostringstream sout to store the serialized feature( serialize(face_descriptors[i], sout)  ), and using sout as the value of redis. But when I deserialized from redis,the error occur:
              Error deserializing object of type int64
                        while deserializing a floating point number.
                        while deserializing a dlib::matrix
sorry for my poor english, hope you can understand my question: )

**Comment by Raincode** [comment]
Hi,
I think it would make helping you a lot easier if you could provide a minimal code example which produces your error :)

**Comment by goodgoodstudy92** [comment]
this is the code I try to drop serialized data in redis:


//faces' feature stored in vector
std::vector<matrix<float,0,1>> face_descriptors = net(faces);

Redis* new_r = new Redis();
for (size_t i = 0; i < face_descriptors.size(); i++)
{
	//trying to connect with redis
	if(!new_r->connect("127.0.0.1",6379))
	{
		cout<<"connect error"<<endl;
	}
	ostringstream sout;		
	serialize(face_descriptors[i],sout);
        //store key and value in redis
	new_r->set(to_string(i),sout.str());
		
}
delete new_r;


Redis* sec_r = new Redis();
for (size_t i = 0; i < face_descriptors.size(); i++)
{
	if(!sec_r->connect("127.0.0.1",6379))
	{
		cout<<"connect error"<<endl;
	}
	string strval;
        //get serialized data from redis
	strval = sec_r->get(to_string(i));
	istringstream sin;
	sin.str(strval);
	matrix<float,0,1> trans_face_embedding;
	deserialize(trans_face_embedding,sin);
	cout<<"deserialize data : "<<trans_face_embedding<<endl;
}
delete sec_r;
