### ISSUE TITLE
Android compiling errors

### ISSUE THREAD

**Issue by netcat88** [davisking/dlib#1713]
## Expected Behavior

The goal is to find the face landmarks in native code for an android application.

## Current Behavior

Android studio reports that in shape_predictor.h, line 227:

feature_pixel_values[i] = get_pixel_intensity(img[p.y()][p.x()]);

img is not an array; plus opening generic_image.h a lot of errors get reported.
I believe these are not the only cases Android studio discovers in the entire dlib code.

## Steps to Reproduce

I can share my code but I simply integrated (and I know it's correct) dlib into an android project.

* **Version**:  19.17
* **Where did you get dlib**:  github repo
* **Platform**:  Android
* **Compiler**:  Gradle 3.3.2

**Comment by xjohnxjohn** [comment]
where the source code you built for android? I used it before in face recognition/face detection/ face shape prediction and working correctly it android.
