### ISSUE TITLE
Error while calling cudaGetDevice(&the_device_id) in file c:\dlib 19.7\dlib\dnn\gpu_data.cpp:178. code: 999, reason: unknown error

### ISSUE THREAD

**Issue by nxp01** [davisking/dlib#1719]
**Brief Summary of the Issue** 

This error occurs when i run the MMOD face detector example with the following cmd 
command - 
> dnn_mmod_face_detection_ex mmod_human_face_detector.dat faces/dogs.jpg

Before running this example i get CUDA toolkit & cuDNN - 
CUDA ToolKit - v10.1
cuDNN           - v7.1

I have it under these paths - 
D:\cudnn-9.0-windows10-x64-v7.1\cuda
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA 

I compile using the following command - 
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:/Opencv/build;D:/cudnn-9.0-windows10-x64-v7.1/cuda" ..

It finds CUDA , cudnn & works fine. But after i run the example by copying the required .dat 
file , it throws up the error in initialization step. 

Its occurring when trying to read the dat file at these lines 
-> deserialize(argv[1]) >> net; ( in dnn_mmod_face_detection_ex.cpp )
-> CHECK_CUDA(cudaGetDevice(&the_device_id)); ( in gpu_data.cpp Line 178 )  

I am unable to get what is the problem here as it hasn't returned a valid message. Do 
you know the reason for this? 

### ## Expected Behavior - 

-> The example is works fine when run on CPU and is detecting faces in input images. 
-> When i use CUDA i am expecting same behavior at a higher speed. 

### ## Current Behavior

Get this following run-time error - 
-> Error while calling cudaGetDevice(&the_device_id) in file c:\dlib 
     19.7\dlib\dnn\gpu_data.cpp:178. code: 999, reason: unknown error
-> Is failing in deserializing dat file.  

**## Steps to Reproduce**

 Steps Followed -> 

Step 1 - Creating build folder & compiling examples with this command 
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:/Opencv/build;D:/cudnn-9.0-windows10-x64-v7.1/cuda" ..

Step 2 - cmake --build . --config Release ( compile in release mode ) 

Step 3 - Copy mmod_human_face_detector.dat to release 

Step 4 - Running the application in cmd - 
dnn_mmod_face_detection_ex mmod_human_face_detector.dat faces/dogs.jpg
 

* **Version**: 
19.7

* **Where did you get dlib**: 

I got it from dlib.net 

* **Platform**: 

Windows 10 64-bit 

* **Compiler**: 

Visual Studio 2017 ( MSbuild 15 )

I am new to Dlib & CUDA , any support would be of great help.

**Comment by davisking** [comment]
This isn't a dlib error, CUDA is telling you there is something wrong with
the CUDA install on your machine.  You also wouldn't need to set
CMAKE_PREFIX_PATH if cuda was correctly installed as cmake would find it
automatically.
