### ISSUE TITLE
Cant Initiali neural network inside class

### ISSUE THREAD

**Issue by RoboEvangelist** [davisking/dlib#172]
I wonder what the problem is here when I declare my neural network. It tells me the function does not exist.

#include <dlib/mlp.h>
typedef dlib::mlp::kernel_1a_c mlp_trainer_type;
Class MyClass:
 public:
     MyClassConstructure()
    {
          /// After declaration, how do I initialize my_neural_network_ here?
          // my_neural_network_(5, 5);  ????
     }
  private:
       **/* this part fails, even without using the typedef. */**
       mlp_trainer_type mouth_neural_network_;

Here is the error:

error: no matching function for call to ‘dlib::mlp_kernel_c<dlib::mlp_kernel_1>::mlp_kernel_c()

Am I missing an updated version of mlp?

Here is also a link:
[http://stackoverflow.com/questions/38648624/dlib-mlpkernel-1a-c-member-initialization-inside-a-class](url)

Thanks

**Comment by RoboEvangelist** [comment]
Now, I have been using the SVM code in my class, and it works. It's just the MLP that does not want to work.

**Comment by davisking** [comment]
That's not valid C++ code, that's why it doesn't work.  Specifically, you can't call a member variable's constructor from within another function.  There are a list of good C++ books here where you can learn C++ syntax: http://dlib.net/books.html

**Comment by RoboEvangelist** [comment]
It's good that is a syntax issue. I wonder why this works for my svm ovo trainers, etc. I always grab all the objects I use from the dlib examples.

**Comment by RoboEvangelist** [comment]
So, I get the error cause there is no default constructure for the MLP class. That was a tricky one.
