### ISSUE TITLE
the layout of weights of convolution layers and fc layers

### ISSUE THREAD

**Issue by Aspirinkb** [davisking/dlib#1722]
I want to know the layout of the weights of convolution layers and fully-connect layers in Dlib. I know that the shape of a filter / kernel tensor is [filter_height, filter_width, in_channels, out_channels] in TensorFlow. So what's the shape of the weights in Dlib?

**Comment by davisking** [comment]
I don't remember and would have to look at the code to find out.  It's probably the same though as dlib just uses cudnn.  The layer objects don't have much code in them, so you can see what they do easily by looking.

**Comment by Aspirinkb** [comment]
Thank you Davis. I find the code snippet in the `setup` function of `con_` class in the layers.cpp file as following:   
```C++
filters = alias_tensor(num_filters_, sub.get_output().k(), filt_nr, filt_nc);
biases = alias_tensor(1,num_filters_);
```   
So I think the convolution layer's weights shape is `[out_channels, in_channels, filter_height, filter_width]`. What do you think?

**Comment by davisking** [comment]
That looks to be the case.

**Comment by Aspirinkb** [comment]
Similar to `con_`, `fc_` class's `setup` function has code snippet:   
```
weights = alias_tensor(num_inputs, num_outputs);
if (bias_mode == FC_HAS_BIAS)
{
        biases = alias_tensor(1,num_outputs);
        // set the initial bias values to zero
        biases(params,weights.size()) = 0;
}
```
