### ISSUE TITLE
Python module: ROC curve.

### ISSUE THREAD

**Issue by sbelharbi** [davisking/dlib#1724]
Hello,
       Thanks for this great work!
Sorry for the issue, but I have a simple question.
I installed, using `pip install dlib`, the Python API (dlib version: 19.17.0) to use it with my Python code.
I was looking for the function [compute_roc_curve](http://dlib.net/ml.html#compute_roc_curve) in Python. I didn't find it. I read somewhere that not all the functionalities were implemented in the Python module. I want to make sure that I am not missing something. Thanks!

The reason I came to this library is that I am trying to compute the ROC curve for a large set (~26 million points). Using [sikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html), it takes ~15seconds on CPU (on the server, and ~8seconds on my computer). I am looking for something faster.

If the dlib's Python module does not implement ROC curve, is there a way to call the C++ one from Python?
Many thanks!

**Comment by davisking** [comment]
It's not in the pyhton API.  You can call C++ stuff from python by defining a binding using pybind11.  That's how all of dlib is made callable from python.  You can see the code for doing this in the tools/python folder, which is where all of dlib's python binding code lives.  You can also read the excellent pybind11 documentation.

**Comment by sbelharbi** [comment]
Thank you Davis for your quick and helpful reply!
I'll check pybind11 to see how to do it. [on the TODO list].
I close this issue.
Thanks!

**Comment by davisking** [comment]
No problem :)
