### ISSUE TITLE
Ability to choose CUDA architectures that dlib compiles for

### ISSUE THREAD

**Issue by xsacha** [davisking/dlib#1726]
## Expected Behavior
Ability to choose CUDA architectures that dlib compiles for

To target multiple architectures we need to pass -gencode to CUDA_NVCC_FLAGS but -arch already exists.

## Current Behavior
Always targets sm_30

## Steps to Reproduce
Compile dlib

* **Version**: master
* **Where did you get dlib**: github
* **Platform**: Windows
  64-bit --> Yes
* **Compiler**: MSVC

**Comment by davisking** [comment]
Do you get better performance when targeting a newer architecture? It may simply be worth changing cmake to use a newer setting rather than adding more options. But I don’t want to do anything unless it really impacts performance or some other important feature.

**Comment by xsacha** [comment]
I think it does affect performance but haven't tested on dlib specifically. I know OpenCV recommends each arch be compiled in rather than use PTX. It does seem to make a big difference there.
Recently I had trouble with Turing cards performance in OpenCV which seems to be resolved by compiling for the arch 75.
I'm having a similar issue in dlib where it is hitting 100% cpu on my Tesla T4 and had hoped to test this.

**Comment by davisking** [comment]
Yeah, I wouldn’t be surprised if there was a speed up. We should check though. However, since dlib uses cudnn for the heavy stuff there might not be any real speed up, since cudnn is already compiled and the arch settings in dlib’s cmake files don’t affect it.

**Comment by xsacha** [comment]
Ah I see. Still confused about why the Turing card is being hit so hard for cpu interrupts. Will have to profile it.

**Comment by davisking** [comment]
CUDA uses a lot of spinlocks, so you will very often see a cpu sitting at
100% when using CUDA applications.

**Comment by xsacha** [comment]
The spinlocks should only be for syncing. I think I have minimised these. I'm getting about 10-20% cpu on the other cards and can get up to 90% GPU utilisation. The Turing cards are stuck at under 10% GPU. I'll have a closer look today.

**Comment by xsacha** [comment]
Was Nvidia driver bug fixed in 425.
