### ISSUE TITLE
which loss layer

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#1727]
Hi,

i want to create a network which gets 2 images as an input and should output if those 2 images show the same type of object.

Right now i started with a loss_multiclass_log with 2 outputs
(outputs: 1 0 for same type objects,  0 1 for not the same type)

I input the 2 images as 1 via join_rows call.

so my questions are

1. what sort of loss layer is good for such a task?
2. is it good pratice to input 2 images as 1 (via join row for example)

best wishes

**Comment by davisking** [comment]
I would use the metric learning loss.  See http://dlib.net/ml.html#loss_metric_, there are examples showing how to do this kind of thing with it.  That's not to say that for some applications there might not be phenomenological reasons to use something else, like maybe something like what you mentioned.  But in general metric learning is more convenient.

**Comment by VisionEp1** [comment]
Would loss_metric also work with new images. 

Lets say i train it with 10 000 Images of different categories.

If i input 2 completely new images of the same (but a never trained) category.
Will the output of those 2 images be close?

**Comment by davisking** [comment]
Yeah, that’s the kind of thing it’s for.

**Comment by VisionEp1** [comment]
thanks!
