### ISSUE TITLE
Getting the affine transform used in extract_image_chip from python

### ISSUE THREAD

**Issue by dtmoodie** [davisking/dlib#1728]
I'm interested in training an object detector that can also predict the affine transform for a face to align it for further facial recognition.  To do that I'd like to use the affine transform from get_face_chip, as far as I can tell I would need to reimplement extract_image_chips  from https://github.com/davisking/dlib/blob/f95560787aee66d9f2427fed7ccffdfdfacfadd5/dlib/image_transforms/interpolation.h to be able to get that affine transformation.  Does anyone know of an easier way or an implementation that exists to do that?

**Comment by davisking** [comment]
I would call the C++ implementation from python.  You can easily do this
using pybind11.  See, for example, tools/python/src for dlib's pybind11
code.
