### ISSUE TITLE
How to merge multiple .dat files to create predictor using Dlib python?

### ISSUE THREAD

**Issue by vasanthhr** [davisking/dlib#1729]
Hello,

This related to Python API:

Could you please guide me how to merge multiple ".dat" predictor files to pass into dlib.shape_predictor("merged dat files")

```
predictor1.dat
predictor2.dat
predictor3.dat
```

Finally need to merge all these three predictor files into one dat file or pass all these three files into dlib.shape_predictor("merged dat files") .

**Comment by davisking** [comment]
That’s not something that makes sense to do. Each file is a separate and unrelated object instance.

**Comment by vasanthhr** [comment]
Hello @davisking 

Please help me to understand the below concept.

What I mean to say here is.

Assume i have totally 10 folders  and each contains 1000 images. And each folder has XML files (labeled file).

So  I thought to train a single model with all these folder images.

Can you help me on these below questions ?

Do you want me to merge all these folders into one folder images and all XML files into one XML file?.

Or, Any looping condition can I apply to pass this folder and respective XML file to below method ?
( dlib.train_shape_predictor(xml, name, options) )

**Comment by davisking** [comment]
Look at the xml files.  You can essentially paste them together to make one big file.
