### ISSUE TITLE
cmake build failed when compile dlib.so for python

### ISSUE THREAD

**Issue by Jolly23** [davisking/dlib#173]
err msg:
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
error: cmake build failed!

I have run "python setup.py install" on Ubuntu 16.04 server in python virtualenvwrapper, it begin compilation, but in the end print err_msg. 

What should I do?

**Comment by davisking** [comment]
Something is wrong with your python install.  I would install python and libpython with apt-get.
