### ISSUE TITLE
Fine-tuning face recognition resnet model

### ISSUE THREAD

**Issue by tomaszgrygiel** [davisking/dlib#1730]
Hi,
i'm working on fine-tuning model from file `dlib_face_recognition_resnet_model_v1.dat`. I've read in another issue that the simplest way to do it is to load net from the file, and then perform dnn training on my dataset (as shown in `dnn_introduction`). The problem is - the example trains net from scratch and uses already implemented function for preparing train set - and I'm not sure how to prepare data for fine-tuning. Is there any example code that can help me?

**Comment by zengjiechuan** [comment]
you can see dnn_metric_learning_on_images_ex.cpp, it may help you.
