### ISSUE TITLE
Using dnn from 19.16 in 19.13

### ISSUE THREAD

**Issue by fizmatbfu** [davisking/dlib#1731]
Hello, Davis.

I made dnn model in dlib version 19.16 and saved it in file .dat. I can load this model in dlib 19.16 (deserialization works fine).
Now i need run this model in dlib version 19.13, and deserialization throws next exception:
"An error occured while trying to read the first object from the file network.dat.
ERROR: Unexpected version found while deserializing dlib::mmod_options"

Can i solve this problem? Is it possible to use dnn model from dlib19.16 in dlib19.13 and what should i do for this?
Thanks.

* **Version**: 19.13
* **Where did you get dlib**: dlib.net
* **Platform**: win64
* **Compiler**: MSVC

**Comment by davisking** [comment]
no
