### ISSUE TITLE
Quantize the DNN model to integer

### ISSUE THREAD

**Issue by harshkn** [davisking/dlib#1733]
Hi, I have train many custom models on custom data using DLIB and they are working great. Now I am trying to optimise the speed of inference. I am looking at two things.
1 - Convert the model weights into a 8 bit integer representation. 
2 - Provide a single interface for GPU and CPU.

I would like to know if 1 and 2 is possible in an easy way. I mean like setting a flag or something. 

if NOT, if anyone has done it , can you please provide some pointers. I am trying to convert the weights into integer by computing the max and min of the float weights and then quantizing them to its integer (0-255). That is the easy part, but I want the inference to be done on this quantized weights. Any idea ? Thank you in advance.

Has anyone succeeded in doing (2) ?

**Comment by davisking** [comment]
There aren't tools in dlib for doing this at the moment.  So unfortunately
you are on your own.

**Comment by harshkn** [comment]
Thanks for your response @davisking . I will figure it out :)
