### ISSUE TITLE
quantum_computing_ex.cpp does not compile

### ISSUE THREAD

**Issue by Lecrapouille** [davisking/dlib#1734]
SHA1 d9af22e53697d3fe676231be4f3432c84c8b3872 On Debian 9.8 AMD 64-bits I got this compilation error when compiling examples (while I compiled successfully recently on Ubuntu 18.04 32-bits on older desktop that I do not have access right now so unknown SHA1).

```
../../src/init2.c:52: MPFR assertion failed: p >= 2 && p <= ((mpfr_prec_t)((mpfr_uprec_t)(~(mpfr_uprec_t)0)>>1))
/home/qq/dlib/examples/quantum_computing_ex.cpp: In function ‘void shor_decode(dlib::quantum_register&)’:
/home/qq/dlib/examples/quantum_computing_ex.cpp:77:6: internal compiler error: Abandon
 void shor_decode (
      ^~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/quantum_computing_ex.dir/build.make:62 : la recette pour la cible « CMakeFiles/quantum_computing_ex.dir/quantum_computing_ex.cpp.o » a échouée
```

**Comment by Lecrapouille** [comment]
Retried with SHA1 8001b924e63ac920a9047610ece2e4e6266e8a4c no longer see this error.

**Comment by fatalfeel** [comment]
i have this error too.........
when i assign my opencv dir
cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DDLIB_USE_CUDA=ON -DUSE_SSE2_INSTRUCTIONS=ON -DUSE_SSE4_INSTRUCTIONS=ON -DOpenCV_CONFIG_PATH=/opt/opencv/share/OpenCV -DOpenCV_DIR=/opt/opencv/share/OpenCV

**Comment by fatalfeel** [comment]
its the dlib::rand rnd;  - problem
after comment all rnd build is ok
