### ISSUE TITLE
 CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by abdou31** [davisking/dlib#1735]
Hello , 
I have problems when i try to compile dlib , i dont't know the source of this error ,
Any Ideas?
+ https://i.imgur.com/Fu1QLPD.png

Thanks

**Comment by davisking** [comment]
Use newest dlib version.

**Comment by abdou31** [comment]
I solved my problem by upgrade CMAKE and DLIB and i cmake Openface 
But for now i get other problems on visual studio 2017 
Did you have any idea about how to solve those problems?

https://i.imgur.com/ycQB9F6.png

Thanks ,

**Comment by davisking** [comment]
Don’t post screenshots.

**Comment by abdou31** [comment]
I don't understand you!!!?

**Comment by davisking** [comment]
Please post text, not links to imgur.

**Comment by abdou31** [comment]
I have posted text , i understand what you mean, 
Please see my previous comment
