### ISSUE TITLE
Is there a way to tell dlib that boost is somewhere other than it expects?

### ISSUE THREAD

**Issue by AlexMcConnell** [davisking/dlib#174]
I'm trying to put dlib on an AWS Lambda instance, which basically means I need dilb and boost in the same self-referencing folder structure.

e.g.
/anything
  /lib
    /boost
    /dlib

I haven't been able to find a way to make dlib work like this. It might help if compiling using setup.py could see the BOOST_LIBRARYDIR and BOOST_ROOT environment variables, which would presumably allow me to use relative paths.

**Comment by davisking** [comment]
I would build directly using the CMake project in tool/pyhton.  That's all the setup.py file does.
