### ISSUE TITLE
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ToNYLin66** [davisking/dlib#1743]
I customized build Dlib 19.17 with Cmake 3.13 VS2015 Win64  Cuda 10.1 cudnn 7.5 through all steps and install in my Anaconda vir-env. I try the scrips without "ace_recognition.face_encodings" can run,  but I try  facerec_from_video_file.py and it occurs these errors. How can I fix this problem?

(Dlib-Python3.6-GPU) D:\Program\face_recognition(Python)>python facerec_from_video_file.py
Traceback (most recent call last):
  File "facerec_from_video_file.py", line 20, in <module>
    lmm_face_encoding = face_recognition.face_encodings(lmm_image)[0]
  File "D:\Anaconda3\envs\Dlib-Python3.6-GPU\lib\site-packages\face_recognition\api.py", line 210, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
  File "D:\Anaconda3\envs\Dlib-Python3.6-GPU\lib\site-packages\face_recognition\api.py", line 210, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
RuntimeError: Error while calling cudaStreamSynchronize(stream) in file D:\Download\dlib-19.17\dlib\cuda\gpu_data.cpp:101. code: 700, reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaStreamDestroy() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered

* **Version**:  19.17
* **Where did you get dlib**:  dlib.net
* **Platform**:  Win10 Python 3.6
* **Compiler**:  Cmake 3.13,  Win10 VS2015 U3 64bit

**Comment by sshazly** [comment]
I've seen this error occur more frequently when other applications are using your GPU at the same time (maybe you forgot your monitor was plugged to the same GPU device you are targeting)

try running nvidia-smi to see what applications are running on which GPU, also print the device name alongside the ID in your application since I've seen the cuda library swap the ids of my 2 GPUs compared to the nvidia-smi output.

Otherwise if you have an RTX card the following [comment](https://github.com/davisking/dlib/issues/1513#issuecomment-1495221525) may help (TLDR, try calling get_net() before train_one_step)
