### ISSUE TITLE
get_best_function_eval returns NaN when global_function_search is initialized with an empty initial eval list

### ISSUE THREAD

**Issue by tsoernes** [davisking/dlib#1747]
## Expected and Current Behavior
When initializing `global_function_search` in Python with an empty `initial_function_evals` list, `get_best_function_eval` always returns an empty/nan result.
```
optimizer = dlib.global_function_search(
    [spec],
    initial_function_evals=[],
    relative_noise_magnitude=noise_mag
)
# Run evaluations ....
print(optimizer.get_best_function_eval())
# >>>(dlib.vector([]), nan, 0)
```
However, if the optimizer is instead initialized in this manner, then `get_best_function_eval` returns the best eval as it should
```
optimizer = dlib.global_function_search(
    [spec]
)
optimizer.set_relative_noise_magnitude(noise_mag)
```

* **Version**: 
dlib                               19.17.0   

* **Where did you get dlib**: 
pip
* **Platform**: 
Fedora 29 x64
* **Compiler**:

**Comment by davisking** [comment]
Yeah, that's not right.  Thanks for reporting this.  I just pushed the fix to github.
