### ISSUE TITLE
PyPi release for v19.0

### ISSUE THREAD

**Issue by AbdealiJK** [davisking/dlib#175]
There seems to be no PyPi release for v19.0

**Comment by davisking** [comment]
Right.  There isn't really any exciting change for the python tools in v19.0.

**Comment by AbdealiJK** [comment]
The Unicode decode error in setup.py which occurs when installing dlib was fixed in 19.0
Not exciting, but bug fix.

**Comment by davisking** [comment]
Yeah, that's a good point.  I'll update on PyPi layer today or tomorrow.

**Comment by davisking** [comment]
Added v19.0 to PyPi.  Just a sdist though.

**Comment by AbdealiJK** [comment]
Looks good, sufficient for me at the moment :) (As I do not use windows)
