### ISSUE TITLE
how to extend shape_predictor_194_face_landmarks.dat?

### ISSUE THREAD

**Issue by essalahsouad** [davisking/dlib#1752]
I have a shape_predictor_194_face_landmarks.dat but I need to add more points to the face(for example 210 points instead to 194), I'm wondering if is' it possible, and should I modifier in the annotations files(add the extern points positions ) and retrain the shape_predictor_194_face_landmarks.dat or there is something else ???

**Comment by davisking** [comment]
You modify the training data and retrain.

**Comment by essalahsouad** [comment]
@davisking thank you

**Comment by kms2229** [comment]
where to get shape_predictor_194_face_landmarks.dat
