### ISSUE TITLE
jpeg_loader not working

### ISSUE THREAD

**Issue by julian59189** [davisking/dlib#1754]
## Expected Behavior
train the shape predictor

## Current Behavior
`exception thrown!
jpeg_loader: error while reading 2007_007763.jpg`

## Steps to Reproduce
clone dlib (19.17.99)
run `cmake .. && make`
execute: `./train_shape_predictor_ex ../faces/`

* **Version**: 19.17.99
* **Where did you get dlib**: github
* **Platform**: MacOS
* **Compiler**: clang

I works just fine with dlib-19.7. Not entirely sure what it going wrong

**Comment by davisking** [comment]
I'm not able to replicate this.  Does this happen with dlib 19.16 or 19.13?  When does it start happening?

**Comment by anazh** [comment]
I have this problem too;

Version: 19.17
Where did you get dlib: dlib.net
Platform: debian
Compiler: make
