### ISSUE TITLE
Clang-compiler warning -Wimplicit-fallthrough

### ISSUE THREAD

**Issue by JVApen** [davisking/dlib#1755]
## Expected Behavior
Compiler warning free code, independent of the compiler when available via the standard.

## Current Behavior
Compiler warnings for G++ are being suppressed via a comment `// fall through` iso the C++17 `[[fallthrough]];` attribute.
dlib/matrix/../general_hash/murmur_hash3.h:218:13: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]

## Steps to Reproduce
Reproducible on compiler explorer: https://gcc.godbolt.org/z/tLNC6R
clang++ -O3  -std=c++2a -Wimplicit-fallthrough -Wsystem-headers -stdlib=libc++ t.cpp

#include <dlib/matrix.h>
void f() { dlib::matrix<std::vector<double>, 0, 1> TypeVector{}; }

* **Version**: Trunk
* **Where did you get dlib**: Compiler explorer
* **Platform**: Issue is platform independent, I've managed to reproduce with clang-cl on windows 64-bit, as linux (compiler explorer)
* **Compiler**: Clang-cl (7.0.0), clang++ (trunk)

**Comment by davisking** [comment]
Thanks for reporting.  I just pushed a change that should address this.

**Comment by JVApen** [comment]
Thanks a lot, just a small remark from my end, VS2017 does support fall through as well. Might be easier to maintain if you would check on __has_cpp_attribute(fallthrough) (See: https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros)

**Comment by davisking** [comment]
I would rather just block msvc. It has terrible standards support. In 5 or 6 years when it finally gets c++17 support I’ll switch the code around.
