### ISSUE TITLE
detect faces when head rotates different angles

### ISSUE THREAD

**Issue by bchen3** [davisking/dlib#1757]
Hi, i extracting face rects using AVMetaDataObject, and pass the rects to dlibWrapper to get landmark points, which are then drawn on the video image(rendered by either OpenCV or openGL) .

It works perfectly fine when detected face's rollAngle is approximately less than 30 degrees ( or more than 330 degrees, saying i'm holding my iphone in landscape with home button on the left and front camera on).  HOWEVER,  all points stop moving along with face when rollAngles is out of the above range. Why is this happening? Please help me! Thanks.

**Comment by davisking** [comment]
The model isn’t trained on data with roll angles that large. You need to train a new model using appropriate data.

**Comment by bchen3** [comment]
Got it, Thank you so much, I'll give it a try. Btw, getting immediate response from davisking feels like making handshakes with the creator of DLIB Kingdom....wowww....exciting.....

**Comment by bchen3** [comment]
One more question: it's possible to train my personal model to meet customed requirement, isn't it? I need your official confirmation. Thanks again!

**Comment by bchen3** [comment]
Since it's mentioned somewhere in the documents that "for any input rect where left > right and top > bottom, it represents an empty value". BUT quite unexpectedly, I'm able to produce very accurate landmarks when camera roates 180 degrees (or face upside down ), by arbitrarily redefining left = rect.origin.x + rect.size.width,  right = rect.origin.x,  top = rect.origin.y + rect.size.height,  and bottom = rect.origin.y. According to your documents, this should be wrong, but it just works.  Am I doing this by chance or if there's actually a mathematical equation that governs the transformation so I don't have to retrain the predictor model to get what I want???

**Comment by davisking** [comment]
There is no `origin` field of the `dlib.rectangle`.  So you must be doing something else.

**Comment by bchen3** [comment]
The rect i'm using is extracted from AVMetaDataObject (ios), expressed as a rectangle, where an origin point of (0.0, 0.0) represents the top-left corner of an unrotated picture and (1.0, 1.0) represents the bottom-right corner of an unrotated picture.

**Comment by davisking** [comment]
Ok, well, I'm not familiar with that.  In dlib a rectangle isn't anything complex.  It's just an axis aligned box.

**Comment by bchen3** [comment]
Hi davisking, 



i'm very sorry but i have to ask you the question i know you hate answering over and over again. Why my jpeg_loader not working?



 i'm using dlib in my ios app for getting face landmarks, and it works pretty well. But errors of jpeg_loader reading images occur when I'm trying to use dlib's frontal_face_detector for better face detection results instead of extracting face bound out of AVMetaDataObject. 



ERROR#1: when <dlib/gui_widgets.h> is include, it reports ""DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to", "Also make sure you have libx11-dev installed on your system";


ERROR#2: when <dlib/gui_widgets.h> is NOT include, it reports "libc++abi.dylib: terminating with uncaught exception of type dlib::image_load_error: jpeg_loader: error while reading /private/var/mobile..."



And yes, DLIB_NO_GUI_SUPPORT:BOOL=OFF, and DLIB_JPEG_SUPPORT:BOOL=ON in cmakeCache.txt; 
And yes, i do have x11 installed on my mac (xQuartz);
and yes, I did add DLIB_PNG_SUPPORT and DLIB_JPEG_SUPPORT and other flags, even though I built dlib through cmake; 






THIS IS MY DLIB.MM FILE IN XCODE:

/////////////////////////////////////////////////////////////////


#import <dlib/image_loader/jpeg_loader.h>
#import <dlib/image_processing.h>
#import <dlib/gui_widgets.h>
#import <dlib/image_io.h>
#import <iostream>
#import <dlib/image_processing/frontal_face_detector.h>
#import <dlib/array2d.h>
#import <dlib/matrix.h>
#import "FaceDetectionDlibWrapper.h"
#import <UIKit/UIKit.h>
#import <CoreImage/CoreImage.h>


@implementation FaceDetectionDlibWrapper {
    dlib::shape_predictor predictor;
    dlib::frontal_face_detector detector;
}


- (instancetype)init
{
    self = [super init];
    if (self) {
        NSString *modelFileName = [[NSBundle mainBundle] pathForResource:@"shape_predictor_68_face_landmarks" ofType:@"dat"];
        NSLog(@"modelFileName: %@", modelFileName);

        std::string modelFileNameCString = [modelFileName UTF8String];
        dlib::deserialize(modelFileNameCString) >> predictor;
        
        detector = dlib::get_frontal_face_detector();
        [self faceDetector];        
    }
    return self;
}



- (void)faceDetector
{
    dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();
    NSString *imagePath = [[NSBundle mainBundle] pathForResource:@"hillary_clinton" ofType:@"jpg"];
    
    dlib::array2d<dlib::rgb_pixel> img;
    std::string fileName = [imagePath UTF8String];
    
    dlib::load_jpeg(img, fileName);
    dlib::pyramid_up(img);
    std::vector<dlib::rectangle> dets = detector(img);
   
    if (dets.size() == 0) {
        return;
    }
    
    for (int i = 0; i < dets.size(); i++) {
        draw_rectangle(img, dets[i],dlib::rgb_pixel(0, 255, 255));
    }
}







BELOW IS HOW I COMPILE DLIB DOWNLOADED FROM GITHUB:

/////////////////////////////////////////////////////////////////
~ cd Downloads/dlib-master/examples
~ mkdir build
~ cd build
~ cmake -G Xcode .. -DUSE_SSE4_INSTRUCTIONS=ON
~ cmake --build . --config Release




BELOW IS CMAKE STATUS INFO:

/////////////////////////////////////////////////////////////////

-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMake version: 3.14.0
-- Compiling dlib version: 19.17.99
-- Enabling SSE4 instructions
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found system copy of libpng: /usr/local/lib/libpng.dylib;/usr/lib/libz.dylib
-- Found system copy of libjpeg: /usr/local/lib/libjpeg.dylib
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.1")
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found LAPACK library
-- Found CBLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- DID NOT FIND CUDA
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bo/Downloads/dlib-master/examples/build





please help me out with this, looking forward to your reply. thanks!


bo





------------------ 原始邮件 ------------------
发件人: "Davis E. King"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 凌晨0:31
收件人: "davisking/dlib"<dlib@noreply.github.com>;
抄送: "陈波"<1132756202@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [davisking/dlib] detect faces when head rotates different angles(#1757)




Ok, well, I'm not familiar with that.  In dlib a rectangle isn't anything complex.  It's just an axis aligned box.
