### ISSUE TITLE
makedocs doesn't work on Mac

### ISSUE THREAD

**Issue by gitclem** [davisking/dlib#1759]
makedocs doesn't work on Mac.  (Mac unix tools differ ever so slightly but incompatibly from Linux.)

## Expected Behavior
Docs should build without errors

## Current Behavior
./makedocs
awk: syntax error at source line 1
 context is
	/set\(CPACK_PACKAGE_VERSION_MAJOR/{ >>>  match($2,"\"(.*)\"", <<< 
awk: illegal statement at source line 1
awk: illegal statement at source line 1
awk: syntax error at source line 1
 context is
	/set\(CPACK_PACKAGE_VERSION_MINOR/{ >>>  match($2,"\"(.*)\"", <<< 
awk: illegal statement at source line 1
awk: illegal statement at source line 1
awk: syntax error at source line 1
 context is
	/set\(CPACK_PACKAGE_VERSION_PATCH/{ >>>  match($2,"\"(.*)\"", <<< 
awk: illegal statement at source line 1
awk: illegal statement at source line 1
Testing environment for needed utilities
All needed utilities found
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Getting the git change logs for 590a9a11b198ef7ecc3cbebb819c54816829fb4c..HEAD
sed: -i may not be used with stdin
  **** failed to complete **** 

## Steps to Reproduce

1. build htmlify in tools directory and copy htmlify to /usr/local/bin
2. cd dlib/docs
3. ./makedocs

* **Version**: 19.17.0 . (not easy to find!)
* **Where did you get dlib**:  github repo
* **Platform**:  Mac OS X 10.14.4 64 bit . (BSD Unix variant)
* **Compiler**:  Mac version of date and sed and awk version 20070501.  Mac doesn't have a --version option for date and sed.

I tried to replace but the date error didn't go away.  It wasn't obvious where the error was occurring....

    DATE_TODAY=`date --date= "+%b %d, %Y"`;

with:

    DATE_TODAY=`date "+%b %d, %Y"`;

The other errors weren't readily obvious to me.

**Comment by davisking** [comment]
You can download the docs from dlib.net. You don’t need to run this. I don’t intend for it to work everywhere.
