### ISSUE TITLE
OpenCV not Found

### ISSUE THREAD

**Issue by crosofg** [davisking/dlib#176]
Although opencv is installed and its path is included in the env variable, the make process shows that OpenCV not installed.
```
F:\Technology\Learning\dlib\dlib\examples\build>cmake ..
-- C++11 activated (compiler doesn't have full C++11 support).
-- Enabling SSE2 instructions
OpenCV not found, so we won't build the webcam_face_pose_ex example.
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Technology/Learning/dlib/dlib/examples/build
```

**Comment by davisking** [comment]
Apparently it's not set or installed correctly :)

That CMake file uses CMake's built in find opencv support.  So if it doesn't work then either you installed opencv wrong or (unlikely) you have a broken version of CMake.

**Comment by crosofg** [comment]
How to set it? What should be the path variable?

**Comment by davisking** [comment]
Modify the cmake script so the opencv find command isn't quiet.  The output
of cmake will then tell you what to do.

**Comment by crosofg** [comment]
```
F:\Technology\Learning\dlib\dlib\examples\build>cmake ..
-- C++11 activated (compiler doesn't have full C++11 support).
-- Enabling SSE2 instructions
-- OpenCV ARCH: x86
-- OpenCV RUNTIME: vc14
-- OpenCV STATIC: OFF
CMake Warning at C:/opencv/build/OpenCVConfig.cmake:163 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:125 (find_package)


CMake Warning at CMakeLists.txt:125 (find_package):
  Found package configuration file:

    C:/opencv/build/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.


OpenCV not found, so we won't build the webcam_face_pose_ex example.
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Technology/Learning/dlib/dlib/examples/build

F:\Technology\Learning\dlib\dlib\examples\build>
```


'''
OPENCV_DIR  C:\opencv\build\x64\vc11\bin

```

**Comment by mowkee** [comment]
You need to add the OpenCV directory in your Path as well as create a variable called `OpenCV_DIR`. add the bin directory to your path for example mine is located at `H:\lib\opencv\build\install\x64\vc14\bin` and then point to the root of your opencv folder in your `OpenCV_DIR` variable mine is `H:\lib\opencv\build\install`. I have built OpenCV from source. If you install it using a binary distribution it will look different.

**Comment by davisking** [comment]
The simplest way is usually to set `CMAKE_PREFIX_PATH` to wherever you put opencv.  For example
```
cd /wherever/you/put/opencv/
mkdir build
cd build
cmake ..
# build opencv
make

cd /wherever/you/put/dlib/examples/build
cmake .. -DCMAKE_PREFIX_PATH=/wherever/you/put/opencv/build
```
