### ISSUE TITLE
Training pre training with own dataset

### ISSUE THREAD

**Issue by abdou31** [davisking/dlib#1760]
Hello ,
I'm setting a system that should detect iris region with landmarks 
I want to use shape predictor to training pretrained model .dat with custom dataset ( images of iris regions ) 
How can i do that ?

**Comment by yyf1986** [comment]
use imglab to tag  your own data,then run train_shape_predictor.py

**Comment by abdou31** [comment]
I have cloned this project 

> https://github.com/italojs/facial-landmarks-recognition-

So what arguments should i have to training my own dataset ?
How to organize my own dataset ? ( Images and Labelling )  
Did you have any idea?
