### ISSUE TITLE
Upgrade dlib's jpeg lib

### ISSUE THREAD

**Issue by VirgileD** [davisking/dlib#1765]
## Expected Behavior
I would like to use jpeg_mem_src but this function is not included in the jpeg library included in dlib

## Current Behavior
The function is not known

* **Version**: 19.17
* **Where did you get dlib**: dlib.net
* **Platform**: it does works on an ubuntu server (with the system lib libjpeg-dev) but I have to make it work on both linux and windows; on windows I would like to rely on the jpeg lib shipped within dlib but it's a release 6b of 27-Mar-1998.
* **Compiler**: on windows, gcc (Rev2, Built by MSYS2 project) 6.2.0

So the questions are: do you plan to upgrade the jpeg lib shipped with dlib to the last jpeglib release? Is there a reason not to (I can handle that I think, with a pull request)?

and, by the way as this is the first time I send a message, I'm still amazed by dlib, not only what I can do with it but also how I keep learning good c++ code through its wonderful in-code documentation. Tx a thousand times.

**Comment by davisking** [comment]
I'm not planning on updating the libjpeg packaged with dlib, but I'm certainly not adverse to having someone else update it.  So if you want to submit a PR that does it that would be cool.

And thanks, glad you like dlib :)

**Comment by VirgileD** [comment]
done: https://github.com/davisking/dlib/pull/1769
