### ISSUE TITLE
Installation Error on Windows 10

### ISSUE THREAD

**Issue by naufil-hassan-confiz** [davisking/dlib#1767]
Hi @davisking , 

I have downloaded latest files from this repository and installed it using (python setup.py install) command. However I keep getting this error
![image](https://user-images.githubusercontent.com/45620633/57839769-b71cac00-77e0-11e9-90c6-58d9ae4b8497.png)

Please let me know how to solve it.

**Comment by davisking** [comment]
Did you read the error message you posed?  Seems like it's telling you the
problem.

**Comment by naufil-hassan-confiz** [comment]
Yes I did read it and tried to correct it some way.
During installation these folders are created at the start and then are recreated at the end, that is when I get this error.
I wanted to know how to fix it ?
I even tried deleting dlib_python.vcxproj file during installation, even that gave me same creation error during installation

**Comment by ConformalTomb** [comment]
Davis, the file lib.win-amd64-3.5 is created when you build using cmake before running the setup.py install.
But when you run Setup.py install, it throws this error.

**Comment by ConformalTomb** [comment]
Okay so what I did was I manually created the directory "lib.win-amd64-3.6" which the program is not able to create as above, and the script ran pretty well until here!
![image](https://user-images.githubusercontent.com/22431349/59261073-6d49a900-8c5a-11e9-8e04-07340961072d.png)
This is the new error that the setup.py is throwing.

**Comment by davisking** [comment]
Don’t run cmake. Just run setup.py. It sounds like you made that build folder yourself and used cmake to fill it with build files. So yeah, there is going to be this kind of error as setup isn’t going to just blow away some files it doesn’t know about. So delete the dlib folder, download a fresh copy, and try again.

But I’m also guessing since I don’t know what you did since you haven’t filled out the issue template. If you run into other errors and want any help follow the issue submission instructions.

**Comment by ConformalTomb** [comment]
No! this screenshot is of the command "setup.py build"
I have also tried "setup.py install --clean" but same error is incurring.
P.S. I am fairly new to GitHub so I have little to no knowledge of the protocols we need to follow here! Pardon me for that please!

**Comment by ConformalTomb** [comment]
![image](https://user-images.githubusercontent.com/22431349/59264912-cbc65580-8c61-11e9-8181-396e15c61f59.png)

This is the error that is encountered after running fresh "setup.py install" in a fresh cloned dlib folder.

**Comment by ConformalTomb** [comment]
You know what, I just used `pip install dlib `and it worked! The python library is now installed and working perfectly with my CUDA GPU.
Thank you so much @davisking
