### ISSUE TITLE
dnn_face_recognition_ex not working right with opencv

### ISSUE THREAD

**Issue by EndErr** [davisking/dlib#1768]
Built example in 2 variants, without OpenCV and with OpenCV. 
Even not using OpenCV in code results are different.

## Expected Behavior
Face descriptor values should be between [-1, 1]

## Current Behavior
Without OpenCV values are between [-1, 1], with OpenCV values are bigger [-10, 11] and sometimes more. That does not give the expected results in face_descriptors and on line 151, "if (length(face_descriptors[i]-face_descriptors[j]) < 0.6)", for the same person (even same face) that subtract value is much bigger than 0.6, in average it is in range of [2,12].

## Steps to Reproduce
CMakeLists.txt for case 1 (without OpenCV):
add_subdirectory(../dlib dlib_build)
add_executable(dnn_face_recognition_ex dnn_face_recognition_ex.cpp)
target_link_libraries(dnn_face_recognition_ex dlib::dlib)

CMakeLists.txt for case 2 (with OpenCV):
add_subdirectory(../dlib dlib_build)
find_package(OpenCV QUIET)
add_executable(dnn_face_recognition_ex dnn_face_recognition_ex.cpp)
target_link_libraries(dnn_face_recognition_ex dlib::dlib ${OpenCV_LIBS})

* **Version**: 19.17
* **Where did you get dlib**: http://dlib.net
* **Platform**: CentOS Linux release 7.6.1810 (Core) x64
* **Compiler**: gcc 4.8.5, gcc 7

**Comment by davisking** [comment]
I am unable to reproduce this.  When I link to opencv it doesn't make any
difference.  I find it very surprising that this would be different.  I
suspect there is something else going on here.

**Comment by EndErr** [comment]
To reproduce:
1. Comment line 127 in CMakeLists.txt: add_gui_example(dnn_face_recognition_ex)
2. Add two lines at position 153 before current add_executable:
```
add_executable(dnn_face_recognition_ex dnn_face_recognition_ex.cpp)
target_link_libraries(dnn_face_recognition_ex dlib::dlib ${OpenCV_LIBS} )
```
3. Build examples and run:  ./dnn_face_recognition_ex ../faces/bald_guys.jpg 

For me there are no clusters, each face is a separate cluster.

**Comment by davisking** [comment]
Yeah, that's what I did and it worked fine.

**Comment by EndErr** [comment]
Hm, very strange, where should I dig to find the problem?
I guess the problem is in OpenCV installation, but why should it be wrong if no "cv" code is used in that example?
The moment that cause differences is here
```
auto shape = sp(img, face);
matrix<rgb_pixel> face_chip;
extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);
...
std::vector<matrix<float,0,1>> face_descriptors = net(faces);
```
the values in face_descriptors[x] are bigger then without OpenCV included.

**Comment by davisking** [comment]
I would start printing things and looking at images and data going in and
out. Maybe the images don't load right.  Who knows.

**Comment by EndErr** [comment]
I've reinstalled OpenCV without OpenMP and it worked like it should.
The question is why it doesn't work with OpenMP?

**Comment by davisking** [comment]
Maybe you also linked against some BLAS library, like the Intel MKL that
uses a different and incompatible version of OpenMP.

**Comment by EndErr** [comment]
Case closed ;)
Need to check all OpenCV build modes and Intel dependences (I use only Intel libs).
