### ISSUE TITLE
Weird RuntimeError: A call to cuDNN failed when run example python script

### ISSUE THREAD

**Issue by Zwei-Eric** [davisking/dlib#1772]
Hi
I compiled dlib on ubuntu 16.04 docker container with cuda 8.0 and cudnn 7.05 successfully.
But the error occurred every time when I run the  example python script: cnn_face_detector.py 

root@4293dcd59742:~/data/dlib/python_examples# ./cnn_face_detector.py  mmod_human_face_detector.dat test6.jpg
Processing file: test6.jpg
Traceback (most recent call last):
  File "./cnn_face_detector.py", line 56, in <module>
    dets = cnn_face_detector(img, 1)
RuntimeError: Error while calling cudnnCreate(&handles[new_device_id]) in file /root/data/dlib/dlib/cuda/cudnn_dlibapi.cpp:104. code: 4, reason: A call to cuDNN failed

It's OK when I just import dlib and use funtions like get_frontal_face_detector.
I can't search much infomation about this error, does anyone know the reason?

* **Version**: 19.17
* **Where did you get dlib**: github repo
* **Platform**: 
Distributor    Ubuntu 16.04.3 LTS
Codename:       xenial
gcc version: 5.4.0

**Comment by asterisk37n** [comment]
Same here. Did you solve?

**Comment by shiwen-cheng** [comment]
i have the same problem, did you fix it?
