### ISSUE TITLE
dlib on TX2 not using gpu

### ISSUE THREAD

**Issue by WIll-Xu35** [davisking/dlib#1778]
## Expected Behavior
I'm using Nvidia Jetson TX2, dlib is isntalled via ‘sudo python3 setup.py’, and is built with cuda support (verified dlib.DLIB_USE_CUDA is True). When running dlib.get_frontal_face_detector() and dlib.shape_predictor(), GPU usage is almost 0 all the time.

## Current Behavior
dlib.get_frontal_face_detector() detect a single 480p image within 110ms, dlib.shape_predictor() detect a single face within 10ms. By looking at the time, it seems dlib.shape_predictor() is using cuda since the execution time is short, consider that it is using a ~100MB model. Does dlib.get_frontal_face_detector() support execution using cuda or not?

## Steps to Reproduce
install dlib on TX2 using setup.py without any argument. Then apply get_frontal_face_detector() and shape_predictor(), check tegrastats for gpu usage to verify if they use cuda or not.

* **Version**: 19.17.0
* **Where did you get dlib**: http://dlib.net/
* **Platform**: Ubuntu 18.04.2 LTS (L4T)
* **Compiler**: gcc 7.4.0

**Comment by davisking** [comment]
These things don’t use cuda.
