### ISSUE TITLE
matrix/matrix.h fails to compile on VC2012.

### ISSUE THREAD

**Issue by tc3t** [davisking/dlib#178]
Commit on [2016-04-19](https://github.com/davisking/dlib/commit/e9fa65398f73827efaab46036918e873b00caf12) introduced conditional include of < initializer_list > to matrix/matrix.h. The condition, however, is faulty because the availability of < initializer_list > is not equal to availability of rvalue references: the former is available since 2010, the latter since VC2013 [[2]](https://msdn.microsoft.com/en-us/library/hh567368.aspx). Interestingly, though, VC2010 does have a header < initializer_list > although the feature itself is not listed as implemented [[2]](https://msdn.microsoft.com/en-us/library/hh567368.aspx) so the compile failure occurs only on VC2012.

**Comment by davisking** [comment]
Thanks.  I'll work something out.  I'm still trying to figure out what
exactly to do regarding C++11 and visual studio.  It's 2016 and no version
of visual studio is C++11 compliant yet :(

**Comment by davisking** [comment]
This should now work without trouble in visual studio 2012.
