### ISSUE TITLE
use gui_core_kernel_2.h caused Error

### ISSUE THREAD

**Issue by woniurensheng** [davisking/dlib#1780]
DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it.

Also make sure you have libx11-dev installed on your system

**Comment by AleksZhuravljov** [comment]
Yep, same here. Lemme add, is it possible to handle it using homebrew?

 Thanks in advance.

**Comment by eitguide** [comment]
I have the same issue when building dlib in iOS project. Any one resolved this issue. Can give me the solution. Thanks in advance.
