### ISSUE TITLE
VC++ MFC Detected memory leaks! 

### ISSUE THREAD

**Issue by libaineu2004** [davisking/dlib#1784]
## Expected Behavior

I used VS2015 to create a new MFC multi-document project, and then introduced the dlib
library into the project, only the private declaration in the class:
#include <dlib/threads.h>
#include <dlib/sqlite.h>
#include <dlib/logger.h>
#include <dlib/misc_api.h>
dlib::read_write_mutex m_mutex;
When the software exits, it prompts memory leaks.

## Current Behavior

Detected memory leaks!
Dumping objects ->
{31611} normal block at 0x07E35070, 8 bytes long.
 Data: <        > 18 18 DA 07 00 00 00 00 
{31610} normal block at 0x07DA1818, 720 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{31609} normal block at 0x07E350A8, 8 bytes long.
 Data: <        > B0 C5 A0 00 00 00 00 00 
{31608} normal block at 0x00A0C5B0, 2000 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{31607} normal block at 0x07E08998, 384 bytes long.
 Data: <  q   q   q $ q > 88 F0 71 00 AC F0 71 00 00 F0 71 00 24 F0 71 00 
Object dump complete.
No memory leaks detected.

## Steps to Reproduce

Use VS2015 to create an MFC dialog app. Add Source.cpp to the project (set to not using precompiled headers for source.cpp)
Compile and run... on exit will show leaks

* **Version**: 
19.17

* **Where did you get dlib**: 
https://github.com/

* **Platform**: 
Win7,x64

* **Compiler**: 
VS2015,Win32

**Comment by davisking** [comment]
It's probably this
https://github.com/davisking/dlib/blob/master/dlib/threads/threads_kernel_shared.cpp#L78

**Comment by libaineu2004** [comment]
Okay, I understand now, thanks!
