### ISSUE TITLE
Correlation tracker throws when using MKL FFT

### ISSUE THREAD

**Issue by facug91** [davisking/dlib#1786]
## Expected Behavior
I'm using the correlation_tracker. When I call start_track using MKL FTT, it should start tracking the object without problem.

## Current Behavior
But when I call start_track using MKL FTT, it throws a segmentation fault and terminate. Without MKL FTT, that doesn't happen and it works correctly.  

## Steps to Reproduce
I'm using a dynamic matrix, where I copy an OpenCV Mat of type 8UC1 and size 800x500.  
I create a correlation_tracker with filter_size = 5, and num_scale_levels = 4, and call start_track with that image and a rectangle(660, 150, 782, 206), which is inside the image. The first time I call it, a segmentation fault is thrown and the execution terminate.  

## Extra information
I've noticed when debugging it, that the problem arise in the line 770 of matrix_fft.h, when calling DftiCommitDescriptor function, but as I don't know much about how fft is implemented in dlib, I don't know how to fix it, or even determine if it is a dlib problem or MKL.

* **Version**: master, commit [8001b92](https://github.com/davisking/dlib/tree/8001b924e63ac920a9047610ece2e4e6266e8a4c/dlib)
* **Where did you get dlib**: I've cloned it from here.
* **Platform**: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
* **Compiler**: 
gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
MKL version 2019 Update 3

**Comment by facug91** [comment]
I've tried the same code and data on Windows, with the same version of MKL, but using VC++, and it works fine.

**Comment by davisking** [comment]
Not sure.  I wouldn't be surprised if there is some kind of linker error causing it. Like you are using OpenCV and it's pulling in an incompatible version of OpenMP which upsets the MKL, which also uses it's own version of OpenMP.

**Comment by facug91** [comment]
Well, I've tried many combinations of compilations. OpenCV without OpenMP, MKL with sequential, both libraries using the same, within others, and still have the error.  

I made some more debug, and I can provide more information.  
When running `start_track` function, all `fft_inplace` in lines 67 and the one perform inside `make_target_location_image` in line 68, ran correctly. The problem starts when calling the first `fft_inplace` in line 81.  
I've noticed two things about this. The data used when working right, it's a completely dynamic matrix (nr == 0 and nc == 0), but when fails, data is a vector (nr == 0 and nc  == 1). Don't know if that could be a problem or not.  
The other thing is that I've put an static int counter inside file `matrix_fft.h`, in method `call_mkl_fft_inplace`, in order to use a break point to stop program before crashing in 770 (when calling `DftiCommitDescriptor`). When printing the counter, it goes from 1 to 33, then 1 again, and then crush, as if the method were using a new static variable. I assumed the compiler might be inlining.  

Still don't know how to fix it, but maybe these things give someone more insides about how to do it.

**Comment by facug91** [comment]
I've been able to "fix it", by commenting lines from 743 to 749 in `matrix_fft.h`, forcing it to always use a bidimentional matrix, even when the data received it a vector. I don't know how much it affects in time, but at least now we know the problem is in when using vectors instead of matrices.

**Comment by davisking** [comment]
Huh.  So what happens when you run the dlib unit tests?  You can run just the fft tests by doing `dtest --test_fft`.  Does this only happen when OpenCV is linked in or all the time?

**Comment by facug91** [comment]
I've tried creating a new test project, and when I use only dlib, it works fine, but when I add OpenCV, it starts to throw the sigsegv, so you were right, it is some sort of problem about OpenCV and dlib working together. Is there something else I can do?

**Comment by davisking** [comment]
I'm not sure what you need to do other than be careful that you link dlib
and opencv to the same OpeMP library.

**Comment by facug91** [comment]
But I'm using OpenCV without OpenMP and MKL with sequential, and dlib with MKL with TBB, I'm not sure why would them be using OpenMP.

**Comment by facug91** [comment]
Well, I'll keep trying. Thank you very much Davis, if I find some solution, I'll post it here.
