### ISSUE TITLE
frontal_face_detector very slow on macbook pro 2017

### ISSUE THREAD

**Issue by fatly** [davisking/dlib#1790]
version: 19.17.99
processing image size: 180x135 grayscale
span time: 220 ms
code: dib face detect example(c++)
windows platform is ok!

**Comment by zhangchn** [comment]
Hi, perhaps you could try adding '-O3' to your compiler/linker command line and this worked for me on mac mini 2014.

As a result, the run time on a 160x160 png would decrease from 1000+ to less than 20 milliseconds.

**Comment by fatly** [comment]
> Hi, perhaps you could try adding '-O3' to your compiler/linker command line and this worked for me on mac mini 2014.
> 
> As a result, the run time on a 160x160 png would decrease from 1000+ to less than 20 milliseconds.

cool!
