### ISSUE TITLE
sqlite3_open：Chinese path is not supported, it is recommended to add sqlite3_open16() interface

### ISSUE THREAD

**Issue by libaineu2004** [davisking/dlib#1791]
## Expected Behavior

\Dlib-19.17\dlib\sqlite\sqlite.h,#74
void open (
            const std::string& file
        )
        {
            filename = file;
            sqlite3* ptr = 0;
            int status = sqlite3_open(file.c_str(), &ptr);
            db.reset(ptr, impl::db_deleter());
            if (status != SQLITE_OK)
            {
                throw sqlite_error(sqlite3_errmsg(db.get()));
            }
        }

sqlite3_open：Chinese path is not supported.

I hope add sqlite3_open16() interface,
eg.
void open16 ( const std::string& file )
{
....
sqlite3_open16(...)
....
}

## Steps to Reproduce

* **Version**: 
19.17
* **Where did you get dlib**: 
github
* **Platform**: 
Win7，x64
* **Compiler**: 
msvc2015，32bit

**Comment by davisking** [comment]
Why can't you use utf-8 instead of utf-16?  utf-8 is usually easier to deal with.

You are welcome to submit a PR for this in any case.  Note that you can't store utf-16 in a `std::string` though, you need to use `std::u16string` instead.
