### ISSUE TITLE
 face recognition when dimming

### ISSUE THREAD

**Issue by Server48** [davisking/dlib#1793]
Hey . Very interested in dlib. A large door phone system has now been developed for your library. But the problem has become extremely acute - darkening of the face. I use the hog detector as it is best suited, but when starting with a dark face is immediately a problem. Could you tell me how to solve this problem - maybe initial processing filters or something else?

Some of the worst blackout examples. But even for better ones, there is a problem of not recognizing
![444](https://user-images.githubusercontent.com/3450868/59061241-afb26500-88ab-11e9-8032-231e8a9da8c8.png)

![21](https://user-images.githubusercontent.com/3450868/59061077-37e43a80-88ab-11e9-93d7-42748f145e93.png)
![555](https://user-images.githubusercontent.com/3450868/59061091-3f0b4880-88ab-11e9-9de3-79a3657cce17.png)
![32](https://user-images.githubusercontent.com/3450868/59061101-43cffc80-88ab-11e9-996b-f875b076970e.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3450868/59061179-7b3ea900-88ab-11e9-89cc-7e65eed33094.gif)

Please tell me how to correct this situation, or at least send you a direction.

**Comment by davisking** [comment]
I would train a new HOG detector with images like these in the training dataset then.

**Comment by Server48** [comment]
So we should train your model already? What is the optimal number of photos we may need?

**Comment by davisking** [comment]
You can start from the dataset used to train the HOG model (available here
http://dlib.net/files/data/dlib_face_detector_training_data.tar.gz) and add
images that fail to it.

**Comment by Server48** [comment]
Many thanks for your help. We can not improve the image using filters to improve accuracy?

**Comment by Server48** [comment]
Thank you very much for your help, I'll start trying immediately. Question on cameras, we can use some kind of image filters to increase the accuracy in using your model.(frontal_face_detector)

**Comment by Server48** [comment]
The arbitrariness of partial training on their images of persons. The result is very good, thank you. However, if I repeat your learning settings completely, can I get the same accuracy?

**Comment by davisking** [comment]
Yes, if you run the same settings on the same dataset you will get the same results. The training parameters are recorded here http://dlib.net/dlib/image_processing/frontal_face_detector.h.html#get_frontal_face_detector

**Comment by Server48** [comment]
Everything is fine, thank you very much. But I just can't transfer the training to the video card. Is this possible on python?

**Comment by Server48** [comment]
although the question is more on RAM, I think my 256 is not enough .. 
Strange, but I can not find information about this
