### ISSUE TITLE
Setting "y" of a dlib.point changes "x" instead

### ISSUE THREAD

**Issue by jtoss** [davisking/dlib#1794]
Using the python API of dlib I noticed that changing the "y" property of a dlib.point changes its "x" property instead. 

Python 3.6.6 
```
dlib.__version__
'19.17.0'
```

## Steps to Reproduce
```
>>> import dlib
>>> p = dlib.point(0,0)
>>> p 
point(0, 0)
>>> p.x = 1
>>> p
point(1, 0)
>>> p.y = 2
>>> p
point(2, 0)
```

**Comment by jotapem** [comment]
Could reproduce it with Python 3.5.2 and Dlib 19.16.0
