### ISSUE TITLE
I recommend adding a Future/Promise C++ implementation，like the scala language

### ISSUE THREAD

**Issue by libaineu2004** [davisking/dlib#1799]
## Expected Behavior
I recommend adding a Future/Promise C++ library, similar to the scala programming language for future and promise implementations.

Future/Promise
There are already a lot of implementations of Future mechanism in C++:
std::future - no API at all, except very basic operations like retrieve value and wait for it. There is a Concurrency TS with .then, but it is still not in the standard.
boost::future - almost the same as std::future.
Folly - Folly futures are also inspired by Scala ones (but different ones, from Twitter framework) and have good API but are a part of huge framework which is too hard to use partially.

But the above libraries are either imperfect or have a lot of dependencies, which is not easy to install and use.So why not to create another one?

In this way, the dlib library will be more advantageous and attractive.

Thank you！

## Steps to Reproduce

* **Version**: 

* **Platform**: 
* **Compiler**:

**Comment by davisking** [comment]
There are futures tools in dlib already, like those in http://dlib.net/dlib/threads/thread_pool_extension_abstract.h.html#thread_pool and http://dlib.net/dlib/threads/async_abstract.h.html#async

**Comment by libaineu2004** [comment]
> There are futures tools in dlib already, like those in http://dlib.net/dlib/threads/thread_pool_extension_abstract.h.html#thread_pool and http://dlib.net/dlib/threads/async_abstract.h.html#async

I hope to add the then() method, the when_all() method, the when_any method, and so on.

**Comment by davisking** [comment]
Cool, you should submit a pull request :)

**Comment by libaineu2004** [comment]
> Cool, you should submit a pull request :)

This is a project of a friend of mine, https://github.com/loveyacper/ananas
he implemented the then, when_all, when_any and other methods of future/promise. Perhaps he is interested in getting involved.
