### ISSUE TITLE
writing a custom layer: the network trains but doesn't work for inference

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#1802]
Hi, I have implemented a new loss, which I named `loss_mean_squared_per_channel`

Basically it does the same as the `loss_mean_squared_per_pixel` except that it computes the loss over all channels of the last convolutional layer. This is useful when we try to do some keypoint/landmark estimation using heatmaps, so that we can force each channel to learn only one keypoint (a similar approach has been done here: https://arxiv.org/abs/1804.06208)
The code for this loss can be found here: https://github.com/arrufat/dlib/commit/ad1b29afe1f749c64145fb42d2ca942bdc400177#diff-32a043d312608d62a296b05ce1bc096eR2894.

I am able to train the network without any problems and I'm even getting the same behavior as `loss_mean_squared_per_pixel` when there's only one output channel, as expected.
The network definition goes something like:
``` c++
// definition
using net_type =
    loss_mean_squared_per_channel<24,
    // some additional layers
    input_rgb_image_sized<224>>;
net_type net;

// the training images and heatmap targets
std::vector<matrix<rgb_pixel>> images;
std::vector<std::array<matrix<float>, 24>> heatmaps;
dnn_trainer<net_type> trainer(net);
trainer.train(images, heatmaps);
```

As I said, all of this works fine. However, I have a problem at inference time, when I run it with an image (that I used for training) it segfaults with the following message:
```
**************************** FATAL ERROR DETECTED ****************************
Error detected at line 1257.
Error detected in file _deps/dlib-src/dlib/../dlib/image_loader/../image_transforms/../statistics/../matrix/matrix.h.
Error detected in function T& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator()(long int, long int) [with T = float; long int num_rows = 0; long int num_cols = 0; mem_manager = dlib::memory_manager_stateless_kernel_1<cha
r>; layout = dlib::row_major_layout].

Failing expression was r < nr() && c < nc() && r >= 0 && c >= 0.
        T& matrix::operator(r,c)
        You must give a valid row and column
        r:    0
        c:    0
        nr(): 0
        nc(): 0
        this: 0x7fff3a28fe90

******************************************************************************

Aborted (core dumped)
```
I must say I'm a bit lost, of course the image that I give to the network has more than 0 columns and rows.
Thanks in advance for your help.
If we manage to find out the issue and you're interested, I would be honored to write some tests and submit a pull request :)

**Comment by davisking** [comment]
You didn’t set the size of the output matrix anywhere in the to_label method. So they are all empty.  Hence the error.

**Comment by arrufat** [comment]
Yes! That was it, I should have seen it. Thank you so much.
I'm closing the issue.
Would you be interested in a pull request?
(Of course I would not push my current branch, in which Vim stripped all the trailing white spaces, so the diff is huge)

**Comment by davisking** [comment]
Cool. Yeah a PR is always welcome so long as it’s documented and includes a little unit test.
