### ISSUE TITLE
Compile with gcc(g++) + nvcc only (not cmake)

### ISSUE THREAD

**Issue by meloman-a** [davisking/dlib#1803]
* **Version**: 19.17
* **Where did you get dlib**: dlib.net
* **Platform**: Windows, 64-bit
* **Compiler**: 
gcc version 8.3.0 (Rev2, Built by MSYS2 project)
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168

Hello, help me please please with compiling by gcc and nvcc, I can't use cmake because of using dlib in Golnang(cgo). There is the same problem explaned  https://stackoverflow.com/questions/32589153/how-to-compile-cuda-source-with-go-languages-cgo. How could I understand, first I need to compile a shared library(so), but how? Maybe someone has already done something like that with dlib?
It will be very usefull if someone can show how to do this on dnn_mmod_face_detection_ex.cpp example.
I am trying to do this for a week.

Thank you in advance.

**Comment by meloman-a** [comment]
Maybe it can be combined with cmake compile results(with cuda) and gcc...

**Comment by davisking** [comment]
You can certainly build dlib as a shared library with cmake and then link to it using whatever you want.

**Comment by meloman-a** [comment]
@davisking
Thank you for your answer. Is using static library correct way?
I am trying like that.
g++ -std=c++11 -O3 -ljpeg -lgdi32 -lcomctl32 -luser32 -lwinmm -lws2_32 -limm32 -I.. dlib19.17.0_release_64bit_msvc1916.lib -lpthread dnn_mmod_face_detection_ex.cpp

but as a result get many error like that:
undefined reference to `dlib::tt::add(float, dlib::tensor&, float, dlib::tensor const&)'
undefined reference to `dlib::tt::affine_transform_conv(dlib::tensor&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&)'

I was trying to compile a shared library, but failed with error:
CMake Error at CMakeLists.txt:105 (message):
  Building dlib as a standalone dll is not supported when using Visual
  Studio.  You are highly encouraged to use static linking instead.  See
  https://github.com/davisking/dlib/issues/1483 for a discussion.

any advice?
Thanks.

**Comment by meloman-a** [comment]
I've switched OS to Ubuntu 19.04 and all my probles have gone.
Thank you @davisking very much for you replay "You can certainly build dlib as a shared library with cmake and then link to it using whatever you want." - it helped me!
