### ISSUE TITLE
shape_predictor_trainer::get_oversampling_translation_jitter() returns unsigned long but backing field is double

### ISSUE THREAD

**Issue by leppie** [davisking/dlib#1808]
https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor_trainer_abstract.h#L166

https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor_trainer.h#L828

While not a bug as the set field value is used, the set value cannot be read back correctly.

**Comment by davisking** [comment]
Thanks, this is indeed a bug.  I just pushed the fix.
