### ISSUE TITLE
AVX256 instead of AVX512

### ISSUE THREAD

**Issue by azhuvath** [davisking/dlib#1809]
I did a source build on a machine that supports AVX512. The vTune report highlights that the vectorization is good, but it still using 256 instead of 512. How to make use of AVX512 instead of AVX256 to speed up?

**Comment by arrufat** [comment]
I usually add this piece of code to the `CMakeLists.txt` to make sure all optimizations are activated:

``` cmake
# Enable all optimization flags supported by the processor
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-march=native" COMPILER_SUPPORTS_MARCH_NATIVE)
if(COMPILER_SUPPORTS_MARCH_NATIVE)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
endif()
```

**Comment by azhuvath** [comment]
I tried adding the above code snippet to CMakeLists.txt prior to source build. Still there is no change. It still using 256 bit instead of 512. I am not sure if code change will have to be made to take advantage of it.

**Comment by arrufat** [comment]
Does this command output support for  AVX512?
``` bash
gcc -march=native -v -Q --help=target
```

**Comment by azhuvath** [comment]
-mavx5124fmaps                        [disabled]
  -mavx5124vnniw                        [disabled]
  **-mavx512bw                               [enabled]
  -mavx512cd                               [enabled]
  -mavx512dq                               [enabled]**
  -mavx512er                                [disabled]
  **-mavx512f                                  [enabled]**
  -mavx512ifma                            [disabled]
  -mavx512pf                                [disabled]
  -mavx512vbmi                           [disabled]
  **-mavx512vl                                [enabled]**
  -mavx512vpopcntdq                 [disabled]
