### ISSUE TITLE
face landmark retrain takes very long time

### ISSUE THREAD

**Issue by shixudongleo** [davisking/dlib#181]
Hi davisking, 

I am using Helen dataset(194 pts) to retrain face landmark model. However, the model training seems to last forever. I am only trying 10 images for now. The situation got worse when I use all the 2330 images. 

How can I boost the training process? Am I doing something wrong in setting the model parameters?

```
python train_shape_predictor.py ./img
Training with cascade depth: 10
Training with tree depth: 2
Training with 500 trees per cascade level.
Training with nu: 0.5
Training with random seed: 
Training with oversampling amount: 30
Training with feature pool size: 400
Training with feature pool region padding: 0
Training with lambda_param: 0.1
Training with 20 split tests.
Fitting trees...
Time remaining: 59.65 minutes.
```

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whyisdlibslow

**Comment by e-fominov** [comment]
@shixudongleo, Please use stackoverflow or sourceforge for support. Here is development process

If you want to train Helen dataset, you will need 64 GB RAM. Training process will take about 20-40 hours for all 2330 images
Your params are good for training simplified model. You can try reducing oversampling amount and trees per cascade level - it will take less time with less precision
Latest version of Dlib with C++ interface can reduce training time twice if use multithreaded training

@davisking, may be we should train and publish this model? Are there any licensing restrictions?

**Comment by shixudongleo** [comment]
Thanks for answering. I will try the C++ interface.

**Comment by davisking** [comment]
@shixudongleo I'm pretty sure you were also running without compiler optimizations.  So make sure you enable those as well.

@e-fominov I don't think there are any restrictions.  If you want to train a helen model and put it into https://github.com/davisking/dlib-models that would be cool.
