### ISSUE TITLE
CNN face detection does not appear to use CUDA on Jetson Nano

### ISSUE THREAD

**Issue by c-x-berger** [davisking/dlib#1810]
I'm using the `cnn_face_detector` script straight from the Python examples directory, with the pre-trained `mmod_human_face_detector.dat` on a Jetson Nano.

## Expected Behavior

The script should detect a face reasonably quickly by using the GPU.
## Current Behavior

I believe it is actually using the CPU, as it takes a long time to process a single image and uses upwards of 3 GB of "normal" RAM according to Ubuntu's System Monitor. It does _eventually_ find the face, but it takes a long while to do so. 

This is in spite of `dlib.DLIB_USE_CUDA` being `True`.

## Steps to Reproduce
1. `pip3 install dlib` on a Jetson Nano.
2. Check that CUDA is compiled in with `dlib.DLIB_USE_CUDA` (returns `True`) and `dlib.cuda.get_num_devices()` (returns 1.)
3. Get `cnn_face_detector.py` and [`mmod_human_face_detector.dat`](http://dlib.net/files/mmod_human_face_detector.dat.bz2).)
3. Run `cnn_face_detector.py` with `python3 cnn_face_detector.py mmod_human_face_detector.dat fabio.jpg` ([`fabio.jpg`](https://user-images.githubusercontent.com/43154879/60210013-dcfa8f00-9829-11e9-9689-3d7a08d5d427.jpg))
4. Watch RAM usage go through the roof (in fact, it gets killed by the OOM killer without a swap file.)

* **Version**: `dlib.__version__` is `19.17.0` 
* **Where did you get dlib**: `sudo pip3 install dlib`
* **Platform**: Ubuntu 18.04 on Jetson Nano 
* **Compiler**: ...`gcc`? I think? Whatever `cmake` found and used in `setup.py`.

**Comment by c-x-berger** [comment]
I tried again, this time using a series of smaller (`fabio.jpg` is ~500 KB, these were ~100) images. Using `tegrastats` shows [`GR3D_FREQ`](https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/AppendixTegraStats.html) spike up on processing each image. These all go by quick enough to only show one "reading" from `tegrastats`.

However, when processing the larger `fabio.jpg`, I can see that most of the time processing the image uses very little of the GPU's power. While `GR3D_FREQ` spikes at the start, for most of the processing time it stays at 0% utilization. (There are maybe two or three "spikes" to 99% utilization.)

**Comment by davisking** [comment]
If `dlib.DLIB_USE_CUDA` is `True` then it must be using cuda.  The non-cuda code paths are not even compiled if that flag says `True`. Maybe you aren't running the code you think you are running. It is very common to have many versions of python and/or dlib installed and to get confused about which version you are running. Maybe you are really running a CPU only version.

**Comment by c-x-berger** [comment]
I know for a fact this system only has one Python and one dlib install. 

I'm on vacation so I don't have access to the Jetson board right now, but I'll do more testing then.

**Comment by c-x-berger** [comment]
So I just double checked for my own sanity. **There is only one installation of Python 3 on this board. There is only one installation of dlib as well.** And it is indicating that CUDA is enabled (*again,* `dlib.DLIB_USE_CUDA` is `True`.)

So I'm pretty darn sure that CUDA is in fact supposed to be enabled when I run something with `dlib`. :P

At any rate, I did see more GPU utilization this time (testing on `fabio.jpg` again), which is good. I'm still a bit in the dark as to why it consumes almost all my RAM and a hearty chunk of swap to run, but maybe there's something I'm missing about how the CUDA code path actually works, I don't know. I guess I can close this issue now.

As an aside, is there a list of function with(out) CUDA support in dlib, or is the answer to that question "everything is CUDA"?

**Comment by davisking** [comment]
Most things are not CUDA
