### ISSUE TITLE
deserialize or serialize from std::stream instead of only from file name

### ISSUE THREAD

**Issue by cfoch** [davisking/dlib#1812]
## Expected Behavior
I would like to be able to serialize or deserialize from a istream or ostream instead that just from a file(name). Allowing to construct a `proxy_deserialize` or a `proxy_serialize` from a istream or ostream for my particular use case would allow me to read the model asynchronously, loading the model into a istringstream.

## Current Behavior
Dlib only allows to serialize/deserialize from a file.

That's annoying because if the file is too big or even in real time applications this is an **I/O blocking** operation, which blocks my program.

* **Version**: v19.17
* **Where did you get dlib**: github
* **Platform**: irrelevant 
* **Compiler**: irrelevant

**Comment by cfoch** [comment]
I see this easy to implement if @davisking agrees and I can do it and submit as a PR. It would just involve to add a new constructor 
```
        explicit proxy_deserialize (
            const std::istream & stream
        )
```
But there another changes that lead me to question of what should I do with the error messages: https://github.com/davisking/dlib/blob/master/dlib/serialize.h#L1618 If I construct the proxy_deserialize with a istream then these error messages would print an empty string because no filename is initialized.

Also, why are you using a shared_ptr [here](https://github.com/davisking/dlib/blob/master/dlib/serialize.h#L1645). Wouldn't it be enough with having it defined as
```
std::istream fin; //"in" or "input_stream" would be a better name
```

**Comment by cfoch** [comment]
Maybe another possibility would be to construct the proxy_deserialize from a buffer and a buffer size.

**Comment by cfoch** [comment]
ping :-)

**Comment by davisking** [comment]
All the serialization method already work on streams. Look at the code. Every single one takes a stream, not a file name.

**Comment by cfoch** [comment]
Yes, thanks. You are right. I have found a good example in the source code of the frontal face detector.
This issue can be closed.

**Comment by davisking** [comment]
Please read the documentation: http://dlib.net/other.html#serialize
