### ISSUE TITLE
gui_api_ex not support base_window default font setup？

### ISSUE THREAD

**Issue by robinhoo1973** [davisking/dlib#1814]
Thanks for the great library! I'm trying to use dlib for UI displaying on different OS platform and found when I change the string in the example of gui_api_ex to CJK(Chinese Japanese Korean) characters, there would be no output at all. I guess it caused by the font settings of base_window. However, I didn't find any document mentioned such configuration. Just wondering whether that's not supported by dlib or just not revealed in the documentation. Thanks for any advice for it.

**Comment by davisking** [comment]
The default font is pretty limited. For anything other than basic ascii characters you need to provide your own font. There is an API for doing this and you can use the bdf font loader (http://dlib.net/dlib/gui_widgets/fonts_abstract.h.html#bdf_font).

**Comment by robinhoo1973** [comment]
Hi, Davisking, Thanks for your quick response and great library that created for us! However, the font that I'm trying to use is true type font, not Bitmap Distribution Format font. How to make it happen? Do we have any sample code to show how it works? Thanks in advance.

**Comment by davisking** [comment]
You need a tool that converts a true type front (at a particular font size)
into a BDF file.  I don't have a tool for this in dlib, but they exist.
