### ISSUE TITLE
import Error dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: mkl_dft_dz2_c_dft

### ISSUE THREAD

**Issue by RobijnDM** [davisking/dlib#1816]
## Expected Behavior
Should be able to import dlib using python 3.6.8 on a virtualenv installed via pip

## Current Behavior
when running import dlib on a python shell it returns the following error:
ImportError: /home/gabhen/venv/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: mkl_dft_dz2_c_dft

## Steps to Reproduce
import dlib on python3.6.8 on a virtualenv shell.

* **Version**: 19.17.0
* **Where did you get dlib**: pip
* **Platform**: 64bit Ubuntu 18.04.2
* **Compiler**: cmake version 3.10.2

Any ideas what might be causing this error ? Already installed Intel MKL and reinstalled dlib, no luck yet.

Thanks for the help!

**Comment by davisking** [comment]
What, exactly, does someone type to reproduce this?

**Comment by RobijnDM** [comment]
> What, exactly, does someone type to reproduce this?
> […](#)
> On Jul 4, 2019, at 11:09 AM, Gabriel Henriques ***@***.***> wrote: Expected Behavior Should be able to import dlib using python 3.6.8 on a virtualenv installed via pip Current Behavior when running import dlib on a python shell it returns the following error: ImportError: /home/gabhen/venv/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: mkl_dft_dz2_c_dft Steps to Reproduce import dlib on python3.6.8 on a virtualenv shell. Version: 19.17.0 Where did you get dlib: pip Platform: 64bit Ubuntu 18.04.2 Compiler: cmake version 3.10.2 Any ideas what might be causing this error ? Already installed Intel MKL and reinstalled dlib, no luck yet. Thanks for the Help!

import dlib

**Comment by davisking** [comment]
That doesn’t reproduce it.

**Comment by RobijnDM** [comment]
> That doesn’t reproduce it.
> […](#)
> On Jul 4, 2019, at 11:32 AM, Gabriel Henriques ***@***.***> wrote: What, exactly, does someone type to reproduce this? … On Jul 4, 2019, at 11:09 AM, Gabriel Henriques @.***> wrote: Expected Behavior Should be able to import dlib using python 3.6.8 on a virtualenv installed via pip Current Behavior when running import dlib on a python shell it returns the following error: ImportError: /home/gabhen/venv/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: mkl_dft_dz2_c_dft Steps to Reproduce import dlib on python3.6.8 on a virtualenv shell. Version: 19.17.0 Where did you get dlib: pip Platform: 64bit Ubuntu 18.04.2 Compiler: cmake version 3.10.2 Any ideas what might be causing this error ? Already installed Intel MKL and reinstalled dlib, no luck yet. Thanks for the Help! import dlib 

Well it's definitly an environment issue given that it works fine on my MacOs, just haven't been able to figure out exactly what is causing this issue
