### ISSUE TITLE
How to calculate a confidence score for the one vs. all trainer

### ISSUE THREAD

**Issue by idilsulo** [davisking/dlib#1818]
I want to calculate whether the predictions that are made using the one_vs_all approach are accurate. Is there a way to calculate the confidence score for the following trainer configurations?

```
        typedef dlib::matrix<float, 0, 1> encoding_type;
        typedef dlib::radial_basis_kernel<encoding_type> kernel_type;

        std::vector<std::string> labels; 
        std::vector<encoding_type> samples;

        typedef one_vs_all_trainer<any_trainer<encoding_type, float>, std::string> ova_trainer;
        ova_trainer trainer;

        typedef radial_basis_kernel<encoding_type> rbf_kernel;

        krr_trainer<rbf_kernel> rbf_trainer;
        rbf_trainer.set_kernel(rbf_kernel(0.1));
        trainer.set_trainer(probabilistic(rbf_trainer, 3));

        one_vs_all_decision_function<ova_trainer> df = trainer.train(samples, labels);
        auto p = df(samples[35]);
```

**Comment by idilsulo** [comment]
I'm thinking about using an approach like Platt scaling that is also proposed in the following link: [https://prateekvjoshi.com/2015/12/15/how-to-compute-confidence-measure-for-svm-classifiers/](https://prateekvjoshi.com/2015/12/15/how-to-compute-confidence-measure-for-svm-classifiers/)

How can I train a probabilistic class on top of the trainer using Dlib library?

**Comment by davisking** [comment]
To do Platt scaling you can call http://dlib.net/ml.html#learn_platt_scaling,
or use the http://dlib.net/ml.html#train_probabilistic_decision_function
wrapper.  There are other techniques like isotonic regression as well.
It's straightforward to apply these to binary classifiers, it's less simple
for multi-class methods and I don't have any ready made tools for doing
that in dlib.  The simplest thing is to find the maximum likelihood
parameters of a multi-class logistic regression model fit on the output
parameters of the model. You can use the find_min optimizers in dlib to set
that up.  Platt scaling is basically the 2 class version of that.

**Comment by idilsulo** [comment]
You are right Platt scaling is a 2 class version of that. Yet, my problem is a multiclass one. I am trying to classify the encodings of the faces of people using the trainer that I have mentioned above. 

I have also tried using the train_probabilistic_decision_function as in the example given below:
   ```
    typedef probabilistic_decision_function<kernel_type> probabilistic_funct_type;  
    typedef normalized_function<probabilistic_funct_type> pfunct_type;

    pfunct_type learned_pfunct; 
    learned_pfunct.normalizer = normalizer;
    learned_pfunct.function = train_probabilistic_decision_function(trainer, samples, labels, 3);
```
However, the trainer for the one_vs_all is a little bit different compared to krr_trainer and svm_trainer. Therefore, I was not able to use the train_probabilistic_decision_function wrapper for this purpose. 

Are there any examples on how to apply train_probabilistic_decision_function wrapper to one_vs_all trainer. Also, do you have any other suggestions on how to compare the predictions for such a problem?

**Comment by davisking** [comment]
There isn't anything in dlib that will give you this kind of mutli-class
probability distribution.  train_probabilistic_decision_function is only
for binary classification problems.

It's worth taking a step back and checking if you really need a calibrated
probability distribution here.  I would be very surprised if that were the
case.  You should be able to use the regular classifier output to do this
sort of thing. Unless you are going to be putting those output PDFs into
some kind of Bayesian filter or some other similar construct you very
likely don't care about getting probabilities but instead just want to know
things like "which class is most likely" or "give me a rank ordering of the
most likely class labels".  Neither of those things require probabilities,
as all these methods that convert classifier outputs into probabilities
just monotonically scale the outputs of the classifier.

**Comment by idilsulo** [comment]
What about the svm_multiclass_linear_trainer? Do you think that it can be used for such a face classification problem? 

Here, we want to determine the class of a face by considering its encodings. Given the face encodings, can we make any comment on whether the face does not belong to any particular class? How can we evaluate the value returned by the multiclass_linear_decision_function?

**Comment by davisking** [comment]
All of the classifiers in dlib give you a number that says how likely an
object is to be in the class they are predicting.  If all the classifiers
report that your new sample isn't an example of their positive class, then
it's none of them.
