### ISSUE TITLE
Unable to compile Dlib with Xcode iOS

### ISSUE THREAD

**Issue by harshitazilen** [davisking/dlib#1819]
Unable to compile Xcode iOS project with Dlib. 

I performed following steps:
1. Imported Dlib in my Xcode project.
2. Set all "other linker flags" and "header search paths" in my Xcode settings.
3. Compile the code

- While compiling the code, I face below error:
`Dlib requires C++11 support.  Give your compiler the -std=c++11 option to enable it.` in file "algs.h"

I checked my "Build settings" tab of Xcode, and updated the "Apple Clang - Language C++" > "C++ Language Dialect" flag to "-std=c++11".

Still I face the same error. Kindly help me.

**Comment by Hellomik2002** [comment]
any solution ?
