### ISSUE TITLE
Face Recognition on D-Lib

### ISSUE THREAD

**Issue by praveenlovely** [davisking/dlib#182]
Hi Dr.Davis,
Will we be able to generate a score using D-Lib? Can we directly use your classifier which has already been trained under several images as a probe to generate scores with test images?

**Comment by davisking** [comment]
The detection_confidence field of the full_detection (see
http://dlib.net/dlib/image_processing/object_detector_abstract.h.html#full_detection)
gives the detection score.

**Comment by praveenlovely** [comment]
Impressive!
Thank you! Do you have a Python version for the same?

**Comment by davisking** [comment]
This is covered in the example program: http://dlib.net/face_detector.py.html

**Comment by praveenlovely** [comment]
I meant, if you have a python version for the score program

**Comment by davisking** [comment]
You mean the score of each face detection?

**Comment by praveenlovely** [comment]
Yes, I would like to generate a score for every face detection. So that I could run it to find TP TN, FP and FN.

**Comment by davisking** [comment]
Yes, that's in the example program.
