### ISSUE TITLE
Want some example dockerfile(s)?

### ISSUE THREAD

**Issue by xkortex** [davisking/dlib#1822]
I have been using dlib in containers a ton lately, such as [here](https://github.com/TadasBaltrusaitis/OpenFace/blob/develop/docker/Dockerfile#L54) and so have a bunch of variant dockerfiles around. Would you be interested in a PR with some dockerfiles and docker compose?

I would structure it something like:
```
./docker-compose.yml
./docker/Dockerfile # bare bones example in Ubuntu18
./docker/dlib-python.docker # dlib + python
./docker/dlib-gpu.docker # dlib with cuda bindings
./docker/Readme.md # container readme and build instructions
```

**Comment by davisking** [comment]
Thanks for the offer, but my experience is that everyone in general wants to setup docker images differently, and there is already good documentation on how to do so on the docker website.  So I don't think adding this to the dlib repo will improve the overall user experience.
