### ISSUE TITLE
Question about bounding box regression in MMOD loss

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#1824]
Hi!
There are some details that I might not understand about the bounding box regression option within the MMOD loss. I've sucessfully trained a 2-class detector using this model:

``` c++
template<long num_filters, typename SUBNET> using con5d = con<num_filters, 5, 5, 2, 2, SUBNET>;
template<long num_filters, typename SUBNET> using con5 = con<num_filters, 5, 5, 1, 1, SUBNET>;
template<typename SUBNET> using downsampler = relu<bn_con<con5d<32, relu<bn_con<con5d<32, relu<bn_con<con5d<16, SUBNET>>>>>>>>>;
template<long num_filters, typename SUBNET> using rcon5 = relu<bn_con<con5<num_filters, SUBNET>>>;
using net_type = loss_mmod<con<1, 9, 9, 1, 1, rcon5<256, rcon5<128, rcon5<128, rcon5<96, rcon5<96, rcon5<64, rcon5<64, rcon5<64, downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>>>>>>;
```

I have manually labelled 1770 images to train it and it works great.
It achieves a loss of around `0.0084` by the end of the training and both classes are detected with high confidence (most of the time over than 1) for the images inside and outside the training set.

Then, I noticed that there is bounding box regression available just by doing:

```c++
options.use_bounding_box_regression = true;
net.subnet().layer_detail().set_num_filters(5 * options.detector_windows.size());
```

However, when I train again on the same data set with only that change, the detector is not able to reach that loss (it only reaches `0.44`).

As a result, I was wondering if there is something else that I need to do? Maybe I should play with the `lambda`?
I've seen that for the car detection example, you trained a shape predictor separately, but I was wondering if that was because the bounding box regression maybe wasn't available in the MMOD loss at that time.
Do you think the model should be bigger to be able to accommodate 5 times as many filters? I think it is already quite big for the task I'm trying to do.

By the way, I haven't forgotten about the PR for the multi channel loss, I'm trying to come up with a test that is not too complex...

Thank you :)

**Comment by davisking** [comment]
Right, it wasn’t available at the time. Getting this working is also requires a bit of fiddling. With lambda and also often by adding a bit to the network.

**Comment by arrufat** [comment]
Ah, ok thank you, I will play with it :)
