### ISSUE TITLE
About dlib.shape_predictor's output in python 

### ISSUE THREAD

**Issue by SYSUMSD** [davisking/dlib#1827]
I have successfully used dlib.shape_predictor to detect landmarks on a face. Here are the codes:
`
detector = dlib.get_frontal_face_detector()     

predictor = dlib.shape_predictor('/home/msd/face recognization/Dlib_face_detection_from_camera-master/data/dlib/shape_predictor_68_face_landmarks.dat')     
  
img = cv2.imread("/home/msd/face recognization/test.jpg", 0)      

faces = detector(img, 0)

landmarks68 = [[p.x, p.y] for p in predictor(img, faces[0]).parts()]
`

But when I want to do some more deepgoing researches on these landmarks I have a question:
This code can return the coordinates of landmarks. What is the orgin of these coordinates? Are these coordinates start from 0 like a python list? Or are these coordinates start from 1 like our count a photo's pixels?

**Comment by davisking** [comment]
They are the indexes into the images you used in training.

**Comment by SYSUMSD** [comment]
> They are the indexes into the images you used in training.
> […](#)
> On Jul 17, 2019, at 3:01 AM, SIDI MA ***@***.***> wrote: I have successfully used dlib.shape_predictor to detect landmarks on a face. Here are the codes: detector = dlib.get_frontal_face_detector() predictor = dlib.shape_predictor('/home/msd/face recognization/Dlib_face_detection_from_camera-master/data/dlib/shape_predictor_68_face_landmarks.dat') img = cv2.imread("/home/msd/face recognization/test.jpg", 0) faces = detector(img, 0) landmarks68 = [[p.x, p.y] for p in predictor(img, faces[0]).parts()] But when I want to do some more deepgoing researches on these landmarks I have a question: This code can return the coordinates of landmarks. What is the orgin of these coordinates? Are these coordinates start from 0 like a python list? Or are these coordinates start from 1 like our count a photo's pixels? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks！
Now I want to get the gray value of a landmark in a face through a  numpy.array class like **img** variable in the above codes.  I have to transform the dlib.shape_predictor's output coordinates  [x,y] to [x-1,y-1] so I can get the gray value of this landmark from a numpy.array class.

**Comment by davisking** [comment]
Any code or models I have written that output image coordinates always output them as indexes into images.  So you never subtract 1 from them.  I'm not sure what you have done here.  Maybe you have trained your own model to regress to outputs that are off by 1 and therefore need to do this subtraction.  But I suspect that is not the case.

**Comment by SYSUMSD** [comment]
Thanks. I have reviewed the code and discoveried that I don't need to do a substraction as you say. I have made a mistake about the pixels' coordinate in a image.
Now I know how to get the gray value from a point got from your model correctly!
