### ISSUE TITLE
install dlib for Python3.5.2 in Ubuntu16.0.4

### ISSUE THREAD

**Issue by monajalal** [davisking/dlib#183]
I followed these commands:

```
git clone git@github.com:davisking/dlib.git
cd dlib/
python setup.py install --yes DLIB_JPEG_SUPPORT
python python_examples/face_detector.py examples/faces/2007_007763.jpg
```
However I got this error:

```
   import dlib
  File "/home/mona/.virtualenvs/cv/lib/python3.5/site-packages/dlib-19.0.99-py3.5-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0: undefined symbol: PyClass_Type
```
How can this be fixed?

**Comment by davisking** [comment]
I just tried these commands on ubuntu 16.04 and they worked as expected.  It looks like you have multiple incompatible versions of python installed.  In particular, boost is apparently compiled against a different version of python than the one you are running.  If you install everything through apt-get it will all be correct.

**Comment by davisking** [comment]
Although, while those commands you posted work, if you try them with python3 instead of python on ubuntu 16.04 they don't work.  This is because of name changes in boost libraries, which I just fixed in dlib's cmake scripts.
