### ISSUE TITLE
integer overflow in array2d_kernel.h set_size

### ISSUE THREAD

**Issue by pauldreik** [davisking/dlib#1830]
I fuzzed dlib::load_image and found this with undefined behaviour sanitizer:
nr_*nc_ overflows.

https://github.com/davisking/dlib/blob/2704f3e26df4e7deadd92174b659e54be89bc0dd/dlib/array2d/array2d_kernel.h#L492

How to reproduce:
 - compile with undefined behaviour sanitizer (-fsanitize=undefined) on clang or gcc
 - feed a [bad image](https://github.com/pauldreik/dlib/blob/fuzz/dlib/test/images/problematic/integer_overflow_3d4e1dc8.txt) to image_load

You can do this by checking out the [fuzz branch in my fork](https://github.com/pauldreik/dlib/tree/fuzz), build the unit tests, and executing
```./dtest -d --test_image_load ../images/problematic/integer_overflow_3d4e1dc8.txt```

Here is an example output:
```
paul@tonfisk:~/code/delaktig/dlib/dlib/test/build$ ./dtest -d --test_image_load ../images/problematic/integer_overflow_3d4e1dc8.txt 
Running test_image_load / /home/paul/code/delaktig/dlib/dlib/../dlib/image_loader/../image_transforms/../statistics/../matrix/../array2d/array2d_kernel.h:509:47: runtime error: signed integer overflow: 4280353023 * 4280352826 cannot be represented in type 'long int'
                                                                               

Testing Finished
Total number of individual testing statements executed: 0
All tests completed successfully

```

I made a simple check for large values by summing the integer logarithms of nr and nc to verify it's reasonable before multiplying and allocating. Are you interested in that fix?

**Comment by davisking** [comment]
Sure, a PR that converts this into a proper exception would be welcome. :)

**Comment by pauldreik** [comment]
This is now included in https://github.com/davisking/dlib/pull/1834

**Comment by pauldreik** [comment]
just fending off autoclose
