### ISSUE TITLE
is <dlib/gui_widgets.h> necessary for face detector to work?

### ISSUE THREAD

**Issue by bchen3** [davisking/dlib#1832]
Hi, is this file <dlib/gui_widgets.h> necessary for face detector to work? My code runs ok without it (quite slow though). But when <dlib/gui_widgets.h> is included in the project, error messages shows in gui_core_kernel_2.h: "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."  How's this happend?

**Comment by Cydral** [comment]
Hi @bchen3, no this lib is not required for the face detector. For the performance issue, please read what has been published by @davisking which is usually useful... If you use the DNN-based detector, having a GPU card seems almost essential for satisfactory performance.

**Comment by bchen3** [comment]
Hi, thanks for your reply. Another question is, what image-preprocessing suggestions would you make on face detection  for better results? Since I found out that certain pre-processing adjustments on any given images, like HDR, increase the accuracy. btw, I'm using HOG-based detector.




------------------ 原始邮件 ------------------
发件人: "Cydral"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 下午3:45
收件人: "davisking/dlib"<dlib@noreply.github.com>;
抄送: "陈波"<1132756202@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [davisking/dlib] is <dlib/gui_widgets.h> necessary for facedetector to work? (#1832)




Hi @bchen3, no this lib is not required for the face detector. For the performance issue, please read what has been published by @davisking which is usually useful... If you use the DNN-based detector, having a GPU card seems almost essential for satisfactory performance.

**Comment by Cydral** [comment]
Hi, the quality of image input is obviously important, but for both methods offered by Dlib, I didn't see a real difference (apart from an additional processing) to the integration of pre-processing adjustments of the images. I'm sometimes using histogram stretching for intensity values, especially if the HOG-based detector is the one deployed. Hope this can help you.

**Comment by bchen3** [comment]
Thanks for your immediate reply. About image preprocessing, I've personally tested serval filters using photpshop(along with some other softwares), and (fake)HDR(tone mapping) seems to be the best. It produces the most accurate and satisfying detection rates for images with different lightings. However, I'm no sure if i'm on the right track, and I do need your option on this approach(single image HDR), and some advices on how to code this kind of filter would be appreciated! 




------------------ 原始邮件 ------------------
发件人: "Cydral"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 下午4:37
收件人: "davisking/dlib"<dlib@noreply.github.com>;
抄送: "陈波"<1132756202@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [davisking/dlib] is <dlib/gui_widgets.h> necessary for facedetector to work? (#1832)




Hi, the quality of image input is obviously important, but for both methods offered by Dlib, I didn't see a real difference (apart from an additional processing) to the integration of pre-processing adjustments of the images. I'm sometimes using histogram stretching for intensity values, especially if the HOG-based detector is the one deployed. Hope this can help you.

**Comment by bchen3** [comment]
Another question, would you suggest use correlation_tracker(or any other tracker) for face alignment in real time face detection? I did test dlib correlation_tracker() to track face in live video frames, yet foud out it was not as good as I supposed, and it lost face very easily when face moved around quickly. Any idea why this happened?  Need your option! Thanks!

**Comment by Cydral** [comment]
The Robertson-HDR algorithm is more a filter used during a capture and thus to avoid the limited dynamic range during an acquisition. If you are working on static images, you however need to have different images (ideally with an same scene) at different exposures.

For instance, you can use three different pictures (that's for instance the mechanism applied with the iPhone cam) with underexposed, normally exposed and overexposed to capture the full brightness range (very bright, very dark pixels) but you can also play with the exposure parameters of your camera.

The second step of this processing is to align images (feature-based alignment is a method you can implement with Dlib) and the last point is to estimate the Camera Response Function (CRF) to recalculate final pixels by averaging all scaled valued. Check this document for details (http://www.pauldebevec.com/Research/HDR/debevec-siggraph97.pdf) which also provides Matlab code.

**Comment by Cydral** [comment]
Regarding your second question, the correlation tracking implemented in Dlib is really good and can also be used for a multi-object tracking.
On a standard configuration, you can expect to reach about 10~15FPS using this method. To accelerate the process, you need to take advantage of a pipe (for captured images) and threads to deal with object tracking on video.
