### ISSUE TITLE
Is Dlib face detector evaluted on some benchmark?

### ISSUE THREAD

**Issue by mrgloom** [davisking/dlib#184]
Is Dlib face detector evaluted on some benchmark (like [FDDB](http://vis-www.cs.umass.edu/fddb/) for example)?

Is it based on HOG+Linear SVM (by Dalal & Triggs) or there are some modification?

**Comment by davisking** [comment]
The detector is discussed in this paper: https://arxiv.org/abs/1502.00046

The specific trained face model that comes with dlib is slightly better than the one in that paper since the model that comes with dlib is actually 5 HOG models.
