### ISSUE TITLE
load_image indirectly uses uninitialised value

### ISSUE THREAD

**Issue by pauldreik** [davisking/dlib#1840]
Running a short image file through load_image() makes the program use unitialized values, which is undefined behaviour.

I happened to see this in the source, and verified it.

The problem is that the buffer https://github.com/davisking/dlib/blob/48b9bf3f93f47f6173e101bc81343d55eedf242d/dlib/image_loader/load_image.h#L37 is filled with 0 to 8 bytes by the file reading, then the elements are referenced a bit further down.

To reproduce:
- build in debug mode
- create a short file, for instance with ```echo -e B >short.bin``` or ```cat /dev/null >empty.bin```
-invoke ```load_image("short.bin")``` through valgrind

The following is output by valgrind:
```
paul@tonfisk:~/code/delaktig/dlib/dlib/test/build_normal$ valgrind ./dtest -d  --test_image_load short.bin 
==22027== Memcheck, a memory error detector
==22027== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22027== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22027== Command: ./dtest -d --test_image_load short.bin
==22027== 
Running test_image_load / ==22027== Conditional jump or move depends on uninitialised value(s)
==22027==    at 0x1C5EFC: dlib::image_file_type::read_type(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (load_image.h:48)
==22027==    by 0x1C6E63: void dlib::load_image<dlib::array2d<dlib::rgb_pixel, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::array2d<dlib::rgb_pixel, dlib::memory_manager_stateless_kernel_1<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (load_image.h:74)
==22027==    by 0x1C4464: (anonymous namespace)::image_load_tester::invoke_on_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (image_load.cpp:58)
==22027==    by 0x1C424C: (anonymous namespace)::image_load_tester::invoke_on_file_or_dir(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (image_load.cpp:44)
==22027==    by 0x1C41BF: (anonymous namespace)::image_load_tester::perform_test(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (image_load.cpp:39)
==22027==    by 0x1B2385: main (main.cpp:142)
==22027== 

```

Proposed fix: either memset, or use std::array

**Comment by davisking** [comment]
Good find.  I think the right thing to do is to say `char buffer[9] = {0}`.  Nothing fancy needed. :)

You want to submit the PR? :)

**Comment by pauldreik** [comment]
Yes, good old C to the rescue! Not even the {0} is necessary, only the {}.
I will add it together with the handicapped fuzz pull request :)

**Comment by davisking** [comment]
Right, but {0} is a bit more readable and suggestive of what happens.  Most
importantly to people who are unsure what {} does, which I'm sure is a
non-empty set of people.

**Comment by davisking** [comment]
Yeah and that sounds awesome.  More generally, feel free to submit a whole bunch of PRs that fix whatever you think needs fixing.  No need to post issues first (but you are welcome to do that as well if you are so inclined) :)

**Comment by pauldreik** [comment]
> Right, but {0} is a bit more readable and suggestive of what happens.  Most

I don't agree, because that zero tricks people into thinking that the 0 is broadcasted! See here https://cppinsights.io/lnk?code=dm9pZCBmKCkKewogICAgIGludCB3aXRob3V0emVyb1s5XT17fTsKICAgICBpbnQgd2l0aHplcm9bOV09ezB9OwogICAgIGludCB3aXRob25lWzldPXsxfTsKfQo=&insightsOptions=cpp17&std=cpp17&rev=1.0

> No need to post issues first

The good thing with an issue is that it gives something to point and link to, if it would be needed. I prefer when bugs are visible, not hidden in a pull request. Glad you don't mind!

**Comment by davisking** [comment]
But the 0 is assigned everywhere.  But yes, if you put {1} thinking it
would broadcast that is bad.  But I see your point.  It may suggest to
people that {1} will broadcast and they will learn the wrong thing.

**Comment by pauldreik** [comment]
prevent auto close
