### ISSUE TITLE
outside bounds access during xml parsing

### ISSUE THREAD

**Issue by pauldreik** [davisking/dlib#1844]
Fuzzing dlib::xml_parser I found a crash after 177 milliseconds. It's a string access outside bounds in [this function](https://github.com/davisking/dlib/blob/48b9bf3f93f47f6173e101bc81343d55eedf242d/dlib/xml_parser/xml_parser_kernel_1.h#L1204)

I will submit a pull request with the fix (replacing str[i] with str.at(i)).

**Comment by pauldreik** [comment]
The crashing input was:
```cpp
 "<?>\0"
```
but it can probably be minimized more.

**Comment by davisking** [comment]
Thanks for finding this.  Don't replace it with `str.at(i)` though.  That will break the contract for this method, and for the parser as a whole.  In this case, you should return -1, as this is what the contract in the header for this method indicates should happen in such situations.

**Comment by pauldreik** [comment]
I guess I will have to spend more than 30 s on the fix :-)
