### ISSUE TITLE
Semantic Segmentation example crashes with multiple GPUs and loss increase

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#1849]
Hi, I'm using dlib from latest git revision and the semantic segmentation example crashes when used with multiple GPUs and the loss increases, so the trainer reloads from a previous state.
I suspect this might be related to https://github.com/davisking/dlib/issues/1677.
As with that issue, the only modification I made to the example code was adding the GPU initializer list to the `dnn_trainer`.

Here's the exact error:
```
step#: 64369  learning rate: 0.1   average loss: 0.424571     steps without apparent progress: 7989
Loss has been increasing, reloading saved state from pascal_voc2012_trainer_state_file.dat_
An unhandled exception was inside a dlib::thread_pool when it was destructed.
It's what string is: 
Error while calling cudaMemset(loss_cuda_work_buffer, 0, sizeof(float)) in file ../dlib/cuda/cuda_dlib.cu:1676. code: 11, reason: invalid argument
```

I suspect this might be hard to reproduce on other people's machines, but I have saved the state files when reloaded from makes this happen, so if you come up with a fix, I can try it easily.

Thanks in advance.

**Comment by arrufat** [comment]
I forgot to mention:
- loading the state itself works fine: I can resume the training from that point
- after resuming, training works well, but when loss increases and tries to reload it again, it crashes
- I have tried this several times and it happens every time
- if I delete that state file (and resume the training from the other one, since there are two of them) loss does not increase, therefore training does not crash.

**Comment by reunanen** [comment]
@arrufat I'll try to reproduce this problem.

> I have saved the state files 

I'll try to reproduce from scratch, but in case my training proceeds differently, could you share the problematic state file?

**Comment by arrufat** [comment]
Hi @reunanen, thank you again, you can download it from [here](https://send.firefox.com/download/352e17aba4fad096/#6VIpYpm0c0apHEZaQ6ck9g) (the link will expire after 1 day or 1 download):

**Comment by reunanen** [comment]
Can reproduce. Will look into it.
