### ISSUE TITLE
save_bmp() function has bug

### ISSUE THREAD

**Issue by xhuan8** [davisking/dlib#1853]
## Expected Behavior
I try to save the face chip after face detection with the following code:
`
extract_image_chip(img, get_face_chip_details(shape, 150, 0.25), face_chip);
matrix<rgb_pixel> face_chip_move = move(face_chip);
...
save_bmp(face_chip_move, faceFile);
`
it suppose to save the face_chip to file.

## Current Behavior
some of the images looks like the data is misaligned, it shows the pointer of first row is incorrect, also there are color masks over some regions.
save_png() will not have this kind of problem.

## Steps to Reproduce
load_image
sub_image
save_bmp
it can be reproduced by invoke the above methods, change the location of rectangle since it may related.

* **Version**: 19.17
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 10 64bit
* **Compiler**: Visual Studio 2017 64bit
![101725_9_](https://user-images.githubusercontent.com/53556761/62276322-5ebb8900-b476-11e9-998c-1aa1c33af42d.png)

**Comment by davisking** [comment]
Can you post a self contained example I can run that reproduces the problem?

**Comment by xhuan8** [comment]
the attachment contains input image "1.bmp", the cpp and exe file; run the exe will generate output images, both bmp and png.


At 2019-08-01 18:21:31, "Davis E. King" <notifications@github.com> wrote:
Can you post a self contained example I can run that reproduces the problem?

> On Aug 1, 2019, at 4:08 AM, xhuan8 <notifications@github.com> wrote:
>
> Expected Behavior
>
> I try to save the face chip after face detection with the following code:
> extract_image_chip(img, get_face_chip_details(shape, 150, 0.25), face_chip); matrix<rgb_pixel> face_chip_move = move(face_chip); ... save_bmp(face_chip_move, faceFile);
> it suppose to save the face_chip to file.
>
> Current Behavior
>
> some of the images looks like the data is misaligned, it shows the pointer of first row is incorrect, also there are color masks over some regions.
> save_png() will not have this kind of problem.
>
> Steps to Reproduce
>
> load_image
> sub_image
> save_bmp
> it can be reproduced by invoke the above methods, change the location of rectangle since it may related.
>
> Version: 19.17
> Where did you get dlib: dlib.net
> Platform: Windows 10 64bit
> Compiler: Visual Studio 2017 64bit
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易163邮箱发来的云附件
save_bmp.zip (32.38M, 2019年8月17日 13:09 到期)
下载
