### ISSUE TITLE
Pedestrian detector

### ISSUE THREAD

**Issue by sturkmen72** [davisking/dlib#186]
i have trained a pedestrian detector with INRIA dataset can be found at https://github.com/sturkmen72/dlib_pedestrian_detection

i will share some more information about how to train it soon on the github repo.

many thanks for @davisking for the great library.

**Comment by davisking** [comment]
Sweet :)   Feel free to add this to the dlib users wiki.

**Comment by pliablepixels** [comment]
Hi there, thanks for this. Very new to dlib. Right now, I am using the face detect data library as such:
```
dlib::shape_predictor sp;
dlib::deserialize( "./shape_predictor_68_face_landmarks.dat" ) >> sp;
```

How does one go about using your contribution for pedestrian detection?

**Comment by tej06** [comment]
I've been trying to train a pedestrian detector using INRIA dataset as well. The training procedure seems to go fine. But I'm not able to detect anything even on the trained data. Does annotation have to do anything with it? Also how does merging the pictures help?

**Comment by sturkmen72** [comment]
can i see your training.xml

**Comment by tej06** [comment]
[https://github.com/tej06/dlib-pedestrian-detection/blob/master/training.xml](url)

**Comment by sturkmen72** [comment]
using INRIA's annotation information to create such training.xml is possible.
how much time did you spend to do it?

**Comment by tej06** [comment]
I wrote a python snippet to extract the information from the INRIA's annotation information. It took me somewhere around 15 to 20 mins. That had an issue where some annotations were not fine. So i annotated them again using imglab. My problem is that after training my percentage of detection is 0.

**Comment by sturkmen72** [comment]
i found the code i used before to generate annotation file and generated four files. you can find them at https://github.com/sturkmen72/dlib_pedestrian_detection/tree/master/INRIA

i was planning to try creating a detector but did not find some free time yet

**Comment by tej06** [comment]
Thanks a lot:) I'll train the detector with this.

How does overlapping annotations affect the training procedure?

**Comment by sturkmen72** [comment]
as i said i did not try yet. i am not too experienced in this field.

**Comment by sturkmen72** [comment]
what is your purpose to train a pedestrian detector?

**Comment by tej06** [comment]
It's a part of a project I'm working on.

**Comment by sturkmen72** [comment]
did you try OpenCV's HOGDecsriptor ?

**Comment by tej06** [comment]
Yes I did. It works well. But it's a bit fickle. Even with NMS it behaves erratically for video streams. I'm trying to achieve a better detection using DLib. If this doesn't work out I'll resort to OpenCV's HOGDescriptor.

**Comment by davisking** [comment]
As I recall, INRIA doesn't label all the people in each image.  That's why it's not working.  There is also an issue of excessively tight cropping which is far from ideal.  You want to train on images that look like the real testing images, not ones that are cropped in some obviously target biased way. But most importantly, the dlib training algorithm uses all non-labeled parts of the image as negatives, so if there are any people in the background it's not going to work very well and will likely learn that the lowest error behavior is to never detect anything.  This feature is why you don't need to deal with hard negative mining.  It does that for you, but it's obviously going to do something bad if the background is full of unlabeled people.

You should get a more modern dataset, like the Caltech Pedestrian Detection Benchmark and take care that you train on images that are fully and consistently labeled.

**Comment by davisking** [comment]
Also, this is such a common question that I just added a new FAQ for it: http://dlib.net/faq.html#WhydoesnttheobjectdetectorItrainedwork :)

**Comment by tej06** [comment]
Thanks a lot **@davisking** This sure did help a lot:)

**Comment by davisking** [comment]
No problem.  I should have written this FAQ answer a long time ago :/

**Comment by madduci** [comment]
Hi @davisking ,
I've found this closed issue and I want to share the work I've done so far with some dataset publicly available on internet: to train the pedestrian classifier, I'm using[this one](http://iris.usc.edu/Vision-Users/OldUsers/bowu/DatasetWebpage/dataset.html) which contains some scenarios with partial occluded elements as well.
All the data from USC is shipped with ground truth data, which makes it easier to be used with dlib, therefore I've written a parser for those XML data and converted in the format supported by dlib (the same used for face_detection). If anyone is still interested, you can find the parser (written with Python 3) here: [Conversion of Ground Truth data for the USC dataset](https://gist.github.com/madduci/9cce47c81875e89a08ae2e67012e12d9).

By the way, thank you for all the efforts you put in this work!
