### ISSUE TITLE
How can I know dlib use gpu

### ISSUE THREAD

**Issue by Julius-ZCJ** [davisking/dlib#1860]
I use follow command to install: 
git clone https://github.com/davisking/dlib.git
cd dlib
mkdir build
cd build
cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
cmake --build .
cd ..
python3.6 setup.py install --set USE_AVX_INSTRUCTIONS=yes --set DLIB_USE_CUDA=yes

And when I use Dlib, I find this spend time is same as I run in CPU, the time is 0.27s,  and I use nvidia-smi to find that Dlib is not use GPU. how can I install Dlib and I can run Dlib in GPU. Thank you

**Comment by ZHUchaojun** [comment]
I have know my dlib not run in gpu, and so I want to cmake it with cuda , but there has something wrong.
Ｉ find that when I cmake my dlib, it gives me error:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /dlib/dlib
CUDA_curand_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /dlib/dlib
CUDA_cusolver_LIBRARY (ADVANCED)
    linked by target "dlib" in directory /dlib/dlib

My cmake version is 3.5.1,and I also try use cmake3.14.6, but it no use , I have no idea abut this error.
Have someone has same question and solved? Can you tell me how to fix this error? Thank you very much.

**Comment by ManuelZ** [comment]
I'm having the same issue
