### ISSUE TITLE
Cannot build with CUDA 10.1 on Archlinux

### ISSUE THREAD

**Issue by alireza7991** [davisking/dlib#1861]
I'm trying to build dlib on Archlinux, using cuda 10.1 and cudnn 7.  Cuda and cudnn are both installed with pacman. When I try to build dlib I get following error:

```
-- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found suitable version "10.1", minimum required is "7.5")
-- DID NOT FIND CUDA
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA

```
There is no directory `/opt/cuda/include`, but I find an include directory in `/opt/cuda/targets/x86_64-linux/include/`. however trying to set `CUDA_INCLUDE_DIRS` to that path, does not work.

**Comment by alireza7991** [comment]
I could solve the error by making a symlink from `/opt/cuda/targets/x86_64-linux/include/` to `/opt/cuda/include`. It seems that cmake is looking for include directory in cuda home path and even changing `CUDA_INCLUDE_DIRS` to right include directory does not fix that issue.
It would be great if we have some patch in dlib which will fix this issue in cmake cuda find package

**Comment by davisking** [comment]
What happens if you set CMAKE_PREFIX_PATH?  That should do the trick.  See
https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html
