### ISSUE TITLE
building dlib with python bindings yocto

### ISSUE THREAD

**Issue by Harishrelysys** [davisking/dlib#1867]
Hi,
    We are able to get C++ library in our custom board using yocto recipe.To get dlib with python bindings pip is not working in our board.So when I am trying to run python setup.py install in yocto recipe I am facing some issue related to 64 bit and 32 bit platform(our custom board is 32 bit armhf and the PC I am building is x64 intel) when I run setup.py in yocto recipe I am getting following error

My yocto recipe is:
===============
```
SUMMARY = "A toolkit for making real world machine learning and data analysis applications"
HOMEPAGE = "https://github.com/davisking/dlib"

DEPENDS = "boost udev swig-native python python-setuptools python-native \
           python-setuptools-native python-distutils-extra-native python-py-native python3-sqlite3 sqlite3 sqlite3-native"
DEPENDS = "sqlite3 python3 python3-native python3-setuptools python3-cython"
           
LICENSE = "Boost-Software"
LIC_FILES_CHKSUM = "file://dlib/LICENSE.txt;md5=2c7a3fa82e66676005cd4ee2608fd7d2 \
                    file://dlib/external/pybind11/LICENSE;md5=beb87117af69fd10fbf9fb14c22a2e62 \
                    file://dlib/external/libpng/LICENSE;md5=243135ddedf702158f9170807cbcfb66 \
                    file://docs/docs/license.xml;md5=2e6ff4080dcb217d4d300b90e9aabb5b \
                    file://examples/LICENSE_FOR_EXAMPLE_PROGRAMS.txt;md5=57eee82829ed297e23d84de5f905afee \
                    file://examples/video_frames/license.txt;md5=127ee508b60a6be9dea8af3b441993dc \
                    file://python_examples/LICENSE_FOR_EXAMPLE_PROGRAMS.txt;md5=064f53ab40ea2b6a4bba1324149e4fde"

SRC_URI = "git://github.com/davisking/dlib.git;protocol=https"

PV = "1.0+git${SRCPV}"
#SRCREV = "3b794540baeabbcd033b544230401967106d5483"
SRCREV = "810ef7937d87c9265bcb5814a00a1f1691285ceb"

S = "${WORKDIR}/git"

inherit cmake

FILES_${PN} += "${libdir}/cmake/dlib"

EXTRA_OECMAKE += "-DDLIB_NO_GUI_SUPPORT=ON -DBUILD_SHARED_LIBS=ON"

do_compile_prepend() {
    export STAGING_LIBDIR=${STAGING_LIBDIR}
    export STAGING_INCDIR=${STAGING_INCDIR}
}

do_install_append() {
    export STAGING_LIBDIR=${STAGING_LIBDIR}
    export STAGING_INCDIR=${STAGING_INCDIR}
    ${S}../recipe-sysroot-native/usr/bin/python3-native/python3 ${S}/setup.py install
}
```
error:
=====

> inux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/temp/log.do_compile.18361
> Log data follows:
> | DEBUG: Executing shell function do_compile
> | running build
> | running build_py
> | package init file 'dlib/__init__.py' not found (or not a regular file)
> | running build_ext
> | Building extension for Python 2.7.13 (default, Jul 15 2019, 10:21:10)
> | Invoking CMake setup: 'cmake /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/build/lib.linux-x86_64-2.7 -DPYTHON_EXECUTABLE=/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/bin/python-native/python -DCMAKE_BUILD_TYPE=Release'
> | -- Found PythonInterp: /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/bin/python-native/python (found version "2.7.13")
> | CMake Error at /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/git/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:122 (message):
> |   Python config failure: Python is 64-bit, chosen compiler is 32-bit
> | Call Stack (most recent call first):
> |   /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/git/dlib/external/pybind11/tools/pybind11Tools.cmake:16 (find_package)
> |   /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/git/dlib/external/pybind11/CMakeLists.txt:33 (include)
> | 
> | 
> | -- Configuring incomplete, errors occurred!
> | See also "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
> | Traceback (most recent call last):
> |   File "setup.py", line 262, in <module>
> |     'Topic :: Software Development',
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/core.py", line 151, in setup
> |     dist.run_commands()
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
> |     self.run_command(cmd)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
> |     cmd_obj.run()
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/command/build.py", line 127, in run
> |     self.run_command(cmd_name)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
> |     self.distribution.run_command(command)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
> |     cmd_obj.run()
> |   File "setup.py", line 135, in run
> |     self.build_extension(ext)
> |   File "setup.py", line 172, in build_extension
> |     subprocess.check_call(cmake_setup, cwd=build_folder)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 186, in check_call
> |     raise CalledProcessError(retcode, cmd)
> | subprocess.CalledProcessError: Command '['cmake', '/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/build/lib.linux-x86_64-2.7', '-DPYTHON_EXECUTABLE=/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/bin/python-native/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
> | ERROR: python setup.py build execution failed.
> | WARNING: /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/temp/run.do_compile.18361:1 exit 1 from 'exit 1'
> | ERROR: Function failed: do_compile (log file is located at /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/temp/log.do_compile.18361)
> ERROR: Task (/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/../meta-rt-demos/recipes-firstdemo/dlib/dlib.bb:do_compile) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 1571 tasks of which 1570 didn't need to be rerun and 1 failed.
> 
> Summary: 1 task failed:
>   /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/../meta-rt-demos/recipes-firstdemo/dlib/dlib.bb:do_compile
> Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

When i comment some lines in FindPythonLibsNew.cmake 

commented lines:
-----------------------
if(CMAKE_SIZEOF_VOID_P AND (NOT "${PYTHON_SIZEOF_VOID_P}" STREQUAL "${CMAKE_SIZEOF_VOID_P}"))
    if(PythonLibsNew_FIND_REQUIRED)
        math(EXPR _PYTHON_BITS "${PYTHON_SIZEOF_VOID_P} * 8")
        math(EXPR _CMAKE_BITS "${CMAKE_SIZEOF_VOID_P} * 8")
        message(FATAL_ERROR
            "Python config failure: Python is ${_PYTHON_BITS}-bit, "
            "chosen compiler is  ${_CMAKE_BITS}-bit")
    endif()
    set(PYTHONLIBS_FOUND FALSE)
    return()
endif()

its compiling but at the end again i am getting following error

error:
====
 

> /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot/usr/include/c++/7.2.1/bits/vector.tcc: In function 'void save_face_chips(dlib::numpy_image<dlib::rgb_pixel>, const std::vector<dlib::full_object_detection>&, const string&, size_t, float)':
> | /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot/usr/include/c++/7.2.1/bits/vector.tcc:105:21: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<dlib::chip_details*, std::vector<dlib::chip_details> >' changed in GCC 7.1
> |     _M_realloc_insert(end(), std::forward<_Args>(__args)...);
> |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> | /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot/usr/include/c++/7.2.1/bits/vector.tcc: In member function 'std::vector<std::vector<dlib::matrix<double, 0, 1> > > face_recognition_model_v1::batch_compute_face_descriptors(const std::vector<dlib::numpy_image<dlib::rgb_pixel> >&, const std::vector<std::vector<dlib::full_object_detection> >&, int, float)':
> | /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot/usr/include/c++/7.2.1/bits/vector.tcc:105:21: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<dlib::chip_details*, std::vector<dlib::chip_details> >' changed in GCC 7.1
> |     _M_realloc_insert(end(), std::forward<_Args>(__args)...);
> |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> | [100%] Linking CXX shared module /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/build/lib.linux-x86_64-2.7/dlib.so
> | /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/libsqlite3.so: file not recognized: File format not recognized
> | collect2: error: ld returned 1 exit status
> | make[2]: *** [CMakeFiles/dlib_python.dir/build.make:446: /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/build/build/lib.linux-x86_64-2.7/dlib.so] Error 1
> | make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/dlib_python.dir/all] Error 2
> | make: *** [Makefile:84: all] Error 2
> | Traceback (most recent call last):
> |   File "setup.py", line 262, in <module>
> |     'Topic :: Software Development',
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/core.py", line 151, in setup
> |     dist.run_commands()
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
> |     self.run_command(cmd)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
> |     cmd_obj.run()
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/command/build.py", line 127, in run
> |     self.run_command(cmd_name)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
> |     self.distribution.run_command(command)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
> |     cmd_obj.run()
> |   File "setup.py", line 135, in run
> |     self.build_extension(ext)
> |   File "setup.py", line 175, in build_extension
> |     subprocess.check_call(cmake_build, cwd=build_folder)
> |   File "/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 186, in check_call
> |     raise CalledProcessError(retcode, cmd)
> | subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2
> | ERROR: python setup.py build execution failed.
> | WARNING: /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/temp/run.do_compile.18466:1 exit 1 from 'exit 1'
> | ERROR: Function failed: do_compile (log file is located at /home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/dlib/1.0+gitAUTOINC+810ef7937d-r0/temp/log.do_compile.18466)
> ERROR: Task (/home/relysys/Harish_Workspace/Project/Renesas/RZG1H/build/user_work/build/../meta-rt-demos/recipes-firstdemo/dlib/dlib.bb:do_compile) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 1571 tasks of which 1570 didn't need to be rerun and 1 failed.
> 
What changes i have to make in setup.py for compiling dlib with python binding to my custom board

Board Info:
=======
Renesas RZG1H processor
Yocto 2.1.1

Thank you,

**Comment by jeranio** [comment]
Hello , have you found a solution.I am also trying to install dlib into an image using yocto but my recipe does not build with similar errors
