### ISSUE TITLE
config_reader enh.: optional quoting of values to preserve surrounding whitespace

### ISSUE THREAD

**Issue by lunakid** [davisking/dlib#1868]
_(New here, but watching the lib for quite a while now; love it!)_

Reading `config_reader_kernel_1.h`, it seems it could easily support preserving surrounding whitespace in values, when that's an important requirement, by just stripping an _optional_ pair of `"` chars from the value, right before adding it to the table. 
The quotes, if there, should also be non-escaped, but checking that is just a no-op, as escaped ones would be implicitly ignored anyway by the first char not being `'"'` (this assuming there's `\`- escaping defined for values).

_(Not proposing actual code, because I doubt I could come up with anything better (and in less time) than you would.)_

**Comment by davisking** [comment]
That's not a bad idea, but I'm hesitant to do this kind of thing as it changes the behavior in a non-backwards compatible way.  This code has been around for a long time and has a lot of users. Any users who already use quoted strings would be broken by such a change.

**Comment by lunakid** [comment]
Ah, true, I managed to ignore that completely. 
Depending on design priorities, perhaps there could still be a `#define` to enable it, though.

**Comment by davisking** [comment]
A #define isn't a great way to do that.  Users can more easily call some
trim() method that removes quotes from strings if that's what they want to
happen.
