### ISSUE TITLE
Transfer learning for shape predictor

### ISSUE THREAD

**Issue by paulinerousseau95** [davisking/dlib#1869]
Hi, 

First of all, thanks for the library and ABOVE all the examples and the quality pretrainning models that help a lot on the understanding of the library possibilities. 

I am a newbie on dlib, it is really my first contact with it, so I am sorry if the question seems naive or a little off scope, but I tried to find the answer on the forums and I didn't managed to. 

What I want to do is to use old models to enable transfer learning to the shape predictor, I first though that would be something simple,  but I didn't find a "parameter" on the API to do so. So I was happy so thought I could contribute to the project adding this parameter to the API and proposing it to the project. 

Looking into the code I identified the shape_predictor train in the shape_predictor_trainer.h [https://github.com/davisking/dlib/blob/170877da88fdd887b9404aec78646e604d8368d8/dlib/image_processing/shape_predictor_trainer.h#L242](url) with makes the real training. I was hopping be able pass as parameter a pre-training model, such as shape_predictor_68_face_landmark.dat, and do something like `net1 = net2;` as explained on this thread [https://sourceforge.net/p/dclib/discussion/442518/thread/40667e18/#4ce8/11e7](url). 

Well sure, collecting from the model all the parameters needed for the training function, such as the number of trees per level, the depth of the cascade, etc.

However, if I understood well for the shape predictor, the forest definition is not iterative, i.e. it does not reuse the previous values as basis for the next training iteration. It goes over each level and over each tree "in one shot", so even if it had another pre-calculated model,
where we had trees already calculated to use as initial values, it wouldn't really help, would it? 

Am I missing something?

Best,

**Comment by davisking** [comment]
Correct. Reusing a model to train a new one doesn’t really make sense for this algorithm. Just train from scratch. Training is fast anyway.
