### ISSUE TITLE
Library not loaded: libmkl_rt.dylib

### ISSUE THREAD

**Issue by spate141** [davisking/dlib#187]
I have successfully compiled and installed dlib in my MAC. I have also installed Dlib's Python Interface. But when I try to import dlib I am getting following error.

`ImportError                               Traceback (most recent call last)`
`<ipython-input-4-82a137582d6f> in <module>()`
`----> 1 import dlib`

`//anaconda/lib/python2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.6-x86_64.egg/dlib/__init__.py in <module>()`
`----> 1 from .dlib import *`
 `     2 __version__ = "19.1.99"`

`ImportError: dlopen(//anaconda/lib/python2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.6-x86_64.egg/dlib/dlib.so, 2): Library not loaded: libmkl_rt.dylib`
` Referenced from: //anaconda/lib/python2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.6-x86_64.egg/dlib/dlib.so`
` Reason: image not found`

Any reason ??

**Comment by davisking** [comment]
The error says it can't find libmkl_rt.  You must have the intel MKL library installed but not in your linker path.

**Comment by malikshubham827** [comment]
@davisking So what can be done in this regard? I am new in this, should I link intel library instead of what it is asking? If yes, how?
