### ISSUE TITLE
XCode Version 10.3 (10G8) compiler error "Functions that differ only in their return type cannot be overloaded" in several dlib headers

### ISSUE THREAD

**Issue by WimVriend** [davisking/dlib#1871]
## Expected Behavior

I installed dlib on my Mac following [these instructions](http://prabhu.xyz/2017/05/29/getting-started-with-dlib-on-ios.html) to the letter. Expected behaviour: successful compilation of my xcode project using dlib.

## Current Behavior

> // Copyright (C) 2010  Davis E. King (davis@dlib.net)
> // License: Boost Software License   See LICENSE.txt for the full license.
> #ifndef DLIB_LAPACk_GEEV_Hh_
> #define DLIB_LAPACk_GEEV_Hh_
> 
> #include "fortran_id.h"
> #include "../matrix.h"
> 
> namespace dlib
> {
>     namespace lapack
>     {
>         namespace binding
>         {
>             extern "C"
>             {
>                 void DLIB_FORTRAN_ID(dgeev) (char *jobvl, char *jobvr, integer *n, double * a,                > _**! Functions that differ only in their return type cannot be overloaded**_
>                                              integer *lda, double *wr, double *wi, double *vl, 
>                                              integer *ldvl, double *vr, integer *ldvr, double *work, 
>                                              integer *lwork, integer *info);
> 
>                 void DLIB_FORTRAN_ID(sgeev) (char *jobvl, char *jobvr, integer *n, float * a,  
> _**! Functions that differ only in their return type cannot be overloaded**_
>                                              integer *lda, float *wr, float *wi, float *vl, 
>                                              integer *ldvl, float *vr, integer *ldvr, float *work, 
>                                              integer *lwork, integer *info);
> 
>        }

## Steps to Reproduce

Install dlib on a Mac with Mojave and Xcode 10.3 using [these instructions](http://prabhu.xyz/2017/05/29/getting-started-with-dlib-on-ios.html). Create an xcode project, add dlib to it as mentioned in the same website and compile

* **Version**: 
9.17
* **Where did you get dlib**: 
dlib.net
* **Platform**: 
XCode 10.3 in Mac Mojave
* **Compiler**: 
Apple Clang, Base SDK iOS

**Comment by WimVriend** [comment]
Hi, 
I would like to add a bit of information to this issue. I am an experienced programmer in various environments, but I am new to iOS development and dlib. I understand that you devs must receive loads of newbie questions like mine, but I hope you want to help me with this (and maybe some other 51-year-old greenhorns like me :)

I fiddled with my project settings and find, that leaving out the DLIB_USE_LAPACK macro helps to bypass the problem. I understand that Lapack is used to speed things up? Of course, that is a feature I want in my project.

That leaves another question: Is there a way to verify that my project uses Lapack, even when the macro is left out? Does it use the default installation on my Mac?

**Comment by davisking** [comment]
The instructions in that web page are wrong.  I'm surprised you don't get
other errors, in particular, the one discussed here
http://dlib.net/faq.html#WhydoIgetUSERERRORinconsistentbuildconfigurationseedlibfaq2.
Follow the official instructions here: http://dlib.net/compile.html.

Also, I don't know what version of dlib you are using.  There is no such
version as 9.17, maybe you meant.  Please try the latest version from
github.

**Comment by WimVriend** [comment]
Hi, Davis,

Thanks for your answer. It was a typo... I meant 19.17 of course :(  It is difficult for someone new to be able to determine which how-to articles are (still) correct and which are not. 

In the end (after getting more errors like you said), I was able to compile my program with dlib, "without using cmake" (added all/sources.cpp etc.). Are there any drawbacks to that method I should know about?

**Comment by davisking** [comment]
Please don't use how-to articles. Always refer to the actual project's
instructions. 99% of these articles are written by students just learning
to program, and as a result, are generally wrong.

There aren't any drawbacks to building some other way. You can build dlib
in a lot of ways. The only restriction is that you need to understand your
build tools if you want to roll your own.  But that's not a dlib related
restriction.

**Comment by WimVriend** [comment]
Ok, that's clear. 

Some other installation-related question. I found that for OpenCV you can link the xcode project to a .framework.  Is it possible to build a dlib framework?
 I have also examined Swift and Cocoapods. Is it possible to install dlib as a "pod"?

If not, maybe that's a nice expansion :)

**Comment by davisking** [comment]
You can build the install target cmake generates and that will result in
the library being installed in the typical unix way. You can use any of the
other tooling cmake provides to setup your build. Aside from that you are
on your own for your IDE setup.

**Comment by WimVriend** [comment]
Sounds like a "No" ...

**Comment by davisking** [comment]
Try using the latest dlib from github.

**Comment by WimVriend** [comment]
Hello Davis,

Finally, I succeeded in mixing OpenCV and Dlib in my project. Thanks for fixing the BLAS and LAPACK headers in the repo.

What confused me most (and I think many other users who want to use Dlib in Xcode+Swift) are the many different solutions and parts of solutions posted on the WWW on this topic. It is still not completely clear to me, why it works now (and why it did not work before).

The official Dlib installation instructions only extend to the building process. I think it would be a great improvement, if someone would add an official guide on how to proceed after that... It would save you a lot of time answering questions like mine :)

**Comment by davisking** [comment]
Glad it's working.  

I understand where you are coming from.  But the topic of how to configure the vast array of possible c++ build environments, IDEs, compilers, and so forth is not not something that can be reasonably accomplished in the dlib documentation. The information about how to do this isn't dlib specific and is better served by the existing literature. For your case as an example, I don't even use XCode or Swift.  So I don't know what you do to setup those enthronements for C++ development or what pitfalls or usability problems might exist with regard to C++ development in those situations. 

It is unfortunate that there are all these blog posts about how to install dlib.  Nearly all of them are wrong.  Most of these things are written by students trying to pad their online resumes.  But unfortunately most of them haven't the foggiest idea how to use C++.  For example, a huge number of them trivially trigger ODR violations (https://en.wikipedia.org/wiki/One_Definition_Rule), which isn't a dlib thing, it's a general ISO standard C++ thing.  It's a basic rule in the language that every C++ developer needs to be mindful of when setting up their build environment. I try to make this easy by having very simple CMake examples that do the right thing. 

I think the bigger issue here is why is this page (http://dlib.net/compile.html) less findable than these blog posts?  When you went looking for instructions, did you find http://dlib.net/compile.html right away? Or was it harder to find and you only found it later?  Maybe there is something I could improve that would cause http://dlib.net/compile.html to be more rapidly found or obviously the place to look. Can you walk through what happened when you tried to find out the answer to these questions? What did you do? What pages did you find? How did you find them? Stuff like that.

**Comment by WimVriend** [comment]
Hello Davis,

I understand your reasoning and I agree: you can't possibly describe all different installation procedures. And I certainly appreciate your patience.

Finding the wrong blogs and such on the internet is easy. I think I used the keywords "install dlib ios" and the [http://dlib.net/compile.html](http://dlib.net/compile.html) page does not show up in the top. It's quit a challenge to change that, I'm afraid...

**Comment by davisking** [comment]
Yeah, not super sure what I can do about that :|
