### ISSUE TITLE
dlib doesn't use cuda

### ISSUE THREAD

**Issue by akashchintha** [davisking/dlib#1874]
I tried installing dlib on Win10 by cloning the repo and running `python setup.py install` inside the dlib directory.

running install
running bdist_egg
running egg_info
creating dlib.egg-info
writing dlib.egg-info\PKG-INFO
writing dependency_links to dlib.egg-info\dependency_links.txt
writing top-level names to dlib.egg-info\top_level.txt
writing manifest file 'dlib.egg-info\SOURCES.txt'
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools\python\build*'
writing manifest file 'dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- The C compiler identification is MSVC 19.16.27026.1
-- The CXX compiler identification is MSVC 19.16.27026.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Program Files/Python36/python.exe (found version "3.6.7")
-- Found PythonLibs: C:/Program Files/Python36/libs/Python36.lib
-- pybind11 v2.2.2
-- Using CMake version: 3.14.0-rc3
-- Compiling dlib version: 19.17.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found suitable version "10.1", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
  cuda_dlib.cu
  cuda_dlib.cu
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cusolver_dlibapi.cu.obj
  cusolver_dlibapi.cu
  cusolver_dlibapi.cu
  -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
  -- pybind11 v2.2.2
  -- Using CMake version: 3.14.0-rc3
  -- Compiling dlib version: 19.17.99
  -- SSE4 instructions can be executed by the host processor.
  -- AVX instructions can be executed by the host processor.
  -- Enabling AVX instructions
  -- Looking for cuDNN install...
  -- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
  -- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
  -- C++11 activated.
  -- Configuring done
  -- Generating done

creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
copying build\lib.win-amd64-3.6\dlib.cp36-win_amd64.pyd -> build\bdist.win-amd64\egg
creating stub loader for dlib.cp36-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\dlib.py to dlib.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying dlib.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying dlib.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying dlib.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying dlib.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying dlib.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
creating dist
creating 'dist\dlib-19.17.99-py3.6-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing dlib-19.17.99-py3.6-win-amd64.egg
removing 'c:\program files\python36\lib\site-packages\dlib-19.17.99-py3.6-win-amd64.egg' (and everything under it)
creating c:\program files\python36\lib\site-packages\dlib-19.17.99-py3.6-win-amd64.egg
Extracting dlib-19.17.99-py3.6-win-amd64.egg to c:\program files\python36\lib\site-packages
dlib 19.17.99 is already the active version in easy-install.pth

Installed c:\program files\python36\lib\site-packages\dlib-19.17.99-py3.6-win-amd64.egg
Processing dependencies for dlib==19.17.99
Finished processing dependencies for dlib==19.17.99

The installation looks fine but dlib.DLIB_USE_CUDA returns false. It recognizes cuda but doesn't run on it.

**Comment by shaheryar1** [comment]
Did you find the solution?

**Comment by Mfweb** [comment]
But gpu cuda usage is 0%
`CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

Using CMake version: 3.15.3
Compiling dlib version: 19.18.0
Enabling AVX instructions
Looking for cuDNN install...
Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
Enabling CUDA support for dlib.  DLIB WILL USE CUDA
C++11 activated.
Configuring done
Generating done`

**Comment by akashchintha** [comment]
> Did you find the solution?

No. 
CUDA support is enabled for dlib but it doesn't use GPU for face extraction.
