### ISSUE TITLE
how to train face detection on your own using CNN+MMOD idea?

### ISSUE THREAD

**Issue by tuanhanhdmprof** [davisking/dlib#1878]
I want to train face detection on your own using CNN+MMOD idea (by Python + Keras). but I do not know how to start, how to define architecture, ... Can you help me?

**Comment by davisking** [comment]
Here is a complete example with documentation:
http://dlib.net/dnn_mmod_face_detection_ex.cpp.html

**Comment by fatemetardasti96** [comment]
any similar example with python?

**Comment by davisking** [comment]
No
