### ISSUE TITLE
What is the purpose of `concat1` ?

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#188]
I was a little confused when reading the docs on `concat`, and noticing there is a `concat1` defined. At first I thought `concat` would concatenate the output of the tagged layers with the output of `SUBNET`. But by reading the code, it seems to me `concat` only concatenates the output of the tagged layers, and ignores the output of `SUBNET`, thus, `concat1` would equivalent to `add_skip_layer`, is that right?

If that is the case, I suggest that the docs explicitly estates that `concat1` don't really concatenates anything, but that it is equivalent to `add_skip_layer`. Ideally, I believe `concat1` should not exists, but since it is already there, it may be too late to change the interface...

**Comment by davisking** [comment]
That's a good point.  I just deleted concat1 to avoid confusion.  I highly doubt anyone was using it :)
