### ISSUE TITLE
DLIB Features

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#1881]
Hi,
it has been a while. I found some old related questions but i think its more productive to ask it here.
Mainly its about "new" AI features and the feature of DLIB in generall. 

Do you have any plans ? (or other contributors) to develop one of the following features:
And if not so, why not? 
Or would you be willing to merge any high-quality contribution into dlib regarding those features:

1. Single Shot Detector (AKA YOLO or SSD)
2. 2019 State of the Art Object Detection (for example Cascade RCNN)
3. Weakly Supervised (or semi supervised) learning for object detection? (or classification)
4. Generative Adversarial Networks (GANs) (i know the layers all exist already to my knownledge, but not something like aworking GAN example)

thanks a lot and best wishes.
In my opinion dlib is one of the best written ML libaries out there and i would love it seeing getting extend to current topics of AI research.

+ Off topic: In case its a matter of ressources, are you willing to accept donation to be able to invest more time into dlib?

best wishes and thx a lot

**Comment by davisking** [comment]
I don't have any specific plans.  But this is nothing new. I've never worked on dlib with any kind of roadmap in mind.  Rather, I work on whatever I find interesting to work on at that moment.

I'm always happy to get high quality pull requests though. If you want to implement something from a recent CVPR paper or anything like that and get it to a high quality that would be a great contribution. Any of the things you just mentioned fit that description.

**Comment by DlibReza** [comment]
Hello Davis
Do you support newest version of CUDA when release in future years?
i am anxious because you dont release any version after 19.17 version.

**Comment by davisking** [comment]
The version of dlib on github should work with the newest cuda version.

**Comment by davisking** [comment]
It's been too long since the last release, so I just made v19.18 :)

**Comment by DlibReza** [comment]
Hello Davis
Thank you for your answer and for new version( v19.18) of Dlib.

**Comment by VisionEp1** [comment]
Thanks for your awnser. 
Do you see yourself working on any of those topics (1-4) in the near future?
(so in case i do a PR we wouldn't do the same thing)

**Comment by davisking** [comment]
I’m not going to work on them in the near future.  So feel free to tackle any of them.

**Comment by VisionEp1** [comment]
Thanks one more thing,
i know dlib uses cuda.

When i would add a new loss layer,
would i need to implement the cuda implementation aswell ?

(didnt work to much with cuda dev. yet)

**Comment by davisking** [comment]
Maybe. But most of the loss layers in dlib are just cpu code. So unless you are doing something really compute or bandwidth intensive cpu only is fine.
