### ISSUE TITLE
how to integrate dlib as part of project in ccs/eclipse without cmake?

### ISSUE THREAD

**Issue by Coneain** [davisking/dlib#1882]
Hi, I want to use dlib in embedded device. Generally people develop embedded program in CCS but I find CCS(code composer studio) is written on the base of Eclipse, so I want to integrate dlib as a part of my project in Eclipse.

(CCS just provides limited function of development, the source file will fail to be build
if it contains function like std::cout. I think if I can successfully make it in Eclipse,
then I can easily transplant my project in CCS with some simple modification.)

I followed the guidance on the site and successfully built a test project using Cmake in Eclipse, 
but CCS DOES NOT support Cmake. So I copied dlib/dlib directly to a test project but failed to build it.

The directory structure is very simple.

|--dlib-test
   |--src
  	|--main.cc
   |--dlib

The source code of main.cc is the same as dnn_metric_learning_ex.cpp in examples.
## Expected Behavior

I just want to integrate dlib as part of project and build it without using cmake.
## Current Behavior

It seemed like the library cannot be found properly.

make all 
Building target: dlib-test
Invoking: MacOS X C++ Linker
g++  -o "dlib-test"  ./src/main.o   
Undefined symbols for architecture x86_64:
  "dlib::threaded_object::stop()", referenced from:
  ...
  ...
	typeinfo for dlib::dnn_trainer ... in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dlib-test] Error 1
## Steps to Reproduce

directly copy dlib/dlib as part of project without any modification of include path and library search path

* **Version**: 
dlib 19.17
* **Where did you get dlib**: 
github
* **Platform**: 
macOS High Sierra 10.13.6
* **Compiler**: 
GCC C++ Compiler with MacOS X C++ Linker

**Comment by davisking** [comment]
Read the instructions here: http://dlib.net/compile.html.  They say how to
build without using cmake.
