### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by essalahsouad** [davisking/dlib#1883]
I started recently dealing with dlib, so would you excuse my ignorance?
I want to train dlib on my custom dataset (335 faces images 513*513)for iris landmark(10 pts)
i use [http://dlib.net/train_shape_predictor.py.html](http://dlib.net/train_shape_predictor.py.html)for training.
my xml file :
![Capture du 2019-09-22 02-39-19](https://user-images.githubusercontent.com/34586193/65381126-429fcf80-dce2-11e9-8240-806a97fab20b.png)
training options:
![Capture du 2019-09-22 02-40-29](https://user-images.githubusercontent.com/34586193/65381138-e12c3080-dce2-11e9-906d-2f6da515155a.png)
left predicted result  ,right groudtruth image
![Capture du 2019-09-22 02-44-02](https://user-images.githubusercontent.com/34586193/65381143-ff922c00-dce2-11e9-9f94-db7ebaf1660a.png)
i got bad result ,i don't know what the problem??
@davisking I will appreciate your help

**Comment by davisking** [comment]
I assume you are asking about the shape_predictor.  For that, each image
doesn't have to have the same points. If some are missing (e.g. maybe they
are occluded) that's fine.

**Comment by essalahsouad** [comment]
@davisking 
no, each image have 20pts(350 images 513*513)and for each one ,box top=1,left=1 and hiegh=width=511,but the points the point there are so close ,as is'it shown in the last pigturet(right one)
and another thing ,i notice the training process took 1.30min,is that normale??
