### ISSUE TITLE
cudaXXX() failed. Reason: driver shutting down

### ISSUE THREAD

**Issue by FXRer** [davisking/dlib#1886]
Hi,

I'm testing the CNN MMOD face detection of dlib. In my multithreaded application, I initialize the detector in the main thread like this :

`dlib::deserialize("data/mmod_human_face_detector.dat") >> mmodFaceDetector;`

Another thread is for the detection : 
`cv::Mat frameDlibMmodSmall;
cv::resize(threadFrame, frameDlibMmodSmall, cv::Size(inWidth, inHeight));`

// Convert OpenCV image format to Dlib's image format
dlib::cv_image<dlib::bgr_pixel> dlibIm(frameDlibMmodSmall);
dlib::matrix<dlib::rgb_pixel> dlibMatrix;
dlib::assign_image(dlibMatrix, dlibIm);

// Detect faces in the image
std::vector<dlib::mmod_rect> faceRects = mmodFaceDetector(dlibMatrix);

Therefore I define the **mmodFaceDetector** as a global variable : 
`using net_type = dlib::loss_mmod<dlib::con<1, 9, 9, 1, 1, rcon5<rcon5<rcon5<downsampler<dlib::input_rgb_image_pyramid<dlib::pyramid_down<6>>>>>>>>;
net_type mmodFaceDetector;`

But I get following error : 
`cudaStreamDestroy() failed. Reason: driver shutting down
cudaFree() failed. Reason: driver shutting down
cudaFreeHost() failed. Reason: driver shutting down`

I found related question here : https://sourceforge.net/p/dclib/discussion/442518/thread/ceeb484f/

It is said that static variable should avoid but in my case it is a global one. Is there any suggestion, please ?

Best regards,
Pascal

* **Version**: 19.18
* **Where did you get dlib**: github repo
* **Platform**: Ubuntu Linux x86-64, Nvidia GTX960M
* **Compiler**: gcc/g++ 7.4

**Comment by davisking** [comment]
Don't make the network a global variable.

**Comment by FXRer** [comment]
THanks Davis for your confirmation.
