### ISSUE TITLE
Compile-time warning in gcc & clang on Linux Mint

### ISSUE THREAD

**Issue by sjk7** [davisking/dlib#1888]
Using dlib in either gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) , or clang9 :
clang version 8.0.1-svn369350-1~exp1~20190820121219.79 (branches/release_80)

gives the following warning:
... /matrix/matrix_la.h:225:32: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
             y = abs(q(i)) + abs(e(i));
                             ~~~^~~~~~
/../matrix/matrix_la.h:163:20: note: within this loop
         for (i=0; i<n; i++)
                   ~^~

Thanks, looks like a nice library

**Comment by davisking** [comment]
Thanks for reporting this, but I'm not really sure what to do about it.  I
don't get this warning in gcc 7.4. There are also some related warnings I
get in gcc 7.4, but I'm pretty sure they are bogus and they go away in
newer versions of gcc.

**Comment by nonvoy** [comment]
ABCDEFGTVex wasGBy.nI'mkkbvcbgl
