### ISSUE TITLE
FYI - cblas.h incompatibility

### ISSUE THREAD

**Issue by CompSciPro** [davisking/dlib#1889]
Hey Folks - I know it was awhile back, but regarding https://github.com/davisking/dlib/issues/570 . . .

Full disclosure - I work at Intel supporting Intel Math Kernel Library.

I came across the above cblas.h issue. There was an incompatibility between netlib's cblas.h and MKL's mkl_cblas.h. This 570 issue sounds like the same thing. We recently changed it in MKL so that if you were using cblas.h from netlib, you can just switch to mkl_cblas.h now (as of MKL 2019 update 4, released in May 2019). This works except for one enum: CBLAS_ORDER - that one has to be handled manually.

Cheers and happy coding :)

**Comment by davisking** [comment]
Cool :)
