### ISSUE TITLE
Include Linux wheel files in PyPi

### ISSUE THREAD

**Issue by mbprodev** [davisking/dlib#1890]
Hello,

Could you include wheels for dlib-19.8.1(dlib-19.8.1-cp36-cp36m-linux_x86_64.whl)?

 I am using Python 3.6.8 . When I do `pip3 install dlib== I9.8.1` I get cmake configuration error. Below is a snippet of the error.
![image](https://user-images.githubusercontent.com/46756021/65924027-f37c2d80-e3b8-11e9-848c-6d847991b1e6.png)
I had already installed cmake with `pip3 install cmake`
It downloads the latest which is 3.15.3. The library doesn't seem to be compatible with cmake-3.15.3. 

So I tried to build it myself after installing(apt-get) libboost-all-dev, cmake and build-essentials on Ubuntu. Then, downloaded the dlib-19.8.1.tar.gz and ran `python3 setup.py bdist_wheel`, which created a dlib-19.8.1-cp36-cp36m-linux_x86_64.whl file.

However, dlib module created from this wheel when used in my program gives error
Exception: ImportError: libboost_python3-py36.so.1.65.1: cannot open shared object file: No such file or directory.
I believe this error is because I didn't compile it properly. Could you upload the whl file or give some guidance? 
Thanks

**Comment by davisking** [comment]
Why don't you use a newer version of dlib?

**Comment by mbprodev** [comment]
The newer version was not working with the packages I was working on, this was one version that worked.
