### ISSUE TITLE
Successfully installed dlib still dlib.DLIB_USE_CUDA returning false

### ISSUE THREAD

**Issue by shiva2410** [davisking/dlib#1892]
I am trying to use GPU for @ageitgey face recognition api 
I installed and compiled dlib successfully during installation of dlib I got
Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found suitable version "10.1", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done

BUT now when I am running
import dlib
print(dlib.DLIB_USE_CUDA)
in SPYDER I am getting FALSE
please help

##Expected Behavior
I expected (dlib.DLIB_USE_CUDA) to return TRUE
I expected CNN face detector model to run on GPU 

## Current Behavior
dlib.DLIB_USE_CUDA is returning false
CNN based face detector is taking whole CPU and RAM 
I also checked gpu usage by using nvidia-smi but it was not showing any usage
cuda.get_num_devices()   returns 1

## Steps to Reproduce
install dlib https://github.com/davisking/dlib
install cuda toolkit and other dependecies
Run this
https://github.com/davisking/dlib

 dlib version dlib==19.18.99
dlib: https://github.com/davisking/dlib
I am working on Windows 10 64 bit
I am using SPYDER

**Comment by 17isme** [comment]
so hard to install dlib....

**Comment by davisking** [comment]
**`dlib.DLIB_USE_CUDA` is a compile time constant**. Therefore, if you install dlib and it says `Enabling CUDA support for dlib. DLIB WILL USE CUDA` during install, but `dlib.DLIB_USE_CUDA` is `False` then this absolutely, 100% guaranteed, means you have installed two separate copies on dlib.  One built to use cuda and another not.  

This isn't because dlib is hard to install.  There is nothing I could possibly do to stop you from installing multiple copies of dlib and configuring them differently.

**Comment by davisking** [comment]
Maybe I need to emphasize that what is happening here is **_you have two copies of dlib installed in different python environments_** and you are getting confused about what python environment you are running your stuff in.

**Comment by shiva2410** [comment]
I got your point @davisking Thnx for helping
I wanted to ask that can we run dlibs hog face detectort on multiple cpu cores?
If yes can you please tell me how

**Comment by punitha-valli** [comment]
#2209 
import dlib.cuda as cuda
print(cuda.get_num_devices());
... 
1
print(cuda.get_device());
0
dlib.DLIB_USE_CUDA
False

still no wits shows that dlib.DLIB_USE_CUDA as False

Can any one tell me how to over come this ?

**Comment by eagle-dot** [comment]
I have similar issue



C:\dlib\dlib-19.21\dlib-19.21\python_examples>python
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import dlib
>>> print(dlib.cuda.get_num_devices())
1
>>> print(dlib.DLIB_USE_CUDA)
False
>>>

My dlib C++ library found cudnn , but the python dlib has a problem to link cudnn

**Comment by davisking** [comment]
That means it didn't build with cuda support.

**Comment by muslimkhudoyberdiyev** [comment]
> DLIB_USE_CUDA

I had the same problem. Later I found out that I had a dlib package in the conda and pip packages. I deleted dlib from the pip packet.

**Comment by nguyenhoan1988** [comment]
> #2209 import dlib.cuda as cuda print(cuda.get_num_devices()); ... 1 print(cuda.get_device()); 0 dlib.DLIB_USE_CUDA False
> 
> still no wits shows that dlib.DLIB_USE_CUDA as False
> 
> Can any one tell me how to over come this ?

maybe you can try to install it using `conda`:
https://gist.github.com/nguyenhoan1988/ed92d58054b985a1b45a521fcf8fa781

**Comment by kushpandey3009** [comment]
> I got your point @davisking Thnx for helping I wanted to ask that can we run dlibs hog face detectort on multiple cpu cores? If yes can you please tell me how

okay so what can we do about it ?
should i uninstall the pip dlib package and rebuild it with cuda ?
or something else.

**Comment by davisking** [comment]
About the HOG stuff not running on the GPU?  That code just doesn't run on
the GPU.  It's not written in CUDA.  So it just is what it is.

**Comment by kushpandey3009** [comment]
> > DLIB_USE_CUDA
> 
> I had the same problem. Later I found out that I had a dlib package in the conda and pip packages. I deleted dlib from the pip packet.

if i delete the pip package dlib then python is unable to find dlib

**Comment by kushpandey3009** [comment]
> #2209 import dlib.cuda as cuda print(cuda.get_num_devices()); ... 1 print(cuda.get_device()); 0 dlib.DLIB_USE_CUDA False
> 
> still no wits shows that dlib.DLIB_USE_CUDA as False
> 
> Can any one tell me how to over come this ?

same problem

**Comment by davisking** [comment]
Yeah if you delete dlib it will be deleted :)

The pip package isn't really any different from installing directly from the main github repo.  If `dlib.DLIB_USE_CUDA` is false then it means your system is missing the nvidia libraries needed to use cuda.  Anyway, if you do `pip install -v dlib` pip will not hide all the messages the install process is printing.  You should see some messages saying something about why your cuda or nvidia libraries are wrong or missing.

**Comment by kushpandey3009** [comment]
> Yeah if you delete dlib it will be deleted :)
> 
> The pip package isn't really any different from installing directly from the main github repo. If `dlib.DLIB_USE_CUDA` is false then it means your system is missing the nvidia libraries needed to use cuda. Anyway, if you do `pip install -v dlib` pip will not hide all the messages the install process is printing. You should see some messages saying something about why your cuda or nvidia libraries are wrong or missing.

i think i am doing everything right but still cant seem to have a true value from import dlib dlib.DLIB_USE_CUDA.
can u give 5 min of your time  and help me solve the issue.< https://meet.google.com/hih-srwx-udo >

**Comment by g7crservice-harshita-gupta** [comment]
can anyone help here, I am getting same error in the dlib usage for cuda device.

>>import dlib
>>print(dlib.DLIB_USE_CUDA)
False

**Comment by kushpandey3009** [comment]
> can anyone help here, I am getting same error in the dlib usage for cuda device.
> 
> > > import dlib
> > > print(dlib.DLIB_USE_CUDA)
> > > False

A little more information would be good in order to resolve the issue like System configuration etc.
most likely u must be using pip dlib package but need to build it from scratch also beware of the cuda and cudnn version + path in your environment variables

**Comment by g7crservice-harshita-gupta** [comment]
Thanks for your reply @kushpandey3009 , Yes I followed from scratch, 
I found the solution provided here and its working fine:
https://stackoverflow.com/questions/58261342/successfully-installed-dlib-still-dlib-dlib-use-cuda-returning-false
