### ISSUE TITLE
Improve Accuracy

### ISSUE THREAD

**Issue by tiago-alves** [davisking/dlib#1898]
I trained a model using the dnn_metric_learning_on_images_ex.cpp code . The only change I made was to increase the iteration without progress threshold to 10000.

I used a dataset with 63K identites that is a combination of VGG2, Asian Celeb and Clean Microsoft Dataset. I also did some manual cleaning. All identities have at least 80 images.

The result was not good. I downloaded the Face Scrub dataset and generated 5K random genuines pairs and 5K random distractors pairs. EER, FMR100 and FMR1000 were worse on this new model.

I don't know what went wrong since I was excepting a good improvement.

@davisking , do you have any advice on this?

**Comment by davisking** [comment]
You have to look at the outputs and see what is wrong.  Very likely your dataset is just bad, like the labels are not very accurate.  Run the model on held out data and look at the errors.  Look at pairs of images it gets wrong, and then look at a whole lot more.  The only way to find out what is wrong with your data is to look at the things the model is getting "wrong" according to the data.

**Comment by tiago-alves** [comment]
Thanks @davisking . I will do some more rounds of data cleaning. 
I will let you know once I have new results.

**Comment by tiago-alves** [comment]
@davisking , can you share the mini batch size you used and also the "iterations without progress threshold"? I performed some cleaning on the dataset using Amazon algorithm, but even after that, the results are far from being as good as with your original model.

Thanks

**Comment by davisking** [comment]
The http://dlib.net/dnn_face_recognition_ex.cpp.html example program has all these details.  See that for detailed notes.
