### ISSUE TITLE
getting coordinates of rectangle of train_object_detector

### ISSUE THREAD

**Issue by avisangray** [davisking/dlib#190]
How to get the coordinates of the bounding box made by train_object_detector?

**Comment by davisking** [comment]
This is discussed in the example http://dlib.net/train_object_detector.py.html

**Comment by avisangray** [comment]
but that's in python. i need it in c++

**Comment by davisking** [comment]
There are a whole bunch of C++ examples as well.  There is also an entire API reference that documents that class as well as all the others.
