### ISSUE TITLE
Cannot get labels of objects from simple_object_detector()

### ISSUE THREAD

**Issue by m0beenali** [davisking/dlib#1901]
I searched and read the documentation of dlib classes, but i couldn't find a way to get labels out of the detector when running test_simple_object_detector. (maybe i missed something)

I'm not using numpy arrays. I'm using XML dataset generated from ImgLab in dlib format. In that i have labeled.

**Current Results:**
When i run the test function, it gives me coordinates of matches found and i use those coordinates to create boxes around it. But there are no labels with the coordinates which i gave while annotating in ImgLab.

**Desired Result:**
I want to get the labels that i gave to the boxes in the ImgLab. i.e. to get labels from simple_object_detector() function.

Please help, i'm stuck here from two weeks
@davisking

**Comment by davisking** [comment]
This tool you are talking about isn't a multi-class detector.  It tells you
where the one kind of object you trained it to find is, and that's it.

**Comment by m0beenali** [comment]
Thanks, @davisking . Is there any other tool for such task in dlib?

**Comment by davisking** [comment]
You just train multiple detectors, one for each of the things you want to
find.
