### ISSUE TITLE
Is it possible to build with  static CRT (MSCV)?

### ISSUE THREAD

**Issue by dpar39** [davisking/dlib#1902]
Opencv defines '-DBUILD_WITH_STATIC_CRT=ON' which effectively allows me to compile OpenCV with no C runtime dependency in MSVC. Does dlib has a similar option? Can one be added?

**Comment by davisking** [comment]
Yes, you can set any build settings you like.  Use the cmake-gui tool to
add whatever build options you like to your build, or edit your cmake files
to set them there.  There is even a handy cmake script that already sets
them for you
in dlib/cmake_utils/tell_visual_studio_to_use_static_runtime.cmake.

**Comment by davisking** [comment]
You don't need to edit any dlib cmake files to do this.  Put this stuff in **your own cmake files**, or use `cmake-gui` to manually set the build options you want.

**Comment by davisking** [comment]
Or set `CMAKE_CXX_FLAGS` when you invoke cmake to set the build options you want.  There are many ways with cmake, none of them are dlib specific or require edits to dlib's files.

**Comment by dpar39** [comment]
I'm compiling and installing dlib as a third party library not with `add_subdirectory()`. Besides, CMAKE_CXX_FLAGS=/MT... won't work because last time I checked cmake appends whatever compiler configuration they have for that compiler at the end of your custom flags, in other words, /MD wins over /MT. That's why you'll find code like this everywhere in the web:

    foreach(FLAG_VAR CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG 
    CMAKE_CXX_FLAGS_RELEASE CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
        if(${FLAG_VAR} MATCHES "/MD")
            string(REGEX REPLACE "/MD" "/MT" ${FLAG_VAR} "${${FLAG_VAR}}")
        endif()
    endforeach()

Even using this new feature in cmake I couldn't get it to compile with /MT: https://cmake.org/cmake/help/v3.15/prop_tgt/MSVC_RUNTIME_LIBRARY.html
