### ISSUE TITLE
Question regarding overlapping objects detection

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#1907]
Lately I've been working on multi-class object detection using CNN + MMOD loss and I can get really good results with a relatively small amount of images.

However, after reading the tutorials and trying several settings, I was wondering if it s possible to find items that overlap completely or that is just impossible due to NMS.

Here's an example of what I would like to detect:
![image](https://user-images.githubusercontent.com/1671644/67775990-07dc4480-faa3-11e9-8d9c-27aa0a8c0e00.png)

How should I setup NMS and test_box_overlaps to make it work, if at all possible.
Also, does NMS work classwise? meaning that I might be able to detect the dress and a necklace, but not both of them?

Thanks in advance :)

**Comment by davisking** [comment]
Different classes are NMSed independently, so a box of class A doesn't do
anything with respect to a box for class B.

As for boxes within a single class, they can overlap completely so long as
they are boxes of different substantially different shapes.  You can set
the mmod_options::overlaps_nms class up however you like.  It has options
to control exactly what it means for boxes to overlap.  Only boxes that
overlap according to overlaps_nms are suppressed.  It sounds like the
default settings are probably ok for what you want to do.

**Comment by arrufat** [comment]
Thanks for the quick response, I will play with those settings to see if I can make it work.
