### ISSUE TITLE
where is set_background implemented?

### ISSUE THREAD

**Issue by crystal-butler** [davisking/dlib#1909]
I'm using a customized version of the face_alignment.py example and would like to be able to change the background color that gets set for areas inside the chip boundary that don't contain image pixels. As far as I can tell this happens when the set_background function runs, but I can't tell where the background color is being set. Is there a way to change the background color to be something other than 0?

**Comment by davisking** [comment]
There is no such option.  If you want to do something different you will
have to code up something specifically do that.

**Comment by crystal-butler** [comment]
Thanks for the clarification. Any pointers as to where the background color is currently being set, though? I thought there might be a default to use black in one of the functions but I haven't tracked down where.
