### ISSUE TITLE
The Dlib webcam_face_pose_ex.exe doesn't display camera feed

### ISSUE THREAD

**Issue by ramasamy-rudram** [davisking/dlib#191]
OpenCV running on my machine shows camera feed, but executing the webcam_face_pose_ex.exe shows only a blank screen.

**Comment by ramasamy-rudram** [comment]
![ss](https://cloud.githubusercontent.com/assets/21058867/17698320/1fbe8898-63d8-11e6-8567-c48e9bfc003f.jpg)

**Comment by ramasamy-rudram** [comment]
Can you please tell me why

**Comment by davisking** [comment]
That example uses OpenCV's VideoCapture tool.  I don't know why it doesn't work on your system.  I would ask the OpenCV people.
