### ISSUE TITLE
Can't build dlib, got error "use of undeclared identifier 'jpeg_mem_src'"

### ISSUE THREAD

**Issue by Brun0oO** [davisking/dlib#1910]
## Expected Behavior

"pip3 install dlib" should install the dlib package...

## Current Behavior

I got the error: 
use of undeclared identifier 'jpeg_mem_src'

Here the CMake output:
`ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-record-vdnc_yh2/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/
    Complete output (176 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
    Invoking CMake setup: 'cmake /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/build/lib.macosx-10.9-x86_64-3.7 -DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is AppleClang 10.0.0.10001145
    -- The CXX compiler identification is AppleClang 10.0.0.10001145
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 (found version "3.7.4")
    -- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.2.2
    -- Using CMake version: 3.15.4
    -- Compiling dlib version: 19.18.0
    -- SSE4 instructions can be executed by the host processor.
    -- AVX instructions can be executed by the host processor.
    -- Enabling AVX instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Found system copy of libpng: /usr/local/lib/libpng.dylib;/usr/lib/libz.dylib
    -- Found system copy of libjpeg: /usr/local/lib/libjpeg.dylib
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for module 'lapack'
    --   No package 'lapack' found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Found LAPACK library
    -- Found CBLAS library
    -- Looking for cblas_ddot
    -- Looking for cblas_ddot - found
    -- Looking for sgesv
    -- Looking for sgesv - found
    -- Looking for sgesv_
    -- Looking for sgesv_ - found
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
    -- DID NOT FIND CUDA
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- Building a C++11 test project to see if your compiler supports C++11
    -- C++11 activated.
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/build/temp.macosx-10.9-x86_64-3.7
    Invoking CMake build: 'cmake --build . --config Release -- -j2'
    Scanning dependencies of target dlib
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
    [  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
    [  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
    [  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
    [  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
    [  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
    [ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
    [ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
    [ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
    [ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
    [ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
    [ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/filtering/kalman_filter.cpp.o
    [ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/test_for_odr_violations.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/svm/auto.cpp.o
    [ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
    [ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
    [ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
    [ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
    [ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
    [ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
    [ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
    [ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
    [ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
    [ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
    [ 32%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
    [ 33%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
    [ 34%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
    [ 36%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
    [ 37%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
    [ 38%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
    [ 39%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
    [ 40%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
    [ 41%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
    [ 43%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
    [ 44%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
    [ 45%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
    [ 46%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
    [ 47%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
    [ 48%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
    [ 50%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
    [ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
    [ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/cpu_dlib.cpp.o
    [ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/tensor_tools.cpp.o
    [ 54%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
    [ 55%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/widgets.cpp.o
    [ 56%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/drawable.cpp.o
    [ 58%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.cpp.o
    [ 59%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/style.cpp.o
    [ 60%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/base_widgets.cpp.o
    [ 61%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.cpp.o
    [ 62%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.cpp.o
    In file included from /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/dlib/gui_core/gui_core_kernel_2.cpp:22:
    /usr/X11R6/include/X11/XKBlib.h:399:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
        register KeySym *           /* sym_return */,
        ^~~~~~~~~
    1 warning generated.
    [ 63%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
    [ 65%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
    [ 66%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
    [ 67%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
    /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/dlib/image_loader/jpeg_loader.cpp:141:37: error: use of undeclared identifier 'jpeg_mem_src'
            else if (imgbuffer != NULL) jpeg_mem_src(&cinfo, imgbuffer, imgbuffersize);
                                        ^
    1 error generated.
    make[2]: *** [dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [dlib_build/CMakeFiles/dlib.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py", line 135, in run
        self.build_extension(ext)
      File "/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py", line 175, in build_extension
        subprocess.check_call(cmake_build, cwd=build_folder)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-install-y2hfr2ky/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/d1/_q__ty7n4nq36m6mcg12wmv40000gn/T/pip-record-vdnc_yh2/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

## Steps to Reproduce

* **Version**: 
Well... as I use the pip command, should be the last one...
* **Where did you get dlib**: 
I think this is an official source as I use the pip command...
* **Platform**: 
macOS (High Sierra - 10.13.6) 64-bit

* **Compiler**: 
xCode version 10.1 (10B61)

**Comment by davisking** [comment]
Seems like your system copy of libjpeg is too old.  Try using the latest version of dlib in github, I just pushed a change that should handle this.

**Comment by Brun0oO** [comment]
Thank you, it works with the change you made !

**Comment by danigosa** [comment]
```
sudo apt-get install libjpeg-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libpng-dev
```

This solve the problem for me
