### ISSUE TITLE
train_shape_predictor get disorder of face landmarks

### ISSUE THREAD

**Issue by watsonwuh** [davisking/dlib#1915]
I try to train the shape predictor of Dlib by executing 'python_examples/train_shape_predictor.py' on [helen dataset](http://www.ifp.illinois.edu/~vuongle2/helen/) , and the 'training_with_face_landmarks.xml' as below:
`
<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>
<dataset>
<name>imglab dataset</name>
<comment>Created by imglab tool.</comment>
<images>
  <image file='100032540_1.jpg'>
	<box top = '410' left = '410' width = '744' height = '744'>
	  <box top = '410' left = '410' width = '744' height = '744'>
	  <part name='00' x='565' y='758'/>
	  <part name='01' x='564' y='781'/>
	  <part name='02' x='563' y='805'/>
	  <part name='03' x='566' y='829'/>
	  <part name='04' x='569' y='856'/>
	  <part name='05' x='572' y='879'/>
	  <part name='06' x='573' y='903'/>
	  <part name='07' x='575' y='927'/>
	  <part name='08' x='579' y='951'/>
	  <part name='09' x='584' y='976'/>
	  <part name='10' x='592' y='999'/>
	  <part name='11' x='604' y='1019'/>
...
`
use the predictor.dat to predict, find out the landmarks are out of order, for example, the face outline: 0,1,2,3,..,9,10,21,22...

also, I use load_image_dataset_metadata to print the items of image boxes, get the order
`
train/100032540_1.jpg
(u'00', point(565, 758))
(u'01', point(564, 781))
(u'02', point(563, 805))
(u'03', point(566, 829))
...
(u'09', point(584, 976))
(u'10', point(592, 999))
(u'100', point(878, 900))
(u'101', point(869, 897))
`

* **Version**: 19.17.1
* **Where did you get dlib**: dlib.net
* **Platform**: macOS
* **Compiler**:  python 2.7

**Comment by davisking** [comment]
The labels you associate with landmarks are just strings.  The points reported back to you are in reference to those strings sorted in **alphabetical order**.  Not in numerical order of the numbers you gave.

**Comment by watsonwuh** [comment]
The points from the landmarks are not continuous if number of points is more than 100, may not so convenient to use.
