### ISSUE TITLE
Working with multi GPU or GPU Cluster

### ISSUE THREAD

**Issue by EndErr** [davisking/dlib#1916]
I know that training can be done on multiple GPU, but how about production algorithms (not training ones) that use trained models? 
Are they designed to work with multiple GPU or to work in a GPU Cluster?
And the second question is, is dlib CUDA-aware MPI?

**Comment by davisking** [comment]
All the normal rules and APIs from cuda apply to running the dlib models.  You can run many at a time on multiple gpus or whatever you would like.  For instance, by calling cudaSetDevice() in the usual way.

**Comment by EndErr** [comment]
So the answer to my question would be that it all depends on how the program that implements the dlib algorithms is written.

**Comment by Cydral** [comment]
As explained by Davis, you can use the cudaSetDevice() function to address a particular card in your cluster more directly, but the distribution of the computation is managed at the program level. On the other hand, and for learning process, the distribution is directly supported by Dlib.
