### ISSUE TITLE
[question] MMOD detector fails to detect any object.

### ISSUE THREAD

**Issue by bhelal** [davisking/dlib#1917]
I have managed to train an MMOD detector based on the example for face detection for another object. I changed both of the window size and the chip dims to 60x155. 

The training progress went well, train and test loss went down to 0.001 and 0.02 within a few tens of thousands of steps. When it reaches the part where it shows training and testing results I get (1 0 0) for both. I also tried running the model manually on images with multiple scales but it always gives zero detections.

I suspect that my data is a bit troublesome as the objects I am trying to detect are mostly touching and covering a large portion of the image which might make it difficult for the cropper to generate negative samples. However, I think it still should be valid for training as I used the same data to train a HOG detector and it achieved 95% AP. Moreover, I have tested the DNN model with an image where there is only a single object in the middle and also did not get any result.

Any insight about the issue is highly appreciated. And by the way, I owe you many thanks for this quality library that has helped me and taught me a lot.

This is the console output after initialization (no warnings):
`num training images: 721
num testing images:  20
num detector windows: 3
detector window width by height: 60 x 157
detector window width by height: 97 x 155
detector window width by height: 60 x 228
overlap NMS IOU thresh:             0.213137
overlap NMS percent covered thresh: 0.305232`

**Comment by davisking** [comment]
Are you saying you set the `random_cropper` to produce crops tightly cropped around the objects?  Do not do that, that can not possibly lead to a working detector.  You must give images to the training code that look like the images you will use when you really run it.

**Comment by bhelal** [comment]
Thanks a lot for your reply.

I have used the random_cropper_ex to review the crops generated using my cropper settings. Surprisingly, almost all the crops are being marked as 'ignored'. This explains the zero detections I am getting.

I have two questions related to how the random_cropper works:
   1.  Is it ok if two or more objects are present within a single crop?
   2.  Is the random cropper also responsible for generating negatives, should I tune it to get images with no objects included?
