### ISSUE TITLE
[QUESTION] why find_min_global threading version need more iterations than the single thread

### ISSUE THREAD

**Issue by arewedancer** [davisking/dlib#1919]
I noticed from our project and even in the holder-table example that find_min_global/find_max_global multi-threading version needs more iterations to reach convergence than the single thread version, which defeats the purpose of parallelism. So I have to set max_function_calls much higher in the find_min_global(tp,...). 
 I'm wondering if my observation is right and why it's that. Thanks!  Please let me know if you want a concrete example.

**Comment by davisking** [comment]
It needs more iterations but takes less time. That’s the point. Samples are drawn from the function in parallel, so they are always going to be drawn without the benefit of knowing the results from other samples that have not finished executing yet. So it will always take more function calls in general.

**Comment by arewedancer** [comment]
Thanks! guess we have to find a sweet spot between max function calls and number of threads to beat the single thread version.
