### ISSUE TITLE
Dlib found different Cuda

### ISSUE THREAD

**Issue by ManafMukred** [davisking/dlib#1920]
I trying to make dlib use cuda ... so when I use **cmake ..**, dlib finds cuda **10.0** (my current version) .. So I get `-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA` 

![image](https://user-images.githubusercontent.com/40954961/68653603-0c0a6680-0567-11ea-9e80-64dfca019f58.png)

but when running the `Python3 setup.py install` the cuda found is **7.5** (which is different and I've already deleted)

![image](https://user-images.githubusercontent.com/40954961/68654413-d4042300-0568-11ea-9698-ca547a63d5f2.png)

when using cmake ... dlib looks for cuda in usr/local/cuda
but when doing the python setup file .. it goes to look for cuda in /usr directory !

Dlib version = 19.18
downloaded from https://github.com/davisking/dlib
Ubuntu 16.04  64-bit -->
using gcc 6.5

**Comment by JonnoFTW** [comment]
You need to specify where it will look for CUDA:

```
python setup.py install --set CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda  --set CMAKE_PREFIX_PATH=/usr/local/cuda/bin
```

**Comment by ManafMukred** [comment]
@JonnoFTW  thanks a lot, I appreciate it
