### ISSUE TITLE
How to get confidence score using cnn detection in batch of images?

### ISSUE THREAD

**Issue by congphase** [davisking/dlib#1921]
Hello everyone,

I'm trying to do detection using cnn for batch of images. Calling the function to do the detection with batch is okay, but it the result doesn't include confidence scores. I take a look at the api and found out that the dlib.mmod_rectangles class does not contain confidence attribute as the dlib.mmod_rectangle class. So how to get the confidence score for each detection if I have to do detections on batches only rather than single images. Sorry for my noob question, but I'm new to dlib, and really need help.

Thank you a lot!!!

**Comment by davisking** [comment]
`dlib.mmod_rectangles` is just a list of `dlib.mmod_rectangle`

**Comment by congphase** [comment]
Thank you, I figured it out. 

Closing the issue now.
