### ISSUE TITLE
Big distance between face descriptors from the same face photo

### ISSUE THREAD

**Issue by don-prog** [davisking/dlib#1922]
I tried a couple of times to get an answer to this question, but unfortunately it is still unanswered. So, I don’t know what to do except try to ask it again. All details and steps to reproduce you can find here: https://github.com/davisking/dlib/issues/1904
I want to remind the last update of this issue.

I get a really big Euclidean distance between some identical face photos which processed on the different computers, but some face photos have correct results(distance `~0.0`) on the different computers.

**1.** I get a difference `0.13` when using this photo: https://drive.google.com/file/d/1QGqnm9fFZSFUqCF9sNMnD329V5nIr3mp/view?usp=sharing

Computer 1 face descriptors: https://drive.google.com/file/d/18bXQj3U7rLR9BkMwk0wJL2Q8ICmDuVwm/view?usp=sharing
Computer 2 face descriptors: https://drive.google.com/file/d/1W_bnBiWJuzcCiXQPWHsLAsSxPgjEVBsO/view?usp=sharing

But I get identical results(difference `0.0`) when using this photo: https://drive.google.com/file/d/1QhVWc42oY1HzN_PUlar8UGG59F-F4cfJ/view?usp=sharing
Computer 1 face descriptors: https://drive.google.com/file/d/1cyI-nYqOqk0_YI3sBzYeXVMBFXJcxl_W/view?usp=sharing
Computer 2 face descriptors: https://drive.google.com/file/d/13JhqYHr6Z5Ltx4vCydsUubaUwGojiEPV/view?usp=sharing

**2.**  I also installed a virtual machine with Ubuntu 16.04 on my computer 1(Ubuntu 18.04). I tried different configurations: with compiler 5.4 and 7.4, without Lapack and with, etc. Any differences were within `0.000002`. It's also strange that this virtual machine gives results that are closer to computer 1(difference is `0.000002`) than to computer 2(difference is `0.13`). So, I think this is not because of the Lapack or compiler versions.

Why I get such a big difference when use first photo and how can I fix it?

**Comment by davisking** [comment]
I don't think this is a dlib issue.  As I said before, using different compiler settings and different CUDA runtimes and cuDNN versions will in general result in different outputs.  It just is what it is and I don't have any control over the runtime variation in NVIDIA code or hardware.

**Comment by don-prog** [comment]
@davisking ok, I just wanted to be sure that you knew about the big difference in descriptors, and not only about the small error.
And, as I understand, the problem is also not in my code [from the first post](https://github.com/davisking/dlib/issues/1904#issue-510453568), correct?

**Comment by davisking** [comment]
I just noticed you have this in your code:
```
    std::vector<matrix<float,0,1>> face_descriptors = net(faces);

    for (int i = 0; i < 128; ++i) {
        cout << face_descriptors[0](0, i) << endl;
    }
```
That loop is looping `i` over the **columns**, but the descriptor is declared to be a row vector.  That is technically illegal, but in this case will end up returning the correct values.  But you still shouldn't do that.  

Nevertheless, I don't see anything in the code you have posted that would cause this.  But maybe you have other array indexing errors that are messing up your program that you didn't post.  I can't say.

**Comment by don-prog** [comment]
@davisking sorry for the delay. So, it is better to use `face_descriptors[0](i)`, right?

**Comment by davisking** [comment]
yes
