### ISSUE TITLE
Tensor Cores Boosting

### ISSUE THREAD

**Issue by EscVM** [davisking/dlib#1927]
Hi! 

I'm currently using DLIB on a platform with Volta GPU microarchitecture. Volta and Turing GPUs feature Tensor Cores that can greatly speed up inference and training.

I was wondering if DLIB can make use of this hw accelerator. Thanks

**Comment by davisking** [comment]
Dlib just forwards this stuff to cuDNN, so if you use the latest version of cuDNN then you get all these benefits.
