### ISSUE TITLE
Is it possible to deploy new model without rebuilding dlib.

### ISSUE THREAD

**Issue by newforrestgump001** [davisking/dlib#1931]
If I modify the network structure,mmod for example, I must rebuild the library.
Is it possible to do that without rebuilding, like caffe(.prototxt and .caffemodel) or darknet(.cfg ang .weights) or tensorflow(.pb only).
Thanks a lot!

**Comment by davisking** [comment]
No

**Comment by newforrestgump001** [comment]
@davisking I got it, thanks for your information.
