### ISSUE TITLE
Slow face detector

### ISSUE THREAD

**Issue by Yosifz8** [davisking/dlib#1932]
Hi!

I'm tried one of the `python_examples`: `face_detector.py`.

But i try to increase the` number_of_times_to_upsample` to 3:

`detector(img, 3)`

With this code change every photo take more than 8 seconds. The photo size is 1280X720 and i don't want to resize the photos.

i installed dlib with : `pip install dlib`

and also tried with: `python setup.py install` and all the instructions that defined in the main page:  https://github.com/davisking/dlib

I'm running the code on:
Intel Core i7-8750H 2.2GHz

Any suggestions how i can decrease running time? I don't want to rezise the photo because the camera is locate in big space and need to cover big space.

Thanks!

**Comment by davisking** [comment]
You are upsizing a large image by a large amount. It's going to be slow.
