### ISSUE TITLE
How to use auto_train_rbf_classifier?

### ISSUE THREAD

**Issue by EndErr** [davisking/dlib#1933]
Working on a SVM training found auto_train_rbf_classifier but can't figure out how to use it.
Used examples` svm_c_ex.cpp` and `svm_ex.cpp`. Is it the same as `learned_function`?
Could you please give a example of usage?

**Comment by davisking** [comment]
Did you look at the docs http://dlib.net/dlib/svm/auto_abstract.h.html#auto_train_rbf_classifier?  It shows what it returns.

**Comment by EndErr** [comment]
I did, that was the place where I found it.
When looking at `svm_c_ex.cpp` there is `learned_function` that looks like `auto_train_rbf_classifier` in declaration. In the example the `learned_function` has `normalizer` and `function` "methods" and is used only in testing.
`...
funct_type learned_function;
learned_function.normalizer = normalizer;  // save normalization information
learned_function.function = trainer.train(samples, labels); // perform the actual SVM training and save the results
...
cout << "This is a +1 class example, the classifier output is " << learned_function(sample) << endl;
...`
Where the trainer is the one who takes C and Gamma/nu parameters.

`auto_train_rbf_classifier` should replace the code of C and Gamma/nu determination but don't know how to do that, because the trainer needs C and Gamma/nu to pass it to learned function.

Could you be so kind and direct me to do that, or maybe a simple example of usage?

**Comment by davisking** [comment]
I don't understand what you are asking about.  What is in `svm_c_ex.cpp` has nothing to do with `auto_train_rbf_classifier`.  Don't look at `svm_c_ex.cpp`

**Comment by EndErr** [comment]
I'm asking some help to understand how to use that function. A example would be very nice.

**Comment by davisking** [comment]
```
auto learned_function = auto_train_rbf_classifier(samples, labels, std::chrono::seconds(5));
```
That's all you do.

**Comment by EndErr** [comment]
Thank you very much, thats what I needed.
