### ISSUE TITLE
How to create a .dat markers file?

### ISSUE THREAD

**Issue by cogitas3d** [davisking/dlib#1934]
Hey there!

I'm developing a photogrammetry system to isolate skulls and scanning it.

I read the documentation and get to select a database of pictures of skull and I created a detector.svm file.

But now, I would like to isolate the skull border with: or a square or a .dat markers points, more or less like this result (but with a skull):

![Captura de tela de 2019-11-25 11-23-04](https://user-images.githubusercontent.com/2422483/69743597-10ad4e00-1115-11ea-824f-b1ff88af652c.png)

Unfortunatelly I did not found a documentation about it. I'm not a expert programmer.

Thanks for the attention!

**Comment by davisking** [comment]
There is a lot of documentation about how to use the dlib tools.  See
http://dlib.net/imaging.html#shape_predictor in particular.

**Comment by cogitas3d** [comment]
Thank you very much!
