### ISSUE TITLE
compile time assertion failure in matrix_utilities.h on VS2015

### ISSUE THREAD

**Issue by grisevg** [davisking/dlib#194]
This assertion fails when I try to compile project using dlib 19.1 with Visual Studio 2015 x64 on Windows 10 - `COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);`
Here's the exact error:
```
...\lib\dlib\matrix\matrix_utilities.h(2665): error C2131: expression did not evaluate to a constant
...\lib\dlib\matrix\matrix_utilities.h(2665): note: failure was caused by call of undefined function or one not declared 'constexpr'
...\lib\dlib\matrix\matrix_utilities.h(2665): note: see usage of 'dlib::relational_operators::operator >'
```

**Comment by davisking** [comment]
Yeah, this just started happening when someone uses dlib/all/source.cpp.  Try the latest code in github.

**Comment by grisevg** [comment]
Cheers, latest code compiles just fine!

**Comment by davisking** [comment]
Super :)
