### ISSUE TITLE
Dlib model predicts face landmarks(LM) in different order compared to trained order.

### ISSUE THREAD

**Issue by vasanthhr** [davisking/dlib#1941]
Hello,

we trained Dlib model with less number of landmarks, and we verified the order of trained landmarks in XML file before training a model.

But trained model predicted landmarks(LM) in different orders compared with trained LM order. Please help me to resolve this issue.

Please find attached screenshot shows the predicted LMs from our trained model.
(FYI: 0,1 are printed one side of face. And 2,3,4 are printed other side of face).

![untitled](https://user-images.githubusercontent.com/20619142/70561107-dce01880-1b57-11ea-97b0-a2023d4e61c8.png)

**Comment by davisking** [comment]
Per the documentation, the landmarks are sorted in lexicographical order.  Not the order they are listed in an xml file, or any other order. Only and always lexicographical.
