### ISSUE TITLE
Dlib is useless when dealing with millions of faces

### ISSUE THREAD

**Issue by davidrasmussen** [davisking/dlib#1944]
I have a database of 30 million faces (from 80px to 500px). When I do a search, comparing the euclidean distance from each face from database to the desired face, I get a result consisting of thousands of dissimilar faces having a euclidean distance < 0.6. 
I tested this with CPU and GPU and got the same results on each of them (I used shape_predictor_68_face_landmarks and dlib_face_recognition_resnet_model_v1).

Absolutely different faces can have the distance = 0.48. Each search result contains an average of 0.05% of the entire database, and the right faces aren't the closest to the desired face so I can't pick K nearest of them. 
Learning on such a large dataset seems impossible.

Davis, have you tested dlib on a large database? What could you advise?

**Comment by davisking** [comment]
This is what you should expect.  The accuracy of comparing two faces with the 0.6 threshold should give the right answer about 99.38% of the time.  Which means it will be wrong 0.42% of the time.  So you 0.05% is better than I would expect.  You need to layer something else on top of this, like do a k-nearest-neighbors or linear SVM classifier.  Or even better, if you have 30 million faces train a model that's better than the example one in dlib.  Really, dlib is about machine learning, not prepackaged models.  The one in that example program is just there to make the example documentation more fun, even though it does work well as a baseline.

**Comment by davidrasmussen** [comment]
Thank you for your reply, Davis. But 0.05% is not the accuracy. This is the percentage of the entire database that the search will return. For example, I have a database of 30 million faces, and every time I search for a face, I will get a result of about 15000 faces with the distance < 0.6. In this case, the accuracy is much lower than 99.38%

**Comment by davisking** [comment]
No, if you compare two faces, the test will be correct 99.38% of the time.  If you do that comparison 30 million times only about 99.38% of them will be correct, which means many will still be wrong.

**Comment by matiasdelellis** [comment]
Hi both,
First time that comment here, so first of all thank you @davisking  for all the development. :smiley: 

I had a similar problem with the Nextcloud application we are working on. A detail that is very poorly documented, and helped us a lot is confidence. 
I do not know the database that Davis used to train, but in our real tests, we find that the blured faces or simply profile faces are the ones that produced the greatest error. You can barely assimilate the confidence with these parameters, and any face with confidence <1 should not compare. In our case it gave good results.

**Comment by davidrasmussen** [comment]
@matiasdelellis you got good results using dlib_face_recognition_resnet_model_v1 or using our own model?

**Comment by matiasdelellis** [comment]
Hi,
dlib_face_recognition_resnet_model_v1, but the clustering is different .. 
Neither better. but we currently use Chinese Whispers for clustering, and with a theshold of 0.5 or 0.4. This gave us good results for our requirements, but there were always mixed groups. When we consider confidence we obtained much better results.

Only highlighted the need to consider that value, but neither check with millions faces, but I can assure you that in real cases you will improve the results. :wink: 

On the other hand, remember that the results depend on the training and validation data. This model had problems with Asian people for example. :disappointed:

**Comment by HAKANMAZI** [comment]
> Thank you for your reply, Davis. But 0.05% is not the accuracy. This is the percentage of the entire database that the search will return. For example, I have a database of 30 million faces, and every time I search for a face, I will get a result of about 15000 dissimilar faces with the distance < 0.6. In this case, the accuracy is much lower than 99.38%

After the 15000 results, maybe you can 90% or more similarity restricting, hereby your results can  less than 15k
