### ISSUE TITLE
I can Forbid  cmake  found BLAS ？because of  I have CUDA

### ISSUE THREAD

**Issue by Micla-SHL** [davisking/dlib#1945]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by Micla-SHL** [comment]
I  try  training dlib code ，it  will long long time。  I  have  2  linux  ，They are different ：cmake found BLAS  is  different ，I can  disable cmake found BLAS?  because of   I have  CUDA 。I want them to have the same speed  when  they  training

**Comment by davisking** [comment]
The DLIB_USE_BLAS and DLIB_USE_LAPACK cmake options can bet set to off to
disable this.

**Comment by Micla-SHL** [comment]
> 可以将DLIB_USE_BLAS和DLIB_USE_LAPACK cmake选项设置为off以禁用此功能。

        Thanks，I'm very lucky。today, I try  training dlib‘s  model（BLAS is not disabled），（2.6 million data）。Learning rate：0.1
5 minutes  = 1000 steps。 so，10000 steps just  1 h，This is too fast（use NVIDIA P100）.Unfortunately，I have 1070 ，it will 2 week（Learning rate：0.01），This makes me give up on it。  
        At last, I I want to know about AMD GPU Can support dlib？？

**Comment by davisking** [comment]
Only NVIDIA GPUs are supported.

**Comment by Micla-SHL** [comment]
Thank you，but a little sorry

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Davis E. King<mailto:notifications@github.com>
发送时间: 2019年12月18日 8:24
收件人: davisking/dlib<mailto:dlib@noreply.github.com>
抄送: Micla-SHL<mailto:shl_j@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [davisking/dlib] I can Forbid cmake found BLAS ？because of I have CUDA (#1945)


Only NVIDIA GPUs are supported.

―
