### ISSUE TITLE
RegularExpression::compile():Nested *?+. RegularExpression::compile():Error in compile.

### ISSUE THREAD

**Issue by SwjtuLyp** [davisking/dlib#1948]
hello.I have met a problem.when I use the"make install" to install the dlib on Ubuntu,it occured an error.it is about:
RegularExpression::compile():Nested *?+.
RegularExpression::compile():Error in compile.
cmake_install.cmake:42(include)

why?what happened?Is there anyone can help me to sovle this problem.

**Comment by felipelucca** [comment]
Same problem.
OS: Fedora 31 amd64 (cuda 10.2)

```
[100%] Built target dlib
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib64/libdlib.a
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at dlib/cmake_install.cmake:45 (file):
  file could not compile REGEX
  "/home/felipedelucca/Development/C++/Repositories/dlib/build/dlib".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
```

**Comment by SwjtuLyp** [comment]
hello,maybe you should try to update the CMake gcc,g++,then do this again.
you should do as this page:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

**Comment by SwjtuLyp** [comment]
> Same problem.
> OS: Fedora 31 amd64 (cuda 10.2)
> dlib v19.19
> 
> ```
> [100%] Built target dlib
> Install the project...
> -- Install configuration: "Release"
> -- Up-to-date: /usr/local/lib64/libdlib.a
> RegularExpression::compile(): Nested *?+.
> RegularExpression::compile(): Error in compile.
> CMake Error at dlib/cmake_install.cmake:45 (file):
>   file could not compile REGEX
>   "/home/felipedelucca/Development/C++/Repositories/dlib/build/dlib".
> Call Stack (most recent call first):
>   cmake_install.cmake:42 (include)
> ```
hello,maybe you should try to update the CMake gcc,g++,then do this again.
you should do as this page:
https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

**Comment by felipelucca** [comment]
> > Same problem.
> > OS: Fedora 31 amd64 (cuda 10.2)
> > dlib v19.19
> > ```
> > [100%] Built target dlib
> > Install the project...
> > -- Install configuration: "Release"
> > -- Up-to-date: /usr/local/lib64/libdlib.a
> > RegularExpression::compile(): Nested *?+.
> > RegularExpression::compile(): Error in compile.
> > CMake Error at dlib/cmake_install.cmake:45 (file):
> >   file could not compile REGEX
> >   "/home/felipedelucca/Development/C++/Repositories/dlib/build/dlib".
> > Call Stack (most recent call first):
> >   cmake_install.cmake:42 (include)
> > ```
> 
> hello,maybe you should try to update the CMake gcc,g++,then do this again.
> you should do as this page:
> https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation

Hello,
I'm going to give a try on a VM, but I managed to manually install dlib using:
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH}
mkdir build && cd build
cmake -DUSE_AVX_INSTRUCTIONS=ON ..
cmake --build . --config Release -- -j8
sudo cp ./dlib/dlib-1.pc /usr/local/lib/pkgconfig/
sudo cp ./dlib/libdlib.a /usr/local/lib64/
sudo cp -r ./../dlib/ /usr/local/include/
sudo ldconfig
```

It's working for me now.
