### ISSUE TITLE
Can't compile... problems with cblas

### ISSUE THREAD

**Issue by DisgruntledBadger** [davisking/dlib#195]
Hello,
I've used cmake&make to build dlib globally but when i try to compile my project I get a bunch of undefined references to cblas_something(daxpy, dscal, dgemm, dgemv, dger... etc)

Now, the think is, cmake did warn me it couldn't find cblas and lapack (although I've installed literally every package that contained the words cblas and lapack from the open SUSE repo). However It also mentioned its using something equivalent from openBLAS so I thought that everything might just work out in the end.

Apparently no...
So how do i make dlib aware of me having cblas ? whereis cblas does give me the location of a cblas header and the devel/src packages for cblas are installed on my machine. However the cmake inside dlib is literally ~10 pages long and I simply don't have the experience and will to look through it, especially since it doesn't seem to be the only one.

Any help would be appreciated.

**Comment by davisking** [comment]
If you aren't using cmake to compile your project then you will have to
tell the compiler to link against your blas library.  With gcc you have to
give an option like -l openblas.

**Comment by DisgruntledBadger** [comment]
Oh, tank you, I did try tetting

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lcblas")

since I foolishly assumed dlib already does the linking with the libraries it found, however when I set it to
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -lopenblas") it worked like a charm
