### ISSUE TITLE
fetchcontent instructions might require an update

### ISSUE THREAD

**Issue by kotoroshinoto** [davisking/dlib#1952]
I am attempting to follow the setup instructions that say to use lines such as the following: 
FetchContent_Declare(
        dlib
        GIT_REPOSITORY https://github.com/davisking/dlib.git
        GIT_TAG        v19.18
)
FetchContent_MakeAvailable(dlib)

however, when I attempt to compile the project, I receive a message stating that I should not put the dlib folder in the include path, which presumably cmake is doing automatically as a result of these commands. What can be done to avoid this?

**Comment by kotoroshinoto** [comment]
ah, I was toying around with including visible headers, and it turns out the iostream header was a strategically placed error-catcher rather than an actual feature-providing header.

Perhaps that should be made more obvious.

**Comment by davisking** [comment]
How could it be made more obvious?
