### ISSUE TITLE
Does dlib python support win server 2003?

### ISSUE THREAD

**Issue by gclsoft** [davisking/dlib#1953]
I tried python2.7 and python3.4 and python3.4.4, all not work at installing dlib.

**Comment by davisking** [comment]
It should work fine on any platform that has a working C++11 compiler.

**Comment by gclsoft** [comment]
but vs2015 cannot installed on winserver2003 which supports c++11, how to solve it?


------------------ Original ------------------

**Comment by davisking** [comment]
Then I guess it can't be done.
