### ISSUE TITLE
compile error: cannot convert from 'const cv::Mat' to 'IplImage'  with dlib 19.19 and OpenCV 4.2.0

### ISSUE THREAD

**Issue by leonyu1010** [davisking/dlib#1955]
## Expected Behavior
trying to use dlib with OpenCV 4.2.0

## Current Behavior
compile error: 
dlib\opencv\cv_image.h(37,1): error C2440: 'initializing': cannot convert from 'const cv::Mat' to 'IplImage'

additional info
1.
https://github.com/opencv/opencv/wiki/ChangeLog#version420
Breaking changes:  Disabled constructors for legacy C API structures.

2.  https://github.com/opencv/opencv/issues/16149

## Steps to Reproduce
compile dlib against OpenCV 4.2.0

* **Version**: 19.19
* **Where did you get dlib**: dlib.net
* **Platform**: windows 10 64bit
* **Compiler**: visual studio 16.4.2

**Comment by davisking** [comment]
Try latest dlib on github.

**Comment by leonyu1010** [comment]
thank you for the help. I should have spotted the commits on master  myself.   It compiles now. thank you

**Comment by hegee** [comment]
soorry to bother you,but I meet the same problem with you,and I just start to study dlib,can you tell me how you solve the problem in detail?
I use also opencv4.2.0 and dlib 19.19

**Comment by hegee** [comment]
sorry to bother you,but I meet the same probelm.can you tell me how you solve it? I'd appreciate it.

**Comment by leonyu1010** [comment]
code change https://github.com/davisking/dlib/commit/131e4598093fea6d8469e7687ac31ef60571f336

and

https://github.com/davisking/dlib/commit/34dc7303045877226ebdd6cd07ce6384c0881eb8

**Comment by hegee** [comment]
THANK you very much!
