### ISSUE TITLE
Lighting issue on Landmark(LM) prediction, Landmark coming inside whenever light intensity is more on face.

### ISSUE THREAD

**Issue by vasanthhr** [davisking/dlib#1956]
We trained DLIB model with 26k to 30K face images. All are colored images.

And we used configuration as below while training:

cascade_dept = 10
tree_depth = 3
feature_pool_size = 400
num_test_splits = 20
oversampling_amount = 20
nu = 0.1
num_trees_per_cascade_level=250

**But landmark prediction will be coming inside the face whenever brightness is more on face.**

**I have attached a tested result here, pls check the same.**

![](https://lh3.googleusercontent.com/-uKij-vd6Wng/XgRp6K4_hXI/AAAAAAAAAxI/yK8XE_VtI506WXyJyui4X-kQg0GjFK_vQCK8BGAsYHg/s0/2019-12-26.jpg)

**Comment by davisking** [comment]
Maybe you need more trees that are deeper.  Try the default parameters. You
also need to use training data that looks like your testing data.  If you
training data never has these bright types of images that is bad.

**Comment by vasanthhr** [comment]
@davisking , thanks for your reply.

We will try including datasets which are of brightness as used for testing the model.

As you mentioned above **"Maybe you need more trees that are deeper", does it mean we need to have more tree_depth or more num_trees_per_cascade_level ?**

**Comment by davisking** [comment]
Both
