### ISSUE TITLE
where is the CBLAS_H ifndef check ?

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1959]
Hi,

to prevent conflict between openblas & dlib . matrix_blas_bindinngs.h there was a guard like : 

`#ifndef C_BLAS_H
`

but latest dlib matrix_blas_bindinngs.h file has not this guard . there is only . 👍 
`#ifdef DLIB_DEFINE_CBLAS_API
`

so it s conflicting again, so I put previous guard there again.

any other way to solve this ?

**Comment by davisking** [comment]
That logic was consolidated into the DLIB_DEFINE_CBLAS_API macro.  So it's
still there. Look at dlib/matrix/cblas_constants.h
