### ISSUE TITLE
Training a Face_Detector

### ISSUE THREAD

**Issue by praveenlovely** [davisking/dlib#196]
Hi Sir,

I am trying to train a detector. I selected close to 100 images for training. I am using the Python environment. As per your advise, I used the Imglab tool to draw the bounding boxes across the images. 
And then placed the generated xml file into my location and called the detector program. Here are my doubts and questions.

1. What should I use as the testing xml file while running the program?
2. I ran without assigning any testing xml in place. However, I get the following.
Training with C: 5
Training with epsilon: 0.01
Training using 8 threads.
Training with sliding window 81 pixels wide by 79 pixels tall.
Training on both left and right flipped versions of images.
Killed

What does 'killed' mean by the way?

3. What should I do now? PLease guide!

**Comment by davisking** [comment]
github issues are for bugs or problems in dlib.

http://dlib.net/faq.html#Itdoesn'twork
