### ISSUE TITLE
[Question] Dlib with scikit-learn for hyper-parameter tuning

### ISSUE THREAD

**Issue by vivekpayasi** [davisking/dlib#1961]
I want to implement hyper-parameter tuning using dlib for tree-based algorithms in scikit-learn like GBM or XGBoost.

I went through the documentation and examples of dlib for python. I couldn't really find any tutorials on the web as well.

Is it possible to utilize the dlib optimizer to this purpose? If it is, can someone point me in the right direction?

**Comment by davisking** [comment]
I would use this: http://dlib.net/global_optimization.py.html

**Comment by vivekpayasi** [comment]
Oh shoot! I read that article of yours and the code as well, but somehow overlooked.

Thanks a lot.
