### ISSUE TITLE
face chip without alignment

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1962]
Hi, 

I am extracting face chips with : 

```

                full_object_detection shape = shape_model(img, detected_faces[i]);

                extract_image_chip(img , get_face_chip_details(shape , 150,0.95) , face_chip);
                extract_image_chip(img , get_face_chip_details(shape , 300,0.25) , big_face_chip);
```

and its gives aligned faces.

Is there a short cut to get face chip without aligned and bigger size as in : 

`               extract_image_chip(img , get_face_chip_details(shape , 300,0.25) , big_face_chip);`

**Comment by davisking** [comment]
You can give extract_image_chip just plain rectangles.
