### ISSUE TITLE
Suggestion on `test_shape_predictor`

### ISSUE THREAD

**Issue by pauloamed** [davisking/dlib#1968]
I'm new on github and don't know if this is the best way to add a suggestion, but 

it would be nice to have an optional argument indicating on which points the error should be computed for this tester. 

The motivation for this is that one can train his/her model for just some of the points, but can't compare (as far as I know) two different models trained on two different sets of points (even if one is subset of another)

**Comment by davisking** [comment]
`test_shape_predictor` is a really simple method.  I don't want to complicate it's API.  If you want to compute some other metrics you are better of writing a method specifically to compute that metric.

**Comment by pauloamed** [comment]
Got it. Thanks!
