### ISSUE TITLE
dnn_instance_segmentation_ex.cpp compilation never finishes

### ISSUE THREAD

**Issue by babylon73** [davisking/dlib#1969]
## Expected Behavior
Truing to build the examples (see steps to reproduce). Expeting this process to be finished eventually, however, it's stuck on dnn_instance_segmentation_ex.cpp compilation.

## Current Behavior
dnn_instance_segmentation_ex.cpp compilation never finishes

## Steps to Reproduce
Just trying to build the examples:
cd dlib\examples
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ..
cmake --build . --config Release

* **Version**: 19.19
* **Where did you get dlib**: dlib.net
* **Platform**: Win10 x64 10.0.17763
* **Compiler**: MSVC 19.0.24215.1 (VS2015 Update 3)

**Comment by babylon73** [comment]
Follow-up: just killed the cl.exe process so the CMake could move on.

dnn_instance_segmentation_train_ex.cpp also can't be compiled with same sympthoms (compilation just never ends). It seems like cl.exe "fails" to do something at the very beginning: amount of memory allocated by the cl.exe process never changes, number of threads in cl.exe never changes, cl.exe just loads one CPU core infinitely.

Same sympthoms for dnn_semantic_segmentation_ex.cpp, dnn_semantic_segmentation_train_ex.cpp.

**Comment by davisking** [comment]
You need to use a newer version of visual studio.  That version doesn't
have very good C++11 support, as you are discovering.

**Comment by babylon73** [comment]
Have those segmentation examples ever been successfully compiled with VS? Don't have newer version at hand... may be some optimization settings (disabling some of them) can fix this.

**Comment by davisking** [comment]
Yeah, @reunanen runs them and others like them in visual studio all the time.

**Comment by babylon73** [comment]
I mean with VS2015... have anybody run them properly with VS2015? Just can't switch to something else at the moment, I have to support CUDA 8.0 (which is the last CUDA that supports Fermi), MS2015 is the last VS that supports CUDA 8.0.

**Comment by reunanen** [comment]
Ok, that may be a difficult requirement to live with.

How long did you actually wait? Previously I had to wait basically overnight, or at least several hours, to compile complex networks. Then MS optimized something, and now life is much better. But I'm not really sure if my "previously" was VS 2015, or just an older version of VS 2017. (I think I did use dlib's dnns with VS 2015, too, but certainly not instance segmentation.)

Having to wait for the compiler for hours isn't great of course, but [compilation firewalls](http://www.gotw.ca/gotw/024.htm) help a lot. And compared to training, the time required to compile may still be relatively short.

Finally, you may be able to compile by simplifying the network a little. Just remove some of the intermediate layers. The results will be different, of course, but it may still work very well; depending on your problem, maybe even better. This is something I often do (for various reasons, including runtime speed, compilation speed, regularization, etc); see e.g. [here](https://github.com/reunanen/dlib-dnn-pimpl-wrapper/blob/b99f2dccd32be5da990be05583d5d52e1d588e6a/NetStructure.h#L147-L206) for an example.

**Comment by babylon73** [comment]
The longest try was about for hours... well, at least I know compiler did not just hang, it was doing it's best :-)

Could you please elaborate on compilation firewalls sultion? Not getting how pointer-to-implementation could make this solved.

May thanks for the hint how to deal with it (layers tweaking), gonna give it a try.

**Comment by reunanen** [comment]
> Could you please elaborate on compilation firewalls solution? Not getting how pointer-to-implementation could make this solved.

It will not solve the problem that compiling takes a long time. But it may help compiling your _other_ code faster. I mean: let's say you have an application that consists of different modules, e.g. user interface, data storage, maybe camera access, possibly integrations with external systems, ... you get the point. In such a case, in order to compile a user interface change for example, the compilation firewall lets you do that quickly. So that only when you actually change the underlying NN structure, you need the long recompile.

But if you can't compile the NN code even once, then this doesn't help of course.

**Comment by reunanen** [comment]
> The longest try was about four hours... well, at least I know compiler did not just hang, it was doing it's best :-)

Well, it may have actually hanged. In some cases it did finally finish for me, in others not (and impossible to say if it would have finally completed, had I waited 2 minutes longer). And as said, I certainly didn't compile instance segmentation in MSVC 2015.

**Comment by davisking** [comment]
As an aside, gcc and clang compile these files in a few seconds.  So this
is really just a bug in visual studio.

**Comment by babylon73** [comment]
What visual studio version do you guys suggest? VS2019 is just pre-released... I guess it leaves VS2017 only?

**Comment by reunanen** [comment]
@babylon73 I'm currently using VS2017 for pretty much all my Windows work. Haven't looked at VS2019 yet.

**Comment by reunanen** [comment]
> As an aside, gcc and clang compile these files in a few seconds.  So this is really just a bug in visual studio.

Back in the day, found [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/265f698a-faf1-426b-a72b-a4c9aab7cd92/an-appeal-to-optimize-visual-c-template-compilation) an interesting read. But I believe they, too, are doing much better today (VS 2017).

**Comment by babylon73** [comment]
I guess they do... interesting anyway, thanks for the link.
