### ISSUE TITLE
HELP: train face recognition model from scratch on a larger database

### ISSUE THREAD

**Issue by sushil-bharati** [davisking/dlib#1972]
Hi @davisking . Thanks a lot for creating a ML/DL tool for training different avenues of models.

I would like to leverage the tool you developed to train my own face recognition model on ~7M images I have collected. I am also willing to open source this if it passes the benchmark. Fingers crossed.

Before I involve myself in this massive training task, here are a couple of questions that seek your attention:

- Were faces aligned for training dlib's face recognition model v1? If yes, what techniques were used?
- Were faces resized for training dlib's face recognition model v1? If yes, what dimensions?
- Does [dnn_metric_learning_on_images_ex.cpp](https://github.com/davisking/dlib/blob/master/examples/dnn_metric_learning_on_images_ex.cpp) suffice to start training?
- Any data augmentation (other than mentioned in the example file above) was used during the original training of dlib's face recognition model v1?
- If there were any changes made to the above example file, would you please share the changes or the original training code template?
- Any other tips/tricks for training face recognition model using dlib tool?

Thank you for your time. :)

**Comment by davisking** [comment]
The docs in
https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp
says
how it was trained.  It's basically using the example you linked to though,
but with the changes noted in
https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp
.
