### ISSUE TITLE
Will Dlib support python 3.7?

### ISSUE THREAD

**Issue by ybsave** [davisking/dlib#1974]
As python 3.7 has been released for long time, will dlib support python 3.7? I tried several ways to install dlib in my conda environment, but none of the online solutions works. Thank you.

My install commands are:  conda install -c menpo dlib python=3.7

The conflict messages are:

Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
dlib -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.1.1b,<1.1.2a'] -> ca-certificates
dlib -> python[version='>=3.5,<3.6.0a0'] -> ca-certificates
Package pip conflicts for:
dlib -> python[version='>=3.5,<3.6.0a0'] -> pip
python=3.7 -> pip
Package python conflicts for:
python=3.7
dlib -> python[version='2.7.*|3.5.*|>=3.5,<3.6.0a0']
dlib -> numpy -> python[version='>=2.7,<2.8.0a0']
Package setuptools conflicts for:
dlib -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools
python=3.7 -> pip -> setuptools
Package wheel conflicts for:
dlib -> python[version='>=3.5,<3.6.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel

**Comment by davisking** [comment]
Dlib should work fine for python 3.7.  Get the dlib code from github and run `python setup.py install`

**Comment by srp6996** [comment]
while installing the dlib in ubuntu 18.04 and python 3.7 
am getting this error
while testing the dlib in terminal giving this
>>> import dlib
Illegal instruction (core dumped)

**Comment by davisking** [comment]
Fill out the complete issue template.  I say this because dlib works fine in python 3.7, so you must have done something unusual.

**Comment by srp6996** [comment]
I have followed the steps from Adrian site to install dlib
https://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/
there is no problem while installing but when i text whether it is installed properly I'm getting that error,(illegal instruction, core dumped)
hardware - ubuntu 18.04
anaconda

**Comment by raibove** [comment]
I installed dlib on windows for python 3.7 with pip install dlib and it was installed successfully.

**Comment by AutoCoder22** [comment]
Hi raibove,

Could you please walk me through the installation process of dlib for python 3.7? 

I have tried many ways to crack it but I couldn't make it.

Thanks in advance

**Comment by Gzurakowski** [comment]
i don't know what happens, i installed Cmake, and windows smk and i still get this error

`ERROR: Command errored out with exit status 1: 'd:\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gonzalo\\AppData\\Local\\Temp\\pip-install-kch32fsc\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Gonzalo\\AppData\\Local\\Temp\\pip-install-kch32fsc\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Gonzalo\AppData\Local\Temp\pip-record-0w_wtkqo\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:Include\dlib' Check the logs for full command output.`

**Comment by HatFayed** [comment]
I successfully installed dlib 19.8.1 on Python 3.7 for windows 64bit using
https://www.file-upload.com/qsd69ajuqr2i

**Comment by hissain** [comment]
Getting below error,

```
Collecting dlib
  Using cached dlib-19.20.0.tar.gz (3.2 MB)
Using legacy setup.py install for dlib, since package 'wheel' is not installed.
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-record-mgd7jsn1/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/dlib
         cwd: /private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/
    Complete output (55 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py", line 223, in <module>
        setup(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py", line 122, in get_cmake_version
        raise RuntimeError("\n*******************************************************************\n" +
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************

    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py'"'"'; __file__='"'"'/private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-install-o6haxzf9/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qz/jy_v70tj0792_gq7d947v1pw0000gn/T/pip-record-mgd7jsn1/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/dlib Check the logs for full command output.
Hissains-MacBook-Pro:hello hissain$ sudo pip install dlib
Password:
WARNING: The directory '/Users/hissain/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting dlib
  Downloading dlib-19.20.0.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 40 kB/s 
Using legacy setup.py install for dlib, since package 'wheel' is not installed.
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-qgvw2vfu/dlib/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-qgvw2vfu/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-8_5bsakx/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/dlib
         cwd: /private/tmp/pip-install-qgvw2vfu/dlib/
    Complete output (55 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "/private/tmp/pip-install-qgvw2vfu/dlib/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

    During handling of the above exception, another exception occurred:
```

How can I resolve it?

**Comment by abhitatachar2000** [comment]
Hi hissain,
try installing cmake using pip install cmake, that should help.

**Comment by silikmaz** [comment]
Getting below error,

**Comment by silikmaz** [comment]
Getting below error, Requirement already satisfied: cmake in d:\program\py\py37\lib\site-packages (3.17.3)     ERROR: Command errored out with exit status 1:
     command: 'd:\program\py\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\silik\AppData\Local\Temp\pip-record-xmfzpcs4\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\program\py\py37\Include\dlib'
         cwd: C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\
    Complete output (57 lines):
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=d:\program\py\py37\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\build\lib.win-amd64-3.7 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.


    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/silik/AppData/Local/Temp/pip-install-4arzvqdz/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "d:\program\py\py37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "d:\program\py\py37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\program\py\py37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\program\py\py37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\program\py\py37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "d:\program\py\py37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "d:\program\py\py37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\program\py\py37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\program\py\py37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "d:\program\py\py37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\program\py\py37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\setup.py", line 135, in run
        self.build_extension(ext)
      File "C:\Users\silik\AppData\Local\Temp\pip-install-4arzvqdz\dlib\setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "d:\program\py\py37\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=d:\\program\\py\\py37\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\program\py\py37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\silik\\AppData\\Local\\Temp\\pip-install-4arzvqdz\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\silik\AppData\Local\Temp\pip-record-xmfzpcs4\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\program\py\py37\Include\dlib' Check the logs for full command output.

**Comment by davisking** [comment]
You need to install visual studio so that you can build dlib.

**Comment by anshikakankane** [comment]
Hi Davisking!
I tried installing dlib in python 3.7 and got this error

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\anshi\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\anshi\AppData\Local\Temp\pip-wheel-2f6wp1cs'
       cwd: C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\Users\anshi\anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\build\lib.win-amd64-3.7 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:3 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/anshi/AppData/Local/Temp/pip-install-ml3hq1e3/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "C:\Users\anshi\anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\anshi\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\anshi\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\Users\anshi\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\anshi\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\anshi\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\setup.py", line 135, in run
      self.build_extension(ext)
    File "C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\Users\anshi\anaconda3\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\Users\\anshi\\anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\anshi\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\anshi\AppData\Local\Temp\pip-record-88girtja\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\anshi\anaconda3\Include\dlib'
         cwd: C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\
    Complete output (57 lines):
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\Users\anshi\anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\build\lib.win-amd64-3.7 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.


    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/anshi/AppData/Local/Temp/pip-install-ml3hq1e3/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "C:\Users\anshi\anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\anshi\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\anshi\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\anshi\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\anshi\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\anshi\anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\anshi\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\anshi\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\setup.py", line 135, in run
        self.build_extension(ext)
      File "C:\Users\anshi\AppData\Local\Temp\pip-install-ml3hq1e3\dlib\setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "C:\Users\anshi\anaconda3\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\Users\\anshi\\anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\anshi\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\anshi\\AppData\\Local\\Temp\\pip-install-ml3hq1e3\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\anshi\AppData\Local\Temp\pip-record-88girtja\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\anshi\anaconda3\Include\dlib' Check the logs for full command output.


Can you please help me to resolve it?
I have already installed cmake, setuptools and visual studio.
Thanks in advance!

**Comment by davisking** [comment]
What happens if you use the latest dlib from github?

**Comment by anshikakankane** [comment]
It shows error: .whl file is not supported on this platform. Because the latest file I used was cp35.whl type.
My python version is 3.7 and I can't find the dlib-..-cp37-...whl file for this version.

**Comment by davisking** [comment]
I don’t know what you did. Please get dlib from github. Note there are no whl files on github.

**Comment by ElPrg** [comment]
> 
> 
> I installed dlib on windows for python 3.7 with pip install dlib and it was installed successfully.

What version of Win ?

**Comment by praveenece443** [comment]
hi sir, i recently bought an asus laptop with windows 10 and python3.8 version, how can i install dlib because i cant find either any wheel file or i cant install through source. please help me

**Comment by HatFayed** [comment]
Try the following whl file for dlib 19.8.1 for Python 3.8 under Windows 64
https://www.file-upload.com/bz98cr81h0lr

**Comment by gengyanlei** [comment]
@HatFayed 
this link is not useful.

**Comment by MengHao666** [comment]
> Hi hissain, try installing cmake using pip install cmake, that should help.

that doesn't help.
