### ISSUE TITLE
face_recognition_model _v1 different input face sizes and boundary boxes 

### ISSUE THREAD

**Issue by Fizmath** [davisking/dlib#1975]
Hello

Can i feed face images with boundary boxes and resolutions from other face detectors  into the ``DLIB's face_recognition_model _v1``  to get the embedding vectors ?  
For example `` 40*40 `` face with boundary boxes  from ``OpenCV cv2.dnn.readNetFromCaffe `` ? 
If it is possible , how would the embedding vectors of the same image with different resolutions  i,e ``40*40``   , `` 80*80``  differ?

**Comment by davisking** [comment]
The face model doesn't somehow know where the boxes come from.  All that matters is that the boxes are aligned the way the dlib code aligns them.  If you attend to that then you are fine.

**Comment by Fizmath** [comment]
Yes it worked fine :

1. Detect faces in frames with ``OpenCV cv2.dnn.readNetFromCaffe `` 
2. Rearrange the output from ``` [(startX, startY, endX, endY)] ``` to ```[(startY, endX, endY, startX)]```
3. Feed the new output to  ``DLIB's face_recognition_model _v1``

The embedded vectors had negligibly small difference from that of ```DLIB``` detector

Thanks
