### ISSUE TITLE
set_listening_ip to public gave error "unable to create listener"

### ISSUE THREAD

**Issue by wpmanoj** [davisking/dlib#1981]
## Expected Behavior
I'm Using server_http_ex.cpp example. I just added a line after "set_listening_port" 

`our_web_server.set_listening_ip("111.111.111.111"); //  this IP is model. i added at that time my pc public ip`

## Current Behavior
then i compile with VS 2019 and run in command line.
 gave me a error : 
"error occurred in server::start()
unable to create listener"

but example works perfectly with IP 112.0.0.1 => localhost

Please let us know how should we use dlib http server to public serve.

* **Version**: 19.19
* **Where did you get dlib**: official release
* **Platform**: Windows 10 1909 64bit
* **Compiler**: visual Studio 2019

**Comment by davisking** [comment]
You can't set any IP address, it has to be an IP address your computer has.
