### ISSUE TITLE
Grayscale and depth information in one image

### ISSUE THREAD

**Issue by sglimberg** [davisking/dlib#1982]
Hi,
I have been training an object detector based on the nice examples provided in dlib. The images I have are all grayscale, but I also have depth information for each image, i.e. each pixel represents the distance to the object from the camera. I consider using an rgb image and then use one channel for the "normal" grayscale image and another for the depth information. 
However, it is not clear to me how dlib handles multiple color channels in one image, will it actually be useful for the object detector or am I better off traning two seperate models?

Thanks,
Stefan

**Comment by davisking** [comment]
Which object detector?  The CNN one or the HOG one?  HOG just sort of is what it is, you could replace a color channel with depth information and maybe that would be fine.  But for a CNN based detector you can make a new input layer that takes in a 2 channel image or whatever you want.  The dlib API is setup so you can easily define your own input layers.  See http://dlib.net/dlib/dnn/input_abstract.h.html#EXAMPLE_INPUT_LAYER

**Comment by sglimberg** [comment]
Thanks, so far I have been using the HOG detector. The fhog_object_detector_ex.cpp uses an array2d<unsigned char> to store images, I assume this will just make a grayscale image out of an rgb image. So I changed it to array2d<rgb_image> instead, which seems to work OK. I will have to train on some more data now to verify. 
Ideally, I would like to use the CNN, but I have a real time constraint in my program and the users will not always have a GPU. Running the dnn_mmod_face_detection_ex with the pretrained face detector takes several seconds on the CPU (Intel i7, 2.6Ghz). I can do the training on a GPU, so that part is Ok, but I cannot allow the detection to take more than ~100 ms. Do you believe that is possible to achieve with a CNN and no GPU? My images are only 320x256.

**Comment by davisking** [comment]
The CNN is faster on CPU if you install the Intel MKL, but it's still very slow compared to HOG.  If HOG is working for you then I would try to stick with that if you care about speed.

**Comment by sglimberg** [comment]
Ok, thanks. Have been training the HOG on more data now and so far it looks really good. Great tool!
