### ISSUE TITLE
Python process hanging on exit after calling cnn_face_detection_model_v1 (Windows)

### ISSUE THREAD

**Issue by rover886** [davisking/dlib#1983]
_Note: The same issue was reported in the year 2017 #1000, and it was closed after fixing it in version 19.7, but it looks like it's happening again,hence opened a new issue._

## Expected Behavior
I am using dlib version 19.19.0 and python version 3.8.1 for CNN based face detection. For testing purpose I used program given on http://dlib.net/cnn_face_detector.py.html. When CNN detection is performed python process should exit after hitting enter.

## Current Behavior
No error message is thrown. Looks like python process is hanged when CNN detection performed. I pressed enter key to continue to exit from program.

## Steps to Reproduce

- Take code from http://dlib.net/cnn_face_detector.py.html
- Execute file with command `cnn_face_detector.py mmod_human_face_detector.dat image.jpg`
- Face detection is performed and image  will be shown in window, on console "Hit enter to continue" will be shown.
- Press enter key. It will close image window but process is still running and does not exit for infinite time.

It has been observed that this behavior only happens when we execute detector, if we comment the line of code `dets = cnn_face_detector(img, 1)` then program exists normally. 

* **Version**: 19.19.0
* **Where did you get dlib**: `pip install dlib`
* **Platform**: Windows 7 64 Bit
* **Compiler**: Python 3.8.1 64 Bit

**Comment by davisking** [comment]
Are you building with CUDA, the Intel MKL, or any other stuff like that?

**Comment by rover886** [comment]
No, I am not using anything of it. Is it compulsory?

**Comment by davisking** [comment]
No, none of that is required. I'm quite surprised this kind of thing is
happening without any funny linking to 3rd party tools though.

**Comment by davisking** [comment]
That is, people use this on windows all the time and don't have this
problem.  I'm expecting there to be something unusual in your setup.

**Comment by rover886** [comment]
I did setup on another machine, but same thing happened.

**Comment by davisking** [comment]
I don't know what to look at.  This isn't something I can reproduce, and lots of other people use dlib in this way and don't have this issue.  There must be something different you aren't reporting that's making it happen.

For instance, I tried running the cnn face detection example yesterday in windows 10 with python 3.8.1, built by visual studio, not using CUDA, and it all worked normally.

**Comment by laviua** [comment]
Apple M1 mac mini
macos: 13.0 (22A380)

the same problem
