### ISSUE TITLE
Unexpected exception after cuda error

### ISSUE THREAD

**Issue by Kicer86** [davisking/dlib#1984]
## Expected Behavior
dlib.cnn_face_detection_model_v1 should be stateless and its result should not depend on previous calls.

## Current Behavior
When using dlib.cnn_face_detection_model_v1 from python bindings it is possible to get an unexpected exception.

I wrote a simple example using face_recognition module from https://github.com/ageitgey/face_recognition. (However I can reproduce it with c++ using dlib directly).
When dlib.cnn_face_detection_model_v1 throws an exception due to too much memory allocation, second usage of this method will **always** throw. No matter the arguments.

See the example code:
```
from PIL import Image
import face_recognition

image = face_recognition.load_image_file("image.jpg")


# First execution with upsamples == 0, we do not expect error
try:
    face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=0, model="cnn")
except:
    print("error")
else:
    print("no error")

# Second execution with upsamples == 1, error may occur when too much memory is to be allocated
try:
    face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=1, model="cnn")
except:
    print("error")
else:
    print("no error")

# Third execution with upsamples == 0, we do not expect error
try:
    face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=0, model="cnn")
except:
    print("error")
else:
    print("no error")

# Fourth execution with upsamples == 0, we do not expect error
try:
    face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=0, model="cnn")
except:
    print("error")
else:
    print("no error")
```

Image used in this code was downloaded from https://thispersondoesnotexist.com/
First call to face_locations returns one face.
Second call fails on my PC due to cuda memory allocation error:
```
  File "/usr/lib/python3.8/site-packages/face_recognition/api.py", line 100, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaMalloc(&data, n) in file /home/michal/.cache/yay/python-dlib-cuda/src/dlib-19.19/dlib/cuda/cuda_data_ptr.cpp:58. code: 2, reason: out of memory
```

This is fine, I can catch this exception.

However next call, which is exactly the same as first one fails too:
```
  File "/usr/lib/python3.8/site-packages/face_recognition/api.py", line 100, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaGetLastError() in file /home/michal/.cache/yay/python-dlib-cuda/src/dlib-19.19/dlib/cuda/gpu_data.cpp:114. code: 2, reason: out of memory

```

My program output:
no error
error
error
no error

Expected output would be:
no error
error
no error
no error

## Steps to Reproduce
call dlib.cnn_face_detection_model_v1(image, upsample) with a big image or use big value for `upsample` argument and catch cuda exception.
call dlib.cnn_face_detection_model_v1(image, upsample) with normal image and get an unexpected exception.

* **Version**: 19.19
* **Where did you get dlib**: Arch AUR repo
* **Platform**:  64 bit Arch Linux:
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
* **Compiler**: gcc (GCC) 9.2.0

**Comment by davisking** [comment]
This is expected.  The network only reallocates when more memory is needed.  So once you have caused it to allocate more it's going to keep it, unless you call `.clean()` on it.  

But really, you need to avoid blowing out the memory in the first place.

**Comment by Kicer86** [comment]
Ok. I have tried to find related information in Python API without success. Could you please tell me where can I read how to check if image will be too big and on which object should I call `clean()` to release memory in case of error.

**Comment by davisking** [comment]
.clean() isn't part of the Python API.  It really exists to remove this
stuff from the network prior to saving the network to disk, so that the
resulting file is smaller.  It's not meant to be a memory management tool.
You definitely should not be writing code that expects, as the normal
execution flow, to be causing and catching memory allocation errors though.
The right thing to do is to not feed in images larger than your machine can
handle.  I don't know what that limit is, it depends on your machine
configuration and if you are using cuDNN, possibly which version of cuDNN,
or the Intel MKL.  Just pick an image size that you know uses whatever is
an appropriate amount of RAM for your task and use that.

**Comment by Kicer86** [comment]
As far as I understand it is impossible to figure out what is the limit in advance, as it depends on current GPU memory usage by other applications. Also if I run my application on another PC, my  assumptions may be incorrect. 
Therefore there is no safe image size and I may end up with exception even for small images.
It is all fine as long as I can safely recover after such an exception, which seems to be problematic at this moment.

**Comment by davisking** [comment]
Doesn't that argument apply to system RAM?

If you run out of GPU RAM for small images then you just can't run.  What
are you going to do when you get a GPU memory allocation failure?  Like
specifically, what do you want to do to recover?

**Comment by Kicer86** [comment]
As far as I understand it applies to GPU RAM as well. I can run nvidia utility to observe how much RAM is free. In my case its ~1.4GB. If I run my python script provided above and I pause execution at first face detection, I see free GPU RAM dropped down to ~700MB.
If I run the same script in a parallel I end up with out of memory at first face detection as there is not enought free GPU memory. 
The same can happen in other scenarios when one app can consume GPU memory for a while during my script execution and I'll end up with out of memory even if a few minutes before it was working.

How can I recover from this? At least 3 ways: 
1. Retry. GPU RAM could be freed.
2. resize image.
3. ask user what to do.

**Comment by davisking** [comment]
The pybind11 bindings for this tool are defined in dlib/tools/python/src/cnn_face_detector.cpp.  So you can call `clean()` by adding a binding for it to the class you are using in python.  I still think this isn't a very good way to organize an application, but you are welcome to call `clean()`.

**Comment by Kicer86** [comment]
Please tell me then how in your opinion application should behave when image (possibly given by user) does not fit into free gpu memory which (as I have shown above) application cannot verify upfront? Because I am clearly missing something here.

**Comment by davisking** [comment]
I would tell the user the error and let them decide. Which generally means
using a smaller image.

**Comment by Kicer86** [comment]
That's what I would do in my program, but even if user takes another, much smaller image, dlib.cnn_face_detection_model_v1 will throw an error as I have described in my first comment.

**Comment by Kicer86** [comment]
Calling `clean()` does not help. Even destroying dlib objects does not help (all GPU RAM is restored).

**Comment by davisking** [comment]
Well, `clean()` is alling `cudaFree()`.  There isn't anything more I could do.  This is a limitation of the CUDA runtime on your platform.  Like in general, I wouldn't expect the CUDA runtime to necessarily be in a great state once an OOM error happens.  Which is another reason why you should structure your application/software/workflow or whatever you have control of to avoid them.
