### ISSUE TITLE
Face detector issue.

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#1990]
Hi,
I got Strange issues with the dlib face recognition.
I also saw 2other recent posts out there.

I myself get a Code 700 on gpu_data.cpp line 97.

Was there anything changed ? 
I use NVIDIA cuda and cudnn (cuda 10.2 if that helps).
Windows 10 btw
Its Strange to me that now Multiple peolple have diffrent wierd Problems with the previous very stable code. Maybe a cuda 10.2&dlib issue ?

Thanks as always

**Comment by VisionEp1** [comment]
Oh and i use c++

**Comment by davisking** [comment]
@reunanen changed that bit of code recently to work around the CUDA bug more completely.  Try the latest code on github.
