### ISSUE TITLE
Need HOG SVM detector file of frontal_face_detector instead of binding inside .h file

### ISSUE THREAD

**Issue by vasanthhr** [davisking/dlib#1992]
Can you please guide me how I can get .SVM file of frontal_face_detector?

(As you mentioned , this HOG detector is binded inside frontal_face_detector.h).

Is there any way I can convert the frontal_face_detector.h into SVM file ?

**Comment by arrufat** [comment]
Have you tried this?

``` c++
frontal_face_detector detector = get_frontal_face_detector();
serialize("frontal_face_detector.svm") << detector;
```

**Comment by vasanthhr** [comment]
@arrufat , thanks for updates.

Can you give me similar dlib API in python ?

**Comment by arrufat** [comment]
@vasanthhr As far as I know, that is not possible from Python.

**Comment by davisking** [comment]
You can call `.save('filename')` on the detector.
