### ISSUE TITLE
Dlib Facial Landmarks Prediction Scores?

### ISSUE THREAD

**Issue by harshit-saraswat** [davisking/dlib#1993]
I'm trying to use dlib's shape predictor to get facial landmarks and after days of researching I found there's no way to get prediction scores/confidences for individual landmarks.

I'm trying to find out, if there's any way to check whether the landmarks given actually exist in the image or not? Doesn't matter if DLIB provides it or not or it's just some naive python code or logic? 

Anyone knows what to do?

**Comment by davisking** [comment]
What do you mean by "exists in the image or not"?

**Comment by harshit-saraswat** [comment]
@davisking 
![Untitled](https://user-images.githubusercontent.com/41959164/74130170-759e1d80-4c07-11ea-8993-87d6b3e3f7ff.png)

As you can see in this image I've covered my mouth area and yet dlib predicted mouth and chin points. Is there a way to know if those points are covered or actually in the image or not?

**Comment by davisking** [comment]
It's up to you to make some classifier or similar thing to make this determination.  There are a lot of ways to do it, depending on the details of your problem.  A simple thing to try first is take the features used by the shape predictor (output as `feats`, see https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor_abstract.h#L68) and train a binary linear SVM classifier to say if they are occluded or not.

**Comment by harshit-saraswat** [comment]
@davisking training the model to check for occlusion would be a tedious task given their might be mutliple types of occlusions and we're given around 68 features.
That's why I was asking if DLIB provides scores directly or not?

**Comment by davisking** [comment]
It doesn’t. You need to set that up if you want it.

**Comment by harshit-saraswat** [comment]
@davisking any idea on how I can do that?

**Comment by lyw8120** [comment]
I do not receive this kind of email any more, please help me unsubscribe it
(I did it on github but no effect.)

**Comment by harshit-saraswat** [comment]
Hey, I was able to create a classifier using transfer learning, which can predict if eyes/mouth/nose actually exist in an image or not! Thanks!
