### ISSUE TITLE
C++20 forbids inserting inappropriate character types into standard streams

### ISSUE THREAD

**Issue by CaseyCarter** [davisking/dlib#1995]
The C++20 draft standard incorporates a change to help avoid confusion when inserting inappropriate character types to iostreams. In previous C++ versions, insertion of inappropriate character types into output streams (e.g., `wchar_t`/`char16_t`/`char32_t` into `std::cout`) doesn't result in transcoding of the character, but instead outputs a representation of its integral value. Insertion of pointers to such character types also does not transcode but outputs the value of the pointer. C++20 will add deleted stream insertion operators so that the expression `os << x` will instead be ill-formed when `os` is a `std::ostream` (a narrow character stream) and `x` is a `wchar_t`/`char16_t`/`char32_t` or pointer to such.

We're implementing these changes right now in MSVC, and our automated tests show that your product (or its tests) will fail to compile with these changes in `/std:c++latest` mode unless the "escape hatch" macro `_HAS_STREAM_INSERTION_OPERATORS_DELETED_IN_CXX20` is defined. Specifically, https://github.com/davisking/dlib/blob/master/dlib/test/string.cpp#L148 seems to output a `wchar_t*` to a `std::ostream`.

**Comment by davisking** [comment]
It's fine to change `DLIB_TEST_MSG( (left_substr(ws,L".") == L"file"), L"");` to `DLIB_TEST( (left_substr(ws,L".") == L"file"));`

Can you adjust this and submit a PR?
