### ISSUE TITLE
DLL load failed after compiling - possibly dlib.cp37-win_amd64.pyd

### ISSUE THREAD

**Issue by TropicalTsunami** [davisking/dlib#1996]
I am building a software that uses the dlib face detector as well as facial landmarks. 
The software works fine on my PC, as well as 5 other virtual and physical machines. However, execution fails on one other system where I tested it.

I compiled with Pyinstaller and created a Windows installer with Inno Setup.

##  Current Behavior
Importing of dlib fails on one tested system:
```
# dlib not found in PYZ
Traceback (most recent call last):
  File "BlinkGuard\blinkguard.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\User\Anaconda3\envs\BlinkGuard_packaging_v3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "BlinkGuard\model.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
```
## Expected Behavior
This is the console output on my own system, were it works fine:
```
# dlib not found in PYZ
# extension module 'dlib' loaded from 'C:\\Users\\User\\AppData\\Local\\Programs\\BlinkGuard\\dlib.cp37-win_amd64.pyd'
# extension module 'dlib' executed from 'C:\\Users\\User\\AppData\\Local\\Programs\\BlinkGuard\\dlib.cp37-win_amd64.pyd'
import 'dlib' # <_frozen_importlib_external.ExtensionFileLoader object at 0x00000215B157CB08>
```
## Steps to Reproduce
I am not sure, what is causing the error. My best guess is, building on a newer PC, executing on an older one. I assume it has something to do with the system architecture. It stands out to me that its a Pentium CPU where the execution fails.

CPU used to building: Intel(R) Core(TM) i7-8750H CPU 
CPU of the system were it fails to execute: Intel(R) Pentium(R) CPU 4415U 

I assume the file dlib.cp37-win_amd64.pyd does not work correctly for the third party system.

* **Version**: dlib=19.19
* **Where did you get dlib**: ```conda install -c conda-forge```
* **Platform**: Win 10 64bit (both built and tested on)
* **Compiler**: pyinstaller 3.6

My best guess is, I need to add a different file than dlib.cp37-win_amd64.pyd to make it work on the other system. However, Googling for hours has not told me if I am right, which dll to use and how to make sure this error does not happen on additional systems in the future.

**Comment by davisking** [comment]
It's probably being built to use SSE and/or AVX instructions, which are
then not available on the old system.  When dlib builds it prints out
messages saying it's using these instructions or not.  The default rule is
to use them if they are available on the system doing the build.  You can
disable these by using --no, like this:

python setup.py build --no USE_AVX_INSTRUCTIONS --no USE_SSE2_instructions
--no USE_SSE4_INSTRUCTIONS

**Comment by TropicalTsunami** [comment]
Thanks! I can confirm the old CPU is not supporting AVX (but SSE is supported). It is a Pentium CPU, apparently, even newer models lack AVX support. They would be painfully slow at face detection anyways, so I will just not support them.

Is it possible to check for an existing dlib build if SSE and/or AVX are used? I did not compile dlib myself but simply installed it using `conda install dlib`

**Comment by davisking** [comment]
Yes, these things are exposed in python as names like `dlib.USE_AVX_INSTRUCTIONS`.

**Comment by TropicalTsunami** [comment]
ok thanks! found it.
