### ISSUE TITLE
Why define DLIB_NO_GUI_SUPPORT by default on Ubuntu?

### ISSUE THREAD

**Issue by pkeir** [davisking/dlib#1998]
Is there a reason `DLIB_NO_GUI_SUPPORT` is defined in `dlib/config.h` in the version of dlib included on Ubuntu (e.g. 19.10)? This can be seen using:

`cd /tmp && apt-get download libdlib-dev && dpkg -x libdlib-dev* . && cat usr/include/dlib/config.h | grep DLIB_NO_GUI_SUPPORT`

Compiling, say [https://raw.githubusercontent.com/davisking/dlib/master/examples/3d_point_cloud_ex.cpp](https://raw.githubusercontent.com/davisking/dlib/master/examples/3d_point_cloud_ex.cpp), and then following the error message instruction, to "Turn DLIB_NO_GUI_SUPPORT off", a user with su privilege might comment out the relevant `#define` in the system file `/usr/include/dlib/config.h`, but for two of my machines at least, the command `g++ 3d_point_cloud_ex.cpp -ldlib` will still fail, with link errors starting:

undefined reference to `dlib::base_window::set_title(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

I am able to clone, build and run dlib and its examples. I only ask as I think this may present a barrier to dlib for some Ubuntu users.

**Comment by davisking** [comment]
I didn't setup the ubuntu package.  I don't know why it's packaged this
way, but yes, it's annoying.  Although some people legitimately have use of
this on systems without X11.  You could complain to the package maintainers
or ask for a libdlib-gui package ¯\_(ツ)_/¯

You definitely can't just go uncomment that line and expect it to work, as
the .so file that comes with it isn't built that way.

**Comment by pkeir** [comment]
Fair enough. I might well do that.
