### ISSUE TITLE
Error while calling cudaStreamSynchronize/cudaStreamCreateWithFlags/

### ISSUE THREAD

**Issue by EndErr** [davisking/dlib#2000]
Using dlib v.19.19 on CentOS 7.8 with CUDA 10.2 and 2 GPUs (GTX1070Ti that is detected as device 0 and a Quadro P4000 that is detected as device 1) with lates driver.
Everything works fine with first divice, thanks for that BTW.
But when try to change the device with dlib::cuda::set_device(1) the application build fine and then errors comes out.
First errors are:
`Error while calling cudaStreamSynchronize(stream) in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:101. code: 700, reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
Error while calling cudaStreamCreateWithFlags(&cstream, cudaStreamNonBlocking) in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:228. code: 700, reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
cudaFree() failed. Reason: an illegal memory access was encountered
Error while calling cudaStreamCreateWithFlags(&cstream, cudaStreamNonBlocking) in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:228. code: 700, reason: an illegal memory access was encountered
`
Found in issues that a solution could be removing upper limit in gpu_data.cpp, did so and then another errors comes out:
`Error while calling cudnnCreate(&handles[new_device_id]) in file /home/dev/test/libraries/dlib/dlib/cuda/cudnn_dlibapi.cpp:104. code: 1, reason: CUDA Runtime API initialization failed.
cudaFreeHost() failed. Reason: an illegal memory access was encountered
Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:218. code: 700, reason: an illegal memory access was encountered
cudaFreeHost() failed. Reason: an illegal memory access was encountered
Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:218. code: 700, reason: an illegal memory access was encountered
Error while calling err in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:97. code: 700, reason: an illegal memory access was encountered
Error while calling cudaMallocHost(&data, new_size*sizeof(float)) in file /home/dev/test/libraries/dlib/dlib/cuda/gpu_data.cpp:208. code: 700, reason: an illegal memory access was encountered
`
Could someone explain what is wrong?

**Comment by Compaile** [comment]
how did you resolve this?
