### ISSUE TITLE
Optimization with compiler

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#2002]
Hi @davisking Is it possible to optimize the speed by way of compiler, like TVM for deep learning models,  is it also possible to add similar features on dlib, e.g. the face landmarks detection to accelerate the speed on specific CPU/GPUs?

**Comment by davisking** [comment]
There isn't anything special in dlib that does this.  You can use the usual compiler optimizations available with your compiler as you would for any C++ code.

**Comment by anguoyang** [comment]
It seems In TVM they converted the model into an intermediate representation, and then it is better for  specific front-end to understand clearly how to optimize it automatically,  e.g. they have an AutoTune mechanism to accelerate the conv2d operation, on the whole network or layer wise.
