### ISSUE TITLE
Continuous Training

### ISSUE THREAD

**Issue by DaeMon87** [davisking/dlib#2003]
Hi

I am currently using dlib to classify product information using the one_vs_one_decision_function and radial_basis_kernel, I am using the one_vs_one_trainer to build my model .
I am adding machine learning to an existing C++ MFC application.

PLEASE NOTE: this project is my first attempt at working with machine learning.

From what I have looked into I build the one_vs_one_decision_function using the trainer which I can then output to a file and then use that to make predictions regarding my data. However I have not seen anything yet with regard to updating the decision funtion with new data?

What we envision our process to do is to train the model using the current product information, then as new product information is added we can use the decision function to classify the new records. After that we allow the user to make manual corrections before saving the information to the database.
What I would like to do is retrain the model using these corrections without losing th previously trained information.

Version: 19.19 of dlib
Source: downloaded from Github and built using cmake-gui and Visual Studio 2017
Platform: 64bit Windows

**Comment by davisking** [comment]
You have to retrain from scratch when you get more training data.  Add your new training data to your old dataset, making a bigger dataset, and train on that.
