### ISSUE TITLE
How to turn on instructions when installing dlib using vcpkg?

### ISSUE THREAD

**Issue by hennmarsk** [davisking/dlib#2004]
Sorry if the question is too naive since I am quite inexperienced.

I have done several researches but still haven't found anything. I'm installing dlib using vcpkg for my personal project, but there seems to be no option to enable instructions like AVX or SSE4, or at least as far as I know.

How do I enable instructions when installing dlib using vcpkg?

**Comment by davisking** [comment]
You just turn on the instructions in visual studio using it's toggle for these instructions, then set the appropriate preprocessor define to tell dlib to use them.  See how it's configured in cmake here for example https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/set_compiler_specific_options.cmake#L84

**Comment by hennmarsk** [comment]
Thanks a lot! For those who don't know how to turn on instructions in Visual Studio, follow Project Property Pages | Configuration Properties | C/C++ | Code Generation | Enable Enhanced Instruction Set.
