### ISSUE TITLE
How to define some things at runtime ?

### ISSUE THREAD

**Issue by DisgruntledBadger** [davisking/dlib#201]
First of all, I'm sorry for using the issue form but I'm unsure where else to post this.

I'm trying to approximate some values using the krr_trainer and since I'm a complete C++ noob I took this as an example for how to do things:

http://dlib.net/krr_classification_ex.cpp.html

Problem is, however, I have ~6 parameters which I could use for this regression and I'm quite unsure which of them are significant and which aren't.
Since the sample size is quite small (bellow 3k) and it seems that running this type of regression (even with 5-6 different parameters) takes quite little I thought I'd try running the regression 2^6 -1 times and trying out every possible parameter combination (then checking the result on the other half of the samples) to figure out which parameters could be used to make significant predictions.

Problem is... this means I have to be able to invoke a wrapper function around the dlib regression with a varied parameter size, like so:

        const int size = flags.par_nr;
        typedef matrix<double, size,1> sample_type;
        typedef radial_basis_kernel<sample_type> kernel_type;

Which, in turn fails, with a "value of size is not usable in a constant expression"  error(I assume because typedef need to be evaluated at compile time... though, again, I'm really bad when it comes to C++ so the reason might be something else).

My question is: Is there a way to have a sample and kernel type that is evaluated at runtime or make the function that computes the parameter number eval at compile time ? 

Is there a way to define a sample_type with a large number of parameters and have the kernel simply ignore them if they are not set ?

If there a way to achieve what I'm after or am i just taking a dumb path when it comes to this type of issue in a compiled language ?

**Comment by DisgruntledBadger** [comment]
Update:
The solution which I came to use is have the matrix be of size <double, 6,1> and not setting the samples to anything if I'm not using them, however I'm unsure if this is a good approach or if I should instead set "empty samples" to all be 0 or 1 or if I should work with "empty samples" in the first place

**Comment by davisking** [comment]
http://dlib.net/faq.html#HowdoIsetthesizeofamatrixatruntime
