### ISSUE TITLE
license plate detection 

### ISSUE THREAD

**Issue by masoudnick** [davisking/dlib#2012]
Hi all.
I trained a model for license plate detection with dlib python version ([code](http://dlib.net/train_object_detector.py.html)).

In the test phase,I wrote a python program and tested model on frame of videos and many license plate images and got in almost good results, but in c++ version of the same program the accuracy and speed of plate detection is less :( ([code](https://gist.github.com/masoudnick/18d42242bb40aa77728008879424d067))

What can I do to increase the speed and accuracy of detection in c++ program?
Do I have to adjust other parameters or not?
Please guide me :)

**Comment by davisking** [comment]
You are probably just not turning on compiler optimizations.
http://dlib.net/faq.html#Whyisdlibslow

**Comment by masoudnick** [comment]
@davisking 
No, i compiled my program in Release mode.

**Comment by masoudnick** [comment]
@dlib-issue-bot 
Ok,I'm ready, do it 😑

**Comment by facug91** [comment]
I think you are not giving enough information about how you are measuring speed.
About the accuracy, you are not converting the BGR image from OpenCV to RGB, before converting it to dlib.
