### ISSUE TITLE
object detection on big images

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#2013]
Hello
I'm thinking about using the dnn part of dlib to detect, and maybe classify, objects in an industrial environment, like, for example, solder joints on PCB's. But, unlike the typical industrial AOI systems, there will be no robot to move the camera, taking small pictures. Instead, one big picture of the board will be used. Some 20 megapixel industrial cameras have been ordered for this purpose.
But now I have the problem that the GPU is not able to process the entire image (at least on my laptop with a 4GB GPU, but for sure for any GPU there are images that don't fit into the GPU).
Is there anything already implemented in dlib to handle bigger images than the GPU can process in one step, or at least to assess the maximum image size the GPU can handle?

**Comment by davisking** [comment]
You should cut images like this up into smaller sub images and process those.  Pick a chunk size you know works with your hardware and algorithm selection.

**Comment by pepeverde9** [comment]
Thank you for the answer.
I was afraid that this has to be done.
It will be a little tricky, as there might be other programs using the GPU, like a web browser.

**Comment by davisking** [comment]
It's not a big deal.  It's just like writing a normal program.  You have to share CPU RAM with other processes as well.
