### ISSUE TITLE
Code and assert statement are inconsistent

### ISSUE THREAD

**Issue by hwiesmann** [davisking/dlib#2014]
## Expected Behavior
Either the assert statement or the code below in the "#else" section of the preprocessor statements should be removed.

PS: All the other methods in the same file do not have the assert statement.

## Current Behavior
Code exists that is not going / should not to be executed.

## Steps to Reproduce
CUDA tensor_tools.cpp has the following code

`    void scale_columns (
        tensor& out,
        const tensor& m,
        const tensor& v
    )
    {
...
#ifdef DLIB_USE_CUDA
        cuda::scale_columns(out, m, v);
#else
        DLIB_CASSERT(false, "shouldn't be called right now");
        out = scale_columns(mat(m), mat(v));
#endif
    }
`

dlib 19.19

**Comment by davisking** [comment]
Oh yeah, that shouldn't be there.  Guess that code never got used and I left a debugging statement in :|

Anyway, fixed it.  Thanks for the report :)
