### ISSUE TITLE
Mac vscode use Dlib, Unable to connect to the X display

### ISSUE THREAD

**Issue by mynamenoway** [davisking/dlib#2016]
hi,I used dlib for the first time and encountered some problems：

@"No protocol specified\r\n"
@" 1197 FATAL [1] dlib.gui_core: Unable to connect to the X display.\r\n"
@"Failed to initialize X11 resources\r\n"

I use vscode by compile all/source.cpp.
examples: webcam_face_pose_ex is ok.
how to fix ? thanks

**Comment by davisking** [comment]
You have to install X11.  Google "install X11 on OS X".  It should tell you
to download XQuartz and install it.

**Comment by mynamenoway** [comment]
My Mac have /usr/X11. Mac version: 10.15.3 (19D76).
this example webcam_face_pose_ex work ok.
Do I need to download x11 again？
