### ISSUE TITLE
Intel OpenVINO / Movidius NCS  support?

### ISSUE THREAD

**Issue by mludvig** [davisking/dlib#2026]
Hi

Are there any plans to support [Intel OpenVINO](https://software.intel.com/en-us/openvino-toolkit) as a backend inference engine for DLIB? That would provide support for all the Intel GPU / VPU hardware including [Intel Movidius NCS](https://software.intel.com/en-us/openvino-toolkit/hardware#VPU) that I would like to use on Raspberry Pi to speed up my inference tasks.

Any plans to add OpenVINO or specifically Movidius NCS support?

Thanks!

**Comment by davisking** [comment]
I have no such plans.
