### ISSUE TITLE
Not work with giflib 5.2.1

### ISSUE THREAD

**Issue by fengerzh** [davisking/dlib#2029]
After `brew upgrade`, now `giflib` is upgrade from 5.1.4 to 5.2.1. And dlib report following error:

```
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/dlib.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/giflib/lib/libgif.7.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/dlib.cpython-37m-darwin.so
  Reason: Incompatible library version: dlib.cpython-37m-darwin.so requires version 8.0.0 or later, but libgif.7.dylib provides version 0.0.0
```

I tried to downgrade giflib to 5.1.4 with `brew install giflib@5.1.4`, but failed, it reports:

```
Error: No available formula with the name "giflib@5.1.4"
```

Seems Mac OSX force to upgrade to giflib 5.2.1, but dlib cannot work with it. Please help, thanks!

**Comment by fengerzh** [comment]
To temporarily solve this problem, all I can do is listed as below in case someone may also meet the same problem:

1. Download giflib source code from [their website](https://sourceforge.net/projects/giflib/files/giflib-5.1.4.tar.gz/download). Be careful, it must be 5.1.4, no other version.

2. Unzip it to a folder, then run:

```
./configure
make
make install
```

3. After install, the executable files will be installed to `/usr/local/bin`, and library files will be installed to `/usr/local/lib`. However, python will try to find the library files from `/usr/local/opt/giflib/lib`, and in this path, there is a symbol link of `libgif.7.dylib` which link to `libgif.7.2.0.dylib`. Firstly we backup this symbol link:

```
mv libgif.7.dylib libgif.7.dylib.old
```

Then, we create a new symbol link to link to 5.1.4 version just installed:

```
ln -s /usr/local/lib/libgif.7.dylib ./libgif.7.dylib
```

After all this done, python with dlib can now work again. But still I hope the community can solve this problem properly. Thank you!

**Comment by davisking** [comment]
It sounds like you built dlib against that older libgif and then removed it during the upgrade. Try reinstalling dlib so it uses the new libgif.

**Comment by fengerzh** [comment]
Yes, I tried following commands, and now it works ok:

```
pip3 uninstall dlib
rm -rf ~/Library/Caches/pip
pip3 install dlib
```

Thank you!
