### ISSUE TITLE
How to get the pose angle for the face in dlib?

### ISSUE THREAD

**Issue by cibin91** [davisking/dlib#203]
In the face_landmark_detection_ex.cpp ,It find the landmark points for the face in the image and then crop and align the face.
I need to know the angle for the face or the yaw.pitch,roll value to determine its pose.

Can anyone helps how to get these values in dlib?

Thanks,
Regards
Cibin

**Comment by davisking** [comment]
This isn't in dlib.  But it's not too hard to do.  See this for example: https://github.com/chili-epfl/attention-tracker
