### ISSUE TITLE
How to use gender and age models?

### ISSUE THREAD

**Issue by mranosa** [davisking/dlib#2030]
Hello, I am a newbie and still learning. How can I implement dnn_gender_classifier_v1.dat and dnn_age_predictor_v1.dat in python? Is this already available for use in the current dlib release? Pointing me to resources that I can figure out or follow is also very much appreciated. Awesome library! Cheers!

**Comment by davisking** [comment]
There isn't any python API for it, but you can easily add one by using pybind11.  All of the pybind11 code dlib uses to expose things to python is in tools/python/src and there are excellent docs for pybind11 on the pybind11 home page.
