### ISSUE TITLE
Use of C++17 deprecated feature: std::iterator

### ISSUE THREAD

**Issue by JVApen** [davisking/dlib#2036]
## Expected Behavior
Compilation with C++17 without issues.

## Current Behavior
Warnings are triggered with new versions of the standard library about the usage of deprecated features.

> C:\DevStudio\Vs2019\VC\Tools\MSVC\14.24.28314\INCLUDE\xutility(974,1): warning C4996: 'std::iterator<std::forward_iterator_tag,double,__int64,double *,double &>::iterator_category': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators. You can define _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
>     using iterator_category = typename _Iter::iterator_category;
> ^

## Steps to Reproduce
Compile a small program with MSVC 14.24 (A recent build of VS2019) using matrix iterators

The issue is located in https://github.com/davisking/dlib/blob/d610e56c2ab000f8d129f0ae008f68a3d5597a4b/dlib/matrix/matrix_exp.h#L60

Relevant info about the deprecation: https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/

Looking in the search, this is the only occurrence.

Note: We were planning to patch this locally, once successful, I'll share a patch.

* **Version**: DLib 19.2 (Also reproducible in trunk)
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 64bit
* **Compiler**: MSVC 14.24

**Comment by JVApen** [comment]
Diff which can be applied
[Dlib_Std_Iterator.diff.txt](https://github.com/davisking/dlib/files/4387164/Dlib_Std_Iterator.diff.txt)

**Comment by davisking** [comment]
That diff duplicates `value_type`, but other than that looks good.  Do you want to submit it as a PR?

**Comment by JVApen** [comment]
Unfortunately, I can't work with git that well. Feel free to do it it in my place
