### ISSUE TITLE
I was trying to train a shape predictor model . I get the model and the model gives good results on the test images . But when i run the test.shape.predictor to get the accuracy i am getting a Nan or a very high value. Can you help?

### ISSUE THREAD

**Issue by cibyamary** [davisking/dlib#2037]
I was trying to train a shape predictor model . I get the model and the model gives good results on the test images . But when i run the test.shape.predictor to get the accuracy i am getting a Nan or a very high value. Can you help?

print("[INFO] evaluating shape predictor on testing data...")
error = dlib.test_shape_predictor("Test_images/45_imglab.xml", shape_detector)
print("[INFO] error: {}".format(error))

[INFO] evaluating shape predictor on testing data...
[INFO] error: nan

Expected Behavior
get the error value

 Current Behavior
[INFO] evaluating shape predictor on testing data...
[INFO] error: nan

* **Version**: dlib 19.19.0
* **Where did you get dlib**: installed using pip install on anaconda terminal
* **Platform**: Anaconda Windows 10

* **Compiler**: python 3.6

**Comment by gondimjoaom** [comment]
does anyone has an explanation for this? I'm also facing this problem
