### ISSUE TITLE
Could NOT find Threads (missing: Threads_FOUND)

### ISSUE THREAD

**Issue by habeeb555-q** [davisking/dlib#2043]
## Expected Behavior
complete the build without giving any errors.

## Current Behavior
cmake .. -DUSE_AVX_INSTRUCTIONS=1; cmake --build .
-- Using CMake version: 3.16.3
-- Compiling dlib version: 19.19.99
-- Enabling AVX instructions
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  dlib/CMakeLists.txt:322 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/syed007/temp/dlib/build/CMakeFiles/CMakeOutput.log".
See also "/home/syed007/temp/dlib/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

## Steps to Reproduce
     git clone https://github.com/davisking/dlib.git
     cd dlib
     mkdir build; cd build; 
     cmake .. -DUSE_AVX_INSTRUCTIONS=1; cmake --build .

* **Version**: dlib version: 19.19.99
* **Where did you get dlib**:  https://github.com/davisking/dlib.git
* **Platform**: Ubuntu 18.04.3 LTS
* **Compiler**: CMake version: 3.16.3

**Comment by habeeb555-q** [comment]
Solved the above issue by adding the following suggestions received on another thread.

    set(CMAKE_THREAD_LIBS_INIT "-lpthread")
    set(CMAKE_HAVE_THREADS_LIBRARY 1)
    set(CMAKE_USE_WIN32_THREADS_INIT 0)
    set(CMAKE_USE_PTHREADS_INIT 1)
    set(THREADS_PREFER_PTHREAD_FLAG ON)

**Comment by habeeb555-q** [comment]
Getting another error:
base64_kernel_1.cpp:6:
/usr/local/include/x86_64-linux-gnu/bits/endian.h:4:3: error: #error "Never use <bits/endian.h> directly; include <endian.h> instead."

**Comment by davisking** [comment]
I don't think this is related to dlib, but rather something is wrong with your compiler install.

**Comment by habeeb555-q** [comment]
Pip installed dlib and all the libraries perfectly but we are getting error only on building dlib while other libraries are doing fine. The following are errors:


Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8nl07hih/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8nl07hih/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_pt8_32g
       cwd: /tmp/pip-install-8nl07hih/dlib/
  Complete output (75 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.8.2 (default, Mar 13 2020, 10:14:16)
  Invoking CMake setup: 'cmake /tmp/pip-install-8nl07hih/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-8nl07hih/dlib/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python (found version "3.8.2")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.2.2
  -- Using CMake version: 3.16.3
  -- Compiling dlib version: 19.19.0
  -- SSE4 instructions can be executed by the host processor.
  -- AVX instructions can be executed by the host processor.
  -- Enabling AVX instructions
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  CMake Error at /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
    Could NOT find Threads (missing: Threads_FOUND)
  Call Stack (most recent call first):
    /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
    /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    /tmp/pip-install-8nl07hih/dlib/dlib/CMakeLists.txt:322 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-8nl07hih/dlib/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-8nl07hih/dlib/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-8nl07hih/dlib/setup.py", line 223, in <module>
      setup(
    File "/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-8nl07hih/dlib/setup.py", line 135, in run
      self.build_extension(ext)
    File "/tmp/pip-install-8nl07hih/dlib/setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-8nl07hih/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-8nl07hih/dlib/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, face-recognition, opencv-contrib-python
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8nl07hih/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8nl07hih/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mqz_c6sn/install-record.txt --single-version-externally-managed --compile --install-headers /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/include/site/python3.8/dlib
         cwd: /tmp/pip-install-8nl07hih/dlib/
    Complete output (77 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.8.2 (default, Mar 13 2020, 10:14:16)
    Invoking CMake setup: 'cmake /tmp/pip-install-8nl07hih/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-8nl07hih/dlib/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python (found version "3.8.2")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.2.2
    -- Using CMake version: 3.16.3
    -- Compiling dlib version: 19.19.0
    -- SSE4 instructions can be executed by the host processor.
    -- AVX instructions can be executed by the host processor.
    -- Enabling AVX instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    CMake Error at /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
      Could NOT find Threads (missing: Threads_FOUND)
    Call Stack (most recent call first):
      /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
      /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.16/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      /tmp/pip-install-8nl07hih/dlib/dlib/CMakeLists.txt:322 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-8nl07hih/dlib/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-8nl07hih/dlib/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8nl07hih/dlib/setup.py", line 223, in <module>
        setup(
      File "/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-8nl07hih/dlib/setup.py", line 135, in run
        self.build_extension(ext)
      File "/tmp/pip-install-8nl07hih/dlib/setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-8nl07hih/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-8nl07hih/dlib/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8nl07hih/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8nl07hih/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mqz_c6sn/install-record.txt --single-version-externally-managed --compile --install-headers /home/syed007/DEV/PYTHON/Workspace/learn/src/venv/include/site/python3.8/dlib Check the logs for full command output.

**Comment by habeeb555-q** [comment]
When I tried to download and build dlib getting following errors:


mkdir build; cd build; cmake .. -DUSE_AVX_INSTRUCTIONS=1; cmake --build .
-- Using CMake version: 3.16.3
-- Compiling dlib version: 19.19.99
-- Enabling AVX instructions
-- Found system copy of libpng: /usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so
-- Found system copy of libjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found OpenBLAS library
-- Using OpenBLAS's built in LAPACK
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/syed007/temp/dlib/build
[  1%] Building CXX object dlib/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
In file included from /usr/include/ctype.h:39,
                 from /usr/include/c++/9/cctype:42,
                 from /usr/include/c++/9/bits/localefwd.h:42,
                 from /usr/include/c++/9/string:43,
                 from /home/syed007/temp/dlib/dlib/base64/../algs.h:93,
                 from /home/syed007/temp/dlib/dlib/base64/base64_kernel_1.h:6,
                 from /home/syed007/temp/dlib/dlib/base64/base64_kernel_1.cpp:6:
/usr/local/include/x86_64-linux-gnu/bits/endian.h:4:3: error: #error "Never use <bits/endian.h> directly; include <endian.h> instead."
    4 | # error "Never use <bits/endian.h> directly; include <endian.h> instead."
      |   ^~~~~
In file included from /usr/include/pthread.h:25,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/gthr.h:148,
                 from /usr/include/c++/9/ext/atomicity.h:35,
                 from /usr/include/c++/9/bits/basic_string.h:39,
                 from /usr/include/c++/9/string:55,
                 from /home/syed007/temp/dlib/dlib/base64/../algs.h:93,
                 from /home/syed007/temp/dlib/dlib/base64/base64_kernel_1.h:6,
                 from /home/syed007/temp/dlib/dlib/base64/base64_kernel_1.cpp:6:
/usr/local/include/x86_64-linux-gnu/bits/endian.h:4:3: error: #error "Never use <bits/endian.h> directly; include <endian.h> instead."
    4 | # error "Never use <bits/endian.h> directly; include <endian.h> instead."
      |   ^~~~~
In file included from /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/gthr.h:148,
                 from /usr/include/c++/9/ext/atomicity.h:35,
                 from /usr/include/c++/9/bits/basic_string.h:39,
                 from /usr/include/c++/9/string:55,
                 from /home/syed007/temp/dlib/dlib/base64/../algs.h:93,
                 from /home/syed007/temp/dlib/dlib/base64/base64_kernel_1.h:6,
                 from /home/syed007/temp/dlib/dlib/base64/base64_kernel_1.cpp:6:
/usr/include/c++/9/ext/concurrence.h:119:34: error: ‘__PTHREAD_MUTEX_INITIALIZER’ was not declared in this scope; did you mean ‘PTHREAD_MUTEX_INITIALIZER’?
  119 |     __gthread_mutex_t _M_mutex = __GTHREAD_MUTEX_INIT;
      |                                  ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/9/ext/concurrence.h:174:44: error: ‘__PTHREAD_MUTEX_INITIALIZER’ was not declared in this scope; did you mean ‘PTHREAD_MUTEX_INITIALIZER’?
  174 |     __gthread_recursive_mutex_t _M_mutex = __GTHREAD_RECURSIVE_MUTEX_INIT;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [dlib/CMakeFiles/dlib.dir/build.make:63: dlib/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:94: dlib/CMakeFiles/dlib.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
