### ISSUE TITLE
in-source build leads to missing headers

### ISSUE THREAD

**Issue by jschueller** [davisking/dlib#2044]
when using out-of source build the headers are installed correctly, but not in-source
see https://github.com/davisking/dlib/blob/master/dlib/CMakeLists.txt#L891

## Expected Behavior

Headers getting installed

## Current Behavior

Headers are not installed

## Steps to Reproduce

```
$ curl -L https://github.com/davisking/dlib/archive/v19.19.tar.gz | tar xz && cd dlib-19.19 \
 && cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release . && make install
$ cat install_manifest.txt
/usr/local/lib64/libdlib.so.19.19.0
/usr/local/lib64/libdlib.so
/usr/local/include/dlib/config.h
/usr/local/include/dlib/revision.h
/usr/local/lib64/cmake/dlib/dlib.cmake
/usr/local/lib64/cmake/dlib/dlib-release.cmake
/usr/local/lib64/cmake/dlib/dlibConfig.cmake
/usr/local/lib64/cmake/dlib/dlibConfigVersion.cmake
/usr/local/lib64/pkgconfig/dlib-1.pc
```

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**: 
version is 19.19, Linux

**Comment by davisking** [comment]
You can't run cmake and tell it to generate all the build files in that folder, it stomps all over a bunch of other dlib files.  Do `mkdir build; cd build; cmake ..` instead.

**Comment by jschueller** [comment]
Yes, that's what I said: out-of-source builds are fine.
If it's borked, then the cmakelists should not allow it in the first place instead of silently messing up the install.

**Comment by davisking** [comment]
Sure.  It's disabled now on master.

**Comment by jschueller** [comment]
thanks
