### ISSUE TITLE
Tensor's memcpy() not working with alias_tensor on dest.

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#205]
Now a real bug for a change.

Using an `alias_tensor_instance` as an argument of tensors' `memcpy()` raises a fatal error:

```
**************************** FATAL ERROR DETECTED ****************************

Error detected at line 214.
Error detected in file /usr/local/include/dlib/dnn/gpu_data.h.
Error detected in function void dlib::memcpy(dlib::gpu_data&, const dlib::gpu_data&).

Failing expression was dest.size() == src.size().


******************************************************************************
```

A minimal code to reproduce is:
```c++
#include <dlib/dnn.h>

using namespace dlib;

int main()
{
	resizable_tensor full_A(1, 100);
	resizable_tensor B(1, 10);

	full_A = -1.0f;
	B = 1.0f;

	auto slice_A = alias_tensor(B.num_samples(), B.k(), B.nr(), B.nc())(full_A, 50);

	/* Any of the following two triggers the issue. */
	//memcpy(slice_A, B); 
	memcpy(B, slice_A);
}
```

**Comment by lvella** [comment]
I forgot to mention. This happens when compiling dlib without CUDA. I don't have a NVidia GPU.

**Comment by davisking** [comment]
Yeah, that's not good.  I'll fix it shorty.

**Comment by davisking** [comment]
I just pushed the fix for this.  Thanks for finding the bug :+1:

**Comment by davisking** [comment]
Oh and you should totally get a NVIDIA 1080.  The deep learning code is wildly faster on a 1080 vs a CPU.  Something that would take days on your CPU will take just a few hours on a 1080.  You can hardly trian anything interesting on a CPU by comparison :)

**Comment by lvella** [comment]
If I get serious with machne learning, I might. But it saddens me that I
already have an expensive AMD GPU that is useless for DNN for lack of
software support.

How much time is needed to clone cudnn in OpenCL?

Em 27/08/2016 12:34, "Davis E. King" <notifications@github.com> escreveu:

Oh and you should totally get a NVIDIA 1080. The deep learning code is
wildly faster on a 1080 vs a CPU. Something that would take days on your
CPU will take just a few hours on a 1080. You can hardly trian anything
interesting on a CPU by comparison :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/davisking/dlib/issues/205#issuecomment-242923890>, or mute
the thread

**Comment by davisking** [comment]
Ah, too bad.

It would be very time consuming to rewrite cudnn in OpenCL.  It's a large
piece of software that's highly optimized for specific pieces of hardware.
NVIDIA has a whole team of people that work on it and keep it updated for
new cards.  Realistically, it's a waste of time to try and rewrite cudnn.
You would have to keep updating it every time new hardware came out or you
would quickly find that cudnn is much better.
