### ISSUE TITLE
Element wise comparison ?

### ISSUE THREAD

**Issue by djomangan** [davisking/dlib#2051]
Hi, 
Thanks for this great code. I have a question

I would like to know how do you perform element-wise comparison of two matrix ?

## Expected Behavior

I expected to following behavior

dlib::matrix<double,3,1> m1; 
m1 = 1,1,1;
dlib::matrix<double,3,1> m2;
m2 = 2,2,2;
m1 <= m2 returns vector 1,1,1 (i.e. element-wise comparison)
m1 <= 2 return vector 1,1,1 (i.e. element-wise comparison)

## Current Behavior

But I currently have the following behavior

dlib::matrix<double,3,1> m1; 
m1 = 1,1,1;
dlib::matrix<double,3,1> m2;
m2 = 2,2,2;
m1 <= m2 returns true (i.e. full comparison)
m1 <= 2 return a vector 1,1,1 (i.e. element-wise comparison)

Idem for the over comparison operators.

## Config

- I am using the last version of dlib (downloaded yesterday from GitHub)
- 64 bit / Ubuntu 18.04 LTS 
- Compiler g++ / Compiled and used as dynamic library

**Comment by davisking** [comment]
There isn't a function in dlib to do that kind of comparison.

**Comment by djomangan** [comment]
Thanks for your fast reply.
