### ISSUE TITLE
module dlib has no attribute 'image_window'

### ISSUE THREAD

**Issue by yossibiton** [davisking/dlib#2057]
## Expected Behavior
after installing from source i was trying to run of the python scripts :
python python_examples/face_detector.py ~/Data/vggface2/test/n000001/*.jpg

## Current Behavior
got the following error message : 
Traceback (most recent call last):
  File "python_examples/face_detector.py", line 45, in <module>
    win = dlib.image_window()
AttributeError: module 'dlib' has no attribute 'image_window'

## Steps to Reproduce
1. install from source
2. run :
python python_examples/face_detector.py ~/Data/vggface2/test/n000001/*.jpg

* **Version**: 19.19.99
* **Where did you get dlib**: github repo
* **Platform**: macOS Catalina
* **Compiler**: used cmake, not sure what was the compiler

**Comment by davisking** [comment]
When you installed dlib it probably printed a big message saying it was
disabling use of GUI tools because X11 isn't installed.  Try reinstalling
dlib and looking for the message.  It tells you what to do to get the GUI
API.

**Comment by yossibiton** [comment]
You are absolutely right, i missed that big message.
It is fixed now, thank you!
