### ISSUE TITLE
dnn corrupted after failed deserialize

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#2059]
Hello

In order to reuse the training time, my application optionally can load a pretrained dnn, to be used usually after updating the dataset. After the last change in the network structure, the training seemed to be working, saving the dnn also seemed to be working, but when I attempted to load the network, it failed, complaining about padding_y being invalid.
As far as I know, there is no guarantee that after a failed deserialize("file")>>net; the network is still usable for training.
Nonetheless, it would be nice if there would be either a guarantee that the dnn is unmodified if deserialize fails, or that it's completely unusable, so that the training fails from the beginning, in order not to waste time attempting to train a network only to find out that it's corrupted and can not be loaded.

**Comment by davisking** [comment]
It throws an exception indicating the failure.  You can't use the `net` object if that happens.  Don't catch the exception and go back to using it.
