### ISSUE TITLE
Error in compling dlib with c++ cmake

### ISSUE THREAD

**Issue by p7Rck** [davisking/dlib#2060]
I am following your compiling dlib in c++ here http://dlib.net/compile.html

when i do the cmake --build . --config Release command

i have these error

Scanning dependencies of target webcam_face_pose_ex
[ 39%] Building CXX object CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o
In file included from /home/p7rck/Documents/dlib/dlib-19.19/dlib/../dlib/opencv.h:10:0,
                 from /home/p7rck/Documents/dlib/dlib-19.19/examples/webcam_face_pose_ex.cpp:30:
/home/p7rck/Documents/dlib/dlib-19.19/dlib/../dlib/opencv/cv_image.h: In instantiation of ‘dlib::cv_image<pixel_type>::cv_image(cv::Mat) [with pixel_type = dlib::bgr_pixel]’:
/home/p7rck/Documents/dlib/dlib-19.19/examples/webcam_face_pose_ex.cpp:73:42:   required from here
/home/p7rck/Documents/dlib/dlib-19.19/dlib/../dlib/opencv/cv_image.h:37:22: error: conversion from ‘const cv::Mat’ to non-scalar type ‘IplImage {aka _IplImage}’ requested
             IplImage temp = img;
                      ^~~~
CMakeFiles/webcam_face_pose_ex.dir/build.make:62: recipe for target 'CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o' failed
make[2]: *** [CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o] Error 1
CMakeFiles/Makefile2:881: recipe for target 'CMakeFiles/webcam_face_pose_ex.dir/all' failed
make[1]: *** [CMakeFiles/webcam_face_pose_ex.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

what causes the problem? any idea how to fix this one?
and can i run dlib without cuda?

Thank You!!

**Comment by arrufat** [comment]
This issue with OpenCV has already been fixed in master, just git clone the the latest revision and you should be fine.
In order to disable CUDA (at compile time) you should pass the `-DDLIB_USE_CUDA=OFF` to cmake.

**Comment by p7Rck** [comment]
Thank you!!! its now working
