### ISSUE TITLE
Is there any impact on accuracy if resizing image when encoding?

### ISSUE THREAD

**Issue by chanduthedev** [davisking/dlib#2065]
Hi @davisking,

I am getting CUDA_ERROR_OUT_OF_MEMORY error when I using face encoding with large set of data in GPU machine. I resized the image by half to resolve this issue. Most of the images are 1280x800 in dimension.

I would like to ask if there is any impact on accuracy if resizing the image to 1/2 or 1/3.

Thanks in advance.

**Comment by davisking** [comment]
I don't know what you are asking about. On accuracy of what?

**Comment by chanduthedev** [comment]
My sincere apologies for not asking clearly.  is there any impact in face encoding if we resize the image?

**Use case:**
We are using this library for Face recognition. First we will encode all faces and later use unknown face to  detect similar face from encoding faces. 
is there any impact on detecting similar face from the encoding faces if we resize the image?

Please forgive me if I am not clear.
Thanks in advance.

**Comment by davisking** [comment]
I still don't know what you are asking about.  The face recognition module
in dlib takes a fixed size image.  There is no opportunity to feed it
anything other than the one size it uses.

**Comment by chanduthedev** [comment]
Thank you for the quick response.  I am using Facial Recognition python model. I will ask in that repo. Thanks again.
