### ISSUE TITLE
Doubts about the MMOD examples

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2068]
Hi, I've been reading the MMOD examples several times, but there are things that I think I am missing.

The first MMOD example talks about a receptive field of a little over 50x50.
https://github.com/davisking/dlib/blob/253745d29fd510620a1bcee0add50a7663a9f5d6/examples/dnn_mmod_ex.cpp#L32-L39

However, the network downsamples the image by a factor of 8, and the sliding window has a size of 6x6 in the feature space, which translates to 48x48 pixels in the image space. So, shouldn't this be `a little under 50x50`?
Regardless of that, the objects that we are trying to detect are 40x40 pixels, which certainly fit inside of the 48x48 sliding windows.

In the DNN Face detection example, the network has been modified to detect 80x80 faces.
https://github.com/davisking/dlib/blob/253745d29fd510620a1bcee0add50a7663a9f5d6/examples/dnn_mmod_face_detection_ex.cpp#L27-L33

However, the sliding window is of size 9x9, which translates to 72x72 in the image space (since the down-sampling factor is 8).

I am guessing there is no problem if the object is a bit bigger or smaller than the sliding window.

Finally, in the car detector example:
https://github.com/davisking/dlib/blob/253745d29fd510620a1bcee0add50a7663a9f5d6/examples/dnn_mmod_train_find_cars_ex.cpp#L221-L229

A similar network is setup, so that the receptive field is 72, but in this case the maximum size is 70, which makes more sense to me than the previous object sizes and network receptive fields.

So, I am certainly missing something here.
I was sure I completely understood the relation between sliding window size, down-sampling of the network and min object size when I read the car examples. But when I read the other two previous examples, I had some doubts.

- Am I understanding correctly what the receptive field means in this case?
- How sensitive is the network to the relation between the min object size and the size of the sliding window? In other words, how much bigger/smaller can objects be with regards to the sliding window in the image space? (my guess is that it depends on how we setup the IoU for scoring the detections)

Thanks in advance :)

Edit:
I know that the literature defines the receptive field of a Iayer (or network) as all the pixels in the input image that contribute to the output of the layer (or network), which is computed in the following way:

![image](https://user-images.githubusercontent.com/1671644/79960981-08d5b800-84c1-11ea-9827-b0ac485324fa.png)

where:
- `rf`: receptive field
- `l`: layer index
- `ks`: kernel size
- `s`: stride
And the receptive field of the first layer is directly the kernel size.
With that in mind, the receptive field of the `dnn_mmod_ex.cpp` is:

|layer           | ks| s| rf                                        |
|----------------|---|--|-------------------------------------------|
|1               | 5 |2 | 5                                         |
|2               | 5 |2 | 5 + (5 - 1) * 2 = 13                      |
|3               | 5 |2 | 13 + (5 - 1) * 2 * 2 = 29                 |
|4               | 3 |1 | 29 + (3 - 1) * 2 * 2 * 2 = 45             |
|5               | 3 |1 | 45 + (3 - 1) * 2 * 2 * 2 * 1 = 61         |
|6               | 3 |1 | 61 + (3 - 1) * 2 * 2 * 2 * 1 * 1 = 77     |
|7               | 6 |1 | 77 + (6 - 1) * 2 * 2 * 2 * 1 * 1 * 1 = 117|

So, according to this formula, the receptive field of this network would be 117.

But I think, in the dlib examples, we are just referring to how we map the input and output coordinates of a layer (or network).

**Comment by davisking** [comment]
I think you understand everything correctly.  There is some kind of "effective receptive field" or reasonable target size for a network, which is closer to the receptive field sizes you noted (the ones based on downsampling factor) rather than the literal "how many pixels are involved in the computation".  I say this since things at the edges aren't necessarily well captured by a network.  This all depends on how the network is defined though.

**Comment by arrufat** [comment]
Oh, that's a relief, thanks for your quick reply.

So in the `dnn_mmod_ex` there's a typo, right? It should say "_a receptive field of a little **under** 50x50 pixels_", right?

It still surprises me that we can detect 80x80 objects with a window of 72x72. Is this because most of the features of what make a face a face are around the center, so it doesn't matter if the window is smaller?

I also noted that the difference in size between the sliding window and the target size is 8 in both mmod face examples (48 -> 40 and 72 -> 80), the same as the scaling factor, which also corresponds to how precise the location of the window will be. Is that on purpose, or just a coincidence?

**Comment by davisking** [comment]
Uh, yeah, maybe it should say `approximately 50x50` ¯\_(ツ)_/¯

Yeah, most of the features are in the interior of a face. And the receptive field is a bit larger than 72x72 anyway, as you have noted.

Right, the thing that matters a lot is box positioning resolution.  These examples have a stride of 8 pixels, which is reasonably small for 80x80 boxes.  If the stride was too big there would be objects we just couldn't detect since no box would fall on them.

**Comment by arrufat** [comment]
Thank you again for your explanation :)
