### ISSUE TITLE
Adapting dnn_face_recognition_ex.cpp for use with full body keypoints?

### ISSUE THREAD

**Issue by antithing** [davisking/dlib#2069]
Hi, and thank you for making this lib available!

I am looking to build a person Re-ID application, and am thinking of using an approach based on the example `dnn_face_recognition_ex.cpp`. 

My question is, will I need to re-train a model for this? Or can the `dlib_face_recognition_resnet_model_v1` be used for any set of keypoints? 

Basically, I would find body keypoints in a set of images, and pass them in place of the face landmarks to match them.

Is this a valid approach?

Thank you.

**Comment by davisking** [comment]
I would not expect that to work very well.  The face model is trained to know about faces.  If you give it pictures of people's bodies rather than faces it's probably not going to do anything sensible.

**Comment by antithing** [comment]
Understood. thank you for your reply. Have a great Sunday.
