### ISSUE TITLE
dlib with qualcomm snapdragon math libraries

### ISSUE THREAD

**Issue by raskolnikov-reborn** [davisking/dlib#207]
Hi Davis,
I'm trying to replace dlibs interface to blas and lapack with the qualcomm optimized QSML library. It shouldn't be too difficult since the library does provide all standard blas/cblas and  lapack interfaces. I've edited the CMakeLists.txt in dlib folder for it to use the include path and library path from the qsml library but where all should I change the code to include the new headers instead of the old ones. Once done, I can commit the changes upstream for you to review them.
Regards
Sahil

**Comment by davisking** [comment]
You only need to modify this one cmake file https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/cmake_find_blas.txt.  It's just a matter of making it output what library you want to link with.  Since the BLAS API is essentially a standard there are no headers or anything else to mess with.

**Comment by raskolnikov-reborn** [comment]
Thanks for your quick response. I pretty much did the same thing with using 2 new variables DLIB_USE_QSML_BLAS and DLIB_USE_QSML_LAPACK and modified the code accordingly. The thing is that in my include folder the headers have names like netlib_lapack.h, qblas1.h, qblas2.h.... I was wondering if I needed to update the code in dlib somewhere to make it use these headers or just specifying the folder name in a new file called cmake_find_qsml_blas.txt should be enough.

**Comment by davisking** [comment]
You don't need any new cmake options nor do you need to worry about those
headers.

I'm not familiar with QSML, but if it's really a BLAS library then all that
is needed is to modify that cmake file I mentioned.  If it's a BLAS library
and you are modifying other dlib files then you are doing something wrong.

**Comment by raskolnikov-reborn** [comment]
QSML provides all the standard blas 1 2 and 3 interfaces. I'll try to just update the cmake_find_blas.txt file instead of messing with CMake options. If it doesn't work, I'll hit you up for advice again. Thanks again for your wonderful work on dlib and your awesome support for the community.

**Comment by davisking** [comment]
No problem :)

All that's needed to work with a BLAS library is just to add the linker
statement.  It should look just like all the other instances in
cmake_find_blas.txt.  So you should only need to add a few lines of text to
that file.

**Comment by xsacha** [comment]
@davisking One problem with libraries such as this is that they may not be supported at run-time (due to lack of Snapdragon chip in this instance). Is there provision to allow fallbacks?

The headers in this library provide a function to check if the library is supported at run-time.

**Comment by davisking** [comment]
No.  This is all fixed at compile time.  If you need both then you need to compile separate binaries and invoke or link to the right thing yourself.
