### ISSUE TITLE
dlib is still using IplImage from OpenCV

### ISSUE THREAD

**Issue by john-forrest** [davisking/dlib#2071]
Recent changes (#1949 and #1963) have been added to work around issues that you can no longer directly assign cv::Mat objects to IplImage. Instead it uses cvIplImage to generate a new one. However, surely that is missing the point: IplImage is deprecated and has been for a while. The removal of the simple assignment is a reflection of this deprecation. For OpenCV4, these declarations still exist but are no longer documented - at least not in the main documentation. The worry is that IplImage will be further deprecated/removed or hidden and this code will be broken.

It would be worth going further and removing the internal use of IplImage at all if cv::Mat is supplied as a parameter. There is a second question as to whether IplImage should be removed from the API - perhaps there could be a build time option to only enable it if required.

**Comment by davisking** [comment]
I don't want to break old code.  You would be surprised how many people run with ancient dependencies.  But if you want to adjust the `cv_image` class so `IplImage` isn't used at all unless the user is using an old version of OpenCV that would be cool with me.
