### ISSUE TITLE
Shows WILL USE CUDA after compile. But returns false for dlib.DLIB_USE_CUDA

### ISSUE THREAD

**Issue by irfanbacker** [davisking/dlib#2072]
Using anaconda

## Expected Behavior
Output of dlib.DLIB_USE_CUDA should be True, indicating usage of GPU

## Current Behavior
Output of dlib.DLIB_USE_CUDA is False. Also GPU is never used by the library.

*compile output:*
-- Using CMake version: 3.16.3
-- Compiling dlib version: 19.19.99
-- Enabling AVX instructions
-- Found system copy of libpng: /usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so
-- Found system copy of libjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found LAPACK library
-- Found BLAS library
-- Looking for cuDNN install...
-- Found cuDNN: /usr/lib/cuda/lib64/libcudnn.so
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/irfan/dlib-master/build

*setup output:*
running install
running bdist_egg
running egg_info
writing dlib.egg-info/PKG-INFO
writing dependency_links to dlib.egg-info/dependency_links.txt
writing top-level names to dlib.egg-info/top_level.txt
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools/python/build*'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
Invoking CMake setup: 'cmake /home/irfan/dlib-master/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/irfan/dlib-master/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/home/irfan/anaconda3/envs/CV/bin/python3 -DCMAKE_BUILD_TYPE=Release'
-- pybind11 v2.2.2
-- Using CMake version: 3.16.3
-- Compiling dlib version: 19.19.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Found system copy of libpng: /usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libz.so
-- Found system copy of libjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found LAPACK library
-- Found BLAS library
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/irfan/dlib-master/build/temp.linux-x86_64-3.8
Invoking CMake build: 'cmake --build . --config Release -- -j8'
[ 68%] Built target dlib
[100%] Built target dlib_python
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.8/dlib.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for dlib.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/dlib.py to dlib.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/dlib-19.19.99-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dlib-19.19.99-py3.8-linux-x86_64.egg
removing '/home/irfan/anaconda3/envs/CV/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg' (and everything under it)
creating /home/irfan/anaconda3/envs/CV/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg
Extracting dlib-19.19.99-py3.8-linux-x86_64.egg to /home/irfan/anaconda3/envs/CV/lib/python3.8/site-packages
dlib 19.19.99 is already the active version in easy-install.pth

Installed /home/irfan/anaconda3/envs/CV/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg
Processing dependencies for dlib==19.19.99

## Steps to Reproduce
1 - cmake  -D CMAKE_PREFIX_PATH=/usr/lib/cuda/ -D DLIB_USE_CUDA=1 -D USE_AVX_INSTRUCTIONS=1 ..

2 - cd ..

3 - python3 setup.py install

* **Version**: 19.19.99
* **Where did you get dlib**: github repo
* **Platform**: ubuntu 20.04 64-bit
* **Compiler**: gcc-7, g++-7

**Comment by Steph71** [comment]
From your log:

"dlib 19.19.99 is already the active version in easy-install.pth"

I think indicates, that the dlib version you just built is allready installed (likely a non cuda build)
and as it its allready there it will not be overwritten ...

try:

`pip uninstall dlib`

and then 

`python3 setup.py install`

**Comment by irfanbacker** [comment]
> From your log:
> 
> "dlib 19.19.99 is already the active version in easy-install.pth"
> 
> I think indicates, that the dlib version you just built is allready installed (likely a non cuda build)
> and as it its allready there it will not be overwritten ...
> 
> try:
> 
> `pip uninstall dlib`
> 
> and then
> 
> `python3 setup.py install`

So how do I uninstall the dlib installation that I just built?
