### ISSUE TITLE
dlib' has no attribute 'grow_rect'

### ISSUE THREAD

**Issue by Blackwolf23** [davisking/dlib#2075]
After my dlib frontal face detector detects faces it returns a list of rectangles of faces. All I wanted to is increase the rectangle by a bit so it included the hair and neck etc... But when I try to use the function described in the python docks I get the following error. I tried reinstalling it with no success.

## Expected Behavior
The expected function "dlib.grow_rect(rect,100) should grow the rectangle by 100

## Current Behavior
When using "dlib.grow_rect()"
I get the error "Exception has occurred: AttributeError
module 'dlib' has no attribute 'grow_rect' "
When using just "grow_rect()" 
I get the error "Exception has occurred: NameError
name 'grow_rect' is not defined"
When I used "'rect2.grow_rect(rect,100)
I get the error "'rectangle' object has no attribute 'grow_rect'"

## Steps to Reproduce
Create a simple rect object "rect= dlib.rectangle(78, 78, 185, 185)" (constructor works fine) and then
try to grow it.

* **Version**: <19.7.0>
* **Where did you get dlib**: <pip install https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl#md5=b7330a5b2d46420343fbed5df69e6a3f>

* **Platform**: < Win 10 64 bit >
* **Compiler**: <--Python 3.6.4 64 bit visual studio code environment -->

**Comment by davisking** [comment]
You are using a really old version of dlib.

**Comment by Blackwolf23** [comment]
> You are using a really old version of dlib.

I Fixed it by hard-coding rect growth on my won, it ain't pretty but it works.
So I assume that grow_rect isn't part of my dlib package? I Only have this package because I get a dlib installation error when using pip
