### ISSUE TITLE
Am I using the alias_tensor correctly?

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2077]
Hi, here's my use case: I have a tensor (num_samples, k, nr, nc) and I would like to apply a sigmoid only to the the first channel (k == 0) of all tensors, so here's what I did in a custom loss layer:

```cpp
// get the output from the network
const tensor& output_tensor = sub.get_output();
// the gradient that I need to fill
tensor& grad = sub.get_gradient_input();
float* g = grad.host()


// alias a subset of the output_tensor (basically only one channel)
alias_tensor sub_tensor(output_tensor.num_samples(), 1, output_tensor.nr(), output_tensor.nc());
// get a const instance of the sub_tensor with 0 offset with regards the output_tensor
auto const_sub_tensor = sub_tensor(output_tensor, 0);
resizable_tensor helper_tensor(sub_tensor.num_samples, sub_tensor.k(), sub_tensor.nr(), sub_tensor.nc());
// apply the sigmoid to the subset tensor and store the result in helper_tensor
tt::sigmoid(helper_tensor, const_sub_tensor);
float* helper_data = helper_tensor.host();
const float* sub_data = const_sub_tensor.get().host();

for (long i = 0; i < output_tensor.num_samples(); ++i, ++truth)
{
    for (long r = 0; r < output_tensor.nr(); ++r)
    {
        for (long c = 0; c < output_tensor.nc(); ++c)
        {
            const size_t idx = tensor_index(output_tensor, i, 0, r, c);
            const size_t sub_idx = tensor_index(const_sub_tensor, i, 0, r, c);
            // then I assume these two values should be the same, because I need the value of helper_data[sub_idx] to update g[idx].
            std::cout << idx << " => " sub_idx << ", " << out_data[idx] << " == " << sub_data[sub_idx] << '\n';
        }
    }
}
```

where `tensor_index` is:
``` cpp
static size_t tensor_index(const tensor& t, long sample, long k, long row, long column)
{
    return ((sample * t.k() + k) * t.nr() + row) * t.nc() + column;
}
```

The problem is that `out_data[idx]` and `sub_data[sub_idx]` are only equal for `i == 0`, that is, the first sample. So I am certainly missing something, but I have read the documentation and, from what I understood, this was the expected behavior.

So my question is: what am I doing wrong?

Thanks in advance :)

EDIT: small example, for a tensor of 4x7x19x19

`idx` and `sub_idx` from 0 to 360 yield the same results for `out_data[idx]` and `sub_data[sub_idx]` (this corresponds to `k == 0` for the first sample (`i == 0`).

However the outputs are different for the second sample (`i == 1`),
`idx` jumps from `360` to `2527` (`19 * 19 * 7`) and `sub_idx` continues to `361`, as I expected, but the values of `out_data[idx]` and `sub_data[sub_idx]` are different from this point on.

**Comment by arrufat** [comment]
Some updates, I know how to get the behavior I expect from `alias_tensor` by doing it manually, so I replaced this:

``` cpp
// alias a subset of the output_tensor (basically only one channel)
alias_tensor sub_tensor(output_tensor.num_samples(), 1, output_tensor.nr(), output_tensor.nc());
// get a const instance of the sub_tensor with 0 offset with regards the output_tensor
auto const_sub_tensor = sub_tensor(output_tensor, 0);
tt::sigmoid(helper_tensor, const_sub_tensor);
float* helper_data = helper_tensor.host();
const float* sub_data = const_sub_tensor.get().host();
```

with this:
``` cpp
resizable_tensor sub_tensor(output_tensor.num_samples(), 1, output_tensor.nr(), output_tensor.nc());
helper_tensor.copy_size(sub_tensor);
float* sub_data = sub_tensor.host();
int sub_idx = 0;
for (long i = 0; i < output_tensor.num_samples(); ++i)
{
    for (long r = 0; r < output_tensor.nr(); ++r)
    {
        for (long c = 0; c < output_tensor.nc(); ++c)
        {
            const size_t idx = tensor_index(output_tensor, i, 0, r, c);
            sub_data[sub_idx++] = out_data[idx];
        }
    }
}
sub_tensor.device();
tt::sigmoid(helper_tensor, sub_tensor);
float* helper_data = helper_tensor.host();
```

But I'm guessing it's not very efficient because of the data transfer and all.

**Comment by davisking** [comment]
You are asking to make a non-contiguous view into the original tensor's memory.  But `alias_tensor` doesn't do that, since it yields only a new `tensor`, and `tensor` objects in dlib always reference contiguous memory blocks (since they just give you a pointer to memory and you do whatever you want with it).

**Comment by arrufat** [comment]
Ok, I see thank you. I'll do it manually, then :)
