### ISSUE TITLE
FPS is slow even when cuda is enabled

### ISSUE THREAD

**Issue by hiroyuki-s1** [davisking/dlib#2078]
FPS is slow even when cuda is enabled

environment
Ubuntu18.04.
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

I tried to install DLIB with CUDA enabled using the following steps.

git clone https://github.com/davisking/dlib
python3 setup.py install --set CUDA_HOST_COMPILER=/usr/bin/gcc-6 --set USE_AVX_INSTRUCTIONS=yes --set DLIB_USE_CUDA=yes

However, despite CUDA being enabled, FPS is slow
I checked the GPU load on nvidia-smi, but there's no sign that dlib is using the GPU
 dlib.DLIB_USE_CUDA was set to true.
What can I do?

**Comment by eddynelson** [comment]
Same isssue! I installed dlib with the same command and downloads the lasted release source code. We grateful for any help.

**Comment by davisking** [comment]
Neither of you said what you are doing with dlib or what parts of dlib you are using.  So no one can answer.  Maybe you aren't even using things that use CUDA.

**Comment by rayjan0114** [comment]
Same issue here!
I install dlib as below:
![image](https://user-images.githubusercontent.com/47523852/83988905-43af8480-a977-11ea-9c4c-ced573bf0bcc.png)

Which would always work before.

And the model I use:
![image](https://user-images.githubusercontent.com/47523852/83988825-0b0fab00-a977-11ea-9e53-fcdb0c6a04cd.png)

But now, the model is running super slow
Even though I try these following steps and still fail:
1. make sure my docker environment does recognize cuda:
   print(dlib.cuda.get_num_devices())  ==>  1 
   print(dlib.DLIB_USE_CUDA) ==> False

2. force to enable cuda:
   dlib.DLIB_USE_CUDA = True

3. make sure is the same version as I did work out before:
    git checkout 579a41d5
