### ISSUE TITLE
How to initialize a the bias vector on a fc DNN layer?

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#208]
I've had some success in implementing a RNN over dlib's DNN framework (I expect to publish it soon), but to correctly implement an LSTM, I need the bias of forget gate set initially to a large value (as [this paper](http://jmlr.org/proceedings/papers/v37/jozefowicz15.pdf) says on section 2.2), otherwise the LSTM loses its power to track large time dependencies. In dlib's terms, this an `fc<>`. Is there an easy way to set how this value will be initialized?

**Comment by davisking** [comment]
You can't do that with the existing fc_ layer.  I would just add a new
field to that class that lets you do what you want to do.  Or make a copy
of the class and edit it to work like you need.
