### ISSUE TITLE
How-to change the number of classes?

### ISSUE THREAD

**Issue by ilChelo** [davisking/dlib#2081]
Yes, I know, really close to "Why can't I change the network architecture at runtime?", the very first Deep Learning question in FAQ section... but I'm asking some help as well. I think DLIB is great to quiclky develop tools for classification: today digits, tomorrow letters or shapes. But today 10 classes, tomorrow 24 or whatelse. I really need to have a parametrized number of classes because I want to release just one tool. That said, far from asking to change anything in DLIB architecture, could someone give me some hints (links, literature, tutorials) about those "_compile time constructs in C++ you can use to enumerate network architectures (e.g. loop over filter widths) if you really wanted to do so_."? Thank you very much.

Michele.

**Comment by arrufat** [comment]
You can change the number of classes at runtime, so long as you haven't allocated the tensor to the corresponding layers (which I am guessing that they most likely are `fc` or `con`.
Let me give you an example:
https://github.com/davisking/dlib/blob/c7062aa3631ba4912255a9bcc0563d404d3bdd5d/examples/dnn_introduction_ex.cpp#L71-L78

You can change the number of outputs of the `fc` layer by doing:
``` cpp
long num_outputs = 42;
net_type net;
net.subnet().layer_details().set_num_outputs(42);
```
The same goes for `con` layers, there's even an example that does it:
https://github.com/davisking/dlib/blob/c7062aa3631ba4912255a9bcc0563d404d3bdd5d/examples/dnn_mmod_train_find_cars_ex.cpp#L283

And, if you are loading a pretrained network, this example shows how to do it:
https://github.com/davisking/dlib/blob/c7062aa3631ba4912255a9bcc0563d404d3bdd5d/examples/dnn_introduction3_ex.cpp#L76-L96

I hope this is helpful.

**Comment by ilChelo** [comment]
Thank you @arrufat, quick and neat... shame on me, it was so simple...

**Comment by arrufat** [comment]
@ilChelo, great! Feel free to close the issue if you don't have any more questions.

**Comment by ilChelo** [comment]
Bye!
