### ISSUE TITLE
Feature request: bridge : multiple subscribers

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2083]
I really like the API for IPC using ```dlib::bridge``` and ```dlib::pipe```.
What would be nice is if a listening bridge could have multiple connections. So rather than having a 1 to 1 bridge, you could have a 1 to many bridge. This would allow for a subscription model whereby connected clients could all receive the same items and do their own thing.

**Comment by davisking** [comment]
Yeah, that would be cool.  You should submit a PR that adds that :)

**Comment by pfeatherstone** [comment]
Fair enough :)

**Comment by pfeatherstone** [comment]
So i haven't had time to properly familiarize myself with your entire networking stack. So i've implemented this using my own async networking tools (that support TCP, UNIX domain socket, SCTP, ENET, UDT and TLS on top of all them). It would have taken me longer to properly use your own tools, add UNIX domain sockets, TLS, ... and get this working right. I'm part of a fast prototyping team and unfortunately we run a tight ship so i thought i would save time and use what i know well. So I won't submit a PR since it's no use polluting the dlib library with outside tools if they don't need it. So it's up to you if you want to close the issue. I think it would be good to keep it open so others can see the suggested enhancement and properly implement it if they have time.
