### ISSUE TITLE
dlib examples compilation problem: error: conversion from ‘const cv::Mat’ to non-scalar type ‘IplImage’ {aka ‘_IplImage’} requested

### ISSUE THREAD

**Issue by marcoippolito** [davisking/dlib#2084]
I downloaded from here http://dlib.net/compile.html the dlib version 19.19 in Ubuntu 18.04.4 Desktop,
gcc version 9.3.0 (Ubuntu 9.3.0-11ubuntu0~18.04.1)

Following the indications found in README. txt
I tried to compile the examples:

    (base) marco@pc01:~/cpp/dlib/dlib-19.19/examples/build$ cmake ..  
    -DUSE_AVX_INSTRUCTIONS=1
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Using CMake version: 3.16.5
    -- Compiling dlib version: 19.19.0
    -- Enabling AVX instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Found X11: /usr/include   
    -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-
    gnu/libXext.so
    -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-
    gnu/libXext.so - found
    -- Looking for gethostbyname
    -- Looking for gethostbyname - found
    -- Looking for connect
    -- Looking for connect - found
    -- Looking for remove
    -- Looking for remove - found
    -- Looking for shmat
    -- Looking for shmat - found
    -- Looking for IceConnectionNumber in ICE
    -- Looking for IceConnectionNumber in ICE - found
    -- Found system copy of libpng: /usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-
    gnu/libz.so
    -- Found system copy of libjpeg: /usr/lib/x86_64-linux-gnu/libjpeg.so
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for module 'lapack'
    --   Found lapack, version 0.2.20+ds
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Found Intel MKL BLAS/LAPACK library
    -- Looking for sgesv
    -- Looking for sgesv - found
    -- Looking for sgesv_
    -- Looking for sgesv_ - found
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE 
    CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
    -- DID NOT FIND CUDA
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/cpp/dlib/dlib-19.19/examples/build

    (base) marco@pc01:~/cpp/dlib/dlib-19.19/examples/build$ cmake --build .
    Scanning dependencies of target dlib
    [  0%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
    [  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    [  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
    [  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
   [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder 
    /entropy_decoder_kernel_1.cpp.o
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder 
    /entropy_decoder_kernel_2.cpp.o
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder 
    /entropy_encoder_kernel_1.cpp.o
    [  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder
    /entropy_encoder_kernel_2.cpp.o
    [  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
    [  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
    [  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
    [  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/global_optimization
    /global_function_search.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/filtering/kalman_filter.cpp.o
    [  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/test_for_odr_violations.cpp.o
    [  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/svm/auto.cpp.o
    [  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
    [  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
    [  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
    [  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
    [  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
    [  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
    [  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
    [  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
    [ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
    [ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
    [ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
    [ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
    [ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
    [ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
    [ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf
    /sockstreambuf_unbuffered.cpp.o 
    [ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
    [ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
    [ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
    [ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads
    /multithreaded_object_extension.cpp.o
    [ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads
    /threaded_object_extension.cpp.o
    [ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
    [ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
    [ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
    [ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
    [ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/cpu_dlib.cpp.o
    [ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/tensor_tools.cpp.o
    [ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
    [ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/widgets.cpp.o
    [ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/drawable.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/style.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/base_widgets.cpp.o
    [ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.cpp.o
    [ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.cpp.o
    [ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
    [ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
    [ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
    [ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
    [ 22%] Linking CXX static library libdlib.a
    [ 22%] Built target dlib
    Scanning dependencies of target train_object_detector
    [ 22%] Building CXX object CMakeFiles/train_object_detector.dir/train_object_detector.cpp.o
    [ 23%] Linking CXX executable train_object_detector
    [ 23%] Built target train_object_detector 
    Scanning dependencies of target threads_ex
     [24%] Building CXX object CMakeFiles/threads_ex.dir/threads_ex.cpp.o
    [ 24%] Linking CXX executable threads_ex
    [ 24%] Built target threads_ex
    Scanning dependencies of target threaded_object_ex
    [ 24%] Building CXX object CMakeFiles/threaded_object_ex.dir/threaded_object_ex.cpp.o
    [ 24%] Linking CXX executable threaded_object_ex
    [ 24%] Built target threaded_object_ex
    Scanning dependencies of target thread_pool_ex
    [ 24%] Building CXX object CMakeFiles/thread_pool_ex.dir/thread_pool_ex.cpp.o
    [ 25%] Linking CXX executable thread_pool_ex
    [ 25%] Built target thread_pool_ex
    Scanning dependencies of target svm_c_ex
    [ 25%] Building CXX object CMakeFiles/svm_c_ex.dir/svm_c_ex.cpp.o
    [ 26%] Linking CXX executable svm_c_ex
    [ 26%] Built target svm_c_ex
    Scanning dependencies of target std_allocator_ex
    [ 27%] Building CXX object CMakeFiles/std_allocator_ex.dir/std_allocator_ex.cpp.o
    [ 27%] Linking CXX executable std_allocator_ex
    [ 27%] Built target std_allocator_ex
    Scanning dependencies of target sockstreambuf_ex
    [ 27%] Building CXX object CMakeFiles/sockstreambuf_ex.dir/sockstreambuf_ex.cpp.o
    [ 28%] Linking CXX executable sockstreambuf_ex
    [ 28%] Built target sockstreambuf_ex
    Scanning dependencies of target sockets_ex
    [ 29%] Building CXX object CMakeFiles/sockets_ex.dir/sockets_ex.cpp.o
    [ 29%] Linking CXX executable sockets_ex
    [ 29%] Built target sockets_ex
    Scanning dependencies of target server_iostream_ex
    [ 30%] Building CXX object CMakeFiles/server_iostream_ex.dir/server_iostream_ex.cpp.o
    [ 30%] Linking CXX executable server_iostream_ex
    [ 30%] Built target server_iostream_ex
    Scanning dependencies of target server_http_ex
    [ 30%] Building CXX object CMakeFiles/server_http_ex.dir/server_http_ex.cpp.o
    [ 30%] Linking CXX executable server_http_ex
    [ 30%] Built target server_http_ex
    Scanning dependencies of target sequence_labeler_ex
    [ 31%] Building CXX object CMakeFiles/sequence_labeler_ex.dir/sequence_labeler_ex.cpp.o
    [ 31%] Linking CXX executable sequence_labeler_ex
    [ 31%] Built target sequence_labeler_ex
    Scanning dependencies of target rvm_regression_ex
    [ 32%] Building CXX object CMakeFiles/rvm_regression_ex.dir/rvm_regression_ex.cpp.o
    [ 32%] Linking CXX executable rvm_regression_ex
    [ 32%] Built target rvm_regression_ex
    Scanning dependencies of target rank_features_ex
    [ 32%] Building CXX object CMakeFiles/rank_features_ex.dir/rank_features_ex.cpp.o
    [ 33%] Linking CXX executable rank_features_ex
    [ 33%] Built target rank_features_ex
    Scanning dependencies of target pipe_ex_2
    [ 33%] Building CXX object CMakeFiles/pipe_ex_2.dir/pipe_ex_2.cpp.o
    [ 34%] Linking CXX executable pipe_ex_2
    [ 34%] Built target pipe_ex_2
    Scanning dependencies of target quantum_computing_ex
    [ 34%] Building CXX object CMakeFiles/quantum_computing_ex.dir/quantum_computing_ex.cpp.o
    [ 35%] Linking CXX executable quantum_computing_ex
    [ 35%] Built target quantum_computing_ex
    Scanning dependencies of target pipe_ex
    [ 36%] Building CXX object CMakeFiles/pipe_ex.dir/pipe_ex.cpp.o
    [ 36%] Linking CXX executable pipe_ex
    [ 36%] Built target pipe_ex
    Scanning dependencies of target train_shape_predictor_ex
    [ 36%] Building CXX object CMakeFiles/train_shape_predictor_ex.dir
    /train_shape_predictor_ex.cpp.o
    [ 36%] Linking CXX executable train_shape_predictor_ex
    [ 36%] Built target train_shape_predictor_ex
    Scanning dependencies of target optimization_ex
    [ 36%] Building CXX object CMakeFiles/optimization_ex.dir/optimization_ex.cpp.o
    [ 37%] Linking CXX executable optimization_ex
    [ 37%] Built target optimization_ex 
    Scanning dependencies of target one_class_classifiers_ex
    [ 37%] Building CXX object CMakeFiles/one_class_classifiers_ex.dir
    /one_class_classifiers_ex.cpp.o
    [ 38%] Linking CXX executable one_class_classifiers_ex
    [ 38%] Built target one_class_classifiers_ex
    Scanning dependencies of target object_detector_ex
    [ 39%] Building CXX object CMakeFiles/object_detector_ex.dir/object_detector_ex.cpp.o
    [ 39%] Linking CXX executable object_detector_ex
    [ 39%] Built target object_detector_ex
    Scanning dependencies of target sequence_segmenter_ex
    [ 39%] Building CXX object CMakeFiles/sequence_segmenter_ex.dir
    /sequence_segmenter_ex.cpp.o
    [ 40%] Linking CXX executable sequence_segmenter_ex
    [ 40%] Built target sequence_segmenter_ex
    Scanning dependencies of target object_detector_advanced_ex
    [ 40%] Building CXX object CMakeFiles/object_detector_advanced_ex.dir
    /object_detector_advanced_ex.cpp.o
    [ 40%] Linking CXX executable object_detector_advanced_ex
    [ 40%] Built target object_detector_advanced_ex
    Scanning dependencies of target svm_rank_ex
    [ 41%] Building CXX object CMakeFiles/svm_rank_ex.dir/svm_rank_ex.cpp.o
    [ 41%] Linking CXX executable svm_rank_ex
    [ 41%] Built target svm_rank_ex
    Scanning dependencies of target mpc_ex
    [ 42%] Building CXX object CMakeFiles/mpc_ex.dir/mpc_ex.cpp.o
    [ 42%] Linking CXX executable mpc_ex
    [ 42%] Built target mpc_ex
    Scanning dependencies of target model_selection_ex
    [ 42%] Building CXX object CMakeFiles/model_selection_ex.dir/model_selection_ex.cpp.o
    [ 42%] Linking CXX executable model_selection_ex
    [ 42%] Built target model_selection_ex
    Scanning dependencies of target bayes_net_gui_ex
    [ 42%] Building CXX object CMakeFiles/bayes_net_gui_ex.dir/bayes_net_gui_ex.cpp.o
    [ 42%] Linking CXX executable bayes_net_gui_ex
    [ 42%] Built target bayes_net_gui_ex
    Scanning dependencies of target kkmeans_ex
    [ 43%] Building CXX object CMakeFiles/kkmeans_ex.dir/kkmeans_ex.cpp.o
    [ 43%] Linking CXX executable kkmeans_ex
    [ 43%] Built target kkmeans_ex
    Scanning dependencies of target svm_sparse_ex
    [ 43%] Building CXX object CMakeFiles/svm_sparse_ex.dir/svm_sparse_ex.cpp.o
    [ 44%] Linking CXX executable svm_sparse_ex
    [ 44%] Built target svm_sparse_ex
    Scanning dependencies of target 3d_point_cloud_ex
    [ 44%] Building CXX object CMakeFiles/3d_point_cloud_ex.dir/3d_point_cloud_ex.cpp.o
    [ 44%] Linking CXX executable 3d_point_cloud_ex
    [ 44%] Built target 3d_point_cloud_ex
    Scanning dependencies of target bsp_ex
    [ 44%] Building CXX object CMakeFiles/bsp_ex.dir/bsp_ex.cpp.o
    [ 45%] Linking CXX executable bsp_ex
    [ 45%] Built target bsp_ex
    Scanning dependencies of target svm_ex
    [ 45%] Building CXX object CMakeFiles/svm_ex.dir/svm_ex.cpp.o
    [ 45%] Linking CXX executable svm_ex
    [ 45%] Built target svm_ex
    Scanning dependencies of target logger_ex
    [ 46%] Building CXX object CMakeFiles/logger_ex.dir/logger_ex.cpp.o
    [ 46%] Linking CXX executable logger_ex
    [ 46%] Built target logger_ex
    Scanning dependencies of target svm_struct_ex
    [ 46%] Building CXX object CMakeFiles/svm_struct_ex.dir/svm_struct_ex.cpp.o
    [ 46%] Linking CXX executable svm_struct_ex
    [ 46%] Built target svm_struct_ex
    Scanning dependencies of target webcam_face_pose_ex
    [ 46%] Building CXX object CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o
    In file included from /home/marco/cpp/dlib/dlib-19.19/dlib/../dlib/opencv.h:10,
                     from /home/marco/cpp/dlib/dlib-19.19/examples/webcam_face_pose_ex.cpp:30:
    /home/marco/cpp/dlib/dlib-19.19/dlib/../dlib/opencv/cv_image.h: In instantiation of   
    ‘dlib::cv_image<pixel_type>::cv_image(cv::Mat) [with pixel_type = dlib::bgr_pixel]’:
    /home/marco/cpp/dlib/dlib-19.19/examples/webcam_face_pose_ex.cpp:73:42:   required from here
    /home/marco/cpp/dlib/dlib-19.19/dlib/../dlib/opencv/cv_image.h:37:29: error: conversion from    
    ‘const cv::Mat’ to non-scalar type ‘IplImage’ {aka ‘_IplImage’} requested
       37 |             IplImage temp = img;
          |                             ^~~
    CMakeFiles/webcam_face_pose_ex.dir/build.make:62: recipe for target     
    'CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o' failed 
    make[2]: *** [CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o] Error 1
    CMakeFiles/Makefile2:1190: recipe for target 'CMakeFiles/webcam_face_pose_ex.dir/all' failed
    make[1]: *** [CMakeFiles/webcam_face_pose_ex.dir/all] Error 2 
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

How to solve the problem?

Marco

**Comment by davisking** [comment]
This issue is fixed in the latest dlib master on github.  So if you grab that it should work.

**Comment by marcoippolito** [comment]
Yes. With the latest dlib master on github it seems ok. Thank you
