### ISSUE TITLE
 code: 13, reason: A call to cuBLAS failed

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#2085]
ubuntu 18.04
Quatro 5000 Nviidia 
latest dlib 

I have below error when I try to run dnn_face_recognition or any gpu related test .:

> Error while calling cublasSgemm(context(), transb, transa, dest_nc, dest_nr, k, &alpha, rhs.device(), rhs_nc, lhs.device(), lhs_nc, &beta, dest.device(),dest_nc) in file /home/bc/Projects/dlib/dlib/cuda/cublas_dlibapi.cpp:152. code: 13, reason: A call to cuBLAS failed

any idea ?

**Comment by MyraBaba** [comment]
ANSWER:

When I compile dlib as a shared library instead of static one it's working now. 

I think we should compile as shared lib when we have gpu .

**Comment by MyraBaba** [comment]
found the answer.

**Comment by quang-sudo** [comment]
Hello @MyraBaba  
Could you tell us how to compile as shared lib?

**Comment by MyraBaba** [comment]
@quang-sudo  really long time ago :) when compiled share its loading GPU driver as needed.

I assume it was. 

cmake -DBUILD_SHARED_LIBS=1 ..
