### ISSUE TITLE
interpolate_bilinear makes lab_pixel as grayscale

### ISSUE THREAD

**Issue by stoperro** [davisking/dlib#2089]
## Expected Behavior
`interpolate_bilinear` should either somehow interpolate `lab_pixel` images, or explicitly fail with descriptive feedback.
While inconvenient, I'm ok with having to convert to `rgb_pixel` before passing to `extract_image_chips()`, though lack of error makes it long to pinpoint the issue...

## Current Behavior
Trying to use images using `lab_pixel`s with `interpolate_bilinear` will cause resulting image to be completely desaturated. The image type will be correct, just all chroma values will be set to 128, with only lighting changes. `interpolate_quadratic` seems to have same pitfall.
`interpolate_bilinear` has two SFINAE overloads checking for RGB or not (=Grayscale). LAB has neither in traits and falls into Grayscale. In theory, checking for 3 channels could work for LAB and interpolating as if it was RGB, although I don't know how chroma (AB) behaves on boundaries when interpolating (my guess is not so great).

## Steps to Reproduce
Use e.g. `extract_image_chips()` on colorful `::dlib::matrix<::dlib::lab_pixel>`. Since `extract_image_chips()` internally interpolates, the color information will be lost.

* **Version**: 19.19
* **Where did you get dlib**: vcpkg
* **Platform**: Windows 10 64-bit
* **Compiler**: MSVC 19.27.28826.0

**Comment by stoperro** [comment]
if ok, I can submit MR with additional `static_assert()` for LAB at least, or just adding support for LAB interpolation if it's reasonably doable.

**Comment by davisking** [comment]
Yeah, a PR that improves this would be awesome.  Either solutions you mentioned would be cool.
