### ISSUE TITLE
Dlib frontal_face_detector not providing consistent detections for the same image and code. 

### ISSUE THREAD

**Issue by Nick-Harvey** [davisking/dlib#2090]
General Summary: 
I'm 98% certain this has to do with my code, but since it's heavily inspired by the dlib example code and I couldn't find any similar issues on GitHub or StackOverflow, so thought I'd open an issue here. Anyhow, for some reason that I can't explain, the `frontal_face_detector()` behaves inconsistently. Using the same image, with the same block of code, dlib will sometimes will pick up the face and other times it won't. So far it seems to be completely random, but again it's probably something I'm overlooking in the code. 

I've tried to eliminate every bit of deterministic code I can think and I've stripped it down to the block below. 

```
import cv2
import dlib
import os
import numpy as np

video = cv2.VideoCapture('./5s_sample.mp4')

def detect_faces(success, frame):
    """Detect faces in a frame."""    
    # Resize the frame
    #frame = imutils.resize(frame, width=400)
    if success:
        # Convert frame to gray and then Use dlib HOG front face detector
        # Note: The dlib CNN version will give more accurate results,
        # but will require more resources aka GPU 
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        detector = dlib.get_frontal_face_detector()
        detections = detector(gray)
        
        faces = []
        if len(detections) > 0:
            for d in detections:
                try:
                    l, t, r, b = d.left(), d.top(), d.right(), d.bottom()
                    l *= 2
                    t *= 2
                    r *= 2
                    b *= 2
                    w, h = r - l, b - t
                    cv2.rectangle(frame, (l,t), (l+w,t+h), (0,255,0), 2)

                except TypeError:
                    print(type(self.frame), self.frame)
                faces.append((l, t, w, h))

            faces.sort(key=lambda bbox: bbox[0])
            processed_frame['faces'] = faces

success, frame = video.read()
detect_faces(success, frame)
print(processed_frame)
```

**Env:** 

- Python 3.8.2
- Dlib 19.19.0 (installed via pip)
- Mac 10.15
- OpenCV 4.2.0.34

## Expected Behavior

The expected output is the face coordinates, but that only happens 1 out of 10 tries or so. Dlib details and how it's being used are posted in the code above. 

## Current Behavior

The current behavior is just inconsistent detections for the same image. There aren't any errors and the frame data is, in fact, making it to the detector which I think eliminates opencv (but again I could be wrong). The video itself is PII so I can't share it exactly but here's the stream information. 

```
Duration: 00:00:05.08, start: 0.000000, bitrate: 1568 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 808x720 [SAR 8:9 DAR 404:405], 1578 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 180k tbc (default)
```
The image really just is close up of a person talking where the front face is 95% of the image (no pre-processing). 
   
## Steps to Reproduce

The code posted above combined with my env details should reproduce the issue.  

* **Version**: 
19.19.0
* **Where did you get dlib**: 
pip3 install dlib

* **Platform**: 
macosx 10.15.4

* **Compiler**: 
3.8.2 (default, Mar 11 2020, 00:29:30) 
[Clang 10.0.0 (clang-1000.11.45.5)]

**Comment by davisking** [comment]
I bet the same image isn't really being passed in.   You should log the
image and check that it's actually the same.

**Comment by Nick-Harvey** [comment]
Thanks for the quick reply. You were correct, after switching to an FFmpeg stream and confirm the order of the frames, things worked perfectly.
