### ISSUE TITLE
dlib release 19.19 doesn't work with opencv-4.3.0

### ISSUE THREAD

**Issue by janakg** [davisking/dlib#2092]
thanks for this amazing library. 

Are you planning for a release to support opencv 4.3.0?

Right now we are building the master to resolve the same.
https://github.com/davisking/dlib/issues/1949

**Comment by davisking** [comment]
Yeah, I've been meaning to tag a new dlib release for a while.  Just made v19.20 official.

**Comment by janakg** [comment]
thanks @davisking
