### ISSUE TITLE
issue while installing it in ubuntu server

### ISSUE THREAD

**Issue by Tamanbir** [davisking/dlib#2094]
while installing dlib it to the ubuntu server i am getting the following error after 85% is completed

**pp:4:
/home/ubuntu/uwsgi-identino/dlib/dlib/external/pybind11/include/pybind11/pybind1     1.h:1831:47: warning: ‘int PyThread_set_key_value(int, void*)’ is deprecated [-W     deprecated-declarations]
 1831 |             PyThread_set_key_value(key, tstate);
      |                                               ^
In file included from /usr/include/python3.8/pystate.h:10,
                 from /usr/include/python3.8/genobject.h:11,
                 from /usr/include/python3.8/Python.h:121,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/external/pybind11/in     clude/pybind11/detail/common.h:111,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/external/pybind11/in     clude/pybind11/pytypes.h:12,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/external/pybind11/in     clude/pybind11/cast.h:13,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/external/pybind11/in     clude/pybind11/attr.h:13,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/external/pybind11/in     clude/pybind11/pybind11.h:43,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/../dlib/python/pybin     d_utils.h:6,
                 from /home/ubuntu/uwsgi-identino/dlib/dlib/../dlib/python.h:6,
                 from /home/ubuntu/uwsgi-identino/dlib/tools/python/src/opaque_t     ypes.h:6,
                 from /home/ubuntu/uwsgi-identino/dlib/tools/python/src/vector.c     pp:4:
/usr/include/python3.8/pythread.h:102:36: note: declared here
  102 | Py_DEPRECATED(3.7) PyAPI_FUNC(int) PyThread_set_key_value(int key,
      |                                    ^~~~~~~~~~~~~~~~~~~~~~**

![image](https://user-images.githubusercontent.com/10224304/83981685-bbf95400-a93d-11ea-8277-da6ac6a8df1f.png)

**Comment by davisking** [comment]
That looks like a warning, not an error.

**Comment by rafale77** [comment]
This is a python version deprecation warning. Look here

https://github.com/davisking/dlib/issues/2055
