### ISSUE TITLE
dlib-19.20.0 - ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by harshlavingia** [davisking/dlib#2097]
Abstract: I have pip installed dlib ver. 19.20.0 using a recent release on 06/06/2020. I am using Python 3.7.6 (Anaconda) in Windows 10. During importing dlib in my python code, I am getting an ImportError: DLL load failed: The specified module could not be found

 

## Steps to Reproduce

* **Version**: dlib-19.20.0
* **Where did you get dlib**: pip install dlib - https://pypi.org/project/dlib/
* **Platform**: Windows 10 64 bit, Python 3.7.6 (Anaconda), VS 2019 Community
* **Compiler**: 

![image](https://user-images.githubusercontent.com/6963824/84114336-0aabfa00-a9e1-11ea-80dc-1a7f99e2c642.png)

**Comment by harshlavingia** [comment]
I have taken the latest changes from Github and compiled successfully but now I am getting an error as below. - attached screenshot

>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\dlib-19.20.99-py3.7-win-amd64.egg\dlib\__init__.py", line 12, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed: The specified module could not be found.

![image](https://user-images.githubusercontent.com/6963824/84198742-db38d400-aa58-11ea-9ae5-a4e674e3102f.png)

**Comment by davisking** [comment]
This is inside that `dlib/__init__.py` file:
```

try:
    import os
    # On windows you must call os.add_dll_directory() to allow linking to external DLLs.  See
    # https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew.
    os.add_dll_directory(os.path.join(os.environ['CUDA_PATH'], 'bin'))
except (AttributeError,KeyError):
    pass
```

So what is in your `CUDA_PATH` environment variable?  If it isn't pointing to your cuda install folder this isn't going to work.

**Comment by harshlavingia** [comment]
I have installed CUDA 11 and cudnn-10.2 and CMake 3.17.3
CUDA_PATH  environment variable shows "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0"

![image](https://user-images.githubusercontent.com/6963824/84210744-5eb0f000-aa6e-11ea-9c0f-9c46be2a0d38.png)

**Comment by davisking** [comment]
Well, the dlib you built is linking to something that isn't in the dll load directory path.  I don't know how you built dlib (you didn't post the output).  But some DLL is missing.  Maybe you have multiple cuda installs and you built dlib against an older version of cuda, or linked to something else.

**Comment by harshlavingia** [comment]
Thanks for helping me out. I have attached build log of my dlib installation. 

[dlib_installation_log_06_09_2020.txt](https://github.com/davisking/dlib/files/4756754/dlib_installation_log_06_09_2020.txt)

**Comment by davisking** [comment]
I don't see anything surprising.  You don't have to build with cmake when using python by the way, that step does nothing.

Try installing a copy with --no DLIB_USE_CUDA and see if you still get this error.

**Comment by davisking** [comment]
I haven't tried cuda 11 on windows, but I would expect it to most likely work fine.  The issue is apparently that the cuda dll files are not in %CUDA_PATH%/bin.  You need to find out where they are and add that path to dlib/__init__.py.

**Comment by harshlavingia** [comment]
I am able to find and fix the issue. CUDA11 installation wasn't able to add a few of the directories into PATH environment variable. It was truncated due to the max length of 2048 characters. I have removed a few of the unused software paths from PATH value and dlib is working with CUDA 11 now. Thanks for helping me out.

**Comment by RoyiAvital** [comment]
@davisking ,
By the way, on my system the Multi Threaded compilation stuck the system.
I edited the Python Script with `build_args += ['--', '/maxcpucount:1'] ` to use single thread compilation. Then it all worked.

I suggest you set that as default and advanced users will use MT compilation using some flag.

**Comment by LaughingBlue** [comment]
I faced same problem(conda package list shows installation success. Totally same import error message. ) and solved it by removing outdated OpenBLAS build env path then rebuild dlib. Thx for **harshlavingia and davisking**'s solution even it does not work directly for me but helping me notice that there might be some compilation problem even the compilation log info shows all OK.

Hope this helps someone not waste their three hours.

**Comment by siddh2** [comment]
![WhatsApp Image 2020-07-27 at 10 52 25 AM](https://user-images.githubusercontent.com/68075023/88506392-70872c00-cff7-11ea-8f1e-76427f3b079d.jpeg)

when i try to import dlib then I get error
My error
_____________
_____________
ImportError: DLL load while importing dlib: A dynamic link library (DLL) initialization routing failed.


plz help me

**Comment by VasilijKolomiets** [comment]
I have the same problem
Windows10 & Anaconda & VS Code @ CUDA10.1

**Comment by yourkg** [comment]
Thank you. I solved this problem by modifying "Dlib\__ init__. py" in line 16:
`if 'ON' == 'ON':
    add_lib_to_dll_path('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/extras/demo_suite/')
    #add_lib_to_dll_path('CUDA_CUDART_LIBRARY-NOTFOUND')`

**Comment by jrsousa2** [comment]
I have the same error. I can dive into the code and see how to hack it, but was hoping for a more definitive answer on this issue. I'm very frustrated that the most upvoted answer in SE points to a page with a zillion links for downloads. It says it's a missing DLL, but it's impossible to download just that single DLL. If the package has already been installed, and the path is right, what else could be wrong? Here my paths:

CUDAToolkit_ROOT_DIR=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
CUDA_PATH_V11_7=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
CUDNN_INCLUDE_DIR=C:\Program Files\NVIDIA\CUDNN\v9.6\include
CUDNN_LIBRARY=C:\Program Files\NVIDIA\CUDNN\v9.6\lib

Oops, looks like I just found the answer myself, that DLL is here (I will add this path to the path var):

Directory of C:\Program Files\NVIDIA\CUDNN\v9.6\bin\11.8

22/Nov/2024  02:52 AM           265,256 cudnn64_9.dll
22/Nov/2024  02:52 AM       240,827,432 cudnn_adv64_9.dll
22/Nov/2024  02:53 AM         3,981,864 cudnn_cnn64_9.dll
22/Nov/2024  02:53 AM       357,839,912 cudnn_engines_precompiled64_9.dll
22/Nov/2024  02:53 AM        17,743,416 cudnn_engines_runtime_compiled64_9.dll
22/Nov/2024  02:53 AM         2,069,552 cudnn_graph64_9.dll
22/Nov/2024  02:53 AM        45,434,408 cudnn_heuristic64_9.dll
22/Nov/2024  02:53 AM        86,552,632 cudnn_ops64_9.dll
               8 File(s)    754,714,472 bytes
