### ISSUE TITLE
raspberry pi cross build performance

### ISSUE THREAD

**Issue by andres7293** [davisking/dlib#2098]
Hi everyone.

I have different performance in example dnn_face_recognition_ex.cpp using a raspberry pi local compiler and my own cross compiler.

I cross compile the source using:
```bash
INCLUDE=-I/opt/rpi/sysroot/include 
LDFLAGS=-L/opt/rpi/sysroot/lib
arm-linux-gnueabihf-g++ -std=c++11 -O3 -DDLIB_NO_GUI_SUPPORT -DDLIB_JPEG_SUPPORT -DDLIB_USE_BLAS -DDLIB_USE_LAPACK -I.. ${INCLUDE} ${LDFLAGS} ../dlib/all/source.cpp -lpthread -ljpeg -lopenblas -lgfortran dnn_face_recognition_ex.cpp -o dnn_face_recognition_ex_con_blas.out
```

Am I missing some compiler flags?

Thanks

**Comment by davisking** [comment]
You didn't say how you build without the cross compiler.

**Comment by andres7293** [comment]
True, let me explain a little bit.
For dev purposes I am using raspbian. I also built [OpenBLAS](https://github.com/xianyi/OpenBLAS) locally in raspberry pi, and installed in usr directory. This is the command to build locally:

```bash
g++ -std=c++11 -O3 -DDLIB_NO_GUI_SUPPORT -DDLIB_JPEG_SUPPORT -DDLIB_USE_BLAS -DDLIB_USE_LAPACK -I.. ../dlib/all/source.cpp -lpthread -ljpeg -lopenblas -lgfortran dnn_face_recognition_ex.cpp -o dnn_face_recognition_ex_con_blas.out
```

For production I have a raspberry pi hardware running LFS.  I also cross build OpenBLAS. Is in LFS running machine where the performance is slower.
I suspect is a compiler related issue.

**Comment by davisking** [comment]
Yeah, not sure.  Must be something with the cross compiler if you really are using the same switches with both compilers.
