### ISSUE TITLE
Run Imglab and receive an error "Unable to connect to the X display"

### ISSUE THREAD

**Issue by elmtang** [davisking/dlib#21]
I tried to run imglab to label some images, I can create a xml file, but got the following error 
Howards-MacBook-Pro:build tang$ imglab aa.xml
    3 FATAL [1] dlib.gui_core: Unable to connect to the X display.
Failed to initialize X11 resources

My Mac OSX 10.10.3
I used brew to install XQuartz
brew install Caskroom/cask/xquartz

I commented the following lines in the cmakelists.txt
#set (DLIB_NO_GUI_SUPPORT_STR 
   #”Enable this if you don't want to compile any of the dlib GUI code" )

When I built imglab, I had the following config in my cmakecache.txt and not sure if it's right
DLIB_NO_GUI_SUPPORT:BOOL=OFF

Thanks a lot,

**Comment by davisking** [comment]
You have to turn XQuartz on

**Comment by elmtang** [comment]
How? 
Thanks a lot for your promptly reply.

**Comment by davisking** [comment]
It's an app like any other.  There is a XQuartz button on your computer and you click on it.  Then it's on.

**Comment by elmtang** [comment]
Works, many thanks.
I guess my configs were correct, right?

**Comment by davisking** [comment]
If they are working then yes :)
