### ISSUE TITLE
Infinite Loop in find_min_trust_region

### ISSUE THREAD

**Issue by frederikaalund** [davisking/dlib#210]
I have a process running which continuously solves optimization problems with `solve_least_squares_lm`. I noticed that this process stalls seemingly at random with approximately with 12 hours in between (though this varies drastically).

This process runs on an embedded system so debugging is difficult but I managed to track down the culprit by inserting logging statements into dlib. Sometimes, the loop in [`dlib/optimization/optimization_trust_region.h`](https://github.com/davisking/dlib/blob/ca498ac2d214fd679f8c641f90d08fb63cac11f6/dlib/optimization/optimization_trust_region.h#L273) runs indefinitely. The loop in question is

    while(stale_x || stop_strategy.should_continue_search(x, f_value, g))

I use a custom `stop_strategy` which limits the number of iterations to a predefined value (5 in my case). Apparently, this limit is not effectuated. I have a log statement as the first thing inside `should_continue_search`. When the stall occurs, I notice that `should_continue_search` isn't called anymore yet the operations inside the loop are still executed over and over. From that I infer that `stale_x` must be `true` and in turn short-circuiting the expression so that the `stop_strategy` isn't evaluated.

It is easy to track `stale_x` in the code. Inside the loop, it only occurs here

    if (rho > 0)
    {
        x = x + p;
        f_value = new_f_value;
        model.get_derivative_and_hessian(x,g,h);
        stale_x = false;
    }
    else
    {
        stale_x = true;
    }

So it must be that `0 >= rho` indefinitely when the loop never returns. `rho` is defined as

    const type rho = measured_improvement/std::abs(predicted_improvement);

Most likely, `0 >= measured_improvement` (though `predicted_improvement` could be really large as well). Apparently, the solver gets stuck (can't improve further `x` further) and this stalls the entire process.

To me it seems strange that we repeat the loop at all when `x` is stale. Why not simply

    if (0 >= rho)
    {
        break;
    }

and let go of `stale_x` completely? If no improvement could be made in this iteration, how could there be any improvement in the next (assuming that the subproblem solver is a pure function)?

**Comment by davisking** [comment]
You need the stale check to deal with numerical failures in the trust
region sub-problem solver.  They are rare but can happen for some badly
conditioned problems.

If rho <= 0 then this code should be executing over and over:
https://github.com/davisking/dlib/blob/ca498ac2d214fd679f8c641f90d08fb63cac11f6/dlib/optimization/optimization_trust_region.h#L304
which would lead to termination once radius gets small enough.  Which
happens quickly.  But for some reason that doesn't happen on your machine?
Are you sure the initial radius isn't zero?

**Comment by frederikaalund** [comment]
Thanks for the quick reply!

I have log statements as follows:

    <<LOG Start of loop>>

    while(stale_x || stop_strategy.should_continue_search(x, f_value, g))
    {
        <<LOG Start of subproblem>>
        const unsigned long iter = solve_trust_region_subproblem(h,
                                                                 g,
                                                                 radius,
                                                                 p, 
                                                                 0.1, 
                                                                 20);
        <<LOG End of subproblem>>


        const type new_f_value = model(x+p);
        const type predicted_improvement = -0.5*trans(p)*h*p - trans(g)*p;
        const type measured_improvement = (f_value - new_f_value);

        // If the sub-problem can't find a way to improve then stop.  This only happens when p is essentially 0.
        if (std::abs(predicted_improvement) <= std::abs(measured_improvement)*std::numeric_limits<type>::epsilon())
            break;

        // predicted_improvement shouldn't be negative but it might be if something went
        // wrong in the trust region solver.  So put abs() here to guard against that.  This
        // way the sign of rho is determined only by the sign of measured_improvement.
        const type rho = measured_improvement/std::abs(predicted_improvement);


        
        if (rho < 0.25)
        {
            radius *= 0.25;

            // something has gone horribly wrong if the radius has shrunk to zero.  So just
            // give up if that happens.
            if (radius <= initial_radius*std::numeric_limits<double>::epsilon())
                break;
        }
        else
        {
            // if rho > 0.75 and we are being checked by the radius 
            if (rho > 0.75 && iter > 1)
            {
                radius = std::min<type>(1000,  2*radius);
            }
        }

        if (rho > 0)
        {
            x = x + p;
            f_value = new_f_value;
            model.get_derivative_and_hessian(x,g,h);
            stale_x = false;
        }
        else
        {
            stale_x = true;
        }

        DLIB_ASSERT(is_finite(x), "The objective function generated non-finite outputs");
        DLIB_ASSERT(is_finite(g), "The objective function generated non-finite outputs");
        DLIB_ASSERT(is_finite(h), "The objective function generated non-finite outputs");
    }

    <<LOG End of loop>>

When the process stalled the last time, the log was as follows:

	Start of loop
	stop_strategy.current_iteration is 0
	Start of subproblem
	End of subproblem
	stop_strategy.current_iteration is 1
	Start of subproblem
	End of subproblem
	stop_strategy.current_iteration is 2
	Start of subproblem
	End of subproblem
	Start of subproblem
	End of subproblem
	Start of subproblem
	End of subproblem
	Start of subproblem
	End of subproblem
	Start of subproblem
	End of subproblem
	Start of subproblem
	End of subproblem
	Start of subproblem
	End of subproblem
	...

It never reaches `End of loop`. So I think it's safe to say that the [break](https://github.com/davisking/dlib/blob/ca498ac2d214fd679f8c641f90d08fb63cac11f6/dlib/optimization/optimization_trust_region.h#L304) statement that you linked is never reached... At least not within a reasonable amount of time (the process runs out of memory a couple of minutes later since a buffer keeps filling up in the background while the main loop is stalled).

> But for some reason that doesn't happen on your machine?

Apparently, yeah. It's an ARM Cortex A9. The binary is compiled with GCC 5.1. Nothing too exotic.

> Are you sure the initial radius isn't zero?

Now that I have found the source of the issue, I will add additional logging statements. I can try to log the `radius` as well. However, it is a long and tiresome process since the stall only happens rarely.

Also, since the loop didn't break the first iteration, then `radius` couldn't be zero to begin with.

**Comment by davisking** [comment]
How many iterations were executed?  radius should be driven below machine
epsilon in under 30 iterations if it's stuck.  Which is maybe more
iterations than it should wait, but it shouldn't be infinite.

**Comment by frederikaalund** [comment]
> How many iterations were executed?

244927 iterations. Took 8 minutes and 20 seconds before the parent process gave up.

I'm going to let it run overnight and hope for a stall. Anything that you'd like to see logged?

**Comment by davisking** [comment]
Just see if the radius is shrinking and why that check that it's <= epsilon
isn't triggering.

**Comment by frederikaalund** [comment]
Finally the error occurred again (almost took a week).

**Initial state**. That is, before the while loop starts:

	stale_x:	false
	f_value:	8.649034330750594e-08
	radius:		1
	x:			8.064693875695084e-06 
				1473105190.20756 
				0.001052001393936634 
				0.04356275194584994 
				0.002204298973083496 

Everything seems reasonable and `g and h` contain reasonable values as well. Note that x[1] is a timestamp (seconds since the Unix epoch).

**First iteration**. Subproblem solver gives:

	p:			-1.35385201211673e-05 
				0.0009906467668197901 
				0.002325868762470198 
				-2.537947130037535e-08 
				-0.001856744283307625 
	rho:		0.09188805324971834

Since `rho < 0.25`, the `radius` is decreased to `0.25`. Likewise (since `rho > 0`), `x`, `g`, `h` and `f_value` are updated:

	x:			-5.473826245472216e-06 
				1473105190.208551 
				0.003377870156406832 
				0.04356272656637863 
				0.0003475546897758709 

	g:				-8.563441858534694e-05 
				-7.307040067143083e-08 
				-1.027289586940727e-07 
				-4.232278142863449e-05 
				1.340170728027009e-06 

	h:			2.447542384577117		0.0007765437907045539	0.003024926738394633	6.201796400720923		-0.03830073394130407 
				0.0007765437907045539	9.768330939878049e-06	-1.666246606188446e-06	-0.01507927763086306	-1.224227225957858e-05 
				0.003024926738394633	-1.666246606188446e-06	1.045564101416769e-05	-0.01569309473596635	-4.71047006169862e-05 
				6.201796400720923		-0.01507927763086306	-0.01569309473596635	330						-0.09785363617659867 
				-0.03830073394130407	-1.224227225957858e-05	-4.71047006169862e-05	-0.09785363617659867	0.0005993627431313574 

	f_value:	8.559709740312501e-08
	stale_x:	false

All values are within reason (not too far from the initial state).

**Second iteration**. Subproblem solver gives:

	p:			-0.02195688289153057 
				0.004313228981041453 
				0.04841471545391627 
				-3.083927417442201e-07 
				-1.401491371459836 

	rho:		0.2546974645290118

The `radius` remains at `0.25` (since `0.75 > rho >= 0.25`). Everything is good so far. When updating the model, however, the derivative and hessian matrices (`g` and `h`) become unstable:

	x:			-0.02196235671777605 
				1473105190.212864 
				0.0517925856103231 
				0.04356241817363689 
				-1.401143816770061 

	g:			-1.744080646805953e-160 
				1.979263582875392e-159 
				5.287980188763079e-158 
				-0.0001101448302976288 
				1.977586404125327e-159 

	h:			7.843276780543929e-311	-8.91288575585488e-310	-2.388463147849715e-308	-8.318066745969836e-155	-8.912788740948281e-310 
				-8.91288575585488e-310	1.012838721518276e-308	2.714187220539983e-307	9.472393158122636e-154	1.01282553022157e-308 
				-2.388463147849715e-308	2.714187220539983e-307	7.273448837563741e-306	2.536502340476404e-152	2.714157438630012e-307 
				-8.318066745969836e-155	9.472393158122636e-154	2.536502340476404e-152 	330						9.458758110400953e-154 
				-8.912788740948281e-310	1.01282553022157e-308	2.714157438630012e-307	9.458758110400953e-154	1.012814461441429e-308 

	f_value:	8.51832924170149e-08
	stale_x:	false

`x` is still reasonable but `g` and `h` contain values very close to 0.

**Third iteration**. Subproblem solver gives:

	p:			-1.561150676956899e+157 
				6.319687295858829e+152 
				5.129372402031413e+154 
				-1.388538990733689e-05 
				-2.749024730721683e+156 

	rho:		-nan

Now `p` contains unreasonable large values (due to the unstable `g` and `h` from the previous iteration). The `rho: -nan` is the real offender. Digging deeper, `rho` becomes `-nan` because the residual function returns `-nan` for extreme values (parameters of approx. `e+150` and above).

All comparisons with a `nan` value returns `false`. *Thus the `radius` is never updated (since `-nan < 0.25: false` and `-nan > 0.75: false`)*. For the same reason, `rho > 0: false` and thus `stale_x` gets set to `true` indefinitely. This causes the infinite loop.

**My take on this**: I don't think it's unreasonable to expect these kind of instabilities in the residual and its derivative. Add an opt-out if `rho` is `nan` at the same place of the  [opt-out if `p` is small](https://github.com/davisking/dlib/blob/ca498ac2d214fd679f8c641f90d08fb63cac11f6/dlib/optimization/optimization_trust_region.h#L288). Alternatively, opt-out if `std::abs(p)` is ridiculously large (e.g., within an order 10 of `std::numeric_limits<type>::max()`).

Moreover, I think that the while loop should be re-structured so that the `stop_stategy.should_continue_search` function is called on *each* iteration. That is, `stale_x` should not be able to short-circuit the stop strategy. Otherwise, it is impossible to implement a `max_iterations` parameter for the stop strategy.

**Comment by davisking** [comment]
Cool, nice work debugging this : )  

Yeah, that would be a problem.   I just pushed a fix to github that adds a check for non-finite rho values.  

I'm not so sure about removing `stale_x` though.  I suppose the stopping strategies could return the max number of iterations to the solver and it can count and break based on that itself.

**Comment by frederikaalund** [comment]
> I just pushed a fix to github that adds a check for non-finite rho values.

Cheers! I know it took a while to get to the root if this problem so I appreciate your patience.

> I'm not so sure about removing stale_x though. I suppose the stopping strategies could return the max number of iterations to the solver and it can count and break based on that itself.

That would work for me. For long-running processes it is nice to have an upper bound on this kind of loop. Better safe than sorry. That's another issue, however, so I'm closing this one. Thanks again!
