### ISSUE TITLE
Train dlib_face_recognition_resnet_model_v1 using own data.

### ISSUE THREAD

**Issue by MikayelSmbatian** [davisking/dlib#2101]
Greetings. I want to thank you for your great work.

I have question about face features extraction model dlib_face_recognition_resnet_model_v1. Is it possible to train that model using my own triplets?

**Comment by tapas** [comment]
I guess the model is trained through metric learning in pair(2) of inputs and not on triplets(3).

**Comment by MikayelSmbatian** [comment]
Anyway, is there any script for training ?

**Comment by davisking** [comment]
Read the docs here http://dlib.net/dnn_face_recognition_ex.cpp.html
