### ISSUE TITLE
HOG not able to detect when is apply to a roi of the same image

### ISSUE THREAD

**Issue by valdes** [davisking/dlib#2102]
I have trained a hog detector(scan_fhog_pyramid<pyramid_disable>), when I passed it an image of the same size as the images used in the training, it is able to detect, but is I select a ROI of the same image it is not able to detect anything.
After googling and looking into the code and not found any clue. I thought if it is any with the slide window size.
Is the slide window size dependent of the input image dimension? And this generates slide windows of size much less small that my 'features' and then it is not able to found it?
Can you help me?
Greeting.

**Comment by davisking** [comment]
I'm not sure exactly what you are asking, but you probably don't want to
use pyramid_disable.  Use the recommended default and it will be able to
detect things regardless of their size in the image.

>

**Comment by valdes** [comment]
I have the following image(640.380):
![s3](https://user-images.githubusercontent.com/1929148/84683510-4c6b0200-af05-11ea-9bbc-d6113260e518.jpg)
And in it the feature is detected(in this image is visible only the feature,) and if I crop a little area that contains just the feature as the next image(128x76):
![s4](https://user-images.githubusercontent.com/1929148/84682721-0eb9a980-af04-11ea-8f3f-c667b2d3264d.jpg)
I crop this image, not resize, not scale and the HOG detector can't detect it.
What is wrong with this?
Why is it unable to find it?

**Comment by davisking** [comment]
It really depends on your training data.  There are border effects that
cause the edge of the image to look like it has a black stripe around it.
So if the training data never has any objects next to the edge of the
image, or next to a perfect black stripe, it will probably not learn to
detect things like that.

**Comment by valdes** [comment]
Thanks @davisking, but I think this is not the case. In the sample I show you, the light blue color is to hide the other part of the image. My main question is why in the big image I am able to detect the hog and in the little one that is a part of the big one I am not able to detect it. I think is cause of the slide window size using to detect the hog in the little one. Can you explain to me what are the possible sizes of the slide window in the little image and how the pyramid_disable affect it?
