### ISSUE TITLE
Training dlib's shape predictor

### ISSUE THREAD

**Issue by tatevmejunts** [davisking/dlib#2106]
Hello,

I'm traning dlib's `shape_predictor` on `300W_LP` dataset (AFW, HELEN, IBUG, LFPW) with default parameters.
It tooks like 20-38 hours to train (depending on count of options.num_threads). 
Is there any way to train it with GPU support or to accelerate when training on CPU:question:

Also I installed dlib from source and run this command :

```python3 setup.py install --set DLIB_USE_CUDA=1 --set USE_AVX_INSTRUCTIONS=1```

Are there any ideas how can i speed it up:question: :confused:

**Comment by davisking** [comment]
How big is the dataset you used exactly?

**Comment by tatevmejunts** [comment]
@davisking 73361 examples

**Comment by tatevmejunts** [comment]
And also I can't find any way to continue training by loading previously trained model, is it actually possible?

**Comment by davisking** [comment]
That's a lot.  It's going to take some time.  This stuff doesn't use CUDA and those --set commands do nothing by the way.  Just do `python3 setup.py install`.  All appropriate optimizations are on by default.

There is no way to warm start from another model.

**Comment by tatevmejunts** [comment]
Okay thank you. And also I noticed in one of your project issues that you trained the `shape_predictor_68_face_landmarks.dat` also with mirrored images. But I can't find `.pts` files of mirrored images. Did you generated them from original ones? And if yes how did you do that?

**Comment by davisking** [comment]
See http://blog.dlib.net/2018/01/correctly-mirroring-datasets.html

**Comment by tatevmejunts** [comment]
Thanks a lot @davisking
