### ISSUE TITLE
Threads::Threads.lib

### ISSUE THREAD

**Issue by tadam98** [davisking/dlib#2107]
Using windows 10
I have TBB and MKL with TBB installed.
I have CUDA 10.0 and cuDNN 7.6.5 installed.

> git clone https://github.com/davisking/dlib.git
> mkdir build
> cd build
> cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
> cmake --build .
$ cd ..
> python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

1. Complains about the --yes **so I removed both**. 
**Not sure how** to tell it to use CUDA and MKL with TBB.

> python setup.py install

2. LINK : fatal error LNK1104: cannot open file '**Threads::Threads.lib**' [C:\Download\dlib\dlib\build\temp.win-amd64-3.7\Rel
ease\_dlib_pybind11.vcxproj]

```
LINK : fatal error LNK1104: cannot open file 'Threads::Threads.lib' [C:\Download\dlib\dlib\build\temp.win-amd64-3.7\Release\_dlib_pybind11.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 262, in <module>
    'Topic :: Software Development',
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 135, in run
    self.build_extension(ext)
  File "setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
```
![cmake-gui](https://user-images.githubusercontent.com/21152079/85193146-84d85a80-b2ce-11ea-99ec-e0022eae8b99.jpg)
[cmake-gui.txt](https://github.com/davisking/dlib/files/4807393/cmake-gui.txt)
[CMakeOutput.log](https://github.com/davisking/dlib/files/4807396/CMakeOutput.log)
[vs2017.log](https://github.com/davisking/dlib/files/4807399/vs2017.log)

**Comment by davisking** [comment]
I don't know.  Something is unusual about your setup.  You will have to look at the cmake output and figure out what's going wrong.

**Comment by tadam98** [comment]
Could it be because of the MKL with TBB?

It cannot find "**Threads::Threads.lib**" - no idea what it is.
Also, both "**--yes**" on the **setup.py** are rejected by setup.py

I have **successfully** compiled OpenCV 4.2.0 in this same **conda** environment with: TBB, **MKL with TBB**, Eigen, CUDA 10.0, cuDNN 7.6.5 and gStreamer.

**Comment by davisking** [comment]
I don't know, but it seems like it's probably the Intel MKL or TBB.   There is nothing in dlib with a name like `Threads::Threads.lib` in any case.

There is no `--yes` option.  So if you give `--yes` you are going to get an error.

**Comment by tadam98** [comment]
Yet, MKL with TBB appears in the CMAKE-gui options.

**Comment by tadam98** [comment]
When the compilation was performed as admin:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" ALL_BUILD.vcxproj /m:6 /p:Configuration=Release
**Completed without error.**

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" INSTALL.vcxproj /m:6 /p:Configuration=Release
**Completed without error.**

**And the following was created.**
`C:\Download\dlib\dlib\build\dlib\Release\dlib19.20.99_release_64bit_msvc1900.lib`

But
`> python setup.py install `
fails:

(cv4cuda) C:\Download\dlib\dlib>python setup.py install
running install
running bdist_egg
running egg_info
writing tools/python\dlib.egg-info\PKG-INFO
writing dependency_links to tools/python\dlib.egg-info\dependency_links.txt
writing top-level names to tools/python\dlib.egg-info\top_level.txt
package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
reading manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools\python\build*'
writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Download\dlib\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Download\dlib\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\Users\Mickey\Miniconda3\envs\cv4cuda\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Download\dlib\dlib\build\lib.win-amd64-3.7 -A x64'
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- pybind11 v2.2.2
-- Using CMake version: 3.17.0-rc1
-- Compiling dlib version: 19.20.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- FOUND libiomp5md.dll: C:/Users/Mickey/Miniconda3/envs/cv4cuda/Library/bin/libiomp5md.dll
-- Found Intel MKL BLAS/LAPACK library
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudnn.lib
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
CMake Warning (dev) at C:/Download/dlib/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "_dlib_pybind11" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:71 (pybind11_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Download/dlib/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "_dlib_pybind11" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:71 (pybind11_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Download/dlib/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "_dlib_pybind11" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:71 (pybind11_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Download/dlib/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "_dlib_pybind11" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:71 (pybind11_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindCUDA.cmake:1833 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dlib" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  C:/Download/dlib/dlib/dlib/CMakeLists.txt:819 (cuda_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindCUDA.cmake:1833 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dlib" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  C:/Download/dlib/dlib/dlib/CMakeLists.txt:819 (cuda_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindCUDA.cmake:1833 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dlib" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  C:/Download/dlib/dlib/dlib/CMakeLists.txt:819 (cuda_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindCUDA.cmake:1833 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dlib" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  C:/Download/dlib/dlib/dlib/CMakeLists.txt:819 (cuda_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Download/dlib/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "_dlib_pybind11" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:71 (pybind11_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindCUDA.cmake:1833 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "dlib" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  C:/Download/dlib/dlib/dlib/CMakeLists.txt:819 (cuda_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: C:/Download/dlib/dlib/build/temp.win-amd64-3.7/Release
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  dlib.vcxproj -> C:\Download\dlib\dlib\build\temp.win-amd64-3.7\Release\dlib_build\Release\dlib19.20.99_release_64bit_
  msvc1916.lib
**LINK : fatal error LNK1104: cannot open file 'Threads::Threads.lib'** [C:\Download\dlib\dlib\build\temp.win-amd64-3.7\Rel
ease\_dlib_pybind11.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 262, in <module>
    'Topic :: Software Development',
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 135, in run
    self.build_extension(ext)
  File "setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\Mickey\Miniconda3\envs\cv4cuda\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

**Comment by tadam98** [comment]
The problem is in the vcxproj file (I added .txt to allow upload to guthub) 
in lines: 117, 163, 209 and 254 where it is looking for:
**Threads::Threads.lib**

[_dlib_pybind11.vcxproj.txt](https://github.com/davisking/dlib/files/4808558/_dlib_pybind11.vcxproj.txt)

**Comment by tadam98** [comment]
And in file: C:\Download\dlib\dlib\build\dlib\CMakeFiles\Export\lib\cmake\dlib\dlib.cmake **line 60**, as part of **INTERFACE_LINK_LIBRARIES**:

INTERFACE_LINK_LIBRARIES "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudart_static.lib;**Threads::Threads**;ws2_32;winmm;comctl32;gdi32;imm32;C:/Users/Mickey/Miniconda3/envs/cv4cuda/Library/lib/libpng.lib;C:/Users/Mickey/Miniconda3/envs/cv4cuda/Library/lib/z.lib;C:/Users/Mickey/Miniconda3/envs/cv4cuda/Library/lib/jpeg.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_tbb_thread.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/tbb/lib/intel64/vc14/tbb.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_tbb_thread.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/tbb/lib/intel64/vc14/tbb.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cublas.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudnn.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/curand.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cusolver.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudart.lib;C:/Users/Mickey/Miniconda3/envs/cv4cuda/Library/lib/sqlite3.lib"

[dlib.cmake.txt](https://github.com/davisking/dlib/files/4808573/dlib.cmake.txt)

**Comment by tadam98** [comment]
It is coming from here:
```
C:\Program Files\CMake\share\cmake-3.17\Modules\FindCuda.cmake line 932:

if(CUDA_BUILD_EMULATION AND CUDA_CUDARTEMU_LIBRARY)
  list(APPEND CUDA_LIBRARIES ${CUDA_CUDARTEMU_LIBRARY})
elseif(CUDA_USE_STATIC_CUDA_RUNTIME AND CUDA_cudart_static_LIBRARY)
  list(APPEND CUDA_LIBRARIES ${CUDA_cudart_static_LIBRARY} Threads::Threads ${CMAKE_DL_LIBS})
  if (CUDA_rt_LIBRARY)
    list(APPEND CUDA_LIBRARIES ${CUDA_rt_LIBRARY})
  endif()
  if(APPLE)
    # We need to add the default path to the driver (libcuda.dylib) as an rpath, so that
    # the static cuda runtime can find it at runtime.
    list(APPEND CUDA_LIBRARIES -Wl,-rpath,/usr/local/cuda/lib)
  endif()
else()
  list(APPEND CUDA_LIBRARIES ${CUDA_CUDART_LIBRARY})
endif()
```

[FindCUDA.cmake.txt](https://github.com/davisking/dlib/files/4808586/FindCUDA.cmake.txt)

**Comment by tadam98** [comment]
I noticed it was under an IF statement ${CUDA_cudart_static_LIBRARY} so I removed the static build which was there as default.

And ...
C:\Download\dlib\dlib\tools\python\build\Release\_dlib_pybind11.cp37-win_amd64.pyd

Was generated.

Procedure:
```
> cd C:\Download\dlib\dlib\tools\python\
> mkdir build
> cd build
> cmake-gui ..

```
Set the options as in the attacked image.
>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" ALL_BUILD.vcxproj /m:6 /p:Configuration=Release

and it appears to work.

![tools_python_cmake-gui](https://user-images.githubusercontent.com/21152079/85211977-e80dcf80-b356-11ea-8f29-3d31dc998548.jpg)

**Comment by tadam98** [comment]
Still not working but I am on the right direction.

**Comment by tadam98** [comment]
Now it works !!!

```
cd C:\Download\dlib\dlib
> python setup.py install --set DLIB_USE_CUDA=1 --set CUDA_USE_STATIC_CUDA_RUNTIME=0 --set PYBIND11_INSTALL=1

Installed c:\users\mickey\miniconda3\envs\cv4cuda\lib\site-packages\dlib-19.20.99-py3.7-win-amd64.egg
Processing dependencies for dlib==19.20.99
Finished processing dependencies for dlib==19.20.99
```

Check in installation:
```
> python
>>> import dlib
>>> dlib.cuda
<module '_dlib_pybind11.cuda'>
>>> dlib.DLIB_USE_CUDA
True
>> exit()
```

**Note**: it is properly installed under my conda cv4cuda environment !

**Comment by davisking** [comment]
These steps shouldn't be needed.  Like are you saying you edited the FindCUDA.cmake file that comes with cmake?  You definitely should not need to do that.

**Comment by tadam98** [comment]
No I did not.
I only understood from it that what is causing the requirement for Threads::Threads is the "static" lib.

Static CUDA lib happens to be the default of setup.py.

To avoid it, I added on the command line of setup.py --set static=0. Which prevented the static link.

And the issue was resolved.

Did not modify anything except adding two more parameters. The second was pybuild11=1 or else the pyd is not generates.

Now all is well.
________________________________

**Comment by davisking** [comment]
¯\_(ツ)_/¯
