### ISSUE TITLE
Programatically creating a dlib XML file for parsing icons

### ISSUE THREAD

**Issue by pranavlal** [davisking/dlib#2109]
Hi all,
I want to create a custom object detector for detecting icons in a network topology diagram. These icons represent various network elements like routers, switches etc.
I have organized the images into various folders that match the names of device classes. For example,  icons representing various models of switches have been placed in a folder called switch.

Is there a way that I can programmatically generate the dlib xml file to detect these icons?
The icons are clean images and the entire image has to go into the model.

I did try searching for a XML  specification but have been unable to find one.

I cannot use the imglab tool because I am blind and the tool involves using the mouse to draw the borders of objects.
Note:
If you want to see the icons, then please grab the library from the following link.
https://www.cisco.com/c/en/us/about/brand-center/network-topology-icons.html
Pranav

**Comment by davisking** [comment]
You want to use the methods here http://dlib.net/ml.html#load_image_dataset_metadata which load and save `dataset` objects to and from that XML format.

**Comment by pranavlal** [comment]
Hi Davis,
Many thanks. I understand the format. I have been able to generate a XML file containing a stub  using the commandline options of the imglab tool. 
I was looking at the commandline options of that tool and found the --box-images option which fits a single image to a single box. 
I think this will do what I want and I will not have to write any code. 
If I am right, how should I organize my files for them to be populated into the xml file?
As of this writing, my data set is in a folder called images. Under the images folder, I have various folders like router, switch, telecom etc. In each of these folders, there are a number of *.jpg files. 

Otherwise, I will begin writing code  to add the relevant tags to the xml stub.
Pranav

**Comment by davisking** [comment]
I'm not sure I understand what you are trying to do.  It sounds like you are able to make the XML file you want.

**Comment by pranavlal** [comment]
Hi Davis,
Indeed, I have been able to draw the bounding boxes around the  images automatically therefore no need to mess with the GUI and the mouse. My problem is solved.
