### ISSUE TITLE
"Deep Learning Introduction Part 1" example build error issue

### ISSUE THREAD

**Issue by triplekimchi** [davisking/dlib#211]
[build environment]
OS: Windows 7 x64  
Compiler: Visual Studio 2015 Community

[building steps]
1. add "dlib/all/source.cpp" to my project in visual studio 2015
2. include the directory of dlib folder's parent folder for includes
3. build

[Error messages]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	19 unresolved externals	dlib_example	c:\users\PC1\documents\visual studio 2015\Projects\dlib_example\Release\dlib_example.exe	1	
Warning	C4819	The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss	dlib_example	c:\users\PC1\desktop\dlib-19.1\dlib-19.1\dlib\general_hash\random_hashing.h	685	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::relu(class dlib::tensor &,class dlib::tensor const &)" (?relu@tt@dlib@@YAXAAVtensor@2@ABV32@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::assign_bias_gradient(class dlib::tensor &,class dlib::tensor const &)" (?assign_bias_gradient@tt@dlib@@YAXAAVtensor@2@ABV32@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::relu_gradient(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &)" (?relu_gradient@tt@dlib@@YAXAAVtensor@2@ABV32@1@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::gemm(float,class dlib::tensor &,float,class dlib::tensor const &,bool,class dlib::tensor const &,bool)" (?gemm@tt@dlib@@YAXMAAVtensor@2@MABV32@_N12@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::softmax(class dlib::tensor &,class dlib::tensor const &)" (?softmax@tt@dlib@@YAXAAVtensor@2@ABV32@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::add(float,class dlib::tensor &,float,class dlib::tensor const &)" (?add@tt@dlib@@YAXMAAVtensor@2@MABV32@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::add(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &)" (?add@tt@dlib@@YAXAAVtensor@2@ABV32@1@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::affine_transform(class dlib::tensor &,class dlib::tensor const &,float)" (?affine_transform@tt@dlib@@YAXAAVtensor@2@ABV32@M@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::affine_transform(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &,float,float)" (?affine_transform@tt@dlib@@YAXAAVtensor@2@ABV32@1MM@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::affine_transform(class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor const &,float,float,float)" (?affine_transform@tt@dlib@@YAXAAVtensor@2@ABV32@11MMM@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::affine_transform_range(unsigned int,unsigned int,class dlib::tensor &,class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor const &,float,float,float)" (?affine_transform_range@tt@dlib@@YAXIIAAVtensor@2@ABV32@11MMM@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl dlib::tt::assign_conv_bias_gradient(class dlib::tensor &,class dlib::tensor const &)" (?assign_conv_bias_gradient@tt@dlib@@YAXAAVtensor@2@ABV32@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: void __thiscall dlib::cpu::pooling::get_gradient(class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor &)" (?get_gradient@pooling@cpu@dlib@@QAEXABVtensor@3@00AAV43@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: void __thiscall dlib::cpu::pooling::operator()(class dlib::resizable_tensor &,class dlib::tensor const &)" (??Rpooling@cpu@dlib@@QAEXAAVresizable_tensor@2@ABVtensor@2@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: void __thiscall dlib::cpu::pooling::setup_max_pooling(int,int,int,int,int,int)" (?setup_max_pooling@pooling@cpu@dlib@@QAEXHHHHHH@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: __thiscall dlib::cpu::pooling::pooling(void)" (??0pooling@cpu@dlib@@QAE@XZ)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: void __thiscall dlib::cpu::tensor_conv::get_gradient_for_filters(class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor &)" (?get_gradient_for_filters@tensor_conv@cpu@dlib@@QAEXABVtensor@3@0AAV43@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: void __thiscall dlib::cpu::tensor_conv::get_gradient_for_data(class dlib::tensor const &,class dlib::tensor const &,class dlib::tensor &)" (?get_gradient_for_data@tensor_conv@cpu@dlib@@QAEXABVtensor@3@0AAV43@@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	
Error	LNK2001	unresolved external symbol "public: void __thiscall dlib::cpu::tensor_conv::operator()(class dlib::resizable_tensor &,class dlib::tensor const &,class dlib::tensor const &,int,int,int,int)" (??Rtensor_conv@cpu@dlib@@QAEXAAVresizable_tensor@2@ABVtensor@2@1HHHH@Z)	dlib_example	c:\Users\PC1\documents\visual studio 2015\Projects\dlib_example\dlib_example\main.obj	1	

-------------------------------------------------------------------------------------------------------

I've also tried using "CMake" but had simular symbol error in version 3.6.1 

While building with CMake, it prints -->
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Failed
-- C++11 activated (compiler doesn't have full C++11 support).

Does this effect to building example?

**Comment by davisking** [comment]
You got a similar error with CMake?  CMake shouldn't even build the DNN
example programs in Visual Studio 2015 because that compiler doesn't
support C++11.

**Comment by davisking** [comment]
I should point out that C++11 is a requirement to use the DNN tools

**Comment by triplekimchi** [comment]
Thanks for the comment.
So DNN tools can't be used in Visual Studio 2015?
C++11 and C++14 are different but I think CMake recognizes that C++14 supports C++11 partly.
(Just a thought)

I haven't tried Visual Studio 2010 but could you suggest which Visual Studio version is fully compatible?

**Comment by davisking** [comment]
When I say C++11 I mean the ISO standard C++ ratified in 2011.  Visual
Studio is a bad compiler and doesn't work with standard C++, even though
it's 2016 and they have had many years to support it.  My impression is
that the next version of Visual Studio will support C++11.   Certainly not
C++14 though.  I'm sure it will take them many years before that happens,
even though GCC has supported C++14 for well over a year now.
