### ISSUE TITLE
Broken pkg-config file

### ISSUE THREAD

**Issue by remicollet** [davisking/dlib#2111]
Generated dlib-1.pc seems broken

# Current
```
$ pkg-config --libs dlib-1
-ldlib -lpthread /usr/lib64/libX11.so /usr/lib64/libXext.so /usr/lib64/libgif.so /usr/lib64/libpng.so /usr/lib64/libz.so /usr/lib64/libjpeg.so /usr/lib64/libopenblasp.so /usr/lib64/libsqlite3.so 
```

library patch is not expected there, only linker options

# Expected
`$ pkg-config --libs dlib-1 -ldlib -lpthread -lSM -lICE -lX11 -lXext -lgif -lpng -lz -ljpeg -lopenblasp -lsqlite3`

**Comment by davisking** [comment]
How is this broken?

**Comment by remicollet** [comment]
for ex `/usr/lib64/libgif.so ` is not a linker option, so the library is not added to linker command, which result in missing symbols.

Ex: buillging [pdlib](https://github.com/goodspb/pdlib) extension for php:
`modules/pdlib.so: undefined symbol: DGifSlurp`

**Comment by remicollet** [comment]
Notice: libgif is the only needed library, as there is direct call to gif fucntions in `image_loader/load_image.h`, other libraries are private (only used by libdlib)

SO:
```
Libs: -L${libdir} -ldlib -lgif
Libs.private:  -lpthread -lX11 -lXext -lpng -lz -ljpeg -lopenblasp -lsqlite3
```

BTW, an alternative way could be to mode the GIF code in some C file, outside the header, so libgif will also be a private library

**Comment by remicollet** [comment]
See how this output is consumed in 
https://github.com/php/php-src/blob/master/build/php.m4#L368

As you can see, only `-l` and `-L` options are used.

Notice: dlib is the only library among the hundreds one installed on my system to use full paths...

**Comment by remicollet** [comment]
I still think pkgconfig file is not clean.

At least public vs private libraries are not handled as expected
And using libraries full path is not a common/best practice

**Comment by davisking** [comment]
You can make a PR to change it. But it’s just got to avoid breaking existing user’s setups.
