### ISSUE TITLE
Problem Replacing MNIST dataset with Fashion MNIST while training dnn inception net example

### ISSUE THREAD

**Issue by WawdhaneP** [davisking/dlib#2119]
Hello , I am using Ubuntu 18.04 with  dlib19.19 for training dlib example dnn_inceptionnet_ex.cpp . The example needs traditional MNIST dataset. I want to train the new FASHION MNIST dataset for the same example it's giving very poor accuracyv i.e 8%. My concern is the network is not even running a single epoch but directly giving the results.

P.S. With original MNIST dataset it is working fine

Please help.

**Comment by arrufat** [comment]
It seems like the `dnn_trainer` is loading the `inception_sync` file from disk.
Did you train on MNIST and then try to train on fashion MNIST? If so, delete the files `inception_sync` and `inception_sync_` and try again.
