### ISSUE TITLE
About rotation invariance

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#2120]
hi @davisking , I saw this:
https://github.com/davisking/dlib/blob/6b581d91f6b9b847a8163420630ef947e7cc88db/dlib/image_keypoint/poly_image.h#L115
does it means dlib support rotation invariant image classification? e.g. 2 images with same object in it, but rotation is different, and background is clean(which means no other objects), and the similarity between these 2 images will be higher, say 0.90,  and if with different type(similar but with same angle/rotation), then the similarity is low, e.g. 0.3

**Comment by davisking** [comment]
It depends entirely on what you do with that class you linked to.  That
class by itself is not an object detector.
