### ISSUE TITLE
Can't import Python package: ImportError: dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPushCallConfiguration

### ISSUE THREAD

**Issue by TheTimKiely** [davisking/dlib#2123]
## Expected Behavior
I am using the Python dlib package through the face_recognition library.  My install worked successfully until I downgraded CUDA from 11 to 10.0.  I see that there was a similar issue reported, but it was closed without a resolution.

## Current Behavior
The error happens when importing dlib:
import dlib
ImportError: /.../venv/lib/python3.6/site-packages/dlib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPushCallConfiguration

* **Version**: 19.20.0
* **Where did you get dlib**: I build dlib from source, using [these instructions](https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf).
* **Platform**: Ubuntu 18.04.4 LTS
* **Compiler**: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

I rebuild dlib after downgrading CUDA, but I must be missing something.  Is there current dlib codebase compatible with CUDA 10.0?  Is there a compiler switch I'm missing?

Thanks,
Tim

**Comment by davisking** [comment]
You probably didn't really reinstall it.  Do `pip uninstall dlib` a few times and make sure it's really gone.  Then download a fresh copy and try again.

**Comment by TheTimKiely** [comment]
Thanks Davis.  I created a fresh Python virtual environment, but I get the same error.

**Comment by davisking** [comment]
Then something is probably wrong with your cuda install.  Try reinstalling CUDA.

**Comment by TheTimKiely** [comment]
I'll give it another try.
Is there a specific version I should be using with the latest dlib code?
Thanks again.

**Comment by TheTimKiely** [comment]
Using these searches
apt list --installed | grep "cuda"
apt list --installed | grep "nvidia"
I found a couple of old packages.
Removing those solved the problem.
