### ISSUE TITLE
error install ubuntu 18.04 

### ISSUE THREAD

**Issue by didierrestrepo** [davisking/dlib#2126]
[ 72%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o
In file included from /home/ubuntu/visionplusapp/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/ubuntu/visionplusapp/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/ubuntu/visionplusapp/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/ubuntu/visionplusapp/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/ubuntu/visionplusapp/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/ubuntu/visionplusapp/dlib/dlib/../dlib/python.h:6,
                 from /home/ubuntu/visionplusapp/dlib/tools/python/src/opaque_types.h:6,
                 from /home/ubuntu/visionplusapp/dlib/tools/python/src/dlib.cpp:4:
/home/ubuntu/visionplusapp/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:10: fatal error:Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/_dlib_pybind11.dir/build.make:82: recipe for target 'CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o' failed

**Comment by davisking** [comment]
You have to install the pyhton dev package.  You didn't fill out the issue template, so I don't know what operating system you are on though.  But ubuntu it's the ones that end in -dev.
