### ISSUE TITLE
FHOG Object Detector 16-bit Images as Input

### ISSUE THREAD

**Issue by rwin94** [davisking/dlib#2127]
Hi, 

Is there a reason why the hfog object detector is not able to run detection on 16 bit grayscale images? 

I was able to train a simple hog object detector in dlib using 16 bit grayscale PNG images as the input data based on the instructions here: http://dlib.net/train_object_detector.py.html

I was expecting the detector to be able to handle taking in 16 bit images to run detections but it gives an error that the expected input images should be 8bit RGB or Gray. However, if I normalize the input images and run the object detector I will get back no results.
Is there a way to make this change on my end in the source code that you could advise me on or is this not possible?

Thanks

* **Version**: 19.20.99
* **Where did you get dlib**: github repo 
* **Platform**: Ubuntu 18.04.4 LTS
* **Compiler**:  gcc==7.5.0, cmake==3.10.2

**Comment by davisking** [comment]
This stuff all runs on 8bit color images.  Whatever you ran was loading those images as 8bit images.  The python interface will not do any color conversion or loading, so you have to explicitly give it 8bit images though.  I don't know what you mean by normalize. Maybe you are accidentally crushing the color channels to 0.  Make sure you don't do that.
