### ISSUE TITLE
Computing landmarks for custom objects ?

### ISSUE THREAD

**Issue by Ravi-Teja-konda** [davisking/dlib#2128]
Hello Everyone,

I'm working on generating the landmarks for my custom object. After the object detection
just like **(facerec.compute_face_descriptor)** will do for generating the face encodings.

How to achieve it for the custom object?

If I want to generate the landmarks for a custom object do I need to annotate or draw dots to objects to which it wants to generate the landmarks for every image in the training data set? 

(If so any links or tutorials you can point me instead of face tutorials)

Any comments will be appreciated...

Thanks.

**Comment by davisking** [comment]
The docs for this tool are here http://dlib.net/ml.html#shape_predictor_trainer.  They explain how to use it in detail.
