### ISSUE TITLE
cmake --build . --config Release   failed

### ISSUE THREAD

**Issue by wangzhongju** [davisking/dlib#2129]
enviroment: win10+cuda10.1+cudnn7.6+vs2019

error C2734: "GifAsciiTable8x8": If it is not external, you must initialize the constant object

**Comment by qingyu-wang** [comment]
how did you solve this problem? @wangzhongju

**Comment by wangzhongju** [comment]
> how did you solve this problem? @wangzhongju

Sorry, it took too long to forget. Maybe you can try to initializing "GifAsciiTable8x8".
