### ISSUE TITLE
How to get byte array output from  serialize and deserialize methods?

### ISSUE THREAD

**Issue by mv2050arshad** [davisking/dlib#2133]
HI. 
First, i want to appreciate you for share your great library. 

I want to get binary data(as byte array) from output of serialize method. but it only send data to physical file that mention in oStream parameter. i just need that binary data without operation on file. how to do that?

Iin other side, i want to deserialize binary data(in byte array) to origin datatype, not from binary file but from an array without open any file. how to do that?

thanks in advance

**Comment by arrufat** [comment]
You can just to the steps to deserialize the fronttal_face_detector from the
https://github.com/davisking/dlib/blob/23b9abd07a56f9fef560aa9e263b37f82543a0cc/dlib/image_processing/frontal_face_detector.h#L2353-L2367

That is exactly what I did in one small project, which you can find here:
https://github.com/arrufat/wallyfinder/blob/789e71a3e442547d39945c6997e7bc42f4503082/src/detector.h#L8-L29

``` c++
dlib::deserialize(model_path) >> net;
std::ostringstream sout;
std::istringstream sin;
dlib::base64 base64_coder;
dlib::compress_stream::kernel_2a compressor;
// put the data into ostream sout
dlib::serialize(net, sout);
// put the data into istream sin
sin.str(sout.str());
sout.str("");
// compress the data
compressor.compress(sin, sout);
sin.clear();
sin.str(sout.str());
sout.str("");
// encode the data into base64
base64_coder.encode(sin, sout);
// print the data on the terminal
std::cout << sout.str() << std::endl;

```

**Comment by mv2050arshad** [comment]
Thank you guy that cool.

**Comment by davisking** [comment]
Right, use the string streams and you can read and write whatever you want to them.

**Comment by mv2050arshad** [comment]
yah you are right. thanks again
