### ISSUE TITLE
poor dnn inference performance on windows10

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#2134]
Hello

I am about to deploy an application to a windows 10 system. The system has a I5-9600KF CPU, 8GB ram and a 4GB GTX 1050TI GPU as the systems only graphics card, using CUDA11.
But the performance of doing inference using a small dnn on this system is very poor - it takes about 110 seconds to run the network on seven images (one by one), four times on each image. The images are between 1.2 and 3.8 megapixels, each having a different size, with an average of about 2 megapixels per image.
On he same system, and on the same images, the same program compiled without CUDA, using MSVC2019 and INTEL MKL takes about 50 seconds for the same task, and also about 50 seconds when compiled with MINGW 7.3 and OpenBLAS.
The same program runs in less than 10 seconds on my home laptop (I5-7200U, 8GB ram, with an 4GB GTX950M) with CUDA10 and Ubuntu18.04.
I was expecting the GTX1050TI on the windows machine to be about twice as fast as the GTX950M.
Training works decently on the windows system, being about 8 times faster on the GTX1050TI compared to the CPU with MKL, or about 9 times faster compared to the CPU with OpenBLAS, or about 25% faster than the GTX950M on Ubuntu.
Therefore, I suppose that the CUDA install is not broken.

The network is defined as follows for training (the batch-norm layers are replaced with affine layers for inference):
`layer<0>	loss_mmod	 (detector_windows:(raspi:66x99), loss per FA:1, loss per miss:1, truth match IOU thresh:0.5, use_bounding_box_regression:0, overlaps_nms:(0.1,0.1), overlaps_ignore:(0.5,1))
layer<1>	con	 (num_filters=1, nr=7, nc=7, stride_y=1, stride_x=1, padding_y=3, padding_x=3) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<2>	prelu	 (initial_param_value=0.25)
layer<3>	add_prev1
layer<4>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<5>	con	 (num_filters=40, nr=3, nc=3, stride_y=1, stride_x=1, padding_y=1, padding_x=1) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<6>	prelu	 (initial_param_value=0.25)
layer<7>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<8>	con	 (num_filters=40, nr=3, nc=3, stride_y=1, stride_x=1, padding_y=1, padding_x=1) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<9>	tag1
layer<10>	prelu	 (initial_param_value=0.25)
layer<11>	add_prev1
layer<12>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<13>	con	 (num_filters=40, nr=3, nc=3, stride_y=1, stride_x=1, padding_y=1, padding_x=1) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<14>	prelu	 (initial_param_value=0.25)
layer<15>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<16>	con	 (num_filters=40, nr=3, nc=3, stride_y=1, stride_x=1, padding_y=1, padding_x=1) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<17>	tag1
layer<18>	prelu	 (initial_param_value=0.25)
layer<19>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<20>	con	 (num_filters=40, nr=5, nc=5, stride_y=2, stride_x=2, padding_y=0, padding_x=0) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<21>	prelu	 (initial_param_value=0.25)
layer<22>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<23>	con	 (num_filters=32, nr=5, nc=5, stride_y=2, stride_x=2, padding_y=0, padding_x=0) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<24>	prelu	 (initial_param_value=0.25)
layer<25>	bn_con   eps=0.0001 running_stats_window_size=100 learning_rate_mult=1 weight_decay_mult=0 bias_learning_rate_mult=1 bias_weight_decay_mult=1
layer<26>	con	 (num_filters=16, nr=5, nc=5, stride_y=2, stride_x=2, padding_y=0, padding_x=0) learning_rate_mult=1 weight_decay_mult=1 bias_learning_rate_mult=1 bias_weight_decay_mult=0
layer<27>	input_rgb_image_pyramid(122.782,117.001,104.298) pyramid_padding=10 pyramid_outer_padding=11`

During inference, the maximum GPU memory used reporded by nvidia-smi is about 30% of the available memory, so I suppose it's not an issue of running out of memory.
Any idea about how to fix this issue?

**Comment by davisking** [comment]
If you were using cuDNN 8 try using the latest copy of dlib from github.  It may fix your error.

**Comment by pepeverde9** [comment]
Thank you for the answer.
Yes, I have cuDNN 8.0.1.13 on this system, alongside cuda 11.0.2.
The version of dlib I had was a clone from github from the 28.06.2020. Indeed, I had to replace sm_30 with sm_50 as minumum cuda architecture, as support for Kepler architecture has been dropped according to https://blog.exxactcorp.com/nvidia-cuda-11-now-available/
Anyway, after downloading the current dlib source today and rebuilding the program, the only difference I noticed was that I don't have to modify the cuda architecture any more.
But the inference performance is still similar to what I had before, more than 10 times slower than what I get on my ubuntu laptop.

**Comment by davisking** [comment]
Well, I don't know what exactly you are doing.  You need to post some minimal but complete program that reproduces what you are seeing.

**Comment by pepeverde9** [comment]
Unfortunately, I do not have the system any more - it has been given to our production floor, running dlib in CPU mode, mostly using FHOG, for something similar to http://www.platiscan.de/txt/platiscan_boardcheck_e.html.

**Comment by pepeverde9** [comment]
Update: We installed another system, also with windows 10, but this time it had a GTX 1650 super GPU. This system performed much better, inference using the GPU was at least 10 times faster than on the I5-9600K with MKL. I still have no clue why the first one behaved so bad. The GPU will be replaced with a GTX 1650 super, in order to have all the systems with identical configuration, we will see if it helps
