### ISSUE TITLE
jatson tx2  build error

### ISSUE THREAD

**Issue by coffice12** [davisking/dlib#2139]
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/lib/aarch64-linux-gnu/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /root/dlib-19.20/build
[  1%] Building NVCC (Device) object dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cusolver_dlibapi.cu.o
[  3%] Building NVCC (Device) object dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o
/root/dlib-19.20/dlib/cuda/cuda_dlib.cu(1762): error: calling a constexpr __host__ function("log1p") from a __device__ function("cuda_log1pexp") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

1 error detected in the compilation of "/tmp/tmpxft_000023be_00000000-6_cuda_dlib.cpp1.ii".
CMake Error at dlib_generated_cuda_dlib.cu.o.cmake:266 (message):
  Error generating file
  /root/dlib-19.20/build/dlib/CMakeFiles/dlib.dir/cuda/./dlib_generated_cuda_dlib.cu.o

dlib/CMakeFiles/dlib.dir/build.make:63: recipe for target 'dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o' failed
make[2]: *** [dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'dlib/CMakeFiles/dlib.dir/all' failed
make[1]: *** [dlib/CMakeFiles/dlib.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davisking** [comment]
Try the latest dlib on GitHub

**Comment by coffice12** [comment]
> Try the latest dlib on GitHub
> […](#)
> On Jul 27, 2020, at 4:13 AM, cafe ***@***.***> wrote: ﻿ -- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.5") -- Looking for cuDNN install... -- Found cuDNN: /usr/lib/aarch64-linux-gnu/libcudnn.so -- Building a CUDA test project to see if your compiler is compatible with CUDA... -- Checking if you have the right version of cuDNN installed. -- Enabling CUDA support for dlib. DLIB WILL USE CUDA -- C++11 activated. -- Configuring done -- Generating done -- Build files have been written to: /root/dlib-19.20/build [ 1%] Building NVCC (Device) object dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cusolver_dlibapi.cu.o [ 3%] Building NVCC (Device) object dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o /root/dlib-19.20/dlib/cuda/cuda_dlib.cu(1762): error: calling a constexpr host function("log1p") from a device function("cuda_log1pexp") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this. 1 error detected in the compilation of "/tmp/tmpxft_000023be_00000000-6_cuda_dlib.cpp1.ii". CMake Error at dlib_generated_cuda_dlib.cu.o.cmake:266 (message): Error generating file /root/dlib-19.20/build/dlib/CMakeFiles/dlib.dir/cuda/./dlib_generated_cuda_dlib.cu.o dlib/CMakeFiles/dlib.dir/build.make:63: recipe for target 'dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o' failed make[2]: *** [dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o] Error 1 CMakeFiles/Makefile2:85: recipe for target 'dlib/CMakeFiles/dlib.dir/all' failed make[1]: *** [dlib/CMakeFiles/dlib.dir/all] Error 2 Makefile:149: recipe for target 'all' failed make: *** [all] Error 2 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

dlib/dlib/cuda/cuda_dlib.cu   edit.  1762 line.    

# old
return std::log1p(std::exp(x));

# new
return std::log1pf(std::exp(x));

fix this

**Comment by takuya-takeuchi** [comment]
@davisking 

Hi, davis.
I faces to same error on the following env.

* Ubuntu 16.04 (docker, base is nvidia/cuda:11.0-cudnn8-devel-ubuntu16.04)
  * Host is Ubuntu 18.04 and CUDA Driver is 450.51.05 (latest)
  * GeForce GTX 750 Ti

After apply @coffice12's aproach, build was successful.

But this error does not on Windows machine without the above modification.
Windows machine is

* Windows 10 1909
* VS 2017
* CUDA Driver is 451.48 (latest)
* cudnn 8

Both envs use https://github.com/davisking/dlib/commit/5a80ca9e5f8fea37b0cc92517415f276b66814f7.
It is a bit old but I guess it does not matter.

Do you have any idea or reason to explain this issue?

**Comment by davisking** [comment]
Thanks for the notes.  I just pushed some changes to github that will hopefully fix this.  Give it a go and let me know what happens.

**Comment by takuya-takeuchi** [comment]
@davisking 
Thank you for your quick support.
OK. I will check build on some CUDA version and operating system.

**Comment by takuya-takeuchi** [comment]
@davisking 

Thanks a lot.
I was successful to build on these envs.

# Ubuntu 16.04 (docker, base is nvidia/cuda:XXX-cudnnXX-devel-ubuntu16.04)

* Ubuntu 18.04 (Host machine)
* CUDA Driver is 450.51.05 (latest)
* GeForce GTX 750 Ti

Build configurations are

* cpu
* intel mkl 2019
* CUDA 9.2 + cudnn 7
* CUDA 100 + cudnn 7
* CUDA 10.1 + cudnn 7
* CUDA 10.2 + cudnn 7
* CUDA 11.0 + cudnn 8

# Windows (physical machine)

* Windows 10 1909
* VS 2017
* CUDA Driver is 451.48 (latest)
* GeForce GTX 1080

Build configurations are

* cpu
* intel mkl 2019
* CUDA 9.2 + cudnn 7
* CUDA 100 + cudnn 7
* CUDA 10.1 + cudnn 7
* CUDA 10.2 + cudnn 7
* CUDA 11.0 + cudnn 8

# OSX

* macOS Catalina
* Apple clang version 11.0.3

Build configurations are

* cpu
* intel mkl 2019
