### ISSUE TITLE
UDP Server

### ISSUE THREAD

**Issue by rhd** [davisking/dlib#214]
Hi Davis,

Have you ever considered writing a cross platform UDP server that has a similar API to your TCP server?

**Comment by davisking** [comment]
No.  At this point it seems like the best tool for that is asio.

**Comment by rhd** [comment]
Yea, you're probably right. One thing I really liked about your TCP server implementation was how easy it was to get going. asio is much harder to grok.

I'll close this issue. Thanks.

**Comment by davisking** [comment]
Yeah, asio is more complex initially.  You could probably create a similar
looking server API on top of asio though.
