### ISSUE TITLE
Import error after ubuntu 18.04 update

### ISSUE THREAD

**Issue by PatrikPatrik2** [davisking/dlib#2140]
Dblibe work perfectly on my Jetson with ubuntu 18.04. The system stated that there was an update of the system available, and after doing the update I can no longer run my application due to an import error with dlib:

`_landmarks, face_encodings, compare_faces, face_distance 
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: /usr/local/lib/python3.6/dist-packages/dlib-19.17.0-py3.6-linux-aarch64.egg/dlib.cpython-36m-aarch64-linux-gnu.so: symbol cudnnGetConvolutionBackwardDataAlgorithm version libcudnn.so.8 not defined in file libcudnn.so.8 with link time reference
`

what shall I do to eliminate the error?

**Comment by facug91** [comment]
Your system probably update cudnn from version 7.x to 8.0. This function `cudnnGetConvolutionBackwardDataAlgorithm` is removed in cudnn 8, but new version of dlib works with cudnn 8, so you should update your dlib version.
