### ISSUE TITLE
Error when run the c++ examples

### ISSUE THREAD

**Issue by sufeidechabei** [davisking/dlib#2142]
Hi, I meet the error when I run the webcam_face_pose_ex.cpp in C++ examples
![5731c484b3c2576f5967ce9572566e2](https://user-images.githubusercontent.com/26901984/89132535-7c1ea980-d547-11ea-9b19-a610f0de86d9.png)

Environment:
Visual Studio 2019
OpenCV:4.01
Laptop with a internal webcam.

**Comment by sufeidechabei** [comment]
If the image can't be showed , open this link:https://images2.imgbox.com/ac/da/dvm4nleS_o.png

**Comment by wpmanoj** [comment]
seems like problem with dlib installation. 

_In most cases, to use this library all you have to do is extract it somewhere, make sure the folder containing the dlib folder is in your include path, and finally add dlib/all/source.cpp to your project._ `http://dlib.net/compile.html`
