### ISSUE TITLE
Aligned memory

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2143]
Feature suggestion: implement a memory manager that aligns memory on 32,64,... byte boundaries. This is useful when doing FFTs for example.

**Comment by pfeatherstone** [comment]
@davisking Do you think this would be a useful feature? it is necessary if you want to do explicit SIMD math (SSE, AVX, NEON, etc) and it also helps the compiler do auto-vectorisation

**Comment by davisking** [comment]
SIMD math works fine without such tooling already.  For instance, the HOG
code uses SIMD instructions.  So this doesn't seem like something we need.

**Comment by pfeatherstone** [comment]
Ok. Do you want to keep this open for discussions? Otherwise happy if you want to close the issue.

**Comment by davisking** [comment]
That's fine.  If you have a specific piece of code where this makes things
faster that would be cool.

**Comment by pfeatherstone** [comment]
It's a habit I have to align memory so that when using SSE or AVX, I can do an aligned load, instead of an unaligned load. Also, I'm used to using FFTW which encourages the use of aligned memory for speedy computation. But for BLAS libraries, i'm willing to accept if makes near to no difference.

**Comment by pfeatherstone** [comment]
Sorry i didn't close this sooner.
