### ISSUE TITLE
Arbitrary FFT sizes

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2144]
Feature suggestion: allow the fft routine to do arbitrary sized FFTs. Let FFTW, lapack, BLAS or whatever do the magic of choosing the correct kernels for the input

**Comment by pfeatherstone** [comment]
Just realised browsing through the code that FFTW is not used because of thread safety and FFTW plans. Creating plans isn’t thread safe but executing them is! Maybe first thing would be to implement a global cache of FFTW plans which is guarded by a global reader-writer lock and use FFTW. When creating plans use a write-lock, when executing plans, use a read-lock.

**Comment by pfeatherstone** [comment]
I don’t mind submitting a PR at some point but might end up in a long battle with the author with regards to incomplete or bad documentation on my behalf and lack of unit tests. So if someone who is used to submitting PRs to dlib is comfortable doing so, then please do.

**Comment by pfeatherstone** [comment]
Once this is done, dlib can choose the right FFTW plan based on the type of input (fft size, aligned memory, in-place, strategy (estimate, measure,...), ...) from the cache.

**Comment by pfeatherstone** [comment]
Hopefully you don’t end up with a global cache exploding. Doubt it...

**Comment by davisking** [comment]
There isn't much to document to make dlib::fft() take arbitrary sizes.  You just remove the comment saying only some sizes are allowed. Some unit tests would be needed though, but that isn't hard either.

Anyway, unless there is something new in fftw it can't be used.  Just having dlib apply a global lock when it does fftw plan creation doesn't solve the problem, since other code in a program may well use fftw directly and therefore not apply the same global lock.  FFTW just needs to provide an API that doesn't depend on global variables in a non-thread safe way.  I mean, I'm open to suggestions, but last I looked at FFTW I don't see how it could possibly be used without the possibility of creating a race condition between whatever we do in dlib and what some other library might do with FFTW.

**Comment by pfeatherstone** [comment]
I hadn’t thought about other pieces of code using FFTW directly. Yes I see your point. Hmm. It’s a shame since FFTW is stupidly fast and I don’t think it will ever remove global variables, that’s it. So might have to look at other implementations. I bet a lot of BLAS libraries use FFTW under the hood anyway but could be wrong.

**Comment by pfeatherstone** [comment]
Maybe kissfft is a candidate. @davisking what do you think ?

**Comment by davisking** [comment]
Yeah, kissfft seems fine.   Note that dlib already links to the Intel MKL
for FFTs, which I imagine is faster than kissfft.  But the issue here is
the following.  Dependencies like this in dlib are optional, and dlib's
built in FFT code doesn't support arbitrary sizes.  So the contract for
functions like dlib::fft() require power of two input sizes regardless of
what backend is used.  To remove the power of two size requirement we have
to make dlib::fft() always work with any input size.  That is, it should
never matter what backend is used. The Intel MKL, kissfft, or whatever is
packaged with dlib by default.

So a reasonable approach here is to put kissfft into the dlib git
repository and replace dlib's built in FFT code with the kissfft code, so
arbitrary fft sizes are always allowed.  Then add some unit tests for
non-power-of-two size inputs.  This should be easy.  The only detail to
attend to is renaming the symbols in kissfft so they don't clash with other
people who already use dlib and kissfft.  That is, we don't want users to
get multiply defined symbol errors because they are suddenly compiling two
separate copies of the kissfft code into their applications.  To fix this,
just switch kiss_fft.c to kiss_fft.cpp and put everything inside the dlib
namespace.  I just tried doing this and kissfft builds without any errors
right off the bat, which is nice.  They aren't doing anything that's C99 or
specifically non-C++.

Finally, it's worth checking if kissfft is faster than the current dlib fft
code for power of two sized inputs.  The current dlib code isn't ultra
optimized, but it's not bad either.  So it may well be appropriate to call
kissfft only for non-power of two input sizes.  I don't know, but this
should be benchmarked to see before throwing out the existing code entirely.

Anyway, if you want to make a pull request that does this that would be
cool.

**Comment by pfeatherstone** [comment]
Thank you. I’ll check with my partner if I’m allowed to do it this weekend. My balls are tightly kept in a small purse.

**Comment by pfeatherstone** [comment]
@davisking on a similar note, have you considered adding a DSP module to dlib? IIR filters, FIR filters, resamplers, mixers, equalisers, AGC, (de)modulators, FFTs of course, and various other bits and bobs? Or is that not an interest of yours or not within the scope of dlib ? For example there could be some dlib “frontend” function calls using the liquiddsp backend to get going, using the lovely dlib::matrix container as well. Could also build the functions from scratch given a bit more time. Maybe this should be in a separate thread.

**Comment by pfeatherstone** [comment]
That would be a lot of work for documentation and unit tests.

**Comment by davisking** [comment]
I am not personally interested in adding those things to dlib.  But if
someone made high quality pull requests that added them that would be
neat.  Such PRs would have to maintain dlib's "all dependencies are
optional" philosophy though.  So something that just skinned over some
other library with functions in dlib:: isn't a good addition to dlib.

**Comment by pfeatherstone** [comment]
Okidok

**Comment by pfeatherstone** [comment]
How does dlib’s fft implementation work with matrix expressions? It’s not obvious to me in the code if the expression is evaluated before going into the fft function.

**Comment by davisking** [comment]
You see the code for dlib::fft()?  In matrix_fft.h:410?

**Comment by pfeatherstone** [comment]
Is it obvious from the declaration:
```
template <typename EXP>
    matrix<typename EXP::type> fft (const matrix_exp<EXP>& data)
```
Sorry, if i've missed something.
Or will the following expression evaluate all preceding matrix expression templates before doing the FFT ? :
```
matrix<typename EXP::type> temp(data);
```
Maybe my question wasn't clear. My concern was about the dlib::matrix object doing lazy evaluation and whether the aggregated expression is evaluated before going into the FFT. Does that make sense? You mention lazy evaluation in the documentation here: http://dlib.net/linear_algebra.html#matrix

**Comment by davisking** [comment]
`matrix<typename EXP::type> temp(data);` makes a copy of the input `data` matrix.  It's just saying `matrix<double> temp(data)` or `matrix<float> temp(data)`.  `temp` is an independent copy, completely disconnected from `data`.

**Comment by pfeatherstone** [comment]
You mention in the documentation about the dlib::matrix object how expressions get accumulated without being evaluated. You mention how sometimes temporary objects need to be created in order to avoid unnecessary computation. You explained this well with the example M*(M+M+M+M+M+M). In that case, the 6 additions need to be evaluated and stored in a temporary object before doing the multiplication. My concern was wether an aggregated expression also needed to be evaluated to a temporary object before going into the FFT.

**Comment by pfeatherstone** [comment]
Maybe this is not a worry and I’m being overly fussy.

**Comment by davisking** [comment]
Right, a temporary is needed for that reason. But the code does this. `temp` is the temporary.

**Comment by pfeatherstone** [comment]
Gotcha.

**Comment by pfeatherstone** [comment]
Having another look at this. What do you think is the best way to get both float and double working? So far i have a separate .cpp file for both float and double. The contents are:
```
#undef kiss_fft_scalar
#define kiss_fft_scalar float
#include "kiss_fft.cpp"

void kiss_fft_1d(const std::complex<float>* in,  std::complex<float>* out,  int n, int sign)
{
    kiss_fft_cfg cfg = kiss_fft_alloc(n, sign == +1 ? 1 : 0, 0, 0);
    kiss_fft(cfg, (const kiss_fft_cpx*)in, (kiss_fft_cpx*)out);
    kiss_fft_free(cfg);
}
```

and 
```
#undef kiss_fft_scalar
#define kiss_fft_scalar double
#include "kiss_fft.cpp"

void kiss_fft_1d(const std::complex<double>* in, std::complex<double>* out, int n, int sign)
{
    kiss_fft_cfg cfg = kiss_fft_alloc(n, sign == +1 ? 1 : 0, 0, 0);
    kiss_fft(cfg, (const kiss_fft_cpx*)in, (kiss_fft_cpx*)out);
    kiss_fft_free(cfg);
}
```

but there are functions like ```kiss_fft_alloc``` which do not have ```kiss_fft_cfg``` or ```kiss_fft_cpx``` arguments so you get multiple definitions of the same function.

What's the best way to handle this? I want to make sure that dlib works with both float and double, using kissfft, and with minimal hacking at kissfft.

**Comment by pfeatherstone** [comment]
Wrap the entire code in a MACRO namespace, like ```kiss_fft_scalar_namespace```, then for float for example have:
```
#undef kiss_fft_scalar
#define kiss_fft_scalar float
#undef kiss_fft_scalar_namespace
#define kiss_fft_scalar_namespace float_np
#include "kiss_fft.cpp"

void kiss_fft_1d(const std::complex<float>* in,  std::complex<float>* out,  int n, int sign)
{
    float_np::kiss_fft_cfg cfg = float_np::kiss_fft_alloc(n, sign == +1 ? 1 : 0, 0, 0);
    float_np::kiss_fft(cfg, (const float_np::kiss_fft_cpx*)in, (float_np::kiss_fft_cpx*)out);
    float_np::kiss_fft_free(cfg);
}
```

??

**Comment by davisking** [comment]
Definitely don't use macros.  Make the scalar type a template argument or use function overloading.

**Comment by pfeatherstone** [comment]
Do you want to template kiss_fft or wrappers thereof ? I would like to minimise changes to kissfft so updating in the future can be fairly easy. The only way i could think of building kissfft for both float and double was to use the trick i describe https://github.com/davisking/dlib/issues/2144#issuecomment-731767508. But i get multiple definitions of the same functions...

**Comment by pfeatherstone** [comment]
> Definitely don't use macros. Make the scalar type a template argument or use function overloading.

I don't think templating the entire thing will work as there are a lot of #ifdef statements for FIXED_POINT. Well you could make it work but it would require hacking away at kiss_fft quite a bit, which i think we should avoid. Ideally, updating kiss_fft in the future should be a quick diff/meld job.

**Comment by pfeatherstone** [comment]
And overloading doesn't work for return types. so
```
kiss_fft_cfg kiss_fft_alloc(int nfft,int inverse_fft,void * mem,size_t * lenmem)
```
causes a problem.

**Comment by pfeatherstone** [comment]
Eigen have already refactored kiss here https://gitlab.com/libeigen/eigen/-/blob/master/unsupported/Eigen/src/FFT/ei_kissfft_impl.h

**Comment by pfeatherstone** [comment]
But doesn't support fixed point precision or SIMD. So reluctant to use Eigen's version

**Comment by davisking** [comment]
I don't quite follow though.  Isn't this just a matter of doing some find/replace on the kissfft code to make things template arguments or function overloads?

**Comment by pfeatherstone** [comment]
Yes that's true. It just requires refactoring a lot of kissfft. It would require a much more careful review than if we were only adding a couple lines of code here and there, refactored kiss_fft.c to kiss_fft.cpp and shoved everything in a namespace. But i guess it's necessary.

**Comment by pfeatherstone** [comment]
[kiss_fft.cpp.txt](https://github.com/davisking/dlib/files/5602135/kiss_fft.cpp.txt)
[kiss_fft.h.txt](https://github.com/davisking/dlib/files/5602136/kiss_fft.h.txt)

@davisking Is this what you had in mind roughly ?

**Comment by pfeatherstone** [comment]
Still need to implement multi-dimensional FFT. There's more code in kiss_fft that does this. Still need to implement SIMD. Could just use dlib's SIMD wrappers. Maybe need to plumb in fixed point FFT, but i doubt dlib cares. Need to put everything in the dlib namespace and countless unit tests.

**Comment by pfeatherstone** [comment]
I haven't done a super scientific benchmark with a range of sizes and devices, but even for powers of 2, kiss_fft seems to have a slight edge over dlib's internal implementation.

**Comment by davisking** [comment]
Yeah, that's what I had in mind.  Like make it C++ rather than C, so no macros or any of that kind of thing.  Also put an RAII face in front of it and make the plan a proper class. I.e. rather than the plan being an argument to a global function there should be some fft class that owns the methods for doing a fft and it just happens that its constructor creates plans.  But users should not know about or see any of that.

**Comment by pfeatherstone** [comment]
I think i might remove the functions that take a "plan" object and keep the "cached" versions. The plan creation will be done in the implementation details. Since this code will be used by dlib only,  i see no reason why there can't be some global thread safe caching of twiddles.

**Comment by pfeatherstone** [comment]
[kiss_fft.cpp.txt](https://github.com/davisking/dlib/files/5615841/kiss_fft.cpp.txt)
[kiss_fft.h.txt](https://github.com/davisking/dlib/files/5615842/kiss_fft.h.txt)

**Comment by davisking** [comment]
Yeah, that's what I mean. Just a normal template :+1:   Although you have to put templates in a header file, not a cpp file.  I would stick this stuff into its own file and reference both the unlicense and bsd license.  Seems like people should prefer the unlicense but who knows.  Just make it all clear it's kissfft.  Put the file in dlib/matrix/kiss_fft.h and then make dlib's fft function use it.

**Comment by pfeatherstone** [comment]
I put the templates definitions in the cpp file and then i do template specialisation for complex<float> and complex<double>. That way there is only one compilation unit. Probably don't need to template the declarations in the header file. Just write out the declarations for float and double explicitly, template the definitions, or at least the implementations details in the CPP file. Also that means i can have a single global thread safe cache in the cpp. If i were to put the global cache in the header file, every one would get their own cache, or at least all compilation units would get their own cache. That's not a problem in principle but when debugging you might get confused as to why you have several singletons for the cache.

**Comment by pfeatherstone** [comment]
@davisking Should we also put all the mkl stuff in its file like ```dlib/matrix/mkl_fft.h```. Then ```dlib/matrix/matrix_fft.h``` can #include the right header file using preprocessor macros?

**Comment by davisking** [comment]
Dlib's matrix library is all header only.  It would be good to keep it that way as many users depend on that.  

You can still have a single global static cache.  Code like
```
inline thing& get_thing()
{
   static thing obj;
   return obj;
}
```
returns a reference to a single global instance.


On second thought about files, just stick it all inside the existing matrix_fft.h file. The kisfft code can go in dlib::impl, replacing the existing fft code I wrote a long time ago and delete the fftw stuff that's commented out.  The MKL code can stay as is.

**Comment by pfeatherstone** [comment]
Don't you think it will get a bit cluttered with both MKL and kissfft code in a single file? I don't see any obvious reasons why we can't have ```dlib/matrix/kiss_fft.h```, ```dlib/matrix/mkl_fft.h``` and ```dlib/matrix/matrix_fft.h```. And inside ```dlib/matrix/matrix_fft.h``` there will be something like:
```
#ifdef MKL
#include "mkl_fft.h"
#else
#include "kiss_fft.h"
#endif
```

**Comment by pfeatherstone** [comment]
> Dlib's matrix library is all header only. It would be good to keep it that way as many users depend on that.
> 
> You can still have a single global static cache. Code like
> 
> ```
> inline thing& get_thing()
> {
>    static thing obj;
>    return obj;
> }
> ```
> 
> returns a reference to a single global instance.
> 
> On second thought about files, just stick it all inside the existing matrix_fft.h file. The kisfft code can go in dlib::impl, replacing the existing fft code I wrote a long time ago and delete the fftw stuff that's commented out. The MKL code can stay as is.

I never knew that technique worked if you used ```inline```. Awesome.

**Comment by davisking** [comment]
> Don't you think it will get a bit cluttered with both MKL and kissfft code in a single file? I don't see any obvious reasons why we can't have `dlib/matrix/kiss_fft.h`, `dlib/matrix/mkl_fft.h` and `dlib/matrix/matrix_fft.h`. And inside `dlib/matrix/matrix_fft.h` there will be something like:
> 
> ```
> #ifdef MKL
> #include "mkl_fft.h"
> #else
> #include "kiss_fft.h"
> #endif
> ```

Sure, that’s fine too if it works. But the mkl code isn’t especially long and more importantly it doesn’t provide implementations for every code path. So the default implementation is still required.

**Comment by pfeatherstone** [comment]
@davisking Do we want to implement MKL DFTi descriptor caching and retrieval using ```DftiCopyDescriptor``` ? Not sure what the overhead of computing descriptors is. But if it's non-negligible, then could be worth it.

**Comment by pfeatherstone** [comment]
I've created PR https://github.com/davisking/dlib/pull/2253. It's not ready. But there's enough to get some feedback if that's possible.

**Comment by pfeatherstone** [comment]
In the future, if someone wants an fftw backend, here is one:
[fftw_fft.h.txt](https://github.com/davisking/dlib/files/5862284/fftw_fft.h.txt)
It has the same API as ```mkl_fft.h``` and ```kiss_fft.h```. Note that this works no problem if you link to ```libmkl_rt.so``` as MKL provides an FFTW compatible API with the added benefit that the planner is thread safe. If you link to FFTW libraries, make sure to uncomment the lines where ```fftwf_make_planner_thread_safe()``` and ```fftw_make_planner_thread_safe()``` are called. MKL libraries don't support these, but FFTW, from version 3.3.5 does.
