### ISSUE TITLE
matrix_add_exp does not work with complex<T> and T

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2145]
## Expected Behavior
I would expect the following to work:
```
dlib::matrix<complex<float>, 0, 1> buf1;
dlib::matrix<float, 0, 1> buf2;
... set sizes of buf1 and buf2 to be the same and set some values
dlib::matrix<complex<float>> buf3 = buf1 + buf2;
```

Note that pointwise_multiply uses 
```
typedef typename impl::compatible<typename M1::type, typename M2::type>::type type;
```
but matrix_add_exp does not. 

## Current Behavior
I get the compiler error:
/usr/local/include/dlib/matrix/matrix.h:363:13: error: static assertion failed: Failed assertion
             COMPILE_TIME_ASSERT((is_same_type<typename LHS::type, typename RHS::type>::value == true));

## Steps to Reproduce
```
dlib::matrix<complex<float>, 0, 1> cbuf;
    cbuf.set_size(10);
    cbuf = 1;
    cout << cbuf << endl;
    
    cout << endl;
    
    dlib::matrix<float, 0, 1> buf;
    buf.set_size(10);
    buf = 2;
    cout << buf << endl;
    
    dlib::matrix<complex<float>> res = cbuf + buf;
    cout << res << endl;
```

* **Version**: 
19.21

* **Where did you get dlib**: 
github

* **Platform**: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
64 bit

* **Compiler**: 
gcc/g++ 8.4.0

**Comment by davisking** [comment]
This is by design.  The underlying BLAS API doesn't support mixed type
expressions.  Dlib could do an implicit conversion but it would be easy for
someone to not realize this was happening and end up with surprisingly slow
code as a result.

**Comment by pfeatherstone** [comment]
Ok I see. How come mixed type is supported for pointwise multiplication ?

**Comment by pfeatherstone** [comment]
I guess doing stuff in the complex domain would be a bit of pain but as dlib doesn't necessarily concern itself with the complex domain it's not really an issue. I guess you could cast matrices where necessary and make it explicit.

**Comment by davisking** [comment]
Well, pointwise_multiply() never binds to the BLAS, so it's not a concern
there.  Also, you can convert a real matrix to a complex by doing
complex_matrix(m).

**Comment by pfeatherstone** [comment]
Thank you. I need to make a decision as to whether i use dlib as a matrix/tensor library. If i did, I might have to add quite a few functions to make my code work. I won't to avoid super bloated libraries like xtensor

**Comment by pfeatherstone** [comment]
I also like that dlib::matrix detects when to evaluate temporary expressions. I don't think tensor libraries like xtensor do that. You have to detect when to evaluate a temporary.

**Comment by pfeatherstone** [comment]
@davisking Did you ever benchmark dlib::matrix against Eigen, Blaze and others?

**Comment by davisking** [comment]
dlib uses some underlying BLAS library that you link to. Like the Intel
MKL.  So that will determine the speed to a large extent.  Matrices that
are known to be small at compile time will not go to BLAS and run just in
dlib's code.  I've generally observed that to be faster than Eigen.  And
the Intel MKL is certainly faster than Eigen.  I realize Eigen has long had
this web page of benchmarks where they claim to be faster than the Intel
MKL, but those are bogus. Eigen is not remotely in the same performance
category as the Intel MKL.

I have never used blaze though so I don't know how its performance
compares.  I would be pretty surprised if it could compete with the Intel
MKL though.  There also isn't any reason not to use a venor optimized BLAS
like the Intel MKL.  The Intel MKL is free, and similar free and high
quality BLAS are available for non-intel platforms.

**Comment by davisking** [comment]
Also note that the main job of dlib's matrix code is to map the equations a
user writes down to BLAS library calls.  Dlib does a bunch of symbolic
linear algebra, at compile time, to rework what you write into something
that can efficiently bind to BLAS.  It will also introduce temporaries at
the right places to avoid aliasing (unlike in eigen, where if you put a
matrix on both sides of = you just silently get the wrong answer), and also
to speed things up to avoid unnecessary repeated computations.

**Comment by pfeatherstone** [comment]
Do you check aliasing for all operations or just multiplication?

**Comment by davisking** [comment]
All operations. Dlib will never silently do the wrong thing. So aliasing is never ignored.

**Comment by pfeatherstone** [comment]
Love it. Thank you. Right i need to convince bosses to give me time to refactor a butt-load of code to some lovely matlab-like code.
