### ISSUE TITLE
module 'dlib' has no attribute 'get_frontal_face_detector'  error

### ISSUE THREAD

**Issue by Abhinav17-hub** [davisking/dlib#2147]
**While just importing face_recognition lib, I get the following error:**

AttributeError                            Traceback (most recent call last)
 in 
----> 1 import face_recognition

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\face_recognition\__init__.py in 
      5 __version__ = '1.2.3'
      6 
----> 7 from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\face_recognition\api.py in 
     15 ImageFile.LOAD_TRUNCATED_IMAGES = True
     16 
---> 17 face_detector = dlib.get_frontal_face_detector()
     18 
     19 predictor_68_point_model = face_recognition_models.pose_predictor_model_location()

AttributeError: module 'dlib' has no attribute 'get_frontal_face_detector'

**Uninstalling dlib & then re-installing it is one of the solution available on internet but I'm unable to uninstall the dlib library! 
Please provide a different solution.**

**Comment by mdrehanhussain** [comment]
Reinstall _Dlib_

**Comment by Chateying** [comment]
Face_Detection.detect_all

**Comment by Chateying** [comment]
ok,搞定，弄了好久~
![44444](https://github.com/user-attachments/assets/a9fee6c1-b2b1-4cb8-8e51-b063d92e4d88)
