### ISSUE TITLE
cmake mex OS X failing

### ISSUE THREAD

**Issue by ckalas** [davisking/dlib#215]
Trying to compile the example mex files in the `matlab` folder, but I get these errors.

> -- C++11 activated (compiler doesn't have full C++11 support).
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> MATLAB_ENG_LIBRARY
>     linked by target "example_mex_struct" in directory /Users/chris/git/dlib-19.1/dlib/matlab
>     linked by target "example_mex_function" in directory /Users/chris/git/dlib-19.1/dlib/matlab
>     linked by target "example_mex_callback" in directory /Users/chris/git/dlib-19.1/dlib/matlab
> MATLAB_MEX_LIBRARY
>     linked by target "example_mex_struct" in directory /Users/chris/git/dlib-19.1/dlib/matlab
>     linked by target "example_mex_function" in directory /Users/chris/git/dlib-19.1/dlib/matlab
>     linked by target "example_mex_callback" in directory /Users/chris/git/dlib-19.1/dlib/matlab
> mex_header_path
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib/matlab
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
>    used as include directory in directory /Users/chris/git/dlib-19.1/dlib
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/chris/git/dlib-19.1/dlib/matlab/CMakeFiles/CMakeOutput.log".

Any ideas?

EDIT: well looking in the cmake_mex_wrapper it only looks for windows paths, so the problem is in this file. still unsure how to proceed but I'm trying to fix the cmake file to actually find matlab.

**Comment by ckalas** [comment]
I got the cmake to not complain by changing these in the cmake_mex_wrapper:

`find_program(MATLAB_EXECUTABLE MATLAB_R2016a "/Users/xxx/Applications/")`
`set(MATLAB_HOME "/Applications/MATLAB_R2016a.app/")`
`set(MATLAB_LIB_FOLDERS
   "${MATLAB_HOME}/extern/lib/maci64/"
   "${MATLAB_HOME}/bin/maci64"
   )`

I manually set `MATLAB_HOME` because otherwise it was looking in `/Contents`. There is probably a  nicer way to get cmake to do this.

**Comment by davisking** [comment]
You need to set the MATLAB_HOME environment variable.  Either that or add the appropriate folders to the list of search paths in cmake_mex_wrapper.  Those don't really look like the right folders.  E.g. is `/Users/xxx/Applications/` really where the matlab executable file is located?
