### ISSUE TITLE
dlib installed via pip looking for incorrect CUDA version

### ISSUE THREAD

**Issue by manybodycpa** [davisking/dlib#2158]
I'm running Ubuntu 18.04 with CUDA (10.2) and dlib (19.19.0). In Python,

`import dlib`

works with pip version 19.0.3 but not with 20.2.2. The error reads:

`ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory`

## Steps to Reproduce

python3.7 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install dlib==19.19.0
python
import dlib

**Comment by davisking** [comment]
Something is wrong with your CUDA install.  `libcublas.so` is an important part of the CUDA runtime.  Reinstall CUDA.

**Comment by manybodycpa** [comment]
Thanks for your comment. However, everything works fine if I fix pip to version 19.0.3, suggesting that there is nothing wrong with my CUDA installation. The problem seems to be that dlib is looking for CUDA version 10.0 even though I have 10.2 installed.
