### ISSUE TITLE
how to detect more faces by setting  adjust_threshold equal to negative infinity

### ISSUE THREAD

**Issue by honghuCode** [davisking/dlib#216]
as 'object_detector_abstract.h' says ' This means that, for example, you can obtain the maximum possible number of detections by setting adjust_threshold equal to negative infinity.' So,how should I do?
should I modify the source code or set adjust_threshold in my program?

**Comment by davisking** [comment]
I would call the function and set that argument to a number rather than editing the code.

**Comment by honghuCode** [comment]
I am so sorry that i have clearly express my issues, this is the segment of face_detector.py 
'''
detector = dlib.get_frontal_face_detector()
 img = io.imread(f)
 dets = detector(img, 1)
'''
so what should I call the function and set that argument. 
ps : I am poor in python and c++

**Comment by davisking** [comment]
http://dlib.net/face_detector.py.html

**Comment by honghuCode** [comment]
@davisking yes,I have run the code of 'http://dlib.net/face_detector.py.html' and it performs well. I know I can set 'dets = detector(img, 1)' to detect more faces.Now,the question is that in 'object_detector_abstract.h'you say 'setting adjust_threshold equal to negative infinity' can detect more faces.so what should i do to detect more faces by setting ' adjust_threshold equal to negative infinity'

**Comment by davisking** [comment]
Read the example

**Comment by honghuCode** [comment]
please say the code of 'https://github.com/davisking/dlib/blob/master/dlib/image_processing/object_detector_abstract.h#L257'

It says '- #dets[i].detection_confidence >= adjust_threshold
                  This means that, for example, you can obtain the maximum possible number
                  of detections by setting adjust_threshold equal to negative infinity.'

I have read the example of 'https://github.com/davisking/dlib/tree/master/examples'  But i do not find a example about how to set the value of adjust_threshold.Could you please give me any examples or tell me how to set the value of adjust_threshold .
