### ISSUE TITLE
I think set_all_bn_inputs_no_bias broke something

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2163]
So, I was trying to stress test the `set_all_bn_inputs_no_bias` to make sure it works everywhere.
I've tried many architectures and setups and it works. However, when I tackled the imagenet training example, I got this error:
```
SCANNING IMAGENET DATASET

images in dataset: 1281167
step#: 0     learning rate: 0.1   average loss: 0            steps without apparent progress: 0

**************************** FATAL ERROR DETECTED ****************************

Error detected at line 938.
Error detected in file /home/adria/imagenet/dlib/dlib/cuda/cuda_dlib.cu.
Error detected in function void dlib::cuda::affine_transform(dlib::tensor&, const dlib::tensor&, const dlib::tensor&, float, float).

Failing expression was dest.size()==src2.size().


******************************************************************************

Aborted (core dumped)
```

The only changes I made to the example program are:
```
diff --git a/examples/dnn_imagenet_train_ex.cpp b/examples/dnn_imagenet_train_ex.cpp
index e672018d..2f1cee88 100644
--- a/examples/dnn_imagenet_train_ex.cpp
+++ b/examples/dnn_imagenet_train_ex.cpp
@@ -214,7 +214,8 @@ int main(int argc, char** argv) try
 
     cout << "\nSCANNING IMAGENET DATASET\n" << endl;
 
-    auto listing = get_imagenet_train_listing(string(argv[1])+"/Data/CLS-LOC/train/");
+    // auto listing = get_imagenet_train_listing(string(argv[1])+"/Data/CLS-LOC/train/");
+    auto listing = get_imagenet_train_listing(string(argv[1]));
     cout << "images in dataset: " << listing.size() << endl;
     const auto number_of_classes = listing.back().numeric_label+1;
     if (listing.size() == 0 || number_of_classes != 1000)
@@ -231,7 +232,7 @@ int main(int argc, char** argv) try
     const double momentum = 0.9;
 
     net_type net;
-    dnn_trainer<net_type> trainer(net,sgd(weight_decay, momentum));
+    dnn_trainer<net_type> trainer(net,sgd(weight_decay, momentum), {0, 1});
     trainer.be_verbose();
     trainer.set_learning_rate(initial_learning_rate);
     trainer.set_synchronization_file("imagenet_trainer_state_file.dat", std::chrono::minutes(10));
@@ -241,6 +242,7 @@ int main(int argc, char** argv) try
     // Since the progress threshold is so large might as well set the batch normalization
     // stats window to something big too.
     set_all_bn_running_stats_window_sizes(net, 1000);
+    set_all_bn_inputs_no_bias(net);
 
     std::vector<matrix<rgb_pixel>> samples;
     std::vector<unsigned long> labels;
```

That is, I changed the imagenet path, I setup the trainer to use 2 GPUs and called `set_all_bn_inputs_no_bias(net)`
It works if:
- remove bias and train on one GPU
- don't remove bias and train on any number of GPUs

But the combination of multiple GPUs without bias makes it crash. I also tried to make the same test on the 2nd introduction example, but there I don't get a crash with multiple GPUs and removing the bias.

**Comment by arrufat** [comment]
After playing a bit more with it, I found what was causing it, I need to call `set_all_bn_inputs_no_bias` **_before_** creating the trainer, otherwise I get a crash, but only if I am using multiple GPUs.
Any idea why?

**Comment by davisking** [comment]
Yeah that’s what should happen. The trainer replicates the network on all gpus. If you modify the network after that (the one you have is just one of them now) then the networks in use don’t all match anymore.

**Comment by davisking** [comment]
The error message could be better in this case though.

**Comment by arrufat** [comment]
That makes sense, thank you.

**Comment by davisking** [comment]
You might want to add a check in dnn/trainer.h:768 that all those tensors in `temp` are the same size.  You could then emit an error message more helpful in this case you ran into.

**Comment by arrufat** [comment]
Ah, yes thank you, I will try something. The error message should be along these lines, right?
_Tensor sizes don't match, make sure you didn't modify the network outside of the trainer_

**Comment by davisking** [comment]
Yeah, something like that.  Like "make sure you don't modify the network structure or number of parameters after constructing the trainer".

**Comment by davisking** [comment]
As an aside, I just realised I broke the visitor functions yesterday.  I just pushed a fix a moment ago though so they are working again.

**Comment by arrufat** [comment]
ah, thank you, I will submit a PR in a bit on top of your changes :)
