### ISSUE TITLE
Feature request : make the unit test framework parallelisable

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2164]
It would be nice if the unit test framework used dlib::thread_pool(std::thread::hardware_concurrency()) to run tests in parallel.

**Comment by davisking** [comment]
Why?

**Comment by pfeatherstone** [comment]
Much quicker to go through all the tests.

**Comment by davisking** [comment]
On travis-ci and appveyor?  Those take a long time because they build lots of variants.  It's the build time that's long.  The tests run plenty fast enough once built.

You should also only run the tests you care about rather than all of them.

**Comment by pfeatherstone** [comment]
OK fair. I'm just lazy and running all the tests. It's a good check anyway i think. Currently working on the PR for type_safe_union, and since that may be used in other places, running all tests is probably a good idea.

**Comment by pfeatherstone** [comment]
Not worth the hassle.
