### ISSUE TITLE
Illegal instruction in correlation tracker

### ISSUE THREAD

**Issue by akjoshi6** [davisking/dlib#2167]
I am facing this issue specifically on Docker for windows. It works fine on docker for ubuntu. Without docker, it works on both windows and linux.

## Expected Behavior
I am tracking people for a computer vision solution. Below snippet adds new person(bouding box) for tracking.
```
tracker = dlib.correlation_tracker()
rect = dlib.rectangle(int(startX), int(startY), int(endX), int(endY))
tracker.start_track(rgb, rect)
```

## Current Behavior
Application is crashing due to illegal instruction on start_track function. Application does not crash if start_track is commented. 

```
tracker = dlib.correlation_tracker()
rect = dlib.rectangle(int(startX), int(startY), int(endX), int(endY))
tracker.start_track(rgb, rect) #Illegal instruction
```

## Steps to Reproduce

Pull [this](https://hub.docker.com/layers/ufoym/deepo/all-py36-cpu/images/sha256-195b21f330a947d0c863d1bce273ef3daac67daac010c71eb4af6aa03813d94b?context=explore) docker image on Docker For Windows. Install dlib using pip and execute following snippet:

```
import dlib
import numpy as np

rgb = np.zeros([800,600,3],dtype=np.uint8)
tracker = dlib.correlation_tracker()
rect = dlib.rectangle(456, 392, 596, 640)
tracker.start_track(rgb, rect)
```

* **Version**: 19.20.0
* **Where did you get dlib**: https://pypi.org/project/dlib/
* **Platform**: Docker container on windows 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
* **Compiler**: gcc 7.5.0
python 3.6.9

**Comment by davisking** [comment]
You must be building dlib on a system with SSE4 (or similar special
instructions) and then running it in a context where they are not
available.  If you run the build on the target system it will auto detect
what instructions are available.

**Comment by akjoshi6** [comment]
I doubt if I got this right. Built a wheel on docker for ubuntu where it is running fine and used that wheel on Docker for windows (docker containers are same but system where docker is running is different). This didn't help.

**Comment by davisking** [comment]
Try building with --no USE_AVX_INSTRUCTIONS or --no USE_SSE4_INSTRUCTIONS

**Comment by akjoshi6** [comment]
Didn't work. This seems to be issue with that particular docker image only. Switched to another image to avoid this issue.
