### ISSUE TITLE
I get a error: illegal instruction (core dumped) when run my program on linux terminal with python

### ISSUE THREAD

**Issue by Rainy000** [davisking/dlib#217]
my codes as below:

import dlib
from scipy import misc
predictor_path = '/home/mylinux/002.jpg'
face_path = '/home/mylinux/shape_predictor_68_face_landmarks.dat'

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(predictor_path)
win = dlib.image_window()

img = misc.imread(face_path)
win.clear_overlay()
win.set_image(img)

dets = detector(img, 1)
print("Number of faces detected: {}".format(len(dets)))
dets = detector(img, 1)
print("Number of faces detected: {}".format(len(dets)))
for k, d in enumerate(dets):
       print("Detection {}: Left: {} Top: {} Right: {} Bottom: {}".format(
            k, d.left(), d.top(), d.right(), d.bottom()))
        # Get the landmarks/parts for the face in box d.
        shape = predictor(img, d)
        print("Part 0: {}, Part 1: {} ...".format(shape.part(0),
                                                  shape.part(1)))
        # Draw the face landmarks on the screen.
        win.add_overlay(shape)
win.add_overlay(dets)
dlib.hit_enter_to_continue()

I run it and get error( illegal instruction(core dumped) ),so I use ipython run it step-by-step,and i found when run the statement（shape = predictor(img,d)）,the error information occur.
Can someone give me some suggestions? thanks!

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework

**Comment by Rainy000** [comment]
@davisking   I  follow the guide of  Getting Started on Unix Variants, and finish "Easy build and install". After that I get  Boost binaries in the path: /home/mylinux/boost_1_61_0/PREFIX/lib, but the error occurs again at the same position when I run it.
Maybe I put the Boost binaries in the wrong path? Is that problem?

**Comment by davisking** [comment]
I don't know.  You should look at the build output and see what boost it is finding.  It's probably not finding the one in your home folder. 

If you are using a linux variant like ubuntu I would just install boost and python with the package manager.  Then they will be compiled correctly.

**Comment by Rainy000** [comment]
@davisking Yeah，I am using ubuntu 14.04.1. Anyway, thank you for your detailed answers, I will try it!

**Comment by davisking** [comment]
I use ubuntu 14.04 as well.  If I do `pip install dlib` it works.  Assuming I've installed boost and python via apt-get.
