### ISSUE TITLE
Casting dlib::vectorstream* to std::istream* causes a bug when calling seekg

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2174]
## Expected Behavior
I expect the following to work:
```
    {
        vector<char> b(10);
        dlib::vectorstream ss(b);
        int ret = ss.peek();
        assert(ret == 0);
        ss.seekg(0);
        ret = ss.peek();
        assert(ret == 0);
    }
    
    {
        vector<char> b(10);
        std::istream* ss = new dlib::vectorstream(b);
        int ret = ss->peek();
        assert(ret == 0);
        ss->seekg(0);
        ret = ss->peek();
        assert(ret == 0);
        delete ss;
    }
```

## Current Behavior
The last assert statement `throws`. ret is equal -1

## Steps to Reproduce
Run the code above.

* **Version**: latest
* **Where did you get dlib**: installed from source form github
* **Platform**:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
* **Compiler**: gcc 8.4.0

**Comment by pfeatherstone** [comment]
boost::interprocess::basic_vectorstream<std::vector<char>> does't have this behaviour.

**Comment by pfeatherstone** [comment]
Basically trying to extend the functionality of ```proxy_serialize``` and ```proxy_deserialize``` to work with ```vector<char>``` and ```string```. I replaced ```std::shared_ptr<std::oftream>``` with ```std::unique_ptr<std::ostream>``` . That works fine with files. Then added constructors to take ```vector<char>``` and reset the smart pointers to consume ```dlib::vectorstream``` pointers. Serialisation works, but deserialisation doesn't. I think i tracked down the problem to the ```seekg``` bug which this issue is all about.

**Comment by davisking** [comment]
Yeah, this isn't supported.  But it should be.  What's missing is an
implementation of seekoff and seekpos in the streambuf. See
https://en.cppreference.com/w/cpp/io/basic_streambuf if you would like to
make a PR for this.

**Comment by pfeatherstone** [comment]
Just looked at how boost does it. Doesn't look trivial.

**Comment by davisking** [comment]
Don't look at the boost code.  I'm sure it's wildly over complex.

**Comment by pfeatherstone** [comment]
It would be nice if ```dlib::vectorstream``` was split into ```dlib::ivectorstream```, ```dlib::ovectorstream``` and finally ```dlib::vectorstream```, so we can use const references where possible.

**Comment by pfeatherstone** [comment]
Ok, @davisking, does this look right:
```
pos_type seekpos(pos_type pos,
                             std::ios_base::openmode mode = std::ios_base::in | std::ios_base::out)
            {
                return seekoff(pos - pos_type(off_type(0)), std::ios_base::beg, mode);
            }

            pos_type seekoff(off_type off, std::ios_base::seekdir dir,
                             std::ios_base::openmode mode = std::ios_base::in | std::ios_base::out )
            {
                assert(dir == std::ios_base::beg);
                read_pos = off;
                return pos_type(off);
            }
```
I don't know for sure if ```seekoff``` will only ever be called by ```seekpos```. C++ streams are like black magic to me. Hence why i've left the assert statement

**Comment by pfeatherstone** [comment]
Using the above now works with ```proxy_(de)serialize```

**Comment by davisking** [comment]
That's close to right, but `seekoff` can definitely be called by something other than `seekpos`.  You would need to implement it as demanded in the standard.  I.e. do what cppreference.com says.

**Comment by pfeatherstone** [comment]
Moving this to PR https://github.com/davisking/dlib/pull/2173
