### ISSUE TITLE
CUDA seems only be used in python dlib not linux c++

### ISSUE THREAD

**Issue by mxgbs** [davisking/dlib#2176]
Hi,

I have used mmod dlib detection. When it's used via python, the GPU is automatically used. However, when it's used via c++, it seems the GPU is not used and the speed is quite slow. The same linux box with CUDA installed. The dlib path is also included. Please advice. Thank you.

**Comment by ndtreviv** [comment]
Help is more likely if you can provide:

1. The commands you used to build dlib
2. The output of those commands

In my experience, the best way of installing dlib is via cmake as a shared library so it can be referenced from your own program's CMakeLists file.

Once you have installed CUDA and cuDNN, and completed the post-install instructions correctly (by adding relevent things to the PATH and LD_LIBRARY_PATH), cmake will automatically detect CUDA and cuDNN and build dlib to us them.

An example cmake command to build dlib as a shared library with CUDA and cuDNN support is:

```
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DUSE_AVX_INSTRUCTIONS=ON -DBUILD_SHARED_LIBS=1 -DCUDA_HOST_COMPILER=/usr/bin/gcc-8 ../
```
You should see from the output whether or not dlib has then successfully picked up the configuration of CUDA and cuDNN, and if not why not (the output really is very helpful in telling you what you haven't done).

For example, you should see something like:

```
-- Found CUDA: /usr (found suitable version "10.1", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Building a cuDNN test project to check if you have the right version of cuDNN installed...
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
```
 
Then you can build:
```
cmake --build . --config Release
```
