### ISSUE TITLE
How get confidence rate(detection score) in face detection ?

### ISSUE THREAD

**Issue by mv2050arshad** [davisking/dlib#2184]
Hi, first i want to appreciated you for your great project.

How i get detection_confidence of face detection base on get_frontal_face_detector() in c++? 
I have seen most of your examples but still can not find a way to access each face detection rate(detection score). but i can set it easily by threshold
.

**Comment by davisking** [comment]
Ask it for a `rect_detection`.  `rect_detection` has the confidence value in it.

**Comment by mv2050arshad** [comment]
oh yahhhh, thats cool. thank you very much. i got it.
But, it seems confidence value having different value in compare to Threshold parameter that we have set for detecting face which are in range[0-1]!can you give me a what is the different between them ? 

thanks in advance

**Comment by davisking** [comment]
The threshold parameter is not bounded between 0 and 1.

**Comment by mv2050arshad** [comment]
Ok thanks, i will read more again about it.
