### ISSUE TITLE
Unable to compile master branch on VS2013

### ISSUE THREAD

**Issue by LorenaGdL** [davisking/dlib#219]
Hello there,

I just downloaded the master branch with latest changes as I wanted to test the new DNN detector example. However, I am unable to compile Dlib in Visual Studio 2013, on my Windows 10 64bit machine.

Errors are found in `algs.h`, in the `relational_operators` namespace:
```
/algs.h(286): error C2144: syntax error : 'bool' should be preceded by ';'
/algs.h(287): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
/algs.h(287): error C2143: syntax error : missing ',' before '&'
/algs.h(289): error C2803: 'operator >' must have at least one formal parameter of class type
/algs.h(289): error C2805: binary 'operator >' has too few parameters
/algs.h(297): error C2144: syntax error : 'bool' should be preceded by ';'
/algs.h(298): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
/algs.h(298): error C2143: syntax error : missing ',' before '&'
```
I am aware that DNN samples can only be compiled under full C++11 compilers (excluding thus VS2013). Might these errors be related to that too?

In any case, are you planning on adding support for such compilers in the (near) future?

Thanks

**Comment by e-fominov** [comment]
DNN will not work in 2013. With some hacks its possible to run some parts of it in CPU mode with VS 2015
The problem you are describing is the leak of support of "constexpr" keyword in VS2013 and this problem does not exists in VS 2015. Please try latest Update 5 of VS 2013 - this problem should be solved

**Comment by LorenaGdL** [comment]
OK, I will try to update VS. In any case, this error appeared while compiling Dlib as is, and therefore some patch/warning should be applied for next release for non-compatible compilers.

Pitty about DNNs, they seemed promising...

**Comment by davisking** [comment]
dlib v19.1 works in visual studio 2013.  But trying to avoid C++11 is too
onerous, so dlib v19.2 will require visual studio 2015 or newer for
everything and will include obvious compiler error messages for older
compilers.

Also, the visual studio dev team has told me they are working to fix the
bugs in visual studio that prevent it from compiling dlib's DNN code.  So
look forward to that.

**Comment by LorenaGdL** [comment]
Understood, I'll try to update to VS2015 as soon as possible. And great news about DNN, I hope the wait isn't too long.

Thank you for your prompt answers. I'll close this down.
