### ISSUE TITLE
About cuda implementation for loss_multiclass_log_per_pixel_weighted

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2190]
Hi, I was going to add a cuda implementation for `loss_multiclass_log_per_pixel_weighted` when I faced the following problem:

The [`weighted_label`](https://github.com/davisking/dlib/blob/20a1477209e1fd28b0f19dbca263508d5c0b9af1/dlib/dnn/loss.h#L373-L385) `struct` is not accessible from the cuda files, since it's defined in [dnn/loss.h](../blob/master/dlib/dnn/loss.h).

I was wondering where I should put this struct so that it's visible from everywhere.
Also, if I am going to do this, would you like to do it like in `loss_mean_squared_per_channel_and_pixel_`?

https://github.com/davisking/dlib/blob/20a1477209e1fd28b0f19dbca263508d5c0b9af1/dlib/dnn/loss.h#L3466-L3470

That is, moving all the code to `cuda_dlib.{h,cu}` and `cpu_dlib.{h,cpp}`. Would you also like me to do the same for `loss_multiclass_log_per_pixel`?

**Comment by davisking** [comment]
Yeah, doing it like the other similar layers is good.  I don't have a strong opinion about where exactly `weighted_label` is located though.

**Comment by arrufat** [comment]
Closing as of #2194
