### ISSUE TITLE
Is there any direct dependency between face detection bounding box and face prediction landmarks?

### ISSUE THREAD

**Issue by chanduthedev** [davisking/dlib#2191]
Hi @davisking,

I would like to know is there any relation between face detection bounding box and face landmarks?
Can I directly use face landmarks directly without face detection?
or is it required to get face bounding box before getting face landmarks?

In the below pictures, in Image1 all landmarks are with in the bounding box, but in image2, Some of the chin landmarks are outside bounding box. Could you please help to understand this?

Image1:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/6205951/94111780-18de3300-fe77-11ea-960d-43bbe75526df.png">

Image2:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/6205951/94111747-0cf27100-fe77-11ea-990e-891491423207.png">

Thanks in advance.

**Comment by davisking** [comment]
I'm not sure what is being asked.  You need to tell the landmark code where the face is, so yes, you need a box on the face.  If you don't know where a face is how could this possibly work?  There might be 10 faces in an image in any location.  How would the landmark code know which face to look at without a box?  But in any case, please read the docs.  The API requires a bounding box as input.

The boxes must be placed on the face with the box annotation style used to train the face landmark system.  Other than that it doesn't matter how you get the box.  And as you noted, landmark points can be outside the box.

**Comment by chanduthedev** [comment]
I understand that landmark points can be outside the box basing on the face.
Than you @davisking  for the response.
