### ISSUE TITLE
Question : why does dlib::read_write_mutex not use pthread_rwlock_t under the hood on linux?

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2196]
Question : why does ```dlib::read_write_mutex``` not use ```pthread_rwlock_t``` under the hood on linux?
The current implementation of ```dlib::read_write_mutex``` uses ```dlib::mutex``` and ```dlib::signaler```. That could be used on non-posix platforms, but on Linux, why not use ```pthread_rwlock_t``` as a shortcut. Perhaps it would be more efficient?

**Comment by pfeatherstone** [comment]
I think that's what ```std::shared_mutex``` does in C++17

**Comment by davisking** [comment]
It's just because it's simpler as `pthread_rwlock_t` isn't available on windows.

**Comment by pfeatherstone** [comment]
Do you think there is benefit in having two kernels, one for linux that uses ```pthread_rwlock_t``` and one for everything else that uses the current implementation.There would be less overhead using ```pthread_rwlock_t``` . Currently ```dlib::read_write_mutex``` has 1 mutex, 1 signaler, 2 unsigned longs, and 2 bools. There would be less logic. My gut feeling is that ```pthread_rwlock_t``` might be  more efficient, but i could be wrong. Is it a problem if ```sizeof(dlib::read_write_mutex)``` is different between platforms. Does that class as ABI breaking?

**Comment by davisking** [comment]
Unless there is a notable measured performance improvement I would rather leave it alone.  The current code is simple and having one code path, rather than divergent implementations for each platform naturally makes things more uniform tested and less likely to have variation from one platform to another.  That said, if it's way faster then sure, it's cool to switch.

**Comment by pfeatherstone** [comment]
Cool i'll test at some point. I'm using dlib::read_write_mutex in anger at the moment coz i can't use C++17. So i need to measure at some point.

**Comment by pfeatherstone** [comment]
Never got round to doing this. Sod it.
