### ISSUE TITLE
Digitialocen droplet rise an error of installing dlib

### ISSUE THREAD

**Issue by bawantha** [davisking/dlib#2203]
## Expected Behavior
pip3 install dlib should work successfully  

## Current Behavior
( I'm  running on a web console sorry I cannot copy text )

![Screenshot 2020-10-07 123953](https://user-images.githubusercontent.com/17080593/95339475-bbfc6700-08d1-11eb-9f43-6928d53e926a.png)
![Screenshot 2020-10-07 134108](https://user-images.githubusercontent.com/17080593/95339494-bef75780-08d1-11eb-91da-c363f64589ec.png)

## Steps to Reproduce
```
$ sudo apt-get update
$ sudo apt-get install build-essential cmake
$ sudo apt-get install libopenblas-dev liblapack-dev 
$ sudo apt-get install libx11-dev libgtk-3-dev
$ sudo apt-get install python3 python3-dev python3-pip
$ pip install numpy
$ pip install dilb
```

* **Version**: not specific versiton
* **Where did you get dlib**: pip install dlib
* **Platform**: Digitalocen  Ubuntu 20.04 (LTS) x64  droplet  1 vCPUs 1GB / 25GB Disk
* **Compiler**: beyond my knowledge

**Comment by bawantha** [comment]
Increasing droplet size resolve this issue

**Comment by azarudeenpn** [comment]
> Increasing droplet size resolve this issue

can you specify the droplet size needed for successful installation?
