### ISSUE TITLE
code from dnn_mmod_face_detection_ex crashes on gpu if image is too small

### ISSUE THREAD

**Issue by spiegelball** [davisking/dlib#2205]
## Expected Behavior
`auto dets = net(img) `
works on image of size 250x250 if run with cpu version. gpu version works if image is upsampled to a size > 1800x1800.

## Current Behavior
Call `auto dets = net(img) ` with gpu version on image of size 250x250. It crashes with dlib::cudnn_error and access reading violation. This is strange because it works with upscaled image.

## Steps to Reproduce
Will try to reproduce outside propriatary environment...

* **Version**: 19.20.99
* **Where did you get dlib**: dlib.net
* **Platform**: Windows 10, x64
* **Compiler**: Visual Studio 15 2017 x64

**Comment by davisking** [comment]
I am unable to reproduce this. Are you sure you don't just have a broken cuda install?

**Comment by spiegelball** [comment]
Just upgraded to 19.21 and cuda 8 and the error is gone. Thanks for getting back!
