### ISSUE TITLE
CMake looks like it works with pip now

### ISSUE THREAD

**Issue by dvf** [davisking/dlib#2207]
I noticed that there's a comment here saying that the pip install for cmake is busted, but it worked for me using Ubuntu 20.04 5.4.0-48-generic.

https://github.com/davisking/dlib/blob/master/setup.py#L237

Could we submit a PR to include this now?

**Comment by davisking** [comment]
It worked for some platforms and not for others.  I forget which though :|  It might have been windows.  So if you test it out on windows and it works then yeah, that would be a cool PR :)
