### ISSUE TITLE
error: cuDNN V5.0 OR GREATER NOT FOUND. DLIB WILL NOT USE CUDA

### ISSUE THREAD

**Issue by timotheecour** [davisking/dlib#221]
this is an upstream error pointing to dlib : https://github.com/Homebrew/homebrew-science/issues/4228#issuecomment-245368172

**Comment by davisking** [comment]
Is this a question about something?

**Comment by timotheecour** [comment]
it's a bug report originally reported in homebrew but moved here as per the last post: "Your output seems to indicate a bug in CMake figuring out where you cuda compiler lives. It seems worth opening an issue on the dlib tracker."

I didn't want to duplicate the error but here it is:

after `ccmake ..` i get: 
```
CMake Error at dlib/cmake_utils/test_for_cudnn/find_cudnn.txt:10 (get_filename_component):
get_filename_component unknown component /usr/local/cuda/lib64/libcublas_device.a
Call Stack (most recent call first):  dlib/CMakeLists.txt:461 (include)
```

however:

after that it seems i can still build (`click c then g then make -j8`)

running `cmake ..` first fails with same error; running it again succeeds.

**Comment by davisking** [comment]
That error doesn't make sense.  get_filename_component() is part of cmake.
It's as if you have a version of cmake that doesn't support it, but there
is a check in the CMakeLists.txt that you have at least cmake 2.8.4, which
I know has get_filename_component().

**Comment by e-fominov** [comment]
@timotheecour , do you have CUDNN 5.0 installed? CUDNN != CUDA
Also if you have CUDNN 4 installed and CUDNN 5 both installed on the same system - you can get this problem, if CUDNN4 is installed (or may be restored somehow) after CUDNN5 - it rewrites headers and library files

Try unpack CUDNN 5 in some folder and put it as param to -DCMAKE_PREFIX_PATH when building dlib

**Comment by davisking** [comment]
@e-fominov You have gotten that specific error message (from line 10 of find_cudnn.txt)?  That's a really odd message for a CUDNN install problem.  Maybe CUDA_CUBLAS_LIBRARIES is a list rather than one thing, which is odd in and of itself.  @timotheecour What is in CUDA_CUBLAS_LIBRARIES?  Put a statement like this in the cmake file and see what it says: `message("what is cuda cublas libraries?  ${CUDA_CUBLAS_LIBRARIES}")`

**Comment by grefab** [comment]
Had the same problem, but I'm not a cmake guru, so I thought I just got something wrong, maybe some problem with my cmake installation. I patched it in an ugly, system specific way: https://github.com/grefab/dlib/commit/27a7415e4e938f8a5854d2c228ffd74fd38ba45e

**Comment by grefab** [comment]
Checked with the message stuff above:
`what is cuda cublas libraries? /usr/local/cuda/lib/libcublas.dylib;/usr/local/cuda/lib/libcublas_device.a`

So it seems to be a list, that explains the error.

**Comment by davisking** [comment]
Yeah.  Does putting "" around it make it work properly?

**Comment by grefab** [comment]
Yep. Here you go: https://github.com/davisking/dlib/pull/230

**Comment by davisking** [comment]
Sweet, thanks :)

**Comment by anguoyang** [comment]
I have the same problem under windows:)

**Comment by davisking** [comment]
What error?

**Comment by anguoyang** [comment]
C++11 activated.
Enabling SSE2 instructions
Searching for BLAS and LAPACK
Looking for cuDNN install...
*** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
*** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
Configuring done

**Comment by anguoyang** [comment]
all other issues have been corrected by me, except this one. "cannot find cudnn" is not an error, dlib could be compiled with visual studio successfully, however, the cudnn module could no longer use the cuda(use dlib_use_cuda is always off, and cannot be changed into on)

**Comment by davisking** [comment]
Do you have cuda and cudnn installed?

**Comment by anguoyang** [comment]
yes, I have also other source code which used cuda and cudnn, e.g. caffe.
I have install cuda sdk 7.5 and 8.0, for cudnn, in windows, only need to unzip into a folder and point to it.

**Comment by davisking** [comment]
Well you have to put cuDNN somewhere cmake can find it, like in the cuda install folder.  Or tell CMAKE_PREFIX_PATH the path to it.  But you can't just unzip it to some random folder on your computer and expect it to be found.

**Comment by anguoyang** [comment]
how to tell CMAKE_PREFIX_PATH the path to it? sorry I am not a guru on cmake. 
I just created an entry in cmake gui, but it did not work.
CMAKE_PREFIX_PATH--->path--->my path for cudnn

**Comment by davisking** [comment]
`cmake .. -DCMAKE_PREFIX_PATH=whatever`

**Comment by anguoyang** [comment]
ok, thank you, i will try it.

**Comment by anguoyang** [comment]
There is no error in the command line mode:
-----------------------------------------------------------------
d:\myproject\dlib\examples\build64>cmake .. -DCMAKE_PREFIX_PATH=D:\cuda
-- C++11 activated.
-- Enabling SSE2 instructions
-- Configuring done
-- Generating done
-- Build files have been written to: D:/myproject/dlib/examples/build64
-------------------------------------------------------------
however,when i open the visual studio project, there is no cuda library or header files included, and the project build without cuda.
i opened the cmake gui again, and found the dlib_use_cuda option could not be changed into on

**Comment by davisking** [comment]
Regenerate the cmake project.  You can't just run the command again on an existing one.  So delete the build folder and do it again.

**Comment by anguoyang** [comment]
I have deleted the whole build folder and re-do with "cmake .. -DCMAKE_PREFIX_PATH=d:\cuda", and get the same error as cmake gui:
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++11 activated.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling SSE2 instructions
-- Searching for BLAS and LAPACK
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5 (found suitable version "7.5", minimum required is "7.5")
CMake Warning at D:/myproject/dlib/dlib/CMakeLists.txt:516 (message):
  You have CUDA installed, but we can't use it unless you put visual studio
  in 64bit mode.


-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
OpenCV not found, so we won't build the webcam_face_pose_ex example.

it seems that cmake do not save the cache information which the gui version generated, sorry i am not good at cmake.

**Comment by davisking** [comment]
Read the messages. 

> -- Searching for BLAS and LAPACK
> -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5 (found suitable version "7.5", minimum required is "7.5")
> CMake Warning at D:/myproject/dlib/dlib/CMakeLists.txt:516 (message):
**_ You have CUDA installed, but we can't use it unless you put visual studio
> in 64bit mode._**
> 
> -- *** cuDNN V5.0 OR GREATER NOT FOUND. DLIB WILL NOT USE CUDA. ***
> -- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
> OpenCV not found, so we won't build the webcam_face_pose_ex example.

**Comment by anguoyang** [comment]
as far as I know, the visual studio itself is a 32-bit program, the cmake message really puzzled me

**Comment by anguoyang** [comment]
is it possible to set CMAKE_PREFIX_PATH by the gui version? I just added CMAKE_PREFIX_PATH as a path in gui cmake and point cudnn path to it, but it did not work

**Comment by davisking** [comment]
http://bfy.tw/AIkE ;)

**Comment by anguoyang** [comment]
haha, thank you so much:)
it seems(i am not sure) worked on command line building by using:
cmake -G "Visual Studio 14 2015 Win64" D:\myproject\dlib\examples -DCMAKE_PREFIX_PATH=d:\cuda

yes, the compiling process is successful, however, when i run the binary exe files(eg. dnn_face_recognition_ex), it did not ask for cuda*.dlls, so, maybe it has not been compiled with cuda.
further more, when I opened the solution with visual studio, there are still no cuda related configurations...

**Comment by davisking** [comment]
If the cmake output says it's using cuda then it's using cuda.

**Comment by anguoyang** [comment]
ok, thank you, i will try to use depends to find the dependencies.

**Comment by smajida** [comment]
platform: Jetson TX1
Ubuntu 16.04
CUDA 8.0
---------
error description:
Eventhough I have added Cudnn folder to to CMAKE_PREFIX_PATH and cmake has found it, in the end CMAKE is not using CUDNN and therefore CUDA.

```bash
(facerec-cv3.3-np1.13.1-py2.7) nvidia@tegra-ubuntu:~/projects/packages/dlib/build$ echo $PATH
/home/nvidia/.virtualenvs/facerec-cv3.3-np1.13.1-py2.7/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/games:/usr/local/games
(facerec-cv3.3-np1.13.1-py2.7) nvidia@tegra-ubuntu:~/projects/packages/dlib/build$ echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64:/home/nvidia/softwares/nccl/build/lib:/home/nvidia/softwares/compiledOpenCV/3.3.0/lib:/home/nvidia/softwares/cudnn/8.0-6.0/lib64
```
```bash
cmake .. -DCMAKE_PREFIX_PATH=/home/nvidia/softwares/cudnn/8.0-6.0:/home/nvidia/softwares/cudnn/8.0-6.0/include:/home/nvidia/softwares/cudnn/8.0-6.0/lib64/libcudnn.so; cmake --build .
```
I tried to manually add cudnn include in CMakelist.txt file, but in the end I got the following error:
```bash
[ 97%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dnn/cuda_data_ptr.cpp.o
[ 98%] Building CXX object dlib/CMakeFiles/dlib_shared.dir/dnn/gpu_data.cpp.o
make[2]: *** No rule to make target '/home/nvidia/softwares/cudnn/8.0-6.0/lib64/libcudnn.so', needed by 'dlib/libdlib.so.19.7.99'.  Stop.
CMakeFiles/Makefile2:124: recipe for target 'dlib/CMakeFiles/dlib_shared.dir/all' failed
make[1]: *** [dlib/CMakeFiles/dlib_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sziraqui** [comment]
I faced similar problem on **Ubuntu 18.04**. I had cuda and cuddn working fine on cuda samples. But dlib's cuda test program failed to build with **gcc-7** (default in Ubuntu 18.04). I **installed gcc-5 and g++-5**, ran update-alternatives and selected gcc-5 in manual mode. Now dlib builds without errors. The error occurs because cudnn does not support gcc 6 and later.


Detailed steps:
````
sudo apt install gcc-5 g++-5
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5
sudo update-alternatives --config gcc

**Comment by shab07** [comment]
> Well you have to put cuDNN somewhere cmake can find it, like in the cuda install folder. Or tell CMAKE_PREFIX_PATH the path to it. But you can't just unzip it to some random folder on your computer and expect it to be found.

Can you help me in understanding the location of cudnn in my system(Ubuntu 16.04). 
How to set the the CMAKE_PREFIX_PATH ?

**Comment by ndtreviv** [comment]
I installed cuDNN (v8) from the downloaded .deb package, and it ended up in: `/usr/lib/x86_64-linux-gnu/`

So I added this to the `CMAKE_PREFIX_PATH`:
```
$ cmake -DUSE_AVX_INSTRUCTIONS=ON -DBUILD_SHARED_LIBS=1 -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/ ../
```

But still I get the error:
```
-- *** cuDNN V5.0 OR GREATER NOT FOUND.                                                       ***
-- *** Dlib requires cuDNN V5.0 OR GREATER.  Since cuDNN is not found DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.                ***
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
```

**Comment by ndtreviv** [comment]
FYI I resolved it. I had only installed cuDNN Runtime Library. I needed to install the Developer Library as well, then it all worked.

**Comment by Longman-Stan** [comment]
Make sure you really have that **Developer Library**, otherwise the build won't work!

**Comment by netrosec** [comment]
> FYI I resolved it. I had only installed cuDNN Runtime Library. I needed to install the Developer Library as well, then it all worked.

How did you install the developer library?
