### ISSUE TITLE
Detect method in python

### ISSUE THREAD

**Issue by glenncameronjr** [davisking/dlib#222]
Is detect method of dlib exposed via the Python bindings?

**Comment by davisking** [comment]
What detect method?

**Comment by glenncameronjr** [comment]
The detect method of the SVM. I am trying to take the boxes returned from dlib.find_candidate_object_locations and run the detector at the specific locations.

**Comment by davisking** [comment]
What is "The SVM"?  There are a whole lot of machine learning functions in dlib, many related to SVMs.   Do you have a specific C++ function you are talking about?

**Comment by glenncameronjr** [comment]
Right now I am using dlib.simple_object_detector to find an object in frames of a video and it is working. However it is running a bit slow. I want to use dlib.find_candidate_object_locations,  use the smaller number of boxes from it, and then run the detector part of dlib.simple_object_detector on them. By detector I mean the method that is checking to see if the box is a match with my model. I don't want to run the detector on all the boxes returned from dlib.simple_object_detector.

**Comment by davisking** [comment]
That will be much slower than calling the simple object detector as there
will be massive recomputation.  Think about it this way.  All those pixels
that overlap in candidate boxes get reprocessed multiple times.  There are
also other problems beyond that that make this not something that will
work.

You should probably have a look at this blog post about making this stuff
run faster:
http://www.learnopencv.com/speeding-up-dlib-facial-landmark-detector/

**Comment by glenncameronjr** [comment]
That is very helpful info. Thank you.
