### ISSUE TITLE
How to enable/disable SSE2 / AVX / CUDA etc. when building with "python setup.py install"?

### ISSUE THREAD

**Issue by josephernest** [davisking/dlib#2222]
I'm building with 

    python setup.py install

How to enable/disable SSE2 / AVX etc. when building for Python with `python setup.py install`?

**Comment by davisking** [comment]
They are enabled by default if your computer supports them.

**Comment by josephernest** [comment]
Thank you for your answer @davisking.

**Comment by josephernest** [comment]
Thank you for your answer @davisking 

Also, I guess it's ok, but just to be sure: is it compiled in `Release` by default (and not `Debug`, as mentioned in http://dlib.net/faq.html#Whyisdlibslow) when doing `python setup.py install`?

___

Last thing: on a low-end i5 laptop without any CUDA GPU, what is the order of magnitude of time spent to process a 3000x2000 px JPG file?

For example, when using this code:

```
import face_recognition, glob, time

myself = face_recognition.load_image_file('me.jpg')
myself_encoding = face_recognition.face_encodings(myself)[0]

for f in glob.glob(r'D:\Documents\mes images\2020\**\*.jpg', recursive=True):
    s = time.time()
    image = face_recognition.load_image_file(f)
    for e in face_recognition.face_encodings(image):
        print(f, face_recognition.compare_faces([myself_encoding], e))
    print(time.time() - s)
```

here is the elapsed time, in seconds, for each image (most of them are standard 3000x2000 JPG or same order of magnitude):

```
0.6990399360656738
8.505486726760864
10.666609764099121
8.479485273361206
0.30701756477355957
10.680610656738281
11.201640844345093
0.5730326175689697
0.350020170211792
0.2630150318145752
0.6260356903076172
1.0320591926574707
3.36619234085083
0.6630380153656006
3.206183433532715
```

Why so much differences ? (From 0.6 second to 10.6 seconds to process one single image)

**Comment by davisking** [comment]
Dlib's `setup.py install` will always build in release mode with all available optimizations on.
