### ISSUE TITLE
Error in loading the mmod_rear_end_vehicle_detector.dat model post training 

### ISSUE THREAD

**Issue by siriusmehta** [davisking/dlib#2224]
Steps to reproduce:

retrained model using **dnn_mmod_train_find_cars_ex.cpp** and tried running the model using **dnn_mmod_find_cars_ex.cpp** 

**Error**:

An error occurred while trying to read the second object from the file 'mmod_rear_end_vehicle_detector.dat'
No more objects were in the stream.

The correct model can be obtained from URI.

Can you please throw some light what am I doing wrong as I am only following the comments provide for training in dnn_mmod_train_find_cars_ex.cpp ?

**Comment by arrufat** [comment]
The original trained model has a shape predictor to perform bounding box regression. If you retrained using the example program, you didn't train one, so you can't deserialize it:

https://github.com/davisking/dlib/blob/83921b390e6cf7575b99b5b3145fc039be375aea/examples/dnn_mmod_find_cars_ex.cpp#L49-L54.

Remove line 49 and change line 54 to:
``` c++
deserialize("mmod_rear_end_vehicle_detector.dat") >> net;
```

You should also modify this loop to display the rectangles from the `mmod_rect` instead:

The original trained model has a shape predictor to perform bounding box regression. If you retrained using the example program, you didn't train one, so you can't deserialize it:

https://github.com/davisking/dlib/blob/83921b390e6cf7575b99b5b3145fc039be375aea/examples/dnn_mmod_find_cars_ex.cpp#L63-L74

Which means replacing the inside of the loop with:
``` c++
win.add_overlay(d.rect, rgb_pixel(255,0,0));
```

**Comment by siriusmehta** [comment]
Thanks @arrufat !

Highly appreciate for your quick response. By incorporating the above modifications it ran successfully.

So, as in the find cars example how can we train shape predictor along with CNN and trainer as in dnn_mmod_find_cars_ex.cpp and similar to mmod_rear_end_vehicle_detector.dat so that 
 
deserialize("mmod_rear_end_vehicle_detector.dat") >> net >> sp; 

works. 

Is it the single model architecture which which deserializes to **net** and **sp** together ?

**Comment by davisking** [comment]
You can ask the mmod trainer to do shape regression. Try that first.  The only use the shape_predictor if you find it more convenient.

**Comment by siriusmehta** [comment]
Sure @davisking !

Thanks for the help!

**Comment by arrufat** [comment]
Ah, this just crossed my mind, @siriusmehta if you retrain the detector with bounding box regression in the [mmod_options](http://dlib.net/dlib/dnn/loss_abstract.h.html#mmod_options), make sure you use the latest version from github, since it contains a fix that makes it work much better, as discussed #2153.
