### ISSUE TITLE
pkg-config returns redundant shared libraries when installed as a shared library

### ISSUE THREAD

**Issue by yurivict** [davisking/dlib#2225]
I have ```dlib-19.21``` built as a shared libarary (-DBUILD_SHARED_LIBS=ON).

pkg-config returns all libraries that ```dlib``` depends on:
```
$ pkg-config --libs dlib-1
-L/usr/local/lib -ldlib -pthread /usr/local/lib/libSM.so /usr/local/lib/libICE.so /usr/local/lib/libX11.so /usr/local/lib/libXext.so /usr/local/lib/libgif.so /usr/local/lib/libpng.so /usr/lib/libz.so /usr/local/lib/libjpeg.so /usr/local/lib/libsqlite3.so 
```

In case of a shared library the correct list of ldflags is: ```-L/usr/local/lib -ldlib -pthread```. The libraries you depend on are already in the dependency set of ```libdlib.so``` and users don't need to add them. In case of a static library the returned list is correct because all users of a static library should link to all dependencies of that static library.

**Comment by davisking** [comment]
Sure.  If you want to submit a PR that improves the list that would be cool :)
