### ISSUE TITLE
extract_image_chip is rounding float results if the interpolation type is bilinear

### ISSUE THREAD

**Issue by spatker** [davisking/dlib#2228]
## Expected Behavior
The function `extract_image_chip` should not round the output to fit into an integer type if the input and output is a float matrix and the interpolation tpye is `dlib::interpolate_bilinear()`.

## Current Behavior
Currently after the commit a83242014e467377fc2afb8942a708bc55b83fe9, the output is rounded to fit into an integer type. Before this commit the output was handeld correctly to be a float.
This behaviour is present in every version of dlib after this commit.
As far as I can tell this does not affect the `resize_prev_to_tagged` DNN layer (at least on CUDA) even though it uses bilinear interpolation also.

## Steps to Reproduce
Run this example program with these versions:
* a83242014e467377fc2afb8942a708bc55b83fe9
* 693aa0a71930e39c2432d6490c649f6675cfdd4a
```C++
#include <dlib/rand.h>
#include <dlib/image_transforms/assign_image.h>
#include <dlib/dnn.h>
#include <iostream>

// from dnn_semantic_segmentation_train_ex.cpp
dlib::rectangle make_random_cropping_rect(
    const dlib::matrix<float>& img,
    dlib::rand& rnd
)
{
    double mins = 0.466666666, maxs = 0.875;
    auto scale = mins + rnd.get_random_double()*(maxs-mins);
    auto size = scale*std::min(img.nr(), img.nc());
    dlib::rectangle rect(size, size);
    dlib::point offset(rnd.get_random_32bit_number()%(img.nc()-rect.width()),
                 rnd.get_random_32bit_number()%(img.nr()-rect.height()));
    return dlib::move_rect(rect, offset);
}


// also from dnn_semantic_segmentation_train_ex.cpp
int main(){
    dlib::matrix<float> img(5,5);
    img = 
         1.1,  2.2,  3.3,  4.4,  5.5,
        11.1, 12.2, 13.3, 14.4, 15.5,
        21.1, 22.2, 23.3, 24.4, 25.5,
        31.1, 32.2, 33.3, 34.4, 35.5,
        41.1, 42.2, 43.3, 44.4, 45.5;

    dlib::matrix<float> chip;
    dlib::rand rnd(0);

    const auto rect = make_random_cropping_rect(img, rnd);
    const dlib::chip_details chip_details(rect, dlib::chip_dims(4, 2));

    dlib::extract_image_chip(img, chip_details, chip, dlib::interpolate_bilinear());
    std::cout << chip << std::endl;
}
```

The output of the a83242014e467377fc2afb8942a708bc55b83fe9 version is:
```
12 14 
18 21 
25 27 
32 34 
```

While the output of the 693aa0a71930e39c2432d6490c649f6675cfdd4a version is:
```
   12.2    14.4 
18.8667 21.0667 
25.5333 27.7333 
   32.2    34.4
```

* **Version**: a83242014e467377fc2afb8942a708bc55b83fe9 and every version after
* **Where did you get dlib**: github
* **Platform**: Ubuntu 18.04.5 LTS
* **Compiler**: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by davisking** [comment]
Thanks for reporting this.  I just pushed a change that should fix it.

**Comment by spatker** [comment]
Thank you, it is fixed!
