### ISSUE TITLE
Question: dlib::pipe vs moodycamel::BlockingConcurrentQueue ? 

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2230]
@davisking Have you ever benchmarked ```dlib::pipe``` against lock-free concurrent queues, like ```moodycamel::BlockingConcurrentQueue```? I've submitted a PR to [concurrentqueue](https://github.com/cameron314/concurrentqueue) which adds ```dlib::pipe``` to their benchmarks but the benchmarks could, in theory, be biased towards the use cases of the author. I understand that ```dlib::pipe``` is probably more flexible and has nice functions like ```wait_until_empty()```, ```disable_enqueue()```, etc, but it would be interesting to know if you've ever come across use-cases where ```dlib::pipe``` was struggling to meet performance and a lock-free queue was necessary?
Thanks.

**Comment by pfeatherstone** [comment]
The author of concurrentqueue mentions that the motivation behind the library was other concurrent queues were struggling to meet performance when egressing audio samples from hardware. Have you ever done something similar and noticed that dlib::pipe was not meeting performance criteria.

**Comment by pfeatherstone** [comment]
By the way, I love ```dlib::pipe```, it's my favorite object in dlib. Just curious how it performs against other concurrent queues. Most of the time, benchmarks are skewed since they always show that the author's implementation is fastest. Like every single BLAS library claims to be the fastest.

**Comment by davisking** [comment]
I've never looked at `moodycamel::BlockingConcurrentQueue`.  But yes, a non-blocking lock free queue can be faster than a blocking queue.  `dlib::pipe` is a blocking queue that also has a bounded size (i.e. enqueue calls on a full pipe will block).  So it's not really the same kind of thing.  My general opinion is that lots of people misuse lock-free queues.  Most of the time what you really want is a blocking and bounded queue.  Only in relatively special situations do you want a lock-free queue.

Like in particular, if you are streaming data through a queue what do you do when the producer is faster than the consumer?  I've seen code that just lets their queue grow and grow until memory is exhausted.  That's not cool.  Similarly, consumers often want to wait until there is data in the queue, which fundamentally requires waiting sometimes.

**Comment by pfeatherstone** [comment]
ok thanks
