### ISSUE TITLE
Feature request: fPIC option in CMakeLists.txt

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2231]
Could fPIC be an option in CMakeLists.txt? Looking through CMakeLists.txt, it looks like it's being set when building a shared library or python bindings. It would be great if you could also force it. I'm not best suited to do cmake PRs. So if someone speaks native cmake, that would be great.

**Comment by davisking** [comment]
This is something you should set in your own cmake files though.  You shouldn't need dlib's cmake files to set it.

**Comment by pfeatherstone** [comment]
Okidok. Though I'm using plain old make files...

**Comment by davisking** [comment]
Oh. Well the. You should be able to set it when you build dlib using cmake’s normal options. Like you can tell cmake to build with whatever compile settings you want.

**Comment by pfeatherstone** [comment]
okidok
