### ISSUE TITLE
Question about modifying console_progress_indicator

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2232]
Hi, I would like to add an option so that it can print to std::cerr (or a custom std::ostream). This can be useful when piping the output, to a file, since we don't want the output of the progress.

So I was wondering if you'll be okay with that. I was thinking about doing it like you do it in the `cmd_line_parser::print_options`, which has an overload with a custom `std::ostream`. Would that be ok?

**Comment by davisking** [comment]
Yeah, so long as it's an optional thing that doesn't break existing user code that sounds cool :)
