### ISSUE TITLE
Manually adjust the starting points of correlation tracker

### ISSUE THREAD

**Issue by iPsych** [davisking/dlib#2235]
Hello,
the dlib correlation tracker works well, but fails when it try to detect faces with 'outlier' shape (i.e. exceptionally long face).
Is there any way to feed the tracker 68 correct points manually defined, and proceed the tracking?

Bests,
J.

**Comment by davisking** [comment]
I don't understand the question.  *Every* use of the correlation tracker requires the user to manually give a starting location to track.  So you should be doing this already.

**Comment by iPsych** [comment]
@davisking 
My mistake. I confused dlib.correlation_tracker and dlib.shape_predictor.
Is there any possible way to provide some manually annotated 'correct' coordinates of 68points of face and let the shape_predictor refer the information for last frames in movie tracking?
In other word, use shape_predictor just like correlation tracker using manual input in initial frame.

Bests,
J.

**Comment by davisking** [comment]
Yes, you give the shape predictor the box that you think contains the
face.  You can figure out the box from the locations of the points.
