### ISSUE TITLE
undefined reference to symbol 'dgesvd_'

### ISSUE THREAD

**Issue by berylyellow** [davisking/dlib#2237]
cmake works fine, but the problem occurs when linking dlib to another project.

After doing cmake ..  when I do make，error comes like this :

Scanning dependencies of target detect
[ 50%] Building CXX object CMakeFiles/detect.dir/detect.cpp.o
[100%] Linking CXX executable detect
/usr/bin/ld: CMakeFiles/detect.dir/detect.cpp.o: undefined reference to symbol 'dgesvd_'
//usr/lib/x86_64-linux-gnu/liblapack.so.3: 无法添加符号: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/detect.dir/build.make:100: recipe for target 'detect' failed
make[2]: *** [detect] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/detect.dir/all' failed
make[1]: *** [CMakeFiles/detect.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How to solve it? Thanks~

**Comment by TungTT1311** [comment]
> cmake works fine, but the problem occurs when linking dlib to another project.
> 
> After doing cmake .. when I do make，error comes like this :
> 
> Scanning dependencies of target detect
> [ 50%] Building CXX object CMakeFiles/detect.dir/detect.cpp.o
> [100%] Linking CXX executable detect
> /usr/bin/ld: CMakeFiles/detect.dir/detect.cpp.o: undefined reference to symbol 'dgesvd_'
> //usr/lib/x86_64-linux-gnu/liblapack.so.3: 无法添加符号: DSO missing from command line
> collect2: error: ld returned 1 exit status
> CMakeFiles/detect.dir/build.make💯 recipe for target 'detect' failed
> make[2]: *** [detect] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/detect.dir/all' failed
> make[1]: *** [CMakeFiles/detect.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> How to solve it? Thanks~

Sorry, have you fixed it?

**Comment by azizalibasic** [comment]
I fixed this by doing the following:

in my CMAKE:

```cpp
find_package(dlib)

target_link_libraries(
    YOUR_LIB
        PUBLIC
            dlib::dlib
)
```

Instead of:
```cpp
find_package(dlib)

target_link_libraries(
    YOUR_LIB
        PUBLIC
            dlib
)
```
