### ISSUE TITLE
whether SVM is used in dlib object detect?has dlib made negative samples ?

### ISSUE THREAD

**Issue by wangxinjun56** [davisking/dlib#2239]
call_separation_oracle_on_all_samples ；
get_num_samples();
has dlib made negative samples when object detect？

i have debug the sourcecode; found that ,there are no  negative samples;
so i doubt that  whether SVM is used in dlib object detect.

**Comment by wangxinjun56** [comment]
negative samples ？ who knows？

**Comment by wangxinjun56** [comment]
negative samples ？ who knows？

**Comment by wangxinjun56** [comment]
negative samples ？ who knows？

**Comment by davisking** [comment]
How it works is explained here https://arxiv.org/pdf/1502.00046.pdf

**Comment by wangxinjun56** [comment]
@davisking thanks very much
