### ISSUE TITLE
Updating the existing annotation

### ISSUE THREAD

**Issue by Zumbalamambo** [davisking/dlib#2242]
I have created an xml for annotating the image using the following command,

`imglab -c mydataset.xml ./
`

After annotating the images, I have added a few more images to the dataset. How do I update the "mydataset.xml" with the newly added images without having to remove the existing annotations?

**Comment by arrufat** [comment]
Checkout `imglab -h`.

I would create a new dataset with all the new images with the command you listed above, and then merge both datasets with `imglab --add mydataset1.xml mydataset2.xml`. But again, check the help (and backup everything before!)
