### ISSUE TITLE
Retrain dlib 68-facial landmark model with different face detector fail.

### ISSUE THREAD

**Issue by Joshua0128** [davisking/dlib#2248]
I recently used dlib **train_shape_predictor** to retrain custom shape predictor on another face detector instead of dlib detector (use hog).
But the training, testing error(MSE) is pretty large like 200-2000(Original testing error nearly 4~10 in the same dataset but different bounding box value). 
I am confused about the reason cause the large difference and how can I get better training result close to the official training result. 

## Current Behavior
The best result with the training argument below:
```
options.tree_depth =4
options.nu = 0.01
options.cascade_depth = 14
options.feature_pool_size = 100
options.num_test_splits = 300
options.oversampling_amount = 1
options.oversampling_translation_jitter = 0
options.be_verbose = True  
```
best result
```
training error : 259.722175759723 
testing error : 613.351754455251 
```

## Steps to Reproduce
1. use openvino with model  **face-detection-retail-0004** to detect face within the image of the dataset.
2. find out the closest bounding box to the label bounding box and replace the bounding box data within the xml file of ibug_300W_large_face_landmark_dataset.
3. use train_shape_predictor with options below:
```
options.tree_depth =2
options.nu = 0.25
options.cascade_depth = 14
options.feature_pool_size = 750
options.num_test_splits = 200
options.oversampling_amount = 1
options.oversampling_translation_jitter = 0.25
options.be_verbose = True  
```
and the result is 
```
training error : 1811.40350662135
testing error : 3005.46610831576
```
## ENV
dlib : 19.6.1
python : 3.6.10
openvino version: 2020.4.287
face-detector model : face-detection-retail-0004

**Comment by davisking** [comment]
It is very likely your dataset is just busted in some way.  You should
visually inspect your data to make sure it's not wrong.

**Comment by Joshua0128** [comment]
Thank you for your reply!

I try to visual inspect my data.
![image](https://user-images.githubusercontent.com/14936390/100563034-6011f580-32f8-11eb-86bb-1c5332544e73.png)
[bounding box]
cropped by openvino : red 
label from ibug : green
[landmark]
landmark point from my xml : blue
landmark point from ibug xml : white

Is there any requirement for the bounding box property(like shape, center)?

Thank a lot!

**Comment by Arritmic** [comment]
Hello,
Yes, there is requirement related to the bounding box. They training model starts a cascaded-fashion topology by fitting a mean shape in the face rectangle in the first stage at every image in the training dataset. That means that there is a projection of a normalized face mean shape into the bounding box used to train the model. If your (red) boxes are not consistent, the model probably is going to fail more, and you probably would need much more samples and data augmentation to achieve the "same" performance.

Find some hints in the functions inside of the `shape_predictor.h`: 
```
inline point_transform_affine unnormalizing_tform (
            const rectangle& rect
        )
        /*!
            ensures
                - returns a transform that maps (0,0) to rect.tl_corner() and (1,1) to
                  rect.br_corner().
        !*/
        {
            std::vector<vector<float,2> > from_points, to_points;
            to_points.push_back(rect.tl_corner()); from_points.push_back(point(0,0));
            to_points.push_back(rect.tr_corner()); from_points.push_back(point(1,0));
            to_points.push_back(rect.br_corner()); from_points.push_back(point(1,1));
            return find_affine_transform(from_points, to_points);
        }
```

Cheers.

**Comment by Joshua0128** [comment]
@Arritmic Thanks for all your help！

**Comment by TimSC** [comment]
Since the method uses boosting, it is sensitive to bad training data.
