### ISSUE TITLE
imglab PNG assertion fail on windows

### ISSUE THREAD

**Issue by grisevg** [davisking/dlib#225]
I can build dlib itself just fine, but when I build imglab, I get PNG assertion:
`dlib-master\dlib\image_saver/save_png.h(64): error C2338: Failed assertion`
It's the latest master and I build it with vs14 x64:
```
cd build
cmake -G "Visual Studio 14 2015 Win64" ..
cmake --build . --config Release
```

**Comment by davisking** [comment]
There is a bug in newer versions of cmake on windows that causes this.  If
you run `cmake .` again in the build fold and then try to build it should
work.  I've tried to find a workaround for this a few times to no avail.
What version of cmake are you using by the way?

**Comment by grisevg** [comment]
Hey it worked, big thanks! I have cmake 3.6.1
