### ISSUE TITLE
[Feature Improvement] add `should_stop` callback to dlib::find_max_global and friends

### ISSUE THREAD

**Issue by robertu94** [davisking/dlib#2250]
@davisking Thanks for your great C++ library!

My colleagues and I wrote a modified version of dlib's find_max_global that allowed the user to pass a callback `should_stop` which accepts a function-like object which has a method `bool operator()(double y)` where y is the result of the function evaluation, and it returns true if the search should stop.

We use this to provide coordinated early termination in two cases:

1. When we know that the user is willing to accept an solution with an objective that is past a certain threshold.  In this case we can stop as soon we find this objective.
2. We invoke find_max_global from multiple MPI ranks (read separate processes, so memory is not shared).  We pass different subdomains to each rank, and want to terminate early if one of the subdomains finds a solution that meets the user's requirements, we can stop all of the searches at their next iteration.

We used this technique to great success in our paper [FRaZ: A Generic High-Fidelity Fixed-Ratio Lossy Compression Framework for ScientificFloating-point Data](https://arxiv.org/pdf/2001.06139.pdf).  We would like to upstream this feature if possible, but wanted to see if there was interest before we go through the effort to update our fork.

**Comment by davisking** [comment]
Cool, yeah, seems like a good idea :)

Just make sure you don't break existing users, so having a default for that option that keeps the existing behavior would do it.
