### ISSUE TITLE
New DNN visitor interface broke program compilation.

### ISSUE THREAD

**Issue by lvella** [davisking/dlib#2254]
It seems that the new visitor interface introduced in afe19fcb8bef83335274c28d1a6ffac421ef1888 introduced some bug that broke the compilation for my program in a way cannot begin to comprehend.

## Expected Behavior
All well behaved, interface abiding programs should compile after changes introduced by commit afe19fcb8bef83335274c28d1a6ffac421ef1888.

## Current Behavior

If try to build my project [lvella/dlib-rnn](https://github.com/lvella/dlib-rnn) using any dlib version after afe19fcb8bef83335274c28d1a6ffac421ef1888, I get a metric ton of template errors, that is too big for GitHub, so I pasted it [here](https://pastebin.com/x9VEBLeT).

## Steps to Reproduce

1. Build and install dlib, branch master;
2. Clone [lvella/dlib-rnn](https://github.com/lvella/dlib-rnn);
3. Type make. There is just one .cpp file, so you can invoke the compiler directly:
```
g++ -c rnn-sample.cpp -std=c++17 `pkg-config dlib-1 --cflags` -pthread
```

* **Version**: branch master, bisected to commit afe19fcb8bef83335274c28d1a6ffac421ef1888
* **Where did you get dlib**: GitHub
* **Platform**: Ubuntu 20.10, x86-64
* **Compiler**: Got the error both with Clang 11 and GCC 10.2.0, both installed from Ubuntu's repository

**Comment by davisking** [comment]
Thanks for reporting this.  I just pushed a fix.  Give it a whirl, should be all good now :)

**Comment by lvella** [comment]
Oddly enough, it did fix for Clang 11, but not for GCC 10.2.0.

The error output is [here](https://pastebin.com/bZ94UdEm). I guess it must be reported to GCC?

**Comment by arrufat** [comment]
Hi, I've just tried to build your code, and it builds fine on my machine with g++ 10.2 and latest dlib from master (but segfaults when I try to run it). Here's what I did:
```
$ git clone https://github.com/lvella/dlib-rnn
$ cd dlib-rnn
$ make
g++ -c rnn.h -std=c++17 `pkg-config dlib-1 --cflags` -pthread -Ofast -march=native -mtune=native
g++ -c rnn-sample.cpp -std=c++17 `pkg-config dlib-1 --cflags` -pthread -Ofast -march=native -mtune=native
g++ -o rnn-sample rnn-sample.o -std=c++17 `pkg-config dlib-1 --cflags` -pthread -Ofast -march=native -mtune=native `pkg-cofig dlib-1 --libs` -lopenblas
$ ./rnn-sample 
Segmentation fault (core dumped)

```

**Comment by lvella** [comment]
I am closing because I was the one to open. It is fixed.
