### ISSUE TITLE
python setup.py install is not hava -T flag?

### ISSUE THREAD

**Issue by int11** [davisking/dlib#2255]
i can build in c++ like this
mkdir build; cd build; cmake ..  -G "Visual Studio 16" -T  v140  -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1; cmake --build .

but it seem python version don't hava "-T v140" flag,

i have a installed vs2019 and msvc v140
how to use gpu in python ?

*****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***
-- ***   Change Dir: C:/dlib/build/temp.win-amd64-3.7/Release/dlib_build/cuda_test_build

   ***   Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && .NET Framework용 M
icrosoft (R) Build Engine 버전 16.8.2+25e4d540b

   ***   Copyright (C) Microsoft Corporation. All rights reserved.
   ***     Checking Build System
   ***     Building NVCC (Device) object CMakeFiles/cuda_test.dir/Debug/cuda_test_generated_cuda_test.cu.obj
   ***     cuda_test.cu
   ***   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\crt/host_config.h(143): **fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2013 and 2017 (inclusive) are suppo
rted!** [C:\dlib\build\temp.win-amd64-3.7\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]
   ***   CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored. [C:\dlib\build\temp.win-amd64-3.7\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]
   ***     CMake Error at cuda_test_generated_cuda_test.cu.obj.Debug.cmake:216 (message):
   ***       Error generating
   ***       C:/dlib/build/temp.win-amd64-3.7/Release/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//Debug/cuda_test_generated_cuda_test.cu.obj
   ***   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: 'C:\dlib\dlib\cmake_utils\test_for_cuda\cuda_test.cu'에 대한 사용자 지정 빌드가 종료되
었습니다(코드 1). [C:\dlib\build\temp.win-amd64-3.7\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]
-- *****************************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done

**Comment by davisking** [comment]
I would hope that -T isn't really required and the defaults would work.  But cuda and visual studio are often frustrating together.  You should just modify the setup.py to do what you want.
