### ISSUE TITLE
Prebuilt binary (package) for Alpine Linux

### ISSUE THREAD

**Issue by agboom** [davisking/dlib#2257]
Hi, I'm trying to get Dlib into Alpine Linux. This will allow Alpine users to install Dlib easily using the package manager with `apk add dlib`. Version 19.18 has been in the [testing][testing] repo for a while now and it works fine. I'm trying to get 19.20 in the community repo with [this merge request][merge], but the build/tests have some problems. This depends on the platform on which is it built. See below for details.

Can anyone help me to get these sources to compile? Is it even realistic to get it working for all of these platforms?

[testing]: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/dlib
[merge]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7177

## Expected Behavior

Alpine Linux has a prebuilt binary package. This is attempted in [this merge request][merge].

## Current Behavior

For some platforms source compilation fails, for some certain (but not all) tests fail. Some give a segmentation fault. See below under "Platform" for detailed logs.

## Steps to Reproduce

Run `abuild -r` on https://gitlab.alpinelinux.org/agboom/aports/-/tree/master/community/dlib
Better: build it using the [Alpine pipeline](https://gitlab.alpinelinux.org/agboom/aports/-/pipelines/63492).

* **Version**:  19.20
* **Where did you get dlib**:  GitHub releases (see APKBUILD)
* **Platform**: 
- `aarch64` (https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268168)
- `ppc64le` (https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268167)
- `s390x` (https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268166)
- `x86` (https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268165)
- `x86_64` (https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268164)
- `armv7` is the only platform that does build successfully  (https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268169)

* **Compiler**: 
```
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
```

**Comment by davisking** [comment]
There is confusing stuff in https://gitlab.alpinelinux.org/agboom/aports/-/tree/master/community/dlib.  For instance, nothing in dlib uses C++20 features and similarly dlib does not use the Intel TBB.  It seems like something that was done external to dlib is causing this trouble.

**Comment by agboom** [comment]
Thanks for reaching out @davisking. That comment is pretty old and I could also be wrong there, my C++ is pretty rusty. Sorry for the confusion. In the more recent builds these problems don't happen anymore.

Looking closer at some of the logs, the x86_64 build seems to fail because of virtual memory exhaustion ([logs here](https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268164/raw)). That could easily be fixed by giving the build system more memory I think.

The x86 build has some failing tests, namely test_fhog, test_image, test_matrix, test_optimization, test_random_forest, test_sparse_vector and test_statistics ([logs here](https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268165/raw)). Do you have an idea why these tests could fail?

In the other builds (ppe64le, aarch64 and s390x ) build there's a segmentation fault ([ARM64 logs here](https://gitlab.alpinelinux.org/agboom/aports/-/jobs/268168/raw)). Not sure how we could debug that, but I also don't know if it's feasible to support these platforms so I could also disable these.

**Comment by davisking** [comment]
Some of those tests might be because the testing epsilons are just slightly
too tight.  You should also try building without linking to any external
BLAS library.  Sometimes people build blas libraries badly and break them,
then that breakage shows up as failures in dlib's unit tests that
ultimately depend on BLAS.

If the compiler seg faults you should report that to the compiler project.
Although maybe you are just running out of RAM there too.

**Comment by agboom** [comment]
Thanks, I'll try that. To achieve that, do I need to include the BLAS source in the build, instead of using `openblas-dev` as make depend?

**Comment by agboom** [comment]
There's also a [blas package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/blas-dev) in Alpine. Maybe that would work better with dlib?

**Comment by agboom** [comment]
The build logs indicate that the examples get compiled as well. Are these needed for package binaries? If not, could I somehow exclude them? 

For example:
```
[ 13%] Building CXX object examples/examples_build/CMakeFiles/queue_ex.dir/queue_ex.cpp.o
```

**Comment by davisking** [comment]
Just don't link dlib to any BLAS.  It will use its own internal code.  Like in CMake there is a DLIB_USE_BLAS setting. Make it false.

The unit test build script builds everything.  If there are things you don't want to build then comment them out.

**Comment by agboom** [comment]
I rebuilt with internal BLAS and the good news is: no segfaults anymore :tada: 
However, some tests still fail. Less than before it seems, just one or two per platform. Except for x86, which has 7 failing tests.
Interestingly enough, now only x86_64 builds successfully, while the other platforms fail.

Link to build logs on all platforms: https://gitlab.alpinelinux.org/agboom/aports/-/pipelines/64794
Link to new APKBUILD: https://gitlab.alpinelinux.org/alpine/aports/-/blob/309fec5d61a86380ac2a43790d1843bc549d1e9f/community/dlib/APKBUILD

@davisking do you have an idea on how to proceed?

**Comment by davisking** [comment]
Can you pull the latest dlib and run again?  I made the unit tests not
print all those warnings about the DNN loss not liking the exact training
data.  So the actual failures will be visible again.

**Comment by agboom** [comment]
Sorry for my delayed question. I've tried to pull the latest Dlib by downloading the latest commit as archive, but the build fails because it cannot find a CMakeLists.txt in the directory. That wasn't a problem in the archive attached to the release, and I cannot find a difference between the two archives (CMakeLists.txt exists in both). I'm not sure what could cause this.

Relevant logs:
```
>>> dlib: Fetching dlib-19.20.tar.gz::https://github.com/davisking/dlib/archive/0fede57ed7ef756e98124be5743097f7321edd53.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   156  100   156    0     0    776      0 --:--:-- --:--:-- --:--:--   776
100 10.1M    0 10.1M    0     0  6875k      0 --:--:--  0:00:01 --:--:-- 10.3M
>>> dlib: Fetching dlib-19.20.tar.gz::https://github.com/davisking/dlib/archive/0fede57ed7ef756e98124be5743097f7321edd53.tar.gz
>>> dlib: Checking sha512sums...
dlib-19.20.tar.gz: OK
>>> dlib: Unpacking /var/cache/distfiles/dlib-19.20.tar.gz...
CMake Error: The source directory "/builds/agboom/aports/community/dlib/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
>>> ERROR: dlib: build failed
``` 
(it says `dlib-19.20.tar.gz`, but that's just a rename of the archive so  that the rest of the build script should work)

Build script can be found here: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7177/diffs

The rest of the build log can be found here: https://gitlab.alpinelinux.org/agboom/aports/-/jobs/274401/raw
