### ISSUE TITLE
How get the pitch、yaw、roll angle from the get_face_chip_details()?

### ISSUE THREAD

**Issue by gufengye** [davisking/dlib#2258]
How to get the pitch、yaw、roll angle for the get_face_chip_details()?
 I found the chip_details contain the roll angle，but how can get the other angle ? 
pitch angle and yaw angle?
Thanks!

**Comment by arrufat** [comment]
check out this project, I've used it in the past and it works great: https://github.com/severin-lemaignan/gazr
