### ISSUE TITLE
identify every moving object and mark it with rectangles

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#226]
Hi, Davis,

There is a requirement on recognizing all kinds of bags on **Conveyor Belt**, typically, the conveyor belt in airport.
It DO NOT need to classify the bags(trolley case or any other bags) , but need to mark every bags with rectangles, no matter the type or size of the bag. After marked the rectangles, we will crop the images and send it to the server for viewing and storage.

My question is, which algorithm in DLIB is best to do with this requirement? there are many algorithms in DLIB, I am not sure which one is the best.

Thanks in advance.

**Comment by davisking** [comment]
I would look at these examples: 

https://github.com/davisking/dlib/blob/master/examples/dnn_mmod_ex.cpp

https://github.com/davisking/dlib/blob/master/examples/fhog_object_detector_ex.cpp
