### ISSUE TITLE
How was dlib 68 landmark shape predictor trained?

### ISSUE THREAD

**Issue by gondimjoaom** [davisking/dlib#2260]
I am preparing to train my own custom shape predictor with my own dataset, and I would like to know what were the options used when training shape_predictor_68_face_landmarks.dat.bz2.

Is this information present anywhere?

**Comment by davisking** [comment]
You should use the default settings.  There was some minor difference but I
don't recall it and the defaults are appropriate.  That's why they are the
defaults :)

**Comment by gondimjoaom** [comment]
oh, I see! Thanks!
