### ISSUE TITLE
Need binding frontal_face_detector inside .h from HOG SVM detector file using train_object.py script?

### ISSUE THREAD

**Issue by ismailpolas** [davisking/dlib#2262]
Is it possible to bind HOG SVM detector file into frontal_face_detector.h to use get_frontal_face_detector in python instead of using simple_object_detector?

P.S: I have already tried to convert detector.svm file to base64 & replace with get_frontal_face_detector.h base64 data. Then I rebuild dlib manually. But it shows this error "RuntimeError: Error detected in compressed data stream."

Thanks in Advance.

**Comment by davisking** [comment]
Maybe you are looking for this
http://dlib.net/python/index.html#dlib.fhog_object_detector ?

**Comment by ismailpolas** [comment]
Thank You @davisking for replying. I have solved the issue by your support.
