### ISSUE TITLE
Feature request: static_vector

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2265]
It would be great to have something like [SmallVector](https://llvm.org/doxygen/SmallVector_8h_source.html) added to dlib.
PR to come soon.

**Comment by pfeatherstone** [comment]
https://github.com/davisking/dlib/pull/2253 could benefit from this

**Comment by pfeatherstone** [comment]
Can this be done with a custom allocator that holds a stack based array of at most N bytes (additional memory is allocated using the default allocator)? Or is that not a great way of doing this ?

**Comment by davisking** [comment]
Yeah you allocate a small amount on the stack but back off to a heap allocation if it gets too big.  This is kinda over the top for #2253 though.  The ffts are either 1 or 2 dimensional, so you could make some simple class that has just two integers in it and some reasonable API to accommodate the needs of #2253.  It could also be made more narrow than a `std::vector`, which would make the client code in #2253 simpler as the type would be capable of only representing reasonable states for that code.

**Comment by pfeatherstone** [comment]
Yeah I agree that the FFTs for matrix types are either 1D or 2D but the kissFFT API can handle ND FFTs. 3D and 4D for example might one day come in handy if you want to do FFTs on tensor types.

**Comment by pfeatherstone** [comment]
Here is a possible implementation. @davisking i think this would be a great addition. If you like it, i can submit a PR when the FFT stuff has been merged.

[static_vector.h.txt](https://github.com/davisking/dlib/files/5754768/static_vector.h.txt)

**Comment by pfeatherstone** [comment]
Note that the above is inspired by https://github.com/palotasb/static_vector. I think there is a bug in the move constructor and move assign operator. i think ```other.m_size = 0``` is required at the end.

**Comment by pfeatherstone** [comment]
Note that i haven't chosen the dlib style container where everything is default constructed up front then use ```std::swap``` thereafter. We use placement new instead.

**Comment by pfeatherstone** [comment]
You can do zero copying using:
* ```push_back(value_type&& value)```
* ```iterator insert(const_iterator pos, value_type&& value)```
* ```template <typename... CtorArgs> void emplace_back(CtorArgs&&... args)```
* ```template <typename... CtorArgs> iterator emplace(const_iterator pos, CtorArgs&&... args) ```

**Comment by pfeatherstone** [comment]
i've added serialization support and swap. I would like to implement a type trait helper ```dlib::is_hashable<>``` so we can add:
```
template <
        typename T, 
        std::size_t Capacity
        std::enable_if<dlib::is_hashable<T>::value>::type* = nullptr
             >
    inline dlib::uint32 hash(
        const static_vector<T,Capacity>& item,
        dlib::uint32 seed = 0)
    {
        seed = dlib::hash((dlib::uint64)item.capacity(), seed);
        seed = dlib::hash((dlib::uint64)item.size(), seed);
        seed = std::accumulate(item.begin(), item.end(), seed, [](dlib::uint32 seed, const T& next) {
            return dlib::hash(next, seed);
        });
        return seed;
    }
```

**Comment by pfeatherstone** [comment]
There you go:
```
#if __cplusplus < 201703L
    template<typename...> using void_t = void;
    #else
    using std::void_t;
    #endif

    template <typename T, typename = void>
    struct is_hashable : std::false_type {};
    
    template <typename T>
    struct is_hashable<T, void_t<decltype(hash(std::declval<const T&>(), std::declval<dlib::uint32>()))>> : std::true_type {};
```

**Comment by pfeatherstone** [comment]
Usually @davisking wouldn't encourage using something like ```is_hashable```, but we can use this, together with ```std::enable_if``` to optionally define ```dlib::hash``` for ```dlib::static_vector<T,Capacity``` if ```T``` is hashable.

**Comment by pfeatherstone** [comment]
I don't even want to think about the number of unit tests required for this. If this makes it into a PR, i might need some help to get a really good exhaustive set of tests.

**Comment by davisking** [comment]
That looks like it's an implementation of
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0843r2.html, which
seems like a nice thing to have.   If you wanted to add this to dlib that's
cool.  Make it conform to
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0843r2.html.
Eventually people should just use the one that will appear in the STL
though.

**Comment by davisking** [comment]
We should also probably use the STL hashing tools too.  Stuff like
dlib::hash() is a pre-c++11 thing.

**Comment by pfeatherstone** [comment]
With regards to hashing, ok. It's my understanding though that std::hash is pretty poor and has loads of collisions. Whereas dlib uses murmur hashing which is possibly better ?

**Comment by pfeatherstone** [comment]
and I will submit a PR when FFT stuff goes through. I need to start using branches

**Comment by pfeatherstone** [comment]
Also to use std::hash you have to inject into the std namespace which is super disgusting.

**Comment by davisking** [comment]
> Also to use std::hash you have to inject into the std namespace which is super disgusting.

It's just a template specialization, so it's fine.  It's not violating any language rules.   As for std::hash quality, I guess I'm not sure.  It's going to depend on the compiler vendor.  I was under the impression gcc used murmur hash which is a pretty great hash.

**Comment by pfeatherstone** [comment]
Okidok

**Comment by pfeatherstone** [comment]
i've updated the code https://github.com/davisking/dlib/issues/2265#issuecomment-752670944

**Comment by pfeatherstone** [comment]
Thread moved to https://github.com/davisking/dlib/pull/2280
