### ISSUE TITLE
Compatibility with Apple Silicon M1

### ISSUE THREAD

**Issue by VlasovKirill** [davisking/dlib#2268]
I get the error every time after import dlib: 

```
    import dlib
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so: mach-o, but wrong architecture
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so: mach-o, but wrong architecture
```
I try rebuild dlib with some settings arch. 

I am using Apple Silicon M1:
* face_recognition version: latest
* Python version: 3.9.1 [Clang 6.0 (clang-600.0.57)] on darwin / 3.8.2 [Clang 12.0.0 (clang-1200.0.32.27)] on darwin
* Operating System: macOS Big Sur 11.1

`file "$( "$(which python3)" -c "import sys;print(sys.executable)" )"`
 ```
/Library/Developer/CommandLineTools/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Library/Developer/CommandLineTools/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Library/Developer/CommandLineTools/usr/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by grischka** [comment]
Having the same issue with Apple Silicon

**Comment by dwojcik92** [comment]
Tried on python 3.8.2 and 3.9.1 with the same result. Any idea how to proceed?

**Comment by adityadhinavahi** [comment]
For me this config worked
I have used the default python3 shipped with my Mac m1
Then I have created a new python3 environment using 
`python3 -m venv env_name`
We need home-brew running in terminal with rosetta
We need cmake and dlib which can be installed as follows
`brew install cmake`
`brew install dlib`
After successful installation of cmake and dlib, activate your environment using
`source env_name/bin/activate`
Then install dlib in python3
`python3 -m pip install dlib`
after successful installation launch python3 and import dlib
This worked for me

**Comment by dayojohn19** [comment]
still have same problem

**Comment by sid7631** [comment]
On m1 Mac install miniforge3 as mentioned here https://developer.apple.com/metal/tensorflow-plugin/
```
brew install cmake
brew install dlib
python -m venv .venv
source .venv/bin/activate
pip install dlib
face_recognition
```

Worked for me!

**Comment by agilebean** [comment]
This issue is already a year old, but doesn't seem to be solved.
Does anyone still have this issue, like me?
Any solutions in sight?

**Comment by leo-scorpio** [comment]
@agilebean  I met this problem today and solved it finally. You may check your cmake: file `which cmake`, make sure it is arm64 executable.

**Comment by buseynehannes** [comment]
solved it by linking the libpng library for me:

```
brew install libpng
export C_INCLUDE_PATH=/opt/homebrew/Cellar/libpng/1.6.37/include
export LIBRARY_PATH=/opt/homebrew/Cellar/libpng/1.6.37/lib
pip3 install dlib --force-reinstall 
```

(replace 1.6.37 by your installed version of libpng)

**Comment by niktheo** [comment]
I am still facing that problem with all the above suggested solutions.  
 ```
 import dlib
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_png_do_expand_palette_rgb8_neon
```
Do you have any other recommendations?

**Comment by AndrewW1999** [comment]
Has there been any updates on this issue, I have tried all suggested solutions and still receive the same error.

`dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_png_do_expand_palette_rgb8_neon)`

**Comment by romitbarua** [comment]
I am having the same issue except with a different missing name space.

`ImportError: dlopen(//opt/anaconda3/envs/DeepFake/lib/python3.10/site-packages/dlib.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_XAllocColor'`

**Comment by maritaganta** [comment]
> On m1 Mac install miniforge3 as mentioned here https://developer.apple.com/metal/tensorflow-plugin/
> 
> ```
> brew install cmake
> brew install dlib
> python -m venv .venv
> source .venv/bin/activate
> pip install dlib
> face_recognition
> ```
> 
> Worked for me!

I had the same problem on M2. After I brew install cmake and dlib to my system, I have no problem in any other virtual environment.

**Comment by damscassiani1994** [comment]
@maritaganta Having the same issue with M2, Any idea how to proceed?
