### ISSUE TITLE
dlib::serialize(dlib::full_object_detection, ostream&)  gives compile error 

### ISSUE THREAD

**Issue by kizilkanat** [davisking/dlib#227]
Hello, 
I am trying to serialize a dlib::full_object_detection object which I obtain by 
```
for (BoundingBox bb : faceRects) {  
        dlib::full_object_detection shape = shapePredictor(this->img, bb);
        std::ostringstream os; 
        dlib::serialize(shape, os); 
        std::string serialized = os.str();
}
```
I am obtaining the following error within a  MS Visual Studio 2013 Project:

> error C2665: 'dlib::serialize' : none of the 41 overloads could convert all the argument types ...... while trying to match the argument list '(dlib::full_object_detection, std::ostringstream)

**Comment by e-fominov** [comment]
try adding "using namespace dlib" at the beginning of your cpp file, i had the same issue and this helped me

**Comment by kizilkanat** [comment]
Thanks. It Works. Why doesnt work when the namespace speficied explicitly before the function name?

**Comment by davisking** [comment]
Because C++ has some goofy rules about how name resolution happens.  :/
