### ISSUE TITLE
Feature request : default jpeg and png support

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2272]
When libjpeg or libpng aren't available, we could use https://github.com/nothings/stb/blob/master/stb_image.h as default backend for ```load_jpeg```, ```save_jpeg```, ```load_png```, and so on. PR at some point.

**Comment by davisking** [comment]
They are always available though.  If there isn't a system copy cmake is
setup to build in the copies in dlib/external.

**Comment by pfeatherstone** [comment]
Oh okidok. I thought i had an error once when using ```save_jpeg``` without linking to libjpeg. I'll check to see it works.

**Comment by pfeatherstone** [comment]
If i don't define DLIB_JPEG_SUPPORT or DLIB_PNG_SUPPORT in cmake, i get runtime error:
```
terminate called after throwing an instance of 'dlib::image_load_error'
  what():  Unable to load image in file /home/pf/Downloads/repos/darknet/data/dog.jpg.
You must #define DLIB_JPEG_SUPPORT and link to libjpeg to read JPEG files.
```

**Comment by pfeatherstone** [comment]
And i assume if you define DLIB_JPEG_SUPPORT and DLIB_PNG_SUPPORT in cmake, you have to explicitly link to libjpeg and libpng

**Comment by pfeatherstone** [comment]
Or is it the case the copy in ```dlib/external``` is only ever used if DLIB_JPEG_SUPPORT is ON but your system doesn't have libjpeg? In which case, it would be nice if you could optionally set DLIB_JPEG_SUPPORT to OFF and JPEG loading/saving was still supported.

**Comment by davisking** [comment]
DLIB_JPEG_SUPPORT and DLIB_PNG_SUPPORT are on by default.  If cmake doesn't
find a system copy it builds the one in external.  Don't set
DLIB_JPEG_SUPPORT to off and it should just work.

**Comment by pfeatherstone** [comment]
Okidok
