### ISSUE TITLE
oneMKL not detected

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#2275]
Hello

A few days ago I wanted to try dlib on windows10, using msvc and the Intel MKL.
I had systems using Intel MKL which just worked, earlier, but this time i got oneMKL 2021.1 Initial Release from the Intel download page.
I installed it, but could not make CMAKE detect the MKL library.
Has anyone used oneMKL with dlib?

**Comment by pfeatherstone** [comment]
I've used oneAPI with dlib yes, but on Linux
