### ISSUE TITLE
Feature suggestion : OPTIONAL video/camera/rtsp capture class using ffmpeg libraries

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2276]
Do you want to be one step closer to removing opencv as a massive dependency from your projects? Look no further.
How about we add a video/camera/rtsp capture class to dlib that is enabled provided the optional dependency on libavcodec is selected.

This is an example: 

[ffmpeg_capture.h.txt](https://github.com/davisking/dlib/files/5774768/ffmpeg_capture.h.txt)
[ffmpeg_capture.cpp.txt](https://github.com/davisking/dlib/files/5774769/ffmpeg_capture.cpp.txt)

**Comment by pfeatherstone** [comment]
We could posh this up so it can consume any valid dlib image container like: ```matrix<rgb_pixel>```, ```matrix<bgr_pixel>```, ```array2d<rgb_pixel>```, etc. It could do all the automatic resampling if these containers have non-zero size. We could make this header only so it's not compiled into libdlib.a, so you only pay for what you use. Lots of nice things people might want.  Crucially, it would mean that you wouldn't need to link to the entire opencv arsenal of libraries when all you want to do is read a video file or camera device. Nice!

**Comment by arrufat** [comment]
Now, that would allow me to completely get rid of OpenCV (which now I only use for camera access, and input video access)

**Comment by davisking** [comment]
Yeah that would be tight.  I also only use OpenCV to grab from a camera.

**Comment by pfeatherstone** [comment]
So good material for a PR ?

**Comment by davisking** [comment]
totally

**Comment by pfeatherstone** [comment]
FFmpeg is LGPL v2.1+. That's not the most permissive of licenses. That means you can't statically link to libavcodec right, only dynamically? I absolutely don't want to make dlib LGPL. But my knowledge of licensing is very limitted. We could always add a caveat that says that if you use dlib's ffmpeg wrapper for video/camera reading, it becomes LGPL.

**Comment by pfeatherstone** [comment]
Looking at the LGPL stuff, it looks like dlib providing a wrapper for libavcodec doesn't affect dlib's license, as it doesn't affect opencv's license. It would only (possibly) affect user code's license. It would be up to the user to choose whether to link statically or dynamically to libavcodec, which determines the licensing of the resulting binary.

I can't imagine this causes an issue for commercial products. The only two mature video codec backends available today are gstreamer and ffmpeg, both of which are LGPL. So if a commercial product is doing video loading, chances are, it's using one of those two backends down the line anyway.

So i can't imagine there would be any NEW licensing issues .

**Comment by davisking** [comment]
Right. This has no impact on dlib licensing. Only on users, and only minimally.

**Comment by pfeatherstone** [comment]
Here is an update. I've only done minimal testing. I won't be able to work on this until at least next weekend, if my partner allows. So have a play, and please post issues here for the time being. I'll make a PR next week but it definitely won't be finished as I'll have to think up a myriad of tests and no doubt there will be 1000000 reviews until it is merged. 

[video_capture.h.txt](https://github.com/davisking/dlib/files/5793054/video_capture.h.txt)

**Comment by pfeatherstone** [comment]
It's worth noting that with a few minor modifications, we can use this to extract audio.

Also, using not too dissimilar code, we could write a video writer class. So all good stuff.

**Comment by pfeatherstone** [comment]
Ffmpeg is awesome.

**Comment by pfeatherstone** [comment]
This thread has been moved to https://github.com/davisking/dlib/pull/2279
