### ISSUE TITLE
Document  Maximum value of confidence provided by get_frontal_face_detector().run

### ISSUE THREAD

**Issue by mayankagarwal-cf** [davisking/dlib#2277]
I wanted to know the maximum value of confidence provided by object detector. From [the documentation](http://dlib.net/dlib/image_processing/object_detector_abstract.h.html#object_detector), "the detection_confidence is equal to the detection value output by the scanner minus the threshold value stored at the end of the weight vector in get_w(#dets[i].weight_index)". This would require further investigation into how algorithm works. It would be great if someone who understands the algorithm can tell me what the value is and I think it should be documented as it should be a part of the api specification.

**Comment by davisking** [comment]
It is unconstrained.   So it could be any `double` value.
