### ISSUE TITLE
unsafe use of relative rpath

### ISSUE THREAD

**Issue by mxye** [davisking/dlib#228]
@davisking Thanks for making dlib available! I followed your instructions for installation but it didn't work on my OSX el capitan. I tried a few times, and the final output to the command `sudo python setup.py install` was 

> "Extracting dlib-19.1.99-py2.7-macosx-10.11-intel.egg to /Library/Python/2.7/site-packages
dlib 19.1.99 is already the active version in easy-install.pth

>Installed /Library/Python/2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.11-intel.egg
Processing dependencies for dlib==19.1.99
>Finished processing dependencies for dlib==19.1.99".

When I tried to import dlib using
`python -c "import dlib"`
I get the error:

>Traceback (most recent call last):
 > File "<string>", line 1, in <module>
>  File "/Library/Python/2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.11-intel.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
>ImportError: dlopen(/Library/Python/2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.11-intel.egg/dlib/dlib.so, 2): Library not loaded: libboost_python.dylib
>  Referenced from: /Library/Python/2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.11-intel.egg/dlib/dlib.so
>  Reason: unsafe use of relative rpath libboost_python.dylib in /Library/Python/2.7/site-packages/dlib-19.1.99-py2.7-macosx-10.11-intel.egg/dlib/dlib.so with restricted binary

Is this a known issue? I haven't found it among the issues reported. 

Puzzled by the issue, I went back to inspect the output during the setup.py installation and the only output that seem to indicate errors are:

>[ 84%] Linking CXX static library libdlib.a
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(stack_trace.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(gui_core_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(stack_trace.cpp.o) has no symbols
>/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libdlib.a(gui_core_kernel_1.cpp.o) has no symbols"

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework
