### ISSUE TITLE
failed to compile dlib c++ example programs: recursive template instantiation exceeded maximum depth of 256

### ISSUE THREAD

**Issue by mxye** [davisking/dlib#229]
@davisking thanks for the response last time. I re-installed boost using homebrew, and it seems to work now. 

I tried to compile dlib c++ example programs:
`cd dlib/examples;
mkdir build;
cd build;
cmake .. ;
cmake --build . --config Release` but got the error with the last step:

>[ 87%] Building CXX object CMakeFiles/dnn_imagenet_train_ex.dir/dnn_imagenet_train_ex.cpp.o
>In file included from /Users/HomeFolder/dlib/examples/dnn_imagenet_train_ex.cpp:12:
>In file included from /Users/HomeFolder/dlib/dlib/../dlib/dnn.h:14:
>In file included from /Users/HomeFolder/dlib/dlib/../dlib/dnn/layers.h:8:
>/Users/HomeFolder/dlib/dlib/../dlib/dnn/core.h:2444:45: fatal error: recursive template instantiation exceeded maximum depth of 256
            using next_type = typename std::remove_reference<decltype(makeT().subnet())>::type;

Is this a known issue?

**Comment by davisking** [comment]
That's a clang thing.  Last time I compile dlib with clang, which was last week, that error also included instructions about what clang compiler switches you need to set to adjust the depth limit.
