### ISSUE TITLE
Some issues with the repeat layer

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2292]
I have been playing a bit with the repeat layer, and I am facing some problems.

Here's an example that showcases the problems I encoutered:

``` cpp
#include <dlib/dnn.h>

using namespace dlib;
using namespace std;

template <typename SUBNET>
using conblock = relu<bn_con<con<32, 3, 3, 1, 1, SUBNET>>>;

// With this network definition everything works
using net_type = loss_multiclass_log<fc<10, conblock<conblock<conblock<input<matrix<float>>>>>>>;

// If we try to use a repeat layer we face several problems
// this doesn't build, repeat layers can't have an input layer as a SUBNET
// using net_type = loss_multiclass_log<fc<10, repeat<3, conblock, input<matrix<float>>>>>;

// This does build, but then, we can't use the get_final_data_gradient method
// using net_type = loss_multiclass_log<fc<10, repeat<2, conblock, conblock<input<matrix<float>>>>>>;

int main()
{
    net_type net;
    std::vector<adam> solvers(net.num_computational_layers, adam());
    std::vector<long> labels(32, 1);
    std::vector<matrix<float>> samples(32, matrix_cast<float>(gaussian_randm(100, 100)));
    resizable_tensor x;
    net.to_tensor(samples.begin(), samples.end(), x);
    net.compute_loss(x, labels.begin());
    net.back_propagate_error(x);
    net.update_parameters(solvers, 0.1);
    const auto& grad = net.get_final_data_gradient();
    cout << grad.num_samples() << 'x' << grad.k() << 'x' << grad.nr() << 'x' << grad.nc() << endl;
}
```

Let's break it down, there are 3 network definitions (that define the same architecture)

1. the first one doesn't use repeat layers, and everything works fine
1. the second one replaces the 3 `conblock`s with a `repeat` layer. Apparently, the `SUBNET` can't be an `input` layer.
1. the third one uses a `repeat` layer to replace 2 `conblocks` and and extra `conblock` before the `input`, but then I realized that `repeat` layers don't have a `get_final_data_gradient()` method.

I am not too worried about the 2nd case, where we can't use an `input` layer as a `SUBNET` for the `repeat` layer, but I think not having the `get_final_data_gradient()` method is a problem... Is this easily solvable?

Thanks in advance :)

**Comment by davisking** [comment]
Oh yeah.  The `repeat` layer is missing a 
```
        const tensor& get_final_data_gradient(                                                                                          
        ) const { return subnetwork.get_final_data_gradient(); }                                                                        
 ```
declaration, which I think is all that's required.  It looks like I just forgot to add it.  Did you find that there was some complication that makes it not work for `repeat` layers?

**Comment by arrufat** [comment]
Actually, I didn't dig that much. Honestly, it's hard to wrap my head around that part of the library... 😔

**Comment by davisking** [comment]
I just made the change. Should all be working now :)

**Comment by arrufat** [comment]
Great, I've just tried and it works now! Thank you so much.

For information, I was trying to do one thing I'm not sure is possible in dlib: I wanted to accumulate the gradients before performing the backward pass so that I can, effectively, use big batch-sizes even if the GPU does not have enough VRAM.

I need to study the API a bit more, and let you know if I make it work.

Anyway, thanks again for taking your time to look into this :)

**Comment by davisking** [comment]
No problem.

Yeah, it's all setup to zero the gradients for you automatically.  Like the contract of each layer's backward() function is that it assigns (i.e. ovewrites) to the parameter gradient.  You would have to go take all those parameter gradients and accumulate them elsewhere.  So it's not going to be very convenient to do it.

**Comment by arrufat** [comment]
Yes, that is exactly what I thought, when I saw that gradients were zeroed out automatically. Anyway, not a big deal, it was more for fun that for a necessity.
