### ISSUE TITLE
dlib on Android

### ISSUE THREAD

**Issue by tzutalin** [davisking/dlib#23]
Hi,
  Dlib is a cross platform library, so dlib is supposed to compile and run successfully on Android?  It seems the only thing to do is writing Android.mk. Does someone have the similar experiences?

**Comment by davisking** [comment]
I haven't done this but I've heard from dlib users that use it on Android.  I don't think any of them have posted a .mk file for it though.

**Comment by tzutalin** [comment]
OK. Thank you. @davisking, do you mind if I port the algorithm you wrote to my Android application?

**Comment by davisking** [comment]
Knock yourself out :)

**Comment by tzutalin** [comment]
Hi,
I wrote a simple Android.mk and run it a sample code on my HTC mobile phone.
https://github.com/tzutalin/dlib-android

**Comment by davisking** [comment]
Nice. People often ask about how to set this up :)  I'll link to this from the dlib docs.

**Comment by hcg1123** [comment]
Hi.
I am working on dlib in Windows with Android Studio.
I am a newbie on Android development.
What should I do to to build dlib-android and dlib-android app.
Looking forward to hearing from you.
Thanks.

**Comment by rishabhMaltare** [comment]
@tzutalin 
Hi, I followed your code and built it on my android device. It ran fine. Now what I want is that I want to integrate the new dlib i.e. 19.4.0 in it. I want it so that I can use it for face recognition using face descriptors, which is not available in previous versions of dlib.

**Comment by hohuns** [comment]
Hi.
I am working on dlib in Mac with Android Studio.
How can I compile this?
