### ISSUE TITLE
dlib not using GPU

### ISSUE THREAD

**Issue by vamsee-asu2019** [davisking/dlib#2305]
Hi,
I'm building dlib with cmake(via add_subdirectory()) in a c++program for facial landmarks detection(shape detector).
Dlib was built successfully with cuda enabled displaying "Dlib will use CUDA" message in the cmake build. But when check the gpu usage using NVIDIA-SMI.EXE while running the same application, the GPU usage is zero. I have also timed the facial marker detection in both cases "with CUDA enabled"  and "with CUDA disabled"(using the flag DLIB_USE_CUDA). In both cases, the time is almost the same around 50ms. 
A similar issue was also faced by @ariel415el in #1155 which was closed. But I couldn`t find the solution to this in the comments of #1155. 

@davisking can you help me with this issue?

I'm using:
Dlib: 19.21
Cuda: 11.1
cudnn: 8.0
cmake: 3.19.2
compiler: Visual C++ 16.0
GPU: GeForce GTX 1650

Thank you,
Vamsee

**Comment by arrufat** [comment]
If I understdood you correctly, you are trying to use the `shape_predictor` and the `frontal_face_detector`, which do not use of the GPU, so everything is working as expected.
As of now, only the DNN related parts of the library make use of the GPU.
See https://github.com/davisking/dlib/issues/2302#issuecomment-775767564.

**Comment by vamsee-asu2019** [comment]
@arrufat  thanks for the reply. I was in the notion that even the shape_predictor is gpu optmized.
