### ISSUE TITLE
potential bug?

### ISSUE THREAD

**Issue by LotharKaps** [davisking/dlib#2309]
https://github.com/davisking/dlib/blob/8b9d04390ce9545fc4cf3e9d8a981fc71ae8570f/dlib/global_optimization/global_function_search.cpp#L626

I believe the variable is supposed to be relative_noise_magnitude_ since testing against a set variable does not seem sound to me. I might be wrong tho. So please someone with more experience doublecheck this :)

**Comment by davisking** [comment]
Oh yeah, that's a bug.  Thanks for reporting it :)

I just pushed a fix.

**Comment by LotharKaps** [comment]
I am happy to help ^.^
