### ISSUE TITLE
dlib with ESP-IDF

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [davisking/dlib#2310]
Hello, 

i was able to Port dlib to ESP-IDF and run it on a ESP32. 

https://github.com/DiplomInformatikerFranzHoepfinger/dlib-esp-idf

@davisking maybe you can look at the Changes i made, and check if it is worth taking over to the master branch. 

Thanks, 
Franz

**Comment by davisking** [comment]
Please submit a PR and I’ll take a look
