### ISSUE TITLE
Python dlib.fhog_object_detector intern parameters

### ISSUE THREAD

**Issue by Markets00** [davisking/dlib#2311]
Hi! Are internal parameters such max number of detected faces, min and max face size available or accessible in any way in dlib.fhog_object_detector using Python?

I'm using dlib.get_frontal_face_detector() from dlib v19.19.0 and those parameters was key to manage detection performance speed in C (I know, I'm using python ^^', but performance matters to me).

Thanks a lot!

**Comment by davisking** [comment]
I'm not sure I know what you are referring to.  Those parameters are not
anywhere in dlib.  Like the text monoface_patience doesn't appear anywhere
in dlib.
