### ISSUE TITLE
Shape predictor training strange behaviour/stuck

### ISSUE THREAD

**Issue by Etoye** [davisking/dlib#2313]
Hi, I am trying to train 5 points shape predictor with the latest dlib version on the original 5 points dataset + custom additional images (~1000). I've encountered strange behavior during the beginning of the training process, where after loading annotations and printing training info nothing else happens and training stuck:

```
[INFO] training shape predictor...  
Training with cascade depth: 20. 
Training with tree depth: 4. 
Training with 500 trees per cascade level.  
Training with nu: 0.1033. 
Training with random seed:  
Training with oversampling amount: 29. 
Training with oversampling translation jitter: 0. 
Training with landmark_relative_padding_mode: 1. 
Training with feature pool size: 677. 
Training with feature pool region padding: 0.0975. 
Training with 8 threads.  
Training with lambda_param: 0.0251. 
Training with 295 split tests.
```

At the same time, if I train an original dataset and supplement the dataset separately - there are no issues and the *fitting tree* message, as well as a timer, appears almost instantly. I've experimented and randomly merged them in different proportions to check if there any problems with annotations themselves but within additional ~200 images merged with the original 5 points dataset no problems occurred. Any ideas about what it can be?

**Comment by davisking** [comment]
You are saying it's hanging?  Maybe you are running out of ram and it's starting to swap and just run super slow.

**Comment by Etoye** [comment]
Right, hanging. After few days it's finished to train. Probably you right and it's a RAM problem - 26GB not enough.
