### ISSUE TITLE
webassembly support

### ISSUE THREAD

**Issue by thinkgamesdeveloper** [davisking/dlib#2318]
Dear,

Do you plan to add webassembly support by enabling compilation with emscripten ? 

Thank you in advance.
Zoheir.

**Comment by davisking** [comment]
No.  I don't know what would be involved.  Dlib is just C++ code though, so
any platform that can compile standard C++ can use it as is.

**Comment by arrufat** [comment]
@thinkgamesdeveloper check this out: https://github.com/seanchas116/wasm-face-detection
