### ISSUE TITLE
Softmax for matrix class

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2319]
Hi! Just some quick questions on how I would go about adding a softmax operation to the amazing matrix class in dlib.
(I know I can just use `tt::softmax(out, in)` where `out` and `in` are tensors and I can just use the `mat` function).

Here's what I got so far, which already works:

``` cpp
namespace dlib
{
    template <typename M>
    struct op_softmax
    {
        op_softmax(const M& m_) : m(m_)
        {
            static_assert((is_same_type<type, float>::value == true ||
                           is_same_type<type, double>::value == true ||
                           is_same_type<type, long double>::value == true));
            denom = sum(exp(m));
        }
        const M& m;
        const static long cost = M::cost + 9;
        const static long NR = M::NR;
        const static long NC = M::NC;
        typedef typename M::type type;
        typedef typename M::mem_manager_type mem_manager_type;
        typedef typename M::layout_type layout_type;
        typedef type const_ret_type;
        const_ret_type apply(long r, long c) const { return std::exp(m(r, c)) / denom; }
        long nr() const { return m.nr(); }
        long nc() const { return m.nc(); }
        template <typename U>
        bool aliases(const matrix_exp<U>& item) const { return m.aliases(item); }
        template <typename U>
        bool destructively_aliases(const matrix_exp<U>& item) const { return m.destructively_aliases(item); }
        private:
        type denom;
    };
    template <typename M> const matrix_op<op_softmax<M>> soft_max(const matrix_exp<M>& m)
    {
        typedef op_softmax<M> op;
        return matrix_op<op>(op(m.ref()));
    }
}
```
The big question is: am I very wrong?
The precise doubts I have are:
- will that static assert go there?
- about the cost: I saw that `exp` has a cost of 7, so here we're basically doing `exp` twice and a division, hence the 9, but there's also a sum there, what should I use as cost here?
- if you're interesting in having it in dlib, how would you name it? `softmax` clashes with the dnn layer.

EDIT: also, I would like to cache the result of applying `exp` to the input matrix, but I didn't succeed yet.

**Comment by davisking** [comment]
Yeah that all looks fine to me.  I assume you read http://dlib.net/matrix_expressions_ex.cpp.html already?  That talks about how to do this stuff. Seems like you got the hang of it though. 

The exact cost values don't really matter.  They are used to decide when to introduce temporaries and only really matter when the code is thinking about adding temporaries before doing matrix multiplies, since multiplies would have to involved repeated accesses to the same elements if no temporary is used.  A cost of 9 is fine here.  The sum doesn't count for the cost.  The cost is the cost of the apply() call, since that's the only part that would be repeated if a temporary wasn't injected.

Not sure how to name it.  You could *maybe* get away with calling it softmax() since the arguments are different.  You could try it and see what happens.  Might be alright.

> EDIT: also, I would like to cache the result of applying exp to the input matrix, but I didn't succeed yet.

Not sure what you mean by this.  You talking about in the matrix expression code or something else?


Also, note that when computing a softmax you really want to do the numerically stable version where you subtract the max values out.  See how the dlib dnn cpu code does softmax for an example.

**Comment by arrufat** [comment]
Thank you again for your comments. Now I get more the point of the cost.
Yes, I read the `matrix_expressions_ex` example :)

About caching the result, I'd like to compute `exps = exp(m)` and store it as a member variable, so I only need to compute the exponential once, although I need to store an extra matrix.
I was trying to do:

``` cpp
private:
M exps;
```

But that didn't work, however this did the trick:
``` cpp
private:
matrix<type, NR, NC> exps;
```

I'm kind of happy with this implementation, except for the fact that I can't use the name `softmax`, so I was thinking about `softmax_mat` or `soft_max`:

``` cpp
template <typename M> struct op_softmax
{
    op_softmax(const M& m_) : m(m_)
    {
        static_assert((is_same_type<type, float>::value == true ||
                       is_same_type<type, double>::value == true ||
                       is_same_type<type, long double>::value == true));
        exps = exp(m - max(m));
        denom = sum(exps);
    }
    const M& m;
    const static long cost = M::cost + 9;
    const static long NR = M::NR;
    const static long NC = M::NC;
    typedef typename M::type type;
    typedef typename M::mem_manager_type mem_manager_type;
    typedef typename M::layout_type layout_type;
    typedef type const_ret_type;
    const_ret_type apply(long r, long c) const { return exps(r, c) / denom; }
    long nr() const { return m.nr(); }
    long nc() const { return m.nc(); }
    template <typename U> bool aliases(const matrix_exp<U>& item) const
    {
        return m.aliases(item);
    }
    template <typename U> bool destructively_aliases(const matrix_exp<U>& item) const
    {
        return m.destructively_aliases(item);
    }

    private:
    type denom;
    matrix<type, NR, NC> exps;
};

template <typename M> const matrix_op<op_softmax<M>> soft_max(const matrix_exp<M>& m)
{
    typedef op_softmax<M> op;
    return matrix_op<op>(op(m.ref()));
}
```

Sometimes I wonder if the dnn stuff should be under their own namespace, `dlib::dnn`.

**Comment by davisking** [comment]
Yeah `M` isn't the type you want to use.  You figured it out though, you have to use a specific and appropriate type, like the one you selected.

**Comment by davisking** [comment]
Although this shouldn't be a matrix expression if the whole thing is basically cached in a member variable.  It's not getting any of the benefit of being a matrix expression anymore.  So just using a regular old function would be more appropriate since it's easier to read.
