### ISSUE TITLE
Implementing solution constraints in global_function_search

### ISSUE THREAD

**Issue by iraikov** [davisking/dlib#2321]
Hello,

I have been using dlib's Global Function Search optimization for a couple of years now, thanks for writing such an excellent optimizer! I have some use cases where it will be beneficial to apply constraints to candidate solutions, similar to how some optimization algorithms partition their candidate solutions into feasible and infeasible based on user-supplied constraint equations. I am willing to develop a detailed proposal  and contribute code to this end, but as I am not very familiar with the internals of dlib, I'd like to hear some suggestions on possible ways to implement solution constraints. To me it seems that a possible solution would be to add a "feasibility" flag to evaluation requests, let the user code set it as an optional argument to the set method, and use the feasibility information when ranking solutions so that feasible solutions are considered first. What I am not clear about is how the feasibility information could be incorporated in the trust region part of the optimizer, so that infeasible solutions are avoided. Any pointers are appreciated!

**Comment by davisking** [comment]
You can probably get by with just making your function output really big values (assuming you are setting things up as a minimization problem) for points you want to be infeasible.  Although yeah, it can be better to have the trust region solver natively support more complicated constraints.  That's a lot more work though, especially depending on the kinds of constraints you want to have.  Like it would be cool if dlib had something like a sequential quadratic program solver or some other generalized non-linear constrained solver that could be used to solve the trust region problem here.  And it's a lot of work to write a decent SQP solver.  

The book Numerical Optimization by Jorge Nocedal and Stephen Wright is an excellent reference for this kind of thing.

**Comment by iraikov** [comment]
Hello Davis,
Thanks for your prompt response and the background explanation. I did read the chapter on SQP in the Numerical Optimization book, and I agree that it seems like it could be a very useful algorithm. So I will try to at least prototype a solver in a high-level language in order to understand the technical challenges, but this will take a while. Thanks again for the information.
