### ISSUE TITLE
Dlib GPU support for Python

### ISSUE THREAD

**Issue by RarDay** [davisking/dlib#2322]
Hi everyone, how can I run face recognition with dlib and face_recognition on the GPU?
My devices don't support CUDA

I have two computers:
1) Windows with Intel Graphics
2) ALT Linux with Ryzen Vega

And PyCharm with Python 3.7, dlib version 19.21.0
Does Dlib support OpenCL?

**Comment by davisking** [comment]
No, only CUDA is supported.

**Comment by RarDay** [comment]
@davisking 
Can you tell me what I can use to run face recognition in python on the GPU (without CUDA)
Do I understand correctly that of the open source facial recognition software, dlib is in the first place?
It seems that PyTorch, Keras and TensorFlow have OpenCL support, how much worse are they than dlib?

(I am considering options with ready-made solutions, without training datasets, and if there is nothing interesting anymore, I will use dlib with CUDA)

Thank you so much for any advice!

**Comment by SheldonPatnett** [comment]
Typically OpenCL implementations are considerably slower than cuDNN. While Dlib doesn't support OpenCL, if your system doesn't have Cuda/Cudnn it should fallback to building with only CPU support. The Python library you mentioned 'face_recognition' should work with Dlib without GPU support.
