### ISSUE TITLE
How to run Dlib with two GPUs in Python?

### ISSUE THREAD

**Issue by duan348733684** [davisking/dlib#2325]
How to run dlib with two GPUs in Python?

**Comment by arrufat** [comment]
I am not sure if I understand what you mean, exactly.
But if you want to run two models in different GPUs, you could set the GPU before loading the model:
``` python
dlib.cuda.get_num_devices()  # this should return at least 2
dlib.cuda.set_device(0)
cnn_face_detector = dlib.cnn_face_detection_model_v1(face_det_model_path)
dlib.cuda.set_device(1)
facerec = dlib.face_recognition_model_v1(face_rec_model_path)
```
Then each model should be loaded in a different GPU.

**Comment by arrufat** [comment]
I am not sure if I understand what you mean, exactly.
But if you want to run two models in different GPUs, you could set the GPU before loading the model:
``` python
dlib.cuda.get_num_devices()  # this should return at least 2
dlib.cuda.set_device(0)
facedet = dlib.cnn_face_detection_model_v1(face_det_model_path)
dlib.cuda.set_device(1)
facerec = dlib.face_recognition_model_v1(face_rec_model_path)
```
Then each model should be loaded in a different GPU.
