### ISSUE TITLE
Principal component analysis example c++

### ISSUE THREAD

**Issue by jbensabat** [davisking/dlib#2326]
Hello 
I am new to DLIB  c++
I am trying to use it for a PCA analysis of data. I do not see any example or guidance 
I don't see any such example in c++ examples
if there is one that I could use for starting I would be glad if you could share
best 
jac

IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by arrufat** [comment]
I've actually used the [`vector_normalizer_pca`](http://dlib.net/ml.html#vector_normalizer_pca) to do the Principal Component Analysis without any issues, did you try that?

**Comment by fatalfeel** [comment]
example here
https://books.google.com.tw/books?id=ozDnDwAAQBAJ&pg=PA187&lpg=PA187&dq=dlib::vector_normalizer_pca+train&source=bl&ots=4jnTiSl1Mj&sig=ACfU3U23Tm922fkpJNu49oBpjzgZvr6R7w&hl=zh-TW&sa=X&ved=2ahUKEwjUy7G9pd72AhWgsFYBHeNCAMIQ6AF6BAgSEAM#v=onepage&q=dlib%3A%3Avector_normalizer_pca%20train&f=false
