### ISSUE TITLE
Dlib build Error

### ISSUE THREAD

**Issue by gaurav7700** [davisking/dlib#2331]
Please help solving this issue, using the lastest version of dlib 
Using visual studio 16 2019 with cmake latest version
Current Behavior - 
Cuda lib generated is newer than Cmakefiles/generated.stamp
Cmakefiles/generate.stamp is out of date 

![PXL_20210323_143010589](https://user-images.githubusercontent.com/81248091/112168296-48fb6880-8c45-11eb-8ca0-d5426e074307.jpg)

**Comment by jarlostensen** [comment]
I have run into the same problem and a quick fix (if you just need it to build) is to change the code to use **floorf** (which I believe maps to a __device__ function), so for example: 

`const int top  = static_cast<int>(floorf(y));`

instead of 

`const int top    = static_cast<int>(::floorf(y));`

This works (and runs) but I am no cuda expert so I'm not sure if this is a "good" fix...

**Comment by davisking** [comment]
Yeah, use the newest dlib on github and it should be fine.  Probably about
time for me to post dlib 19.22 :)

**Comment by gaurav7700** [comment]
thanks

**Comment by gaurav7700** [comment]
> I have run into the same problem and a quick fix (if you just need it to build) is to change the code to use **floorf** (which I believe maps to a **device** function), so for example:
> 
> `const int top = static_cast<int>(floorf(y));`
> 
> instead of
> 
> `const int top = static_cast<int>(::floorf(y));`
> 
> This works (and runs) but I am no cuda expert so I'm not sure if this is a "good" fix...

in which file do i have to make these changes?

**Comment by jarlostensen** [comment]
check your error message for details but it should be in ``cuda_dlib.cu``

**Comment by gaurav7700** [comment]
> check your error message for details but it should be in ``cuda_dlib.cu`` 

Error is for a lot of things, not even able to build wheel for dlib

**Comment by jarlostensen** [comment]
Then I'm afraid I at least am unable to provide any more help.
