### ISSUE TITLE
Indicating the number of input variable during the runtime

### ISSUE THREAD

**Issue by ArashMassoudieh** [davisking/dlib#2333]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Steps to Reproduce

* **Version**: 
* **Where did you get dlib**: 
* **Platform**: 
* **Compiler**:

**Comment by ArashMassoudieh** [comment]
Hi Davis, I am new to DLIB. I am trying to use dlib's mlp library in a project where the number of input variables is not known beforehand. The problem is that I don't know the size of my input variables during the compile time. I am trying to find out a way to be able to specify the size of input variables during runtime. I realized that for example in "typedef matrix<double, i, 1> sample_type;", i has to be a constant number. Is there a way to do that i can be a variable to be determined in the runtime? Thank you for your help.

**Comment by arrufat** [comment]
Hi, did you read the [matrix example](http://dlib.net/matrix_ex.cpp.html)?
You can just set the dimension you want to modify at runtime to 0:

``` cpp
typedef matrix<double, 0, 1> sample_type;
sample_type sample;
long i = 2;
sample.set_size(i, 1);
```

**Comment by ArashMassoudieh** [comment]
Thank you very much! This will do it.

Arash
