### ISSUE TITLE
cudaMalloc out of memory

### ISSUE THREAD

**Issue by monsterlyg** [davisking/dlib#2340]
RuntimeError: Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /tmp/pip-install-xxga2353/dlib_4f93121a35234eb9a87f6fe37649ce92/dlib/cuda/gpu_data.cpp:221. code: 2, reason: out of memory

I have a 12G gpu, When I try to run 5000 imgs face detection, the process stops at 864th image. Every time I restart the code, it still stops at 864th image and raises an error above. I have checked the image size and gpu memory. And it runs sunccessfully on several hundred images. Any reason may lead to the corruption?

**Comment by SheldonPatnett** [comment]
Can you post more details about the image in question? Does your recognition do any sort of up-scaling of images?

**Comment by BingoGreen** [comment]
I have the same question, have you address ？ Thanks

**Comment by SheldonPatnett** [comment]
@BingoGreen Please open a separate issue a be sure to follow the reporting template and we will attempt to help you there.
