### ISSUE TITLE
Does dlib.train_simple_object_detector() generate an image pyramid?

### ISSUE THREAD

**Issue by ufukcbicici** [davisking/dlib#2342]
I am trying to train a real-time (fast) sliding window object detector with dlib, in Python. I am using the function train_simple_object_detector() to train a structural SVM for the detection. I am somewhat confused how the function works behind the curtain. The common HOG+SVM sliding window detector of Dalal and Triggs usually generates an image pyramid, like (WxH, W/2xH/2, W/4xH/4, ...) etc. Provided a sliding window size of (w x h), then this gets convolved on the whole image pyramid to detect objects of different scales. So, currently the object I want to detect has square bounding boxes, so the aspect ratio is not an issue (I want to detect cat faces, btw). However, I am getting pretty awful detection scores (like an AP of %40) for a relatively simplistic object like cat faces. I am now worrying about if I am using the function correctly, so I have a couple of questions.

- Assuming that I provide images of the size (WxH), with a sliding window of the size (w x h) and set "upsample_limit" to 0, would the function "train_simple_object_detector()" generate the down-sampled versions of the original image (WxH sized) automatically? Or it just runs the sliding window on the provided image, as it is provided?

- If it is the case that the function "train_simple_object_detector()" only works on the original image size and sliding window size; what would be the correct way to implement the image pyramid effect with the Python API, since the scale of the object changes in my training images. (I think in the C++ library, we have  the "scan_fhog_pyramid<pyramid_down<6>>" object but I am not sure this is the same in Python).

Thanks everyone.

**Comment by davisking** [comment]
Yes, it uses an image pyramid and scans the detector over the pyramid to find objects.  It always uses a pyramid.  And if you set upsample_limit to 0 it just means it won't upsample your images, so you won't be able to detect things smaller than your sliding window size.

If it's not working it's because there is something wrong with your training data.  Like the labeling is inconsistent in some way.

**Comment by ufukcbicici** [comment]
Thank you for the quick answer!
