### ISSUE TITLE
nvcc fatal : Value 'sm_30' is not defined for option 'gpu-architecture' dlib

### ISSUE THREAD

**Issue by SheldonPatnett** [davisking/dlib#2343]
## Expected Behavior

Trying to build dlib from dlib-19.9.tar.bz2 with cuda and cudnn

## Current Behavior
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/duser/Downloads/dlib-19.9/build/temp.linux-x86_64-3.9/dlib_build/cuda_test_build
***   
***   Run Build Command(s):/usr/bin/make -f Makefile && [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o

***   nvcc fatal : Value 'sm_30' is not defined for option 'gpu-architecture' dlib

## Steps to Reproduce
sudo python3 setup.py install  

* **Version**: 
* dlib-19.9
* **Where did you get dlib**: 
http://dlib.net/files/
* **Platform**: 
x64
* **Compiler**: 
cmake version 3.20.0

**Comment by SheldonPatnett** [comment]
http://dlib.net/files/dlib-19.21.tar.bz2 builds without issue in the same environment.

**Comment by davisking** [comment]
Right. Old code doesn’t work with new tools. Use the new version.

**Comment by SheldonPatnett** [comment]
Right, thank you. Closing issue.
