### ISSUE TITLE
Error when using repeat layer with dimpl::subnet_wrapper

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2344]
Hi, I wanted to use the `repeat` layer with the `loss_mmod`, but I found the following issue, which can be reproduced like this:

Just change this line:
https://github.com/davisking/dlib/blob/0ffe9c4c40a77506c8b421aca574795343d4024c/examples/dnn_mmod_train_find_cars_ex.cpp#L38

to look like this:

``` c++
 using net_type = loss_mmod<con<1,9,9,1,1,repeat<3,rcon5,downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>; 
```

And the example program does not compile anymore:
```
/home/adria/Projects/dlib/dlib/../dlib/dnn/core.h:2710:29: error: static assertion failed: Call to layer() attempted to access non-existing layer in neural network.
 2710 |             static_assert(i < T::num_layers, "Call to layer() attempted to access non-existing layer in neural network.");       
      |                           ~~^~~~~~~~~~~~~~~
```

So, it seems there is a problem when `dimpl::subnet_wrapper` contains a `repeat` layer. Is this fixable?

**Comment by davisking** [comment]
Yeah.  `layer<idx>(net)` doesn't work when `net` is a `subnet_wrapper`.  `impl::layer_helper` needs some appropriate overload to catch that case.  Should be fixable.  Or just overload `input_layer()` for this specific type. I just spend some time looking and I'm not sure what the most straightforward fix is though.  I also got intercepted by my kids and can't work on it further right now :|

If you want to give it a whirl though be my guest :)

**Comment by arrufat** [comment]
Thank you, I already tried to work on it for some time before posting, but I will look at it later. I also can't work on it right now, since it's a bit late.

Have fun! :)

**Comment by arrufat** [comment]
So, I tried again to figure out how to work around this issue, and it seems that the `subnet_wrapper` case should be handled here, but it's not:
https://github.com/davisking/dlib/blob/8d4df7c0b3fa7c4c1e4175951161b01ccf4541b5/dlib/dnn/core.h#L2857-L2868

I don't understand that part of the library very well, so it's hard to fix it, but I will keep trying :)

**Comment by arrufat** [comment]
I am not making any progress... The main reason why I need this to work it the fact that I'd like to use more complicated networks for detection. The ultimate goal is to be to train a network with a YOLO loss, and be able to check the boxes and centers' coordinates between image and feature spaces using this would be really convenient.

So, I would kindly appreciate it, when you have time, if you can have a look at it. No rush :)
Or if you can tell me where I can learn more about the obscure (to me) template magic that's going on in `core.h`.

**Comment by davisking** [comment]
Yeah I'm honestly not sure either.  I spent a bit the other day trying to get it to work but couldn't get it going. I'll look again a bit this weekend.

**Comment by arrufat** [comment]
The thing I can't get my heard around is that we're calling `layer` recursively, so when we hit the `repeat`layer, we skip all the layers inside and eventually run out of layers... so I can't figure out how to go through those repeated layers...

**Comment by arrufat** [comment]
I was trying to replace
https://github.com/davisking/dlib/blob/9b502d29a43c1f95260869ebb28b2f218ccb4b7f/dlib/dnn/loss.h#L1853
with
``` c++
det_window = layer<net_type::num_layers - 1>(net).tensor_space_to_image_space(input_tensor, det_window);
```
But it complains with the same error.

So I tried:
``` c++
det_window = layer<decltype(net)::num_layers - 1>(net).tensor_space_to_image_space(input_tensor, det_window);
```
But it complains that the wrapped network does not contain a member named `num_layers`.
I also tried with `decltype(net.subnet().subnet())::num_layers - 1`, so that I skip the `repeat` layer, but same error.

**Comment by davisking** [comment]
Not sure. I tried to add some overloads to handle this. On the surface it seems like it ought to be just a matter of adding the right one but there is something I’m overlooking since I couldn’t get it compiling despite trying for a while.

**Comment by arrufat** [comment]
Oh, if it's not easy for you to do it, I'm not sure if it's worth it for me to keep trying... It's a lost battle, 😅.

**Comment by davisking** [comment]
Yeah the repeat layer is the most complicated part of the dnn tooling. Everything else is pretty simple. That thing is a bit squirrely.

**Comment by arrufat** [comment]
I kind of got that feeling, haha. Anyway, I will try to implement the YOLO loss without it.

My idea was to make a `loss_yolo<tag_stride_32, tag_stride_16, tag_stride_8, SUBNET>` that would get the output at those tags and compute the loss using the `input_layer` or the `layer<tag>` functions. I will see if I can implement it without them...

I wanted to implement it similar to the `concat` layer, so that it could accept a variable number of tags. But if this doesn't work, I will need to hard-code the output layer tags. With the added limitation that it might not work for `input_rgb_image_pyramid`.

Anyway, it's a long-term project that I'd like to do whenever I can spend some time on it. Thank you. Feel free to close this issue if you think it's not fixable (or don't want to spend more time on it).

**Comment by arrufat** [comment]
I've been trying a bit more, without much success... do you think adding these two methods to [`subnet_wrapper`](https://github.com/davisking/dlib/blob/8e9755ab0f0825988c4955fda71bacdb2432ed28/dlib/dnn/core.h#L628) would help?

``` c++
T& unwrap() { return l; }
const T& unwrap() const { return l; }
```
Then we could get the unwrapped network and maybe make it work? I've tried, but it still doesn't compile, but it might inspire you :)

**Comment by arrufat** [comment]
I've made a simpler example that reproduces the issue, I've been trying to debug it with this one, but still nothing
``` c++
#include <dlib/dnn.h>

using namespace std;
using namespace dlib;

template <typename SUBNET> using rcon5  = relu<bn_con<con<55,5,5,1,1,SUBNET>>>;
using net_type_1 = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<tag1<input_rgb_image_pyramid<pyramid_down<6>>>>>>>;
using net_type_2 = loss_mmod<con<1,9,9,1,1,repeat<2,rcon5,tag1<input_rgb_image_pyramid<pyramid_down<6>>>>>>;

int main() try
{
    net_type_1 net1;
    input_layer(net1);
    dimpl::subnet_wrapper<net_type_1::subnet_type, true> w1(net1.subnet(), 1);
    input_layer(w1);

    net_type_2 net2;
    input_layer(net2);
    dimpl::subnet_wrapper<net_type_2::subnet_type, true> w2(net2.subnet(), 1);
    input_layer(w2);  // <-- this line does not compile.
    return EXIT_SUCCESS;
}
catch (const exception& e)
{
    cout << e.what() << endl;
    return EXIT_FAILURE;
}
```

**Comment by arrufat** [comment]
I just started trying to see if we could get the input layer of a network using a visitor (but I don't know if that has runtime costs, or if it's even feasible...)
Here's the first (useless) version, that does nothing...

``` c++
namespace dlib
{
    namespace impl
    {
        class visitor_input_layer
        {
        public:

            template <typename T>
            void operator()(size_t, T&) const {}

            template <typename T>
            T& operator()(size_t, input<T>& l) { return l; }

            input_rgb_image& operator()(size_t, input_rgb_image& l) { return l; }

            template <size_t NR, size_t NC>
            input_rgb_image_sized<NR, NC>& operator()(size_t, input_rgb_image_sized<NR, NC>& l) { return l; }

            template <typename T>
            input_rgb_image_pyramid<T>& operator()(size_t, input_rgb_image_pyramid<T>& l) { return l; }

            template <typename T>
            input_grayscale_image_pyramid<T>& operator()(size_t, input_grayscale_image_pyramid<T>& l) { return l; }
        };
    }
    template <typename net_type>
    auto get_input_layer(
        net_type& net
    )
    {
        visit_layers_backwards(net, impl::visitor_input_layer());
    }
}
```

I don't want to write a visitor for each member function of the input layers...

**Comment by davisking** [comment]
Yeah you definitely don't want to stack on top of the visitor.   What ought to work is overload `input_layer()` for a `subnet_wrapper` or something simple but I frustratingly couldn't get anything like that to build the other day.

**Comment by davisking** [comment]
You know what, just add a `.input_layer()` method to `add_layer`.  Make it call into the sublayer it contains.  That should be easy and not involve any template magic or any of that kind of thing.  `subnet_wrapper` needs a `.input_layer()` too but should be just a simple non-template method as well.  I would add it right now but I've to go take my kid to school or we are going to be late :\

**Comment by arrufat** [comment]
Oh, thank you, I will try it in a bit :)

**Comment by arrufat** [comment]
Yeah, nope... I've been trying for some time and I feel a bit dumb... You made it look so easy, but I didn't get it, and it was not so obvious to me how to make it work... 😅

**Comment by davisking** [comment]
In C++14 it's easy, you can just return `decltype(auto)` and it just does the right thing here.  But in C++11 the thing to do is to add typedefs to the classes that declare the type we want and make `input_layer()` return that type.  Even in C++14 it's nice to do this because it's usually nice to have those types easily on hand anyway.

I just pushed https://github.com/davisking/dlib/commit/1de47514bdf104d5b5a7deea0a436fce559f02e3 which adds `.input_layer()` to all networks and makes it so `repeat` works here as well.

**Comment by arrufat** [comment]
Oh, I see now, I got confused with the `.subnet()` method. Thank you so much for taking your time to look into this :)

**Comment by davisking** [comment]
No problem. Thanks for reporting the issue :)
