### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by dashesy** [davisking/dlib#235]
In our project we run with warnings as errors, and it is C++14.
I can see some warnings could be easily fixed, for example:

> warning C4297: 'dlib::thread_pool::~thread_pool': function assumed not to throw an exception but does
> note: destructor or deallocator has a (possibly implicit) non-throwing exception specification

Also it seems the presence of so many consts in `numeric_constants.h` make it unavoidable to clash, for example `e` will result in warning:

> optimization_line_search.h(135): warning C4459: declaration of 'e' hides global declaration

That can be fixed by renaming `e` to `err` but perhaps hiding constants in `numeric_constants` in another level of namespace like

``` C++
    namespace dlib 
    {
    namespace constants 
    {
    ...
    }
    }
```

could be a better approach.

Do you think it is useful if I send some PR for cleaning up these warnings?

**Comment by davisking** [comment]
Visual studio has a lot of inane warnings.  That warning about constants is
silly.  I already have a bunch of pragma statements that disable some
visual studio warnings in dlib/algs.h.  You can add to that list if you
want.

Although some warnings you are getting might be reasonable to fix with code
changes.  It depends on what they are though.  For example, putting a call
to exit() in the thread_pool's destructor could be a reasonable change.  Or
maybe even declaring the destructor as a throwing destructor, although it's
definitely a bad user error if there are exceptions at that point.  My
preference is to leave the code as it is.   But I could be persuaded here
to use exit() to avoid the warning.

I also test dlib at the highest warning levels in gcc and clang and don't
get warnings.  I also never have warnings in gcc that I need to disable.
But visual studio is ridiculous.   There is even a warning in visual studio
(which I've disabled in algs.h) that says parts of the C++ standard library
are deprecated and you are advised to use something windows specific.

**Comment by e-fominov** [comment]
Hi, i have just updated to GCC 6.2 (MinGW-based) and I see this warnings when building dlib (latest source from git):
In file included from C:/work/dlib/dlib/threads.h:22:0,
                 from C:/work/dlib/dlib/sync_extension/sync_extension_kernel_1.h:6,
                 from C:/work/dlib/dlib/sync_extension.h:6,
                 from C:/work/dlib/dlib/gui_core/gui_core_kernel_1.h:34,
                 from C:/work/dlib/dlib/gui_core/windows.h:4,
                 from C:/work/dlib/dlib/gui_core.h:12,
                 from C:\work\dlib\dlib\gui_widgets\drawable.h:8,
                 from C:\work\dlib\dlib\gui_widgets\base_widgets.h:8,
                 from C:\work\dlib\dlib\gui_widgets\base_widgets.cpp:6:
C:/work/dlib/dlib/threads/thread_pool_extension.h: In destructor 'dlib::thread_pool::~thread_pool()':
C:/work/dlib/dlib/threads/thread_pool_extension.h:516:17: **warning: throw will always call terminate() [-Wterminate]
                 throw;
                 ^~~~~**
C:/work/dlib/dlib/threads/thread_pool_extension.h:516:17: **note: in C++11 destructors default to noexcept**
C:/work/dlib/dlib/threads/thread_pool_extension.h:521:17: **warning: throw will always call terminate() [-Wterminate]
                 throw;
                 ^~~~~**
C:/work/dlib/dlib/threads/thread_pool_extension.h:521:17: **note: in C++11 destructors default to noexcept**

And this warning is Windows-specific:
In file included from C:\work\dlib\dlib\sockets\sockets_kernel_1.cpp:18:0:
D:/mingw62/mingw64/x86_64-w64-mingw32/include/winsock2.h:15:2: **warning: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h
  ^~~~~~~**

**Comment by davisking** [comment]
I just pushed a code change that makes `thread_pool`'s destructor call abort() instead of rethrowing the exception.

Did you check if the code still compiled when switching the order of windows.h and winsock2.h?  I would check but I don't want to reboot into windows right now :)

**Comment by e-fominov** [comment]
Yes, compiles well now (with #236). Tested with MinGW 6.2 and MSVC 2015 x64 - no warning at all

**Comment by davisking** [comment]
sweet

**Comment by dashesy** [comment]
You would get the same warning (about `e` hiding global declaration) with gcc too if you add `-Wshadow` which we do. 
We compile with `gcc`, `MSVC` and `clang`, turning on many of the warnings project-wide and also making warnings into errors. Most of the time those warnings help discover hard to find problems. For exampe it is easy to miss one `e` when renaming, and have the code use  the global constant.

I can turn off the warnings for `dlib` using pragmas, but since most of `dlib` is templated and is in the headers it means I have to wrap dlib headers within some other header and include the latter.

**Comment by davisking** [comment]
I do just -W -Wall.

Also, I'm not a fan of heavily nested namespaces.

**Comment by dashesy** [comment]
How about I rename for example `e` to `err` when `catch (const exception& e)`, and send PR?

**Comment by davisking** [comment]
That's fine :)

Anything like that that doesn't break the API is generally fine.

**Comment by e-fominov** [comment]
catch (const exception& e) construction is everywhere in dlib's code, so it's like dlib's style
new code will have it again

i have just removed "e" from numeric_constants and dlib.so still compiles well
may be better put constants into nested namespace?

**Comment by davisking** [comment]
I'm more worried about user's code not compiling anymore.

But sure, if both of you guys are being bothered by these warnings then
I'll relent and we can put the constants in a sub-namespace.  I'm blaming
you guys if users complain though :)

**Comment by e-fominov** [comment]
:) no, i am not using -Wshadow. just tried now and there are hundreds of warnings. yes, 90% of them are about "e", but there are a lot of warnings about other variables and fixing them will not be trivial

i think, that solving this problem can affect dlib's code and will be a reason of new problems

**Comment by davisking** [comment]
Ok.  Definitely don't want to break stuff :)

**Comment by dashesy** [comment]
Sent a PR, feel free to look. 
Yes most are about `e`. In Visual Studio the warning is on by default.

**Comment by grisevg** [comment]
There are also quite a lot of warnings in Xcode. Most of them are about conversion/comparison of signed and unsigned types. It's easy to get rid of them, by doing an explicit `static_cast`.

I'd be happy to do a PR if it helps.

**Comment by davisking** [comment]
Sure, be my guest :)

**Comment by grisevg** [comment]
While we're on the topic - wouldn't it be better to change unsigned types to signed types where it's safe to do so.
As far as I understand, signed integral arithmetics run much faster and enable compilers to do a lot of additional optimisations (first of all unsigned types are twice as slow due to compilers have to add mod operation for wrap_over guarantee and then compilers can't do most optimisations: https://kristerw.blogspot.co.uk/2016/02/how-undefined-signed-overflow-enables.html ).  
There is a potential danger of overflow of course, but considering that most of the code uses long, it's nearly impossible to overflow that.
There is also a danger of users passing negative values to functions that expect positive only values, but that could be solved with assertions.

**Comment by davisking** [comment]
I'm pretty sure that's not how it works.  But if you can show some
performance improvements then that would be super.
