### ISSUE TITLE
Usage of std::allocator member types, deprecated in C++17 and removed in C++20

### ISSUE THREAD

**Issue by torgeiws** [davisking/dlib#2350]
We use dlib in a project at our company. I tried to compile with the `cpplatest` compiler flag in the latest Visual Studio preview version, currently 16.10 Preview 2.1.

I got compilation errors in dlib, because dlib uses this feature that was deprecated in C++17 and is now being removed in C++20.

Specifically, the compilation error happens in `dlib/stl_checked/std_vector_c.h` which looks like this on the master branch at the time of writing:
``` cpp
    template <
        typename T,
        typename Allocator = std::allocator<T>
        >
    class std_vector_c : public std::vector<T,Allocator>
    {
        typedef typename std::vector<T,Allocator> base_type;
    public:
        // types:
        typedef typename Allocator::reference         reference;
```
Looking at [cppreference](https://en.cppreference.com/w/cpp/memory/allocator), one will notice that  the titular feature was deprecated in C++17, and is being removed in C++20.

I found [this post on stackoverflow](https://stackoverflow.com/questions/38565365/why-did-stdallocator-lose-member-types-functions-in-c17/38565547) which suggests using [std::allocator_traits](https://en.cppreference.com/w/cpp/memory/allocator_traits) instead. That being a feature that was present in C++11, so it should be readily available.

**Comment by davisking** [comment]
I merged https://github.com/davisking/dlib/pull/2351 a moment ago which should fix this.  Let us know if you are still running into trouble.

**Comment by torgeiws** [comment]
I works now :)
