### ISSUE TITLE
How to predict a batch of samples in parallel?

### ISSUE THREAD

**Issue by YuliZheng** [davisking/dlib#2355]
Hi, I am new to dlib. For example let's say I have trained a krls model
`krls<kernel_type> model(kernel_type, params);`
I know that `model(one sample)` would give me the prediction of this sample.
However, can I predict a batch of samples at the same time? perhaps in parallel?
I didnot find any document containing this aspect. Appreciate any help!

**Comment by davisking** [comment]
No.  You should use a `for` loop and call it on each sample.  Or if you want to use threads that's up to you to do so.  You could use `dlib::parallel_for` or any other threading construct you like.

**Comment by YuliZheng** [comment]
Got it. Thx 👍
