### ISSUE TITLE
How to train dlib on Helen dataset

### ISSUE THREAD

**Issue by jankaWIS** [davisking/dlib#2363]
This seems like a simple question but I am unable to find an answer for it. If I want to train a predictor using `dlib` as described [here](http://dlib.net/train_shape_predictor.py.html), where do I find the corresponding xml file? The official HELEN dataset [page](http://www.ifp.illinois.edu/~vuongle2/helen/) only has images with corresponding txt files. I have gone through several pages and posts (https://github.com/davisking/dlib/issues/768, https://github.com/davisking/dlib/issues/1003, https://stackoverflow.com/questions/36908402/dlib-training-shape-predictor-for-194-landmarks-helen-dataset, ...) but in none they share the HELEN xml file. Alternatively, is there already a pretrained HELEN model? Thanks.

**Comment by davisking** [comment]
You need to convert the data on the HELEN webpage into that html file.  I
don't have one on hand.

**Comment by jankaWIS** [comment]
I have tried following the official documentation on [dlib](http://dlib.net/train_shape_predictor.py.html) with data from the [Helen dataset](http://www.ifp.illinois.edu/~vuongle2/helen/) which I have converted into an xml file of the following structure using the following code:
```python
import os
import dlib,cv2
import numpy as np
x = "<?xml version='1.0' encoding='ISO-8859-1'?><?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>"
x += "<dataset><name>Helen face point dataset - testing images</name><images>"  

# go over all training
for tmp_name in training_set:
    # write image name
    x += f"<image file={os.path.join(image_path, tmp_name+'.jpg')}> "
    
    # write coordinates
    tmp_coordinates = np.genfromtxt(os.path.join(coordinates_path, "label",f"{tmp_name}.txt"), dtype=int)

    # skip first 40 landmarks
    i=41

    # append after 10
    for tag in tmp_coordinates[i-1:100]:
        i +=1
        x += f"    <part name='0{i}' x='{tag[0]}' y='{tag[1]}'/> "
        
    # append after 100
    for tag in tmp_coordinates[100:]:
        i +=1 
        x += f"    <part name='{i}' x='{tag[0]}' y='{tag[1]}'/> "    

    x += "</image>"
x += "</images></dataset>"
open("training_set.xml", "w").write(x)
```
where the coordinates are the coordinates of the landmarks associated with each image in the dataset. When I then run the code using this training dataset:
```python
options = dlib.shape_predictor_training_options()
options.be_verbose = True

# dlib.train_shape_predictor() does the actual training.  It will save the
# final predictor to predictor.dat.  The input is an XML file that lists the
# images in the training dataset and also contains the positions of the face
# parts.
training_xml_path = os.path.join('./', "training_set.xml")
dlib.train_shape_predictor(training_xml_path, "predictor.dat", options)
```

I get the following error

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-148-65d4a323b4f0> in <module>
      6 # parts.
      7 training_xml_path = os.path.join('./', "training_set.xml")
----> 8 dlib.train_shape_predictor(training_xml_path, "predictor.dat", options)

RuntimeError: There is a fatal error on line 1 so parsing will now halt.
```
I have searched for some answers or documentation on what this error means and how to fix it but have not found any. I guess that the xml file is broken or not according to the expectations but I have not found the expectations. Is there a template for the XML file? Or how do I convert it?

**Comment by jankaWIS** [comment]
I have found the problem. It was a stupid issue of missing single quotes around the file name... Thanks a lot anyway.
