### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#237]
Hi,
Since i really like to use the dlib http server, i asked myself how to make a https server(basic ssl encryption based on certificates) out of this.
is there any way to do this? And if there is no such feature where would you start to develop it?
Thanks alot

**Comment by davisking** [comment]
That's not currently a feature.  I would look at libssl's documentation to
see how to do this kind of thing.

**Comment by VisionEp1** [comment]
Thanks for the quick reply!
I know boost assio supports ssl(Since you already use boost(as far as i know)).

One more question: is this a feature you plan to add at some day?

Thanks

**Comment by davisking** [comment]
No problem.

Maybe someday, but not in the near future.

**Comment by VisionEp1** [comment]
ok, thanks alot :)!
