### ISSUE TITLE
Logic Error In File'dlib/__init__.py' 

### ISSUE THREAD

**Issue by Tooisorahe** [davisking/dlib#2370]
IF YOU ARE REPORTING A BUG OR PROBLEM WITH DLIB THEN FILL OUT THE ENTIRE TEMPLATE BELOW.  ISSUES ASKING QUESTIONS ABOUT WHY SOMETHING DOESN'T WORK THAT FAIL TO FILL OUT THE ENTIRE TEMPLATE WILL BE CLOSED.

It is OK to suggest interesting improvements to dlib, even if you are not volunteering to implement them.  **However, the issue tracker is not a code writing service, do not ask for someone to write code for you.**  E.g. Do not ask for feature improvements to the example programs. **If there is some feature improvement you want in an example program then it's up to you to write it**.  

Before you ask a question, check Google for a solution, [the dlib FAQ](http://dlib.net/faq.html), or consult the dlib documentation.  Every single function in dlib is documented in detail.  If you obviously haven't read the documentation your issue will be closed.  

If you aren't reporting a bug or problem with dlib then delete this template and write whatever you want here.
 

## Expected Behavior

```
>>> import dlib
>>>
```

## Current Behavior

```
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\DEV\Python385\lib\site-packages\dlib-19.22.0-py3.8-win-amd64.egg\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found
```
## Steps to Reproduce

1.Install CUDA
2.Install cuDNN
3.Download and unzip [http://dlib.net/files/dlib-19.22.zip]()
4.Enter path 'dlib-19.22' And run ` python setup.py install --set USE_AVX_INSTRUCTIONS=1 --set DLIB_USE_CUDA=1` under CMD

* **Version**:  19.22.0
* **Where did you get dlib**:  http://dlib.net/
* **Platform**: OS: Windows10 20H2 64-bit, CUDA: v11.2, cuDNN: 8.1.1, Python: 3.8.5, Visual Studio: 2019

> Installed e:\dev\python385\lib\site-packages\dlib-19.22.0-py3.8-win-amd64.egg
> Processing dependencies for dlib==19.22.0
> Finished processing dependencies for dlib==19.22.0
CMD output after compiling and installing

It cannot be imported in Python, like 'Current Behavior'

```
# Copyright (C) 2020  Davis E. King (davis@dlib.net)
# License: Boost Software License   See LICENSE.txt for the full license.

def add_lib_to_dll_path(path):
    """ On windows you must call os.add_dll_directory() to allow linking to external DLLs.  See
    https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew.  This function adds the folder
    containing path to the dll search path. 
    """
    try:
        import os
        os.add_dll_directory(os.path.join(os.path.dirname(path), '../../bin'))
    except (AttributeError,KeyError):
        pass

if 'l' == 'ON':
    add_lib_to_dll_path('C:/CUDA/CUDA Development/v11.2/lib/x64/cudnn.lib')
    add_lib_to_dll_path('C:/CUDA/CUDA Development/v11.2/lib/x64/cudart.lib')

from _dlib_pybind11 import *
from _dlib_pybind11 import __version__, __time_compiled__

```

But I noticed that in the file'dlib/__init__.py' this line `if 'l' == 'ON':`, I try to delete it

```
# Copyright (C) 2020  Davis E. King (davis@dlib.net)
# License: Boost Software License   See LICENSE.txt for the full license.

def add_lib_to_dll_path(path):
    """ On windows you must call os.add_dll_directory() to allow linking to external DLLs.  See
    https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew.  This function adds the folder
    containing path to the dll search path. 
    """
    try:
        import os
        os.add_dll_directory(os.path.join(os.path.dirname(path), '../../bin'))
    except (AttributeError,KeyError):
        pass


add_lib_to_dll_path('C:/CUDA/CUDA Development/v11.2/lib/x64/cudnn.lib')
add_lib_to_dll_path('C:/CUDA/CUDA Development/v11.2/lib/x64/cudart.lib')

from _dlib_pybind11 import *
from _dlib_pybind11 import __version__, __time_compiled__

```
Then I found that it can be imported normally

```
import sys
import cv2
import dlib


def _help():
    print("Usage:")
    print("     python pic_face_detect_dlib.py <path of a picture>")
    print("For example:")
    print("     python pic_face_detect_dlib.py pic/HL.jpg")


def face_detect(file_path):
    color_image = cv2.imread(file_path)
    gray_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2GRAY)

    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor("model/shape_predictor_68_face_landmarks.dat")
    faces = detector(gray_image, 1)

    for face in faces:
        left = face.left()
        top = face.top()
        right = face.right()
        bottom = face.bottom()
        cv2.rectangle(color_image, (left, top), (right, bottom), (0, 255, 0), 2)

        shape = predictor(color_image, face)
        for idx, pt in enumerate(shape.parts()):
            pt_pos = (pt.x, pt.y)
            cv2.circle(color_image, pt_pos, 2, (0, 0, 255), -1)
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(color_image, str(idx + 1), pt_pos, font, 0.3, (255, 0, 0), 1, cv2.LINE_AA)
    cv2.namedWindow("Image", cv2.WINDOW_NORMAL)
    cv2.imshow("Image", color_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


if len(sys.argv) == 1 or "-h" in sys.argv or "--help" in sys.argv:
    _help()
else:
    face_detect(sys.argv[1])

```

Use the above code for face recognition, it working!

Summary: I think there is no problem connecting the DLL path at compile time. It should be the part of the code mentioned above that hinders the normal import operation.As for why there is `if'l' =='ON':` this code I don't know, I don't know what it wants to express

**Comment by davisking** [comment]
It's because you are forcing `DLIB_USE_CUDA` to 1 by giving `--set DLIB_USE_CUDA=1` to cmake.  Try it again without doing that.

More generally, do not ever do `--set USE_AVX_INSTRUCTIONS=1 --set DLIB_USE_CUDA=1` that kind of thing (unless you really understand what you are doing to cmake).  The default behavior is to detect if these things are available and use them if so.  It is never necessary to set them and setting them to odd values interferes with normal CMake operation.

**Comment by Tooisorahe** [comment]
You are right, no additional parameters are really needed, he will automatically use CUDA
Thanks for the answer.

**Comment by Tooisorahe** [comment]
> It's because you are forcing `DLIB_USE_CUDA` to 1 by giving `--set DLIB_USE_CUDA=1` to cmake. Try it again without doing that.
> 
> More generally, do not ever do `--set USE_AVX_INSTRUCTIONS=1 --set DLIB_USE_CUDA=1` that kind of thing (unless you really understand what you are doing to cmake). The default behavior is to detect if these things are available and use them if so. It is never necessary to set them and setting them to odd values interferes with normal CMake operation.

You are right, no additional parameters are really needed, he will automatically use CUDA
Thanks for the answer.

**Comment by davisking** [comment]
Sweet :)
