### ISSUE TITLE
dlib fails to install on Windows 10

### ISSUE THREAD

**Issue by mrjeanclaude91** [davisking/dlib#2371]
## Expected Behavior
Expected dlib to be instalable on Windows 10 running Python 3.6 (as a conda virtual env) with command: `pip install dlib`. Have installed cmake and numpy as prerequisites. This failed with: 

(py36) PS C:\Users\Jean Claude> pip install dlib
Collecting dlib
  Using cached dlib-19.22.0.tar.gz (7.4 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Jean Claude\anaconda3\envs\py36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\setup.py'"'"'; __file__='"'"'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\JEANCL~1\AppData\Local\Temp\pip-wheel-03d14jpb'
       cwd: C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=C:\Users\Jean Claude\anaconda3\envs\py36\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\build\lib.win-amd64-3.6 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:5 (message):

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\setup.py", line 134, in run
      self.build_extension(ext)
    File "C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\setup.py", line 171, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\Jean Claude\\anaconda3\\envs\\py36\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Jean Claude\anaconda3\envs\py36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\setup.py'"'"'; __file__='"'"'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\JEANCL~1\AppData\Local\Temp\pip-record-odoruwut\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Jean Claude\anaconda3\envs\py36\Include\dlib'
         cwd: C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\
    Complete output (60 lines):
    running install
    running build
    running build_py
    package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=C:\Users\Jean Claude\anaconda3\envs\py36\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\build\lib.win-amd64-3.6 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:5 (message):

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      You must use Visual Studio to build a python extension on windows.  If you
      are getting this error it means you have not installed Visual C++.  Note
      that there are many flavors of Visual Studio, like Visual Studio for C#
      development.  You need to install Visual Studio for C++.

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\setup.py", line 134, in run
        self.build_extension(ext)
      File "C:\Users\JEANCL~1\AppData\Local\Temp\pip-install-bdv23ese\dlib_6034d75b85f2455eaa1e85e06b14242b\setup.py", line 171, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "C:\Users\Jean Claude\anaconda3\envs\py36\lib\subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Users\\Jean Claude\\anaconda3\\envs\\py36\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Jean Claude\anaconda3\envs\py36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\setup.py'"'"'; __file__='"'"'C:\\Users\\JEANCL~1\\AppData\\Local\\Temp\\pip-install-bdv23ese\\dlib_6034d75b85f2455eaa1e85e06b14242b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\JEANCL~1\AppData\Local\Temp\pip-record-odoruwut\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Jean Claude\anaconda3\envs\py36\Include\dlib' Check the logs for full command output.

**Comment by bohdansok** [comment]
Install Visual Studio Community (classic C++ option) fisrt for free and be blessed.

**Comment by Frosterast2** [comment]
I'm trying to install dlib from this link [here](https://pypi.org/simple/dlib/), can anyone tell me which one do I need to install for python 3.9.1?

**Comment by davisking** [comment]
Use the newest

**Comment by Frosterast2** [comment]
Tysm :D

**Comment by ricardo-reis-1970** [comment]
Please reopen this. This is an ongoing issue with lots of assumptions made, the first being that "The Universe uses Visual Studio." This is *not* true.

I am running the following environment:
- Windows 10 Pro 21h2 64 bits
  - Intel(R) Celeron(R) CPU 4205U @ 1.80GHz   1.80 GHz
  - 8GB RAM
- Python 3.9.9
- CMake version 3.18.4

- VS Community 2022 17.0.2
  - with C++ CMake tools for Windows [.vsconfig.txt](https://github.com/davisking/dlib/files/7697615/default.vsconfig.txt)
- VS Build Tools 2022 17.0.2
  - with C++ CMake tools for Windows [.vsconfig_bt.txt](https://github.com/davisking/dlib/files/7697616/default.vsconfig_bt.txt)

I do `poetry install`, and my `pyproject.toml` targets `19.21.1`. I get:
```cmd
  • Installing dlib (19.21.1)

  EnvCommandError
[...]
    CMake Error at CMakeLists.txt:5 (message):



      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


      You must use Visual Studio to build a python extension on windows.  If you
      are getting this error it means you have not installed Visual C++.  Note
      that there are many flavors of Visual Studio, like Visual Studio for C#
      development.  You need to install Visual Studio for C++.


      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[...]
```

I'm a Python developer. I do not do C++ at all. I do not use Visual Studio at all. I'm trying to install `dlib` in a brand new Intel NUC (an embedded device, with limited resources) and simply put there are no clear end-to-end instructions or even fuzzy guidelines as to what exactly do in order to achieve this greenfield, from scratch, zero assumptions, foolproof.

I find it preposterous that the general rule is a blanket "Install VS 20##", ignoring the simple fact that we're being asked to install a **sixteen gigabytes** full IDE in order to compile what amounts to an 8MB `.pyc`. Is this just me?

I understand that different HW configurations require different compilations and that therefore `dlib` is not distributed ready compiled, like `numpy`, `pandas` or `OpenCV`, but at the very least a serious and responsible guide to an absolute minimum prerequisite installation would be interesting. I'm not sure how big a VS installation configuration file would be, but that would also be grand.

Alternatively, is there any other compiler that doesn't use up the entire disk? Something non-IDE and non-Microsoft that could be used in such cases? I'm thinking of something along the lines of Linux `gcc` that would compile `dlib`.

Any suggestions would be highly appreciated. As it stands, I am forced to carry around a `.pyc` file on my project's repository, and this just feels wrong.

**Comment by davisking** [comment]
This isn't a dlib thing.  It's a Python thing.  If you want to compile any python extension on windows you have to use visual studio. See https://docs.python.org/3/extending/windows.html.

**Comment by ricardo-reis-1970** [comment]
Hi Davis,

Thank you for the rather quick reply. That page was a nice refreshment on the differences between Linux and Windows, but I'm afraid it still does not serve the purpose of my enquiries. Fully aware that the fact that I'm currently locked to Windows (much to my personal distaste) is not `dlib` team's fault, I'm still looking for a way to make this whole thing happen under Windows. A lot of ML for my medical device hinges on `dlib`.

The closest I found so far was [How to install dlib library for Python in Windows 10](https://medium.com/analytics-vidhya/how-to-install-dlib-library-for-python-in-windows-10-57348ba1117f) and this is by absolutely no means either comprehensive or accurate, or up-to-date (or even in English, claims my pedantic self). The approach seems to be install everything and put your hands together in prayer. Still not working in my device.

Do you know of any such resource that would help people like me being able to successfully `pip install dlib` under Windows with bare minimum boilerplate?

Here's the catch: if I succeed in coming up with something of the sort, I will submit it to be added to `dlib`'s documentation. My issue is that these NUCs are very slow and each attempt takes tens of minutes.

Many thanks
Ricardo

**Comment by davisking** [comment]
Sorry, but it's not clear to me what the hang up is. Just installing visual studio (and clicking that you want c++ support when it asks in the installer) is sufficient. Assuming you have python and cmake installed as well.

**Comment by ricardo-reis-1970** [comment]
Again, thank you for replying on a Sunday, and join the club! It is not clear to me either what could it be that is hanging up, but as per my trace above, the system keeps claiming that I must install VS for C++, despite all the time I spent doing just that.

Worse: it is working on my laptop, but not on any of the embedded devices.

**UPDATE:** _isn't it always something small and slightly humiliating?_ The issue was mismatched versions. **CMake 3.18.4** supports as high as **VS 16 (2019)**, same as I have on my laptop. However, on the devices I'm using **VS 17 (2022)**. All it took was to get the latest **CMake 3.22.1** and it immediately started working.

You might think you didn't do much, but you helped. Thank you very much!

**Comment by iznasnikhadidja** [comment]
bonjour tous le monde. svp j'ai cette erreur a chaque fois que j'essaye d'installer dlib sur anaconda3 environement 
ERROR: Command errored out with exit status 1: 'C:\Users\tayme\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tayme\\AppData\\Local\\Temp\\pip-install-tcbzxpu8\\dlib_5ce9c75c2ff9445ea1fc2dd84f3a005f\\setup.py'"'"'; __file__='"'"'C:\\Users\\tayme\\AppData\\Local\\Temp\\pip-install-tcbzxpu8\\dlib_5ce9c75c2ff9445ea1fc2dd84f3a005f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tayme\AppData\Local\Temp\pip-record-ccmai4is\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\tayme\anaconda3\Include\dlib' Check the logs for full command output.
quelqu'un peut m'aider a resoudre ce probleme. merci.

**Comment by xiaohaoo** [comment]
> Please reopen this. This is an ongoing issue with lots of assumptions made, the first being that "The Universe uses Visual Studio." This is _not_ true.请重新打开这个。这是一个持续的问题，有很多假设，第一个是“宇宙使用Visual Studio。“这不是真的。
> 
> I am running the following environment:我正在运行以下环境：
> 
> * Windows 10 Pro 21h2 64 bitsWindows 10 Pro 21h2 64位
>   
>   * Intel(R) Celeron(R) CPU 4205U @ 1.80GHz   1.80 GHzIntel（R）Celeron（R）CPU 4205 U @ 1.80GHz   1.80 GHz
>   * 8GB RAM
> * Python 3.9.9简体中文
> * CMake version 3.18.4
> * VS Community 2022 17.0.2VS社区2022 17.0.2
>   
>   * with C++ CMake tools for Windows [.vsconfig.txt](https://github.com/davisking/dlib/files/7697615/default.vsconfig.txt)使用C++ CMake tools for Windows[. vsconfig.txt](https://github.com/davisking/dlib/files/7697615/default.vsconfig.txt)
> * VS Build Tools 2022 17.0.2VS构建工具2022 17.0.2
>   
>   * with C++ CMake tools for Windows [.vsconfig_bt.txt](https://github.com/davisking/dlib/files/7697616/default.vsconfig_bt.txt)使用Windows的C++ CMake工具[. vsconfig_bt. txt](https://github.com/davisking/dlib/files/7697616/default.vsconfig_bt.txt)
> 
> I do `poetry install`, and my `pyproject.toml` targets `19.21.1`. I get:我做`poetry install`，我的`pyproject.toml`目标是`19.21.1`。我得到：
> 
> ```batchfile
>   • Installing dlib (19.21.1)
> 
>   EnvCommandError
> [...]
>     CMake Error at CMakeLists.txt:5 (message):
> 
> 
> 
>       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 
>       You must use Visual Studio to build a python extension on windows.  If you
>       are getting this error it means you have not installed Visual C++.  Note
>       that there are many flavors of Visual Studio, like Visual Studio for C#
>       development.  You need to install Visual Studio for C++.
> 
> 
>       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> [...]
> ```
> 
> I'm a Python developer. I do not do C++ at all. I do not use Visual Studio at all. I'm trying to install `dlib` in a brand new Intel NUC (an embedded device, with limited resources) and simply put there are no clear end-to-end instructions or even fuzzy guidelines as to what exactly do in order to achieve this greenfield, from scratch, zero assumptions, foolproof.我是一个Python开发者。我根本就不懂C++。我不使用Visual Studio。我试图在一个全新的英特尔NUC（一个嵌入式设备，资源有限）中安装`dlib`，简单地说，没有明确的端到端指令，甚至没有模糊的指导方针，以实现这个格林菲尔德，从头开始，零假设，万无一失。
> 
> I find it preposterous that the general rule is a blanket "Install VS 20##", ignoring the simple fact that we're being asked to install a **sixteen gigabytes** full IDE in order to compile what amounts to an 8MB `.pyc`. Is this just me?我觉得荒谬的是，一般规则是一个毯子“安装VS 20##”，忽略了一个简单的事实，即我们被要求安装一个16GB的完整IDE，以编译什么数额为8MB `.pyc`。只有我这么觉得吗
> 
> I understand that different HW configurations require different compilations and that therefore `dlib` is not distributed ready compiled, like `numpy`, `pandas` or `OpenCV`, but at the very least a serious and responsible guide to an absolute minimum prerequisite installation would be interesting. I'm not sure how big a VS installation configuration file would be, but that would also be grand.我知道不同的硬件配置需要不同的编译，因此`dlib`并不是像`numpy`，`pandas`或`OpenCV`那样已经编译好了，但至少一个严肃和负责任的绝对最低先决条件安装指南会很有趣。我不确定VS安装配置文件会有多大，但那也是很大的。
> 
> Alternatively, is there any other compiler that doesn't use up the entire disk? Something non-IDE and non-Microsoft that could be used in such cases? I'm thinking of something along the lines of Linux `gcc` that would compile `dlib`.或者，有没有其他编译器不会用完整个磁盘？在这种情况下可以使用非IDE和非Microsoft的东西？我正在考虑一些沿着于Linux `gcc`的东西，可以编译`dlib`。
> 
> Any suggestions would be highly appreciated. As it stands, I am forced to carry around a `.pyc` file on my project's repository, and this just feels wrong.任何建议将不胜感激。就目前的情况而言，我被迫在我的项目存储库中携带一个`.pyc`文件，这感觉是错误的。

我深表赞同！
