### ISSUE TITLE
cnn_face_detection_model_v1 So slow on GPU

### ISSUE THREAD

**Issue by kiva12138** [davisking/dlib#2374]
I installed Dlib(python) using GPU

and it shows normal when checking GPU:
`
print(dlib.DLIB_USE_CUDA) # True
`
When initiliaze the detector, it seems no problem:
`
cnn_face_detector = dlib.cnn_face_detection_model_v1('./mmod_human_face_detector.dat') # normal
`

but when I detecting faces by CNN detector, It just stuck.
`
cnn_dets = cnn_face_detector(img, 1) # Stuck
`
Then  nothing shows and it just stuck.

The GPU control shows DLIB is using GPU:
`
nvidia-smi # shows normal 
`

**Comment by kiva12138** [comment]
Why?
Can anyone explain this for me? Thanks

**Comment by bohdansok** [comment]
The easiest way to check  if dlib recognizes your GPU is.

```
import dlib.cuda as cuda

print(cuda.get_num_devices())
```
If the number of devices is >= 1 then dlib can use your device.

**Comment by kiva12138** [comment]
> The easiest way to check if dlib recognizes your GPU is.
> 
> ```
> import dlib.cuda as cuda
> 
> print(cuda.get_num_devices())
> ```
> 
> If the number of devices is >= 1 then dlib can use your device.
> Also, CNN on GPU demands a lot of resources.: 4GB of GDDR is barely enough for processing of 600-800 kB pictures maximum, and rises exception if ran out of memory.

Yes, the result returns 3.
As we use three RTX 3090 GPU, so I dont think the memory is the cause.

As mentioned, I waited for about 10 minutes and it worked.
Howerver, it is so slow (It takes about 0.5 seconds to process a single image). 
I dont know why. XD

**Comment by MuadDev** [comment]
I experience the same behaviour as @kiva12138 reports.
I have 2 RTX 3090 GPUs, I can see that the model is loaded onto the GPU, but it is sooooo slow.
It does not crash, but compared to packages like pytorch this takes an eternity.

**Comment by brtasavpatel** [comment]
@kiva12138 were you able to solve this issue?

**Comment by weathon** [comment]
I am running into the same issue
