### ISSUE TITLE
Results of test_shape_predictor()

### ISSUE THREAD

**Issue by Almas-Alz** [davisking/dlib#2379]
I've trained custom dlib's shape predictor for facial landmarks prediction and used test_shape_predictor() function to evaluate it. It gives me numbers that I don't know how to interpret and use for comparison. 
In documentation of test_shape_predictor() function I found this:

"This function tests the predictor against the dataset and returns the mean average error of the detector. In fact, The return value of this function is identical to that of dlib’s shape_predictor_trainer() routine. Therefore, see the documentation for shape_predictor_trainer() for a detailed definition of the mean average error."

But I couldn't find the documentation of shape_predictor_trainer(). When I google this error, I see the mean absolute error. Is this the same thing? Could someone give the definition of the mean average error?

**Comment by davisking** [comment]
Refer to the main docs: http://dlib.net/ml.html#test_shape_predictor and in particular the more details button.  It talks at length about what it does.

See also http://dlib.net/faq.html#Whereisthedocumentationforobjectfunction
