### ISSUE TITLE
After call "compute_face_descriptor", process exits very slowly.

### ISSUE THREAD

**Issue by samsha1971** [davisking/dlib#2382]
python：3.8.10
dlib: 19.22 with CUDA 11.0 , compiler : visural studio 2017
os: win10 x64
issue: Run "dlib-19.22\python_examples\face_recognition.py" in command line environment, if you call "compute_face_descriptor", it will takes a long time for the process to return to the console after the last line of code has been executed.   How to deal with it?

**Comment by steinio** [comment]
I have  this same issue, for both CUDA versions 10.2 and 11.6 and with dlib versions from 19.21 to 19.23.
Using Visual Studio 2019 on x64 Win, crashes with the error code 

`Processing file: C:/Projects/dlib_test/images\image.jpg
Number of faces detected: 1
Detection 0: Left: 123 Top: 430 Right: 1503 Bottom: 1810

Process finished with exit code -1073740791 (0xC0000409)`

I added printouts and also stepped in debug to verify that it does not go past the compute_face_descriptor function.
