### ISSUE TITLE
RAM saturation during dlib shape detector training

### ISSUE THREAD

**Issue by bach05** [davisking/dlib#2387]
## Expected Behavior
I'm trying to re-train the dlib shape detector with my own dataset on a machine with 16 GB of RAM. The training set size is not larger than 3 GB. I expect that the training will be finished correctly. 

## Current Behavior

The training process appears blocked. The RAM consumption continuously increases since the PC reaches saturation (also of the swap area) and basically slows down until the process is killed. This is the console output: 

```
python enhanced_training.py -tr "enhanced_labels_ibug_300W_train.xml" -m "model_6k.dat" -te "enhanced_labels_ibug_300W_test.xml" 
[INFO] setting shape predictor options...
[INFO] shape predictor options:
shape_predictor_training_options(be_verbose=1, cascade_depth=15, tree_depth=4, num_trees_per_cascade_level=500, nu=0.05, oversampling_amount=2, oversampling_translation_jitter=0.1, feature_pool_size=300, lambda_param=0.1, num_test_splits=50, feature_pool_region_padding=0, random_seed=, num_threads=4, landmark_relative_padding_mode=1)
[INFO] training shape predictor...
Killed
```

## Steps to Reproduce

I followed [this tutorial](https://www.pyimagesearch.com/2019/12/16/training-a-custom-dlib-shape-predictor/) to re-train the shape predictor with my dataset. 

* **Version**: 19.22.0
* **Where did you get dlib**: `pip install dlib`
* **Platform**:  
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
* **Compiler**: Python 2.7.17

**Comment by davisking** [comment]
Sometimes you just need more RAM.

**Comment by bach05** [comment]
Yes, I have read in previous issues. But in my case, I have more or less 5 times the space required to load the entire training set. It's strange, isn't it?

 Is there a way to understand how much RAM you should need? Thank you.

**Comment by davisking** [comment]
It's not strange.  The algorithm has to hold a bunch of stuff in memory for
each training sample.  And the images are held decompressed too.

Generally speaking, to find out how much RAM a program needs you just run
it and see how much it uses.
