### ISSUE TITLE
Installation failed on zorin os 15.3

### ISSUE THREAD

**Issue by rinkeshpanwar** [davisking/dlib#2388]
Hello there installation failed on zorin os 15.3. I am using zorin os 15.3 and recently came across this library, tried to install but it failed. Firstly i was getting error for cmake, once i installed i am still not able to install this library. here is the complete error i am getting for installation of dlib in virtual environment. i am using python 3.6.9
pip install dlib
Collecting dlib
  Using cached dlib-19.22.0.tar.gz (7.4 MB)
Using legacy 'setup.py install' for dlib, since package 'wheel' is not installed.
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/rinkesh/Desktop/xcitechmlrepo/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6t78gbgo/install-record.txt --single-version-externally-managed --compile --install-headers /home/rinkesh/Desktop/xcitechmlrepo/include/site/python3.6/dlib
         cwd: /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/
    Complete output (285 lines):
    running install
    running build
    running build_py
    package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.6.9 (default, Jan 26 2021, 15:33:00)
    Invoking CMake setup: 'cmake /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/build/lib.linux-x86_64-3.6 -DPYTHON_EXECUTABLE=/home/rinkesh/Desktop/xcitechmlrepo/bin/python3 -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /home/rinkesh/Desktop/xcitechmlrepo/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: python3.6m
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.2.4
    -- Using CMake version: 3.20.5
    -- Compiling dlib version: 19.22.0
    -- SSE4 instructions can be executed by the host processor.
    -- AVX instructions can be executed by the host processor.
    -- Enabling AVX instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
     *****************************************************************************
     *** DLIB GUI SUPPORT DISABLED BECAUSE X11 DEVELOPMENT LIBRARIES NOT FOUND ***
     *** Make sure libx11-dev is installed if you want GUI support.            ***
     *** On Ubuntu run: sudo apt-get install libx11-dev                        ***
     *****************************************************************************
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    -- Looking for cblas_ddot
    -- Looking for cblas_ddot - not found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
     *****************************************************************************
     *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
     *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
     *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
     ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
     *** Or you can easily install OpenBLAS from source by downloading the     ***
     *** source tar file from http://www.openblas.net, extracting it, and      ***
     *** running:                                                              ***
     ***    make; sudo make install                                            ***
     *****************************************************************************
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
    -- Found CUDA, but CMake was unable to find the cuBLAS libraries that should be part of every basic CUDA install. Your CUDA install is somehow broken or incomplete. Since cuBLAS is required for dlib to use CUDA we won't use CUDA.
    -- DID NOT FIND CUDA
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/build/temp.linux-x86_64-3.6
    Invoking CMake build: 'cmake --build . --config Release -- -j2'
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    [  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
    [  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
    [  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
    [  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
    [  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
    [  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
    [  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
    [  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
    [  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
    [  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/test_for_odr_violations.cpp.o
    [  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
    [ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
    [ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
    [ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
    [ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
    [ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
    [ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
    [ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
    [ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
    [ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
    [ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
    [ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
    [ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
    [ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
    [ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
    [ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
    [ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
    [ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
    [ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
    [ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
    [ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
    [ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
    [ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
    [ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
    [ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
    [ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/cpu_dlib.cpp.o
    [ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/tensor_tools.cpp.o
    [ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
    [ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
    [ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/cifar.cpp.o
    [ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
    [ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/filtering/kalman_filter.cpp.o
    In file included from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/filtering/../matrix.h:11:0,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/filtering/kalman_filter.h:7,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/filtering/kalman_filter.cpp:6:
    /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/filtering/../matrix/matrix_la.h: In function ‘long int dlib::svd4(dlib::svd_u_mode, bool, const dlib::matrix_exp<EXP>&, dlib::matrix<typename EXP::type, uM, uN, MM1, L1>&, dlib::matrix<typename EXP::type, qN, qX, MM2, L1>&, dlib::matrix<typename EXP::type, vM, vN, MM3, L1>&) [with EXP = dlib::matrix_op<dlib::op_trans<dlib::matrix_op<dlib::op_trans<dlib::matrix<double, 1, 2, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > > > >; long int qN = 1; long int qX = 1; long int uM = 1; long int uN = 1; long int vM = 2; long int vN = 1; MM1 = dlib::memory_manager_stateless_kernel_1<char>; MM2 = dlib::memory_manager_stateless_kernel_1<char>; MM3 = dlib::memory_manager_stateless_kernel_1<char>; L1 = dlib::row_major_layout]’:
    /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/filtering/../matrix/matrix_la.h:225:32: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
                 y = abs(q(i)) + abs(e(i));
                                 ~~~^~~~~~
    /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/filtering/../matrix/matrix_la.h:163:20: note: within this loop
             for (i=0; i<n; i++)
                       ~^~
    [ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/svm/auto.cpp.o
    [ 32%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/arm/arm_init.c.o
    [ 33%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/arm/filter_neon_intrinsics.c.o
    [ 33%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/png.c.o
    [ 34%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngerror.c.o
    [ 34%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngget.c.o
    [ 35%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngmem.c.o
    [ 36%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngpread.c.o
    [ 36%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngread.c.o
    [ 37%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngrio.c.o
    [ 38%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngrtran.c.o
    [ 38%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngrutil.c.o
    [ 39%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngset.c.o
    [ 40%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngtrans.c.o
    [ 40%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwio.c.o
    [ 41%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwrite.c.o
    [ 42%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwtran.c.o
    [ 42%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwutil.c.o
    [ 43%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/adler32.c.o
    [ 44%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/compress.c.o
    [ 44%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/crc32.c.o
    [ 45%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/deflate.c.o
    [ 45%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzclose.c.o
    [ 46%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzlib.c.o
    [ 47%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzread.c.o
    [ 47%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzwrite.c.o
    [ 48%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/infback.c.o
    [ 49%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inffast.c.o
    [ 49%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inflate.c.o
    [ 50%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inftrees.c.o
    [ 51%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/trees.c.o
    [ 51%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/uncompr.c.o
    [ 52%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/zutil.c.o
    [ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
    [ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
    [ 54%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jaricom.c.o
    [ 54%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapimin.c.o
    [ 55%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapistd.c.o
    [ 56%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcarith.c.o
    [ 56%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccoefct.c.o
    [ 57%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccolor.c.o
    [ 58%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcdctmgr.c.o
    [ 58%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jchuff.c.o
    [ 59%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcinit.c.o
    [ 60%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmainct.c.o
    [ 60%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmarker.c.o
    [ 61%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmaster.c.o
    [ 62%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcomapi.c.o
    [ 62%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcparam.c.o
    [ 63%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcprepct.c.o
    [ 64%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcsample.c.o
    [ 64%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapimin.c.o
    [ 65%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapistd.c.o
    [ 65%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdarith.c.o
    [ 66%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatadst.c.o
    [ 67%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatasrc.c.o
    [ 67%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcoefct.c.o
    [ 68%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcolor.c.o
    [ 69%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jddctmgr.c.o
    [ 69%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdhuff.c.o
    [ 70%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdinput.c.o
    [ 71%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmainct.c.o
    [ 71%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmarker.c.o
    [ 72%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmaster.c.o
    [ 73%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmerge.c.o
    [ 73%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdpostct.c.o
    [ 74%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdsample.c.o
    [ 74%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jerror.c.o
    [ 75%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctflt.c.o
    [ 76%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctfst.c.o
    [ 76%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctint.c.o
    [ 77%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctflt.c.o
    [ 78%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctfst.c.o
    [ 78%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctint.c.o
    [ 79%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemmgr.c.o
    [ 80%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemnobs.c.o
    [ 80%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant1.c.o
    [ 81%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant2.c.o
    [ 82%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jutils.c.o
    [ 82%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
    [ 83%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
    [ 84%] Linking CXX static library libdlib.a
    [ 84%] Built target dlib
    [ 84%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o
    [ 85%] Building CXX object CMakeFiles/_dlib_pybind11.dir/src/matrix.cpp.o
    In file included from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/cast.h:13,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/attr.h:13,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/../dlib/python/pybind_utils.h:6,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/../dlib/python.h:6,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/tools/python/src/opaque_types.h:6,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/tools/python/src/matrix.cpp:4:
    /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    In file included from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/cast.h:13,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/attr.h:13,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/../dlib/python/pybind_utils.h:6,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/../dlib/python.h:6,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/tools/python/src/opaque_types.h:6,
                     from /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/tools/python/src/dlib.cpp:4:
    /tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/dlib/external/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    compilation terminated.
    CMakeFiles/_dlib_pybind11.dir/build.make:75: recipe for target 'CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o' failed
    make[2]: *** [CMakeFiles/_dlib_pybind11.dir/src/dlib.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/_dlib_pybind11.dir/build.make:89: recipe for target 'CMakeFiles/_dlib_pybind11.dir/src/matrix.cpp.o' failed
    make[2]: *** [CMakeFiles/_dlib_pybind11.dir/src/matrix.cpp.o] Error 1
    CMakeFiles/Makefile2:117: recipe for target 'CMakeFiles/_dlib_pybind11.dir/all' failed
    make[1]: *** [CMakeFiles/_dlib_pybind11.dir/all] Error 2
    Makefile:90: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/home/rinkesh/Desktop/xcitechmlrepo/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/rinkesh/Desktop/xcitechmlrepo/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py", line 134, in run
        self.build_extension(ext)
      File "/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py", line 174, in build_extension
        subprocess.check_call(cmake_build, cwd=build_folder)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/rinkesh/Desktop/xcitechmlrepo/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2xfd1yme/dlib_145d1f765d61431d907285099d624105/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6t78gbgo/install-record.txt --single-version-externally-managed --compile --install-headers /home/rinkesh/Desktop/xcitechmlrepo/include/site/python3.6/dlib Check the logs for full command output.

**Comment by davisking** [comment]
The output you pasted says 

Python.h: No such file or directory
#include <Python.h>

You need to install the python headers.

**Comment by rinkeshpanwar** [comment]
> The output you pasted says Python.h: No such file or directory #include <Python.h> You need to install the python headers.
> […](#)
> On Jul 2, 2021, at 6:14 AM, rinkesh panwar ***@***.***> wrote: Python.h: No such file or directory #include <Python.h>

actually, I am using  python so I don't think I need to import the python header in python itself...kindly provide a solution for the python3.6 programming language

**Comment by nmstoker** [comment]
Maybe I've misunderstood you @rinkeshpanwar but it looks like either:
1. you could be misunderstanding the point about the python headers (what you write suggests you might not know about how the Python headers work: you don't import them into python, they're usually an OS level package you install)
2. you could be running into a similar problem to #1269 whereby you need to create your virtual environment after you install the headers

Anyway, I'd start by trying:
````
sudo apt install python3.6-dev
````

If option 2 above applies, recreate your virtual env.
Then try again.
