### ISSUE TITLE
Image Loader BMP code unreachable

### ISSUE THREAD

**Issue by iaincoulter** [davisking/dlib#2392]
Image Loader BMP code tests the bitmap header. 
If the size of the bitmap header is not 40 dlib returns error 6 "header too small"  

BUT immediately after that it then tests if size is greater than 40.  Due to the fact the first condition throws an exception the second condition is never checked

```
           if (biSize != 40)
                throw image_load_error("bmp load error 6: header too small");

            // read and discard any extra bytes that are part of the header
            if (biSize > 40)
            {
```

* **Version**:  current master branch
* **Where did you get dlib**: github
* **Platform**: all
* **Compiler**: affects all compilers

**Comment by davisking** [comment]
Ha yeah, thanks.  That's some ancient code there :)  I just removed it.
