### ISSUE TITLE
Bad results on custom landmark predictor

### ISSUE THREAD

**Issue by PedroFumero** [davisking/dlib#2394]
I have trained a custom face landmark predictor using this hyperparameters:

- tree_depth = 4
- nu = 0.1
- cascade_depth = 15
- feature_pool_size = 400
- num_test_splits = 50
- oversampling_amount = 5
- oversampling_translation_jitter = 0.1

Next, I attached the final result: [Final result - Youtube](https://youtu.be/H-FHbnWklLI)

I would like to know, could be possible to get a better result on points stabilization tunning some hyperparameters and training again?

**Comment by arrufat** [comment]
The input video seems very noisy, have you tried with a better quality video?
