### ISSUE TITLE
Poor face recognition

### ISSUE THREAD

**Issue by DougRogers** [davisking/dlib#2399]
Running the face recognition example [here ](http://dlib.net/dnn_face_recognition_ex.cpp.html)

The attached images have faces that are not detected.  The faces are pretty obvious and I would have expected them to be recognized.

dlib Version 19.21, obtained from vcpkg
Windows x64, Release
Visual Studio 2019

![faces](https://user-images.githubusercontent.com/7563851/127062361-b3ebbfa7-5c9c-4ccb-aa17-9495d383ea23.jpg)
![faces2](https://user-images.githubusercontent.com/7563851/127062371-216a3455-e067-40ab-8dbc-d1fd27680083.jpg)
![faces3](https://user-images.githubusercontent.com/7563851/127062374-6c738f87-7b04-41d5-98c1-95c0a806f4a8.jpg)

**Comment by davisking** [comment]
Upsample the images before running the detector on them, since it's only going to find faces that are large enough.  Those must all be too small.

**Comment by DougRogers** [comment]
I up sampled and that helped, but the woman with her head on the man was not recognized.  Image #1.  In image #2 the woman at the bottom left was not recognized.
