### ISSUE TITLE
Compile Error -  non-constant condition

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#240]
Hi, its me once again.
Sorry to bother you.
Im trying to compile dlib on my debian 8.

But when i run this in my makefile:
`g++ -g -std=c++11 -Wall -O3 -mfpu=neon -funsafe-math-optimizations -fopenmp -mfloat-abi=hard -mtune=native -march=native -D USE_NEON -D USE_OPENMP   -c -g -I/usr/include -I/usr/local/include -MMD -MP -MF "build/Debug/GNU-Linux/dlib/all/source.o.d" -o build/Debug/GNU-Linux/dlib/all/source.o dlib/all/source.cpp`

i get multiple times the same error:
Example:
```
dlib/all/../base64/../assert.h:93:45: error: non-constant condition for static assertion
     #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
```

one more:

```
dlib/all/../data_io/../geometry/../matrix/matrix_utilities.h:2665:50: error: call to non-constexpr function ‘bool dlib::relational_operators::operator>(const A&, const B&) [with A = dlib::pixel_traits<dlib::rgb_pixel>::<anonymous enum>; B = int]’
         COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
```

Maybe you got a idea what the problem is?
Best regards

                                             ^

**Comment by devil6665** [comment]
avrdude: Version 6.3-20171130
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr/etc/avrdude.conf"

         Using Port                    : COM3
         Using Programmer              : arduino
         Overriding Baud Rate          : 57600
avrdude: ser_open(): can't open device "\\.\COM3": Odmowa dost�pu.



avrdude done.  Thank you.

Problem z wgrywaniem na płytkę. Sprawdź http://www.arduino.cc/en/Guide/Troubleshooting#upload w poszukiwaniu sugestii.
