### ISSUE TITLE
Face clustering identifies two different people as the same person.

### ISSUE THREAD

**Issue by DougRogers** [davisking/dlib#2402]
The two women with glasses are incorrectly identified as the same person.  

![faces2](https://user-images.githubusercontent.com/7563851/127366216-01833ae2-e3d4-47d7-bd0b-b068f4b92a97.jpg)
![faces4](https://user-images.githubusercontent.com/7563851/127366632-1f432acd-fb47-4627-b708-8e5c3f459777.jpg)

**Comment by davisking** [comment]
I'm not sure what you are referring to.  The dlib example program?  It's an educational document.  Not a turn key face clustering application.

**Comment by DougRogers** [comment]
Yes. The example program.  I assumed that it would be more than just educational.
