### ISSUE TITLE
Face detection incorrectly identifies object as face.

### ISSUE THREAD

**Issue by DougRogers** [davisking/dlib#2403]
Two faces are detected in this image
![faces5](https://user-images.githubusercontent.com/7563851/127403676-756ec1f2-ba74-4937-8683-3b412ea4e3b2.jpg)

**Comment by VisionEp1** [comment]
Any detection will have some false positives especially the nn based ones. 
I dont quite understand the point of this issue

**Comment by DougRogers** [comment]
The silver circle does not seem remotely like a face, so it seems more than just a normal false positive. So what do I need to use to get fairly reliable face recognition since the example does not do that?
