### ISSUE TITLE
Dlib 19.4.0 install problem: "cmake configuration error!"

### ISSUE THREAD

**Issue by Babobox0626** [davisking/dlib#2406]
Hello, I'm sorry about my poor English ability.

First of all, I am going to use the LipNet model in Ubuntu 20.04, python 2.7.18.

I downloaded that git(https://github.com/rizkiarm/LipNet) from github and I entered Linux Terminal and typed 
sudo python setup.py install 
(Since the created model was written based on Python 2.7, I had no choice but to use Python 2.7.)

An error occurred while downloading dlib 19.4.0.

linux@linux-14Z970-EA50K:~/Download/LipNet-master$ sudo python setup.py install
running install
Searching for dlib==19.4.0
Reading https://pypi.org/simple/dlib/
Downloading https://files.pythonhosted.org/packages/1d/76/0f91fde37a83a40cf27e6cabd900b975c2667c522a07ae38e31cda2fa486/dlib-19.4.0.tar.gz#sha256=c23c172dd42d7bf703392e2ba6414e986e8ff5e3be1f848f0f1d1733fc0895b8
Best match: dlib 19.4.0
Processing dlib-19.4.0.tar.gz
Writing /tmp/easy_install-m3E4pd/dlib-19.4.0/setup.cfg
Running dlib-19.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-m3E4pd/dlib-19.4.0/egg-dist-tmp-2yyuV2
error: Setup script exited with error: cmake configuration failed!

so I typed 
pip install dlib, 
pip install cmake
so I already have dlib==19.22.0, cmake==3.21.1

But when I type sudo python setup.py install
I got same error (error: Setup script exited with error: cmake configuration failed!) while download dlib

How can I fix it?, I searched various information on Google, but they didn't work.

* **Version**: <dilb==19.4.5>
* **Where did you get dlib**: <installing setup.py from the git(https://github.com/rizkiarm/LipNet) >
* **Platform**: <ubuntu 20.04, 64-bit -->
* **Compiler**: <ubuntu Terminal>

**Comment by Babobox0626** [comment]
I also tryed pip install dlib==19.4.0, but I got error

Attempting uninstall: dlib
    Found existing installation: dlib 19.22.0
    Uninstalling dlib-19.22.0:
      Successfully uninstalled dlib-19.22.0
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pd7_e8/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pd7_e8/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z_5BIu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/linux/.local/include/python2.7/dlib
         cwd: /tmp/pip-install-pd7_e8/dlib/
    Complete output (29 lines):
    running install
    running build
    Detected Python architecture: 64bit
    Detected platform: linux2
    Removing build directory /tmp/pip-install-pd7_e8/dlib/./tools/python/build
    Configuring cmake ...
    CMake Warning (dev) in CMakeLists.txt:
      No project() command is present.  The top-level CMakeLists.txt file must
      contain a literal, direct call to the project() command.  Add a line of
      code such as
        project(ProjectName)
      near the top of the file, but after cmake_minimum_required().
      CMake is pretending there is a "project(Project)" command on the first
      line.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Could NOT find Boost (missing: python) (found suitable version "1.71.0", minimum required is "1.41.0")
    error: cmake configuration failed!
    ----------------------------------------
  Rolling back uninstall of dlib
  Moving to /home/linux/.local/lib/python2.7/site-packages/_dlib_pybind11.so
   from /tmp/pip-uninstall-W5_1wF/_dlib_pybind11.so
  Moving to /home/linux/.local/lib/python2.7/site-packages/dlib-19.22.0.dist-info/
   from /home/linux/.local/lib/python2.7/site-packages/~lib-19.22.0.dist-info
  Moving to /home/linux/.local/lib/python2.7/site-packages/dlib/
   from /home/linux/.local/lib/python2.7/site-packages/~lib
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pd7_e8/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pd7_e8/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z_5BIu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/linux/.local/include/python2.7/dlib Check the logs for full command output.

**Comment by davisking** [comment]
That version of dlib is super old.  Use the current version.
