### ISSUE TITLE
Compilation errors including clustering.h

### ISSUE THREAD

**Issue by pparkman** [davisking/dlib#2413]
compilation errors with CUDA compile on Centos

## Expected Behavior
trying to compile after upgrading to latest version

## Current Behavior

-- 
-- ******************* piXsearch Configuration Summary *******************
-- General:
--   Version           :   9.6L
--   System            :   Linux
--   C++ compiler      :   /usr/local/bin/g++
--   Release CXX flags :   -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -std=c++11 -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
-- 
-- Dependencies:
--   BLAS              :   Yes ()
--   Boost             :   Yes (ver. 1.65)
--   OpenCV            :   Yes (ver. 4.5.1)
--   CUDA              :   No
-- 
-- Install:
--   Install path      :   /home/admin/Indigo/E/Projects/9.6_Work_L/_src/_x64/_bin/install
-- 
--   targets           :   
--   package           :   
-- Configuring done
-- Generating done

[ 12%] Building CXX object dld/CMakeFiles/dld.dir/dldInterface.cpp.o
In file included from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/sparse_vector.h:9:0,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../sparse_vector.h:6,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/modularity_clustering.h:7,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering.h:6,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/dldInterface.cpp:26:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../algs.h:1096:11: error: \u2018score_func\u2019 has not been declared
         F score_func
           ^~~~~~~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../algs.h:1137:11: error: \u2018score_func\u2019 has not been declared
         F score_func
           ^~~~~~~~~~
In file included from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads.h:21:0,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/matrix_la.h:25,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix.h:11,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/sparse_vector.h:13,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../sparse_vector.h:6,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/modularity_clustering.h:7,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering.h:6,
                 from /home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/dldInterface.cpp:26:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:32:36: error: expected \u2018)\u2019 before \u2018,\u2019 token
             super_funct_4 ( F funct, T1 arg1, T2 arg2, T3 arg3, T4 arg4) :
                                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:44:15: error: \u2018f\u2019 does not name a type
             F f;
               ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:55:36: error: expected \u2018)\u2019 before \u2018,\u2019 token
             super_funct_3 ( F funct, T1 arg1, T2 arg2, T3 arg3):
                                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:66:15: error: \u2018f\u2019 does not name a type
             F f;
               ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:76:36: error: expected \u2018)\u2019 before \u2018,\u2019 token
             super_funct_2 ( F funct, T1 arg1, T2 arg2) :
                                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:86:15: error: \u2018f\u2019 does not name a type
             F f;
               ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:95:36: error: expected \u2018)\u2019 before \u2018,\u2019 token
             super_funct_1 ( F funct, T arg) : f(funct), a(arg)
                                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:102:15: error: \u2018f\u2019 does not name a type
             F f;
               ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:110:36: error: function definition does not declare parameters
             super_funct_0 ( F funct) : f(funct)
                                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:116:15: error: \u2018f\u2019 does not name a type
             F f;
               ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:13: error: \u2018f\u2019 was not declared in this scope
             f.reset(new super_funct_0<F>(funct));
             ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:40: error: wrong number of template arguments (0, should be 1)
             f.reset(new super_funct_0<F>(funct));
                                        ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:107:15: note: provided for \u2018template<class> class dlib::thread_function::super_funct_0\u2019
         class super_funct_0 : public base_funct
               ^~~~~~~~~~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:42: error: \u2018funct\u2019 was not declared in this scope
             f.reset(new super_funct_0<F>(funct));
                                          ^~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:42: note: suggested alternative: \u2018fRect\u2019
             f.reset(new super_funct_0<F>(funct));
                                          ^~~~~
                                          fRect
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:49: error: expected \u2018}\u2019 before \u2018;\u2019 token
             f.reset(new super_funct_0<F>(funct));
                                                 ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:49: error: field \u2018funct\u2019 has incomplete type \u2018dlib::thread_function\u2019
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:18:11: note: definition of \u2018class dlib::thread_function\u2019 is not complete until the closing brace
     class thread_function : private threaded_object
           ^~~~~~~~~~~~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:126:49: error: data member \u2018funct\u2019 cannot be a member template
             f.reset(new super_funct_0<F>(funct));
                                                 ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:127:19: error: ISO C++ forbids declaration of \u2018start\u2019 with no type [-fpermissive]
             start();
                   ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:128:10: error: expected \u2018;\u2019 after class definition
         }
          ^
          ;
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h: In member function \u2018void dlib::thread_function::super_funct_0< <template-parameter-1-1> >::go()\u2019:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:114:25: error: there are no arguments to \u2018f\u2019 that depend on a template parameter, so a declaration of \u2018f\u2019 must be available [-fpermissive]
             void go() { f(); }
                         ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:114:25: note: (if you use \u2018-fpermissive\u2019, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h: At global scope:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:132:20: error: expected \u2018)\u2019 before \u2018,\u2019 token
             F funct,
                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:142:20: error: expected \u2018)\u2019 before \u2018,\u2019 token
             F funct,
                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:153:20: error: expected \u2018)\u2019 before \u2018,\u2019 token
             F funct,
                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:165:20: error: expected \u2018)\u2019 before \u2018,\u2019 token
             F funct,
                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:177:9: error: declaration of \u2018~dlib::thread_function\u2019 as non-member
         )
         ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:183:11: error: non-member function \u2018bool dlib::is_alive()\u2019 cannot have cv-qualifier
         ) const
           ^~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h: In function \u2018bool dlib::is_alive()\u2019:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:185:46: error: cannot call member function \u2018bool dlib::threaded_object::is_alive() const\u2019 without object
             return threaded_object::is_alive();
                                              ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h: At global scope:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:189:11: error: non-member function \u2018void dlib::wait()\u2019 cannot have cv-qualifier
         ) const
           ^~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h: In function \u2018void dlib::wait()\u2019:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:191:35: error: cannot call member function \u2018void dlib::threaded_object::wait() const\u2019 without object
             threaded_object::wait();
                                   ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h: At global scope:
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:194:5: error: expected unqualified-id before \u2018private\u2019
     private:
     ^~~~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:201:25: error: \u2018base_funct\u2019 was not declared in this scope
         std::unique_ptr<base_funct> f;
                         ^~~~~~~~~~
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:201:25: note: suggested alternative: \u2018iswpunct\u2019
         std::unique_ptr<base_funct> f;
                         ^~~~~~~~~~
                         iswpunct
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:201:35: error: template argument 1 is invalid
         std::unique_ptr<base_funct> f;
                                   ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:201:35: error: template argument 2 is invalid
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:204:40: error: expected \u2018)\u2019 before \u2018&\u2019 token
         thread_function(thread_function&);        // copy constructor
                                        ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:205:52: error: \u2018dlib::thread_function& dlib::operator=(dlib::thread_function&)\u2019 must be a nonstatic member function
         thread_function& operator=(thread_function&);    // assignment operator
                                                    ^
/home/admin/Indigo/E/Projects/9.6_Work_L/_src/piXsearch/dld/../../_ExtrnHeaders/dlib/clustering/../svm/../matrix/../threads/thread_function_extension.h:210:1: error: expected declaration before \u2018}\u2019 token
 }
 ^

## Steps to Reproduce
try to compile using a Makelist that has worked for years

operational statement seems to be: 
#include <dlib/clustering.h>

* **Version**: 
* The latest version - dlib 19-22
* **Where did you get dlib**: 
* github repo
* **Platform**: 
Centos 
* **Compiler**: 
g++ 7.3.0

**Comment by davisking** [comment]
I'm guessing you have defined or included some other code elsewhere that has done `#define score_func` to some odd string.
