### ISSUE TITLE
Why is assertion on parsed_line() in command_line_parser::add_option needed and can we make the parser object reusable?

### ISSUE THREAD

**Issue by KOLANICH** [davisking/dlib#2421]
## Expected Behavior
```c++
dlib::command_line_parser app;
app.add_option(...);
app.parse(...);
app.add_option(...); // should be OK
app.parse(...);  // should parse
```

## Current Behavior
Assertion failure, parsed_line() is true. cmd_line_parser_kernel_c.h, line 113 (thrown from the last `add_option` call).

Looking into the source I found that `clear()` clears that flag, and also deletes all the options. I wonder if it is really needed and if we can get appendable args without breaking anything.

* **Version**: 19l10-3build1
* **Where did you get dlib**: Ubuntu Hirsute packages (`libdlib-dev`)
* **Platform**: x86_64
* **Compiler**: clang 14

**Comment by davisking** [comment]
I see what you mean.   Sure, if you want to post a PR that makes this change that's fine with me.  Please be sure to update the docs in the abstract.h header as well.

**Comment by KOLANICH** [comment]
Does the library currently rely anyhow on the fact that currently it is not allowed to append into args spec after parsing of a CLI? In other words, can we just remove the assertion without allowing strange or insecure behavior or do we have to make any changes in other places too?

**Comment by davisking** [comment]
I'm not sure. You should look and send me a PR :)
