### ISSUE TITLE
Online or streaming ml functionalities?

### ISSUE THREAD

**Issue by andrewm4894** [davisking/dlib#2423]
Hello, 

just a question I could not really figure out from the docs. Is there any streaming or online ml algos in dlib?

I'm thinking about online clustering for example.

I think we could leverage what is there for some versions of mini batched type approaches but was just wondering if any specific online stuff implemented.

Cheers,
Andy

**Comment by davisking** [comment]
There isn't any online clustering code.  Although you could adapt stuff
like http://dlib.net/ml.html#chinese_whispers pretty easily to do it.

**Comment by andrewm4894** [comment]
cool thanks - will do some research
