### ISSUE TITLE
Question: dlib::type_safe_union::swap()

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2425]
Why is the swap function not just this:
```
void swap (
    type_safe_union& item
)
{
    std::swap(mem, item.mem);
    std::swap(type_identity, item.type_identity);
}
```

**Comment by pfeatherstone** [comment]
If you try it, the unit tests don't pass. But i cannot see why...

**Comment by pfeatherstone** [comment]
Is it that this won't work if whatever object is being constructed with placement-new stores its own underlying storage in a pointer. Possibly std::string does this?

**Comment by pfeatherstone** [comment]
Something like that.

**Comment by davisking** [comment]
Right. That wouldn't work for objects that are not trivially copyable. Such as std::string.

**Comment by pfeatherstone** [comment]
Yeah I understand why now. But fundamentally, you would think, "why can't I swap the storage, and the thing that tells you how to read the storage". After a few years of C++ing, you still get surprised by subtle things like this. If you're a hardcore python programmer and have never had to care about memory or object layout in your life, I would recommend never to touch C++, coz you will write bugs like these.
