### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by andrewm4894** [davisking/dlib#2427]
Hello again :)

We are looking to use dlib in our monitoring agent ([netdata](https://github.com/netdata/netdata)) to power some anomaly detection features on the agent.

I see dlib is boost and we are GPLv3. I'm just starting process to make sure we are compatible etc. which i will follow up with our legal team as it's not anything i have a great understanding of myself at all. 

But i was just wondering if you see any potential issues with netdata making use of dlib in this way? Or have any precedence of other example projects that might have used dlib in similar ways etc.

Many thanks for the project, love it!

**Comment by davisking** [comment]
Na, you can use dlib with that. There is no conflict.

**Comment by MyLtYkRiTiK** [comment]
Hello Davis,
May it is possible to get advice about pretrained models? 
There are restrictions for landmark model due to dataset restrictions.
But are pretrained detectors restricted too? Like Hog and CNN one? 
Or recognition model?

Thanks,
Valentina

**Comment by MyLtYkRiTiK** [comment]
I see, Davis, thank you!
