### ISSUE TITLE
Question: How to enable cuda support when installing dlib from vcpkg?

### ISSUE THREAD

**Issue by Darker** [davisking/dlib#2433]
The fact that `dlib` is on vcpkg was one of the most compelling reasons for me to try it, since I wanted to learn using neural networks, not spend a lot of time setting and compiling a library.

However, now that I have successfully built the example I don't really think it is using my graphics card (NVidia GTX 1060). I suppose I will need to install cuda from here: https://developer.nvidia.com/cuda-90-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal

And then somehow rebuild with some vcpkg parameter? I am really not sure.

**Comment by davisking** [comment]
I'm not sure since I don't use vcpkg.  They might have some cuda option.  You will have to look at their docs for how vcpkg deals with cuda.   Or just use cmake, which is what I would normally use instead of vcpkg.

**Comment by arrufat** [comment]
@Darker I've also never used vcpkg, but came across this project, flashlight, which has cuda as a dependency and uses vcpkg: https://github.com/flashlight/flashlight#from-source-build-with-vcpkg
