### ISSUE TITLE
Train object detector details

### ISSUE THREAD

**Issue by mrgloom** [davisking/dlib#244]
Seem I have successfully trained object detector based on [train_object_detector.cpp](https://github.com/davisking/dlib/blob/02d8ebc903443e994d74c80c59a6c0886748cf1f/examples/train_object_detector.cpp) example.

`time ./train_object_detector -tv -u 0 --threads 4 --flip data/training.xml`
~~~
Loading image dataset from metadata file data/training.xml
Number of images loaded: 78
objective:     45.1205
objective gap: 45.1167
risk:          45.1167
risk gap:      45.1167
num planes:    3
iter:          1

...

objective:     3.44535
objective gap: 0.00889926
risk:          2.99319
risk gap:      0.00889926
num planes:    60
iter:          157

Saving trained detector to object_detector.svm
Testing detector on training data...
Test detector (precision,recall,AP): 1 0 0 

Parameters used: 
  threads:                 4
  C:                       1
  eps:                     0.01
  target-size:             6400
  detection window width:  80
  detection window height: 80
  upsample this many times : 0
  trained using left/right flips.


real	3m17.072s
user	9m54.928s
sys	0m4.328s
~~~

But then I try to apply detector to any image from training set it can't detect any objects `Number of detections: 0`.

**Comment by e-fominov** [comment]
> Test detector (precision,recall,AP): 1 0 0 

until you will get "1 1 1" - your detector is not trained well

P.S. goto stackoverflow. this is not a bug

**Comment by mrgloom** [comment]
Ok.
http://stackoverflow.com/questions/39660801/train-object-detector-using-dlib
