### ISSUE TITLE
dlib fails to detect faces

### ISSUE THREAD

**Issue by neerajBaji** [davisking/dlib#245]
Hi,

I ran dlib on this dataset of 48x48 facial images (https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data) but dlib fails to detect faces in about 30% of the images (~10000 images)

I understand that dlib has been trained on 80x80 sized images and hence I resize the images before feeding them into the detector.

Any pointers would help. If this is not the correct forum for such questions, please redirect to me the correct forum and I shall repost my question there.

Thanks

**Comment by davisking** [comment]
The detector is what it is.  But there is a deeper question, why do you
want to run a detector on an image that is already cropped around the
face?  You already know where the face is.

**Comment by neerajBaji** [comment]
Fair point. I am trying to extract facial landmarks and then feed those downstream for emotion detection. 
I will run the landmark detection directly on the images. 

I wanted to be sure that I am not using the dlib face detector in an incorrect manner.
Apologies for the wasted time.

Thanks!

**Comment by davisking** [comment]
No worries.  It's very likely that the cropping adversely effects the
detector.  I haven't looked at the images, but the edge of the image looks
like black pixels to the detector and that could throw it off if its right
next to the face.
