### ISSUE TITLE
Intellisense of Visual Studio too slow in dlib

### ISSUE THREAD

**Issue by z-pc** [davisking/dlib#2455]
Hi,
### Current Behavior
this problem may be not from dlib, but I tested on some other machines (above VS 2015, VS 2019), all is too slow when I using Intellisense of VS to find reference of variable or definition of types.
Intellisense almost does not work, It's make for me some annoying.
I feedbacke [this problem](https://developercommunity.visualstudio.com/t/Intellisense-too-slow-on-large-Solution/1554299?space=62&entry=myfeedback) to Visual Studio forum, but there doesn't seem to be any progress.
Intellisense on other my local projects is normally.

### Steps to Reproduce
I just do,:
```
git clone https://github.com/davisking/dlib.git
cd dlib/examples
mkdir build & cd build
cmake .. -G "Visual Studio 16 2019" -Ax64
```
then open
-> output examples solution
-> “dnn_imagenet_train_ex” project
-> “dnn_imagenet_train_ex.cpp” file
and try find declare some variable that declared in that document.

Sorry if this not should post in here.

* **Version**:  19.22.1
* **Where did you get dlib**: on git
* **Platform**: Windows 11 Enterprise 64bit
* **Compiler**: Visual Studio 2019 and VS2015

**Comment by davisking** [comment]
That's a problem with visual studio.   Try variations on this: https://github.com/davisking/dlib/blob/master/dlib/dnn.h#L15-L24

**Comment by z-pc** [comment]
Nightmare with me, 
Thanks davis.
