### ISSUE TITLE
Import Face_recognition got reason: initialization error

### ISSUE THREAD

**Issue by ChesterProgram** [davisking/dlib#2456]
Dlib==19.22.0
I got Dlib from the official site
Windows 10 pro 64bit
The Compiler I used Cmake
I used GT 630

The expected behavior is I can import Face recognition

The current behavior is when I import Face_recogntion 
I get this Error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'face_recogntion'
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\face_recognition\__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\face_recognition\api.py", line 26, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file C:\dlib-19.22\dlib\cuda\gpu_data.cpp:204. code: 3, reason: initialization error

Steps to reproduce
Install visual studio 2019
install cmake
compile dlib with cmake
install face_recognitiom
and lastly import face_recogntion

**Comment by ChesterProgram** [comment]
Is there a gpu requirment to use Dlib?

**Comment by davisking** [comment]
> Is there a gpu requirment to use Dlib?

No

**Comment by ChesterProgram** [comment]
Then why did I run import face recognition it says dlib\cuda\gpu_data.cpp:204. code: 3, reason: initialization error
