### ISSUE TITLE
Read matrix from CSV with semicolon as separator

### ISSUE THREAD

**Issue by aribiere** [davisking/dlib#2459]
## Expected Behavior
I want to use semicolon (`;`) separator when importing CSV file to matrix.

It seems to be a *very* small code modification in [here](https://github.com/davisking/dlib/blob/master/dlib/matrix/matrix_read_from_istream.h) so, a pull request may be a bit excessive... But I can create one if needed.

Thanks!

## Current Behavior
CSV import can be done easily as explained [here](https://github.com/davisking/dlib/blob/master/examples/matrix_ex.cpp#L140-L142) but separators *must* be:

> either space, tab, or comma

So now I need to replace all semi-colons with commas in my CSVs...

## Steps to Reproduce
Use any semi-colon separated CSV file to import to matrix.

* **Version**: v19.22
* **Where did you get dlib**: from dlib.net
* **Platform**: Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

* **Compiler**: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by davisking** [comment]
Sure, send me a PR :)

**Comment by aribiere** [comment]
Sorry, I forgot to close it 😕 

Thanks for the merge!
