### ISSUE TITLE
import dlib fails on macosx arm64

### ISSUE THREAD

**Issue by oliverguhr** [davisking/dlib#2469]
Hello,
importing dlib 19.22.1 fails with following error message. If I build dlib from source the import fails with the same error message.

```
ImportError: dlopen(/venv/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-darwin.so, 0x0002): 
symbol not found in flat namespace '_png_do_expand_palette_rgb8_neon'
```

## Steps to Reproduce

```
$ pip install dlib
Collecting dlib
  Using cached dlib-19.22.1-cp38-cp38-macosx_12_0_arm64.whl
Installing collected packages: dlib
Successfully installed dlib-19.22.1
```
```
$ python 
Python 3.8.9 (default, Aug  3 2021, 19:21:54) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.8/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen(/venv/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_png_do_expand_palette_rgb8_neon'
```

* **Version**: 19.22.1 
* **Where did you get dlib**:installed via pip
* **Platform**: MacOSX M1
* **Compiler**: Apple clang version 13.0.0

**Comment by davisking** [comment]
Something about your copy of libpng is broken.  Or something about your environment is broken.  There is `dlib/dlib/cmake_utils/test_for_libpng` in dlib that is built during the install process to test if you have a functional libpng, and if it fails then it won't use libpng.  But apparently this:
```
cd dlib/dlib/cmake_utils/test_for_libpng
mkdir build
cd build
cmake ..
make
```
must not give any errors for some reason?  Even though apparently your libpng it finds must be broken in some way.

**Comment by mit-vincode** [comment]
Hello! I have a similar problem (macos m1 x86_64 python3.9.7).

In the terminal, a report that dlib is installed successfully:

(tensorflow) bolkhovskiydmitriy @ x86_64-apple-darwin13 CamGroup02% pip install dlib
Requirement already satisfied: dlib in /Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages (19.22.99)

But when I try to run the import dlib code, I get an error:

    import dlib
  File "/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen (/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so, 2): no suitable image found. Did find:
/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so: mach-o, but wrong architecture
/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so: mach-o, but wrong architecture

Please help me figure it out

**Comment by oliverguhr** [comment]
@davisking Thanks for your fast response. You are right building "test_for_libpng" works just fine. I installed dlib in a fresh virtual environment and it worked just fine and now it works in all other environments. I could not figure out what caused this issue.

**Comment by oliverguhr** [comment]
@mit-vincode It looks like there is no Mac ARM package for dlib on conda. Try installing it via `pip install dlib`

**Comment by mit-vincode** [comment]
@oliverguhr Conda doesn't really install the package at all - conda install dlib - it just throws an error. As I wrote above, pip install dlib - the package is installed without errors.
Dlib package installed
However, when running the / import dlib / code, an error is thrown

File "/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/dlib/init.py", line 19, in
from _dlib_pybind11 import *
ImportError: dlopen (/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so, 2): no suitable image found. Did find:
/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so: mach-o, but wrong architecture
/Users/bolkhovskiydmitriy/miniforge3/envs/tensorflow/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-darwin.so: mach-o, but wrong architecture
