### ISSUE TITLE
Compiling error - scan_fhog_pyramid is not a template

### ISSUE THREAD

**Issue by ShacharWeis** [davisking/dlib#247]
I compiled the examples and everything was fine, than I changed something and it stopped compiled. I undid all my changes, and it STILL WONT COMPILE.

The error I get - scan_fhog_pyramid is not a template.

I traced it back to this file - dlib-19.1\dlib\image_processing\scan_fhog_pyramid_abstract.h

and the first two lines are:
```
#undef DLIB_SCAN_fHOG_PYRAMID_ABSTRACT_Hh_
#ifdef DLIB_SCAN_fHOG_PYRAMID_ABSTRACT_Hh_
```

I don't understand this at all. Why does it undefine a var and then asks if the var exists? The whole include file is grayed out. I can't figure out how this compiled in the first place.

Can someone explain this?

Thanks.

**Comment by davisking** [comment]
You must not have undone all your changes.  I would download a fresh copy of dlib and try again. 

The abstract.h files contain only documentation. All of this is explained in the dlib introduction: http://dlib.net/intro.html

**Comment by ShacharWeis** [comment]
It is the only place I found that defines scan_fhog_pyramid. If not there, where is scan_fhog_pyramid coming from?

**Comment by ShacharWeis** [comment]
ok, you are right, something got messed up with my dlib files.
