### ISSUE TITLE
**this is not an issue but a question** microprocessor extensions SSE AVX

### ISSUE THREAD

**Issue by patatetom** [davisking/dlib#2470]
hi,

I embed Dlib in a Linux Live distribution and so, _even if they are now all supported by the new generations of microprocessors_, I do not know in advance the capabilities of the microprocessor.

to do this, I compile Dlib three times with different options and I link the right library according to the microprocessor capabilities at system startup.

compilation options are :

- `--no USE_SSE4_INSTRUCTIONS --no USE_AVX_INSTRUCTIONS` for microprocessors with no SSE4 and AVX extension,
- `--no USE_AVX_INSTRUCTIONS` for microprocessors with no AVX extension,
- and  _no option_ (eg. nothing) for microprocessors with all extensions.
 
is it necessary to make these three compilations ?
if i compile Dlib with all the extensions enabled (eg. no compilation option), will it be able to run on a machine that doesn't have them or that doesn't have all of them ?

thank you in advance for your explanations.
regards, lacsaP.

**Comment by davisking** [comment]
No, you can't execute a binary that uses SS4 instructions (or whatever other instruction set) on a machine that doesn't have SSE4 instructions if the silicon doesn't actually support SSE4.  This isn't a dlib limitation, it's just how this stuff is in general.

**Comment by patatetom** [comment]
hi Davis,

thanks for your quick feedback.

so, if I understand correctly, I have to keep compiling Dlib three times : the _"who can do more can do less"_ does not take place in these conditions.

here is the code I use to dynamically link the right shared object at the start of the live system :

```bash
ln -sfv dlib.sse2 ${so:=/usr/lib/python3.9/site-packages/_dlib_pybind11.cpython-39-x86_64-linux-gnu.so}
grep -q '\<sse4[^a]' <( grep ^flags /proc/cpuinfo ) && ln -sfv dlib.sse4 ${so}
grep -q '\<avx' <( grep ^flags /proc/cpuinfo ) && ln -sfv dlib.avx ${so}
```

the three shared objects are previously registered in `/usr/lib/python3.9/site-packages/`.

thanks a lot for Dlib Davis, regard, lacsaP.

**Comment by davisking** [comment]
Right. Either that or always build without those instructions.
