### ISSUE TITLE
About save_face_chips with rotation

### ISSUE THREAD

**Issue by BingoGreen** [davisking/dlib#2473]
In the reference, it says "The faces will be **rotated upright** and ....". Why the faces would be rotate, please? And how to extract the face **without rotation,** just preserving original angle. I try to find the souce code of this function and change it in python sitepackage, but it is only an __init__.py. How to address it please, thanks~

**Comment by arrufat** [comment]
If you don't want to get the face rotated upright (or aligned) you shouldn't use `get_face_chips`. The function that you want is [`get_image_chips`](http://dlib.net/python/index.html#dlib.extract_image_chips).

**Comment by BingoGreen** [comment]
> If you don't want to get the face rotated upright (or aligned) you shouldn't use `get_face_chips`. The function that you want is [`get_image_chips`](http://dlib.net/python/index.html#dlib.extract_image_chips).

How about save the image please? "dlib.save_face_chips()" also rotate and "dlib.save_image()" doesn't recieve " faces:dlib.full_object_detections", how to save face chips without rotation please? Thanks
