### ISSUE TITLE
How to build it for macOS to use this library in ObjectiveC xcode project?

### ISSUE THREAD

**Issue by wXMart961** [davisking/dlib#2476]
I used `python setup.py install` command to make build for to use in Objective-C xcode project. But I can see the `libdlib.a` generated inside `dlib/build/temp.macosx-10.9-x86_64-3.9/dlib_build` folder. 

 ![Screenshot 2021-12-19 at 7 31 58 AM](https://user-images.githubusercontent.com/96360827/146661053-93609e63-5024-4e56-95b2-08a39d34a769.png)

 ## Expected Behavior
 I've to include `#include <dlib/image_processing.h>` header file. 

## Current Behavior
I get error `'dlib/image_processing.h' file not found`.

I tried 
`mkdir build`
`cd build`
`cmake ..`
`cmake --build . --config Release`

by following [this](https://github.com/davisking/dlib/blob/master/examples/CMakeLists.txt) doc.

but also get error
![Screenshot 2021-12-19 at 7 53 50 AM](https://user-images.githubusercontent.com/96360827/146661350-bd227f2f-d804-4ef1-a2de-ecd728b5e5e2.png)

## Steps to Reproduce
 I just want to generate library for macOS to use it in Xcode project. 
 
* **Version**: Latest
* **Platform**: macOS catalina
* **Compiler**:

**Comment by davisking** [comment]
You don't use setup.py for this.  setup.py is only for python users. See http://dlib.net/compile.html

**Comment by wXMart961** [comment]
@davisking Inside `dlib/dlib` I ran this commands,

`mkdir build`
`cd build`
`cmake ..`
`cmake --build . --config Release`

This generates `libdlib.a` file. 

![Screenshot 2021-12-19 at 11 23 43 PM](https://user-images.githubusercontent.com/96360827/146685391-bdd5ab0a-565e-4963-88ea-2299f0385029.png)

But I'm still getting same error. `'dlib/image_processing.h' file not found`.  I've to use [SameFace](https://github.com/BohdanNikoletti/SameFace/tree/develop/lib) library for macOS. I did all conversion but, I couldn't able build `dlib` for macOS.

![Screenshot 2021-12-19 at 11 28 43 PM](https://user-images.githubusercontent.com/96360827/146685528-4b5588cb-5594-4979-9308-ec0215b57b57.png)

I am not sure whether I am doing correct way to get build for macOS. Can you please help me?

**Comment by wXMart961** [comment]
I included header files like these,

```
#include "../../lib/dlib/image_processing.h"
#include "../../lib/dlib/opencv.h"
```
