### ISSUE TITLE
F77_INT: undeclared identifier

### ISSUE THREAD

**Issue by MurphyLaw** [davisking/dlib#248]
Hi,
so I tried using your library through Visual Studio 2015 and I think I did the things here(http://dlib.net/compile.html) correctly because when I tried compiling and running some examples it runs completely but when I create my own program I ran into this problem.
In cblas_icamax.c, cblas_idamax.c, cblas_isamax.c, cblas_izamax.c I get this error:
'F77_INT': undeclared identifier and
'iamax': undeclared identifier.

what should I do? is there something that I missed doing?
oh and I use some OpenCV Libraries too.

thank you

**Comment by davisking** [comment]
When you "created your own program" what did you do?  It looks like you
added a bunch of cblas files into your project.  Nowhere in the dlib
compile instructions does it say to put cblas files into your project.

**Comment by MurphyLaw** [comment]
well it's in the external folder and it says in the instructions to add all the source files in the dlib/external folder so I added libjpeg, libpng, zlib, and cblas.
well the program that I'm recreating, I should say, is the fhog_object_detector and I'm adding some OpenCV there.
should I add the cblas folder on my project?

**Comment by davisking** [comment]
I guess that's confusing.  I mean all the files for png and jpeg. :)

No, you don't need cblas.

**Comment by MurphyLaw** [comment]
it's okay now thanks...
