### ISSUE TITLE
Python examples compile fails when using code from git

### ISSUE THREAD

**Issue by dksr** [davisking/dlib#25]
Hi,
I cloned the current git version and when I try to compile the python examples, it fails with the following error:

[ 94%] Building CXX object CMakeFiles/dlib_.dir/src/rectangles.cpp.o
[ 95%] Building CXX object CMakeFiles/dlib_.dir/src/object_detection.cpp.o
In file included from /tmp/dlib/dlib/../dlib/image_processing/../image_processing.h:12:0,
                 from /tmp/dlib/dlib/../dlib/image_processing/scan_image_pyramid.h:9,
                 from /tmp/dlib/dlib/../dlib/image_processing/remove_unobtainable_rectangles.h:7,
                 from /tmp/dlib/tools/python/src/simple_object_detector.h:12,
                 from /tmp/dlib/tools/python/src/object_detection.cpp:9:
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:70:9: error: variable or field ‘setup_hashed_features’ declared void
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:70:9: error: ‘scan_image_pyramid’ was not declared in this scope
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:70:35: error: expected primary-expression before ‘,’ token
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
                                   ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:70:87: error: expected primary-expression before ‘>’ token
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
                                                                                       ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:70:90: error: ‘scanner’ was not declared in this scope
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
                                                                                          ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:71:9: error: expected primary-expression before ‘const’
         const image_array& images,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:72:9: error: expected primary-expression before ‘const’
         const feature_extractor& fe,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:73:9: error: expected primary-expression before ‘int’
         int bits,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:74:9: error: expected primary-expression before ‘unsigned’
         unsigned long num_samples = 200000
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:114:9: error: variable or field ‘setup_hashed_features’ declared void
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:114:9: error: ‘scan_image_pyramid’ was not declared in this scope
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:114:35: error: expected primary-expression before ‘,’ token
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
                                   ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:114:87: error: expected primary-expression before ‘>’ token
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
                                                                                       ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:114:90: error: ‘scanner’ was not declared in this scope
         scan_image_pyramid<pyramid, feature_image<feature_extractor, projection_hash> >& scanner,
                                                                                          ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:115:9: error: expected primary-expression before ‘const’
         const image_array& images,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:116:9: error: expected primary-expression before ‘int’
         int bits,
         ^
/tmp/dlib/dlib/../dlib/image_processing/../image_processing/setup_hashed_features.h:117:9: error: expected primary-expression before ‘unsigned’
         unsigned long num_samples = 200000
         ^
make[2]: *** [CMakeFiles/dlib_.dir/src/object_detection.cpp.o] Error 1
make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
make: *** [all] Error 2

- K

**Comment by davisking** [comment]
Oops.  This should be fixed now.  Thanks for pointing this out.
