### ISSUE TITLE
imglab Build Error: error C2338: Failed assertion 

### ISSUE THREAD

**Issue by MurphyLaw** [davisking/dlib#250]
Hi, so whenever I build the imglab through cmake it fails.
I tried both the latest version here in Github and the 19.1 in the website
here's the complete error It think:
"C:\Users\antho\Desktop\dlib-19.1\dlib-19.1\tools\imglab\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\antho\Desktop\dlib-19.1\dlib-19.1\tools\imglab\build\imglab.vcxproj" (default target) (4) ->
(ClCompile target) ->
  c:\users\antho\desktop\dlib-19.1\dlib-19.1\dlib\image_saver/save_png.h(64): error C2338: Failed assertion [C:\Users\antho\Desktop\dlib-19.1\dlib-19.1\tools\imglab\build\imglab.vcxproj]

thanks!!!

**Comment by davisking** [comment]
What happens if you run `cmake .` again before building?   I think there is
a bug in recent windows versions of cmake that makes it not generate
projects correctly on the first invocation.

**Comment by MurphyLaw** [comment]
yeah that did it.
thanks again...
