### ISSUE TITLE
Wrong Predictions for Coin Held in Hand

### ISSUE THREAD

**Issue by optimaltaskin** [davisking/dlib#2505]
Hi,

I have been trying to train a shape predictor which predicts a coin held in hand. For this purpose I have trained taken photos of myself holding coin in a specific manner. Drew rectangles on each photo and selected 8 parts on each image with imglab tool. A sample image is shown below:

![training](https://user-images.githubusercontent.com/85254524/153584822-5e2f8863-661b-4720-95e4-cb484cbcade0.PNG)

I have trained a couple of models with different hyperparameters. First, tried default values for all parameters. Then tried another models with different parameters. I have listed hyperparameters of 2 sample models I have trained below(to give an idea about hyperparameters I used):
Model 1:
```
options.oversampling_amount = 300
options.nu = 0.3
options.tree_depth = 8
options.cascade_depth = 15
options.feature_pool_size = 512
options.num_test_splits = 256
options.be_verbose = True
options.oversampling_translation_jitter = 0.1
```

Model 2:
```options.oversampling_amount = 500
options.nu = 0.5
options.tree_depth = 8
options.cascade_depth = 16
options.feature_pool_size = 1024
options.num_test_splits = 512
options.be_verbose = True
options.oversampling_translation_jitter = 0.1
```

However all predictors predict in a wrong way. As training set, I have 25 photos marked as shown above. As far as I read from other messages here on github, flipping images can be a good way to increase number of data. To do that I have used --flip command which as far as I understand that marks part numbers correctly. In that way I have increased my training data set to 50 images. But still the result is like below:

![wrong_prediction](https://user-images.githubusercontent.com/85254524/153585536-3418d1c2-8e64-4d9b-ba85-3c8aa5c1bd7f.PNG)

Before training my shape predictor, I have trained an object detector with same data set(I understood that it uses drawn triangles to understand which object - in that case hand- to find). Then with the same xml file which also includes parts, I have trained the shape predictor. For example model 1 mentioned above gave results below:

```
Training accuracy: 0.0
Testing accuracy: 236.3158642767593
```

I know that it's difficult to offer any perfect solution in machine learning world but I need help to solve my prediction issue. I don't understand why there is a shift in position and aspect ratio of the predicted coin. However I want to ask few questions about my issue:

1) Am I doing something wrong to mark the images? For example drawing the box too large? Or shall I increase number of parts?
2) Can the hyperparameters I chose might be causing those wrong predictions?
3) Are 50 images a low number of data to train such a predictor? 
4) I noticed that object detector's boundary box's aspect ratio is different than the ones I drew on training images. Does that cause aspect ratio issue for the predicted object?

I hope I didn't ask too many questions. I appreciate any help about that subject. Thanks in advance,

**Comment by davisking** [comment]
Sounds like there are several issues.  50 images is not very many, way too few realistically.  Also, in all things ML, you must make the training data look like the real data you will actually see when you run the model.  In this case, it means that the boxes must be the boxes that come from the box detector you are using. The fact that they aren't is why you see that aspect ratio change.  You should also almost certainly make your box detector look for the coin, rather than the hand, since the coin is the thing you are trying to locate.

**Comment by optimaltaskin** [comment]
Hi @davisking ,

Thanks for your very quick response, I really appreciate it. Moreover thanks for that great library as well. I'll look for ways to increase the number of samples in my data set in that case.

One more question about drawing boxes. In that case I'll train a detector by using train_object_detector and then use that detector to determine boxes in my training set which I'll use for the shape predictor. Than I'll create training.xml file for shape predictor by using those boxes(I'll need to write some code to import detector's boxes into xml file) and mark part numbers on that training set. Am I right?

Thanks

**Comment by optimaltaskin** [comment]
Once again thanks for your help Davis. I better get back to work :)

**Comment by optimaltaskin** [comment]
Issue solved with implementation of Davis's suggestion. Thanks Davis!
