### ISSUE TITLE
Boost.Python.ArgumentError for dlib.rectangle

### ISSUE THREAD

**Issue by sattawat61** [davisking/dlib#2516]
Hello,

I am getting this weird issue where the dlib.rectangle is working when I try it in python shell, but doesn't work when i try it in a script in the same shell.

Here is my code 
def get_faces2(self, image, get_largest=True, return_shape=False):
        res = None
        shp = None
        _, _, pts = self.detector.detect(Image.fromarray(image), landmarks=True)
        if pts is not None:
            if get_largest:
                pts = [pts[0]]

            res = np.zeros((len(pts), self.out_size, self.out_size, 3), dtype=np.uint8)
            shp = []
            for i, pt in enumerate(pts):
                face = np.array((min(pt[:, 0]), min(pt[:, 1]), max(pt[:, 0]), max(pt[:, 1])))
                w, h = face[2] - face[0], face[3] - face[1]
                ex = np.abs(h - w) / 2.
                if h > w:
                    face[[0, 2]] = face[0] - ex, face[2] + ex
                else:
                    face[[1, 3]] = face[1] - ex, face[3] + ex

                ex = max(h, w) * 0.5
                face[:] = face[0] - ex, face[1] - ex, face[2] + ex, face[3] + ex

                rec = dlib.rectangle(*face)
                shaped = self.shaper(image, rec)
                shp.append(shaped)
                aligned = dlib.get_face_chip(image, shaped, size=self.out_size)
                res[i] = aligned

        if return_shape:
            return res, shp, pts
        return res
giving me following error:
File "create_masked_face_dataset.py", line 48, in <module>
    face, shaped, _ = mtcnn.get_faces2(image, return_shape=True)
  File "D:\project\FaceNetPytoch-Mask-master\FaceDetector.py", line 116, in get_faces2
    rec = dlib.rectangle(*face)
Boost.Python.ArgumentError: Python argument types in
    rectangle.__init__(rectangle, numpy.float32, numpy.float32, numpy.float32, numpy.float32)
did not match C++ signature:
    __init__(struct _object * __ptr64, long left, long top, long right, long bottom)
    __init__(struct _object * __ptr64)
I am not sure what is wrong with it. Thanx for the help in advance.

**Comment by arrufat** [comment]
It looks to me that you might be using an old version of the library, where the python bindings were done with Boost. Can you try a newer version?
(I might be wrong, though)
