### ISSUE TITLE
Missing Threads::Threads target when using static dlib and dlibConfig*.cmake

### ISSUE THREAD

**Issue by APTX** [davisking/dlib#2522]
## Expected Behavior
No cmake error.

## Current Behavior
```
Target "my_target" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

## Steps to Reproduce
I use `dlib` in my cmake project the following way:
```
find_package(dlib CONFIG REQUIRED)
# [...]
target_link_libraries(my_target dlib::dlib)
```

As far as I understand this is a limitation of how cmake handles "transitive dependencies" (dependencies of dependencies that become direct dependencies of a target). This is usually only an issue with static linking.

When linking with a static library, the target has to link to the dependencies of that library. When `dlib` links statically with CUDA, the [`Threads::Threads` dependency is added by `FindCUDA`](https://github.com/Kitware/CMake/blob/859241d2bbaae83f06c44bc21ab0dbd38725a3fc/Modules/FindCUDA.cmake#L1047).

When `my_target` links statically with `dlib`, it has to link `dlib`'s dependencies, including the ones inherited from CUDA. `dlib`'s cmake config file only lists the `Threads::Threads` dependency but does not find it like `FindCUDA` does.

As a workaround it's possible to fix the error by adding `find_package(Threads)` as the cmake error suggests. This way `my_target` finds the `Threads::Threads` dependency for `dlib`, even if `my_target` doesn't use `Threads::Threads` directly.

This could be a duplicate of issue #2107.

* **Version**: 19.22
* **Where did you get dlib**: `emerge dlib` (distribution package manager)
* **Platform**: Gentoo linux
* **Compiler**: gcc (Gentoo 11.2.0 p1) 11.2.0
* **Cmake version**: 3.22.2

**Comment by davisking** [comment]
Gentoo isn't a platform that's officially supported (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) and my experience is that they are pretty serious about really not supporting other platforms.  I know people make it work sometimes anyway.  So this isn't surprising that there are issues.

Anyway, if there is some PR you can make that works around this I'm cool with it so long as it doesn't break or harm other dlib users in some way.

**Comment by APTX** [comment]
The problem isn't with CUDA. `FindCUDA` isn't even a part of CUDA, it's part of cmake (It's also deprecated). It's a problem with [dlib's cmake config](https://github.com/davisking/dlib/blob/54af1f85f879d0e8d1312a27befaa39fe1948aad/dlib/cmake_utils/dlibConfig.cmake.in).

The problem should be visible on unix platforms ([`FindCUDA` only adds the `Threads` dependency on unix](https://github.com/Kitware/CMake/blob/859241d2bbaae83f06c44bc21ab0dbd38725a3fc/Modules/FindCUDA.cmake#L1037)), when dlib was linked statically with CUDA (the default) and is being linked statically (also default) **and** when using the cmake config file.

The [dlib examples do **not** use the generated dlib cmake config file](https://github.com/davisking/dlib/blob/54af1f85f879d0e8d1312a27befaa39fe1948aad/examples/CMakeLists.txt#L40). Building like that would not trigger the error (when including dlib's `CMakeLists.txt` directly, `FindCUDA` will call `find_package(Threads)` and cmake will know about the target, but when dlib's cmake config is used `FindCUDA` is not used).

If a cmake project already depends on `Threads` the error would also be no error as the `Threads::Threads` target would already be known to cmake (essentially the same as the workaround, but `find_package(Threads)` isn't being called for dlib).

The solution is to make dlib config call `find_package(Threads)` when it's required. ([Stackoverflow example](https://stackoverflow.com/questions/46861504/cmake-transitive-dependency-is-not-found-via-find-package)). When cmake generates the config file it adds the required targets, but does not actually generate the `find_package` calls to find the targets.
