### ISSUE TITLE
If we find_clusters_using_kmeans() on constant data with k=2 what will happen?

### ISSUE THREAD

**Issue by andrewm4894** [davisking/dlib#2525]
I am wondering what would happen if we try to find clusters with k=2 when all feature vectors are identical. 

We use dlib in [here](https://github.com/netdata/netdata/tree/master/ml) to power some unsupervised anomaly detection and i am just trying to reason about what might be happening when we train cluster centers (we use k=2 by default) on near constant values like say an error counter that always just some constant value. Obviously then fitting a cluster model with k=2 might be a bit silly here as all the feature vectors are literally the same (or very very very close). 

I tried to read the code behind find_clusters_using_kmeans and pick_initial_centers but could not really 100% be sure (i don't know c++ well enough yet :) ) - it looked like maybe it might start with k=1 and expand to k=2 as defined by `num_centers` based on how the distances play out. So maybe if distances always closet to first center then it would just sort of end up fitting k=1. 

Apologies for the random issue like this. I was just trying to figure it out myself by reading the code (which i 'll continue to do) but just thought might as well just ask :) 

cheers!

**Comment by davisking** [comment]
If all the samples are identical then the two clusters you get back will be
identical.  But maybe I'm not understanding the question.

**Comment by andrewm4894** [comment]
Ohh k, yeah that makes sense, I didn't think about that case. Cheers. I'll try confirm this on my end to be sure but sounds like that would actually be good for how we are using it.
