### ISSUE TITLE
Generalization Problem for Object Detector 

### ISSUE THREAD

**Issue by optimaltaskin** [davisking/dlib#2530]
Hello,

I have been trying to measure distance between pupils with a precision of 2-3 mm. As a reference length, I'm using a credit card held on forehead. I have trained my object detector with a small training set. Training set consists of two different people's 35 photos. I'm populating training by applying different transformations(color space change, adding noise, changing brightness etc.). In that way I have increased training set size to 220 images. I have trained object detector with following parameters:

options.add_left_right_image_flips = True
options.C = 5
options.num_threads = 8

My object detector find credit card on people who are used among training set. Thus for those two poeple, object detector finds credit card pretty well. Those images are below:

![det1](https://user-images.githubusercontent.com/85254524/156038992-011cdd49-0479-4ff0-a7c0-464189555a8e.jpg)    ![det2](https://user-images.githubusercontent.com/85254524/156039143-27b2db2a-65a6-46f6-b593-66a57bfaec6e.jpg)

However when I try detector on people who were not present on training set, detector fail to detect properly such as below:

![failed_det1](https://user-images.githubusercontent.com/85254524/156039715-64f21500-914a-4ae2-bf92-14c1ad97a261.jpg)  ![failed_det2](https://user-images.githubusercontent.com/85254524/156039720-5e992021-dccd-494c-b7c9-220db072af2b.jpg) 
![failed_det3](https://user-images.githubusercontent.com/85254524/156039723-608c4602-5894-4017-83fc-c85384da4625.jpg)

Why detector can not detect a similar pattern in totally different images? It even didn't detect any card in the first image. Is object detector overfitting? I think because object detector can not find credit card properly, shape predictor can not determine landmarks as it should. So first I need to train object detector properly. Is populating training set to increase the number of images for object detector a bad practice? I assumed since increasing image number in that way provides better results with shape predictor, same will happen for object detector as well. 

When training set size exceeds ~220 images, training fails because of insufficient memory. So in that case how can I train a detector which can generalize better?

I know that it's difficult to determine a certain reason but any idea for improvement is very welcome. Thanks.

**Comment by davisking** [comment]
Yes, it is overfitting.  You need more data that is more diverse.  It's just that.  Like it's definitely not going to generalize to other people if there are only two people in the training dataset.
