### ISSUE TITLE
dlib.shape_predictor confidence

### ISSUE THREAD

**Issue by MrCri5py** [davisking/dlib#2534]
I am trying to use shape_predictor to set points of interest and then measure them. However, there are instances where one or more points shouldn't be shown as the location of interest is not visible, making their placement incorrect. Is there a way to set a confidence threshold to the shape_predictor? I am sure this feature would make the shape_predictor the highlight to many more projects. :)

**Comment by davisking** [comment]
There isn't a function for that.  But you can train your own additional binary classifier by taking the `feats` output of the shape predictor and training a linear SVM to tell you if the point is visible or not.

**Comment by MrCri5py** [comment]
Thank you for the feedback. I assume this is the feats output that you mentioned <_dlib_pybind11.full_object_detection object at 0x0000017B003124F0> ? Where this "0x0000017B003124F0" will be used to train the SVM? :) I got it from print(landmarks), where landmarks = predictor(img, drect). If this is incorrect, how does one get the feats?

**Comment by davisking** [comment]
No.  I mean here http://dlib.net/dlib/image_processing/shape_predictor_abstract.h.html#operator

**Comment by MrCri5py** [comment]
Again thank you for the quick feedback. I do apologize in advance and appreciate your patience. I am unsure of what function to use in your link. Do you have an example code?

**Comment by MrCri5py** [comment]
Thank you for your response. I used dlib.full_object_detection(rect, [dlib.point(int(shape_point[1]), int(shape_point[0]))]) where rect is the dlib.rectangle coordinates and shape_point is the numpy array of the predictor landmarks (i.e. predictor(img, rect)).

My resulting output is <_dlib_pybind11.full_object_detection object at 0x00000241A91225B0>
how do I get the feats out of this?
:)
