### ISSUE TITLE
"nvcc fatal" error with cmake option CUDA_SEPARABLE_COMPILATION

### ISSUE THREAD

**Issue by amwink** [davisking/dlib#2536]
I am compiling DLib on a KUbuntu 20.04 system with an RTX2070, CUDA 11.5 and CUdnn 8

Software:
g++ 9.3.0-17 (Ubuntu 20.04)
dlib: cloned from github 4/3/2022
uname -a: 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

## Expected Behavior
The option "compile CUDA objects with separate compilation enabled" requires CUDA version >= 5, so should work in this case.

## Current Behavior
With the option set to OFF, it compiles.
With the option set to ON, compilation exits with the message

```
[  1%] Building NVCC (Device) object dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cusolver_dlibapi.cu.o
[  2%] Building NVCC (Device) object dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cuda_dlib.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[  4%] Building NVCC intermediate link file dlib/CMakeFiles/dlib.dir/dlib_intermediate_link.o
nvcc fatal   : Unknown option '-gencode arch=compute_50,code=[sm_50,compute_50]'
make[2]: *** [dlib/CMakeFiles/dlib.dir/build.make:1241: dlib/CMakeFiles/dlib.dir/dlib_intermediate_link.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: dlib/CMakeFiles/dlib.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

## Steps to Reproduce
1. download dlib: git clone https://github.com/davisking/dlib.git
2. cd dlib/examples && mkdir build && cd build
3. cmake .. -DDLIB_USE_CUDA=1; ccmake ..
4. [t]oggle 'advanced', change the option named above (just hit enter)
5. [c]onfigure, [g]enerate
6. make -j6
gives the error.

Repeating 4, 5, 6 (so with the option to OFF again) results in full compilation.

According to 
   https://developer.nvidia.com/blog/separate-compilation-linking-cuda-device-code
it's better to do use separate compilation/linking so I was wondering if there is a way to enable it.

**Comment by davisking** [comment]
You will have to edit the cmake scripts to do this I expect.

**Comment by amwink** [comment]
Thanks! Does it mean that the card is too old (because of the warnings ('compute_50 is deprecated' etc) for cudnn8?

**Comment by arrufat** [comment]
> Thanks! Does it mean that the card is too old (because of the warnings ('compute_50 is deprecated' etc) for cudnn8?

No, that's a different thing, to get rid of the warning, you can define `-DDLIB_USE_CUDA_COMPUTE_CAPABILITIES=75`, which card specific. Note that you need dlib 19.23 to be able to set that.
