### ISSUE TITLE
dnn + python

### ISSUE THREAD

**Issue by thaiat** [davisking/dlib#254]
Are dnn functions exposed through python ?

**Comment by e-fominov** [comment]
No. And as Dlib does no provide dynamic network structure - it will not be possible to make python API for DNN
http://dlib.net/faq.html#Whycan'tIchangethenetworkarchitectureatruntime

**Comment by davisking** [comment]
Right.  I doubt I will add any sort of Python training API for the DNN
tooling since Python is incapable of representing the C++11 language
concepts used by the DNN API.

Although maybe I'll add a Python API for running specific trained models if
that eventually makes sense.  We will see.

**Comment by thaiat** [comment]
yep that would be awesome to run the detection on a trained model via python

**Comment by abhisheksoni27** [comment]
Any news?

**Comment by davisking** [comment]
No.  It's still impossible to expose C++ templates to python.

**Comment by sukhad-app** [comment]
hi davisking. What value of padding has to be used for training the HELEN dataset for face landmark detection ?

**Comment by davisking** [comment]
Read Kazemi's paper.  It's all in there.
