### ISSUE TITLE
[question]  What to do if some argument values are not valid?

### ISSUE THREAD

**Issue by lesshaste** [davisking/dlib#2543]
dlib version 19.23.0 on ubuntu 20.04 64 bit using dlib from python

I have an objective function that takes integer parameters but some parameters are not valid.  Is there a recommendation for what to do in this circumstance using dlib's find_min_global?  Looking at the Lipschitz optimization method it seems that just returning a very large value when calling the objective function with invalid arguments risks artificially giving a very large Lipschitz constant to the optimization method which might ruin its efficiency.

**Comment by davisking** [comment]
There is aLipschitz constant separately for each dimension.  So you just
have to do something reasonable for each dimension.  What is reasonable
will depend on the nature of your function.
