### ISSUE TITLE
please add cuda 11.3 above support

### ISSUE THREAD

**Issue by fatalfeel** [davisking/dlib#2548]
RTX 3050 need cuda 11.X above and libcudnn 8.2.1 above
the dlib not support not please add it~

**Comment by arrufat** [comment]
It's already supported: I am using dlib with CUDA 11.6.1 and cuDNN 8.3.2.44 without any issues.

**Comment by fatalfeel** [comment]
ok i will try

**Comment by arrufat** [comment]
I am doing it in C++. It works. You should really fill the issue template so that we can figure out what's going on.

**Comment by fatalfeel** [comment]
ok try now thanks a lot sir

**Comment by fatalfeel** [comment]
-- Building a cuDNN test project to check if you have the right version of cuDNN installed...
-- *****************************************************************************************************
-- *** Found cuDNN, but we failed to compile the dlib/cmake_utils/test_for_cudnn project. 
-- *** You either have an unsupported version of cuDNN or something is wrong with your cudDNN install.
-- *** Since a functional cuDNN is not found DLIB WILL NOT USE CUDA. 
-- *** The output of the failed test_for_cudnn build is: 
-- *** 
-- ***   Change Dir: /root/image_sdk/dlib/build/dlib/cudnn_test_build
   ***   
   ***   Run Build Command(s):/usr/bin/make -f Makefile && Scanning dependencies of target cudnn_test
   ***   [ 50%] Building CXX object CMakeFiles/cudnn_test.dir/cudnn_dlibapi.cpp.o
   ***   /root/image_sdk/dlib/dlib/cuda/cudnn_dlibapi.cpp: In member function ‘void dlib::cuda::tensor_conv::select_best_algorithms(const dlib::tensor&, const dlib::cuda::tensor_descriptor&, dlib::cuda::tensor_conv::allow_cache_use)’:
   ***   /root/image_sdk/dlib/dlib/cuda/cudnn_dlibapi.cpp:803:74: error: ‘allow_cache_use’ is not a class, namespace, or enumeration
   ***                if (iter != config_to_algo_cache.end() && allow_cache_use == allow_cache_use::yes)
   ***                                                                             ^
   ***   CMakeFiles/cudnn_test.dir/build.make:74: recipe for target 'CMakeFiles/cudnn_test.dir/cudnn_dlibapi.cpp.o' failed
   ***   make[2]: *** [CMakeFiles/cudnn_test.dir/cudnn_dlibapi.cpp.o] Error 1
   ***   CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/cudnn_test.dir/all' failed
   ***   make[1]: *** [CMakeFiles/cudnn_test.dir/all] Error 2
   ***   Makefile:90: recipe for target 'all' failed
   ***   make: *** [all] Error 2
   ***   
   ***   
-- *****************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA

**Comment by arrufat** [comment]
Please fill the issue template, so I don't have to ask questions you should have already answered, such as compiler and compiler version that you're using.

**Comment by fatalfeel** [comment]
successful

if (iter != config_to_algo_cache.end() && allow_cache_use == allow_cache_use::yes)
~change to
if (iter != config_to_algo_cache.end() && allow_cache_use == tensor_conv::allow_cache_use::yes)

build ok~~~

**Comment by fatalfeel** [comment]
issue template:
Author: Øystein Myrmo <oystein.myrmo@gmail.com>  2022-03-22 21:32:14
Committer: Davis E. King <davis685@gmail.com>  2022-03-23 20:44:27
sha1: 5cb036564c986fcc45eb16dd0174b1602ceb4f7f

gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

root@unitedlinux:~# uname -r
4.15.0-142-generic

cuda_11.6.1_510.47.03_linux.run

###cudnn-local-repo-ubuntu1804-8.3.2.44_1.0-1_amd64.deb###
dpkg -x ./cudnn-local-repo-ubuntu1804-8.3.2.44_1.0-1_amd64.deb ./
cd ./var/cudnn-local-repo-ubuntu1804-8.3.2.44
gdebi libcudnn8_8.3.2.44-1+cuda11.5_amd64.deb
gdebi libcudnn8-dev_8.3.2.44-1+cuda11.5_amd64.deb
gdebi libcudnn8-samples_8.3.2.44-1+cuda11.5_amd64.deb

**Comment by arrufat** [comment]
I haven't tried building CUDA programs with GCC 5.4.0, might be the issue...

**Comment by fatalfeel** [comment]
> I haven't tried building CUDA programs with GCC 5.4.0, might be the issue...

could I request a feature to Svm trainer, we set pca object class to SVM, just like scanner can do hog
