### ISSUE TITLE
Does dlib support face 128D space Euclidean distance for c++ function 

### ISSUE THREAD

**Issue by fatalfeel** [davisking/dlib#2556]
Therefore, you can perform face recognition by mapping faces to
the 128D space and then checking if their Euclidean distance is small
enough. 

in python is linalg.norm 
in opencv https://answers.opencv.org/question/14188/calc-eucliadian-distance-between-two-single-point/
what is  Euclidean distance c++ function in dlib

**Comment by arrufat** [comment]
http://dlib.net/dlib/matrix/matrix_utilities_abstract.h.html#length

**Comment by fatalfeel** [comment]
arrufat, thank you sir~~

**Comment by arrufat** [comment]
It looks like. You should read these:
- http://dlib.net/dnn_metric_learning_ex.cpp.html
- http://dlib.net/dnn_metric_learning_on_images_ex.cpp.html
- http://dlib.net/dnn_face_recognition_ex.cpp.html

**Comment by fatalfeel** [comment]
good good good ~~~many thanks~~~~~
