### ISSUE TITLE
get_face_chips of face_alignment.py and get_face_chip_details of dlib_dnn_face_recognition.cpp the same function

### ISSUE THREAD

**Issue by fatalfeel** [davisking/dlib#2558]
images = dlib.get_face_chips(img, faces, size=320) in py
extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip); in c++

I want to do aligned face images in c++
Are dlib.get_face_chips and get_face_chip_details the same function?

**Comment by fatalfeel** [comment]
ok i try both, they are the same function, both can do face align

**Comment by rajhlinux** [comment]
Thanks I also had the same question, would like to do the face alignment in C++.

which one did you use for c++?

was it `get_face_chip_details`?

Thanks.
