### ISSUE TITLE
Running facial Landmark detector

### ISSUE THREAD

**Issue by sarmadm** [davisking/dlib#256]
I have installed Dlib on Ubuntu , Now I want to run facial landmark detector using web cam but I don't know how this should be done , Do I need to install opencv ?
what is the compilation process ?

Thanks

**Comment by e-fominov** [comment]
This is not a bug of dlib. Please ask your question on stackoverflow or sourceforge
You need to use webcam_face_pose_ex example in dlib/examples folder
Yes, you need OpenCV
