### ISSUE TITLE
Dlib 19.23 + CUDA not work, Dlib 19.22 + CUDA yes.

### ISSUE THREAD

**Issue by sergiogut1805** [davisking/dlib#2569]
Hi Davis, 

I am trying to compile Dlib 19.23 + CUDA but not work, instead Dlib 19.22 + CUDA yes.

Enviroment:
**Windows 10 21H2
Visual studio 2019 v16.11.12
Visual studio 2022 v17.1.4 
CUDA 10.1 update 2 + CUDNN 7.6 
CUDA 11.5 + CUDNN 8.4
Nvidia GTX 1080ti 11GB
Nvidia 512.15 latest Drivers**

CMAKE proccess is OK, never fails, "CUDA activated ok" but when you compile any visual studio dnn project cuda fails in the run(the compilation is ok).

**Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
The C compiler identification is MSVC 19.29.30142.1
The CXX compiler identification is MSVC 19.29.30142.1
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Using CMake version: 3.23.1
Compiling dlib version: 19.23.0
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of void*
Check size of void* - done
Enabling SSE2 instructions
Searching for BLAS and LAPACK
Searching for BLAS and LAPACK
FOUND libiomp5md.dll: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/compiler/libiomp5md.dll
Found Intel MKL BLAS/LAPACK library
Looking for cblas_ddot
Looking for cblas_ddot - found
Looking for sgesv
Looking for sgesv - found
Looking for sgesv_
Looking for sgesv_ - found
Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found suitable version "10.1", minimum required is "7.5") 
Looking for cuDNN install...
Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudnn.lib
Building a CUDA test project to see if your compiler is compatible with CUDA...
Building a cuDNN test project to check if you have the right version of cuDNN installed...
Enabling CUDA support for dlib.  DLIB WILL USE CUDA, compute capabilities: 50
C++11 activated.
OpenCV not found, so we won't build the webcam_face_pose_ex example.
Configuring done**

**I run any DNN project and CUDA fails, but the other projects works ok.** 

CUDA 10.1 update 2 + CUDNN 7.6:
![image](https://user-images.githubusercontent.com/36478245/163722266-b8ad779b-720b-45c4-999c-56d99ca29a3b.png)

CUDA 11.5 + CUDNN 8.4
![image](https://user-images.githubusercontent.com/36478245/163722276-0317d2e4-edac-40f3-8200-55c8b22d74c4.png)

**Dlib 19.22 + CUDA works ok** with the same configuration.

Can you check this please? because with DLIB 19.23 is imposible execute deep learning projects or test the new features.

thanks.

**Comment by Andrew653** [comment]
I have the same situation, the same configuration but with 1080 video card (non ti).

I try also with rtx 2070 card and get the same message with cuda 10 "Cudnn status not supported" and with cuda 11.6 "fail to load cudnn_cnn_infer64_8.dll" obviously Cudnn is installed and cmake has activated cuda on dlib.

some advance for run DLIB 19.23 with cuda without these errors?

i want test and run yolo example.

best regards.

**Comment by sergiogut1805** [comment]
Hi, @davisking sorry for disturb, have you had time for check this error?

Any solution for run dlib 19.23 on windows + CUDA correctly?

thanks.

**Comment by davisking** [comment]
It's just that you haven't installed cudnn correctly somehow.  Uninstall it and reinstall it.  Note that the error is saying windows can't find the cudnn dll.  Maybe you have put it in the wrong folder or it's not in your PATH or something.  It's not something I or dlib can fix.  The basic problem is that the cudnn dll isn't in your PATH though, that's what needs to be corrected.

**Comment by reunanen** [comment]
When you installed cudnn 8, did you download the zlib dll as well, and put it to some location where it can be found?

If not, then you may be getting an error message like that. Yes, it's a misleading error message, but that's a cudnn issue and not a dlib one.

See: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows

**Comment by VisionEp1** [comment]
This Reply from reunaen should be pinned somewhere, to prevent this issue coming up 100 times in the next weeks.
I also had this issue some weeks ago especially since the error message is hard misleading, i thought it was about some dlib incompatibility first etc... it took a while to figure it out  

btw how can NVIDIA change an installation process which was the exact same for many years without at least a hint or anything in the installer, you actually have to randomly find the line in the install guide. Who reads an install guide when the process doesn't change for years

**Comment by davisking** [comment]
Yeah NVIDIA packing and install on windows has never been great either :|

**Comment by sergiogut1805** [comment]
> When you installed cudnn 8, did you download the zlib dll as well, and put it to some location where it can be found?
> 
> If not, then you may be getting an error message like that. Yes, it's a misleading error message, but that's a cudnn issue and not a dlib one.
> 
> See: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows

CUDA 10.1 or superior + CUDNN 7 definitely **not work** with Dlib 19.23 or 19.24!
CUDA 10.1 or superior + CUDNN 8 works ok.

Apparently Cudnn 7 is out of support :/

Note: NOT all Cudnn 8 versions need the zlib dll, only the 8.4 version.
