### ISSUE TITLE
Unable to run `./imglab --cluster`.

### ISSUE THREAD

**Issue by mrgloom** [davisking/dlib#257]
Unable to run `./imglab --cluster 8 ../data/OutputDir/training.xml`
`ERROR: unable to open ../data/OutputDir/training.xml for reading.`

but path to `training.xml` is valid, I can run for example 
`./imglab --stats ../data/OutputDir/training.xml`

Update:
`./imglab --cluster 8 training.xml` works, if I place `training.xml` in the same folder near `imglab`, also it work if I use full path to `training.xml`, so for some reason relative path is not working.

**Comment by davisking** [comment]
Yeah, that's a problem.  I just pushed the fix to github.  Thanks for finding this :)
