### ISSUE TITLE
Consider avoid use of non-standard cmake find methods

### ISSUE THREAD

**Issue by aborzunov** [davisking/dlib#2581]
## Expected Behavior
Cmake scripts should use only `find_package`. Provide dedicated cmake option to compile with vendored dependency.

## Current Behavior
Non-standard `find_libpng` fails and [silently build](https://github.com/davisking/dlib/blob/master/dlib/CMakeLists.txt#L442-L449) `libpng` with vendored zlib with wrong version, notwithstanding the fact, that we provided `libpng` 1.6.37 compiled with zlib  1.2.12 and compatible `zlib` 1.2.12.

## Steps to Reproduce
Conan CI with [recipe](https://conan.io/center/dlib?tab=configuration) in [PR](https://github.com/conan-io/conan-center-index/pull/10536)

[Build log](https://c3i.jfrog.io/c3i/misc/logs/pr/10536/2-configs/macos-m1-clang/dlib/19.23//8f726db3d08522ec5da20c4e1ba50bc234e38083-build.txt) 

* **19.23**: 
* **Github Release page**: [19.23](https://github.com/davisking/dlib/archive/refs/tags/v19.23.tar.gz) 
* **macOS, Clang (M1/arm64)**: 
* **Clang: 13.0/12.0**:

**Comment by davisking** [comment]
I'm not sure what you mean.  dlib's cmake script uses `find_package(PNG QUIET)` to find libpng.  Only if that fails does the fallback happen.

**Comment by aborzunov** [comment]
Actually, it uses `include(cmake_utils/find_libpng.cmake)` to find libpng [here](https://github.com/davisking/dlib/blob/master/dlib/CMakeLists.txt#L442-L449):

```cmake
if (DLIB_PNG_SUPPORT)
         include(cmake_utils/find_libpng.cmake)
         if (PNG_FOUND)
            include_directories(${PNG_INCLUDE_DIR})
            set (dlib_needed_libraries ${dlib_needed_libraries} ${PNG_LIBRARIES})
         else()
            # If we can't find libpng then statically compile it in.
            include_directories(external/libpng external/zlib)
            set(source_files ${source_files}
```

Apparently, it works on default combination of OS/compiler/... but fails on non-default, whereas package manager provide dependencies that can be found using `FindLibpng.cmake` script in build directory using CMake `find_package` method.

**Comment by arrufat** [comment]
I also don't get what you mean: `include(cmake_utils/find_libpng.cmake)` uses the “standard” `find_package(PNG QUIET)`

**Comment by aborzunov** [comment]
Sorry, my fault. Didn't examine `cmake_utils/find_libpng.cmake`. Indeed, issue is senseless in this wording.

Thanks.
