### ISSUE TITLE
Does Dlib support Bayesian network structure learning and parameter learning?

### ISSUE THREAD

**Issue by cowboylym** [davisking/dlib#2589]
Does Dlib support Bayesian network structure learning and parameter learning?

**Comment by davisking** [comment]
Nope.

**Comment by cowboylym** [comment]
> Nope.

Thanks for the reply, is there any C/C++ library that supports Bayesian network structure learning and parameter learning?

**Comment by davisking** [comment]
Not sure.  I’ve never had need to specifically do that.

**Comment by cowboylym** [comment]
> 

Thank you anyway！
