### ISSUE TITLE
Unable to convert dat to caffe

### ISSUE THREAD

**Issue by brlcad** [davisking/dlib#2592]
Hi, I'm attempting to convert one of the sample vehicle detection models to caffe and am running into an issue.

## Expected Behavior

I was expecting to run the dtoc program on mmod_front_and_rear_end_vehicle_detector.xml (generated by calling dlib::net_to_xml(net, "mmod_front_and_rear_end_vehicle_detector.xml")) and get a Caffe conversion.

## Current Behavior

Instead, I get the following error:
  
```
~/src/dlib/tools/convert_dlib_nets_to_caffe/.build/dtoc mmod_front_and_rear_end_vehicle_detector.xml 1 1 928 478
Writing python part of model to mmod_front_and_rear_end_vehicle_detector_dlib_to_caffe_model.py
Writing weights part of model to mmod_front_and_rear_end_vehicle_detector_dlib_to_caffe_model.weights


*************** ERROR CONVERTING TO CAFFE ***************
string cast error: invalid string = 'true'

```

## Steps to Reproduce

Steps shown above.  I simply compiled dtoc, called net_to_xml(), ran dtoc on resulting xml, and got an erro (no ou 

* **Version**: 

19.24.99

* **Where did you get dlib**: 
github repo

* **Platform**: 
Mac

* **Compiler**: 
Apple clang version 13.0.0 (clang-1300.0.29.30)

**Comment by davisking** [comment]
That model isn't convertible to something caffe could understand.

**Comment by brlcad** [comment]
I'm not sure I understand the terse response.  The model clearly didn't convert (i.e., isn't convertible).  Is the input simply unsupported presently or is it outright an invalid input that cannot possibly convert?

**Comment by arrufat** [comment]
In my humble opinion, there are two key aspects unique to dlib in that network:
- the input layer: [input_rgb_image_pyramid](http://dlib.net/ml.html#input_rgb_image_pyramid)
  - this layer creates a tiled pyramid of the input image which, as far as I know, it's not supported anywhere else
- the loss layer: [loss_mmod](http://dlib.net/ml.html#loss_mmod_)
  - this loss layer is also unique to dlib, no equivalent in other machine learning frameworks exists.

As for the rest of the network, it's just a bunch of the standard convolution + batch norm + relu blocks, so nothing special there.

Therefore, unless you write those layers on caffe, there's no way that network would work.
I'd suggest you read about [this blog post](http://blog.dlib.net/2017/08/vehicle-detection-with-dlib-195_27.html), which explains it in more detail.

**Comment by brlcad** [comment]
Thank you for the responses.  The gist I'm understanding is that the dtoc tool cannot support any dlib network via xml, but only certain ones.  Thus the syntax error in my report is really an indication that should have simply reported back as "unsupported" or even "unsupportable" (though I don't know if that's strictly true).  Thanks for the responses received.
