### ISSUE TITLE
Can't compile or install dlib

### ISSUE THREAD

**Issue by VenRoot** [davisking/dlib#2593]
Trying to compile dlib or install it from pip with pip install dlib results in an error. I tried for weeks and now finally giving up and directly creating an issue. Thank you in advance

## Expected Behavior
It should compile and build, or should install via pip3

## Current Behavior
Either compiling or building results in errors.
This is the output when trying to compile it: https://pastebin.com/Yf9BXX6u
And this is the output when trying to install it via pip3 [log.log](https://github.com/davisking/dlib/files/8809225/log.log) <-- too big for pastebin

## Steps to Reproduce
a) From Github Source
1. Clone the github repo
2. Make a build folder
3. Prepare the files in the build folder
4. Try to build -> it will fail

b) pip
1. pip install dlib
2. It fails

* **Version**: 19.24
* **Where did you get dlib**: This github repo and pip3 sources
* **Platform**: 
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
Linux pop-os 5.17.5-76051705-generic
* **Compiler**: 
cmake 3.22.1
gcc 11.2.0

**Comment by davisking** [comment]
Those errors aren't from dlib, but the copy of the C++ standard library installed on your computer.  Something is apparently wrong with it.

**Comment by VenRoot** [comment]
Oh thank you, you know a simple way to "restore" these files? Couldn't find much on google

**Comment by VenRoot** [comment]
I got it. /usr/include/cpp/11 was corrupted and I replaced it from another linux installation
