### ISSUE TITLE
[HELP] How to invert the process after alignment?

### ISSUE THREAD

**Issue by Mayorc1978** [davisking/dlib#2595]
How do I Invert the alignment after performing edits on the chipped (aligned) images?

From the code the process looks like this:
```
faces = dlib.full_object_detections()
for detection in dets:
    faces.append(sp(img, detection))
images = dlib.get_face_chips(img, faces, size=320)
```
Any API call to **get the transform**, save it in a variable, then revert the alignment? Or a direct call with the chipped image and the cropped image as parameters to get the transform, or a call to embed and render the edited chipped image back on the original uncropped image?

**Comment by davisking** [comment]
There is tooling in dlib to do that.  It's not exposed to python though.  E.g. `dlib::get_mapping_to_chip()`

**Comment by Mayorc1978** [comment]
> There is tooling in dlib to do that. It's not exposed to python though. E.g. `dlib::get_mapping_to_chip()`

How do I make a wrapper for that method in Python?

**Comment by davisking** [comment]
The python bindings are over in the tools/python/src folder and use pybind11.
