### ISSUE TITLE
Object Recogniton

### ISSUE THREAD

**Issue by aishaandatt** [davisking/dlib#2598]
## Expected Behavior

I'm Trying to implement Object Recognition , for that I made 3 files Object Detector SVM file, Object Landmark Generation File and then Object Embeddings Generation Resnet File. The first two files are working perfectly but the third file should generate the 128 embeddings just like the pre trained face resnet file.

## Current Behavior

When I try to input the image into the recognition file, an error comes ERROR: Unexpected version found while deserializing dlib::input_rgb_image_sized. I've tried all the solutions online but nothing seems to be working for my dataset. 

## Steps to Reproduce

The files that I have used to generate the files are
1. Object Detecton - train_object_detector.cpp
2. Landmark Generation (10 point) - train_shape_predictor // I made custom landmark XML files using 10 Points and getting good accuracy
3. Embeddings Generation ResNet File - dnn_metric_learning_learning_on_images_ex.cpp

In the third file I got the the error which I have mentioned above.

* **Version**:  Dlib Versoin 19.24.99
* **Where did you get dlib**:  Github
* **Platform**:  MacOS
* **Compiler**:  GCC compiler

**Comment by DarsithSPillai** [comment]
> ## Expected Behavior
> I'm Trying to implement Object Recognition , for that I made 3 files Object Detector SVM file, Object Landmark Generation File and then Object Embeddings Generation Resnet File. The first two files are working perfectly but the third file should generate the 128 embeddings just like the pre trained face resnet file.
> 
> ## Current Behavior
> When I try to input the image into the recognition file, an error comes ERROR: Unexpected version found while deserializing dlib::input_rgb_image_sized. I've tried all the solutions online but nothing seems to be working for my dataset.
> 
> ## Steps to Reproduce
> The files that I have used to generate the files are
> 
> 1. Object Detecton - train_object_detector.cpp
> 2. Landmark Generation (10 point) - train_shape_predictor // I made custom landmark XML files using 10 Points and getting good accuracy
> 3. Embeddings Generation ResNet File - dnn_metric_learning_learning_on_images_ex.cpp
> 
> In the third file I got the the error which I have mentioned above.
> 
> * **Version**:  Dlib Versoin 19.24.99
> * **Where did you get dlib**:  Github
> * **Platform**:  MacOS
> * **Compiler**:  GCC compiler

Have you resolved the issue?
