### ISSUE TITLE
hierarchical clustering?

### ISSUE THREAD

**Issue by andrewm4894** [davisking/dlib#2599]
I'm wondering if there is any hierarchical clustering in dlib or something like dbscan so I don't have to define anything like K in advance. 

I'm reading up on Chinese Whispers to see if I could use that but I have just tabular data so unsure if there is some trick or way I can convert it into some graph data representation.

I'm looking to start investigating if/how we could build a Clustered Heatmap (https://github.com/andrewm4894/netdata-ml-app) into our monitoring agent and so trying to see what clustering algos from dlib we might be able to use.

Going to keep exploring the docs but also just thought may as well ask here too.

Many thanks!

**Comment by davisking** [comment]
Not much clustering stuff in dlib.  The best ones are the graph clustering
methods.  But yeah, you need to be able to make some kind of sensible graph
of your data for those to make sense.
