### ISSUE TITLE
find_candidate_object_proposal of python and c++ output different

### ISSUE THREAD

**Issue by OutOfMemory14** [davisking/dlib#26]
I try to use the find_candidate_object_proposal, but I found it seems output different number of proposals of find_candidate_object_proposal.py and find_candidate_object_proposal function. python's version output 996 proposals, but the other one output 18776 proposals. Please help me!

**Comment by davisking** [comment]
Are you calling them with the same arguments?

**Comment by OutOfMemory14** [comment]
Yes, they are the same, I use default parameter， find_candidate_object_locations (in_img_, rects, linspace(50, 200, 3)，min_size = 20, max_merging_iterations = 50 ).  I see in python it reads image using skimage, and in c++ it uses libjpeg, does it make difference ?

**Comment by OutOfMemory14** [comment]
@davisking sorry, I make a mistake, my min_size is 200.
