### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by MarwanIbrahim195** [davisking/dlib#260]
Hello,

i'm facing a strange error and i don't know its reason
i'm using this code:

```
`import sys
import dlib
from skimage import io

# Take the image file name from the command line
file_name = sys.argv[1]

# Create a HOG face detector using the built-in dlib class
face_detector = dlib.get_frontal_face_detector()

win = dlib.image_window()

# Load the image into an array
image = io.imread(file_name)

# Run the HOG face detector on the image data.
# The result will be the bounding boxes of the faces in our image.
detected_faces = face_detector(image, 1)

print("I found {} faces in the file {}".format(len(detected_faces), file_name))

# Open a window on the desktop showing the image
win.set_image(image)

# Loop through each face we found in the image
for i, face_rect in enumerate(detected_faces):

	# Detected faces are returned as an object with the coordinates 
	# of the top, left, right and bottom edges
	print("- Face #{} found at Left: {} Top: {} Right: {} Bottom: {}".format(i, face_rect.left(), face_rect.top(), face_rect.right(), face_rect.bottom()))

	# Draw a box around each face we found
	win.add_overlay(face_rect)
	        
# Wait until the user hits <enter> to close the window	        
dlib.hit_enter_to_continue()`
```

and when running it, 

> "illegal instruction (core dumped)"

 this error appears,
so i decided to run the code line by line using Python command, and it appears to show this error in this line: 
`win = dlib.image_window()
`
and when i deleted this line, the same error appears in this line: 

`detected_faces = face_detector(image, 1)
`

so what's wrong?

i also tried using **Docker** and followed this link: https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78#.giggisuvt 

and stuck at another error:

> Can't initialize X11 resources

and i don't know how to fix it

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework
