### ISSUE TITLE
Does Dlib support virtual/soft evidence?

### ISSUE THREAD

**Issue by cowboylym** [davisking/dlib#2601]
Does Dlib support soft evidence-based Bayesian network inference?
Like [pgmpy](https://pgmpy.org/models/bayesiannetwork.html) 
![image](https://user-images.githubusercontent.com/7411688/173389142-6837b9ad-d341-4942-bb63-aa15d9f61899.png)

**Comment by davisking** [comment]
You can only set actual observed values in dlib.  But you can certainly make your node conditional on some other node (let's call it a virtual node) and adjust the CDF dynamically to do this kind of soft evidence stuff.  Right, like set the virtual node to be always observed to have a value of 0 (or any other arbitrary value) and then tweak the CDF of the node you are interested in.

**Comment by cowboylym** [comment]
> 

Thanks for your reply I will try.
