### ISSUE TITLE
Failure to train DNN on multiple GPUs

### ISSUE THREAD

**Issue by iivanich** [davisking/dlib#2603]
## Expected Behavior
I am using the dnn_metlric_learning_on_images_ex.cpp to train the face recognition network on a big set of face images. I succesfully trained and used the network on a single GPU. Now I am trying to run the same code on the same dataset but on 8 GPUs. 

## Current Behavior
To use more GPUs, I modified the initialisation of the trainer and increased the thread workers to 20. Then, with 8 GPUs the program crashes:
 ************************** FATAL ERROR DETECTED **************************
 ************************** FATAL ERROR DETECTED **************************
 ************************** FATAL ERROR DETECTED **************************

Two fatal errors have been detected, the first was inappropriately ignored.
To prevent further fatal errors from being ignored this application will be
terminated immediately and you should go fix this buggy program.

The error message from this fatal error was:

Error detected at line 2125.
Error detected in file /data/vii/dlib-19.24/dlib/../dlib/dnn/loss.h.
Error detected in function double dlib::loss_metric_::compute_loss_value_and_gradient(const dlib::tensor&, const_label_iterator, SUBNET&) const [with const_label_iterator = __gnu_cxx::__normal_iterator<long unsigned int*, std::vector<long unsigned int> >; SUBNET = dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::fc_<128, (dlib::fc_bias_mode)1>, dlib::add_layer<dlib::avg_pool_<0, 0, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag2>, dlib::add_layer<dlib::avg_pool_<2, 2, 2, 2, 0, 0>, dlib::add_skip_layer<dlib::tag1, dlib::add_tag_layer<2, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 2, 2, 0, 0>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag2>, dlib::add_layer<dlib::avg_pool_<2, 2, 2, 2, 0, 0>, dlib::add_skip_layer<dlib::tag1, dlib::add_tag_layer<2, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<256, 3, 3, 2, 2, 0, 0>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<128, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<128, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<128, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<128, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag2>, dlib::add_layer<dlib::avg_pool_<2, 2, 2, 2, 0, 0>, dlib::add_skip_layer<dlib::tag1, dlib::add_tag_layer<2, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<128, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<128, 3, 3, 2, 2, 0, 0>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag2>, dlib::add_layer<dlib::avg_pool_<2, 2,
2, 2, 0, 0>, dlib::add_skip_layer<dlib::tag1, dlib::add_tag_layer<2, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<64, 3, 3, 2, 2, 0, 0>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 3, 3, 1, 1,
1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::add_prev_<dlib::tag1>, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 3, 3, 1, 1, 1, 1>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 3, 3, 1, 1, 1, 1>, dlib::add_tag_layer<1, dlib::add_layer<dlib::max_pool_<3, 3, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::bn_<(dlib::layer_mode)0>, dlib::add_layer<dlib::con_<32, 7, 7, 2, 2, 0, 0>, dlib::input_rgb_image_sized<150>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void> >, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void> >, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void> >, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void> >, void>, void>, void>, void>, void>, true, void>].

Failing expression was num_neg_samps>=1.
Make sure each mini-batch contains both positive pairs and negative pairs

With 2 GPUs the program does not crash, but can not load both GPUs at 100%. It loads them at 75% instead.

## Steps to Reproduce
1. take the dnn_metric_learning_on_images_ex.cpp and a (relatively) big dataset of faces. 
2. modify the code: init trainer to use 8 GPUs, increase number of working threads to 20, increase the learning threshold from 300 to 30000
3. run dnn_metric_learning_on_images_ex on a machine with 8 cuda GPUs

* **Version**:
dlib-19.24
* **Where did you get dlib**: 
dlib.net
* **Platform**: 
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

* **Compiler**: 
g++ (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.

**Comment by arrufat** [comment]
It looks like the error message already tells you what's wrong:
> Failing expression was num_neg_samps>=1.
> Make sure each mini-batch contains both positive pairs and negative pairs

So, when you use more GPUs the batch will be divided evenly across them, so you need to build it in a way that each 1/8 of the batch size contains both positive and negative samples.

**Comment by iivanich** [comment]
Ok, I will fix up the positive/negative samples. What about the GPU load? How to load all GPUs at 100%?
