### ISSUE TITLE
Buffer read interface for load_image

### ISSUE THREAD

**Issue by jason-richards** [davisking/dlib#2605]
In order for dlib to decode images; it is necessary to write the image to disk before passing it to dlib - or manipulate the image data as an OpenCV matrix.  This is a request to add buffer read interface to load_image.  Maybe support std::istream?

**Comment by arrufat** [comment]
Hi, `load_jpeg` and `load_png` support loading from a buffer.

**Comment by jason-richards** [comment]
Thank you!  This was not easy to find; and wasn't present in the version of
the library I am using.  This forces the user of the library to replicate
code thats already in the dlib image loader.
