### ISSUE TITLE
Dlib installation takes too much time

### ISSUE THREAD

**Issue by chinembedded** [davisking/dlib#2610]
Hi, 

Thanks for the great repository!  
I tried to install `dlib` in docker container using `pip install dlib`. It takes around 10-15 minutes to install the package. I was wondering if there are any specific steps to install `dlib` faster.

**Comment by davisking** [comment]
Nope, that's the way it is.  It is just a single shared library that's being build though so if you wanted to build it and manually copy the files to the right places you could do that too.  That's on you though :)
