### ISSUE TITLE
undefined reference to 'png_init_filter_functions_neon' when build with arm neon

### ISSUE THREAD

**Issue by miscellanea** [davisking/dlib#262]
Hi,
I'm trying to build dlib with https://github.com/taka-no-me/android-cmake
It's very simple.
cmake -DCMAKE_TOOLCHAIN_FILE=~/android-cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a with NEON" -DANDROID_NATIVE_API_LEVEL=android-9 ..
make

However, it raise the error as below
CMakeFiles/dlib_shared.dir/external/libpng/pngrutil.c.o:pngrutil.c:function png_read_filter_row: error: undefined reference to 'png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
make[2]: *** [dlib/libdlib.so] Error 1
make[1]: *** [dlib/CMakeFiles/dlib_shared.dir/all] Error 2

As a simple check, I can not find arm directories in dlib/external/libpng which is supposed to contain the neon function, however, it does have arm directories in http://libpng.sourceforge.net/.

Can we add arm directories to dlib's libpng? There are only several files, should not be a big deal.

BTW: build dlib without NEON on arm is ok with android-cmake
cmake -DCMAKE_TOOLCHAIN_FILE=~/android-cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_NATIVE_API_LEVEL=android-9 ..
make

Thanks.

**Comment by davisking** [comment]
Sure, if you want to submit a pull request for this that would be super.

**Comment by miscellanea** [comment]
Thanks, sure, will do that this weekend.
