### ISSUE TITLE
How to train objects to detect the shape of an electronic chip？

### ISSUE THREAD

**Issue by w136111526** [davisking/dlib#2620]
Hello: I would like to use dlib training to detect this shape object 100 * 100 size target image, search the large image is 2448 * 2048 size, is there a similar example?

**Comment by w136111526** [comment]
![template](https://user-images.githubusercontent.com/29495143/177166312-3efc821f-a4f4-433f-a82e-61529102af99.jpg)

**Comment by arrufat** [comment]
It seems like it could be achieved with something like this: http://dlib.net/imaging.html#object_detector

Example programs:
- [C++](http://dlib.net/train_object_detector.cpp.html)
- [Python](http://dlib.net/train_object_detector.py.html)

**Comment by davisking** [comment]
Yeah that HOG detector should work super well for this.

**Comment by w136111526** [comment]
Thank you, I refer to the example object_detector_advanced_ex.cpp achieve the same effect？

**Comment by davisking** [comment]
> Thank you, I refer to the example object_detector_advanced_ex.cpp achieve the same effect？

I mean, you can, but like the advanced example says at the top, you have to be familiar with http://dlib.net/train_object_detector.cpp.html first before it will make any sense to you.  And for what you want you really do just want the HOG one.
