### ISSUE TITLE
 want to contribute to creating a pipeline that converts Dlib deeplearning models to ONNX standard format.

### ISSUE THREAD

**Issue by intellizd** [davisking/dlib#2625]
Dlib machine learning platform is powerful and great. And thank you for allowing us to use these powerful platforms.
As you know, these days, deep learning frameworks are standardized and changing with ONNX format.
We want to contribute to creating a pipeline that converts Dlib deeplearning models to ONNX standard format.
Please give us a lot of advice.

**Comment by davisking** [comment]
Cool.  Yeah just do what tools/convert_dlib_nets_to_caffe does.  I.e. parse the output of `dlib::net_to_xml()` and resave it in whatever format you want.

**Comment by davisking** [comment]
Oh yeah, or use a visitor.  It depends on how you want to setup the software.  I've found that people who ask this question often don't want to do the whole visitor thing.  Buy yeah, if I was doing it I definitely would not have an XML middle man.  So :shrug:

**Comment by arrufat** [comment]
But visitors are fun, all that SFINAE feels almost like pattern matching in functional languages, haha!

**Comment by davisking** [comment]
Yeah I like the visitor
