### ISSUE TITLE
If I install the GPU version of dlib on nano, will the processing speed be faster?

### ISSUE THREAD

**Issue by Glory-Peng** [davisking/dlib#2629]
If I install the GPU version of dlib on nano, will the processing speed be faster?

**Comment by Nitin286roxs** [comment]
> If I install the GPU version of dlib on nano, will the processing speed be faster?

Yes, I have build dlib it for Nano, Now facial recognition take 25 msec which Is pretty fast. 
I am trying same dlib build for amd64 GPU, I have build but its not utilizing GPU.
