### ISSUE TITLE
cant  install

### ISSUE THREAD

**Issue by TAMILVIP007** [davisking/dlib#2652]
running install
C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating tools\python\dlib.egg-info
writing tools/python\dlib.egg-info\PKG-INFO
writing dependency_links to tools/python\dlib.egg-info\dependency_links.txt
writing top-level names to tools/python\dlib.egg-info\top_level.txt
writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
reading manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools\python\build*'
no previously-included directories found matching 'dlib\cmake_utils\*\build*'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
adding license file 'LICENSE'
adding license file 'LICENSE.txt'
writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(cmake_version) < '3.1.0':
Building extension for Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\build\lib.win-amd64-cpython-310 -DPYTHON_EXECUTABLE=C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\build\lib.win-amd64-cpython-310 -A x64'
CMake Error at CMakeLists.txt:5 (message):
  

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  You must use Visual Studio to build a python extension on windows.  If you
  are getting this error it means you have not installed Visual C++.  Note
  that there are many flavors of Visual Studio, like Visual Studio for C#
  development.  You need to install Visual Studio for C++.

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

-- Configuring incomplete, errors occurred!
See also "C:/Users/indrajeeth/AppData/Local/Programs/Python/Python310/Lib/site-packages/build/temp.win-amd64-cpython-310/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setup.py", line 222, in <module>
    setup(
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup   
    return run_commands(dist)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\dist.py", line 1217, in run_command       
    super().run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\install.py", line 74, in run      
    self.do_egg_install()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\dist.py", line 1217, in run_command       
    super().run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\command\install_lib.py", line 11, in run  
    self.build()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\dist.py", line 1217, in run_command       
    super().run_command(command)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
    cmd_obj.run()
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setup.py", line 134, in run
    self.build_extension(ext)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\Lib\site-packages\setup.py", line 171, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "C:\Users\indrajeeth\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\indrajeeth\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\indrajeeth\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\build\\lib.win-amd64-cpython-310', '-DPYTHON_EXECUTABLE=C:\\Users\\indrajeeth\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\indrajeeth\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\build\\lib.win-amd64-cpython-310', '-A', 'x64']' returned non-zero exit status 1.

i tried to install it in my windows but givin this error
os - windowns 10
py version 3.10
vs studio code is installed but still gettin this error

**Comment by TanimSk** [comment]
Do you have Cmake installed?
https://cmake.org/download/
make sure to add it into PATH

**Comment by TAMILVIP007** [comment]
> Do you have Cmake installed? https://cmake.org/download/ make sure to add it into PATH

Yeh it is

**Comment by goyalyashpal** [comment]
@TAMILVIP007 how did u fix this?? i (and my teammates too) are facing exactly same issue

**Comment by goyalyashpal** [comment]
## Environment info:

* OS: Windows 10 22H2
* python: 3.11.2 (via python.org installer)
* pip: 23.1.2
* shell: bash (via msys2)
* cmake: 3.26.4 (mingw-w64 via msys2)

## Logs

```console
$ pip install dlib --verbose
```

```powershell
Using pip 23.1.2 from D:\15_devt\GitHub\oooo\.venv\Lib\site-packages\pip (python 3.11)
Collecting dlib
  Using cached dlib-19.24.2.tar.gz (11.8 MB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Collecting cmake
    Using cached cmake-3.26.4-py2.py3-none-win_amd64.whl (33.0 MB)
  Installing collected packages: cmake, wheel, setuptools
  Successfully installed cmake-3.26.4 setuptools-68.0.0 wheel-0.40.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  writing tools/python\dlib.egg-info\PKG-INFO
  writing dependency_links to tools/python\dlib.egg-info\dependency_links.txt
  writing top-level names to tools/python\dlib.egg-info\top_level.txt
  reading manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'tools\python\build*'
  no previously-included directories found matching 'dlib\cmake_utils\*\build*'
  no previously-included directories found matching 'dlib\test'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  adding license file 'LICENSE.txt'
  writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info
  writing C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info\PKG-INFO
  writing dependency_links to C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info\dependency_links.txt
  writing top-level names to C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info\top_level.txt
  writing manifest file 'C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'tools\python\build*'
  no previously-included directories found matching 'dlib\cmake_utils\*\build*'
  no previously-included directories found matching 'dlib\test'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  adding license file 'LICENSE.txt'
  writing manifest file 'C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib.egg-info\SOURCES.txt'
  creating 'C:\Users\NemoUSR\AppData\Local\Temp\pip-modern-metadata-g7st43en\dlib-19.24.2.dist-info'
  Preparing metadata (pyproject.toml) ... done
```

```powershell
Building wheels for collected packages: dlib
  Running command Building wheel for dlib (pyproject.toml)
  running bdist_wheel
  running build
  running build_ext
  <string>:125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  Building extension for Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\NemoUSR\AppData\Local\Temp\pip-install-m4l_t_ho\dlib_3eca10703e464ad1a0cbb41bdcc2b738\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\NemoUSR\AppData\Local\Temp\pip-install-m4l_t_ho\dlib_3eca10703e464ad1a0cbb41bdcc2b738\build\lib.win-amd64-cpython-311 -DPYTHON_EXECUTABLE=D:\15_devt\GitHub\oooo\.venv\Scripts\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\NemoUSR\AppData\Local\Temp\pip-install-m4l_t_ho\dlib_3eca10703e464ad1a0cbb41bdcc2b738\build\lib.win-amd64-cpython-311 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:5 (message):



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!




  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "D:\15_devt\GitHub\oooo\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "D:\15_devt\GitHub\oooo\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\15_devt\GitHub\oooo\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 218, in <module>
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\NemoUSR\AppData\Local\Temp\pip-build-env-uaev03an\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 130, in run
    File "<string>", line 167, in build_extension
    File "D:\ProgramFiles\Python\Python311\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\NemoUSR\\AppData\\Local\\Temp\\pip-install-m4l_t_ho\\dlib_3eca10703e464ad1a0cbb41bdcc2b738\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\NemoUSR\\AppData\\Local\\Temp\\pip-install-m4l_t_ho\\dlib_3eca10703e464ad1a0cbb41bdcc2b738\\build\\lib.win-amd64-cpython-311', '-DPYTHON_EXECUTABLE=D:\\15_devt\\GitHub\\oooo\\.venv\\Scripts\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\NemoUSR\\AppData\\Local\\Temp\\pip-install-m4l_t_ho\\dlib_3eca10703e464ad1a0cbb41bdcc2b738\\build\\lib.win-amd64-cpython-311', '-A', 'x64']' returned non-zero exit status 1.
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'D:\15_devt\GitHub\oooo\.venv\Scripts\python.exe' 'D:\15_devt\GitHub\oooo\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' build_wheel 'C:\Users\NEMOUS~1\AppData\Local\Temp\tmp1mc7baho'
  cwd: C:\Users\NemoUSR\AppData\Local\Temp\pip-install-m4l_t_ho\dlib_3eca10703e464ad1a0cbb41bdcc2b738
  Building wheel for dlib (pyproject.toml) ... error
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

```

**Comment by facug91** [comment]
Do you have Visual C++ installed?

**Comment by facug91** [comment]
Well, what you say about the documentation seems right, it doesn't specify Visual C++ for Windows. But in the error log you uploaded says:

```
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

So I guess you need to install that one.

**Comment by facug91** [comment]
Just to be clear, I hardly ever use Windows, and I've never used dlib with Python, I'm just trying to help. If that doesn't work, maybe someone else can give you a hint.

**Comment by goyalyashpal** [comment]
* i am 90% sure it has to do something with #2803 
* ... & the corresponding fix # 2804 which add "_minimal_ pyproject.toml"
* ... i.e. not a significant information in the `[build-system]` section if i am right....

**Comment by goyalyashpal** [comment]
hey @davisking 

I am sorry to ask like this, but can u please help look into this. 

i have tried looking 
* at various places like stackoverflow, youtube; and 
* at various approaches: 
* different package managers (pip, micromamba), 
* using different os (windows local, vs. linux  remote codespaces)
* compiling vs using precompiled wheel (.whl) binaries etc... 

but nothing seem to be working and is failing one way or the another... please help 🙏🙏

**Comment by davisking** [comment]
> Well, what you say about the documentation seems right, it doesn't specify Visual C++ for Windows. But in the error log you uploaded says:
> 
> 
> 
> ```
> 
>     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 
> 
> 
> 
>     You must use Visual Studio to build a python extension on windows.  If you
> 
>     are getting this error it means you have not installed Visual C++.  Note
> 
>     that there are many flavors of Visual Studio, like Visual Studio for C#
> 
>     development.  You need to install Visual Studio for C++.
> 
> 
> 
> 
> 
>     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> ```
> 
> 
> 
> So I guess you need to install that one.

This is the answer. You have to do like these instructions say. That is, for windows, python (not dlib) requires visual studio.

**Comment by goyalyashpal** [comment]
so there's no way to use the msys toolchain?

**Comment by goyalyashpal** [comment]
[micromamba]: https://mamba.readthedocs.io/en/latest/installation.html#micromamba-standalone-executable "micromamba"
[conda-forge]: https://conda-forge.org/feedstock-outputs/index.html "conda-forge feedstock"
[conda-forge]: https://conda.anaconda.org/conda-forge/ "conda-forge on anaconda"
[pypi-dlib]: https://pypi.org/project/dlib "dlib on pypi"
[conda-forge-dlib]: https://anaconda.org/conda-forge/dlib "dlib on conda-forge"

> these pac-mans mentioned that they fetch packages from community distributed builds

yeah, used [micromamba] with packages from the "channel" [conda-forge], it fetched this thing for dlib, and _finallyyyy_ it's working good :)

also, the version in conda-forge (at least for [dlib][conda-forge-dlib]) matches the one distributed at [pypi][pypi-dlib] (i.e. via pip): 19.24.2 :)

```
  Name                       Version             Build               Channel
----------------------------------------------------------------------------------
  dlib                       19.24.2             py311he12e1e2_0     conda-forge
```

**Comment by davisking** [comment]
Visual studio is free.  So you could download it and install in short order.  For more details see https://docs.python.org/3/extending/windows.html.  The notable detail is it also instructs you to use visual studio.  If you want to do something else then you are on your own.  I honestly don't know if it would be possible. I expect it would not work though.

**Comment by goyalyashpal** [comment]
> If you want to do something else then you are on your own. I honestly don't know if it would be possible. I expect it would not work though.

I dont understand what this meant. 

but the `conda` (or `micromamba` in my case, hereafter referred as mmb) approach is used by Anaconda IDE, and is widely used as much commonly as `pip`. also, after completing the setup with mmb, i ran my python program using dlib and it worked.

---- 

> Visual studio is free. So you could download it and install in short order.

following may sound like a rant, but its not. I am just calmly laying down all the reasons why i didnt follow that way.

[#218 comment]: https://github.com/davisking/dlib/issues/218#issuecomment-419350406
[readme by charlielito]: https://github.com/charlielito/install-dlib-python-windows#readme
[vc]: https://visualstudio.microsoft.com/vs/community/
[see here]: https://github.com/microsoft/PowerToys/issues/20656

1. Visual Studio might be free, but its a ginormous bloat package, which as per this [readme by charlielito] file (mentioned at [#218 comment]) consumes 12GB. 

2. Also, _like all MicroSoft products_ ([see here] for _one_ example) , it doesn't mention upfront the download & install size required. And i assume it wont tell even while downloading either.

3.  * The file downloaded from the [site of Visual Studio][vc] "VisualStudioSetup.exe" is just 3-4 MiB, i.e. it will fetch the installer later on and is not standalone. 
    * The experience with non-standalone/file fetchers like google chrome, ms vscode, ms widows update helper, google android studio, desktop analytics etc 
    * ... tells me this approach is _extemely fragile_ and unreliable as these small fetchers likely dont contain a dedicated robust download manager to resume downloads.
    * Yes, the network connection doesnt always stay silk smooth.

4. These all things make me feel even more helpless, and like _a puppet_. Alongwith; it also has an unproductive financial, mental & temporal toll:
    * just waiting hours for download to finish; 
    * incurring additional charges on data connection;  
    * staying awake at night (in hopes of faster download speeds)
    * yet still having the fears that the whole download can fail even at last moment.

5. Even after finishing the download:
    * I am forever afraid to uninstall that fat bloat lest having to go through all that again. So, it behaves like a lock-in as well.
    * Oh, and updates....

7. All this is just not worth it for me. I strive to avoid such trapes at all costs.

Contrast this with other way, u just spend _time_ actually _learning_ the stuff once, and it most likely remains reproducible in future. no repeated and constant (for lack of a better word at hand) tortures. 

the download size is communicated beforehand, i am not treated like a kid and spoonfed blindly with bloat.

**Comment by davisking** [comment]
Yeah I feel you.  I loath needing to turn on visual studio or deal with it.  This stuff is outside my control though.  Like what you did was just find some other package system where someone else built dlib with visual studio for you.  I really don't want to get into the binary package game, especially on windows, in part because of the issues you mentioned with visual studio.  But that is just the tip of the iceberg.

The other problem you will find with these binary dlib packages is they are built to lowest common denominator hardware.  So it will be slower than if you built it yourself.  E.g. it probably isn't built to use AVX instructions.  And I wager it isn't built with CUDA or cuDNN either.  And I definitely do not want to get into the repackaging nvidia binaries, that's even more frustrating than dealing with visual studio.

**Comment by arrufat** [comment]
Actually, I've been thinking about how to solve this problem, too, since a big chunk of the issues that people open here are related to Windows installation and MSVC.

For some time now, I've keeping an eye on [Zig](https://ziglang.org/).

I got interested in it for several reasons, but one of them is that it ships with Clang, so it's able to build C++ code.

You just [download](https://ziglang.org/download/) the binary for your platform from their website and type `zig c++` and you get access to a ready to roll C++ compiler (it's just Clang).

So maybe then, just running `CC="zig cc" CXX="zig c++" cmake -B build` should work. I need to try it, though.

Furthermore, if I made a `build.zig` that compiles dlib, then the compilation would be trivial on all platforms: just run `zig build` and done. You could even cross-compile easily, just by passing the target OS as a flag to the command line.

I don't know how hard it is to get CMake feature parity, but I am certainly willing to try. That should probably not be the recommended way of installing dlib if you want to use it as a library, though.

However, being able to build the python module using `zig build` would be a game changer for Python users, especially those on Windows.

Here's an [example](https://github.com/raysan5/raylib/blob/master/build.zig) of a C project that uses the Zig build system: [raylib](https://github.com/raysan5/raylib)

**Comment by davisking** [comment]
That would be neat.  It's got to be able to produce dll files that can be loaded by a binary built by visual studio (i.e. the python interpreter).  That's the real rub.  Visual studio is sort of its own world when it comes to how that all works, which is a big part of the problem.

**Comment by goyalyashpal** [comment]
one long term possible solution for all this - can be to go to https://discuss.python.org/ and raise your voices and concern about providing clang as an alternate to MS-VS.

Many other people have done already, if more and more module maintainers raise this concern, then they surely will provide this.

**Comment by davisking** [comment]
The biggest part of the problem isn't anything the core python devs did or have control over either though.  It's really due to the huge variability in C and C++ build systems, linking conventions, and so forth. It's not super clear to me there is much they can do either.

**Comment by arrufat** [comment]
Yes, I was exposed to the linking conventions issue in here: https://github.com/davisking/dlib/discussions/2838 for the first time in my life.

I had always built everything with the same compiler, so far.

**Comment by davisking** [comment]
Yeah I'll be real surprised if that works :) 

Maybe though. At some point something hopefully unseats visual studio. I kinda want clang to eat the world.

**Comment by arrufat** [comment]
Oh, why is that? Ease of cross-platform development?

**Comment by davisking** [comment]
The biggest problem with C++ is how confusing the build process is to people. It's too easy to run into binary incompatibility or ODR problems.

But you could imagine some day there is some standard way to build. And then there can be some decent C++ package management.

Not going to hold my breath though. At its root this requires a bunch of organizations to all cohesively cooperate in a way you don't often see. And there is all this old stuff that needs to be incorporated somehow too. Like Fortran libraries.

**Comment by arrufat** [comment]
Oh, yeah, that too…

**Comment by goyalyashpal** [comment]
hi again. can u share the dlib wheeels for windows with me - even if unofficially? 😓 
i am having trouble getting other tools to work with micromamba: https://github.com/mamba-org/mamba/issues/2702

**Comment by arrufat** [comment]
I don't have any dlib wheels.
