### ISSUE TITLE
Performance regression from version 19.23 onwards

### ISSUE THREAD

**Issue by facug91** [davisking/dlib#2655]
I'm using dlib 19.22. When I tried to upgrade to dlib 19.24, I've noticed that my code ran ~11% slower. Then I tried to downgrade to 19.23, but the same happened.

I can't share my code, so I made a test runner modifying example [dnn_mmod_find_cars2_ex.cpp](https://github.com/davisking/dlib/blob/master/examples/dnn_mmod_find_cars2_ex.cpp). Here it's the code I use for this new tests:

<details>
<summary>Show/hide code</summary>

```cpp
// The contents of this file are in the public domain. See LICENSE_FOR_EXAMPLE_PROGRAMS.txt
/*
    This example shows how to run a CNN based vehicle detector using dlib.  The
    example loads a pretrained model and uses it to find the front and rear ends
    of cars in an image.  The model used by this example was trained by the
    dnn_mmod_train_find_cars_ex.cpp example program on this dataset:   
        http://dlib.net/files/data/dlib_front_and_rear_vehicles_v1.tar
    
    Users who are just learning about dlib's deep learning API should read
    the dnn_introduction_ex.cpp and dnn_introduction2_ex.cpp examples to learn
    how the API works.  For an introduction to the object detection method you
    should read dnn_mmod_ex.cpp.

    You can also see a video of this vehicle detector running on YouTube:
        https://www.youtube.com/watch?v=OHbJ7HhbG74
*/


#include <iostream>
#include <dlib/dnn.h>
#include <dlib/image_io.h>
#include <dlib/gui_widgets.h>
#include <dlib/image_processing.h>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace dlib;



// The front and rear view vehicle detector network
template <long num_filters, typename SUBNET> using con5d = con<num_filters,5,5,2,2,SUBNET>;
template <long num_filters, typename SUBNET> using con5  = con<num_filters,5,5,1,1,SUBNET>;
template <typename SUBNET> using downsampler  = relu<affine<con5d<32, relu<affine<con5d<32, relu<affine<con5d<16,SUBNET>>>>>>>>>;
template <typename SUBNET> using rcon5  = relu<affine<con5<55,SUBNET>>>;
using net_type = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>;

// ----------------------------------------------------------------------------------------

int main() try
{
	net_type net;
	shape_predictor sp;
	// You can get this file from http://dlib.net/files/mmod_front_and_rear_end_vehicle_detector.dat.bz2
	// This network was produced by the dnn_mmod_train_find_cars_ex.cpp example program.
	// As you can see, the file also includes a separately trained shape_predictor.  To see
	// a generic example of how to train those refer to train_shape_predictor_ex.cpp.
	deserialize("mmod_front_and_rear_end_vehicle_detector.dat") >> net >> sp;

	//image_window win;

	std::vector<std::string> paths;
	cv::glob("<path_to_images_folder>", paths);
	cv::Mat image;

	matrix<rgb_pixel> img;

	int cnt = 0, sum = 0;
	for (const auto& path : paths) {
		load_image(img, path);
		cnt++;
		auto t1 = std::chrono::high_resolution_clock::now();
		// Run the detector on the image and show us the output.
		for (auto&& d: net(img)) {
			//win.set_image(img);
			// We use a shape_predictor to refine the exact shape and location of the detection
			// box.  This shape_predictor is trained to simply output the 4 corner points of
			// the box.  So all we do is make a rectangle that tightly contains those 4 points
			// and that rectangle is our refined detection position.
			auto fd = sp(img, d);
			rectangle rect;
			for (unsigned long j = 0; j < fd.num_parts(); ++j)
				rect += fd.part(j);

			//std::cout << rect << std::endl;
			//if (d.label == "rear")
			//	win.add_overlay(rect, rgb_pixel(255, 0, 0), d.label);
			//else
			//	win.add_overlay(rect, rgb_pixel(255, 255, 0), d.label);
		}
		auto t2 = std::chrono::high_resolution_clock::now();
		auto lapse = std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();
		sum += lapse;
		std::cout << cnt << " : " << lapse << std::endl;
	}
	std::cout << "Avg: " << sum / cnt << std::endl;


	cout << "Hit enter to end program" << endl;
	cin.get();
}
catch(image_load_error& e)
{
	cout << e.what() << endl;
	cout << "The test image is located in the examples folder.  So you should run this program from a sub folder so that the relative path is correct." << endl;
}
catch(serialization_error& e)
{
	cout << e.what() << endl;
	cout << "The correct model file can be obtained from: http://dlib.net/files/mmod_front_and_rear_end_vehicle_detector.dat.bz2" << endl;
}
catch(std::exception& e)
{
	cout << e.what() << endl;
}
```

</details>

I've used 970 image files I have in my computer, with many different sizes, but I think any dataset of images can be used to test it.

After running this test many times, I observed performance being consistently slower with the newer version. With dlib 19.22, processing time is at an average of 36.2 ms, while in `master` it is around 39.8 ms. This is roughly the same results I get with my own software, which runs around ~9.94% slower.

To make it easier to reproduce, I've used the Docker image: `nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04`.

If there is any extra information which I may have forgotten, please let me know so I may provide it.

**Comment by arrufat** [comment]
Do you think it's related to that PR, in particular, to `cudnnConvolutionBiasActivationForward`?
Could you try to fuse the layers (`fuse_layers(net)`) and see of you recover the speed?

**Comment by facug91** [comment]
In fact it was a strange coincidence, but it could be related to that PR.

I've run tests again. Improves speed, but still not as good as it was. These are the new results:
- `master` without `fuse_layers`: 40ms  
- `master` with `fuse_layers`: 38.2ms  
- `v19.22`: 36.7ms  

I'm using a GeForce GTX 1650, if that helps in some way.

**Comment by arrufat** [comment]
Hi, thanks for looking into this. Here are my results:

- `master` without `fuse_layers`: 6.67151±0.978008 ms 
- `master` with `fuse_layers`: 6.6486±1.06256 ms (-0.34%)
-  `v19.22`: 6.42804±1.0158 ms (-3.65%, -3.32%)

First, I've run a slightly different program, where I only measure the network inference, with a `running_stats_decayed` and a half-life decay of 100 to avoid the memory allocation issue at the beginning and other variables.
I've run it over the 5000 validation image set of COCO2017 on a Quadro RTX 5000, using CUDA 11.7.1 and cuDNN 8.4.1.

I do notice that the current code is slightly slower than the master version, but not 10%.
It's hard to understand why, though.
Dlib v19.22 does two calls for each convolution (CUDA kernel and bias addition) while master does it all in one call. When the layers are fused, the bias addition is not even done.

I wonder if that's the case for larger networks, too.
I remember that, when I benchmarked this, it was a ResNet50, and several YOLO models, and I got consistent (but sometimes small) speed improvements when fusing layers over the original net, as I mentioned here: https://github.com/davisking/dlib/pull/2294#issuecomment-772506129

Here's the code I ran:
```c++
int main(int argc, char** argv) try
{
    net_type net;
    shape_predictor sp;
    deserialize("mmod_front_and_rear_end_vehicle_detector.dat") >> net >> sp;
    fuse_layers(net);

    matrix<rgb_pixel> img;
    const auto files = get_files_in_directory_tree(argv[1], match_endings(".jpg"));
    console_progress_indicator progress(files.size());
    running_stats_decayed<float> stats(100);
    for (size_t i = 0; const auto& file : files)
    {
        load_image(img, file.full_name());
        const auto t0 = chrono::steady_clock::now();
        const auto dets = net(img);
        const auto t1 = chrono::steady_clock::now();
        stats.add(chrono::duration_cast<fms>(t1 - t0).count());
        progress.print_status(++i);
    }
    progress.finish(); // this does not exist in v19.22
    std::cout << "time: " << stats.mean() << "±" << stats.stddev() << " ms" << std::endl;
}
```

**Comment by davisking** [comment]
Yeah I was just reading over all the code changes and looking around as well.  I didn't run anything though.  But it sure appears the relevant change is the switch from doing conv with two calls to just one.  Maybe for these networks cudnn's fused conv+bias addition sucks and we shouldn't use it :shrug:   Did either of you try switching `con_::forward()` from the current single fused call back to the one that invokes the bias adding separately?  I.e. switching back to this?
```
conv(false, output,
     sub.get_output(),
     filters(params,0));
tt::add(1,output,1,biases(params,filters.size()));
```

**Comment by arrufat** [comment]
With your change, on master, we get this:
- without `fuse_layers`: 6.23861±1.02142 ms
- with `fuse_layers`: 6.06294±1.00233 ms

I will prepare PR.

**Comment by arrufat** [comment]
@davisking thank you :)

**Comment by davisking** [comment]
> @davisking thank you :)

No problem, and really thank you for the PR :)
