### ISSUE TITLE
error in installing dlip: ‘WebPFree’ was not declared in this scope

### ISSUE THREAD

**Issue by hoduchieu01** [davisking/dlib#2657]
## Expected Behavior

When I install the dlib by following the documentation, I faced the issue as below

## Current Behavior

aibrain@aibrain-VirtualBox:~/lib/dlib/build$ cmake --build .
[  1%] Building CXX object dlib/CMakeFiles/dlib.dir/image_saver/save_webp.cpp.o
/home/aibrain/lib/dlib/dlib/image_saver/save_webp.cpp: In function ‘void dlib::impl::impl_save_webp(const string&, const uint8_t*, int, int, int, float, dlib::impl::webp_type)’:
/home/aibrain/lib/dlib/dlib/image_saver/save_webp.cpp:78:36: error: ‘WebPFree’ was not declared in this scope
                     WebPFree(output);
                                    ^
/home/aibrain/lib/dlib/dlib/image_saver/save_webp.cpp:86:28: error: ‘WebPFree’ was not declared in this scope
             WebPFree(output);
                            ^
dlib/CMakeFiles/dlib.dir/build.make:915: recipe for target 'dlib/CMakeFiles/dlib.dir/image_saver/save_webp.cpp.o' failed
make[2]: *** [dlib/CMakeFiles/dlib.dir/image_saver/save_webp.cpp.o] Error 1
CMakeFiles/Makefile2:97: recipe for target 'dlib/CMakeFiles/dlib.dir/all' failed
make[1]: *** [dlib/CMakeFiles/dlib.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

## Steps to Reproduce

I installed by following the README documentation with the python 2.7.12 and cmake  3.24.1 on ubuntu 16.04

**Comment by arrufat** [comment]
Maybe that ubuntu version comes with a libwebp that is too old? Could you try again disabling WebP support?

**Comment by hoduchieu01** [comment]
@arrufat Thank you for your suggestion. Could you let me know how I do that?

**Comment by arrufat** [comment]
You can do it the “graphical” way, by typing `ccmake .` inside the build directory, and toggling the `DLIB_WEBP_SUPPORT` flag.

Or directly, when you configure `cmake`, you can pass the flag `cmake -DDLIB_WEBP_SUPPORT=OFF`.

**Comment by arrufat** [comment]
I've just noticed that `WebPFree` was introduced in v0.5.0, whereas Ubuntu 16.04 ships v0.4.4, both released in 2015. See the [NEWS](https://chromium.googlesource.com/webm/libwebp/+/refs/heads/main/NEWS#155) file.

I don't know whether we should check for the libwebp version and either:
- disable WebP support for versions lower than 0.5.0.
  - how many people are still using Ubuntu 16.04?
  - Canonical wants to support it until 2026, but should we?
- handle the case to allow for lower versions (not too fond of this one)

Or even not care about this case, and users can either:
- use a dlib version lower than v19.24
- update their systems
- disable WebP support
- update their libwebp, if they really need WebP support in dlib.

But I think we might have to do something about it, as this is the second issue we get on this, ref: #2594.

**Comment by davisking** [comment]
Should totally have cmake check for the right version and not use it if it's not available.  I expected this, since this always happens with third party libraries :)

**Comment by arrufat** [comment]
Ok, let me see how I can make this happen :)

**Comment by hoduchieu01** [comment]
@arrufat Thank you for your suggestion. I have installed it successfully by following your suggestion. For those who face the same issue, please use this command `sudo python setup.py install --no DLIB_WEBP_SUPPORT`

**Comment by arrufat** [comment]
@hoduchieu01 no problem, hopefully, a better solution is coming :)
