### ISSUE TITLE
Failure to build with py11

### ISSUE THREAD

**Issue by luyatshimbalanga** [davisking/dlib#2659]
## Expected Behavior
dlib should be able to build with python 3.11

## Current Behavior
dib failed to build with newest version of python 3.11.
[build.log](https://github.com/davisking/dlib/files/9440233/build.log)

## Steps to Reproduce
Attempt to build dlib with python 3.11. Provided log above to see the failure.

* **Version**: 19.24
* **Where did you get dlib**: dlib.net via https://src.fedoraproject.org/rpms/dlib/
* **Platform**: Fedora Linux 36
* **Compiler**: gcc 12.2.1

**Comment by davisking** [comment]
Python 3.11 is not out yet.  The latest release of python is 3.10.

**Comment by luyatshimbalanga** [comment]
I am aware that python 3.11 will get released on October 22. Fedora Project just used the unreleased python 3.11 on their build system exposing the failure. Additionally, [Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html) is in candidate release giving the opportunity address future changes.

In a meanwhile, is there a way to use external pybind11 as it seems the internal version in dlib failed to handle python 3.11?

**Comment by davisking** [comment]
You can just replace the code in dlib/external/pybind11.   But yes, if there end up being API breaks in python 3.11 when it's fully released we will update pybind11.  I'm fine with updating pybind11 now if you want to send a PR for it.

**Comment by arrufat** [comment]
@luyatshimbalanga, could you try to build again from master (after #2660 or commit https://github.com/davisking/dlib/commit/65bce59a1512cf222dec01d3e0f29b612dd181f5)?

**Comment by luyatshimbalanga** [comment]
@arrufat The commit successfully built as highlighted by the [build.log](https://github.com/davisking/dlib/files/9572866/build.log). Updating pybind11 solved the issue.

**Comment by AbdullahJirjees** [comment]
I am getting errors with installing dlib v 19.24.1 with python3.10
