### ISSUE TITLE
Other Shape Detectors Models (Public)

### ISSUE THREAD

**Issue by lucmichalski** [davisking/dlib#266]
Hi guys,

Hope you are all doing well !

I was wondering if there is any wiki page or official page to share custom shape predicators made with DLIB ? Same spirit as for caffe and some pre-trained models: https://github.com/BVLC/caffe/wiki/Model-Zoo

I saw one for cats but it is not working well as only 20 pics were used to train the shape predicator:
https://enoxsoftware.com/dlibfacelandmarkdetector/documentation/q-a/

And one gist for road signs:
https://gist.github.com/iandees/f773749c47d088705199

Cheers,
L.

**Comment by davisking** [comment]
There is this github repository with the official dlib models in it https://github.com/davisking/dlib-models.  

I just added a wiki page for this here https://github.com/davisking/dlib-models/wiki/Trained-models.  Not a lot to put there at the moment though.

**Comment by grisevg** [comment]
@davisking  What was `mmod_dog_hipsterizer.dat.bz2` trained on? Does it  detect faces?

**Comment by davisking** [comment]
I just updated the wiki.  But it's from this new example program: https://github.com/davisking/dlib/blob/master/examples/dnn_mmod_dog_hipsterizer.cpp.  

It automatically draws glasses and a mustache on dogs :)

Like this:

![image](https://cloud.githubusercontent.com/assets/6259399/19149275/0be7a078-8b8f-11e6-801b-3160c046cb4c.png)

**Comment by grisevg** [comment]
@davisking this is brilliant, thank you so much! 
I've been trying to do a dog face detection and alignment for some time now, but couldn't get over 90% recall in HOG, even with clustering.
I haven't tried CNNs yet, because of CUDA Windows problems and my limited knowledge on CNN design, so this example will help me a lot.

**Comment by davisking** [comment]
Na, no problem.  This was too funny of a dlib demo to pass up.  Creating
the detector with a CNN was actually somewhat trivial :)

**Comment by lucmichalski** [comment]
Hi @davisking,

That's really awesome :-) What is the name of the example to use to test it ?

And, do you think that CNN could work on Unity 3D too ? (https://github.com/EnoxSoftware/DlibFaceLandmarkDetector). Or getting some performances improvements above the one mentioned by http://www.learnopencv.com/speeding-up-dlib-facial-landmark-detector/. 

I wonder if ArrayFire could help Dlib to be more performant too or what could help to be more efficient on mobile devices ? https://github.com/arrayfire/arrayfire 

Ps. I made a face shape detectors for cats with Dlib with 5k pictures but still need some tweaks on it. Will share it later.

Cheers,
Luc Michalski

**Comment by davisking** [comment]
This example: https://github.com/davisking/dlib/blob/master/examples/dnn_mmod_dog_hipsterizer.cpp

**Comment by RoyiAvital** [comment]
Pretrained models are great!

Has anyone trained on 194 Landmark Points using the [Helen Database](http://www.ifp.illinois.edu/~vuongle2/helen/)?

Thank You.
