### ISSUE TITLE
ValueError: path 'dlib/CMakeLists.txt/' cannot end with '/'

### ISSUE THREAD

**Issue by Azheng-tora** [davisking/dlib#2668]
I am installing GPU accelerated dlib.
My compiling orders are:

git clone https://github.com/davisking/dlib.git
cd dlib
mkdir build
cd build
cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
cmake --build .
cd ..
python setup.py install --set USE_AVX_INSTRUCTIONS=1 --set DLIB_USE_CUDA=1

The environment is Anoconda. And the version of python is Python 3.6.13 :: Anaconda, Inc.

And I encountered an error.
ValueError: path 'dlib/CMakeLists.txt/' cannot end with '/'
![DlibInstallError](https://user-images.githubusercontent.com/112361984/191705727-0fb66e96-c5fc-4611-8e79-a2d8b017809f.jpg)

I donot know how to fix this. I need your help.

**Comment by Azheng-tora** [comment]
I know how to fix it now. 
open util.py and change the 127th line: pathname=pathname[:-2].

Now my new problem is:
error: [WinError 183] 当文件已存在时，无法创建该文件。: 'build\\bdist.win-amd64\\egg\\EGG-INFO\\PKG-INFO'.

My order is:
F:\dlib>python setup.py install --clean --no DLIB_GIF_SUPPORT --set USE_AVX_INSTRUCTIONS=1 --set DLIB_USE_CUDA=1

Thank you for your help.

**Comment by geocine** [comment]
Have you found a solution?

**Comment by Azheng-tora** [comment]
Thank you, geocine.  I succeeded.
