### ISSUE TITLE
train_shape_predictor_ex problem

### ISSUE THREAD

**Issue by MurphyLaw** [davisking/dlib#267]
so I've added some pictures to your examples of testing_with_face_landmarks.xml and training_with_face_landmarks.xml, added 4 images in training and 2 images in testing.
then, I do think I placed the 68 landmarks correctly in the added images, however, after I started the train_shape_predictor_ex and get a new .DAT and used it in webcam_face_pose_ex I've got an error that says I've got a total of 78 landmarks instead of 68 landmarks.
did I do something wrong in the process?

**Comment by davisking** [comment]
Obviously you did something wrong :)

Also, http://dlib.net/faq.html#Itdoesn'twork
