### ISSUE TITLE
Linking with mold fails

### ISSUE THREAD

**Issue by kiufta** [davisking/dlib#2670]
Linking with https://github.com/rui314/mold doesn't work:

## Current Behavior
```
mold: error: duplicate symbol: dlib_build/libdlib.a(global_function_search.cpp.o): /tmp/ccYNTk0E.ltrans2.ltrans.o: std::_Sp_make_shared_tag::_S_ti()::__tag
mold: error: duplicate symbol: dlib_build/libdlib.a(fonts.cpp.o): /tmp/ccYNTk0E.ltrans74.ltrans.o: dlib::crc32::table(unsigned int) const::crc_table
mold: error: duplicate symbol: dlib_build/libdlib.a(widgets.cpp.o): /tmp/ccYNTk0E.ltrans0.ltrans.o: std::__detail::__to_chars_10_impl<unsigned int>(char*, unsigned int, unsigned int)::__digits
```

## Steps to Reproduce
`	python setup.py build --no DLIB_USE_CUDA`

* **Version** & **Where did you get dlib**: 19.25-git
* **Platform**:  ArchLinux
* **Compiler**: gcc 12.2, Python 3.10

**Comment by arrufat** [comment]
I've been building my dlib projects using mold for some time now, and never had an issue. Could you give more details? How are you telling GCC to use mold, for example?

I usually put this in my CMakeLists.txt file

```cmake

# Use the mold linker if possible
find_program(MOLD_FOUND mold)
if(MOLD_FOUND)
    message(STATUS "MOLD linker was found")
    add_compile_options(-fuse-ld=mold)
endif()
```

**Comment by kiufta** [comment]
I'm adding mold through the LDFLAGS
`LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fuse-ld=mold"`

**Comment by arrufat** [comment]
However, it builds fine using clang:
`CC=clang CXX=clang++ LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fuse-ld=mold" python setup.py build --no DLIB_USE_CUDA`

So, there must be an isse in GCC?
