### ISSUE TITLE
warn_about_unavailable_but_used_cpu_instructions() doesn't work

### ISSUE THREAD

**Issue by kolbma** [davisking/dlib#2675]
## Expected Behavior

There is  
https://github.com/davisking/dlib/blob/1bebccfb8728f6112d6142ba24f2dd65970ff6a2/dlib/simd/simd_check.h#L153-L171

And this also gets called by python module here:  
https://github.com/davisking/dlib/blob/1bebccfb8728f6112d6142ba24f2dd65970ff6a2/tools/python/src/dlib.cpp#L42

So I should see a warning about compiled in instructions not available, like...

```
$ echo "import dlib;" | python3
Dlib was compiled to use AVX instructions, but these aren't available on your machine.
Illegal instruction (core dumped)
```

## Current Behavior

But there seems to be some call to __AVX__ related instruction before this warning is called.  
And the SEGV is immediately on import.

```
$ echo "import dlib;" | python3
Illegal instruction (core dumped)
```

## Steps to Reproduce

Compile dlib with AVX enabled (Linux distribution cloud build environments).  
Try to import it on an old CPU without AVX.

## Possible the problem

https://github.com/davisking/dlib/blob/1bebccfb8728f6112d6142ba24f2dd65970ff6a2/tools/python/src/dlib.cpp#L4-L7

Here the `#include "opaque_types.h"` is doing a lot including. And the `dlib/simd/simd_check.h` check is after all this.

* **Version**: 19.24.0
* **Where did you get dlib**: https://files.pythonhosted.org/packages/source/d/dlib/dlib-19.24.0.tar.gz
* **Platform**: openSUSE Leap 15.4 x86_64
* **Compiler**: different GCC versions

**Comment by davisking** [comment]
Yeah realistically I don't know what can be done to avoid this.  GCC is likely emitting AVX instructions for some run of the mill C++ code somewhere that runs earlier.  Like in some constructor of some variable at global scope maybe.  So I don't know how this would be avoided for all platforms and compilers.  You could try adding a global variable that calls `warn_about_unavailable_but_used_cpu_instructions()` in its constructor to see if it ends up being called first.   But other than that :shrug:

**Comment by kolbma** [comment]
Ok.  
Maybe we just document it with these issues, so that others find the source of the problem faster.  
I'm not interested in investing much more time to try this out.  
Closing?

**Comment by davisking** [comment]
Yeah, I added a comment about it that hopefully helps out the next person :)
