### ISSUE TITLE
Installing dlib returns an error that no matter what I do, I can't seem to fix.

### ISSUE THREAD

**Issue by Sxvxgee** [davisking/dlib#2683]
## Expected Behavior

I wasn't using dlib to begin with, I just had to install it so I can use a library called `face_recognizer`. Well, no matter what I do, dlib would just not install and return TONS of errors. What should happen is for dlib to install, but it isnt.

## Current Behavior

Whatever the hell I do to install dlib, I get this exact same error: https://mystb.in/AtlanticGhostEffective (error too long)

## Steps to Reproduce

I'm using python 3.11. I tried doing the normal `pip install dlib` I tried building cmake then doing the git cloning dlib and using make to build it, I tried using python to do setup.py install, I tried EVERYTHING.

* **Version**: latest
* **Where did you get dlib**:  official source
* **Platform**:  No LSB modules are available.
Distributor ID:	Zorin
Description:	Zorin OS 16.2
Release:	16
Codename:	focal

* **Compiler**: I guess cmake? I'm not sure, I just followed tons of guides including this: https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf and this: https://pyimagesearch.com/2018/01/22/install-dlib-easy-complete-guide/

**Comment by arrufat** [comment]
Try using dlib from the master branch, it's already Python 3.11 compatible.
Follow the instructions in the README file. https://github.com/davisking/dlib#compiling-dlib-python-api

**Comment by Sxvxgee** [comment]
> Try using dlib from the master branch, it's already Python 3.11 compatible. Follow the instructions in the README file. https://github.com/davisking/dlib#compiling-dlib-python-api

Alright, I'll try doing so and let you know if my problem was fixed.

**Comment by Sxvxgee** [comment]
> Try using dlib from the master branch, it's already Python 3.11 compatible. Follow the instructions in the README file. https://github.com/davisking/dlib#compiling-dlib-python-api

Sorry for replying twice and then deleting my replies, however I just remembered I did actually try that and I cloned the master branch and did those steps but it didn't work. The error I got is the same as in the original comment

**Comment by Sxvxgee** [comment]
> Try using dlib from the master branch, it's already Python 3.11 compatible. Follow the instructions in the README file. https://github.com/davisking/dlib#compiling-dlib-python-api

No matter what I tried, it gave me the same errors. And at times it'd stop and pause at around 58% and then crash.

**Comment by Suchir2004** [comment]
Download the dlib files
Link - https://drive.google.com/file/d/11Hip8-llWEm5GN3_u4ibI09unL7xCw0g/view?usp=drivesdk
And just copy the path of that file and paste it into the terminal.
Stable version is 10 among all files that you have been downloaded from the link

In terminal you just need copy the path of that particular file; there are 4 files the choose one which is suitable for your computer work on windows.

**Comment by Murtaza-Saeed** [comment]
This link will solve all your problem👇
https://youtu.be/qImLubzBOWg
