### ISSUE TITLE
Dlib is impossible to install

### ISSUE THREAD

**Issue by Abecadarian** [davisking/dlib#2693]
I have been trying to install dlib on Anaconda, and have been frustrated at every turn. When I try to run 'pip install dlib', the result is:

subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

I'm using Python 3.9 on Anaconda, on a Windows computer. I have not been able to find any information online whatsoever about why this is happening, and trying to install it by downloading dlib from GitHub and building it results in the same error. Can anyone provide me with some suggestions on how to fix this?

**Comment by arrufat** [comment]
I don't have enough information to see what's going on, but did you install CMake?

**Comment by Abecadarian** [comment]
Yes, I've installed CMake and Visual Studio.

**Comment by arrufat** [comment]
Is it CMake 3.25.0? Can you try with an 3.24.0 in that case?

**Comment by Abecadarian** [comment]
No, unfortunately that leads to the exact same output.

**Comment by vuehrjer** [comment]
I have the same problem and I don't understand why it is apparently impossible to get it to work with pip when it works with `conda install -c conda-forge dlib` like a charm, which is nice but not what I need.
