### ISSUE TITLE
extract features about object detect

### ISSUE THREAD

**Issue by junranhe** [davisking/dlib#27]
I use alex-net(deeplearning) to extract features of images, can I use your object detect framework?can you give me some advise？my feature is full connect layer data

**Comment by davisking** [comment]
Yes, you can do that.  In particular, you can replace the hog feature extractor with a user defined one by supplying an argument of your design as the second template argument to the scan_fhog_pyramid.  The details are documented in this file: http://dlib.net/dlib/image_processing/scan_fhog_pyramid_abstract.h.html#scan_fhog_pyramid
