### ISSUE TITLE
Custom Class in Node.data and Edge.data in directed_graph structure | Serialization error

### ISSUE THREAD

**Issue by shexbeer** [davisking/dlib#270]
Hi, i have a directed_graph structure which i want to (de)serialize.
In graph node data is a custom class of mine (QSharedPointer<CustomClass>).
Same in edge.data (std::pair<QSharedPointer<OtherClass>,QSharedPointer<OtherClass>>)

To let dlib know how to serialize my class i added this declarations in CustomClass Header:

`
namespace dlib {
inline void serialize (const QSharedPointer<MML::Operator::Operator>& item,std::ostream& out);
inline void deserialize (QSharedPointer<MML::Operator::Operator>& item, std::istream& in);
}
`

with this implementation:

`
namespace dlib {
void serialize(const QSharedPointer<MML::Operator::InputPort> &item, std::__1::ostream &out)
{
    if(!item.isNull()) {
        std::stringstream helpStream;

        QBuffer buffer;
        QDataStream stream;
        stream.setDevice(&buffer);

        stream << item;

        out << buffer.buffer().toStdString();
    } else {
        qCritical(MML::LogCategory_Serialization) << "Something went wrong while deserialize a operator. Possible a unknown operator type?";
    }
}

void deserialize(QSharedPointer<MML::Operator::InputPort> &item, std::__1::istream &in) \
{
    // reading into memory via stringstream
    std::stringstream stringstream;
    stringstream << in.rdbuf();

    // converting into a qt bytearray
    QByteArray operatorAsBytes( stringstream.str().data(), static_cast<int>(stringstream.str().size()) );

    // putting bytes into a qdatastream
    QBuffer qBuffer;
    QDataStream datastream;
    datastream.setDevice(&qBuffer);
    datastream << operatorAsBytes;

    // using regular qt deserialization
    datastream >> item;
}
`

My Problem is error:
`../../../MMLLibrary/ldlib/dlib/serialize.h:785: Error: call to 'serialize' is ambiguous
            serialize(item.first,out);
            ^~~~~~~~~
../../../MMLLibrary/lib/dlib/dlib/directed_graph/directed_graph_kernel_1.h:428: in instantiation of function template specialization 'dlib::serialize<QSharedPointer<MML::Operator::OutputPort>, QSharedPointer<MML::Operator::InputPort> >' requested here
                    serialize(item.node(i).child_edge(c), out);
                    ^
/Users/christian/GIT/Masterarbeit/src/MobileML/MMLLibrary/operator/executionenviroment/operatorgraph.cpp:252: in instantiation of function template specialization 'dlib::serialize<QSharedPointer<MML::Operator::Operator>, std::__1::pair<QSharedPointer<MML::Operator::OutputPort>, QSharedPointer<MML::Operator::InputPort> >, dlib::memory_manager_stateless_kernel_1<char>, true>' requested here
    dlib::serialize(operatorGraph_, helpStream);
          ^
/Users/christian/GIT/Masterarbeit/src/MobileML/MMLLibrary/operator/operator.h:89: candidate function
inline void serialize (const QSharedPointer<MML::Operator::Operator>& item,std::ostream& out);
            ^
../../../MMLLibrary/lib/dlib/dlib/serialize.h:740: candidate function
    inline void serialize (
                ^
`

Same error for Edge serialization.

Whats the common way to implement custom class serialization for graph structures?

Best Regards,
Christian

**Comment by davisking** [comment]
Don't put your functions in the dlib namespace.   Put them in the same
namespace you put the rest of your code.

**Comment by shexbeer** [comment]
Thanks for your help. That caused the error!
Great work with your library 👍

**Comment by davisking** [comment]
No problem :)
