### ISSUE TITLE
Example variadic Python functions in find_max_global

### ISSUE THREAD

**Issue by AnkitAggarwalAlphagrep** [davisking/dlib#2700]
Hi

Please provide me the example for using the find_max_global with non fixed number of arguyments. The current example present doesn't show the functionality

Thanks,
Ankit

**Comment by davisking** [comment]
Do this kind of thing
```
def holder_table(*args):
    x0, x1 = args
    return -abs(sin(x0)*cos(x1)*exp(abs(1-sqrt(x0*x0+x1*x1)/pi)))
```
