### ISSUE TITLE
dlib import error on termux 

### ISSUE THREAD

**Issue by okbyxray** [davisking/dlib#2702]
I try to run a program but it returns an error

###################################
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/./faceswap.py", line 47, in <module>
    import dlib
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/dlib-19.24.99-py3.11-linux-aarch64.egg/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/dlib-19.24.99-py3.11-linux-aarch64.egg/_dlib_pybind11.cpython-311.so"...
###################################

then,I try to replace "from _dlib_pybind11 import *" with "#from _dlib_pybind11 import".But another error appeared

###################################Traceback (most recent call last):                             File "/data/data/com.termux/files/home/./faceswap.py", line 47, in <module>
    import dlib                                                File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/dlib-19.24.99-py3.11-linux-aarch64.egg/dlib/__init__.py", line 20, in <module>
    from _dlib_pybind11 import __version__, __time_compiled__
ImportError: dlopen failed: cannot locate symbol "PyExc_ImportError" referenced by "/data/data/com.termux/files/usr/lib/python3.11/site-packages/dlib-19.24.99-py3.11-linux-aarch64.egg/_dlib_pybind11.cpython-311.so"...
###################################

How to fix it?

dlib version:19.24.99
python version:3.11.1
termux version:0.118.21
android version:12

**Comment by hxssnb** [comment]
6
