### ISSUE TITLE
dlib::toMat results in error.

### ISSUE THREAD

**Issue by CMF-TOM** [davisking/dlib#2709]
## Expected Behavior
cv::Mat newImage = dlib::toMat(image); // this should wrap the image so that OpenCV Mat format could be used for other functions.

## code

#include <string>
#include <vector>
#include <stdlib.h>
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>
#include <dlib/image_io.h>
#include <iostream>
#include <dlib/opencv/cv_image.h>
Main { ....
    ......
    cv::Mat image = cv::imread(imagePath, cv::IMREAD_COLOR);
    dlib::cv_image<bgr_pixel> cv_img(image);
    assign_image(img, cv_img);
    
    std::vector<full_object_detection> shapes;
    dlib::array<array2d<bgr_pixel>>face_chips;
    getFaceShapes(img, shapes, face_chips); // this part works, no worries about here
    dlib::toMat(face_chips); // <== Error 
}

results with error
## error ##
namespace "dlib" has no member "toMat"C/C++(135)

## Steps to Reproduce
CMake include libs and includefiles to project file for OpenCV and dlib is included as subdirectoyry. I believe a conflict occurs for both sides tries to define a Mat object.
to_open_cv.h file
#include <opencv2/core.hpp> cannot include the file, main project has them all and working.

* **Version**: dlib-19.24
* **Where did you get dlib**: github release version dlib-19.24
* **Platform**: win11 x64, vscode
* **Compiler**: CMake + Visual Studio 17
* 
![image](https://user-images.githubusercontent.com/106155816/211799603-893245b0-eafb-4670-a96c-ab25f2ecb3e4.png)

**Comment by arrufat** [comment]
From the documentation: [`dlib::toMat`](http://dlib.net/dlib/opencv/to_open_cv_abstract.h.html#toMat) expects an object that implements the interface defined in `dlib/image_processing/generic_image.h` or a `dlib::matrix` object which uses a row_major_layout.

Here you are using it with an array of images, just loop over each image in that array and apply `dlib::toMat` to each one of those.

**Comment by davisking** [comment]
Per the docs, http://dlib.net/imaging.html#toMat, you should `#include <dlib/opencv.h>`. But the code snippet you pasted doesn't do that.
