### ISSUE TITLE
gcc pair warnings

### ISSUE THREAD

**Issue by hramrach** [davisking/dlib#2712]
## Expected Behavior
no warning

## Current Behavior
[  132s] /home/abuild/rpmbuild/BUILD/dlib-19.24.0/dlib/gui_widgets/../image_transforms/../statistics/lda.h: In function ‘std::pair<double, double> dlib::equal_error_rate(const std::vector<double>&, const std::vector<double>&)’:
[  132s] /home/abuild/rpmbuild/BUILD/dlib-19.24.0/dlib/gui_widgets/../image_transforms/../statistics/lda.h:199:5: note: parameter passing for argument of type ‘std::pair<double, double>’ when C++17 is enabled changed to match C++14 in GCC 10.1
[  132s]   199 |     )
[  132s]       |     ^

there is a lot of these drowning reports of actual problems

## Steps to Reproduce
build dlib

* **Version**: 19.24.0
* **Where did you get dlib**: https://files.pythonhosted.org/packages/source/d/dlib/dlib-19.24.0.tar.gz
* **Platform**: Preparing to boot Linux version 6.1.7-1-default (geeko@buildhost) (gcc (SUSE Linux) 12.2.1 20221020 [revision 0aaef83351473e8f4eb774f8f999bbe87a4866d7], GNU ld (GNU Binutils; openSUSE Tumbleweed) 2.39.0.20220810-1)  SMP Wed Jan 18 11:12:34 UTC 2023 (872045c)
* **Compiler**: GCC 12.2.1

**Comment by davisking** [comment]
PRs are welcome :)

**Comment by CharlesChen888** [comment]
Maybe this is helpful: https://stackoverflow.com/questions/77729813/parameter-passing-for-argument-when-c17-is-enabled-changed-to-match-c14
