### ISSUE TITLE
How to sort dlib.rectangle elements?

### ISSUE THREAD

**Issue by seongyonglim** [davisking/dlib#2713]
I'm trying to save faces in file from left to right.

if the dlib.rectangles like this : rectangles[[(115, 56) (223, 163)], [(330, 80) (438, 187)], [(225, 96) (315, 186)]]
I would like to sort it like : rectangles[[(115, 56) (223, 163)], [(225, 96) (315, 186)], [(330, 80) (438, 187)]]

Is there any way to do this?

**Comment by arrufat** [comment]
That's not a dlib-related question. It's a sorting question with a custom comparator. Try typing that on a search engine :)

**Comment by seongyonglim** [comment]
You were right. Thankyou!
