### ISSUE TITLE
ImportError: libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by ArtyomVancyan** [davisking/dlib#2724]
## Expected Behavior
I was trying to import the `dlib` after installation and got `ImportError`

## Current Behavior
The full stderr looks following:
```text
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import dlib
  File "/home/artyom/anaconda3/envs/machine-learning/lib/python3.6/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: /home/artyom/anaconda3/envs/machine-learning/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/artyom/anaconda3/envs/machine-learning/lib/python3.6/site-packages/_dlib_pybind11.cpython-36m-x86_64-linux-gnu.so)
```

## Steps to Reproduce
I am using conda environment with version 3.6 of Python.
### 1. Install dlib using pip
```bash
python3 -m pip install dlib
```
### 2. import the dlib
```python
import dlib
```

* **Version**: 19.24.0
* **Where did you get dlib**: installed using `pip`
* **Platform**: No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	jammy
* **Compiler**: c++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by handicraftsmanthk** [comment]
I have meet the same problem. dlib version: 19.24.2

**Comment by BirenMer** [comment]
We can manually replace the files temporary unitl this issue get's solved by dlib
Start with    
`sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test`   
`sudo apt install -y g++-11`
After this enter command    
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`  
This  will display all the string in the link|so file
If we see our version i.e. **GLIBCXX_3.4.29**  
Then we can go to the path /usr/lib/x86_64-linux-gnu/  using command    
`cd /usr/lib/x86_64-linux-gnu/`    
We can now open the folder usign the command     
`xdg-open .`
Once the UI pops up find the file `libstdc++.so.6` using search   
In my case I got two files    
1. libstdc++.so.6   
2. libstdc++.so.6.0.32   
I copied them both to the path `/anaconda3/envs/my_eny/lib` and the files were replaced and working fine    
Again to open the folder I used `cd` follwed by `xdg-open .`
