### ISSUE TITLE
Would it be ok to add bgr_alpha_pixel?

### ISSUE THREAD

**Issue by grisevg** [davisking/dlib#273]
This is what iOS camera gives out. 
Would it be ok if I add it to dlib?

**Comment by davisking** [comment]
Sure, that's fine.

**Comment by grisevg** [comment]
@davisking fhog's  `pyramid_down` wouldn't work on a pixel type with alpha though, correct?
```
COMPILE_TIME_ASSERT( pixel_traits<in_pixel_type>::has_alpha == false );
```
So it image would need converting anyway

**Comment by davisking** [comment]
Right

**Comment by grisevg** [comment]
Is there a reason for that? To simplify image algorithms?

**Comment by davisking** [comment]
It's just sort of bizarre to extract HOG features from an image with an
alpha channel.  I'm not sure what you would even want that to mean.  So the
API forces users to commit to a normal image without any kind of
transparency layer.

**Comment by grisevg** [comment]
From what I've seen in the code, it will work with alpha types just fine through their `pixel_traits`, just ignoring the alpha. 
But I agree that it's silly to use those types, since the algorithm is specifically designed to work on grayscale alphaless image data. Shouldn't it also refuse to accept  non-grayscale images then (right now it doesn't care cause it uses intensity of a pixel trait)?
And converting BGRA/RGBA image to `unsigned char` alphaless grayscale should be a very cheap operation because it's very cache friendly and vectorizable, right?

If I understand it right, converting the whole image first by just discarding alpha might be even faster, because `get_pixel_intensity` does a lot of stuff?

**Comment by davisking** [comment]
HOG does something with RGB images beyond convert them to grayscale.  Also,
when you assign an alpha pixel to a non-alpha pixel it does alpha
blending.  So it's not that the alpha gets ignored.  And you probably don't
want to have alpha blending happening when HOG is running.  Or at least,
the user should decide explicitly that that makes sense for them (it
probably doesn't), but the API certainly shouldn't it automatically.

**Comment by grisevg** [comment]
Right, and no matter what, iOS camera will always return full alpha for each pixel (silly Apple, right?) so no point doing alpha blending, when you can just discard it.

Wha are the benefits of passing RGB images to HOG? All examples I've seen use `unsigned char` grayscale format.

What are usages of alpha images in dlib? They don't make much sense for object detection.

**Comment by davisking** [comment]
RGB has little effect on HOG.  In some cases it improves the results, but
not a lot.

I don't use alpha for any object detection things.  Alpha is only for GUI
or other visual presentation style stuff.  Not for machine vision.

**Comment by grisevg** [comment]
Thank you very much for clarifying all this, I really appreciate this. 
Now I see that implementing `bgr_alpha_pixel` would be a very silly thing, that would do more harm than good.
