### ISSUE TITLE
I want to know how to support unicode character in box label in imglab. Could you give me some hints. Thanks!

### ISSUE THREAD

**Issue by newforrestgump001** [davisking/dlib#2732]
I want to know how to support unicode character(for example:标签) in box label in imglab. Could you give me some hints. Thanks!

**Comment by arrufat** [comment]
You'll have to edit the source code and load a BDF font that support those characters instead, such as [GNU Unifont](https://en.wikipedia.org/wiki/GNU_Unifont).

I've done something similar for a custom GUI app I made with dlib some time ago.

Maybe we could add an optional `--font` option that allows to pass a custom font.

I might do it later if that's something that would be merged.

**Comment by arrufat** [comment]
Could you try https://github.com/davisking/dlib/pull/2733?
