### ISSUE TITLE
dlib’s find_min_global function creating SIGSEGV error

### ISSUE THREAD

**Issue by PerformanceGenetics** [davisking/dlib#2738]
We have created a custom training using the find_min_global function to search for the best parameters for an image landmarking program we have written.

We have run the python program in a pipeline on GCP with the following parameters

machine_type : n1-highcpu-64
max_func_calls: 100
params {"tree_depth": [2, 8, true], "nu": [0.001, 0.2, false], "cascade_depth": [6, 20, true], "feature_pool_size": [400, 1200, true], "num_test_splits": [20, 150, true], "oversampling_amount": [1, 50, true], "oversampling_translation_jitter": [0.0, 0.5, false], "feature_pool_region_padding": [-0.2, 0.2, false], "lambda_param": [0.01, 0.99, false]}

## Expected Behavior
The code executes as it should, running through the iterations and training. It returns the saved predictor to file temp.dat and the training and testing error values...except it creates an error on one iteration (see below)

## Current Behavior
We have run the code twice three times, and it gets through the iterations until it reaches the following parameters

shape_predictor_training_options(be_verbose=1, cascade_depth=7, tree_depth=3, num_trees_per_cascade_level=500, nu=0.0352574, oversampling_amount=1, oversampling_translation_jitter=0.492069, feature_pool_size=1168, lambda_param=0.909473, num_test_splits=143, feature_pool_region_padding=0.0857562, random_seed=, num_threads=64, landmark_relative_padding_mode=1)

This produces : Fatal Python error: Segmentation fault. The replica workerpool0-0 exited with a non-zero status of 139(SIGSEGV)

Every time we have run the code it has produced the correct output (getting through 20 or so iterations) and then it fails on this one parameter setting.

## Steps to Reproduce
I have outlined the steps that we took to get to the issue above.

* **Version**: v19.24
* **Where did you get dlib**: this Github
* **Platform**: Google Clould Platform. Vertex AI pipeline  n1-highcpu-64.
* **Compiler**: python 3.9

**Comment by davisking** [comment]
Please post a minimal program that reproduces the error when run.

**Comment by PerformanceGenetics** [comment]
hyperparameter_tuning.py

import os
import multiprocessing
import dlib
import sys

# determine the number of processes/threads to use
procs = multiprocessing.cpu_count()

TRAIN_PATH = "train.xml"
TEST_PATH = "test.xml"
TEMP_MODEL_PATH = "temp.dat"
MAX_FUNC_CALLS = int(os.environ['MAX_FUNC_CALLS'])


def test_shape_predictor_params(treeDepth, nu, cascadeDepth, featurePoolSize, numTestSplits, oversamplingAmount,
                                oversamplingTransJitter, padding, lambdaParam):
    # grab the default options for dlib's shape predictor and then
    # set the values based on our current hyperparameter values,
    # casting to ints when appropriate
    options = dlib.shape_predictor_training_options()
    options.tree_depth = int(treeDepth)
    options.nu = nu
    options.cascade_depth = int(cascadeDepth)
    options.feature_pool_size = int(featurePoolSize)
    options.num_test_splits = int(numTestSplits)
    options.oversampling_amount = int(oversamplingAmount)
    options.oversampling_translation_jitter = oversamplingTransJitter
    options.feature_pool_region_padding = padding
    options.lambda_param = lambdaParam
    # tell dlib to be verbose when training and utilize our supplied
    # number of threads when training
    options.be_verbose = True
    options.num_threads = procs
    print("[INFO] starting training...")
    print(f"[INFO] using {procs} CPUs")
    print(options)
    sys.stdout.flush()
    # train the model using the current set of hyperparameters
    dlib.train_shape_predictor(TRAIN_PATH,
                               TEMP_MODEL_PATH, options)
    # take the newly trained shape predictor model and evaluate it on
    # both our training and testing set
    trainingError = dlib.test_shape_predictor(TRAIN_PATH,
                                              TEMP_MODEL_PATH)
    testingError = dlib.test_shape_predictor(TEST_PATH,
                                             TEMP_MODEL_PATH)
    # display the training and testing errors for the current trial
    print("[INFO] train error: {}".format(trainingError))
    print("[INFO] test error: {}".format(testingError))
    sys.stdout.flush()
    # return the error on the testing set
    return testingError


def hypertune(params: dict):
    """This function does the actual hyper tuning
    :param input parameters with
    """
    lower = [v[0] for (k, v) in params.items()]
    upper = [v[1] for (k, v) in params.items()]
    isint = [v[2] for (k, v) in params.items()]

    best_params, best_loss = dlib.find_min_global(
        test_shape_predictor_params,
        bound1=lower,
        bound2=upper,
        is_integer_variable=isint,
        num_function_calls=MAX_FUNC_CALLS)
    # display the optimal hyperparameters so we can reuse them in our
    # training script
    print("[INFO] final optimal parameters: {}".format(best_params))
    print("[INFO] final optimal error: {}".format(best_loss))

    optimal_parameters = {}
    for i, param in enumerate(params):
        optimal_parameters[param] = best_params[i]

    output_data = {
        'optimal_parameters': optimal_parameters,
        'error': best_loss
    }

    print(output_data)
    return output_data

**Comment by PerformanceGenetics** [comment]
`import os
import multiprocessing
import dlib
import sys

# determine the number of processes/threads to use
procs = multiprocessing.cpu_count()

TRAIN_PATH = "train.xml"
TEST_PATH = "test.xml"
TEMP_MODEL_PATH = "temp.dat"
MAX_FUNC_CALLS = int(os.environ['MAX_FUNC_CALLS'])


def test_shape_predictor_params(treeDepth, nu, cascadeDepth, featurePoolSize, numTestSplits, oversamplingAmount,
                                oversamplingTransJitter, padding, lambdaParam):
    # grab the default options for dlib's shape predictor and then
    # set the values based on our current hyperparameter values,
    # casting to ints when appropriate
    options = dlib.shape_predictor_training_options()
    options.tree_depth = int(treeDepth)
    options.nu = nu
    options.cascade_depth = int(cascadeDepth)
    options.feature_pool_size = int(featurePoolSize)
    options.num_test_splits = int(numTestSplits)
    options.oversampling_amount = int(oversamplingAmount)
    options.oversampling_translation_jitter = oversamplingTransJitter
    options.feature_pool_region_padding = padding
    options.lambda_param = lambdaParam
    # tell dlib to be verbose when training and utilize our supplied
    # number of threads when training
    options.be_verbose = True
    options.num_threads = procs
    print("[INFO] starting training...")
    print(f"[INFO] using {procs} CPUs")
    print(options)
    sys.stdout.flush()
    # train the model using the current set of hyperparameters
    dlib.train_shape_predictor(TRAIN_PATH,
                               TEMP_MODEL_PATH, options)
    # take the newly trained shape predictor model and evaluate it on
    # both our training and testing set
    trainingError = dlib.test_shape_predictor(TRAIN_PATH,
                                              TEMP_MODEL_PATH)
    testingError = dlib.test_shape_predictor(TEST_PATH,
                                             TEMP_MODEL_PATH)
    # display the training and testing errors for the current trial
    print("[INFO] train error: {}".format(trainingError))
    print("[INFO] test error: {}".format(testingError))
    sys.stdout.flush()
    # return the error on the testing set
    return testingError


def hypertune(params: dict):
    """This function does the actual hyper tuning
    :param input parameters with
    """
    lower = [v[0] for (k, v) in params.items()]
    upper = [v[1] for (k, v) in params.items()]
    isint = [v[2] for (k, v) in params.items()]

    best_params, best_loss = dlib.find_min_global(
        test_shape_predictor_params,
        bound1=lower,
        bound2=upper,
        is_integer_variable=isint,
        num_function_calls=MAX_FUNC_CALLS)
    # display the optimal hyperparameters so we can reuse them in our
    # training script
    print("[INFO] final optimal parameters: {}".format(best_params))
    print("[INFO] final optimal error: {}".format(best_loss))

    optimal_parameters = {}
    for i, param in enumerate(params):
        optimal_parameters[param] = best_params[i]

    output_data = {
        'optimal_parameters': optimal_parameters,
        'error': best_loss
    }

    print(output_data)
    return output_data`

**Comment by PerformanceGenetics** [comment]
**Requirements.txt**

dlib==19.24.0
google-cloud-bigquery==2.34.4
google-cloud-storage==1.44.0
google-cloud-secret-manager==2.12.6
google-cloud-firestore==2.10.0
db-dtypes==1.0.4
gcsfs==2022.5.0
opencv-python==4.5.5.64
numpy==1.23.4
flask==2.2.2
mailjet_rest==1.3.4
gunicorn==20.1.0

**Comment by PerformanceGenetics** [comment]
**Vertex_Parameter_Tuning.py**

import os
import sys
import json
import logging
import datetime

import gcsfs
import pandas as pd
from google.cloud import storage
from google.cloud import firestore
from simple_ml_morph.preprocessing import preprocess

from hyperparameter_tuning import hypertune

if os.environ.get('DEV', ''):
    gcs_fs = gcsfs.GCSFileSystem()
else:
    gcs_fs = gcsfs.GCSFileSystem(token='cloud')

logging.basicConfig(level=logging.INFO, stream=sys.stdout)


def download_data(images: list[dict], output_folder: str):
    if not os.path.exists(output_folder):
        os.mkdir(output_folder)
    for image_gcs_uri in images:
        filename = image_gcs_uri.split('/')[-1]
        # logging.info(f'downloading file: {image_gcs_uri}')
        local_path = os.path.join(output_folder, filename)
        try:
            with gcs_fs.open(image_gcs_uri) as gcs_f, open(local_path, 'wb') as f:
                f.write(gcs_f.read())
        except Exception as e:
            logging.error(f'exception while downloading file {image_gcs_uri} {e}')


def tuning_process(training_data_uri: str, params: dict):
    """
    :param training_data_uri: Cloud Storage full path (folder) where dataset input files are, must end with "training-*"
            so it only gets training files, i.e. "gs://bucket/path/training-*"

    """

    images_folder = 'images'
    training_filename = 'training_data_hyper.csv'

    files = gcs_fs.glob(training_data_uri)
    dataframes = []
    for filex in files:
        gcs_uri = f'gs://{filex}'
        dfx = pd.read_csv(gcs_uri)
        dataframes.append(dfx)

    df = pd.concat(dataframes, axis=0, ignore_index=True)

    images = df['image_gcs_uri'].tolist()
    df['image_gcs_uri'] = df['image_gcs_uri'].apply(lambda image: image.split('/')[-1])
    df.to_csv(training_filename, index=False)

    download_data(images, images_folder)
    preprocess(images_folder, csv_file=training_filename)

    output_data = hypertune(params)
    return output_data


def run_tuning(params: dict):
    logging.info('starting tuning job')
    print('starting tuning job')
    print(f'using input parameters {params}')
    logging.info(f"using input parameters {params}")
    training_data_uri = os.environ["AIP_TRAINING_DATA_URI"]
    # test_data_uri = os.environ["AIP_TEST_DATA_URI"]
    model_directory = os.environ["AIP_MODEL_DIR"]
    gcp_project = os.environ["CLOUD_ML_PROJECT_ID"]
    parent_gcp_project = 'velox-horse1'
    #
    print(f'training_data_uri: {training_data_uri}')
    print(f'model_directory: {model_directory}')

    doc_data = tuning_process(training_data_uri, params)

    db = firestore.Client(project=parent_gcp_project)
    dt_now = datetime.datetime.utcnow()
    doc_id = dt_now.strftime('%Y%M%d_%H%M%S')
    doc_ref = db.collection('morph_landmarks_input_parameters').document(doc_id)

    doc_data['datetime_created'] = datetime.datetime.utcnow()
    print(f'uploading data to Firestore {doc_data}')
    doc_ref.set(doc_data)

    print('job is completed')


if __name__ == '__main__':

    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--params', dest='params', type=str, help='Input parameters as a JSON text')
    args = parser.parse_args()
    params_str = args.params
    try:
        params = json.loads(params_str)
    except ValueError as e:
        logging.error(f"couldn't decode a params string: {params_str}, got exception {e}")
        sys.exit(1)
    run_tuning(params)

**Comment by PerformanceGenetics** [comment]
**Morph_Parameters_Tuning_Pipeline**

```
import json

import google.cloud.aiplatform as aip
from google_cloud_pipeline_components import aiplatform as gcc_aip
from kfp.v2 import dsl
from kfp.v2 import compiler
from kfp.v2.dsl import component
from kfp.v2.dsl import (
    Input,
    Artifact,
)


@component(
    base_image='python:3.9',
    packages_to_install=['google-cloud-bigquery', 'pandas', 'pyarrow', 'db-dtypes', 'google-cloud-storage', 'fsspec',
                         'gcsfs']
)
def get_dataset_data(gcp_project: str, pipeline_root: str) -> str:
    import json
    import datetime

    import pandas as pd
    from google.cloud import bigquery

    def format_landmarks(calculated_data):
        landmarks = calculated_data['edited_landmarks']
        landmarks = sorted(landmarks, key=lambda x: x['id'])
        landmarks_lst = []
        for landmark in landmarks:
            land_x = landmark['x']
            land_y = landmark['y']
            landmarks_lst.append(str(land_x))
            landmarks_lst.append(str(land_y))
        landmarks_fmt = ",".join(landmarks_lst)
        landmarks_no = len(landmarks_lst)
        if landmarks_no != 40:
            print(landmarks_no)
        return pd.Series(landmarks_lst)

    bq = bigquery.Client(project=gcp_project)
    df = bq.query(
        "SELECT image, calculated_data FROM `velox-horse1.velox_webapp_db.image_measurement` WHERE calculated_data IS NOT NULL").to_dataframe()
    df['image'] = df['image'].apply(lambda image: json.loads(image))
    df['calculated_data'] = df['calculated_data'].apply(lambda data: json.loads(data))
    df['landmarks'] = df['calculated_data'].apply(lambda x: x['edited_landmarks'])
    df['image_filename'] = df['image'].apply(lambda image: image['filename'])
    df['image_gcs_path'] = df['image'].apply(lambda image: f'{image["path"]}')
    df['image_gcs_uri'] = df['image'].apply(lambda image: f'gs://{image["bucket"]}/{image["path"]}')

    dfx = df['calculated_data'].apply(format_landmarks)
    res_df = pd.concat([df, dfx], axis=1, join='inner')
    columns = ['image_gcs_uri'] + list(range(0, 40))
    ts = datetime.datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    gcs_path = f'{pipeline_root}/dataset_input/{ts}.csv'
    dataset_input_file_path = f'gs://{gcs_path}'
    res_df[columns].to_csv(dataset_input_file_path, index=False)
    return dataset_input_file_path


@component(
    base_image='python:3.9',
    packages_to_install=['google-cloud-aiplatform']
)
def run_custom_job(display_name: str, container_uri: str, staging_bucket: str, params: str, max_func_calls: int,
                   dataset: Input[Artifact]
                   ):
    from google.cloud.aiplatform import CustomContainerTrainingJob, TabularDataset

    dataset_id = dataset.metadata['resourceName']
    ds = TabularDataset(dataset_id)

    custom_job = CustomContainerTrainingJob(
        display_name=display_name,
        container_uri=container_uri,
        staging_bucket=staging_bucket,
        command=['python', 'vertex_parameter_tuning.py']
    )

    custom_job.run(
        dataset=ds,
        service_account='velox-webapp@velox-horse1.iam.gserviceaccount.com',
        training_fraction_split=1.0,
        replica_count=1,
        machine_type='n1-highcpu-64',
        args=[f"--params={params}"],
        environment_variables={'MAX_FUNC_CALLS': str(max_func_calls)}
    )


@dsl.pipeline()
def pipeline(
        gcp_project: str,
        pipeline_root: str,
        pipeline_name: str,
        container_uri: str,
        custom_training_bucket: str,
        max_func_calls: int,
        params: str,
):
    dataset_file_op = get_dataset_data(gcp_project, pipeline_root)

    tabular_dataset_create_op = gcc_aip.TabularDatasetCreateOp(
        project=gcp_project,
        display_name=pipeline_name,
        gcs_source=dataset_file_op.output,
    )

    run_custom_job(display_name, container_uri, custom_training_bucket, params, max_func_calls,
                   tabular_dataset_create_op.outputs['dataset'])


def compile_upload(pipeline_export_filepath: str):
    from google.cloud import storage
    compiler.Compiler().compile(pipeline_func=pipeline,
                                pipeline_name=display_name,
                                package_path=pipeline_export_filepath)
    gcs_bucket = 'velox-vertex-ai'
    gcs_path = 'compiled_pipelines'
    blob_path = f'{gcs_path}/{pipeline_export_filepath}'
    gcs = storage.Client(project=gcp_project)
    bucket = gcs.bucket(gcs_bucket)
    blob = bucket.blob(blob_path)
    blob.upload_from_filename(pipeline_export_filepath)


def run(pipeline_export_filepath: str, display_name: str, gcp_project: str, custom_training_bucket: str,
        pipeline_bucket: str, max_func_calls: int, params: dict):
    pipeline_root = f"{pipeline_bucket}/pipeline_root/{display_name}"

    compiler.Compiler().compile(pipeline_func=pipeline,
                                pipeline_name=display_name,
                                package_path=pipeline_export_filepath)

    params_json = json.dumps(params)

    pipeline_params = {
        'gcp_project': gcp_project,
        'pipeline_root': pipeline_root,
        'pipeline_name': display_name,
        'container_uri': 'gcr.io/velox-horse1/morph-landmarks',
        'custom_training_bucket': custom_training_bucket,
        'max_func_calls': max_func_calls,
        'params': params_json
    }

    job = aip.PipelineJob(
        display_name=display_name,
        template_path=pipeline_export_filepath,
        pipeline_root=f'gs://{pipeline_root}',
        project=gcp_project,
        parameter_values=pipeline_params,
        enable_caching=False
    )

    job.submit()


if __name__ == '__main__':
    display_name = 'morph-landmarks-parameters-tuning'
    custom_training_bucket = 'velox-vertex-ai-custom-training'
    pipeline_bucket = 'velox-vertex-ai'
    gcp_project = 'velox-horse1'
    pipeline_export_filepath = f'{display_name}.json'

    params = dict([
        ("tree_depth", (2, 8, True)),
        ("nu", (0.001, 0.2, False)),
        ("cascade_depth", (6, 20, True)),
        ("feature_pool_size", (400, 1200, True)),
        ("num_test_splits", (20, 150, True)),
        ("oversampling_amount", (1, 50, True)),
        ("oversampling_translation_jitter", (0.0, 0.5, False)),
        ("feature_pool_region_padding", (-0.2, 0.2, False)),
        ("lambda_param", (0.01, 0.99, False))
    ])
    max_func_calls = 100
    # compile_upload(pipeline_export_filepath)
    run(pipeline_export_filepath, display_name, gcp_project, custom_training_bucket, pipeline_bucket, max_func_calls,
        params)
```

**Comment by davisking** [comment]
Ha ok, I mean, can you give something that I can run on my laptop that reproduces the problem?  :)

**Comment by PerformanceGenetics** [comment]
I have sent you the code, etc. I should have also mentioned that the script is running inside a Docker container on the 64 CPUs machine

**Comment by davisking** [comment]
I'm running this now.  Looks like it's going to run for many hours before it gets to the problem.  Is there a fast way to make it happen?

**Comment by davisking** [comment]
As an aside, the training and test data looks really wrong.  Like 
![image](https://user-images.githubusercontent.com/6259399/224567547-badadde8-5157-4426-abaa-9c264fffad38.png)

The keypoints don't appear to be on anything.  It looks like some program was run that transformed the points somehow and messed them all up.

**Comment by PerformanceGenetics** [comment]
Hi

It looks like the image measurements are inverted (eg 0 should be over the eye of the horse). Zdenko, is there a reason for this ?

Byron Rogers
Performance Genetics LLC
+1 859 285 0431


On Mar 12, 2023, at 3:17 PM, Davis E. King ***@***.***> wrote:

﻿

As an aside, the training and test data looks really wrong. Like
[image]<https://user-images.githubusercontent.com/6259399/224567547-badadde8-5157-4426-abaa-9c264fffad38.png>

The keypoints don't appear to be on anything. It looks like some program was run that transformed the points somehow and messed them all up.

**Comment by davisking** [comment]
So far this hasn't reproduced for me.  I let it run for about 10 hours and it appeared to be working.

**Comment by PerformanceGenetics** [comment]
We did actually manage to get it to produce the optimal parameters and have the model train with those parameters

<img width="279" alt="Screenshot 2023-03-31 at 10 24 00 AM" src="https://user-images.githubusercontent.com/6619599/229147446-e3c46a6b-9ebb-46ce-9ce1-659188a64999.png">
