### ISSUE TITLE
[Bug]: error when building example programs for dlib (ffmpeg)

### ISSUE THREAD

**Issue by rossfg** [davisking/dlib#2752]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64), Linux (aarch64)

### dlib version

git head 

### Compiler

gcc 11.3

### Expected Behavior

expected all examples to build:
get to around 95% when encountering ffmpeg* programs and then errors out on build.

### Current Behavior

while building the examples for dlib

get the following errors when attempting the new ffmpeg* example programs.

using ubunutu 22.04 with ffmpeg 4.4.2

cat dlib_error

In file included from /home/rfg/w/dlib/dlib/../dlib/media.h:13,
                 from /home/rfg/w/dlib/examples/ffmpeg_webcam_face_pose_ex.cpp:35:
/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h: In member function ‘bool dlib::ffmpeg::demuxer::open(const dlib::ffmpeg::demuxer::args&)’:
/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h:657:73: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
  657 | AVInputFormat* input_format = st.args_.input_format.empty() ? nullptr : av_find_input_format(st.args_.input_format.c_str());
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |
      |                                                             const AVInputFormat*

/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h: In lambda function:
/home/rfg/w/dlib/dlib/../dlib/media/ffmpeg_demuxer.h:695:100: error: invalid conversion from ‘AVCodec**’ to ‘const AVCodec**’ [-fpermissive]
  695 | v_find_best_stream(st.pFormatCtx.get(), media_type, -1, -1, &pCodec, 0);
      |                                                             ^~~~~~~
      |                                                             |
      |                                                             AVCodec**

### Steps to Reproduce

build example programs from dlib/examples

cd dlib/examples; mkdir build; cd build; cmake ..; cmake -build .

**Comment by pfeatherstone** [comment]
#2746 should fix this
