### ISSUE TITLE
incorrect detection of trained model via train_shape_predictor

### ISSUE THREAD

**Issue by avisangray** [davisking/dlib#278]
![capture](https://cloud.githubusercontent.com/assets/16693355/19218205/b516076e-8e11-11e6-86e7-cb5e5526258f.PNG)

left is marking shown my imglab tool  and right is detection via face_landmark_detection_ex. marked 80+ images. 
there is some issue which i'm unable to resolve with training. i'm training the face on the rs.10 bill but detection is highly irregular. i have trained aflw dataset before and road signs they seem to go excellent. but this one isn't. i changed all the parameters and even oversample to 12000 but still same result. what could be the issue?

**Comment by e-fominov** [comment]
First of all, this is not a bug of Dlib, but a question on how to use it. Lets go to stackoverflow and we will solve it
Also give us this info:
1. Where is face bounding box on the right sample?
2. Show us all training params - both for object detector and for shape predictor and also training results output
3. You are talking about one sample. Do you have any statistics? All samples do not work? Event samples used for training?

Please do not answer here - close an issue and goto http://stackoverflow.com/questions/tagged/dlib
