### ISSUE TITLE
Add PSNR metric

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2788]
### Main idea

It would be great if we added the PSNR metric to the image utilities.

**Comment by pfeatherstone** [comment]
Maybe we could also add Structural Similarity (SSIM)

**Comment by arrufat** [comment]
I was also thinking about this the other day, I've written it several times, but never in a generic reusable way.

**Comment by pfeatherstone** [comment]
SSIM also makes for a good loss function
