### ISSUE TITLE
setup.py broken (readme.txt renamed)

### ISSUE THREAD

**Issue by traits** [davisking/dlib#279]
Traceback (most recent call last):
  File "setup.py", line 608, in <module>
    long_description=readme('README.txt'),
  File "setup.py", line 349, in readme
    return open(os.path.join(script_dir, fname)).read()
FileNotFoundError: [Errno 2] No such file or directory: 'v:\\libs\\src\\dlib\\README.txt'
v:\libs\scripts>

**Comment by davisking** [comment]
Thanks, just fixed it.
