### ISSUE TITLE
shape_predictor.h missing parallel_for_extension.h include

### ISSUE THREAD

**Issue by semeyerz** [davisking/dlib#280]
#126 from @e-fominov introduced threaded computation for shape prediction.

Since then the build of my project using dlib fails with:
`include/dlib/image_processing/shape_predictor.h:805:13: error: ‘thread_pool’ has not been declared`

adding parallel_for_extension.h include to shape_predictor fixes this.

**Comment by davisking** [comment]
Thanks for reporting this.  It should be fixed now.
