### ISSUE TITLE
[Bug]: MMOD Face detctor is running forever on not detecting a face object 

### ISSUE THREAD

**Issue by chandraOloid** [davisking/dlib#2807]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24.99

### Compiler

GCC9

### Expected Behavior

return 0 detected faces

### Current Behavior

runs forever

Killed PID 1904

### Steps to Reproduce
On Ubuntu 20.04, use this stand-alone code -> [Link](https://drive.google.com/file/d/1w9gpz04DcjZm2o07KJHCwgLB_H1FPnAX/view?usp=share_link)
Use this file as test.jpg with the standard example dnn_mmod_face_detection_ex.cpp

![test](https://github.com/davisking/dlib/assets/57661133/1706985c-79aa-4af6-87eb-30bb96dab57b)

### Anything else?

WITH GPU on linux ubuntu20.04 x86_64 using CUDA python, We get this output

Processing file: test.jpg
Number of faces detected: 1
Detection 0: Left: 814 Top: 520 Right: 1166 Bottom: 872 Confidence: 1.019325613975525

WITHOUT GPU on windows x86_64 using cpu python, we get this output, stuck on processing for more than 1 min and windows m/c freezes.

Processing file: test.jpg

Seems some issue when the cnn is run on cpu. Would be great to fix the same.

**Comment by davisking** [comment]
Sounds like your computer is just running out of ram and starting to swap to disk.  And maybe it's not built with compiler optimizations on or with the a fast BLAS linked in.  In any case, the DNN tooling is meant to be used with a GPU.  It's going to be real slow on a CPU.

**Comment by chandraOloid** [comment]
I can confirm that mmod_human_face_detector works on NVIDIA GPU based computer. Just on a cpu based computer, it is taking infinitely longer on certain images. Again most images with frontal face work fine but on some edge case images this is causing an issue. 

If there is a way to debug this, like tracing the header files or looking into the source on where it gets stuck, this will be super useful. We can work on it under your supervision as a **bug fix** and patch it up in the next week. 

We tried threads with timeout after say N s (N=10s say). On timeout, a **pthread_kill** is called but this crashes the program. Seems like CNN does not like to be killed in the middle. 

Any other suggestions to fix/workaround this would be greatly appreciated.
