### ISSUE TITLE
error when build dlib on windows

### ISSUE THREAD

**Issue by ZhaoWangFu** [davisking/dlib#281]
I cloned the newest dlib from github and use CMake3.5.0 to biuld it on windows7 64bit.
And i want to use dlib in a Qt project.
And What i need is the face landmark detection function in Dlib.

Here is My local environment:
**PS D:\dlib-master\dlib_build> gcc -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.9.3/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-4.9.3/configure --build=x86_64-pc-linux-gnu --host=mingw32 
--prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 
--enable-languages=c,c++,objc,obj-c++,fortran,ada --enable-static --enable-shared 
--enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs 
--enable-libstdcxx-d**

And Then i use CMake-GUI to configure and generate the Makefile;

In CMake GUI, the generater is set to MinGW Makefiles, and use default native compilers.
The configure and generate step goes well EXCEPT not found CUDA.

Configure log info:
**The C compiler identification is GNU 4.9.3
The CXX compiler identification is GNU 4.9.3
Check for working C compiler: C:/MinGW/bin/gcc.exe
Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/bin/g++.exe
Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
C++11 activated.
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
*** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
*** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
Configuring done**

Generate log info:
**C++11 activated.
Configuring done
Generating done**

And then in powerShell, i go to my build directory( D:/dlib/dlib_build_git ), and run command **mingw32-make**

Then i got errors and the build ends.

Here is a part of log:
**......
[ 28%] Building CXX object CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.obj
[ 28%] Building CXX object CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.obj
[ 29%] Building CXX object CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.obj
[ 30%] Building CXX object CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.obj
[ 31%] Building CXX object CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.obj
[ 32%] Building CXX object CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.obj
[ 33%] Building CXX object CMakeFiles/dlib.dir/threads/async.cpp.obj
D:\dlib-master\dlib\threads\async.cpp: In function 'long unsigned int dlib::impl::default_num_threads()':
D:\dlib-master\dlib\threads\async.cpp:28:25: error: 'std::thread' has not been declared
             return std::thread::hardware_concurrency();
                         ^
CMakeFiles\dlib.dir\build.make:1037: recipe for target 'CMakeFiles/dlib.dir/threads/async.cpp.obj' failed
mingw32-make[2]: *** [CMakeFiles/dlib.dir/threads/async.cpp.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/dlib.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/dlib.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error** 

I am new to CMake and i totally  have no idea how to solve this problem, i need someone to help me out, Thank you!

**Comment by e-fominov** [comment]
Just tested on latest dlib with MinGW6.2 - all fine.
But as I see in your logs - there is usage of `std::thread` in async.cpp. And there is no `#include <thread>` inside it. I think - this should be changed

As a quick solution - you can try adding this
```
#include <thread>
```

into D:\dlib-master\dlib\threads\async.cpp at line 12

**Comment by davisking** [comment]
I just tried to compile dlib with mingw and got the same error, even after adding `#include <thread>`.  It seems like the default mingw install is missing things from the standard library.  There is a lot of stuff about this issue on google, e.g. http://stackoverflow.com/questions/21211980/mingw-error-thread-is-not-a-member-of-std.

**Comment by e-fominov** [comment]
Yes, there are several MinGW distributions. To make it work on x86 - i am using posix/sjlj installation options for MinGW i686. Default is posix/dwarf

**Comment by davisking** [comment]
Yeah, I found that after googling.  Not sure there is much we can do here.
