### ISSUE TITLE
[Bug]: can not recognition different people if they are face feature are similarity

### ISSUE THREAD

**Issue by xingyuezhiyun** [davisking/dlib#2816]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24

### Compiler

c11

### Current Behavior

can not recognition different people if they are face feature are similarity

### Steps to Reproduce

as the example code

**Comment by pfeatherstone** [comment]
Can you give more information please? A reproducible example with data is the minimum I'm afraid otherwise we can't fix anything.

**Comment by xingyuezhiyun** [comment]
> Can you give more information please? A reproducible example with data is the minimum I'm afraid otherwise we can't fix anything.

![20230625-140348](https://github.com/davisking/dlib/assets/19636480/3ba8caa6-9f40-4f80-96a2-61b1926e365b)
![20230625-140412](https://github.com/davisking/dlib/assets/19636480/9a5b392c-98c8-4915-b769-44cdd7894f4d)

How can I distinguish these two faces? Their similarity is calculated to be 0.42, while the similarity between my own photo and mine is only around 0.45.

**Comment by arrufat** [comment]
We still need additional information.
How are you running the code? Are you detecting the faces, extracting the aligned chips to be 150×150 and then running the model, or doing something else?

Also, as far as I know, this model might underperform on non-Caucasian people.

**Comment by xingyuezhiyun** [comment]
> We still need additional information. How are you running the code? Are you detecting the faces, extracting the aligned chips to be 150×150 and then running the model, or doing something else?
> 
> Also, as far as I know, this model might underperform on non-Caucasian people.

https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp
this is the example what i used, they are Chinese, how can i do ?

**Comment by xingyuezhiyun** [comment]
May I ask if anyone can help me? @arrufat

**Comment by arrufat** [comment]
> May I ask if anyone can help me? @arrufat

I'm afraid there's not much I can do... maybe you can try jitter_image with several images and see if that makes it work. But I think it's kind of expected that the model underperforms with Asian people.

**Comment by jilen** [comment]
> I'm afraid there's not much I can do... maybe you can try jitter_image with several images and see if that makes it work. But I think it's kind of expected that the model underperforms with Asian people.

I can confirm this model does not work very well with asian faces.

It says I (and another my colleague) and Daniel Wu are the same person.
[Daniel Wu](https://upload.wikimedia.org/wikipedia/commons/0/07/Daniel_Wu_by_Gage_Skidmore.jpg)

@xingyuezhiyun  You can try opencv dnn method, it performs a bitter better.

**Comment by davisking** [comment]
Yeah it's trained mostly on American celebrities so people who don't look like them don't work as well :|

**Comment by xingyuezhiyun** [comment]
There's no way. Let me try other libraries, or if there are Asian models available, please let me know. Thank you very much!

**Comment by pfeatherstone** [comment]
Maybe you could train the dlib model from scratch on http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html ?

**Comment by xingyuezhiyun** [comment]
> Maybe you could train the dlib model from scratch on http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html ? This website shows other datasets too which might be less biased: https://datagen.tech/blog/face-datasets/ If you do end up with a better model, maybe consider releasing the weights.

Thanks a lot ! i will try to train the model by myself and have to learn how to train the model from dlib website.

**Comment by xingyuezhiyun** [comment]
> Maybe you could train the dlib model from scratch on http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html ? This website shows other datasets too which might be less biased: https://datagen.tech/blog/face-datasets/ If you do end up with a better model, maybe consider releasing the weights.

I found hard to train a dlib model  to used face dataset, I haven't found a complete training example

**Comment by xingyuezhiyun** [comment]
> 

OK, Thank you ~
