### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FurqanAthar28** [davisking/dlib#2837]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19,24

### Python version

3.11

### Compiler

VS CODE

### Expected Behavior

Failed building wheel for dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

### Current Behavior

Failed building wheel for dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

### Steps to Reproduce

I'm unable to install face-recognition in python

### Anything else?

no

**Comment by arrufat** [comment]
Perfect example of https://github.com/davisking/dlib/pull/2835
