### ISSUE TITLE
Advice on improving MMOD CNN performance?

### ISSUE THREAD

**Issue by grisevg** [davisking/dlib#284]
I've managed to setup `dnn_mmod_dog_hipsterizer.cpp` on iOS and it works amazingly well.
Accuracy is through the roof, compared to HOG detector.
But speed is quite low, processing a single frame takes about a second on iPhone 7 and about 3 seconds on iPad Air 2.
I understand that's a tradeoff of CNN compared to HOG, but I was wondering if there are ways to improve performance at least a bit.

I already compile with `-O3 -DDLIB_USE_BLAS -DDLIB_USE_LAPACK -DNDEBUG`.

Could you give any advice on pushing the performance further?

UPDATE: Dropping resolution to 352x288 helped a lot. Do you think there's anything else that would help?

**Comment by davisking** [comment]
That's pretty much the extent of what makes it faster without big changes like using a different network architecture or rewriting the CPU code to use SIMD instructions or generally be faster.

**Comment by grisevg** [comment]
Yeah, that's what I thought, just wanted to get a second opinion. Huge thanks, with low resolution and limited area it runs close to real-time. When I get time I'll looks at NEON and Metal.

One thing, though I do not use CMake, I just add `source.cpp` to the project and I don't add `ENABLE_ASSERTS`, dlib's asserts still get checked.

**Comment by davisking** [comment]
Some asserts are always on, but most of them are off unless you enable them.

**Comment by grisevg** [comment]
Is there any more special flags I need to pass, to run dlib in full-speed production mode?

**Comment by davisking** [comment]
No.   There are two kinds of assert, DLIB_CASSERT and DLIB_ASSERT.
DLIB_CASSERT is always enabled no matter what.  I only put those type of
asserts in places that don't effect runtime.  Like in a place that doesn't
get called a lot.

**Comment by grisevg** [comment]
Got it. Thank you.

**Comment by AndreaPisoni** [comment]
@grisevg would you be willing to share some indications on how to make dog hipsterizer work on the iPhone? That would be awesome! Thanks!

**Comment by roscopecoltran** [comment]
Hi all,

Hope you are all well !

Is it possible to create a cross-platform boilerplate for testing examples, maybe based on qt5 for limited computational resource, embedded systems and IoT devices ?

**Why ?**
Easy to test and boostrap, so we can improve performances more easily.

**How ?**
I would suggest to use maybe a project like [gatherer](https://github.com/headupinclouds/gatherer) as a boilerplate base; it is a cross platform gpgpu opengl (es) shader pipeline framework: ogles_gpgpu + qt (UI). For anything related to vision, web camera, It would provide a demo for linux, ios, android and windows.

Also, it uses [hunter](https://github.com/ruslo/hunter), a CMake-driven cross-platform package manager for C++. Linux, Mac, Windows, iOS, Android, Raspberry Pi, and Polly, a toolcahain helper, 

One example,  dlib related, is available [[here](https://github.com/ruslo/hunter/blob/master/cmake/projects/dlib/hunter.cmake#L79-L84)], or one with opencv for ios or android ([link](https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenCV/hunter.cmake#L227-L262)).

It is really convenient for caching,  customizing some packages build. For eg, ([dlib shared](https://github.com/ruslo/hunter/tree/master/examples/dlib), [dlib static](https://github.com/ruslo/hunter/tree/master/examples/dlib-staticLib))

I saw tiny-dnn using these helpers for iOS; https://github.com/tiny-dnn/tiny-dnn/tree/master/examples/ios

**Questions:**
- Is there any simple example with MMOD, or the normal facial landmark detector for iOS/Android available ? (would be funny to test this repo with [facial landmarks for sheep](https://github.com/grisevg/TIFfacealignment) :-) )
- Are NEON instructions able to improve performances for MMOD (eg.[ dlib for arm](https://github.com/jbrjake/dlib_for_arm)) ?
- Shall I start a new issue ? I just commented as it was related to the fact to test the dog hipsterizer on iOS and to bundle a default client boilerplate for dlib cpu or mobile devices.

Hope I was clear enough about this suggestion for dlib, meanwhile I wish you all an awesome day !

Cheers,
Richard

**Comment by mrgloom** [comment]
I wonder if usage of dlib cnn face detector is feasible for mobile devices (i.e. support of computations on GPU?) Also is there any benchmark of dlib cnn detector in terms of FPS?

**Comment by davisking** [comment]
The GPU tooling in dlib uses CUDA and cuDNN.  So anywhere you can use those
things you can use the CNN+MMOD in dlib on a GPU.
