### ISSUE TITLE
[Bug]: I want to train my own model, but I don't know the format for photo training

### ISSUE THREAD

**Issue by xingyuezhiyun** [davisking/dlib#2844]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24

### Python version

3.8

### Compiler

gcc11

### Expected Behavior

Could you please send the dlib_ face_ recognition_ resnet_ model_v1.dat Can I have the training dataset for v1. dat? I want to take a look at the format of the photo and train my model, my email ywb10.8@qq.com Thank you~

### Current Behavior

training model

### Steps to Reproduce

none

**Comment by davisking** [comment]
Take a look at the example programs.  At the top of http://dlib.net/dnn_face_recognition_ex.cpp.html there are instructions for how to understand this with links to further examples that specifically answer your questions about how to train this.

**Comment by xingyuezhiyun** [comment]
> Take a look at the example programs. At the top of http://dlib.net/dnn_face_recognition_ex.cpp.html there are instructions for how to understand this with links to further examples that specifically answer your questions about how to train this.

if i want the original trained data, where i can obtain ?

**Comment by davisking** [comment]
> > Take a look at the example programs. At the top of http://dlib.net/dnn_face_recognition_ex.cpp.html there are instructions for how to understand this with links to further examples that specifically answer your questions about how to train this.
> 
> 
> 
> if i want the original trained data, where i can obtain ?

That data isn't publicly available.
