### ISSUE TITLE
dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `dlib::thread_pool_implementation::thread() [clone .constprop.81]': thread_pool_extension.cpp:(.text+0x16d7): undefined reference to `vtable for dlib::mfp_kernel_1_base_class<0ul>::mp_impl_T<dlib::mfp_kernel_1_base_class<0ul>::mp_null<dlib::mfp_kernel_1_base_class<0ul>::dummy> >'[Bug]: 

### ISSUE THREAD

**Issue by lucasjinreal** [davisking/dlib#2848]
### What Operating System(s) are you seeing this problem on?

Linux (aarch64)

### dlib version

master

### Python version

3.10

### Compiler

7

### Expected Behavior

dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `dlib::thread_pool_implementation::thread() [clone .constprop.81]':
thread_pool_extension.cpp:(.text+0x16d7): undefined reference to `vtable for dlib::mfp_kernel_1_base_class<0ul>::mp_impl_T<dlib::mfp_kernel_1_base_class<0ul>::mp_null<dlib::mfp_kernel_1_base_class<0ul>::dummy> >'

### Current Behavior

dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `dlib::thread_pool_implementation::thread() [clone .constprop.81]':
thread_pool_extension.cpp:(.text+0x16d7): undefined reference to `vtable for dlib::mfp_kernel_1_base_class<0ul>::mp_impl_T<dlib::mfp_kernel_1_base_class<0ul>::mp_null<dlib::mfp_kernel_1_base_class<0ul>::dummy> >'

### Steps to Reproduce

dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `dlib::thread_pool_implementation::thread() [clone .constprop.81]':
thread_pool_extension.cpp:(.text+0x16d7): undefined reference to `vtable for dlib::mfp_kernel_1_base_class<0ul>::mp_impl_T<dlib::mfp_kernel_1_base_class<0ul>::mp_null<dlib::mfp_kernel_1_base_class<0ul>::dummy> >'

### Anything else?

dlib_build/libdlib.a(thread_pool_extension.cpp.o): In function `dlib::thread_pool_implementation::thread() [clone .constprop.81]':
thread_pool_extension.cpp:(.text+0x16d7): undefined reference to `vtable for dlib::mfp_kernel_1_base_class<0ul>::mp_impl_T<dlib::mfp_kernel_1_base_class<0ul>::mp_null<dlib::mfp_kernel_1_base_class<0ul>::dummy> >'

**Comment by jercylew** [comment]
I encountered the same error in CentOS 7, I resolve it by upgrading the gcc to 10

```
sudo yum install centos-release-scl
sudo yum install devtoolset-10-gcc*
scl enable devtoolset-10 bash
```

Now verify its version

```
which gcc
gcc --version
```

But I strongly suggest use the latest OS distribute, since CentOS 7 will retire soon
