### ISSUE TITLE
DLIB SQL return Auto increment

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#285]
Hi Its my once again.
Does executing a insert statement return the created row?
(so does move_next() work after insert or update statement?)

And if so how is it possible to access the created row.

If you cant do this its problematic. Image following situation:

TableA : id (primary index with auto increment), name(text)

Query:
INSERT INTO TableA (name) VALUES("test");

Now we created a new entry. But if you want to keep track of this entry you need the id.

So i'm asking myself if dlib supports this or if there is no way of doing that?

**Comment by davisking** [comment]
Dlib's API is just a type safe and RAII interface to sqlite's C API.  So you should refer to the sqlite documentation.  As I recall, sqlite has special query you can use to find the rowid of the most recently created row.  Conveniently, dlib provides a function, `last_insert_rowid()` to do this query.  Although, as I was saying, you should in general refer to the sqlite documentation to find out the capabilities of a sqlite database.
