### ISSUE TITLE
[Bug]: Configuration error on macOS when using non-Apple compiler

### ISSUE THREAD

**Issue by marcpaterno** [davisking/dlib#2852]
### What Operating System(s) are you seeing this problem on?

macOS (Intel)

### dlib version

19.24

### Python version

3.11.5

### Compiler

LLVM  clang++ 15.0.7

### Expected Behavior

Configuration of the build using CMake, on macOS, with a compiler other than Apple’s version of clang, should work.

### Current Behavior

The configured build fails with the error:
```
<full path of the rankin used>: error: Invalid option: '-no_warning_for_no_symbols’
```

### Steps to Reproduce

Following the CMake build instructions with the addition of specifying the clang++ to use is other than Apple’s clang:

```
cmake -DCMAKE_CXX_COMPILER=$(which clang++) -DCMAKE_C_COMPILER=$(which clang) ..
```

In my case, `$(which clang++)` yields:
```
/Users/paterno/mambaforge/envs/for-fc-cpu/bin/clang
```
which is the compiler used to build all the other C++ libraries in my Conda environment.

### Anything else?

The problem seems to be fixed by modifying `dlib/dlib/CMakeLists.txt`. The diff is:

```
❯  git diff
diff --git a/dlib/CMakeLists.txt b/dlib/CMakeLists.txt
index 8fc43ec5..83230606 100644
--- a/dlib/CMakeLists.txt
+++ b/dlib/CMakeLists.txt
@@ -136,10 +136,12 @@ endmacro()


 # Suppress superfluous randlib warnings about libdlib.a having no symbols on MacOSX.
-if (APPLE)
+if (CMAKE_C_COMPILER_ID STREQUAL "AppleClang")
    set(CMAKE_C_ARCHIVE_CREATE   "<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>")
-   set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>")
    set(CMAKE_C_ARCHIVE_FINISH   "<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>")
+endif()
+if (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
+   set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>")
    set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>")
 endif()
```

If it is helpful, I would be happy to supply a pull request.

**Comment by davisking** [comment]
Yeah, totally send me a pull request with this :)
