### ISSUE TITLE
[Bug]: Test Project Build Paths Too Long - Windows

### ISSUE THREAD

**Issue by corymalon** [davisking/dlib#2853]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.2

### Python version

3.9.10

### Compiler

MSVC 19.37.32822.0

### Expected Behavior

I am running Windows 11 Enterprise 22H2. After completing the pre-requisite steps of installing NVIDIA CUDA and CUDNN, along with CMAKE, and VS Build Tools I expected that installing dlib via pip would build with CUDA support.

### Current Behavior

Currently the install fails to build the test project. Errors appear to be around creating log files in the temp directories. The paths that fail exceed Microsoft's 260 character limit. Attempting to force long paths in Windows 11 via policy is broken and a known issue. Is it possible to reduce path lengths for the test builds?

* FileTracker : error FTK1011: could not create the new file tracking log file:
[log.txt](https://github.com/davisking/dlib/files/12566960/log.txt)
![Screenshot 2023-09-09 180849](https://github.com/davisking/dlib/assets/96668487/c4ba1629-e186-4d9b-bfe5-cddb506cbd48)

### Steps to Reproduce

pip install dlib --verbose --no-cache-dir

**Comment by davisking** [comment]
It's not super clear to me how to get pip and/or cmake to locate files in different folders.  If you figure something out send us a PR though :)

**Comment by corymalon** [comment]
Your comment gave me some much needed hints. It appears that cmake/pip use the Windows environment variables for TEMP and TMP which default as shown below.

![DefaultTemp](https://github.com/davisking/dlib/assets/96668487/ece36b82-5aad-40e1-a8e2-c4ff5a3c861f)

I was able to successfully build by changing my TEMP/TMP paths to a location closer to the root. While this may be considered a workaround, it is acceptable for my purposes.
![RevisedTemp](https://github.com/davisking/dlib/assets/96668487/d1cc9e91-472e-4ce6-bb3a-8d202e9ae092)

I believe this is likely directly related to cmake and not pip. 

Another possible solution for anyone looking for alternatives if they do not have permissions to modify environment variables may be to force this in the CMakeLists.txt file, however I have not tested this, and it would not be a global solution that is platform independent.

```
set(ENV{TEMP} "C:/Temp")
set(ENV{TMP} "C:/Temp")
```

To note, any alternate location will need to be a path that the user has full RW access to.

As I do not posses the necessary skills to dive further into this for a more permanent fix, I am submitting this work around as the solution and closing the bug.

**Comment by davisking** [comment]
Thanks for the follow up :)
