### ISSUE TITLE
[Bug]: Artifact after using rotate_image on windows10 mingw64

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#2856]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24

### Compiler

mingw64 7.3

### Expected Behavior

get a clean rotated image, without artifacts, after applying rotate_image.

### Current Behavior

I noticed that on the windows build of my program using dlib, some artifacts appear in some images after applying rotate_image. The linux version seems unaffected.
The source image is this: https://bitbucket.org/guenterneust/rotate_image_bug/src/master/t.png
and the rotated image with artifacts is this one: https://bitbucket.org/guenterneust/rotate_image_bug/src/master/tmp2.png

### Steps to Reproduce

A small program replicating the issue is here: https://bitbucket.org/guenterneust/rotate_image_bug/src/master/

**Comment by pepeverde9** [comment]
I was using an older (from spring) version of dlib on windows. After pulling the latest version, the issue disappeared.

**Comment by arrufat** [comment]
I just checked, and yes, `rotate_image` uses `interpolate_quadratic` internally, when no interpolation is specified.

https://github.com/davisking/dlib/blob/f6c58c2d21a49d84967e48ffa33e7d1c783ae671/dlib/image_transforms/interpolation.h#L521-L539

It had a small bug, which was fixed recently here: https://github.com/davisking/dlib/pull/2806
