### ISSUE TITLE
error: undefined reference to `dlib::base64::base64()'

### ISSUE THREAD

**Issue by ZhaoWangFu** [davisking/dlib#286]
First, Thank you for helping me to build dlib with mingw. [](**https://github.com/davisking/dlib/issues/281**)

And then, after dlib was build successfully, i used dlib in my project like this.
In my CMakeLists.txt:

**project(MakeTestProject)
cmake_minimum_required(VERSION 2.8)

find_package( OpenCV REQUIRED )

set(DLIB_INCLUDE_DIR "D:/dlib_master_new/dlib-master")
set(DLIB_LIB_DIR "D:/dlib_master_new/dlib-master/dlib_build_dir")

INCLUDE_DIRECTORIES(${DLIB_INCLUDE_DIR})
LINK_DIRECTORIES(${DLIB_LIB_DIR})

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${OpenCV_LIBS})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} dlib )**

And in my main.cpp, i used the face_detector like this:

```
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>
#include <dlib/image_io.h>

using namespace dlib;
using namespace std;
using namespace cv;

int main(int argc, char *argv[])
{
    //test dlib
    frontal_face_detector detector = get_frontal_face_detector();
    shape_predictor sp;
    string picPath = "D:/asmlib-opencv-master/data/visia-1.jpg";

    deserialize( "D:/QTWorkPlace/MakeTestProject/shape_predictor_68_face_landmarks.dat" ) >> sp;

    array2d<rgb_pixel> img;
    load_image(img, picPath);

    // Make the image larger so we can detect small faces.
    pyramid_up(img);

    // Now tell the face detector to give us a list of bounding boxes
    // around all the faces in the image.
    std::vector<dlib::rectangle> dets = detector(img);
    cout << "Number of faces detected: " << dets.size() << endl;
}
```

Things goes well until i run my project, I got errors:

**D:\QTWorkPlace\MakeTestProject\main.cpp:-1: error: undefined reference to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'

D:\QTWorkPlace\MakeTestProject\main.cpp:-1: error: undefined reference to `dlib::base64::base64()'

D:\QTWorkPlace\MakeTestProject\main.cpp:-1: error: CMakeFiles\MakeTestProject.dir/objects.a(main.cpp.obj): bad reloc address 0x10 in section `.text$_ZN4dlib28get_serialized_frontal_facesEv[__ZN4dlib28get_serialized_frontal_facesEv]'**

I waste lots of time on googling this problem but i just can't make things right. 

Could you please tell me how to use dlib in my projetc?
I am new to CMake but my project has to use CMake.
Thanks a lot!

**Comment by ZhaoWangFu** [comment]
Here is my directory relationship:

**PS D:\dlib_master_new\dlib-master\dlib_build_dir> tree
D:.
├─CMakeFiles
│  ├─3.5.0
│  │  ├─CompilerIdC
│  │  └─CompilerIdCXX
│  ├─CMakeTmp
│  ├─dlib.dir
│  │  ├─base64
│  │  ├─bigint
│  │  ├─bit_stream
│  │  ├─bsp
│  │  ├─data_io
│  │  ├─dir_nav
│  │  ├─dnn
│  │  ├─entropy_decoder
│  │  ├─entropy_encoder
│  │  ├─external
│  │  │  ├─libjpeg
│  │  │  ├─libpng
│  │  │  └─zlib
│  │  ├─gui_core
│  │  ├─gui_widgets
│  │  ├─image_loader
│  │  ├─image_saver
│  │  ├─linker
│  │  ├─logger
│  │  ├─md5
│  │  ├─misc_api
│  │  ├─server
│  │  ├─sockets
│  │  ├─sockstreambuf
│  │  ├─threads
│  │  ├─timer
│  │  ├─tokenizer
│  │  └─unicode
│  ├─dlib_automoc.dir
│  └─Export
│      └─lib
│          └─cmake
│              └─dlib
├─config
└─dlib
    ├─CMakeFiles
    │  ├─dlib.dir
    │  │  ├─base64
    │  │  ├─bigint
    │  │  ├─bit_stream
    │  │  ├─bsp
    │  │  ├─data_io
    │  │  ├─dir_nav
    │  │  ├─dnn
    │  │  ├─entropy_decoder
    │  │  ├─entropy_encoder
    │  │  ├─external
    │  │  │  ├─libjpeg
    │  │  │  ├─libpng
    │  │  │  └─zlib
    │  │  ├─gui_core
    │  │  ├─gui_widgets
    │  │  ├─image_loader
    │  │  ├─image_saver
    │  │  ├─linker
    │  │  ├─logger
    │  │  ├─md5
    │  │  ├─misc_api
    │  │  ├─server
    │  │  ├─sockets
    │  │  ├─sockstreambuf
    │  │  ├─threads
    │  │  ├─timer
    │  │  ├─tokenizer
    │  │  └─unicode
    │  ├─dlib_automoc.dir
    │  └─Export
    │      └─lib
    │          └─cmake
    │              └─dlib
    └─config**

**Comment by davisking** [comment]
Dlib comes with examples that are built using cmake.  Look at the example's cmake file to see how to write a CMakeLists.txt that is correct.

**Comment by ZhaoWangFu** [comment]
Sorry, here is my CMakeLists.txt file content, i forgot to add some important details in my question . And the problem still exist. 

**project(MakeTestProject)
cmake_minimum_required(VERSION 2.8)

set(CMAKE_AUTOMOC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_CXX_STANDARD 11) # C++11...
set(CMAKE_CXX_STANDARD_REQUIRED ON) #...is required...
set(CMAKE_CXX_EXTENSIONS OFF) #...without compiler extensions like gnu++11

find_package( OpenCV REQUIRED )

set(DLIB_INCLUDE_DIR "D:/dlib_master_new/dlib-master")
set(DLIB_LIB_DIR "D:/dlib_master_new/dlib-master/dlib_build_dir")

INCLUDE_DIRECTORIES(${DLIB_INCLUDE_DIR})
LINK_DIRECTORIES(${DLIB_LIB_DIR})

aux_source_directory(. SRC_LIST)
add_executable(${PROJECT_NAME} ${SRC_LIST})

TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${OpenCV_LIBS})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} dlib )**

**Comment by davisking** [comment]
That looks nothing like the CMakeLIsts.txt in the examples folder.  You should try following the instructions and then things will work better.

**Comment by ZhaoWangFu** [comment]
Ok, thanks anyway!

**Comment by anonym24** [comment]
did you solve this issue? I'm trying to use face detection on Android https://stackoverflow.com/questions/57158716/frontal-face-detector-h2358-undefined-reference-to-dlibbase64decode

my Android CmakeLists.txt:

```
# Sets the minimum version of CMake required to build the native
# library. You should either keep the default value or only pass a
# value of 3.4.0 or lower.

cmake_minimum_required(VERSION 3.4.1)

# OpenCV stuff
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)

add_library( lib_opencv SHARED IMPORTED )
set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}/libopencv_java3.so)

add_library( lib_dlib SHARED IMPORTED )
set_target_properties(lib_dlib PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}/libandroid_dlib.so)

# Creates and names a library, sets it as either STATIC
# or SHARED, and provides the relative paths to its source code.
# You can define multiple libraries, and CMake builds it for you.
# Gradle automatically packages shared libraries with your APK.

add_library( # Sets the name of the library.
        native-lib

        # Sets the library as a shared library.
        SHARED

        # Provides a relative path to your source file(s).
        # Associated headers in the same location as their source
        # file are automatically included.
        # src/main/cpp/test.cpp
        native-lib.cpp)

# Searches for a specified prebuilt library and stores the path as a
# variable. Because system libraries are included in the search path by
# default, you only need to specify the name of the public NDK library
# you want to add. CMake verifies that the library exists before
# completing its build.

find_library( # Sets the name of the path variable.
        log-lib

        # Specifies the name of the NDK library that
        # you want CMake to locate.
        log )

# Specifies libraries CMake should link to your target library. You
# can link multiple libraries, such as libraries you define in the
# build script, prebuilt third-party libraries, or system libraries.

target_link_libraries( # Specifies the target library.
        native-lib

        # OpenCV lib
        lib_opencv

        # dlib
        lib_dlib

        # Links the target library to the log library
        # included in the NDK.
        ${log-lib} )

```

**Comment by anonym24** [comment]
@davisking I don't need all examples, only code from face detection in my `native-lib.cpp` file:

```
void test()
{
    dlib::array2d<dlib::bgr_pixel> dlibImage;
    dlib::assign_image(dlibImage, cv_image<dlib::bgr_pixel>(*matOpenCV));

    frontal_face_detector detector = get_frontal_face_detector();

    std::vector<dlib::rectangle> dets = detector(dlibImage);

    LOGD("Number of faces detected: %lu", dets.size());
}
```

I don't see anything special in CmakeLists.txt from dlib/examples

So what do I miss?
