### ISSUE TITLE
[Bug]: Webcam example does not work properly with FFmpeg 6

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2865]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

master

### Compiler

GCC 13.2.1

### Expected Behavior

Run normally.

### Current Behavior

![Screenshot from 2023-09-20 10-42-05](https://github.com/davisking/dlib/assets/1671644/68085c47-e936-41e0-a08b-1d78d6ddeea1)

There's seems to be some kind of size or stride problem somewhere.
@pfeatherstone can you check if it still works on previous versions of FFmpeg? I am not sure it's a 6.0 specific thing.

### Steps to Reproduce

```bash
git clone https://github.com/davisking/dlib
cd dlib/examples
wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
bzip2 -d shape_predictor_68_face_landmarks.dat.bz2
cmake -B build -G Ninja
cmake --build build --target ffmpeg_webcam_face_pose_ex
./build/ffmpeg_webcam_face_pose_ex --height 480 --width 640
```

Relevant CMake output:
```
-- Searching for FFMPEG/LIBAV
-- Checking for modules 'libavdevice;libavfilter;libavformat;libavcodec;libswresample;libswscale;libavutil'
--   Found libavdevice, version 60.1.100
--   Found libavfilter, version 9.3.100
--   Found libavformat, version 60.3.100
--   Found libavcodec, version 60.3.100
--   Found libswresample, version 4.10.100
--   Found libswscale, version 7.1.100
--   Found libavutil, version 58.2.100
-- Found FFMPEG/LIBAV via pkg-config in `/usr/lib`
```

### Anything else?

Just ran this example to make sure it worked before a new dlib version is released.

**Comment by pfeatherstone** [comment]
Yep will check when I get to work

**Comment by pfeatherstone** [comment]
Yep. It's not a bug with the implementation details or ffmpeg version, it's the example. When reading "ffmpeg::frame" instances, we're not asking it to convert pixel format to RGB. They are coming out as YUV. The easiest thing is to use the simpler API and read directly into `array2d<rgb_pixel>`. I'll submit PR.

**Comment by pfeatherstone** [comment]
I've a PR. Let me know if that fixes it on your end. Cheers

**Comment by arrufat** [comment]
Yes, it works, thank you!

**Comment by davisking** [comment]
We can also use DLIB_CASSERT which is always activated for key functions. Like where we think it doesn't have a meaningful performance impact in any use case and would catch what's likely to be a common user error.
