### ISSUE TITLE
[Serialization] support std::chrono objects

### ISSUE THREAD

**Issue by pfeatherstone** [davisking/dlib#2868]
### Main idea

Support serialization of std::chrono time_point objects. I think it's good practice to represent timestamps using std::chrono. Everything is type safe and less error prone that using uint64_t for time since epoch in nanoseconds. I occasionally need to serialize timestamps to file and have to use the hack of storing `time_since_epoch().count()`. It would be great if dlib supported std::chrono explicitly and did so a bit more reliably, i.e. taking into account durations, representations, etc.

### Anything else?

I can have a look around other libraries to see how they do it.

**Comment by pfeatherstone** [comment]
For example, i'm serializing and deserializing a `system_clock::time_point` as follows:
```
system_clock::time_point timestamp{};
dlib::serialize(timestamp.time_since_epoch().count(), out);
uint64_t timestamp_since_epoch{0};
dlib::deserialize(timestamp_since_epoch, in);
timestamp = system_clock::time_point{system_clock::duration{timestamp_since_epoch}};
```
I'm 100% sure this will not work in general going between 2 different machines with different architectures, different operating systems and using different compilers.

**Comment by pfeatherstone** [comment]
I don't think boost supports serialization of boost::chrono objects

**Comment by pfeatherstone** [comment]
The YAS library does. I'm not convinced this is the right way to do. The serialization code should read the reps and durations, and do any conversions if necessary.

https://github.com/niXman/yas/blob/7c5ced1d940ddc6826cf537468e65ea1f592bfe4/include/yas/types/std/chrono.hpp#L50-L97

**Comment by pfeatherstone** [comment]
Cereal does this:
https://github.com/USCiLab/cereal/blob/d1fcec807b372f04e4c1041b3058e11c12853e6e/include/cereal/types/chrono.hpp#L35-L70
Maybe we should just do something like that.

**Comment by pfeatherstone** [comment]
something like this ?
```
namespace dlib
{
    template<class R, class P>
    void serialize(const std::chrono::duration<R,P>& dur, std::ostream& out)
    {
        serialize(dur.count(), out);
    }

    template<class R, class P>
    void deserialize(std::chrono::duration<R,P>& dur, std::istream& in)
    {
        R count{0};
        deserialize(count, in);
        dur = std::chrono::duration<R,P>{count};
    }

    template<class C, class D>
    void serialize(const std::chrono::time_point<C,D>& tp, std::ostream& out)
    {
        serialize(tp.time_since_epoch(), out);
    }

    template<class C, class D>
    void deserialize(std::chrono::time_point<C,D>& tp, std::istream& in)
    {
        D elapsed{};
        deserialize(elapsed, in);
        tp = std::chrono::time_point<C,D>{elapsed};
    }
}
```

**Comment by pfeatherstone** [comment]
i think we should serialize unit and clock information as well

**Comment by davisking** [comment]
> i think we should serialize unit and clock information as well

Yeah I would probably serialize the unit information at least.  Otherwise someone is invariably going to serialize some times, then change their code to some other unit, and deserialize and be confused why it's all messed up now.  And for instance, `std::chrono::system_clock` doesn't actually define a particular duration. So if someone saved the `now()` time and then loaded it with some other compiler that really ought to work, but it wouldn't without also saving the unit information so the count could be converted into the correct units.

Doesn't seem like you need to save the clock though.  Not sure how to do that in a sensible way anyway.

**Comment by davisking** [comment]
It seems like the two libraries you linked don't save the unit information.  I honestly don't get how anyone could find that useful, given how stuff like `std::chrono::system_clock::now().time_since_epoch().count()` is not in a standard unit.  Like on some systems it's nanoseconds but others it isn't.  And if you can't save time points from the clock what good is it?

**Comment by pfeatherstone** [comment]
Isn't it that some clocks think timestamp 0 starts in 1970 and others 1990 ? In which case, knowing the clock is important.

**Comment by davisking** [comment]
It was unspecified until C++20 (see https://en.cppreference.com/w/cpp/chrono/system_clock), but now it's supposed to be unix time. I'm not sure what common implementations used anything else.  In any case, I think it's fine to say that a `time_point` is not going to be portably reloadable if the clock it uses is itself not portable.  That's just on people to use well defined clocks.  Don't know what we could do about it.  Some clocks aren't even connected to calendar time or even the actual passage of time on earth.
