### ISSUE TITLE
dlib cocoapods error

### ISSUE THREAD

**Issue by odedharth** [davisking/dlib#287]
Hi,

I've tried to install dlib using its [pod](https://cocoapods.org/pods/dlib) on ios 10.
I got this error:

```
PhaseScriptExecution CMake\ PostBuild\ Rules build/dlib/Project.build/Release-iphoneos/dlib_shared.build/Script-EC3A774C23804CEA9D72B295.sh
    cd /Users/admin/Library/Caches/CocoaPods/Pods/Release/dlib/19.1-65c1e
    /bin/sh -c /Users/admin/Library/Caches/CocoaPods/Pods/Release/dlib/19.1-65c1e/build/dlib/Project.build/Release-iphoneos/dlib_shared.build/Script-EC3A774C23804CEA9D72B295.sh
echo "Creating symlinks"
Creating symlinks
/usr/local/Cellar/cmake/3.3.0/bin/cmake -E cmake_symlink_library /Users/admin/Library/Caches/CocoaPods/Pods/Release/dlib/19.1-65c1e/build/dlib/Release/libdlib.19.1.0.dylib /Users/admin/Library/Caches/CocoaPods/Pods/Release/dlib/19.1-65c1e/build/dlib/Release/libdlib.19.1.0.dylib /Users/admin/Library/Caches/CocoaPods/Pods/Release/dlib/19.1-65c1e/build/dlib/Release/libdlib.dylib
CMake Error: cmake_symlink_library: System Error: No such file or directory
make: *** [dlib_shared_buildpart_0] Error 1

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ PostBuild\ Rules build/dlib/Project.build/Release-iphoneos/dlib_shared.build/Script-EC3A774C23804CEA9D72B295.sh
(1 failure)

```
Any idea how to fix this?

**Comment by davisking** [comment]
I've never seen this pod thing before :)

I would follow the instructions here to compile: http://dlib.net/compile.html

**Comment by grisevg** [comment]
@odedharth I've spent ages trying to setup automated build for dlib on ios.
You can generate an Xcode project using CMake, but then you have to manually open it and change SDK to iOS. I tried different iOS CMake toolchains but none of them have worked.

The easiest and most reliable way to add dlib to ios app is to add `source.cpp` to Xcode source files and add dlib folder to header files search path.

**Comment by odedharth** [comment]
@grefab Thanks for the response!
I've been able to create Xcode project using CMake, but I'm not sure how to add dlib to another existing Xcode project.
Which files should I transfer? Should I change something in the build settings?

**Comment by davisking** [comment]
Did you read this page? http://dlib.net/compile.html

There is a section called "Compiling C++ Examples Without CMake" that
answers this question.

**Comment by odedharth** [comment]
@davisking Yes I read it, it's just that I'm not coming from the C++ world and it's still not very clear to me.

@grisevg I did what you suggested:
 - added the dlib folder without adding it to the target
 - added the folder containing dlib to the header search path
 - added source.cpp to the source files 

but I get this error from the source.cpp file:

`/source.cpp:11:10: '../base64/base64_kernel_1.cpp' file not found
`

Any idea why?

Thanks alot

**Comment by grisevg** [comment]
It sounds like you added it wrong.
Is the source.cpp still inside dlib folder? did you add it to `Compile Sources` in `Build Phases`?
Did you add correct folder to header search path?

We can't help you by trying to guess what you did wrong, you need to be specific.

**Comment by davisking** [comment]
I don't see how you could get that error unless you are moving files around inside the dlib folder.  **_Do not edit any files in the dlib folder in any way_**.

**Comment by odedharth** [comment]
I recorded what I'm doing - https://dl.dropboxusercontent.com/u/13317676/dlib.mov

What am I missing?

**Comment by davisking** [comment]
I haven't used XCode for years, so I don't know how to use it's GUI to
setup a project.  Maybe when you drag all/source.cpp across the screen it
makes a copy of the file in another folder (which is not what you want to
happen).  I have no idea.  In any case, the dlib forums are not the correct
place to ask questions about how to use an IDE or to ask about how to add a
.cpp file or whatever.  That has nothing to do with dlib.

**Comment by odedharth** [comment]
Ok Weird... 
Anyway @grisevg did you add dlib to xcode in the process I did?

**Comment by odedharth** [comment]
The problem was due cocoapods flag https://github.com/zweigraf/face-landmarking-ios/issues/7
