### ISSUE TITLE
[Bug]: dlib won't install because of building wheels?

### ISSUE THREAD

**Issue by reidoeshecker** [davisking/dlib#2893]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.2

### Python version

3.12

### Compiler

C++ Compiler

### Current Behavior

this is my first time using these and i don't really know how to fix this. this is my 4th time trying to install dlib but it just won't install. this is where process stops

```
Collecting dlib
  Using cached dlib-19.24.2.tar.gz (11.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml): started
  Building wheel for dlib (pyproject.toml): still running...
  Building wheel for dlib (pyproject.toml): still running...
  Building wheel for dlib (pyproject.toml): still running...
  Building wheel for dlib (pyproject.toml): still running...
  Building wheel for dlib (pyproject.toml): still running...
  Building wheel for dlib (pyproject.toml): still running...
  Building wheel for dlib (pyproject.toml): still running...
```

### Steps to Reproduce

is there any way that can solve this?

### Anything else?

i hope i can have an immediate response, this project is for our thesis due on dec. 1 :')))

**Comment by arrufat** [comment]
Could you try with python 3.11 instead?
I haven't tried with 3.12, but 3.11.6 works fine.

Pybind11 needs to be updated to 2.11 (using 2.10 now, and I can see in the [2.11 changelog](https://github.com/pybind/pybind11/releases/tag/v2.11.0) that they added some stuff for Python 3.12)

So, if you're in a hurry, the fastest way to solve your issue would be to downgrade Python.

**Comment by davisking** [comment]
What's the exact problem?  Maybe you didn't wait long enough for it to compile?  I don't see an error in the post.

**Comment by reidoeshecker** [comment]
> What's the exact problem? Maybe you didn't wait long enough for it to compile? I don't see an error in the post.

i did wait for it to compile but it just keeps getting the process cancelled by its own, but i tried installing it using command prompt and it did install, but then the dlib in my venv script folder is nowhere to be seen, however dlib can be seen in my lib folder, is that alright or there should also be a dlib in my script folder?

![Screenshot 2023-11-23 183209](https://github.com/davisking/dlib/assets/147685793/1e5d9c23-6e38-40dc-991c-1ad7ca40057a)
![Screenshot 2023-11-23 183310](https://github.com/davisking/dlib/assets/147685793/3c5917a4-e80f-4e03-9cf7-3beed9828b4e)

**Comment by davisking** [comment]
I'm still not sure what you have been trying.  For instance, the only way I know to install is to use the command prompt.  I'm not sure what the non-command-prompt way of installing would be (so whatever that is probably won't work).  I would just do `pip install dlib` on the command prompt.

**Comment by TimSC** [comment]
FYI dlib takes about 15 min to compile on my machine.
