### ISSUE TITLE
[Bug]: cuda_utils.h:164. code: 98, reason: invalid device function with the latest CUDA toolkits and cuDNN v12.3 

### ISSUE THREAD

**Issue by pvinhha** [davisking/dlib#2896]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.2

### Python version

3.8.10

### Compiler

-- Building for: Visual Studio 16 2019 -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621. -- The C compiler identification is MSVC 19.29.30147.0 -- The CXX compiler identification is MSVC 19.29.30147.0

### Expected Behavior

CUDA was enabled and expect to run on the NVIDIA RTX 4070 with CUDA driver and cuDNN version 123.1 installed.  Both compilation and installation were successfully built and completed.  dlib.DLIB_USE_CUDA = 1 on checking after the installation. Also cuda.get_num_devices() returns 1 as expected.

### Current Behavior

I'm building new version of DLIB with the latest CUDA toolkit and cuDNN version 12.3.  The build and installation were successful. 
 But at the run time when testing with the face_recognition module, it failed with the below errorcode and message:

Python38\lib\site-packages\face_recognition\api.py", line 103, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in dlib\cuda\cuda_utils.h:164. code: 98, reason: invalid device function

### Steps to Reproduce

import face_recognition
import cv2

image = cv2.imread("face_image.jpg")
rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
boxes = face_recognition.face_locations(rgb_image,
	model="cnn")
encodings = face_recognition.face_encodings(rgb_image, boxes)

### Anything else?

I need to use it with RTX4070 for high efficienccy and being synched with tthe latest drivers. Please advice the possible fixing solutions.  Thanks.

**Comment by davisking** [comment]
I'm not sure what is going wrong, but that error indicates something is wrong with your CUDA runtime as it isn't seeing your graphics card.  Try reinstalling cuda and make sure you follow the official nvidia instructions. There are a lot of hacky ways to install cuda talked about on the internet, and many of them lead to partly broken CUDA installs.  But I've found that the official instructions on nvidia's web site always (well almost always) work fine.
