### ISSUE TITLE
[Bug]: Training randomly crashes with cuda_error: invalid device function

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2905]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24

### Python version

N/A

### Compiler

GCC 12.3.0

### Expected Behavior

Not crash with GPU errors.

### Current Behavior

Randomly, while I am training a neural network, the code would crash with an error similar to this:

```
terminate called after throwing an instance of 'dlib::cuda_error'
  what():  Error while calling cudaOccupancyMaxPotentialBlockSize(&num_blocks,&num_threads,K) in file dlib/dlib/cuda/cuda_utils.h:186. code: 98, reason: invalid device function
```

The training had been running for several hours, for about 120k steps on an NVIDIA GeForce RTX 4090.
I was getting similar errors when using compute capabilities 89 (the latest one supported for that GPU) so I changed to 50 (the default in dlib) but still getting some errors.

After the training crashes, I can run it again, and it resumes from the latest synchronization file, as if nothing had happened. Maybe it's a buggy GPU?

### Steps to Reproduce

Run a training long enough (it happened also with the ImageNet trainer)

### Anything else?

I'm sorry, I know there's not enough information here to help diagnose the problem, but maybe someone has an idea about what's going on.

**Comment by davisking** [comment]
Huh, nothing has changed in a while as far as I know.  You using a new version of ubuntu or cuda or anything like that?

**Comment by arrufat** [comment]
Ah, I forgot to mention my setup:
- Arch Linux (up to date)
- CUDA 12.3.1
- CUDNN 8.9.7.29
- NVIDIA 545.29.06

Maybe that's the price to pay for being on the bleeding edge...

**Comment by davisking** [comment]
That's not in the supported platform list in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html 

My experience is nvidia is pretty serious about that and when I've tried to deviate (or seen others do so) the nvidia libraries just flake out and aren't reliable.

**Comment by arrufat** [comment]
I see, then I can't complain… I've always used dlib with this distro.
It was bound to happen at some point.
Thank you!

**Comment by davisking** [comment]
Maybe your glibc or compiler version was updated?   IDK, something is different. :shrug:

**Comment by arrufat** [comment]
Maybe, it only happens to me on that GPU, though. I have the same setup on another machine, but with a different (older) GPU and there it works perfectly, as always has.
I can be training for a few days, and everything is fine and, suddenly, it gives that error.

**Comment by davisking** [comment]
Ah, yeah that sucks. Maybe the GPU is broken.  I've totally had that happen and just like you describe.  You swap the GPU out with a new card and poof, no more failures.

**Comment by arrufat** [comment]
Yes, I'll investigate more, thank you!
