### ISSUE TITLE
[Bug]: Zero Sized Image (letterbox_image function: img_out size must be bigger than zero, but was 0x0)

### ISSUE THREAD

**Issue by carkaci1** [davisking/dlib#2910]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

https://github.com/davisking/dlib/commit/19a952c3a4d983b456d497aa888942694d98a809

### Compiler

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Expected Behavior

In the current implementation, the variable temp.first.size is expected to be equal to (image_size, image_size). However, during execution, it appears that the size is not set correctly, leading to unexpected behavior.

### Current Behavior

Line 444 `train_data.enqueue(temp);` Set the size of the temp.first to zero.

### Steps to Reproduce

Just run.

### Anything else?

As a suggestion: Move the Line 398 : `temp.first.set_size(image_size, image_size);`in a loop.

**Comment by arrufat** [comment]
Oops, my bad, I should've tested it properly. Can you check if #2911 solves the issue for you?

**Comment by carkaci1** [comment]
Yes. It works for me.
