### ISSUE TITLE
[Bug]: Pipe tests fail on latest Visual Studio

### ISSUE THREAD

**Issue by reunanen** [davisking/dlib#2926]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

d5909ed9773f89f78203ba4d8324c066b8159925

### Python version

N/A

### Compiler

Visual Studio 2022, version 17.9.2

### Expected Behavior

Tests pass on latest Visual Studio 2022.

### Current Behavior

On the latest Visual Studio 2022 (version 17.9.2), [the pipe test](https://github.com/davisking/dlib/blob/master/dlib/test/pipe.cpp) fails for Debug builds.

The reason appears to be that Microsoft seems to have added [this check](https://github.com/microsoft/STL/commit/acb342c03a2b7978b5d11481af5618ea50b3dbfe#diff-e24ffc00f5c103372fd883f6c4d31c61c95262684010e4957c2faa86cc0f48b4R596-R597) to their STL implementation:
```
"wait_until's caller must own the lock argument (N4958 [thread.condition.condvar]/17)"
```

### Steps to Reproduce

Get latest Visual Studio 2022 (version 17.9.2), build Debug tests, and execute [the pipe test](https://github.com/davisking/dlib/blob/master/dlib/test/pipe.cpp).

### Anything else?

It seems that the `std::unique_lock` object constructed with the `std::defer_lock` option in `dlib::signaler::wait_or_timeout` does not end up "owning" the mutex when calling the condition variable's `wait_until`, which appears to be something Microsoft's updated STL does not really like.

I am not sure if this is a bug in the Microsoft STL implementation (it might very well be), or something to change in dlib, but at bare minimum I need to find some workaround. If I should just `#define _CONTAINER_DEBUG_LEVEL 0` for now, then so be it – but in any case wanted to at least post this for awareness, because expecting that other dlib users may stumble upon this as well, when they update their Visual Studio to the latest versions.

Please note that the underlying code has worked just fine on previous Visual Studio versions. In addition, Release builds (which do not have this check) still work great.

For the record: It seems that Microsoft [have updated](https://github.com/microsoft/STL/issues/3969) to [N4958](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4958.pdf), which does say this for `condition_variable::wait_until` (on page 1893):
> Preconditions: `lock.owns_lock()` is `true`

So I'm guessing that's where this precondition check basically comes from.

**Comment by davisking** [comment]
Huh yeah, not sure what I was thinking with that defer_lock use.  I guess that's equivalent to what was there before but obviously that's not how the std:: variant is meant to be used.  And the docs at https://en.cppreference.com/w/cpp/thread/condition_variable/wait say clearly that it's wrong.  So yeah, if you delete those two `std::defer_lock` uses it all starts working?  I.e. do this:
```
--- a/dlib/threads/threads_kernel_1.h
+++ b/dlib/threads/threads_kernel_1.h
@@ -92,7 +92,7 @@ namespace dlib
         void wait (
         ) const
         { 
-            std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);
+            std::unique_lock<std::mutex> cs(m.cs);
             cv.wait(cs);
         }
 
@@ -100,7 +100,7 @@ namespace dlib
             unsigned long milliseconds
         ) const
         { 
-            std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);
+            std::unique_lock<std::mutex> cs(m.cs);
             auto status = cv.wait_until(cs, std::chrono::system_clock::now() + std::chrono::milliseconds(milliseconds));
             return status == std::cv_status::no_timeout;
         }
```

**Comment by reunanen** [comment]
That is pretty much what I tried first, but then it will complain already when trying to construct the unique_lock, apparently because the mutex is already locked:
```
// undefined behavior, only occurs for plain mutexes (N4950 [thread.mutex.requirements.mutex.general]/6)
_STD _Throw_Cpp_error(_RESOURCE_DEADLOCK_WOULD_OCCUR);
```

**Comment by PiootrK** [comment]
Debug builds that use `dlib::server_http` also fail with the same error when compiled with Visual Studio 2002 17.9.2.

**Comment by davisking** [comment]
Er, sorry, wasn't paying attention.  The lock is definitely already locked.  So what's there ought to be fine.  Like note that the signaler::wait_or_timeout() has a precondition that the associated lock is locked by the calling thread.  And if you check the pipe code you can see that it is indeed locked.  So this is totally a bug in visual studio. 

Although we still need to deal with it because visual studio is what it is.  Anyway, if you just move `std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);` so it's a member of the `dlib::mutex` class that probably works around it?  So like this:

```
--- a/dlib/threads/threads_kernel_1.h
+++ b/dlib/threads/threads_kernel_1.h
@@ -44,7 +44,7 @@ namespace dlib
     public:
 
         mutex (
-        ) 
+        ) : cs(m, std::defer_lock)
         {
         }
 
@@ -61,7 +61,8 @@ namespace dlib
 
         friend class signaler;
 
-        mutable std::mutex cs;
+        mutable std::mutex m;
+        mutable std::unique_lock<std::mutex> cs;
 
         // restricted functions
         mutex(mutex&);        // copy constructor
@@ -92,16 +93,14 @@ namespace dlib
         void wait (
         ) const
         { 
-            std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);
-            cv.wait(cs);
+            cv.wait(m.cs);
         }
 
         bool wait_or_timeout (
             unsigned long milliseconds
         ) const
         { 
-            std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);
-            auto status = cv.wait_until(cs, std::chrono::system_clock::now() + std::chrono::milliseconds(milliseconds));
+            auto status = cv.wait_until(m.cs, std::chrono::system_clock::now() + std::chrono::milliseconds(milliseconds));
             return status == std::cv_status::no_timeout;
         }
```

**Comment by reunanen** [comment]
> So this is totally a bug in visual studio.

Yep, it does look like that to me as well – although can't really say I've been able to get to the bottom of this just yet.

> Anyway, if you just move `std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);` so it's a member of the `dlib::mutex` class that probably works around it?

No, not really I'm afraid – it looks like this now leads to [a deadlock or something](https://github.com/reunanen/dlib/actions/runs/8216107535/job/22470294322). In addition, with this change, tests that would otherwise work start to [fail](https://github.com/reunanen/dlib/actions/runs/8216107535/job/22470294270), even in the previous Visual Studio version (where without this change things are generally working).

(To [reproduce](https://github.com/reunanen/dlib/actions/runs/8216099147/job/22470276531) this issue in GitHub Actions, had to [update Visual Studio and build a Debug version](https://github.com/reunanen/dlib/commit/3227895c44307e8a2971ccaf24be65197150d428). And then on top of that, I just [applied your patch](https://github.com/reunanen/dlib/commit/5f2d9fb4168b3958e30fdc8c7fe7f08566b0ea89).)

**Comment by davisking** [comment]
Oh, I'm pretty sure I see the issue. Dlib isn't quite right, not a bug in visual studio.  It's that std::unique_lock::owns_lock() is *not* telling you if the mutex is locked, but if the `unique_lock` was the one to make it locked.  That is, the bool telling if it's locked is in `unique_lock`, not the mutex itself.  And the precondition on wait() is that `unique_lock()::owns_lock() == true`.  Which is a fine way to setup the API for the normal use case.

Anyway, it should be this.  Pretty sure this will make everything square:
``` 
--- a/dlib/threads/threads_kernel_1.h
+++ b/dlib/threads/threads_kernel_1.h
@@ -92,16 +92,22 @@ namespace dlib
         void wait (
         ) const
         { 
-            std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);
+            std::unique_lock<std::mutex> cs(m.cs, std::adopt_lock);
             cv.wait(cs);
+            // Make sure we don't actually modify the mutex. Since the calling code will have locked
+            // it and it should remain locked.
+            cs.release();
         }
 
         bool wait_or_timeout (
             unsigned long milliseconds
         ) const
         { 
-            std::unique_lock<std::mutex> cs(m.cs, std::defer_lock);
+            std::unique_lock<std::mutex> cs(m.cs, std::adopt_lock);
             auto status = cv.wait_until(cs, std::chrono::system_clock::now() + std::chrono::milliseconds(milliseconds));
+            // Make sure we don't actually modify the mutex. Since the calling code will have locked
+            // it and it should remain locked.
+            cs.release();
             return status == std::cv_status::no_timeout;
         }
```

**Comment by reunanen** [comment]
> It's that std::unique_lock::owns_lock() is _not_ telling you if the mutex is locked, but if the `unique_lock` was the one to make it locked.

That's what I thought as well, so I tried to add an assertion that should trigger on Linux builds, too. But that did not happen – they completed just fine.

... and only now I realize that's just because I only added it to `threads_kernel_1.h`, which is not used for Linux builds at all 😂 

> Anyway, it should be this. Pretty sure this will make everything square:

Now running the same test [here](https://github.com/reunanen/dlib/actions/runs/8217009894).

**Comment by reunanen** [comment]
Looks like that test [passed](https://github.com/reunanen/dlib/actions/runs/8217009894/job/22472212109)! Will also run my application-level tests now.

**Comment by reunanen** [comment]
Looks like all good on my side. Thank you so much Davis for fixing this so quickly!!

For your convenience, I can wrap your patch into a PR. :)

**Comment by davisking** [comment]
Sweet, yeah thanks for posting the problem :)

**Comment by reunanen** [comment]
@PiootrK, you may want to test that the latest `master` version works for you, too?

**Comment by PiootrK** [comment]
> @PiootrK, you may want to test that the latest `master` version works for you, too?

Yes, it does! Thanks a lot guys!
