### ISSUE TITLE
[Bug]: Building Error "Python libraries not found"

### ISSUE THREAD

**Issue by cheezecrisp** [davisking/dlib#2928]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24.0

### Python version

3.8.10

### Compiler

MSVC 19.38.33133.0

### Expected Behavior

Install successfully

### Current Behavior

Install Failed, detail info:

(venv) D:\AI\video-retalking>pip3 install dlib-19.24.0.tar.gz
Processing d:\ai\video-retalking\dlib-19.24.0.tar.gz
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [116 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cmake_version) < '3.1.0':
      Building extension for Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\build\lib.win-amd64-cpython-38 -DPYTHON_EXECUTABLE=D:\AI\video-retalking\venv\Scripts\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\build\lib.win-amd64-cpython-38 -A x64'
      -- Building for: Visual Studio 17 2022
      CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
      -- The C compiler identification is MSVC 19.38.33133.0
      -- The CXX compiler identification is MSVC 19.38.33133.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/cmake_utils/tell_visual_studio_to_use_static_runtime.cmake:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      Call Stack (most recent call first):
        CMakeLists.txt:35 (include)
      CMake Deprecation Warning at C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      CMake Deprecation Warning at C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/tools/pybind11Tools.cmake:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      Call Stack (most recent call first):
        C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/CMakeLists.txt:33 (include)
      CMake Warning (dev) at C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:60 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      Call Stack (most recent call first):
        C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/tools/pybind11Tools.cmake:16 (find_package)
        C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/CMakeLists.txt:33 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      -- Found PythonInterp: D:/AI/video-retalking/venv/Scripts/python.exe (found version "3.8.10")
      **CMake Error at C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:158 (message):
        Python libraries not found**
      Call Stack (most recent call first):
        C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/tools/pybind11Tools.cmake:16 (find_package)
        C:/Users/cheeese/AppData/Local/Temp/pip-req-build-0jz7ejg8/dlib/external/pybind11/CMakeLists.txt:33 (include)
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\setup.py", line 222, in <module>
          setup(
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\AI\video-retalking\venv\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\AI\video-retalking\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\setup.py", line 134, in run
          self.build_extension(ext)
        File "C:\Users\cheeese\AppData\Local\Temp\pip-req-build-0jz7ejg8\setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "subprocess.py", line 364, in check_call
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\cheeese\\AppData\\Local\\Temp\\pip-req-build-0jz7ejg8\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\cheeese\\AppData\\Local\\Temp\\pip-req-build-0jz7ejg8\\build\\lib.win-amd64-cpython-38', '-DPYTHON_EXECUTABLE=D:\\AI\\video-retalking\\venv\\Scripts\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\cheeese\\AppData\\Local\\Temp\\pip-req-build-0jz7ejg8\\build\\lib.win-amd64-cpython-38', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

### Steps to Reproduce

step1: build python venv environments
step2: install torch/torchvision `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`
step3: install dlib (using whl file) `pip install dlib-19.24.0.tar.gz` and error occurs

**Comment by davisking** [comment]
I'm not sure what the issue is but your system is missing the python libraries that are normally there which are needed to compile a python extension.  Maybe reinstall python.  Can't say.

**Comment by cheezecrisp** [comment]
> I'm not sure what the issue is but your system is missing the python libraries that are normally there which are needed to compile a python extension. Maybe reinstall python. Can't say.

I have python 3.10 installed on my OS, but the code for "video retalking" requires python3.8 so I downloaded the embed version of python3.8 and created a python3.8 venv environment using virtualenv.
