### ISSUE TITLE
[Bug]: dlib v19.24.3 release reports version 19.24.99

### ISSUE THREAD

**Issue by jschueller** [davisking/dlib#2935]
### What Operating System(s) are you seeing this problem on?

Other (plase, specify in the Steps to Reproduce)

### dlib version

19.24.3

### Python version

all

### Compiler

all

### Expected Behavior

19.24.3

### Current Behavior

19.24.99

### Steps to Reproduce

https://github.com/davisking/dlib/blob/v19.24.3/dlib/CMakeLists.txt#L21

**Comment by davisking** [comment]
Oops, yeah, let me fix that.  Thanks for posting about it.

**Comment by davisking** [comment]
Sorted.  Now we have a v19.24.4 :D
