### ISSUE TITLE
[Bug]: dlib 19.24.4 and 19.24.3 are not available on PyPI

### ISSUE THREAD

**Issue by Jamim** [davisking/dlib#2940]
### What Operating System(s) are you seeing this problem on?

Other (plase, specify in the Steps to Reproduce)

### dlib version

19.24.4

### Python version

any

### Compiler

any

### Expected Behavior

```bash
Collecting dlib
  Downloading dlib-19.24.4.tar.gz
...
Successfully installed dlib-19.24.4
```

### Current Behavior

```bash
Collecting dlib
  Downloading dlib-19.24.2.tar.gz (11.8 MB)
...
Successfully installed dlib-19.24.2
```

### Steps to Reproduce

On any platform, run:
```bash
pip install dlib
```
Since there are no **dlib** [19.24.4](https://github.com/davisking/dlib/releases/tag/v19.24.4) and [19.24.3](https://github.com/davisking/dlib/releases/tag/v19.24.3) [on PyPI](https://pypi.org/project/dlib/#history), it will try to download and install the latest _available_ version, which is [19.24.2](https://github.com/davisking/dlib/releases/tag/v19.24.2) at the moment.

**Comment by davisking** [comment]
Oh right, yep, just pushed 19.24.4 to PyPI.  Thanks.
