### ISSUE TITLE
Unable to compile dlib due to some file encoding issue?

### ISSUE THREAD

**Issue by ManHinnn0509** [davisking/dlib#2953]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24

### Python version

3.9.13

### Compiler

GCC 11.3.0, MSVC 14

### Expected Behavior

Since CUDA and cuDNN was found, I expect to install dlib with CUDA support

### Current Behavior

When I run `cmake ..` in `build` directory, it says "CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA." and CUDA is not going to be used in dlib. The error message seems to be related to some file encoding issue? The whole output is very long so I uploaded it as a [gist raw file](https://gist.githubusercontent.com/ManHinnn0509/669e74409c2f6c2fdcf78e6de7c39cfb/raw/d74cd5609043b3a0889d6d4db5a234924b5cfb9f/cmake-dlib-error)

### Steps to Reproduce

```
cd dlib
mkdir build
cd build
cmake ..
```
^ The error occurs during in `cmake ..`

### Anything else?

I also tried to build `test_for_cuda` and `test_for_cudnn` (As mentioned in [another issue](https://github.com/davisking/dlib/issues/2108#issuecomment-647121284)), `test_for_cudnn` has no error but `test_for_cuda` has error in `cmake --build .`, the output is also very long so I also uploaded it as a [gist raw file](https://gist.githubusercontent.com/ManHinnn0509/669e74409c2f6c2fdcf78e6de7c39cfb/raw/d74cd5609043b3a0889d6d4db5a234924b5cfb9f/cmake-build-test_for_cuda)

Tried to Google this and search it in here but by far couldn't find anything related to this... Please help

**Comment by davisking** [comment]
I can't say, other than it looks like something in your visual studio or cuda install is broken (i.e. something unrelated to dlib).

**Comment by ManHinnn0509** [comment]
I downgraded CUDA from 11.3 to 11.2, it's working because Tensorflow is using my GPU and also upgraded VS2019 but the problem still exists.

I wonder if I can use VS2019 to compile dlib? Because I can't download VS2015 anymore and I plan to re-install VS2019 if it can be used to compile dlib

**Comment by davisking** [comment]
Yeah VS2019 is fine.  As are newer versions of visual studio.
