### ISSUE TITLE
C++ warnings 

### ISSUE THREAD

**Issue by odedharth** [davisking/dlib#296]
There are warnings when running dlib on Xcode 8 ([here are some of them](https://www.evernote.com/l/ADkQtTCfZvRGJqYgAPTJ20IvM6AnrV-HrnE))

The most occurring one is `Implicit conversion loses integer precision: 'integer' (aka 'long') to 'int'`

**Comment by davisking** [comment]
Cool. Submit a pull request :)

**Comment by odedharth** [comment]
Submitted 👍
