### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 1rdsk1** [davisking/dlib#2962]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24

### Compiler

VS2022

### Expected Behavior

The build succeeded, but there was an error when attempting to open the cuDNN library file. Specifically, the error message "LINK : fatal error LNK1104: cannot open file 'cudnn.lib'" indicates that the linker was unable to locate the cuDNN library file during the linking stage of the build process.

### Current Behavior

unable to determine what is wrong as all paths and properties appear correctly set

### Steps to Reproduce

attempt to create dlib.dll with cuda support has failed

### Anything else?

no

**Comment by 1rdsk1** [comment]
Looking at the dlib.vcx.proj file at lines 68 and 69, the targetname and tearget extension are overriden from those I set in the properties window.  I set dlib.dll but this gets overridden by dlibxxxxxxxxx.lib  I'm struggling to understand why?

**Comment by davisking** [comment]
I can't say.  It sounds like something is wrong with your cudnn install.  I would try installing it again and being sure to follow the instructions nvidia gives for your platform :shrug:
