### ISSUE TITLE
[Bug]: linking error using DLIB_USE_MKL_WITH_TBB = ON

### ISSUE THREAD

**Issue by amwink** [davisking/dlib#2963]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24.4

### Python version

3.11.8

### Compiler

g++ 12.3.0-5

### Expected Behavior

After seeing (with cmake-gui) that libraries mkl_tbb and mkl_tbb_thread are found and setting DLIB_USE_MKL_WITH_TBB to ON, for DLib to compile using the Intel-optimised routines.

### Current Behavior

With DLIB_USE_MKL_WITH_TBB set to OFF, Compilation finishes, but with DLIB_USE_MKL_WITH_TBB set to ON, it gives these errors
[dlib_errors_MKL_FFT.txt](https://github.com/user-attachments/files/15727622/dlib_errors_MKL_FFT.txt)

### Steps to Reproduce

With the switch set to OFF it compiles, with the switch set to ON it gives these linking errors.

### Anything else?

Added the option '-ltbb'   ( /usr/lib/x86_64-linux-gnu/libtbb.so points to libtbb.so.12.5 ) but CMake puts it at the start, when no symbols are added.

**Comment by davisking** [comment]
You don't need to use the TBB.  But if you want to you will have to figure out how to link to it for your platform and send us a PR that makes cmake know how to do it :)
