### ISSUE TITLE
[Bug]: Fhog_example does not work with example data

### ISSUE THREAD

**Issue by TonyCongqianWang** [davisking/dlib#2967]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24 51c7a3597935ed2cb969521a0ada0b7209f78ec2

### Python version

N/A

### Compiler

GCC 9.4.0

### Expected Behavior

I compiled the example programs and tried to ran the ./fhog_object_detector_ex ../faces that worked. But when I removed the "optional" upsampling, I get an exception that there was an impossible box. To me it it should be possible to run the example program even after removing the "optional" code.

### Current Behavior

Exception is thrown "impossible box detected".

### Steps to Reproduce

clone current repo, build examples, comment out the lines 
```        
upsample_image_dataset<pyramid_down<2> >(images_train, face_boxes_train);
        upsample_image_dataset<pyramid_down<2> >(images_test,  face_boxes_test);
```
 in fhog_object_detector_ex.cpp and run with `./fhog_object_detector_ex ../faces`

**Comment by davisking** [comment]
Thanks, yeah those comments are not clear, since for that dataset upsampling is required.  I just updated them to be less confusing.
