### ISSUE TITLE
[Bug]: runtime error importing dlib

### ISSUE THREAD

**Issue by norflin321** [davisking/dlib#2977]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### dlib version

0947215ddb268fef192e45c140c9430f77648166

### Python version

3.10.12

### Compiler

clang 15.0.7

### Expected Behavior

`import dlib` without errors

### Current Behavior

```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/norflin/code/miniforge3/lib/python3.10/site-packages/dlib-19.24.99-py3.10-macosx-11.0-arm64.egg/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen(/Users/norflin/code/miniforge3/lib/python3.10/site-packages/dlib-19.24.99-py3.10-macosx-11.0-arm64.egg/_dlib_pybind11.cpython-310-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib
  Referenced from: <4E8ECBBB-080F-3260-882E-4014BB1E62AE> /opt/homebrew/Cellar/ffmpeg/7.0_1/lib/libavdevice.61.1.100.dylib
  Reason: tried: '/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/opt/homebrew/Cellar/openvino/2024.2.0_1/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openvino/2024.2.0_1/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/opt/homebrew/Cellar/openvino/2024.2.0_1/lib/libopenvino_onnx_frontend.2410.dylib' (no such file)Library not loaded: /opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib
  Referenced from: <B417A657-2A9E-3395-8D13-6686418E25E2> /opt/homebrew/Cellar/ffmpeg/7.0_1/lib/libavfilter.10.1.100.dylib
  Reason: tried: '/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/opt/homebrew/Cellar/openvino/2024.2.0_1/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openvino/2024.2.0_1/lib/libopenvino_onnx_frontend.2410.dylib' (no such file), '/opt/homebrew/Cellar/openvino/2024.2.0_1/lib/libopenvino_onnx_frontend.2410.dylib' (no such file)
```

### Steps to Reproduce

- follow these steps https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf
- run `import dlib` in python 3

### Anything else?

- i have reinstalled "openvino: stable 2024.2.0"
- it seems like dlib trying to use an older version of openvino
- i have `/opt/homebrew/opt/openvino/lib/libopenvino_onnx_frontend.2420.dylib` but dlib is trying to load `libopenvino_onnx_frontend.2410.dylib`

**Comment by arrufat** [comment]
Something is off. Dlib does not depend on either OpenVINO nor ONNX.

**Comment by norflin321** [comment]
i just completely reinstalled python and created a new venv, with zero packages installed, then builded dlib from source following [these](https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf) steps, and i still get the same error

**Comment by norflin321** [comment]
> Something is off. Dlib does not depend on either OpenVINO nor ONNX.

could you suggest any ideas what this issue might be related with?

**Comment by arrufat** [comment]
Honestly, I don't know :(
This should just work:
```
python -m venv venv
source venv/bin/activate
pip install dlib
```

That's what I've always done with Python, unless I need a development version of dlib.

**Comment by norflin321** [comment]
> Honestly, I don't know :( This should just work:
> 
> ```
> python -m venv venv
> source venv/bin/activate
> pip install dlib
> ```
> 
> That's what I've always done with Python, unless I need a development version of dlib.

fixes after reinstalling `ffmpeg` with homebrew, it turns out ffmpeg was broken

**Comment by arrufat** [comment]
@davisking maybe we should disable building FFmpeg when building the Python wheel, since there are no Python bindings, right?

**Comment by davisking** [comment]
> @davisking maybe we should disable building FFmpeg when building the Python wheel, since there are no Python bindings, right?

Yep, good idea.
