### ISSUE TITLE
[Bug]: dlib doesnt install.  says cmake is required but have installed cmake.

### ISSUE THREAD

**Issue by p3p3fr0g** [davisking/dlib#2981]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

whatever pip install dlib tries to install

### Python version

3.10.12

### Compiler

pip install dlib

### Expected Behavior

expected it to install

### Current Behavior

pip install dlib
Defaulting to user installation because normal site-packages is not writeable
Collecting dlib
  Using cached dlib-19.24.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/usr/local/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)

it says cmake must be installed
but

cmake --version
cmake version 3.30.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

so it is installed

### Steps to Reproduce

i type pip install dlib and it doesnt work
i've tried sudo pip install dlib and that doesn't work

**Comment by arrufat** [comment]
How did you install CMake?

**Comment by arrufat** [comment]
I think your linux distro will install the binaries in `/usr/bin/` but your current `cmake` command points to `/usr/local/bin/`.
Try to cleanly get rid of the one in that `/usr/local/bin`.

**Comment by arrufat** [comment]
It's failing when building libpng?

**Comment by arrufat** [comment]
Can you try by running:
`CFLAGS='' pip install dlib`?

I don't know if it will work.
It works when I git clone and run `CFLAGS="" python setup.py install`

**Comment by arrufat** [comment]
Also, you're using clang, maybe you can try with `CC=gcc pip install dlib`
