### ISSUE TITLE
[Bug]: Installation failed in 'microcanda env'

### ISSUE THREAD

**Issue by 807502278** [davisking/dlib#2985]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

all

### Python version

3.11

### Compiler

c++17.9,cmake==3.25.2(python-env),setuptools==68.2.2~72.0.0

### Expected Behavior

List the versions of other dependency packages that need to be used?

### Current Behavior

I switched many versions of dlib and setuptools, but I still got this error message.  
![image](https://github.com/user-attachments/assets/3775d458-a03c-4805-876b-76c9c52a3e9e)

### Steps to Reproduce

Directly "pip install dlib" from Python env

**Comment by vitali-yanushchyk-valor** [comment]
Hey.

It's cause of new version setuptools where deprecated  test command was removed

https://github.com/pypa/setuptools/issues/931

**Comment by 807502278** [comment]
I switched to a lower version yesterday but still got an error. Today, I restarted the system and it worked unexpectedly. Thank you!

**Comment by vitali-yanushchyk-valor** [comment]
I'm sure it's because setuptools restore the tests command
https://setuptools.pypa.io/en/stable/history.html

**Comment by davisking** [comment]
Yeah.  I just pulled the test stuff out of setup.py anyway.  Nothing uses that stuff anymore so it's not needed.
