### ISSUE TITLE
[Bug]: dlib doesn't build with FFmpeg 7

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#2986]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24

### Compiler

GCC 14.1.1

### Expected Behavior

Build dlib successfully with FFmpeg support

### Current Behavior

FFmpeg broke some APIs,
There are some fields that got renamed from `channel_layouts` to `ch_layouts`.

### Steps to Reproduce

``` console
git clone https://github.com/davisking/dlib
cd dlib
cmake -B build -G Ninja
cmake --build build
```

### Anything else?

It would be great if @pfeatherstone could take a look at this, since I don't have multiple FFmpeg installations, I might fix this and break other versions...

**Comment by pfeatherstone** [comment]
Yeah I can have a look later today

**Comment by pfeatherstone** [comment]
I won't be able to test with gcc14 though. Best I can do 13

**Comment by arrufat** [comment]
Thank you! I don't think the compiler poses a problem.

**Comment by pfeatherstone** [comment]
Meta-programming not working. I'm replacing the FFMPEG macro with a custom one. Looks like it's working.

**Comment by pfeatherstone** [comment]
https://github.com/davisking/dlib/pull/2987

**Comment by arrufat** [comment]
I can confirm it works now, thank you so much!

**Comment by davisking** [comment]
Awesome, thanks guys :D
