### ISSUE TITLE
[Bug]: unable to access dlib.net from work because there is no valid signed certificate

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#2990]
### What Operating System(s) are you seeing this problem on?

Windows

### dlib version

19.24

### Compiler

any

### Expected Behavior

to be able to read about dlib on dlib.net using any mainstream browser with internet access

### Current Behavior

As our company uses some security solution which disables https sites without valid certificate, for some time now I'm unable to access https://dlib.net from my work PC.

### Steps to Reproduce

open https://dlib.net using any browser

**Comment by arrufat** [comment]
As far as I know, there's no https version, the site is http://skin.net.

**Comment by davisking** [comment]
Yeah there is no https version.  I would add it but GoDaddy wants a fee to enable it.  It's also literally a static HTML web page so there is no reason at all to use https with it.

**Comment by pepeverde9** [comment]
Thank you. The message in the browser misled me, when trying to open the site from a google search:
![image](https://github.com/user-attachments/assets/4e7a7b69-e8ac-4945-988c-5b9568794901)
But it just opens when opened by writing the full 

> http://dlib.net

 in the address bar.
