### ISSUE TITLE
[Bug]: Cmake regex error while trying to make install

### ISSUE THREAD

**Issue by Bariskizilkaya** [davisking/dlib#2991]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### dlib version

19.24.5

### Compiler

gcc 11.4.0

### Expected Behavior

installation successfully done

### Current Behavior

Gives error whie sudo make install

### Steps to Reproduce

mkdir build
cd build
cmake .. //sucessfull
make //sucessfull
sud make install // gives an error

### Anything else?

![image](https://github.com/user-attachments/assets/9cc7d08e-2581-4700-99ef-7312142f7211)

**Comment by davisking** [comment]
Try without + characters in your file path.  Like don't put + in your directory name.

I don't know that this is anything I can control.
