### ISSUE TITLE
dlib website update

### ISSUE THREAD

**Issue by DlibReza** [davisking/dlib#2997]
### Main idea

hello
i hava a question,
why latest dlib release version is only on github and not updated on dlib website and dlib website have relaese 19.24.
in my opinion ,website is more imprtant than github.
thanks a lot.

**Comment by davisking** [comment]
Yep, what @arrufat said.  There is also https://github.com/davisking/dlib/issues/2902, not sure if you were looking at that @arrufat.  That's the main thing I was letting sit before making a major release.

**Comment by arrufat** [comment]
Those minor releases are just for Python packaging purposes,they don't expose any of the newly added C++ functionality.
The next version of dlib contains many new features,  such as ffmpeg support, that need to be tested for a while.

**Comment by arrufat** [comment]
I still couldn't figure out why... Maybe we should remove suport for that layer until I fix it? I don't think anyone is using it.

**Comment by davisking** [comment]
Yeah maybe.  I haven't looked at it either.  I'll look before I do anything though.

**Comment by arrufat** [comment]
Ok, don't waste too much time into it

**Comment by davisking** [comment]
Heh, yeah that issue is fixed.  I should update the website :)
