### ISSUE TITLE
[Bug]: Bus error: 10

### ISSUE THREAD

**Issue by zxfxpower** [davisking/dlib#2998]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### dlib version

19.24.6

### Python version

3.10.13

### Compiler

pip install dlib

### Expected Behavior

The following code can execute normally
```
shape = dlib.shape_predictor(path_of_lm)
t = list(shape.parts())
```

### Current Behavior

The following error occurred
Bus error: 10

### Steps to Reproduce

nothing

### Anything else?

The code needs to be modified as follows in order to execute normally. Skipped the last part。Additionally, I am using MacBook Pro M3，macos 14.5 (23F79)
```
shape = dlib.shape_predictor(path_of_lm)
t = []
parts = shape.parts()
for i, part in enumerate(parts):
    if i == len(parts) - 1:
        break  
    t.append(part)
```

**Comment by zxfxpower** [comment]
@davisking The complete code is here：https://github.com/tomy128/video-retalking/blob/m1/utils/ffhq_preprocess.py
line 49。
It may be a compatibility issue，The code can only run on m1, but not on m3

**Comment by davisking** [comment]
IDK.  Nothing in dlib should care about what kind of CPU it's running on.
Maybe there is some bug in that program you have that's not obvious.

**Comment by zxfxpower** [comment]
@davisking Thank you for your answer！
