### ISSUE TITLE
1927 FATAL [1] dlib.gui_core: Unable to connect to the X display on ubuntu

### ISSUE THREAD

**Issue by avisangray** [davisking/dlib#300]
i'm executing a program for image processing on ubuntu server but it gives following error
1927 FATAL [1] dlib.gui_core: Unable to connect to the X display

however on ubuntu desktop it works fine

**Comment by avisangray** [comment]
there isn't any gui window in code

**Comment by davisking** [comment]
You sure about that?

**Comment by avisangray** [comment]
apologizie. error came from some opencv code within. have fixed. Thanks

**Comment by davisking** [comment]
No worries

**Comment by sunshineclt** [comment]
@avisangray  Got the same problem on Mac

**Comment by elaughli** [comment]
@sunshineclt I recently ran into this same issue on High Sierra (10.13.2). 

I then stumbled upon [this explanation of X11 support for Apple](https://support.apple.com/en-us/HT201341). 

The solution is to download [XQuarts from here](https://www.xquartz.org/) then follow the prompts through install, including logging out and logging back in. Everything worked perfectly after that.

**Comment by sunshineclt** [comment]
@elaughli Exactly, my solution is the same with you 😄

**Comment by davisking** [comment]
Both of you should have seen a message print during dlib build telling you to go download XQuartz. Didn't it print?

**Comment by elaughli** [comment]
@davisking hmm nope I don't see any message in the output about that. Although I am seeing in the CMakeLists.txt where it should've output that. There must be some conflict I'm unaware of that found xlib when actually it wasn't there because DLIB_NO_GUI_SUPPORT was set to OFF.

**Comment by davisking** [comment]
Are you sure you don't mean DLIB_NO_GUI_SUPPORT was ON?

**Comment by elaughli** [comment]
Sorry, my wording there could've been better. It was set OFF which means that it found something to tell it xlib was there and to use the gui even though I hadn't install XQuartz yet. 

After poking around a little I see that Xcode has some Xlib.h headers, and although I haven't pinpointed it exactly I think that might be what it was finding.

**Comment by pfeatherstone** [comment]
> Both of you should have seen a message print during dlib build telling you to go download XQuartz. Didn't it print?

I didn't see this message and getting the same error that dlib can't correct to X display.
