### ISSUE TITLE
Image turns blue

### ISSUE THREAD

**Issue by praveenlovely** [davisking/dlib#303]
Hi,

I have a quick question. I am using your library to extract specific points from a face image using python.
After I use the dlib detector, the image turns bluish. Is there any specific reason for this and is there a way to prevent it? 
Please explain.

**Comment by davisking** [comment]
Nothing in dlib should be making blue images.

**Comment by vicproon** [comment]
@praveenlovelyl, this can happen if you misinterpret BGR image as RGB. Try performing a color transformation.
