### ISSUE TITLE
find_max_global does not expose rng seed

### ISSUE THREAD

**Issue by jschueller** [davisking/dlib#3034]
### Main idea

find_max_global uses the global_function_search which initializes a random seed, so there is no control over the points generated, it would be great to allow to pass the seed to get a deterministic behavior, what do you think ?

**Comment by davisking** [comment]
It's already deterministic though.

**Comment by davisking** [comment]
Well, aside from the use of threads if you turn that on.  That introduces non-determinism.  That's got nothing to do with the seed though.

**Comment by jschueller** [comment]
yes, it seems to com from threading, but not the dlib one, the openblas ones, it goes away if I set OMP_NUM_THREADS=1
