### ISSUE TITLE
Detect rotated objects in images

### ISSUE THREAD

**Issue by vals19** [davisking/dlib#304]
Hello Davis, and my congratulations for this awesome C++ library.
I'm currently developing a project which should detect some objects in different images. The objects that I want to detect are randomly rotated and also don't have an 1:1 aspect ratio.

So, I've tested your HOG and DNN examples.

With the HOG detector it works very well when there are only images which don't have rotated objects (I've trained my own image dataset). Are there some options or possibilities to do that with HOG detector?

I've tried to test the DNN module from examples (on Windows 10 with Visual Studio 2015 with Update 3). I've successfully run the dnn_mmod_dog_hipsterizer.cpp.  On your [blog post](http://blog.dlib.net/2016/10/easily-create-high-quality-object.html)  you said that running on CPU takes about 370ms to process a 640x480 image.  When I've run on my machine, it takes about 13 seconds (using Release mode). I have 8GB RAM and an i7 processor installed on this machine. If I run dnn_mmod_face_detection_ex.cpp the PC freezes and a restart is needed. I think that I run out of memory. Why? I don't know. I see here people that runs the DNN on iPhone (#284) and takes about a second. 

Do you have some suggestions on how to use dlib for this use-case and detect all objects in different positions?

**Comment by davisking** [comment]
No problem :)

No, HOG can't deal with rotation.  

I'm skeptical that you actually compiled in release mode:  see http://dlib.net/faq.html#Whyisdlibslow

I would use the DNN, that will work well for any objects.  Just make the boxes square.
