### ISSUE TITLE
Parameters used for training shape predictor

### ISSUE THREAD

**Issue by abhilashi** [davisking/dlib#305]
@davisking Not sure if this is the right place to post. Apologies in advance if it isn't.

Coming to the issue, the current landmark detector is running in 20 ms on a 1.2 GHz Android phone. We need to get it under 5ms to achieve 30 fps. One of the things we intend to do is train and run shape predictor on a subset of these 68 points. (Because we're not using all sixty eight in our pipeline)

Few questions in this regard. 

1)  Am I right in stating that the current [model](http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
)  is trained using this [ibug dataset](http://dlib.net/files/data/ibug_300W_large_face_landmark_dataset.tar.gz) 

2) Does it use the same default parameters listed in the file for training: http://dlib.net/dlib/image_processing/shape_predictor.h.html
```
            _cascade_depth = 10;
            _tree_depth = 4;
            _num_trees_per_cascade_level = 500;
            _nu = 0.1;
            _oversampling_amount = 20;
            _feature_pool_size = 400;
            _lambda = 0.1;
            _num_test_splits = 20;
            _feature_pool_region_padding = 0;
            _verbose = false;
            _num_threads = 0;
```
3) Any other hacks/tips to improve performance in the context of Android/mobile would be greatly appreciated :)

**Comment by davisking** [comment]
Yes, that's the data it's trained on.  It used something similar to the default parameters.  Just try some things and see what works best.

**Comment by abhilashi** [comment]
@davisking Thanks for the quick reply :) 

The trainer is killed after a few minutes without any log messages.

```
ubuntu@ip-172-31-24-103:~/dlib/examples/build$ ./train_shape_predictor_ex ibug_300W_large_face_landmark_dataset/
Killed
```

```
saadhana@Abhilashs-MacBook-Air-4 ~/dlib-android/jni/dlib/examples/build((HEAD detached at 40ea658)) $ ./train_shape_predictor_ex /Users/saadhana/Downloads/ibug_300W_large_face_landmark_dataset/
Fitting trees...
Killed: 9
```

I tried running on machines with 4GB and 16GB RAM. It ran out of memory on both of these machines. Could you please share the machine configuration you used while training?

**Comment by davisking** [comment]
My machine has 32GB of ram.
