### ISSUE TITLE
Possibility of adding hunter-ized cmake changes

### ISSUE THREAD

**Issue by caseymcc** [davisking/dlib#308]
I have recently starting using a package handler named hunter (built on top of cmake, https://github.com/ruslo/hunter). And they have a package handler for dlib that has been modified to allow hunter to download dlib and include (header only) it through cmake. I have recently altered it to build the static lib and use hunter-ized libjpeg and libpng (https://github.com/caseymcc/dlib, not yet merged to hunter). The changes should not directly affect normal dlib builds and I am wondering if this is something you all would like to include in the mainline so that the hunter fork would not have to be maintained?

**Comment by davisking** [comment]
Sure, so long as it doesn't cause problems with existing dlib use.

**Comment by caseymcc** [comment]
I ended up having to make more changes than I expected (and ruslo would like a few more changes, https://github.com/hunter-packages/dlib/pull/5) so I am not sure it is something you would want back in the mainline (the changes: https://github.com/hunter-packages/dlib/pull/5/files). Let me know if you are interested and I will see what I can do to make it work for both.

**Comment by davisking** [comment]
If you want to create a PR for it I'll take a look.  But if not then I'm
not too worried about it.
