### ISSUE TITLE
[RFC] Update of CI status badge

### ISSUE THREAD

**Issue by stefan-it** [davisking/dlib#309]
Hi @davisking,

currently the CI status badge (in `README.md`) points to an [empty website](https://camo.githubusercontent.com/d1f27ca3ae5f5eb6bf7ba8d890e4b823ee17ef25/68747470733a2f2f7472617669732d63692e6f72672f64617669736b696e672f646c69622e7376673f6272616e63683d6d6173746572).

What do you think about using the CI status badge from the Travis site + put a link to the [dlib Travis CI status site](https://travis-ci.org/davisking/dlib)?

If you agree with that, I would prepare a PR for that small change :)

**Comment by davisking** [comment]
Sounds good :)
