### ISSUE TITLE
Integrating dlib with android ndk

### ISSUE THREAD

**Issue by anmoluppal** [davisking/dlib#31]
I would like to integrate the `dlib` library with my android app which has the ndk configuration, But I am facing problems  in building the library using the `ndk-build` command it outputs a lot of errors as `undefined reference to `XOpenDisplay``. But it seems that I have correctly installed the X11 library, I would like to know is it possible to integrate your library code with android ndk?

**Comment by davisking** [comment]
There are lots of people using dlib on android, here is an example:
https://github.com/tzutalin/dlib-android

If you want to turn off the GUI code then read the instructions here:
http://dlib.net/compile.html

**Comment by rishabhMaltare** [comment]
@davisking @tzutalin Can you please help me with if the new dlib (i.e. 19.4.0) can be used in android? My main purpose is to use it in a face recognition app.  Thank you!

**Comment by davisking** [comment]
Yes, the new version works fine on android.  Lots of people use it for that and there isn't anything special you need to do to use it.
