### ISSUE TITLE
Image recognition

### ISSUE THREAD

**Issue by praveenlovely** [davisking/dlib#310]
How can we use D-lib for image recognition?
I could see your program where we could generate scores for images but how could we use it for recognition?

Can I train my own set of images to create my own SVM classifier? I have close to 20000 images. Is this possible? If yes, how? can you please help?

**Comment by davisking** [comment]
github issues are for bugs or problems in dlib.

http://dlib.net/faq.html#Itdoesn'twork

**Comment by praveenlovely** [comment]
@davisking  Can you advise if it is possible?

**Comment by davisking** [comment]
Dlib is a machine learning and computer vision library.  Of course it is possible.

**Comment by praveenlovely** [comment]
I am using this http://dlib.net/train_object_detector.py.html link to train my detector for image recognition. 
However, in these lines, 
images = [io.imread(faces_folder + '/2008_002506.jpg'),
          io.imread(faces_folder + '/2009_004587.jpg')]

Do, I have to put all my 20000 images here with their bounding boxes? 
Is there a way to automate/simplify the process?

**Comment by praveenlovely** [comment]
I can understand that the algorithm generates a similarity score. But how can it be used to generate TP,FP, TN and FN to generate a confusion matrix? 
Any help on this regard is highly appreciated.
