### ISSUE TITLE
test_active_learning fails on ARM64

### ISSUE THREAD

**Issue by stefan-it** [davisking/dlib#313]
Hi,

the `test_active_learning` test fails on ARM64 - reproducible on my two test devices (ODROID-C2 and PINE64).

# Preparation for a more verbose output

First, the following `LINFO` command should be added to the `test_active_learning` test:

```diff
diff --git a/dlib/test/active_learning.cpp b/dlib/test/active_learning.cpp
index a60f6de..d7ad853 100644
--- a/dlib/test/active_learning.cpp
+++ b/dlib/test/active_learning.cpp
@@ -111,6 +111,7 @@ namespace
             //cout << "tsamples.size(): " << tsamples.size() << endl;
             const unsigned long num = tsamples.size();
             const double active = test_binary_decision_function(df, samples, labels)*s;
+           dlog << LINFO << "active: " << active;
             //cout << "test: "<< active;
             df = trainer.train(randomly_subsample(samples,num,i), randomly_subsample(labels,num,i));
             const double random = test_binary_decision_function(df, samples, labels)*s;
```

# Comparison with `x86_64`

The next table shows the values for the `active`, `active_learning_score` and `random_score` variable after the first unit test run for the

```cpp
DLIB_TEST(test_rank_unlabeled_training_samples(samples, labels, max_min_margin, 25, true) >= 0.97);
```
condition:

| `active` on ARM64  | `active` on  x86_64
| --------------------------   | ---------------------------
| 0.553288                   | 0.571429
| 0.503401                   | 0.569161
| 0.553288                   | 0.569161
| 0.553288                   | 0.687075
| 0.553288                   | 0.68254
| 0.553288                   | 0.707483
| 0.553288                   | 0.866213
| 0.553288                   | 0.85941
| 0.553288                   | 0.870748
| 0.553288                   | 0.904762
| 0.553288                   | 0.907029
| 0.84127                     | 0.907029
| 0.825397                   | 0.891156
| 0.8322                       |  0.891156
| 0.773243                   | 0.920635
| 0.811791                   | 0.941043
| 0.904762                   | 0.927438
| 0.884354                   | 0.918367
| 0.85941                     | 0.897959
| 0.852608                   | 0.895692
| 0.922902                   | 0.904762
| 0.936508                   | 0.920635
| 0.938776                   | 0.920635
| 0.931973                   | 0.956916
| 0.938776                   | 0.961451

For ARM64 the final result for the first unittest condition is calculated like:

| `active_learning_score` | `random_score`
| ---------------------------------- | -----------------------
| 18.2902                             | 19.3651

So `active_learning_score` / `random_score` = 0.9444929279993388

But the unittest condition demands a value `>= 0.97`, that's the reason why this test fails.

For x86_64:

| `active_learning_score` | `random_score`
| ---------------------------------- | -----------------------
| 20.0136                             | 19.3651

So `active_learning_score` / `random_score` = 1.0334880790700796

# Summary

The condition:

```cpp
DLIB_TEST(test_rank_unlabeled_training_samples(samples, labels, max_min_margin, 25, true) >= 0.97);
```

is not met on ARM64 in the ``test_active_learning` test. The output for the `active` variable is given, because this value differs for ARM64 compared to x86_64.

Please let me know if more logging output is needed :) Notice: I currently see three failed test cases on ARM64, so this issue described the first one.

**Comment by davisking** [comment]
Does the failure go away if you increase the number of iterations?

**Comment by stefan-it** [comment]
Yes, with `35` iterations, the test will succeed :) So a PR increasing the number of iterations is welcome?

**Comment by davisking** [comment]
Definitely :)
