### ISSUE TITLE
Issues with ENABLE_ASSERT and config.h (config.h.in)

### ISSUE THREAD

**Issue by caseymcc** [davisking/dlib#314]
dlib's CMakeLists forces ENABLE_ASSERTS on for debug builds 

```
# Make sure ENABLE_ASSERTS is defined for debug builds
if (NOT CMAKE_CXX_FLAGS_DEBUG MATCHES "-DENABLE_ASSERTS")
   set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DENABLE_ASSERTS" 
      CACHE STRING "Flags used by the compiler during C++ debug builds." 
      FORCE)
endif ()
```
without affecting cmakes var DLIB_ENABLE_ASSERTS, which sets up ENABLE_ASSERTS and DLIB_DISABLE_ASSERTS. Later when config.h is built using:

```
#cmakedefine ENABLE_ASSERTS       // asserts always enabled 
#cmakedefine DLIB_DISABLE_ASSERTS // asserts always disabled 
```
the wrong values are provided unless the developer knew to set DLIB_ENABLE_ASSERTS to true before calling cmake. Since the same config file is used for both release and debug this basically forces asserts for both if the developer ever plans to debug.

A simple fix for MSVC would be just to change the config.h.in to 

```
#ifdef _DEBUG //asserts force on for debug versions
#define ENABLE_ASSERTS
#undef DLIB_DISABLE_ASSERTS
#else
#cmakedefine ENABLE_ASSERTS       // asserts always enabled 
#cmakedefine DLIB_DISABLE_ASSERTS // asserts always disabled 
#endif
...
```

Ill put in a PR for this but I am not sure what should be done for GCC/Clang, etc... as I don't think _DEBUG is standard across the compilers. Is NDEBUG a good choice to key off of?

**Comment by davisking** [comment]
Yeah, that's a problem.  That if statement should also set the
DLIB_ENABLE_ASSERTS option to ON so config.h is generated correctly.

Although, I'm not sure what you mean by the same config.h file being used
in release and debug builds.  Are you trying to use the same compiled
version of dlib in different modes of visual studio?  You can't do that in
visual studio.  Here is a good article explaining visual studio's various
runtimes and why you can't mix them in a single application:
http://siomsystems.com/mixing-visual-studio-versions/.

Also, config.h must not change behavior based on any external signals (like
_DEBUG being defined).  The whole point of config.h is to ensure that the
same set of #defines that were in effect when the library was compiled are
used by any applications that use dlib.  Otherwise, there will be
violations of C++'s one definition rule and subsequent
ABI incompatibilities and other problems.

As an aside, you really should avoid building lib files in visual studio.
A much less error prone way to build C++ applications is to compile
everything together in the same project, as the examples included with dlib
show.

**Comment by caseymcc** [comment]
The config.h file is install to the same include folder that will be used whether you are compiling for a debug dlib lib or a release dlib lib. If you leave out DLIB_ENABLE_ASSERTS during the cmake build you will end up with dlibd.lib (debug lib, built with ENABLE_ASSERT) and a dlib.lib (release lib, build without ENABLE_ASSERT) and a config.h

```
/* #undef ENABLE_ASSERTS */
#define DLIB_DISABLE_ASSERTS // asserts always disabled 
```

so when you compile your app in debug using dlibd.lib it will fail. If you compile in release with dlib.lib it will succeed. If define DLIB_ENABLE_ASSERTS  for cmake it will work for both.

**Comment by davisking** [comment]
I wouldn't install them to the same folder.  That's asking for ODR
violations.

**Comment by caseymcc** [comment]
> As an aside, you really should avoid building lib files in visual studio.
> A much less error prone way to build C++ applications is to compile
> everything together in the same project, as the examples included with dlib
> show.

I am so far in the opposite mindset of this response that you would never get me to see your reasoning behind this so I plan to  just ignore this issue. :)

> I wouldn't install them to the same folder.  That's asking for ODR
> violations.

I am not sure what you are referencing about installing to the same folder? The includes or the libs?



If you run a cmake build now on the current cmakelists file, at the end of the compile you will end up with this

/installfolder/include/dlib
/installfolder/lib/
/installfolder/share/doc/

in /installfolder/include/dlib is the config.h file along with all other includes.
in /installfolder/lib/ is dlib.lib (release) and dlibd.lib (debug)

Normally from this point with a new project using dlib, I would just add /installfolder/include to the include search directories and /installfolder/lib to the lib search directories. Then I would compile for debug linking to dlibd.lib and release linking to dlib.lib.

If I do the above using dlib built without DLIB_ENABLE_ASSERTS during dlib's cmake build I end up with a config.h file like this:

```
...
/* #undef ENABLE_ASSERTS */
#define DLIB_DISABLE_ASSERTS // asserts always disabled 
...
```

If I then compile in debug mode I will get a linking error caused by the ENABLE_ASSERTS not being defined in the config.h but the library being built with it on. If I build with DLIB_ENABLE_ASSERTS on during the cmake build I get the following config.h:
```
...
#define ENABLE_ASSERTS  // asserts always enabled 
/* #undef DLIB_DISABLE_ASSERTS*/
...
```
and everything builds correctly (both debug and release). But I am forced to have the release version with ENABLE_ASSERTS on.

Now if I fix it with your suggestion above (adding DLIB_ENABLE_ASSERTS ON to the if (NOT CMAKE_CXX_FLAGS_DEBUG MATCHES "-DENABLE_ASSERTS"). Then ENABLE_ASSERTS will be always on for both debug and release as the if statement will always happen. The CMAKE_CXX_FLAGS_DEBUG check is high in the file and unless someone manual changes it somewhere else it will never have -DENABLE_ASSERTS in it. And once DLIB_ENABLE_ASSERTS is set ON for any reason it will be on for both the debug and release builds of dlib.

For me the fact that ENABLE_ASSERTS is forced on for debug build really means it not an config option any more so hard coding a pre-processor in the config file does not seem that odd. It seems like the following would work for all cases:

```
#ifdef NDEBUG
#cmakedefine ENABLE_ASSERTS       // asserts always enabled 
#cmakedefine DLIB_DISABLE_ASSERTS // asserts always disabled 
#else
#define ENABLE_ASSERTS // asserts always enabled for debug builds
#undef DLIB_DISABLE_ASSERTS
#endif
```

**Comment by davisking** [comment]
Visual studio has this odd notion of debug vs release, but other compilers (e.g. gcc) don't.  So what you are talking about only works in visual studio and messes up all other users.

**Comment by caseymcc** [comment]
Agreed, it is a hack.

Is there any particular reason to have the debug version force ENABLE_ASSERTS? If that force was not included there would be no issue for VS with this setup.

**Comment by davisking** [comment]
It's convenient to have it enabled since in environments other than visual
studio, when you want to debug something, you can go into ccmake to enable
debug mode, recompile, then debug and you don't need to remember to enable
asserts.  But for this case we can simply disable this if statement when
you are building dlib as a stand alone library, which is what the commit I
just pushed does.  So that should fix the problem :)

**Comment by caseymcc** [comment]
thanks, that sounds good.

**Comment by davisking** [comment]
No problem.  Thanks for pointing out this issue :)

**Comment by caseymcc** [comment]
FYI, the rabbit hole goes a little deeper. Testing your change today and I hit this in assert.h

```
#if !defined(DLIB_DISABLE_ASSERTS) && ( defined DEBUG || defined _DEBUG)
    // make sure ENABLE_ASSERTS is defined if we are indeed using them.
    #ifndef ENABLE_ASSERTS
        #define ENABLE_ASSERTS
    #endif
#endif
```

unless you specifically set DLIB_DISABLE_ASSERTS debug will still compile with ENABLE_ASSERTS while release compiles without it. The config.h file used during the build is all remarked out, it is only setup properly during install so it does not affect this statement. Easy enough to work around just thought you might like to know.

**Comment by davisking** [comment]
Oops.  That's definitely not right.  The two need to match.

**Comment by caseymcc** [comment]
also, DLIB_DISABLE_ASSERTS is not added to the CMAKE_CXX_FLAGS so asserts.h will never see that option. I made a change to the CMakeLists that includes it opposite ENABLE_ASSERTS. That allows me to control it via DLIB_ENABLE_ASSERTS ON/OFF to cmake.

```
option(DLIB_ENABLE_ASSERTS ${DLIB_ENABLE_ASSERTS_STR} OFF)
   if(DLIB_ENABLE_ASSERTS)
      # Set these variables so they are set in the config.h.in file when dlib
      # is installed.
      set (DLIB_DISABLE_ASSERTS false)
      set (ENABLE_ASSERTS true) 
      add_global_define(ENABLE_ASSERTS)
      remove_global_define(DLIB_DISABLE_ASSERTS)
   else()
      # Set these variables so they are set in the config.h.in file when dlib
      # is installed.
      set (DLIB_DISABLE_ASSERTS true)
      set (ENABLE_ASSERTS false) 
      remove_global_define(ENABLE_ASSERTS)
      add_global_define(DLIB_DISABLE_ASSERTS)
   endif()
```

**Comment by davisking** [comment]
It shouldn't be an option though.  It should just do the right thing, which
is to make sure compilation options are always consistent between what ends
up in config.h and what cmake really used.  I'll fix it later today.

**Comment by caseymcc** [comment]
True, it is just a quick fix. Seems you could removed the current config.h file from the source (or overwrite) and have cmake build it upfront in the source directory (rather than in the build folder during the install step) and copy it during install. However I don't know how that would affect the include only setups.

**Comment by davisking** [comment]
Ok, I think it should be fixed this time.  Thanks for pointing this problem out again :)
