### ISSUE TITLE
Aspect ratio dnn_mmod_ex issue

### ISSUE THREAD

**Issue by AndreaPisoni** [davisking/dlib#317]
I keep seeing this error when I try to run the mmod cnn on my dataset: `Encountered a truth rectangle with a width and height of 22 and 22.
The image pyramid and sliding window can't output a rectangle of this shape. 
This is because the rectangle's aspect ratio is too different from the detection window,
which has a width and height of 15 and 57.
`

If I change the mmod_options parameter the numbers change but the issue persist. I already used `cropper.set_randomly_flip(false);` to stop flipping but to no use.

**Comment by davisking** [comment]
Maybe you shouldn't rotate the image?  I don't know, but I'm not sure how I can explain the problem in clearer english than what I wrote in the error message.

**Comment by AndreaPisoni** [comment]
How am I rotating the image? I set max degree on the cropper to 0 and random flip to false

**Comment by davisking** [comment]
Oh, you didn't mention changing the max rotation degree.  In that case, you
must have a square box in your dataset.

**Comment by AndreaPisoni** [comment]
the objects I am trying to recognise are rectangular, think like bottles.
Will I be able to still detect them if I expand the bbox on training.xml to
be squared?

Il giorno dom 6 nov 2016 alle ore 19:57 Davis E. King <
notifications@github.com> ha scritto:

**Comment by davisking** [comment]
Probably, but that isn't the issue.  The error is telling you that you have
a box in your training dataset that has a very different aspect ratio from
all the others.  Since, in your case, the detector slides a tall and skinny
box over the images to find things it can't ever match a perfectly square
box.  That's what the error is saying.

**Comment by AndreaPisoni** [comment]
Ok I understand, so probably I was not precise enough when using imagelab.
I will write a script to force all the bboxes to have the same aspect ratio
and see how it goes.

Il giorno dom 6 nov 2016 alle ore 21:20 Davis E. King <
notifications@github.com> ha scritto:

**Comment by davisking** [comment]
That's probably the issue.  I'll update mmod to support multiple aspect
ratios in the near future.  But for now you have to be careful that your
data is uniform in this way.

**Comment by AndreaPisoni** [comment]
OK I re-did the labeling in imagelab skipping the more skewed objects. I do not see the error anymore, which is good. However, now I see an error saying that some truth rectangles are too close to the edges of the image to be recognized.

Now, I think my rectangles are reasonably distant from the borders, and I would like to recognize objects that are not in the center as well. Maybe it is possible to pad the image before feeding it to the network?

**Comment by davisking** [comment]
Objects don't need to be in the center.  Basically, the center of the
object needs to be inside the image.  But you can certainly pad the image
boundaries if you want.

**Comment by AndreaPisoni** [comment]
If that's the case, I should not get that error? I labeled the objects
manually with image lab and definitely all the objects are fully inside of
the picture...what's going wrong here?

**Comment by davisking** [comment]
It depends somewhat on the network architecture you pick.  Don't worry
about it.  Just pad your images a little.

**Comment by AndreaPisoni** [comment]
Ok thanks!! Can do pad through slob directly? Otherwise I will use opencv or something similar.

Thanks again for your help!

**Comment by davisking** [comment]
It can certainly be done with dlib in a variety of ways.  Like assigning to
a sub_image.  I would use whatever method you are most comfortable with.

**Comment by Benuraj** [comment]
@davisking 
> In that case, you must have a square box in your dataset.
Square annotation you mean? All the annotated objects need to be rectangle ?

**Comment by davisking** [comment]
All the annotations need to have more or less the same aspect ratio, whatever it may be.  This is because this is a sliding window detector with just one sliding window.   So it's impossible for it to detect things with widely varying aspect ratios.  I'll upgrade it in the near future to use multiple windows which will allow arbitrary aspect ratio mixtures.  But right now this is how it is.
