### ISSUE TITLE
How to add the output of two previous layers?

### ISSUE THREAD

**Issue by ly-atdawn** [davisking/dlib#318]
Hi.
If I have a net like this:
![net](https://cloud.githubusercontent.com/assets/23294606/20038794/6ffdbab8-a474-11e6-88b5-caa23fb4a35e.jpg)
How to add the output of fc1 and fc2 to get fc layers with add_prev or add_prev2? 
Thanks.

**Comment by davisking** [comment]
I don't know what to tell you.  add_prev literally does that.  But you already know about add_prev apparently.  Use add_prev?  I don't know what else to say.

**Comment by ly-atdawn** [comment]
Thanks.
I wrote the net like this:
`using TAG1 = fc<128,
                       con<64,5,5,1,1,
                       input<matrix<rgb_pixel>>>>; `  
  
`using TAG2 = fc<16,
                      con<16,3,3,1,1,
                      input<matrix<rgb_pixel>>>>;`

`using add1 = add_prev<TAG2, TAG1>;`

`using net_type = loss_multiclass_log<fc<58, add1>>;`
 
But is wrong. I don't konw how to use add_prev?

**Comment by davisking** [comment]
The second introductory example shows how to use add_prev.

**Comment by ly-atdawn** [comment]
Thanks a lot.
