### ISSUE TITLE
Reference to mutex is ambiguous 

### ISSUE THREAD

**Issue by anmoluppal** [davisking/dlib#32]
I get the following error while building the examples provided in the project:

[ 75%] Building CXX object CMakeFiles/parallel_for_ex.dir/parallel_for_ex.cpp.o
/Users/anmoluppal/Downloads/dlib-18.10/examples/parallel_for_ex.cpp:197:5: error: 
      reference to 'mutex' is ambiguous
    mutex m;
    ^
/Users/anmoluppal/Downloads/dlib-18.10/dlib/../dlib/threads/threads_kernel_2.h:38:11: note: 
      candidate found by name lookup is 'dlib::mutex'
    class mutex
          ^
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:27:24: note: 
      candidate found by name lookup is 'std::__1::mutex'
class _LIBCPP_TYPE_VIS mutex

**Comment by davisking** [comment]
You are using an old version of dlib.   Use a newer version and you don't get this error.
