### ISSUE TITLE
imglab --split option

### ISSUE THREAD

**Issue by thaiat** [davisking/dlib#321]
Hi,

There's seem to be a change between version v1.6 and v1.7 of imglab regarding the split option
* v1.6 : the result '_with_' xml file contains only annotation of the passed argument for split
* v1.7: the result '_with_' xml file contains any annotation as long as they are part of an image that contains the passed argument for split

**Comment by davisking** [comment]
yes

**Comment by thaiat** [comment]
any way to return to the previous behaviour, it was really usefull to test a algorithm against a single class

**Comment by davisking** [comment]
When you call load_image_dataset you can tell it to only load only boxes with a particular label (see http://dlib.net/dlib/data_io/load_image_dataset_abstract.h.html#load_image_dataset).  Or you could strip boxes from xml files imglab's --rmlabel command if you wanted to go that way.

**Comment by thaiat** [comment]
i understand but we are using command line for that, and rmlabel would mean that i need to give all the classes i dont want (about a hundred in my case) that i dont want...

**Comment by davisking** [comment]
Aren't you then using load_image_dataset() to load them?   

But in any case, I would be amenable to a pull request that added a --rm-other-labels or some such command to imglab :)

The reason --split is the way it is now is because it makes the transformation invertible and much more useful in the context of the other commands like --add.

**Comment by thaiat** [comment]
ok i ll try a PR
by the way dlib is amazing, if you'd like to see what we built with it i ll be happy to show you

**Comment by davisking** [comment]
Thanks :)

Sure, what did you guys build?

**Comment by thaiat** [comment]
image detection for shelves products i ll be happy to elaborate on skype
