### ISSUE TITLE
compilation of the python interface failed

### ISSUE THREAD

**Issue by ldv1** [davisking/dlib#325]
hi,

dlib 19.2 on Linux suse 42.1

I could compile and install dlib C++,
but I failed to compile the dlib python interface;
the command "python  setup.py install" issued:

[...]
[ 84%] Building CXX object CMakeFiles/dlib_.dir/src/other.cpp.o
In file included from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_io.h:14:0,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io.h:11,
                 from /home/laurent/Download/dlib-19.2/tools/python/src/other.cpp:7:
/home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_loader/load_image.h: In function ‘void dlib::load_image(image_type&, const string&)’:
/home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_loader/load_image.h:151:71: error: too many arguments to function ‘int DGifCloseFile(GifFileType*)’
                     DGifCloseFile(gif DLIB_GIFLIB_HANDLE_DIFF_VERSIONS);
                                                                       ^
In file included from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_loader/load_image.h:14:0,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_io.h:14,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io.h:11,
                 from /home/laurent/Download/dlib-19.2/tools/python/src/other.cpp:7:
/usr/include/gif_lib.h:182:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
In file included from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_io.h:14:0,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io.h:11,
                 from /home/laurent/Download/dlib-19.2/tools/python/src/other.cpp:7:
/home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_loader/load_image.h:156:75: error: too many arguments to function ‘int DGifCloseFile(GifFileType*)’
                         DGifCloseFile(gif DLIB_GIFLIB_HANDLE_DIFF_VERSIONS);
                                                                           ^
In file included from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_loader/load_image.h:14:0,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/../image_io.h:14,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io/load_image_dataset.h:9,
                 from /home/laurent/Download/dlib-19.2/dlib/../dlib/data_io.h:11,
                 from /home/laurent/Download/dlib-19.2/tools/python/src/other.cpp:7:
/usr/include/gif_lib.h:182:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
CMakeFiles/dlib_.dir/build.make:206: recipe for target 'CMakeFiles/dlib_.dir/src/other.cpp.o' failed
error: cmake build failed!

big thanks for any help !

regards,
Laurent

**Comment by davisking** [comment]
You apparently have a version of libgif with a different API.  All the
versions of libgif I have match the code in dlib.  I would try to figure
out why DLIB_GIFLIB_HANDLE_DIFF_VERSIONS isn't dealing with the API
variability correctly if I were you.

**Comment by ldv1** [comment]
I have libgif 5.0.5;
which version are you using precisely ?

**Comment by davisking** [comment]
I test against versions of libgif in the 4.0 and 5.0 series including 5.1.2
and 4.1.6 as well as a few others.  Anyway, it's probably a simple fix.
But I can't replicate it so you will have to figure it out.

**Comment by ldv1** [comment]
I've just compiled and installed the latest libgif version and I could compile the dlib python interface. Thanks for your help.

**Comment by davisking** [comment]
No problem.
