### ISSUE TITLE
Imglib not building properly

### ISSUE THREAD

**Issue by ThorbjornSomod** [davisking/dlib#326]
Hi!

I just cloned your repo for dlib and was planning on using your fHOG feature extractor for a project I'm working on. Unfortunately the Imglab tool for creating the .xml files used in the extractor doesn't seem to build properly. This is what I've done so far:

- Cloned your repo to C:\
- Made a build folder inside at C:\dlib\
- Run `cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=C:\dlib`
- Run `cmake --build . --config Release --target install`
- And `cmake --build . --config Debug --target install`
- Opened the Project.sln and build ALL_BUILD and INSTALL in both Debug and Release mode

I then went into the C:\dlib\tools\imglab folder but noticed that imglab had not been built. I then created a build folder in the imglab folder and repeated the process above by generating the imglab.sln project. I tried to build it's ALL_BUILD and INSTALL in both Debug and Release mode, but for some reason building INSTALL results in this error log:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133	
```

Do you know of any fixes for this? I really want to use dlib!

**Comment by davisking** [comment]
It's probably just telling you that you don't have write access to c:\program files. 

Anyway, don't bother running the install target.  Just take the exe file and put it wherever you want and run it.

**Comment by ThorbjornSomod** [comment]
Well where is this exe file located? I can't seem to find any exe file in the Imglab folder.

**Comment by davisking** [comment]
The exe file is in the build folder you created.  In a subfolder called Release.  That's how visual studio works.  It has nothing to do with dlib.
