### ISSUE TITLE
Find contours in image

### ISSUE THREAD

**Issue by symisc** [davisking/dlib#329]
Hi,
is there a function or a method in Dlib to find object contours (any object) in a given image without passing by trainer approach?

**Comment by davisking** [comment]
This is an ill-posed problem, so there are lots of techniques that do this
depending on exactly what is meant by "the objects I want".  For example,
there are these functions in dlib:
http://dlib.net/imaging.html#segment_image,
http://dlib.net/imaging.html#skeleton, or even just classic edge detection:
http://dlib.net/image_ex.cpp.html.

However, you will probably need to design something that is appropriate for
your particular idea of what "my object" is.
