### ISSUE TITLE
Issues with opening .xml file in dlib hog feature extraction

### ISSUE THREAD

**Issue by ThorbjornSomod** [davisking/dlib#331]
Hi!

Im trying to use DLIB's tools to extract fHoG features from a dataset of .bmp images. I have used the imglab tool provided by DLIB to create the .xml file used in extracting the features, but when I try to open up the file with this call:

`dlib::load_image_dataset(images_train, object_boxes_train, object_directory+"/test.xml");`

I get an image load error. My .xml file is written on this form:

```
<?xml version='1.0' encoding='ISO-8859-1'?>
<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>
<dataset>
<name>imglab dataset</name>
<comment>Created by imglab tool.</comment>
<images>
  <image file='positive\pos1.bmp'>
    <box top='926' left='652' width='717' height='301'/>
  </image>
  <image file='positive\pos10.bmp'>
    <box top='858' left='578' width='783' height='344'/>
```

When I tried to debug the error it seems that load_image_dataset thinks that my .xml file is empty. Do you have any ideas as to how I could fix this? I spent a couple of hours marking all the objects, and would rather not have all that time be spent in vain. I am working in Visual Studio 15 on Windows 10. Thanks in advance for any help!

PS: This is the rest of my code for the extraction:

```
void hogFeatureExtraction() {

    String object_directory = "C:/Users/xxxxxx/Documents/Visual Studio 2015/Projects/xxxxxxxx/xxxxxxxx/fhog_feature_extraction";

    dlib::array<dlib::array2d<unsigned char>> images_train;

    std::vector<std::vector<dlib::rectangle>> object_boxes_train;

    dlib::load_image_dataset(images_train, object_boxes_train, object_directory+"/test.xml");

    typedef dlib::scan_fhog_pyramid<dlib::pyramid_down<6>> image_scanner_type;

    image_scanner_type scanner;

    scanner.set_detection_window_size(75, 30);

    dlib::structural_object_detection_trainer<image_scanner_type> trainer(scanner);

    trainer.set_num_threads(4);

    trainer.set_c(1);

    trainer.be_verbose();

    trainer.set_epsilon(0.01);

    dlib::object_detector<image_scanner_type> detector = trainer.train(images_train, object_boxes_train);

    dlib::image_window hogwin(draw_fhog(detector), "Learned fHOG detector");

}
```

PPS: I also submitted this issue on StackOverflow, and I will close both of the posts as soon as I solve this issue :)

**Comment by davisking** [comment]
http://dlib.net/faq.html#Itdoesn'twork

Note, you didn't mention the specific error message or error code or anything like that.

**Comment by ThorbjornSomod** [comment]
Ah, sorry for not providing enough information on the topic. I have updated the original post with the information you asked for and included what version of DLIB I'm using. As you say it is probably some user error, but seeing as I have no one else to ask, I thought I'd try on the repo page.
