### ISSUE TITLE
Correlation tracker 

### ISSUE THREAD

**Issue by edmBernard** [davisking/dlib#332]
I got an error when i use correlation tracker.
it appear there is missing include in the file `image_processing/correlation_tracker.h`.

the current included files
```
#include "correlation_tracker_abstract.h"
#include "../geometry.h"
#include "../matrix.h"
#include "../array2d.h"
#include "../image_transforms/assign_image.h"
```
we need this 2 more include
```
#include "../image_transforms.h"
#include "../image_transforms/interpolation_abstract.h"
```

otherwise there is issues with 
`interpolate_bilinear()`
and 
`chip_details`

**Comment by davisking** [comment]
Thanks.  Should be fixed now.
