### ISSUE TITLE
import the library to your build.gradle

### ISSUE THREAD

**Issue by touseefahmad** [davisking/dlib#335]
i am trying to import dlib into my project using 
repositories {
    maven {
        url 'https://dl.bintray.com/tzutalin/maven'
    }
}

dependencies {
    compile 'com.tzutalin.dlib-android-app:dlib:1.0.3'
} 
 i have added  repo to project gradle file and 
compile 'com.tzutalin.dlib-android-app:dlib:1.0.3' to app module gradle file 

bit it shows error:
Error:(25, 20) Failed to resolve: com.tzutalin.dlib-android-app:dlib:1.0.3
gradle version is 
classpath 'com.android.tools.build:gradle:2.1.0' can some help me what is the issue and how can i resolve it

**Comment by davisking** [comment]
This isn't part of the dlib project.  I would suggest contacting whoever is running https://dl.bintray.com/tzutalin/maven
