### ISSUE TITLE
Xavier initialization and ReLu

### ISSUE THREAD

**Issue by AndreaPisoni** [davisking/dlib#339]
Hi Davis,

I have seen in the docs that you use the "Xavier initialization" described in http://jmlr.org/proceedings/papers/v9/glorot10a/glorot10a.pdf to set up the network parameters. 

However, I saw in some of your examples you use rectified linear units (ReLu) in between the layers . A 2015 paper from Kaiming He (resnet guy) says the Xavier initialization should not be used with ReLu as the network might not be able to converge properly.  

The paper I am referring to is here: https://arxiv.org/pdf/1502.01852v1.pdf,  _Comparisons with “Xavier” Initialization_ chapter. The initialization proposed in the paper is actually very similar to Xavier, just adds an extra factor. 

What do you think? Should we change the initialisation, or at least overload randomize_parameters  to have both?

**Comment by davisking** [comment]
Yes, I know about this.  I haven't had any trouble with the existing
initialization.  However, a more general way of initializing layers is also
needed.  So if you want to propose something that's fine with me.  I'll get
around to improving it eventually, but to my mind it's relatively low
priority.

**Comment by AndreaPisoni** [comment]
Sure I will open a PR if I ever get the time to do it after I am done with my detection program.
