### ISSUE TITLE
sparse cholesky decomposition and triangular solver in solve_trust_region_subproblem 

### ISSUE THREAD

**Issue by ShuangLiu1992** [davisking/dlib#345]
Hello Davis,

I'm trying to write a sparse version of `solve_trust_region_subproblem` by replacing `dlib::chol` with cholmod in suitesparse, however I have noticed that the result obtained from `triangular_solver(CblasLeft, CblasLower, CblasTrans, CblasNonUnit, R, p);` and `triangular_solver(CblasLeft, CblasLower, CblasNoTrans, CblasNonUnit, R, p);` are different from what I get from suitesparse.

I know that dlib's implementation is based on Numerical Optimization by Nocedal and Wright, and the result of `p` is the same as the result returned by cholmod_spsolve(CHOLMOD_A), but I just couldn't find a combination of CHOLMOD_*, when applied to -g and p, that produce a q similar to the one in dlib.

After various attempts I just used  `CHOLMOD_Lt` and `-g` to solve for `q`, which produce a numerically similar result for `std::pow(q_norm / p_norm, 2)`, since p is the same and q is just used for adjusting lambda, surprisingly they both converge to the same solution. Nevertheless I fear something might go wrong in the future. Do you know why this would happen and whether it's a numerical stability issues or bug?

I'm compiling dlib with lapack and blas shipped with ubuntu, I suppose it might have something to do with lapack implementation as well?

**Comment by davisking** [comment]
I have no idea.  There are a large number of possible reasons why you might end up with different results, none of which I can infer based on the information you posted.  I would refer to the Nocedal and Wright book for the best methods to solve large sparse trust region problems.  I also don't think the best thing to do is to simply try and convert some of the calls in dlib to sparse LAPACK calls.  But in any event, refer to the book for more information.

**Comment by ShuangLiu1992** [comment]
Would posting the content of `B + lambda * dlib::identity_matrix<double>(B.nr())` help you to infer what's going on? I was printing each variable in both dlib and my implementation to see where things went wrong, and it lead me to dlib::chol.

I read Chapter 4.3 of Numerical Optimization a couple of times, but the way triangular_solver is called in dlib really confuses me, due to my limited knowledge of how things work in dlib, it doesn't seem to me that it's doing what the book says it should, although the result of p is the same as the result from other library, i.e. suitesparse but q isn't, don't know if you are in a bad mood or too busy working on other things, but it could just be a bug and some simple investigation might fix it.

Thanks.

**Comment by davisking** [comment]
Not in a bad mood. I'm just busy and this doesn't sound like a bug in dlib. Most importantly, the routine works. And in general two numerical pieces of software aren't going to exactly mirror each other. So just being different is not a reason to expect a bug. If you find a case that leads to incorrect results then that would be very different.
