### ISSUE TITLE
Finding OpenBLAS but not colas when trying to build with guy support

### ISSUE THREAD

**Issue by KajaStene** [davisking/dlib#346]
I am getting a confusing output when trying to build dlib with cmake, it outputs  No package 'cblas' found and  No package 'lapack' found but then later Found OpenBLAS library and  Found LAPACK library. It goes on to say that there is no GUI support so it will but build a bunch of files. 

So I interpreted this to mean that it will not build with GUI support because it cannot find cblas and lapack, but how can I fix this when it also finds OpenBLAS (which should contain cblas) and lapack?

Here goes the full output: 

$ cmake ..
-- C++11 activated.
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Found OpenBLAS library
-- Found LAPACK library
No GUI support, so we won't build the dnn_imagenet_ex example.
No GUI support, so we won't build the dnn_mmod_ex example.
No GUI support, so we won't build the dnn_mmod_face_detection_ex example.
No GUI support, so we won't build the random_cropper_ex example.
No GUI support, so we won't build the dnn_mmod_dog_hipsterizer example.
No GUI support, so we won't build the 3d_point_cloud_ex example.
No GUI support, so we won't build the bayes_net_gui_ex example.
No GUI support, so we won't build the face_detection_ex example.
No GUI support, so we won't build the face_landmark_detection_ex example.
No GUI support, so we won't build the fhog_ex example.
No GUI support, so we won't build the fhog_object_detector_ex example.
No GUI support, so we won't build the gui_api_ex example.
No GUI support, so we won't build the hough_transform_ex example.
No GUI support, so we won't build the image_ex example.
No GUI support, so we won't build the mpc_ex example.
No GUI support, so we won't build the object_detector_advanced_ex example.
No GUI support, so we won't build the object_detector_ex example.
No GUI support, so we won't build the one_class_classifiers_ex example.
No GUI support, so we won't build the surf_ex example.
No GUI support, so we won't build the train_object_detector example.
No GUI support, so we won't build the video_tracking_ex example.
No GUI support, so we won't build the webcam_face_pose_ex example.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kaja/Downloads/dlib-master/examples/build

**Comment by davisking** [comment]
All of those messages are unrelated to each other.  There are different packages called 'cblas', 'lapack', and 'openblas'.  This also has nothing to do with having a GUI.

**Comment by KajaStene** [comment]
But then, if you dont mind, how can I get dlib with GUI-support?

**Comment by davisking** [comment]
Run cmake in a clean folder and paste the entire output here.

**Comment by KajaStene** [comment]
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++11 activated.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.1")
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - not found
-- Found LAPACK library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Could NOT find CUDA: Found unsuitable version "7.0", but required is at least "7.5" (found /usr/local/cuda)
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
OpenCV not found, so we won't build the webcam_face_pose_ex example.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kaja/Downloads/dlib-master/examples/build

**Comment by davisking** [comment]
Where are the messages about not enabling the GUI?

**Comment by KajaStene** [comment]
That seemed to fix it, thank you very much :)
