### ISSUE TITLE
Does color space matters for for dlib?

### ISSUE THREAD

**Issue by grisevg** [davisking/dlib#347]
Should I take into account human eye correction when extracting monochrome image, e.g:
`Gray = (Red * 0.2126 + Green * 0.7152 + Blue * 0.0722)`
or just do simple average `Gray = (Red + Green + Blue) / 3`?

I'm specifically interested in effects on the CNN and Face Alignment algorithms.
As far as I understand, it doesn't matter as long as I use the same conversion for both training and testing, but I'd like to be sure.

Thank you

**Comment by davisking** [comment]
I wouldn't worry about it as long as you are consistent.
