### ISSUE TITLE
Raspberry Pi 3 Install Crash

### ISSUE THREAD

**Issue by StuartIanNaylor** [davisking/dlib#351]
Hi, apols as a bit of a noob but both pip and python setup.py install both get to about 88% and crash the Pi.
Complete crash and total hang so I can not really say more.

The Pi is completely up to date with the recent dist-upgrade and rpi-update so maybe something in the new kernel?

I am going to go back to the original image before the latest rpi-update and try again.

Just wondered if anyone has any toptips :)

Also I saw a section about NEON is that working and how do you include?

Did the sudo apt-get install libboost-python-dev cmake

It mentions something about OpenBlas but only needed for optimisation.

Both pip install dlib and pip install scikit-image get to 88% and bang well more of a blank screen whimper.

**Comment by StuartIanNaylor** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?p=983001#p983001

Its the Pi and not enough memory, logout and close all unnecessary services and then run.

**Comment by StuartIanNaylor** [comment]
Only reopened so that other numb noobs such a myself dont do the same.

python setup.py build
then
python setup.py install

doh.

**Comment by davisking** [comment]
Don't worry about it :)
