### ISSUE TITLE
dlib 19.2 - python bindings crash on Ubuntu 16.04

### ISSUE THREAD

**Issue by cbruccoleri** [davisking/dlib#352]
I successfully compiled and installed 19.2 C++ version, including examples, which seem to work fine.

I also successfully compiled the python bindings. However the (minimal) code below results in a core-dump.
```
1. import dlib
2. win = dlib.image_window()
```
Execution of line 2 results in:
> Illegal instruction (core dumped)
Stack trace shows the error occurs in:
[0] dlib::button::set_size(..)

I compiled the library with the following packages:
libboost1.58-all-dev
libboost-python1.58.0

Python 2.7 is the default interpreter (python). Python3 is also installed as python3, by the  Ubuntu installation.

Any suggestions? I stress that the C++ version of the library works just fine.

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework

**Comment by davisking** [comment]
In particular, you probably have other copies of python or boost that you
don't know about.  Or they aren't compiled against what you think they are.

**Comment by cbruccoleri** [comment]
Davis,
Thank you. I had seen the FAQ, but it did not seem to be the same problem I was having since the python bindings do compile and the `import dlib` statement does not cause any issue. I will dig more into my system to check what version mismatch there might be and I will report back.
Christian

**Comment by cfoch** [comment]
I have the exact problem. Please, let me know what you have tried so far. It happens in Arch Linux as in Ubuntu. This is what journalctl tells:

> ris 27 10:26:50 fabian-ubuntu kernel: traps: python3[2880] trap invalid opcode ip:7fbabfa6a3ed sp:7ffdcae2e098 error:0 in dlib.so[7fbabf514000+

**Comment by davisking** [comment]
Try the latest code in github.  There was a change this morning that might cause the correct dependent python libraries to be linked in more often.
