### ISSUE TITLE
Can not find boost

### ISSUE THREAD

**Issue by wasamisam0119** [davisking/dlib#353]
![snip20161205_5](https://cloud.githubusercontent.com/assets/17445431/20889601/78db1034-bafb-11e6-848c-ea4aa600ae2b.png)
![snip20161205_6](https://cloud.githubusercontent.com/assets/17445431/20889666/aead3b60-bafb-11e6-9b3a-5dc08445c612.png)

Is it found the boost lib or not?  Where I should put the boost library in?  which root it checks the for the boost?

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework

Also, don't post screenshots, especially ones where the text is truncated.

**Comment by wasamisam0119** [comment]
thanks for replying so quickly!

2016年12月5日 下午3:12，"Davis E. King" <notifications@github.com>写道：
