### ISSUE TITLE
input_grayscale_image_pyramid?

### ISSUE THREAD

**Issue by grisevg** [davisking/dlib#354]
It's probably a stupid question, but could you explain why there isn't an `input_grayscale_image_pyramid` that works on `matrix<unsigned_char>` instead of `matrix<rgb_pixel>` in `input_rgb_image_pyramid`?

Does CNN behave better on coloured images than on grayscale?

**Comment by davisking** [comment]
Yes, in many applications color is useful.  Although sometimes it obviously
doesn't matter.  So there isn't any reason why there couldn't be a
grayscale version of the input layer.

**Comment by grisevg** [comment]
So the only practical reason to make `input_grayscale_image_pyramid` would be to safe performance?

**Comment by davisking** [comment]
Right.

**Comment by grisevg** [comment]
Thank you very much for clarifying that
