### ISSUE TITLE
imglab tool cannot edit the image under windows 

### ISSUE THREAD

**Issue by stereomatchingkiss** [davisking/dlib#355]
Cannot edit the bounding box by imglab under windows 10, 64bits.
I pull the dlib from master, so the codes are same as the one at github(7/12/2016).
More precisely, I can open the imglab, the imglab can load the image, switch the image by up/down arrow but I cannot enlarge the imglab.
It always stay around taskbar of windows

![sample](https://s15.postimg.org/q0g1qef2z/imglab_bug.png "imglab around taskbar")

The steps to reproduce the problem

1 : Download the traininig data from [kaggle](https://www.kaggle.com/c/the-nature-conservancy-fisheries-monitoring/data), because of the NDA, I cannot upload the images.
2 : Unzip the train data
3 : Go to the training folder(ex : c:\Users\davis\kaggle\train)
4 : Enter command "imglab -c lag_labels.xml LAG" by command prompt
5 : Enter command "imglab lab_labels.xml" by command prompt 

After that you would find out imglab cannot enlarge but always stay around the taskbar

**Comment by davisking** [comment]
I'm not going to sign up for kaggle and sign an NDA.  Please post some image that reproduces the issue.  Make up a fake image if you have to.  

Also, I don't understand what "I cannot enlarge the imglab" means.  You can't resize the window?  I also don't see any problem in the screenshot you posted.  It's just showing the program working normally.

**Comment by stereomatchingkiss** [comment]
I will upload the images when I find the images can produce the same issue.

>Also, I don't understand what "I cannot enlarge the imglab" means.

imglab always "minimize" and stay around the taskbar, I cannot make it show on the screen.Hard to explain, maybe I should record a video. This phenomenon only happens when I use extend screen mode, if I open the imglab under "pc screen only" mode, everything are fine.

**Comment by davisking** [comment]
Huh, weird.  Let me know when you find a way to reproduce it and I'll take a look.

**Comment by sutr90** [comment]
@stereomatchingkiss Are you sure the imglab window is moved to another screen?

Ex: You connect to another display, and setup dual screen configuration in Windows. If the another screen is setup as main display, new program windows will prefer to show up on the main display, regardless what screen are you looking at. Maybe the setting is stuck or Windows misbehave?

**Comment by stereomatchingkiss** [comment]
>Are you sure the imglab window is moved to another screen?

I cannot move it at all, because imglab always stay at minimum state. I
move my mouse to the imglab icon on taskbar, click it, but it still stay at
minimum state.

>dual screen configuration in Windows

Not sure we are talking the same mode or not, I am using extension mode,
this mode "combine" two windows together.

>Maybe the setting is stuck or Windows misbehave?

But other apps work, like adobe reader, QtCreator, notepad++, so I guess
there are something preventing the windows show up. However, I need to find
out the images which cause this issue.



2016-12-10 2:45 GMT+08:00 sutr90 <notifications@github.com>:
