### ISSUE TITLE
dnn_mmod_face_detection_ex doesn't return 

### ISSUE THREAD

**Issue by Puneetsharma030** [davisking/dlib#357]
Hi,

I am trying to the dnn_mmod_face_detection_ex example from the example set. In the example after loading the model and test image, the example executes 
     auto dets = net(img);
This function then never returns and the gets stuck inside function

        const tensor& forward(const tensor& x)
        {
            subnetwork->forward(x);
            const dimpl::subnet_wrapper<subnet_type> wsub(*subnetwork);
            if (!this_layer_setup_called)
            {
                details.setup(wsub);
                this_layer_setup_called = true;
            }
            if (this_layer_operates_inplace())
                impl::call_layer_forward(details, wsub, private_get_output());
            else
                impl::call_layer_forward(details, wsub, cached_output);
            gradient_input_is_stale = true;
            return private_get_output();
        }
in core.h

 The subnetwork->forward(x); invocation seems to be the source of the problem.

I am using visual studio 2015 update 3 on windows to build and run the examples.

**Comment by davisking** [comment]
How long did you wait?  http://dlib.net/faq.html#Whyisdlibslow

**Comment by Puneetsharma030** [comment]
I waited for more than 10 minutes for one image. In the command line arguments I was using 
mmod_human_face_detector.dat test.jpg

Its a release build, with USE_AVX_INSTRUCTIONS enabled.

The input image is a RGB .jpg image with dimensions, 500x375

**Comment by davisking** [comment]
What happens when you compile with cmake and then run the example program on the provided images, and you don't make any modifications to any of the code?

**Comment by Puneetsharma030** [comment]
Hi, I get the same behavior. I am attaching the screenshot and configurations for my visual studio.

![cmake](https://cloud.githubusercontent.com/assets/5556978/21147499/8bb0cd74-c155-11e6-904b-7bc804803099.png)
![project](https://cloud.githubusercontent.com/assets/5556978/21147504/8e9f59c4-c155-11e6-8ac9-d0d2e06cfc2c.png)

**Comment by davisking** [comment]
Run it on the command line, not inside visual studio.

**Comment by Puneetsharma030** [comment]
same behavior. 
![untitled](https://cloud.githubusercontent.com/assets/5556978/21147766/66223ea2-c156-11e6-91bc-666813234e07.png)

**Comment by davisking** [comment]
I tested this and it does work.  Maybe you are running out of RAM or your CPU doesn't support AVX instructions.   Also, that example upsamples those images a whole lot, so if you don't run the program with any acceleration like CUDA or the intel MKL then it will take a long time to run.  Remove the upsampling in the example and see if it runs.

**Comment by Puneetsharma030** [comment]
Hi,

If I want to run the program without any GPU support, how much time should I expect the program to take to process one image of size 640x480 which has just one face inside. (given that my CPU supports AVX)

http://blog.dlib.net/2016/10/easily-create-high-quality-object.html

In this blog, it is mentioned that it should take about 370 ms for an image size of 640x480. Is it the same model which is provided as a link in example program? Should I be able to obtain the same results using CPU?

Thanks!

**Comment by davisking** [comment]
Yes, it's the same model.  You should get similar times.  You have to
compile your program with optimizations and use a decent BLAS library like
the Intel MKL though.

**Comment by Puneetsharma030** [comment]
Hi Thanks alot! initially I was using open_blas for BLAS and it was probably causing the crash with CPU. now with MKL, it returns and takes around 400 ms on images with size 500x375 without any up-scaling (I disabled that pyramid_up). The 370 ms reported in the blog is without any up-scaling as well?

**Comment by davisking** [comment]
Yes
