### ISSUE TITLE
Use function multi-versioning (on supported platforms) to ensure optimized code whenever possible

### ISSUE THREAD

**Issue by severin-lemaignan** [davisking/dlib#36]
`gcc-4.8` introduced the concept of [function multiversioning](https://gcc.gnu.org/wiki/FunctionMultiVersioning) to ease support of SSE/AVX (or any other ISA specific optimization) be providing automatic runtime enabling of optimized code when supported by the CPU.

While this would introduce `gcc` specific code into `dlib`, it would ensure that optimized code is always used (on platforms supporting `gcc`) when supported by the host CPU.

**Comment by severin-lemaignan** [comment]
Btw, ``clang`` also supports a similar system with attributes, for instance ``__attribute__((target("fpmath=387"))``

**Comment by davisking** [comment]
If there is a way to do this that doesn't negatively impact dlib's portability or usability then I'm all for it.  However, it's not immediately clear to me how we would change the code to use this feature.  What did you have in mind?

**Comment by severin-lemaignan** [comment]
To take an example ([simd8f.h:160](https://github.com/davisking/dlib/blob/master/dlib/simd/simd8f.h#L160)), the current code:

```cpp
    inline simd8f operator+ (const simd8f& lhs, const simd8f& rhs) 
    { 
#ifdef DLIB_HAVE_AVX
        return _mm256_add_ps(lhs, rhs); 
#else
        return simd8f(lhs.low()+rhs.low(),
                      lhs.high()+rhs.high());
#endif
    }
```

would become:
```cpp
__attribute__ ((target ("default")))
inline simd8f operator+ (const simd8f& lhs, const simd8f& rhs) 
{ 
        return simd8f(lhs.low()+rhs.low(),
                      lhs.high()+rhs.high());
}

__attribute__ ((target ("avx")))
inline simd8f operator+ (const simd8f& lhs, const simd8f& rhs) 
{ 
        return _mm256_add_ps(lhs, rhs);
}
```
``gcc`` would automatically generate the dispatch code so that, *at runtime*, either the default or the AVX versions are used, depending on what the CPU supports.

It is probably necessary to put this code within ``gcc`` fences to maintain portability on VS (so I guess it would simply be easier to have a ``simd8f-multiversioning.h`` version of ``simd8f.h``).

Please note that *I do not* intend to submit pull requests  implementing these changes in the foreseeable future. I opened this issue merely to track possible future feature, relevant to ``dlib``.

**Comment by davisking** [comment]
From the description on gcc's web page it sounds like using that feature will not produce inline functions but instead perform a full function pointer based call each time operator+ is called.  Have you tried any version of this?  I expect that doing this would make the code run much slower, like maybe an order of magnitude slowdown, if the functions are not inlined into the call sites.

**Comment by severin-lemaignan** [comment]
I did not try any of these, and indeed, if it breaks inlining, then it defeats much of the point in our case.

Multiversioning + inlining has been [discussed on GCC mailing list](https://gcc.gnu.org/ml/gcc/2012-03/msg00074.html), but I did not tracking down all the discussion thread to know if and how this has been eventually implemented.
