### ISSUE TITLE
USE_AVX_INSTRUCTIONS in cmake - is it ignored?

### ISSUE THREAD

**Issue by pliablepixels** [davisking/dlib#360]
Hi there, building dlib using 
```
cmake ..  -DUSE_AVX_INSTRUCTIONS=ON
```

Produces this warning
```
CMake Warning:
  Manually-specified variables were not used by the project:
    USE_AVX_INSTRUCTIONS
```

I don't see this flag in subsequent make commands. Does this mean AVX_INSTRUCTIONS are not being used? 

I noticed this PR that is not yet merged as it has open issues to resolve:
https://github.com/davisking/dlib/pull/234

So what do I need to do to enable AVX for now? thanks

**Comment by davisking** [comment]
It's not ignored.  However, you must be building the dlib shared library, and that part of the code doesn't use it.   You have to appreciate that 95% of the code in dlib is templated and so lives in header files.  So when you "build dlib" it's building almost nothing.

**Comment by pliablepixels** [comment]
Thanks - I am building both shared and static. I'm following [these](http://dlib.net/compile.html) instructions. I didn't realize most of dlib lives in header files. So I suppose adding `-mavx` to my project that uses dlib is what I need to make sure dlib runs as fast as it can (with the exception of also installing cuda - its a 1.8GB behemoth that keeps failing to download)

**Comment by davisking** [comment]
Those instructions don't tell you to compile the CMakeLists.txt in the dlib
folder.  They tell you to compile the examples folder.  If you did that you
wouldn't have these issues.

**Comment by Climax777** [comment]
How would you enable `avx` instructions for the shared library via `cmake` @davisking?

**Comment by davisking** [comment]
I'm not talking about the shared lib at all.  For that, you don't need to set anything regarding avx since dlib is pretty much a header only library.  None of the stuff that ends up in the shared library part has anything to do with avx or not avx.

**Comment by Climax777** [comment]
Excellent thats what I wanted to know. Thanks

**Comment by sharpstill** [comment]
@davisking I am using python to call import dlib, because you said shared library part has nothing with optimized, so python cannot get speed up in dlib?

**Comment by davisking** [comment]
Not in python, think about it, when you use python the only thing there is it he dlib.so file.  So all the optimizations have to be in there.  This issue you are posting about is talking about something else.  If you want it to run faster in python then go ahead and enable AVX instructions or whatever instruction set makes sense for your machine.
