### ISSUE TITLE
Error detected in function dlib::cv_image<pixel_type>::cv_image(cv::Mat) [with pixel_type = dlib::bgr_pixel].

### ISSUE THREAD

**Issue by sarmadm** [davisking/dlib#361]
When I execute ./webcam_face_pose_ex , the video file plays normally and just before it ends this error is displayed :+1: 

Error detected at line 36.
Error detected in file /home/tofi/dlib/dlib/../dlib/opencv/cv_image.h.
Error detected in function dlib::cv_image<pixel_type>::cv_image(cv::Mat) [with pixel_type = dlib::bgr_pixel].

Failing expression was img.depth() == cv::DataType<typename pixel_traits<pixel_type>::basic_pixel_type>::depth && img.channels() == pixel_traits<pixel_type>::num.
The pixel type you gave doesn't match pixel used by the open cv Mat object.
	 img.depth():    0
	 img.cv::DataType<typename pixel_traits<pixel_type>::basic_pixel_type>::depth: 0
	 img.channels(): 1
	 img.pixel_traits<pixel_type>::num: 3

**Comment by davisking** [comment]
Sounds like you modified the program to read from a file but forgot to
check for end of file.
