### ISSUE TITLE
DNN_mmod_face_Detection Python wrapper issue 

### ISSUE THREAD

**Issue by Samarth-991** [davisking/dlib#362]
Hello Davis 
As per my application which is face recognition and detection . For recognition I am using Python code (As I am using Theano and Keras ) but for detection I am using  your DNN_MMOD_FACE_DETECTION code on C++ . Hence I am passing image (in nd_array) to c++ code which converts it into cv::Mat . Then I pass  the image to the the Face detect function which is your DNN_MMOD_Face_detection . I call the test_np_mat from python by passing the frame simply . 

So I have made a Python wrapper for it using boost . On my PC which is not having a GPU its running well without any issue but when I ran the same code on a different PC with GPU and CUDA enabled the code crashes producing error.The point where it crashes is at line **"auto dets = net(img)"**. On the same PC when I ran the code from your native dlib library and it worked perfectly .  I have provided the entire code below.  

" Error detected at line 1718.
Error detected in file /home/tapas/dlib-19.2_3/dlib/dnn/cpu_dlib.cpp.
Error detected in function void dlib::cpu::tensor_conv::operator()(dlib::resizable_tensor&, const dlib::tensor&, const dlib::tensor&, int, int, int, int).

Failing expression was filters.nr() <= data.nr() + 2*padding_y.
Filter windows must be small enough to fit into the padded image.
"
-------------------------------------------------------------- Code --------------------------------------------------- 

`// Wrapper for most external modules
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
#include <exception>

// Dlib Includes
#include <dlib/dnn.h>
#include <dlib/data_io.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>
#include <dlib/opencv.h>
// Opencv includes
#include <opencv2/opencv.hpp>
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION

using namespace std;
namespace py = boost::python;
using namespace dlib;
int facedetect( cv::Mat); // MY function which will detect faces . 
// ----------------------------------------------------------------------------$
template <long num_filters, typename SUBNET> using con5d = con<num_filters,5,5,2,2,SUBNET>;
template <long num_filters, typename SUBNET> using con5  = con<num_filters,5,5,1,1,SUBNET>;

template <typename SUBNET> using downsampler  = relu<affine<con5d<32, relu<affine<con5d<32, relu<affine<con5d<16,SUBNET>>>>>>>>>;
template <typename SUBNET> using rcon5  = relu<affine<con5<45,SUBNET>>>;

using net_type = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>;

// ----------------------------------------------------------------------------$

cv::Mat test_np_mat(const cv::Mat& in) 
{
  //std::cerr << "in: " << in << std::endl;
  std::cerr << "sz: " << in.size() << std::endl;
  cv::Mat frame ;
  frame = in.clone();
  // Function calling
  facedetect( frame );
  return frame;
}

int facedetect( cv::Mat frame)
{
    const char dNN_path[100]="/home/tapas/Project/smartcity/dlib/mmod_human_fac$
    string file = "/tmp/frame.jpeg";
    cv::imwrite(file, frame);  // Just to check weather my converter is working fine or not and its working 
    cv::waitKey(10);

    net_type net;
    deserialize(dNN_path) >> net;  
   
    // make a standard vector imgs
    matrix<rgb_pixel> img;       //RGB image

    dlib::rectangle cords;
    //size_t constexpr batch_size = 1;

   dlib::load_image(img , file);
   std::cout<<img.size()<<endl;
   
 //imgs.emplace_back(std::move(img)); 

   cv::Mat imf,imf_crop;

   auto dets = net(img);
   for (auto&& d :  dets)
         {             cords=d;
                        cv::Rect roi (cords.left(),cords.top(),cords.width(),cords.height());
                       // Will crop the face region here ..
          }

}
namespace fs { namespace python {
BOOST_PYTHON_MODULE(np_opencv_module)
{
  // Main types export
  fs::python::init_and_export_converters();
  py::scope scope = py::scope();
 
  // Basic test
  py::def("test_np_mat", &test_np_mat);

}

} // namespace fs
} // namespace python

    cv::waitKey(10);

    net_type net;
    deserialize(dNN_path) >> net;  
   
    // make a standard vector imgs
    matrix<rgb_pixel> img;       //RGB image

    dlib::rectangle cords;
    //size_t constexpr batch_size = 1;

   dlib::load_image(img , file);
   std::cout<<img.size()<<endl;
   //imgs.emplace_back(std::move(img)); 

   cv::Mat imf,imf_crop;

   auto dets = net(img);
   for (auto&& d :  dets)
         {             cords=d;
                        cv::Rect roi (cords.left(),cords.top(),cords.width(),cords.height());
                       // Will crop the face region here ..
          }

}
namespace fs { namespace python {
BOOST_PYTHON_MODULE(np_opencv_module)
{
  // Main types export
  fs::python::init_and_export_converters();
  py::scope scope = py::scope();
 
  // Basic test
  py::def("test_np_mat", &test_np_mat);

}

} // namespace fs
} // namespace python
`
Is there any dependencies issue due to which such kind of issue is coming or some thing wrong with my code . Please help or suggest any other way to do this if possible as I have been stuck with this problem for 2 weeks. Please inform me if you need any other information

**Comment by davisking** [comment]
You must have given an input image that is too small.

Also, the part that says `Error detected in function void
dlib::cpu::tensor_conv::operator()(dlib::resizable_tensor&, const
dlib::tensor&, const ` means you aren't running any cuda code.
