### ISSUE TITLE
Coordinates of the detected object using dnn_mmod

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#366]
Hello,

How can I get access to the detected object coordinates in DNN?

**Comment by davisking** [comment]
The examples show how to get a vector of detections.  Each detection is just a mmod_rect, which contains the coordinates.

**Comment by VanitarNordic** [comment]
Alright while I was editing the post, you replied. 
I see test input are images, How can I use video stream from a camera instead?

**Comment by davisking** [comment]
Use some video capture tool like OpenCV's VideoCapture object.
