### ISSUE TITLE
training.xml and testing.xml in "dlib-19.2\dlib-19.2\examples\faces"

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#367]
Hello,
I checked the `training.xml `file, which as you mentioned contains the information of 4 images and related face annotations and coordinates.

But why the `testing.xml` file also contains rectangle annotation as `training.xml` file?! The file names in the testing are not the same with training, but why `testing.xml` should contain annotation of faces?!

**Comment by davisking** [comment]
Github issues are for posting bugs or problems with dlib.  For basic questions about machine learning you should look elsewhere.  There is a lot of great material on the internet.  I've also compiled a list of suggested books here: http://dlib.net/books.html

**Comment by VanitarNordic** [comment]
Alright, thank you but it was weird for me why train and test data-sets "both" should contain annotations, as I experienced so far, training should have, but for the test the algorithm should find them! By the way your simple replies sometimes can be shortcuts to learn. as you yourself learned. I could not find nowhere to ask except here.

Thank you.

**Comment by davisking** [comment]
That's fine, but nothing is like books.  You will learn more from one book
than 10,000 internet posts :)

The testing data is labeled so the example program can print out how well
it performed on the testing data.
