### ISSUE TITLE
Deadend dnn_mmod_ex training

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#369]
Hello,

I tried to train DNN with dnn_mmod_ex. The training stuck at average losses between 3..4 and does not progress. few hours and 36 steps passed. I have attached the images and xml files. 

The data-set contains one test image and 20 training images.

[images.zip](https://github.com/davisking/dlib/files/663164/images.zip)

![2016-12-20_12-23-35](https://cloud.githubusercontent.com/assets/18719591/21344216/daaecc96-c6af-11e6-8545-25438a093117.jpg)

**Comment by AndreaPisoni** [comment]
It seems to me you are training on CPU. If you want to train neural
networks you should use CUDA as it takes several thousands steps and CPU is
way too slow for training.

**Comment by VanitarNordic** [comment]
Thank you for your reply,

Yes, it is on intel  i7 CPU with embedded GPU, but I just selected just 20 training and only 1 test images. Still can take a long time? average losses are normal?

**Comment by VanitarNordic** [comment]
here is another image, it shows no progress. it should not take a long time and many steps with small number of images.

![2](https://cloud.githubusercontent.com/assets/18719591/21344889/49ed89d2-c6b3-11e6-8367-d41e87b85500.jpg)

**Comment by davisking** [comment]
No, it takes a long time.  You need to use a GPU to get reasonable performance.

**Comment by VanitarNordic** [comment]
Do you know any cloud GPU servers which at least we could do the training remotely?

I found this: http://www.softlayer.com/GPU

**Comment by davisking** [comment]
There are lots.  Amazon AWS is famous.  Although you are a lot better off
buying a NVIDIA card.  They are cheaper than using cloud services most of
the time.  Also, a whole lot of people already have graphics cards for
gaming.  The NVIDIA 1080 gaming card is excellent for deep learning.

**Comment by VanitarNordic** [comment]
Thank you for the reply. 

Yes, that's a good GPU card. apart from this, what is your suggestion to use DNN and similar algorithms for battery powered applications?

You know GPU cards consume too mush power, besides they are only accessible through PICe and traditional Motherboards. therefore as I realized there is no way to use them for battery powered applications. FPGA could be an option but usually there are more expensive and quite complex to implement.

What is your suggestion sir?

**Comment by davisking** [comment]
You aren't going to be able to train deep models with battery powered
hardware.  That's just how it is with today's hardware.

**Comment by AndreaPisoni** [comment]
Usually you would train the model on GPU/cloud and then deploy the model on
a CPU battery powered system

**Comment by VanitarNordic** [comment]
Yes, I man using, not training. Therefore the trained model can work on smaller hardware to be used for mobile robots, Yes?

**Comment by davisking** [comment]
Yes

**Comment by AndreaPisoni** [comment]
It works ok on iOS/Android. Don't know about less powerful embedded systems
with less memory

**Comment by VanitarNordic** [comment]
My last question Davis and Andrea.
Usually how long it takes for a model (Dlib DNN mmod) to be trained completely on your own computer and number of input images is in linear relation with the training time?

**Comment by davisking** [comment]
It will take at least several hours, possibly the better part of a day.  It depends on the network and the data.
