### ISSUE TITLE
dnn out of memory after several epoch

### ISSUE THREAD

**Issue by xiaoxTM** [davisking/dlib#370]
Hi, dlib author (and every dlib-ist):

    I am using dlib dnn module for segmentation with customized layer. Precisely, customized categorical cross entropy loss layer and up-sample layer. The issue is, after several epoch, dlib complains that there is not enough memory, saying: 
  "terminate called after throwing an instance of 'dlib::cuda_error'
    what():  Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /home/xiaox/studio/src/c++-series/dlib/dlib/dnn/gpu_data.cpp:190. code: 2, reason: out of memory"

GPU used: Titan X with 12 GB memory.

Here is the last lines of training output (I modified the output for better view):

Epoch 5 - learning rate: 0.001000 - synchronize file: syn/crfnn
avg_loss: 0.014139 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 6 - learning rate: 0.001000 - synchronize file: syn/crfnn
avg_loss: 0.013108 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 7 - learning rate: 0.001000 - synchronize file: syn/crfnn
avg_loss: 0.013431 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 8 - learning rate: 0.000100 - synchronize file: syn/crfnn
avg_loss: 0.013288 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 9 - learning rate: 0.000100 - synchronize file: syn/crfnn
avg_loss: 0.013177 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 10 - learning rate: 0.000100 - synchronize file: syn/crfnn
avg_loss: 0.013108 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 11 - learning rate: 0.000010 - synchronize file: syn/crfnn
avg_loss: 0.013091 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 12 - learning rate: 0.000010 - synchronize file: syn/crfnn
avg_loss: 0.013077 [++++++++++++++++++++, 1464 / 1464, 100%]
Epoch 13 - learning rate: 0.000010 - synchronize file: syn/crfnn
avg_loss: 0.012461 [+++++++++++++++     , 1087 / 1464, 74%]

![dlib-out-of-memory](https://cloud.githubusercontent.com/assets/11028486/21373979/603e959c-c766-11e6-9937-76d10c18a8f4.png)

  Here is my question: does dlib increases gpu memory usage after each epoch ?

To my understanding, with the progress goes, gpu memory usage should not be 
greater than the first epoch does. Therefore, if memory not enough, the error should 
goes out at the first epoch, which did not happen in my case.

Best Wishes
xiaox

**Comment by davisking** [comment]
No, dlib doesn't have any sort of memory leaks in it, GPU or otherwise.  Maybe you made your mini-batch bigger?
