### ISSUE TITLE
Linker Library Errors when Creating DNN

### ISSUE THREAD

**Issue by StephanSalas** [davisking/dlib#371]
**Issue Description**

#include <dlib/dnn.h>
#include <dlib/data_io.h>

Some Unrelated Code... then,

    using net_type = loss_multiclass_log<
                                fc<10,        
                                relu<fc<84,   
                                relu<fc<120,  
                                max_pool<1,2,1,3,relu<con<16,1,8,1,3,
                                max_pool<1,2,1,3,relu<con<6,1,8,1,3,
                                input<matrix<double>> 
                                >>>>>>>>>>>>;
	net_type net;

**Specific Compiler Error**
Compiler Yields errors: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __thiscall dlib::cpu::pooling::pooling(void)" (??0pooling@cpu@dlib@@QAE@XZ) <something.obj 1 here>

**Important Notes**
I have included dlib/all/source.cpp in my project. I have added the C++ path in my "includes directories".
In addition, I would like to note that if the "net_type net;" declaration is removed, the program compiles and runs. 

Is there a part of the API that I'm not including that I am supposed to include, or is this a deeper issue?

**Comment by davisking** [comment]
What did you type?

I just ran this 
`g++ dnn_introduction_ex.cpp -I.. ../dlib/all/source.cpp   -std=c++11 -lX11 -lpthread`
and it compiled the example with no errors.

**Comment by StephanSalas** [comment]
It turns out that after deleting `#if __cplusplus >= 201103` from source.cpp, the linker errors go away, however, in my current setup in Visual Studio 2015, compiling dnn_introduction_ex.cpp yields even more errors for errors such as: 

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	C3927	'->': trailing return type is not allowed after a non-function declarator	EWS_Port	C:\dlib-19.2\dlib-19.2\examples\dnn_introduction_ex.cpp	92	Build	

I am quite confused as to why this would occur, but I can guess that this error has something to do with Visual Studio's C++ Compiler Versioning.

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whycan'tIusetheDNNmodulewithVisualStudio

**Comment by StephanSalas** [comment]
Thanks for the link -- I installed the most recent edition of Visual Studio 2015 Update 3 from the Microsoft Web Page: 

> https://www.visualstudio.com/downloads/

Unfortunately, the current release does not seem to have come with the necessary support for C++11 features that are in the DNN API. 

Therefore, I think I have narrowed down the the problem to either being with the most recent download's failure to include the relevant C++ features in the DNN API, or because I have not set the correct command line-compiler options for C++11 within Visual Studio 2015, v3. 

I could just cmake the library, but I would like to help improve support for the API in Visual Studio as well for future API users. It's interesting that Microsoft doesn't support the relevant features by default, and I would like to find a workaround for the Visual Studio User posterity.

**Comment by davisking** [comment]
I just tried making a plain win32 project using visual studio's project wizard and it worked (adding just dlib/all/source.cpp and the metric learning DNN example).  Although I did have to remove the `#if __cplusplus >= 201103` check in dlib/all/source.cpp since visual studio still doesn't define it to the proper value even though it ostensibly supports C++11.   I pushed this change to github since the check is redundant with a check in dlib/algs.h which happens to be written in a way that works around this problem with visual studio.

Anyway, this should work when you do it.  Maybe you need to get the newest code from github.

**Comment by StephanSalas** [comment]
Downloading the source directly from Github seems to have fixed the issue.
