### ISSUE TITLE
build with ninja

### ISSUE THREAD

**Issue by tzutalin** [davisking/dlib#373]
Hi @davisking ,
  I tried to build dlib with ninja and do some comparisons with makefile. There are the results for your references.

My environment: 
```
CPU: Intel® Core™ i7-4790 CPU @ 3.60GHz × 8 
Memory : 16G
Ubuntu : 14.04
ninja : 1.3.4
cmake : 3.2.2
dlib : v19.2
```

>Build target: libdlib.so with only 1 job at once

| MakeFile  |  Ninja | 
|---|---|
|  154 sec | 42 sec  |

**Comment by davisking** [comment]
Cool.  Did you give -j8 or -j12 to make?

**Comment by tzutalin** [comment]
No. 
I just try '$ make' and '$ ninja' to do comparisons. It is supposed to use -j 1
`$ cmake -G Ninga ..; ninja `
`$ cmake ..;make`

**Comment by davisking** [comment]
That's probably why make is running slower :)
