### ISSUE TITLE
Singular Value Decomposition

### ISSUE THREAD

**Issue by ly-atdawn** [davisking/dlib#375]
In the svd_fast, What is the meaning of l ( unsigned long l ) ?
 template `<typename  T>`
    void svd_fast (
        const matrix<T>& A,
        matrix<T>& u,
        matrix<T>& w,
        matrix<T>& v,
        unsigned long l,
        unsigned long q = 1
    );

Though, svd_fast is very fast and suitable for use with very large matrices.  Are there other ways to improve SVD speed？

Thanks.

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whereisthedocumentationforobjectfunction
