### ISSUE TITLE
Including dlib in android ndk

### ISSUE THREAD

**Issue by johnygeorge** [davisking/dlib#378]
I am trying to create an `android ndk` project which combines `dlib` and `opencv`. The error is coming from the `dlib` library.

But I am getting the following error, when I try to build the program.
What is wrong ?

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':mobile:externalNativeBuildDebug'.
    > Build command failed.
      Error while executing '/opt/android-sdk-linux/cmake/3.6.3155560/bin/cmake' with arguments {--build mobile/.externalNativeBuild/cmake/debug/arm64-v8a --target native-lib}
      [1/4] Building CXX object CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o
      FAILED: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  -target aarch64-none-linux-android -gcc-toolchain /opt/android-sdk-linux/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64  -Dlib_dlib_EXPORTS -I/usr/local/include -I/usr/local/include/dlib -isystem /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -std=c++11 -frtti -fexceptions -v -Wall -Werror -Wno-unused-variable -w -std=gnu++11 -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o -MF CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o.d -o CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o -c mobile/src/main/cpp/source.cpp
      Android clang version 3.8.256229  (based on LLVM 3.8.256229)
      Target: aarch64-none-linux-android
      Thread model: posix
      InstalledDir: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin
      Found candidate GCC installation: /opt/android-sdk-linux/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x
      Selected GCC installation: /opt/android-sdk-linux/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x
      Candidate multilib: .;@m64
      Selected multilib: .;@m64
       "/opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" -cc1 -triple aarch64-none-linux-android -emit-obj -mrelax-all -mnoexecstack -mnoexecstack -disable-free -disable-llvm-verifier -main-file-name source.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -backend-option -aarch64-fix-cortex-a53-835769=1 -target-linker-version 2.24 -v -dwarf-column-info -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -ffunction-sections -coverage-file mobile/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o -resource-dir /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.256229 -dependency-file CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o.d -sys-header-deps -MT CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o -isystem /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -D lib_dlib_EXPORTS -I /usr/local/include -I /usr/local/include/dlib -D ANDROID -D ANDROID -isysroot /opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64 -internal-isystem /opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64/usr/local/include -internal-isystem /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.256229/include -internal-externc-isystem /opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64/include -internal-externc-isystem /opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64/usr/include -O0 -Wformat -Werror=format-security -Wformat -Werror=format-security -Wall -Werror -Wno-unused-variable -w -std=gnu++11 -fdeprecated-macro -fdebug-compilation-dir mobile/.externalNativeBuild/cmake/debug/arm64-v8a -ferror-limit 19 -fmessage-length 0 -femulated-tls -stack-protector 2 -fallow-half-arguments-and-returns -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o CMakeFiles/lib_dlib.dir/src/main/cpp/source.cpp.o -x c++ /mobile/src/main/cpp/source.cpp
      clang -cc1 version 3.8.256229 based upon LLVM 3.8.256229 default target x86_64-unknown-linux
      ignoring nonexistent directory "/opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64/usr/local/include"
      ignoring nonexistent directory "/opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64/include"
      #include "..." search starts here:
      #include <...> search starts here:
       /usr/local/include
       /usr/local/include/dlib
       /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include
       /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include
       /opt/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward
       /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/clang/3.8.256229/include
       /opt/android-sdk-linux/ndk-bundle/platforms/android-21/arch-arm64/usr/include
      End of search list.
      In file included from mobile/src/main/cpp/source.cpp:22:
      In file included from /usr/local/include/dlib/dlib/data_io/image_dataset_metadata.cpp:6:
      In file included from /usr/local/include/dlib/dlib/data_io/image_dataset_metadata.h:8:
      In file included from /usr/local/include/dlib/dlib/base64/../geometry/../image_processing/../geometry.h:10:
      In file included from /usr/local/include/dlib/dlib/base64/../geometry/point_transforms.h:9:
      In file included from /usr/local/include/dlib/dlib/base64/../statistics/../matrix.h:7:
      /usr/local/include/dlib/dlib/base64/../geometry/../matrix/matrix_utilities.h:2665:29: error: static_assert expression is not an integral constant expression
              COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
      /usr/local/include/dlib/dlib/base64/../gui_core/../assert.h:93:59: note: expanded from macro 'COMPILE_TIME_ASSERT'
          #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                                                ^~~~~~~~~~
      /usr/local/include/dlib/dlib/base64/../gui_widgets/canvas_drawing.h:945:23: note: in instantiation of function template specialization 'dlib::pixel_to_vector<long, dlib::rgb_pixel>' requested here
                          ((pixel_to_vector<long>(pixel_top)*t + 
                            ^
      /usr/local/include/dlib/dlib/base64/../gui_widgets/style.h:633:21: note: in instantiation of function template specialization 'dlib::fill_rect_with_vertical_gradient<dlib::rgb_pixel>' requested here
                          fill_rect_with_vertical_gradient(c,rect,rgb_pixel(110,160,255),  rgb_pixel(100,130,250),display_rect);
                          ^
      /usr/local/include/dlib/dlib/base64/../gui_widgets/style.h:597:19: note: in instantiation of function template specialization 'dlib::list_box_style_default::draw_list_box_item_template<std::basic_string<char> >' requested here
              ) const { draw_list_box_item_template(c,rect,display_rect, enabled, mfont, text, is_selected); }
                        ^
      /usr/local/include/dlib/dlib/base64/../geometry/../matrix/matrix_utilities.h:2665:50: note: non-constexpr function 'operator><dlib::pixel_traits<dlib::rgb_pixel>::(anonymous enum at /usr/local/include/dlib/dlib/base64/../gui_widgets/../image_transforms/../pixel.h:414:9), int>' cannot be used in a constant expression
              COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
                                                       ^
      /usr/local/include/dlib/dlib/base64/../sync_extension/../algs.h:286:14: note: declared here
              bool operator> (
                   ^
      In file included from mobile/src/main/cpp/source.cpp:22:
      In file included from /usr/local/include/dlib/dlib/data_io/image_dataset_metadata.cpp:6:
      In file included from /usr/local/include/dlib/dlib/data_io/image_dataset_metadata.h:8:
      In file included from /usr/local/include/dlib/dlib/base64/../geometry/../image_processing/../geometry.h:10:
      In file included from /usr/local/include/dlib/dlib/base64/../geometry/point_transforms.h:9:
      In file included from /usr/local/include/dlib/dlib/base64/../statistics/../matrix.h:7:
      /usr/local/include/dlib/dlib/base64/../geometry/../matrix/matrix_utilities.h:2665:29: error: static_assert expression is not an integral constant expression
              COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
      /usr/local/include/dlib/dlib/base64/../gui_core/../assert.h:93:59: note: expanded from macro 'COMPILE_TIME_ASSERT'
          #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                                                ^~~~~~~~~~
      /usr/local/include/dlib/dlib/base64/../gui_widgets/canvas_drawing.h:945:23: note: in instantiation of function template specialization 'dlib::pixel_to_vector<long, dlib::rgb_alpha_pixel>' requested here
                          ((pixel_to_vector<long>(pixel_top)*t + 
                            ^
      /usr/local/include/dlib/dlib/base64/../gui_widgets/base_widgets.h:1570:17: note: in instantiation of function template specialization 'dlib::fill_rect_with_vertical_gradient<dlib::rgb_alpha_pixel>' requested here
                      fill_rect_with_vertical_gradient(c, rect,rgb_alpha_pixel(0,200,0,100), rgb_alpha_pixel(0,0,0,100));
                      ^
      /usr/local/include/dlib/dlib/base64/../geometry/../matrix/matrix_utilities.h:2665:50: note: non-constexpr function 'operator><dlib::pixel_traits<dlib::rgb_alpha_pixel>::(anonymous enum at /usr/local/include/dlib/dlib/base64/../gui_widgets/../image_transforms/../pixel.h:450:9), int>' cannot be used in a constant expression
              COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
                                                       ^
      /usr/local/include/dlib/dlib/base64/../sync_extension/../algs.h:286:14: note: declared here
              bool operator> (
                   ^
      In file included from mobile/src/main/cpp/source.cpp:22:
      In file included from /usr/local/include/dlib/dlib/data_io/image_dataset_metadata.cpp:6:
      In file included from /usr/local/include/dlib/dlib/data_io/image_dataset_metadata.h:8:
      In file included from /usr/local/include/dlib/dlib/base64/../geometry/../image_processing/../geometry.h:10:
      In file included from /usr/local/include/dlib/dlib/base64/../geometry/point_transforms.h:9:
      In file included from /usr/local/include/dlib/dlib/base64/../statistics/../matrix.h:7:
      /usr/local/include/dlib/dlib/base64/../geometry/../matrix/matrix_utilities.h:2665:29: error: static_assert expression is not an integral constant expression
              COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
      /usr/local/include/dlib/dlib/base64/../gui_core/../assert.h:93:59: note: expanded from macro 'COMPILE_TIME_ASSERT'
          #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                                                ^~~~~~~~~~
      /usr/local/include/dlib/dlib/base64/../gui_widgets/canvas_drawing.h:836:31: note: in instantiation of function template specialization 'dlib::pixel_to_vector<unsigned long, dlib::rgb_alpha_pixel>' requested here
                                  ((pixel_to_vector<unsigned long>(top_color)*c_t + pixel_to_vector<unsigned long>(bottom_color)*c_s)/c_div));
                                    ^
      /usr/local/include/dlib/dlib/gui_widgets/style.cpp:146:13: note: in instantiation of function template specialization 'dlib::fill_gradient_rounded<dlib::rgb_alpha_pixel>' requested here
                  fill_gradient_rounded(c,rect,radius,rgb_alpha_pixel(255, 255, 255,120-d), 
                  ^
      /usr/local/include/dlib/dlib/base64/../geometry/../matrix/matrix_utilities.h:2665:50: note: non-constexpr function 'operator><dlib::pixel_traits<dlib::rgb_alpha_pixel>::(anonymous enum at /usr/local/include/dlib/dlib/base64/../gui_widgets/../image_transforms/../pixel.h:450:9), int>' cannot be used in a constant expression
              COMPILE_TIME_ASSERT(pixel_traits<P>::num > 0);
                                                       ^
      /usr/local/include/dlib/dlib/base64/../sync_extension/../algs.h:286:14: note: declared here
              bool operator> (
                   ^
      3 errors generated.
      ninja: build stopped: subcommand failed.
    
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by davisking** [comment]
Yeah, that's annoying. I just pushed a change to github that should fix
it.  So try the latest code.

**Comment by davisking** [comment]
Now it's just that your build scripts are wrong.  It's telling you that you need to link to x11.

**Comment by johnygeorge** [comment]
@davisking Can you help me with a query.

I got a frame from `opencv` and trying to use `land mark detection` to track facial land mark.

```
JNIEXPORT void JNICALL Java_kom_thesis_tudarmstadt_moodanalyzer_NativeClass_landMarkDetection
        (JNIEnv *env, jclass, jlong mAddrFrame) {

    LOGI("landMarkDetection");

    Mat &frame = *(Mat *) mAddrFrame;

    detectLandMark(frame);
}

   void detectLandMark(Mat &addrFrame) {

    LOGI("detectLandMark");

    cv_image<bgr_pixel> cimg(addrFrame);

    //detect faces using dlib
    std::vector<dlib::rectangle> faces = detector(cimg);

    //find the pose of the each face using dlib
    std::vector<full_object_detection> shapes;

    for (unsigned long i = 0; i < faces.size(); ++i)
        shapes.push_back(pose_model(cimg, faces[i]));

    //render to destination
    renderToMat(shapes, addrFrame);
}
```

But in this ` cv_image<bgr_pixel> cimg(addrFrame);` the code just crashes from `dlib` and this is the error that I get ` A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 28961 (Thread-30816)`

Can you help me with this ? What is wrong ?

**Comment by davisking** [comment]
I don't know.  You have some bug in your code. Probably the JNI is not right.  But I doubt it has anything to do with dlib.

**Comment by Doupi** [comment]
@johnygeorge, has your problem solved already? If yes, could you share me the solution? Thank you very much!
