### ISSUE TITLE
be_verbose() in optimization_stop_strategies.h

### ISSUE THREAD

**Issue by Trombach** [davisking/dlib#379]
Hello,

I'm using dlib's multidimensional function minimiser with great success. I'm running multiple optimisations in parallel openMP threads and I would like to output information about the intermediate steps to a file. Unfortunately the be_verbose() option only allows output to std::cout. My implementation uses individual streams for each optimisation that will be synchronised.
So, as a feature request: would it be possible to change the be_verbose() option to allow for output to non cout streams?

Thanks (also for this awesome library)

Lukas

**Comment by davisking** [comment]
You can do this by implementing another stopping strategy object that does
whatever kind of logging you need.  These kind of more complex cases are
why the API lets you pass in any stopping strategy object you want.

**Comment by Trombach** [comment]
Thanks for your quick reply. I really didn't think of this, but it's a great solution. Keep up the great work!

**Comment by davisking** [comment]
No problem :)
