### ISSUE TITLE
doc bug at http://dlib.net/dlib/optimization/max_cost_assignment_abstract.h.html ?

### ISSUE THREAD

**Issue by keithbriggs** [davisking/dlib#38]
http://dlib.net/dlib/optimization/max_cost_assignment_abstract.h.html#max_cost_assignment has this at the top which doesn't look right:

#undef DLIB_MAX_COST_ASSIgNMENT_ABSTRACT_Hh_
#ifdef DLIB_MAX_COST_ASSIgNMENT_ABSTRACT_Hh_

Surely the ifdef can never be true?

**Comment by davisking** [comment]
Yes, but the file is just documentation.  It's not supposed to be processed by the compiler.
