### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by netcat88** [davisking/dlib#380]
Hi,

I tried to setup everything as it should be to build the library (miniglog and opencv and dlib from the site) and I started the build having admin privileges, but I got an error:

In file included from jni/jni_detections/jni_face_det.cpp:14:
In file included from jni/jni_detections/detector.h:14:
In file included from jni/../dlib/dlib/image_processing.h:17:
In file included from jni/../dlib/dlib/image_loader/../image_processing/setup_hashed_features.h:8:
In file included from jni/../dlib/dlib/image_loader/../array2d/../geometry/../image_processing/scan_image_boxes.h:12:
In file included from jni/../dlib/dlib/image_loader/../array2d/../geometry/../image_processing/../image_transforms.h:28:
jni/../dlib/dlib/image_loader/../image_transforms/random_cropper.h:146:67: error: no member named 'round' in namespace 'std'
            const unsigned long min_object_height_absolute = std::round(min_object_height*crop_plan.rows);
                                                             ~~~~~^
In file included from jni/jni_detections/jni_pedestrian_det.cpp:14:
In file included from jni/jni_detections/detector.h:14:
In file included from jni/../dlib/dlib/image_processing.h:17:
In file included from jni/../dlib/dlib/image_loader/../image_processing/setup_hashed_features.h:8:
In file included from jni/../dlib/dlib/image_loader/../array2d/../geometry/../image_processing/scan_image_boxes.h:12:
In file included from jni/../dlib/dlib/image_loader/../array2d/../geometry/../image_processing/../image_transforms.h:28:
jni/../dlib/dlib/image_loader/../image_transforms/random_cropper.h:146:67: error: no member named 'round' in namespace 'std'
            const unsigned long min_object_height_absolute = std::round(min_object_height*crop_plan.rows);
                                                             ~~~~~^
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_shared.cpp
[armeabi-v7a] Compile++ thumb: dlib <= entropy_decoder_kernel_2.cpp
[armeabi-v7a] Compile++ thumb: dlib <= base64_kernel_1.cpp
[armeabi-v7a] Compile++ thumb: miniglog <= logging.cc
[arm64-v8a] Compile++      : android_dlib <= jni_imageutils.cpp
[arm64-v8a] Compile++      : android_dlib <= jni_pedestrian_det.cpp
[arm64-v8a] Compile++      : android_dlib <= jni_face_det.cpp
1 error generated.
1 error generated.
make: *** [obj/local/armeabi-v7a/objs/android_dlib/jni_pedestrian_det.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi-v7a/objs/android_dlib/jni_face_det.o] Error 1
Build Error


May I provide additional details?

Regards

**Comment by netcat88** [comment]
I noticed it's a NDK related bug. which version would be better to use?

**Comment by davisking** [comment]
I don't know.  I don't do android development.  But it looks like you aren't using a C++11 compiler since std::round is part of C++11.  

Also, if you google `dlib android` you get lots of hits from people using dlib on android.  Some of them show how to setup an android project.
