### ISSUE TITLE
Recurrent Convolutional Neural Networks

### ISSUE THREAD

**Issue by mpeniak** [davisking/dlib#381]
Thanks for the great work! Is there any way I could use dlib to implement RCNNs (both forward and backward pass)?

**Comment by davisking** [comment]
Not right now.  There has been a lot of discussion about this already https://github.com/davisking/dlib/pull/213 and https://github.com/davisking/dlib/issues/290.  I'll update it to include support at some point in the not too distant future, but right now can't really do it in a convenient way.

**Comment by minmummax** [comment]
thanks

**Comment by Arritmic** [comment]
Hello davidsking!
Has that point "in the not too distant future" already happened?
Thanks so much

**Comment by davisking** [comment]
Turns out it's still in the future :/

**Comment by davisking** [comment]
I've been too busy with the object detection updates.  E.g. http://blog.dlib.net/2017/09/fast-multiclass-object-detection-in.html

**Comment by Arritmic** [comment]
Yes, I reviewed the new update. And it looks pretty good. I am so fan of your lib. Thanks so much for your constant support and dedication. I appreciate it a lot. :)
Best wishes from Oulu ( Finland ).

**Comment by davisking** [comment]
Thanks :)
