### ISSUE TITLE
dlib::image_dataset_metadata::load_image_dataset_metadata uninitialized parts for ignored rect

### ISSUE THREAD

**Issue by ShuangLiu1992** [davisking/dlib#382]
it seems to me that if the first bounding box has the attribute "ignore" then the result of the parts of the rest of the box are not proper initialized if the parts are empty (that's what I observed anyway), parts.size() would produce garbage values.

**Comment by davisking** [comment]
Is this a question?

**Comment by ShuangLiu1992** [comment]
if github is not the place, where do I report potential bugs?

**Comment by davisking** [comment]
No, github is where you report bugs.  

The ignore flag is just a flag, it isn't interpreted nor does it effect the behavior of load_image_dataset_metadata.  So it isn't clear to me what you are trying to say.

**Comment by ShuangLiu1992** [comment]
I wrote the same routine to convert the training labels to other format by using load_image_dataset_metadata, and the following code snippet is giving me weird bugs so naturally I tried to print the size of the std::vector<point> parts, and I found a pattern of parts.size() not being correct when the first bounding box has the ignore label and the second doesn't. To me it seems like it hasn't been properly initialized. I took a look at the code of load_image_dataset_metadata and it keeps reusing variables such temp_image and temp_box, hence the first question.

```
        for (size_t i = 0; i < self.images.size(); i++) {
            image["filename"] = self.images[i].filename;
            for (size_t ind = 0; ind < self.images[i].boxes.size(); ind++) {
                dlib::rectangle rect = self.images[i].boxes[ind].rect;
                std::vector<dlib::point> parts(self.images[i].boxes[ind].parts.size());
                for (const auto &part : self.images[i].boxes[ind].parts) {
                    size_t part_ind = std::stoi(part.first);
                    make_sure(part_ind >= 0 && part_ind < parts.size());
                    parts[std::stoi(part.first)] = part.second;
                }
                std::cout << parts.size() << std::endl;
                dlib::full_object_detection detection(rect, parts);
```

**Comment by davisking** [comment]
If you think you found a bug post a minimal but complete program that illustrates the problem.
