### ISSUE TITLE
Errors during final DLIB compilation for Python API.

### ISSUE THREAD

**Issue by rogerleecadet** [davisking/dlib#383]
Platform: Windows 7 (64)
DLIB: 19.2
Python: 2.7.8
Boost: 1.62
Command-line execution using Windows DOS Prompt.

Steps executed:
D:\DLIB (contents extracted from DLIB 19.2's zip file)
D:\DLIB\TOOLS\PYTHON\mkdir BUILD
D:\DLIB\TOOLS\PYTHON\BUILD\cmake -G "MinGW Makefiles" ..
D:\DLIB\TOOLS\PYTHON\BUILD\mingw32-make.exe all

Hello there,

I am using GCC as the compiler, and have no VS on my system. Tried many different ways for the last 3-4 days. Solved some nasty errors from the start by using CMAKE -G "MinGW Makefiles" (Windows defaulted to use NMAKE) and produced successful BUILD.  Then compiling using MINGW32-MAKE.EXE was working well.. until near towards the end, then the following similar final errors always showed:

CMakeFiles\dlib_.dir\build.make:62: recipe for target 'CMakeFiles/dlib_.dir/src/dlib.cpp.obj' failed
mingw32-make.exe[2]: *** [CMakeFiles/dlib_.dir/src/dlib.cpp.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/dlib_.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

Prior to the above errors, here are the logs (as far as my DOS WINDOW buffers able to keep):

[ 80%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jchuff.cpp.obj
D:\DLIB\dlib\external\libjpeg\jchuff.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 81%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmainct.cpp.obj
D:\DLIB\dlib\external\libjpeg\jcmainct.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 82%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcphuff.cpp.obj
D:\DLIB\dlib\external\libjpeg\jcphuff.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 82%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcprepct.cpp.obj
D:\DLIB\dlib\external\libjpeg\jcprepct.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 83%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcsample.cpp.obj
D:\DLIB\dlib\external\libjpeg\jcsample.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 84%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctint.cpp.obj
D:\DLIB\dlib\external\libjpeg\jfdctint.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 85%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctflt.cpp.obj
D:\DLIB\dlib\external\libjpeg\jfdctflt.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 85%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctfst.cpp.obj
D:\DLIB\dlib\external\libjpeg\jfdctfst.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
[ 86%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.obj
D:\DLIB\dlib\image_loader\jpeg_loader.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright (C) 2010  Davis E. King (davis@dlib.net), Nils Labugt
 ^
[ 87%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.obj
D:\DLIB\dlib\image_saver\save_jpeg.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright (C) 2014  Davis E. King (davis@dlib.net), Nils Labugt
 ^
[ 87%] Linking CXX static library libdlib.a
[ 87%] Built target dlib
Scanning dependencies of target dlib_
[ 88%] Building CXX object CMakeFiles/dlib_.dir/src/dlib.cpp.obj
D:\DLIB\tools\python\src\dlib.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright (C) 2015 Davis E. King (davis@dlib.net)
 ^
In file included from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/random:38:0,
                 from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/stl_algo.h:66,
                 from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/algorithm:62,
                 from D:/BOOST162/boost/function/detail/prologue.hpp:13,
                 from D:/BOOST162/boost/function/function_template.hpp:13,
                 from D:/BOOST162/boost/function/detail/maybe_include.hpp:13,
                 from D:/BOOST162/boost/function/function0.hpp:11,
                 from D:/BOOST162/boost/python/errors.hpp:13,
                 from D:/BOOST162/boost/python/handle.hpp:11,
                 from D:/BOOST162/boost/python/args_fwd.hpp:10,
                 from D:/BOOST162/boost/python/args.hpp:10,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/cmath:1094:11: error: '::hypot' has not been declared
   using ::hypot;
           ^
In file included from D:/BOOST162/boost/python/detail/is_xxx.hpp:8:0,
                 from D:/BOOST162/boost/python/detail/is_auto_ptr.hpp:9,
                 from D:/BOOST162/boost/python/detail/copy_ctor_mutates_rhs.hpp:8,
                 from D:/BOOST162/boost/python/detail/value_arg.hpp:7,
                 from D:/BOOST162/boost/python/object/forward.hpp:13,
                 from D:/BOOST162/boost/python/object/pointer_holder.hpp:16,
                 from D:/BOOST162/boost/python/to_python_indirect.hpp:10,
                 from D:/BOOST162/boost/python/converter/arg_to_python.hpp:10,
                 from D:/BOOST162/boost/python/call.hpp:15,
                 from D:/BOOST162/boost/python/object_core.hpp:14,
                 from D:/BOOST162/boost/python/args.hpp:25,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/BOOST162/boost/python/detail/is_auto_ptr.hpp:17:40: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
 BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
                                        ^
D:/BOOST162/boost/detail/is_xxx.hpp:20:4: note: in definition of macro 'BOOST_DETAIL_IS_XXX_DEF'
    qualified_name< BOOST_PP_ENUM_PARAMS_Z(1, nargs, T) >        \
    ^
D:/BOOST162/boost/python/detail/is_auto_ptr.hpp:17:1: note: in expansion of macro 'BOOST_PYTHON_IS_XXX_DEF'
 BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
 ^
In file included from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/memory:81:0,
                 from D:/BOOST162/boost/function/function_base.hpp:16,
                 from D:/BOOST162/boost/function/detail/prologue.hpp:17,
                 from D:/BOOST162/boost/function/function_template.hpp:13,
                 from D:/BOOST162/boost/function/detail/maybe_include.hpp:13,
                 from D:/BOOST162/boost/function/function0.hpp:11,
                 from D:/BOOST162/boost/python/errors.hpp:13,
                 from D:/BOOST162/boost/python/handle.hpp:11,
                 from D:/BOOST162/boost/python/args_fwd.hpp:10,
                 from D:/BOOST162/boost/python/args.hpp:10,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from D:/BOOST162/boost/python/object/make_instance.hpp:9:0,
                 from D:/BOOST162/boost/python/object/make_ptr_instance.hpp:8,
                 from D:/BOOST162/boost/python/to_python_indirect.hpp:11,
                 from D:/BOOST162/boost/python/converter/arg_to_python.hpp:10,
                 from D:/BOOST162/boost/python/call.hpp:15,
                 from D:/BOOST162/boost/python/object_core.hpp:14,
                 from D:/BOOST162/boost/python/args.hpp:25,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/BOOST162/boost/python/object/instance.hpp:14:36: warning: type attributes ignored after type is already defined [-Wattributes]
   struct BOOST_PYTHON_DECL_FORWARD instance_holder;
                                    ^
In file included from D:/BOOST162/boost/python/converter/arg_to_python.hpp:10:0,
                 from D:/BOOST162/boost/python/call.hpp:15,
                 from D:/BOOST162/boost/python/object_core.hpp:14,
                 from D:/BOOST162/boost/python/args.hpp:25,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/BOOST162/boost/python/to_python_indirect.hpp: In static member function 'static PyObject* boost::python::detail::make_owning_holder::execute(T*)':
D:/BOOST162/boost/python/to_python_indirect.hpp:90:24: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
           typedef std::auto_ptr<T> smart_pointer;
                        ^
In file included from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/memory:81:0,
                 from D:/BOOST162/boost/function/function_base.hpp:16,
                 from D:/BOOST162/boost/function/detail/prologue.hpp:17,
                 from D:/BOOST162/boost/function/function_template.hpp:13,
                 from D:/BOOST162/boost/function/detail/maybe_include.hpp:13,
                 from D:/BOOST162/boost/function/function0.hpp:11,
                 from D:/BOOST162/boost/python/errors.hpp:13,
                 from D:/BOOST162/boost/python/handle.hpp:11,
                 from D:/BOOST162/boost/python/args_fwd.hpp:10,
                 from D:/BOOST162/boost/python/args.hpp:10,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from D:/BOOST162/boost/python/object/function_handle.hpp:10:0,
                 from D:/BOOST162/boost/python/converter/arg_to_python.hpp:19,
                 from D:/BOOST162/boost/python/call.hpp:15,
                 from D:/BOOST162/boost/python/object_core.hpp:14,
                 from D:/BOOST162/boost/python/args.hpp:25,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/BOOST162/boost/python/object/py_function.hpp: At global scope:
D:/BOOST162/boost/python/object/py_function.hpp:167:18: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     mutable std::auto_ptr<py_function_impl_base> m_impl;
                  ^
In file included from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/memory:81:0,
                 from D:/BOOST162/boost/function/function_base.hpp:16,
                 from D:/BOOST162/boost/function/detail/prologue.hpp:17,
                 from D:/BOOST162/boost/function/function_template.hpp:13,
                 from D:/BOOST162/boost/function/detail/maybe_include.hpp:13,
                 from D:/BOOST162/boost/function/function0.hpp:11,
                 from D:/BOOST162/boost/python/errors.hpp:13,
                 from D:/BOOST162/boost/python/handle.hpp:11,
                 from D:/BOOST162/boost/python/args_fwd.hpp:10,
                 from D:/BOOST162/boost/python/args.hpp:10,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from D:/BOOST162/boost/python.hpp:41:0,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/BOOST162/boost/python/make_constructor.hpp: In member function 'void boost::python::detail::install_holder<T>::dispatch(U*, mpl_::true_) const':
D:/BOOST162/boost/python/make_constructor.hpp:48:16: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
           std::auto_ptr<U> owner(x);
                ^
In file included from D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/memory:81:0,
                 from D:/BOOST162/boost/function/function_base.hpp:16,
                 from D:/BOOST162/boost/function/detail/prologue.hpp:17,
                 from D:/BOOST162/boost/function/function_template.hpp:13,
                 from D:/BOOST162/boost/function/detail/maybe_include.hpp:13,
                 from D:/BOOST162/boost/function/function0.hpp:11,
                 from D:/BOOST162/boost/python/errors.hpp:13,
                 from D:/BOOST162/boost/python/handle.hpp:11,
                 from D:/BOOST162/boost/python/args_fwd.hpp:10,
                 from D:/BOOST162/boost/python/args.hpp:10,
                 from D:/BOOST162/boost/python.hpp:11,
                 from D:\DLIB\tools\python\src\dlib.cpp:4:
D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;

**Comment by davisking** [comment]
The error you posted says `D:/PROGRAMMING/GCC/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/cmath:1094:11: error: '::hypot' not been declared`.  That's not a dlib file.  That error might as well say "error, this compiler is broken".  Maybe it's installed wrong.  I don't know.  But the compiler shouldn't error out when parsing its own files.  Maybe that version of mingw is just garbage, or maybe reinstalling it will fix it.

Also, I'm pretty sure python modules on windows need to be compiled with visual studio or you will get errors when you try to use the module.   So really I would install visual studio.
