### ISSUE TITLE
dlib is not compatible with openblas (tested with v19.2 in mac os)

### ISSUE THREAD

**Issue by huangynn** [davisking/dlib#384]
error type 1: conflict definition
![image](https://cloud.githubusercontent.com/assets/12636388/21562194/d187b79a-ceb1-11e6-9a56-8c7d157d0f03.png)

error type 1:  connot convert 'const std::complex<double> *' to 'const double *'
![image](https://cloud.githubusercontent.com/assets/12636388/21562197/dc6c338e-ceb1-11e6-99ec-b1688cb6fc44.png)

dlib version: 19.2
openblas version: 0.2.18_2
os: Mac OSX

**Comment by davisking** [comment]
Line 47 in matrix_blas_bindings.h tries to disable that block of definitions if a cblas header has already been included.  Apparently the cblas header you have uses different inclusion guards?  If you look at your cblas.h you should be able to update the guard around the definitions in matrix_blas_bindings.h

**Comment by huangynn** [comment]
![image](https://cloud.githubusercontent.com/assets/12636388/21577638/112e4e40-cf9d-11e6-8041-fc752e51f609.png)
above is the guard in cblas.h

![image](https://cloud.githubusercontent.com/assets/12636388/21577643/3146c3a6-cf9d-11e6-8d40-c11fa7ce73d3.png)
and this is the guard in  matrix_blas_bindings.h

They are the same. So it should be blocked, but id didn't....

**Comment by davisking** [comment]
Are you sure there isn't another file that's defining those cblas functions?

**Comment by huangynn** [comment]
There is only one cblas.h file in the include directory, and there is a conversion problem
![image](https://cloud.githubusercontent.com/assets/12636388/21629303/0714c958-d262-11e6-898b-334771f682d2.png)

**Comment by davisking** [comment]
If that's the only error left then putting pointer casts on those arguments should fix it.

**Comment by huangynn** [comment]
But I see than in ubuntu system, the conversion can be done successfully, and no compiling error appeared
