### ISSUE TITLE
not able to import dlib from python code

### ISSUE THREAD

**Issue by cap-1203** [davisking/dlib#389]
I have been able to successfully build and install dlib. 
However when I try to import dlib in my python code, I get the following error

ImportError: /usr/local/lib/python2.7/dist-packages/dlib-19.2.99-py2.7-linux-x86_64.egg/dlib/dlib.so: undefined symbol: _ZN4dlib12pixel_traitsINS_9rgb_pixelEE3numE

System - Ubuntu 14.04
Pyton Version - python2.7

**Comment by davisking** [comment]
What version of gcc?

**Comment by davisking** [comment]
Try the latest code.  I think this might be fixed now.

**Comment by cap-1203** [comment]
GCC version - 4.8.2
The latest change fixed the issue. Thanks

**Comment by davisking** [comment]
No problem

**Comment by liuheng92** [comment]
undefined symbol: _ZN4dlib12pixel_traitsINS_9rgb_pixelEE3numE
GCC version - 4.8.4
dlib19.2
why did this happen?
