### ISSUE TITLE
Error occurs when execute dnn_mmod_ex.exe(cudaMallocHost code: 2, reason: out of memory`)

### ISSUE THREAD

**Issue by Windaway** [davisking/dlib#391]
I have compiled dlib 19.2 in Win10 with vs2015 update3, but when I run dnn_mmod_ex to test the faces dataset, an error occurs.

> num training images: 4
> num testing images:  5
> detection window width,height:      40,40
> overlap NMS IOU thresh:             0.0781701
> overlap NMS percent covered thresh: 0.257122
> step#: 0     learning rate: 0.1   average loss: 0           steps without apparent progress: 0 Error while calling cudaMallocHost(&data, new_size*sizeof(float)) in file C:\dlib\dlib\dnn\gpu_data.cpp:181. code: 2, reason: out of memory

My computer is a notebook with i5 6400 Z170 GTX1070. I have installed cuda 8.0 cudnn 5.1 openblas vs2015 vs2013 opencv3.1. 

How to solve this problem?

cudaMallocHost  may need DRAM, but my computer only have 8GiB Memory and 1070 equips with 8GiB GDRAM, can not my memory afford the computing task?

**Comment by davisking** [comment]
Then you should load less data.  In particular, make either the network smaller or the mini-batch smaller.
