### ISSUE TITLE
test_matrix2 fails on ARM64

### ISSUE THREAD

**Issue by stefan-it** [davisking/dlib#392]
Hi,

the `test_matrix2` test case fails reproducibly on ARM64:

```cpp
{
            print_spinner();
            matrix<double,1,1> m1;
            matrix<double,2,2> m2;
            matrix<double,3,3> m3;
            matrix<double,4,4> m4;

            dlib::rand rnd;
            for (int i = 0; i < 50; ++i)
            {
                m1 = randm(1,1,rnd);
                m2 = randm(2,2,rnd);
                m3 = randm(3,3,rnd);
                m4 = randm(4,4,rnd);

                DLIB_TEST(max(abs(m1*inv(m1) - identity_matrix(m1))) < 1e-13);
                DLIB_TEST(max(abs(m2*inv(m2) - identity_matrix(m2))) < 1e-13);
                DLIB_TEST(max(abs(m3*inv(m3) - identity_matrix(m3))) < 1e-13);
                DLIB_TEST_MSG(max(abs(m4*inv(m4) - identity_matrix(m4))) < 1e-12, max(abs(m4*inv(m4) - identity_matrix(m4))));
            }
}
```

From [here](https://github.com/davisking/dlib/blob/master/dlib/test/matrix2.cpp#L1108) fails for  `DLIB_TEST(max(abs(m2*inv(m2) - identity_matrix(m2))) < 1e-13);`.

## Output

Here's the output for all 50 epochs for `max(abs(m2*inv(m2) - identity_matrix(m2)))` on ARM64 and x86_64:

| Epoch  | ARM64    | x86_64
| ---------  | ------------ | ----------
| 0| 2.22045e-16 | 2.22045e-16
| 1| 1.11022e-16 | 2.22045e-16
| 2| 2.22045e-16 | 0
| 3| 2.85723e-15 | 3.55271e-15
| 4| 1.11022e-16 | 5.55112e-17
| 5| 1.9984e-15   | 1.77636e-15
| 6| 2.22045e-16 | 2.22045e-16
| 7| 4.71824e-16 | 4.44089e-16
| 8| 2.22045e-16 | 0
| 9| 3.29443e-16 | 4.44089e-16
| 10| 2.22045e-16 | 2.22045e-16
| 11| 3.09558e-15 | 7.10543e-15
| 12| 2.22045e-16 | 4.44089e-16
| 13| 1.11022e-16 | 1.11022e-16
| 14| 2.22045e-16 | 1.11022e-16
| 15| 1.11022e-16 | 1.11022e-16
| 16| 1.11022e-16 | 2.22045e-16
| 17| 3.42171e-16 | 4.44089e-16
| 18| 2.9035e-16   | 4.44089e-16
| 19| 3.55301e-16 | 0
| 20| 4.44089e-16 | 4.44089e-16
| 21| 4.44089e-16 | 4.44089e-16
| 22| 2.22045e-16 | 4.44089e-16
| 23| 3.0798e-16   | 2.22045e-16
| 24| 1.11022e-16 | 1.11022e-16
| 25| 1.86148e-16 | 2.22045e-16
| 26| 4.96909e-17 | 1.11022e-16
| 27| 3.24391e-16 | 1.11022e-16
| 28| 1.11022e-16 | 1.11022e-16
| 29| 1.77636e-15 | 0
| 30| 2.92231e-17 | 5.55112e-17
| 31| 2.22045e-16 | 2.22045e-16
| 32| 3.95459e-16 | 4.44089e-16
| 33| 7.08456e-17 | 0
| 34| **1.05471e-13**  | 0
| 35| 1.78436e-16 | 0
| 36| 3.10319e-16 | 4.44089e-16
| 37| 1.3482e-16   | 2.22045e-16
| 38| 2.22045e-16 | 2.22045e-16
| 39| 2.22045e-16 | 4.44089e-16
| 40| 2.22045e-16 | 2.22045e-16
| 41| 5.01675e-16 | 8.88178e-16
| 42| 2.22045e-16 | 2.22045e-16
| 43| 1.55431e-15 | 1.77636e-15
| 44| 5.62909e-18 | 0
| 45| 1.11022e-15 | 0
| 46| 1.11022e-16 | 1.11022e-16
| 47| 2.22045e-16 | 2.22045e-16
| 48| 2.16103e-16 | 4.44089e-16
| 49| 2.22045e-16 | 2.22045e-16

So one result (in bold) is under the test threshold.

If it's ok I would provide the following modification to the test case in a PR:

```cpp
DLIB_TEST(max(abs(m2*inv(m2) - identity_matrix(m2))) < 1e-12);
```

Now the test case succeeds on ARM64 :)

**Comment by davisking** [comment]
Yeah, that would be super :)
