### ISSUE TITLE
sudo python3 setup.py install

### ISSUE THREAD

**Issue by adimittal** [davisking/dlib#393]
I'm not sure why these errors might be coming during sudo python3 setup.py install

I'm on centos 6.8 using python3.4

Build using cmake ...
Scanning dependencies of target dlib
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
In file included from /home/whakpedi/sandbox/dlib/dlib/base64/base64_kernel_1.h:6,
                 from /home/whakpedi/sandbox/dlib/dlib/base64/base64_kernel_1.cpp:6:
/home/whakpedi/sandbox/dlib/dlib/base64/../algs.h:306: error: expected constructor, destructor, or type conversion before ‘bool’
/home/whakpedi/sandbox/dlib/dlib/base64/../algs.h:317: error: expected constructor, destructor, or type conversion before ‘bool’
/home/whakpedi/sandbox/dlib/dlib/base64/../algs.h:328: error: expected constructor, destructor, or type conversion before ‘bool’
/home/whakpedi/sandbox/dlib/dlib/base64/../algs.h:339: error: expected constructor, destructor, or type conversion before ‘bool’
gmake[2]: *** [dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o] Error 1
gmake[1]: *** [dlib_build/CMakeFiles/dlib.dir/all] Error 2
gmake: *** [all] Error 2
error: cmake build failed!

**Comment by davisking** [comment]
You need to install a C++11 compiler.

**Comment by adimittal** [comment]
Yes, thanks forgot to update, figured that out, in that process of waiting for it to install :)

Leaving a link here in case it helps someone later - update gcc from 4.4 to 4.8 for C++11 compiler:  https://edwards.sdsu.edu/research/c11-on-centos-6/
