### ISSUE TITLE
 Error 'You must #define DLIB_JPEG_SUPPORT and link to libjpeg to read JPEG files' 

### ISSUE THREAD

**Issue by LiuJinxue** [davisking/dlib#40]
When I run train_object_detector.py , caused error 'You must #define DLIB_JPEG_SUPPORT and link to libjpeg to read JPEG files' 

I used 'python setup.py install --yes DLIB_JPEG_SUPPORT' to install dlib.
How to solve it?

**Comment by davisking** [comment]
What OS and version of the compiler and python are you using?

**Comment by davisking** [comment]
Actually, I think this was a bug in the dlib cmake files which should now be fixed.  If you repull the code from github it should work without issue now.

**Comment by LiuJinxue** [comment]
@davisking Ubuntu 14.04 LTS, python 2.7.6,  I will try again,  Thanks!

**Comment by LiuJinxue** [comment]
@davisking  After repull the code , it works. Thanks for you help!

**Comment by LiuJinxue** [comment]
@davisking   After repull the code , it works. Thanks for your help!

**Comment by davisking** [comment]
No problem :)

**Comment by 892768447** [comment]
Recently, I have encountered this problem, I have resolved, you can try this:
open dlib\config.h and add these code

#define DLIB_JPEG_SUPPORT 1
#define DLIB_JPEG_STATIC 1
#define DLIB_PNG_SUPPORT 1

Then python setup.py install
