### ISSUE TITLE
how can i do crop an image with dlib library

### ISSUE THREAD

**Issue by busrakb** [davisking/dlib#403]
hey i want to crop an image faces how can i do? there is tile_images(face_chips) but i wanna save every faces to a file i dont want to save a image. for example there are five images i want to save five images seperatly. so how can i do it ?

**Comment by davisking** [comment]
I assume you are referring to this example program: http://dlib.net/face_landmark_detection_ex.cpp.html

Which already crops out faces.  If you don't want to call tile_images() don't call tile_images().  Just do something with each image individually like save it as a png.  All you need to do is write a for loop that saves each image in the array.  If you don't know how to do something as basic as write a for loop then you would be much better serviced by reading a programming book than by having me write the code for you.  I have suggested books here: http://dlib.net/books.html
