### ISSUE TITLE
[Feature Request] Mean Square Loss Function for Multiple Output

### ISSUE THREAD

**Issue by orinocopl** [davisking/dlib#404]
Hello,

There is support for Mean Square Loss in git version of dlib for further release ([Feature Request] Mean Square Loss Function #152). The main limitation of this solution is the number of outputs (only one is allowed) at this moment. The support of Multiple outputs is necessary for some tasks.

Thanks !

**Comment by dennisfrancis** [comment]
Hi, 

I am working on this, will create a PR soon.
Thanks.
