### ISSUE TITLE
use caffe and dlib 

### ISSUE THREAD

**Issue by pouya1991** [davisking/dlib#408]
Hi 
I want to use caffe and dlib together in a project but I get below error , how can I fix it ? 
(Ubuntu 14.04 , CUDA 8.0, Cudnn 5.1)
 
`In file included from /usr/local/include/dlib/image_loader/load_image.h:14:0,
                 from /usr/local/include/dlib/image_io.h:14,
                 from Head_Pose_stimation.cpp:6:
/usr/include/google/protobuf/repeated_field.h:189:33: error: expected nested-name-specifier before ‘void’
 template <typename It, typename VoidPtr> class RepeatedPtrOverPtrsIterator;
                                 ^
/usr/include/google/protobuf/repeated_field.h:189:33: error: two or more data types in declaration of ‘parameter’
 template <typename It, typename VoidPtr> class RepeatedPtrOverPtrsIterator;
                                 ^
In file included from /usr/local/include/caffe/proto/caffe.pb.h:24:0,
                 from /usr/local/include/caffe/blob.hpp:9,
                 from /usr/local/include/caffe/caffe.hpp:7,
                 from Classifier.h:10,
                 from Head_Pose_stimation.cpp:27:
/usr/include/google/protobuf/repeated_field.h:484:63: error: type/value mismatch at argument 2 in template parameter list for ‘template<class It, <declaration error> > class google::protobuf::internal::RepeatedPtrOverPtrsIterator’
   typedef internal::RepeatedPtrOverPtrsIterator<Element, void*>
                                                               ^
/usr/include/google/protobuf/repeated_field.h:484:63: error:   expected a constant of type ‘<type error>’, got ‘void*’
/usr/include/google/protobuf/repeated_field.h:486:75: error: type/value mismatch at argument 2 in template parameter list for ‘template<class It, <declaration error> > class google::protobuf::internal::RepeatedPtrOverPtrsIterator’
   typedef internal::RepeatedPtrOverPtrsIterator<const Element, const void*>
                                                                           ^
/usr/include/google/protobuf/repeated_field.h:486:75: error:   expected a constant of type ‘<type error>’, got ‘const void*’
In file included from /usr/local/include/dlib/image_loader/load_image.h:14:0,
                 from /usr/local/include/dlib/image_io.h:14,
                 from Head_Pose_stimation.cpp:6:
/usr/include/google/protobuf/repeated_field.h:1268:37: error: expected nested-name-specifier before ‘void’
 template<typename Element, typename VoidPtr>
                                     ^
/usr/include/google/protobuf/repeated_field.h:1268:37: error: two or more data types in declaration of ‘parameter’
 template<typename Element, typename VoidPtr>`

**Comment by davisking** [comment]
I don't know.  That doesn't look like the error has anything to do with dlib.  It looks like there is some name conflict between libgif and google protobuf.  You could remove libgif I suppose, but I would fix protobuf or whatever is causing the problem.

**Comment by pouya1991** [comment]
thank you. I fixed this error by setting DLIB_GIF_SUPPORT to OFF
