### ISSUE TITLE
full_object_detection.rects is not the bounding box of the points

### ISSUE THREAD

**Issue by expenses** [davisking/dlib#410]
The Python documentation (http://dlib.net/python/index.html#dlib.full_object_detection) states that the `.rect` attribute of a `full_object_detection` object is the bounding box of all the parts.

In practise, however, it just inherits the rectangle from the detected face:

    >>> faces[1]
    rectangle(1993,525,2080,611)
    >>> landmarks.rect
    rectangle(1993,525,2080,611)
    >>> arr = np.array([[p.x, p.y] for p in landmarks.parts()])
    >>> arr
    array([[1997,  553],
           [1997,  562],
           [1998,  572],
           < -- Concatenated for readability .. >       
           [2034,  591],
           [2030,  591],
           [2027,  591]])
    >>> np.min(arr, 0)
    array([1997,  536])
    >>> np.min(arr, 0)
    array([2085,  613])

In this case, the rectangle is `(1993, 525, 2080, 611)` when it should be `(1997, 536, 2085, 613)`.

If this is the intended behaviour, I recommend you change the documentation so that it is clear how the `.rect` rectangle is calculated.

**Comment by davisking** [comment]
Yeah, it shouldn't say that.  The rect is the face box, the points can go wherever they want independent of that.  Thanks for finding this documentation error.
