### ISSUE TITLE
LNK1104 error in setup.py

### ISSUE THREAD

**Issue by aufheben1** [davisking/dlib#411]
I tried to install dlib for python using 'py.exe setup.py install' command in windows.
It runs well for a while and at some point it finishes with LNK1104 error.
'LINK : fatal error LNK1104 : cannot open file 'python35.lib' [~~~/dlib/tools/python/build/dlib_.vcproj]

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework
