### ISSUE TITLE
streaming machine leanring visualisation

### ISSUE THREAD

**Issue by andrewcz** [davisking/dlib#412]
Hi!
Huge fan of the library!! I use it as a learning tool to further my interest.
Was just wondering, the library has a socket connection.
Could this connect to a stream of data, and have a model sit on top of the stream to create a learning visualisation on streaming data. So three parts stream of data, an online learning tool and a visual to show how it's learning against the drift of data. I not sure if I am describing this accurately but I was wondering if it could be built using this library?
Many thanks,
Best,
Andrew

**Comment by davisking** [comment]
Yes, you could do this.  You could do anything really since when you use dlib you are writing a C++ program and C++ is a turing complete systems programming language :)
