### ISSUE TITLE
"hash" test failes on ppc64

### ISSUE THREAD

**Issue by barkovv** [davisking/dlib#415]
```
./dtest --test_hash
Failure message from test:
Error occured at line 131.
Error occured in file /root/dlib/dlib/test/hash.cpp.
Failing expression was temp1.first == temp2.first
```

Some info about system:
```
uname -a
Linux virtualppc64 3.16.0-4-powerpc64 #1 SMP Debian 3.16.39-1 (2016-12-30) ppc64 GNU/Linux

gcc --version
gcc (Debian 4.9.2-10) 4.9.2

cmake --version
cmake version 3.0.2
```

**Comment by davisking** [comment]
Thanks for posting this issue.  

I don't have a ppc computer to test on.  So I'm not able to debug this.  Can anyone with such a machine take a look?

**Comment by dmiller423** [comment]
I think this must have something to do with you using qemu
This is ubuntu 16.10 on Power8/le
>>
Testing Finished
Total number of individual testing statements executed: 556697328
All tests completed successfully

**Comment by barkovv** [comment]
@dmiller423  I was testing on qemu POWER7 big-endian. It seems to be a endian problem
