### ISSUE TITLE
Illegal instruction (core dumped) error w/ Ubuntu 16.04 (Python)

### ISSUE THREAD

**Issue by adrian1906** [davisking/dlib#419]
I have not been able to determine the cause of this error. 
I downloaded **dlib-19.2** for Ubuntu 16.04 and installed using

`sudo python setup.py install`

The build took about 5 minutes. I received the following message at the end:

**Installed /usr/local/lib/python2.7/dist-packages/dlib-19.2.0-py2.7-linux-x86_64.egg
Processing dependencies for dlib==19.2.0
Finished processing dependencies for dlib==19.2.0**

I then navigated to the `/dlib/dlib-19.2/python_examples`  folder and ran:
`python face_detector.py ../examples/faces/*.jpg`  (per the instruction in the face_detector.py file).

I received the error message:
**Illegal instruction (core dumped)**

I also ran 
`python2.7 face_detector.py ../examples/faces/*.jpg` just to be sure.

I also tried the  `pip install dlib` and still received the same error.

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework

**Comment by adrian1906** [comment]
Thank you for providing the link. I saw it before here:

`https://github.com/davisking/dlib/issues/217` 

In that thread, the individual fixed the problem by simply using
`pip install dlib.`

That did not work for me.

I failed to mention in my post that I installed boost using 

`sudo apt-get install libboost-all-dev`

I assumed that was all that was required. I did it both inside and outside a Python Environment.  I assumed that it was 'compiled against my specific version of Python interpreter' (Python 2.7)

Since that didn't work, I tried another way:

I downloaded **boost_1_63_0.tar.gz** and read the **Getting Started Guide**
Following their guidance, I moved my **boost_1_63_0** folder to **/usr/local**
I also added **/usr/local/boost_1_63_0/** to my PATH

The guide says that **"There is no need to “install Boost” in order to get started using Boost.Python"** 
 
[http://www.boost.org/doc/libs/1_63_0/libs/python/doc/html/building/no_install_quickstart.html]

I was able to successfully run the Jamfile.  I then tried to run the **dlib** `face_detection.py` file and failed.

I then inadvertently issued a **bjam** command at: `/usr/local/boos_1_63_0` and away it went! About 15 minutes later, I received the following message:

**The Boost C++ libraries were sucessfully built!
The following directory should be added to compiler include paths:
/usr/local/boost_1_63_0
The following directory should be added to linker library paths:
/usr/local/boost_1_63_0/stage/lib**


I added the two paths to $PATH and ran the face_decector.py file again.

I still get the illegal instruction (core dumped) error.

After more digging, I was able to find a **README** file under `libboost-python1.58-dev `(a part of _libboost-all-dev_)

It mentions **'linking against -lboost_python-py27'**

I have not tried this because I do not know how to do it.


```
Here is the content of that file.


        Choosing the default Python
        ---------------------------

You may simply link with -lboost_python.  This will always be the
default python version.

These default symlinks are automatically updated when the Python
runtime version changes.


        Choosing a specific Python Version
        ----------------------------------

The library names are suffixed by "-py24" and "-py25", allowing you to
select the specific Python version desired.  This holds true
for both the upstream names and the simplified Debian names.

So link against -lboost_python-py24 for Python 2.4.


 -- Steve M. Robbins <smr@debian.org>, Mon, 16 Feb 2009 16:04:22 z
```

**Comment by davisking** [comment]
Did you delete other copies of boost python and recompile dlib?

**Comment by adrian1906** [comment]
Yes.

I removed **libboost-all-dev** using
`sudo apt-get autoremove libboost-all-dev`

I ran` bash bootstrap.sh`

I then went to rebuild **dlib** using

`sudo python setup.py install`

and received an error indicating that boost was not installed.

I verified that my recommended path was correct.


I read through the error message and saw that it gave more detailed instructions on how to install Boost.Python

In the error message it said to run these commands:

```
./bootstrap.sh --with-libraries=python
./b2
sudo ./b2 install

```
I retried 

`sudo python setup.py install` 
and it compiled.

I also added `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` to my .profile

I navigated to the **python_examples** folder and typed:

`python face_detector.py ../examples/faces/*.jpg`

It still produced the I**llegal instruction (core_dumped)** error

Here's a snap shot:

```
adriansr@HoodServer:~/Downloads/dlib-19.2/python_examples$ ll
total 11616
drwxrwxr-x 2 adriansr adriansr     4096 Jan 31 20:36 ./
drwxrwxr-x 9 adriansr adriansr     4096 Jan 31 20:36 ../
-rwxr-xr-x 1 adriansr adriansr     2825 Oct 10 19:36 correlation_tracker.py*
-rw-r--r-- 1 root     root     11803640 Jan 31 20:36 dlib.so
-rwxr-xr-x 1 adriansr adriansr     3432 Oct 10 19:36 face_detector.py*
-rwxr-xr-x 1 adriansr adriansr     3900 Oct 10 19:36 face_landmark_detection.py*
-rwxr-xr-x 1 adriansr adriansr     2134 Oct 10 19:36 find_candidate_object_locations.py*
-rw-r--r-- 1 adriansr adriansr      808 Oct 10 19:36 LICENSE_FOR_EXAMPLE_PROGRAMS.txt
-rwxr-xr-x 1 adriansr adriansr     2558 Oct 10 19:36 max_cost_assignment.py*
-rwxr-xr-x 1 adriansr adriansr     8663 Oct 10 19:36 sequence_segmenter.py*
-rwxr-xr-x 1 adriansr adriansr     7276 Oct 10 19:36 svm_rank.py*
-rwxr-xr-x 1 adriansr adriansr    17617 Oct 10 19:36 svm_struct.py*
-rwxr-xr-x 1 adriansr adriansr     7225 Oct 10 19:36 train_object_detector.py*
-rwxr-xr-x 1 adriansr adriansr     6133 Oct 10 19:36 train_shape_predictor.py*
adriansr@HoodServer:~/Downloads/dlib-19.2/python_examples$ python face_detector.py ../examples/faces/*.jpg
Illegal instruction (core dumped)
adriansr@HoodServer:~/Downloads/dlib-19.2/python_examples$ 
```

**Comment by davisking** [comment]
You probably have more than one version of python installed and are mixing
them up.

**Comment by adrian1906** [comment]
I fixed the problem.  I found the solution here:
[http://stackoverflow.com/questions/37904503/illegal-instruction-core-dumped-while-running-dlib-face-detection]

My CPU (AMD Athlon 7550) only supports SSE2 and does not support SSE4. ( I don't know how I missed that :) ).  I had to make the following change in the file: **/tools/python/CMakeLists.txt** 

`set(USE_SSE2_INSTRUCTIONS ON CACHE BOOL "Use SSE2 instructions")`

**Comment by davisking** [comment]
Yeah, that would be a problem.  I set the default to use SSE4 since, I
think, you have to have a computer at least 9 years old to encounter this
error.  How old is your machine?

**Comment by adrian1906** [comment]
I had it since 2009. It's a Compaq that I converted to run Linux a few years ago. It didn't show its age until now. :).  Thanks for the help.

**Comment by davisking** [comment]
Ah, ok :)
