### ISSUE TITLE
Possible to get select()/poll() like behavior for multiple pipes?

### ISSUE THREAD

**Issue by rhd** [davisking/dlib#42]
Hi,

I love the dlib::pipe - one thing that I miss is the ability to service multiple pipes from the same thread (without polling them in a loop). Would something like this ever be possible with dlib?

Thanks!

**Comment by davisking** [comment]
Why don't you use just one pipe?  You can put multiple types of objects
into one by using a type_safe_union, for example, like this:
http://dlib.net/bridge_ex.cpp.html

**Comment by rhd** [comment]
Hi Davis,

It's more about data routing and convenience. The last project I did used multithreaded objects and pipes to communicate between them and there were several times I wish I had a select/poll like behavior to handle multiple pipes in a single thread. In the end, my app had a lot of threads because of the one thread per pipe limitation.

**Comment by davisking** [comment]
What were you doing though that required one thread to read from multiple pipes?  I wager you could have done it with one pipe containing type_safe_union objects.

**Comment by rhd** [comment]
Hi Davis,

I want to thank you for taking the time to entertain the idea :)

An analogy to your question might be "why do you need select()/poll() for sockets when you can find ways to put everything into a single socket?"

My specific example: I was reading a stream of bytes from multiple radios and I needed to route those bytes to various multithreaded_object via a pipe<vector<char>> for processing.

I could certainly frame the bytes and add routing information into the object I put into the pipe, but it's just not convenient. I just wanted to receive bytes from multiple input pipe, process them, put them in the various output pipes. Obviously, every input pipe required a thread - not the end of the world, just not the most convenient or efficient (threads are pretty heavy)

Thanks for listening!

**Comment by davisking** [comment]
No problem.

I would have added a select() for the pipes a while ago but it's not clear to me how to implement it in a way that is both robust and efficient. Maybe if I looked into it in more detail a reasonable solution would become obvious, but I'm also not convinced that using some kind of select() would result in simpler client code than framing approaches like the type_safe_union or any other user defined framing method.

For example, wouldn't it have been easier to so something like this?

```
dlib::pipe<std::pair<int,yourdata>> p(10);
...
std::pair<int,yourdata> data;
while(p.dequeue(data))
{
    // use data.first to recognize which radio the stuff in data.second came from.
} 
```
   
It's not clear to me that a select() based system would result in simpler client code.  How would select() tell you which pipe has data?  Something like `int id = select(p1,p2,p3,p4,p5,p6);` where the id tells you which parameter is ready?

**Comment by rhd** [comment]
Hi Davis,

You bring up some good points about using a pair<int, vector> for simple framing. That probably would have suited me OK. I would just have to be careful about unwanted copies (I'm stuck with older compilers). 
```
typedef vector<char> data_t;
typedef pair<int, data_t> id_data_t;
...then...
id_data_t data(1,data_t(1000000));
``` 

This should work and not cause any copies and yet it will allow me to read directly into the vector. See anything wrong here? I think this is good enough.

I think a select() would still be nicer though :)

> How would select() tell you which pipe has data? Something like int id = select(p1,p2,p3,p4,p5,p6); where the id tells you which parameter is ready?

Yea, that's kind of what I was thinking. Or you could give each pipe an ID internally and we could check against p1.id(), p2.id(), etc. I'm not a huge fan of depending on position to tell which pipe woke up.

**Comment by davisking** [comment]
In C++11 it won't result in copying.  But if you have an older compiler you will need to write a global swap that swaps that pair efficiently by calling the vector's swap.  But in C++11 std::pair comes with such a swap so you don't need to do anything.

That's a good point, having a p1.id() type of thing that matches the select return would be decent.  But still, it's not straightforward to implement efficiently so I'm not going to do it any time soon :)
