### ISSUE TITLE
Deep learning examples require DLL?

### ISSUE THREAD

**Issue by mohammadAdnan** [davisking/dlib#421]
Hello, 

Some examples such as Bayesian classifier and others don't require DLL. But deep learning examples require DLL, how i can get that?

Thanks

**Comment by davisking** [comment]
Nothing in dlib requires any sort of DLL.

**Comment by mohammadAdnan** [comment]
Deep learning examples are not working they gave me linking errors, but other examples such as neural network and Bayesian for example work fine.

**Comment by sschnug** [comment]
Then you probably did something wrong. I just tested this a few days ago with success.
The documentation tells you how to compile and use these examples.

Without much more information, there is not much help!
