### ISSUE TITLE
x64 build "train_shape_predictor_ex.cpp" crashes 

### ISSUE THREAD

**Issue by cetinol** [davisking/dlib#422]
Hello Mr.King,

Platform : Windows 64 operating system ,4 core cpu,c++,visual studio 2015.

- x32 build runs ,no problem
- x64 build crashes in line 128 of  **logger_kernel_1.cpp** with :
Exception thrown at 0x00007FF6048E8245 in Egitici.exe: 0xC000001D: Illegal Instruction.
Unhandled exception at 0x00007FF6048E8245 in Egitici.exe: 0xC000001D: Illegal Instruction.

- What is the problem ?
- Can you pls also state  minimum ram required for training 2000 HELEN images with 194 landmarks ?

Thank you very much in advance.

**Comment by davisking** [comment]
I don't see how that can possibly happen since the code in logger_kernel_1.cpp isn't in any way part of the train_shape_predictor_ex.cpp program.  It's not included or executed.

**Comment by cetinol** [comment]
I have included source.cpp (\dlib-19.2\dlib\all\source.cpp) as suggested .
 It has line a line #include "../logger/logger_kernel_1.cpp".
May be I sould not include source.cpp ?

Thank you.

**Comment by davisking** [comment]
Still, no one calls that function inside that program.  So I don't see how this can happen unless you are either editing the code or are running an entirely different program.

**Comment by cetinol** [comment]
I have also included imglab (jpeg support). Pls. find code below

Thank you.


#include <dlib/image_processing.h>
#include <dlib/data_io.h>
#include <iostream>

using namespace dlib;
using namespace std;

// ----------------------------------------------------------------------------------------
std::vector<std::vector<double> > get_interocular_distances(const std::vector<std::vector<full_object_detection> >& objects	);
// ----------------------------------------------------------------------------------------

int main(int argc, char** argv)
{
	try
	{
		const std::string faces_directory = "shape_predictor_194_face_landmarks";
		dlib::array<array2d<unsigned char> > images_train, images_test;
		std::vector<std::vector<full_object_detection> > faces_train, faces_test;
		load_image_dataset(images_train, faces_train, faces_directory + "/shape_predictor_194_face_landmarks.xml");
		load_image_dataset(images_test, faces_test, faces_directory + "/shape_predictor_194_face_landmarks_test.xml");
		shape_predictor_trainer trainer;

		trainer.set_cascade_depth(10);
		trainer.set_tree_depth(4);
		trainer.set_num_trees_per_cascade_level(500);
		trainer.set_nu(0.1);
		trainer.set_oversampling_amount(20);
		trainer.set_feature_pool_size(400);
		trainer.set_lambda(0.1);
		trainer.set_num_test_splits(20);
		trainer.set_feature_pool_region_padding(0);
		trainer.set_num_threads(2);

		shape_predictor sp = trainer.train(images_train, faces_train);
		cout << "mean training error: " <<
			test_shape_predictor(sp, images_train, faces_train, get_interocular_distances(faces_train)) << endl;
		cout << "mean testing error:  " <<
			test_shape_predictor(sp, images_test, faces_test, get_interocular_distances(faces_test)) << endl;

		// Finally, we save the model to disk so we can use it later.
		serialize("shape_predictor_194_face_landmarks/shape_predictor_194_face_landmarks.dat") << sp;
	}
	catch (exception& e)
	{
		cout << "\nexception thrown!" << endl;
		cout << e.what() << endl;
	}
}

// ----------------------------------------------------------------------------------------

double interocular_distance(
	const full_object_detection& det
	)
{
	dlib::vector<double, 2> l, r;
	double cnt = 0;
	// Find the center of the left eye by averaging the points around 
	// the eye.
	for (unsigned long i = 36; i <= 41; ++i)
	{
		l += det.part(i);
		++cnt;
	}
	l /= cnt;

	// Find the center of the right eye by averaging the points around 
	// the eye.
	cnt = 0;
	for (unsigned long i = 42; i <= 47; ++i)
	{
		r += det.part(i);
		++cnt;
	}
	r /= cnt;

	// Now return the distance between the centers of the eyes
	return length(l - r);
}

std::vector<std::vector<double> > get_interocular_distances(
	const std::vector<std::vector<full_object_detection> >& objects
	)
{
	std::vector<std::vector<double> > temp(objects.size());
	for (unsigned long i = 0; i < objects.size(); ++i)
	{
		for (unsigned long j = 0; j < objects[i].size(); ++j)
		{
			temp[i].push_back(interocular_distance(objects[i][j]));
		}
	}
	return temp;
}

// ----------------------------------------------------------------------------------------

**Comment by cetinol** [comment]
I have reinstalled dlib+vis studio 2015, everything seems fine.

Thank you very much.
