### ISSUE TITLE
Q: The influence of a GPU card on the Dlib or similar model's accuracy 

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#424]
Hello,

I decided to buy a GTX 1060 or GTX 1070 card to try with Deep Learning, but I am curious if the RAM size of The GPU or its bandwidth/speed/Cuda cores will affect the **accuracy** of the final model or not, by comparing these two specific GPU cards.

in the other word, I want to know selecting the GTX 1060 will just cause longer training time over GTX 1070, or it will affect the accuracy of the model either.

**Comment by davisking** [comment]
No. It only effects speed.

**Comment by VanitarNordic** [comment]
You know some people told me with a limited GPU memory (for example 6G with1060), we have to adjust the batch sizes to avoid GPU memory overflow during training.

By the way modifying batch sizes, training image sizes or similar parameters (to fit the GPU memory) will finally affect the model's accuracy, 

do you agree?

**Comment by davisking** [comment]
Yes. Obviously.  If you run a different algorithm you will get different results. But if you don't change anything about the algorithm then you will get the same results regardless of what hardware runs it.
