### ISSUE TITLE
Error detected at line 646 dlib\image_processing/shape_predictor.h

### ISSUE THREAD

**Issue by xam33r** [davisking/dlib#425]
I am trying to use train_shape_predictor.py to train a predectior.dat of my own but I receive following error and could not figure it out.

and according to your comments in the shape_predictor.h file  I have listed full objects.
your omments
// make sure the objects agree on the number of parts and that there is at
// least one full_object_detection. 
Error detected at line 646.

error message I get a runtime. I haven't changed original code in  train_shape_predictor.py 

Error detected in file c:\dlib\dlib\image_processing/shape_predictor.h.

Error detected in function class dlib::shape_predictor __cdecl dlib::shape_predictor_trainer::train<class dlib::array<class dlib::array2d<unsigned char,class dlib::memory_manager_stateless_kernel_1<char> >,class dlib::memory_manager_stateless_kernel_1<char> >>(const class dlib::array<class dlib::array2d<unsigned char,class dlib::memory_manager_stateless_kernel_1<char> >,class dlib::memory_manager_stateless_kernel_1<char> > &,const class std::vector<class std::vector<class dlib::full_object_detection,class std::allocator<class dlib::full_object_detection> >,class std::allocator<class std::vector<class dlib::full_object_detection,class std::allocator<class dlib::full_object_detection> > > > &) const.
Failing expression was objects[i][j].num_parts() != 0.

	 shape_predictor shape_predictor_trainer::train()

	 You can't give objects that don't have any parts to the trainer.

	 batch-represent/main.lua -outDir generated-embeddings -data aligned-images

**Comment by davisking** [comment]
I don't know what else to say that isn't already said by that error message.

**Comment by zoha21** [comment]
Could you please explain what the error means and how to fix it? I don't quite understand what they refer to.
