### ISSUE TITLE
png_loader.h seems loading 16-bit alpha grayscale incorrectly

### ISSUE THREAD

**Issue by hcl14** [davisking/dlib#428]
[`png_loader.h`](https://github.com/davisking/dlib/blob/master/dlib/image_loader/png_loader.h), which has functions called for `load_png()` , contains the following code for loading 16-bit grayscale png:

```
else if (is_graya() && bit_depth_ == 16)
            {
                for ( unsigned n = 0; n < height_;n++ )
                {
                    const uint16* v = (uint16*)get_row( n );
                    for ( unsigned m = 0; m < width_; m++ )
                    {
                        dlib::uint16 p = v[m*2];
                        if (!pixel_traits<pixel_type>::has_alpha)
                        {
                            assign_pixel( t[n][m], p );
                        }
                        else
                        {
                            dlib::uint16 pa = v[m*2+1];
                            rgb_alpha_pixel pix;
                            assign_pixel(pix, p);
                            assign_pixel(pix.alpha, pa);
                            assign_pixel(t[n][m], pix);
                        }
                    }
                }
}
```

But `rgb_alpha_pixel ` according to [`pixel.h`](https://github.com/davisking/dlib/blob/master/dlib/pixel.h) is 

```
unsigned char red;
unsigned char green;
unsigned char blue;
unsigned char alpha;
```

So when I'm loading the image where all the values are multiplied by 255, `save_png` then saves empty white output.

I've seen that `is_rgb() && bit_depth_ == 16` is converted to 8-bit below, so if 16-bit is totally unsupported (is it so?) then the code above can also convert to 8-bit (`matrix<rgb_alpha_pixel>` works fine for me for storing grayscale images). 

Or am I missing something about it? Maybe first dividing by 255 will be better than just `static_cast<uint8>` as done below?

The reason of asking is that I'm writing serializer to receive images from Python as I use NN face extractor and this interface seems not supported in Python:

```
template <long num_filters, typename SUBNET> using con5d = con<num_filters,5,5,2,2,SUBNET>;
template <long num_filters, typename SUBNET> using con5  = con<num_filters,5,5,1,1,SUBNET>;

template <typename SUBNET> using downsampler  = relu<affine<con5d<32, relu<affine<con5d<32, relu<affine<con5d<16,SUBNET>>>>>>>>>;
template <typename SUBNET> using rcon5  = relu<affine<con5<45,SUBNET>>>;

using net_type = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>;

net_type net;
```

**Comment by davisking** [comment]
Yeah, it should probably divide the values by 256 before converting to 8bits.  You can submit a pull request for that if you want :)

**Comment by hcl14** [comment]
What's about 16-bit images? I found that only non-alpha grayscale is possible, others are converted to 8-bit then.

**Comment by davisking** [comment]
Right.  There isn't a 16bit pixel type in dlib for this.  You could add one
if you want but you will need to expand the pixel_traits type appropriately
along with the core routines like assign_pixel().

**Comment by hcl14** [comment]
Here is my wrapper so far, now I'm able to send data from Python to NN code, maybe you will be interested (it is very simple though): 

https://github.com/hcl14/Python-Cpp-send-image-to-dlib-as-array

However I haven't found so far methods that allowed sending arbitrary image array (`int *` in this case) to dlib. It also contains my view of how the `load_png` function should be changed.
