### ISSUE TITLE
object detectors saved with C++ API can not be loaded by Python API

### ISSUE THREAD

**Issue by nzjrs** [davisking/dlib#43]
If I train a detector using the C tool

```bash
$ /train_object_detector -tv ....
```
that generates a file `object_detector.svm`. However if I load that file with the python API it doesn't work.

```python
dlib.simple_object_detector("object_detector.svm")
```
gives `RuntimeError: Error deserializing object of type int`

Interestingly however, the following does work

```python
print dlib.test_simple_object_detector(training_xml_path, "object_detector.svm")
```

and works perfectly, giving the same precision and recall as the trained C api.

**Comment by davisking** [comment]
Try the dlib.fhog_object_detector.
