### ISSUE TITLE
Very minor: But nicer exception when runing out of GPU memory instead of just Aborted

### ISSUE THREAD

**Issue by OranjeeGeneral** [davisking/dlib#430]
While I was trying to write some sample code to do fine tunning on a pre-trained resnet34 neural network in dlib I always stumbled on the problem that after two single training steps the program would just unexpectedly terminate with the only Exception thrown being Aborted.

After basically eliminating all the possibilities in my sample code. I went to check the GPU memory usage to realize it was running out of GPU memory.

Would be nice to see a better Exception than just Aborted I am sure the CuDNN interface must throw up something that could potentially be forwarded.

**Comment by davisking** [comment]
It does throw an exception when you run out of RAM.  That's literally what happens.  There is no abort in the code.

**Comment by OranjeeGeneral** [comment]
Sorry badly phrased. well the Exception is Aborted when you print it out with e.what().

**Comment by davisking** [comment]
Printing to the screen does not cause an abort, neither does looking at e.what().

**Comment by OranjeeGeneral** [comment]
Sorry you're misunderstanding the actual printout of e.what() to the console is I think "Aborted" 

Or more I am seeing this printed out on the console after it ran out of GPU memory:

terminate called without an active exception
Aborted
