### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by unicorn7t** [davisking/dlib#431]
This is the error I get while trying to train dlib simple object detector on a Server.

Invalid MIT-MAGIC-COOKIE-1 key  314 FATAL [1] dlib.gui_core: Unable to connect to the X display.
Traceback (most recent call last):
  File "train_objects_detector.py", line 76, in <module>
    win_det = dlib.image_window()
RuntimeError: Failed to initialize X11 resources

I am not able to understand the error and also not able to find workaround. I read threads with similar problem but their solution didn’t help me out. (eg: ISSUE #15, #21)

**Comment by davisking** [comment]
Don't call image_window then.

**Comment by unicorn7t** [comment]
Thanks. Code works fine now. But can you help me understand what was happening? @davisking

**Comment by davisking** [comment]
You tried to open a window on a server that doesn't have a UI.  What would you expect to happen?
