### ISSUE TITLE
How to create dlib.framework for OS X ?

### ISSUE THREAD

**Issue by atrbx5** [davisking/dlib#432]
```
cmake -G Xcode ..
cmake --build . --config Release
```

So now I have build folder with some examples.xcodeproj I can open it and run but what should I do next, how to create framework? Currently i have libdlib.a and sources in my project and as i understand it compiles every time.

**Comment by davisking** [comment]
I don't know.  This forum isn't the place to ask about how to write C++ programs for iOS.

**Comment by atrbx5** [comment]
Well it's more about building and integration... So e.g. OpenCV has scripts for creating platform specific builds. Also asking here because I am not the only one who use it and smd may already did it.

**Comment by davisking** [comment]
Well, dlib is just a bunch of C++ source code files.  So whatever you do to
build C++ source code in general will work.
