### ISSUE TITLE
dlib cross-platform boilerplate with web-camera (Qt based)

### ISSUE THREAD

**Issue by roscopecoltran** [davisking/dlib#433]
Hi all,

Hope you are all well !

Is it possible to create a cross-platform boilerplate for testing examples, maybe based on qt5 for limited computational resource, embedded systems and IoT devices ?

**Why ?**
Easy to test and boostrap, so we can improve performances more easily.

**How ?**
**Potential base #1**
I would suggest to use maybe a project like [gatherer](https://github.com/headupinclouds/gatherer) as a boilerplate base; it is a cross platform gpgpu opengl (es) shader pipeline framework: ogles_gpgpu + qt (UI). For anything related to vision, web camera, It would provide a demo for linux, ios, android and windows.

Also, it uses [hunter](https://github.com/ruslo/hunter), a CMake-driven cross-platform package manager for C++. Linux, Mac, Windows, iOS, Android, Raspberry Pi, and Polly, a toolcahain helper, 

They already have integrated DLIB [[here](https://github.com/ruslo/hunter/blob/master/cmake/projects/dlib/hunter.cmake#L79-L84)], or opencv for ios, android, desktop, windows ([link](https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenCV/hunter.cmake#L227-L262)).

It is really convenient for caching,  customizing some packages build. For eg, ([dlib shared](https://github.com/ruslo/hunter/tree/master/examples/dlib), [dlib static](https://github.com/ruslo/hunter/tree/master/examples/dlib-staticLib))

**Potential base #2**
Or your have this Vuforia employee project, [Yarrar](https://github.com/ndob/yarrar), stopped because he is working full-time now (ref [discussion](https://github.com/ndob/yarrar/issues/1)) , [examples](https://github.com/ndob/yarrar/tree/master/example) (iOS,Android,Desktop and Unity) 

**Potential base #3 **
Mixing both above, I can do that.

Nb. I saw tiny-dnn using these helpers for iOS; https://github.com/tiny-dnn/tiny-dnn/tree/master/examples/ios

**Questions:**
- Is there any simple example with MMOD, or the normal facial landmark detector for iOS/Android available ? (would be funny to test this repo, @grisevg,  with [facial landmarks for sheep](https://github.com/grisevg/TIFfacealignment), it made me laugh so much :-) )
- Are NEON instructions able to improve performances for MMOD (eg.[ dlib for arm](https://github.com/jbrjake/dlib_for_arm)) ?
- Shall I start a new issue ? I just commented as it was related to the fact to test the dog hipsterizer on iOS and to bundle a default client boilerplate for dlib cpu or mobile devices.

Hope I was clear enough about this suggestion for dlib, meanwhile I wish you all an awesome day !

Nb. it was inspired/related to a previous issue: https://github.com/davisking/dlib/issues/284

Cheers,
Richard

**Comment by davisking** [comment]
Yes, NEON instructions make things faster if they are used.  

I have no idea what your suggestion is about.  Making some desktop application that uses dlib?  That's super.  We aren't going to put desktop applications into the dlib repository though.  If you want to do something like that then it should be its own separate project.
