### ISSUE TITLE
fatal error: sqlite3.h: No such file or directory

### ISSUE THREAD

**Issue by typedeph** [davisking/dlib#434]
I get the follow fatal error when cmaking from a fresh clone of this repo on Xubuntu 16.04.1 LTS. I'm assuming this is a missing dependency but I wanted to get some clarity and get this listed as a dependency in some doc for dlib.
![sqlite_error](https://cloud.githubusercontent.com/assets/6923930/22845535/0a687458-efb1-11e6-9233-a58476e5a650.png)

**Comment by davisking** [comment]
sqlite isn't required.  CMake checks if your system has sqlite and only
tries to build the sqlite example if it finds sqlite.  There is something
funny about your system, where CMake thinks it found sqlite but really it's
not installed in the usual way.

**Comment by typedeph** [comment]
@dashesy Any recommendations on paths towards debugging this issue?

**Comment by davisking** [comment]
Do you even want to use the sqlite API?  If not then ignore it.

**Comment by typedeph** [comment]
I am a cmake novice, I am assuming `cmake --build .` is some type of target in your cmake file that sets some default sqlite dependencies. I have now compiled to completion by just typing `make` instead of `cmake --build .`.

**Comment by jiangwenj02** [comment]
sudo apt-get install libsqlite3-dev

**Comment by Aditi1Singh** [comment]
We don't need the sqlite API, so how to skip it?

**Comment by davisking** [comment]
Just ignore it.  It shouldn't be bothering you.

**Comment by Aditi1Singh** [comment]
It stops the building and the following error comes up.
![screenshot 1](https://user-images.githubusercontent.com/40431156/41660596-2a1d9f0a-74ba-11e8-9d87-3cacdc0ceeb9.png)
