### ISSUE TITLE
module 'dlib' has no attribute 'get_frontal_face_detector'

### ISSUE THREAD

**Issue by mohsin512** [davisking/dlib#435]
why thats arror accure ??

**Comment by davisking** [comment]
You must not have dlib installed, because `get_frontal_face_detector` is always part of it.

**Comment by mohsin512** [comment]
I have installed dlib successfully but error is remain. you can view the
below image

**Comment by Imtiazhussain123** [comment]
I have the same issue with dlib. I have all possible solution for that but the error is still stands on position
`AttributeError                          
Traceback (most recent call last)
<ipython-input-3-b08f5cd13242> in <module>
      2 import numpy as np
      3 import os
----> 4 import face_recognition

c:\users\imtia\anaconda3\envs\version3.6\lib\site-packages\face_recognition\__init__.py in <module>
      5 __version__ = '1.2.3'
      6 
----> 7 from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance

c:\users\imtia\anaconda3\envs\version3.6\lib\site-packages\face_recognition\api.py in <module>
     15 ImageFile.LOAD_TRUNCATED_IMAGES = True
     16 
---> 17 face_detector = dlib.get_frontal_face_detector()
     18 
     19 predictor_68_point_model = face_recognition_models.pose_predictor_model_location()

AttributeError: module 'dlib' has no attribute 'get_frontal_face_detector'`

**Comment by Luoluyao-studying** [comment]
> 我对dlib有同样的问题。我已经完成了所有可能的解决方案，但是错误仍然存​​在。
> 
> 在 2 import numpy as np中的AttributeError
> Traceback（最近一次调用为最后） 3 import os ----> 4 import face_recognition
> 
> 
> 
> 
> C：\用户\ imtia \ anaconda3 \ ENVS \ version3.6 \ lib中\站点包\ face_recognition_ _初始化_ _.py在
> 5 **版本** = '1.2.3'
> 6
> ----> 7从.API进口load_image_file，face_locations， batch_face_locations，face_landmarks，face_encodings，compare_faces，face_distance
> 
> c：\ users \ imtia \ anaconda3 \ envs \ version3.6 \ lib \ site-packages \ face_recognition \ api.py in
> 15 ImageFile.LOAD_TRUNCATED_IMAGES = True
> 16
> ---> 17 face_detector = dlib.get_frontal_face_detector（）
> 18
> 19预报器_68_point_model = face_recognition_models.pose_predictor_model_location（）
> 
> AttributeError：模块'dlib'没有属性'get_frontal_face_detector'`您好，请问您解决了吗
