### ISSUE TITLE
How to get second prediction with loss_multiclass_log?

### ISSUE THREAD

**Issue by alireza7991** [davisking/dlib#436]
I 'm currently using _loss_multiclass_log_ for classification problem and I can get the top scoring class easily, but, in my project, I need to know second and third classes in term of confidence, so is there any way to get confidences of **all classes**?

**Comment by davisking** [comment]
All you need to do is get the tensor output from the network.  It's the last layer.  How to access the layers is discussed in great detail in the introductory example programs and also in the reference documentation, which documents every function and class in dlib.

**Comment by alireza7991** [comment]
I 've just looked into loss layer and found how to get tensor output from network. Now I'm trying to return that values from the network by creating a custom operator() for the class. Where is definition of the nueral network so that I can edit that? I mean the class which we call to predict and train in dnn. (e.g. the net class in dnn introduction example).

**Comment by davisking** [comment]
You don't need to modify any code in dlib.  Once you have the tensor you
have the data.  Fundamentally, the tensor is just an array of float
values.  Those floats are the numbers you want.
