### ISSUE TITLE
How to solve the truth rectangle problem ...

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#439]
Hi,

I tried to train the `dnn_mmod_ex` and I got the following error. Would you please guide me to solve it?

![2017-02-14_13-02-41](https://cloud.githubusercontent.com/assets/18719591/22923259/edb9077a-f2b5-11e6-8cd3-0f66958af9a6.png)

**Comment by davisking** [comment]
There is too much diversity in your annotation rectangles.  Make them have a more similar aspect ratio.
