### ISSUE TITLE
error while using train_object_detector.py

### ISSUE THREAD

**Issue by great-thoughts** [davisking/dlib#44]
Hi, 
Thank you for the nice library. 
I have a question. I am using 'train_object_detector'  to detect whales(some images attached). When trying to train my detector, I got the following error:
Training with C: 5
Training with epsilon: 0.01
Training using 8 threads.
Training with sliding window 88 pixels wide by 73 pixels tall.
Training on both left and right flipped versions of images.
Traceback (most recent call last):
  File "/Users/mas/dlib/python_examples/train_object_detector.py", line 76, in <module>
    dlib.train_simple_object_detector(training_xml_path, "detector.svm", options)
RuntimeError: An impossible set of object labels was detected. This is happening because none
of the object locations checked by the supplied image scanner is a close enough
match to one of the truth boxes. To resolve this you need to either lower the 
match_eps or adjust the settings of the image scanner so that it hits this 
truth box. Or you could adjust the offending truth rectangle so it can be 
matched by the current image scanner. Also, if you are using the 
scan_image_pyramid object then you could try using a finer image pyramid or 
adding more detection templates. E.g. if one of your existing detection 
templates has a matching width/height ratio and smaller area than the offending
rectangle then a finer image pyramid would proably help. 

image index              108
match_eps:               0.5
best possible match:     0.480948
truth rect:              [(792, 412) (1134, 945)]
truth rect width/height: 0.642322
truth rect area:         183162
nearest detection template rect:              [(778, 537) (1122, 813)]
nearest detection template rect width/height: 1.24549
nearest detection template rect area:         95565

<img width="861" alt="screen shot 2015-09-30 at 5 34 01 pm" src="https://cloud.githubusercontent.com/assets/7269393/10194452/cac7756a-6799-11e5-9068-fc00239718de.png">
<img width="964" alt="screen shot 2015-09-30 at 5 34 19 pm" src="https://cloud.githubusercontent.com/assets/7269393/10194454/cb090c5a-6799-11e5-89f0-0ce65abd3a60.png">
<img width="815" alt="screen shot 2015-09-30 at 5 34 39 pm" src="https://cloud.githubusercontent.com/assets/7269393/10194453/cb05f7cc-6799-11e5-9b1f-c6a6314882db.png">

**Comment by davisking** [comment]
This is a sliding window detector.  So if you give it a truth rectangle that has a wildly different aspect ratio than the sliding window's aspect ratio it can't possibly succeed.  That's what the error is telling you.  So you need to use multiple different detectors to handle different aspect ratios.  Or make all your truth boxes have the same or nearly the same aspect ratio.

**Comment by great-thoughts** [comment]
I see. How can I access those parameters?

**Comment by johannmiller** [comment]
Hi Davis -
Sorry to bug you about this. Another commenter asked a slight variant to this question on a SourceForge thread: https://sourceforge.net/p/dclib/discussion/442518/thread/4f745394/

I'm seeing the same behavior. Only when I set ```add_left_right_image_flips = True``` do I get the error message posted above.  I'm curious why flipping would cause this. Thanks!
