### ISSUE TITLE
krr_classification_ex link error

### ISSUE THREAD

**Issue by typedeph** [davisking/dlib#440]
On Ubuntu 16.04, while trying to compile the examples as suggested on the site I am getting the following linker errors. under build in examples I have exported the cloned directory to my PATH.
![dlib_link_error](https://cloud.githubusercontent.com/assets/6923930/23004886/32903690-f3c7-11e6-988e-dd7aa2cbcf2e.png)
The closest thing I found related to this was: <https://github.com/cloudius-systems/osv/issues/474> but installing lib32stdc++-4.9-dev does not help. Any advice on how to proceed?

**Comment by davisking** [comment]
Those aren't dlib errors.  It looks like your compiler is just broken.  I would reinstall the compiler.

**Comment by typedeph** [comment]
You were right, it would seem my gcc packages were broken or something. On a fresh install of Ubuntu 16.04.2 everything works fine. I got #348 but after a libx11-dev install everything compiled to completion and the examples run.
