### ISSUE TITLE
Problem in dlib installation: #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."

### ISSUE THREAD

**Issue by hgpadovani** [davisking/dlib#441]
Hello there, if there is a topic related to this, please excuse me, I haven`t found it anywhere. So my problem is, I am trying to install dlib to use in one of my projects, and I am following the step-by-step here in the github, but I alway got this message: #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."

I don`t know how to overcome this, can someone give me some help, please?
Thank you all =)

**Comment by davisking** [comment]
What did you do so far?

**Comment by davisking** [comment]
Like what are you running?  What did you type?  What happened?  Are you using C++?  Why do you care about the GUI?

**Comment by hgpadovani** [comment]
I am just trying to install dlib, I have downloaded the directory here, and when I try to install it, I got this message error. I haven`t done nothing it but trying to install

**Comment by hgpadovani** [comment]
This message error pops up when I run this: mkdir build; cd build; cmake .. ; cmake --build .

**Comment by davisking** [comment]
Is that all it says?  Paste in exactly what you typed and what the output from cmake and the build process is.

Also, I'm pretty sure the cmake output has a huge warning message that explains exactly how to solve this.  It should also be noted that GUI support isn't needed to use dlib. That's why it's an option.  It wouldn't be optional if it wasn't :)

**Comment by hgpadovani** [comment]
So, in the dlib folder downloaded in my ubuntu, I did the following:
cd examples
mkdir build
cd build
cmake ..
cmake --build . --config Release

after that, it goes until 93% of the installationg process, then displays this message:

[ 93%] Building CXX object CMakeFiles/dnn_face_recognition_ex.dir/dnn_face_recognition_ex.cpp.o
In file included from /home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets/../gui_core/xlib.h:4:0,
                 from /home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets/../gui_core.h:14,
                 from /home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets/drawable.h:8,
                 from /home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets/widgets.h:9,
                 from /home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets.h:13,
                 from /home/hugo/Downloads/dlib/examples/dnn_face_recognition_ex.cpp:22:
/home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets/../gui_core/gui_core_kernel_2.h:11:2: error: #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
 #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLI
  ^
/home/hugo/Downloads/dlib/dlib/../dlib/gui_widgets/../gui_core/gui_core_kernel_2.h:12:2: error: #error "Also make sure you have libx11-dev installed on your system"
 #error "Also make sure you have libx11-dev installed on your system"
  ^
CMakeFiles/dnn_face_recognition_ex.dir/build.make:62: recipe for target 'CMakeFiles/dnn_face_recognition_ex.dir/dnn_face_recognition_ex.cpp.o' failed
make[2]: *** [CMakeFiles/dnn_face_recognition_ex.dir/dnn_face_recognition_ex.cpp.o] Error 1
CMakeFiles/Makefile2:2398: recipe for target 'CMakeFiles/dnn_face_recognition_ex.dir/all' failed
make[1]: *** [CMakeFiles/dnn_face_recognition_ex.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have no idea how to solve this =(

**Comment by davisking** [comment]
What did cmake output on the first command?

**Comment by hgpadovani** [comment]
cmake ..
-- C++11 activated.
-- Enabling AVX instructions
No GUI support, so we won't build the dnn_mmod_ex example.
No GUI support, so we won't build the dnn_mmod_face_detection_ex example.
No GUI support, so we won't build the random_cropper_ex example.
No GUI support, so we won't build the dnn_mmod_dog_hipsterizer example.
No GUI support, so we won't build the dnn_imagenet_ex example.
No GUI support, so we won't build the 3d_point_cloud_ex example.
No GUI support, so we won't build the bayes_net_gui_ex example.
No GUI support, so we won't build the face_detection_ex example.
No GUI support, so we won't build the face_landmark_detection_ex example.
No GUI support, so we won't build the fhog_ex example.
No GUI support, so we won't build the fhog_object_detector_ex example.
No GUI support, so we won't build the gui_api_ex example.
No GUI support, so we won't build the hough_transform_ex example.
No GUI support, so we won't build the image_ex example.
No GUI support, so we won't build the mpc_ex example.
No GUI support, so we won't build the object_detector_advanced_ex example.
No GUI support, so we won't build the object_detector_ex example.
No GUI support, so we won't build the one_class_classifiers_ex example.
No GUI support, so we won't build the surf_ex example.
No GUI support, so we won't build the train_object_detector example.
No GUI support, so we won't build the video_tracking_ex example.
No GUI support, so we won't build the webcam_face_pose_ex example.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hugo/Downloads/dlib/examples/build

**Comment by davisking** [comment]
Delete the build folder and run it fresh. What does it say?

**Comment by hgpadovani** [comment]
cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++11 activated.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
OpenCV not found, so we won't build the webcam_face_pose_ex example.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hugo/Downloads/dlib/examples/build

**Comment by davisking** [comment]
Hmm. There should have been a big message that tells you what to type to get GUI support. Just to make sure, when you compile now does it work?

**Comment by hgpadovani** [comment]
no, it is pops up the same error message in the end of the installation process =(

**Comment by davisking** [comment]
What does `cmake -LA` output when you run it in the build folder?

**Comment by hgpadovani** [comment]
CMake Error: The source directory "/home/hugo/Downloads/dlib/examples/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_FLAGS:STRING= -Wreturn-type -DDLIB_JPEG_SUPPORT    -DDLIB_PNG_SUPPORT  
CMAKE_CXX_FLAGS_DEBUG:STRING=-g -DENABLE_ASSERTS
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
...

and the list goes for a while

**Comment by davisking** [comment]
Post the whole list

**Comment by hgpadovani** [comment]
cmake -LA                 
CMake Error: The source directory "/home/hugo/Downloads/dlib/examples/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_FLAGS:STRING= -Wreturn-type -DDLIB_JPEG_SUPPORT    -DDLIB_PNG_SUPPORT  
CMAKE_CXX_FLAGS_DEBUG:STRING=-g -DENABLE_ASSERTS
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_CUDART_LIBRARY:FILEPATH=CUDA_CUDART_LIBRARY-NOTFOUND
CUDA_CUDA_LIBRARY:FILEPATH=CUDA_CUDA_LIBRARY-NOTFOUND
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_NVCC_EXECUTABLE:FILEPATH=CUDA_NVCC_EXECUTABLE-NOTFOUND
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TARGET_CPU_ARCH:STRING=
CUDA_TOOLKIT_INCLUDE:PATH=CUDA_TOOLKIT_INCLUDE-NOTFOUND
CUDA_TOOLKIT_ROOT_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
CUDA_TOOLKIT_TARGET_DIR:PATH=CUDA_TOOLKIT_ROOT_DIR-NOTFOUND
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=OFF
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_cublas_LIBRARY:FILEPATH=CUDA_cublas_LIBRARY-NOTFOUND
CUDA_cublasemu_LIBRARY:FILEPATH=CUDA_cublasemu_LIBRARY-NOTFOUND
CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND
CUDA_cufftemu_LIBRARY:FILEPATH=CUDA_cufftemu_LIBRARY-NOTFOUND
DLIB_ENABLE_ASSERTS:BOOL=OFF
DLIB_ENABLE_STACK_TRACE:BOOL=OFF
DLIB_GIF_SUPPORT:STRING=OFF
DLIB_ISO_CPP_ONLY:BOOL=OFF
DLIB_JPEG_SUPPORT:BOOL=ON
DLIB_LINK_WITH_SQLITE3:STRING=OFF
DLIB_NO_GUI_SUPPORT:BOOL=OFF
DLIB_PNG_SUPPORT:BOOL=ON
DLIB_USE_BLAS:STRING=OFF
DLIB_USE_CUDA:STRING=OFF
DLIB_USE_LAPACK:STRING=OFF
DLIB_USE_MKL_FFT:STRING=OFF
GIF_INCLUDE_DIR:PATH=GIF_INCLUDE_DIR-NOTFOUND
GIF_LIBRARY:FILEPATH=GIF_LIBRARY-NOTFOUND
JPEG_INCLUDE_DIR:PATH=JPEG_INCLUDE_DIR-NOTFOUND
JPEG_LIBRARY:FILEPATH=JPEG_LIBRARY-NOTFOUND
OpenCV_DIR:PATH=OpenCV_DIR-NOTFOUND
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/bin/pkg-config
USE_AVX_INSTRUCTIONS:BOOL=OFF
USE_SSE2_INSTRUCTIONS:BOOL=OFF
USE_SSE4_INSTRUCTIONS:BOOL=OFF
X11_ICE_INCLUDE_PATH:PATH=X11_ICE_INCLUDE_PATH-NOTFOUND
X11_ICE_LIB:FILEPATH=X11_ICE_LIB-NOTFOUND
X11_SM_INCLUDE_PATH:PATH=X11_SM_INCLUDE_PATH-NOTFOUND
X11_SM_LIB:FILEPATH=X11_SM_LIB-NOTFOUND
X11_X11_INCLUDE_PATH:PATH=/usr/include
X11_X11_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libX11.so
X11_XRes_INCLUDE_PATH:PATH=X11_XRes_INCLUDE_PATH-NOTFOUND
X11_XRes_LIB:FILEPATH=X11_XRes_LIB-NOTFOUND
X11_XShm_INCLUDE_PATH:PATH=X11_XShm_INCLUDE_PATH-NOTFOUND
X11_XSync_INCLUDE_PATH:PATH=X11_XSync_INCLUDE_PATH-NOTFOUND
X11_XTest_INCLUDE_PATH:PATH=X11_XTest_INCLUDE_PATH-NOTFOUND
X11_XTest_LIB:FILEPATH=X11_XTest_LIB-NOTFOUND
X11_Xaccessrules_INCLUDE_PATH:PATH=X11_Xaccessrules_INCLUDE_PATH-NOTFOUND
X11_Xaccessstr_INCLUDE_PATH:PATH=/usr/include
X11_Xau_INCLUDE_PATH:PATH=/usr/include
X11_Xau_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libXau.so
X11_Xcomposite_INCLUDE_PATH:PATH=X11_Xcomposite_INCLUDE_PATH-NOTFOUND
X11_Xcomposite_LIB:FILEPATH=X11_Xcomposite_LIB-NOTFOUND
X11_Xcursor_INCLUDE_PATH:PATH=X11_Xcursor_INCLUDE_PATH-NOTFOUND
X11_Xcursor_LIB:FILEPATH=X11_Xcursor_LIB-NOTFOUND
X11_Xdamage_INCLUDE_PATH:PATH=X11_Xdamage_INCLUDE_PATH-NOTFOUND
X11_Xdamage_LIB:FILEPATH=X11_Xdamage_LIB-NOTFOUND
X11_Xdmcp_INCLUDE_PATH:PATH=/usr/include
X11_Xdmcp_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libXdmcp.so
X11_Xext_LIB:FILEPATH=X11_Xext_LIB-NOTFOUND
X11_Xfixes_INCLUDE_PATH:PATH=X11_Xfixes_INCLUDE_PATH-NOTFOUND
X11_Xfixes_LIB:FILEPATH=X11_Xfixes_LIB-NOTFOUND
X11_Xft_INCLUDE_PATH:PATH=X11_Xft_INCLUDE_PATH-NOTFOUND
X11_Xft_LIB:FILEPATH=X11_Xft_LIB-NOTFOUND
X11_Xi_INCLUDE_PATH:PATH=X11_Xi_INCLUDE_PATH-NOTFOUND
X11_Xi_LIB:FILEPATH=X11_Xi_LIB-NOTFOUND
X11_Xinerama_INCLUDE_PATH:PATH=X11_Xinerama_INCLUDE_PATH-NOTFOUND
X11_Xinerama_LIB:FILEPATH=X11_Xinerama_LIB-NOTFOUND
X11_Xinput_INCLUDE_PATH:PATH=X11_Xinput_INCLUDE_PATH-NOTFOUND
X11_Xinput_LIB:FILEPATH=X11_Xinput_LIB-NOTFOUND
X11_Xkb_INCLUDE_PATH:PATH=/usr/include
X11_Xkbfile_INCLUDE_PATH:PATH=X11_Xkbfile_INCLUDE_PATH-NOTFOUND
X11_Xkbfile_LIB:FILEPATH=X11_Xkbfile_LIB-NOTFOUND
X11_Xkblib_INCLUDE_PATH:PATH=/usr/include
X11_Xlib_INCLUDE_PATH:PATH=/usr/include
X11_Xmu_INCLUDE_PATH:PATH=X11_Xmu_INCLUDE_PATH-NOTFOUND
X11_Xmu_LIB:FILEPATH=X11_Xmu_LIB-NOTFOUND
X11_Xpm_INCLUDE_PATH:PATH=X11_Xpm_INCLUDE_PATH-NOTFOUND
X11_Xpm_LIB:FILEPATH=X11_Xpm_LIB-NOTFOUND
X11_Xrandr_INCLUDE_PATH:PATH=X11_Xrandr_INCLUDE_PATH-NOTFOUND
X11_Xrandr_LIB:FILEPATH=X11_Xrandr_LIB-NOTFOUND
X11_Xrender_INCLUDE_PATH:PATH=X11_Xrender_INCLUDE_PATH-NOTFOUND
X11_Xrender_LIB:FILEPATH=X11_Xrender_LIB-NOTFOUND
X11_Xscreensaver_INCLUDE_PATH:PATH=X11_Xscreensaver_INCLUDE_PATH-NOTFOUND
X11_Xscreensaver_LIB:FILEPATH=X11_Xscreensaver_LIB-NOTFOUND
X11_Xshape_INCLUDE_PATH:PATH=X11_Xshape_INCLUDE_PATH-NOTFOUND
X11_Xt_INCLUDE_PATH:PATH=X11_Xt_INCLUDE_PATH-NOTFOUND
X11_Xt_LIB:FILEPATH=X11_Xt_LIB-NOTFOUND
X11_Xutil_INCLUDE_PATH:PATH=/usr/include
X11_Xv_INCLUDE_PATH:PATH=X11_Xv_INCLUDE_PATH-NOTFOUND
X11_Xv_LIB:FILEPATH=X11_Xv_LIB-NOTFOUND
X11_Xxf86misc_LIB:FILEPATH=X11_Xxf86misc_LIB-NOTFOUND
X11_Xxf86vm_LIB:FILEPATH=X11_Xxf86vm_LIB-NOTFOUND
X11_dpms_INCLUDE_PATH:PATH=X11_dpms_INCLUDE_PATH-NOTFOUND
X11_xf86misc_INCLUDE_PATH:PATH=X11_xf86misc_INCLUDE_PATH-NOTFOUND
X11_xf86vmode_INCLUDE_PATH:PATH=X11_xf86vmode_INCLUDE_PATH-NOTFOUND
ZLIB_INCLUDE_DIR:PATH=ZLIB_INCLUDE_DIR-NOTFOUND
ZLIB_LIBRARY_DEBUG:FILEPATH=ZLIB_LIBRARY_DEBUG-NOTFOUND
ZLIB_LIBRARY_RELEASE:FILEPATH=ZLIB_LIBRARY_RELEASE-NOTFOUND
atlas_lib:FILEPATH=atlas_lib-NOTFOUND
cblas_lib:FILEPATH=cblas_lib-NOTFOUND
generic_blas:FILEPATH=generic_blas-NOTFOUND
lapack_lib:FILEPATH=lapack_lib-NOTFOUND
mkl_core:FILEPATH=mkl_core-NOTFOUND
mkl_include_dir:PATH=mkl_include_dir-NOTFOUND
mkl_intel:FILEPATH=mkl_intel-NOTFOUND
mkl_iomp:FILEPATH=mkl_iomp-NOTFOUND
mkl_pthread:FILEPATH=/usr/lib/x86_64-linux-gnu/libpthread.so
mkl_rt:FILEPATH=mkl_rt-NOTFOUND
mkl_thread:FILEPATH=mkl_thread-NOTFOUND
nsllib:FILEPATH=/usr/lib/x86_64-linux-gnu/libnsl.so
satlas_lib:FILEPATH=satlas_lib-NOTFOUND
socketlib:FILEPATH=socketlib-NOTFOUND
sqlite:FILEPATH=sqlite-NOTFOUND
sqlite_path:PATH=sqlite_path-NOTFOUND
tatlas_lib:FILEPATH=tatlas_lib-NOTFOUND

**Comment by davisking** [comment]
I don't see how you could be getting the error you are getting.  The CMake output shows that it's finding X11, you can see in what you posted `DLIB_NO_GUI_SUPPORT:BOOL=OFF`.  Moreover, this variable contains the compile flags `CMAKE_CXX_FLAGS:STRING= -Wreturn-type -DDLIB_JPEG_SUPPORT -DDLIB_PNG_SUPPORT` and you can see it doesn't have a `-DDLIB_NO_GUI_SUPPORT` entry, which is what triggers the error you are reporting. 

Are you sure you haven't modified dlib in some way?  Somewhere something is defining the DLIB_NO_GUI_SUPPORT preprocessor macro and it sure don't look like it's cmake.  Try this, paste in the first few lines of output from this command: `make VERBOSE=1 | grep GUI`

**Comment by hgpadovani** [comment]
make VERBOSE=1 | grep GUI
/home/hugo/Downloads/dlib/dlib/external/libjpeg/jdhuff.cpp:23:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wshift-negative-value"
                                ^
/home/hugo/Downloads/dlib/dlib/external/libjpeg/jdphuff.cpp:23:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wshift-negative-value"
                                ^
it is still running. Do you want me to wait until the end and post something else?

**Comment by davisking** [comment]
Ok, more lines than that :)

I want to see the compiler invocation.  Even better than the first one though, you can find the compiler invocation for the file that gives the error message.  It will contain the entire compile command.

**Comment by davisking** [comment]
Well, really the point is to see if there is any command that includes -DDLIB_NO_GUI_SUPPORT.  If that never happens then it means somewhere on your system is some C++ file or something that defines DLIB_NO_GUI_SUPPORT.

**Comment by davisking** [comment]
So find the compiler line for the file giving you the error, CMakeFiles/dnn_face_recognition_ex.dir/dnn_face_recognition_ex.cpp.o, that file.  What is it?

**Comment by hgpadovani** [comment]
Just rewinding, the command didn't return anything else, just that.

About the compiler line, how do I do that? I am a little bit new to linux, I am not sure how to do this.

**Comment by davisking** [comment]
Just do `make VERBOSE=1`.  The output will be huge and you should find the part where the error happens.

**Comment by davisking** [comment]
Here, do `make VERBOSE=1 dnn_face_recognition_ex`

**Comment by davisking** [comment]
Or even more to the point: `Here, do `make VERBOSE=1 dnn_face_recognition_ex | grep cpp`

**Comment by hgpadovani** [comment]
for: make VERBOSE=1 dnn_face_recognition_ex, I got this message:
make VERBOSE=1 dnn_face_recognition_ex
/usr/bin/cmake -H/home/hugo/Downloads/dlib/examples -B/home/hugo/Downloads/dlib/examples/build --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 dnn_face_recognition_ex
make[1]: Entering directory '/home/hugo/Downloads/dlib/examples/build'
/usr/bin/cmake -H/home/hugo/Downloads/dlib/examples -B/home/hugo/Downloads/dlib/examples/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/hugo/Downloads/dlib/examples/build/CMakeFiles 42
make -f CMakeFiles/Makefile2 CMakeFiles/dnn_face_recognition_ex.dir/all
make[2]: Entering directory '/home/hugo/Downloads/dlib/examples/build'
make -f dlib_build/CMakeFiles/dlib.dir/build.make dlib_build/CMakeFiles/dlib.dir/depend
make[3]: Entering directory '/home/hugo/Downloads/dlib/examples/build'
cd /home/hugo/Downloads/dlib/examples/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Downloads/dlib/examples /home/hugo/Downloads/dlib/dlib /home/hugo/Downloads/dlib/examples/build /home/hugo/Downloads/dlib/examples/build/dlib_build /home/hugo/Downloads/dlib/examples/build/dlib_build/CMakeFiles/dlib.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/hugo/Downloads/dlib/examples/build'
make -f dlib_build/CMakeFiles/dlib.dir/build.make dlib_build/CMakeFiles/dlib.dir/build
make[3]: Entering directory '/home/hugo/Downloads/dlib/examples/build'
make[3]: Nothing to be done for 'dlib_build/CMakeFiles/dlib.dir/build'.
make[3]: Leaving directory '/home/hugo/Downloads/dlib/examples/build'
[ 97%] Built target dlib
make -f CMakeFiles/dnn_face_recognition_ex.dir/build.make CMakeFiles/dnn_face_recognition_ex.dir/depend
make[3]: Entering directory '/home/hugo/Downloads/dlib/examples/build'
cd /home/hugo/Downloads/dlib/examples/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/hugo/Downloads/dlib/examples /home/hugo/Downloads/dlib/examples /home/hugo/Downloads/dlib/examples/build /home/hugo/Downloads/dlib/examples/build /home/hugo/Downloads/dlib/examples/build/CMakeFiles/dnn_face_recognition_ex.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/hugo/Downloads/dlib/examples/build'
make -f CMakeFiles/dnn_face_recognition_ex.dir/build.make CMakeFiles/dnn_face_recognition_ex.dir/build
make[3]: Entering directory '/home/hugo/Downloads/dlib/examples/build'
make[3]: Nothing to be done for 'CMakeFiles/dnn_face_recognition_ex.dir/build'.
make[3]: Leaving directory '/home/hugo/Downloads/dlib/examples/build'
[100%] Built target dnn_face_recognition_ex
make[2]: Leaving directory '/home/hugo/Downloads/dlib/examples/build'
/usr/bin/cmake -E cmake_progress_start /home/hugo/Downloads/dlib/examples/build/CMakeFiles 0
make[1]: Leaving directory '/home/hugo/Downloads/dlib/examples/build'


but for make VERBOSE=1 dnn_face_recognition_ex | grep cpp, I didn't get any output

**Comment by davisking** [comment]
Uh, that message you just pasted says it worked.

**Comment by hgpadovani** [comment]
So it worked? that is it? dlib is OK for use?

**Comment by davisking** [comment]
It's been OK for use this entire time.  Regardless of if you have a GUI around to use.

**Comment by hgpadovani** [comment]
I tried to use one script (face_landmark_detection.py) and got this message:

Traceback (most recent call last):
  File "face_landmark_detection.py", line 47, in <module>
    import dlib
ImportError: No module named 'dlib'

**Comment by davisking** [comment]
You didn't compile the python module.  You just built a bunch of C++ example programs.  If you want to use python you have to follow the instructions to compile it for python.

**Comment by hgpadovani** [comment]
I did compile, and get this message:

sudo python3 setup.py install --yes USE_AVX_INSTRUCTIONS
running install
running bdist_egg
running build
Detected Python architecture: 64bit
Detected platform: linux
Removing build directory /home/hugo/Downloads/dlib/./tools/python/build
Configuring cmake ...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Boost
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py35
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (Required is at least
  version "3.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPythonLibs.cmake:265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/hugo/Downloads/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
  CMakeLists.txt:6 (include)
-- Configuring incomplete, errors occurred!
See also "/home/hugo/Downloads/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
error: cmake configuration failed!

**Comment by davisking** [comment]
You need to install boost-python

**Comment by davisking** [comment]
Well and also the python development header files.  It seems like maybe you have boost-python. But I'm a little surprised that you would have boost-python but no the python headers.
