### ISSUE TITLE
dnn_face_recognition on lfw

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [davisking/dlib#444]
I changed the dnn_face_recognition_ex.cpp to evaluate the model's performnce on LFW.
The accuracy i got is 98.8% after jitter_image.
There are 55 images in LFW failed to detect a face successfully.
How can i get the 99.38 with the model on dlib?

**Comment by davisking** [comment]
Face detection isn't part of the LFW evaluation.  Importantly, the images in the LFW challenge are already face detections. Each image is a capture of one face that is centered squarely in the middle.   LFW is an evaluation of the face verification part only.  

So don't throw away images that the HOG detector, in the example program, incidentally doesn't find.  That's not part of LFW.  Although, as an aside, dlib includes a CNN face detector that's more accurate and can find all the faces in LFW, but is slower to execute.

**Comment by ZHAIXINGZHAIYUE** [comment]
thanks.To get the accuracy 0.993 using your provided model on LFW, how should I preprocess the original LFW dataset,thanks again.

**Comment by davisking** [comment]
Use the HOG detector's box, but if it doesn't find one, put a box in the middle of the image.

**Comment by e-fominov** [comment]
@ZHAIXINGZHAIYUE , 98.8 and 99.3 - what is this? face detection accuracy, or AUC computed by LFW method?

if you are talking about AUC (i.e. face comparison accuracy) - this is on you, how you train the network. Dlib has a only sample of metric learning, but it is not the face recognition library

**Comment by ZHAIXINGZHAIYUE** [comment]
@e-fominov It's AUC ，dlib has provided a trained model .

**Comment by davisking** [comment]
Well, LFW isn't measured in AUC.  It's classifier accuracy at the decision threshold (0.6) in this case.

**Comment by ZHAIXINGZHAIYUE** [comment]
@e-fominov Sorry .It's not AUC. It's classifier accuracy.I compute the distance of every pair provided by LFW.Then seclected a best threshold to get the highest accuracy on LFW. 
@davisking To evaluate the performance of your provided model,we need't get the face's landmark 'extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);' ?
what we need to do is get the bounding box?
By the way,the size of image to feed thr model must be 150*150?

**Comment by davisking** [comment]
yes

**Comment by ZHAIXINGZHAIYUE** [comment]
THE image size  we feed the model must be 150*150?

**Comment by ZHAIXINGZHAIYUE** [comment]
another question,which LFW dataset to use :`All images as gzipped tar file` `All images aligned with deep funneling ` `All images aligned with funneling`  `All images aligned with commercial face alignment software`?
thanks .

**Comment by davisking** [comment]
I'm not going to walk you through writing a program step by step.  I also don't want to explain the LFW benchmark to you when it's perfectly well explained on the LFW webpage.  So you should read the LFW evaluation documentation and try to understand what your goals are.  Then you can do an evaluation that hits at some aspect of performance you care about.

**Comment by ZHAIXINGZHAIYUE** [comment]
sorry.

**Comment by davisking** [comment]
No worries.  I'm just saying though, read the available documentation :)
