### ISSUE TITLE
Geting a CURAND_LAUNCH_FAILURE when running the dnn test suite

### ISSUE THREAD

**Issue by OranjeeGeneral** [davisking/dlib#445]
Right in the second test (test_conv) in dnn.cpp when it tries to random uniform fill the data tensor.

Any idea why that would be? And how to resolve this? 
Everything else seems to work fine.

**Comment by davisking** [comment]
There is probably something wrong with your CUDA install.  I would reinstall all the CUDA stuff (nvcc, cuda toolkit, cuDNN, etc.)

**Comment by OranjeeGeneral** [comment]
Okay thanks will try but still very odd though because I can run all the dnn examples including the training and testing ones. Is CURAND not used in those for initializing some of the initial parameter spaces?

**Comment by davisking** [comment]
Right, cuRAND isn't used much.
