### ISSUE TITLE
markers of cut in imglab

### ISSUE THREAD

**Issue by patatetom** [davisking/dlib#449]
hi Davis,
do you think it is possible to have in imglab "markers of cut" that would follow the mouse as in this image ?
![2017 02 24-10 32 39](https://cloud.githubusercontent.com/assets/14196171/23304898/71dddf10-fa9c-11e6-9268-dfd6bc285db7.png)
this would greatly facilitate the selection of objects.
regards, lacsaP.

**Comment by keaaw** [comment]
Additionally, being able to clear, move (drag), and resize the placement of a selection box, and showing  (x, y, width, height) of the current box while it's being drawn or resized.

**Comment by davisking** [comment]
You can already remove or resize boxes.

**Comment by davisking** [comment]
Just added this to imglab :)

**Comment by patatetom** [comment]
thanks Davis !
![cool -](https://cloud.githubusercontent.com/assets/14196171/23589838/5458799c-01d5-11e7-9081-196d3d25ec04.png)

**Comment by davisking** [comment]
No problem
