### ISSUE TITLE
my classifier doesn't detect any object in the training dataset

### ISSUE THREAD

**Issue by great-thoughts** [davisking/dlib#45]
I changed the true boxes so to get rid of the error due to the variation in the aspect ratio of the truth box. the code is now training the classier. However, the trained classifier did not detect a single box in the whole training dataset consisting of around 100 images. 

Any help will be appreciated

Thank you.

PS: those are few images from my training dataset
![screen shot 2015-10-03 at 9 26 55 pm](https://cloud.githubusercontent.com/assets/7269393/10264297/4b83d8bc-6a18-11e5-8d96-8377857ef862.png)
![screen shot 2015-10-03 at 9 28 20 pm](https://cloud.githubusercontent.com/assets/7269393/10264301/4bca6ba6-6a18-11e5-9113-8a9baf21f913.png)
![screen shot 2015-10-03 at 9 29 13 pm](https://cloud.githubusercontent.com/assets/7269393/10264303/4bcc1ff0-6a18-11e5-8b5d-c17fd9a97086.png)
![screen shot 2015-10-03 at 9 29 23 pm](https://cloud.githubusercontent.com/assets/7269393/10264299/4bc74624-6a18-11e5-9650-fb4607eab789.png)
![screen shot 2015-10-03 at 9 29 30 pm](https://cloud.githubusercontent.com/assets/7269393/10264300/4bc77dce-6a18-11e5-9125-f8f07cefa56a.png)
![screen shot 2015-10-03 at 9 29 44 pm](https://cloud.githubusercontent.com/assets/7269393/10264302/4bcaf364-6a18-11e5-8107-0c25366bcc50.png)
![screen shot 2015-10-03 at 9 29 57 pm](https://cloud.githubusercontent.com/assets/7269393/10264298/4bb05d92-6a18-11e5-97b1-b4d5f8ba85bf.png)
![screen shot 2015-10-03 at 9 30 12 pm](https://cloud.githubusercontent.com/assets/7269393/10264304/4bdcb932-6a18-11e5-92d6-5f88adf2f0fe.png)

**Comment by davisking** [comment]
A HOG based object detector isn't going to be good for dealing with complex rotating objects.  It's basically just a sliding template.  If you can train one where all the whales are oriented the same way then it might work but it's impossible to say.
