### ISSUE TITLE
Python equivalent for pyramid_up

### ISSUE THREAD

**Issue by anirudt** [davisking/dlib#450]
Hi,

I noticed that there isn't a Python equivalent for pyramid_up, which is quite essential for detecting objects in smaller images. Could this be added to future action points, or is a Python binding for the same considered irrelevant?

I don't mind closing this down if it is not the need of the hour, I would like to try the porting myself, would you mind showing some pointers?

**Comment by davisking** [comment]
There are already a lot of python image processing libraries that provide
equivalent functions.  But if you want to submit a pull request for this
that's fine with me.
