### ISSUE TITLE
how to train the resnet/face model

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#453]
could I just simply use dnn_metric_learning_on_images_ex.cpp for training process?
dnn_metric_learning_on_images_ex  ./topdirofimages/

**Comment by davisking** [comment]
Read the example.  It is literally written to answer this question.

**Comment by anguoyang** [comment]
i am sorry to re-open this issue, as i could not find dnn_metric_learning_on_images_ex project file after cmake command line, now the gpu is ok, and there are several dnn_xxx projects in the build folder, but there is no project file for dnn_metric_learning_on_images_ex.

**Comment by davisking** [comment]
I assume you are using Visual Studio.  I have cmake setup to skip building that example when compiled with visual studio because visual studio has a bug in it that causes visual studio to crash when it tries to compile it.  I should note, that the example cmake build file explains this, so if you had read it you would know :)

Anyway, visual studio is a terrible compiler.  You should try using another compiler that supports CUDA.

**Comment by anguoyang** [comment]
my laptop is Windows:) and cuda is not supported in virtual machine.
could i add this project into cmake file? i will try to solve the problem, if success, i will pr it

**Comment by anguoyang** [comment]
could you please share the cmake file which support that project, thank you

**Comment by davisking** [comment]
It's all in the examples folder.

**Comment by anguoyang** [comment]
hi @davisking , fortunately, there is no problem on my pc, haha:), yes, the memory consume more and more in a while(about 1.5g), but finally down to the normal usage after compiled successfully

**Comment by stereomatchingkiss** [comment]
>Anyway, visual studio is a terrible compiler. You should try using another
compiler that supports CUDA.

But Davis, it is the one and only compiler supported by CUDA as far as I
know :(.

2017-03-04 8:48 GMT+08:00 Davis E. King <notifications@github.com>:

**Comment by e-fominov** [comment]
Gcc works perfect on Linux with Cuda. MinGW+OpenBlas works fast on CPU, with some minor changes Visual Studio will comile this example with Cuda too - you will need to simplify the network declaration or the compiler will crash

But in general, Linux+Gcc+Cuda is the best way to train dlib's networks

**Comment by anguoyang** [comment]
I am also work on jetson(ubuntu)/cuda, but I have to say, the cuda development team are mostly windows developers:)

**Comment by davisking** [comment]
The problem here is that dlib now requires a C++11 conforming compiler.  Unfortunately, visual studio is still not a C++11 compiler.  You should complain to the visual studio team about their lack of support for the C++11 standard.

**Comment by anguoyang** [comment]
hi, @davisking , the training process is very slow, even for johns folder, which contains only a few images, is there any method to accelerate it? thank you

**Comment by davisking** [comment]
Use a good GPU, like a 1080 or titan x.
