### ISSUE TITLE
"test_one_vs_all_trainer" produces random output and does not always pass

### ISSUE THREAD

**Issue by avaucher** [davisking/dlib#458]
The title says it all. Executing 
```
./dtest --test_one_vs_all_trainer
```
will produce varying output and not always pass.

For instance, I get:
```
Error occurred at line 141.
Error occurred in file /home/eth/avaucher/devel/playground/temp_dlib/dlib/test/one_vs_all_trainer.cpp.
Failing expression was ans == res.
res: 
60  0  0 
18 52  0 
33  7 40 
```
```
Error occurred at line 141.
Error occurred in file /home/eth/avaucher/devel/playground/temp_dlib/dlib/test/one_vs_all_trainer.cpp.
Failing expression was ans == res.
res: 
30  0 30 
 0 57 13 
 0  0 80 
```
```
Error occurred at line 141.
Error occurred in file /home/eth/avaucher/devel/playground/temp_dlib/dlib/test/one_vs_all_trainer.cpp.
Failing expression was ans == res.
res: 
30  0 30 
 0 58 12 
 0  0 80 
```
```
Error occurred at line 141.
Error occurred in file /home/eth/avaucher/devel/playground/temp_dlib/dlib/test/one_vs_all_trainer.cpp.
Failing expression was ans == res.
res: 
30  8 22 
 0 64  6 
 0  0 80 
```
```
Error occurred at line 141.
Error occurred in file /home/eth/avaucher/devel/playground/temp_dlib/dlib/test/one_vs_all_trainer.cpp.
Failing expression was ans == res.
res: 
60  0  0 
34 36  0 
26 14 40 
```

**Comment by davisking** [comment]
Are you using BLAS?  If so, try turning it off and see if the problem goes
away.  I've found that some systems have bad BLAS libraries that produce
unreliable results.

**Comment by avaucher** [comment]
The problem didn't disappear after disabling BLAS, but close enough, afterwards I disabled LAPACK as well and then it worked.
It was on a Centos 7 machine with LAPACK 3.4.2 (-> released in 2012).

**Comment by davisking** [comment]
Yeah, that happens.  For some reason some versions of linux come with broken BLAS or LAPACK libraries.  I don't think there is anything I can do about this.  But I'm open to suggestions.  Like if there is some non-onerous way to detect broken versions of LAPACK in cmake somehow that doesn't involve running a really long test during cmake configure.  I think it's pretty hopeless though :(

**Comment by avaucher** [comment]
If it was something else than BLAS/LAPACK this would be easy to do by just checking the version with CMake. However because there are different implementation providers for BLAS/LAPACK I do not see an easy solution either...
