### ISSUE TITLE
Possible bug in templates

### ISSUE THREAD

**Issue by accensi** [davisking/dlib#460]
Hi David

Trying to mix dlib and OpenCV on the same project I got this error (or a naive C++ programmer :-)). Could you take a look?

// g++ -Wall -fno-strict-aliasing -fPIC  -fopenmp -fpermissive -Werror -DDEBUG  -pg -g3 
// -DSHMEM -DDLIB_PNG_SUPPORT -DDLIB_JPEG_SUPPORT -I. -I../../include/ -I/usr/local/include/ 
// -I./Frontal/dlib-master/   -c -o face_detect.o face_detect.cpp

#include <stdio.h>
#include <vector>

#include <dlib/opencv.h>
#include <dlib/matrix.h>
#include <dlib/geometry.h>
#include <dlib/pixel.h>
#include <dlib/image_processing.h>
#include <dlib/image_transforms.h>
#include <dlib/image_io.h>
#include <dlib/image_processing/frontal_face_detector.h>

#include "opencv2/opencv.hpp"
#include "opencv2/imgcodecs.hpp"

using namespace std;
using namespace dlib;
using namespace cv;

int main(int argc, char* argv[])
{

    // std::cout << "Model: " << argv[1] << "\nImg: " << argv[2] << std::endl;
    
    dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();
    
    cv::Mat img = cv::imread(argv[2], 1);
    std::cout << img.cols << "x" << img.rows << std::endl;

    dlib::cv_image<dlib::bgr_pixel> img_dlib( img );
    
    // trying to comment out the cv_image above and read the the file again, same errors
    // dlib::matrix<dlib::rgb_pixel> img_org;
    // dlib::load_image(img_org, argv[2]);
    // dlib::array2d<unsigned char> img_dlib_gray;
    // dlib::assign_image( img_dlib_gray, img_org);
     
    std::vector<dlib::rectangle> dets = detector(img);
    int dets_n = dets.size();

    printf("Detected faces: %d \n", dets_n);

    return 0;
}

/*
xxx@yyyy Teste ]$ g++ -Wall -fno-strict-aliasing -fPIC  -fopenmp -fpermissive -Werror -DDEBUG  -pg -g3 -DSHMEM -DDLIB_PNG_SUPPORT -DDLIB_JPEG_SUPPORT -I. -I../../include/ -I/usr/local/include/ -I./Frontal/dlib-master/   -c -o face_detect.o face_detect.cpp
In file included from ./Frontal/dlib-master/dlib/image_processing/remove_unobtainable_rectangles.h:10:0,
                 from ./Frontal/dlib-master/dlib/image_processing.h:20,
                 from face_detect.cpp:16:
./Frontal/dlib-master/dlib/image_processing/scan_fhog_pyramid.h: In instantiation of ‘void dlib::impl::create_fhog_pyramid(const image_type&, const feature_extractor_type&, dlib::array<dlib::array<dlib::array2d<float> > >&, int, int, int, long unsigned int, long unsigned int, long unsigned int) [with pyramid_type = dlib::pyramid_down<6u>; image_type = cv::Mat; feature_extractor_type = dlib::default_fhog_feature_extractor]’:
./Frontal/dlib-master/dlib/image_processing/scan_fhog_pyramid.h:633:48:   required from ‘void dlib::scan_fhog_pyramid<Pyramid_type, Feature_extractor_type>::load(const image_type&) [with image_type = cv::Mat; Pyramid_type = dlib::pyramid_down<6u>; Feature_extractor_type = dlib::default_fhog_feature_extractor]’
./Frontal/dlib-master/dlib/image_processing/object_detector.h:433:9:   required from ‘void dlib::object_detector<image_scanner_type_>::operator()(const image_type&, std::vector<dlib::rect_detection>&, double) [with image_type = cv::Mat; image_scanner_type_ = dlib::scan_fhog_pyramid<dlib::pyramid_down<6u> >]’
./Frontal/dlib-master/dlib/image_processing/object_detector.h:507:16:   required from ‘std::vector<dlib::rectangle> dlib::object_detector<image_scanner_type_>::operator()(const image_type&, double) [with image_type = cv::Mat; image_scanner_type_ = dlib::scan_fhog_pyramid<dlib::pyramid_down<6u> >]’
face_detect.cpp:45:53:   required from here
./Frontal/dlib-master/dlib/image_processing/scan_fhog_pyramid.h:601:71: error: invalid use of incomplete type ‘struct dlib::image_traits<cv::Mat>’
               typedef typename image_traits<image_type>::pixel_type pixel_type;
                                                                     ^~~~~~~~~~
In file included from ./Frontal/dlib-master/dlib/opencv/../matrix/../array2d/../geometry/rectangle.h:12:0,
                 from ./Frontal/dlib-master/dlib/opencv/../matrix/../array2d/array2d_kernel.h:10,
                 from ./Frontal/dlib-master/dlib/opencv/../matrix/../array2d.h:7,
                 from ./Frontal/dlib-master/dlib/opencv/../matrix/matrix_mat.h:10,
                 from ./Frontal/dlib-master/dlib/opencv/cv_image.h:11,
                 from ./Frontal/dlib-master/dlib/opencv.h:10,
                 from face_detect.cpp:12:
./Frontal/dlib-master/dlib/opencv/../matrix/../array2d/../geometry/../image_processing/generic_image.h:123:12: note: declaration of ‘struct dlib::image_traits<cv::Mat>’
     struct image_traits;
            ^~~~~~~~~~~~
...
Followed on with several other errors caused by  
*/

**Comment by davisking** [comment]
Don't pass an opencv Mat to a dlib function, which is what you are doing in the detector call.

**Comment by accensi** [comment]
or a naive C++ programmer :-)
Really!

Thanks
