### ISSUE TITLE
least_squares_ex.cpp.html compile errors

### ISSUE THREAD

**Issue by VVE** [davisking/dlib#461]
Hi, 
trying least_squares_ex.cpp.html I got compile (Visual Studio 2015) errors. They are in Russian. Is it better to translate them into English?
1>------ Сборка начата: проект: dlib, Конфигурация: Debug Win32 ------
1>  stdafx.cpp
1>  dlib.cpp
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(3): error C4430: отсутствует спецификатор типа - предполагается int. Примечание. C++ не поддерживает int по умолчанию
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(3): error C2143: синтаксическая ошибка: отсутствие "," перед "&"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(8): error C2065: input_vector: необъявленный идентификатор
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(8): error C2923: std::pair: "input_vector" не является допустимым аргументом типа шаблон для параметра "_Ty1"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(9): error C4430: отсутствует спецификатор типа - предполагается int. Примечание. C++ не поддерживает int по умолчанию
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(9): error C2143: синтаксическая ошибка: отсутствие "," перед "&"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(13): error C2065: input_vector: необъявленный идентификатор
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(13): error C2923: std::pair: "input_vector" не является допустимым аргументом типа шаблон для параметра "_Ty1"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(14): error C4430: отсутствует спецификатор типа - предполагается int. Примечание. C++ не поддерживает int по умолчанию
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(14): error C2143: синтаксическая ошибка: отсутствие "," перед "&"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.h(15): error C4430: отсутствует спецификатор типа - предполагается int. Примечание. C++ не поддерживает int по умолчанию
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(34): error C2660: model: функция не принимает 2 аргументов
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(34): error C2789: "output": требуется инициализация объекта типа класса, квалифицированного как const
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(34): note:  см. объявление "output"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(43): error C2664: "int residual_derivative(const std::pair &,const int)": невозможно преобразовать аргумент 1 из "std::pair<input_vector,double>" в "const std::pair &"
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(43): note: Причина: невозможно преобразовать "std::pair<input_vector,double>" в "const std::pair"
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(43): note: Для выполнения данного преобразования нет доступного оператора преобразования, определенного пользователем, или вызов оператора невозможен
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(44): error C2780: const dlib::central_differences<funct> dlib::derivative(const funct &,double): требует аргументов: 2, имеется: 1
1>  c:\program files\dlib-19.3\dlib\optimization\optimization.h(94): note:  см. объявление "dlib::derivative"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(44): error C2893: Сбой при специализации функции-шаблона "const dlib::central_differences<funct> dlib::derivative(const funct &)"
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(44): note: Со следующими аргументами шаблона:
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(44): note: "funct=double (const std::pair &,int)"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(75): error C2780: const dlib::central_differences<funct> dlib::derivative(const funct &,double): требует аргументов: 2, имеется: 1
1>  c:\program files\dlib-19.3\dlib\optimization\optimization.h(94): note:  см. объявление "dlib::derivative"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(75): error C2893: Сбой при специализации функции-шаблона "const dlib::central_differences<funct> dlib::derivative(const funct &)"
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(75): note: Со следующими аргументами шаблона:
1>  c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(75): note: "funct=double (const std::pair &,int)"
1>c:\users\vova\documents\visual studio 2015\projects\dlib\dlib\dlib.cpp(77): error C2780: double dlib::solve_least_squares_lm(stop_strategy_type,const funct_type &,const funct_der_type &,const vector_type &,T &,double): требует аргументов: 6, имеется: 4
1>  c:\program files\dlib-19.3\dlib\optimization\optimization_least_squares.h(310): note:  см. объявление "dlib::solve_least_squares_lm"

**Comment by e-fominov** [comment]
First versions of Visual Studio 2015 does not support C++11 standard. Try updating to VS update 3. Compiler version that is known to work is 19.00.24215.1

**Comment by VVE** [comment]
Many thanks!!! Please excuse me my mistake.Best regards 01.03.2017, 14:45, "Davis E. King" <notifications@github.com>:Closed #461.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
