### ISSUE TITLE
runtime error:  dlib::cuda_error while calling cudaMemcpy

### ISSUE THREAD

**Issue by jiangxuehan** [davisking/dlib#462]
When i ran the dnn_metric_learning_on_images_ex , an error arose when reloading saved state. I complied dlib with cuda7.5 and cudnnv5.1,below is the error info:
...
step#:  7837 learning rate:0.1  average loss:0.0132317 steps without apparent progress: 3054
Loss has been increasing , reloading saved state from face_metric_sync
terminate called after throwing  an instance of  'dlib::cuda_error'
 what():  Error while calling cudaMemcpy(dest.device_write_only(),src.device()+src_offset,num*sizeof(float),cudaMemcpyDeviceToDevice) in file dlib/dnn/gpu_data.cpp: 62. code 11,reason :invalid argument

**Comment by davisking** [comment]
Try reinstalling CUDA and cuDNN

**Comment by ZHAIXINGZHAIYUE** [comment]
cuda:8.0
cudnn:5.1
when i run the `dnn_mmod_face_detection_ex`

```
Error while calling cudaMalloc(&backward_data_workspace, backward_data_workspace_size_in_bytes) in file /home/zhaixingzi/Applications/dlib/dlib/dnn/cudnn_dlibapi.cpp:888. code: 2, reason: out of memory
```
what should i do to resolve thre problem?

**Comment by davisking** [comment]
Get more memory or load less data (e.g. make the image smaller).
