### ISSUE TITLE
Add Shake-Shake support

### ISSUE THREAD

**Issue by alireza7991** [davisking/dlib#464]
Shake-Shake Residual network has been introduced recently, it claims to achieve 2.72% error on CIFAR-10:

> This method aims at helping computer vision practitioners faced with an overfit problem. The idea is to replace, in a 3-branch ResNet, the standard summation of residual branches by a stochastic affine combination. The largest tested model improves on the best single shot published result on CIFAR-10 by reaching 2.72% test error.

![image](https://cloud.githubusercontent.com/assets/3162787/23487816/d0ac688a-fefd-11e6-89ed-84d5656dcd38.png)

It would be nice to see dlib supporting Shake-Shake since it would improve results greatly, also, it's not so difficult to implement. Shake Shake needs some simple modification in add_prev to use a stochastic affine combination instead of the current addition and some modification to use 2 residual branches instead of the only 1. 

There is an implementation in torch:
https://github.com/xgastaldi/shake-shake
Here is the reference paper:
https://openreview.net/forum?id=HkO-PCmYl&noteId=HkO-PCmYl

**Comment by davisking** [comment]
Looks cool.  You should write it up and submit it as a pull request :)

**Comment by alireza7991** [comment]
I've just implemented 2 branch residual, now I'm working on adding stochastic affine combination. I have the following error:

https://hastebin.com/yehihuvoqa.cpp

Here is my implementation of shake shake layer:

https://hastebin.com/asajomanit.cpp
