### ISSUE TITLE
face recognition with my face detector

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#466]
as for face recogntion:
--------------------------------------------------------------
 std::vector<matrix<rgb_pixel>> faces;
    for (auto face : detector(img))
    {
        auto shape = sp(img, face);
        matrix<rgb_pixel> face_chip;
        extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);
        faces.push_back(move(face_chip));
        // Also put some boxes on the faces so we can see that the detector is finding
        // them.
        win.add_overlay(face);
    }
.................................
std::vector<matrix<float,0,1>> face_descriptors = net(faces);
----------------------------------------------------
my question is, could I use my face detector and just send the cropped-faces images into the net for feature extraction?
like this:
std::vector<matrix<rgb_pixel>> faces = myDetector(img);
std::vector<matrix<float,0,1>> face_descriptors = net(faces);

thank you!

**Comment by davisking** [comment]
Yes, obviously it doesn't matter where the faces come from, so long as they are scaled and aligned the same way.

**Comment by anguoyang** [comment]
hi davis, is there any samples about how to set/get values with matrix<float,0,1>? thank you

**Comment by davisking** [comment]
http://bfy.tw/AWS0 ;)

**Comment by anguoyang** [comment]
thank you, I finished the face recognition demo finally:) with my own face detector and also alignment.
It is really accurate when I tested on several image pairs, except for this image pair: 
https://raw.githubusercontent.com/cmusatyalab/openface/master/images/examples/lennon-2.jpg
https://raw.githubusercontent.com/cmusatyalab/openface/master/images/examples/lennon-1.jpg

so I tried to use the default recognizer in dlib, it is worked perfectly, it is obviously that the problem is related with my detector/alignment.

I would like to use the landmark detector in dlib, it is excellent and accurate, however, it is really slow, so I have to use my own detector instead, but it is not accurate as the default one in dlib, I dont know how to do next:)

**Comment by anguoyang** [comment]
I am sure the problem is because my detector is different with the following code of default alignment:
--------------------------------------
for (auto face : detector(img))
    {
        auto shape = sp(img, face);
        matrix<rgb_pixel> face_chip;
        extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);
        faces.push_back(move(face_chip));
        // Also put some boxes on the faces so we can see that the detector is finding
        // them.
        win.add_overlay(face);
    }
--------------------------------------------

the key point is:
extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);

I have detected on img and get my own face_chip, could I re-apply with this?

        auto shape = sp(face, face); // in my case, there is no img anymore
        matrix<rgb_pixel> face_chip;
        extract_image_chip(face, get_face_chip_details(shape,150,0.25), face_chip);
        faces.push_back(move(face_chip));
        // Also put some boxes on the faces so we can see that the detector is finding
        // them.
        win.add_overlay(face);

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whyisdlibslow

**Comment by anguoyang** [comment]
Thank you @davisking , I have opened the sse4 and also build with release mode, without GPU(because I want to test dlib detector which did not use GPU). and my CPU is i5(macbook air). 
There are 2 faces in an image, the total processing time of dnn face recognition is about 6 seconds, however, the face feature extractor and comparison process is not slow, it took only 200ms in total for extraction and comparison, but the face detector is really slow, which occupy the rest of the seconds.

**Comment by anguoyang** [comment]
this code is time consuming:
--------------------------------------------
    for (auto face : detector(img))
    {
        auto shape = sp(img, face);
        matrix<rgb_pixel> face_chip;
        extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);
        faces.push_back(move(face_chip));
        // Also put some boxes on the faces so we can see that the detector is finding
        // them.
        win.add_overlay(face);
    }
--------------------------------------------

but this code is not slow which is unexpected happy:)
--------------------------------------------------------------
std::vector<matrix<float,0,1>> face_descriptors = net(faces);
..........................
            if (length(face_descriptors[i]-face_descriptors[j]) < 0.6)
                edges.push_back(sample_pair(i,j));
---------------------------------------------------------

**Comment by anguoyang** [comment]
hi @davisking , sorry for the confusion, the speed is slow because of jitter_image operation, it copy 100 images for transformation, I just wonder why we need this to improve accuracy? if I don't use this, then the accuracy is bad, however it become fast.
