### ISSUE TITLE
memory leaks (dnn/cuda)

### ISSUE THREAD

**Issue by ecionis** [davisking/dlib#468]
Hi,

I have done simple sample, but memory is fast leaking on testing many images (1M samples)
What i am doing wrong?

dlib 19.3
cuda 8.0
cudnn 5.0
vs 2015 14.0.25431.01 update 3
compiled with DLIB_USE_CUDA

Code:

`
#pragma comment(lib, "cudnn.lib")
#ifdef DLIB_USE_CUDA
#pragma comment(lib, "cublas.lib")
#pragma comment(lib, "curand.lib")
#endif

#include <dlib/dnn.h>
#include < iostream>
#include <dlib/data_io.h>

void zero(dlib::matrix< float> &m)
{
	for(int x = 0; x < m.nc(); x++)
	for(int y = 0; y < m.nr(); y++) m(y, x) = 0;
}

std::vector<dlib::matrix< float>> training_images;
std::vector< unsigned long>       training_labels;

int w = 6, h = 1;

void build_train()
{
	int cimg = 3;

	training_images.resize(cimg);
	training_labels.resize(cimg);

	training_labels[0] = 1;
	training_images[0].set_size(h, w);
	zero(training_images[0]);
	training_images[0](0, 0) = 1;

	training_labels[1] = 2;
	training_images[1].set_size(h, w);
	zero(training_images[1]);
	training_images[1](0, 0) = -1;

	training_labels[2] = 3;
	training_images[2].set_size(h, w);
	zero(training_images[2]);
	training_images[2](0, 1) = 2;
}

//////////////////////////////////////////////////////////////////////////
int main(int argc, char *argv[]) try
{
	std::vector<dlib::matrix< float>> testing_images;
	std::vector< unsigned long>       testing_labels;

	testing_images.resize(1);
	testing_labels.resize(1);

	testing_labels[0] = 2;
	testing_images[0].set_size(h, w);
	zero(testing_images[0]);
	testing_images[0](0, 0) = -1.;

	using net_type = dlib::loss_multiclass_log<
		dlib::fc<4,
		dlib::relu<dlib::fc<84,
		dlib::relu<dlib::fc<120,
		dlib::max_pool<1, 2, 2, 2, dlib::relu<dlib::con<16, 1, 5, 1, 1,
		dlib::max_pool<1, 2, 2, 2, dlib::relu<dlib::con<6, 1, 5, 1, 1,
		dlib::input<dlib::matrix< float>>>>>>>>>>>>>>;

	net_type net;
	dlib::dnn_trainer<net_type> trainer(net);
	trainer.set_learning_rate(0.01);
	trainer.set_min_learning_rate(0.00001);
	trainer.set_mini_batch_size(128);

	auto start = std::chrono::system_clock::now();

		build_train();
		trainer.train(training_images, training_labels);

    std::chrono::duration<double> diff = std::chrono::system_clock::now() - start;
	std::cout << "Time " << diff.count() << " s\n";

	int crc32 = 0;
	for(unsigned int i = 0; i < 1000000; i++) //<-- here leak and leak
	{
		std::vector<unsigned long> predicted_labels = net(testing_images);
		crc32 += predicted_labels[0];
	}

	std::cout << crc32 << std::endl;
	return 0;
}
catch (std::exception& e)
{
	std::cout << e.what() << std::endl;
}
`

**Comment by davisking** [comment]
Why do you think there is a memory leak?

**Comment by ecionis** [comment]
I see in the task manager. Memory grow from 400mb to 1,2Gb. My working project growed to 6Gb (when i terminated it). It is abnormal. (but GPU memory does not grow)

**Comment by davisking** [comment]
Oh yeah, wow, that's a slow memory leak.  I've run this for weeks and not encountered it.  Anyway, I just pushed the fix to github.  

Thanks for finding this :)
