### ISSUE TITLE
split threshold for shape_predictor

### ISSUE THREAD

**Issue by inspirit** [davisking/dlib#47]
Hello,

i was wondering what is the reason to limit threshold to [-64;64] here:
https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor.h#L866
the possible range is [-255;255] if i understand it correctly.

**Comment by davisking** [comment]
Because a threshold of 255 or -255 literally does nothing, all the points
go to the same side of the split.  The more extreme thresholds are
similarly nearly useless.

**Comment by inspirit** [comment]
thats true, still isn't 64 too small? or do u think 127 is also too extreme?

**Comment by davisking** [comment]
The threshold isn't very important.  You could all thresholds to 0 and the
algorithm would still function.  -64 to 64 is empirically a good balance.
