### ISSUE TITLE
"Small" speed down in dnn with some parameters

### ISSUE THREAD

**Issue by ecionis** [davisking/dlib#471]
Hi,

I train dnn (cuda) and i have noticed, if 
(training_images.size() % mini_batch_size) != 0 speed down 2,6 times

ex. 
for mini_batch_size=3000, speed down 2,6 times
for mini_batch_size=1024, speed down 2,5 times
for mini_batch_size=128, speed down 1,15 times
for mini_batch_size=64, speed down 1,07 times

I think, some reallocation memory prevent normal train.

ex. training_images.size()=6001, mini_batch_size=3000

for(epoch..0-10000)
{
 trainer.train_one_step(3000)
 trainer.train_one_step(3000)
 trainer.train_one_step(1) <-- reallocation here
}

Is it bug or feature?

**Comment by davisking** [comment]
I'm not sure what else you expect to happen.  You give differently sized mini-batches it has to reallocate.
