### ISSUE TITLE
About find_candidate_object_locations

### ISSUE THREAD

**Issue by user1103** [davisking/dlib#472]
Hi, I don't know if this is the right place for this question, but I was wondering how find_candidate_object_locations actually finds the candidates. I was reading the description of what this function ensures, but I couldn't quite understand it. The description had referenced a paper "Segmentation as Selective Search for Object Recognition by Koen E. A. van de Sande, et al.", but said the implementation deviated from the paper slightly and to refer to the code, which unfortunately I don't understand either.

So my question is, how exactly is this function finding the candidates or bounding boxes of a given image?

**Comment by davisking** [comment]
This forum isn't really the appropriate place to ask for computer vision/algorithm help.
