### ISSUE TITLE
Issue with python 3.6 on Linux

### ISSUE THREAD

**Issue by d4nst** [davisking/dlib#473]
I have been using dlib with python 2.7 without any problems. Recently, I made the switch to python 3.6 but unfortunately I haven't been able to install dlib. 

This is what I have tried and the errors I get when I try to import the library:

**1) Installing boost and dlib from source (the problem here comes from boost):**

```
In [1]: import dlib
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-82a137582d6f> in <module>()
----> 1 import dlib

/home/daniel/Dev/anaconda2/envs/py3/lib/python3.6/site-packages/dlib-19.4.99-py3.6-linux-x86_64.egg/dlib/__init__.py in <module>()
----> 1 from .dlib import *
      2 __version__ = "19.4.99"

ImportError: /usr/local/lib/libboost_python3.so.1.63.0: undefined symbol: PyClass_Type
```

**2) Installing boost from conda and dlib from source:**

```
In [1]: import dlib
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-82a137582d6f> in <module>()
----> 1 import dlib

/home/daniel/Dev/anaconda2/envs/py3/lib/python3.6/site-packages/dlib-19.4.99-py3.6-linux-x86_64.egg/dlib/__init__.py in <module>()
----> 1 from .dlib import *
      2 __version__ = "19.4.99"

ImportError: /home/daniel/Dev/anaconda2/envs/py3/lib/python3.6/site-packages/dlib-19.4.99-py3.6-linux-x86_64.egg/dlib/dlib.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```

**3) Installing boost from apt-get and dlib from pip (same error as before - dlib from pip links to libboost_python-py34, so in this case it makes sense that it doesn't work with python 3.6):**

```
In [1]: import dlib
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-82a137582d6f> in <module>()
----> 1 import dlib

/home/daniel/Dev/anaconda2/envs/py3/lib/python3.6/site-packages/dlib/__init__.py in <module>()
----> 1 from .dlib import *
      2 __version__ = "19.3.1"

ImportError: /home/daniel/Dev/anaconda2/envs/py3/lib/python3.6/site-packages/dlib/dlib.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```

**Comment by davisking** [comment]
You have to compile boost.python against the specific python you want to use.  It sounds like you have multiple copies of python installed.  You should look up the boost.python build instructions to find out how to tell it what python (i.e. what folder on your computer that contains the python you want) you want it to build against.  

To say that another way.  If you have multiple copies of python installed you can't just build/install boost.python and hope for the best.  However you install/build it, you need to tell it what pyhton you want it to use or it's going to pick one randomly and you will have a bad time.

**Comment by d4nst** [comment]
I only have python 2.7 and 3.6 installed and I used the following command to configure boost installation:

` ./bootstrap.sh --with-python=/home/daniel/Dev/anaconda2/envs/py3/bin/python --with-libraries=python --with-python-root=/home/daniel/Dev/anaconda2/envs/py3/ --with-python-version=3.6`

Besides, the compiled library is `libboost_python3.so.1.63.0`, which seems to indicate that python 3 was indeed used.

In any case, that doesn't explain why option 2 doesn't work since the version installed with conda is `boost: 1.61.0-py36_0`.

**Comment by davisking** [comment]
It has to be compiled against the exact python you are using.  There aren't just 2 versions of python.  There  are a huge number.  Odds are pretty good you have more than 2 versions of python installed.  Or maybe you have multiple versions of the python development libraries, what boost.python uses, installed.  Maybe some via apt-get, some via conda, giving you well over 2 copies that are all slightly incompatible with each other.

**Comment by d4nst** [comment]
I was finally able to make it work by downgrading to python 3.5 and installing dlib from this repo: https://anaconda.org/menpo/dlib

**Comment by davisking** [comment]
Cool. There shouldn't be anything special about that copy of dlib though.  It didn't work with the copy from https://github.com/davisking/dlib?

**Comment by d4nst** [comment]
No, it didn't work. I got the same error as in option 2 and 3 from my first post.

**Comment by davisking** [comment]
Does menpo install a compiled dlib binary?

**Comment by d4nst** [comment]
Yeah it does. Also the dlib version is 18.18 and not the latest one, I'm not sure if that might be related.

**Comment by davisking** [comment]
No, it's just that it's already compiled with compatible versions of python/boost.python :)
