### ISSUE TITLE
where is the 'object_detector.dat' in 'frontal_face_detector.h' from?

### ISSUE THREAD

**Issue by pencoa** [davisking/dlib#474]
These codes is in the 'image_processing/frontal_face_detector.h'. As mentioned in the comment, the frontal face detector is from base64 encoded 'object_detector.dat'.
```
    inline const std::string get_serialized_frontal_faces()
    {
        dlib::base64 base64_coder;
        dlib::compress_stream::kernel_1ea compressor;
        std::ostringstream sout;
        std::istringstream sin;

        // The base64 encoded data from the file 'object_detector.dat' we want to decode and return.
        sout << "AW2B5ZIvv09mlKLVYjKqbJC05yeR2KsCpPGEGOgn2QlwM92S4UT4HgQkV0V9WqYRf6xETTSVKz7Z";
        sout << "YcJ84Jc4C3+VdPgZDhV+LDt6qAt3OI4nA9zN4Y9cCIb6ivlETkN/JMmapbOAUW2mrSzDif5zjAaq";
        sout << "+NFvw/5V0Jciopw9tR6nYtV41unWGvyyfsO9CcqvDy81QIydToHh0a7UaL0jCtA2DYzkViDufxyv";
```
Where is the 'object_detector.dat' from?
```
    /*
        It is built out of 5 HOG filters. A front looking, left looking, right looking, 
        front looking but rotated left, and finally a front looking but rotated right one.
```
According to the comments above, it is produced with HOG method, the same method as 'train_object_detector.py'. But the output of 'train_object_detector.py' is 'detector.svm'. They have different suffix.
Where is the 'object_detector.dat' in 'frontal_face_detector.h' from?

**Comment by e-fominov** [comment]
> It is built out of 5 HOG filters. A front looking, left looking, right looking, front looking but rotated left, and finally a front looking but rotated right one.

each one separate HOG filter is "detector.svm" file. so this object_detector.dat contains 5 ".svm" detectors inside

you can look [here](http://dlib.net/dlib/image_processing/object_detector_abstract.h.html#object_detector) for documentation. if you want to construct detector from multiple files, you should use this constructor from C++ code:
```C++
        explicit object_detector (
            const std::vector<object_detector>& detectors
        );
```
after that result detector can be serialized into "object_detector.dat" file and loaded/used later (even from python)

anyways, this is not a bug and should be closed. [read the faq](http://dlib.net/faq.html)

**Comment by pencoa** [comment]
Thank you.
