### ISSUE TITLE
Update boost dependency

### ISSUE THREAD

**Issue by baloodevil** [davisking/dlib#475]
I'm trying to install on Windows.  I have Python 3.6 Anaconda.  Trying to install with `conda install -c menpo dlib` gives...
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - dlib -> boost 1.56.0 -> python 3.5*
  - python 3.6*
```
Looks like the boost 1.61.0 supports python 3.6.  Could dlib be updated to use a more recent version of boost?

**Comment by davisking** [comment]
Dlib works fine with new versions of boost.  This is a conda problem.  If you download dlib from dlib.net or github it should be fine.

**Comment by baloodevil** [comment]
Thanks for the note and quick response.
