### ISSUE TITLE
The frontal_face_detector takes extremely long time to handle a picture. 

### ISSUE THREAD

**Issue by nesadiankemo** [davisking/dlib#477]
Hi, I use the example code ( face_detection_ex.cpp ) to detect face in a 640*480 picture. but it takes almost 23+ seconds every time.  am I compile it in a wrong way?  My computer basic info :  win7-64bit, Intel i5-6500, 8GB RAM.

**Comment by e-fominov** [comment]
Compiler params affect the performance much. Read the [FAQ](http://dlib.net/faq.html#Whyisdlibslow) first

This is not a bug, should be closed

**Comment by nesadiankemo** [comment]
Thanks.
