### ISSUE TITLE
dnn face recognition performance

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [davisking/dlib#480]
respected author:
did you train your dnn face recognition model only with western face data?
I collect a very small dataset, ,include: 42 pair (21 pair are same person 21 pair are different).ALL are chinese people.
After calculate the euclidean distance, if i use the threshold 0.6 to make a decesion,almost all the pair will be think as the same person. If you are instreated with this, i would share you with the small dataset.

here are these distance:
`
**same**
1. 0.3084938465354163
2.  0.460631237629359
3.  0.2965240761436536
4.  0.5132927183004672
5.  0.2608081542756828
6.  0.4620464327832487
7.  0.3309806464696864
8.  0.555607487840727
9.  0.277878314413183
10.  0.4493739800536354
11.  0.2188173402260331
12.  0.4728988738834609
13.  0.3082224127779247
14.  0.5863535817761367
15.  0.4057091891451969
16.  0.6974094415571297
17.  0.2675724149796544
18.  0.6362704172815054
19.  0.3597395076700426
20.  0.4771334144279341
21.  0.2887894908285575
**different**
22.  0.4723264933704739
23.  0.3103683206929148
24.  0.5726200776226548
25.  0.328977753973606
26.  0.6205834061615754
27.  0.4001112913453917
28.  0.561800312226643
29.  0.323379256459661
30.  0.7183244094259837
31.  0.4291364055219034
32.  0.4690874961527581
33.  0.3161479148788168
34.  0.5321610123449068
35.  0.2909887711518453
36.  0.4654103436074761
37.  0.2191511381099579
38.  0.5411735871265148
39.  0.2609189096612428
40.  0.6852108551024549
41.  0.2635223483000905
42.  0.394368450878619

`

**Comment by davisking** [comment]
There is definitely a bias in the training data towards western white people.  But it did include a lot of non-white people.  Are you sure you are running the code exactly as the example program shows?

**Comment by ZHAIXINGZHAIYUE** [comment]
yes,i am sure.Not only i use the C++ API ,but also  the python API. URL: https://pan.baidu.com/s/1pLc1pI7 PASSWD: 9fij

**Comment by davisking** [comment]
I have no idea how to download that file.  I tried but I'm getting a bunch of popups in chinese (which I don't speak).  :(

**Comment by ZHAIXINGZHAIYUE** [comment]
ok ,i sen an email to davis@dlib.net. do you have recieved it?

**Comment by davisking** [comment]
Yeah, I just looked at it.  I don't see anything funny about the images.  It's probably just that the model isn't super great on those people.  

The most popular training datasets are all very USA centric.  I did a lot of my own scraping to try and add non-white people into the training data because I knew this would be a problem.  But still.  I'm just one guy and it's hard to create that large of an additional dataset.  So this is probably one of the limits of the model :(

**Comment by ZHAIXINGZHAIYUE** [comment]
you are the best. I would try my best to improve this model.

**Comment by madhavajay** [comment]
@ZHAIXINGZHAIYUE Did you have any luck improving the performance on Asian faces, I am having this issue too!

**Comment by utkarshrai2** [comment]
@madhavajay and @ZHAIXINGZHAIYUE  iam also facing the similar issue. Any insight to share?
