### ISSUE TITLE
Question: background options for `transform_image`

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib#482]
I was wondering if there is a way to provide continuity to the areas outside the image by replicating the old borders of the image, in a similar way as GL_CLAMP functions work in OpenGL, or as BORDER_REPLICATE in OpenCV.
I haven't seen how can the `set_background` argument in `transform_image` can help me do this.

Here is an example to illustrate what I want to do with dlib:
I take the original picture, on the left, and perform an affine transform that aligns it, and crops it with a border. The result, on the right, is an image with the face centred.

![screenshot from 2017-03-15 18-27-16](https://cloud.githubusercontent.com/assets/1671644/23962033/1d2dba2e-09ad-11e7-8159-126542ec0c9a.png)

Thank you again for your work on dlib, it is a pleasure to work with it!

**Comment by davisking** [comment]
Unfortunately, there isn't a function that does this in dlib.
