### ISSUE TITLE
import dlib: importerror libcudnn.so.5 cannot open shared object file

### ISSUE THREAD

**Issue by z3ppj1g5aw** [davisking/dlib#484]
Hi,
I'm using ubuntu 16.04, anaconda with python 2.7, cuda 8.0 and cudnn 5.1 installed (in usr/local/cuda)

I was able to compile the python api without any errors. But when I try to import dlib, I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z3pp/miniconda2/lib/python2.7/site-packages/dlib-19.4.99-py2.7-linux-x86-64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: libcudnn.so.5: cannot open shared object file: No such file or director

The libcudnn.so.5 is present in /usr/local/cuda/lib64 and my LD_LIBRARY_PATH has /usr/local/cuda in it.

What am I missing here?
Ta

**Comment by davisking** [comment]
Put `/usr/local/cuda/lib64` in your path, since that's where the library is.

**Comment by z3ppj1g5aw** [comment]
Sorry that didn't work either. But it worked fine now when I compiled the files directly using cmake without using setup.py
