### ISSUE TITLE
Can't get dlib to work, with the frontal face detector.

### ISSUE THREAD

**Issue by mcourteaux** [davisking/dlib#490]
I've been searching for a couple of hours now.

I'm using pretty much identical code to the example `face_detection_ex.cpp`, with the only difference that I'm constructing the `dlib::array2d<dlib::rgb_pixel>` myself, instead of reading it from a file using `dlib::image_load`. The example program compiles fine and works, but in the application I'm trying to embed this, it isn't working: it returns an empty vector of rectangles.

Note: I stripped the triangle_up call (from both my code and the example code) as my input images are large enough.

Now, what really blows my mind is: I'm outputting the image2d I'm constructing myself, to a file as a verification. The file looks perfectly fine, but still dlib doesn't find any faces. However, when running the example program to this very same file, it perfectly detects the faces.

I am using in my CMakeLists.txt (note: the .git folder for dlib is at: `ext/dlib/.git`)

```
ADD_SUBDIRECTORY("ext/dlib/dlib")
INCLUDE_DIRECTORIES("ext/dlib/")

TARGET_LINK_LIBRARIES(SilverNode
    // ...
    dlib::dlib)
```

All this compiles fine, links fine, and runs fine, except it doesn't detect faces. The only difference I am aware of is that I'm using `ADD_SUBDIRECTORY` instead of `INCLUDE` as proposed by the example cmake file. When I use `INCLUDE` this gives some build error because my project uses C++14, and dlib sets the compiler settings to C++11 globally (and thus also for my project, which causes the error).

**Comment by mcourteaux** [comment]
Update: I tweaked the dlib helper cmake to enable c++14 instead of c++11, and recompiled my project using an `include` instruction instead of `add_subdirectory`: successful compilation as well, but still 0 faces detected.

**Comment by davisking** [comment]
I doubt it has anything to do with compiler settings.  You probably just have some silly mistake in your code, like you aren't really giving it the image or something :)

**Comment by mcourteaux** [comment]
I'm really out of inspiration. I'm confident my code is right. (I am pretty experienced with C++: more than 5 years of experience). Here is roughly the code that I'm using. My exact algo is omitted. But I can verify that the result is fine. The resulting ppm file looks perfect (and feeding it - after converting to jpeg - into the example program `face_detection_ex`, it detects faces fine). Again: I know I omitted the `pyramid_up` call, but this is not needed in the example program either.

    dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();

    dlib::array2d<dlib::rgb_pixel> img;
    img.clear();
    img.set_size(dimensions[0], dimensions[1]);

    // My algo for constructing the img here...
    img.reset();
    while (img.move_next()) {
        dlib::rgb_pixel &pixel = img.element();
        // set pixel.{red,green,blue} components here
    }

    /* Write a test ppm file for debugging and verifying. */
    FILE *testfile = fopen("test.ppm", "wb");
    fprintf(testfile, "P6\n%d %d\n255\n", dimensions[0], dimensions[1]);
    img.reset();
    while (img.move_next()) {
        dlib::rgb_pixel &pixel = img.element();
        (void)fwrite(&pixel.red, 1, 3, testfile);
    }
    fflush(testfile);
    fclose(testfile);

    std::vector<dlib::rectangle> dets = detector(img);
    printf("Number of faces detected: %zu\n", dets.size());

**Comment by mcourteaux** [comment]
Nevermind!

**Comment by mcourteaux** [comment]
For reference, you were right. It was a silly mistake. I swapped width and height in the `array2d::set_size()` call.
