### ISSUE TITLE
problem installing imglab

### ISSUE THREAD

**Issue by nanijnv1** [davisking/dlib#491]
i don't whats going wrong this is the error
logger_kernel_1.cpp:(.text._ZN4dlib12map_kernel_cINS_12map_kernel_1INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_10scoped_ptrINS_6logger11global_data15level_containerENS_15default_deleterISB_EEEENS_27binary_search_tree_kernel_2IS7_SE_NS_33memory_manager_stateless_kernel_1IcEESt4lessIS7_EEESH_EEE10remove_anyERS7_RSE_[_ZN4dlib12map_kernel_cINS_12map_kernel_1INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_10scoped_ptrINS_6logger11global_data15level_containerENS_15default_deleterISB_EEEENS_27binary_search_tree_kernel_2IS7_SE_NS_33memory_manager_stateless_kernel_1IcEESt4lessIS7_EEESH_EEE10remove_anyERS7_RSE_]+0x2f2): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
collect2: error: ld returned 1 exit status
CMakeFiles/imglab.dir/build.make:260: recipe for target 'imglab' failed
make[2]: *** [imglab] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/imglab.dir/all' failed
make[1]: *** [CMakeFiles/imglab.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davisking** [comment]
`std::__cxx11::basic_ostringstream` is part of the standard C++ library.  If you are getting this error the problem has nothing to do with dlib but instead is because your compiler is broken.  Maybe it's installed wrong somehow, I don't know. Try reinstalling the compiler.
