### ISSUE TITLE
unit test failed "test_matrix_lu" on macOS Sierra

### ISSUE THREAD

**Issue by simonchen77** [davisking/dlib#493]
Hi you all,

I git cloned and built the project from the master branch (commit f080bdeccac24095ae83507fe555eca79ffa508a)  (#487) on the macOS Sierra. All of the unit tests in "./dtest --runall" passed except for "test_matrix_lu". The below is the error message:

>  xxxchen $ ./dtest -d --test_matrix_lu
> Running test_matrix_lu / 
> 
> ### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEST FAILED: test_matrix_lu !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Failure message from test: 
> 
> Error occurred at line 89.
> Error occurred in file /Users/siyuanchen/Tools/dlib/dlib/test/matrix_lu.cpp.
> Failing expression was (temp= max(abs(test.get_l()*test.get_u() - rowm(m,test.get_pivot())))) < eps.
> 103.755
> 
> 
> 
> Testing Finished
> Total number of individual testing statements executed: 251
> Number of failed tests: 1
> Number of passed tests: 0

I am wondering if anybody in this community could give me a hint on how to avoid this error.

Thank you so much,
-Simon

**Comment by davisking** [comment]
Disable blas and lapack in the cmake settings and try it again.  It's sadly
common that people have broken blas or lapack libraries installed and the
unit tests catch that.

**Comment by simonchen77** [comment]
Hi Davis,

Thank you for your reply. I am not very familiar with cmake. A bit difficult to find the switches of blas and lapack. Please advise me where to spot them. The following is the message when I did "cmake .." under dlib/test/build. 

> bash-3.2$ cmake ..
> 
> -- Building a C++11 test project to see if your compiler supports C++11
> 
> -- C++11 activated.
> 
> -- Searching for BLAS and LAPACK
> 
> -- Checking for module 'cblas'
> 
> --   No package 'cblas' found
> 
> -- Checking for module 'lapack'
> 
> --   No package 'lapack' found
> 
> -- Found OpenBLAS library
> 
> -- Found LAPACK library
> 
> -- Configuring done
> 
> -- Generating done
> 

Thank you so much,
- Simon

**Comment by davisking** [comment]
Use ccmake

**Comment by simonchen77** [comment]
Hi Davis,

It worked! Thank you!

- Simon
