### ISSUE TITLE
Undefined type 'dlib::pixel_traits<pixel_type>' in cv_image class

### ISSUE THREAD

**Issue by musiko** [davisking/dlib#495]
I am not sure if this issue is platform-related or due to the poor C++11 support by MSVC (Windows 7 + VS2015, Dlib version 19.4)
Would you please advise the possible root cause? Thank you in advance.

```C++
#include <dlib/image_processing.h>
#include <dlib/image_transforms.h>
#include <dlib/opencv.h>

using namespace dlib;

cv::Mat getFaceChipImage(cv::Mat src_img, unsigned long size, double padding) const {
	cv_image<array2d<rgb_pixel>> dlib_cvimg(src_img);     // <<<< Apparent
	cv_image<array2d<rgb_pixel>> face_chip;
	extract_image_chip(dlib_cvimg, get_face_chip_details(shape, size, padding), face_chip);
	cv::Mat mat = toMat(face_chip);
	return mat;
}
```

Compilation of above function encountered the following errors in `dlib\include\dlib\opencv\cv_image.h`:
```C++
line 28:
- Error C2027:	use of undefined type 'dlib::pixel_traits<pixel_type>'	
- Error C2146:	syntax error: missing '>' before identifier 'basic_pixel_type' 
- Error C2065:	'num': undeclared identifier 
```

```C++
line 36:
- Error C2027:	use of undefined type 'dlib::pixel_traits<pixel_type>'
- Error C2146:	syntax error: missing '>' before identifier 'basic_pixel_type'
- Error C2065:	'num': undeclared identifier
```

**Comment by davisking** [comment]
Yeah that looks like an error in MSVC.  Try it in gcc, I'm pretty sure it will work.  

Also make sure you have all the updates for MSVC 2015 since there are many: http://dlib.net/faq.html#HowcanIusedlibinVisualStudio.  Although maybe you have discovered yet another bug in MSVC related to C++11 support.
