### ISSUE TITLE
Set GPU to use

### ISSUE THREAD

**Issue by buvaev** [davisking/dlib#496]
Is there a way to set which gpu to use? 
Right now it uses gpu(0) by default.

**Comment by davisking** [comment]
You can use all the normal cuda commands, like cudaSetDevice().

**Comment by ncuxiaogang** [comment]
how can I you python to set which GPU to use? Thanks.

**Comment by davisking** [comment]
Try using the CUDA_​VISIBLE_​DEVICES environment variable.  Google it for documentation.
