### ISSUE TITLE
msvc 2017 cpu build stucks at compile time on dnn_face_recognition_ex.cpp

### ISSUE THREAD

**Issue by nazmulkibria** [davisking/dlib#497]
I was trying to build dlib 19.04 on msvc 2017 in cpu mode (no cuda, no gpu). I found it stucks on compile time while building **dnn_face_recognition_ex** example. It happens due to nested template network of deep learning. Problem happens due to this line:

```
using anet_type = loss_metric<fc_no_bias<128,avg_pool_everything<
                            alevel0<
                            alevel1<
                            alevel2<
                            alevel3<
                            alevel4<
                            max_pool<3,3,2,2,relu<affine<con<32,7,7,2,2,
                            input_rgb_image_sized<150>
                            >>>>>>>>>>>>;
```

Can you please fix this issue, I was able to build the same on linux without having any issue.

IMPORTANT info is this I can build **dnn_mmod_face_detection_ex** which have a comparatively little network.

**Comment by davisking** [comment]
MSVC 2017 is buggy.  MSVC 2015 is slightly less buggy.   But at the end of the day you need a C++11 compiler to use new versions of dlib. 

If you want someone to fix this then complain to the MSVC dev team (i.e. report the bug to them).

**Comment by nazmulkibria** [comment]
@davisking is there any way to build it for cpu in windows?

**Comment by davisking** [comment]
Like I said, use another compiler.  MSVC 2015 should work.  Or gcc or whatever.
