### ISSUE TITLE
Is there examples to illustrate hash?

### ISSUE THREAD

**Issue by willard-yuan** [davisking/dlib#5]
Hi, davisking
I'm really appreciate the lib **dlib** you develop. I have used it to detect object task. Recently, I want to the lib to build a fast index. Luckily, I find the lib contains hash module. However, there is not a example to illustrate how to use these functions such as **LSH**. Can you write a example to compact data to binary code, then compute the hamming distance between them?

Yours,

Yong Yuan

**Comment by davisking** [comment]
If you have 2 vectors A and B, declared as a matrix<double> for example, then you can just do this:
hash_similar_angles_256 h;
auto hash1 = h(A);
auto hash2 = h(B);
cout << "hamming distance: " << h.distance(hash1,hash2) << endl;

**Comment by willard-yuan** [comment]
Thanks for your great help.
