### ISSUE TITLE
HOG detector

### ISSUE THREAD

**Issue by tzutalin** [davisking/dlib#50]
Hi Davisking,
   Excuse me, do yo have a model which can detect person using HOG detector? 

I would like to do a demo for my dlib-android application. 

Currently, I use opencv HOG person detector instead of dlib.

Could you share the model if you have?

https://github.com/tzutalin/dlib-android-app

**Comment by davisking** [comment]
I don't have such a model, but it's easy to train one using the HOG training tool in dlib. See http://dlib.net/fhog_object_detector_ex.cpp.html

**Comment by tzutalin** [comment]
Hi @davisking ,
Use INRIA person dataset to train person. SVM result is as bellows for the people who needs
https://github.com/tzutalin/dlib-android/tree/master/data
