### ISSUE TITLE
Issue with compute_lda_transform

### ISSUE THREAD

**Issue by travek** [davisking/dlib#501]
Hi!

I'm using dlib v 19.2.
I took one example from previous issue re the use of compute_lda_transform. The code is presented below. I find the results returning from the function strange:
1) Mean is equal zero, but should not
2) results differs significantly from theones get from R

Could you check and write what is wrong.
How I need to use compute_lda_transform if Ineed to get coordinates of x in a new transformed vector space?

Code example:
#include <dlib/matrix.h>
#include <dlib/rand.h>
#include <dlib/statistics.h>

using namespace dlib;
using namespace std;

int main()
{

	typedef matrix<double, 2, 1> Sample;

	std::vector<unsigned long> labels;
	std::vector<Sample> samples;
	Sample vector_;

	for (int i = 0; i<4; i++) {
		Sample s;
		s(0) = i;
		s(1) = i + 1;
		samples.push_back(s);
		labels.push_back(1);

		Sample s1;
		s1(0) = i + 1;
		s1(1) = i;
		samples.push_back(s1);
		labels.push_back(2);
	}

	matrix<double> X;
	X.set_size(8, 2);
	for (int i = 0; i<8; i++) {
		X(i, 0) = samples[i](0);
		X(i, 1) = samples[i](1);
	}

	matrix<double, 0, 1> mean;

	dlib::compute_lda_transform(X, mean, labels,1);

	cout << "Samples: \n";
	for (int i = 0; i < samples.size(); ++i)
		cout << samples[i](0) << "; "<<samples[i](1) << endl;
	cout << "\n";
	cout << mean << "\n";
	cout << X << "\n";
	for (int i = 0; i<samples.size(); i++) 
	{
		cout << X*samples[i] - mean << "\n";
	}

	cin.get();
	return 0;
	
}

**Comment by davisking** [comment]
Read the documentation.  The function doesn't output a mean.  The exact behavior of the function is described in great detail in the documentation.

**Comment by travek** [comment]
Devis,
I see in the documentation that Mean should be returned. Please find the quote below from the docs on compute_lda_transform:
"- We overwrite the input matrix X and store Z in it.  Therefore, the outputs of this function are in X and M."

So it should be, but not returned.

**Comment by davisking** [comment]
I don't see the word mean in the quoted documentation.
