### ISSUE TITLE
Q: How can I easily get to a layer at at a certain layer number in a DNN?

### ISSUE THREAD

**Issue by OranjeeGeneral** [davisking/dlib#502]
First off I know there is

layer<IntLiteral><net_type> but that works only for constant integer literals at compile time not values that might be stored in a numeric-type variable. 

Having a loop and then using subnet() on add_layer and add_loss class doesn't really work either since it is all templated I can't easily store an intermediate result in a variable to loop through or am I missing something?

Any other ideas?

**Comment by OranjeeGeneral** [comment]
Oh silly me I forgot I can use C++-11 auto of course :)

**Comment by OranjeeGeneral** [comment]
Actually that is not going to work either!

**Comment by davisking** [comment]
You have to use some compile time looping/recursion.  Look at the visit layer functions if you need an example of how to do that sort of thing.

**Comment by OranjeeGeneral** [comment]
Thanks for the hint. Kind of was a bit afraid of that answer :). Will wade my way through the templates
