### ISSUE TITLE
Multi GPU Result

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#503]
Hi,
I got a question regarding running the network on multple gpus.
Training on multiple gpus is fine and wokrs perfect
example:
dnn_trainer<net_type,adam> trainer(net,adam(0.0005, 0.9, 0.999), {0,1,2,3});

However in the example programms the result images are validated by something like:
 matrix<float,1,1000> p = sum_rows(mat(snet(images.begin(), images.end())))/num_crops;

Is there a option to run the snet(images.begin(), images.end()) on multiple gpus ?

My problem is that i made a image classifier which should run on many images at the end to classify them.
Is there also a approach to run that on multiple gpu?(maybe with a data queue like in the imagenet train example)

Thanks and best regards

**Comment by davisking** [comment]
The net object runs on just one GPU.  But nothing is stopping you from making multiple net objects, each with a different cuda device selected and running them all in parallel.

**Comment by VisionEp1** [comment]
Thanks, makes sence. 
How can i select the cude device?

**Comment by davisking** [comment]
Call cudaSetDevice()

**Comment by VisionEp1** [comment]
thanks!

**Comment by davisking** [comment]
No problem.
