### ISSUE TITLE
Cleanup functionality needed for win-platform for singletons (socket, global_clock)

### ISSUE THREAD

**Issue by sigbjorn** [davisking/dlib#505]
**Hi!**

First of all,
  while writing something at dlib site, **thanks so much** for this high quality library !

  We are using dlib as part of the shyft open-source project, at https://github.com/statkraft/shyft.
  It has excellent quality, header-only, well documented, multiplatform, and very well maintained.

We encountered something that we think is win-platform specific issue that we tracked to 
the function

dlib::get_global_clock().

That function maintains the singleton for timer_global_clock(), and works as expected for all practical purposes. We use dlib socket/streams and server, and it most likely gets activated for those parts.

The only problem we have found is when  we use the dlib as part of a python extension library.
When we exit python,  the python interpreter
 hangs forever in a lock/unlock during delete of the timer_global_clock singleton object.

The debugger attached picks up the thread/callstack located to:
 line 168..169 in shared_ptr_thread_safe.h 
  shared_node->unlock(); 
  delete data;

The callstack indicates that it's during the extension-library unload process, maybe static object destructors are called.

More specific info:
 only on windows platform (ms c++ 2015&2017, python 3.4..3.5.3),
 We are not able to reproduce on any linux-platform nor python version.

We found a workaround, that could be formed as a pull-request:
We just exposed a new function:

dlib::delete_global_clock();

- that reset the global-thread-safe singleton shared-pointer.
  (it's available at the fork https://github.com/sigbjorn/dlib)

If  we invoke this function as part of the python atexit registered function in our extension-module,
everything cleans up nice, and no more hang-situations. 

I suspect the dlib author(s) could provide even better solutions to this, maybe  with no code-changes,
so I leave this as an issue/question to maybe get some hint's about better approaches for solving this.

Br.
Sigbjørn Helset
MSc, Chief Developer Statkraft/ maintainer of shyft

**Comment by davisking** [comment]
Thanks, I'm glad you like dlib :)

If it's pausing it should be because one of the timer events is still running when you try to unload it.  Like maybe you have called `iosockstream::terminate_connection_after_timeout()` and the timer is still running.  Are you sure all the dlib objects have been freed before you unload it?  If that were the case this shouldn't happen.

**Comment by sigbjorn** [comment]
Hi,

Thanks for immediate feedback, - 
I am looking into it to day, and yes, the only dlib-object, the iostream socket is deleted before we call exit. (verified by printouts).

During the socket/close/delete, a timer is created (and global-clock thread started), 
and then removed upon successful socket close.

Inspecting the process by debugger at this time, before python exit, shows 4 threads, where we recognize the s.wait_or_timeout() thread, the global-clock thread waiting for more work to do.
There are no timers active (tm. size()==0).

If we then invoke function to terminate the thread (shutdown=true ,signal etc.), it terminates the thread, and everything works as expected during static desctructors on unloading the dll.

If we let the global clock thread just run, call the python exit, the next things that happens is that the dll get unloaded. At this time c++ invokes the static desctructors around in the dll,  in some order.

Attaching the debugger at this time reveals that *all* threads are gone, except the python main-thread which is doing the dll-unloading. 
Nevertheless, the waiters variable of the global timer clock is 1, and thus a WaitForSingleObject(....) is invoked during s.signal() (expecting the global timer thread to ping back).
 This call will never return, since the global timer-thread somehow escaped the scene without ticking down the signaler.waiters counter.

I am experimenting with adding a global timer thread stop when no more timers are left in the timer-list, i.e. *symmetric* solution to the 
timer_global_clock::add() that do start the thread if it's not running.
thus, the 
timer_global_clock::remove(..) could/should stop the thread, if there is no more timers active, keeping moving parts at a minimum.

Early tests indicates that this also do work, but I feel that's still a workaround, since I have not found the exact point where the timer_global_clock thread 'leaves the building' with no traces.
 -  except leaving the state of the timer_global_clock in disorder, that is, the state of the object indicates there is someone waiting &running, but there is no more threads running.

I continue work a bit on this to see if we can reveal the point where the global clock thread exits, I feel that could be useful if there is something that needs special care during shutdown.

Br Sigbjørn

**Comment by davisking** [comment]
So it's blocked on the call to wait() in the timer_global_clock
destructor?  Or something else?

**Comment by sigbjorn** [comment]
Yes, it's blocked on 
~timer_gloval_clock() {
  m.lock();
  shutdown = true; // a this point s.waiters is 1, indicating there is a thread alive waiting..
  s.signal(); // blocks here,  ref line 192 in threads_kernel_1.h, WaitForSingleObject(hCountSema,infinite..)
  : 
}

**Comment by davisking** [comment]
That's bizarre.  s.signal() should never block under any circumstances.  Are you certain that's where it's blocked?  Also, are you debugging this in the normal dlib code or the one you modified.  The only way I would expect s.signal() to block is if something has gone catastrophically wrong (e.g. s has already been destructed before the call to s.signal).

**Comment by sigbjorn** [comment]
Yes, we are on the windows platform ;-) 
During investigation, I run on unmodified code (straight from github, master).

 I am digging into the exit process of  python on windows, according to

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx

"
Exiting a process causes the following:
1.All of the threads in the process, except the calling thread, terminate their execution without receiving a DLL_THREAD_DETACH notification.
2. The states of all of the threads terminated in step 1 become signaled.
3. The entry-point functions of all loaded dynamic-link libraries (DLLs) are called with DLL_PROCESS_DETACH
"
it seems that it could terminate all threads (except main) as the very first point on the 'termination' recipe (with no notification). 
This supports the impression we get when attaching the debugger. I will do some more checking to verify that this is whats really happening.

**Comment by sigbjorn** [comment]
Update: 
I have confirmed that the execution are in the ExitProcess() function of windows when this happens.
Debugger reveals that python.exe/python34.dll, microsoft runtime version 10,  line 621 in file crt0dat.c, 
call to __crtExitProcess(code).

Furthermore, that our python extension module (.pyd-file), receive a the DLL_PROCESS_DETACH call, that  do call the static destructors, including the timer_global_clock, that end up in infinite wait.

The problem is that microsoft kills all dlib-threads (and other for that matter) before calling the static destructors.

The timer_global_clock() destructor rely on a correct state of it's object, including it's thread (very reasonable!)
This condition is broken (by ms!) during the ExitProcess function.

So the thing going catastrophically wrong seems to be performed by ms ExitProcess function, that silently kills the threads. 
Memory etc everything is ok, including the state of the objects, but the threads executing on the objects are taken away silently.

From my understanding now, this is something that we have to deal with, for that specific platform and use-case.

I am not just sure which solutions we should recommend:

If this is just something that relates to the timer_global_clock(), then we could just shrink  
the destructor of the singleton to  barely nothing ,
 after all, the threads are gone, and memory is about to be dealt with at operating-system/process level anyway .
 
We also need to be certain that we don't introduce something that do not work on the linux platform.

**Comment by davisking** [comment]
Well, you have to worry about someone who unloads and reloads the dll repeatedly.  So you can't just remove the destructor.  

Also, I'm a little surprised by this.  I've used threads inside dlls in windows before and don't recall this being an issue.  It always seemed like global objects were destructed before threads were terminated.  But maybe I'm wrong.  As a test, you should make a thread with std::thread (as a global object) and see if MS kills the thread before the std::thread instance is destructed.  If that works properly we can just change the windows implementation to use std::thread.

**Comment by sigbjorn** [comment]
Hi,

I have done that, and verified the behavior.

See the attached vs 2017 thread_termination example.

The threads are killed before  *.dll process detach* is called (this is according to how I understand the doc from ms, although it's not written that clearly in doc.).

(Notice that in the main.exe, it seems that destructors are called first, then ExitProcess takes care of the 'rest', starting with thread cleanup as first point, secondly calling dll_process detach that calls static destructors of each and every .dll loaded)

[thread_termination.zip](https://github.com/davisking/dlib/files/880107/thread_termination.zip)

For us, it's a sufficient solution that we do have some functions to reset/clear threads/objects that needs that kind of interaction, by explicit call that we put into place in the python-module at_exit function.

In the scenario of multiple load/unload the same dll (or .so) into the same process context, we have to ensure that second to n'th time looks and behaves like the first (no memory or resource-leak etc.).

Br Sigbjørn

**Comment by davisking** [comment]
Hmm.  So it's only in the dll that threads are killed before destructors.  That's irritating.  There should be some general solution for this that doesn't require the user (you in this case) to know to call some special global cleanup function.  It's not possible to tell python to explicitly unload all the dlls before terminating the process?

**Comment by sigbjorn** [comment]
Yes, there is one possibility that we can use, but it needs some help from the library.
By registering a callback for the at_exit function, we get a callback from python prior to 
the ms- stuff that breaks most code. 
If we put in a possibility to clean-up typical singletons (put them back to the original state, as before they are invoked the first time), - that would solve these issues in a manner that is kind of platform independent.

I have tested this approach in shyft, and it works for that particular purpose. (shyft branch dtss_2, in combination with my fork github.com/sigbjorn/dlib that contain a rudimentary patch to provide a one-way ticket cleanup.

If I put some more work into the singleton pattern, we could have a solution for the usage in dll's .

If you wish, I could do some more work on my fork, to ensure thread-safety, multiple load/unload etc. and do a PR for it? 

Br Sigbjørn

**Comment by davisking** [comment]
Still, that requires users to know about this implementation detail.  What
about creating a thread_local variable inside the timer's thread and having
that variable's destructor do the work we are talking about.  Hopefully
visual studio will destroy thread_local variables.  Have you tried that?
Or does it just kill the thread and leak thread_local objects?

**Comment by sigbjorn** [comment]
Hi,

Well, all the destructors are called, the only problem is that if it's a dll, then the threads are gone, so we can't rely on any thread handshake during *static* destructors.

I guess that there are very few static destructors, and of those, even fewer that explicit or implicit rely on thread-handshake.

Somehow our solution have to workaround that limitation, I will have a look into that, including investigating if we can utilize tls.

Br Sigbjørn

**Comment by sigbjorn** [comment]
Update: testing shows that  tls  destructors are not called if  ExitProgram and thread is killed.

**Comment by davisking** [comment]
Wow, it just leaks thread_local variables?

**Comment by logidelic** [comment]
Might this issue account for a memory leak under Windows each time a new thread is used to access a DNN? I'm trying to figure out a leak that only happens as I use DNNs in new threads. The weird thing is that if I force the exact same stuff into only a single thread, I don't get the leak. Similarly, if I do the same thread stuff but without the DNN access, I don't get the leak...

**Comment by davisking** [comment]
If you aren't loading and unloading a DLL that contains the deep learning code then this shouldn't apply to you.  Unless you have discovered another way visual studio fails to implement thread_local correctly.
