### ISSUE TITLE
Detector for face recognition

### ISSUE THREAD

**Issue by bkj** [davisking/dlib#506]
Was the `dlib_face_recognition_resnet_model_v1.dat` model trained using faces extracted w/ the HOG detector or the new DNN-based detector?  

The examples suggest HOG, but the blog suggests the DNN detector is more accurate, so wanted to make sure I was using the recommended one.  Presumably it's best to use the detector that the model was trained with, to keep things like cropping constant.

**Comment by davisking** [comment]
It was trained with faces from the HOG model.  Yes, I would use the HOG one.  Although it doesn't really matter so long as the landmarking works since that's what does the alignment and face crop extraction.
