### ISSUE TITLE
dlib for all types of face poses

### ISSUE THREAD

**Issue by PVNathan** [davisking/dlib#507]
Hi Davis,
First of all, I really appreciate the dlib library and more importantly the active updates and responses that you and others have been providing here on github. 

Now my question: I have been searching online if I could train a model using dlib that would detect faces with frontal, profile and any other views. More specifically I was hoping to get performance accuracy similar to CLM framework. I did come across one of your suggestions to train a model that would detect profile (left and/or right) faces. What I am confused about is whether in order to make a "global" face detector should I have multiple models, each trained on different view of the face and apply all of them in like an if-else condition or Is there a way to train one model that can find a face regardless of the view. 

Along the same lines of training a new model, can someone suggest a database with all types of faces that do not have license associated with it.  I know some of them have non-commercial research purpose only attached to them. 

Appreciate the help!
Thanks

**Comment by davisking** [comment]
This question is pretty much directly answered by this blog post from a few
months ago:
http://blog.dlib.net/2016/10/easily-create-high-quality-object.html

**Comment by PVNathan** [comment]
Thanks for the response. I thought the blog post was about deep learning. Is training an all-pose model only possible through deep learning? I was trying to not go down the path of deep-learning as I do not have the hardware resources to train it. 
Thanks

**Comment by PVNathan** [comment]
I think I got the answer. Thanks

**Comment by davisking** [comment]
No problem.  If you want to train a HOG model you need multiple models.  You can use imglab --cluster to help you group your training data into sensible subsets for training multiple models.  You will need to manually review it and make it nice and clean by hand though.  But --cluster makes it a lot easier.

**Comment by PVNathan** [comment]
Thanks. By the way do you have any idea about a ace dataset that doesn't come with 'research-purpose only' attached to it? I couldn't find any yet. Thanks

**Comment by davisking** [comment]
I don't know.  It's pretty easy to make your own though.  Just scrape the internet.

**Comment by PVNathan** [comment]
Hi Davis,
Sorry for troubling you again. I am training dlib for detecting faces in different poses. Say I had to detect faces that could go from -45 degree to 0 degree with 0 degree meaning the frontal pose. Roughly, how many example images would I need to make a detector to do that? I was thinking of dividing the 45 degree span into maybe 3-4 sub-angles and maybe for each angle 50 example images. This would mean to detect one side of frontal face I would have about 150-200 example images. Would that be sufficient?
Appreciate the answer
Thanks

**Comment by davisking** [comment]
Maybe. You will have to try it and see.

**Comment by PVNathan** [comment]
okay, thanks. Also, thanks for for providing imglab tool, its a great help.
