### ISSUE TITLE
Add example for Reinforcement Learning feature

### ISSUE THREAD

**Issue by travek** [davisking/dlib#508]
Hi!
Could you please provide an example of using Reinforcement Learning feature or give a link on the already existing example.
It will be very valuable to have an example of how to train, test and use the the feature for new samples.

Thanks!

**Comment by davisking** [comment]
It wouldn't be a very useful example.  LSPI is a fickle algorithm and you need to apply it carefully to your problem to get any kind of useful result.  At this point, I'm not really even a fan of it anymore.  Realistically, I would go with a different method.

**Comment by travek** [comment]
Davis,
will there be other Reinforcement Learning algorithms implemented in dlib soon ? Are there any plans on this ?

**Comment by davisking** [comment]
Probably not.
