### ISSUE TITLE
Q: Is there an easy way to split a matrix of K, R*C back into a tensor of K,R,C

### ISSUE THREAD

**Issue by OranjeeGeneral** [davisking/dlib#509]
I needed to convert a tensor from 1,K,R,C to a matrix of K,R*C to do some calculation but is there an easy way to convert it back to a tensor of format 1,K,R,C? 

Can't see it in the tensor class I could only find a matrix of format N,K*R*C assignment.

**Comment by davisking** [comment]
No, there isn't a function that does that.

**Comment by OranjeeGeneral** [comment]
Are you sure? There seems to be a method kind of I can use set_sample that does the trick when I specify a result tensor in the right format.

**Comment by davisking** [comment]
Well, yeah, there are a lot of things in there and it's easy to do what you
are asking.  But there isn't one function that does specifically what you
want.
