### ISSUE TITLE
regression target of shape predictor trainer

### ISSUE THREAD

**Issue by prayshe** [davisking/dlib#51]
I am confused about the regression target when training a shape predictor model. In your code, the target is the difference of ground truth and current shape. According to this paper, [Face Alignment by Explicit Shape Regression](http://research.microsoft.com/pubs/206636/Face%20Alignment%20by%20Explicit%20Shape%20Regression.pdf), however, the real target is product of difference and similarity transformation matrix, which has been computed when extracting pixel values. Have you ever considered that? It may influence the performance.

**Comment by davisking** [comment]
There is a similarity transform in my code.

**Comment by prayshe** [comment]
Of course I know you have computed the transform matrix, but you did't use it to normalize the difference between target and current, you just use it to extract features.

**Comment by davisking** [comment]
Where else would I use it other than in the parts of the code that look at
the image (i.e. the parts that extract features)?

**Comment by prayshe** [comment]
suppose we have two images with the same face but different angle, which means one can be obtained by rotating another one in 2-D plane. Obviously, they have the same pixel difference features, but different shape offsets. So why not transforming these offsets.I tested this idea a small dataset, LFPW, and it outperforms without transforming offsets. But in other larger datasets, such as I-BUG, it seems doesn't matter. So it's just a hint. Thanks.

**Comment by davisking** [comment]
How do you know how to transform the image when you really use it? It isn't as if you know the true labels when you get a new image during test time.

**Comment by prayshe** [comment]
We don't need the true label when transforming a current shape. We just transform the current shape to the initial shape, such as mean shape, to make sure we are working in the same coordinate system. More details are talked in face alignment by explicit shape regression. Equation 3 In section 2.1 describes the regression target like that, y = M(gt - current), not y = gt - current, where M is the transform matrix between current and mean.
