### ISSUE TITLE
setCudeDevice issue

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#511]
Hi,

If i call dlib::cuda::set_device(2) (or others)
i get this error:
terminate called after throwing an instance of 'dlib::cublas_error'
  what():  Error while calling cublasCreate(&handles[new_device_id]) in file /home/vision/dnn/dlib-19.4/dlib/dnn/cublas_dlibapi.cpp:78. code: 1, reason: CUDA Runtime API initialization failed.
Aborted (core dumped)

I simply created multiple net objects.
And then i used the dlib thread libary to create diffrent threads.

Example where the error occurs:
void thread3(void*) {
	dlib::rand rnd3(time(0));
	int threadId = 2;
       printf("Start Thread 3\n");
      dlib::cuda::set_device(threadId);
....
 for(int i = threadId; i < mdata.size(); i+=4) {
	     dlib::array<matrix<rgb_pixel>> images;
        matrix<rgb_pixel> img;
        load_image(img, mdata[i].filename);       
        randomly_crop_images(img, images, rnd3, crops);       
        matrix<float,1,20> p = sum_rows(mat(snet3(images.begin(), images.end())))/crops;   
}

Any ideas what i do wrong here or is this maybe even a bug?

as always thanks a lot.

Btw training with mutliple gpus selected via your trainer works fine. So i dont think its an hardware issue

**Comment by davisking** [comment]
You have to set the cuda device before you make the network.  GPU memory is allocated on a device.  So you can't make some object that allocates GPU memory, then switch devices, and then try to use it.  That doesn't make sense and will give a cuda error.  

Although the error you posted doesn't sound like that.  That does sound more like some kind of hardware failure.  But who knows.

**Comment by VisionEp1** [comment]
Thanks,
that solved the problem.

I was also confused by the error message.

As always thanks a lot!

**Comment by davisking** [comment]
No problem :)

**Comment by ivankras** [comment]
One related question (the error message is similar): How can I run a detector with a network trained on 2 GPUs on a PC that has only one GPU?

P.S.: this is the error I'm getting
*Error while calling cudnnCreate(&handles[new_device_id]) in file C:\dep\dlib\dlib\cuda\cudnn_dlibapi.cpp:104. code: 1, reason: CUDA Runtime API initialization failed*

**Comment by davisking** [comment]
How you train a network has no connection to how it is run later on.  In
particular, all the network objects in dlib run on a single GPU.  This is
regardless of how many GPUs were used in training.
