### ISSUE TITLE
problems about imglab，please help me!

### ISSUE THREAD

**Issue by coolsworder** [davisking/dlib#516]
Hi eveyone,

I am just want to add 68 parts in the image using imglab, but I found imglab cannot show the all indexes,  like the following image shows.

![12345](https://cloud.githubusercontent.com/assets/14148802/24661901/395a86da-1986-11e7-998e-93218190aaa4.png)

how to select the index(or parts) of 30~67, they are not displayed.

thanks!

**Comment by coolsworder** [comment]
![12345](https://cloud.githubusercontent.com/assets/14148802/24661822/05d2dce0-1986-11e7-875f-6096902cff25.png)

**Comment by davisking** [comment]
You should add a generic template to each file.  Like put the landmarks in their average location inside each object to start with.  Then use imglab to go in and move them to their correct position.  That's way easier than adding them through the GUI.

**Comment by coolsworder** [comment]
thanks davisking , but how to move landmarks, for example, the "05 point" in the following picture, I cannot find how to move it to another position

**Comment by davisking** [comment]
Click the About button.

**Comment by coolsworder** [comment]
thanks for your quickly reply,  @davisking
