### ISSUE TITLE
DNN face detecion hangs after C# application finishes

### ISSUE THREAD

**Issue by txicos** [davisking/dlib#520]
Hi All,

I have included dlib´s deep learning face detector in my own computer vision static library (lets name it mylib.lib) which is used by both a "pure" Microsoft C++ windows console application and C# application. DLIB library was compiled as a static library as well.

In case of the C++ application it directly imports mylib.lib into .exe. The C# application, on the other hand, imports mylib.lib through a C++ CLR managed code DLL.

After executing both applications, it can be seen that C++ application returns to OS. However, C# application hangs. After inserting some printf´s on dlib´s code it was possible to check that problem is on
 
```
thread_pool_implementation::shutdown_pool
.
.
.

            task_ready_signaler.broadcast(TIMEOUT); // my adaptation
```

The _broadcast_ method call MS _WaitForSingleObject_ , which becomes irresponsive. My solution so far was to add a timeout instead of waiting indefinitely with INFINITE.

I wonder if you guys would have a better idea or some other comment?

I attached a debugging code together with its output. You can notice in CPPOK.txt that interlocking between _wait()_ and _broadcast()_ works as expected. However, in case of c#fail.txt _wait()_ hangs on
 `WaitForSingleObject (hSemaphore,INFINITE);` 

and never releases _broadcast()´s_  

`WaitForSingleObject(hCountSema,milliseconds);`

[c#fail.txt](https://github.com/davisking/dlib/files/896498/c.fail.txt)
[CPPOK.txt](https://github.com/davisking/dlib/files/896500/CPPOK.txt)
[thread_pool_extension_cpp.txt](https://github.com/davisking/dlib/files/896501/thread_pool_extension_cpp.txt)
[thread_pool_extension_h.txt](https://github.com/davisking/dlib/files/896502/thread_pool_extension_h.txt)
[threads_kernel_1_h.txt](https://github.com/davisking/dlib/files/896499/threads_kernel_1_h.txt)

**Comment by davisking** [comment]
If you set DLIB_THREAD_POOL_TIMEOUT to 0 that will disable the thread pool
and might make this go away.  Does that do the trick?

**Comment by txicos** [comment]
Hi Davis,

Unfortunately it didn´t work.

**Comment by davisking** [comment]
Do you know what threads are blocking?  Or what part of the code you are running that is launching these threads?

**Comment by txicos** [comment]
Hi,

My applications both end up instantiating a _loss_mmod_ object which in turn calls _input_rgb_image_pyramid_, which calls _to_tensor_ (dnn/input.h), which makes use of a _parallel_for_. It is this _parallel_for_ that makes use of thread_pool and launches the blocking threads.

**Comment by davisking** [comment]
What version of dlib are you using? I would expect this to not happen in the latest version.

**Comment by txicos** [comment]
dlib 19.4. In fact it is a clone of master branch. So it is updated with latest commits.

**Comment by davisking** [comment]
Well, the parallel_for code doesn't make any calls into the threading code
you said is hanging, so it can't be that.  You must be calling some other
part of dlib that does it, like maybe the gui code.

**Comment by txicos** [comment]
Hi,

Could it be possible that parallel_for at [https://github.com/davisking/dlib/blob/master/dlib/dnn/input.h](url)@571 shouldn´t be using the thread_pool? Eventually the _default_thread_pool_ should be using 

Anyway, I placed some _printf(" %s %d \n", __FUNCTION__,__LINE__);_ in relevant methods of _input.h_, _parallel_for_extension.h_ and _thread_pool_implementation.cpp_ and it can be seen that it seizes threads through the thread_pool

 _dlib::input_rgb_image_pyramid<class dlib::pyramid_down<6> >::to_tensor 554_
_dlib::parallel_for 319_  5th overloaded method which call _default_thread_pool_
--->>>  _dlib::thread_pool_implementation::thread_pool_implementation 29_
_dlib::parallel_for 270_ 3rd overloaded method
_dlib::parallel_for 219_ 1st overloaded method
_dlib::parallel_for_blocked_ 87
 _threads in pool 8 dlib::parallel_for_blocked 99_  --> inside if for adding tasks

Coincidentally the number 8 is the same number of threads waiting to be released. Furthermore, I don´t make any direct use of dlib/gui* methods

Once inside _thread_pool_implementation_ class _shutdow_n method is called during object release and codes get stuck on **MS** _WaitForSingleObject (hSemaphore,INFINITE);_

**Comment by davisking** [comment]
Ah, sorry.  I get a lot of posts and forget who I'm talking to sometimes.  Yes, the parallel_for code does call into this thread pool (there is another in dlib but it's not involved here).  

This seems to be a recent problem with windows which involves how visual studio abruptly and without warning kills threads during dll unload. (see https://github.com/davisking/dlib/issues/505).  There doesn't seem to be a very good general solution.  You could try switching the dlib mutex and signaler to use the C++11 equivalents, std::mutex and std::condition_variable.  That is, make dlib::mutex and dlib::signaler implemented in terms of those C++11 tools and maybe it won't hang.  Although based on the discussion from #505 I wouldn't be surprised if you ran into some other problem.

**Comment by txicos** [comment]
Hi,

I think I will keep using my workaround for the time being, since It didn´t show any side effects so far.

In _thread_pool_extension.cpp_

```
#ifdef WIN32	
#define TIMEOUT 4000
#else
#define TIMEOUT INFINITE
#endif

            task_ready_signaler.broadcast(TIMEOUT);
```


Then in _thread_hernel_1.h_

```
        void broadcast (unsigned long milliseconds = INFINITE) const 
        { 
            // get a lock on the mutex for the waiters variable
            waiters_mutex.lock();
            
            if (waiters > 0)
            {   
                // make the semaphore release all the waiting threads
                ReleaseSemaphore(hSemaphore,(LONG)waiters,NULL);

                // wait for count to be zero
                for (unsigned long i = 0; i < waiters; ++i)
                {
                    WaitForSingleObject(hCountSema,milliseconds);
                }

                waiters = 0;
            }
						
            // release the mutex for waiters
            waiters_mutex.unlock();
        }
```
