### ISSUE TITLE
Some questions about train_shape_predictor_ex_main.cpp

### ISSUE THREAD

**Issue by coolsworder** [davisking/dlib#521]
hello everyone,

I runned the example in train_shape_predictor_ex_main.cpp and got the file sp_cs.dat. Then, I used sp_cs.dat to detect landmarks of my face using camera. I found the detected results are very different between continuous frames when I keep the same posture.
I am wondering why this appears, was it because the training set is too small? If I augment the training dataset, can I get more precisely sp_cs.dat?

By the way, train_shape_predictor_ex_main.cpp mentions 
“This algorithm has a bunch of parameters you can mess with.  The
  documentation for the shape_predictor_trainer explains all of them.
  You should also read Kazemi's paper which explains all the parameters
  in great detail”
what's the exactly paper does 'Kazemi's paper' means?

BRS

**Comment by davisking** [comment]
Yes, it's just an example.  It doesn't make a high quality model as the dataset is too small.  

The example program you are reading contains a full reference to Kazemi's paper.

**Comment by coolsworder** [comment]
thanks @davisking
