### ISSUE TITLE
dnn_face_recognition_ex compiling error after building dlib

### ISSUE THREAD

**Issue by msobhan69** [davisking/dlib#528]
dlib compiled and built with msvc 2015 in CPU-Release-x64 mod completely. Also, I test dnn_face_recognition_ex.exe, and it's working. 
next, I create a c++ project and use dlib to face recognition, completely like face recognition example.
error is occurred, see below:

main.cpp
Generating code
fatal error C1083: Cannot open compiler intermediate file: '****\facerecog.ipdb': Not enough space
LINK : fatal error LNK1257: code generation failed

**Comment by davisking** [comment]
I don't know.  Maybe you are out of harddrive space?  Or maybe you have discovered a bug in visual studio.

**Comment by msobhan69** [comment]
@davisking Tank you for your comment. You're right, the memory is full (2G free memory).
How much free memory is necessary for dnn_face_recognition_ex? If this need a lot of free memory, why is there no problem in building dlib?

**Comment by davisking** [comment]
Beats me.  I would file a bug report on Microsoft's web page.
