### ISSUE TITLE
Q: How do you set dropout rate on a dropout layer

### ISSUE THREAD

**Issue by OranjeeGeneral** [davisking/dlib#529]
Sorry for the rather dumb question but how do you set a dropout rate on a dropout layer as it explicitly constructor set it to 0.5 and the layer has no set_drop_rate method just a get_drop_rate method.

**Comment by davisking** [comment]
Make a layer configured how you want and use the = to assign to the layer.  Like `whatever = new_object(args,you,want);`

**Comment by OranjeeGeneral** [comment]
Ah okay thank you so I basically need to get the layer with layer<layerNr>(NET) and then just assign it to a new Dropout_ instance. Didn't think about that.
