### ISSUE TITLE
The order of landmarks have been changed

### ISSUE THREAD

**Issue by pencoa** [davisking/dlib#531]
I want to train new face landmark detector with another annotation standard.   
This is the training data location.
![xml](https://cloud.githubusercontent.com/assets/7123063/24915037/a45bb97c-1f08-11e7-9e83-718842b71200.png)
This is the predictor result location.
![wx20170411-151809](https://cloud.githubusercontent.com/assets/7123063/24915055/ac6733e4-1f08-11e7-96f4-b14b45f8ba5e.png)
The predictor is still able to predict the location of face landmarks. But the order of landmarks have been changed. Has anyone met this problem?

![wx20170411-225201](https://cloud.githubusercontent.com/assets/7123063/24915366/86ff91d6-1f09-11e7-8a16-972fb5fee7cd.png)
The things I have done is that I trained new face detector and modified frontal_face_detector.h and render_face_detection.h in dlib/image_processing.

**Comment by davisking** [comment]
Loading data correctly is up to you.  But if I had to guess I bet you are getting messed up somewhere based on alphabetic sorting of strings (the labels) being different from numeric sorting.

**Comment by pencoa** [comment]
Oh, you are right. Here is the difference between training xml with example xml.  
![wx20170412-181136](https://cloud.githubusercontent.com/assets/7123063/24952835/9fda6a12-1fab-11e7-8eb9-7c4ee7e38fd4.png)

**Comment by sarmadm** [comment]
@pencoa , Could you please show me how did you train a new landmark detector ?

**Comment by pencoa** [comment]
@sarmadm  which step?
Firstly, prepare the 'training_with_face_landmarks.xml' with /tools/imglab. 
Secondly, training with /python_example/train_shape_predictor.py.

**Comment by sarmadm** [comment]
for helen data set which contains 2000 images , I need only to detect the eyes .

1. do I have to label the eyes for all the 2000 images ?
2. is labelling ( drawing rectangle ) around the eyes sufficient ?

Thanks

**Comment by pencoa** [comment]
**Step1** draw rectangle with dlib original face detector.
Here is my code.
```

#!/usr/bin/python

"""
using the original dlib face detector to draw face box
"""

import sys

import dlib
from skimage import io

detector = dlib.get_frontal_face_detector()
win = dlib.image_window()

head = """<?xml version='1.0' encoding='ISO-8859-1'?>
<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>
<dataset>
<name>imglab dataset</name>
<comment>Created by imglab tool.</comment>
<images>"""

tail = """</images>
</dataset>"""

print(head)

for f in sys.argv[1:]:
    name = f[-11:]
    img = io.imread(f)
    # detect faces in img
    dets = detector(img, 1)
    if len(dets) < 1:
        continue
    # one face and one box in each image
    box = dets[0]
    # <box top='3' left='154' width='364' height='517'>
    # box.top() box.left() box.width() box.height()
    print("  <image file='%s'>" %name)
    print("    <box top='%d' left='%d' width='%d' height='%d'>"
              %(box.top(), box.left(), box.width(), box.height()))
    print("    </box>")
    print("  </image>")


print(tail)

```

**Step2** extract the landmarks location data in HELEN training dataset and inset them into the xml file from step1. The structure is like my answer above. Pay attention to the order number of each part.

**Comment by pencoa** [comment]
Of course, you can label directly around the eyes. But you need to train another object detector.
Using the existing face detector is enough for your aim.

**Comment by sarmadm** [comment]
@pencoa Thanks .

I'm still confused . I run your code like below : 

> ubuntu@ubuntu:~$ python3.4 train.py
<?xml version='1.0' encoding='ISO-8859-1'?>
<?xml-stylesheet type='text/xsl' href='image_metadata_stylesheet.xsl'?>
<dataset>
<name>imglab dataset</name>
<comment>Created by imglab tool.</comment>
<images>
</images>
</dataset>

**Comment by zoha21** [comment]
@pencoa do you mind sharing your code for step 2?
