### ISSUE TITLE
Cleaning of kernel recursive least squares function

### ISSUE THREAD

**Issue by travek** [davisking/dlib#532]
Hi!

I have a short question on the cleaning (memory erasing) of kernel recursive least squares function (krls) in dlib.
I declared klrs function and initialized it.
I trained krls on 100 samples.
I want to train krls on next 100 samples but in a way that previous 100 samples are not impacting the training result of new training iteration.
I tried to use clear_dictionary() but noticed that this doesn't totally clean initially trained krls.
How do you recommend to fully cleaned initially trained krls ??

I'm using the code like

typedef sigmoid_kernel<sample_type> kernel_type;
krls<kernel_type2> krls_predictor(kernel_type(kernel_param, kernel_param2), sensitivity, krls_dictionary_size_);

krls_predictor.clear_dictionary();			
for (int ind = 0; ind < samples.size(); ++ind)
{
	krls_predictor.train(samples[ind], targets[ind]);
	if (krls_predictor.dictionary_size() >= krls_dictionary_size_)
		break;
}

**Comment by davisking** [comment]
I'm pretty sure clear_dictionary makes it forget the training data.  That's the point of that function.

**Comment by travek** [comment]
Davis,
here's a mistake.

After the call of clear_dictionary() it does NOT clear q, a, k, temp_matrix params of KLRS. You can easily trace this.
There's a need in a fix that after a call of clear_dictionary() it clears all params, but not only dictionary, alpha, K_inv, K, P params.

**Comment by davisking** [comment]
Those variables don't matter.  The output from the object will be the same as a fresh copy.
