### ISSUE TITLE
Build PythonAPI on Windows 10

### ISSUE THREAD

**Issue by IronBCC** [davisking/dlib#535]
I'm trying to build last version (19.4) from sources on Windows 10 platform, but have such errors :
(My config : CUDA 8.0; CuDNN (in same folder, but dlib couldn't find it); Boost 1.63 from Sources; Anaconda 2 64bib; MinGW-w63 6.3 posix, sjlj)
1. Using VS 15 2017 Compiler for build boost and dlib it's stuck at (or right after) building face_recognition.cpp for awhile (more then 4 hours)
2. Using MinGW-w64 for boost and dlib, everything is almost good (dlib builds well from dlib root folder), but there is error for build-install step for python api (in tools/python folder)
`$ cmake --build . --clean-first --config Release --target install -- -j8 cxxflags="-include cmath -D_hypot=hypot" CMAKE_CXX_FLAGS="-include cmath -D_hypot=hypot"`

`... a lot of same undefined reference things...`                                                  
`CMakeFiles\dlib_.dir/objects.a(gui.cpp.obj):gui.cpp:(.text.startup+0x15b): undefined reference to 
'__imp__ZN5boost6python9converter8registry6lookupENS0_9type_infoE'`                     
`...`                                                                             
`CMakeFiles\dlib_.dir/objects.a(gui.cpp.obj):gui.cpp:(.text$_ZN5boost6python7objects12value_holderIN4dlib12image_windowEED1Ev[_ZN5boost6python7objects12value_holderIN4dlib12image_windowEED1Ev]+0x26): undefined reference to '__imp__ZN5boost6python15instance_holderD2Ev'`
`...`
`C:/Boost/lib/libboost_python-mgw63-mt-1_63.a(module.o):module.cpp:(.text+0x270): undefined reference to '__imp_Py_InitModule4'`
`collect2.exe: error: ld returned 1 exit status`
`CMakeFiles\dlib_.dir\build.make:561: recipe for target 'dlib.pyd' failed`
`...`

Has anyone idea what is wrong, and what to do? Maybe some one can publish .pyd to conda repo?

**Comment by davisking** [comment]
Those linker errors mean you have installed boost wrong.  You probably have multiple versions of python installed and you compiled boost against a different version than you are trying to use.  Also, yes, visual studio 2017 is buggy.  VC2015 should compile it fine.  I don't know about mingw on windows as far as python extensions go.  You might find that they are incompatible with the runtime used in the main python interpreter or it might work fine.  I would use VC2015.
