### ISSUE TITLE
undefined references

### ISSUE THREAD

**Issue by HanaaMAldaly** [davisking/dlib#541]
l used dlib library in detection(face landmark detection) and it works well but when use dnn for face recognition l get this error :
jni/dlib\dlib/threads/parallel_for_extension.h:310: error: undefined reference t
o 'dlib::default_thread_pool()'
jni/dlib\dlib/threads/thread_pool_extension.h:537: error: undefined reference to
 'dlib::thread_pool_implementation::num_threads_in_pool() const'
jni/dlib\dlib/threads/thread_pool_extension.h:537: error: undefined reference to
 'dlib::thread_pool_implementation::num_threads_in_pool() const'
jni/dlib\dlib/threads/thread_pool_extension.h:540: error: undefined reference to
 'dlib::thread_pool_implementation::wait_for_all_tasks() const'
jni/dlib\dlib/threads/thread_pool_extension.h:268: error: undefined reference to
 'dlib::thread_pool_implementation::find_empty_task_slot() const'
jni/dlib\dlib/threads/thread_pool_extension.h:269: error: undefined reference to
 'dlib::thread_pool_implementation::is_worker_thread(long) const'
jni/dlib\dlib/threads/thread_pool_extension.h:288: error: undefined reference to
 'dlib::thread_pool_implementation::find_empty_task_slot() const'
jni/dlib\dlib/threads/thread_pool_extension.h:292: error: undefined reference to
 'dlib::thread_pool_implementation::make_next_task_id(long)'
jni/dlib\dlib/dnn/layers.h:1732: error: undefined reference to 'dlib::tt::relu(d
lib::tensor&, dlib::tensor const&)'
jni/dlib\dlib/dnn/layers.h:1732: error: undefined reference to 'dlib::tt::relu(d
lib::tensor&, dlib::tensor const&)'
jni/dlib\dlib/dnn/layers.h:1732: error: undefined reference to 'dlib::tt::relu(d
lib::tensor&, dlib::tensor const&)'
jni/dlib\dlib/dnn/layers.h:1732: error: undefined reference to 'dlib::tt::relu(d
lib::tensor&, dlib::tensor const&)'
jni/dlib\dlib/dnn/tensor_tools.h:788: error: undefined reference to 'dlib::cpu::
tensor_conv::operator()(dlib::resizable_tensor&, dlib::tensor const&, dlib::tens
or const&, int, int, int, int)'
jni/dlib\dlib/dnn/layers.h:159: error: undefined reference to 'dlib::tt::add(flo
at, dlib::tensor&, float, dlib::tensor const&)'
jni/dlib\dlib/dnn/layers.h:1512: error: undefined reference to 'dlib::tt::affine
_transform(dlib::tensor&, dlib::tensor const&, dlib::tensor const&, dlib::tensor
 const&)'
jni/dlib\dlib/dnn/layers.h:1514: error: undefined reference to 'dlib::tt::affine
_transform_conv(dlib::tensor&, dlib::tensor const&, dlib::tensor const&, dlib::t
ensor const&)'
jni/dlib\dlib/dnn/tensor_tools.h:788: error: undefined reference to 'dlib::cpu::
tensor_conv::operator()(dlib::resizable_tensor&, dlib::tensor const&, dlib::tens
or const&, int, int, int, int)'
jni/dlib\dlib/dnn/layers.h:159: error: undefined reference to 'dlib::tt::add(flo
at, dlib::tensor&, float, dlib::tensor const&)'
jni/dlib\dlib/dnn/tensor_tools.h:788: error: undefined reference to 'dlib::cpu::
tensor_conv::operator()(dlib::resizable_tensor&, dlib::tensor const&, dlib::tens
or const&, int, int, int, int)'
jni/dlib\dlib/dnn/layers.h:159: error: undefined reference to 'dlib::tt::add(flo
at, dlib::tensor&, float, dlib::tensor const&)'
jni/dlib\dlib/dnn/tensor_tools.h:788: error: undefined reference to 'dlib::cpu::
tensor_conv::operator()(dlib::resizable_tensor&, dlib::tensor const&, dlib::tens
or const&, int, int, int, int)'
jni/dlib\dlib/dnn/layers.h:159: error: undefined reference to 'dlib::tt::add(flo
at, dlib::tensor&, float, dlib::tensor const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make: *** [obj/local/armeabi-v7a/libMyLibs.so] Error 1

E:\generateLibs>

**Comment by davisking** [comment]
Did you compile the example programs with cmake?

**Comment by HanaaMAldaly** [comment]
Nope actually l complile Dlib by cmd abd and it works with me but the dnn
algorithms doesn't work
Did you compile the example programs with cmake?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/davisking/dlib/issues/541#issuecomment-294983183>, or mute
the thread

**Comment by davisking** [comment]
Well, you are messing it up.  You are missing some of the dlib .cpp files.  That's what that linker error is telling you.  In any case, you should just use cmake.  It will set it up properly.

**Comment by HanaaMAldaly** [comment]
OK l ganna try it,
thanks

**Comment by HanaaMAldaly** [comment]
I'm sorry but how l can get the missing files because l'm working on mobile
app and l should compile it using ndk

**Comment by davisking** [comment]
There are instructions here that tell you how to use dlib: http://dlib.net/compile.html
