### ISSUE TITLE
python.h

### ISSUE THREAD

**Issue by Hend12** [davisking/dlib#542]
I have to run python scripts from cpp (c++) file and i used dlib/python.h  but  when I compile used android .mk  ,i get this error " fatal error: 'boost/python.hpp' file not found
#include <boost/python.hpp>"
and I downloaded boost library and get  this error  "fatal error: 'pyconfig.h' file not found
# include <pyconfig.h>"

**Comment by davisking** [comment]
pyconfig.h isn't part of dlib.  The problem is that you are missing header files for libraries other than dlib.  You should install those libraries.
