### ISSUE TITLE
extract_image_chips on Ubuntu 16.04.02 fails to extract valid data

### ISSUE THREAD

**Issue by Andrew62** [davisking/dlib#543]
I am running Ubuntu 16.04.02 in a docker container and compiling the following code with clang 3.8, dlib 19.3, and opencv 3.2:

    // create the simple socket
    net::Socket sockt = net::Socket(listenPort);
    
    // bind to  port
    sockt.bindSock();
    
    // look for connections
    sockt.startListening(backlog);
    
    // start accepting data from this new file descriptor
    sockt.acceptData(their_addr);
    
    // size of the image from the client
    int32_t image_size = 0;
    
    // object to store raw image data
    cv::Mat rawImage;
    
    // initialize the detector
    dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();
    dlib::shape_predictor sp;
    dlib::deserialize(argv[1]) >> sp;
    
    std::cout << "Capturing..." << std::endl;
    
    // for writing out images 
    int image_id = 1;
    
    while (true){
        
        // retrieve image size
        sockt.getData(&image_size, 4, NULL);
        
        if (image_size > 0) {
        
            rawImage.create(1, image_size, CV_8UC1);

            sockt.getData(rawImage.data, image_size, MSG_WAITALL);
            
            // decode raw image from 1xN into a proper jpeg
            dlib::cv_image<dlib::bgr_pixel> d_image = utils::process_frame(rawImage);
            
            // this saves a proper jpeg unlike below where we try to save chips
            dlib:save_jpeg(d_image, argv[2] + "full_image.jpg");

            std::vector<dlib::rectangle> detections = detector(d_image);
 
            if (detections.size() > 0){
                std::vector<dlib::full_object_detection> shapes;
                for (int idx = 0; idx < detections.size(); idx++){
                    dlib::full_object_detection shape = sp(d_image, detections[idx]);
                    shapes.push_back(shape);
                }
                dlib::array<dlib::array2d<dlib::bgr_pixel>> face_chips;
                dlib::extract_image_chips(d_image, dlib::get_face_chip_details(shapes), face_chips);
                for (int idx = 0; idx < face_chips.size(); idx++){
                    std::string fname = argv[2] + std::to_string(image_id) + ".jpg";
                    
                    // Saves corrupt jpeg
                    dlib::save_jpeg(face_chips[idx], fname);
                    image_id++;
                }

            }
            
            // clear the raw image 
            memset(&rawImage, 0x0, sizeof(rawImage));
            
        } else {
            std::cout << "No message yet" << std::endl;
            
        }
        // pause for half a second
        image_size = 0;
        usleep(1000);
    };

The compiler does not throw any warnings but produces invalid output. Here is an example of a corrupt image chip:
![3](https://cloud.githubusercontent.com/assets/3361916/25157917/6959c930-2472-11e7-888d-6063aae7a379.jpg)

It is worth mentioning that I have tried to compile this bare metal on Ubuntu 16.04 with the same result.  Sometimes part of the image will write correctly but a chip will always have errors. 
I have also compiled with -DDLIB_JPEG_SUPPORT and without with the same problem.

**Comment by Andrew62** [comment]
I have also compiled with -DDLIB_JPEG_SUPPORT and without with the same problem.

**Comment by e-fominov** [comment]
Please provide smaller example. We are not debugging your code here :)

Does examples/face_landmark_detection_ex works fine on your machine?

```C++
matrix<rgb_pixel> img, chip;
load_image(img, "test.jpg");
rectangle chip_rect(10, 10, 30, 30);
chip_dims dims(100, 100);
chip_details chip(chip_rect, dims);
extract_image_chip(img, chip, digit);
save_jpeg(chip, "chip.jpg");
```

Does this minimal code work?

**Comment by davisking** [comment]
Yes, this is not a dlib issue and this isn't the place to look for C++ help.  But I will point out that `memset(&rawImage, 0x0, sizeof(rawImage));` is definitely not right. You can't just go blasting the memory of C++ objects to zero like that.  That's definitely a problem.  I assume there are similar things elsewhere in the code (that you didn't post).  It's highly likely that this kind of thing is causing this problem.

**Comment by Andrew62** [comment]
Apologies for the long code example but i wanted to be thorough. I figured out the problem and was able to remove some pieces thanks to your snippet above. The problem is that `process_image` returned `dlib::cv_image` which I guess was causing issues since d_image still refers to the original `cv::Mat`. Thanks for your response.
