### ISSUE TITLE
Face detection on Video frames is very slow in Python

### ISSUE THREAD

**Issue by issa-s-ayoub** [davisking/dlib#547]
I have installed and compiled dlib on windows 10 with AVX_Instructions enabled to make code faster. Additionally, when building the project in Visual Studio I compiled it with the release mode x64. 
I tested the c++ version of the code and is working perfectly and very fast.

Inside the dlib directory I write the following in cmd: 
python setup.py install --yes USE_AVX_INSTRUCTIONS

But, when testing the python version of the code with a video as input, mainly face detection code, face detection was too slow, requiring around 170 ms for each frame. 

Please note that I am reading the frames with opencv3.1.
I have anaconda and python3.

**Comment by issa-s-ayoub** [comment]
I have solved it, mainly the problem was with enlarging the frame size. That is, with: 
dets = detector(frame, 1). Hence the one should be kept 0.

**Comment by didrudcks** [comment]
Hi I'm having same problem as you that running "faces = detector(frame_rgb)" in python and it gets so slow, Can you explain more how you fixed it? I still don't get what I should change to fix this problem
