### ISSUE TITLE
config_reader not recognizing escaped characters

### ISSUE THREAD

**Issue by rderby** [davisking/dlib#548]
Minor issue when adapting and testing your config_reader (config_reader_kernel1) to be used as the configuration file reader for an in-house non-commercial project.

Config reader not recognizing escaped characters. (config_reader_kernel1)

seems to work after: 
tokenizer.get_token added
 case '\\':
                type = CHAR;
                token = '\\';
                return;

config_reader.parse_config_file added
 
                        else if (tok.peek_type() == Tokenizer::CHAR &&
                            tok.peek_token()[0] == '{')
                        {
                            tok.get_token(type,token);
                            value += '{';
                        }

                        else if (tok.peek_type() == Tokenizer::CHAR &&
                            tok.peek_token()[0] == '=')
                        {
                            tok.get_token(type,token);
                            value += '=';
                        }

Thank you for the use of  your elegant code. rderby

**Comment by davisking** [comment]
Cool, I'm glad you like dlib :)

Can you post a config file that fails with the current code?
