### ISSUE TITLE
arm cross-compile fail

### ISSUE THREAD

**Issue by gangm** [davisking/dlib#549]
hello,

 I tried to port dlib to our armv7 platform, but got a problem when compling, see below:
[  8%] Building CXX object dlib/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
In file included from /home/gangm/arm-linux/dlib/dlib/bsp/../sockets/../threads.h:22:0,
                 from /home/gangm/arm-linux/dlib/dlib/bsp/../sockets/sockets_kernel_2.h:33,
                 from /home/gangm/arm-linux/dlib/dlib/bsp/../sockets/posix.h:4,
                 from /home/gangm/arm-linux/dlib/dlib/bsp/../sockets.h:14,
                 from /home/gangm/arm-linux/dlib/dlib/bsp/bsp.h:7,
                 from /home/gangm/arm-linux/dlib/dlib/bsp/bsp.cpp:6:
/home/gangm/arm-linux/dlib/dlib/bsp/../sockets/../threads/thread_pool_extension.h:456:21: error: 'exception_ptr' in namespace 'std' does not name a type

seems our arm compiler don't support std::exception_ptr, does anyone got the same problem? which arm compiler support this c++11 fature? thanks~

the version of our arm compiler is：
arm-none-linux-gnueabi-g++ (Sourcery CodeBench Lite 2013.05-24) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

i also tried 4.8.3, but no work yet...

**Comment by padmalcom** [comment]
Can you please explain why you closed this issue? I'm stuck here as well, if you have a solution please tell us.

**Comment by davisking** [comment]
You just need a C++11 compiler.

**Comment by padmalcom** [comment]
I call "cmake -DCMAKE_C_FLAGS="-O3 -mfpu=neon -fprofile-use -DENABLE_NEON" -DNEON=ON -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabi-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabi-g++ -DCMAKE_CXX_FLAGS="-std=c++11" --build --config Release ..". But I keep getting this error.

**Comment by padmalcom** [comment]
I figured out I had to use arm-linux-gnueabihf-gcc and arm-linux-gnueabihf-g++

**Comment by heweiSing** [comment]
I try to build for armv7:
"
dlib-19.8/build$ cmake -DCMAKE_C_FLAGS=”-O3 -mfpu=neon -fprofile-use -DENABLE_NEON” -DNEON=ON -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_CXX_FLAGS=”-std=c++11″ –build –config Release ..
Parse error in command line argument: -DENABLE_NEON”
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
"
But got the above error, any suggestion?

Thanks and best regards

**Comment by heweiSing** [comment]
Ok. Now I can build it successfully. and Any script / procedures to install on target ARM platform?

Thanks and best regards
He Wei

**Comment by trohit920** [comment]
@davisking @padmalcom @heweiSing Hello, I have successfully cross-compiled dlib for arm-architecture. However i am getting an error like: 
```
/usr/lib/gcc-cross/arm-linux-gnueabihf/5/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lX11
collect2: error: ld returned 1 exit status
```
My command line arguments are:
` arm-linux-gnueabihf-g++ -std=c++11 -o3 -I/home/rohit/rohit/dlib /home/rohit/rohit/dlib/dlib/all/source.cpp -lpthread -lX11 webcam_face_pose_ex.cpp -o webcam `pkg-config --cflags --libs opencv`

I have installed libX11-dev and it is present the folder. I am wondering is it because my libX11 is not for arm. Please help me with this. Waiting of your replies.

**Comment by trohit920** [comment]
I have solved the above error by using libX11 for arm-architecture. However i am getting another error while trying to compile the reference example:
```
/usr/lib/gcc-cross/arm-linux-gnueabihf/5/../../../../arm-linux-gnueabihf/lib/../lib/libX11.so: undefined reference to `fcntl@GLIBC_2.28'
collect2: error: ld returned 1 exit status
```
Please take a look at this.

**Comment by gianlazz** [comment]
> I try to build for armv7:
> "
> dlib-19.8/build$ cmake -DCMAKE_C_FLAGS=”-O3 -mfpu=neon -fprofile-use -DENABLE_NEON” -DNEON=ON -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_CXX_FLAGS=”-std=c++11″ –build –config Release ..
> Parse error in command line argument: -DENABLE_NEON”
> Should be: VAR:type=value
> CMake Error: No cmake script provided.
> CMake Error: Problem processing arguments. Aborting.
> "
> But got the above error, any suggestion?
> 
> Thanks and best regards

@heweiSing 

I'm having the same `> Parse error in command line argument: -DENABLE_NEON”` issue. Your comment is one of only a couple online mentioning it. How did you solve it?
