### ISSUE TITLE
Import Error: ... Undefined symbol dormqr_

### ISSUE THREAD

**Issue by maximus009** [davisking/dlib#55]
Hi,
I have worked on dlib v18.17  and the experience has been wonderful.

I am working on an AMI Linux system now.
To use dlib, I cloned your repository, instead of downloading dlib (I guess the latest one is v18.18). Anyway, I seem to face some issues on importing dlib.
<code>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/dlib.so: undefined symbol: dormqr_
</code>

Have I cloned the repo properly?
Kindly help with the solution. 

Thanks.

**Comment by davisking** [comment]
How did you compile it?

**Comment by maximus009** [comment]
The same way as I did before, using CMake.

**Comment by davisking** [comment]
Try typing `pip install dlib`

**Comment by davidglivar** [comment]
I have actually just run into this issue as well, running ubuntu 14.04

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /usr/local/lib/python2.7/dist-packages/dlib/dlib.so: undefined symbol: dormqr_
```

**Comment by davisking** [comment]
dormqr is a LAPACK function, so there must be something wrong with the version of LAPACK installed on your machine.  What lapack package is installed?  Also, what does `ldd /usr/local/lib/python2.7/dist-packages/dlib/dlib.so` output?

**Comment by davidglivar** [comment]
output of `ldd /usr/local/lib/python2.7/dist-packages/dlib/dlib.so`:

```
	linux-vdso.so.1 =>  (0x00007ffe123c2000)
	libboost_python-py27.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0 (0x00007f8235e2d000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f82358c9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82356ab000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8235376000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f8235150000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f8234efb000)
	libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007f82336f2000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f82333ee000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f82330e8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8232ed2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8232b0d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f82328f4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f82326f0000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f82324ed000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8236aaa000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f82322ce000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f82320ca000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8231ec4000)
```

Looks like lapack is not installed on my machine. I'll install and reinstall dlib and report back.

**Comment by davisking** [comment]
If you get the dlib source code and then run cmake by saying `mkdir build;
cd build; cmake ../tools/python` what is the output?

**Comment by davidglivar** [comment]
@davisking heres the output from above

```
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.6")
-- USING BOOST_LIBS: /usr/lib/x86_64-linux-gnu/libboost_python.so
-- USING PYTHON_LIBS: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Enabling SSE4 instructions
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - found
-- Using OpenBLAS's built in LAPACK
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/src/dlib/build
```

**Comment by davisking** [comment]
I have CMake setup to use dlib's built in LAPACK if an appropriate one
isn't found on the system.  However, it looks like it thinks your copy of
OpenBLAS has a good LAPACK but that's obviously not the case.  You can see
the cmake code that does this check here:
https://github.com/davisking/dlib/blob/master/dlib/cmake_find_blas.txt#L114
.

I tried this on my system, running Ubuntu 14.04 with libopenblas-base
installed and cmake correctly determined that openblas didn't have LAPACK
in it and used the one provided by the liblapack3 package and worked
properly.

I also just tried including the dormqr function in the cmake check but that
causes it to inappropriately fail to use the LAPACK in openblas when
openblas is compiled for cygwin.  So that's not the correct fix.  In any
case, I'm not able to reproduce this on any systems I have access to.  So
figuring out how to deal with this falls to you guys :)

**Comment by LiberiFatali** [comment]
I got this problem, too. I use Ubuntu 14.04 and build from lastest source.

**Comment by davisking** [comment]
What openblas package do you have installed?

**Comment by LiberiFatali** [comment]
I install OpenBLAS at /opt/OpenBlas. When I do:
```
$ grep OPENBLAS_VERSION /opt/OpenBLAS/include/openblas_config.h
```
==> 
```
#define OPENBLAS_VERSION " OpenBLAS 0.2.14 "
```

I got this problem with latest source. dlib 18.16 (https://github.com/davisking/dlib/releases/download/v18.16/dlib-18.16.tar.bz2) works well. Is there something between 18.16 and 18.18 or latest?

**Comment by davisking** [comment]
I didn't make any changes to how BLAS or LAPACK are linked or used between those versions so it doesn't seem like it should make a difference.  

How exactly did you install openblas?

**Comment by LiberiFatali** [comment]
For version 18.16, I use instructions from http://cmusatyalab.github.io/openface/setup/#by-hand to generate dlib.so

I compile OpenBLAS from source:

```
  sudo apt-get install build-essential gcc g++ gfortran git libgfortran3
  git clone https://github.com/xianyi/OpenBLAS.git
  cd OpenBLAS 
  make NO_AFFINITY=1 USE_OPENMP=1
  sudo make install
```

**Comment by davisking** [comment]
I just installed openblas in Ubuntu 14.04, compiled the dlib python bindings using cmake and Python 2.7.6, and was able to use the dlib.so file in python without issue.  What error do you get exactly?

**Comment by LiberiFatali** [comment]
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /usr/local/lib/python2.7/dist-packages/dlib-18.18.99-py2.7-linux-x86_64.egg/dlib/dlib.so: undefined symbol: dormqr_

**Comment by davisking** [comment]
Try removing the version of openblas you have installed and install it via `apt-get install libopenblas-dev`

**Comment by LiberiFatali** [comment]
I need this OpenBLAS for other frameworks. It works well until now. I also tried apt-get install libopenblas-dev and still get this error.

**Comment by davisking** [comment]
Well, I've done exactly what you said on my Ubuntu 14.04 system and it's working.  So I don't know what to tell you.  What does ldd say when you run it on the dlib.so file?  Also, try compiling the dlib unit tests in dlib/test using cmake and running the dtest executable that results.  Does it give you the same linker error?

**Comment by LiberiFatali** [comment]
I build new OpenBLAS 0.2.15 version from source, install it. Then I do ```sudo pip install dlib``` which install dlib 18.17. The error is gone when I do ```import dlib```

**Comment by davisking** [comment]
Ah, what version of openblas where you using?

**Comment by LiberiFatali** [comment]
It was OpenBLAS 0.2.14. 
Newest OpenBLAS (0.2.15) works well with dlib when I install dlib (18.17) using pip as above. However, there's still this error when I compile dlib 18.18 from source.

**Comment by LiberiFatali** [comment]
I figured out a fix for my case: adding a file to /etc/ld.so.conf.d/ called openblas.conf, containing the path to OpenBLAS libraries (/opt/OpenBLAS/lib), then run sudo ldconfig.

Now all version of dlib works well on my machine.

Thank you for your help :)

**Comment by davisking** [comment]
Ah yes, that would explain it.  :)

**Comment by sathiz91** [comment]
thanks!!that worked
