### ISSUE TITLE
recipe for target 'webcam_face_pose_ex' failed - I'm on Ubuntu 16.04 64 bit

### ISSUE THREAD

**Issue by Kacppian** [davisking/dlib#551]
//usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0: undefined reference to `g_type_check_instance_is_fundamentally_a'

//usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0: undefined reference to `g_type_class_adjust_private_offset'

collect2: error: ld returned 1 exit status

CMakeFiles/webcam_face_pose_ex.dir/build.make:122: recipe for target 'webcam_face_pose_ex' failed
make[2]: *** [webcam_face_pose_ex] Error 1
CMakeFiles/Makefile2:3471: recipe for target 'CMakeFiles/webcam_face_pose_ex.dir/all' failed
make[1]: *** [CMakeFiles/webcam_face_pose_ex.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I couldn't find a solution for this. Everything else compiles, it just breaks down at 98%.

**Comment by davisking** [comment]
Those errors aren't part of dlib.  You must have installed OpenCV wrong or one of OpenCV's dependencies is messed up, maybe part of libgstreamer.

**Comment by Kacppian** [comment]
I compiled that example separately from the examples directory and it worked. Any idea why?

**Comment by davisking** [comment]
No idea.  What folder you are in when you compile shouldn't matter at all.
