### ISSUE TITLE
DNN does only use 1 CPU

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#553]
Hi,
in my tests when i want to execute  dlib programm (for example imagenet) without gpu support.
The whole calculation only uses 1 processor (intel system).

Is it possible to use more the 1 processor ? And if so how ?

As always thanks a lot

**Comment by davisking** [comment]
If you install a multithreaded BLAS like the Intel MKL it will use multiple cores.

**Comment by VisionEp1** [comment]
I installed
Intel MKL (https://github.com/01org/MKL-DNN)
(and rebuild the dlib programm)

still the example imagenet programm uses only 1 core out of 4.

Do i have to link it somehow or use a specific cmake option?

**Comment by davisking** [comment]
That isn't the Intel-MKL.  MKL-DNN is something else.

**Comment by VisionEp1** [comment]
thanks, as always you solved the problem!
