### ISSUE TITLE
Compiler on vs2017

### ISSUE THREAD

**Issue by VictoryDong** [davisking/dlib#554]
Hi,
 I'm trying to compiler example of 'dnn_face_recognition_ex.cpp' on VS2017。But the day has passed, the compiler has been running, there is no error message, did not generate executable files.

**Comment by davisking** [comment]
Visual studio 2017 is buggy and hangs when it tries to compile some C++11 code, like the code in that example.  So you will have to use a different compiler.  Visual studio 2015 works, although it's not a great C++11 compiler either.
