### ISSUE TITLE
dlib image window problem

### ISSUE THREAD

**Issue by mohamaddanesh** [davisking/dlib#556]
Hi,
I have installed dlib(version 19.4.0) with python3.6. When I want to run a detector I get this problem:

```
win = dlib.image_window()
AttributeError: module 'dlib' has no attribute 'image_window'
```

I have macOS 10.12.4 and I have installed xquartz.

What should I do?

**Comment by davisking** [comment]
When cmake compiles dlib it will print messages about this.  They tell you what to do.

**Comment by mohamaddanesh** [comment]
I have installed dlib using pip. There is no cmake printed messages.
Any suggestions?

**Comment by davisking** [comment]
What messages are there?  Just saying "it doesn't work" tells us nothing.

**Comment by mohamaddanesh** [comment]
I run this in terminal:

`pip3 install dlib`

after it's done, there was nothing special printed in the terminal. It displays the following messages:

```
Collecting dlib
Installing collected packages: dlib
Successfully installed dlib-19.4.0
```

I haven't install it using cmake. Should I try cmake? or is there a solution?
