### ISSUE TITLE
OpenCV support in Python API

### ISSUE THREAD

**Issue by pkdogcom** [davisking/dlib#558]
The Python API doesn't seem to include OpenCV support of the C++ codes. One of my use case is to capture webcam video via OpenCV and perform object tracking with correlation tracker,  which can be achieved in C++ by converting Mat to array2d with cv_image.  However, there doesn't seem to have a Python binding for cv_image.

**Comment by davisking** [comment]
The python API just expects numpy arrays.  Make your images have the right format and it will work fine.  I'm pretty sure you can use OpenCV's python api to generate appropriately formatted numpy arrays so you don't need any special conversion from dlib.
