### ISSUE TITLE
Fails to find Cuda 8 on ubuntu 16.04

### ISSUE THREAD

**Issue by chris-hawley** [davisking/dlib#559]
I installed cuda 8 on ubuntu 16.04 and now i'm trying to install dlib. I've added cuda to path. it's located under /usr/local/cuda which is the standard install location for cuda8.

Output from cmake. 
`Could NOT find CUDA (missing:  CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found suitable version "8.0", minimum required is "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
`

I then deleted the folder and tried 
`cmake -DCMAKE_PREFIX_PATH=/usr/local/cuda ..`

Same message. I'm not quite sure what i'm doing wrong. OpenCV found my cuda install and i just re-cmaked that project to ensure nothing changed. Any thoughts?

**Comment by e-fominov** [comment]
http://stackoverflow.com/questions/19980412/how-to-let-cmake-find-cuda#comment29746097_19981506

**Comment by chris-hawley** [comment]
I already have that setup.

**Comment by e-fominov** [comment]
this is not a dlib issue. CMake's module FindCuda.cmake shows this error. Googling will help you

Reading this SO question and answers I see that you are trying to use CMAKE_PREFIX_PATH, while recommended way is cmake -D **CUDA_TOOLKIT_ROOT_DIR**=/usr/local/cuda-7.5 ..

Also good way installing CUDA is [downloading installer from NVidia website and running it](https://developer.nvidia.com/cuda-downloads)

And FindCuda.cmake module documentation is [here](https://cmake.org/cmake/help/v3.4/module/FindCUDA.html)

**Comment by davisking** [comment]
Yes, if you get cuda from the NVIDIA website it works as expected.

**Comment by chris-hawley** [comment]
I installed it through the nvidia repository.

**Comment by davisking** [comment]
Maybe reinstall cuda.  I use CUDA all the time on ubuntu 16.04 and cmake finds it without any special switches.  So it should work fine so long as your cuda install isn't messed up.

**Comment by chris-hawley** [comment]
Wait...I would like to point out that cuda 8 was found. However, the message clearly states that it wasn't. 

`**Could NOT find CUDA** (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (**found suitable version "8.0"**, minimum required is "7.5")`

Also, does CuDNN 6.0 work with Dlib?

**Comment by chris-hawley** [comment]
I installed cuda from the nvidia website and nothing changed.

**Comment by davisking** [comment]
Yes, you can use cuDNN 6.  That's what I use.

CMake messages are somewhat confusing.  They often say this kind of thing,
like "I found X! ...  oh wait, I didn't find X!" because some important
part of X turns up to be missing.

**Comment by chris-hawley** [comment]
I just tried rebuilding OpenCV with cuda support and it failed aswell. Although, There is a known issue with not finding thrust. I'm going to try installing cuda 7.5  and hope it works a bit better for me.

**Comment by chris-hawley** [comment]
installing cuda 7.5 allowed it build with cuda support.

**Comment by davisking** [comment]
Huh.  I use cuda 8 in ubuntu and it works fine.
