### ISSUE TITLE
Get a lot of error while compiling Dlib

### ISSUE THREAD

**Issue by XueXuehai** [davisking/dlib#56]
Hi,I want to build examples on mac using comment line "cmake --build ."but I got an error like this:
```
In file included from /Users/xxh/dlib/dlib/gui_widgets/fonts.cpp:14:
/Users/xxh/dlib/dlib/gui_widgets/nativefont.h:313:21: error: use of undeclared identifier
      'XAllocColor'
                    XAllocColor(d, cmap, &xcol);
                    ^
/Users/xxh/dlib/dlib/gui_widgets/nativefont.h:319:36: error: use of undeclared identifier
      'XmbTextExtents'; did you mean 'XTextExtents'?
                            return XmbTextExtents(fs, str, len, ink, logical);
                                   ^~~~~~~~~~~~~~
                                   XTextExtents
/Users/xxh/dlib/dlib/gui_widgets/nativefont.h:318:43: note: 'XTextExtents' declared here
                        inline static int XTextExtents (XFontSet fs, char *str, int len...
                                          ^
/Users/xxh/dlib/dlib/gui_widgets/nativefont.h:322:36: error: use of undeclared identifier
      'XwcTextExtents'; did you mean 'XTextExtents'?
                            return XwcTextExtents(fs, str, len, ink, logical);
                                   ^~~~~~~~~~~~~~
                                   XTextExtents
```

what's that mean?

**Comment by davisking** [comment]
Something is wrong with your X11 install since it's missing functions from
X11.  Did you install XQuartz?

**Comment by XueXuehai** [comment]
@davisking Yes,I have installed XQuartz.It seems that the identifier in X11 is different from that in /Users/xxh/dlib/dlib/gui_widgets/nativefont.h.

I reinstalled the XQuartz2.7.7.The error still exist.Should I use the older vision?

**Comment by davisking** [comment]
The older version of what?

**Comment by XueXuehai** [comment]
@davisking XQuartz

**Comment by davisking** [comment]
I doubt it.  It's probably finding another copy of X11 on your machine.  Other people have posted about anaconda installing a broken copy of the X11 headers on their machines.  Maybe that's the source of the trouble.

**Comment by XueXuehai** [comment]
@davisking yes,I once installed anaconda.And what can I do to fix it?

**Comment by davisking** [comment]
Uninstall anaconda?

**Comment by XueXuehai** [comment]
SORRY,maybe I didn't describe the problem clearly.
Firstly,using comment line "cmake --build ."and I got an error like this:
```
/Users/xxh/dlib/dlib/gui_widgets/nativefont.h:29:10: fatal error: 
'X11/Xlocale.h' file not found
```
Then, I find the Xlocale.h in /opt/X11/include/X11,and use " ln -s /opt/X11/include/X11 /usr/local/include/X11" in terminal.
Last,run the "cmake --build ." and got the MORE error above.

**Comment by XueXuehai** [comment]
I uninstall anaconda using "rm -rf ~/anaconda".
it's run successfully.
Thanks a lot.

**Comment by davisking** [comment]
No problem

**Comment by jacobyan** [comment]
@davisking   Thanks a lot, finally it works after uninstalling anaconda,  it has confused me several days.
