### ISSUE TITLE
No Module Named "image_window"

### ISSUE THREAD

**Issue by haow85** [davisking/dlib#560]
When I tried to run "python correlation_tracker.py" in the python_example folder, I got the following error:

`appledeMacBook-Pro-5:python_examples apple$ python correlation_tracker.py 
Traceback (most recent call last):
  File "correlation_tracker.py", line 53, in <module>
    win = dlib.image_window()
AttributeError: 'module' object has no attribute 'image_window'`

How to fix it ?

**Comment by e-fominov** [comment]
This require compiling dlib with GUI support. You need to recompile dlib. Check this answers too:

https://sourceforge.net/p/dclib/discussion/442518/thread/e593cf63/#218f

http://lmgtfy.com/?q=dlib+macos+x11+gui+python
