### ISSUE TITLE
Where is the built video_tracking_ex example ?

### ISSUE THREAD

**Issue by haow85** [davisking/dlib#561]
I built the C++ examples using 

`mkdir build; cd build; cmake .. ; cmake --build .`

but I couldn't find the compiled video_tracking_ex.cpp file in the build folder. Where is this example ?

**Comment by e-fominov** [comment]
This is because video_tracking_ex examle require GUI support. Check CMake messages about GUI/X11 - and you will find the problems. You will need X11 library on Linux machines
