### ISSUE TITLE
How to improve face landmark detection

### ISSUE THREAD

**Issue by salos1982** [davisking/dlib#562]
I compiled example face_landmark_detection_ex and found that it takes quite a lot of time to detect face landmarks. about 370ms for image 1491*1914 on Core i7 3770K with AVX instructions. It is too much.
Possibly I need to add some configuration (openCV or whatever).
Mainly I have only one face on photo probably it is possible optimization for that.
 Also I do not need all landmarks in a time. Probably I can detect only lips or eyes.

**Comment by e-fominov** [comment]
This example does face detection + face landmark detection. And most of time (i think about 360 ms from this 370) is spent on face detection stage
Try removing pyramid_up function call and reduce the image resolution. 320x240 image is enough for face detection and landmarks, but if face is small or there are many small faces on this 3MP image - this is up to you how to choose the ROI and reduce image resolution

Also check this: http://dlib.net/faq.html#Whyisdlibslow

**Comment by salos1982** [comment]
Thanks for quick reply. This test was done without  pyramid_up function. Is it possible to detect face for reduced image (320*240) and then scale region with face to initial image and find landmarks on initial image.

**Comment by e-fominov** [comment]
>  Is it possible to detect face for reduced image (320*240) and then scale region with face to initial image and find landmarks on initial image.

Just use some kind of affine transform to map into original resolution:

original width = 1000
resized width = 100
K = 100 / 1000 = 0.1
detected rect left = 10
map to original: left / K = 100

after rectangle is mapped this is up to you - you can run shape_predictor on original image or on resized one. and the landmark points can be mapped same way as the rect coordinates

and one more tip: greyscale images will work faster and will detect same amount of faces

**Comment by salos1982** [comment]
ooo thank you very much.
