### ISSUE TITLE
net forward in dnn face recognition is slow

### ISSUE THREAD

**Issue by msobhan69** [davisking/dlib#568]
When I use dlib-net(img) to embed vector , the time it took when embedding 1 image on Windows OS (visual studio 2015) it took 0.4s.
I use AVX and Blas library(mkl) in release mode. I think it should be real-time

**Comment by e-fominov** [comment]
There are no official benchmarks that can tell us if this time is small or big. Also performance depends on processor, RAM, library versions... Have you compared this time with other DNN libraries (Caffe, Torch, Tensorflow...) on the same machine/compiler/OS? Do you have GPU?

Do you think if there is a bug in Dlib? 

I think you can make some minimal-code example and somebody will be able to run it on his machine and compare the time

In any case you are welcome to provide PR's that can make library better

**Comment by msobhan69** [comment]
Tank you @e-fominov , 
The system: intel core i7-6700k 4.00 GHz, 16G RAM, windows10 64bit, no GPU.
I read your comment in https://github.com/davisking/dlib/issues/517 about DNN CPU speed, you said "the main hint is to use BLAS libraries (OpenBLAS/MKL) - CPU DNN module performance increases about 20x".
There is no deference when I run net() (in face recognition example) without Intel MKL and with Intel MKL.

**Comment by e-fominov** [comment]
I was testing on different network structure with MinGW 6.3 + single-threaded OpenBLAS on SandyBridge i7. After adding OpenBLAS CPU DNN timings reduced very much. You can try this compiler and Blas library
I am not working with Visual Studio anymore and never tried MKL. May be there are some options that can fine-tune MKL to work faster

And the main question - is MKL really used at runtime? Because 400 ms is the time I expect on your configuration without any BLAS
I recommend you to test
a) MSVC Without BLAS
b) MSVC  With MKL
c) MSVC + OpenBLAS
d) MinGW  with no BLAS
e) MinGW + OpenBLAS

Then we can discuss your results

And make sure that BLAS is single-threaded to make measurements compareable

**Comment by davisking** [comment]
If you are getting the same timings with and without BLAS then you are
definitely actually not using BLAS at all.  You can see in the cmake
output, or in the compiler settings if you look, if BLAS is being used.

**Comment by msobhan69** [comment]
@e-fominov I will do you recommendations and report results here.
@davisking I see in the cmake entries:
The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
C++11 activated.
Searching for BLAS and LAPACK
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of void*
Check size of void* - done
**Found Intel MKL BLAS/LAPACK library**
Looking for cblas_ddot
Looking for cblas_ddot - found
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
*** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
*** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
Configuring done

**Comment by davisking** [comment]
Huh.  Are you sure you are timing just the neural network part of the code?  Not the whole program or parts of the data loading or face detection?

**Comment by msobhan69** [comment]
Dear @davisking Yes, I'm sure.
begin = clock();
face_descriptor = net(face);
end = clock();
elapsed_secs = double(end - begin) / CLOCKS_PER_SEC;
cout<<elapsed_secs<<endl;

**Comment by e-fominov** [comment]
@msobhan69 , we need full source code for testing. Here Christopher made code for ARM testing but different function. better to have code with no file reading/writing

https://gist.github.com/bakercp/157573d1e27eec5f6fe4467c98477aa7

this is from #557 

So If you can make something like this with detailed timings - we can try to make Dlib faster

**Comment by msobhan69** [comment]
I guess the problem is The DLIB_USE_BLAS and DLIB_USE_LAPACK are not define in visual studio Preprocessor Definition. But now, I have many errors in run time:
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGESVD.
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGESVD.
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGESVD.
...
...
...
...
Intel MKL ERROR: Parameter 13 was incorrect on entry to DGESVD.
Intel MKL ERROR: Parameter 9 was incorrect on entry to cblas_dgemm.

**Comment by davisking** [comment]
Huh.  Something is going wrong in the cmake setup and it's not setting the compiler options it's supposed to.  What version of cmake and dlib are you using?

**Comment by msobhan69** [comment]
Dear @davisking @e-fominov , I found my mistake. After adding DLIB_USE_BLAS and DLIB_USE_LAPACK in visual studio Preprocessor Definition, I set Use Intel MKL to Parallel in visual studio Common Properties in my project, so there is no problem anymore. Dlib-net() is running in real time (0.02s), now.

**Comment by e-fominov** [comment]
Now we know how fast it should be :)  So looks like no additional changes in Dlib required

**Comment by davisking** [comment]
Well, cmake should have set it correctly the first time.  Maybe something is different about a new cmake or MKL, but when I have tested cmake here it correctly sets these things without the user needing to do anything, which is how I intend it to work.  

So what versions of dlib and cmake are you using?  Did you make any changes to the CMakeLists.txt file or anything else?

**Comment by msobhan69** [comment]
Dear @davisking You are right, it correctly sets these things without the user needing to do anything, but I build dlib and use it's lib in new project. So, everything is ok about cmake and dlib.

**Comment by davisking** [comment]
Ah, you should have mentioned that :)
