### ISSUE TITLE
Can't run example code in Xcode using webcam_face_pose_ex.cpp?

### ISSUE THREAD

**Issue by XueXuehai** [davisking/dlib#57]
The error like this:
```
Undefined symbols for architecture x86_64:
  "_USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives", referenced from:
      _dlib_check_consistent_assert_usage in main.o
  "dlib::base_window::invalidate_rectangle(dlib::rectangle const&)", referenced from:
      void dlib::image_display::set_image<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&) in main.o
  "dlib::base_window::set_size(int, int)", referenced from:
      void dlib::image_window::set_image<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&) in main.o
  "dlib::image_window::add_overlay(std::__1::vector<dlib::image_display::overlay_line, std::__1::allocator<dlib::image_display::overlay_line> > const&)", referenced from:
      _main in main.o
  "dlib::image_window::clear_overlay()", referenced from:
      _main in main.o
  "dlib::image_window::image_window()", referenced from:
      _main in main.o
  "dlib::image_window::~image_window()", referenced from:
      _main in main.o
  "dlib::popup_menu_region::disable()", referenced from:
      void dlib::image_display::set_image<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&) in main.o
  "dlib::scrollable_region::set_total_rect_size(unsigned long, unsigned long)", referenced from:
      void dlib::image_display::set_image<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&) in main.o
  "dlib::draw_sunken_rectangle(dlib::canvas const&, dlib::rectangle const&, unsigned char)", referenced from:
      dlib::scrollable_region_style_default::draw_scrollable_region_border(dlib::canvas const&, dlib::rectangle const&, bool) const in main.o
  "dlib::entropy_decoder_kernel_2::get_target(unsigned int)", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in main.o
      dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&) in main.o
  "dlib::entropy_decoder_kernel_2::set_stream(std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in main.o
  "dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in main.o
      dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>::decode(unsigned long&) in main.o
  "dlib::entropy_decoder_kernel_2::entropy_decoder_kernel_2()", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in main.o
  "dlib::entropy_decoder_kernel_2::~entropy_decoder_kernel_2()", referenced from:
      dlib::compress_stream_kernel_1<dlib::entropy_encoder_model_kernel_5<257ul, dlib::entropy_encoder_kernel_2, 200000ul, 4ul>, dlib::entropy_decoder_model_kernel_5<257ul, dlib::entropy_decoder_kernel_2, 200000ul, 4ul>, dlib::crc32>::decompress(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in main.o
  "dlib::base64::base64()", referenced from:
      dlib::get_serialized_frontal_faces() in main.o
  "dlib::base64::~base64()", referenced from:
      dlib::get_serialized_frontal_faces() in main.o
  "dlib::base_window::is_closed() const", referenced from:
      _main in main.o
  "dlib::image_display::get_image_display_rect() const", referenced from:
      void dlib::image_window::set_image<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&) in main.o
  "dlib::base64::decode(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const", referenced from:
      dlib::get_serialized_frontal_faces() in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
did I missing some *.dylib?I did not find dylib file about dlib.

**Comment by davisking** [comment]
Did you make the project using cmake?

**Comment by XueXuehai** [comment]
@davisking yes，I used the commend "mkdir build; cd build; cmake .. ; cmake --build ." in README.and I can run the project  with  "./webcam_face_pose_ex" in commend line.

**Comment by willard-yuan** [comment]
@XueXuehai I also faced a similar problem when I compiled a project in Xcode without cmake. After for a few tries I have compiled it successfully. Here is the steps which may help you:

1). Make sure you have compiled the examples in dlib by using cmake. If it throws some errors related with **X11** (I faced the problem once), download the [**XQuartz**](http://www.xquartz.org/) and install it. Then make a link with the following command:

```sh
ln -s /opt/X11/include/X11 /usr/local/include/X11
```
Then recompiled the **dlib**, and you will compiled it successfully.

2). Make sure you have added the `/usr/local/include` and `dlib-18.18` to the Header search paths, and `/usr/local/lib` to the Library search paths in your project when you use the **dlib**. Then remember to add the `*.dylib` of `/usr/X11/lib` to your project. If all is done, just compile it and it will be successful.

The configure in my Xcode is as follows:
<img width="850" alt="screen shot 2015-11-16 at 22 16 45" src="https://cloud.githubusercontent.com/assets/5379711/11184129/dc816b44-8cb0-11e5-9524-f867ff6e54be.png">
<img width="259" alt="screen shot 2015-11-16 at 22 16 58" src="https://cloud.githubusercontent.com/assets/5379711/11184128/dc80ce64-8cb0-11e5-8b12-a88a77f49b15.png">

 I hope this helps and good luck with everything!

**Comment by XueXuehai** [comment]
@willard-yuan Oh,I forgot to add `/usr/X11/lib`

Thanks!

**Comment by JohnSolstice** [comment]
@XiaXuehai @willard-yuan I know I'm a little late to this conversation, but I'm having the same issue.  When you say to add `dlib-18.18` to the search path, I'm not sure what `dlib-18.18` is.  Is it just the /dlib/dlib folder?

**Comment by davisking** [comment]
http://dlib.net/compile.html

**Comment by JohnSolstice** [comment]
@davisking oh, I got it working now.  I was compiling through CLion (which uses the same version of cmake that I used on the command line) but for some reason it just wasn't working with that.

**Comment by JohnSolstice** [comment]
@davisking So that issue is fixed, but now I'm getting a new error.  I'm not sure if this is the correct place to ask about this, but the error looks fairly similar to the other one.

`Undefined symbols for architecture x86_64:
  "dlib::base_window::invalidate_rectangle(dlib::rectangle const&)", referenced from:
      void dlib::image_display::set_image<dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > const&) in main.cpp.o
  "dlib::base_window::set_size(int, int)", referenced from:
      void dlib::image_window::set_image<dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > const&) in main.cpp.o
  "dlib::image_window::add_overlay(std::__1::vector<dlib::image_display::overlay_rect, std::__1::allocator<dlib::image_display::overlay_rect> > const&)", referenced from:
      void dlib::image_window::add_overlay<dlib::rgb_pixel>(std::__1::vector<dlib::rectangle, std::__1::allocator<dlib::rectangle> > const&, dlib::rgb_pixel) in main.cpp.o
  "dlib::image_window::clear_overlay()", referenced from:
      _main in main.cpp.o
  "dlib::image_window::image_window()", referenced from:
      _main in main.cpp.o
  "dlib::image_window::~image_window()", referenced from:
      _main in main.cpp.o
  "dlib::popup_menu_region::disable()", referenced from:
      void dlib::image_display::set_image<dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > const&) in main.cpp.o
  "dlib::scrollable_region::set_total_rect_size(unsigned long, unsigned long)", referenced from:
      void dlib::image_display::set_image<dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > const&) in main.cpp.o
  "dlib::draw_sunken_rectangle(dlib::canvas const&, dlib::rectangle const&, unsigned char)", referenced from:
      dlib::scrollable_region_style_default::draw_scrollable_region_border(dlib::canvas const&, dlib::rectangle const&, bool) const in main.cpp.o
  "dlib::image_display::get_image_display_rect() const", referenced from:
      void dlib::image_window::set_image<dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::array2d<unsigned char, dlib::memory_manager_stateless_kernel_1<char> > const&) in main.cpp.o
ld: symbol(s) not found for architecture x86_64`

Any idea what I could be missing?  (I'm on OSX btw)

**Comment by davisking** [comment]
You aren't following the instructions on http://dlib.net/compile.html

**Comment by JohnSolstice** [comment]
@davisking You're right, it's working when following the instructions exactly.
