### ISSUE TITLE
Unexpected version found while deserializing dlib::input_rgb_image_sized

### ISSUE THREAD

**Issue by anguoyang** [davisking/dlib#575]
hi@davisking, when i used the model generated by  dnn_metric_learning_on_images_ex, and replace/rename into dlib_face_recognition_resnet_model_v1.dat for dnn_face_recognition_ex, i got this error:
------------------------
Unexpected version found while deserializing dlib::input_rgb_image_sized
---------------
it worked when i used the original .dat file, so it is because of the model file. it is really strange, as the .dat file is only a model file, however the error message is about image size.

my pc is in ubuntu 16.04 with cuda/cudnn, all things are ok during building, and i use the default johns images for training.

**Comment by davisking** [comment]
The input layers are different.  That's what the error is telling you.  They have to be the same.

**Comment by GoldenAbel** [comment]
@davisking 
Hi, I use the script  "dnn_metric_learning_on_images_ex.cpp" and load the pretrained model:
    deserialize("dlib_face_recognition_resnet_model_v1.dat") >> net;
   also, i have resize the image by add a line code as below:
   for (size_t j = 0; j < samples_per_id; ++j)
        {
            const auto& obj = objs[id][rnd.get_random_32bit_number()%objs[id].size()];
            load_image(image, obj);

            image.set_size(150, 150);

            images.push_back(std::move(image));
            labels.push_back(id);
        }
 i get an error: 
 terminate call after throwing an instance of 'dlib::serialization_error'
 what(): unexpected version found while deserializing dlib::input_rgb_image.

**Comment by sorenchiron** [comment]
I think it is the word "version" that stops some programmers from reading the rest of the error message.
I myself fell into dlib version checking for quite a while...

**Comment by anguoyang** [comment]
@sorenchiron I am still puzzling on this:)
does it mean that I need to change this:
input_rgb_image_sized<150>
into:
input_rgb_image_sized<"size of my training images">
?

**Comment by davisking** [comment]
You can't just change the network definition and then deserialize a model
that uses a different network.  That's what the error is telling you.

**Comment by anguoyang** [comment]
@davisking thank you.
another problem, I have used vgg face for metric learning, it finished in few minutes, I am not sure if it is correct or not, as there is only these logs, no more information:
objs.size(): 8631
done training
num_right: 250
num_wrong: 50

**Comment by anguoyang** [comment]
@davisking I found a strange problem on training:
1.If I run the dnn_metric_learning_on_images_ex vgg(I used aligned vgg face dataset and cropped all images into the same size) in command line, then it will generate the above message
2.However, if I run it in visual studio(in debug mode), then it is OK
I have checked the param(only 1 parameter) and visual studio configuration, there is no difference, it is really strange.

**Comment by anguoyang** [comment]
by the way, the problem of this issue has been solved, just as you said, I need to set the network definition same with training, thank you.
But the accuracy is not as good as your model

**Comment by arunxz98** [comment]
hey @anguoyang can you please elaborate how you solved this problem? i'm trying to explore Dlib,  and this would be of great help.

**Comment by wangx404** [comment]
> by the way, the problem of this issue has been solved, just as you said, I need to set the network definition same with training, thank you.
> But the accuracy is not as good as your model

Hi, could you tell me how you solve this problem? Change the image size in `dnn_metric_learning_on_images_ex` ? If so, which size should I use? Thank you.

**Comment by wangx404** [comment]
I find the solution in another issue. Anyway, thanks.

**Comment by wzh52112** [comment]
> 

Can you tell me how it was solved? I urgently need to train a model with dlib now.
