### ISSUE TITLE
Is NEON available on Android? 

### ISSUE THREAD

**Issue by gicheonkang** [davisking/dlib#576]
Hi, I'm using dlib with android.
I'm trying my best to boost up the speed of face detection using dlib.

I read almost of the optimization issue posted in this repository like [157](https://github.com/cmusatyalab/openface/issues/157) 

To optimize the application, I tried the most of the suggestion which can be changed in app
(resizing, grayscale, ...). **Mean FPS : 9~10**.

If available, I wanna use ARM-NEON. Does anybody how to compile it with .so format ?
**I'm using cortex-a53 chipset**

**Comment by e-fominov** [comment]
Dlib now supports NEON. You can try it with latest Dlib source code from git
To enable NEON support in compiler, put "-mfpu=neon" as compiler flag

**Comment by gicheonkang** [comment]
@e-fominov Thank you for your reply. 
You mean type `cmake .. -DCMAKE_CXX_FLAGS="-mfpu=neon"` ?
Neon is different with parallel computing technics?

@fastfastball
How did you build it with neon support using [dlib-android](https://github.com/tzutalin/dlib-android) ?
can you give any specifics?

**Comment by 9crk** [comment]
arm64-v8a support neon by default.
if you use armeabi,then you should add neon support by hand.
