### ISSUE TITLE
matrix<float,0,1> set element 

### ISSUE THREAD

**Issue by hardjob** [davisking/dlib#577]
What is the equivalent of std::vector::push_back() , in matrix<float,0,1>
I tried M(i) = xx,xx , but the program crash and i get "Segmentation fault (core dumped)"

**Comment by e-fominov** [comment]
This is not an issue of dlib, use instructions from  [examples](http://dlib.net/matrix_ex.cpp.html)   and  [Stackoverflow for support](http://stackoverflow.com/questions/43821261/dlib-matrixfloat-0-1-set-element) is recommended
