### ISSUE TITLE
SefFault on module import in Python

### ISSUE THREAD

**Issue by guribe94** [davisking/dlib#58]
I compiled the python bindings using the included setup.py file (`python setup.py install`). It seemed to compile fine but when I import the module to the python interpreter it causes a segfault. How should I go about troubleshooting this? I attached the output of the setup file below

┌[user@dyn-160-39-234-85] [/dev/ttys000] [master ⚡] [1]
└[~/Devspace/dlib]> sudo python setup.py install    
running install
running bdist_egg
running build
Detected Python architecture: 64bit
Removing build directory /Users/gabriel/Devspace/dlib/./tools/python/build
Configuring cmake ...
-- The C compiler identification is AppleClang 7.0.0.7000176
-- The CXX compiler identification is AppleClang 7.0.0.7000176
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2.6")
-- USING BOOST_LIBS: /usr/local/lib/libboost_python-mt.dylib
-- USING PYTHON_LIBS: /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
-- Enabling SSE4 instructions
 *****************************************************************************
 *** DLIB GUI SUPPORT DISABLED BECAUSE X11 DEVELOPMENT LIBRARIES NOT FOUND ***
 *** Make sure XQuartz is installed if you want GUI support.               ***
 *** You can download XQuartz from: http://xquartz.macosforge.org/landing/ ***
 *****************************************************************************
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found LAPACK library
-- Found CBLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring done
-- Generating done
Build using cmake ...
Scanning dependencies of target dlib
[  0%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.o
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.o
[  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.o
[  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.o
[  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.o
[  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.o
[  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.o
[  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.o
[  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.o
[ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.o
[ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.o
[ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.o
[ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.o
[ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.o
[ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.o
[ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.o
[ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.o
[ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.o
[ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.o
[ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.o
[ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.o
[ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.o
[ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.o
[ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.o
[ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.o
[ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.o
[ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.o
[ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.o
[ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.o
[ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.o
[ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.o
[ 32%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.o
[ 33%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.o
[ 34%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.o
[ 35%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.o
[ 36%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.o
[ 37%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.o
[ 38%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.o
[ 39%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcomapi.o
[ 40%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapimin.o
[ 41%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapistd.o
[ 42%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatasrc.o
[ 43%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcoefct.o
[ 44%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcolor.o
[ 45%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jddctmgr.o
[ 46%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdhuff.o
[ 47%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdinput.o
[ 48%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmainct.o
[ 49%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmarker.o
[ 50%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmaster.o
[ 50%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmerge.o
[ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdphuff.o
[ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdpostct.o
[ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdsample.o
[ 54%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jerror.o
[ 55%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctflt.o
[ 56%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctfst.o
[ 57%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctint.o
[ 58%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctred.o
[ 59%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemmgr.o
[ 60%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemnobs.o
[ 61%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant1.o
[ 62%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant2.o
[ 63%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jutils.o
[ 64%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapimin.o
[ 65%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatadst.o
[ 66%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcparam.o
[ 67%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapistd.o
[ 68%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmarker.o
[ 69%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcinit.o
[ 70%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmaster.o
[ 71%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcdctmgr.o
[ 72%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccoefct.o
[ 73%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccolor.o
[ 74%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jchuff.o
[ 75%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmainct.o
[ 75%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcphuff.o
[ 76%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcprepct.o
[ 77%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcsample.o
[ 78%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctint.o
[ 79%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctflt.o
[ 80%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctfst.o
[ 81%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.o
[ 82%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.o
[ 83%] Linking CXX static library libdlib.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(stack_trace.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(stack_trace.o) has no symbols
[ 83%] Built target dlib
Scanning dependencies of target dlib_
[ 84%] Building CXX object CMakeFiles/dlib_.dir/src/dlib.cpp.o
[ 85%] Building CXX object CMakeFiles/dlib_.dir/src/matrix.cpp.o
[ 86%] Building CXX object CMakeFiles/dlib_.dir/src/vector.cpp.o
[ 87%] Building CXX object CMakeFiles/dlib_.dir/src/svm_c_trainer.cpp.o
[ 88%] Building CXX object CMakeFiles/dlib_.dir/src/svm_rank_trainer.cpp.o
[ 89%] Building CXX object CMakeFiles/dlib_.dir/src/decision_functions.cpp.o
[ 90%] Building CXX object CMakeFiles/dlib_.dir/src/other.cpp.o
[ 91%] Building CXX object CMakeFiles/dlib_.dir/src/basic.cpp.o
[ 92%] Building CXX object CMakeFiles/dlib_.dir/src/cca.cpp.o
[ 93%] Building CXX object CMakeFiles/dlib_.dir/src/sequence_segmenter.cpp.o
[ 94%] Building CXX object CMakeFiles/dlib_.dir/src/svm_struct.cpp.o
[ 95%] Building CXX object CMakeFiles/dlib_.dir/src/image.cpp.o
[ 96%] Building CXX object CMakeFiles/dlib_.dir/src/rectangles.cpp.o
[ 97%] Building CXX object CMakeFiles/dlib_.dir/src/object_detection.cpp.o
[ 98%] Building CXX object CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o
[ 99%] Building CXX object CMakeFiles/dlib_.dir/src/correlation_tracker.cpp.o
[100%] Linking CXX shared library dlib.so
[100%] Built target dlib_
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/gabriel/Devspace/dlib/tools/python/../../python_examples/dlib.so
Populating the distribution directory /Users/gabriel/Devspace/dlib/./dist/dlib ...
Copying file /Users/gabriel/Devspace/dlib/./python_examples/correlation_tracker.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/correlation_tracker.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/dlib.so -> /Users/gabriel/Devspace/dlib/./dist/dlib/dlib.so.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/face_detector.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/face_detector.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/face_landmark_detection.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/face_landmark_detection.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/find_candidate_object_locations.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/find_candidate_object_locations.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/LICENSE_FOR_EXAMPLE_PROGRAMS.txt -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/LICENSE_FOR_EXAMPLE_PROGRAMS.txt.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/max_cost_assignment.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/max_cost_assignment.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/sequence_segmenter.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/sequence_segmenter.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/svm_rank.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/svm_rank.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/svm_struct.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/svm_struct.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/train_object_detector.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/train_object_detector.py.
Copying file /Users/gabriel/Devspace/dlib/./python_examples/train_shape_predictor.py -> /Users/gabriel/Devspace/dlib/./dist/dlib/examples/train_shape_predictor.py.
running build_py
creating build
creating build/lib.macosx-10.11-x86_64-2.7
creating build/lib.macosx-10.11-x86_64-2.7/dlib
copying dist/dlib/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/dlib
running egg_info
creating dist/dlib.egg-info
writing dist/dlib.egg-info/PKG-INFO
writing top-level names to dist/dlib.egg-info/top_level.txt
writing dependency_links to dist/dlib.egg-info/dependency_links.txt
writing manifest file 'dist/dlib.egg-info/SOURCES.txt'
reading manifest file 'dist/dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '**' found under directory 'dlib/build'
warning: no files found matching '*.bat' under directory 'python_examples'
warning: no previously-included files matching '**' found under directory 'python_examples/build'
writing manifest file 'dist/dlib.egg-info/SOURCES.txt'
copying dist/dlib/dlib.so -> build/lib.macosx-10.11-x86_64-2.7/dlib
creating build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/LICENSE_FOR_EXAMPLE_PROGRAMS.txt -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/correlation_tracker.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/face_detector.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/face_landmark_detection.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/find_candidate_object_locations.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/max_cost_assignment.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/sequence_segmenter.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/svm_rank.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/svm_struct.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/train_object_detector.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
copying dist/dlib/examples/train_shape_predictor.py -> build/lib.macosx-10.11-x86_64-2.7/dlib/examples
running build_ext
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
creating build/bdist.macosx-10.11-x86_64
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/dlib
copying build/lib.macosx-10.11-x86_64-2.7/dlib/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/dlib
copying build/lib.macosx-10.11-x86_64-2.7/dlib/dlib.so -> build/bdist.macosx-10.11-x86_64/egg/dlib
creating build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/correlation_tracker.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/face_detector.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/face_landmark_detection.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/find_candidate_object_locations.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/LICENSE_FOR_EXAMPLE_PROGRAMS.txt -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/max_cost_assignment.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/sequence_segmenter.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/svm_rank.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/svm_struct.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/train_object_detector.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
copying build/lib.macosx-10.11-x86_64-2.7/dlib/examples/train_shape_predictor.py -> build/bdist.macosx-10.11-x86_64/egg/dlib/examples
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/correlation_tracker.py to correlation_tracker.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/face_detector.py to face_detector.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/face_landmark_detection.py to face_landmark_detection.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/find_candidate_object_locations.py to find_candidate_object_locations.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/max_cost_assignment.py to max_cost_assignment.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/sequence_segmenter.py to sequence_segmenter.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/svm_rank.py to svm_rank.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/svm_struct.py to svm_struct.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/train_object_detector.py to train_object_detector.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/examples/train_shape_predictor.py to train_shape_predictor.pyc
creating stub loader for dlib/dlib.so
byte-compiling build/bdist.macosx-10.11-x86_64/egg/dlib/dlib.py to dlib.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying dist/dlib.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying dist/dlib.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying dist/dlib.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying dist/dlib.egg-info/not-zip-safe -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying dist/dlib.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/dlib-18.18.99-py2.7-macosx-10.11-x86_64.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing dlib-18.18.99-py2.7-macosx-10.11-x86_64.egg
removing '/usr/local/lib/python2.7/site-packages/dlib-18.18.99-py2.7-macosx-10.11-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/dlib-18.18.99-py2.7-macosx-10.11-x86_64.egg
Extracting dlib-18.18.99-py2.7-macosx-10.11-x86_64.egg to /usr/local/lib/python2.7/site-packages
dlib 18.18.99 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/dlib-18.18.99-py2.7-macosx-10.11-x86_64.egg
Processing dependencies for dlib==18.18.99
Finished processing dependencies for dlib==18.18.99

**Comment by davisking** [comment]
I don't have a mac so I can't debug this.  However, dlib users post all the
time about difficulty building the python bindings on mac and it's
invariably because they have multiple incompatible versions of python
installed.  For example, maybe boost python is not compiled to use the
version of python you are using.  Or maybe you compiled dlib for a home
brew version of python but are using it with the system installed python.

**Comment by KGOURAV** [comment]
hey davis my raspberry pi has built till this **Building CXX object CMakeFiles/dlib_.dir/src/svm_c_trainer.cpp.o**  then its not proceeding further
