### ISSUE TITLE
Error while checking test_for_cuda

### ISSUE THREAD

**Issue by axmadjon** [davisking/dlib#581]
I wanted to check on the presence of whether I can compile "dlib" to "cuda" but this error occurs

![2017-05-10 12-28-12](https://cloud.githubusercontent.com/assets/6769854/25887847/2c760ad0-357d-11e7-8aa1-d03be0df6625.png)
![2017-05-10 12-28-30](https://cloud.githubusercontent.com/assets/6769854/25887853/31998460-357d-11e7-93ac-8e62021c3a2c.png)
![2017-05-10 12-28-35](https://cloud.githubusercontent.com/assets/6769854/25887854/33ee89ae-357d-11e7-9ff2-8eb01948789a.png)

If you make such an error without checking

![1](https://cloud.githubusercontent.com/assets/6769854/25887893/5c800a50-357d-11e7-843c-02c1926bb3f2.png)
![2](https://cloud.githubusercontent.com/assets/6769854/25887895/621d2d1c-357d-11e7-8eb8-dd9732a3cf46.png)
![3](https://cloud.githubusercontent.com/assets/6769854/25887903/6ae75224-357d-11e7-874e-7917c62b19ee.png)

How can I fix it please help me how to compile "dlib" with "cuda"

Axmadjon Xamidov
axmadjon.xamidov@gmail.com

**Comment by davisking** [comment]
Don't post screen shots.  

Also, these don't look like dlib errors.  Your cuda install or compiler or something about your OS is just busted.
