### ISSUE TITLE
It seems that the VS version is wrong

### ISSUE THREAD

**Issue by GaspardQin** [davisking/dlib#582]
in line 61 of _use_cpp_11.cmake_

> elseif(MSVC AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19.0.24215.1 ) 
   message(STATUS "NOTE: Visual Studio didn't have good enough C++11 support until Visual Studio 2015 update 3 (v19.0.24215.1)")
   message(STATUS "So we aren't enabling things that require full C++11 support (e.g. the deep learning tools).")
   message(STATUS "Also, be aware that Visual Studio's version naming is confusing, in particular, there are multiple versions of 'update 3'")
   message(STATUS "So if you are getting this message you need to update to the newer version of Visual Studio to use full C++11.")
   set(USING_OLD_VISUAL_STUDIO_COMPILER 1)
else()  

If i am not wrong, the correct Version seems to be 14.0.24215.1 ?
Thanks

**Comment by davisking** [comment]
Why do you think this?

**Comment by GaspardQin** [comment]
Because Visual Studio 2015 means the version 14?

**Comment by davisking** [comment]
No.  Run cmake and see what happens.
