### ISSUE TITLE
Limiting the number of pyramid levels in input_rgb_image_pyramid ?

### ISSUE THREAD

**Issue by grochefort** [davisking/dlib#584]
Mainly for performances, I would like to limit the scale space where to look for object detection. For example, I know for sure than images smaller than the size of the detector is a waste of time to look for.

The input_rgb_image_pyramid class (::to_tensor) relies on create_tiled_pyramid to create the multiresolution pyramidal image. Unfortunately, none of them expose a parameter to control the number of levels. 
create_tiled_pyramid uses a hardcoded value of 5 pixels to end, should that value be exposed as parameter of the function or is there another better idea to do this ?

Thanks.

**Comment by davisking** [comment]
You should try it and see what happens.  I think you will find it hardly effects performance.  If you pop one of the tiled images on the screen you will see that the vast majority of the pyramid layers are packed into the image in a way that don't add any additional pixels to be processed.  So removing them won't make the DNN processing faster, which is the bulk of the computation.

**Comment by grochefort** [comment]
I tried. I was not thinking to just remove one or two layers but keeping a few. 
To get a decent improvement, I guess you have to reduce the packed layers image size, which will only happen if more than half the layers are discarded.
It is a very specific context, I agree, where I am only checking a few scales with a resize factor between 0.8 and 0.9. Using MKL with CPU only, I finally decreased the computation time by 30-50% on average without impacting object detection accuracy.

**Comment by davisking** [comment]
Right, you have to remove a whole lot of the pyramid layers.  You might even be better off turning the pyramid into a mini-batch and running it that way.  For instance, if you only ran 3 different image scales I wouldn't be surprised if it runs faster by packing the pyramid layers into different samples in a tensor rather than in one big image.
