### ISSUE TITLE
usage dlib/http_client/http_client.cpp

### ISSUE THREAD

**Issue by vinnitu** [davisking/dlib#585]
I need before load_image() download file by url
I see dlib/http_client/http_client.cpp but seems it is not public/(not used?)

What is you proposition to load_image from net?

**Comment by davisking** [comment]
Right, that thing isn't really used.  It was added to dlib a long time ago and never really got finished.  There are a lot of ways to get files from HTTP, I would try whatever you find convenient.  Just forming the HTTP text yourself is pretty easy and what I usually do.
