### ISSUE TITLE
Much smaller shape model size compared to the shape_predictor_68_face_landmarks.dat as provided by Dlib

### ISSUE THREAD

**Issue by scotthong** [davisking/dlib#589]
Hi @davisking:

I've followed instructions as provided on the links below to train a shape predictor using the train_shape_predictor_ex.cpp.

* https://sourceforge.net/p/dclib/discussion/442517/thread/71b4b7c8/?limit=25
* https://github.com/davisking/dlib/issues/359
* Dataset: http://dlib.net/files/data/

I found that there is a big difference in file size between the one I've trained and the one provided by Dlib.

* shape_predictor_68_face_landmarks.dat: 99.7M 
* sp_20170512.dat: 16.6M

Here is the project I've created: 

* https://github.com/scotthong/dlib-align-faces

Can you elaborate on what might be the cause of the huge difference in terms of file size? 
By the way, do you have a way to evaluate the performance of the shape predictor?

Thanks,

**Comment by davisking** [comment]
If you read the paper that describes the method it will be very clear to you what the parameters do and how they influence the size of the resulting regression forest.  It's very clearly articulated in the paper, so I'm not going to repeat it here.  It's also pretty clearly explained in the dlib documenation: http://dlib.net/dlib/image_processing/shape_predictor_abstract.h.html#shape_predictor_trainer

**Comment by smtabatabaie** [comment]
@scotthong I wanted to ask if your file worked? I'm also struggling with the size of dlib file. I couldn't find sp_20170512.dat in your github page.
Thanks

**Comment by scotthong** [comment]
You can download the model using the link below:
https://github.com/scotthong/dlib-align-faces/tree/master/models

I haven't got the chance to validate the model. The hyper parameters used to train the model are detailed in the paper and I haven't get a chance to get to it yet. That's the answer I've got from @davisking.

**Comment by devanandd8245** [comment]
@davisking Can you please tell us how did you annotate the images to get the facial landmarks with eye detection and proceeded for training of the algorithm. That is have you annotated the images using landmark annotation or normal annotation with squares.

Please help me as i am struck in the type of annotation to be given as input for the training the model file.

**Comment by wangqiang624731186** [comment]
> Hi @scotthong ，Has this problem been solved? I use the default train parameter ,this size of model is 16.6M .
> Thanks

你弄明白了吗，模型体积变小
