### ISSUE TITLE
Inputting batch of data w/ model that has fully connected layer w/ softmax.

### ISSUE THREAD

**Issue by Dranithix** [davisking/dlib#592]
Hi,

I was wondering if there was any way to output a `std::vector` of `matrix<unsigned char/input type>` from a softmax FC network.

Something along the lines of: `std::vector<matrix<float, 1, 7>> softmax_outputs = model(tensor_of_inputs);`

Thanks,

**Comment by davisking** [comment]
Yes, you can do this by writing your own loss layer and have it output anything you want.

**Comment by Dranithix** [comment]
Is there no way to do it presently right now w/ the current softmax loss layer?

**Comment by davisking** [comment]
You can get the last tensor by calling subnet().  That last output from the network has all the log probabilities in it for each class.  Then you can do whatever you want with them like stuff them into a std::vector or anything else you like.

**Comment by Dranithix** [comment]
My bad, think I phrased my question wrong. As of right now softmax outputs a matrix of floats representing the distribution of probabilities for a bunch of classes.

Is there any way to call say a convolutional net with softmax being the loss layer on a batch of images, to then get a std::vector of a bunch of softmax outputs for each image in the batch with the present softmax implementation in Dlib right now? Or, does that have to be implemented through a custom loss layer?

**Comment by davisking** [comment]
If you have the floats then you have the numbers.  You can get them.  You seem to know you can get them.  I don't know what else to say.
