### ISSUE TITLE
Ambiguous Reference caused by Protobuf when using Caffe and Dlib

### ISSUE THREAD

**Issue by pkdogcom** [davisking/dlib#594]
I've run into naming conflicts during compilation which seems to be caused by protobuf when I try to use Caffe and Dlib together. 

The error looks like this:
`In file included from /usr/include/google/protobuf/message.h:120:0,
                 from /opt/caffe/build/include/caffe/proto/caffe.pb.h:23,
                 from /opt/caffe/include/caffe/blob.hpp:9,
                 from /opt/caffe/include/caffe/caffe.hpp:7,
                 from /root/surveillance/ssd_detector.h:8,
                 from /root/surveillance/main.cpp:9:
/usr/include/google/protobuf/descriptor.h:290:24: error: reference to 'vector' is ambiguous
   void GetLocationPath(vector<int>* output) const;
                        ^
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /root/dlib/dlib/../dlib/opencv/cv_image.h:6,
                 from /root/dlib/dlib/../dlib/opencv.h:10,
                 from /root/surveillance/main.cpp:1:
/usr/include/c++/5/bits/stl_vector.h:214:11: note: candidates are: template<class _Tp, class _Alloc> class std::vector
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from /root/dlib/dlib/../dlib/opencv/../matrix/../array2d/../geometry/rectangle.h:11:0,
                 from /root/dlib/dlib/../dlib/opencv/../matrix/../array2d/array2d_kernel.h:10,
                 from /root/dlib/dlib/../dlib/opencv/../matrix/../array2d.h:7,
                 from /root/dlib/dlib/../dlib/opencv/../matrix/matrix_mat.h:10,
                 from /root/dlib/dlib/../dlib/opencv/cv_image.h:11,
                 from /root/dlib/dlib/../dlib/opencv.h:10,
                 from /root/surveillance/main.cpp:1:
/root/dlib/dlib/../dlib/opencv/../matrix/../array2d/../geometry/vector.h:30:11: note:                 template<class T, long int NR> class dlib::vector
     class vector;
           ^
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /root/dlib/dlib/../dlib/opencv/cv_image.h:6,
                 from /root/dlib/dlib/../dlib/opencv.h:10,
                 from /root/surveillance/main.cpp:1:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:                 template<class _Tp, class _Alloc> class std::vector
     class vector : protected _Vector_base<_Tp, _Alloc>
`

The issue seems to be caused by the descriptor.h file in protobuf which use vector without specifying naming space. Is there a way to fix this issue without changing the codes in either protobuf or dlib?

FYI, My CMakeList.txt looks like this:
`
cmake_minimum_required(VERSION 2.8.12)
project(test)

set(CMAKE_CXX_STANDARD 11)

set(USE_AVX_INSTRUCTIONS ON CACHE BOOL "Use AVX for better CPU speed")
include(~/dlib/dlib/cmake)

find_package(OpenCV QUIET)
include_directories(${OpenCV_INCLUDE_DIRS})

find_package(Caffe QUIET)
include_directories(${Caffe_INCLUDE_DIRS})

set(DLIB_ALGS dlib_face_descriptor.cpp ssd_detector.cpp)

add_executable(main main.cpp ${DLIB_ALGS})
target_link_libraries(main ${Caffe_LIBRARIES} ${OpenCV_LIBS} dlib::dlib)
`

**Comment by davisking** [comment]
Have you written something like 'using namespace dlib' in front of a
#include statement?  That would explain this.
