### ISSUE TITLE
landmark detector turns 170ms on my mobile phone(Android),how can I speed it up?

### ISSUE THREAD

**Issue by 9crk** [davisking/dlib#598]
seems downscaling the image is useless for speed.

btw, 95M of dat file is too big. is that the reason for the slow?

I'v speed up the face detection to 17ms, but I cant speed the landmark detection up..

pls help.

**Comment by davisking** [comment]
That doesn't sound like the right speed.  But in any case, if you want a different model file you need to train your own.  The example programs show you how to do this.

**Comment by 9crk** [comment]
will changing the model get better speed?

**Comment by 9crk** [comment]
what's the right speed? what may cause my problem?

**Comment by davisking** [comment]
Read the documentation so you can understand what the model parameters do.

But in any event, no matter what you do the shape_predictor is at least an order of magnitude faster than the face detector.  So if you think the shape_predictor isn't faster you are doing something wrong.  Probably you are not measuring the time right.  Or you are measuring other things as well like you are doing a bunch of file I/O or something else.  I have no idea.  http://dlib.net/faq.html#Itdoesn'twork

**Comment by 9crk** [comment]
Im not mean face detector is faster than shape_predictor.
I'm using opencv to do face detector,so I can resize the image to 4x smaller to do face detector.
then the time cost of face detector turns less than shape predictor.

I'm pretty sure I measured the process in right way.
both in Mac Pro or Android device.

but the best time I can minimize is about 170ms on shape predictor.

this cant get me a real-time face tracker...

**Comment by 9crk** [comment]
now I get 19ms landmark + 8ms face detector to every frame on my Mac pro.
I have no idea on how to reduce the time anymore...

**Comment by purudpd** [comment]
> now I get 19ms landmark + 8ms face detection to every frame on my Mac pro.
> I have no idea on how to reduce the time anymore...

How did the get the speed gains? Would be helpful if you mention that.
