### ISSUE TITLE
Unable to build face detection example on OS X Yosemite

### ISSUE THREAD

**Issue by vimalthilak** [davisking/dlib#6]
@davisking 

Thanks for making dlib available on github. I am unable to build the example with the latest code as of Feb 03, 2015 because of the following error:

Linking CXX executable face_detection_ex
Undefined symbols for architecture x86_64:
  "_jpeg_CreateDecompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_destroy_decompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_finish_decompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_read_header", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_read_scanlines", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_start_decompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_std_error", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_stdio_src", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [face_detection_ex] Error 1
make[1]: *** [CMakeFiles/face_detection_ex.dir/all] Error 2
make: *** [all] Error 2

I'm aware of a change that forced libjpeg to be built statically on Apple. But I still continue to see the above linker error. Can you please advise what else might be missing/wrong that is preventing me from building the examples?

Thanks,

-Vimal

**Comment by davisking** [comment]
What happens when you execute these exact commands?

cd examples
rm -rf build
mkdir build
cd build
cmake ..
cmake --build . --config Release

**Comment by vimalthilak** [comment]
output of cmake ..

-- The C compiler identification is AppleClang 6.0.0.6000056
-- The CXX compiler identification is AppleClang 6.0.0.6000056
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found LAPACK library
-- Found CBLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Check for STD namespace
-- Check for STD namespace - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vimalthilak/work/dlib/examples/build

**Comment by vimalthilak** [comment]
Output of cmake --build . -config Release

cmake --build . --config Release
Scanning dependencies of target dlib
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.o
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.o
[  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.o
[  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.o
[  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.o
[  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.o
[  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.o
[  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.o
[  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.o
[  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.o
[  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.o
[  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.o
[  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.o
[  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.o
[ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.o
[ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.o
[ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.o
[ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.o
[ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.o
[ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.o
[ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.o
[ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.o
[ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.o
[ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.o
[ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.o
[ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.o
[ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.o
[ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.o
[ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.o
[ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.o
[ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.o
[ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.o
[ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.o
[ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.o
[ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.o
[ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.o
[ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.o
[ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/widgets.o
[ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/drawable.o
[ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.o
[ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/style.o
[ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_widgets/base_widgets.o
[ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.o
[ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.o
[ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcomapi.o
[ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapimin.o
[ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapistd.o
[ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatasrc.o
[ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcoefct.o
[ 31%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcolor.o
[ 32%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jddctmgr.o
[ 32%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdhuff.o
[ 33%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdinput.o
[ 33%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmainct.o
[ 34%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmarker.o
[ 35%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmaster.o
[ 35%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmerge.o
[ 36%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdphuff.o
[ 36%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdpostct.o
[ 37%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdsample.o
[ 37%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jerror.o
[ 38%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctflt.o
[ 39%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctfst.o
[ 39%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctint.o
[ 40%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctred.o
[ 40%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemmgr.o
[ 41%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemnobs.o
[ 41%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant1.o
[ 42%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant2.o
[ 43%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jutils.o
[ 43%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapimin.o
[ 44%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatadst.o
[ 44%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcparam.o
[ 45%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapistd.o
[ 45%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmarker.o
[ 46%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcinit.o
[ 47%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmaster.o
[ 47%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcdctmgr.o
[ 48%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccoefct.o
[ 48%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccolor.o
[ 49%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jchuff.o
[ 49%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmainct.o
[ 50%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcphuff.o
[ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcprepct.o
[ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcsample.o
[ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctint.o
[ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctflt.o
[ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctfst.o
[ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.o
[ 54%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.o
Linking CXX static library libdlib.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(stack_trace.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(gui_core_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(stack_trace.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(gui_core_kernel_1.o) has no symbols
[ 54%] Built target dlib
Scanning dependencies of target assignment_learning_ex
[ 54%] Building CXX object CMakeFiles/assignment_learning_ex.dir/assignment_learning_ex.cpp.o
Linking CXX executable assignment_learning_ex
[ 54%] Built target assignment_learning_ex
Scanning dependencies of target bayes_net_ex
[ 55%] Building CXX object CMakeFiles/bayes_net_ex.dir/bayes_net_ex.cpp.o
Linking CXX executable bayes_net_ex
[ 55%] Built target bayes_net_ex
Scanning dependencies of target bayes_net_from_disk_ex
[ 55%] Building CXX object CMakeFiles/bayes_net_from_disk_ex.dir/bayes_net_from_disk_ex.cpp.o
Linking CXX executable bayes_net_from_disk_ex
[ 55%] Built target bayes_net_from_disk_ex
Scanning dependencies of target bayes_net_gui_ex
[ 56%] Building CXX object CMakeFiles/bayes_net_gui_ex.dir/bayes_net_gui_ex.cpp.o
Linking CXX executable bayes_net_gui_ex
[ 56%] Built target bayes_net_gui_ex
Scanning dependencies of target bridge_ex
[ 56%] Building CXX object CMakeFiles/bridge_ex.dir/bridge_ex.cpp.o
Linking CXX executable bridge_ex
[ 56%] Built target bridge_ex
Scanning dependencies of target bsp_ex
[ 57%] Building CXX object CMakeFiles/bsp_ex.dir/bsp_ex.cpp.o
Linking CXX executable bsp_ex
[ 57%] Built target bsp_ex
Scanning dependencies of target compress_stream_ex
[ 58%] Building CXX object CMakeFiles/compress_stream_ex.dir/compress_stream_ex.cpp.o
Linking CXX executable compress_stream_ex
[ 58%] Built target compress_stream_ex
Scanning dependencies of target config_reader_ex
[ 58%] Building CXX object CMakeFiles/config_reader_ex.dir/config_reader_ex.cpp.o
Linking CXX executable config_reader_ex
[ 58%] Built target config_reader_ex
Scanning dependencies of target custom_trainer_ex
[ 59%] Building CXX object CMakeFiles/custom_trainer_ex.dir/custom_trainer_ex.cpp.o
Linking CXX executable custom_trainer_ex
[ 59%] Built target custom_trainer_ex
Scanning dependencies of target dir_nav_ex
[ 59%] Building CXX object CMakeFiles/dir_nav_ex.dir/dir_nav_ex.cpp.o
Linking CXX executable dir_nav_ex
[ 59%] Built target dir_nav_ex
Scanning dependencies of target empirical_kernel_map_ex
[ 60%] Building CXX object CMakeFiles/empirical_kernel_map_ex.dir/empirical_kernel_map_ex.cpp.o
Linking CXX executable empirical_kernel_map_ex
[ 60%] Built target empirical_kernel_map_ex
Scanning dependencies of target face_detection_ex
[ 60%] Building CXX object CMakeFiles/face_detection_ex.dir/face_detection_ex.cpp.o
/Users/vimalthilak/work/dlib/examples/face_detection_ex.cpp:11:34: warning: '/*' within block comment [-Wcomment]
        ./face_detection_ex faces/*.jpg
                                 ^
1 warning generated.
Linking CXX executable face_detection_ex
Undefined symbols for architecture x86_64:
  "_jpeg_CreateDecompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_destroy_decompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_finish_decompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_read_header", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_read_scanlines", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_start_decompress", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_std_error", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
  "_jpeg_stdio_src", referenced from:
      dlib::jpeg_loader::read_image(char const*) in libdlib.a(jpeg_loader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [face_detection_ex] Error 1
make[1]: *** [CMakeFiles/face_detection_ex.dir/all] Error 2
make: *** [all] Error 2

**Comment by davisking** [comment]
If you change dlib/external/libjpeg/jmorecfg.h's #define EXTERN(type) statement at line 175 to this does it fix it:

#ifdef __cplusplus
#define EXTERN(type)		extern "C" type
#else
#define EXTERN(type)		extern type
#endif

**Comment by vimalthilak** [comment]
That change worked! Thanks @davisking

**Comment by davisking** [comment]
No problem.  Thanks for pointing this out :)

**Comment by osjunior** [comment]
Hi davisking,

I am trying to compile dlib.a library in an iOS Project, I get this error.

ld: warning: directory not found for option '-L/Users/koombea/apps/FaceImage/Framework'
Undefined symbols for architecture x86_64:
 
"_USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives", referenced from:
      _dlib_check_consistent_assert_usage in FJMorph.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation).


This error happened when I imported  "#import <dlib/image_processing.h>"

What is wrong here?

**Comment by rostopira** [comment]
I've got the same error while installing through `pip3 install dlib`, so I can't just edit jmorecfg.h

Any workaround? (Mac OS X El Captain)

**Comment by davisking** [comment]
This error isn't about python, so you probably aren't getting the same error.  What error did you get?

**Comment by doanduchieu** [comment]
Hi davisking, I got the same error with osjunior. Please help us.
Thanks,

> I am trying to compile dlib.a library in an iOS Project, I get this error.

ld: warning: directory not found for option '-L/Users/apps/ImageDetection/Framework'
Undefined symbols for architecture x86_64:

"_USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives", referenced from:
_dlib_check_consistent_assert_usage in FJMorph.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation).

This error happened when I imported "#import <dlib/image_processing.h>"

**Comment by davisking** [comment]
Do the unmodified example programs compile when you use the cmake instructions on the dlib web page?

**Comment by srikanthpagadala** [comment]
Hi @davisking. I got a similar error. I'm installing using "pip3 install dlib" (with python3.5.2 on MacOS 10.12.3). My error trace is following:

  [ 96%] Building CXX object CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o
  [ 97%] Building CXX object CMakeFiles/dlib_.dir/src/correlation_tracker.cpp.o
  [ 98%] Building CXX object CMakeFiles/dlib_.dir/src/face_recognition.cpp.o
  [ 99%] Building CXX object CMakeFiles/dlib_.dir/src/gui.cpp.o
  [100%] Linking CXX shared library dlib.so
  Undefined symbols for architecture x86_64:
    "boost::python::detail::init_module(PyModuleDef&, void (*)())", referenced from:
        _PyInit_dlib in dlib.cpp.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [dlib.so] Error 1
  make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
  make: *** [all] Error 2
  error: cmake build failed!
  
Any suggestions?

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whywon'tthePythonbindingscompilework
