### ISSUE TITLE
landmark detection

### ISSUE THREAD

**Issue by VictoryDong** [davisking/dlib#600]
Hi, davisking:
I would like to ask a problem about the face landmark detection , I try to optimize themodel size, hoping to drop to 5M and below, may I ask some feasible direction?
Thanks a lot.

**Comment by davisking** [comment]
Train a new model with fewer landmarks or smaller trees.

**Comment by 9crk** [comment]
I optimize the model to 18M. in the way of store all the leaf into a packed format.
which can be optimized more.
about 10M I think.

**Comment by laper** [comment]
Hi, @9crk 
Did you optimize the model to 18M by retrain a new model or something else?
"Store all the leaf into a packed format"
Could you please give me more details about it?
Thanks.

**Comment by 9crk** [comment]
@laper just store all the value into a binary file.(not a ascii file). then it works.
