### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by auroua** [davisking/dlib#601]
When I run the commond:
python  /home/aurora/workspaces/dlib-19.4/models/shape_predictor_68_face_landmarks.dat /home/aurora/workspaces/dlib-19.4/models/dlib_face_recognition_resnet_model_v1.dat  face_recognition.py /home/aurora/workspaces/data/1.jpg

I got the following error, how to solve it?

SyntaxError: Non-UTF-8 code starting with '\x81' in file /home/aurora/workspaces/dlib-19.4/models/shape_predictor_68_face_landmarks.dat on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by davisking** [comment]
/home/aurora/workspaces/dlib-19.4/models/shape_predictor_68_face_landmarks.dat  is not a python script.  You have to give the python interpreter a python script.
