### ISSUE TITLE
[question] Support of CUDA_GENERATION in CMake

### ISSUE THREAD

**Issue by archenroot** [davisking/dlib#605]
Will you allow new variable for CMake subsystem with name of CUDA_GENERATION? I am taking it from OpenCV project where it is used for specification of Fermi, Pascal, Maxwell or Volta, etc. and limits the code generation only for specific architecture (gencode = compute....)

Here is how it is done within OpenCV:
https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake

There is probably in the moment broken auto detector as this issue I faced:
https://github.com/opencv/opencv/issues/8781

This is related to Gentoo ebuild system where we in system wide /etc/portage/make.conf file might configure variable CUDA_GENERATION value and pass it to any project.

I understand this is definitely something which will require massive adoption in the wild, but maybe good idea. What do you think?

**Comment by davisking** [comment]
Is it just supposed to supply the value for nvcc's -arch switch?

**Comment by archenroot** [comment]
Yes, actually it is responsible to both externally configurable or auto mode if not specified to produce one of those:
-gencode arch=compute_20,code=sm_20
-gencode arch=compute_30,code=sm_30
-gencode arch=compute_35,code=sm_35 
-gencode arch=compute_37,code=sm_37
-gencode arch=compute_50,code=sm_50
-gencode arch=compute_52,code=sm_52
-gencode arch=compute_60,code=sm_60
-gencode arch=compute_61,code=sm_61

On binary distribution it just make the package biger, but on Gentoo source distribution it multiply the compile time..

**Comment by archenroot** [comment]
I am now working on latest Gentoo ebuild as our last version is sci-libs/dlib-18.15. We support in the moment following integration/USE variables:
```
 * Found these USE flags for sci-libs/dlib-18.15:
 U I
 + + X        : Add support for X11
 + + blas     : Add support for the virtual/blas numerical library
 - - doc      : Add extra documentation (API, Javadoc, etc). It is recommended to enable per
                package instead of globally
 - - examples : Install examples, usually source code
 + + jpeg     : Add JPEG image support
 + + lapack   : Add support for the virtual/lapack numerical library
 - - png      : Add support for libpng (PNG images)
 - - test     : Workaround to pull in packages needed to run with FEATURES=test.
                Portage-2.1.2 handles this internally, so don't set it in
                make.conf/package.use anymore
```
I would like to introduce latest version with both **CUDA and AVX instructions** USE variables support (used in configuration phase to enable/disable features)

**Comment by davisking** [comment]
Ok.  Well, I'm still not totally clear on what you want to do.  But you can
submit a PR for it and I'll look it over then.

**Comment by davisking** [comment]
I should emphasize that whatever you do shouldn't break existing builds.

**Comment by archenroot** [comment]
Yes, regarding DLIB it is only supposed to generate NVCC arch switches, nothing more.. in controlled way.

In default it generates code for Fermi, Maxwell, Pascal, Volta, etc. By this external parametrization via CUDA_GENERATION="Maxwell" for example it will generate code only for:
```
-gencode arch=compute_50,code=sm_50
-gencode arch=compute_52,code=sm_52
```

On top, if this parameter is not submitted, so CMake CUDA_GENERATION will set to AUTO mode and tries to execute following code on the fly:
```
#include <stdio.h>
int main()
{
    int count = 0;
    if (cudaSuccess != cudaGetDeviceCount(&count)){return -1;}
    if (count == 0) {return -1;}
    for (int device = 0; device < count; ++device)
    {
        cudaDeviceProp prop;
        if (cudaSuccess != cudaGetDeviceProperties(&prop, device)){ continue;}
        printf("%d.%d ", prop.major, prop.minor);
    }
    return 0;
}
```
The result of this should be major and minor version of architecture, for example 5.0. So again it should limit need for binary files to just specific architecture.

And it the end if value is not submitted by packaging system (Gentoo ebuild) and AUTO mode fails -> it is not end of days, as this will finally failover to generate simply all architectures. So no  one should be harm, only used for tuning.

I will fork dlib and test locally and come with final PR when it is ready.
