### ISSUE TITLE
How to build multi-class classifier using structured SVM

### ISSUE THREAD

**Issue by vg123** [davisking/dlib#607]
I was using the python( 2.7.6) wrapper of `dlib 19.4.0` for training my dataset and building a mutli-class classifier. But, due to lack of proper documentation I am unable to do the same. Could you please help me provide the same with example for python?

**Comment by davisking** [comment]
I don't really understand what you are trying to ask.

**Comment by vg123** [comment]
`http://dlib.net/svm_struct.py.html` in this link you give example having 4 training sample vectors  and  3 classes (0,1,2) and `weights = dlib.solve_structural_svm_problem(problem)`  returns a vector of 9 values list that is stored in "weights" above, what will be the size of weight vector when we have image matrices as training samples for multi-classes ?

**Comment by davisking** [comment]
This isn't the tool you want to use.  It's meant for experts who want to design new types of learning algorithms.  Instead, you should probably use one of the multi-class classifiers in scikit-learn if you want to use python.
