### ISSUE TITLE
How to compile the project without cmake

### ISSUE THREAD

**Issue by Sar-Kerson** [davisking/dlib#608]
I am trying to compile my project on Ubuntu using g++ but errors are shown.
I didn't add any path in the environment variables but I typed this:
_g++ -o Face_test Face_test.cpp -I/home/sar/Desktop/dlib/dlib/image_processing -I/home/sar/Desktop/dlib
_
And here's my include files in my code:
`#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>
#include <dlib/image_io.h>

using namespace dlib;
using namespace std;`

I would be appreciate if anyone can help me.

**Comment by davisking** [comment]
There are instructions here: http://dlib.net/compile.html
