### ISSUE TITLE
Object detector training results don't detect very much

### ISSUE THREAD

**Issue by endotronic** [davisking/dlib#61]
First things first: I'm posting here because it seems like the SourceForge discussion isn't very active. My issue is almost certainly a mistake on my part and not a dlib bug, though, so if I am abusing the Issues section here, just close this and I'll seek guidance on the appropriate channels.

I'm using the object detector to detect fingertips, and I've prepared about 800 truth boxes in about 200 images. The range of angles for the fingers is no more than +/- 45 degrees, which I figure is probably OK, since the face detector seems to work with similar angles. Training works just fine, and when I generate an image with draw_fhog(), I can clearly see a representation of a finger (I love this feature!)

When I go to use the detector, I rarely get results. Even when I run the detector on the same images that I trained with, I rarely get any rectangles out of the detector. When I do, they are correct though. I also find that the fewer images I train with, the more results I do get, though they pretty much only happen with images from the training set. If I train with more than 50 truth boxes, it seems I will not ever detect anything.

I'm sure we're all very busy, so I don't expect much assistance here. I'm just wondering if anything comes to mind why I might be experiencing this? I am mostly using default parameters for training (c=1, epsilon=0.01, pyramid_down<6>, which I think means the downsampling ratio is 5/6). I've increased c and epsilon with no noticeable results. Fingers don't have a lot of detail for the training to fit to, but I expected that I'd have false positives, not a lack of positives. I don't mind false positives if I can at least get the training set to be detected.

**Comment by davisking** [comment]
It's better to post this in the source forge forums.  But in any event, I can't tell if you are doing it wrong based on the information you provided.  However, if I had to guess I would say it's probably something wrong or inconsistent about your data.

**Comment by endotronic** [comment]
I'm continuing to look into it. I'll post in the source forge forums in the future. Thanks.
