### ISSUE TITLE
dnn_metric_learning_on_images_ex: Crash when using multi GPU and Loss increased.

### ISSUE THREAD

**Issue by sebcactus** [davisking/dlib#614]
When using the example dnn_metric_learning_on_images_ex with 2 GPUs who have not the same amount of memory: 8GB and 11GB ;  the overall memory usage is 13GB which is nicely split evenly (~6500MB per GPU) on the two GPUs but would not fit on one GPU ; and the state is reloaded because the loss increased, I got the following issue
```
step#: 57758  learning rate: 0.1   average loss: 0.0182338    steps without apparent progress: 1619
Saved state to face_metric_sync
step#: 57843  learning rate: 0.1   average loss: 0.0183944    steps without apparent progress: 1622
step#: 57931  learning rate: 0.1   average loss: 0.0183579    steps without apparent progress: 1730
step#: 58019  learning rate: 0.1   average loss: 0.0188993    steps without apparent progress: 1887
step#: 58107  learning rate: 0.1   average loss: 0.0188605    steps without apparent progress: 1999
step#: 58195  learning rate: 0.1   average loss: 0.0184567    steps without apparent progress: 2122
step#: 58283  learning rate: 0.1   average loss: 0.0180592    steps without apparent progress: 2204
step#: 58371  learning rate: 0.1   average loss: 0.0185274    steps without apparent progress: 2275
step#: 58459  learning rate: 0.1   average loss: 0.0191554    steps without apparent progress: 2466
Loss has been increasing, reloading saved state from face_metric_sync
terminate called after throwing an instance of 'dlib::cuda_error'
  what():  Error while calling cudaMemcpy(dest.device_write_only(), src.device()+src_offset, num*sizeof(float), cudaMemcpyDeviceToDevice) in file /home/spiccand/git/dlib/dlib/dnn/gpu_data.cpp:62. code: 11, reason: invalid argument
Aborted (core dumped)
```

**Comment by davisking** [comment]
Does this happen reliably, or just once?

**Comment by sebcactus** [comment]
Systematically, when the Loss is increasing

**Comment by davisking** [comment]
How are you creating the dnn_trainer?

**Comment by davisking** [comment]
Well, actually, can you post a complete program and whatever is needed for
me to reproduce this problem?

**Comment by sebcactus** [comment]
dlib version: commit 97ff8cb2a9256b78907b0b9ac3630b4a54490783
Here is the code.
The notable changes from your example:
- convert RGB to gray
- trainer devices {0, 1}
- increase batch size (50, 20) -> would not fit on one device
- increase iterations without progress (10000)

I can not share the data. It is about 4M 150x150 RGB images and 60K ids.
[dnn_metric_learning_on_gray_images_ex.zip](https://github.com/davisking/dlib/files/1040474/dnn_metric_learning_on_gray_images_ex.zip)

**Comment by davisking** [comment]
Thanks for the info.  I'm not going to try and guess what causes the bug though.  For all I know it's not even a bug in dlib but something specific about your setup (which is usually ultimately the case when people post this kind of thing).  You should try and figure out a way to make some program you can post that exhibits the bug.  If you can't then you are on your own debugging this.

**Comment by sebcactus** [comment]
I will see if I can make it small, but as you say I might be on my own unfortunately.

**Comment by plumtus** [comment]
I got the same error:
Loss has been increasing, reloading saved state from training_metric.sync
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
I debug this error, and guess the reason may be: in the class dnn_trainer(trainer.h), the averagers was allocated and setup only at the first iteration. but when training_metric.sync was reloaded, the tensors was deserialized, the previous data structure has changed, the operation affine_transform in multi_device_tensor_averager.average() triggered this error.
I try to fix this error by reinitializing averagers when saved sync file was reloaded. I add a memeber variable 'sync_file_reloaded' to record the status reloaed, and modified the line 710 in "trainer.h": "if (averagers.size() == 0)" to "if (averagers.size() == 0 || sync_file_reloaded)", It works. But I am not sure is it correct?

**Comment by davisking** [comment]
Ah, yeah, that's the problem.  I totally forgot about the averagers holding pointers to those gradients that get cleared when syncing happens.  I only tested the auto-reloading with one GPU so never saw this issue.  Good catch.  The change you suggest is the correct thing to do.  Do you want to submit it as a PR?

**Comment by plumtus** [comment]
Yes, can I
