### ISSUE TITLE
How do I compile Python bindings with NEON support for Pi3?

### ISSUE THREAD

**Issue by jyurek** [davisking/dlib#615]
I apologize if this is a noob question but I don't have experience with either setup.py or cmake. I've seen in a few places that I need to compile with the `-mfpu=neon` flag but I don't have any idea where to specify that. I see the `python setup.py install --yes USE_AVX_INSTRUCTIONS` but that doesn't seems to help with NEON.

I'm on linux on a Pi3. I have compiled dlib successfully without NEON so at least it works. What do I need to do here?

**Comment by BarbaL** [comment]
I'm on the same situation. If someone got this, please let us know.

**Comment by davisking** [comment]
I just added the `--compiler-flags` option to setup.py.  You can use that to pass arbitrary options to gcc now, such as `-mfpu=neon`.

**Comment by jyurek** [comment]
Thanks very much!

**Comment by jyurek** [comment]
I hate to belabor this issue, but I used this flag on my Pi (`sudo python3 setup.py install --compiler-flags "-mfpu=neon"`) and didn't see any apparent speed increase. Is there a way I can confirm the flag was set or that it's being used? I'll gladly accept exasperated RTFM replies if that's what this question deserves. :)

**Comment by davisking** [comment]
The build folder should be in tools/python/build.  You can go there and see what the cmake settings are.  It should have a whole cmake generated project that is the one that build the python module.

**Comment by jyurek** [comment]
Awesome. The `-mfpu=neon` options are definitely in there. Going to have the sleuth this one out. Thanks very much for the help.

**Comment by davisking** [comment]
No problem :)
