### ISSUE TITLE
Problem including dlib/dnn/cuda_utils.h after recent updates.

### ISSUE THREAD

**Issue by ptran516** [davisking/dlib#616]
@davisking 

I have been using functions *dlib*'s `cuda_utils.h` to handle tedious block/thread iteration and kernel launching on my person re-identification repo [here](https://github.com/ptran516/idla-person-reid). The GPU build of the project just failed after pulling the most up-to-date version of *dlib*.

```shell
.../idla/src/difference_impl.cu:3:33: fatal error: dlib/dnn/cuda_utils.h: No such file or directory
```

The first commit of *dlib* that I can build with which produces the above error is [6ed65b](https://github.com/davisking/dlib/commit/6ed65bf3f125a89eb860262c37956143df18972b). It looks like a  few commits earlier, [0d4987](https://github.com/davisking/dlib/commit/0d4987a51b42c52fdd90556994364231eaf97929) removes `INCLUDE_DIRECTORIES(${dlib_path}/..)` from `dlib/cmake`; which may be a likely cause of this sort of issue.

I tried to manually add the `dlib` directory via `include_directories`, but it looks like that's not the right thing to do (based on the message I got :smiley:).

```shell
#error "Don't put the dlib folder in your include path"
```

The CPU build of my project is working fine, but recent[ish] updates have screwed up my GPU build. Is it obvious why this is happening? Is `cuda_utils.h` not meant to be externalized?

Thanks in advance.

**Comment by davisking** [comment]
The new dlib cmake scripts use cmake's target properties which propagate all this kind of dependency information automatically.  But you have to use `dlib::dlib` rather than `dlib` as the argument to `target_link_libraries` for some reason to get it to happen.

**Comment by davisking** [comment]
Although, I've had issues with cmake not propagating target dependencies when it compiles cuda executables.  So you might have to just add the `include_directories` statement yourself.  You also want to make sure you pass the compiler options to nvcc as well, which you can get from cmake's target options with cmake code like this:

```
get_property(dlib_opts TARGET dlib::dlib PROPERTY COMPILE_OPTIONS)
list(APPEND CUDA_NVCC_FLAGS "${dlib_opts}")
```

Presumably some newer version of cmake will have cuda tooling that doesn't mess this up or does it in some smarter way.

**Comment by davisking** [comment]
Cool.  You should definitely use dlib::dlib as the target though.  It's always better near as I can tell.

**Comment by ptran516** [comment]
The following lines make `dlib::dlib` backwards compatible with older versions of `dlib`:

```cmake
if (${DLIB_VERSION} VERSION_LESS 19.4.0)
  add_library(dlib::dlib ALIAS dlib)
endif()
```
