### ISSUE TITLE
Any plans to extend tensor type to 16bit-float halfs?

### ISSUE THREAD

**Issue by OranjeeGeneral** [davisking/dlib#618]
As this would cut down memory requirement for DNN by half allowing larger models to train and also likely increase the training/interference speed. 

For a decent half-type implementation one could have a look at OpenEXR image format source.

CuDNN supports 16bit half tensor data structure for a while now and I see that Intel MKL-DNN has added something in that area too. 

Alternatively one could make Tensor data structure a generic template type. That would allow even smaller data type or even simple binary,trinary networks in the future, but is probably a lot of work too.

Any thoughts?

**Comment by davisking** [comment]
I'm not planning on it right now, but it's something I've thought about.  It would require some reworking of the interfaces and is likely a little tricky to do in a way that doesn't cause the interfaces to have usability problems.  Although I'm sure it can be done.
