### ISSUE TITLE
When test it with for videos, six movies cannot be opened

### ISSUE THREAD

**Issue by hbgxsm95** [davisking/dlib#62]
Falcon:CLM-framework-master zhaotsuchikaqin$ ./bin/SimpleCLM -f "./videos/changeLighting.wmv" -f "./videos/0188_03_021_al_pacino.avi" -f "./videos/0217_03_006_alanis_morissette.avi" -f "./videos/0244_03_004_anderson_cooper.avi" -f "./videos/0294_02_004_angelina_jolie.avi" -f "./videos/0417_02_003_bill_clinton.avi" -f "./videos/0490_03_007_bill_gates.avi" -f "./videos/0686_02_003_gloria_estefan.avi" -f "./videos/1034_03_006_jet_li.avi" -f "./videos/1192_01_006_julia_roberts.avi" -f "./videos/1461_01_021_noam_chomsky.avi" -f "./videos/1804_03_006_sylvester_stallone.avi" -f "./videos/1815_01_008_tony_blair.avi" -f "./videos/1869_03_009_victoria_beckham.avi" -f "./videos/1878_01_002_vladimir_putin.avi"
Reading the CLM landmark detector/tracker from: ./bin/model/main_ccnf_general.txt
Reading the CLM module from: ./bin/model/clm_ccnf_general.txt
Reading the PDM module from: ./bin/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: ./bin/model/tris_68.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/patch_experts/ccnf_patches_0.25_general.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/patch_experts/ccnf_patches_0.35_general.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/patch_experts/ccnf_patches_0.5_general.txt....Done
Reading part based module....inner
Reading the CLM landmark detector/tracker from: ./bin/model/model_inner/main_ccnf_inner.txt
Reading the CLM module from: ./bin/model/model_inner/clm_ccnf_inner.txt
Reading the PDM module from: ./bin/model/model_inner/pdms/pdm_51_inner.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
Done
Reading part based module....left_eye_28
Reading the CLM landmark detector/tracker from: ./bin/model/model_eye/main_ccnf_synth_left.txt
Reading the CLM module from: ./bin/model/model_eye/clm_ccnf_left_synth.txt
Reading the PDM module from: ./bin/model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading part based module....right_eye_28
Reading the CLM landmark detector/tracker from: ./bin/model/model_eye/main_ccnf_synth_right.txt
Reading the CLM module from: ./bin/model/model_eye/clm_ccnf_right_synth.txt
Reading the PDM module from: ./bin/model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: ./bin/model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading the landmark validation module....Done
Attempting to read from file: ./videos/changeLighting.wmv
WARNING: Couldn't read movie file ./videos/changeLighting.wmv
Fatal error: Failed to open video source
Abort trap: 6

and when testing it for multiple faces,there is nothing happening actually..
 
i was using mac os.

**Comment by davisking** [comment]
This does not appear to have anything to do with dlib.
