### ISSUE TITLE
[trainer] do not clean completely the net in sync_to_disk()

### ISSUE THREAD

**Issue by sebcactus** [davisking/dlib#621]
Hi, Since commit df19361c8fb8f4d966e6691185754850fe6b1e75, the net is completely cleaned and all gradients information are lost.
This avoids the purpose of sync_to_disk() because when we restart, we lost all information.
I am actually wondering whether the net.clean() should at all be called in sync_to_disk().

**Comment by davisking** [comment]
Yes, it should be called.  The only thing that matters are the parameters, which is what is saved to disk.
