### ISSUE TITLE
installation on kubuntu 16.10

### ISSUE THREAD

**Issue by guenterneust** [davisking/dlib#623]
Hello
I want to use dlib on kubuntu 16.10, which I installed on my laptop a few months ago.
I installed libcblas, openblas from the ubuntu repositories and cuda 8.0 and cudnn 6.0 from nvidia, but I get the following messages when trying to configure the compilation for the examples using cmake-gui:

C++11 activated.
Enabling AVX instructions
Searching for BLAS and LAPACK
Checking for module 'cblas'
  No package 'cblas' found
Found OpenBLAS library
Found LAPACK library
BLAS library does not have cblas symbols, so dlib will not use BLAS or LAPACK
 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************
Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5") 
Looking for cuDNN install...
*** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
*** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
Found CUDA: /usr (found suitable exact version "8.0") 

Is dlib supposed to run on (K)ubuntu 16.10?
If yes, what am I doing wrong?

**Comment by davisking** [comment]
Yes. It will work. Did you do what the message said?  sudo apt-get install libopenblas-dev liblapack-dev

**Comment by guenterneust** [comment]
As far as I can tell, I did:
Maybe I installed something too much and it's conflicting with something else, but I have no idea what it can be.
I'm using a fresh clone of dlib from github.

guenter@Aspire:$ dpkg-query -l | grep blas
cuda-cublas-8-0                                 8.0.61.1-1                                  amd64        CUBLAS native runtime libraries
cuda-cublas-dev-8-0                             8.0.61.1-1                                  amd64        CUBLAS native dev links, headers
libblas-common                                  3.6.1-2ubuntu1                              amd64        Dependency package for all BLAS implementations
libblas-dev                                     3.6.1-2ubuntu1                              amd64        Basic Linear Algebra Subroutines 3, static library
libblas3                                        3.6.1-2ubuntu1                              amd64        Basic Linear Algebra Reference implementations, shared library
libcblas-dev                                    3.2.1+dfsg-1                                amd64        Basic Linear Algebra Subroutines 3, static library
libcblas3                                       3.2.1+dfsg-1                                amd64        Basic Linear Algebra Reference implementations, shared library
libclblas-dev:amd64                             2.10-4                                      amd64        development files for clBLAS
libclblas2:amd64                                2.10-4                                      amd64        OpenCL BLAS library
libcublas8.0:amd64                              8.0.44-0ubuntu1                             amd64        NVIDIA cuBLAS Library
liblastfm1:amd64                                1.0.9-1                                     amd64        Last.fm web services library (Qt4 build)
libnvblas8.0:amd64                              8.0.44-0ubuntu1                             amd64        NVBLAS runtime library
libopenblas-base                                0.2.18-1ubuntu1                             amd64        Optimized BLAS (linear algebra) library (shared library)
libopenblas-dev                                 0.2.18-1ubuntu1                             amd64        Optimized BLAS (linear algebra) library (development files)
guenter@Aspire:$ dpkg-query -l | grep cud
cuda                                            8.0.61-1                                    amd64        CUDA meta-package
cuda-8-0                                        8.0.61-1                                    amd64        CUDA 8.0 meta-package
cuda-command-line-tools-8-0                     8.0.61-1                                    amd64        CUDA command-line tools
cuda-core-8-0                                   8.0.61-1                                    amd64        CUDA core tools
cuda-cublas-8-0                                 8.0.61.1-1                                  amd64        CUBLAS native runtime libraries
cuda-cublas-dev-8-0                             8.0.61.1-1                                  amd64        CUBLAS native dev links, headers
cuda-cudart-8-0                                 8.0.61-1                                    amd64        CUDA Runtime native Libraries
cuda-cudart-dev-8-0                             8.0.61-1                                    amd64        CUDA Runtime native dev links, headers
cuda-cufft-8-0                                  8.0.61-1                                    amd64        CUFFT native runtime libraries
cuda-cufft-dev-8-0                              8.0.61-1                                    amd64        CUFFT native dev links, headers
cuda-curand-8-0                                 8.0.61-1                                    amd64        CURAND native runtime libraries
cuda-curand-dev-8-0                             8.0.61-1                                    amd64        CURAND native dev links, headers
cuda-cusolver-8-0                               8.0.61-1                                    amd64        CUDA solver native runtime libraries
cuda-cusolver-dev-8-0                           8.0.61-1                                    amd64        CUDA solver native dev links, headers
cuda-cusparse-8-0                               8.0.61-1                                    amd64        CUSPARSE native runtime libraries
cuda-cusparse-dev-8-0                           8.0.61-1                                    amd64        CUSPARSE native dev links, headers
ii  cuda-demo-suite-8-0                             8.0.61-1                                    amd64        Demo suite for CUDA
cuda-documentation-8-0                          8.0.61-1                                    amd64        CUDA documentation
cuda-driver-dev-8-0                             8.0.61-1                                    amd64        CUDA Driver native dev stub library
cuda-drivers                                    375.51-1                                    amd64        CUDA Driver meta-package
cuda-license-8-0                                8.0.61-1                                    amd64        CUDA licenses
cuda-misc-headers-8-0                           8.0.61-1                                    amd64        CUDA miscellaneous headers
cuda-npp-8-0                                    8.0.61-1                                    amd64        NPP native runtime libraries
cuda-npp-dev-8-0                                8.0.61-1                                    amd64        NPP native dev links, headers
cuda-nvgraph-8-0                                8.0.61-1                                    amd64        NVGRAPH native runtime libraries
cuda-nvgraph-dev-8-0                            8.0.61-1                                    amd64        NVGRAPH native dev links, headers
cuda-nvml-dev-8-0                               8.0.61-1                                    amd64        NVML native dev links, headers
cuda-nvrtc-8-0                                  8.0.61-1                                    amd64        NVRTC native runtime libraries
cuda-nvrtc-dev-8-0                              8.0.61-1                                    amd64        NVRTC native dev links, headers
cuda-repo-ubuntu1604                            8.0.61-1                                    amd64        cuda repository configuration files
rc  cuda-repo-ubuntu1604-8-0-local                  8.0.44-1                                    amd64        cuda repository configuration files
cuda-runtime-8-0                                8.0.61-1                                    amd64        CUDA Runtime 8.0 meta-package
cuda-samples-8-0                                8.0.61-1                                    amd64        CUDA example applications
cuda-toolkit-8-0                                8.0.61-1                                    amd64        CUDA Toolkit 8.0 meta-package
cuda-visual-tools-8-0                           8.0.61-1                                    amd64        CUDA visual tools
libcuda1-375                                    375.66-0ubuntu0.16.10.1                     amd64        NVIDIA CUDA runtime library
libcudart8.0:amd64                              8.0.44-0ubuntu1                             amd64        NVIDIA CUDA Runtime Library
libcudnn6                                       6.0.21-1+cuda8.0                            amd64        cuDNN runtime libraries
libcudnn6-dev                                   6.0.21-1+cuda8.0                            amd64        cuDNN development libraries and headers
libcudnn6-doc                                   6.0.21-1+cuda8.0                            amd64        cuDNN documents and samples
nvidia-cuda-dev                                 8.0.44-0ubuntu1                             amd64        NVIDIA CUDA development files
nvidia-cuda-doc                                 8.0.44-0ubuntu1                             all          NVIDIA CUDA and OpenCL documentation
nvidia-cuda-gdb                                 8.0.44-0ubuntu1                             amd64        NVIDIA CUDA Debugger (GDB)
nvidia-cuda-toolkit                             8.0.44-0ubuntu1                             amd64        NVIDIA CUDA development toolkit

**Comment by davisking** [comment]
Like the message says. You have a blas library that is missing cblad symbols. Start deleting blas libraries until you delete the right one.

**Comment by guenterneust** [comment]
Thank you.
Yeah, after I noticed that cmake is only checking the first time when it's run what libraries are available, I could apply your suggestion and solved the blas issue.
For the cuda issue, I had to manually set the host compiler to gcc-5/g++-5 and now it's compiling
