### ISSUE TITLE
Python's setup.py doesn't work with CUDA installed

### ISSUE THREAD

**Issue by yoniker** [davisking/dlib#628]
Hi!

So I've previously successfully installed dlib before on my laptop,and it was awesome.
Long story short, while installing Nvidia's CUDA I messed up my own driver so I had to reinstall Ubuntu.
Now that I'm trying to run setup.py install (which previously was smooth) I'm getting error messages so I really think that might be it (attached at the bottom of this message, if any more info is needed let me know). I do have python boost on my system (well,at the very least i can do "import boost"- i installed it just to get dlib).

I will appreciate help, and while I prefer dlib to use my GPU,I'm ok with just a workaround it.
What should I do? I've tried running setup with -DDLIB_NO_GUI_SUPPORT=yes and that didn't help :P

Edit: Now I realize it's not just python: when I've tried to run
mkdir build; cd build; cmake .. ; cmake --build .
after gettingthis repo,I got a similar (but not identical) error message :(

-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5")
-- Looking for cuDNN install...
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
cudnn_include (ADVANCED)
   used as include directory in directory /home/yoni/Projects/dlib/dlib/cmake_utils/test_for_cudnn
   used as include directory in directory /home/yoni/Projects/dlib/dlib/cmake_utils/test_for_cudnn
   used as include directory in directory /home/yoni/Projects/dlib/dlib/cmake_utils/test_for_cudnn
CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- *** Found cuDNN, but it looks like the wrong version so dlib will not use it. ***
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
error: cmake configuration failed!

**Comment by davisking** [comment]
Maybe you are using cuDNN 6?  You need the latest dlib from github to use
cuDNN 6.

**Comment by yoniker** [comment]
The error message states (correctly):
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5")
So I have Cuda 8.0. Oh and btw now im running it with the option --yes USE_AVX_INSTRUCTIONS and it seems to work (I'm at 80% now, if that is of interest I will keep you posted).

**Comment by davisking** [comment]
Well, for one thing, there is no such thing as cuDNN 5.5.  :/

**Comment by yoniker** [comment]
True, you are fast- i correct that within 2 mins :)

**Comment by davisking** [comment]
I don't know then.  Try compiling the test_for_cudnn project on it's own and see what errors you get.

**Comment by yoniker** [comment]
OK...how do i do that? :P

**Comment by yoniker** [comment]
The folder test_for_cudnn is pretty empty:
yoni@yoni-Lenovo-Z710:~/Projects/dlib/dlib/cmake_utils/test_for_cudnn$ ls
CMakeLists.txt  find_cudnn.txt
yoni@yoni-Lenovo-Z710:~/Projects/dlib/dlib/cmake_utils/test_for_cudnn$ cat f*.txt

message(STATUS "Looking for cuDNN install...")
# Look for cudnn, we will look in the same place as other CUDA
# libraries and also a few other places as well.
find_path(cudnn_include cudnn.h
    HINTS ${CUDA_INCLUDE_DIRS} ENV CUDNN_INCLUDE_DIR  ENV CUDNN_HOME
    PATHS /usr/local ENV CPATH
    PATH_SUFFIXES include
    )
get_filename_component(cudnn_hint_path "${CUDA_CUBLAS_LIBRARIES}" PATH)
find_library(cudnn cudnn
    HINTS ${cudnn_hint_path} ENV CUDNN_LIBRARY_DIR  ENV CUDNN_HOME 
    PATHS /usr/local /usr/local/cuda ENV LD_LIBRARY_PATH
    PATH_SUFFIXES lib64 lib x64
    )
mark_as_advanced(cudnn cudnn_include)
yoni@yoni-Lenovo-Z710:~/Projects/dlib/dlib/cmake_utils/test_for_cudnn$ cat C*.txt

cmake_minimum_required(VERSION 2.8.12)
project(cudnn_test)
include(../use_cpp_11.cmake)

find_package(CUDA 7.5 REQUIRED)
set(CUDA_HOST_COMPILATION_CPP ON)
list(APPEND CUDA_NVCC_FLAGS "-arch=sm_30;-std=c++11;-D__STRICT_ANSI__")
add_definitions(-DDLIB_USE_CUDA)

include(find_cudnn.txt)

include_directories(${cudnn_include})

cuda_add_library(cudnn_test STATIC ../../dnn/cudnn_dlibapi.cpp ${cudnn} )

**Comment by yoniker** [comment]
As a temporary fix I've commented out the file find_cudnn.txt (eg added a '#' character in each line since it seemed like a python code used somewhere) and now installation works without my gpu.

**Comment by davisking** [comment]
Huh, that's a strange cmake behavior.  Try pulling the latest dlib code from github and see if it works.

**Comment by yoniker** [comment]
Well the only reason I was able to comment out parts of the setup python code is downloading the repo from github ;) So..already done. Weirdest behavior, yeah. It's a shame since dlib itself is really good.

**Comment by davisking** [comment]
I updated it this morning after you commented.  So try it now.

**Comment by voletiv** [comment]
I'm getting the same error. I have followed @yoniker 's suggestion of commenting out the line `include (find_cudnn.txt)` in GitHubRepos/dlib/dlib/cmake_utils/test_for_cudnn/CMakeLists.txt, worked.

**Comment by davisking** [comment]
Try it now. It should be fixed.  Let me know if it's still an issue.
