### ISSUE TITLE
landmarks inaccurate for wide-open mouths

### ISSUE THREAD

**Issue by az0** [davisking/dlib#63]
While generally accurate for most faces and very helpful (thank you!), the landmarks on the lower lip and chin are not accurate when the mouth is open very wide.

I installed dlib 18.17.100 on Python 2.7 with the following shape predictor
http://sourceforge.net/projects/dclib/files/dlib/v18.10/shape_predictor_68_face_landmarks.dat.bz2

Example raw image:
![212002_d5613ee416_z](https://cloud.githubusercontent.com/assets/933680/11847902/e2d66592-a3dc-11e5-8e2c-453428c41dd6.jpg)

Same image with landmarks:
![big mouth](https://cloud.githubusercontent.com/assets/933680/11847930/ff3d083a-a3dc-11e5-81a5-203602a23c45.jpg)

**Comment by davisking** [comment]
Yes, this kind of face isn't represented in the training set so I wouldn't expect it to work well on it.  If you want to improve it you need to gather training data for these types of faces and add it into the dataset used to generate dlib's model.  The original dataset can be found here: http://dlib.net/files/data/

**Comment by az0** [comment]
Are you interested in contributions of face images for the shape predictor or frontal face detector? Today I also noticed many false negatives the frontal face detector.

**Comment by davisking** [comment]
Sure, if you want to improve those training datasets then that would be
super.  Realistically you likely need at least a few hundred additional
examples to improve the results.

**Comment by az0** [comment]
Hmm, I have one huge set of standardized images. Each image is one person facing forward and usually standing, and there is a manual crop coordinates for the head, which is a larger area that includes the shoulders and a bit of the upper chest. These re-annotated to a tighter crop around the head, right?

**Comment by davisking** [comment]
Yes, the annotations must be done in a way that matches the previous
annotations.  So the boxes must bound the same parts of the faces and the
landmarks must be at the same positions.  If it's not consistent it will
just make the resulting model worse when retrained.  I would use the
existing dlib landmark detector to generate initial annotations and then go
through them with the imglab tool and adjust (shift+right click and drag)
the outputs so they are correct.  That would be the fastest and most likely
to result in a consistent annotation.

**Comment by az0** [comment]
Two more questions.

First, for the frontal face detector suppose I have an "unlimited" supply of these photos that failed to detect a face. What are the minimum and maximum counts that would help?

Second, do you require any particular license? Do the photos need to be redistributable?

**Comment by davisking** [comment]
It's hard to say.  You can look at the face training dataset I used to get
a general sense of it but your millage may vary.  But as a rule of thumb,
between a few hundred to a few thousand is good.

I'm a fan of public domain dedications for stuff like this (e.g.
https://github.com/davisking/dlib-models).

**Comment by az0** [comment]
OK, I will think about the efforts of the annotations and negotiating public access to the images
