### ISSUE TITLE
Speed diff for facerec.compute_face_descriptor() between OSX and Linux

### ISSUE THREAD

**Issue by giffordw** [davisking/dlib#631]
I'm seeing a large difference in speed running compute_face_descriptor (python API) when I run on a new Macbook Pro vs. a Docker container on the same machine (0.03 seconds for 1 face on OSX vs. 0.34 seconds in Docker). I'm running with python 3.6 on both and obviously using the same processor. The code I'm testing is the facial_recognition python example, and the time is measured only to make that one function call. I'm not sure why this would be so different on OSX vs. Linux. I'm guessing there is some difference in how dlib is compiled between the two systems, so any help in identifying a potential culprit is much appreciated. dlib was installed on the Mac via [these](http://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/) instructions.

Below is the Dockerfile used in the test:
```
FROM python:3.6

RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-dev \
    libavcodec-dev \
    libavformat-dev \
    libboost-all-dev \
    libgtk-3-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    tk-dev \
    python3-dev \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN cd ~ && \
    mkdir -p dlib && \
    git clone -b 'v19.4' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS

RUN pip install Click>=6.0 dlib>=19.3.0 numpy Pillow scipy>=0.17.0 face_recognition requests matplotlib
```

**Comment by davisking** [comment]
You probably have a BLAS library on your mac but not in docker.  It's important to install an optimized BLAS like the Intel MLK or OpenBLAS.

**Comment by giffordw** [comment]
@davisking Thanks! That seems to have removed the difference. Really appreciate the quick suggestion.

**Comment by davisking** [comment]
No problem.

**Comment by artem-malko** [comment]
@giffordw  Hello) What did you install to fix your problem) Do you have a Dockerfile example?
