### ISSUE TITLE
Ability to specify CBLAS library directly

### ISSUE THREAD

**Issue by xsacha** [davisking/dlib#632]
Right now DLib searches some hardcoded paths. On Windows, specifically, it only looks for Intel MKL and only in some predefined paths.
It would be useful if we could populate some variable that contains the library dir instead.

**Comment by davisking** [comment]
You can always set variables like CMAKE_PREFIX_PATH to control this kind of thing.  But if there really is some use you want that isn't covered by the current BLAS finding or existing cmake variables then you can always submit a PR :)

**Comment by xsacha** [comment]
That's what I am using now (CMAKE_LIBRARY_PATH) but I figured there is usually an option for setting it.

**Comment by davisking** [comment]
That's the option for setting it :)
