### ISSUE TITLE
Does the order of training data matter when training a new shape predictor?

### ISSUE THREAD

**Issue by ChandlerWu** [davisking/dlib#635]
Hi, I am trying to expand the original dataset to improve the predictor. However, when adding new examples to the dataset, since I will be adding a group of similar examples, do I need to randomly adding them so that the original and new are well mixed or the ordering doesn't matter in this case?

I am sorry if this is a dumb question but I am new to ML. I tried to read the source code, I found "generate_split()" in "shape_predictor_trainer.h". I can kinda get the idea that trainer randomly get samples from the training set, but I could't be sure about it. If the trainer choose samples randomly, how do we make sure that all the training set will be visited? I also read the Kazemi paper but couldn't found things this basic. 

It would be so nice of you if you can give me some guidance. Also, if I want to fully understand "shape_predictor_trainer.h", where should I start? Thanks in advance for your help!

**Comment by davisking** [comment]
Don't worry about it.  Order of images doesn't matter.  You just add data and the algorithm does the right thing.  Do understand it you should read Kazemi's paper.

**Comment by davisking** [comment]
Also, if you are having trouble understanding Kazemi's paper then it's probably because you lack the necessary mathematical background.  The best way to fix that is to read the appropriate books beforehand: http://dlib.net/books.html
