### ISSUE TITLE
how to finetune the face recognition model

### ISSUE THREAD

**Issue by auroua** [davisking/dlib#638]
I want to finetune the ```dlib_face_recognition_resnet_model_v1.dat``` model using some new datasets. I think the first step to finetune this model is to **detect** faces in the training images and then **align** the detected faces, and at last  feed the aligned faces into the model as input. But in the ```dnn_face_recognition_ex.cpp``` files the author says the following differences, and not mentioned the **face detection** and **align**.
> // Also, the dnn_metric_learning_on_images_ex.cpp example shows how to train this network.
// The dlib_face_recognition_resnet_model_v1 model used by this example was trained using
// essentially the code shown in dnn_metric_learning_on_images_ex.cpp except the
// mini-batches were made larger (35x15 instead of 5x5), the iterations without progress
// was set to 10000, the jittering you can see below in jitter_image() was used during
// training, and the training dataset consisted of about 3 million images instead of 55. 

In the above comment you said 3 million images were used to train this model. Can you tell me which datasets were used to train this model?
I also want to find out have you did the detection and alignment during you training process.
Thanks!

**Comment by davisking** [comment]
Yes, the detection and alignment is important.  You obviously need to do that to create the training dataset in the first place.  How else would you have the cropped faces that are the input to training?

The dataset I used is unfortunately not publically available for download.

**Comment by auroua** [comment]
Thanks
