### ISSUE TITLE
image scaling in face recognition

### ISSUE THREAD

**Issue by bkj** [davisking/dlib#640]
Hi -- 

I'm wondering how images are getting preprocessed before going into `face_recognition_model_v1`.  There's a comment in the code that suggests the face chips are upsampled to 150x150, but I could find exactly where that's happening, or what kind of upsampling is being done.  

Roughly, I'm trying to measure how performance of the model degrades with the quality of the image.  I have a dataset where a number of the extracted faces are smaller than 50x50, so trying to build intuition about how the model might behave at those resolutions.

Thanks
Ben

**Comment by davisking** [comment]
Look at the C++ example program http://dlib.net/dnn_face_recognition_ex.cpp.html.  It shows all the processing steps from loading the image to computing the face descriptor.
