### ISSUE TITLE
Build-Error on OS X

### ISSUE THREAD

**Issue by moha42** [davisking/dlib#641]
First thanks in advance!

I have troubles compiling dlib on OSX 10.12.15 with Qt5.9. I did a clean install like described on http://dlib.net/compile.html. I could implement the library into Qt and try some functions like rotate_image() etc. I'm trying to build a GUI for a example in dlib like http://dlib.net/fhog_object_detector_ex.cpp.html. I'm reading an image and train and test the data sets. Compiling works for these steps until I copy this line:
`object_detector<image_scanner_type> detector = trainer.train(images_train, face_boxes_train);
`
At this point compiling doesn't work anymore and I get this error:
:-1: error: symbol(s) not found for architecture x86_64
:-1: error: linker command failed with exit code 1 (use -v to see invocation)

I really searched hard for this but I couldn't find an answer and the MacOs community using Qt seems to be very small. As a beginner in programming and to dlib I wanted to ask here.
I'm also not sure if <dlib/gui_widgets.h> is supported in Qt. So I'm really new to everything.

PS
I included the lib like this:

INCLUDEPATH += -I /usr/local/Cellar/dlib/19.4/include/
LIBS += -L/usr/local/Cellar/dlib/19.4/lib/ -ldlib
PKGCONFIG += /usr/local/Cellar/dlib/19.4/lib/pkgconfig

I really hope to solve this problem.

**Comment by davisking** [comment]
Dlib doesn't have anything to do with Qt.  So the fact that you are using Qt will have no effect on what dlib does or how it works.  Your question is really about how to use qmake it seems, it is better asked in a forum dedicated to helping people understand qmake or how to setup Qt projects in general. 

I will also note that dlib/19.4/include/ is not part of the dlib folder structure, which makes me think you aren't using the copy of dlib from dlib.net but some other repackaged version that may or may not be totally messed up.  You should get dlib from dlib.net (or the main dlib github which is where you are posting now).
