### ISSUE TITLE
dnn_mmod_ex.cpp doesn't compile

### ISSUE THREAD

**Issue by nikhilpandey360** [davisking/dlib#644]
Every time I tried to run dnn_mmod_ex.cpp , I met with the issue as follows. I have no idea why this is happening as i tried to compile the g++ -std=c++11 -O3 -I.. svm_ex.cpp and compiled quite easily!
Is it a bug or is there some error in cmake procees? 

error:
```
`np@np-HP-15-Notebook-PC:~/Downloads/dlib-master/examples$ g++ -std=c++11 -O3 -I.. ./dnn_mmod_ex.cpp faces
/usr/bin/ld: cannot find faces: File format not recognized
collect2: error: ld returned 1 exit status
`
```

**Comment by davisking** [comment]
What did you type?  What happened?

**Comment by nikhilpandey360** [comment]
I think the error is not related to the dnn_mmod_ex.cpp itself rather this is some thing related to the fashion I'm trying to compile. Anyway, as it stats on [this page](http://dlib.net/compile.html), I tried to run
 
`g++ -std=c++11 -O3 -I.. ../dlib/all/source.cpp -lpthread -lX11 dnn_mmod_ex.cpp /home/directory/with/images_and_xml/`

and then it gives that error. 

Thing to be noted is that the following command produces the output as expected.
`g++ -std=c++11 -O3 -I.. svm_ex.cpp`

It might be my stupidity as I have worked on python examples for quite a while and it works just fine.

**Comment by nikhilpandey360** [comment]
` g++ -std=c++11 -O3 -I.. ../dlib/all/source.cpp -lpthread -lX11 -ljpeg -DDLIB_JPEG_SUPPORT dnn_mmod_ex.cpp `
This worked. But not without the -ljpeg. Can you tell me why?
