### ISSUE TITLE
Multithreading in MMOD examples

### ISSUE THREAD

**Issue by nikhilpandey360** [davisking/dlib#645]
I was using the python examples(train_object_detector.py) and there was option of the no of threads to be used during training. I am trying to mutithread the dnn_mmod_ex.cpp for object detection purposes. The training set contains 10 images and a total of around 2000 annotated objects in a xml file.

Since training this on single core would take ages, why is that I can multithread that python script but not this c++?

**Comment by davisking** [comment]
You can set the same multi threading option in C++ as well.  It's one of the methods on the trainer object.

**Comment by nikhilpandey360** [comment]
Thanks.
