### ISSUE TITLE
Error in `convert_dlib_nets_to_caffe` w/ `dlib_face_recognition_resnet_model_v1`

### ISSUE THREAD

**Issue by bkj** [davisking/dlib#648]
Hi --

I was trying to convert the `dlib` face recognition model to `caffe` using the `convert_dlib_nets_to_caffe` utility. 

I wrote the net to XML by running 
```
    anet_type net;
    deserialize("dlib_face_recognition_resnet_model_v1.dat") >> net;
    net_to_xml(net, "dlib_face_recognition_resnet_model_v1.xml");
```
as part of `dnn_face_recognition_ex.cpp`.

When I run
```
./dtoc dlib_face_recognition_resnet_model_v1.xml 1 3 150 150
```
I get the following error:
```
Writing python part of model to dlib_face_recognition_resnet_model_v1_dlib_to_caffe_model.py
Writing weights part of model to dlib_face_recognition_resnet_model_v1_dlib_to_caffe_model.weights


*************** ERROR CONVERTING TO CAFFE ***************
No conversion between dlib pooling layer parameters and caffe pooling layer parameters found for layer 127
dlib_output_nc: 35
bottom_nc:      72
padding_x:      0
stride_x:       2
kernel_w:       3
pad_x:          1
```

Any thoughts?

**Comment by davisking** [comment]
Caffe can't represent all possible dlib networks.  So this is just what it is, unless you can figure out a way to construct an equivalent caffe network.

**Comment by bkj** [comment]
This error gets thrown after just a couple of layers that should work in Caffe, so sortof seems like a bug.  I'll try to track it down though, will post if I come up with anything.
```
max_pool<3,3,2,2,
    relu<
    affine<
    con<32,7,7,2,2,
    input_rgb_image_sized<150
>>>>
```

**Comment by davisking** [comment]
There are a lot of comments in the conversion code that explains these issues relative to caffe.  This in particular is discussed in some detail, so you will see what the issue is if you look there.  Anyway, it's not a bug, it's just that caffe has odd ways of calculating the output tensor sizes for pooling layers and they don't always work out.
