### ISSUE TITLE
unable to open training.xml for reading?

### ISSUE THREAD

**Issue by canmerve** [davisking/dlib#649]
I am trying to execute [fhog_object_detector_ex.cpp.](http://dlib.net/fhog_object_detector_ex.cpp.html) I give examples/faces directory as an argument. When compile it;

exception thrown!
ERROR: unable to open faces/training.xml for reading.

I did not change anything, however I cannot find a solution.

**Comment by davisking** [comment]
What did you type?

**Comment by canmerve** [comment]
/computerVision/dlib/examples/build$ ./fhog_object_detector_ex faces

in faces folder there are training.xml and testing.xml files.

**Comment by davisking** [comment]
Is there a faces folder in the build folder?

**Comment by canmerve** [comment]
Thanks for your help. It helps! Now I understand, it is a very silly question! Also thanks for dlib.
