### ISSUE TITLE
Comparable/hashable (d)rectangles in Python

### ISSUE THREAD

**Issue by hbredin** [davisking/dlib#65]
As of now, `dlib.drectangle` and `dlib.rectangle` instances are not comparable (nor hash-stable):

```python
>>> import dlib
>>> x1 = dlib.drectangle(0, 1, 2, 3)
>>> x2 = dlib.drectangle(0, 1, 2, 3)
>>> assert x1 == x2, 'Rectangles differ'
AssertionError: Rectangle differ
>>> assert hash(x1) == hash(x2), 'Hashes differ'
AssertionError: Hashes differ
```

Therefore, they cannot be used as dictionary keys for instance, nor in a set.
Solving this issue can be solved by implementing `__hash__` and `__eq__` methods in Python API.

I am willing to help but am not familiar with interfacing C and Python API so I don't really know where to start...

**Comment by uetoyo** [comment]
Python port is made by Boost Python Library, so you should start here...
http://www.boost.org/doc/libs/1_60_0/libs/python/doc/html/index.html
see...
https://github.com/davisking/dlib/blob/master/tools/python/src/rectangles.cpp

**Comment by patricksnape** [comment]
@hbredin #73 fixes your equality issue. However, `rectangle` and `drectangle` are not immutable and therefore they should not hash to the same value according to the Python hash semantics.

**Comment by davisking** [comment]
Sweet, thanks.

**Comment by hbredin** [comment]
Great. Thanks a lot.
