### ISSUE TITLE
Variable for hog is not building with different argument ?!

### ISSUE THREAD

**Issue by rahuldeo2047** [davisking/dlib#650]
Question : master.examples.fhog_ex.cpp#L53
 
https://github.com/davisking/dlib/blob/master/examples/fhog_ex.cpp#L53 

        // Now convert the image into a FHOG feature image.  The output, hog, is a 2D array
        // of 31 dimensional vectors.
        array2d<matrix<float,31,1> > hog;

is not compiling with any number other than 31. Am I missing something?

**Comment by davisking** [comment]
That's how it works.   I'm not sure what else you would expect.
