### ISSUE TITLE
Reinforcement learning neuronal network

### ISSUE THREAD

**Issue by VisionEp1** [davisking/dlib#651]
Hi,
Once again it's me.
Is there a way to use reinforcement learning with the dlib library. (With an neuronal network). For example input data in the network and after the result tell the network it performed good or bad. And use this as a training algorithm. I "only" saw Reinforcement algorithm in your library but not within a neuronal network.

As always thanks a lot.

**Comment by davisking** [comment]
You can define your own loss layers.  So if there is some particular thing you want to do like this you can do so.  The loss layer API is fully documented on the dlib web page.
