### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by GaryLensar** [davisking/dlib#653]
With only source.cpp included (no other code) the app runs but leaks two blocks of 16 bytes a block of 3200 and one of 608 bytes... If I define DLIB_ISO_CPP_ONLY there is no leak so it's in there somewhere.

Using VS2015 on Windows 10 64

**Comment by davisking** [comment]
This is not enough information to do anything useful with.  It's also probably not a memory leak.  But if you find a specific part of the code that you think leaks feel free to post about that.

**Comment by GaryLensar** [comment]
here are the steps to reproduce the leak ...
Use VS2015 to create an MFC dialog app. Add Source.cpp to the project (set to not using precompiled headers for source.cpp)

Compile and run... on exit will show leaks

**Comment by davisking** [comment]
I get how to do it.  My point is that those things aren't really leaks or don't matter.  In particular, there are things that look like leaks but are there to work around bugs in windows.  You can find extended discussion of some of them in comments in the code or in some of the github issues.
