### ISSUE TITLE
dnn_metric_learning_on_images_ex compile error

### ISSUE THREAD

**Issue by bearsprogrammer** [davisking/dlib#654]
Hello davis, i know this question is boring to you. But, i've been trying to compile the "dnn_metric_learning_on_images_ex" example for a few weeks, but it's not working and I need help.
My symptom is that i'm in an infinite loop while coding this example in my solution. 
To be precise, the compiler does not stop parsing the moment i declare 'net_type' in the main() function.
The code contents are as follows.

============================================
// training network type
using net_type = loss_metric<fc_no_bias<128, avg_pool_everything<
	level0<
	level1<
	level2<
	level3<
	level4<
	max_pool<3, 3, 2, 2, relu<bn_con<con<32, 7, 7, 2, 2,
	input_rgb_image
	>>>>>>>>>>>>;
///////////////////////////////////////////////////////////////////////
int main()
{
	auto objs = load_objects_list("../data/face/johns");

	cout << "objs.size(): " << objs.size() << endl;

	std::vector<matrix<rgb_pixel>> images;
	std::vector<unsigned long> labels;

	net_type net; // <- this 
============================================
I think there were a lot of questions like this. i saw the questions, set up cuDNN with cmake, and changed the code to e-forminov of 'MSVC 2015 supports C++ 11 now #243', but the result was the same. 
I would like you to advise me if i'm going in the wrong direction to solve this problem, or if there is a problem, or if there is a solution. Thank you.

My Window config: Window 10 x64, Core i7, CPU 4.0GHz, RAM 32GB, VGA NVIDIA GeForce GTX 970
Using IDE: MSVC 2015 update 3, dlib-19.4v
CUDA: cuda v8.0, cudnn v5.0

**Comment by davisking** [comment]
Visual studio just doesn't have good C++11 support.  So if the compiler is hanging or crashing, that's just what it is.  You should use a different compiler.  Me and others have spent a lot of time trying to work around the bugs in visual studio and it's as good as it's going to get until microsoft fixes visual studio.

**Comment by bearsprogrammer** [comment]
First, thanks for the quick answer.
If so, does another compiler mean to use Python or Eclipse? 
and one more question, is there an example of using the above example successfully in the same envirment(OS and PC spec) with Visual Studio?

**Comment by davisking** [comment]
No, Python is an entirely unrelated programming language and Eclipse is a text editor with a bunch of plugins.  Neither of these things are related to C++ or are even compilers.  Use GCC or clang.  Those compilers work.
