### ISSUE TITLE
Training the shape predictor takes too long.

### ISSUE THREAD

**Issue by liuyi999111** [davisking/dlib#655]
I try to use the dlib python interface to train shape predictor with 95 face landmarks.There are more than 8,000 images in the training data set. I did not change the parameters in train_shape_predictor.py, but changed the dataset. These are printed information

Training with cascade depth: 10
Training with tree depth: 2
Training with 500 trees per cascade level.
Training with nu: 0.05
Training with random seed:
Training with oversampling amount: 300
Training with feature pool size: 400
Training with feature pool region padding: 0
Training with lambda_param: 0.1
Training with 20 split tests.
Fitting trees...
Time remaining: 394.16 hours.

My CP information: cpu e5-2682，48 GB RAM.
Is it feasible to train these data with dlib?

**Comment by davisking** [comment]
Reduce the oversampling amount.  More generally, read the documentation.  All this stuff is explained in excruciating detail.
