### ISSUE TITLE
How can I use train_shape_predictor for an object not face?

### ISSUE THREAD

**Issue by canmerve** [davisking/dlib#656]
Hi, 
I am trying to train shape predictor for an object. I collected object photos. I labeled photos using dlib/imglab. I have training.xml, testing.xml, training_landmarks.xml, testing_landmarks.xml. However, I do not know how should I change shape_predictor_ex.cpp according to my object. Buy the way, my object is mug. 
example of labeling: 
![screenshot from 2017-06-20 20-11-28](https://user-images.githubusercontent.com/18442875/27382553-1eecb146-5690-11e7-91a3-accfc72831d3.png)

**Comment by davisking** [comment]
github issues are for reporting bugs or discussing dlib development, not for general programming or computer vision help.
