### ISSUE TITLE
libcublas.so.8.0 not found

### ISSUE THREAD

**Issue by GonzaBCCC** [davisking/dlib#657]
Hi, i am having this issue with import dlib after following the python installation instructions:

$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dlib-19.4.99-py2.7-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

I have searched for this in many posts but none aim to libcublas problems, most just ask about libcudart, so i opened this in hope someone may point me in the right direction.

I have Ubuntu 16.04 lts, cuda 8.0, cudnn v5.2, python 2.7, opencv 3.2.0 installed.

**Comment by davisking** [comment]
Something is wrong with your CUDA install, since dlib's build system found CUDA when compiled and linked with cublas.  But it looks like the runtime linker on your system doesn't know where cublas is.  Anyway, this isn't a dlib bug and there isn't anything I can do about it.  You just have to install CUDA correctly.  I would try reinstalling it.

**Comment by GonzaBCCC** [comment]
Ok, thanks for the tip!

**Comment by kanakst** [comment]
@GonzaBCCC 
Hello,
I have exactly the same issue.
Could you solve it?

**Comment by GonzaBCCC** [comment]
Hi kanakst, I tried reinstalling both CUDA and dlib, but this time i also manually linked the libcublas.so.8.0 going to the libraries folder and using **sudo ln** to link all versions of libcublas.so (it happens that my **dlib build system** found a different library name for libcublas, so i linked all of them).

Afterwards, and in order to make sure i performed:
**ldconfig /usr/local/lib**

In this case the problem was not CUDA, but **dlib** compiling to old lib filenames. Hope this helps you.

**Comment by davisking** [comment]
Did you install CUDA via the .deb packages provided by NVIDIA?  If you do that you should never have these incorrect symbolic links.
