### ISSUE TITLE
General tensor input layer to DNN

### ISSUE THREAD

**Issue by rdaiasy** [davisking/dlib#658]
Hi all,

I noticed that supported input layers to a DNN includes:
- RGB image for which each color is 8 bits (input_rgb_image, input_rgb_image_sized)
- matrix<rgb_pixel> - again 8bits per channel.
- input<T> where T is some kind of pixel type, for which pixel_traits<T::type> is defined. In the code one can find that that a grayscale pixel type is defined for some kind of scalar (assuming floating point pixel value is OK?)

For my applications I need to have a generic input image with plurality of floating point channels - some kind of generic tensor.

Is it possible in dlib to define a DNN with such kind of input?

I thought about defining an input of a concatenation of many gray scale images - is this possible?

Thanks in advance,

Ron.

**Comment by davisking** [comment]
That's all correct.   If you want to give something else as input you can define your own input layers that take any input you want.  The input layer interface is fully documented.  It's only a few functions you have to implement, and all are described in great detail.
