### ISSUE TITLE
Problem with library installation using cmake

### ISSUE THREAD

**Issue by pixelou** [davisking/dlib#66]
Hello,

I know building the project as a library is not the common way of using it, but since the CMakeLists.txt is written for it, and because it is convenient for cmake-based projects, I would like to report something.

Headers installation has a strange behaviour here and installs the wrong headers (the ones necessary for the build only). I checked cmake's documentation and it seems your code is right but it still behaves strangely here (cmake 3.4.1). I propose the following modification:

```diff
--- a/dlib/CMakeLists.txt	2015-10-29 01:27:41.000000000 +0100
+++ b/dlib/CMakeLists.txt	2016-01-08 09:13:10.410043662 +0100
@@ -429,7 +429,8 @@
 
        install(DIRECTORY ${CMAKE_SOURCE_DIR}/ DESTINATION include/dlib
                FILES_MATCHING PATTERN "*.h"
-               REGEX "${CMAKE_CURRENT_BINARY_DIR}" EXCLUDE)
+               REGEX "config.h" EXCLUDE 
+               REGEX "revision.h" EXCLUDE)
 
 
        configure_file(${CMAKE_SOURCE_DIR}/../dlib/config.h.in ${CMAKE_CURRENT_BINARY_DIR}/config.h)
```

Also I don't understand the role of CONF_INSTALL_PATH, as it seems to ignore the standard CMAKE_INSTALL_PREFIX variable. Below is a proposal of a modification.

```diff
--- a/dlib/CMakeLists.txt	2015-10-29 01:27:41.000000000 +0100
+++ b/dlib/CMakeLists.txt	2016-01-08 09:13:10.410043662 +0100
@@ -448,7 +449,6 @@
             NAMESPACE dlib::
             DESTINATION ${ConfigPackageLocation})
 
-       set(CONF_INSTALL_PATH "\${dlib_CMAKE_DIR}/../../../")
        configure_file(dlibConfig.cmake.in "${CMAKE_CURRENT_BINARY_DIR}/config/dlibConfig.cmake" @ONLY)
 
        include(CMakePackageConfigHelpers)

--- a/dlib/dlibConfig.cmake.in	2016-01-08 09:00:05.647628418 +0100
+++ b/dlib/dlibConfig.cmake.in	2016-01-08 09:00:40.744104951 +0100
@@ -22,11 +22,7 @@
 # Compute paths
 get_filename_component(dlib_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
 
-if(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} VERSION_LESS 2.8)
-    get_filename_component(dlib_INSTALL_PATH "@CONF_INSTALL_PATH@" ABSOLUTE)
-else()
-    get_filename_component(dlib_INSTALL_PATH "@CONF_INSTALL_PATH@" REALPATH)
-endif()
+set(dlib_INSTALL_PATH "@CMAKE_INSTALL_PREFIX@")
 
 set(dlib_INCLUDE_DIRS "${dlib_INSTALL_PATH}/include")

 
```

**Comment by davisking** [comment]
What gets installed that shouldn't?  I just did a test and CMAKE_INSTALL_PREFIX worked as expected and the only files installed were header files and library files.

**Comment by pixelou** [comment]
It was copying the excluded files 'config.h' and 'revision.h' only, but it does seem to work for me again. It might have been a problem with an unclean build tree...
Sorry for the inconvenience, you can close.

**Comment by davisking** [comment]
No worries
