### ISSUE TITLE
Raspberry Pi 3B python3 facerec.compute_face_descriptor() crash after multiple calls

### ISSUE THREAD

**Issue by terencezl** [davisking/dlib#660]
Hi Davis, I tried installing dlib through pip as well as compile from source, but these two installations both gave the below problem. It doesn't always happen, but when it happens, the program either hangs with 400% CPU (all cores) usage, or exits abruptly with a segmentation fault.

```
import dlib
import skimage.io
import skimage.transform

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')
facerec = dlib.face_recognition_model_v1('classifiers/dlib_face_recognition_resnet_model_v1.dat')

frame = skimage.io.imread('frame_resized.jpg')  # it's a 300x400 image with a face
rects = detector(frame, 0)
landmarks = predictor(frame, rects[0])  # until here everything is fine

while True:
    vec = facerec.compute_face_descriptor(frame, landmarks)
    print(vec)
```

I don't have another Pi so don't know if it's reproducible. On my Pi it's quite consistent.

**Comment by davisking** [comment]
Huh.  It doesn't happen in my usage.  Are you sure you aren't just running out of RAM or something mundane like that?

**Comment by terencezl** [comment]
Don't think so. Mem split is 128 MB with 1024MB swapfile.

![2017-06-26-085121_1824x984_scrot](https://user-images.githubusercontent.com/3190888/27540074-cc2ae980-5a4c-11e7-8ab8-fbda4b8cd0f1.png)

**Comment by terencezl** [comment]
Any way to profile the calls even with a process hang or fault?

I'll try the C++ version when I figure out the correct syntax.

**Comment by davisking** [comment]
It's not so easy from python.  I would debug it in pure C++.

**Comment by diegodgs** [comment]
I have a similar problem. I have a micro webservice with a dnn_mmod_rect detector, when i use jmeter to stress my system. I have a segmentation fault error. I'm using python2. If I isolate dlib portion code and make someone generic computation with a similar cpu time. I dont get error.

**Comment by terencezl** [comment]
OK I compiled an example, edited from dnn_face_recognition_ex.cpp:

I removed the window drawing code and the code below:
```
    std::vector<matrix<float,0,1>> face_descriptors = net(faces);
```

I put a loop around it:

```
for (int i = 0; i < 10; i++) {
    std::vector<matrix<float,0,1>> face_descriptors = net(faces);
    cout << "round " << i << endl;
}
```

The result is

```
round 0
round 1
round 2
round 3
Segmentation fault
```

Sometimes it can go to round 6. Sometimes it doesn't seg fault but hangs there at 400% CPU usages. This is exactly the same behavior as I called it through the Python binding.

**Comment by davisking** [comment]
Try disabling the use of whatever BLAS library you are using.  It's entirely possible that there is a bug in the BLAS that causes this.

**Comment by davisking** [comment]
Well, and really, you need to learn how to use a debugger to find the problem.  If you google gdb you will find out how to find exactly where the crash happened.

**Comment by davisking** [comment]
But basically, you compile the program with -ggdb as an option.  Then run it like this:

```
bash prompt$ gdb ./your_program
(gdb) r
```

**Comment by terencezl** [comment]
Cool will try.

**Comment by terencezl** [comment]
Froze/Fault at a libopenblas call.

Replaced libopenblas for libatlas and liblapack, and everything works now.

Thanks!

**Comment by chpmk98** [comment]
@terencezl when you say "replaced libopenblas for libatlas and liblapack", how do you go about doing that? I'm getting the same problem as you are...

**Comment by DanceDance** [comment]
> @terencezl when you say "replaced libopenblas for libatlas and liblapack", how do you go about doing that? I'm getting the same problem as you are...

I've uninstalled openblas that was previously installed with "apt-get remove libopenblas-dev" and installed libatlas with " sudo apt-get install libatlas-base-dev libatlas-dev"

**Comment by Heramb001** [comment]
> > @terencezl when you say "replaced libopenblas for libatlas and liblapack", how do you go about doing that? I'm getting the same problem as you are...
> 
> I've uninstalled openblas that was previously installed with "apt-get remove libopenblas-dev" and installed libatlas with " sudo apt-get install libatlas-base-dev libatlas-dev"

I tried those steps, but no luck, can you please let me know if it worked for you.
