### ISSUE TITLE
the efficiency is not right when i use C++ to detect face...

### ISSUE THREAD

**Issue by TianBinyu** [davisking/dlib#661]
Dear Sir~
I am sorry to bother you~
I want to detect the faces in one 1600*1200 size image, but it is strange:
1.if i use python code to detect the face, it only take less than 1 second.
2.if i use c++ code to detect the face, it will take more than 15 seconds...

Python code:
    img = cv2.imread(imgpath)
    detector = dlib.get_frontal_face_detector()
    dets = detector(img, 1)
...
C++ code:
dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();
 dlib::matrix<dlib::rgb_pixel> img;
 dlib::load_image(img, imgpath);
std::vector<dlib::rectangle> facesNew = detector(img);	
...

detector() api will take more than 15 seconds in C++, which will only take less than 1 second...
(I test the code in same linux computer)
If any one can help me to fix this issue?
Thank you very much~~

**Comment by Amos-zq** [comment]
http://dlib.net/faq.html#Whyisdlibslow

**Comment by TianBinyu** [comment]
@Amos-zq 
Dear Amos-zq
I am not using Visual Studio to test the code, i am using linux to test the code,like this:
g++ -std=c++1y *.cpp $(pkg-config --libs opencv lapack) -ldlib .................

**Comment by Amos-zq** [comment]
Maybe you should enable either SSE4 or AVX instruction use in cmake-gui.

**Comment by e-fominov** [comment]
@TianBinyu , try adding this switches to g++ command line: `-mavx -Ofast`

**Comment by TianBinyu** [comment]
@e-fominov 
Thank you for your help~It works well for me~
And i have another question,i have one small image (size: 480*290/faces: 8)
My python code above  can detect 8 face.
But the c++ code above only can detect 0 face...
After i added :
dlib::pyramid_up(img);
Then c++ code will detect 8 faces.
If python will do the pyramid_up auto?


@ Amos-zq  thank you for your reply,too :)~

**Comment by e-fominov** [comment]
@TianBinyu , yes python makes upsamling:
```Python
dets = detector(img, 1)
```
If you will change 1 to 0, it will disable pyramid_up

**Comment by TianBinyu** [comment]
@e-fominov Thank you very much~~ you have helped me a lot~ :)  :+1: 
I will close this issue now.

**Comment by TianBinyu** [comment]
@e-fominov 
I have fixed this issue, thank you very much~
	long old_nc = img2.nc();
	dlib::pyramid_up(img2);
	long new_nc = img2.nc();
...shapes[0].part(i).x() * old_nc / new_nc...
