### ISSUE TITLE
dlib_face_detection_dataset-2016-09-30.tar.gz

### ISSUE THREAD

**Issue by scott-vsi** [davisking/dlib#664]
In examples/dnn_mmod_face_detection_ex.cpp you note that the model [mmod_human_face_detector.dat](http://dlib.net/files/mmod_human_face_detector.dat.bz2) was trained with a slightly modified dnn_mmod_ex.cpp with training data from http://dlib.net/files/data/dlib_face_detection_dataset-2016-09-30.tar.gz. However, dnn_mmod_ex.cpp tries to load training.xml and testing.xml, which don't exist. Although dlib_face_detection_dataset includes faces_2016_09_30.xml, it doesn't split all of the data into train and test (and val) directories, so it wasn't clear if/how the rest of the data was split.

**Comment by davisking** [comment]
That example is meant to be an educational document, not a log of how the face detector was trained.  So you will have to modify it to accommodate your project needs.  As for the included dlib face detector, it was trained on the whole dataset.

**Comment by scott-vsi** [comment]
I see. Thanks
