### ISSUE TITLE
Use an image buffer in face detector without copying its contents

### ISSUE THREAD

**Issue by fabioperez** [davisking/dlib#665]
[Question]

I'm using the dlib face detector similarly to the [face_detection_ex.cpp](dlib.net/face_detection_ex.cpp.html). However, I want to pass an image buffer (`uint8_t* img`) with dimensions `width`x`height`.

Is it possible to create an `array2d` that wraps the image buffer without copying its contents? Currently, I'm using `assign_pixel` to copy from the image buffer to an `array2d` object.

**Comment by davisking** [comment]
You can make your own image objects and pass them in.  Google dlib's generic image interface.  For example, cv_image is an example of what you are asking about.

**Comment by fabioperez** [comment]
Thanks! It worked!

Links for reference:
http://dlib.net/dlib/opencv/cv_image.h.html
http://dlib.net/dlib/image_processing/generic_image.h.html

**Comment by bakercp** [comment]
Here's one other reference for those doing this - I adapted openFrameworks image types to work without copying here:

https://github.com/bakercp/ofxDlib/blob/master/libs/ofxDlib/include/ofx/Dlib/Types.h
