### ISSUE TITLE
 undefined symbol: USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_

### ISSUE THREAD

**Issue by zqr688** [davisking/dlib#667]
I compiled my **jni** project as the examples and successfully generated libface.so file on centos7, But when I  called it, It threw an exception
> Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/face_build/libface.so: /opt/face_build/libface.so: undefined symbol: USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
> 	at java.lang.Runtime.load0(Runtime.java:795)
> 	at java.lang.System.load(System.java:1062)
> 
Here's the CMakeLists.txt information
> cmake_minimum_required(VERSION 2.8.12)
> PROJECT(face)
> aux_source_directory(. DIR_SRCS)
> include(../dlib/cmake)
> ADD_LIBRARY(face SHARED ${DIR_SRCS})
> add_dependencies(face dlib::dlib )

**Comment by davisking** [comment]
I don't know what to say that isn't already said in the text of the error.

**Comment by zqr688** [comment]
How to deal with it，Is CMakeLists.txt missing something?

**Comment by davisking** [comment]
Who knows.  You haven't even posted what you are doing.

**Comment by zqr688** [comment]
I just want to compile the following project into a libface.so file that lets Java can call it
[face_recognition.zip](https://github.com/davisking/dlib/files/1114953/face_recognition.zip)

**Comment by zqr688** [comment]
I just want to compile the following jni project in the Linux environment to build the libface.so file so that Java can call it. Through the Cmake way , libface.so file can be successfully generated, But threw the above exception when java called it. Is CMakeLists.txt missing something?
The code is as follows：
**com_test_Dlib.h**
`
#include "jni.h"


#ifndef _Included_com_test_Dlib
#define _Included_com_test_Dlib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_intple_test_Dlib_verify
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
`

**dnn_face_recognition_jni.cpp** 
`
#include "jni.h"
#include "com_test_Dlib.h"
#include <dlib/gui_widgets.h>
#include <dlib/clustering.h>
#include <dlib/string.h>
#include <dlib/dnn.h>
#include <dlib/image_io.h>
#include <dlib/image_processing/frontal_face_detector.h>

using namespace dlib;
using namespace std;


template <template <int, template<typename>class, int, typename> class block, int N, template<typename>class BN, typename SUBNET>
using residual = add_prev1<block<N, BN, 1, tag1<SUBNET>>>;

template <template <int, template<typename>class, int, typename> class block, int N, template<typename>class BN, typename SUBNET>
using residual_down = add_prev2<avg_pool<2, 2, 2, 2, skip1<tag2<block<N, BN, 2, tag1<SUBNET>>>>>>;

template <int N, template <typename> class BN, int stride, typename SUBNET>
using block = BN<con<N, 3, 3, 1, 1, relu<BN<con<N, 3, 3, stride, stride, SUBNET>>>>>;

template <int N, typename SUBNET> using ares = relu<residual<block, N, affine, SUBNET>>;
template <int N, typename SUBNET> using ares_down = relu<residual_down<block, N, affine, SUBNET>>;

template <typename SUBNET> using alevel0 = ares_down<256, SUBNET>;
template <typename SUBNET> using alevel1 = ares<256, ares<256, ares_down<256, SUBNET>>>;
template <typename SUBNET> using alevel2 = ares<128, ares<128, ares_down<128, SUBNET>>>;
template <typename SUBNET> using alevel3 = ares<64, ares<64, ares<64, ares_down<64, SUBNET>>>>;
template <typename SUBNET> using alevel4 = ares<32, ares<32, ares<32, SUBNET>>>;

using anet_type = loss_metric<fc_no_bias<128, avg_pool_everything<
	alevel0<
	alevel1<
	alevel2<
	alevel3<
	alevel4<
	max_pool<3, 3, 2, 2, relu<affine<con<32, 7, 7, 2, 2,
	input_rgb_image_sized<150>
	>>>>>>>>>>>>;



std::vector<matrix<rgb_pixel>> jitter_image(
	const matrix<rgb_pixel>& img
);


JNIEXPORT jboolean JNICALL Java_com_intple_test_Dlib_verify
(JNIEnv *env, jobject jobj, jstring path1, jstring path2, jstring landmark, jstring model, jdouble threshold)
{

	jboolean  result = false;
	try {
		const char* impath1 = NULL;
		const char* impath2 = NULL;
		const char* landmarks = NULL;
		const char* modelpath = NULL;	
		impath1 = (env)->GetStringUTFChars(path1, NULL);
		impath2 = (env)->GetStringUTFChars(path2, NULL);
		landmarks = (env)->GetStringUTFChars(landmark, NULL);
		modelpath = (env)->GetStringUTFChars(model, NULL);



		frontal_face_detector detector = get_frontal_face_detector();

		shape_predictor sp;
		deserialize(landmarks) >> sp;
		anet_type net;
		deserialize(modelpath) >> net;

		matrix<rgb_pixel> img;
		matrix<rgb_pixel> img1;
		load_image(img, impath1);
		load_image(img1, impath2);
		image_window win(img);
		image_window win1(img1);
		std::vector<matrix<rgb_pixel>> faces;
		for (auto face : detector(img))
		{
			auto shape = sp(img, face);
			matrix<rgb_pixel> face_chip;
			extract_image_chip(img, get_face_chip_details(shape, 150, 0.25), face_chip);
			faces.push_back(move(face_chip));

			win.add_overlay(face);
		}
		for (auto face1 : detector(img1))
		{
			auto shape1 = sp(img1, face1);
			matrix<rgb_pixel> face_chip1;
			extract_image_chip(img1, get_face_chip_details(shape1, 150, 0.25), face_chip1);
			faces.push_back(move(face_chip1));
	
			win1.add_overlay(face1);
		}

		if (faces.size() == 0)
		{
			cout << "No faces found in image!" << endl;
			return false;
		}

		std::vector<matrix<float, 0, 1>> face_descriptors = net(faces);
		std::vector<sample_pair> edges;
		for (size_t i = 0; i < face_descriptors.size(); ++i)
		{
			for (size_t j = i + 1; j < face_descriptors.size(); ++j)
			{
				cout << "score: " << length(face_descriptors[i] - face_descriptors[j]) << endl;
				if (length(face_descriptors[i] - face_descriptors[j]) < threshold)
					result = true;
			}
		}
	}
	catch (std::exception& e) {
		std::cout << "Exception caught" << std::endl;
		std::cout << e.what() << std::endl;
	}
	return result;

}

std::vector<matrix<rgb_pixel>> jitter_image(
	const matrix<rgb_pixel>& img
)
{
	thread_local random_cropper cropper;
	cropper.set_chip_dims(150, 150);
	cropper.set_randomly_flip(true);
	cropper.set_max_object_height(0.99999);
	cropper.set_background_crops_fraction(0);
	cropper.set_min_object_height(0.97);
	cropper.set_translate_amount(0.02);
	cropper.set_max_rotation_degrees(3);

	std::vector<mmod_rect> raw_boxes(1), ignored_crop_boxes;
	raw_boxes[0] = shrink_rect(get_rect(img), 3);
	std::vector<matrix<rgb_pixel>> crops;

	matrix<rgb_pixel> temp;
	for (int i = 0; i < 100; ++i)
	{
		cropper(img, raw_boxes, temp, ignored_crop_boxes);
		crops.push_back(move(temp));
	}
	return crops;
}

`
**CMakeLists.txt**

> 
>  cmake_minimum_required(VERSION 2.8.12)
> 
> PROJECT(face)
> aux_source_directory(. DIR_SRCS)
> include(../dlib/cmake)
> 
> ADD_LIBRARY(face SHARED ${DIR_SRCS})
> add_dependencies(face dlib::dlib )

**Comment by zqr688** [comment]
How to deal with it？Thanks a lot!

**Comment by davisking** [comment]
This has nothing to do with dlib.  You just don't know how to compile and work with JNI.  You should read a C++/JNI tutorial.  

I would start by reading this blog post that has an example of how to call C++ from JNI.  It tells you exactly what to do.  If you follow the instructions it will work.

**Comment by zqr688** [comment]
Thank you, I am a C ++ novice, please forgive me.！
