### ISSUE TITLE
ImportError: dlopen(/Users/liuhuichuan/anaconda2/envs/py2/lib/python2.7/site-packages/dlib-19.4.99-py2.7-macosx-10.7-x86_64.egg/dlib/dlib.so, 2): Library not loaded: libpng15.15.dylib

### ISSUE THREAD

**Issue by HuichuanLiu** [davisking/dlib#668]
`>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liuhuichuan/anaconda2/envs/py2/lib/python2.7/site-packages/dlib-19.4.99-py2.7-macosx-10.7-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/Users/liuhuichuan/anaconda2/envs/py2/lib/python2.7/site-packages/dlib-19.4.99-py2.7-macosx-10.7-x86_64.egg/dlib/dlib.so, 2): Library not loaded: libpng15.15.dylib
  Referenced from: /Users/liuhuichuan/anaconda2/envs/py2/lib/python2.7/site-packages/dlib-19.4.99-py2.7-macosx-10.7-x86_64.egg/dlib/dlib.so
  Reason: image not found`
This occurs when I tried to import it in python2.7
It was wired coz dlib was successfully installed and imported and used in my macos 10.12.5 in the past few days. Accidentally I removed the build dir under dlib today so I had to do a reinstall in the same machine ,the same conda env, the same location. 
I tried to installed it with pip or from github, but both led to the import error in python, which I never seen before.
Any idea?

**Comment by davisking** [comment]
No idea.  Something is wrong with your system since sometimes it can find libpng and sometimes it can't.  Google LD_LIBRARY_PATH and how runtime linking is setup on your computer.
