### ISSUE TITLE
compute_face_descriptor fails with numpy array

### ISSUE THREAD

**Issue by paulaceccon** [davisking/dlib#677]
I'm trying to solve [this](https://stackoverflow.com/questions/44885779/python-dlib-compute-face-descriptor/44886021#44886021) issue.

I have an 50x50 image as a numpy array and I'm trying to call:

`face_descriptor.compute_face_descriptor(image, shape)`

Which results in:

**RuntimeError: Unsupported image type, must be 8bit gray or RGB image.**

I have tried to do:

1. x = x[:, :, np.newaxis]
2. To convert x to image using PIL and scipy.misc
3. To convert it to OpenCV mat.

I have no clue of what I should do to use this method properly.

**Comment by davisking** [comment]
The example shows you how to use it.  If you run it without modifying the code it will work.

**Comment by paulaceccon** [comment]
I'm just reading another set of images. It doesn't make sense that this makes the code stop working.

**Comment by paulaceccon** [comment]
```
predictor_model = 'Resources/shape_predictor_68_face_landmarks.dat'
embeddings = 'Resources/dlib_face_recognition_resnet_model_v1.dat'

# Create a HOG face detector using the built-in dlib class
face_detector = dlib.get_frontal_face_detector()
face_pose_predictor = dlib.shape_predictor(predictor_model)
face_aligner = openface.AlignDlib(predictor_model)
face_descriptor = dlib.face_recognition_model_v1(embeddings)

labels = []
images = []
size = 50

path = 'Data/yalefaces'
for p in os.listdir(path):
    images.append(io.imread(os.path.join(path, p), as_grey=True))
    labels.append(int(p.split('.')[0].replace('subject', ''))-1) # original from 1 to 15
    
n_targets = len(set(labels))

def get_embeddings(image):
    face_rect = dlib.rectangle(left=0, top=0, right=size, bottom=size)
    # Get the landmarks/parts for the face in box face_rect.
    shape = face_pose_predictor(image, face_rect)
    # Compute the 128D vector that describes the face in img identified by
    # shape.  In general, if two face descriptor vectors have a Euclidean
    # distance between them less than 0.6 then they are from the same
    # person, otherwise they are from different people.  He we just print
    # the vector to the screen.
    return face_descriptor.compute_face_descriptor(image, shape, 1)

for x in images:
    print(x.shape)
    l = get_embeddings(x)
```

This is my full code. Not much of changes.

**Comment by davisking** [comment]
What happens when you run the example without any code changes at all?

**Comment by paulaceccon** [comment]
Same thing:

```
Data/yalefaces
Processing file: Data/yalefaces\subject01.glasses.gif
Number of faces detected: 1
Detection 0: Left: 110 Top: 82 Right: 239 Bottom: 211
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-236587bcd4fa> in <module>()
     42         # person, otherwise they are from different people.  He we just print
     43         # the vector to the screen.
---> 44         face_descriptor = facerec.compute_face_descriptor(img, shape)
     45         print(face_descriptor)
     46         # It should also be noted that you can also call this function like this:

RuntimeError: Unsupported image type, must be RGB image.
```

**Comment by davisking** [comment]
Post that image somewhere and I'll take a look.

**Comment by paulaceccon** [comment]
Ok, thank you. You can find everything here: https://github.com/paulaceccon/mlPlayground.  The notebook is FaceRecognizer.ipynb and the images are under Data. Thank you again.

**Comment by davisking** [comment]
That's not an RGB image, as the error says.  Use an RGB image or convert the image to RGB.

**Comment by paulaceccon** [comment]
Sorry if this is stupid, but I didn't understood what is the expected input. For example, I tried to convert,  by code, my 2D (1 channel) data to 3 channels (like numpy.array([x, x, x]) and this didn't work either. Is there an expected format in terms of array, tensor, etc?

**Comment by davisking** [comment]
Use some program to convert the image file to RGB, or google how to do it.  This forum is for reporting dlib bugs or discussing dlib development.  It's not the place to ask for generic programming advice or tutorials.  There is already a lot of that available on the net elsewhere.

**Comment by paulaceccon** [comment]
Ok, thank you. I was JUST trying to understanding the input type, as the doc doesn't say if it is a numpy.array or whatever.

```
compute_face_descriptor((face_recognition_model_v1)arg1, (object)img, (full_object_detection)face[, (int)num_jitters=0]) → vector :
Takes an image and a full_object_detection that references a face in that image and converts it into a 128D face descriptor. If num_jitters>1 then each face will be randomly jittered slightly num_jitters times, each run through the 128D projection, and the average used as the face descriptor.
```
