### ISSUE TITLE
Is there any Java wrapper created for dlib?

### ISSUE THREAD

**Issue by Bahramudin** [davisking/dlib#681]
I looking a Java wrapper of the dlib, is it possible or not? Thanks!!

**Comment by davisking** [comment]
It's easy to do with SWIG.  See here for an example: http://blog.dlib.net/2014/10/mitie-v03-released-now-with-java-and-r.html

**Comment by Bahramudin** [comment]
@davisking I have compiled the source and generated a jar file with 4 DLL files. And I saw some examples it was good, it was all for text. Is it possible or not to use in images, like face recognition and so on. If yes, then is there any example to show how to use this API for recognition purpose. Thanks!!

**Comment by davisking** [comment]
You can code up anything you want.  I don't have any more examples though.

**Comment by Bahramudin** [comment]
@davisking Hmm, so the problem is how to start playing images with. Anyway, hope in the soon feature there be a good documentation for better use of the API.

**Comment by davisking** [comment]
The dlib API is fully documented.  So is the SWIG API and the JNI API.  You are asking about Java JNI/SWIG questions.  You should refer yourself to their documentation.

**Comment by tahaemara** [comment]
I added a java wrapper to simply use dlib face detector, facial landmarks, and face embedding model.
https://github.com/tahaemara/jdlib
