### ISSUE TITLE
ordering of singular values by svd()

### ISSUE THREAD

**Issue by rjdmoore** [davisking/dlib#682]
The singular values returned by svd() (when not compiled with LAPACK support) are in no particular order - as per the docs. However, when compiled with LAPACK support, or when running other similar functions (e.g. svd_fast()), the singular values **are** ordered. This obviously affects the other returned matrices as well.

There is no error with the output - the matrices returned by svd() are consistent. But I think it is unexpected that the result returned by the function is dramatically different depending on whether or not dlib was compiled with LAPACK support.

**Comment by davisking** [comment]
There is in general no guarantee on singular value ordering with LAPACK either.  You are just getting lucky in those other cases.
