### ISSUE TITLE
Segfault in loss_metric

### ISSUE THREAD

**Issue by pasbi** [davisking/dlib#683]
I tried to run [this example](https://github.com/davisking/dlib/blob/master/examples/dnn_face_recognition_ex.cpp), but because of compiler errors in the `jitter_image` function, I removed the very same and also all code after line 137. [My code](https://gist.github.com/pasbi/c983f3343545d4d6152caf590b942575).
I don't use the `bald_guys.jpg` but `bald_guys.bmp` because jpg didn't work out of the box.

The example should still work fine, doesn't it?
Well the line
```std::vector<matrix<float,0,1>> face_descriptors = net(faces);``` 
raises a segfault:
```./a.out bald_guys.bmp
0
[1]    25645 segmentation fault  ./a.out bald_guys.bmp
./a.out bald_guys.bmp  33.99s user 0.26s system 103% cpu 33.024 total
```
I find it quite hard to search for this since `net` is actually `loss_metric<...>` which is `add_loss_layer<...>`.

I know that the segfault happens even if I change the line to 
```net(faces);``` 

So I'm a bit lost. What happens here, and what goes wrong?

**Comment by davisking** [comment]
I don't know.  The code looks fine.  Maybe your compiler is broken (it couldn't compile the other code after all).

**Comment by pasbi** [comment]
I don't think that g++ is broken.
Maybe it's because I copied the headers and libs manually to ~/.local after compiling? I have no sudo on this machine. I mean it could find the headers and also linking worked.

The problem with the example code was, that g++ said `random_cropper` had no method `set_max_object_size`. I use the most recent release (v19.4), downloaded as tar.gz from github.

**Comment by davisking** [comment]
Oh, yes, you obviously messed up the dlib files, don't do that :)

Just use CMake.  The example programs shows you how to use it.
