### ISSUE TITLE
Dlib face recognition example: mutex lock

### ISSUE THREAD

**Issue by rayjs** [davisking/dlib#684]
Thank you for this great library. I am currently facing this odd problem involving thread. Face recognition is part of my small application. When I remove face recognition the application runs fine when I include dlib face recognition, it compiles successfully but throws this run time error. I have tried running dlib face recognition class both on the main thread and on a background thread but I have had no luck so far. 

I have wrapped dlibs face recognition example in a class and I have not even instantiated the class but still I am getting this run time error. 

`../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion 'mutex->__data.__owner == 0' failed.
Aborted`

Process returned 134 (0x86)   execution time : 0.045 s
Press ENTER to continue.

Please help. Thank you so much.

**Comment by davisking** [comment]
When writing threaded programs, in general, you can't touch an object from multiple threads without synchronization.  So don't touch an instance of the network from multiple threads at the same time.

**Comment by rayjs** [comment]
Hi Davis,
Perhaps I was not clear. Yes that right but here its just one thread that is doing the face recognition and yet I get this lock. I have not even instantiated face recognition class (which wraps the face recognition example from dlib).

**Comment by davisking** [comment]
I doubt this has anything to do with dlib.  But if you can post a small program that reproduces the error then I'll take a look.   This includes posting complete steps to reproduce the error.
