### ISSUE TITLE
face recognition evaluation against LFW

### ISSUE THREAD

**Issue by vedrusss** [davisking/dlib#688]
Hi Davis,

I'm trying to repeat face recognition accuracy results you have reported on http://vis-www.cs.umass.edu/lfw/results.html#dlib (99,38%) but with no success. My results are just 97,7% (with 0,635 threshold).
What I do is
1) obtain face descriptors for aligned LFW faces;
2) compute euclidean distances while obtaining threshold and accuracy.

May be I do anything wrong? or there are some tricks?

Thanks for your great job. Dlib is really cool!

**Comment by davisking** [comment]
There aren't any funny tricks.  You must be doing something wrong.  You can find the entire test script I used to test it here: http://dlib.net/files/dlib_face_recognition_resnet_model_v1_lfw_test_scripts.tar.bz2

**Comment by vedrusss** [comment]
Thanks a lot, Davis!

**Comment by Lennon-cheng** [comment]
@davisking Hi, I want to use this lfw test script (http://dlib.net/files/dlib_face_recognition_resnet_model_v1_lfw_test_scripts.tar.bz2 ) to evaluation performance on my model. If I only replace 'dlib_face_recognition_resnet_model_v1.dat' into my model.dat? How can I convert model  format from 'caffemodel' to dat? thank you very much!
