### ISSUE TITLE
cc1plus compile warning:  [-Wfloat-equal]  [-Werror=sign-compare] [-Werror=overloaded-virtual]

### ISSUE THREAD

**Issue by burkun** [davisking/dlib#694]
env = gcc 4.8.5

in  **float_details.h**  line 68 -70, the functions will call **convert_from_T**, which has equal operations between float, double variables

val == -std::numeric_limits<T>::infinity()

the temporary solution i choosed is add

> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wfloat-equal"
> .......
> #pragma GCC diagnostic pop

in these header files

more
tensor_tools.cpp:104:48: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

more and more 
[-Wfloat-equal]
> ./geometry/point_transforms.h//float-equal
> ./geometry/drectangle.h// ignored warning, float-equal
> ./dnn/tensor_tools.cpp//float-equal
> ./dnn/cpu_dlib.cpp//float-equal
> ./optimization/optimization_search_strategies.h// ignored warning, float-equal
> ./optimization/optimization.h// ignored warning, float-equal
> ./optimization/optimization_line_search.h// ignored warning, float-equal
> ./pixel.h// float-equal
> ./matrix/matrix_lu.h// ignored warning, float-equal
> ./matrix/matrix_assign.h// ignored warning, float-equal
> ./matrix/matrix_trsm.h// ignored warning, float-equal
> ./matrix/matrix_math_functions.h// ignored warning, float-equal
> ./matrix/matrix_la.h// ignored warning, float-equal
> ./console_progress_indicator.h//float-equal
> ./float_details.h//float-equal

[-Werror=overloaded-virtual]
> dlib/all/../server/server_iostream.h:77:14: error: 'virtual void dlib::server_iostream::on_connect(dlib::connection&)' was hidden [-Werror=overloaded-virtual]

> dlib/all/../server/server_http.h:196:22: error:   by 'virtual void dlib::server_http::on_connect(std::istream&, std::ostream&, const string&, const string&, short unsigned int, short unsigned int, dlib::uint64)' [-Werror=overloaded-virtual]

**Comment by burkun** [comment]
the temporary i choose is add this in these header files 
#pragma GCC diagnostic ignored "-Wfloat-equal"

**Comment by burkun** [comment]
more 
tensor_tools.cpp:104:48: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

**Comment by davisking** [comment]
These are silly warnings.  Sometimes the right thing to do is compare for equality or overload.
