### ISSUE TITLE
./dtest: undefined symbol: dgesvd_

### ISSUE THREAD

**Issue by feiyang2010jin** [davisking/dlib#699]
building  success  but  run give out wrong instruction:

./dtest: symbol lookup error: ./dtest: undefined symbol: dgesvd_

**Comment by davisking** [comment]
What did you type to build it?

**Comment by feiyang2010jin** [comment]
I build the test file on ubuntu.  It did not have problem in 18.18 ,but cannot run for the newest version 19.4

**Comment by feiyang2010jin** [comment]
Running test_active_learning | ./dtest: symbol lookup error: ./dtest: undefined symbol: dgesvd_

**Comment by feiyang2010jin** [comment]
@davisking
