### ISSUE TITLE
Python dlib module has no image_window attribute?

### ISSUE THREAD

**Issue by gstro** [davisking/dlib#7]
Hi! Thanks for making a Python API for dlib -- I'm excited to try it out (once I get it working)!

I compiled the examples today and tried to run `train_object_detector.py` but it gave the following error:
```
File "train_object_detector.py", line 95, in <module>
    win_det = dlib.image_window()
AttributeError: 'module' object has no attribute 'image_window'
```
I get the same error from the Python interpreter:
```
$ python
Python 2.7.9 (default, Jan 18 2015, 00:53:20) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> window = dlib.image_window()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'image_window'
>>>
```

I'm on OS X 10.10.2. Any help you can offer would be greatly appreciated.

**Comment by gstro** [comment]
Deleted examples build and recompiled, and now I can't recreate the error. Not quite through the woods but I don't think this is an issue anymore.

**Comment by davisking** [comment]
Sweet :)

**Comment by vasekjares** [comment]
Same issue, recompiled several times and still can't find solution. OS X 10.10.2

**Comment by davisking** [comment]
What error did you get?

**Comment by vasekjares** [comment]
Hi,
thank you for quick reaction!
I don't get any errors. But if I use pydoc on compiled package, there is no class image_window.
array
        cca_outputs
        fhog_object_detector
        full_object_detection
        matrix
        pair
        point
        points
        range
        ranges
        rangess
        ranking_pair
        ranking_pairs
        rectangle
        rectangles
        rgb_pixel
        segmenter_params
        segmenter_test
        segmenter_type
        shape_predictor
        shape_predictor_training_options
        simple_object_detector
        simple_object_detector_training_options
        simple_test_results
        sparse_ranking_pair
        sparse_ranking_pairs
        sparse_vector
        sparse_vectors
        sparse_vectorss
        svm_c_trainer_histogram_intersection
        svm_c_trainer_linear
        svm_c_trainer_radial_basis
        svm_c_trainer_sparse_histogram_intersection
        svm_c_trainer_sparse_linear
        svm_c_trainer_sparse_radial_basis
        svm_rank_trainer
        svm_rank_trainer_sparse
        vector
        vectors
        vectorss

I'm using commands from python_examples/compile_dlib_python_module.bat. And I get this:
Linking CXX static library libdlib.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(stack_trace.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(sockets_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(dir_nav_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(threads_kernel_1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libdlib.a(stack_trace.o) has no symbols

Should it cause that problem?
Thanks!

**Comment by davisking** [comment]
Those warnings about not having symbols are fine.  The issue is probably that it didn't find libx11 on your machine, which is required to use the GUI components.  When you initially ran the script it should have output a message saying that it didn't find X11 and that you need to install XQuartz.  If you do that then it should work.

**Comment by vasekjares** [comment]
Thanks! Installing libx11 solved problem.

**Comment by kimg1234** [comment]
@davisking 
My computer system is windows7, have the same error.
How should I do it?
Thanks!

**Comment by davisking** [comment]
You don't need X11 on windows, unless you are trying to compile in something like cygwin.

**Comment by kimg1234** [comment]
@davisking  
How do I solve this problem?
.....

**Comment by davisking** [comment]
http://dlib.net/faq.html#Itdoesn'twork

**Comment by kimg1234** [comment]
i use "conda install -c menpo dlib=18.18"  in windows 7 64+py27
and tried to run face_landmark_detection.py but it gave the following error: 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\Users\e069383\Desktop\notebook\py\face_landmark_detection.py in <module>()
     65 detector = dlib.get_frontal_face_detector()
     66 predictor = dlib.shape_predictor(predictor_path)
---> 67 win = dlib.image_window()
     68 
     69 for f in glob.glob(os.path.join(faces_folder_path, "*.jpg")):

AttributeError: 'module' object has no attribute 'image_window'
`

**Comment by davisking** [comment]
menpo must have disabled it for some reason.  I would download dlib from
the dlib website and use that version.

**Comment by kimg1234** [comment]
i use "conda install -c conda-forge dlib=19.0"  
in windows 7 64 py27  can work

**Comment by dmittal5** [comment]
hi, I have been trying to run face detection file in python on ubuntu. but there is the following error - 
Traceback (most recent call last):
  File "/home/divya/proj/detect.py", line 9, in <module>
    face_detector = dlib.get_frontal_face_detector()
AttributeError: 'module' object has no attribute 'get_frontal_face_detector'

please help!

**Comment by abhisheksoni27** [comment]
I have libx11-dev installed on my machine, but I am still getting the same error. Anything else I might check?

**Comment by davisking** [comment]
The compile process prints messages telling you what it's doing.  It will announce if it found X11 or not.

**Comment by abhisheksoni27** [comment]
It does find `libx11.so`

**Comment by jorgher** [comment]
All dependencies installed (X11, Boost, Boos.Python, ..)
(opencv) jorgher@jorgher-Lenovo-G575: conda install -c menpo dlib
(opencv) jorgher@jorgher-Lenovo-G575:~/Documents/dlib/python_examples$ python face_detector.py ../examples/faces/*.jpg
Traceback (most recent call last):
  File "face_detector.py", line 52, in <module>
    win = dlib.image_window()
AttributeError: module 'dlib' has no attribute 'image_window'

pls help

**Comment by CHENCHAOQI** [comment]
I meet the same problem,and I follow some instruction,but I meet new problem,it is:Illegal instruction (core dumped). 
How can I solve it?

**Comment by pawanvirsingh** [comment]
the with me

>>> import dlib
>>> import skimage
>>> impface_detector = dlib.get_frontal_face_detector()
>>> 
>>> face_detector = dlib.get_frontal_face_detector()
>>> win = dlib.image_window()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dlib' has no attribute 'image_window'

on ubuntu  pls help if someone did before

**Comment by davisking** [comment]
Install X11 and recompile dlib.  When you compile dlib it prints messages
about this that tell you exactly what to do.

**Comment by DyLanCao** [comment]
on ubuntu . I forget to run the commond on dlib root: python setup.py install

**Comment by bhomass** [comment]
I installed xquartz on my mac. I also reinstalled dlib, but still I am getting 
AttributeError: module 'dlib' has no attribute 'image_window'

Anything else I should be beside install xquartz?

**Comment by davisking** [comment]
That should be all. Make sure you really are recompiling dlib.  Delete everything and redownload.

**Comment by bhomass** [comment]
yes, rebuild c++ from scratch, then python setup.py install inside my conda env. Finally, it's running. conda install -c menpo dlib does not work.
