### ISSUE TITLE
Issues while installing dlib

### ISSUE THREAD

**Issue by alexattia** [davisking/dlib#706]
For installing dlib, I followed this tutorial : http://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/. 
I am on Mac OS X 10.12.5 and using Python 3.5.
I run 
````
$ brew install cmake
$ brew install boost
$ brew install boost-python --with-python3
````
It works ! 
But when I try to install dlib with `pip install dlib`. I have an error :  
```
The C compiler
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
    is not able to compile a simple test program.
error: cmake configuration failed!
```
For the full error, please see on this link (doesn't want to paste the full error) : 
https://gist.github.com/alexattia/3e98685310d90b65031db640d3ea716a 

Thank you very much,

**Comment by TarrySingh** [comment]
Tried this?
`conda install -c menpo dlib=19.4`

**Comment by alexattia** [comment]
I don't use Anaconda. I have some issues with libraries interfering from Homebrew and MacPorts.

**Comment by davisking** [comment]
You need to have a C++ compiler on your computer.  That error is telling you that either you don't or it's somehow terribly broken.  I would install XCode from Apple.

**Comment by TarrySingh** [comment]
Xcode is a pain, huge install but anyway you'll be needing :
- X11
- Xcode
- cmake (see you already have that)

**Comment by alexattia** [comment]
I just reinstalled Xcode, CMake and checked that I have X11 but I still have the same error ..

**Comment by alexattia** [comment]
No idea ?

**Comment by davisking** [comment]
I have no idea.  It's also obviously not a dlib related problem.
