### ISSUE TITLE
Problem building imglab

### ISSUE THREAD

**Issue by Vishu-Chaudhary** [davisking/dlib#707]
Can you help me out?
`[100%] Linking CXX executable imglab
CMakeFiles/imglab.dir/src/main.cpp.o: In function `dlib::row_major_layout::layout<double, 0l, 3l, dlib::memory_manager_stateless_kernel_1<char>, 3>::set_size(long, long) [clone .isra.245]':
main.cpp:(.text+0x57): undefined reference to `__cxa_throw_bad_array_new_length'
CMakeFiles/imglab.dir/src/main.cpp.o: In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.418]':
main.cpp:(.text+0xcb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
CMakeFiles/imglab.dir/src/main.cpp.o: In function `rename_labels(dlib::image_dataset_metadata::dataset&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text+0xb6e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/imglab.dir/src/main.cpp.o: In function `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode) [clone .constprop.913]':
main.cpp:(.text+0xcc7): undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text+0xcd8): undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text+0xd32): undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text+0xd5c): undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text+0xd8f): undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
main.cpp:(.text+0xdf5): undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
`

**Comment by davisking** [comment]
Something is terribly wrong with your C++ compiler.  Those are core C++ components it's complaining about.  

Try reinstalling the compiler or installing a different one.
