### ISSUE TITLE
The library does not recognize the face on the left or the right edge

### ISSUE THREAD

**Issue by axmadjon** [davisking/dlib#708]
Hello! I have questions.
 In the front view it recognizes perfectly
 But is it possible to make it so that it recognizes the left side of the face.
 If I look at the camera it will recognize.
 And if I turn my head to the left or right, he does not even find a face.
 It is possible to make it so that he at least finds a face
 I think it will be possible because TenserFlow is able to do this.

**Comment by axmadjon** [comment]
![image02](https://user-images.githubusercontent.com/6769854/28204846-fefdf4d8-6898-11e7-825b-6447037f128a.png)

**Comment by davisking** [comment]
Yes, obviously you can train a model to do this.  You didn't even say what model you are using.  One of the pretrained dlib models probably?

**Comment by axmadjon** [comment]
yes
https://github.com/ageitgey/face_recognition

**Comment by davisking** [comment]
You can either train your own model or use the new CNN based detector that comes with dlib if you want a wider range of poses to be detected.  See http://dlib.net/dnn_mmod_face_detection_ex.cpp.html
