### ISSUE TITLE
Working Fine in Ubuntu 16.04 but in Kali linux(debian 9) not

### ISSUE THREAD

**Issue by Vishu-Chaudhary** [davisking/dlib#709]
import dlib
  File "/usr/local/lib/python2.7/dist-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory

**Comment by LOGHORIZION** [comment]
Hi， have you solved that?
