### ISSUE TITLE
dlib Taking up all RAM

### ISSUE THREAD

**Issue by Vishu-Chaudhary** [davisking/dlib#711]
I am trying to train object detector on 14k images all labled but it ends up taking all the RAM and stuck.What to do?I have 16gigs of RAM but stuck.. :(

**Comment by davisking** [comment]
Buy more RAM or use fewer and/or smaller images.

**Comment by TarrySingh** [comment]
Have GPU? You need to explain better your system specs etc. 14K is huge, whats the training model, how many steps, how many epochs? Questions, questions...
