### ISSUE TITLE
Have a release named 'dlib-latest.zip' for use by scripting?

### ISSUE THREAD

**Issue by qacollective** [davisking/dlib#712]
Hi,

This is such a small feature request that it really only constitutes a change in deployment practice.

I'd just like to put up the idea that there be a dlib-latest.zip file placed in dlib.net/files so that when I write a script (mainly a Dockerfile) to build an environment, I'm always getting the latest version automatically.

I'm open to arguments as to why this may be a bad idea, or potentially the suggestion that I would be better off just running a 'git clone' on this repository?

Andrew

**Comment by davisking** [comment]
Why don't you just grab the latest copy from github?

**Comment by xsacha** [comment]
Did you want the latest commit in master: https://github.com/davisking/dlib/archive/master.tar.gz ?
Or the latest release: https://github.com/davisking/dlib/releases/latest ?

**Comment by qacollective** [comment]
Hi Davis,

Good point - so would you expect that the latest version from Github would
be as stable as a 'release version' placed on the website?

The basis of my feature request was probably incorrectly assuming that this
may not be the case.

Apologies,
Andrew

**Comment by davisking** [comment]
No, it won't be as stable.  The whole point of a release is that it's specifically a good stable reference point. 

That's not to say that dlib isn't generally stable all the time.  But really, stability is pretty much the defining feature of a 'release'.

If you want the latest release you can get it out of the html on the web page, or write a rule about getting the latest file, or release from github.  There are a lot of options.

**Comment by qacollective** [comment]
Sorry, I'm a bit new to GitHub - didn't realize it was that easy.

**Comment by davisking** [comment]
No worries.
