### ISSUE TITLE
SSE2 and NEON acceleration with different preformance enhancement

### ISSUE THREAD

**Issue by waterball2016** [davisking/dlib#713]
I've tried SSE2 on my laptop and gained a 10 times speedup when performing face detection (640 x 480), from 500ms to 50ms. That is quite enough. Well, when switching to arm and use NEON to optimize the code. It only enhances the performance from 35ms to 28ms per frame(360 x 360). I notice that I didn`t compile the blas and lapack into my code, that matters a little. What else can I do to improve the performace?

**Comment by davisking** [comment]
Give the `-mfpu=neon` switch to GCC.  You can also turn on profile driven optimizations and those make a big difference, see this thread: https://github.com/davisking/dlib/issues/557
