### ISSUE TITLE
dnn_mmod labelling options

### ISSUE THREAD

**Issue by luketg8** [davisking/dlib#715]
I have successfully used this network on a dataset of ~100 images, each containing about 50 objects that I labelled using the imglab tool you provided. However, as you can imagine the dataset does take a long time to create, which leads me to my question. I have an existing dataset of cropped images that were used for training a HOG+SVM method, these images are each 50x50 and only contain the object in question, is it possible for me to adapt the DNN_MMOD framework to train using these individual images, instead of the images I labelled using the tool? Would it require me to put in individual bounding boxes of 50x50 for it to work? Or could I simply use the images as input? 

Thanks in advance

**Comment by davisking** [comment]
No, if you train on tightly cropped images it's going to learn that what makes your objects objects is being right on the border of the image, due to the border effects (i.e. implicit 0s on the edges).  Moreover, all the negative training data comes from the parts of the image not annotated with a box.  So these cropped training examples wouldn't have any negative data, or very little.

**Comment by luketg8** [comment]
Hi again,

Thanks for getting back to me! I thought as much, but thought it was worth a shot regardless :) I will resume labelling!

**Comment by davisking** [comment]
No problem.

**Comment by luketg8** [comment]
Hi again,

Now that I have labelled my dataset, I was wondering if it is possible to do transfer learning? Ie load from the successful 'my_network.dat' file I had previously created.

Thanks

**Comment by davisking** [comment]
Yes, you can load the file.  The examples show you how to do this.  That's probably not what you mean though.

**Comment by luketg8** [comment]
Thanks, but loading the file isn't the problem. I was just wondering if it was possible to use my current existing network as a starting point for training on the new images I've added to the dataset, ie http://cs231n.github.io/transfer-learning/

**Comment by davisking** [comment]
Yeah I know what transfer learning is.  :)

Yes, you can load the model and fine tune it just like you can with any DNN framework.  There are introductory DNN examples that explain the API and detailed reference documentation for each class an function on the dlib website as well.

**Comment by luketg8** [comment]
Thank you! I'll give it a go

**Comment by luketg8** [comment]
Managed it, thank you for the excellent documentation and library! Second to none :)
