### ISSUE TITLE
exception thrown! Unable to load image. You must #define DLIB_JPEG_SUPPORT and link to libjpeg to read JPEG files

### ISSUE THREAD

**Issue by eler** [davisking/dlib#72]
![2016-01-21 16 13 52](https://cloud.githubusercontent.com/assets/4978135/12474932/041d6a9a-c05a-11e5-97d3-6f824c6ccced.png)
![2016-01-21 16 19 42](https://cloud.githubusercontent.com/assets/4978135/12475034/cee08ef6-c05a-11e5-8386-12acb9eb85f2.png)

compile & link program using g++, no error.
But couldn't run it .  
Do you have any idea?

**Comment by davisking** [comment]
Try pulling the latest dlib code from github and trying it again ;-)

**Comment by eler** [comment]
the latest dlib code gives me this . It doesn't works,right?
![2016-01-22 11 35 14](https://cloud.githubusercontent.com/assets/4978135/12501797/694b2f4a-c0fc-11e5-8db3-e338a9fce07b.png)

**Comment by davisking** [comment]
Yes, but that error tells you what you should do right? :)

**Comment by 892768447** [comment]
Recently, I have encountered this problem, I have resolved, you can try this:
open dlib\config.h and add these code

`#define DLIB_JPEG_SUPPORT 1
#define DLIB_JPEG_STATIC 1
#define DLIB_PNG_SUPPORT 1`

Then python setup.py install
