### ISSUE TITLE
A question (issue) on using Inception Network

### ISSUE THREAD

**Issue by travek** [davisking/dlib#722]
Hi!

Could someone help me to understand why do I have an issue working with inception network

I have input as 11x11 map of float number (1 channel).

If I use network from example code for DLib (dnn_inception_ex.cpp) - It works OK.
/*
template <typename SUBNET> using block_a1 = relu<con<10,1,1,1,1,SUBNET>>;
template <typename SUBNET> using block_a2 = relu<con<10,3,3,1,1,relu<con<16,1,1,1,1,SUBNET>>>>;
template <typename SUBNET> using block_a3 = relu<con<10,5,5,1,1,relu<con<16,1,1,1,1,SUBNET>>>>;
template <typename SUBNET> using block_a4 = relu<con<10,1,1,1,1,max_pool<3,3,1,1,SUBNET>>>;

template <typename SUBNET> using incept_a = inception4<block_a1,block_a2,block_a3,block_a4, SUBNET>;

template <typename SUBNET> using block_b1 = relu<con<4,1,1,1,1,SUBNET>>;
template <typename SUBNET> using block_b2 = relu<con<4,3,3,1,1,SUBNET>>;
template <typename SUBNET> using block_b3 = relu<con<4,1,1,1,1,max_pool<3,3,1,1,SUBNET>>>;
template <typename SUBNET> using incept_b = inception3<block_b1,block_b2,block_b3,SUBNET>;

typedef matrix<double, 11, 11> sample_type;

using net_type = loss_multiclass_log<
	fc<2,
	relu<fc<64,
	max_pool<2, 2, 2, 2, incept_b<
	max_pool<2, 2, 2, 2, incept_a<
	input<sample_type>
	>>>>>>>>;
*/

If I start to change network architecture (below) and start to use 2x2 and 3x3 convolutions in block_a2 and block_a3 (instead of 3x3 and 5x5), then the tool starts to crash.
template <typename SUBNET> using block_a2 = relu<con<10,2,2,1,1,relu<con<16,1,1,1,1,SUBNET>>>>;
template <typename SUBNET> using block_a3 = relu<con<10,3,3,1,1,relu<con<16,1,1,1,1,SUBNET>>>>;

Could you please explain why does the change of the size in conv layer leads to the crash issue ?
What is incorrectly used ?

**Comment by e-fominov** [comment]
When it "crash", it normally means some assertion check was failed. In this case you should see error messages on your screen. It will help if you will show us this message

Inception idea is simply to run some parallel subnetworks on same input data and join (concat) their outputs

To make it work, you must make all subnetworks to produce same dimensions of outputs (nr and nc), while k-dimension can be different

Can you check if 2*2 convolution produce same output size as 3*3?

**Comment by travek** [comment]
@e-fominov 
I don't understand the output topic.
If I have 11x11 input and apply 5x5 filter - result will be 7x7-size output
If I have 11x11 input and apply 3x3 filter - result will be 9x9-size output

So in case of 
template using block_a2 = relu<con<10,3,3,1,1,relu<con<16,1,1,1,1,SUBNET>>>>;
template using block_a3 = relu<con<10,5,5,1,1,relu<con<16,1,1,1,1,SUBNET>>>>;
there should always be an assert error.
Why is working for the above example if nc andnr of the output seems to be different ??

**Comment by e-fominov** [comment]
5x5 and 7x7 will bith have 11x11 output because they will have 2 and 3 padding, same for 3x3(1 padding), but for 2x2 convolution with padding 1 and stride 1, we can expect output size 12x12

Padding is done automaticaly in dlib - see con_ template definition

**Comment by travek** [comment]
@e-fominov,
Thanks, clear!
