### ISSUE TITLE
Hey guys the dlib face recognition model doesn't take grayscale, any ideas?

### ISSUE THREAD

**Issue by nchafni** [davisking/dlib#723]
Unsupported image type, must be RGB image.

**Comment by davisking** [comment]
Use RGB images?

**Comment by nchafni** [comment]
I'm preforming some image preprocessing on the grayscale version of the image to improve results, works great with landmark detection so I'ld like use grayscale if possible

**Comment by davisking** [comment]
Convert to RGB before sending it to the detector.

**Comment by marimcode** [comment]
@nchafni Hi, can I know which kind of pre processing you have done?
