### ISSUE TITLE
problem building dlib with cmake on ubuntu 16.04

### ISSUE THREAD

**Issue by linengmiao** [davisking/dlib#727]
Hello

I am trying to build dlib on my ubuntu machine, but am facing some issues when executing: 

           cmake --build . --config Release

I tried adding SET ( CMAKE_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0" ) after PROJECT(examples) as suggested by other people on askubuntu.com, but the issue is not solved:

part of the modified CMakeLists.txt file: http://paste.ubuntu.com/25183001

this is the error I keep getting: http://paste.ubuntu.com/25182997 

I seem to not be the only one with that issue:
https://askubuntu.com/questions/931225/dlib-19-4-will-not-build-with-cmake-on-ubuntu-16-04

https://askubuntu.com/questions/940237/cmake-build-issue-undefined-reference-to-std-cxx11basic-stringchar-std

How can I solve this issue?

Thank you

**Comment by davisking** [comment]
Those links are broken.  Paste the errors here.

**Comment by linengmiao** [comment]
@davisking my bad, I corrected the links. The output is a bit lengthy...

**Comment by davisking** [comment]
The error:

```
sqlite_ex.cpp:(.text._ZN4dlib5randmEll[_ZN4dlib5randmEll]+0xd3): undefined reference to `__cxa_throw_bad_array_new_length'
```

is not a dlib error.  Getting that error means there is something terribly wrong with your compiler as __cxa_throw_bad_array_new_length is a core part of the compiler toolchain.  You need to get a working c++ compiler.

**Comment by linengmiao** [comment]
@davisking the only time I get this type of error is when trying to use dlib. Could you maybe help to fix this, so I can try use your open source software?

**Comment by davisking** [comment]
Google __cxa_throw_bad_array_new_length.  Lots of people have this error and it has nothing to do with dlib.  It's because something is wrong with how you installed GCC.

**Comment by linengmiao** [comment]
@davisking  I didn't even really install gcc myself, I just use the one that comes when installing ubuntu on my machine....
