### ISSUE TITLE
CUDA not working

### ISSUE THREAD

**Issue by DomLi** [davisking/dlib#729]
Hi,
Recently, just following the Dlib tutorial on CNN, I built a  project with windows VS2015, using dnn_mmod_ex.cpp to train  a model , but CUDA on my machine did not give any speed up, I am not sure if I did right way cos I did not use CMake. and Meawhile, the an error Dlib:: impossible_labelling_error , occurred.  
can any help please , thank you

**Comment by vrodionovpro** [comment]
I have same error I've do this
https://github.com/davisking/dlib/issues/756

**Comment by davisking** [comment]
Yes, use cmake and do as @vrodionovpro points out.  Also, get the latest dlib from github, it will be easier to use.
