### ISSUE TITLE
Linux install dlib error

### ISSUE THREAD

**Issue by jiangwqcooler** [davisking/dlib#731]
When i install dlib-19.4, i get this error, somebody help me? thanks!

-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- C++11 activated (compiler doesn't have full C++11 support).
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'cblas'
--   package 'cblas' not found
-- checking for module 'lapack'
--   package 'lapack' not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenBLAS library
-- Looking for sgetrf_single
-- Looking for sgetrf_single - not found
-- Found LAPACK library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5") 
-- *** Dlib CUDA support requires C++11 but your compiler doesn't support it. ***
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenqiang/lib/dlib-19.4/build
wenqiang@facethinkGPU:~/lib/dlib-19.4/build$ cmake --build . --config Release
Scanning dependencies of target dlib
[  0%] Building CXX object dlib/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
[  1%] Building CXX object dlib/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
[  2%] Building CXX object dlib/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
[  3%] Building CXX object dlib/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
[  4%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
[  5%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
[  6%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
[  7%] Building CXX object dlib/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
[  8%] Building CXX object dlib/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
[  9%] Building CXX object dlib/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
[ 10%] Building CXX object dlib/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
[ 11%] Building CXX object dlib/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
[ 12%] Building CXX object dlib/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
[ 12%] Building CXX object dlib/CMakeFiles/dlib.dir/dnn/cpu_dlib.cpp.o
In file included from /home/wenqiang/lib/dlib-19.4/dlib/dnn/cpu_dlib.cpp:9:0:
/home/wenqiang/lib/dlib-19.4/dlib/dnn/tensor_tools.h:1305:36: error: '<::' cannot begin a template-argument list [-fpermissive]
/home/wenqiang/lib/dlib-19.4/dlib/dnn/tensor_tools.h:1305:36: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
/home/wenqiang/lib/dlib-19.4/dlib/dnn/tensor_tools.h:1305:36: note: (if you use '-fpermissive' G++ will accept your code)
make[2]: *** [dlib/CMakeFiles/dlib.dir/dnn/cpu_dlib.cpp.o] Error 1
make[1]: *** [dlib/CMakeFiles/dlib.dir/all] Error 2
make: *** [all] Error 2

**Comment by davisking** [comment]
You need a C++11 compiler.  So install a newer version of gcc.

**Comment by jiangwqcooler** [comment]
@davisking I had use gcc-5 and g++-5  and  solved this error, but still thank you for reply.
