### ISSUE TITLE
test\matrix2.cpp is incompatible with C++17

### ISSUE THREAD

**Issue by xiangfan-ms** [davisking/dlib#733]
Hi,
    The issue can be illustrated as follows:

	#include <algorithm>

	namespace dlib
	{
		struct matrix_exp {};

		template<typename T, int n = 2>
		struct matrix : matrix_exp {
			operator T() const {
				static_assert(n == 1);
			}
		};
		void clamp(matrix_exp&, matrix_exp&, matrix_exp&) {}
	}

	// test\matrix2.cpp

	using namespace dlib;
	using namespace std;

	void f()
	{
		matrix<int> x, l, u;
		// std::clamp is added in C++17 and chosen by the overload resolution because it is an exact match.
		// To resolve 'operator <', the compiler is required to instantiate matrix<int>::operator int
		// Then the assertion in it will be hit
		clamp(x, l, u);
	}

One possible way to workaround this in the test is to use 'dlib::clamp' explicitly.

**Comment by davisking** [comment]
Yeah, putting dlib:: in front is sensible.  Do you want to submit a PR? :)

**Comment by namar0x0309** [comment]
If busy I can take this. Want to start contributing to dlib :)
