### ISSUE TITLE
When I compile a cpp file in caffe

### ISSUE THREAD

**Issue by jiangwqcooler** [davisking/dlib#735]
When i compile a cpp file which refer to dlib，i get this error， how should i do？

/usr/local/include/dlib/image_processing/scan_fhog_pyramid.h:52:34:   required from 'void dlib::default_fhog_feature_extractor::operator()(const image_type&, dlib::array<dlib::array2d<float> >&, int, int, int) const [with image_type = dlib::array2d<dlib::bgr_pixel>]'
/usr/local/include/dlib/image_processing/scan_fhog_pyramid.h:594:15:   required from 'void dlib::impl::create_fhog_pyramid(const image_type&, const feature_extractor_type&, dlib::array<dlib::array<dlib::array2d<float> > >&, int, int, int, long unsigned int, long unsigned int, long unsigned int) [with pyramid_type = dlib::pyramid_down<6u>; image_type = dlib::array2d<dlib::bgr_pixel>; feature_extractor_type = dlib::default_fhog_feature_extractor]'
/usr/local/include/dlib/image_processing/scan_fhog_pyramid.h:633:48:   required from 'void dlib::scan_fhog_pyramid<Pyramid_type, Feature_extractor_type>::load(const image_type&) [with image_type = dlib::array2d<dlib::bgr_pixel>; Pyramid_type = dlib::pyramid_down<6u>; Feature_extractor_type = dlib::default_fhog_feature_extractor]'
/usr/local/include/dlib/image_processing/object_detector.h:433:9:   required from 'void dlib::object_detector<image_scanner_type_>::operator()(const image_type&, std::vector<dlib::rect_detection>&, double) [with image_type = dlib::array2d<dlib::bgr_pixel>; image_scanner_type_ = dlib::scan_fhog_pyramid<dlib::pyramid_down<6u> >]'
/usr/local/include/dlib/image_processing/object_detector.h:507:16:   required from 'std::vector<dlib::rectangle> dlib::object_detector<image_scanner_type_>::operator()(const image_type&, double) [with image_type = dlib::array2d<dlib::bgr_pixel>; image_scanner_type_ = dlib::scan_fhog_pyramid<dlib::pyramid_down<6u> >]'
examples/face_landmark.cpp:55:56:   required from here
**## /usr/local/include/dlib/pixel.h:1313:52: error: 'lab' is not a member of 'dlib::pixel_traits<float>'
         typename enable_if_c<pixel_traits<P1>::lab && pixel_traits<P2>::hsi>::type
                                                    ^
/usr/local/include/dlib/pixel.h:1313:52: error: 'hsi' is not a member of 'dlib::pixel_traits<int>'**

**Comment by davisking** [comment]
What did you type?

**Comment by jiangwqcooler** [comment]
@davisking After compiled caffe,  I added a .cpp in caffe/example/  and in caffe/ dir i type make
