### ISSUE TITLE
Port Dlib 19.4 to Android for face recognition

### ISSUE THREAD

**Issue by Doupi** [davisking/dlib#739]
Hi, @davisking

I am trying to use dlib for face recognition in android app. I followed @tzutalin's work for face detection. 

However, I got link error when I tried to use DNN for face recognition.  The error message is as follows,

XXXXX:git_dlib_android XXXX$ ndk-build -j 2
Android NDK: android-8 is unsupported. Using minimum supported version android-14.    
TOP Level Path: 
...........
............
jni/jni_common/Android.mk:10: "Build jni_common"
jni/jni_common/Android.mk:16: jni/jni_common
"Won't build test's executable file"
Android NDK: WARNING:jni/jni_common/Android.mk:jni_common: LOCAL_LDLIBS is always ignored for static libraries    
[armeabi-v7a] Compile++ arm  : android_dlib <= jni_imageutils.cpp
[armeabi-v7a] Compile++ arm  : android_dlib <= jni_pedestrian_det.cpp
[armeabi-v7a] Compile++ arm  : android_dlib <= jni_face_det.cpp
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_shared.cpp
[armeabi-v7a] Compile++ thumb: dlib <= entropy_decoder_kernel_2.cpp
[armeabi-v7a] Compile++ thumb: dlib <= base64_kernel_1.cpp
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_1.cpp
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_2.cpp
[armeabi-v7a] Compile++ thumb: jni_common <= jni_bitmap2mat.cpp
[armeabi-v7a] Compile++ thumb: jni_common <= jni_fileutils.cpp
[armeabi-v7a] Compile++ thumb: jni_common <= jni_utils.cpp
[armeabi-v7a] Compile++ thumb: jni_common <= rgb2yuv.cpp
[armeabi-v7a] Compile++ thumb: jni_common <= yuv2rgb.cpp
[armeabi-v7a] Compile++ thumb: miniglog <= logging.cc
[arm64-v8a] Compile++      : android_dlib <= jni_imageutils.cpp
[arm64-v8a] Compile++      : android_dlib <= jni_pedestrian_det.cpp
[arm64-v8a] Compile++      : android_dlib <= jni_face_det.cpp
[arm64-v8a] Compile++      : dlib <= threads_kernel_shared.cpp
[arm64-v8a] Compile++      : dlib <= entropy_decoder_kernel_2.cpp
[arm64-v8a] Compile++      : dlib <= base64_kernel_1.cpp
[arm64-v8a] Compile++      : dlib <= threads_kernel_1.cpp
[arm64-v8a] Compile++      : dlib <= threads_kernel_2.cpp
[arm64-v8a] Compile++      : jni_common <= jni_bitmap2mat.cpp
[arm64-v8a] Compile++      : jni_common <= jni_fileutils.cpp
[arm64-v8a] Compile++      : jni_common <= jni_utils.cpp
[arm64-v8a] Compile++      : jni_common <= rgb2yuv.cpp
[arm64-v8a] Compile++      : jni_common <= yuv2rgb.cpp
[arm64-v8a] Compile++      : miniglog <= logging.cc
[x86] Compile++      : android_dlib <= jni_imageutils.cpp
[x86] Compile++      : android_dlib <= jni_pedestrian_det.cpp
[x86] Compile++      : android_dlib <= jni_face_det.cpp
[x86] Compile++      : dlib <= threads_kernel_shared.cpp
[x86] Compile++      : dlib <= entropy_decoder_kernel_2.cpp
[x86] Compile++      : dlib <= base64_kernel_1.cpp
[x86] Compile++      : dlib <= threads_kernel_1.cpp
[x86] Compile++      : dlib <= threads_kernel_2.cpp
[x86] Compile++      : jni_common <= jni_bitmap2mat.cpp
[x86] Compile++      : jni_common <= jni_fileutils.cpp
[x86] Compile++      : jni_common <= jni_utils.cpp
[x86] Compile++      : jni_common <= rgb2yuv.cpp
[x86] Compile++      : jni_common <= yuv2rgb.cpp
[x86] Compile++      : miniglog <= logging.cc
[x86_64] Compile++      : android_dlib <= jni_imageutils.cpp
[x86_64] Compile++      : android_dlib <= jni_pedestrian_det.cpp
[x86_64] Compile++      : android_dlib <= jni_face_det.cpp
[x86_64] Compile++      : dlib <= threads_kernel_shared.cpp
[x86_64] Compile++      : dlib <= entropy_decoder_kernel_2.cpp
[x86_64] Compile++      : dlib <= base64_kernel_1.cpp
[x86_64] Compile++      : dlib <= threads_kernel_1.cpp
[x86_64] Compile++      : dlib <= threads_kernel_2.cpp
[x86_64] Compile++      : jni_common <= jni_bitmap2mat.cpp
[x86_64] Compile++      : jni_common <= jni_fileutils.cpp
[x86_64] Compile++      : jni_common <= jni_utils.cpp
[x86_64] Compile++      : jni_common <= rgb2yuv.cpp
[x86_64] Compile++      : jni_common <= yuv2rgb.cpp
[x86_64] Compile++      : miniglog <= logging.cc
[armeabi-v7a] StaticLibrary  : libdlib.a
[armeabi-v7a] StaticLibrary  : libjni_common.a
[armeabi-v7a] StaticLibrary  : libminiglog.a
[arm64-v8a] StaticLibrary  : libdlib.a
[arm64-v8a] StaticLibrary  : libjni_common.a
[arm64-v8a] StaticLibrary  : libminiglog.a
[x86] StaticLibrary  : libdlib.a
[x86] StaticLibrary  : libjni_common.a
[x86] StaticLibrary  : libminiglog.a
[x86_64] StaticLibrary  : libdlib.a
[x86_64] StaticLibrary  : libjni_common.a
[x86_64] StaticLibrary  : libminiglog.a
[armeabi-v7a] SharedLibrary  : libandroid_dlib.so
jni/../dlib/dlib/dnn/tensor_tools.h:874: error: undefined reference to 'dlib::cpu::pooling::pooling()'
jni/../dlib/dlib/dnn/tensor_tools.h:874: error: undefined reference to 'dlib::cpu::pooling::pooling()'
jni/../dlib/dlib/dnn/tensor_tools.h:874: error: undefined reference to 'dlib::cpu::pooling::pooling()'
jni/../dlib/dlib/dnn/tensor_tools.h:874: error: undefined reference to 'dlib::cpu::pooling::pooling()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libandroid_dlib.so] Error 1
make: *** Waiting for unfinished jobs....

How can I fix this problem? Thank you!

**Comment by Doupi** [comment]
The error happens when I declared the dnn as follows,

..........
 // The code defines a ResNet network.
   template <template <int,template<typename>class,int,typename> class block, int N, template<typename>class BN, typename SUBNET>
   using residual = dlib::add_prev1<block<N,BN,1,dlib::tag1<SUBNET>>>;
   
   template <template <int,template<typename>class,int,typename> class block, int N, template<typename>class BN, typename SUBNET>
   using residual_down = dlib::add_prev2<dlib::avg_pool<2,2,2,2,dlib::skip1<dlib::tag2<block<N,BN,2,dlib::tag1<SUBNET>>>>>>;
   
   template <int N, template <typename> class BN, int stride, typename SUBNET>
   using block  = BN<dlib::con<N,3,3,1,1,dlib::relu<BN<dlib::con<N,3,3,stride,stride,SUBNET>>>>>;
   
   template <int N, typename SUBNET> using ares      = dlib::relu<residual<block,N,dlib::affine,SUBNET>>;
   template <int N, typename SUBNET> using ares_down = dlib::relu<residual_down<block,N,dlib::affine,SUBNET>>;
   
   template <typename SUBNET> using alevel0 = ares_down<256,SUBNET>;
   template <typename SUBNET> using alevel1 = ares<256,ares<256,ares_down<256,SUBNET>>>;
   template <typename SUBNET> using alevel2 = ares<128,ares<128,ares_down<128,SUBNET>>>;
   template <typename SUBNET> using alevel3 = ares<64,ares<64,ares<64,ares_down<64,SUBNET>>>>;
   template <typename SUBNET> using alevel4 = ares<32,ares<32,ares<32,SUBNET>>>;
   using anet_type = dlib::loss_metric<dlib::fc_no_bias<128,dlib::avg_pool_everything<
                                                 alevel0<
                                                 alevel1<
                                                 alevel2<
                                                 alevel3<
                                                 alevel4<
                                                 dlib::max_pool<3,3,2,2,dlib::relu<dlib::affine<dlib::con<32,7,7,2,2,
                                                 dlib::input_rgb_image_sized<150>
                                                 >>>>>>>>>>>>;

   anet_type net;

..........

**Comment by davisking** [comment]
You aren't compiling all the dlib code.  http://dlib.net/compile.html tells you how to compile dlib.
