### ISSUE TITLE
Threads options for face_detector and test_simple_object_detector

### ISSUE THREAD

**Issue by rajacheers** [davisking/dlib#74]
Is it possible to run face_detector and test_simple_object_detector using multiple threads. I know there is an example to train with multiple threads. This will really help to make the code faster

**Comment by davisking** [comment]
No

**Comment by wuwei0509** [comment]
any idea how to improve the performanc?

**Comment by davisking** [comment]
If there was an option to improve performance it would be on by default :)

**Comment by wuwei0509** [comment]
many thanks.
