### ISSUE TITLE
How to compile dlib as PHP extension?

### ISSUE THREAD

**Issue by fengerzh** [davisking/dlib#740]
Is it possible to compile dlib as PHP extension? Do I need to modify the source code? Please someone give some hint. Thanks!

**Comment by davisking** [comment]
I've never used PHP, but you should never need to modify dlib's source code when using it, as an extension module for some language, application, or whatever.  Any tutorial on how to create PHP extension models that call C++ should work fine for dlib.

**Comment by goodspb** [comment]
@fengerzh try https://github.com/goodspb/pdlib , but I'm just do it for fun, use it carefully!
