### ISSUE TITLE
What does the 128D descriptor physically represent?

### ISSUE THREAD

**Issue by abhisheksoni27** [davisking/dlib#742]

**Comment by davisking** [comment]
Nothing.  It's just numbers and the more similar they are the more likely two images are of the same person.

**Comment by abhisheksoni27** [comment]
Can you take a moment and think about how you call them "just numbers" and then say they actually are related to a face?

**Comment by davisking** [comment]
There isn't any more to it than what I said.  It's not anything like "the 16th element models the ears and the 42th element models the nose".  It's a 128D vector where the Euclidean distance between them has this property of separating identities.  That's the only structure built into the model.

**Comment by abhisheksoni27** [comment]
Thanks for the clarification, Sir.
