### ISSUE TITLE
Model not learning correctly

### ISSUE THREAD

**Issue by abhisheksoni27** [davisking/dlib#748]
I am training a linear SVM using a dataset that includes twenty 128D vectors for each class. Right now, it has two classes.

I want to know whether I'd have to put a threshold over the Euclidean distance in the SVM? Just like in the original Distance metric example?

I am using `sklearn`.

Does it mean I need more data? Or is it just not worth training a SVC against the 128 vector representation?

**Comment by davisking** [comment]
It doesn't sound like you are using dlib.  You should ask on a sklearn forum.

**Comment by abhisheksoni27** [comment]
I am using dlib to extract faces, then landmarks, then the face descriptor(128D Vector)

**Comment by davisking** [comment]
Try using a linear SVM
