### ISSUE TITLE
Illegal instruction (core dumped) while running Dlib Face detection

### ISSUE THREAD

**Issue by CHENCHAOQI** [davisking/dlib#749]
I am trying to run face_detector.py example sample which was provided by the Dlib library.
But when i am trying to run the command via ubuntu terminal I am getting error: Illegal instruction (core dumped).I try any demo about dlib,and got the same problem.How should I do to fix this problem?Thank you very much.

**Comment by davisking** [comment]
Maybe you have SSE or AVX instructions enabled but you have a really old Intel CPU?
