### ISSUE TITLE
python2.7 windows compile problem

### ISSUE THREAD

**Issue by Fankbai** [davisking/dlib#750]
@davisking hi, the compiler seems not continue when to "face_gecognition.cpp", which takes much time. what should i do?
![image](https://user-images.githubusercontent.com/10338671/29238455-9010e4e0-7f68-11e7-8ce7-b0a9cc2075c7.png)

**Comment by davisking** [comment]
Visual Studio 2017 is buggy and unable to compile the C++11 code since it lacks full C++11 support.  Visual Studio 2015 will work though since it had better C++11 support, at least in this regard.
