### ISSUE TITLE
issue about my cuda when compile my c++ files

### ISSUE THREAD

**Issue by minmummax** [davisking/dlib#752]
when compile my c++ file using dlib i got two warnings like this:
g++  train*.o -o train  -L/usr/local/lib -lboost_system -ldlib -lpng -L/usr/local/cuda-8.0/lib64/ -lcublas -lcurand -lpthread -lblas  -llapack -lgif
/usr/bin/ld: warning: libcublas.so.7.5, needed by /usr/local/lib/libdlib.so, may conflict with libcublas.so.8.0
/usr/bin/ld: warning: libcurand.so.7.5, needed by /usr/local/lib/libdlib.so, may conflict with libcurand.so.8.0
,although it may seems that my cuda matters but i wanna fix this ,and my cuda'version is 8.0 
how can the 7.5 version happens??
so please give some advice about this problem!!

**Comment by davisking** [comment]
I don't know what to tell you.  Be consistent about which cuda version you are using seems like the obvious answer.  Tell g++ to link to cuda 7.5.  Or compile dlib against 8.0 rather than 7.5.  Really though, why do you even need to tell g++ to link against cublas?  Are *you* using cublas yourself?
