### ISSUE TITLE
Is it possible to calculate the joint possibility in Bayes Network？

### ISSUE THREAD

**Issue by King-Of-Knights** [davisking/dlib#754]
Thank in advance for your great job! 
I notice the example in Bayes Network_ex.cpp that we could get the value of P(A|B,C) by using joint tree.possibility(A)(1) and setting the evidence, but I have no idea which function may I use to get P(A, B| C ), any advise? 
Much appreciate !

**Comment by davisking** [comment]
It doesn't give you that.  If you wanted it you should make a node with the cross product of A and B as states.
