### ISSUE TITLE
Visualize trained SVM

### ISSUE THREAD

**Issue by nlhkh** [davisking/dlib#755]
In most cases, when dlib is installed with conda or pip,  it will not have the `image_window` module. I only need to use this module to visualize a trained svm model. So, if `image_window` does not work out of the box from pip and conda, is there an alternative to visualize a trained model?

**Comment by davisking** [comment]
There are lots of visualization tools in python.  matplotlib is a popular example.

**Comment by nlhkh** [comment]
Visualizing a "detector", loaded from a ".svm" file. Not an image.

**Comment by davisking** [comment]
If that's what you want then you should get a properly compiled copy of dlib that has the image_window.
