### ISSUE TITLE
CUDA Windows 10 c++ manual

### ISSUE THREAD

**Issue by vrodionovpro** [davisking/dlib#756]
Hi all.

I have spend many days then try to compile dlib 19.4 on Windows and may be someone used my expirience.

On Windows 10 with Nvidia videocard you need exactly this:
-windows 10 x64
-ms vs 2015 update 3 (I have 19.0.24210.0)
-cuda sdk 8
-cudnn 5.1 !!! (Most Important. Not working with new versions)
-dlib 19.4

And after toy can type (set your cudnn path)
`cmake -G "Visual Studio 14 2015 Win64" -DCOMPILER_CAN_DO_CPP_11=ON -DCMAKE_PREFIX_PATH="C:/cudnn/" ..`

and 
`cmake --build . --config Release`

And it's done!

**Comment by davisking** [comment]
You shouldn't need to set COMPILER_CAN_DO_CPP_11.  All that should be
required is putting cudnn somewhere cmake will find it by default or
setting CMAKE_PREFIX_PATH to tell it where

**Comment by davisking** [comment]
You should also have been able to use cudnn 6.  Are you saying that didn't
work?

**Comment by vrodionovpro** [comment]
Without COMPILER_CAN_DO_CPP_11 cuda is not supported. And with cadnn 6 you cannot compile test example and cuda is not supported.

**Comment by davisking** [comment]
Ah, right, v19.4.  If you use the latest dlib from github you won't have to fiddle with anything.  I just checked and if you let cuda install to the default folders (i.e. in c:\program files) it will all work without any extra cmake flags.  But v19.4 was more complicated with regard to C++11 and visual studio 2015.

**Comment by alexandreofbh** [comment]
What is the CUDA version and cuDNN version is ideal for DLIB to work with CUDA? In linux ubuntu 16.04 and GPU GE FORCE GTX 1080Ti?

**Comment by davisking** [comment]
I would use the newest versions of each.  Any recent versions should work though.
