### ISSUE TITLE
68 landmarks features

### ISSUE THREAD

**Issue by elliotresearcher** [davisking/dlib#757]
Hi,
  thanks for providing codes,you are helping people a lot.
I have run your file and detected 68 landmarks,now i want to save it in .mat file to use it in matlab,please guide me.thanks for your help.

**Comment by davisking** [comment]
You can use dlib's matlab mex interface to easily make a mex file that does whatever you want with dlib and call it from matlab.  See: https://github.com/davisking/dlib/tree/master/dlib/matlab

**Comment by elliotresearcher** [comment]
thanks for your reply,but from your code which file should i call.sorry i didn't get point.please guide me.
