### ISSUE TITLE
options.num_threads in dlib.train_simple_object_detector

### ISSUE THREAD

**Issue by magveda** [davisking/dlib#76]
whenever I set num_threads to 2 or 1, there are 5 threads created when I start the training

dlib version 18.18
http://dlib.net/train_object_detector.py.html

**Comment by davisking** [comment]
How do you know it's 5 threads?

**Comment by magveda** [comment]
hey, I checked process list in htop. maybe it is not right :)?..

**Comment by davisking** [comment]
That's fine.  It's just BLAS using additional threads in the background.  If you want to change how BLAS behaves set the OMP_NUM_THREADS environment variable.
