### ISSUE TITLE
Building dlib example to js

### ISSUE THREAD

**Issue by akshay-hazari** [davisking/dlib#762]
I have been trying to build the code for webcam_face_pose_ex.cpp to js using Emscripten.  https://github.com/kripken/emscripten/issues/5435 . It fails while it is using OpenCV where it accesses native c++ code instead of the Emscripten libraries. 
Had tried building OpenCV by using its Emscripten configuration in CMakeLists . 
Any help defining a good way to approach this will be appreciated.

**Comment by akshay-hazari** [comment]
Was able to build it successfully just had to install some libraries in my system. 
sudo apt-get install libgfortran3 
Then linking it to Emscripten libraries while compiling the dlib code.

**Comment by akshay-hazari** [comment]
Hey, I needed some help here.
I built DLIB like this.
```
mkdir build 
cd build
 cmake -DCMAKE_CXX_COMPILER=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.21/em++ -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_C_COMPILER=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.21/emcc  -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.21/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_INSTALL_PREFIX=/home/akshay/DLIB/INSTALL2 ..
cmake --build . --config Release
make install
```
This creates a directory with the installed files but it removes all the cpp files from the installation directory.

Then I manually added the cpp files from dlib repository. I thought cpp files would directly use the llvm libraries since I was specifying them in make in the below command. I also included /home/akshay/DLIB/INSTALL/include/dlib/source.cpp in directories included while cross compiling the webcam_face_pose_ex.cpp file. I guess since llvm must use llvm libraries it fails and gives an error of llvm reader and producer versions to be different.

```
cmake -DCMAKE_CXX_COMPILER=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.21/em++ -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_C_COMPILER=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.21/emcc -Ddlib_DIR=/home/akshay/DLIB/INSTALL/lib/cmake/dlib -DOpenCV_DIR="/home/akshay/OPENCV1/INSTALL/share/OpenCV" -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.21/cmake/Modules/Platform/Emscripten.cmake  -D CMAKE_INSTALL_PREFIX=/home/akshay/Downloads/emsdk-portable 
```

Do the cpp files need to get created while crosscompiling DLIB using emscripten c++ and c libraries where I do
`make install` after `cmake --build . --config Release `build.

**Comment by kavikode** [comment]
is there a way to build dlib without errors?
