### ISSUE TITLE
vs2015 cann't complie "dnn_metric_learning_on_images_ex.cpp"

### ISSUE THREAD

**Issue by yanchao12122** [davisking/dlib#763]
I try to complie the file in microsoft visual studio 2015, but after 30minites, it fails to complie.

**Comment by e-fominov** [comment]
This is an old bug of Visual Studio, you will not be able to make this without simplifying the network structure. If you need to make it work with Windows OS, you can use MinGW or Clang.

MinGW is fully supported by DLib but will not work with CUDA and not compatible with MSVC .libs

CLang will work with Cuda and will be compatible with MSVC, but compiling Dlib with it will require some  changes in dlib's CMakeLists.txt. I don't remember the list of changes, not trivial (but works)

Most simple way to make training - use Linux machine, or you can remove some levels from network and it will start compiling on Windows
