### ISSUE TITLE
How to get the probability of shape_predictor (68 landmarks)

### ISSUE THREAD

**Issue by yanchao12122** [davisking/dlib#764]
I try to localize the 68 landmark of a face, but I find some points not accurate, so I want to get the probability of them

**Comment by e-fominov** [comment]
shape_predictor algorithm does not have meaning of landmarks confidence. it is based on [Kazemi algorithm](http://www.csc.kth.se/~vahidk/papers/KazemiCVPR14_poster.pdf)

if you need to have confidence of landmarks, you can try algorithms from OpenCV or train separate object detectors for landmarks
