### ISSUE TITLE
How to change the .dat library into android .so library?

### ISSUE THREAD

**Issue by CHENCHAOQI** [davisking/dlib#765]
I want use dlib in android platform,I need to change dlib_face_recognition_resnet_model_v1.dat into .so library.How can I make it?Thank you very much.

**Comment by e-fominov** [comment]
The .dat file is not a library, but the DNN trained model file. You need to compile C++ code into native android library.

Some example can be found here: https://github.com/tzutalin/dlib-android

I suggest, you can as dlib-android author to add face recognition function

**Comment by omis76** [comment]
have anyone did dlib_face_recognition_resnet_model_v1.dat this in android
