### ISSUE TITLE
Frontal_face_detector returns rectangles with negative coordinates

### ISSUE THREAD

**Issue by itai-icx** [davisking/dlib#767]
The issue is that frontal_face_detector returns negative coordinates for the faces it detects.
Reproduction code:
```
import dlib
import numpy as np
from PIL import Image

im = Image.open('<image_path>')
face_detector = dlib.get_frontal_face_detector()  # Face detector
faces = face_detector(np.array(im.convert('RGB')), 1) # Image is RGBA, so convert to RGB
face = faces[0]
print face
```
And the image used is the one attached below (taken from Google).
This outputs for me `[(-37, 23) (260, 290)]`.

Maybe I'm missing something, but it seems strange to me that it returns negative coordinates.

Thanks!

![15](https://user-images.githubusercontent.com/29126341/29555650-058ec776-872c-11e7-90b0-fffa3a9738b9.jpg)

**Comment by davisking** [comment]
Yes, you can get negative coordinates because faces can be only party in an image, as your is.
