### ISSUE TITLE
how to process 194 landmarks (helen dataset) ?

### ISSUE THREAD

**Issue by volye** [davisking/dlib#768]
I had trained DLIB's shape_predictor for 194 face landmarks using helen dataset. but, when I call the function of "get_face_chip_details" for face-recognition, DLIB throw an exception.

so, how to modify the DLIB's source code in order to adapting the 194 face landmarks ? 

thanks.

**Comment by davisking** [comment]
Look at the code for that function.  It should be clear what to do.  But in any case, I'm not going to type the code out for you, and it's not likely anyone else will either.

**Comment by volye** [comment]
but, how to fix the array variable of mean_face_shape_x and mean_face_shape_y ?
