### ISSUE TITLE
how to fix the value of mean_face_shape_x and mean_face_shape_y in the get_face_chip_details function ?

### ISSUE THREAD

**Issue by volye** [davisking/dlib#769]
To do face-recognition with 194 face landmarks using helen dataset, an exception was occurred in the get_face_chip_details function.

**Comment by e-fominov** [comment]
**get_face_chip_details**  internals are searching parameters for affine-transform that will map your original image into chip image. if you will look inside, you will find that this function does not use all landmarks from face - only most important one

Helen dataset has 194 face landmarks, and this landmarks looks like extension to dlib's 68 landmarks. So you can find corresponding points from 68-set and 194-set, select them from 194-detected points, produce new **full_object_detection** that will have 68 points selected from 194 detected ones and use this **full_object_detection** instance to **get_face_chip_details**

This is simple and straightforward way. It will have same precision as the full mapping of points - don't be afraid to miss something here

You can also build new **get_face_chip_details** function that will use all landmarks - but is on you :)
