### ISSUE TITLE
wrapper for C# or VB.NET

### ISSUE THREAD

**Issue by dahanco2015** [davisking/dlib#774]
hello

is there any prebuild dlib.dll to use in visual studio 2015  directly (C# or VB.NET) 
no matter 32 or 64 bit

Thanks

**Comment by davisking** [comment]
No, there is no such dll.  You have to define a C# API that maps to the C++ features you want to use anyway, so there is no possible generic dlib dll file that could exist.  

I recommend using SWIG to call C++ code from C#.  That's what I've done in the past and it's quite convenient.
