### ISSUE TITLE
Coding IMG to another IMG

### ISSUE THREAD

**Issue by vrodionovpro** [davisking/dlib#775]
Man. Great thanks for your library and you soul! Amazing lib.

I have one question, may be some one tell me how can I do it. I have images, and I need get some retouched images on output.

Input images and output images:
![photoshop_dsc_0035_2615__1](https://user-images.githubusercontent.com/18420865/29678212-622af53c-8906-11e7-8339-47128aecc886.jpg)
![photoshop_dsc_0035_2615__1_b](https://user-images.githubusercontent.com/18420865/29678213-622d18e4-8906-11e7-8934-edf70a794011.jpg)
![photoshop_dsc_0042_2641__2](https://user-images.githubusercontent.com/18420865/29678210-6228d572-8906-11e7-8049-dced82c19cf1.jpg)
![photoshop_dsc_0042_2641__2_b](https://user-images.githubusercontent.com/18420865/29678214-622f1220-8906-11e7-8d99-3909bc3aaf22.jpg)
![photoshop_dsc_0045_2723__1](https://user-images.githubusercontent.com/18420865/29678211-622a6fc2-8906-11e7-88d1-c41596a35f47.jpg)
![photoshop_dsc_0045_2723__1_b](https://user-images.githubusercontent.com/18420865/29678215-622f0316-8906-11e7-8f71-b1f3a45adbcb.jpg)

How I can do it with dlib? May be some example? Autoencoder or something else?

**Comment by e-fominov** [comment]
A bit more detailed explanation can help us to understand you better. But as i see, you need to find person mouth area
To do this, you can use dlib's [shape_predictor](https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor_abstract.h) object, [see example here](https://github.com/davisking/dlib/blob/master/examples/face_landmark_detection_ex.cpp)

This will give you face landmark coordinates (just googled the scheme):
![image](https://ibug.doc.ic.ac.uk/media/uploads/images/300-w/figure_1_68.jpg)

So you can crop the specific area, and use opencv's [fillConvexPoly](http://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#fillconvexpoly)

**Comment by vrodionovpro** [comment]
Thanks for answer!

Yes, I need to found region of the teeth on mouth area picture.

I tried to use landmark model on full face, but in my case, teeths shapes are very varios and landmark give me dirty shape in many cases. 

But it I can teaching shape predictor on my images, I can give need region. But I dont no how to teach it.


Now I using dnn mmod region finder and it works and teaching ideal for mouth detection. But now I need to find exactly area of teeth.

I think there are some deconv layers on dlib and you can upload picture of mouth and get on output picture of teeth region.

**Comment by e-fominov** [comment]
I recommend you not to spend time on DNN here. Human mouth area has high level of contrast, your images are aligned well and have not many distortions. 

Try shape predictor training first. It is a perfect tool for finding shape of some objects. It is fast, preciese and easy to train. [Check this example](https://github.com/davisking/dlib/blob/master/examples/train_shape_predictor_ex.cpp)

No need to train full face - use only mouth area and mouth landmarks. You will need at least 1k images for training and at 16GB+ CPU RAM

Dlib has no ready-to-use CNN example with deconvolution that I can recommend you to use if you want  to use NN here - it will be your experiments

**Comment by vrodionovpro** [comment]
Yeaaa man, thanks. All working now.

I'm using 3 network - dnn_mmode (face detection defaul base), dnn_mmod (mouth detection trained) and shape_predictor (teeth detection trained).

Thanks to all. Dlib is cool!
