### ISSUE TITLE
I can not compile the library

### ISSUE THREAD

**Issue by axmadjon** [davisking/dlib#779]
i have some problems when compiling android ndk-bundle

I use https://github.com/tzutalin/dlib-android/ such library

help me please

In file included from jni/jni_detections/jni_face_det.cpp:14:
In file included from jni/jni_detections/detector.h:14:
In file included from jni/../dlib/dlib/image_processing.h:11:
In file included from jni/../dlib/dlib/image_loader/../image_processing/scan_image.h:13:
In file included from jni/../dlib/dlib/image_loader/../array2d/../geometry/../image_processing/../image_transforms/spatial_filtering.h:13:
In file included from jni/../dlib/dlib/image_loader/../image_transforms/../simd.h:8:
jni/../dlib/dlib/image_loader/../simd/simd8f.h:104:24: error: ambiguous conversion for functional-style cast from 'const dlib::simd4f' to
      'dlib::simd4i'
            temp.low = simd4i(_low);
                       ^~~~~~~~~~~
jni/../dlib/dlib/image_loader/../simd/simd4i.h:107:16: note: candidate constructor
        inline simd4i(const int32x4_t& val):x(val) {}
               ^
jni/../dlib/dlib/image_loader/../simd/simd4i.h:108:16: note: candidate constructor
        inline simd4i(const uint32x4_t& val):x((int32x4_t)val) {}

**Comment by axmadjon** [comment]
![2017-08-26 10-43-03](https://user-images.githubusercontent.com/6769854/29738997-68cbe59e-8a4c-11e7-9aee-8f897dddd228.png)

**Comment by e-fominov** [comment]
This looks like old clang compilation problem. It was solved some months ago

Try updating dlib to latest version

**Comment by axmadjon** [comment]
sorry is already fixed

**Comment by axmadjon** [comment]
да спасибо умения старая версия была поэтому возникли ошибки
