### ISSUE TITLE
"setup_max_pooling" can not find its function body if I doesn't set macro DLIB_USE_CUDA

### ISSUE THREAD

**Issue by Becavalier** [davisking/dlib#781]
"setup_max_pooling" can not find its function body if I doesn't set macro DLIB_USE_CUDA.

I always get error message "warning: unresolved symbol:_ZN4dlib3cpu7pooling17setup_max_poolingEiiiiii" when I try using dnn in program.

**Comment by davisking** [comment]
Are you following the instructions http://dlib.net/compile.html?

**Comment by Becavalier** [comment]
I can compile dlib successfully when I just use kmeans related functions in my program, but it will causes error if I use dnn related methods in my program. Any idea on this?

BTW: I am try compiling dlib into webassembly, and run it into browser.

**Comment by davisking** [comment]
You are not including dlib's .cpp files.  Follow the instructions on http://dlib.net/compile.html.  You are probably not including dlib/all/source.cpp.
