### ISSUE TITLE
How to disable MKL when installing dlib in Ubuntu 16.04?

### ISSUE THREAD

**Issue by yxchng** [davisking/dlib#783]
I tried disabling the flag "DLIB_USE_MKL_FFT_STR" and "DLIB_USE_MKL_FFT" in CMakeLists.txt but it still keep telling that it has found MKL and probably uses it because my program complains that it cannot find MKL.

**Comment by e-fominov** [comment]
you can try disabling two more options: DLIB_USE_BLAS, DLIB_USE_LAPACK
this will disable using BLAS support at all and will make you compile the library if your MKL installation is broken

[This file](https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/cmake_find_blas.txt) determines the algorithm of searching BLAS libraries. Reading it will help you understand the details

**Comment by yxchng** [comment]
Is libmkl_rt.so a necessary dependencies for dlib? I edited the file u link so that "found_intel_mkl" and "found_intel_mkl_headers" are 0 but it still keep telling me libmkl_rt.so not found

**Comment by davisking** [comment]
No.  You don't need any BLAS libraries to run dlib.  They just make things run faster if you do have them.

**Comment by davisking** [comment]
Also, if it's not finding it then you are done right?  Your goal is for it to not use the Intel MKL.  It's not using the Intel MKL.  So what is the problem?
