### ISSUE TITLE
Found Intel MKL BLAS/LAPACK library but DLIB_USE_MKL_FFT off

### ISSUE THREAD

**Issue by amincheloh** [davisking/dlib#787]
Hi,

I try to compile dlib with Intel MKL on Windows but DLIB_USE_MKL_FFT is off. I think there is a problem in [dlib/cmake_utils/cmake_find_blas.txt](https://github.com/davisking/dlib/blob/master/dlib/cmake_utils/cmake_find_blas.txt) file but not sure how to deal with it.

![capture](https://user-images.githubusercontent.com/1217397/29882981-ef535770-8dd8-11e7-8a67-21124fafe2bf.jpg)

**Comment by davisking** [comment]
It's because it's not finding the Intel MKL header files.

However, are you using fourier transforms?  Do you even care about this
feature?

**Comment by amincheloh** [comment]
I have mkl_version.h file in c:/Program Files (x86)/IntelSWTools/compiler_and_libraries/windows/mkl/include direct, look like cmake does not check is it exists.

I do not directly use this feature, just feel weird.

**Comment by davisking** [comment]
If you want to add it to the list of paths cmake searches and submit it as
a pull request that would be cool :)

Make sure to run the unit tests though to make sure it's really the right
file though.
