### ISSUE TITLE
How object detector SVM sample negative samples?

### ISSUE THREAD

**Issue by nlhkh** [davisking/dlib#788]
This is just a question of how object detector works.

From what I notice, we only give the svm trainer positive samples (regions on images of objects we want to detect) via xml or directly. How, then, would the svm be able to identify when it does not find the objects (negative samples)?

**Comment by davisking** [comment]
This is explained in detail in the reference paper: https://arxiv.org/abs/1502.00046

There is also some information about how the detector works here as well: http://blog.dlib.net/2017/08/vehicle-detection-with-dlib-195_27.html

**Comment by nlhkh** [comment]
Sweet! Thanks Davis!
