### ISSUE TITLE
Averaging a set of 128D descriptors of the same person

### ISSUE THREAD

**Issue by abhisheksoni27** [davisking/dlib#789]
**What I am doing**: I have twenty images of a person with different expressions and lighting conditions. I find the face in the image, then the landmarks, and then the `128D` descriptor. 

I now have a `2D` array of the shape `(20, 128)`.

Next up, since there can be slight variations in the descriptor but not too much for the same face, I average the **20** descriptors to a single `128D` vector. `(128, )`

Do you think it's a feasible approach?

**Comment by davisking** [comment]
It depends on your problem. Maybe it works fine maybe it doesn't.  Try it and see.
