### ISSUE TITLE
where is the training dataset used in frontal_face_detector.h

### ISSUE THREAD

**Issue by wuwei0509** [davisking/dlib#79]
Hi~
I wonder to ask 2 questions:
1.where is the training dataset and xml files like "frontal_faces.xml"
2.which tool u used to train the frontal_face_detector

**Comment by davisking** [comment]
The data is here: http://dlib.net/files/data/ and the tools are discussed here http://blog.dlib.net/2014/02/dlib-186-released-make-your-own-object.html

**Comment by wuwei0509** [comment]
thanks a lot!
