### ISSUE TITLE
dlib-19.6.0-cp36-cp36m-win_amd64.whl wants cublas64_80.dll for work

### ISSUE THREAD

**Issue by manmitya** [davisking/dlib#792]
Hi!
I install python-3.6.2 for Win64 from python.org and dlib from https://pypi.python.org/pypi/dlib
"Clear" dlib don't want to work:
```
C:\>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-64\lib\site-packages\dlib\__init__.py", line 1, in <module>
    from .dlib import *
ImportError: DLL load failed: the given module is not found.
>>>
```
Search with the Process Monitor (Windows Sysinternals) showed that the problem in the absence cublas64_80.dll and cudnn64_7.dll
With dlib-19.4.0-cp35-cp35m-win_amd64.whl there is no problem.
Is it possible to rebuild dlib-19.6.0-cp36-cp36m-win_amd64.whl at https://pypi.python.org/pypi/dlib ?

**Comment by davisking** [comment]
Oops, yeah, I meant to upload the version that didn't use cuda.  Try it now.

**Comment by manmitya** [comment]
Thank you for quick response and new version 19.6! CNN face detection in python very interesting for me. Now all ok :)
