### ISSUE TITLE
does fhog need padding?

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#793]
Hello

I want to use dlib to build (using two students) an application which checks the presence and orientation of THT components mounted on printed circuit boards (capacitors, connectors IC's ...).
I consider that fhog classifiers should do the job (one for each type of component). For checking the orientation, I considered creating a tool like imglab, which also marks the orientation (4 possible directions). For training I considered chipping out all the positive images, rotate them to have the same orientation, and provide them to the trainer. To also have negative samples, the original image is also given to the trainer, with all the positive objects marked as ignore.
But after some experiments, the students are telling me that the detector trained with the original train_object_detector, by manually cropping and rotating the image chips, is not working. But it works if the components are marked as positive in the image of the entire PCB only when they have correct orientation, by rotating the entire image to get all components.
So, does the trainer need some padding around the positive samples?
If yes, how much is enough?

**Comment by davisking** [comment]
You should give the trainer the normal unmodified images.  Give it images that look like the actual images you will be using when you run the detector.  Why don't you want to do this?

**Comment by pepeverde9** [comment]
As I need to detect the orientation of the components, the classifier needs to be able to detect the orientation. On the same PCB, I have the same type of component oriented upwards, downwards, to the left or to the right.
So for training I need to rotate all these components to be oriented upwards, as I do not want to create four datasets in order to create four classifier for the same component (I will probably need to create classifiers for over hundred different component types).
Another way would be to rotate the entire images, but this would increase the needed memory pretty much (while experimenting, one student made the laptop crash by using just 20 images of 3 megapixels because of lack of memory).

**Comment by davisking** [comment]
Rotating is fine.  Although if there are just 4 directions I would train 4 classifiers.  That will run more quickly than rotating 4 times and running the same classifier on each since you won't have to recompute the HOG pyramid 4 times.  Use dlib::evaluate_detectors() to do this efficiently.

However, don't tightly crop things.  If you have a huge 3 megapixel image and are looking for a 10x10 object, obviously you don't need the whole image as input.  Crop it to 100x100 or something reasonable that is still representative of the task you are doing, but doesn't cause you to run out of RAM.

**Comment by pepeverde9** [comment]
OK, thank you.
Probably the real camera will be 12megapixels, and detected objects at least 3000 pixels, but not necessarily square, for now we are using only a 3 megapixel webcam to see how it works.
The plan is to run the classifier only in the region of interest for each component, not on the entire image, as I suspect that in this way it will be possible to inspect a board in a reasonable time.

**Comment by davisking** [comment]
Downsample your images.  3000x3000 pixels is excessive.   What did you set the sliding window size to?  I assume it's still something small, or maybe even at the default value, which is far smaller than 3000x3000.  So it's spending a lot of time scanning for really tiny things in these huge images which is a waste of computer resources.

**Comment by pepeverde9** [comment]
Sorry, I was not very clear. I meant the area of the object image is at least 3000 pixels, like 40x75, or 55x55, which will possibly need upsampling, not downsampling.
One of the classifiers will be used to find the entire board (on a soldering frame of 40x60cm), so maybe this will be downsampled once or twice, but the others will be small components placed on the board (around 1 cm square).
