### ISSUE TITLE
Failed train_shape_predictor_ex

### ISSUE THREAD

**Issue by vrodionovpro** [davisking/dlib#795]
Hi everyone!

I update last dlib today and run train_shape_predictor_ex on windows 10 x64 with 24 gb ram and Intel Xeon 28 cores. My images from 100x100 to 800x800 and I try to detect some region from 8 points.

All training works perfectly on 500 images, but on 1200 it fails, then finished, but before saving model unfortunately. 

I tried some parameters and trying to debug project in VS 2015, but see only it in output window:
```
Exception thrown at 0x00007FFF72C71F28 in train_shape_predictor_ex.exe: Microsoft C++ exception: dlib::fatal_error at memory location 0x000000F35F6FDED0.
The program '[15720] train_shape_predictor_ex.exe' has exited with code 0 (0x0).

```

On my screen I see that:
```
Fitting trees...
Training complete
```

And my code is (try to change all parameters):
```
...
trainer.set_oversampling_amount(100);
trainer.set_nu(0.05);
trainer.set_tree_depth(1);
trainer.set_num_threads(1);
trainer.be_verbose();
trainer.set_cascade_depth(2);
trainer.set_num_trees_per_cascade_level(80);

shape_predictor sp = trainer.train(images_train, faces_train);
...
```

**Comment by davisking** [comment]
Print the error string in the exception.  It's going to tell you something
very important about what is wrong.

**Comment by vrodionovpro** [comment]
Sorry man. I found it. My model have only 8 points. I then you call interocular_distance with 68 points it fails.

Strange than VS2015 cannot debug it, then I run generated by cmake project in debug x64 mode.

**Comment by davisking** [comment]
Visual studio, for all it's problems, is definitely able to debug a thrown exception.  You just have to tell it to do that.  Or print the message or something.  It's default behavior is to let the program terminate.
