### ISSUE TITLE
NDK-BUILD r15 compile error

### ISSUE THREAD

**Issue by xjohnxjohn** [davisking/dlib#797]
Hi
   I try to port dnn_face_recognition to android with ndk-build.  I used the same method of https://github.com/tzutalin/dlib-android-app. When I built library with ndk-build, it show error below
![screenshot from 2017-09-03 16-18-32](https://user-images.githubusercontent.com/7420735/30001852-5f701b2c-90c4-11e7-9bd7-a1bc39b66839.png)

How to solve it?

**Comment by davisking** [comment]
Read this entire page: http://dlib.net/compile.html

But to help a little, you are missing dlib/all/source.cpp.

**Comment by xjohnxjohn** [comment]
thanks, Davis.
