### ISSUE TITLE
Landmark detection with custom initial shapes

### ISSUE THREAD

**Issue by tuxa** [davisking/dlib#798]
I just wanted to know if it make sense to create an own shape predictor class (analog to shape_predictor.h) that takes a custom initial shape when detecting the landmarks.
The background is, that I already have 5 landmark points in addition to the face bounding box (due to a powerful CNN), and I want to use this information to fit 68 landmark points. In my head this should work really well, since the initial shape would just need to be transformed slightly.

The only problem I'm thinking of is that I would also need to have an own trainer implementation, since I would need to create an own model that includes this prior information.

What do you think?

**Comment by davisking** [comment]
Sure, that makes sense.  You don't know how good it is until you try it.  My guess is that it's not worth the trouble.  But you never know.
