### ISSUE TITLE
Parse Error in PNG Files 

### ISSUE THREAD

**Issue by danishnazir** [davisking/dlib#804]
HI!
I have png files in my dataset that I am using for training! Whenever I starts training or try to make boxes on png files it says
RuntimeError: png_loader: parse error in file images/person_236d.png
Now the thing is it works fine for jpg files can you please help me what I am doing wrong? or it is a bug in. libpng ? or the version of libpng is making issues? 
Regards

**Comment by davisking** [comment]
I highly doubt there is a bug in libpng.  You probably just have your file path typed wrong.

**Comment by danishnazir** [comment]
thank you sir for replying
I have double checked the paths!! plus my point is why its working for jpg images? i have installed dlib in 2 machines
1)Macbook Pro macos Siera 
2)Google VPS
and in both i am getting the same error

**Comment by scott-vsi** [comment]
Perhaps it is a malformed png (#106). You could try to load it with another program and resave it. Alternatively, you could build dlib in debug mode and run it via gdb.

**Comment by danishnazir** [comment]
Thanks guyz i will check it out and let you know thanks for your support :)
