### ISSUE TITLE
How to train a shape predictor after the dlib neural network?

### ISSUE THREAD

**Issue by Stanpol** [davisking/dlib#806]
I tried to repeat the examples [dnn_mmod_train_find_cars_ex.cpp](http://dlib.net/dnn_mmod_train_find_cars_ex.cpp.html) and [dnn_mmod_find_cars_ex.cpp](http://dlib.net/dnn_mmod_find_cars_ex.cpp.html), but got stuck with training a shape predictor to predict object boxes. This step is skipped in the examples, even if shape_predictor is included in a pretrained model.

So after finishing training a neural network `serialize("mmod_rear_end_vehicle_detector.dat") << net;` I use a new trainer for a shape predictor `shape_predictor_trainer sptrainer;` 
On input I guess we give the output of neural network and the original boxes `shape_predictor sp = sptrainer.train(net(images_train), boxes_train);` but shape_predictor expects full_object_detection, which boxes_train doesn't have.

Did anyone manage to repeat these examples including the shape predictor training?
Could you please provide a snippet how properly to train the shape predictor in these examples?

Thanks!

**Comment by davisking** [comment]
Tell the shape predictor to predict the 4 box corners.  There is an example program that show show to train shape predictors.  You tell them to predict points.  Tell it to predict 4 points in each box, the box corners.
