### ISSUE TITLE
run time exception when use dlib

### ISSUE THREAD

**Issue by aligoglos** [davisking/dlib#808]
i compile dlib with visual studio 2015 successfully and add my c++ project to use hog face detection class. i compile my program and run successfully without any problem, but when i copy my program to another computer and run exe file exception occurred ! for debugging i create log file in my program to log witch line of code run successful and witch line rise exception and i found when my program wants to execute this line :
`detector = dlib::get_frontal_face_detector();  `  , rise exception. why its occurred?
its because of dlib library or another reason like compiler or architecture issue?
my two computer have different hardware (different CPU and GPU and ...) but two computer is x64.
if have any idea please described thanks.
can i compile dlib as dynamic library and put its dll's behind my exe?

**Comment by e-fominov** [comment]
if you got some exception, it should have some message inside, describing the problem. I am sure, it is displayed somewhere in the output console. But you can use this code to understand the situation:

```C++
try
{
    detector = dlib::get_frontal_face_detector();
}
catch(const std::exception& e)
{
    std::cout << e.what() << std::endl;
}
```

If you will have an error message - all fine, just read it and do something to fix it. If not - may be some invalid instruction set problem. I.e. compiled with AVX, but the second machine has old CPU and it will crash running the application

**Comment by aligoglos** [comment]
my problem is try catch not work !!! and program closed directly.
if issue is instruction set can i set my compiler to compile dlib to all CPU's ?
my first computer's CPU is `6700 HQ` and second is `Intel® Core™2 Duo Processor P8700`
but i also test in mini computers with CPU's : `Celeron 1037U and J3160` but not different.

**Comment by davisking** [comment]
Don't enable AVX instructions.  Or maybe it's SSE4.  Turn those off if you
are running on a really old CPU.

**Comment by aligoglos** [comment]
yes solved issue. i change property `Properties->c/c++->Code Generation-> Enable Enhanced Instruction: Advanced Vector Extensions (/arch:AVX)` to `Not Set` and recompile project and works.
thanks for your advice.
