### ISSUE TITLE
 hwo to reduce the memory usuage when using fhog_object_detector_ex?

### ISSUE THREAD

**Issue by tornadomeet** [davisking/dlib#81]
Hello,
when i command `fhog_object_detector_ex` to training the face detector, it using all machine's memory(>200G), I think it is because the training face numbers is about >100k and training image number is about > 10k, so i guess  it maybe put all the hog features(of all faces)into the memory when training the structural svm classifier, so when debug the code, i found it is the line https://github.com/davisking/dlib/blob/master/examples/fhog_object_detector_ex.cpp#L148 which caused it.
so how to change this ?please give some advise, thanks!

**Comment by davisking** [comment]
Get more RAM or use smaller images.  Also, general dlib questions should be directed to the sourceforge forums.

**Comment by tornadomeet** [comment]
ok,thanks
