### ISSUE TITLE
CBLAS Build error in dlib external

### ISSUE THREAD

**Issue by travek** [davisking/dlib#814]
Hi!

I'm trying to compile cblas that is in external/cblas folder of dlib.
I'm using MSVS 2015.
I run 
cmake -G "Visual Studio 14 2015 Win64"
and I got 
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:11 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.
  
I installed G95 fortran compiler before but Cmake doesn't see it.
Could someone advise how to fix this ?

**Comment by davisking** [comment]
Why do you want to do this in the first place?

**Comment by travek** [comment]
Davis,
You mean in external/cblas ?

I thought Ican build a library just to add this lib to the project after.

**Comment by davisking** [comment]
I don't see any reason why anyone would want to build that cblas project when using visual studio.  If you want a BLAS library, download the Intel MKL.  

I should also point out that cblas doesn't contain a BLAS, it's just part of something that's useful in certain situations when you *already have a BLAS library*, which I highly doubt is your situation.
