### ISSUE TITLE
dnn mmod face detector training problem

### ISSUE THREAD

**Issue by mfouadthabet** [davisking/dlib#815]
Trying to train the dnn mmod face detector as instructed in the example files (dnn_mmod_face_detection_ex , dnn_mmod_ex) and using the dataset from the link:
http://dlib.net/files/data/dlib_face_detection_dataset-2016-09-30.tar.gz

windows 10 , cuda 8 , dlib 19.6.

The only changes I made besides the changes stated in the face detector examples documentation was to change trainer.set_iterations_without_progress_threshold(2500) as it stayed for ~8 hours without real improvement with 0.1 LR with threashold = 8000
 

Note:
The generated dat file is ~24MB and it results in the below error by the end of training and also upon running the detection example using it.
It seems that ~1.35 as an average loss is the best it can get , is this good enough?

===========================
Saved state to mmod_sync
step#: 22954  learning rate: 0.0001  average loss: 1.36111      steps without apparent progress: 2360
step#: 22985  learning rate: 0.0001  average loss: 1.32451      steps without apparent progress: 2399
step#: 23016  learning rate: 0.0001  average loss: 1.36526      steps without apparent progress: 2425
step#: 23047  learning rate: 0.0001  average loss: 1.35642      steps without apparent progress: 2451
step#: 23078  learning rate: 0.0001  average loss: 1.34853      steps without apparent progress: 2490
Saved state to mmod_sync_
done training

Error detected at line 1007.
Error detected in file ..../dlib-19.6/dlib/dnn/cuda_dlib.cu.
Error detected in function void dlib::cuda::affine_transform(dlib::tensor &, const dlib::tensor &, const dlib::tensor &, const dlib::tensor &).

Failing expression was A.nr()==B.nr() && B.nr()==src.nr() && A.nc()==B.nc() && B.nc()==src.nc() && A.k() ==B.k() && B.k()==src.k().

A.nr(): 567
B.nr(): 567
src.nr(): 477
A.nc(): 159
B.nc(): 159
src.nc(): 134
A.k(): 16
B.k(): 16
src.k(): 16

==============================================

**Comment by davisking** [comment]
You must have changed the network architecture to something that doesn't make sense to get that error.  But you didn't post the changes you made.  Post code or no one will help you.

**Comment by mfouadthabet** [comment]
Thanks , for the fast response.
After posting this error I found this help, o be:

https://sourceforge.net/p/dclib/discussion/442518/thread/86c02f97/

**Comment by davisking** [comment]
A reasonable loss depends on your problem.  Look at the output when it's done and see if it looks good enough for what you are trying to accomplish.
