### ISSUE TITLE
Can't compile a project with DLIB and DLIB_USE_BLAS

### ISSUE THREAD

**Issue by travek** [davisking/dlib#816]
Hi!

I'm trying to build my project that uses dlib with DLIB_USE_BLAS defined. 
I'm using MSVS 2015.
I have installed Intel MKL.
I added to the MSVS project libs:
mkl_core.lib
mkl_intel_lp64.lib
mkl_intel_thread.lib
libiomp5md.lib

When I'm trying to build I've got
 error LNK2001: unresolved external symbol _cblas_dscal
 error LNK2001: unresolved external symbol _cblas_dger
 error LNK2001: unresolved external symbol _cblas_daxpy

 Why it'slooking for _cblas_* functions instead of cblas_* that I can see in MKL *.h files ?
 May be Ineed to use specific options to build this ?...

**Comment by davisking** [comment]
You need to link to the Intel MKL in the correct way.  There are a lot of options and they are documented in the Intel MKL documentation.  Either refer to their documentation for instructions or use CMake.  The dlib cmake scripts will set up the linking options for the Intel MKL if you use cmake.  If you don't want to use cmake then follow the Intel MKL's instructions.
