### ISSUE TITLE
What is  the most efficient way to create an array2d<rgb_pixel> while the data is stored in memory?

### ISSUE THREAD

**Issue by adhere** [davisking/dlib#818]
If the image(raw data, bmp, png, jpeg format) data is holding on memory， such as：

`const char *imgDataPtr = "The Image Data";`

How can Iconvert it to array2d<rgb_pixel> efficiently?

As far as I know:
1.  Save the memory data to disk and use dlib::load_image to load the image. (Bad)
2.  Convert the memory data to cv::Mat and do it like "examples/webcam_face_pose_ex.cpp". (Not good)
3.  If the memory image is bmp or dng, load_bmp or load_dng can do that. But I want to support png and jpeg as well.
`void load_bmp (image_type& image_, std::istream& in_);
 void load_dng (image_type& image_, std::istream& in_)`
4.  If on Linux, I can use fmemopen to create a FILE * from memory data, I can implement a memory version  load_image. But I want it works on Windows too.

5. How, need help ! -_

This may be duplicated. [how-to-assign-memory-images-to-a-dlib-array2d-or-image](https://stackoverflow.com/questions/41991651/how-to-assign-memory-images-to-a-dlib-array2d-or-image)

Thanks!

**Comment by davisking** [comment]
There isn't any function in dlib for decoding jpeg and png files in memory.  The underlying libjpeg and libpng libraries do support doing that though, so you can just call them directly to decode them into a memory buffer.  An array2d is just a contiguous memory buffer. So there isn't any problem doing this.  You should look to the libpng and libjpeg documentation for further details.
