### ISSUE TITLE
How to training 5 hog detector and combine it to one detector?

### ISSUE THREAD

**Issue by tornadomeet** [davisking/dlib#82]
hello, i am newbie with dlib, and i found the commit https://github.com/davisking/dlib/blob/master/dlib/image_processing/frontal_face_detector.h, in which it said that the pre-trainined face detector in dlib is built out of 5 HOG filters.  
so if i want to train my own face detector with dlib, should i train it separate and then combine them?if so, how to do that?  or if not, does it means thant i only need to train one detector with 5 pose face images at once?  
thanks a lot!

**Comment by davisking** [comment]
It depends on what you want to do.  There are many possible design decisions.   So I can't say.  

Also, general questions should be directed to the sourceforge forums.  The github issue tracker is for dlib issues (e.g. bugs, things that need doing).
