### ISSUE TITLE
No known transformation from dlib's input_rgb_image_pyramid  layer to caffe.

### ISSUE THREAD

**Issue by ygyin-ivy** [davisking/dlib#820]
i want to convert mmod_human_face_detector.dat to caffe model , then use ncnn framework to speed up face detect on mobile.
but the 181209 line of "mmod_human_face_detector.dat" xml has a layer "input_rgb_image_pyramid" ,
and convert_dlib_nets_to_caffe cant convert this layer, 
how can i fix this? i use dlib release version 19.6.

**Comment by davisking** [comment]
Caffe just doesn't support that layer type.  There is nothing you can do about it.

**Comment by ygyin-ivy** [comment]
thanks



yinyongguang@ivymobile.com
 
From: Davis E. King
Date: 2017-09-14 17:36
To: davisking/dlib
CC: ygyin-ivy; Author
Subject: Re: [davisking/dlib] No known transformation from dlib's input_rgb_image_pyramid layer to caffe. (#820)
Caffe just doesn't support that layer type. There is nothing you can do about it.
