### ISSUE TITLE
undefined reference to symbol 'cblas_sscal'?

### ISSUE THREAD

**Issue by TianxinTse** [davisking/dlib#822]
I've successfully built dlib on Ubuntu16.04 which made me very happy. But when I compile an example `face_landmarks_detection_ex.cpp` with dlib, it complained as follows:

```
>> g++ -std=c++11 fld.cpp -o fld `pkg-config --cflags --libs dlib-1`         
/usr/bin/ld: /tmp/cc6IpsiA.o: undefined reference to symbol 'cblas_sscal'
//usr/lib/libcblas.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I've googled it for a long time. But there's no solution for this.

**Comment by davisking** [comment]
Something is wrong with your blas library.  Install openblas or some other blas that isn't missing symbols.

**Comment by emavgl** [comment]
Same problem here, openblas did not solve.

**Comment by davisking** [comment]
You guys should use cmake.  Follow the instructions here: http://dlib.net/compile.html

**Comment by emavgl** [comment]
cmake works fine, but the problem occurs when linking dlib to another project.
However, I solved installing OpenBLAS (compiling and linking it) as you suggested and using [this guide](https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts). Seems that the problem was a non-updated package.

**Comment by IvyGongoogle** [comment]
Same problem

**Comment by arju1996** [comment]
same issue still persists
