### ISSUE TITLE
what is the goal of add_layer::sample_expansion_factor?

### ISSUE THREAD

**Issue by e-fominov** [davisking/dlib#826]
DNN layer wrappers (add_layer) have a member names "sample_expansion_factor", it is initialized after running the "to_tensor" method and shows the relation between the count of samples used as netwok input and the tensor::num_samples() produced by the input layer

No of Dlib's layers changes this amount - so all inputs now produce the same num_samples as used in to_tensor input

I was wondering, if there is some special idea to have this member?

In my experiments, I have created RNN (LSTM) implementation with Dlib and I found this member good to be used to hold the sequence len of RNN input
For example, MNIST digit has dimension of 1x28x28, I am creating a batch of 10 digits, and some new cusom input layer produces a tensor of 280x1x1x28, where one row of MNIST digit is used as one real training time step sample for RNN. So here I have sample_expansion_factor = 28

This makes me easy to use all layers of Dlib to process this input except the loss layer. And RNN works fine as I know the length of training sequence

Is it a good decision to use this member for RNN to hold time sequence len or may be there is some other way to encode the time dimension?

**Comment by davisking** [comment]
Yes, that's the idea.  I added it exactly for this kind of application.  Another application for it would be in a triplet or pairwise metric learning loss where the expansion would be 3 and 2 respectively.  Nothing in the code does anything with it, it's just there to let the loss layer validate it's inputs and to make the documentation more explicit.

**Comment by e-fominov** [comment]
ok, so i will cleanup my code and will make PR with LSTM example, this will take about 1-2 weeks

**Comment by davisking** [comment]
Sweet

**Comment by RBelogorodtsevFBase** [comment]
@e-fominov @davisking so do you have this LSTM example implemented somewhere?
