### ISSUE TITLE
Import of tensorflow affects the training of an object detector

### ISSUE THREAD

**Issue by csagonas** [davisking/dlib#828]
It looks like training a simple object detector in python via `train_simple_object_detector` is affected when the tensorflow package is already imported. For an unknown reason the training procedure convergences after just a few of steps (in most of cases after only 2 steps). I tried to train the detector before importing the tensorflow and everything was ok. Any explanation or solution for the aforementioned behaviour?

**Comment by davisking** [comment]
I don't know.  But if I had to guess I assume it's because you have managed
to link to two different and incompatible BLAS libraries.

**Comment by csagonas** [comment]
Thanks a lot for the response!
