### ISSUE TITLE
face landmark style error

### ISSUE THREAD

**Issue by Aspirinkb** [davisking/dlib#835]
Hello everyone, I use dlib's (19.4.0 version) face recognition api according to its python example, but there is a face landmark style error.
code snippet:
```
predictor_path = './models/dlib/shape_predictor_5_face_landmarks.dat'
face_rec_model_path = './models/dlib/dlib_face_recognition_resnet_model_v1.dat'
...
faces = detector(img, 1)
...
shape = shape_predictor(img, face)
face_descriptor = face_recognizer.compute_face_descriptor(img, shape)
```
error info:
```
face_descriptor = face_recognizer.compute_face_descriptor(img, shape)

RuntimeError: The full_object_detection must use the iBUG 300W 68 point face landmark style.
```

It seems that the `shape` must be iBUG 300W 68 point face landmark style, but the `shape_ predictor` returns some other face landmark style since it is initialed by  `shape_predictor_5_face_landmarks.dat`. But this is given in dlib's [python_examples face_recognition.py](https://github.com/davisking/dlib/blob/master/python_examples/face_recognition.py)

**Comment by davisking** [comment]
Use the new version of dlib

**Comment by Aspirinkb** [comment]
@davisking The newest version of Dlib on Anaconda Cloud is 19.4.0, so I use the older shape predictor, i.e. `shape_predictor_68_face_landmarks.dat`. Does any performance difference exist between these two?

**Comment by davisking** [comment]
Yes, they are different.  The new one is smaller and faster and works with a wider range of detectors.  They both give the same alignment accuracy.
