### ISSUE TITLE
How to do mmod detection model harder

### ISSUE THREAD

**Issue by vrodionovpro** [davisking/dlib#837]
Hi. I used mmod detection model and it's cool. Lightweight train and detection.

But how can I train more harder model for object detection? I don't know which numbers and layers in model description need to increase for more effectively train. Time is nothing for my case.

Can I use resnet but for detection? Or other heavy models and how? Thanks!!!

**Comment by AndreaPisoni** [comment]
I will leave it to Davis to answer, but my understanding is that as long as
your input is an image pyramid, and your output is a mmod_loss layer, you
can have any other layer in the middle, be it resnet, inception etc...

**Comment by vrodionovpro** [comment]
Tnx man, I tried pack dlib's resnet model

`// training network type
using netMouth = loss_mmod<fc_no_bias<128,avg_pool_everything<
                            level0<
                            level1<
                            level2<
                            level3<
                            level4<
                            max_pool<3,3,2,2,relu<bn_con<con<32,7,7,2,2,
                            input_rgb_image_pyramid<pyramid_down<6>>
                            >>>>>>>>>>>>;`


And get error 
`error C2039: 'set_num_filters': is not a member of 'dlib::fc_<128,dlib::FC_NO_BIAS>'`

and commented line `net.subnet().layer_details().set_num_filters(options.detector_windows.size());`

but got error:
`error C2039: 'map_output_to_input': is not a member of 'dlib::fc_<128,dlib::FC_NO_BIAS>'`


I think need right syntaxis of resnet description for mmod only, but I don't know how to do it.

**Comment by davisking** [comment]
Don't use fc layers.  Think about it.  It's got to be convolutional.  But in general you can do whatever you want.

**Comment by vrodionovpro** [comment]
Thanks for answer, but it still won't works. I replaced `fc_no_bias<128,`with `con<1,9,9,1,1,`
and get this error:

`dlib/dnn/utilities.h:218:41: error: no member named 'map_output_to_input' in
      'dlib::add_prev_<tag1>'
                p = net.layer_details().map_output_to_input(p);
                    ~~~~~~~~~~~~~~~~~~~ ^`

**Comment by davisking** [comment]
Hmm, yeah, I thought that got updated in a PR a bit ago.  I guess not.  Anyway, you can probably just add that function to the layer as an identity mapping.  It's a little bit weird to have it in add_prev, since it pulls together two potentially differently sized layers.  But in the cases where it does make sense the identity mapping is what you would want.

**Comment by vrodionovpro** [comment]
Man, my little brain exploded from your message. Anyway, thanks for your work and I hope someone in future build complex big model for object detection!
