### ISSUE TITLE
[python] dnn face recognition with cnn face detector

### ISSUE THREAD

**Issue by kizilkanat** [davisking/dlib#838]
Hi Davis, appreciate your every piece of work.
I have been looking for your face recognition examples for a while, and used frontal face detector (hog+svm) successfully in my dnn face recognition (your pretrained resnet v1 model) application. Now, I am planning to employ your new 5-point landmark detection instead of older 68-point landmark detector, together with cnn face detector. What should be a proper step to  take, to employ a combination of your cnn face detector + 5-point landmark detector + dnn face recognizer?
Afaik, the 5 point landmark detector and dnn face recognizer (pretrained resnet v1 model) were trained with hog+svm face detector outputs, so that you are not using cnn face detector in your recent face rec examples. So, do I have to train 5-point landmark detector and dnn face recognizer from scratch, with cnn face detector outputs to get reasonable results when using cnn as face detector?

**Comment by davisking** [comment]
You don't have to do anything.  The new 5-point model is a drop in replacement for the old one.  That's the whole point :)

**Comment by kizilkanat** [comment]
So, I am just replacing the frontal face detector with cnn face detector and thats it? dont have to train a new resnet model with cnn face detector outputs?
