### ISSUE TITLE
installing dlib

### ISSUE THREAD

**Issue by Pedimage** [davisking/dlib#84]
Hi .I've typed these commands into command prompt in example folder: 
mkdir build
cd build  
cmake ..
cmake --build
  now how can I use dlib in my project? is there any way to use dlib?
 thanks in advance.

**Comment by davisking** [comment]
What are you trying to do?

**Comment by Pedimage** [comment]
I want to use dlib in my project.
I've followed http://dlib.net/compile.html

**Comment by davisking** [comment]
What does that mean?  You want to write some code that uses dlib?

**Comment by Pedimage** [comment]
sorry. 
yes i want to use it in my project. actually I want to write some code that uses dlib.

**Comment by davisking** [comment]
The examples show you how to do this.  There are literally 84 different and complete example programs illustrating it's use.  Each has a narrative that explains what is going on and how it is accomplished.   There is also a complete API reference here http://dlib.net/ which lists every feature in the entire library with detailed documentation in each case.   Moreover, there is even a recommended sequence of text books that can take you from not knowing how to program at all to some level of expert in all the topics in dlib: http://dlib.net/books.html

You have posted the same question over 10 times now.  Unfortunately, I don't know what more I could possibly do to explain how to use dlib.  You obviously have just begun learning to program.  So as I suggested in the beginning, get an introduction to programming book and start there.  Please don't keep posting questions that essentially say "how can I write a program?".  These aren't dlib questions and are well answered in any of the many introduction to programming text books available.

**Comment by Pedimage** [comment]
it's just a misunderstanding. I typed all in dlib site. but I it didn't install completely.

**Comment by davisking** [comment]
There is no install.  You put the .cpp text files into your compiler and you can write C++ programs.

**Comment by Pedimage** [comment]
sorry dear davis. can i ask you another question. my problem is not how to write a c++ code.:)

**Comment by davisking** [comment]
What is your problem? :)

**Comment by Pedimage** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17319072/13380144/8e6d5b8c-de33-11e5-9a85-44a696017585.png)
thank you.:)
let me start with your example.
for starting example I typed what you suggested in command prompts.
after that I have a folder called "build". I attached it.
are these files which created, true?
when I run these example, they exit with code 0.

**Comment by davisking** [comment]
That's what's supposed to happen.  But you are asking a basic programming question "how do I use visual studio?".   This has nothing to do with dlib and, as I said, is best answered by consulting a good text book.

**Comment by Pedimage** [comment]
ok.thanks
