### ISSUE TITLE
Python setup.py  install  error

### ISSUE THREAD

**Issue by cong520** [davisking/dlib#842]
pip，git clone,and zip the same problem,  i'am centos6
[root@]# python setup.py install --yes USE_AVX_INSTRUCTIONS
running install
running bdist_egg
running build
Detected Python architecture: 64bit
Detected platform: linux2
Configuring cmake ...
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.41.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib64/libpython2.6.so (found suitable version "2.6.6", minimum required is "2.6")
-- USING BOOST_LIBS: /usr/lib64/libboost_python-mt.so
-- C++11 activated.
-- Enabling AVX instructions
CMake Deprecation Warning at /home/bl/dlib/dlib/CMakeLists.txt:31 (cmake_policy):
  The OLD behavior for policy CMP0023 will be removed from a future version
  of CMake.
  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23")
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bl/dlib/tools/python/build
Build using cmake ...
Scanning dependencies of target dlib
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
In file included from /home/bl/dlib/dlib/base64/base64_kernel_1.h:6,
                 from /home/bl/dlib/dlib/base64/base64_kernel_1.cpp:6:
/home/bl/dlib/dlib/base64/../algs.h:313: error: expected constructor, destructor, or type conversion before ‘bool’
/home/bl/dlib/dlib/base64/../algs.h:324: error: expected constructor, destructor, or type conversion before ‘bool’
/home/bl/dlib/dlib/base64/../algs.h:335: error: expected constructor, destructor, or type conversion before ‘bool’
/home/bl/dlib/dlib/base64/../algs.h:346: error: expected constructor, destructor, or type conversion before ‘bool’
gmake[2]: *** [dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o] Error 1
error: cmake build failed!

**Comment by davisking** [comment]
Your compiler is really old.  You need to use a compiler that supports C++11.  So install a newer version of gcc or clang.
