### ISSUE TITLE
How to speed up the face detection

### ISSUE THREAD

**Issue by Assassintears** [davisking/dlib#844]
I want to detect face from video stream, but the detection consuming of a frame comes up to exaggeratedly more than five seconds. Can the Dlib face detection consuming time be optimized to milliseconds like OpenCV?

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whyisdlibslow

**Comment by cfoch** [comment]
Hello, Is there something faster that the dlib frontal face detector that I can use with the 68 face keypoints landmark model predictor?

**Comment by davisking** [comment]
No.  Also, http://dlib.net/faq.html#Whyisdlibslow

**Comment by cfoch** [comment]
What about DNN face detector? Isn't it faster on GPU http://dlib.net/dnn_mmod_face_detection_ex.cpp.html

**Comment by davisking** [comment]
Yes, the CNN runs faster on the GPU than the CPU. Maybe that's fast enough
for you if you get a good enough GPU. I can't say.

**Comment by ndtreviv** [comment]
It might be helpful to see a benchmark documented. For example, I'm using the dnn detector on the GPU. When processing a single 250x250px image on an AWS g4dn.4xlarge instance (which has a single NVIDIA Tesla T4 GPU), it takes ~1.5s to find the face using the detector.

That's with this as the cmake command:
```
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DUSE_AVX_INSTRUCTIONS=ON ../
```
and this as the build:
```
cmake --build . --config Release
```

Does that sound right? It _seems_ slow, but I don't have a ton of experience with cnn detector speeds, so...how can I tell?

**Comment by davisking** [comment]
That does not sound right.  Are you timing the whole program?  Note that the CUDA runtime has a long startup time.

**Comment by ndtreviv** [comment]
This is the what I'm timing:

```
void extract_faces_cnn(std::vector<dlib::matrix<rgb_pixel>> &faces, std::vector<dlib::rectangle> &coords, dlib::cv_image<rgb_pixel> &img, shape_predictor &sp) {
    matrix<rgb_pixel> imgmat = mat(img);

    std::cout << "Starting: " << get_current_time_millis() << std::endl;
    auto dets = cnn_detector(imgmat);
    std::cout << "Done: " << get_current_time_millis() << std::endl;

    for (auto&& face : dets)
    {
        auto shape = sp(imgmat, face);
        matrix<rgb_pixel> face_chip;
        extract_image_chip(img, get_face_chip_details(shape,150,0.25), face_chip);
        faces.push_back(move(face_chip));
        coords.push_back(face.rect);
    }
}
```

Output is:
```
Starting: 1602238331667
Done: 1602238333133
```
Difference is  1,466

I thought it was because dlib wasn't using BLAS, but that's now been resolved and it is, and nothing has changed speed-wise.

**Comment by davisking** [comment]
The first time you run the detector the cuda runtime turns on. That takes a while.

**Comment by ndtreviv** [comment]
> The first time you run the detector the cuda runtime turns on. That takes a while.

That's good to know - thanks!
To test I literally copy-pasted the `cnn_detection` line with timing outputs.

First detection took 1,909ms, second took 13ms.
dlib is *not* slow!

**Comment by CSharpDummy** [comment]
If you install dlib using the Python pypi installer, do you still need to specify the "release" setting on windows? Or is that part of the make file?

**Comment by davisking** [comment]
You don't mention release or cmake or anything like that if you are installing the python bindings.  You do exactly and only what http://dlib.net/compile.html says and it should be fine.
