### ISSUE TITLE
libpng and libjpeg-turbo

### ISSUE THREAD

**Issue by skryv-softserveinc** [davisking/dlib#852]
hi,
consider using libjpeg-turbo as good alternative to libjpeg.
also boost::GIL as an alternative to libpng

**Comment by davisking** [comment]
I use dlib with libjpeg turbo all the time.  You can link to whatever libjpeg you want already.  The same goes for libpng implementations.

**Comment by skryv-softserveinc** [comment]
I have it built but when I try to use it in OpenFace I get:
CMake Error at lib/3rdParty/dlib/CMakeLists.txt:362 (add_library):
  Cannot find source file:

    include/dlib/external/libjpeg/jcomapi.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

**Comment by davisking** [comment]
Sounds like a problem with the openface build scripts.  You should post in their forums.

**Comment by skryv-softserveinc** [comment]
Thanks
