### ISSUE TITLE
how can I compile the cpp with cuda?

### ISSUE THREAD

**Issue by yanchao12122** [davisking/dlib#853]
when I use this command to compile the source code:

g++ -std=c++11 -O3 -I.. ../dlib/all/source.cpp dnn_metric_learning_on_images_ex.cpp  -lX11 -lpthread

it runs so slow~
so if I want to use the cuda, what can I do?

**Comment by davisking** [comment]
Use cmake and follow the instructions here http://dlib.net/compile.html
