### ISSUE TITLE
decision function output is same for every input sample!!

### ISSUE THREAD

**Issue by msobhan69** [davisking/dlib#855]
I trained a svm_c based on svm_c_ex.cpp (normalized_function object).
training_data: vector<matrix<double, 128, 1>>
The classifier output is constant and same for every input sample.
what is my mistake?

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whydoesmydecisionfunctionalwaysgivethesameoutput

**Comment by msobhan69** [comment]
Dear @davisking , tanks for your quick reply, you are right. But, I do cross validation using cross_validate_trainer() with the gamma and c that i used for training, and I got good result from cross_validate_trainer() output.
Why a gamma value is good in cross_validate_trainer() but not in trainer.train()?

**Comment by msobhan69** [comment]
Dear @davisking , I changed gamma value to many values from small to large, but decision_function outputs are very close together yet.
