### ISSUE TITLE
Unable to use evaluate_detectors in python

### ISSUE THREAD

**Issue by danishnazir** [davisking/dlib#856]
Hi i want to use evaluate_detectors function in python can you please tell me how to do that? if its not in python then do tell how can i add it thanks

**Comment by davisking** [comment]
It's not part of the pyhton API.  If you want to add it edit the code in
tools/python.

**Comment by danishnazir** [comment]
thanks i do need to add the src file link in my cmake file? do correct me if i am wrong. moreover which file that i need to add ? do you have any guide on that?
