### ISSUE TITLE
Train CNN mmod with negative images

### ISSUE THREAD

**Issue by vrodionovpro** [davisking/dlib#858]
Hi.

I train my cnn mmod with 
<image ...>
   <box ...>
</ image>

Can I add negative images for train with empty box like this:
<image ...>
</ image>

or dlib just ignore them in train process?

**Comment by davisking** [comment]
That's fine.  You can do that.  But look at the code you are running.  It's your responsibility to call train_one_step() with whatever images you want.  Dlib includes functions for loading those xml files.  But you still have to write code that passes the data to the training routines.  The examples discuss this in great detail.
