### ISSUE TITLE
How to create the Header File to work with LIB file(dilb.lib)

### ISSUE THREAD

**Issue by FlamingJay** [davisking/dlib#859]
we can generate a LIB file with the help of CMake.
But if i want to import the LIB file into my VS project ,i must use a Header file to work with LIB file.
So,the question is how to create a header file ?

**Comment by davisking** [comment]
This question makes no sense.  The dlib download comes with all the header files.  You don't "make them".  You need to either learn to use visual studio and how C++ works, or, use cmake the way the examples show.  Read the instructions here http://dlib.net/compile.html.  They tell you how to compile the examples.  Then read the example's CMakeLists.txt file.   It's a tutorial.  It's very easy to use cmake to setup visual studio.

**Comment by davisking** [comment]
http://dlib.net/examples/CMakeLists.txt.html
