### ISSUE TITLE
Accuracy parameters of Dlib 19.7

### ISSUE THREAD

**Issue by VanitarNordic** [davisking/dlib#861]
Hello,

May I ask you about the Accuracy or Recall or mAP or IoU of your final model-19.7?
What Parameters were available for you is enough, not necessary all parameters that I mentioned above.

I could not find this info in the blog post.

**Comment by davisking** [comment]
I don't recall.  But you can download the training dataset and run it on the test data included to see whatever metrics you want.

**Comment by VanitarNordic** [comment]
I received this error after the Build process finished:

`fatal error C1083: Cannot open include file: 'sqlite3.h': No such file or directory`
