### ISSUE TITLE
CUDA not being used

### ISSUE THREAD

**Issue by alison-carrera-pegasus** [davisking/dlib#863]
Hi @davisking I've compiled dlib, apparently successfully, in windows using MSVC. According to the output messages of cmake the CUDA is being detected and build too, but when I run the code in visual studio of dnn face detection it's taking almost 6s (716x556 resized bald_guys.jpg) and my nvidia gtx 1080 seems to be unused during the execution time.!
I'm compiling the project like specified in "Compiling on Windows Using Visual Studio 2015 or Newer" section.
Currently I'm not linking any BLAS/LAPACK how could it impact the process? Since I see there is something really wrong from my side.

thanks in advance ...

**Comment by davisking** [comment]
What does cmake say?  Paste the output here.

**Comment by alison-carrera-pegasus** [comment]
Thanks for your precious help Davis, I think I fixed the things now. I was trying to build the app in VS, now i'm using the cmake script provided for building the examples (initially i just built the one that makes the "dlib.lib"), then i could see the correct settings for the commands to compile (i missed the DLIB_USE_CUDA macro for example...). Now i can achieve 60ms in a full hd image. But for sure I'm not using blas, would it affect even more the efeciency of the dnn? Can it really make some diference?

**Comment by davisking** [comment]
If you are using CUDA then you don't need BLAS.
