### ISSUE TITLE
Crash in full_object_detection on iOS with Xcode 9

### ISSUE THREAD

**Issue by gimulnautti** [davisking/dlib#865]
We are using dlib for face landmarks detection on iOS. We use the 68 landmarks model. After upgrading the build environment to use osx High Sierra and Xcode 9, the builds of our application for iOS suddenly started crashing when the full_object_detection object is created by the shape_predictor.

code snippet:
    static dlib::shape_predictor* sp;

    extern "C" void detectLandmarks()
    {
      ....
      dlib::full_object_detection shape = (*sp)(dlib::cv_image<dlib::bgr_pixel>(initial_image), face_rect);

When Assertions are enabled, the following error is thrown:
                
		**************************** FATAL ERROR DETECTED ****************************

		Error detected at line 1314.
		Error detected in file /Users/[path suppressed]/dlib/opencv/../array2d/../geometry/../matrix/matrix.h.
		Error detected in function const T &dlib::matrix<float, 0, 1, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>::operator()(long) const [T = float, num_rows = 0, num_cols = 1, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout].

		Failing expression was 0 <= i && i < size().
			const type matrix::operator(i)
			You must give a valid row/column number
			i:      3725201376
			size(): 136
			this:   0x170ef24c8

		******************************************************************************

		libc++abi.dylib: terminate_handler unexpectedly returned
		(lldb) bt
		dev was compiled with optimization - stepping may behave oddly; variables may not be available.
		* thread #58, stop reason = signal SIGABRT
		    frame #0: 0x00000001844b5348 libsystem_kernel.dylib`__pthread_kill + 8
		    frame #1: 0x00000001845c9354 libsystem_pthread.dylib`pthread_kill$VARIANT$mp + 396
		    frame #2: 0x0000000184424fd8 libsystem_c.dylib`abort + 140
		    frame #3: 0x0000000183e88068 libc++abi.dylib`abort_message + 132
		    frame #4: 0x0000000183ea0558 libc++abi.dylib`std::__terminate(void (*)()) + 28
		    frame #5: 0x0000000183e9fea8 libc++abi.dylib`__cxa_throw + 136
		  * frame #6: 0x0000000102a1803c dev`dlib::matrix<float, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>::operator(this=<unavailable>, i=<unavailable>)(long) const at matrix.h:1308 [opt]
		    frame #7: 0x0000000102a050e4 dev`void dlib::impl::extract_feature_pixel_values<dlib::cv_image<dlib::bgr_pixel>, float>(dlib::cv_image<dlib::bgr_pixel> const&, dlib::rectangle const&, dlib::matrix<float, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> const&, dlib::matrix<float, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::vector<dlib::vector<float, 2l>, std::__1::allocator<dlib::vector<float, 2l> > > const&, std::__1::vector<float, std::__1::allocator<float> >&) [inlined] dlib::impl::location(shape=0x0000000170ef24c8, idx=<unavailable>) at shape_predictor.h:119 [opt]
		    frame #8: 0x0000000102a050d4 dev`void dlib::impl::extract_feature_pixel_values<dlib::cv_image<dlib::bgr_pixel>, float>(img_=<unavailable>, rect=<unavailable>, current_shape=0x0000000170ef24c8, reference_shape=<unavailable>, reference_pixel_anchor_idx=size=1, reference_pixel_deltas=size=1, feature_pixel_values=size=1) at shape_predictor.h:277 [opt]
		    frame #9: 0x00000001029cce74 dev`dlib::full_object_detection dlib::shape_predictor::operator(this=0x0000000116f0da00, img=0x0000000170ef25d8, rect=0x0000000170ef2630)<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&, dlib::rectangle const&) const at shape_predictor.h:351 [opt]
		    frame #10: 0x00000001029cca20 dev`::detectLandmarks() at [inhouse library suppressed].cpp:588 [opt]
		    frame #11: 0x0000000100f13eb0 dev`::[inhouse library suppressed]_detectLandmarks_m1437936662(__this=0x0000000000000000, method=0x0000000000000000) at Bulk_Assembly-CSharp_1.cpp:32744
		    frame #12: 0x0000000100f2b054 dev`::U3CCreateFaceFitU3Ec__AnonStorey2_U3CU3Em__3_m3877446931(__this=0x000000010af8d580, method=0x000000011157adf0) at Bulk_Assembly-CSharp_1.cpp:40280
		    frame #13: 0x000000010133711c dev`::Action_Invoke_m3616226065(__this=0x0000000117c73e00, method=0x0000000000000000) at Bulk_System.Core_0.cpp:6830
		    frame #14: 0x0000000100e49994 dev`::IDispatch_U3CUpdateU3Em__0_m3583299710(__this=0x0000000000000000, ___e0=0x0000000117c73e00, method=0x000000011e169f20) at Bulk_Assembly-CSharp-firstpass_1.cpp:31895
		    frame #15: 0x000000010101d468 dev`::Action_1_Invoke_m2740336873_gshared(__this=0x0000000117b88b60, ___obj0=0x0000000117c73e00, method=0x00000001105ef6c0) at Bulk_Generics_0.cpp:20140
		    frame #16: 0x00000001010982c4 dev`::List_1_ForEach_m3387658631_gshared(__this=0x0000000117d66990, ___action0=0x0000000117b88b60, method=0x00000001105ed7e8) at Bulk_Generics_12.cpp:43376
		    frame #17: 0x0000000100e46b18 dev`::IDispatch_Update_m2475693710(__this=0x0000000117d58b90, method=0x0000000000000000) at Bulk_Assembly-CSharp-firstpass_1.cpp:31885
		    frame #18: 0x0000000100e465d4 dev`::ConcurrentDispatch_Update_m3947768311(__this=0x0000000117d58b90, method=0x000000011b7fbfc0) at Bulk_Assembly-CSharp-firstpass_1.cpp:30448
		    frame #19: 0x0000000101953d70 dev`::ThreadStart_Invoke_m2405277633(__this=0x0000000117d65bd0, method=0x000000011abfbf70) at Bulk_mscorlib_7.cpp:31721
		    frame #20: 0x0000000101c0581c dev`RuntimeInvoker_Void_t3992764623(methodPointer=(dev`::ThreadStart_Invoke_m2405277633(ThreadStart_t568625303 *, const RuntimeMethod *) at Bulk_mscorlib_7.cpp:31706), methodMetadata=0x000000011abfbf70, obj=0x0000000117d65bd0, args=0x0000000170ef2e70)(), MethodInfo const*, void*, void**) at Il2CppInvokerTable.cpp:31126
		    frame #21: 0x00000001027fd864 dev`il2cpp::vm::Runtime::DelegateInvoke(Il2CppDelegate*, void**, Il2CppException**) [inlined] il2cpp::vm::Runtime::Invoke(method=0x000000011abfbf70, exc=0x0000000170ef2e60) at Runtime.cpp:467 [opt]
		    frame #22: 0x00000001027fd844 dev`il2cpp::vm::Runtime::DelegateInvoke(delegate=0x0000000117d65bd0, params=0x0000000170ef2e70, exc=0x0000000170ef2e60) at Runtime.cpp:416 [opt]
		    frame #23: 0x00000001027cbbc4 dev`il2cpp::icalls::mscorlib::System::Threading::ThreadStart(arg=0x000000010af87c30) at Thread.cpp:158 [opt]
		    frame #24: 0x00000001027d4288 dev`il2cpp::os::Thread::RunWrapper(arg=<unavailable>) at Thread.cpp:168 [opt]
		    frame #25: 0x00000001027d895c dev`il2cpp::os::ThreadImpl::ThreadStartWrapper(arg=0x000000011156d0f0) at ThreadImpl.cpp:104 [opt]
		    frame #26: 0x00000001845c832c libsystem_pthread.dylib`_pthread_body + 308
		    frame #27: 0x00000001845c81f8 libsystem_pthread.dylib`_pthread_start + 312
		    frame #28: 0x00000001845c6c38 libsystem_pthread.dylib`thread_start + 4

After the error appeared, we updated to dlib 19.4, and rebuilt the library as follows

    mkdir build && cd build
    cmake -G Xcode ..
    cmake --build . --config Release

with the following options

    c/c++ flags
    -DDLIB_NO_GUI_SUPPORT -DNDEBUG -DDLIB_USE_BLAS -DDLIB_USE_LAPACK -DENABLE_ASSERTS

    linker flags
    -ObjC

We have built the library with both C++11 and C++14, and with both Apple LLVM standard library and Gnu++ standard library but there is no change in behaviour. Also tried to change DLIB_USE_LAPACK and DLIB_USE_BLAS, either/or and neither or both. Toggling optimisations to None also doesn't help.

Any help would be appreciated.

**Comment by davisking** [comment]
You probably have uninitialized variables in your code.  You are also using global variables and raw pointers.  So that kind of error is not at all surprising.

**Comment by gimulnautti** [comment]
In other words, the shape predictor could have been incorrectly deserialised?

**Comment by davisking** [comment]
I have no idea.  Maybe you have a dangling pointer.  Maybe you have a race condition between threads.  I can't tell anything from the code you posted other than the face that you are *using global variables and bare pointers* both of which are very bad C++ practice and likely to lead to bugs.  

I'm not going to debug your program, especially when I can't even see the code.

**Comment by gimulnautti** [comment]
I am not asking you to debug our program. I am aware of bad programming practices there, and I did not write them myself, but am having to debug the issue.. So, we are in the same boat here.

But you've made it clear that you do not intend to help me out with anything regarding dlib here. So I will not trouble you about it. Thanks and have a nice day.
