### ISSUE TITLE
A generic viewer to a dnn network

### ISSUE THREAD

**Issue by daisyron** [davisking/dlib#866]
Hi,

I’m interested in writing a viewer application with which the kernels and the outputs of the different layers (for some input excitation) of general dnn network. I would like to get the network architecture and weights from a file that was generated using the seialize method.
My problem, as far as I understand the library, is that in order to desirialize the network it’s architecture should be known to the viewer in compile time. This prevent writing a generic network viewer.

Is the a solution to this restriction of the (template based) dlib dnn implementation?

Thanks,

Ron.

**Comment by davisking** [comment]
Having a viewer would be cool.

Yeah you need to have the template definition available to load the network.  If you want to make something that doesn't need the template definition then you should save the network to disk using dlib::net_to_xml() and use that file format instead.

**Comment by daisyron** [comment]
Thanks for you fast replay...

Do you have an example how I define a network whose architecture is not known and desrialize it from an xml file?

Ron.

**Comment by davisking** [comment]
No, I don't have an example that reads the XML file.  But you can call net_to_xml() on any network object and it will dump it to an XML. If you look at the XML contents it should be pretty obvious how to read it.

**Comment by daisyron** [comment]
so, if i undersnat you right, I have to parse the xml, extract the network architecture, than define an appropriate template based network type, compile the source code, and than use it to view the specific file. This way I can’t see how to write a general network viewer...

Am I right?

Is there a simpler way?

Thanks,

Ron.

**Comment by davisking** [comment]
No, that's crazy.   The XML file contains all the information there is to know about the entire network.  You don't need anything else.  That's the whole point of the XML file we are talking about.

**Comment by daisyron** [comment]
Dear Davis,

Sorry, but I can't find in the documentation and examples how to do that. 

For the case when I know in compile time the network, I can do for binary serialized network, for example:
`
using net_type = loss_multiclass_log<
                                fc<10,
                                relu<fc<84,
                                relu<fc<120,
                                max_pool<2,2,2,2,relu<con<16,5,5,1,1,
                                max_pool<2,2,2,2,relu<con<6,5,5,1,1,
                                input<matrix<unsigned char>>
                                >>>>>>>>>>>>;

net_type net;
dlib::deserialize(fileName) >> net;
`

What is the equivalent code to build a network from an XML file? 
I don't have the net_type, so how do I define a net at all?

Thanks.

**Comment by daisyron** [comment]
Any comment please?

**Comment by davisking** [comment]
Look at the XML file contents, it contains everything you need.  If you can't write the code to parse an XML file then writing the code to create the kind of display program you are talking about is going to be way too hard.

**Comment by xsacha** [comment]
@daisyron 
I think the idea isn't to build a network from an XML file but to generate the XML file from the net.
Like you showed above, you deserialise in to the net, then you call dlib::net_to_xml.
