### ISSUE TITLE
Distributed DNN training

### ISSUE THREAD

**Issue by c9s** [davisking/dlib#867]
Hi Davis,

Thank you for open sourcing this awesome project. I'm wondering if the distributed DNN training support is in the roadmap? If it's in your plan, what do you want it looks like?

Thanks,

**Comment by davisking** [comment]
Thanks, glad you like dlib :)

No, I'm probably not going to add multi-machine training.  You can already train with multiple GPUs. So for example, you could stuff 8 NVIDIA 1080ti GPUs into one machine and train with them as a group.  Support for training with multiple GPUs in multiple machines requires special hardware to enable fast communication.  It's not the sort of thing you are going to want to do with commodity machines connected with gigabit ethernet if that's what you have in mind.

**Comment by c9s** [comment]
Thanks for your kindly reply. One of my friend mentioned that TensorFlow supports distributed training. And so I am curious about your thoughts.

I also wonder if it's worth to do the dnn training across different machine with gigabit eth.

**Comment by davisking** [comment]
I highly doubt that works well.

**Comment by davisking** [comment]
If you want to train fast buy some NVIDIA 1080ti cards

**Comment by c9s** [comment]
Thank you for sharing the thoughts :)

Thanks again for this awesome project
