### ISSUE TITLE
trouble using dlib/dnn.h

### ISSUE THREAD

**Issue by AEHousman** [davisking/dlib#868]
dlib 19.7 installed. using visual studio 2015. cuda 8.0 installed. visual studio is set up to build cuda 8.0 programs. I've added dlib/all/source.cpp to my project.

I successfully built and ran the 3D point cloud app.

However, this program

    #include <dlib/dnn.h>
    int main()
    {
    	exit(0);
    }

generates the following error messages

	1>------ Build started: Project: dlib-test, Configuration: Debug x64 ------
	1>  baz.cpp
	1>e:\src\dlib-19.7\dlib\dnn\core.h(254): error C2995: 'alwaysbool<unknown-type>::type dlib::impl::backward_requires_forward_output(layer_type &,SUBNET &)': function template has already been defined
	1>  e:\src\dlib-19.7\dlib\dnn\core.h(239): note: see declaration of 'dlib::impl::backward_requires_forward_output'
	1>e:\src\dlib-19.7\dlib\dnn\core.h(290): error C2995: 'alwaysbool2<unknown-type>::type dlib::impl::has_inplace_backward(layer_type &,SUBNET &)': function template has already been defined
	1>  e:\src\dlib-19.7\dlib\dnn\core.h(275): note: see declaration of 'dlib::impl::has_inplace_backward'
	1>e:\src\dlib-19.7\dlib\dnn\core.h(350): error C2995: 'unknown-type dlib::impl::call_layer_backward(layer_type &,const dlib::tensor &,const dlib::tensor &,SUBNET &,dlib::tensor &)': function template has already been defined
	1>  e:\src\dlib-19.7\dlib\dnn\core.h(329): note: see declaration of 'dlib::impl::call_layer_backward'
	1>e:\src\dlib-19.7\dlib\dnn\core.h(410): error C2995: 'unknown-type dlib::impl::call_layer_forward(layer_type &,const SUBNET &,dlib::tensor &)': function template has already been defined
	1>  e:\src\dlib-19.7\dlib\dnn\core.h(378): note: see declaration of 'dlib::impl::call_layer_forward'
	1>e:\src\dlib-19.7\dlib\dnn\core.h(422): error C2995: 'unknown-type dlib::impl::call_layer_forward(layer_type &,const SUBNET &,dlib::resizable_tensor &)': function template has already been defined
	1>  e:\src\dlib-19.7\dlib\dnn\core.h(393): note: see declaration of 'dlib::impl::call_layer_forward'
	========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The dnn example programs don't build either, but let's see if fixing the above also fixes the other issues.

**Comment by AEHousman** [comment]
To make it clear, my include path is effectively "e:\src\dlib-19.7\" . I wasn't expecting the code meta to reformat the error message; sorry about that.

**Comment by davisking** [comment]
You probably have an older version of visual studio 2015.  see http://dlib.net/faq.html#WhycantIusetheDNNmodulewithVisualStudio.

**Comment by AEHousman** [comment]
Indeed I did. Updated to update 3 and things compile now. I didn't think the FAQ would address a compile issue, so didn't check it. I now have read the FAQ fully. Do you have a recommended compiler for Windows 10 that works with all of the machine learning code in dlib?

**Comment by davisking** [comment]
Clang or GCC will work fine.  Really any C++11 compiler.

**Comment by AEHousman** [comment]
OK, thanks. I am used to the VS2015 IDE, so won't change until I actually have to. Closing.

**Comment by davisking** [comment]
You can use clang with visual studio’s IDE.

**Comment by AEHousman** [comment]
clang_c2 installed. After working around the IUnknown error by adding the following to source.cpp
    #if defined(__c2__) &&  __clang_major__ == 3 && __clang_minor__ == 8
    //To avoid compile error
    //C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): error : unknown type name 'IUnknown'
    //          static_cast<IUnknown*>(*pp);    // make sure everyone derives from IUnknown
    struct IUnknown;
    #endif
I now crash in the clang compiler with the following error message
    1>  'union __m128 __cdecl _mm_cvtepi32_ps(union __m128i)': Intrinsic not yet implemented:
    1>    %4 = call <4 x float> @llvm.x86.sse2.cvtdq2ps(<4 x i32> %3)
    1>E:\src\dlib-test\dlib-test\source.cpp : fatal error C1001: An internal error has occurred in the compiler.
    1>  (compiler file 'llvm-bridge.cpp', line 5757)
    1>   To work around this problem, try simplifying or changing the program near the locations listed above.
Since I don't actually need clang at the moment, I'm going to assume the above problem will eventually be fixed.

**Comment by davisking** [comment]
How did you install clang?  I've used the version here
http://prereleases.llvm.org/win-snapshots/LLVM-5.0.0-r306282-win64.exe and
it worked well.

**Comment by davisking** [comment]
See also the discussion here https://github.com/davisking/dlib/pull/772

**Comment by AEHousman** [comment]
I installed clang using the Visual Studio 2015 installer.

I also installed clang using your link above, and using the LLVM-vs2014 platform toolset, I was able to build successfully.

There are a lot of warning messages though. What's your recommendation about them?

**Comment by davisking** [comment]
Don't worry about them.  I honestly haven't looked at them though.  I don't use visual studio very much anymore.  I do have regular unit tests run against visual studio.  But it's not a very good C++ compiler.  One of it's many problems is the absurd warnings it gives out.  I often disable them in the code, but I haven't gone through and dealt with them in a while.  As a few examples, visual studio will give warnings saying that some parts of the standard C++ library are deprecated and that you should use functions that only exist on windows.  That is pernicious bullshit of the highest order.  There are also a lot of warnings about internal imitations of visual studio or even about bug fixes in their compiler.  

If you use a normal version of GCC or clang you shouldn't see any warnings.  But for visual studio you might see some.

**Comment by AEHousman** [comment]
The warning messages were from my using the Visual Studio IDE with the clang 5.0 C++ front end, not the Microsoft C++ compiler.  Here's one of them. (I'm ignoring the ones from source.cpp since I'll only see them once.)

1>------ Build started: Project: dlib-test, Configuration: Debug x64 ------
1>clang-cl.exe : warning : argument unused during compilation: '/ZI' [-Wunused-command-line-argument]
1>clang-cl.exe : warning : argument unused during compilation: '/Gm' [-Wunused-command-line-argument]
1>  In file included from baz.cpp:62:
1>  In file included from ..\..\dlib-19.7\dlib/dnn.h:12:
1>  In file included from ..\..\dlib-19.7\dlib/dnn/tensor.h:8:
1>  In file included from ..\..\dlib-19.7\dlib/image_keypoint/../matrix.h:6:
1>  In file included from ..\..\dlib-19.7\dlib/array2d/../geometry/../matrix/matrix.h:9:
1>  In file included from ..\..\dlib-19.7\dlib/vectorstream/../serialize.h:158:
1>..\..\dlib-19.7\dlib/map/../interfaces/enumerable.h(48,24): warning : function definition with pure-specifier is a Microsoft extension [-Wmicrosoft-pure-definition]
1>          inline virtual ~enumerable(
1>                         ^
1>  ..\..\dlib-19.7\dlib/sequence/sequence_kernel_2.h(61,13):  note: in instantiation of member function 'dlib::enumerable<dlib::lbfgs_search_strategy::data_helper>::~enumerable' requested here
1>              sequence_kernel_2 (
1>              ^
1>  ..\..\dlib-19.7\dlib/matrix/../optimization/optimization_search_strategies.h(157,18):  note: in instantiation of member function 'dlib::sequence_kernel_2<dlib::lbfgs_search_strategy::data_helper, dlib::memory_manager_stateless_kernel_1<char> >::sequence_kernel_2' requested here
1>          explicit lbfgs_search_strategy(unsigned long max_size_) : max_size(max_size_), been_used(false)
1>                   ^
--------------------
There are eight of the above from including dnn.h (all pure function warnings.) The other warning message is

1>  In file included from baz.cpp:62:
1>  In file included from ..\..\dlib-19.7\dlib/dnn.h:12:
1>  In file included from ..\..\dlib-19.7\dlib/dnn/tensor.h:8:
1>  In file included from ..\..\dlib-19.7\dlib/image_keypoint/../matrix.h:6:
1>  In file included from ..\..\dlib-19.7\dlib/array2d/../geometry/../matrix/matrix.h:9:
1>  In file included from ..\..\dlib-19.7\dlib/vectorstream/../serialize.h:162:
1>  In file included from ..\..\dlib-19.7\dlib/dnn/../byte_orderer.h:7:
1>..\..\dlib-19.7\dlib/byte_orderer/byte_orderer_kernel_1.h(139,13): warning : unused typedef 'DAHSL2_139' [-Wunused-local-typedef]
1>              DLIB_ASSERT_HAS_STANDARD_LAYOUT(T);
1>              ^
1>  ..\..\dlib-19.7\dlib/map/../assert.h(191,38):  note: expanded from macro 'DLIB_ASSERT_HAS_STANDARD_LAYOUT'
1>      DLIB_NO_WARN_UNUSED typedef char BOOST_JOIN(DAHSL2_,__LINE__)[sizeof(BOOST_JOIN(DAHSL_,__LINE__))];
1>                                       ^
1>  ..\..\dlib-19.7\dlib/map/../assert.h(24,28):  note: expanded from macro 'BOOST_JOIN'
1>  #define BOOST_JOIN( X, Y ) BOOST_DO_JOIN( X, Y )
1>                             ^
1>  ..\..\dlib-19.7\dlib/map/../assert.h(25,31):  note: expanded from macro 'BOOST_DO_JOIN'
1>  #define BOOST_DO_JOIN( X, Y ) BOOST_DO_JOIN2(X,Y)
1>                                ^
1>  ..\..\dlib-19.7\dlib/map/../assert.h(26,32):  note: expanded from macro 'BOOST_DO_JOIN2'
1>  #define BOOST_DO_JOIN2( X, Y ) X##Y
1>                                 ^
1>  <scratch space>(66,1):  note: expanded from here
1>  DAHSL2_139
1>  ^
1>  9 warnings generated.
1>  dlib-test.vcxproj -> E:\src\dlib-test\x64\Debug\dlib-test.exe
1>  dlib-test.vcxproj -> E:\src\dlib-test\x64\Debug\dlib-test.pdb (Full PDB)
1>  copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart*.dll" "E:\src\dlib-test\x64\Debug\"
1>  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart32_80.dll
1>  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll
1>          2 file(s) copied.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by davisking** [comment]
They seem fine.  Although if you want to figure out how to avoid those warnings and submit a pull request with them that would be cool :)

**Comment by AEHousman** [comment]
Okay, thanks for your help. I'll put fixing the warnings on my to-do list.

**Comment by AEHousman** [comment]
In the Visual Studio IDE, Configuration Properties>C/C++>Command Line, add the following in the Additional Options section to remove nearly all of the warnings:

-Wno-microsoft-pure-definition -Wno-deprecated-declarations -Wno-unused-local-typedef -Wno-exceptions -Wno-unused-command-line-argument

The no-exceptions one might be a little problematical, but I'll leave that to you. I'm aware this is a band-aid, but I'm fine with my local fix to the minor issue.

**Comment by davisking** [comment]
Thanks for reporting back.  I'll see about improving the warnings in this configuration.

**Comment by AEHousman** [comment]
Changing stuff to support clang in VS2015 with no error messages might be a moot issue. See https://stackoverflow.com/questions/38432211/how-do-i-use-other-c-compilers-with-cuda-on-windows ; I can't use clang and compile my own CUDA code, and I don't know how to change the toolset to use for different parts of a project (and don't really want to.) So I'm just going to have to hope I don't run into the limitations of VS2015, or hope Microsoft fixes VS2017. At the moment, I am OK (dnn.h builds with no issues now after updating VS2015 per your comment.) I assume you'll know when VS2017 starts working well again!

**Comment by davisking** [comment]
Yeah, lack of CUDA support in clang is a bummer.  VC2015 is mostly alright.
