### ISSUE TITLE
Detect best face angle in video stream

### ISSUE THREAD

**Issue by manmitya** [davisking/dlib#871]
How to detect best face angle in video stream for face recognition? Is any recipe for it in dlib or OpenCV?

**Comment by davisking** [comment]
No.  I would use the landmarks to try and pick out front looking faces though.

**Comment by manmitya** [comment]
Is any example for this ( preferably on a python)? What is best for it - HOG or CNN detector?
We detect face, we track it, our need one foto with this face to put it in database and recognize it.

**Comment by davisking** [comment]
I don't have any code examples for this.

**Comment by manmitya** [comment]
Ok :) May be some ideas how to get best angle of face based on parameters of 5 or 68 dots landmarks?

**Comment by davisking** [comment]
You could go crazy with something like PNP, but really, just thresholding
the aspect ratio of the box that fits the 5 face points is probably more
than sufficient to identify front looking faces.

**Comment by manmitya** [comment]
:)) yes, and is it difficult to know look human to camera with open eyes or not?

**Comment by manmitya** [comment]
Can dlib to know - open eyes or closed? Look human to camera or not?

**Comment by davisking** [comment]
Yes, but you need to write come code to do this.

**Comment by manmitya** [comment]
Do you tell me more information about?

**Comment by davisking** [comment]
You could run the 68 point model and look at how far apart the eyelids are.  There is a lot of information on the net about this.  However, github issues is not a code writing service, so if you are expecting someone to write it for you that's probably not going to happen.

**Comment by manmitya** [comment]
Oh, yes! :) Thank a lot!
