### ISSUE TITLE
trained model issue

### ISSUE THREAD

**Issue by avisangray** [davisking/dlib#873]
i trained resnet model using dlib_metric_learning_on_images. but when i'm using it for tests and try to detect any of image in johns directory it is unable to detect any person. however when i use trained model on bald_guys.jpg it detects them all as one person. what am i doing wrong while training?i also changed input_rgb_image_sized class of face_recognition to input_rgb_image class.

note:- model is trained on johns faces folder and testing it on same image bald_guys.jpg in faces folder.

i know this need to be posted on somewhere like stackoverflow but i didn't got any reply there. i'll appreciate your help

**Comment by davisking** [comment]
I just replied on stackoverflow.  Anyway, 61 faces is way too few.  You need more training data.
