### ISSUE TITLE
Import Error_ gcc version 5.4.0

### ISSUE THREAD

**Issue by RaviRaaja** [davisking/dlib#877]
Please suggest me which version of gcc should i use , why this error is popping up 
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stan/anaconda2/lib/python2.7/site-packages/dlib-19.7.99-py2.7-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /home/stan/anaconda2/lib/python2.7/site-packages/dlib-19.7.99-py2.7-linux-x86_64.egg/dlib/dlib.so: undefined symbol: _ZTTNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE

**Comment by davisking** [comment]
I don't know.  You can use any gcc.  Maybe your copy of gcc is installed wrong since you have missing symbols from the standard C++ library.  You should google for that linker error to find out how to fix your system.

**Comment by RaviRaaja** [comment]
Thank you so much ! the error is because of GCC , im using anacoda , once i installed libgcc in conda it worked, 
conda install libgcc 
can you suggest any clustering algorithm to effectively cluster similar faces from its 128 descriptors (unlabelled faces)?

**Comment by davisking** [comment]
The face recognition example that comes with dlib does face clustering.  I would do that.
