### ISSUE TITLE
Deserializing Error

### ISSUE THREAD

**Issue by kalravibhor** [davisking/dlib#879]
Hi, 

I am trying to use the newest addition to the dlib face detection module : the 5 point pose landmark detector. However on trying to run the compiled program I am running into the below mentioned error. 

`An error occurred while trying to read the first object from the file pathtofile/shape_predictor_5_face_landmarks.dat.
ERROR: Error deserializing object of type unsigned long
   while deserializing object of type std::string`.

Tried doing a quick google lookup but did not manage to get any satisfactory results. Thanks in advance.

**Comment by davisking** [comment]
Post the exact steps to reproduce the error.

**Comment by kalravibhor** [comment]
Hey Davis,

I am trying to run "dnn_mmod_face_detection_ex.cpp" with modifications. However in retrospect I realise that the convnet used for the 5 pose landmark estimation would be very different from that used for 68 landmarks. However I couldn't find the architecture for the same. Nonetheless below is the code. Do let me know your thoughts on where exactly am I going wrong ? Thanks.

`#include <iostream>
#include <dlib/dnn.h>
#include <dlib/data_io.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>


using namespace std;
using namespace dlib;

// ----------------------------------------------------------------------------------------

template <long num_filters, typename SUBNET> using con5d = con<num_filters,5,5,2,2,SUBNET>;
template <long num_filters, typename SUBNET> using con5  = con<num_filters,5,5,1,1,SUBNET>;

template <typename SUBNET> using downsampler  = relu<affine<con5d<32, relu<affine<con5d<32, relu<affine<con5d<16,SUBNET>>>>>>>>>;
template <typename SUBNET> using rcon5  = relu<affine<con5<45,SUBNET>>>;

using net_type = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>;

// ----------------------------------------------------------------------------------------


int main(int argc, char** argv) try
{
    if (argc == 1)
    {
        cout << "Call this program like this:" << endl;
        cout << "./dnn_mmod_face_detection_ex mmod_human_face_detector.dat faces/*.jpg" << endl;
        cout << "\nYou can get the mmod_human_face_detector.dat file from:\n";
        cout << "http://dlib.net/files/mmod_human_face_detector.dat.bz2" << endl;
        return 0;
    }


    net_type net;
    deserialize(argv[1]) >> net;  

    image_window win;
    for (int i = 2; i < argc; ++i)
    {
        matrix<rgb_pixel> img;
        load_image(img, argv[i]);

        // Upsampling the image will allow us to detect smaller faces but will cause the
        // program to use more RAM and run longer.
        while(img.size() < 900*900)
            pyramid_up(img);

        // Note that you can process a bunch of images in a std::vector at once and it runs
        // much faster, since this will form mini-batches of images and therefore get
        // better parallelism out of your GPU hardware.  However, all the images must be
        // the same size.  To avoid this requirement on images being the same size we
        // process them individually in this example.
        auto dets = net(img);
        win.clear_overlay();
        win.set_image(img);
        for (auto&& d : dets)
            win.add_overlay(d);

        cout << "Hit enter to process the next image." << endl;
        cin.get();
    }
}
catch(std::exception& e)
{
    cout << e.what() << endl;
}`

**Comment by kalravibhor** [comment]
Hey Davis, apologies for bothering you. I got it to work. Had made a silly error. Thanks.
