### ISSUE TITLE
Compiling issue for face_detector

### ISSUE THREAD

**Issue by shadabnaseem** [davisking/dlib#88]
I am new to try dlib library. I have gone through the compiling instruction but still the problem persists.
I am using command line for compiling and execution.
I used the following commands and gave me errors.
`g++ -O3 -I.. ../dlib/all/source.cpp -lpthread -lX11 face_detection_ex.cpp -DDLIB_JPEG_SUPPORT`

![screenshot from 2016-03-21 14 39 131](https://cloud.githubusercontent.com/assets/17870668/13914284/5c727cec-ef73-11e5-8b13-30c3eaae0481.png)

Please tell me whats wrong.
Thank You

**Comment by davisking** [comment]
You didn't link to libjpeg.  The instructions here
http://dlib.net/compile.html tell you what to type to make g++ link to
libjpeg.

**Comment by shadabnaseem** [comment]
thnx man ..
