### ISSUE TITLE
Learning to Rank with more than two ranks

### ISSUE THREAD

**Issue by usptact** [davisking/dlib#884]
The python example on how to train and use SVM ranker is excellent:
https://github.com/davisking/dlib/blob/master/python_examples/svm_rank.py

My question is: Is it possible to learn and use a ranker that has more than two ranks?

The example script shows that dataset gets added relevant and nonrelevant vectors:
```
data.relevant.append(dlib.vector([1, 0]))
data.nonrelevant.append(dlib.vector([0, 1]))
```

In my application, I have three ranks:

1. highly relevant
2. somewhat relevant
3. non-relevant

My feature vectors are sparse.

**Comment by davisking** [comment]
The ranking tool in dlib is just binary, relevant/non-relevant.

**Comment by usptact** [comment]
Thanks @davisking

**Comment by davisking** [comment]
No problem.  I should mention that the code for doing learning to rank is
relatively straightforward.  All the difficult bits are in the underlying
cutting plane solver.  The part that defines the learning to rank class is
itself just a simple thing and not very hard to modify.  So if you are
familiar with C++ you should be able to create custom ranking losses
without too much trouble.
