### ISSUE TITLE
libcudnn.so: error adding symbols: File in wrong format dlib

### ISSUE THREAD

**Issue by smajida** [davisking/dlib#885]
I just wanted to install Dlib on my Jetson TX1 and got the following error:

`[ 99%] Linking CXX shared library libdlib.so
/usr/local/cuda-8.0/lib64/libcudnn.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
dlib/CMakeFiles/dlib_shared.dir/build.make:1663: recipe for target 'dlib/libdlib.so.19.7.99' failed
make[2]: *** [dlib/libdlib.so.19.7.99] Error 1
CMakeFiles/Makefile2:124: recipe for target 'dlib/CMakeFiles/dlib_shared.dir/all' failed
make[1]: *** [dlib/CMakeFiles/dlib_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by davisking** [comment]
I don't know, but I don't think this is a dlib error.  You probably have the wrong version of cudnn for a jetson TX1.  Make sure you download a version of cudnn that is compatible with the jetson.

**Comment by mrzhaorui** [comment]
do you solve the issue? I have the same issue on tx2

**Comment by ParmpalGill** [comment]
One Way to install it without cuda is use
cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1
