### ISSUE TITLE
Bayesnet Convert to DLL

### ISSUE THREAD

**Issue by King-Of-Knights** [davisking/dlib#892]
Hi there, Thanks for your great job, it greatly helps my research in Bayesnet. However, I need to add Bayesnet to my project, so I wish to compile a  DLL containing all function that needed, there are hundred function here and Template T is an obstacle to do so. Any suggestion to make it a little easier? Do I still need to include all the header flie if I use the DLL?

**Comment by davisking** [comment]
There are instructions for compiling dlib here: http://dlib.net/compile.html.  I strongly recommend you to use cmake if you are not familiar with C++'s compile and link mechanisms. 

But in any case, there isn't anything special about dlib's C++ code.  You compile it into an application just like any other C++ code.
