### ISSUE TITLE
Dlib Issues on mac os ,Symbol not found: _PyClass_Type

### ISSUE THREAD

**Issue by adhikaribishwo** [davisking/dlib#893]
Hello, I get the following error: 
>>> import cv2
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bishwoadhikari/anaconda/lib/python3.6/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/Users/bishwoadhikari/anaconda/lib/python3.6/site-packages/dlib/dlib.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python-mt.dylib

I have spent whole night to install : $ brew install --with-python3 graph-tool
==> Installing graph-tool from homebrew/science
==> Installing dependencies for homebrew/science/graph-tool: gmp, mpfr, libmpc, isl, gcc, boost-python, libsigc++, freetype, fontconfig, pixman, gettext, libffi, pcre, glib, cairo, cairomm, cgal, google-sparsehash, gobject-introspection, gdk-pixbuf, atk, libepoxy, graphite2, icu4c, harfbuzz, pango, hicolor-icon-theme, gsettings-desktop-schemas, gtk+3, scipy, matplotlib, py2cairo, py3cairo, libcroco, librsvg, gnome-icon-theme, pygobject3
==> Installing homebrew/science/graph-tool dependency: gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/90/90715336080bd2deb92bd74361f50d91fe288d18e4c18a70a8253add6aa13200?__gda__=exp=1508368275~hmac=1444441b48b4
######################################################################## 100.0%
==> Pouring gmp-6.1.2_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.1.2_1: 18 files, 3.1MB
==> Installing homebrew/science/graph-tool dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-3.1.6.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a8/a8f99b5754688942fdb644a6c00f37d3c4311bcd4477f58b6dc356b0f32ee29d?__gda__=exp=1508368276~hmac=7765f28bdc9c
######################################################################## 100.0%
==> Pouring mpfr-3.1.6.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.6: 26 files, 3.6MB
==> Installing homebrew/science/graph-tool dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmpc-1.0.3_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3_1: 12 files, 345.0KB
==> Installing homebrew/science/graph-tool dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.18.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/1c/1c2765a5766f8bc022dc49d77d7d32a9c3e92e82452bc63ab534f3c1f18a913c?__gda__=exp=1508368279~hmac=383b57f35412
######################################################################## 100.0%
==> Pouring isl-0.18.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.18: 80 files, 3.8MB
==> Installing homebrew/science/graph-tool dependency: gcc
Warning: Building gcc from source:
  The bottle needs the Xcode CLT to be installed.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e9e0ee09389a54cc4c8fe1c24ebca3cd765ed0ba/gcc/6.1.0-jit.patch
######################################################################## 100.0%
==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> ../configure --build=x86_64-apple-darwin16.7.0 --prefix=/usr/local/Cellar/gcc/7.2.0 --libdir=/usr/local/Cellar/gcc/7.2.0/lib/gcc/7 --enable-languages=c,
==> make

   
==> make install
🍺  /usr/local/Cellar/gcc/7.2.0: 1,487 files, 285.0MB, built in 337 minutes 57 seconds
==> Installing homebrew/science/graph-tool dependency: boost-python
==> Downloading https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2
==> Downloading from https://akamai.bintray.com/98/9807a5d16566c57fd74fb522764e0b134a8bbe6b6e8967b83afefd30dcd3be81?__gda__=exp=1508388558~hmac=3ddc9bb1a437
######################################################################## 100.0%
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.65.1 --libdir=/usr/local/Cellar/boost-python/1.65.1/lib --with-libraries=python --with-python=p
==> ./b2 --build-dir=build-python --stagedir=stage-python python=2.7 --prefix=/usr/local/Cellar/boost-python/1.65.1 --libdir=/usr/local/Cellar/boost-python/

==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.65.1 --libdir=/usr/local/Cellar/boost-python/1.65.1/lib --with-libraries=python --with-python=p
==> ./b2 --build-dir=build-python3 --stagedir=stage-python3 python=3.6 --prefix=/usr/local/Cellar/boost-python/1.65.1 --libdir=/usr/local/Cellar/boost-pytho
🍺  /usr/local/Cellar/boost-python/1.65.1: 465 files, 29.5MB, built in 42 minutes 4 seconds
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> Installing homebrew/science/graph-tool dependency: libsigc++
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> Downloading https://homebrew.bintray.com/bottles/libsigc++-2.10.0.sierra.bottle.tar.gz
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> Downloading from https://akamai.bintray.com/58/58af260cf09d48886e9e6c8d85d81979ebdaba4abcfa0bbc4a3a9ab3f78dd929?__gda__=exp=1508391082~hmac=8e4a60129959
######################################################################## 100.0%
Error: No such file or directory - getcwd
Warning: Bottle installation failed: building from source.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> Downloading https://download.gnome.org/sources/libsigc++/2.10/libsigc++-2.10.0.tar.xz
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> Downloading from https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnome.org/sources/libsigc++/2.10/libsigc++-2.10.0.tar.xz
######################################################################## 100.0%
Error: No such file or directory - getcwd

**Comment by davisking** [comment]
See this thread: https://github.com/davisking/dlib/issues/889
