### ISSUE TITLE
cudaMallocHost() is very slow

### ISSUE THREAD

**Issue by azat-d** [davisking/dlib#895]
Hi, Davis!
I made my own face detector using dlib dnn. I noticed that the performance of the detector falls dramatically if you feed images of different sizes. Moreover, in this case, it is not possible to efficiently parallelize the calculations on multiple gpus. As a result of profiling it became clear that the reason for the slowdown lies in the frequent calls of cudaMallocHost() function. I solved this problem by changing the method resizable_tensor::set_size(...) as follows:

```
diff --git a/dlib/dnn/tensor.h b/dlib/dnn/tensor.h
index 80d51ef..bcbb700 100644
--- a/dlib/dnn/tensor.h
+++ b/dlib/dnn/tensor.h
@@ -385,7 +385,8 @@ namespace dlib
             m_nr = nr_;
             m_nc = nc_;
             m_size = n_*k_*nr_*nc_;
-            data_instance.set_size(m_size);
+            if (data_instance.size() < m_size)
+                data_instance.set_size(m_size);
 #ifdef DLIB_USE_CUDA
             cudnn_descriptor.set_size(m_n,m_k,m_nr,m_nc);
 #endif
```

Is it the best way to solve this problem?

**Comment by davisking** [comment]
Yeah, that's fine and should work.  I've considered adding this but it bothers me a little.  The other option is to pad your images so they are the same sizes.  That's obviously less convenient, but makes it more obvious what's happening.  I might add this kind of change to dlib.  Although probably would allow for setting the tensor size to 0 to cause a full deallocation.

**Comment by azat-d** [comment]
I was thinking about padding, but in the case of very different image sizes, this would lead to significant computation overhead. I think that resizing to a smaller size without reallocation is normal behavior (std::vector behaves like this as you know). I think it is better to rewrite resizable_tensor::clear() so that it cause a full dealocation.

**Comment by davisking** [comment]
Yeah. I know.  Ok, I've come around to this.  If you want you can submit a PR with the change :)

**Comment by davisking** [comment]
I just pushed a change that does this to github.   Thanks for the good idea :)
