### ISSUE TITLE
Serialization Error

### ISSUE THREAD

**Issue by kalravibhor** [davisking/dlib#902]
Hi, 

I tried creating a function that takes an image as the input and spits out the names of the faces recognized. For that purpose I defined my net and landmark predictor in accordance with the below mentioned code.

`shape_predictor sp;`
`anet_type net;`
`deserialize("../../Others/shape_predictor_5_face_landmarks.dat") >> sp;`
`deserialize("../../Others/dlib_face_recognition_resnet_model_v1.dat") >> net;`

I am able to build the program successfully but run into the below mentioned runtime error.

`libc++abi.dylib: terminating with uncaught exception of type dlib::serialization_error: Unable to open ~/Desktop/Face_Recognition/Others/shape_predictor_5_face_landmarks.dat for reading.
Abort trap: 6`

What is perplexing is that it used to work fine before this and I tried downloading the file again in addition to modifying the read and write privileges to 777. Even on googling I found no respite, waiting to hear from Davis and other experts.

Vibhor

**Comment by avisangray** [comment]
Could you post the full code?

**Comment by paulyzheng1** [comment]
hi @kalravibhor ,
Does this problem fixed? Could you share it? Thanks a lot! Today, I  run into this same problem with dlib 19.14.
code as belows:
void FaceRecongination::loadFaceDescriptorData(){

    FileUtil fileUtil;
    if(fileUtil.isExist("/storage/emulated/0/FaceData/shape.dat")) {
        deserialize("/storage/emulated/0/FaceData/shape.dat") >> sp;
        deserialize("/storage/emulated/0/FaceData/model.dat") >> net;
    }
    ...
}

**Comment by kalravibhor** [comment]
@paulyzheng1 , unfortunately no. I didn't find the solution to this. Sorry.
