### ISSUE TITLE
Iterate over DNN layers

### ISSUE THREAD

**Issue by daisyron** [davisking/dlib#904]
Hi,

I would like to go over a DNN and get layers parameters to visualize. 

I've seen the `visit_layers` method that needs a visitor class. I tried the simple visitor class:
`template <typename net_type>`
`class PrintNetVistor {`
`public:`
`     void operator()(size_t idx, net_type t) {`
`           std::cout << "Layer " << idx << " Details:\n" << t.layer_details() << "\n";`
`      }`
`};`

and called the `visit_layers` as:
` PrintNetVistor<theInnerNet> printVisitor;`
`dlib::visit_layers(net.subnet(),printVisitor);`

This code failed to compile.... giving many errors like this:

`/usr/local/include/dlib/dnn/core.h:669:45: error: no matching function for call to ‘dlib::relu_::relu_(const layer_details_type&)’`
`    cached_output(item.cached_output)`

What is wrong with what I did?

Do you have a working example of using this visiting mechanism?

Best Regards,

Ron.

**Comment by grochefort** [comment]
Hi,

This is not the class PrintNetVisitor which needs a template parameter but
the operator() method. Doing so, you can choose what to do with specific
layer using specialized template parameters.

As you wrote it, you can only recurse on one layer type (probably the first
one).

Here are some examples:
*class PrintNetVisitor*
*{*
*public:*
 * template <typename any_net>*
*  void operator()(size_t idx, any_net & net)*
*  {*
*  }*

*  template <typename T, typename U, typename E>*
*  void operator()(size_t , add_layer<T,U,E>& l)*
*  {*
*    std::cout << l.layer_details() << std:endl;*
*  }*
*};*
*Best,*
Gilles.

**Comment by davisking** [comment]
Yes, @grochefort is right.  You also might want to use `visit_layer_parameters()` if you only want the parameters.
