### ISSUE TITLE
No face

### ISSUE THREAD

**Issue by amitguptagwl** [davisking/dlib#905]
I tested the pre trained model i.e. **shape_predictor_68_face_landmarks.dat** against ibug_300W_large_face_landmark_dataset/**ibug/image_007.jpg** using python_examples/face_landmark_detection.py and it reported no face. I believe it is because of face angle. Do I need to pass some parameters? Am I missing something?

**Comment by davisking** [comment]
You need to pass it a box around the face.  If the HOG face detector isn't finding the face use the CNN face detector in dlib instead.

**Comment by amitguptagwl** [comment]
Thanks. This time I tried `python_examples/cnn_face_detector.py mmod_human_face_detector.dat ../ibug_300W_large_face_landmark_dataset/ibug/image_007.jpg`. And luckily it detected the face. But since it took a lot of time in processing (even mentioned in comment in the file), it can be used only on server side and not on videos. 

Is it possible to  train the model to detect such faces?

**Comment by davisking** [comment]
Many things are possible.  You could train a HOG detector with more HOG filters to find a wider set of faces.

**Comment by amitguptagwl** [comment]
sorry to say that "HOW?" I mean I have no knowledge of image processing, matlab etc. And My laptop has core i7 processor with 16GB RAM.

Last time I run `train_shape_predictor.py`  with default settings with `ibug_300W_large_face_landmark_dataset` and it took 4 hrs to generate faulty model of just 6.5 mb (timing is fine, I can run it for whole night). But rerun with different settings is painful.

I would appreciate your guidance. Or should I take some training before asking such stupid question :-| ?

**Comment by amitguptagwl** [comment]
If I'm correct, I should use `imgtool` to label images then `fhog_object_detector_ex.cpp` to train HOG detector?

**Comment by davisking** [comment]
Yes

**Comment by amitguptagwl** [comment]
I have created a web based tool which can help for labeling and marking for landmark points manually. Some work is still pending. https://naturalintelligence.github.io/imglab/index.html

It can be helpful to prepare dataset for detector and predictor both.

**Comment by davisking** [comment]
That doesn't seem easier to use than dlib's imglab.  Did you try using
imglab?

**Comment by amitguptagwl** [comment]
dlib's imglab tool is much helpful and anyhow better. I just wanted to create a web version. So I can use other available web API's as well to reduce my work. 

The only difficulty I faced with dlib's imglab is to create parts. As per the instruction, I have selected the rectangle and right click. But no menu appeared.

**Comment by davisking** [comment]
You have to use the --part option to fill out the right click menu.  This is explained in the about dialog in the GUI.  But really, you should prepopulate the part locations automatically and then just use imglab to drag them to the correct locations.  That's way faster than clicking and adding parts.

**Comment by amitguptagwl** [comment]
I have done rest necessary changes in imglab (web version) to make it more usable, talk to 3rd party libraries, and export data in dlib required format.
