### ISSUE TITLE
Division by zero in random_cropper::make_random_cropping_rect

### ISSUE THREAD

**Issue by APTX** [davisking/dlib#907]
I get an unhandled exception:
> Unhandled exception at 0x00007FF7BADDBBFF in program.exe: 0xC0000094: Integer division by zero. occurred

This occurs on the first line of:
`            point offset(rnd.get_random_32bit_number()%(img.nc()-rect.width()),
                rnd.get_random_32bit_number()%(img.nr()-rect.height()));`

Dlib is built with VS2017 with CUDA in RelWithDebInfo.

Available runtime values are:
> dims	{rows=300 cols=300 }
img	{data={...} nr_=93 nc_=125 ...} }
maxs	0.31000000000000000

The scale is not available but some simple math suggests it is equal to maxs, making the rect and the img equal in width (or height).

Is this an unhandled edge case in random_croper? Could this mean one of the images in the data set is tagged wrong in some way?

On a side note: that way of generating a random number from a range does not give a uniform distribution (unless the divisor happens to divide the entire range without a reminder.)

Backtrace (copied from VS, it looks terrible on github):
> [Inline Frame] program.exe!dlib::random_cropper::make_random_cropping_rect(const dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> &) Line 282	C++	Symbols loaded.
program.exe!dlib::random_cropper::make_crop_plan<dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> >(const dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> & img, const std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> > & rects, dlib::chip_details & crop_plan, bool & should_flip_crop) Line 238	C++	Symbols loaded.
program.exe!dlib::random_cropper::operator()<dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout>,dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> >(const dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> & img, const std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> > & rects, dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> & crop, std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> > & crop_rects) Line 175	C++	Symbols loaded.
program.exe!dlib::random_cropper::operator()<std::vector<dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout>,std::allocator<dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> > >,dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> >(const std::vector<dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout>,std::allocator<dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> > > & images, const std::vector<std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> >,std::allocator<std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> > > > & rects, dlib::matrix<dlib::rgb_pixel,0,0,dlib::memory_manager_stateless_kernel_1<char>,dlib::row_major_layout> & crop, std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> > & crop_rects) Line 157	C++	Symbols loaded.
[Inline Frame] program.exe!dlib::random_cropper::append::__l2::<lambda>(long) Line 135	C++	Symbols loaded.
program.exe!dlib::impl::helper_parallel_for_funct<void <lambda>(long) >::run(long i) Line 54	C++	Symbols loaded.
program.exe!dlib::impl::helper_parallel_for<dlib::impl::helper_parallel_for_funct<void <lambda>(long) > >::process_block(long begin, long end) Line 37	C++	Symbols loaded.
[Inline Frame] program.exe!dlib::member_function_pointer<long,long,void,void>::operator()(long) Line 360	C++	Symbols loaded.
program.exe!dlib::thread_pool_implementation::thread() Line 206	C++	Symbols loaded.
[Inline Frame] program.exe!dlib::thread_pool_implementation::{ctor}::__l4::<lambda>() Line 26	C++	Symbols loaded.
[Inline Frame] program.exe!std::_Invoker_functor::_Call(dlib::thread_pool_implementation::{ctor}::__l4::void <lambda>(void) &&) Line 1790	C++	Symbols loaded.
[Inline Frame] program.exe!std::invoke(dlib::thread_pool_implementation::{ctor}::__l4::void <lambda>(void) &&) Line 1790	C++	Symbols loaded.
[Inline Frame] program.exe!std::_LaunchPad<std::unique_ptr<std::tuple<void <lambda>(void) >,std::default_delete<std::tuple<void <lambda>(void) > > > >::_Execute(std::tuple<void <lambda>(void) > &) Line 240	C++	Symbols loaded.
[Inline Frame] program.exe!std::_LaunchPad<std::unique_ptr<std::tuple<void <lambda>(void) >,std::default_delete<std::tuple<void <lambda>(void) > > > >::_Run(std::_LaunchPad<std::unique_ptr<std::tuple<void <lambda>(void) >,std::default_delete<std::tuple<void <lambda>(void) > > > > *) Line 247	C++	Symbols loaded.
program.exe!std::_LaunchPad<std::unique_ptr<std::tuple<void <lambda>(void) >,std::default_delete<std::tuple<void <lambda>(void) > > > >::_Go() Line 232	C++	Symbols loaded.
program.exe!std::_Pad::_Call_func(void * _Data) Line 211	C++	Symbols loaded.
[External Code]		Annotated Frame

**Comment by davisking** [comment]
This is fixed in the newest code on github.

**Comment by APTX** [comment]
I see the [fix](https://github.com/davisking/dlib/commit/cabad6d5fba85ea8095e2942868535903aaffd95). I guess I should switch to master. I am currently using the latest (19.7) version.

**Comment by davisking** [comment]
Yep, definitely use master.

And thanks for reporting the bug, even it was already fixed :)
