### ISSUE TITLE
tbb accelerate，python interface,undefined symbol: _ZTIN3tbb4taskE

### ISSUE THREAD

**Issue by jesszgc** [davisking/dlib#911]
hi, i am using dlib to run my face research. And i am try to accelerate the face detection by using TBB。As the most code is written in the cpp head files ,so it is **ok to compile the c++ projects** using dlib with adding TBB includes and  links. ****
However ,when i want to **compile the python interface, it goes wrong**. I am not clear of how to add the TBB settings to the cmake files. I add two lines to the tools/python/CMakesLists.txt before the set(python_srcs like this:
       include_directories(/home/jess/soft/tbb-2018_U1/include)
       link_directories(/home/jess/soft/tbb-2018_U1/build/linux_intel64_gcc_cc4.8_libc2.19_kernel4.2.0_release)
**the "python setup.py install" goes OK**
but i got the "linux-x86_64.egg/dlib/dlib.so: **undefined symbol: _ZTIN3tbb4taskE"** error while import dlib in python.

**Comment by davisking** [comment]
You need to add TBB to the `target_link_libraries`.  So you would need to edit the cmake code in `dlib/cmake_utils/add_python_module` since that's where `target_link_libraries` is called.

**Comment by jesszgc** [comment]
@davisking thanks a lot! it works. for the development of dlib, i have 2 suggestions,1 add tbb or openmp to parallel the pyramid work; 2 make the pyramid levels settable for searching if we have fixed sizes of faces from the same camera.
