### ISSUE TITLE
can you give an example for adding new metric learning layers?

### ISSUE THREAD

**Issue by yanchao12122** [davisking/dlib#912]
There is a new metric learning about DNN, in CVPR2017, 
'https://github.com/wy1iu/sphereface'

I am going to add a layer of sphereface model to train my own face recogintion,
but there are too many errors.
can you add the sphere layer and give an example for training.

thanks thanks thanks!!!

**Comment by xsacha** [comment]
Just a note: Sphereface seems to get same percentage in LFW as dlib's face recognition. That is, 99.3%.

**Comment by davisking** [comment]
It's also a kinda similar loss.  The metric loss in dlib optimizes getting each identity packed within a sphere and everyone else outside that person's sphere.

**Comment by yanchao12122** [comment]
but in my own dataset, about 180 persons (20 pictures for each person)
the accuracy of sphereface is 42%, 
and the dlib's face is 26%
So I want to migrant the sphereface to the dlib.
