### ISSUE TITLE
Face detection: image preprocessing and different ROI

### ISSUE THREAD

**Issue by lezan** [davisking/dlib#914]
Hello,
I am playing with DLIB and face detection. After some try I saw a different ROI return by detector.
If load the image with OpenCV (it is a tiff image) 
`image = cv::imread(imagePath[imageId], CV_LOAD_IMAGE_COLOR);`
then apply a clahe in this way
```
double clipLimit = 4.0f;
Size tileGridSize(8, 8);
Ptr<CLAHE> clahe = cv::createCLAHE(2.0, tileGridSize);
clahe->apply(gray, output);
```
and search for a face, detector returns image on the left.
If I load the image in the same way, but without apply clahe (or equalizeHist), detector returns ROI on the right side.
![immagine](https://user-images.githubusercontent.com/1663016/32126106-46695636-bb6f-11e7-89ae-8b5959459e86.jpg)
Am I missing something? My preprocessing is not the right thing to do? This is not the only case (in this case KA.FE4.48.tiff), also some other image from JAFFE dataset show the same result.
Thanks.

**Comment by davisking** [comment]
Yes, if you change the inputs you might get different outputs.  This is expected.

**Comment by lezan** [comment]
Looking to two ROIs I think would be better the right one. Do you agree with me? So in this case would be better if I do not not preprocessing, I think.
By the way, thanks for you answer.

**Comment by davisking** [comment]
Yes, it's probably better if you don't modify the images.

**Comment by lezan** [comment]
Sorry if I take advantage of your time, but do you think that also convert to grayscale is not a good choice with your detector? Or it just a stupid question, because we can not take as generale case.

**Comment by davisking** [comment]
It's fine.  The detector doesn't really do anything with the color information anyway.
