### ISSUE TITLE
two days for compiling the dlib for python2.5

### ISSUE THREAD

**Issue by Fankbai** [davisking/dlib#917]
HI, @davisking ,I try to compile dlib for python 2.5  version, that has been token two days. I did that many times. Once compiling "face_recognition.cpp", it seems stopping there:
![2017-11-03_212332](https://user-images.githubusercontent.com/10338671/32375898-2880d0e6-c09b-11e7-9694-55d1d9a70584.jpg)

i just use this:
### python setup.py install --yes USE_AVX_INSTRUCTIONS ###

is something wrong or that really need a long time to work?

**Comment by davisking** [comment]
Visual Studio 2017 is broken and goes into an infinite loop when it encounters certain C++11 constructs.  Use Visual Studio 2015 since it has better C++11 support.
