### ISSUE TITLE
Android Face Recognition NEON arm-v7a, arm64-v8a

### ISSUE THREAD

**Issue by axmadjon** [davisking/dlib#918]
NEON can i get the best result on the arm-v7a, arm64-v8a android processor 
this time of skill only for face recognition is 3-5 seconds
please, help. how can i improve and reduce time

**Comment by xsacha** [comment]
Run the Android Profiler to see what part of the face recognition process takes up most that time.

For me, dlib process takes only 300ms on Android and the actual comparison is almost instant.
Slowest phone I have tested is almost 2000ms.

Your only solution to this is to use a faster BLAS library.

**Comment by axmadjon** [comment]
when converting faces into 128D vector
std::vector<matrix<float,0,1>> face_descriptors = net(faces);

2-3 seconds on huawei p10
"SoC HiSilicon Kirin 960, 8 cores: 4 @ 2.4 GHz (ARM Cortex-A73) + 4 @ 1.8 GHz (ARM Cortex-A53)"

6-7 seconds on GeneralMobile Android One
"Qualcomm Snapdragon 410 8916 Frequency: 1.20 GHz Number of cores: 4 GPU: Adreno 306"

**Comment by xsacha** [comment]
For comparison I get 300ms on a Huawei P9 (HiSilicon 955, virtually identical to yours).

I am using OpenBLAS.

I have faces resized to 96x96 before generating models.

**Comment by axmadjon** [comment]
xsacha thank you very much

**Comment by weank1984** [comment]
Hi, @xsacha 
After resizing the image to 96x96, I found that only the face detection time is much shorter, but the time for calculating the feature points is almost unchanged. And by testing different size images, I found that the image size seems to have almost no effect on the calculated features. Is this a normal situation?
In addition, I would like to ask how to include OpenBLAS on Android ?

**Comment by rambabu125** [comment]
i am using https://github.com/axmadjon/ComputerVision/blob/eb6af669205ac594814d77b5300951d29a86419a/FaceTrack/lib-dlib/src/main/cpp/dlib-face-landmarks-detector-jni.cpp#L244

once check what is the problem .,
now i am getting normal phones 6-7 sec

**Comment by teleger** [comment]
I would like to ask you how I can use openblas on android studio. I have now cross-compiled it.

**Comment by teleger** [comment]
Hi， @weank1984   

Do you know how to use the openBlas library on android studio? Just add an item on cmakelists.txt, -DDLIB_USE_BLAS=1 ? Doesn't seem to work? There is no good solution. I don't know how to add it right now, let's say I have the dlib code and I have the openblas library that's cross-compiled, okay?
