### ISSUE TITLE
test_dnn failing when CUDA enabled.

### ISSUE THREAD

**Issue by OtacilioNeto** [davisking/dlib#925]
After build dlib and tests with cuda enabled, I'm getting this error when running ./dtest --runall

ota@rigel:~/src/Dlib/dlib-19.7/dlib/build_tests$ ./dtest --runall
Running test_dnn |                                                             

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEST FAILED: test_dnn !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Failure message from test: 

Error occurred at line 2159.
Error occurred in file /home/ota/src/Dlib/dlib-19.7/dlib/test/dnn.cpp.
Failing expression was rs.mean() < 0.1.

                                                                               

Testing Finished
Total number of individual testing statements executed: 470359852
Number of failed tests: 1
Number of passed tests: 133

ota@rigel:~/src/Dlib/dlib-19.7/dlib/build_tests$

Ubuntu 16.04. CUDA packages installed (using CUDA 8):

ii  cuda                                                     9.0.176-1                                    amd64        CUDA meta-package
ii  cuda-8-0                                                 8.0.61-1                                     amd64        CUDA 8.0 meta-package
ii  cuda-9-0                                                 9.0.176-1                                    amd64        CUDA 9.0 meta-package
ii  cuda-command-line-tools-8-0                              8.0.61-1                                     amd64        CUDA command-line tools
ii  cuda-command-line-tools-9-0                              9.0.176-1                                    amd64        CUDA command-line tools
ii  cuda-core-8-0                                            8.0.61-1                                     amd64        CUDA core tools
ii  cuda-core-9-0                                            9.0.176-1                                    amd64        CUDA core tools
ii  cuda-cublas-8-0                                          8.0.61.2-1                                   amd64        CUBLAS native runtime libraries
ii  cuda-cublas-9-0                                          9.0.176-1                                    amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-8-0                                      8.0.61.2-1                                   amd64        CUBLAS native dev links, headers
ii  cuda-cublas-dev-9-0                                      9.0.176-1                                    amd64        CUBLAS native dev links, headers
ii  cuda-cudart-8-0                                          8.0.61-1                                     amd64        CUDA Runtime native Libraries
ii  cuda-cudart-9-0                                          9.0.176-1                                    amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-8-0                                      8.0.61-1                                     amd64        CUDA Runtime native dev links, headers
ii  cuda-cudart-dev-9-0                                      9.0.176-1                                    amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-8-0                                           8.0.61-1                                     amd64        CUFFT native runtime libraries
ii  cuda-cufft-9-0                                           9.0.176-1                                    amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-8-0                                       8.0.61-1                                     amd64        CUFFT native dev links, headers
ii  cuda-cufft-dev-9-0                                       9.0.176-1                                    amd64        CUFFT native dev links, headers
ii  cuda-curand-8-0                                          8.0.61-1                                     amd64        CURAND native runtime libraries
ii  cuda-curand-9-0                                          9.0.176-1                                    amd64        CURAND native runtime libraries
ii  cuda-curand-dev-8-0                                      8.0.61-1                                     amd64        CURAND native dev links, headers
ii  cuda-curand-dev-9-0                                      9.0.176-1                                    amd64        CURAND native dev links, headers
ii  cuda-cusolver-8-0                                        8.0.61-1                                     amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-9-0                                        9.0.176-1                                    amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-8-0                                    8.0.61-1                                     amd64        CUDA solver native dev links, headers
ii  cuda-cusolver-dev-9-0                                    9.0.176-1                                    amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-8-0                                        8.0.61-1                                     amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-9-0                                        9.0.176-1                                    amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-8-0                                    8.0.61-1                                     amd64        CUSPARSE native dev links, headers
ii  cuda-cusparse-dev-9-0                                    9.0.176-1                                    amd64        CUSPARSE native dev links, headers
ii  cuda-demo-suite-8-0                                      8.0.61-1                                     amd64        Demo suite for CUDA
ii  cuda-demo-suite-9-0                                      9.0.176-1                                    amd64        Demo suite for CUDA
ii  cuda-documentation-8-0                                   8.0.61-1                                     amd64        CUDA documentation
ii  cuda-documentation-9-0                                   9.0.176-1                                    amd64        CUDA documentation
ii  cuda-driver-dev-8-0                                      8.0.61-1                                     amd64        CUDA Driver native dev stub library
ii  cuda-driver-dev-9-0                                      9.0.176-1                                    amd64        CUDA Driver native dev stub library
ii  cuda-drivers                                             384.81-1                                     amd64        CUDA Driver meta-package
ii  cuda-libraries-9-0                                       9.0.176-1                                    amd64        CUDA Libraries 9.0 meta-package
ii  cuda-libraries-dev-9-0                                   9.0.176-1                                    amd64        CUDA Libraries 9.0 development meta-package
ii  cuda-license-8-0                                         8.0.61-1                                     amd64        CUDA licenses
ii  cuda-license-9-0                                         9.0.176-1                                    amd64        CUDA licenses
ii  cuda-misc-headers-8-0                                    8.0.61-1                                     amd64        CUDA miscellaneous headers
ii  cuda-misc-headers-9-0                                    9.0.176-1                                    amd64        CUDA miscellaneous headers
ii  cuda-npp-8-0                                             8.0.61-1                                     amd64        NPP native runtime libraries
ii  cuda-npp-9-0                                             9.0.176-1                                    amd64        NPP native runtime libraries
ii  cuda-npp-dev-8-0                                         8.0.61-1                                     amd64        NPP native dev links, headers
ii  cuda-npp-dev-9-0                                         9.0.176-1                                    amd64        NPP native dev links, headers
ii  cuda-nvgraph-8-0                                         8.0.61-1                                     amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-9-0                                         9.0.176-1                                    amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-dev-8-0                                     8.0.61-1                                     amd64        NVGRAPH native dev links, headers
ii  cuda-nvgraph-dev-9-0                                     9.0.176-1                                    amd64        NVGRAPH native dev links, headers
ii  cuda-nvml-dev-8-0                                        8.0.61-1                                     amd64        NVML native dev links, headers
ii  cuda-nvml-dev-9-0                                        9.0.176-1                                    amd64        NVML native dev links, headers
ii  cuda-nvrtc-8-0                                           8.0.61-1                                     amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-9-0                                           9.0.176-1                                    amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-8-0                                       8.0.61-1                                     amd64        NVRTC native dev links, headers
ii  cuda-nvrtc-dev-9-0                                       9.0.176-1                                    amd64        NVRTC native dev links, headers
ii  cuda-repo-ubuntu1604                                     9.0.176-1                                    amd64        cuda repository configuration files
ii  cuda-repo-ubuntu1604-8-0-local-cublas-performance-update 8.0.61-1                                     amd64        cuda repository configuration files
ii  cuda-repo-ubuntu1604-8-0-local-ga2                       8.0.61-1                                     amd64        cuda repository configuration files
ii  cuda-runtime-8-0                                         8.0.61-1                                     amd64        CUDA Runtime 8.0 meta-package
ii  cuda-runtime-9-0                                         9.0.176-1                                    amd64        CUDA Runtime 9.0 meta-package
ii  cuda-samples-8-0                                         8.0.61-1                                     amd64        CUDA example applications
ii  cuda-samples-9-0                                         9.0.176-1                                    amd64        CUDA example applications
ii  cuda-toolkit-8-0                                         8.0.61-1                                     amd64        CUDA Toolkit 8.0 meta-package
ii  cuda-toolkit-9-0                                         9.0.176-1                                    amd64        CUDA Toolkit 9.0 meta-package
ii  cuda-visual-tools-8-0                                    8.0.61-1                                     amd64        CUDA visual tools
ii  cuda-visual-tools-9-0                                    9.0.176-1                                    amd64        CUDA visual tools
ii  libcuda1-384                                             384.90-0ubuntu0.16.04.1                      amd64        NVIDIA CUDA runtime library
ii  libcudnn7                                                7.0.3.11-1+cuda8.0                           amd64        cuDNN runtime libraries
ii  libcudnn7-dev                                            7.0.3.11-1+cuda8.0                           amd64        cuDNN development libraries and headers
ii  libcudnn7-doc                                            7.0.3.11-1+cuda8.0                           amd64        cuDNN documents and samples
rc  nvidia-cuda-toolkit                                      7.5.18-0ubuntu1                              amd64        NVIDIA CUDA development toolkit

**Comment by davisking** [comment]
Huh, I have seemingly the same setup but don't get this test failure.  Can you look at what's going on and see what the issue is?  Maybe training parameters need to be set to use more iterations to make the test reliable.  Or maybe the random seed needs to be set at the top of the function to make weight initialization more consistent.  Try calling srand(1234) at the top of that function.

**Comment by OtacilioNeto** [comment]
After add srand(1234) to top of 

void test_simple_linear_regression_with_mult_prev()

the test have finished with success. 
================================
ota@rigel:~/src/Dlib/dlib-19.7/dlib/build_tests$ ./dtest -d -a --test_dnn
                                                                               

Testing Finished
Total number of individual testing statements executed: 562846
All tests completed successfully
================================
Thank you by your hint!
Should I close this issue?

**Comment by davisking** [comment]
Sweet :)

Yeah, but submit a PR with the change you made :)
