### ISSUE TITLE
issue about the conv layer

### ISSUE THREAD

**Issue by minmummax** [davisking/dlib#926]
hi!
I am wondering why should the conv layer's padding is like this:
int _padding_y = _stride_y!=1? 0 : _nr/2,
int _padding_x = _stride_x!=1? 0 : _nc/2
this make me crazy because I can not choose the paddings I want,how can I solve this problem??

**Comment by davisking** [comment]
Set the padding to the number you want then?

**Comment by minmummax** [comment]
yes,the conv module can not set this value,it only contents 
        long _num_filters,
        long _nr,
        long _nc,
        int _stride_y,
        int _stride_x
       it calculate the padding use this formula 
       int _padding_y = _stride_y!=1? 0 : _nr/2,
       int _padding_x = _stride_x!=1? 0 : _nc/2,
       how can I deal with this?

**Comment by davisking** [comment]
You can set it to whatever you want.  Make a `using` declaration and stick whatever numbers you want in there. Those you posted are just the defaults.

**Comment by minmummax** [comment]
oh,thanks,I will try it and find the solution

**Comment by minmummax** [comment]
I AM sorry can you show me an example please?

**Comment by davisking** [comment]
https://github.com/davisking/dlib/blob/master/dlib/dnn/layers.h#L317
