### ISSUE TITLE
Threshold setting or control for Detection score in Object detection[DNN and MMOD].

### ISSUE THREAD

**Issue by harshkn** [davisking/dlib#930]
Hello, I have trained an object detector based on DNN MMOD loss layer in DLIB to detect "A" in an image. For high res images, I can detect "A" in an image. But in case of low resolution images, I am not able to detect. In order to understand why, I tried to visualise the detector output scores and I get the below result. 

<img width="1048" alt="screen shot 2017-11-08 at 2 51 18 pm" src="https://user-images.githubusercontent.com/377759/32541647-4b998b3c-c496-11e7-8509-1a07acb3dda2.png">

I can see that I get good score for some pyramid scale(bottom left in the pyramid), but the output of the detector does not return any rectangles. I am guessing, there is a threshold that is set and the score is not above the threshold. So my question is, is my guess right, if yes, do I need to look into ```loss.h``` file or any other file ? (please let me know) and if not, how do I go about getting the mmod_rect as result on "A".

**Comment by davisking** [comment]
You could certainly change the detection threshold.  You will probably get
false alarms as well though.  But in any case, you can easily adjust the
threshold by calling net.process().  See the documentation
http://dlib.net/dlib/dnn/core_abstract.h.html#add_loss_layer

**Comment by harshkn** [comment]
Thank you very much @davisking for the help. This is what I was looking for.
