### ISSUE TITLE
webcam_pose_ex && dnn_face_recognition_ex

### ISSUE THREAD

**Issue by andriy-gerasika** [davisking/dlib#931]
Hello,
I have some problems getting face recognizer DNN to work w/ OpenCV in my project -- see webcam_face_pose_ex.cpp that I have slightly modified to illustrate the problem:
[http://www.gerixsoft.com/tmp/webcam_face_pose_ex.cpp](http://www.gerixsoft.com/tmp/webcam_face_pose_ex.cpp)
(my changes are marked by "--------------------------------" lines)

The problem is that the following code
```
	std::vector<matrix<float,0,1>> face_descriptors1 = net(face_chips);
	std::vector<matrix<float,0,1>> face_descriptors2 = net(face_chips);
	cout << "test: " << length(face_descriptors1[0] - face_descriptors2[0]) << endl;
```
emits totally random numbers:
```
test: 78.6697
test: 77.5696
test: 67.7178
test: 82.1669
test: 76.3041
```
but it should be all zeros...

**Comment by davisking** [comment]
I don't know.  Your code looks fine.  You should pop up windows and look at
the intermediate results, like the chip going into the network and see if
it looks funny.

**Comment by andriy-gerasika** [comment]
chip input looks ok, however output descriptor contains values that are greater than 1:
-1.24362 3.80243 2.49374 etc...
I guess these values should all be in -1..1 range -- any ideas why network will emit values greater than 1?

```
	auto m = face_descriptors1[0];
	for (long r = 0; r < m.nr(); ++r)
		for (long c = 0; c < m.nc(); ++c)
			cout << m(r,c) << " ";
	cout << endl;

	image_window chip_win;
	chip_win.set_image(face_chips[0]);
	cin.get();
```

**Comment by davisking** [comment]
The output values can be any numbers at all.  But usually they will be
smaller than 1.

You should try running the unmodified dlib examples and see if they work,
then start from there again to find the problem.

**Comment by andriy-gerasika** [comment]
well, as it turns out, the problem was in my OpenCV build -- all unmodified examples worked, but as soon as I was modifying DNN face_recognition example to trivially use OpenCV it immediately started to emit weird numbers.

I had OpenCV 3.3+libopenblas/lapack+Intel MKL libraries installed on Ubuntu 16.04 (no CUDA). So, I have uninstalled Intel MKL and other Intel IPP libs and rebuilt OpenCV and example started to working ok, albeit a bit slower.

So, I guess Intel MKL 2018 is a bit buggy, or OpenCV is incorrectly using it, or...
