### ISSUE TITLE
Header only?

### ISSUE THREAD

**Issue by mcourteaux** [davisking/dlib#936]
Hey @davisking!

I'm considering to change the cmake again a little, such that we can disable building both the static and the shared library. Because, for now, my main use is the face detector, which is header-only. But the entire dlib project is build, twice (static + shared), when it's totally unnecessary.

Any recommendations or thoughts? I'd go with two CMake options: `DLIB_BUILD_STATIC`, `DLIB_BUILD_SHARED`, which have default values that correspond to what we have now. This would allow to disable both, resulting in CMake simply making an `INTERFACE` library with the necessary include paths and build flags.

**Comment by davisking** [comment]
No, this will definitely confuse a lot of dlib users.  I already get a huge number of questions from people who obviously have no concept of what it even means to compile some code and link to it.  This would just make the situation even more confusing.  

Anyway, how are you using cmake where it builds both of these things?  If you used it like in the examples/CMakeLists.txt it would build dlib just once, statically.

**Comment by mcourteaux** [comment]
As a git submodule in my project. Then simply this cmake:

     add_subdirectory("ext/dlib")

This causes the shared one to be build as well, all the time. The shared one is build if:

    if (UNIX AND NOT DLIB_IN_PROJECT_BUILD)

`UNIX` is `TRUE` for me, as I'm on macOS. Thus, the in-project-build flag is false, which is weird, as I'm building it in my project. I might be misinterpreting the name of this variable name. I see you are detecting this using the `PARENT_DIRECTORY` property. The documentation says:

 > This read-only property specifies the source directory that added the current source directory as a subdirectory of the build. In the top-level directory the value is the empty-string.

So, I guess the directory `ext/` that sits in between shouldn't be a problem, I believe.

**Comment by mcourteaux** [comment]
Considering increased confusion. The options would be backwards compatible. If you don't explicitly configured them differently, the advanced nor dumb C++ users wouldn't notice the difference. It allows us to explicitly disable certain build types (possibly all).

**Comment by davisking** [comment]
Try using the latest dlib from github.

**Comment by davisking** [comment]
Are you using the latest from github?  It shouldn't have this problem.

**Comment by mcourteaux** [comment]
Update: pulling latest in did work: shared is now no longer build.
For the static one: even with all unneeded extensions (cuda, gui, lapack, blas, mlk, gif, png, jpeg, etc etc) disabled, significant time is spent to compiling the dlib core, when I actually don't need it.

**Comment by mcourteaux** [comment]
Hehe, that was a sad but funny read. What bothers me about the current situation is that I do:

    target_link_libraries(my_program dlib)

which causes it to be actually linked as well, which again I don't need, and needlessly increases the resulting binary size. But yet, I have to do this, in order to inherit the include_directories properties.

**Comment by davisking** [comment]
Don't you just need to add the dlib folder to your include search path?
That's probably all you need.

**Comment by mcourteaux** [comment]
Well, I could that definitely do that. That would be equivalent to defining the INTERFACE library in dlib. I'd be nice to have this feature included in some cmake code of dlib, such that we don't need to recreated this interface library ourselves. I'll try and report back in a few minutes.

**Comment by mcourteaux** [comment]
Oh. I'm getting some missing symbols. It seems that the frontal face detector is not header only. Then why was I thinking that? Was it at some time in the past? It's missing the entropy decoder, and a base64 decoder.

Well, then I guess there's no point to this whole issue. I thought you made the frontal face detector header only, to make it as easy as possible to use, to avoid many issues and emails. I'm kinda ruining it here... 😛

**Comment by davisking** [comment]
The detector is header only, but the saved data for the default detector is
stuffed in code that needs some .cpp files.  But if you saved it to a file
yourself and used the iostreams or whatever it would be header only.

lol, yeah, see, I told you :)

**Comment by mcourteaux** [comment]
Is there an example somewhere out there that demonstrates this header-only approach?

**Comment by mcourteaux** [comment]
I found it! Thanks.

https://github.com/davisking/dlib/blob/master/dlib/image_processing/frontal_face_detector.h#L20
