### ISSUE TITLE
CUDA not being use with python API

### ISSUE THREAD

**Issue by Prakosza** [davisking/dlib#941]
Hi 
I compiled the newest version of dlib (straight from master) with VS 2015. I used your setup.py script and I'm sure that during that process the info about that CUDA will be used was displayed. I have CUDA 9 installed with cuDNN 7. Now I don't see any gpu use while using function like compute_face_descriptor. 
Edit: Log of process of compilation and setup https://pastebin.com/x6B8nSuq

**Comment by davisking** [comment]
What is the output of setup.py?

**Comment by Prakosza** [comment]
I added the output in the post above https://pastebin.com/x6B8nSuq

**Comment by davisking** [comment]
It says this

```
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
```

So it's using CUDA.  If it's compiled to use cuda then it's impossible for it to execute without it, so it's definitely using it. There is no non-cuda codepath.

**Comment by so-as** [comment]
@davisking you mean the dlib version that is compiled with cuda on the gpu machine can't execute on the only cpu environment ?

**Comment by Prakosza** [comment]
I was thinking that cuda wasn't working because with shape_predictor_5_face_landmarks.dat and dlib_face_recognition_resnet_model_v1.dat usage of gpu was minimal. But when I added mmod_human_face_detector.dat oh boy was I wrong. Gpu at 70%.

**Comment by davisking** [comment]
Yes, if you compile dlib to use CUDA it's going to use CUDA.  That's how it
is.

**Comment by xhuvom** [comment]
How to compile dlib with cuda support? I am running a real-time facial landmark (5 point) detection example on GTX 1080 GPU  but there is about 1~2 sec lag. Monitoring GPU memory shows it only uses about 10Mb GPU memory. As on my 8GB GPU, the code should fly without any lag.

**Comment by garinthengineer** [comment]
As I understood, to compie dlib for python API with CUDA support one should have CUDA and, probbably cuDNN installed on the machine. That one should git clone the dlib reepsetory, and then run a setup.py file from the root there witn special flags like:
python setup.py install --yes DLIB_USE_CUDA
and, perhaps some others like --yes USE_AVX_INSTRUCTIONS if ones processor support such instructions

**Comment by davisking** [comment]
Yes, you need to have CUDA and cudNN installed to use any CUDA related accelerations. Just running `python setup.py install` is fine.  Despite all the nonsense on the internet, you never need to give `--yes DLIB_USE_CUDA`.  The command `--yes DLIB_USE_CUDA` literally does nothing and has always done nothing.  You could say `--no DLIB_USE_CUDA` and it would disable CUDA though.

If are going to use the python module on a CPU with AVX instructions then you can say `--yes USE_AVX_INSTRUCTIONS` and some things will be faster.  The default has been to not use AVX unless the users asks.  However, the code currently in git now checks if the host computer supports AVX and automatically enables it for python modules.  So anyone using the latest dlib doesn't have to say `--yes USE_AVX_INSTRUCTIONS` and it is literally a noop now.  However, `--no USE_AVX_INSTRUCTIONS` can disable them just like `--no` works for CUDA.
