### ISSUE TITLE
dlib/assert.h:97:45: error: static assertion failed: Failed assertion

### ISSUE THREAD

**Issue by smajida** [davisking/dlib#942]
when I compile Dlib library for Python using the following link. I get error.

```bash
python setup.py install
```
```bash
/home/meysam/vision/dlib-master/dlib/../dlib/assert.h:97:45: error: static assertion failed: Failed assertion
     #define COMPILE_TIME_ASSERT(expression) static_assert(expression, "Failed assertion")
                                             ^
/home/meysam/vision/dlib-master/dlib/../dlib/matrix/matrix.h:1093:13: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
             COMPILE_TIME_ASSERT(EXP::NC == NC || NC == 0 || EXP::NC == 0);
             ^
make[2]: *** [CMakeFiles/dlib_.dir/src/decision_functions.cpp.o] Error 1
make[1]: *** [CMakeFiles/dlib_.dir/all] Error 2
make: *** [all] Error 2
error: cmake build failed!
```

python 3.5
ubuntu14.04
No GPU (cuda is not needed)

**Comment by smajida** [comment]
I was compiling with master version.
the issue was resolved with cloned 19.7 version.

**Comment by davisking** [comment]
Are you saying the version of dlib in github right now doesn't compile for you but v19.7 does?

**Comment by smajida** [comment]
Yes, this is what I noticed. Maybe I am wrong, but I did not changed anything in my system configuration, except I downloaded v19.7 rather than master branch and I could compile for python with no problems.
