### ISSUE TITLE
Loss_binary_log // DNN Module // Error

### ISSUE THREAD

**Issue by Arritmic** [davisking/dlib#944]
Hi,
I am trying to train a binary classifier usind the DNN module but I am having some errors.

The "loss_multiclass" classifier is working based on your examples. But any example about the loss_binary function.

I am trying to using the "loss_binary" function because in your documentation, you tell I am going to obtain a value between 0 and 1. And if it is >0 then it belongs to class 1. Because I need a confidence value apart of the classification.

My net:

```
    using net_type = loss_binary_log<fc<1,
    relu<fc<32,
    relu<fc<64,
    max_pool<2,2,2,2,relu<con<16,5,5,1,1,
    max_pool<2,2,2,2,relu<con<6,5,5,1,1,
    input<matrix<unsigned char>>
    >>>>>>>>>>>>>;
```
The error:
_**************************** FATAL ERROR DETECTED ****************************

Error detected at line 197.
Error detected in file ../../../libs/dlib_19_7v2/dlib/dlib/dnn/loss.h.
Error detected in function double dlib::loss_binary_log_::compute_loss_value_and_gradient(const dlib::tensor&, const_label_iterator, SUBNET&) const [with const_label_iterator = __gnu_cxx::__normal_iterator<float*, std::vector<float> >; SUBNET = dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::fc_<1ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::fc_<1ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::fc_<32ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::fc_<64ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::max_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::con_<16l, 5l, 5l, 1, 1, 2, 2>, dlib::add_layer<dlib::max_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::con_<6l, 5l, 5l, 1, 1, 2, 2>, dlib::input<dlib::matrix<unsigned char, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void>].

Failing expression was y == +1 || y == -1.
y: 0

******************************************************************************_

And if I define the net changing the number of labels like this:

```
    using net_type = loss_binary_log<
    relu<fc<32,
    relu<fc<64,
    max_pool<2,2,2,2,relu<con<16,5,5,1,1,
    max_pool<2,2,2,2,relu<con<6,5,5,1,1,
    input<matrix<unsigned char>>
    >>>>>>>>>>>;
```
The error changes but I can understand it...
_**************************** FATAL ERROR DETECTED ****************************

Error detected at line 182.
Error detected in file ../../../libs/dlib_19_7v2/dlib/dlib/dnn/loss.h.
Error detected in function double dlib::loss_binary_log_::compute_loss_value_and_gradient(const dlib::tensor&, const_label_iterator, SUBNET&) const [with const_label_iterator = __gnu_cxx::__normal_iterator<float*, std::vector<float> >; SUBNET = dlib::dimpl::subnet_wrapper<dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::fc_<32ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::fc_<64ul, (dlib::fc_bias_mode)0u>, dlib::add_layer<dlib::max_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::con_<16l, 5l, 5l, 1, 1, 2, 2>, dlib::add_layer<dlib::max_pool_<2l, 2l, 2, 2, 0, 0>, dlib::add_layer<dlib::relu_, dlib::add_layer<dlib::con_<6l, 5l, 5l, 1, 1, 2, 2>, dlib::input<dlib::matrix<unsigned char, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >, void>, void>, void>, void>, void>, void>, void>, void>, void>, void>, true, void>].

Failing expression was output_tensor.nr() == 1 && output_tensor.nc() == 1 && output_tensor.k() == 1.

******************************************************************************_

Thanks in advance. Probably it is a stupid question. So, it is so, my apologies

**Comment by davisking** [comment]
The labels have to be either +1 or -1.  That's what the error is telling
you.

**Comment by Arritmic** [comment]
Yes.... You are totally right... That is the result of working a Saturday night. Thanks so so much for your fast answer!! Muchas gracias!! :)

**Comment by Arritmic** [comment]
Btw, the problem was solved perfectly.  Thanks again.
