### ISSUE TITLE
Can we train model with some images of our own

### ISSUE THREAD

**Issue by sukhalid** [davisking/dlib#947]
Dear sir, I am working on face recognition, need to train (incrementally train) already trained model with images of my classmates. Is this some how possible and can you guide me to some relevant link?

**Comment by harshkn** [comment]
Check this issue [https://github.com/davisking/dlib/issues/922](https://github.com/davisking/dlib/issues/922). I am guessing it is not possible to train the model with trained model as starting point as the batch norm layer is removed saved trained model. 

Also as Davis suggests, it is not a good idea to fine tune.
