### ISSUE TITLE
Error building DTEST on MSVC 2015

### ISSUE THREAD

**Issue by e-fominov** [davisking/dlib#95]
compiling by *cmake .. -G"Visual Studio 14 2015"*:
**dlib\dlib\test\multithreaded_object.cpp(186): error C2694: `anonymous namespace'::test4_c2::~test4_c2(void) throw(std::exception)
'override': overriding virtual function has less restrictive exception specification than base class virtual member function 'base'**

https://msdn.microsoft.com/en-us/library/e4x95xf8.aspx

MSVC 2015 fails to build a test (MSVC2013 works good)

failed destructor code:

```c++
~test4_c2() throw (std::exception)
{
            DLIB_TEST(number_of_threads_registered() == 2);
            DLIB_TEST(number_of_threads_alive() == 2);
            DLIB_TEST_MSG(is_running() == false,"is_running(): " << is_running());
            stop();
            DLIB_TEST(number_of_threads_registered() == 2);
            DLIB_TEST(is_running() == false);
            wait();
            DLIB_TEST(number_of_threads_registered() == 2);
            DLIB_TEST(number_of_threads_alive() == 0);
            DLIB_TEST(is_running() == false);
        }
```

base class destructor code
```c++
    multithreaded_object::
    ~multithreaded_object (
    )
    {
        try
        {
            DLIB_ASSERT(number_of_threads_alive() == 0,
                   "\tmultithreaded_object::~multithreaded_object()"
                   << "\n\tYou have let a multithreaded object destruct itself before terminating its threads"
                   << "\n\tthis: " << this
            );
        }
        catch (std::exception& e)
        {
            std::cerr << e.what() << std::endl;
            assert(false);
            abort();
        }
    }
```
do we really need *throw (std::exception)* ? if no - I can make PR

**Comment by davisking** [comment]
We need the throw (std::exception) because destructors are noexcept by default in C++11 (see http://en.cppreference.com/w/cpp/language/noexcept_spec).  Without it, if any of those tests fail in test4_c2 the program will be abruptly terminated.

So the right thing to do is to disable this visual studio warning in just this test file with a #pragma.

**Comment by davisking** [comment]
Oops, you are right.  I fixed this months ago but accidentally made the changes in a private dlib branch (I'm adding deep learning tooling to dlib). I'm going push the updated branch in a few days which will fix this so don't worry about it :)

**Comment by davisking** [comment]
Ok, it should be fixed now.

**Comment by e-fominov** [comment]
Yes, the problem with compiling multithreaded_object solved
But now it fails to build dnn.cpp from dtest:

>c:\work\dlib\dlib\dnn\core.h(159): error C2995: alwaysbool<unknown-type>::type dlib::impl::backward_requires_forward_output(layer_type &,SUBNET &): function template already defined
> c:\work\dlib\dlib\dnn\core.h(144): note:  see previous definition of "dlib::impl::backward_requires_forward_output"
>c:\work\dlib\dlib\dnn\core.h(603): error C2976: dlib::add_layer:too few template arguments
>  c:\work\dlib\dlib\dnn\core.h(878): note:  see definition of "dlib::add_layer"

total 25 such errors (MSVC 2015 x64), and I dont have CUDNN installed

**Comment by davisking** [comment]
That code uses a bunch of C++11 features, some of which weren't supported by visual studio 2015.  So I added the COMPILER_CAN_DO_CPP_11 cmake flag (defined in dlib/use_cpp_11.cmake) to check if C++11 was supported and only try to compile these things if it was.  Apparently that's not working on your machine.  

Maybe you have a slightly newer version of visual studio and it supports all the things listed in use_cpp_11.cmake but that list is incomplete?

**Comment by davisking** [comment]
I just ran it on the newest version of visual studio.  I had to adjust the build scripts to detect that visual studio still doesn't fully implement C++11.

**Comment by e-fominov** [comment]
Right now successfully built MSVC2013 and 2015 - all ok. DNN tests skipped from build process

**Comment by davisking** [comment]
Cool

**Comment by stanrusnak** [comment]
Hello, I'm trying to compile with vs2015, but got exactly same "function template already defined" errors. Can you maybe some details, how did you manage to build it with MSVC2015? Thanks.

**Comment by davisking** [comment]
http://dlib.net/faq.html#Whycan'tIusetheDNNmodulewithVisualStudio

**Comment by stanrusnak** [comment]
It builds with vs2015 update 3. Thanks!
