### ISSUE TITLE
Which face area is used by CNN to build a descriptor

### ISSUE THREAD

**Issue by manmitya** [davisking/dlib#954]
Often, after "face detection", the area of ​​the face without chin, ears and forehead is highlighted. However, if we mark the face with 68 landmarks, then the chin will be highlighted. Two parameters are fed to the input of dlib CNN dlib_face_recognition_resnet_model_v1.dat - a rectangle from "face detect" and 68 landmarks. Question: which area is used by the CNN to build the descriptor? Is there a chin in this area that did not fit into the face detect rectangle, but entered the area of ​​the landmarks?

**Comment by davisking** [comment]
The whole face is used, including the chin.  If you look at the code
examples you can see an image gets cropped out using the landmarks and then
that image goes to the network. Look at that image and you can see what
goes to the network.

**Comment by davisking** [comment]
I guess you need to look at the C++ example to see these details.

**Comment by manmitya** [comment]
Ok, I get it. Just in the python examples it is not obvious :)

**Comment by manmitya** [comment]
As I understand it, we are talking about the functions extract_image_chip and get_face_chip_details. Do you have plans to do bindings for these functions in Python? ;)

**Comment by davisking** [comment]
It's already in
https://github.com/davisking/dlib/blob/master/python_examples/face_clustering.py

**Comment by manmitya** [comment]
This is great news! And tell me, please, 150 x 150 is the size of the images on which the CNN dlib_face_recognition_resnet_model_v1.dat was trained? Why the image of this size is transferred for processing of a CNN?

**Comment by davisking** [comment]
150x150 was determined empirically to be good.

**Comment by manmitya** [comment]
clearly, this size was used for network training too?

**Comment by davisking** [comment]
Yes

**Comment by manmitya** [comment]
Ok, thanks!
