### ISSUE TITLE
Build With Android NDK r15 Fails 

### ISSUE THREAD

**Issue by schrieveslaach** [davisking/dlib#955]
I'm trying to build dlib for Android. Therefore, I create a custom Android toolchain (with statically linked libc++, see [here](https://developer.android.com/ndk/guides/standalone_toolchain.html)):

```
$ANDROID_NDK/build/tools/make_standalone_toolchain.py  --arch arm --api 21 --stl=libc++ --install-dir target/android-toolchain/arm/ --force
```

Now I have my `CMakeLists.txt`.

```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(localizer CXX)

SET(CMAKE_CROSSCOMPILING FALSE)
SET(DLIB_NO_GUI_SUPPORT TRUE)
ADD_COMPILE_OPTIONS(-fPIC)

INCLUDE(dlib/dlib/cmake)

FIND_PACKAGE(Java)
FIND_PACKAGE(JNI)

SET(APP_INCLUDE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/main/include/")
SET(APP_SOURCE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/main/c++/")
SET(DLIB_INCLUDE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/dlib/")

INCLUDE_DIRECTORIES(
        "${APP_INCLUDE_DIRECTORY}"
        "${DLIB_INCLUDE_DIRECTORY}")

ADD_LIBRARY(mylib SHARED
    "${APP_SOURCE_DIRECTORY}/dlib/MyLib.cpp")
TARGET_LINK_LIBRARIES(mylib dlib::dlib)

SET_TARGET_PROPERTIES (
    mylib
    PROPERTIES
        LINKER_LANGUAGE CXX
        LIBRARY_OUTPUT_DIRECTORY "${CLASSPATH_TARGET_DIRECTORY}"
)
```

and a toolchain file, `Android-armeabi-v7a.cmake`:

```cmake
SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER   "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/bin/arm-linux-androideabi-gcc")
SET(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/bin/arm-linux-androideabi-g++")

# No pthread for Android
SET(DLIB_ISO_CPP_ONLY TRUE)

# Disable MKL FFT (Intel Fourier Transform Functions)
SET(DLIB_USE_MKL_FFT FALSE)

ADD_COMPILE_OPTIONS(-static-libstdc++)

SET(CLASSPATH_TARGET_DIRECTORY "${CMAKE_BINARY_DIR}/../classes/android-armeabi-v7a")

# Workaround, suggested here: https://github.com/android-ndk/ndk/issues/215#issuecomment-253354618
ADD_COMPILE_OPTIONS(-nostdinc)
INCLUDE_DIRECTORIES(
    "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/sysroot/usr/include/"
    "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/include/c++/4.9.x/"
    "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/sysroot/usr/local/include/"
    "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/lib/gcc/arm-linux-androideabi/4.9.x/include/"
    "${CMAKE_CURRENT_SOURCE_DIR}/target/android-toolchain/arm/include/c++/4.9.x/arm-linux-androideabi/"
)
```

Then I run `cmake`

```bash
cmake -DCMAKE_TOOLCHAIN_FILE=Android-armeabi-v7a.cmake CMakeLists.txt  --target target/Android-armeabi-v7a/
```

When I run `make`, I get following error;

```
target/android-toolchain/arm/include/c++/4.9.x/cmath:313:9: error: '::signbit' has not been declared
 using ::signbit;
         ^
```

Do you have any suggestion how to build dlib with Android toolchain?

**Comment by schrieveslaach** [comment]
I found a solution. You can use the toolchain file provided by the Android NDK (you even do not need to `$ANDROID_NDK/build/tools/make_standalone_toolchain.py`). 

```bash
cmake \
    -DCMAKE_TOOLCHAIN_FILE=${env.ANDROID_NDK}/build/cmake/android.toolchain.cmake
    --target target/Android-armeabi-v7a/ \
    -DANDROID_PLATFORM=android-19 \
    -DANDROID_ABI=armeabi-v7a \
    -DANDROID_STL=c++_static \
    -DDLIB_USE_BLAS=FALSE \
    -DDLIB_USE_LAPACK=FALSE \
    -DDLIB_NO_GUI_SUPPORT=TRUE \
    -GNinja
```

@davisking, do you mind to add this to your `README.md`?

**Comment by davisking** [comment]
This seems like a general "How to compile C++ on android" rather than "how
to use dlib".  Also, certainly, some of those settings like the ABI must be
different for different android platforms.  So this probably isn't
appropriate for dlib's readme.

**Comment by schrieveslaach** [comment]
There is a current trend to use native machine learning code on Android devices. For example, Google released [Tensorflow lite](https://developers.googleblog.com/2017/11/announcing-tensorflow-lite.html). So I think the library should show that it is possible to compile Dlib for Android devices and that there is no [explicit fork](https://github.com/tzutalin/dlib-android) necessary. 

IMHO, the examples could contain an Android example and I was a little challenge to find a solution. So it might be useful for others too.

**Comment by schrieveslaach** [comment]
This issue #965 mentions the usage on Android as well.

**Comment by davisking** [comment]
Fair enough.  But an entire working example app is probably what is
needed.  Can you contribute something like that?  I haven't done any
android development myself so I'm not sure what constitutes a reasonable
tutorial.

**Comment by schrieveslaach** [comment]
I can do it. I'm thinking to use [this example](https://github.com/davisking/dlib/blob/master/examples/face_landmark_detection_ex.cpp). An App could show an image and after clicking onto the image, it will highlight the images. 

If I omit [`image_window win, win_faces;`](https://github.com/davisking/dlib/blob/3d62b85c502b351e0b9dcd804dbc9b13c2896792/examples/face_landmark_detection_ex.cpp#L91), will it compile with `-DDLIB_NO_GUI_SUPPORT=TRUE`?

**Comment by davisking** [comment]
Sweet.

Yeah, if you remove those things, along with the #include for the gui
header files and set that preprocessor switch it should build just fine.

**Comment by axmadjon** [comment]
try using
http://slides.com/boywang/face-landmarks-in-your-android-app/fullscreen#/

**Comment by xsacha** [comment]
I've never had any issues compiling with NDK r15. I recently switched to NDK r16.

For reference, these are the CMake options I set:
```CMake
                                                DLIB_USE_CUDA=OFF
                                                DLIB_HEADER_ONLY=OFF
                                                DLIB_ISO_CPP_ONLY=OFF
                                                DLIB_NO_GUI_SUPPORT=ON
                                                DLIB_ENABLE_STACK_TRACE=OFF
                                                DLIB_JPEG_SUPPORT=OFF
                                                DLIB_PNG_SUPPORT=OFF
                                                DLIB_GIF_SUPPORT=OFF
                                                CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
                                                DLIB_LINK_WITH_SQLITE3=OFF
```
