### ISSUE TITLE
Error deserializing object unpack_int and unpack_byte 

### ISSUE THREAD

**Issue by arana2T** [davisking/dlib#963]
Hi @davisking :) ,

i like dlib library and i need to train my own model , I use dnn_imagenet_train_ex.cpp sample training picture classification, and i have done the train  but the model get an error .

`
Error deserializing object of type unsigned long
while deserializing object of type std::vector .
`

I do not know, maybe the problem in the operating system platform 32/64 and Linux / windows on which I did the training or the deserialization of file dnn after the training,

`if (ser_helper :: unpack_int (item, in)) throw serialization_error ("Error deserializing object of type" + std :: string (#T));

if (unpack_byte (item, in)) throw serialization_error ("Error deserializing object of type" + std :: string (#T));`

please ,I want you to recommend me on a desirable system (linux/windows and 32 or 64) to avoid these types of errors on unpack_int, unpack_byte  when deserializing dnn file ,

thank you , :)

**Comment by davisking** [comment]
The serialization code works on all computers and operating systems the
same.  That doesn't matter.  There is no combination you could use that
would make it not work. You probably have just typed the filename wrong.

**Comment by omarkacem** [comment]
hello @davisking @arana2T ;
 I have the same problem despite I downloaded the ILSVRC2015 (about 166 Gb) and i start the training with the same imagenet2015_validation_images.txt  and i passing the same parameters in dnn_imagenet_train_ex but the dnn_imagenet_ex.cpp give me the same error:
    Error deserializing object of type unsigned long
    while deserializing object of type std::vector.
And i am sure that the file name is not wrong.
Can you help me if i forget something.
I do not know why that happened.

**Comment by davisking** [comment]
Look at the example training code in dnn_imagenet_train_ex.cpp.  It only saves the network.  The other example, dnn_imagenet_ex.cpp, loads a saved network **and the imagnet string labels, which are not included in the output of dnn_imagenet_train_ex.cpp**.   

You have to read the examples and understand them.  The point of them is to be educational documents.  Not a set of utilities you just run and do useful things with.  None of them are intended to be useful tools.  They are documentation.  You have to read them, understand, and think about what it is you are trying to accomplish.  If all you wanted to do was run an imagenet trained model you could download the provided file.  If you want to train a new model you need to think about what you are trying to accomplish and write code that is appropriate for that task.  But the first step is reading the examples.
