### ISSUE TITLE
Segmentation Fault in impl_extract_fhog_features - Ubuntu 16.04

### ISSUE THREAD

**Issue by 79rpm** [davisking/dlib#967]
Hello,

I am running some stability testing with the very basic code that is using the FHOG for face detection. I am running a HD video coming in at 30fps. I am currently running the detector on each of the frames. 

I checked with GDB and was stopped in the push_back below. I need to check the memory allocation. 
.....
scanner.load(img);
        std::vector<std::pair<double, rectangle> > dets;
        std::vector<rect_detection> dets_accum;

        for (unsigned long i = 0; i < w.size(); ++i)
        {
            const double thresh = w[i].w(scanner.get_num_dimensions());
            scanner.detect(w[i].get_detect_argument(), dets, thresh + adjust_threshold);
            for (unsigned long j = 0; j < dets.size(); ++j)
            {
                rect_detection temp;
                temp.detection_confidence = dets[j].first-thresh;
                temp.weight_index = i;
                temp.rect = dets[j].second;
                dets_accum.push_back(temp); <<<<< last call before the segmentation fault
            }
        }

Thread 1 "mai-app" received signal SIGSEGV, Segmentation fault.
malloc_consolidate (av=av@entry=0x7ffff2c88b20 <main_arena>) at malloc.c:4167
4167	malloc.c: No such file or directory.
(gdb) bt
#0  malloc_consolidate (av=av@entry=0x7ffff2c88b20 <main_arena>) at malloc.c:4167
#1  0x00007ffff2945cde in _int_malloc (av=av@entry=0x7ffff2c88b20 <main_arena>, 
    bytes=bytes@entry=1073088) at malloc.c:3450
#2  0x00007ffff2948184 in __GI___libc_malloc (bytes=1073088) at malloc.c:2913
#3  0x00007ffff323ae78 in operator new(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff323af19 in operator new[](unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x0000000000426ff4 in void dlib::impl_fhog::impl_extract_fhog_features<dlib::cv_image<dlib::bgr_pixel>, dlib::array<dlib::array2d<float, dlib::memory_manager_stateless_kernel_1<char> >, dlib::memory_manager_stateless_kernel_1<char> > >(dlib::cv_image<dlib::bgr_pixel> const&, dlib::array<dlib::array2d<float, dlib::memory_manager_stateless_kernel_1<char> >, dlib::memory_manager_stateless_kernel_1<char> >&, int, int, int) ()
#6  0x000000000042b8be in void dlib::impl::create_fhog_pyramid<dlib::pyramid_down<6u>, dlib::cv_image<dlib::bgr_pixel>, dlib::default_fhog_feature_extractor>(dlib::cv_image<dlib::bgr_pixel> const&, dlib::default_fhog_feature_extractor const&, dlib::array<dlib::array<dlib::array2d<float, dlib::memory_manager_stateless_kernel_1<char> >, dlib::memory_manager_stateless_kernel_1<char> >, dlib::memory_manager_stateless_kernel_1<char> >&, int, int, int, unsigned long, unsigned long, unsigned long) ()
#7  0x00000000004313ef in void dlib::object_detector<dlib::scan_fhog_pyramid<dlib::pyramid_down<6u>, dlib::default_fhog_feature_extractor> >::operator()<dlib::cv_image<dlib::bgr_pixel> >(dlib::cv_image<dlib::bgr_pixel> const&, std::vector<dlib::rect_detection, std::allocator<dlib::rect_detection> >&, double) ()
#8  0x0000000000414b8d in makexxxxGui() ()
#9  0x0000000000410550 in main ()

**Comment by davisking** [comment]
Post something that I can run that reproduced the problem.

**Comment by 79rpm** [comment]
Thanks for the quick reply, I am working on it.

**Comment by 79rpm** [comment]
I am closing this issue, as we were not able to reproduce the crash with unit testing. We are investigating other SW components now.
