### ISSUE TITLE
When I use toMat() to cv::Mat ,Error hapen

### ISSUE THREAD

**Issue by anthonyyuan** [davisking/dlib#970]
[ 98%] Building CXX object CMakeFiles/df.dir/df.cpp.o
In file included from /home/anthony/work/tool/dlib--a/dlib/../dlib/opencv.h:11:0,
                 from /home/anthony/work/tool/dlib--a/examples/df.cpp:28:
/home/anthony/work/tool/dlib--a/dlib/../dlib/opencv/to_open_cv.h: In instantiation of ‘cv::Mat dlib::toMat(image_type&) [with image_type = dlib::matrix<dlib::rgb_pixel>]’:
/home/anthony/work/tool/dlib--a/examples/df.cpp:327:35:   required from here
/home/anthony/work/tool/dlib--a/dlib/../dlib/opencv/to_open_cv.h:29:119: error: ‘type’ is not a member of ‘cv::DataType<dlib::rgb_pixel>’
  num_columns(img), cv::DataType<type>::type, image_data(img), width_step(img));
                                                                              ^
CMakeFiles/df.dir/build.make:62: recipe for target 'CMakeFiles/df.dir/df.cpp.o' failed
make[2]: *** [CMakeFiles/df.dir/df.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/df.dir/all' failed
make[1]: *** [CMakeFiles/df.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davisking** [comment]
Closed because you ignored the issue template.  Read the instructions for submitting an issue and resubmit.
