### ISSUE TITLE
CMAKE_PREFIX_PATH is being overwritten

### ISSUE THREAD

**Issue by andrewbleonard** [davisking/dlib#973]
## Expected Behavior

I want to specify CMAKE_PREFIX_PATH to have find_library, find_path, and find_file look in different locations for libraries, binaries, and headers.  I need to do this because I am developing on a system that does not install its dependencies to /usr/.

## Current Behavior

CMAKE_PREFIX_PATH is being overwritten in dlib/cmake_utils/add_python_module line 35, so I can't specify my own CMAKE_PREFIX_PATH via the command-line invocation of cmake.  This should either be removed or changed to append to the CMAKE_PREFIX_PATH, like this: `list(APPEND CMAKE_PREFIX_PATH "${PYTHON_PATH}")`
I tried both ways and both worked for me.

## Steps to Reproduce

Put dependencies (like boost and openblas) into non-standard directories, pass `-DCMAKE_PREFIX_PATH=/path/to/your/deps` to cmake, and build using the CMakeLists.txt in dlib/tools/python so that add_python_module is called.  /path/to/your/deps should be the directory that contains the libs/, bin/, and include/ directories.

* **Version**:  v19.7
* **Where did you get dlib**:  git clone -b 'v19.7' --single-branch https://github.com/davisking/dlib.git dlib/
* **Platform**:  Ubuntu 16.04.3 within a Docker container (version 17.09.0-ce)
* **Compiler**:  GCC 5.4.0

**Comment by davisking** [comment]
Yes, good idea.  I just pushed this change to github.  Thanks for suggesting it.
