### ISSUE TITLE
compiling /dlib/dlib/cmake_utils/test_for_cuda/ ends in "std" has no member "__builtin_fpclassify"

### ISSUE THREAD

**Issue by nanu-c** [davisking/dlib#981]
## Expected Behavior

Compiling the test for cuda

## Current Behavior

It's missing somehow the std.
If I modify/comment the line 
`/optimization_line_search.h(215): error: namespace "std" has no member "__builtin_fpclassify"`
the next error is
`dlib/dlib/cmake_utils/test_for_cuda/../../dnn/../matrix/../serialize.h(1549): error: namespace "std" has no member "to_string"`

## Steps to Reproduce

```
nanu@xyW-R:~/src$ git clone https://github.com/davisking/dlib.git
Klone nach 'dlib' ...
remote: Counting objects: 42599, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 42599 (delta 43), reused 41 (delta 24), pack-reused 42530
Empfange Objekte: 100% (42599/42599), 17.12 MiB | 3.33 MiB/s, Fertig.
Löse Unterschiede auf: 100% (29792/29792), Fertig.
nanu@xyW-R:~/src$ mkdir testcuda
nanu@xyW-R:~/src$ cd testcuda/
nanu@xyW-R:~/src/testcuda$ cmake ../dlib/
appveyor.yml       dlib/              examples/          .gitignore         .hgtags            MANIFEST.in        README.md          tools/             
CMakeLists.txt     docs/              .git/              .hgignore          ISSUE_TEMPLATE.md  python_examples/   setup.py           .travis.yml                               
nanu@xyW-R:~/src/testcuda$ cmake ../dlib/dlib/cmake_utils/test_for_cuda/
CMakeLists.txt  cuda_test.cu    
nanu@xyW-R:~/src/testcuda$ cmake ../dlib/dlib/cmake_utils/test_for_cuda/
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nanu/src/testcuda
nanu@xyW-R:~/src/testcuda$ make
[ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
/home/nanu/src/dlib/dlib/cmake_utils/test_for_cuda/../../dnn/../matrix/../optimization/optimization_line_search.h(215): error: namespace "std" has no member "__builtin_fpclassify"

1 error detected in the compilation of "/tmp/tmpxft_00004593_00000000-7_cuda_test.cpp1.ii".
CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:282 (message):
  Error generating file
  /home/nanu/src/testcuda/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o


CMakeFiles/cuda_test.dir/build.make:63: die Regel für Ziel „CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o“ scheiterte
make[2]: *** [CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/cuda_test.dir/all“ scheiterte
make[1]: *** [CMakeFiles/cuda_test.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
nanu@xyW-R:~/src/testcuda$ 
```

* **Version**:  Most recent from github
* **Where did you get dlib**: github
* **Platform**: 
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

* **Compiler**: 
```
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
```
```
g++-5 -v
Using built-in specs.
COLLECT_GCC=g++-5
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20171010 (Ubuntu 5.5.0-1ubuntu1)
```

```
gcc-5 -v
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20171010 (Ubuntu 5.5.0-1ubuntu1) 
```

**Comment by nanu-c** [comment]
```
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. ***
CMake Warning (dev) at /usr/share/cmake-3.9/Modules/FindOpenMP.cmake:200 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "c" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  dlib/CMakeLists.txt:615 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA

```

**Comment by davisking** [comment]
Weird.  Something is wrong with your compiler if it's missing fpclassify().  I would try reinstalling gcc and/or nvcc, depending on which ones are missing this function.

**Comment by nanu-c** [comment]
okey, removing my complete cuda installation like described here:

https://askubuntu.com/questions/530043/removing-nvidia-cuda-toolkit-and-installing-new-one

and reinstalling

then the cuda 9 isn't working with gcc-5/g++-5 but
with ` export CXX=/usr/bin/g++-6 && export CC=/usr/bin/gcc-6`

**Comment by maxisme** [comment]
did you find a solution to this?

**Comment by nanu-c** [comment]
This `export CXX=/usr/bin/g++-6 && export CC=/usr/bin/gcc-6` was my solution

**Comment by harshulgupta2** [comment]
Is there any solution to this problem. I am unable to compile DLIB with CUDA. It shows namespace "std" has no member "__builtin_fpclassify". 
Ubuntu: 17.10
GCC version used: 4.8
CUDA: 8.0
Cudnn: 6.0
Thank you

**Comment by nanu-c** [comment]
I think you have to use 
GCC version used: 6

**Comment by davisking** [comment]
Yes, you have to read the manual.  https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html  It tells you what compilers are supported by CUDA.

**Comment by harshulgupta2** [comment]
Thank you for your response but DLIB compilation asks to use a GCC version lower than 5.0.That's why I downgraded the GCC to 4.8. 
My GPU compute capability is 2.1 so will that affect DLIB execution on GPU even if I do manage to compile DLIB correctly.
Thank you

**Comment by davisking** [comment]
Dlib doesn't require a gcc version lower than anything.  Where does it say
lower than 5.0?

**Comment by harshulgupta2** [comment]
Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cudnn/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA. 
-- *** The output of the failed CUDA test compile is shown below: 
-- ***   Change Dir: /home/hgupta/dlib/build/temp.linux-x86_64-2.7/dlib_build/cuda_test_build
   ***   
   ***   Run Build Command:"/usr/bin/make"
   ***   [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
   ***                    from <command-line>:0:
   *****   **/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!****
   ***    #error -- unsupported GNU version! gcc versions later than 5 are not supported!
   ***     ^~~~~
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:218 (message):
   ***     Error generating
   ***     /home/hgupta/dlib/build/temp.linux-x86_64-2.7/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
   ***   
   ***   
   ***   CMakeFiles/cuda_test.dir/build.make:63: recipe for target 'CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o' failed
   ***   make[2]: *** [CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o] Error 1
   ***   CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cuda_test.dir/all' failed
   ***   make[1]: *** [CMakeFiles/cuda_test.dir/all] Error 2
   ***   Makefile:83: recipe for target 'all' failed
   ***   make: *** [all] Error 2
   ***   
-- *****************************************************************************************************************

I used below cmd 
sudo python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA --set CMAKE_PREFIX_PATH=/usr/local/cudnn

**Comment by davisking** [comment]
Ok, that's not a dlib message. It's CUDA.  In any case, you have to use the
compiler required by CUDA.

**Comment by harshulgupta2** [comment]
but when I switch to GCC 4.8 I get **namespace "std" has no member "__builtin_fpclassify".**

**Comment by davisking** [comment]
I don't know. But this isn't related to dlib.  https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html  Read the instructions.  You aren't supposed to use GCC 4.8 on ubuntu 17.04.  You have somehow terribly messed up the CUDA install.  Read the NVIDIA instructions and follow them carefully.

**Comment by harshulgupta2** [comment]
Okay. I will check there. 
Thanks a lot for the help.
