### ISSUE TITLE
 WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by shashankavs** [davisking/dlib#982]
When I run this ->sudo ./face_recognition.py shape_predictor_68_face_landmarks.dat dlib_face_recognition_resnet_model_v1.dat ..examples/face

I am getting this error
** (face_recognition.py:1732): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Pls help.

**Comment by pranavji** [comment]
Hey try running 
$ sudo apt-get install at-spi2-core
and reboot.
also change value of eye_ar_consec_frames=10 or close the eye long enough. (48 frames)
