### ISSUE TITLE
How to optimize the face identification?

### ISSUE THREAD

**Issue by volye** [davisking/dlib#984]
There are three different photos, a and b are the same person, the score is 0.61, a and c are different people, the score is 0.62, apparently misjudged, may I ask how to optimize?

**Comment by yanchao12122** [comment]
use your own dataet to train your own model

**Comment by davisking** [comment]
That's what's supposed to happen, different people have higher "Scores" (i.e. higher distances). 

If you want to make it better I would train a linear classifier like a linear SVM on top of the model.
