### ISSUE TITLE
QImage to array2d<rgb_pixel>

### ISSUE THREAD

**Issue by pepeverde9** [davisking/dlib#986]
Hello
Using Qt, I want to convert a QImage, having the format QImage::Format_RGB888 to array2d<rgb_pixel>.
After some googling, I came up with
void qImage2array2d(const QImage &src, dlib::array2d<dlib::rgb_pixel> &dst)
{
    dlib::assign_image(dst,
                       dlib::mat((const dlib::rgb_pixel *)src.bits(),
                                 src.height(), src.width() /*, src.bytesPerLine()/3 */));
}
It works well when src.bytesPerLine() is 3 * src.width(). But the stride parameter seems not to be in bytes.
Therefore, I find no way to compensate the padding used by QImage to make all rows to be 32 bit aligned.
Is there any better way to do this in dlib except for using memcpy row by row to build a data buffer without padding?

**Comment by davisking** [comment]
There is not a function dlib that does this conversion, so you will have to write the code to do it.

**Comment by mshobeyri** [comment]
you can use https://github.com/mshobeyri/QFaceRecognition repo that is a qt/qml wrapper on dlib.
