### ISSUE TITLE
centos6.6   dlib-18.18  CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o error

### ISSUE THREAD

**Issue by acBool** [davisking/dlib#99]
I use dlib-18.18, and I run "python setup.py intall",but when run at 98%,I have an error,the error information is:

[ 98%] Building CXX object CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o
In file included from /usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing.h:18,
                 from /usr/dlib18-18/dlib-18.18/tools/python/src/shape_predictor.cpp:7:
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h: In member function âdouble dlib::correlation_tracker::update(const image_type&, const dlib::drectangle&)â:
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h:130: éè¯¯ï¼å¯¹âpointwise_multiply(dlib::matrix<std::complex<double>, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, std::complex<dlib::matrix<std::complex<double>, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >&)âçè°ç¨æ²¡æå¹é
çå½æ°
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h:171: éè¯¯ï¼å¯¹âpointwise_multiply(dlib::matrix<std::complex<double>, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&, std::complex<dlib::matrix<std::complex<double>, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >&)âçè°ç¨æ²¡æå¹é
çå½æ°
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h: In member function âvoid dlib::correlation_tracker::make_target_location_image(const dlib::vector<double, 2l>&, dlib::matrix<std::complex<double>, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&) constâ:
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h:310: éè¯¯ï¼no match ä¸ºâoperator=âå¨âg = std::conj(_Tp) [with _Tp = dlib::matrix<std::complex<double>, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>]()âä¸­
/usr/dlib18-18/dlib-18.18/dlib/../dlib/matrix/matrix.h:1522: éæ³¨ï¼å¤éä¸ºï¼ dlib::matrix<T, num_rows, num_cols, mem_manager, layout>& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator=(const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>&) [with T = std::complex<double>, long int num_rows = 0l, long int num_cols = 0l, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout]
/usr/dlib18-18/dlib-18.18/dlib/../dlib/matrix/matrix.h:1656: éæ³¨ï¼         dlib::matrix<T, num_rows, num_cols, mem_manager, layout>& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator=(const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper&) [with T = std::complex<double>, long int num_rows = 0l, long int num_cols = 0l, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout]
/usr/dlib18-18/dlib-18.18/dlib/../dlib/matrix/matrix.h:1664: éæ³¨ï¼         const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator=(const T&) [with T = std::complex<double>, long int num_rows = 0l, long int num_cols = 0l, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout]
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h: In member function âvoid dlib::correlation_tracker::make_scale_target_location_image(double, dlib::matrix<std::complex<double>, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>&) constâ:
/usr/dlib18-18/dlib-18.18/dlib/../dlib/image_processing/correlation_tracker.h:326: éè¯¯ï¼no match ä¸ºâoperator=âå¨âg = std::conj(_Tp) [with _Tp = dlib::matrix<std::complex<double>, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>]()âä¸­
/usr/dlib18-18/dlib-18.18/dlib/../dlib/matrix/matrix.h:1522: éæ³¨ï¼å¤éä¸ºï¼ dlib::matrix<T, num_rows, num_cols, mem_manager, layout>& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator=(const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>&) [with T = std::complex<double>, long int num_rows = 0l, long int num_cols = 1l, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout]
/usr/dlib18-18/dlib-18.18/dlib/../dlib/matrix/matrix.h:1656: éæ³¨ï¼         dlib::matrix<T, num_rows, num_cols, mem_manager, layout>& dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator=(const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper&) [with T = std::complex<double>, long int num_rows = 0l, long int num_cols = 1l, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout]
/usr/dlib18-18/dlib-18.18/dlib/../dlib/matrix/matrix.h:1664: éæ³¨ï¼         const dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::literal_assign_helper dlib::matrix<T, num_rows, num_cols, mem_manager, layout>::operator=(const T&) [with T = std::complex<double>, long int num_rows = 0l, long int num_cols = 1l, mem_manager = dlib::memory_manager_stateless_kernel_1<char>, layout = dlib::row_major_layout]
gmake[2]: *** [CMakeFiles/dlib_.dir/src/shape_predictor.cpp.o] éè¯¯ 1
gmake[1]: *** [CMakeFiles/dlib_.dir/all] éè¯¯ 2
gmake: *** [all] éè¯¯ 2
error: cmake build failed!

How to solve the problem?

**Comment by e-fominov** [comment]
It's impossible to understand the issue if we cant read compiler output, can you provide readable error messages?
Also, please tell GCC version number. It is well-knows, that Centos uses old GCC versions and old libraries

Do you have errors compiling C++ examples?
examples/video_tracker_ex uses corellation tracker, that was unable to compile in your case - try to compile it
