### ISSUE TITLE
Training facial landmark using dnn_face_detector

### ISSUE THREAD

**Issue by ncuxiaogang** [davisking/dlib#996]
Hi, Davis E. King. When I use your nice facial landmark detection, the "dlib's HOG face detector" can not detect the faces in the image. But I use your dnn_face_detector, it can detect the faces. As you say in "Also note that this model file is designed for use with dlib's HOG face detector. That is, it expects the bounding boxes from the face detector to be aligned a certain way, the way dlib's HOG face detector does it. It won't work as well when used with a face detector that produces differently aligned boxes, such as the CNN based mmod_human_face_detector.dat face detector." So in my understanding when using the CNN based face detector, the facial landmark detection will not be very good. My qusetion is below. 
1. How can I train the facial landmark based on your "CNN based face detector"? I have seen the example on how to train the facial landmark code "https://github.com/davisking/dlib/blob/master/examples/train_shape_predictor_ex.cpp". But I still have a question regarding the "training_with_face_landmarks.xml" .  The "box top='90' left='194' width='37' height='37'" is the output of the dlib's HOG face detector? I have download the iBug facial landmark dataset, but it does not contain the face rect. So if I want to use your "CNN based face detector" as input of the facial landmark, How should I do? Thanks very much!

**Comment by davisking** [comment]
Take the iBug data and use the CNN face detector to create the training rect.

**Comment by ncuxiaogang** [comment]
Thanks a lot! I got it.
