### ISSUE TITLE
is DNN thread-safe

### ISSUE THREAD

**Issue by andriy-gerasika** [davisking/dlib#998]
assuming I deserialized pre-trained "net_type" object from dnn_face_recognition_ex.cpp:

is it safe to use its operator() on vector of images from multiple threads?

p.s.
just double-checking, I know, dlib::object_detector is not thread-safe, but dlib::shape_predictor is...

Thank You

* **Version**: 19.7
* **Where did you get dlib**: dlib.net && github
* **Platform**: Ubuntu 16.04 x64
* **Compiler**: gcc-5.4

**Comment by davisking** [comment]
No.   Unless otherwise documented, it's not safe to touch dlib objects from multiple threads at the same time.
